### ISSUE TITLE
"Delete All Items" from extended user pod deletes all users

### ISSUE THREAD

**Issue by grantnorwood** [pods-framework/pods#1000]
This is actually more about user intent, not a bug in the code.  When I hover over an extended user pod and choose 'Delete All Items", it deletes all of my users without proper warning (except the currently logged-in user).

I believe that a user is more likely to intend to simply delete the extended users' properties rather than wanting to delete all users.  Or, if this should still be the action taken upon clicking the "Delete All Items" link, then there should be the appropriate (read: big and scary) warning letting the administrator know the impact of clicking that link.

Thoughts on how this should behave?

**Comment by jimtrue** [comment]
This also will delete all 'posts' if the user is 'delete all' from Extender Pods. The intent I believe should be to delete all 'meta' added by Pods, not the posts themselves for extended items.

**Comment by jimtrue** [comment]
@sc0ttkclark @pglewis This isn't actually a 'doc improvement' either, this would be a functional change, wouldn't it?

**Comment by JoryHogeveen** [comment]
I think `Delete all items` should delete as usual, not deleting the current user.
I also think an extra option "Delete all Pods data" would be nice.

**Comment by sc0ttkclark** [comment]
I disabled the ability altogether to Delete All Items if Pod type is User.
