### ISSUE TITLE
Using form() to upload featured image

### ISSUE THREAD

**Issue by nahue** [pods-framework/pods#1005]
How can i create a frontend form and have a field to load a featured image ? i have a pod that uses featured image to display items in a grid and i really need that field.

**Comment by r8r** [comment]
Hi guys – I've been wondering, if there have been specific updates to this in the past two years?

**Comment by Shelob9** [comment]
@r8r  Unfortunately not, but we would welcome a pull request to add this feature.

**Comment by sc0ttkclark** [comment]
It shouldn't be too difficult given enough time, we have the basis of some of it already in core it's just not hooked up for logic on post types.
