### ISSUE TITLE
WP Menus: Add Advanced Content Type Items

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1053]
Like Custom Post Types have, the ability to add items. Requires the pod have the option enabled to show in nav menus (like CPT), and have a detail URL defined.

**Comment by Salloom88** [comment]
i faced the same issue!

**Comment by JoryHogeveen** [comment]
Sounds like a nice feature indeed

**Comment by ineffabilis** [comment]
I'm guessing this won't happen...
