### ISSUE TITLE
Using the featured image and renaming the "more fields"

### ISSUE THREAD

**Issue by Vanbrent** [pods-framework/pods#1057]
Dear developers
It would be nice to have pods (normaly text field paragraph field) could ad the featured image and rename the label.
Or rename the "more fields"

Is that possible?

**Comment by AlexZaicu** [comment]
@Shelob9 Can you give an example? I've tried <a href="https://github.com/pods-framework/pods-code-library/blob/master/example/hooks/actions/pods_api_post_save_pod_item_podname/examples/set-featured-image.php">this example</a> but it doesn't work. Thanks!

**Comment by iamandrewpeters** [comment]
I saw that there was a coming update to change the 'More Fields' text that contains the fields we create. Has this been updated? I still don't see a way to do this.

**Comment by jimtrue** [comment]
@iamandrewpeters #799 is slated for 2.8. you can change the More Fields with a filter using this code:
```
/**
 * Change the meta box title to the pod name
 */

add_filter('pods_meta_default_box_title', 'gnt_pods_meta_title', 10, 5);
function gnt_pods_meta_title($title, $pod, $fields, $pod_type, $pod_name) {
		
	if (!empty($fields)) {
		$title = $pod['label'];
  	}
 
	return $title;
}
```

You can also use pods_group_add to define your own field groups at present, though 2.8 will add a UI for this and some additional field group options.
http://pods.io/docs/code/general-functions/pods-group-add/

Featured Images in forms are handled with Pods Gravity Forms AddOn (or the method @Shelob9 describes above with uploading into a file field and replacing the thumbnail.

Changing the labels of existing WordPress objects in a Custom Post Type editor like the Featured Image is handled using this filter:
https://developer.wordpress.org/reference/hooks/post_type_labels_post_type/

Do we want to add the ability to 'customize' common Post Type editor 'labels' like the Placeholder text in the Title (so it could instead be called 'Add Auto Name' or something more helpful, likewise for the 'editor' and the Featured Image and possible override the labels in the 'Publish' metabox?
