### ISSUE TITLE
Custom rewrite %tags%

### ISSUE THREAD

**Issue by Rayken** [pods-framework/pods#1092]
When creating a new Pod (custom post type), one can assign a custom rewrite slug. I believe extending this functionality to allow for custom rewrite tags would be a great option for Pods.

Here's how I see it:
![custom-tags-in-pods](https://f.cloud.github.com/assets/1472749/184891/91a91cb6-7cf0-11e2-8180-d0ba63727535.png)

If selected as above, perhaps some more trickery to detect relationships and give a couple of choices. However, the %company% tag in my case relates to a custom taxonomy Pod called company. 

To make the permalinks work, here's what I did:

``` php
/**
 * Include the post term in the permalink of CPT posts
 * The tag %company% has been added in the Pod settings for the CPT
 */ 
    add_filter( 'post_link', 'company_permalinks', 10, 3 );
    add_filter( 'post_type_link', 'company_permalinks', 10, 3 );

    function company_permalinks( $permalink, $post_id, $leavename ) {
        // check if our custom tag is present
        if( strpos( $permalink, '%company%' ) === FALSE ) 
            return $permalink;

        // get post
        $post = get_post( $post_id );

        // if there isn't a post
        if( !$post ) 
            return $permalink;

        // fetch the terms
        $terms = wp_get_object_terms( $post->ID, 'company' );

        // make sure an object is returned and that no errors occured
        if( !is_wp_error( $terms ) && !empty( $terms ) && is_object( $terms[0] ) ) 
            $taxonomy_slug = $terms[0]->slug;
        else 
            $taxonomy_slug = 'not-related';

        // return the new permalink with term inserted
        return str_replace( '%company%', $taxonomy_slug, $permalink );
    }  
```

So for example, instead of having:
http://yourdomain.com/custom-post-type/post-name 

we now have:
http://yourdomain.com/something/specific-company/post-name

Thanks!

**Comment by jimtrue** [comment]
This is referenced in #442 Closing as duplicate.
