### ISSUE TITLE
Simple Repeatable Fields

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1095]
The ability to mark a specific field as 'repeatable', letting the user enter more than one value.

## Official Scope

Scope doc: https://docs.google.com/document/d/19xNBlsJrHWs3qmeYU5cJOScJDei2Y2fgCMqpVko8WDU/edit#heading=h.2qxn6m5lx6t7

## Features

- [x] Add Another (it will add another item to the end of the list of inputs)
- [x] Delete (you can delete all but one)
- [x] Stores as JSON (table-based) or serialized (meta-based)
- [x] Returns as array, like relationship fields

### Text

- [x] Plain Text
- [x] Website
- [x] Phone
- [x] E-mail

### Paragraph

- [x] Plain Paragraph Text
- [x] WYSIWYG

### Date / Time

- [x] Date / Time
- [x] Date
- [x] Time

### Number

- [x] Plain Number
- [x] Currency

### Other

- [x] Color Picker
- [x] oEmbed

This is separate from #109, which is itself a group of fields that can be repeatable.

**Comment by lkraav** [comment]
Would absolutely love to have something like this for post type "Notes" model (a la WooCommerce), for plugins that don't ship one in core.

**Comment by dingman** [comment]
+1

**Comment by sc0ttkclark** [comment]
Pods 2.9 Beta 2 is out and includes this feature: https://github.com/pods-framework/pods/releases/tag/2.9.0-beta-2

**Comment by kelfy** [comment]
awesome
