### ISSUE TITLE
Field length / Yes-No Box only half / Label is in the field

### ISSUE THREAD

**Issue by marieneig** [pods-framework/pods#1129]
Hi I try to use the pods plugin for the first time, I want to add some additional field to the comments form but the field length are all very small even if I go to the Additional field option and I put Maximum Length = 2000. (default was 255). 
Also, the labels appears to be inside the field but not even centered, it is completely at the top left so it is not very beautiful. The description shows up at the bottom. 
Yes/No field type only shows the Yes box
thank you

**Comment by JoryHogeveen** [comment]
> to the comments form

This is theme business right?
