### ISSUE TITLE
No ability to display a pod elements "Label"

### ISSUE THREAD

**Issue by whatwillb** [pods-framework/pods#1151]
It does not seem as tho you can reference a pod elements Label. I would like to display the field contents and the Label. 

Something like:
$mypod->field('their_name.label') .' : ' . $mypod->field('their_name')

Would output:
Name: Stacey Jones

This seems like it would be needed by a lot of people so that you could automatically list the contents of the pod as well as the labels for each of  the fields that the user has filled in the WP editor.
I think this is pretty self explanatory, but me know if it is not clear

**Comment by sandrocirlini** [comment]
hello....
how can i get a field name instead of value from with magic tags?
example: {@elenco.name}

**Comment by Shelob9** [comment]
@sandrocirlini Please use http://pods.io/forums for support
