### ISSUE TITLE
Bilingual backend with qTranslate

### ISSUE THREAD

**Issue by gmaggio** [pods-framework/pods#1162]
I’m using **qTranslate** to create a bilingual frontend as well as **backend**. For the frontend, it is easier because you can just modify the theme. As for the backend, it may need **integration** with the plugin.

To make this short, here's a link to illustrate my ideas: http://to.ly/kME1

**Comment by el56** [comment]
Bump.
I am using [mqtranslate](https://wordpress.org/plugins/mqtranslate/) since qtranslate is no longer being maintained.
The intent is to use Pods on a site that is available in six languages.
What I have been able to do so far is to make Pods post types (at least the title and text body) translatable, but custom fields and taxonomies are not.

Any help is appreciated. I am happy to assist and can give access to the site if needed.

**Comment by Shelob9** [comment]
@el56

**Comment by el56** [comment]
I'm using standard meta storage.

In the short term, it may be a matter of how input is parsed or filtered. In most parts of WP that are not explicitly translate-friendly (such as menus), there is a syntax that the translation system understands which is this:

Research TeamEquipo de investigaciónفريق البحثKooxda Cilmi baarista

So, what is "Research Team" when in English is "Equipo de investigación" if the user switches to Spanish, etc. As you can see, we even have it working nicely right-to-left for Arabic. It looks awful in the menu dashboard but great to the end user.

(If you want a look, the site in testing is http://www.refugeeresearch.net/new/)

The mqtranslate module offers a nice multilingual interface for standard taxonomies (which is probably just a nice front-end to create the syntax above), but this is not available for Pods-created taxonomies.

If I could use the above syntax in Pods, I would be OK until there is better integration. However, the <...> stanzas are stripped out upon saving, so I can't use it. I've tried the abive syntax both in Pods Templates and for Pods Taxonomies and it doesn't work in either.

**Comment by Shelob9** [comment]
What type of custom field are you saving these strings in and how are you displaying them? It seems like either validation or sanitization is stripping the < and >

**Comment by el56** [comment]
The fields are all of type "Plain Text" and "Website", and one "Date".
The Website and Date fields don't need translation, of course.

My plan was to display them using Frontier Auto Templates.
