### ISSUE TITLE
Repeatable / Loop Field Design

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1174]
This is to track design progress for #109, #291, and #1095.

**Design Constraints**
1. Maximum 3 Levels of loop fields
2. 2nd and 3rd level indented
3. 3 fields on rows when minimized. First 3 if not customized
4. Which fields (from 3) are shown can be customized from the loop field options

**Comment by diegosomar** [comment]
Hello! This loop field is no longer available?

**Comment by mastef** [comment]
10 years later...
