### ISSUE TITLE
Component: Custom Fields for Relationships (wp_podsrel_meta)

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1195]
Something I like about Posts 2 Posts is that it can attach meta to a relationship.

Example:
- You have an `cast` relationship field on a 'Movie' pod that relates to multiple actors / actresses
- You can add a field to the relationship for 'Part', e.g. 'Bilbo Baggins' or 'Gandalf'
- So you can then select 'Martin Freeman' from your 'Actors' pod
- Then type his part in as 'Bilbo Baggins'

It would be a fusion of how the loop field UI in #109 will work and the relationship UI from #291.

The table structure would be like this (following how Posts 2 Posts works):

```
wp_podsrel_meta:
  - meta_id (auto increment)
  - rel_id (related to wp_podsrel.id)
  - meta_key (ex. 'part')
  - meta_value (ex. 'Bilbo Baggins')
```

**Comment by StaggerLeee** [comment]
+1
