### ISSUE TITLE
jQuery UI css "breaks" WP Editor

### ISSUE THREAD

**Issue by julianmatz** [pods-framework/pods#1203]
The included stylesheet
wp-content/plugins/pods/ui/css/smoothness/jquery-ui.custom.css
seems to break the WP (TinyMCE) editor. Only the Insert/edit link popup, though, as far as I can tell. Maybe it's a bug in WordPress iteself, since all the other popup dialogs seem fine.

In the backend, it's not really a big deal, but I have a Pods form on the frontend, and it looks pretty bad, especially the overlay.

Are there any known fixes or work-arounds? I know the stylesheet is required by the date-picker.

**Comment by JoryHogeveen** [comment]
Didn't WP 3.8 and jQuery UI 1.10.3 fix this?

**Comment by pglewis** [comment]
I'm not seeing anything untoward with Insert/Edit link on WordPress 4.7.1 and Pods 2.6.8.  I'm going to declare this a relic.
