### ISSUE TITLE
2.3 autocomplete relation field shows duplicates

### ISSUE THREAD

**Issue by normadize** [pods-framework/pods#1204]
This is with a Pods pulled half an hour ago. My wp_postmeta and wp_podsrel contain only one record for a relation field attached to a custom post type that accepts multiple values (the relation is to Users). That relation field "Autocomplete". On the post edit page, it shows two instances of that single record (two rows with the same user).

(this might be related to #1198 but I don't think so)

**Comment by pglewis** [comment]
I've heard no reports of this and no feedback for a couple years.
