### ISSUE TITLE
Using the wysiwyg editor but no html (paragraphs / breaks) in front-end

### ISSUE THREAD

**Issue by Vanbrent** [pods-framework/pods#1214]
Hello Scott
on http://bergercommunicatie.nl/?page_id=18
you can see a contactpage. the problem lies within the following:
In the editor the adress has 3 lines:
Alexander Gogelweg 8 
2517 JH Den Haag 
tel. 06 22 99 40 15

but on the front end it is shown as: Alexander Gogelweg 8 2517 JH Den Haag tel. 06 22 99 40 15 (1 line)

I have updated to version 2.3 
What can be a solution? (my client does not know html)

greetings 

Brent

**Comment by KeriCaraher** [comment]
Im also having this problem.

**Comment by JoryHogeveen** [comment]
@KeriCaraher 
Since this is a very old issue, please open a new one and provide us with all info so we can try to reproduce.
