### ISSUE TITLE
Add separator functionality to Admin UI

### ISSUE THREAD

**Issue by mastef** [pods-framework/pods#1231]
Being able to create separators for the left-hand side dashboard view, to group Pods together based on their Menu Position, would be great

**Comment by lkraav** [comment]
Yes, working with `2.6.1` today led me to the same conclusion. +1.

**Comment by jimtrue** [comment]
You do realize this is available in Admin Menu Editor as a workaround, right?

**Comment by lkraav** [comment]
Aha, you mean https://wordpress.org/plugins/admin-menu-editor/ right?

I've tried some menu editors in the past, but the interfaces have been so cluttered, they never stuck. Not sure if I've looked at your proposed plugin before though.

**Comment by jimtrue** [comment]
Yep that's the one. One of the least annoying ones out there. When I couldn't figure out menu #'s etc or I wanted to put Pods within another menu, I use that plugin
