### ISSUE TITLE
Export/Import Relationships

### ISSUE THREAD

**Issue by jcampbell05** [pods-framework/pods#1247]
Relationships can't be imported or exported in 2.3. When I export a custom pod, which one of its fields is a relationship to multiple taxonomies, the field in question becomes empty in the exported xml.

So lets say the field is called categories, I would expect it to be somehting like this:
`<categories>
<category id="23"/>
</categories>`

But instead I get this:

`<categories/>`

**Comment by aQziany** [comment]
Hi, 

I have this problem to, but with 2 custom fields that are in a custom post type - both created with Pods. 

The custom fields are:

Relationship (Bi-directional Field) [type: pick]
Selection Type: Multiple Select
Format: Autocomplete 

I tried 2 plugins to do an Export/Import. 

The first one was: [WP All Import & Export Pro](https://docs.pods.io/plugins/wp-all-import-export/)
The second one was: [WP Sheed Editor Pro](https://wpsheeteditor.com/pods-how-export-import-custom-post-types/)

All things went just fine with both, except the:

Principal White Grape Varieties
Principal Red Grape Varieties

Who are both:

Relationship (Bi-directional Field) [type: pick]
Selection Type: Multiple Select
Format: Autocomplete 

![Screenshot 2020-12-02 000130](https://user-images.githubusercontent.com/29342405/100804560-c5b7cc00-3435-11eb-9e87-6f87703b40e2.png)
![Screenshot 2020-12-02 000507](https://user-images.githubusercontent.com/29342405/100804564-c6506280-3435-11eb-8124-e2a184832816.png)
![Screenshot 2020-12-01 115854](https://user-images.githubusercontent.com/29342405/100804654-f0a22000-3435-11eb-866e-7d2b49241a0f.png)
