### ISSUE TITLE
Customise Plupload Directory

### ISSUE THREAD

**Issue by jcampbell05** [pods-framework/pods#1248]
Is there a way of customising where images are uploaded either through a hook or filter? If not can it be added in somehow.

**Comment by christoferw** [comment]
+1 
i am currently looking for an option to move files uploaded outside the default media directory. 
i already tryed some hools like wp_handle_upload_prefilter without success

**Comment by pglewis** [comment]
What's the use case here?  Our image uploads integrate with the media library, so all images end up saved as attachment post types and then located via WordPress's normal facilities.  Saving loose files from potentially untrusted sources in a location outside WordPress's designated uploads directory seems like a bad idea unless there's a very compelling reason.

**Comment by christoferw** [comment]
Reasion

Attachments for that kind of POD/CPT
- are not intended to be used somewhere else on the Wordpress site
- should be handled more private, e.g. with htacess rules for that folder that checks some things..
- should not be added to the imagesitemap / published
- should be archived in another folder structure to be reused for other purposes.
- are no images but zip files, pdf, etc...

**Comment by christoferw** [comment]
by the way: it could be upload directory it that can fit that requirements...
