### ISSUE TITLE
Advanced Relationships with another DB Table Bug

### ISSUE THREAD

**Issue by rclai** [pods-framework/pods#1258]
Steps:
- Enable complex relationships
- Create ACT pod - NewPod
- Create field of field type Relationship
- Select - Related To: Database Tables
- Select - Related Table - wp_whatever
- Go to Add'l Field Options tab
- Put in Table ID Column as PK of wp_whatever
- Put in display column name on Table Index Column
- Made sure it is a multi-select using select2 plugin (Autocomplete)
- Make sure Show Admin Menu in Dashboard is checked on Admin UI tab
- Save Pod
- Go to create a NewPod
- The select2 field shows a totally different display, but the value is right (tested with just a regular select dropdown element too)

In addition, another bug:

After creating the relationship field with advanced relationship to another DB table and saving the pod, editing the field again shows a different Related To value selected, but the setting is still properly saved in the backend.

**Comment by chloechancys** [comment]
I able to get table from table,but unable to save selection data to backend db,please guide
