### ISSUE TITLE
Enhanced Options For Creating Custom Settings Pages

### ISSUE THREAD

**Issue by tomherold** [pods-framework/pods#1266]
I was experimenting with the custom settings pages and it works great, however I was missing some options to group elements. I ended up with installing another plugin called KC Settings. Maybe you can contact the author and get some info on how to integrate some of its options. As far as I know it's the only plugin that really creates nice looking settings pages and also includes a wide range of elements.

Adding this would bring pods to new level!

**Comment by jimtrue** [comment]
#799 would handle this I believe.
