### ISSUE TITLE
Password Field values are saved as plaintext by default?

### ISSUE THREAD

**Issue by rclai** [pods-framework/pods#1277]
Shouldn't they be hashed at least?

Perhaps have an option in the field definition to choose what kind of encryption to use?

**Comment by lougreenwood** [comment]
Any news on this? I just noticed that password fields are stored as plain text.

Also, one thing I'd like to suggest is that when this is released, all existing passwords fields are automatically changed to be saved as hash, so there's no need to manually update posts...
