### ISSUE TITLE
Feature Request: Header/Section Break "field"

### ISSUE THREAD

**Issue by nciske** [pods-framework/pods#1301]
Ok, so it's not technically a 'field' in the sense of the database, but I'm finding that not having the ability to break up larger public forms with some section breaks (in Gravity Form terminology) is limiting.

Whether this is something mixed into the array fed to the $pods->form() call (as it's display only) or ideally a 'field' type on the backend with no actual DB field (so it can be arranged and edited alongside the other fields) it'd be great to have something with a title and description at the minimum.

Would this be better as a plugin (is that even possible?)

Right now, I'm using 'simple' relationship fields and hiding the actual form element, but it's hacky and a pain to manage (see attachments).
![Screen Shot 2013-04-18 at 6 48 34 PM](https://f.cloud.github.com/assets/974354/399881/0aa90366-a883-11e2-87e0-df4b4ba0d3ad.png)
![Screen Shot 2013-04-18 at 6 46 22 PM](https://f.cloud.github.com/assets/974354/399882/0aace9f4-a883-11e2-8805-bb099d346e63.png)
![Screen Shot 2013-04-18 at 6 48 21 PM](https://f.cloud.github.com/assets/974354/399883/0aac2a3c-a883-11e2-932b-1f3fd3ff2e6d.png)

**Comment by jimtrue** [comment]
This is to be handled with #799 Closing as Duplicate.
