### ISSUE TITLE
My suggestion for the permissions page layout

### ISSUE THREAD

**Issue by YammYcoding** [pods-framework/pods#1307]
Here it is. The changes are small details that make the whole difference =)

Notice i changed the naming of the permissions. That's because organizing like this, you can have a visual clue by type of permission, and also in code you order by name to display things alphabetically.

I hope it helps =)
![pods-new-permissions-page](https://f.cloud.github.com/assets/1200923/403830/c2a2e4dc-a92d-11e2-9181-2744978917ee.jpg)

**Comment by jimtrue** [comment]
Closed by #1934
