### ISSUE TITLE
Expand internal field names for relationship/file fields

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1334]
We should have a few more options for users to utilize (mainly in magic tags):
- [ ] `related_post._link` would work like `related_post.detail_url` (as a replacement)
- [ ] `related_post._list` would output a `<ul>` list of posts, each linked to their detail url
- [ ] `related_post._list_text` would output a `<ul>` list of posts, text only
- [ ] `related_post._list_comma` would output a `pods_serial_comma` list of posts, each linked to their detail url
- [ ] `related_post._list_comma_text` would output a `pods_serial_comma` list of posts, text only
- [ ] `related_post._list_id_comma` would output a list of post id's separated with comma's perfect for a SQL IN statement
This would help new users be able to do a bit more out of the box, without knowing PHP, when they're using templates / magic tags / shortcodes.

By default, just using `{@related_post}` currently defaults to `related_post._list_comma_text`

**Comment by jimtrue** [comment]
^^ This enhancement would seem to help a lot of the shortcode based things work with us better, possibly.
