### ISSUE TITLE
Implement new Media modal UI for Shortcodes and File uploads

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1344]
@thomasgriffin built some cool stuff for us a couple of months back and it's awesome, it allows use the WP 3.5 Media modals in some very cool ways, like for forms and other popup screens. Essentially, replacing anytime we'd normally use Thickbox.

**Comment by pglewis** [comment]
I think this should be broken out into a separate issues for filters and shortcodes.  File upload has had media modal integration for a while, obviously.
