### ISSUE TITLE
Cannot delete field

### ISSUE THREAD

**Issue by BevCyc** [pods-framework/pods#1349]
I'm using Pods Version 2.3.4.  I added a new field to an existing pod that extends a post type.  I realized I didn't need the field so tried to delete it.  I got the popup that says "Are you sure you want to delete this field?" and I clicked OK but it didn't delete the field.

The field is a plain text field that's not required.  I tried deleting it before any records had text in the field.   When that didn't work I added text in that field and tried deleting the field again but it still didn't work.

Bev

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
