### ISSUE TITLE
jquery Date calendar : not beeing translated

### ISSUE THREAD

**Issue by YammYcoding** [pods-framework/pods#1363]
Can I have this calendar translated to current wp language as well ? If it's supposed to work, it's not working for me. ( in any of my pod installs )

If it still needs the translation typing, please tell me where is the code for it, that I get it done for you...

[]s

**Comment by JoryHogeveen** [comment]
Related: https://github.com/pods-framework/pods/issues/3429

**Comment by JoryHogeveen** [comment]
Fixed in #3641
@sc0ttkclark We might want to put this in Pods core instead of a component. You can close this issue if you think the component is fine.

**Comment by pavelevap** [comment]
Datepicker (no time) localization is part of WordPress from version 4.6: https://core.trac.wordpress.org/ticket/29420

**Comment by JoryHogeveen** [comment]
Hi @pavelevap 
Ah ok! @sc0ttkclark Shall I remove it from the
