### ISSUE TITLE
Single file upload using plupload

### ISSUE THREAD

**Issue by junpendon** [pods-framework/pods#1377]
Hi, thanks for this awesome plugin.

I am new in Pods Framework and created a single file upload field using plupload and want to enhance my form.
1. How can I disable “Add File” button after a successful upload?
2. When “Minus Sign” next to the uploaded file is clicked,  delete uploaded file from WP uploads folder  and then restore back "Add File" button.

![singlepod](https://f.cloud.github.com/assets/2124659/491858/956dbae0-ba63-11e2-8209-6677a42e0f94.png)

**Comment by pglewis** [comment]
We're already swapping out the delete/trash in favor of remove/red X in #3341, to help avoid confusion

Maybe the default behavior for #3334 should be to hide the add new button for single file fields.  It requires an extra click to change out a file but it may be less confusing... I'm on the fence

**Comment by unpezvivo** [comment]
In case anyone could be interested, i've found a simple CSS solution for this. Inject this code through your functions.php. The "#pods-form-ui-pods-meta-pdf" element is the one Pods asigns to your file field ID. In my case the element id was "pdf".

This will make the button appear/dissapear depending on the previous sibling visibility, that is, the .pods-file info box. The empty trick prevents the buttons dissapear on new created pod.

`function replace_admin_css() { ?>
		<style>

			#pods-form-ui-pods-meta-pdf ul.pods-files:not([style*="display: none"]) + a {
				display: none;
			}

			#pods-form-ui-pods-meta-pdf-en ul.pods-files:empty + a {
				display: inline-block;
			}


		</style>
	<?php }
	add_action( 'admin_head', 'replace_admin_css' );`

**Comment by sc0ttkclark** [comment]
I'm okay with making this optional, however I'd much rather replace the text from 'Add File' to 'Replace File' instead of hiding the button altogether.

**Comment by sc0ttkclark** [comment]
This is tagged for Pods 2.7 and we rewrote the file uploader field itself to be powered by Marionette + Backbone, so this will definitely be much easier to do in that code.

**Comment by pglewis** [comment]
Whatever is left there is outside the scope of 2.7, punting to future
