### ISSUE TITLE
[suggestion] having ghost relation tables besides podsrel

### ISSUE THREAD

**Issue by lucianahanan** [pods-framework/pods#1396]
The idea:

When you insert into podsrel for a 1-n relation ( like lists of cities in a dropdown ),  I would like to see a 'copy' of the same data to behave like it's a foreign key in parent table, and inserting into the fk table rows with the dropdown list.

example:
pods_user { id, name, id_city }
pods_fk_city { id, cityname }

So I can do a query like this:
select c.cityname from pods_user u, pods_fk_city c where u.id_city = c.id ;

Or maybe write a view with the table joins.

**Comment by Angelo-Verona** [comment]
I'm also for this idea. Podsrel is actually a pain in the ass if you have a lot and lot of relationships, that table can be huge like few GBs just for simple lookup to another custom table.
I would like to see something like "foreign relationship" for ACT which would simply create column as any other field in pods first custom table and would be attachable to another column in another table + load Labels from second table and some column for nice UX. This could be easily done without any "lookup" table as podsrel. Just let DB hande consistency.
