### ISSUE TITLE
Pick Fields Returns False Instead of Array

### ISSUE THREAD

**Issue by jacksonwp** [pods-framework/pods#1408]
I am unable to get the value of a pick field, using the following code on WP 3.5.1 and Pods 2.3.4

I have a pod called 'members' with a relationship single pick field called 'membership_type' for a pod called 'membership_type'.

`
$member = pods( 'members', intval( $_GET['id'] ) );
echo( $member->field( 'contact_first' ) .' ' . $member->field('contact_last') );
echo( $member->get_field( 'membership_type' ) );
echo( $member->get_field( 'membership_type.name' ) );`

Will output:

Jackson Whelan
bool(false)
bool(false)

The behavior is the same for all my pick fields. Am I missing something here? Or is this a bug?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
