### ISSUE TITLE
Built in Taxonomies dont appear when lang is configurated as pt_BR

### ISSUE THREAD

**Issue by andersonchagas** [pods-framework/pods#1418]
I was figuring out why the Built-In section in "Advanced Options" dont was showing options.
When I commented localization line in wp-confing.php and try again, the built-in taxonomies appear. So this can be a bug related with localization files.

**Comment by JoryHogeveen** [comment]
This is a WP bug and is fixed since 4.0.
https://make.wordpress.org/core/2014/09/05/language-chooser-in-4-0/
