### ISSUE TITLE
Numbers with non english installations

### ISSUE THREAD

**Issue by Gring** [pods-framework/pods#1439]
Hi, sorry if this bug has already been declared, I'm new here.

When you have a french wordpress installation, and when you edit a record (pods manage page), plain numbers are formatted the french way (space instead of comma every three digits, comma instead of point for the decimals).

This gets filtered by the client side (and probably server side) filter... You have everytime to rewrite all the numbers in your pod object in english format.

**Comment by Ramoonus** [comment]
this is a duplicate
