### ISSUE TITLE
Component: WPMS Network-wide mode (w/ shared content)

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#144]

**Comment by compumatter** [comment]
I need multisite pods.  I created an extensive slider with lots of coding and it's a real bummer to have to replicate it all.   Any idea when / if this is coming our way ?

Thanks.

Jay

**Comment by sc0ttkclark** [comment]
This won't make it into Pods 3.0, but it's still on our priorities for a future release

**Comment by nerevolution** [comment]
Just another fan of Pods looking for the ability to share pods across a multisite network. I'm looking to have a staff database on our site and be able to pull fields on any site throughout the network. Thanks for considering this feature!

**Comment by julianmatz** [comment]
Just wanted to say, for anyone that doesn't know, this functionality (shared content / data) can be achieved, or partially achieved, using the switch_to_blog() function. Here is a quick example:

`### Get Locations
		global $switched;
		// Switch to main site
		switch_to_blog( 1 );
		$params = [ 'limit' => -1, ];
		$obj = pods( 'locations', $params );
		$locations = [];
		while ( $obj->fetch() ) {
			$locations[ $obj->field( 'ID' ) ] = $obj->field( 'post_title' );
		}
		// Switch back to the current site
		restore_current_blog();
		print_r( $locations );`

Maybe it will help someone.
