### ISSUE TITLE
Pods_Add not respecting Bidirectional Field

### ISSUE THREAD

**Issue by jcampbell05** [pods-framework/pods#1440]
I have two pods, branch and events.

They both have a bidirectional relationship field to each other. When I add the branches to the new events I create via pods_add that should show up in the fiels in the events pod, then the branches show up fine when I go to the edit screen.

But when I go to the Branches, and look at the field pointing to the events, none of the ones relating to the branches show up. It looks like the bidirectional field isn't being respected.

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
