### ISSUE TITLE
All wp_enqueue'd files end up in wp_footer() after update from Pods 2.3.4 to 2.3.6

### ISSUE THREAD

**Issue by TwoWholeWorms** [pods-framework/pods#1457]
We're using wp_enqueue_script() and wp_enqueue_style() to hook in a load of JavaScript and CSS files including jQuery hosted on Google's CDN and a bunch of plugins we've written.

As soon as I update Pods to version 2.3.6, all these enqueued files disappear from wp_head() and end up just before the end of the body tag in wp_footer(). I can't for the life of me figure out why it would do this, but the behaviour is consistent. I've updated to 2.3.6 and rolled back to 2.3.4 several times now, and each time it moves the JS into the footer.

I had wondered if there was an option in Pods Admin to do this, but I couldn't find one. Also, some of my WYSIWYG fields which display fine in 2.3.4 are no longer appearing in 2.3.6.

Anyone else noticed this problem?

**Comment by pglewis** [comment]
Never got a reply on this and enqueueing in the footer is generally preferred where possible.
