### ISSUE TITLE
where clause is not working in pod 2.3.6

### ISSUE THREAD

**Issue by farhanrashad** [pods-framework/pods#1460]
I was using pod 2.0 and after upgrading the where clause is not working for me.
i was using previously the below code
<?php
$id = pods_url_variable('last');
echo $id;
$params['limit'] = 24;
$params['pagination'] = true;
$params['where'] = "editors.id=24";
$params['orderby'] = "publish_date desc";

// Maps to the new find method
$mypod = pods( 'mposts', $params );

// Display it to the template
echo pods( 'mposts' )->find( $params )->template( 'posts_list' ); 
 echo "<div class=zpagination>";
 echo $mypod->getPagination();
echo "</div>";
?>

**Comment by quasel** [comment]
this works close it ;)

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
