### ISSUE TITLE
z-index issues with calendar when over a code field

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#1474]
![calendar-z-index](https://f.cloud.github.com/assets/1973916/656191/132f9404-d525-11e2-85f0-7e10ea5335e9.png)

**Comment by NikV** [comment]
Fixed!

**Comment by Shelob9** [comment]
@NikV Fixed via what?

**Comment by NikV** [comment]
Fixed here: https://github.com/pods-framework/pods/pull/2700
