### ISSUE TITLE
Multiple bi-directional relationships between 2 pods causing logout

### ISSUE THREAD

**Issue by artalat** [pods-framework/pods#1476]
Hi. Im trying to make 2 bidirectional relationships between 2 pods: "person" and "shop".

One relationship is called owner, and other is manager. However, as soon as I create the second relationship, i get thrown out to login page. And from there, im locked out, because it wont let me login. 

The only solution Ive found is to delete the field from wp_posts table and then it lets me login again.

using wordpress 3.5.1 and pods 2.3.8

**Comment by pglewis** [comment]
This one never reproduced, off it goes.
