### ISSUE TITLE
get_meta() should always return an empty array if there is no associated meta

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#1484]
get_post_meta() specifies that _"If there is nothing to return the function will return an empty array unless $single has been set to true..."_  Since get_meta() filters get_post_meta(), it should do the same.  

At least one known situation: extended page with a multi-select relationship to an ACT.  If there is nothing associated for a page, then get_post_meta() returns a single element array with false as the value.  

![get_post_meta](https://f.cloud.github.com/assets/1973916/673504/44240cb4-d8ba-11e2-8a1a-f2a14017cbaf.png)

**Comment by quasel** [comment]
@pglewis is gona take a fresh look to settle that once and for all @sc0ttkclark I remember closing a similar issue where you commented like default wp stuff - but can't find it anymore :/

**Comment by JoryHogeveen** [comment]
Fixed since 2.7.21
https://github.com/pods-framework/pods/pull/5661
