### ISSUE TITLE
Pods Export - Custom Taxonomies & other fields issue

### ISSUE THREAD

**Issue by paoloimpelluso** [pods-framework/pods#1486]
Hi,
when i use the export() method I can't get any custom taxonomy in my export array.

This is my configuration: boat (Custom Post Type w/ Table Storage Type), Boat Category (Custom Taxonomy w/ Table Strage Type). Custom Tax is linked to Boat with classical WP relation ( defined in Advanced Options > Built-in Taxonomies )

Also, one other field is missing: i can obtain classical info (like post_title, post_content, post_date etc etc ) but all the attachments are missing (like post_thumbnail).

Is this the correct behaviour expected? Or am I missing something?

thanks, Paolo

WP version: 3.5.1
Pods Version: 2.3.8

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
