### ISSUE TITLE
[BUG ?] UI presentation for table storage pods

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#1494]
Hi..
i have a Custom Post Type Pod, with table storage and i want to show a list of pods of this type..
but using the canonical template() function it seems don't work, neither with the pod list widget…

while, with CPT pods with canonical storage method, it works…
i'm so confuse...

is it a bug, or do i miss something ? 

PS : Pods - Custom Content Types and Fields: 2.3.8
PPS : i read this post that seem similar 
        [http://podsframework.org/forums/topic/custom-post-types-and-table-based-data/]
    but the solution doesn't work for me…

**Comment by quasel** [comment]
So much has changed in that area - seems to be no longer an issue!
