### ISSUE TITLE
Bidirectional Relationship issues

### ISSUE THREAD

**Issue by bakaburg1** [pods-framework/pods#1506]
Hi Scott, as I told you in the chat I've got quite some problems with the relationships.
The pods are 4, Resources, Sources, Feeds, Topics.

These are the relationships:
Resources <-----> Topics (multi), Feeds (multi), Sources (mono)
Sources <-----> Topics (multi), Resources (multi)
Feeds <-------> Topics (multi), Resources (multi)
Topis <------> Resources (multi), Sources (multi), Feeds (multi).

I have a process ajax based wich for every topic, for every feed connected to the topic, collects the urls in the feed rss plus some more data. For every url that was found the system checks if its domain (the source) is already in the Sources database. If not, saves the Source and the Resource. If yes instead checke if the resource is already in the Resources database, and if yes makes two add_to() to that resource, for the actual topic and feed in the loop thus adding them to the Resource if not already saved.
Linear isn't it?

But in reality it's a mess!!! for some reason this process is also altering the connections between feeds and topic adding the seconds to the first in case of duplicates. There is one catch all topic with many duplicates with the other topics and this is up with all the feeds after running the process. The relationships fo feeds and topics should not cjange during the process!! I suspect it's the Resources objects that drove the modification.

Please I really need to solve this. 

PS: the site is online so if you would like to I can give you my credentials.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
