### ISSUE TITLE
Autocomplete + Flexible relationships

### ISSUE THREAD

**Issue by pixeline** [pods-framework/pods#1512]
AFAIK Pods does not make it possible to have an input logic that behaves like the Wordpress "Tags" box: you type, it looks for matches (autosuggest/ autocomplete) and either it find matches you can select, or you create a new taxonomy entry.

Can you add it to the features list?

**Comment by sc0ttkclark** [comment]
We added this to Pods, select Autocomplete and choose Taggable

**Comment by sc0ttkclark** [comment]
This was released in 2.4 - April 16th, 2014, just forgot to close the issue
