### ISSUE TITLE
How to import an image / images

### ISSUE THREAD

**Issue by basepack** [pods-framework/pods#1530]
Hi,

I have a question, how can I import an image. When I provide the guid, Pods won't eat that.

Example import.csv

``` csv
name;image;
Diverse;http://www.example.com/wp-content/uploads/2013/07/logo.png
```

My import Pod Page code

``` php
<form action="" method="post"
      enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="file" id="file"><br>
    <input type="submit" name="submit" value="Submit">
</form>
<?php
if ($_FILES){
    if ($_FILES["file"]["error"] > 0)
    {
        echo "Error: " . $_FILES["file"]["error"] . "<br>";
    }
    else
    {
        // Get the API
        $api = pods_api('categorie');

        // Get CSV data
        $data = file_get_contents($_FILES["file"]["tmp_name"]);

        // Run the import
        //$api->import($data);

        // Run the import and set the format to CSV
        $api->import($data, false, 'csv');
    }
}
```

Hope you can explain how to import an php Array within a .csv file so we can import everything we want.

Thanks!

Edit: maybe is my code above something to add in the docs?

**Comment by mastef** [comment]
Since I keep coming back to this issue to look at my own code, I've made a small write-up on how to [cycle through a .csv file and import the images right away](https://blog.stefanxo.com/2018/12/how-to-import-images-from-urls-into-your-wordpress-pods/).

**Comment by jimtrue** [comment]
This one has now been updated on: https://docs.pods.io/code/media-functions/pods_attachment_import/ and https://pods.io/docs/code/media-functions/pods-attachment-import/

Added update to add your tutorial here: https://github.com/pods-framework/pods-docs/issues/12
