### ISSUE TITLE
Admin edit form loses part or all of value for time field type

### ISSUE THREAD

**Issue by sbarnaby** [pods-framework/pods#1558]
If time field is configured to use html5 input, a refresh of admin edit form displays time as not set. If not configured to use html5 input, then the am/pm part is lost, and after several updates to other, unrelated fields in the admin form, the time field (if set to "pm") reverts to "am". Seems to be a bug in populating the display when loading that results in inadvertent, bad updates.

**Comment by GaryJones** [comment]
> If time field is configured to use html5 input, a refresh of admin edit form displays time as not set.

With the data not saved, a page refresh naturally wipes out the unsaved data.

With the data saved (Post Updated), then refreshing the page doesn't change the output (the time still shows correctly).



> If not configured to use html5 input, then the am/pm part is lost

I get the same behaviour as the HTML5 input - a page refresh before saving the data reverts the field back to the previously saved value (or empty), and after updating the post, the latest value shows correctly on each refresh.

I'm going to assume this one is fixed, but please let us know if it's not.
