### ISSUE TITLE
Request: CALCULATION Field Type

### ISSUE THREAD

**Issue by Whirl3d** [pods-framework/pods#1572]
I would like to be able to select CALCULATION from the field type selector and (like with the relationship field), define a set of parameters to be calculated for the field. The following example shows how the calculation field would be useful for counting the number of students in a classroom.
##### CREATE CLASS POD

_From the PODS ADMIN Screen_
**class name**: String (16 chars max)
**class grade** Number (integer)
**class teacher**: relationship (single, dropdown)
                     _from TEACHERS POD using Teacher Name field_
**class students**: relationship  (multiple, checkboxes)
                     _from STUDENTS POD using Student Name field_
**class student count**: _calculate_
                     _apply COUNT formula to CLASS POD:class student count_

NEW CLASS POD
_From the New POD Screen_
**class name**: Math
**class grade**: 5
**class teacher**: [Mr.Robinson]
**class students**: [john][sally][joe][julie]
**class student count**: {4} 

For the first round of updates, you would create a new Field Type called "Calculation" and it would require a multiple entry field as it's target.The required properties of the calculation field type would be:

**target field**: a field with multiple-values selected from the existing PODS' field list
**formula**: selected from a predefined list of formulas*

*the predefined list of formulas would ideally contain a CUSTOM...option as well as IMPORT/EXPORT options. Then, as people began writing custom calculation formulas, they could export them and share them.

This would set the stage for my next suggestion: FILTER field types

But that's another request.

Thanks for taking the time to listen. I love PODS. Thanks.

Jase

**Comment by jimtrue** [comment]
Adding #1561, #1562, #1563, #1564, #1565, #1566 and #1567 as parts of this Calculation Field Request. This request should be used to pull the Pull Request against and any task lists or concerns.
