### ISSUE TITLE
get_post_meta() returns array even if $single is set to true for a related post

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#1578]
Unsure if this is relationships to posts only, or other objects as well.  

Report is that get_post_meta() with $single set to true still returns an array for a related post field.  To be consistent with the WordPress codex docs for get_post_meta(), it should probably return the post ID as a string in this case.  

Tested that this is due to Pods by surrounding the call to get_post_meta() with pods_no_conflict_on() and pods_no_conflict_off(), and the string ID value was returned as expected.

**Comment by sc0ttkclark** [comment]
Returns array / "" depending on value, this can be closed.

**Comment by pglewis** [comment]
The problem, if I recall correctly, is that the behavior does not match the documentation for `get_post_meta()`.  That's a problem.

**Comment by sc0ttkclark** [comment]
Returns array() if $single = false, returns "" if $single = true, no matter what Pods::field() returns, it forces $single return normalization for the get_metadata functionality to work as expected. At one point this was broken, we fixed it though and this was leftover.

**Comment by quasel** [comment]
just for documentation - if you use get_post_meta() on "relationship type fields" ( includes e.g. images) - you always get back an array() not matter $singel ( which is a bit suboptimal given the desciption ) 

if you need to just get a single value ( which is the ID of the related "CPT/Media/etc..." )
just use:

pods_no_conflict_on( 'post_type' )

**Comment by jimtrue** [comment]
This is still an issue. Why was it closed?

**Comment by jimtrue** [comment]
`pods_no_conflict_on` is a workaround for this. Shouldn't this work the optimal way for get_post_meta? @quasel (you were the one that posted that particular solution)

**Comment by JoryHogeveen** [comment]
Related: #3614

**Comment by JoryHogeveen** [comment]
Closing this issue.
The latest versions of Pods no include settings which can disable this behavior if you user wants this!
