### ISSUE TITLE
Add option to edit default "Enter title here" prompt via Pods label editing tab

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#1622]
Even though you can change the "Add new [podname]" text sometimes the default WordPress prompt in the post title field jars.

For instance if you want to change the label to "Add new venue" then "Enter title here" doesn't work well as a user prompt ( "Enter venue name here" would be preferable ).

There are filters in WP that allow you to do this in functions.php or via a plugin but it would be neater if it was a part of the label editor.

**Comment by meganedesigns** [comment]
+1
