### ISSUE TITLE
Allow Read Only on every field type.

### ISSUE THREAD

**Issue by bakaburg1** [pods-framework/pods#1637]
Hi there,

I'm glad to see the read only option in 2.3.9, very welcomed!

I noticed hwr that this option is not available on certain field, for example relationships.

Is it a choice or just you didn't have time to implement it yet?
Since I sometimes generate pods items with relationships already set, it would be useful for me to make them not editable by the UI.

They can be shown as text or as link for pods relationships.

Thanks

**Comment by jimtrue** [comment]
@pglewis is this handled/allowed in the new Flexible Relationship Fields? Readonly uneditable relationship fields based on capability/role?
