### ISSUE TITLE
WHERE related field has ALL values in list (AND)

### ISSUE THREAD

**Issue by brockfanning** [pods-framework/pods#1662]
Sorry for asking a blatant support question here!

I am trying to get all pods of post_type "news" that are tagged as BOTH "term_1" and "term_2". I'm able to do ORs, but I can't seem to figure out the AND. I had been trying to do this all in the "where" statement, but with no success. Do I actually need to do some manual JOINs?

Any tips to point me in the right direction?  Thank you!

**Comment by sc0ttkclark** [comment]
Great deal of ideas and information here: #1978

**Comment by pcfreak30** [comment]
pods-framework/pods/pull/3036

**Comment by sc0ttkclark** [comment]
Fixed by #3033

**Comment by sc0ttkclark** [comment]
Following up with the example usage here:

`$pod->find(
    [
        'where' => [
            [
                'field' => 'category.name',
                'value' => [
                    'first',
                    'second',
                ],
                'compare' => 'ALL',
            ],
        ]
    ]
);`
