### ISSUE TITLE
PODS_STRICT and/or PODS_DEBUG setting

### ISSUE THREAD

**Issue by mastef** [pods-framework/pods#1689]
a developer mode in PODS would be great

e.g. if PODS_DEBUG or PODS_STRICT would be defined, then

instantiating a non-existing pods, like `pods('nonexistingpod')` ( instead of the current strict version `pods('nonexistingpods',null,true)`)
or calling `$pods->field('nonexistingfield');` would produce a fatal error

this would massively help with initial development time

**Comment by pglewis** [comment]
Related: https://github.com/pods-framework/pods/issues/3060

**Comment by mastef** [comment]
@sc0ttkclark @pglewis Please reopen this, the related issue doesn't seem to be that much related.

The request is simple : 

Throw an error when you try to access a non-existing pod or a non-existing field. That's all.

There should never ever be a use-case where continuing with a non-existing pod or non-existing field would be desirable.
