### ISSUE TITLE
Post Type / Taxonomy relationship fields not saving

### ISSUE THREAD

**Issue by ionofzion** [pods-framework/pods#1693]
On any of my Pods CPTs, if I add a relationship field listing posts from another Pod, my selection is not saved when I publish/update the post. I've tested with all available single and multi formats. This is similar to the issue I reported recently https://github.com/pods-framework/pods/issues/1630

Pods: 2.3.10 Alpha 4
WordPress: 3.6
Plugins: All except Pods disabled for testing

**Comment by sc0ttkclark** [comment]
Closing as fixed by #2375
