### ISSUE TITLE
Traversal of post_author

### ISSUE THREAD

**Issue by Desertsnowman** [pods-framework/pods#1694]
The aim is to be able to pull more information about the post author like:
`{@post_author.display_name}` or `{@post_author.avatar.60}` or `{@post_author.description}` and so on.

**Comment by m9n** [comment]
+1 for this.  Would be sooo helpful in so many use cases, essentially allowing us to grab quite rich user(author) information for displaying with posts, or filtering posts by things like the author's display name.

**Comment by quasel** [comment]
closing in favor of  #4119
