### ISSUE TITLE
Custom Simple Relationships: optgroup format (and empty value setting)

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1696]
```
|#USA
al|Alabama
az|Arizona
.......
.......
|#Canada
on|Ontario
.......
```

Opt group labels start with # with no space.

Values can be empty by placing an `|` before the label but with no preceding value.

Current value / label format is `value|Label`.

Related to #1672

**Comment by oligoform** [comment]
does it work to make optgroups with PODS 2.7.20 in this way?

**Comment by JoryHogeveen** [comment]
@oligoform This is not implemented as this point.
