### ISSUE TITLE
Front end form doesn't work in IE since WP 3.6

### ISSUE THREAD

**Issue by MaartenvanLoon** [pods-framework/pods#1709]
Hello,

This issue is related to issue #1619 ... I thought it was completely solved, but now it seems it only works on firefox, chrome and safari, but not in IE.

Front end form keeps running after pressing the 'Save' button (since upgrade to WP 3.6).

You can test this in IE (I'm using IE10 for testing) with user/pass test/test:

goto url: http://www.b2bike.be/wp-login.php
user/pass: test/test

You are forwarded to the correct page with a front-end pod form.

There is one large user pod form on this page. you can fill in some random data, or just press the "Bewaar" (means 'save') button. Nothing happens and cursor keeps 'running'.

In the IE script console I get this error: "SCRIPT438: De eigenschap of methode indexOf wordt niet ondersteund door dit object 
jquery.pods.js, regel 102 teken 25"

in english: ...indexOf is not supported by this object jquery.pods.js, line 102 teken 25

line 102 shows this code: if ( '' != field_name && 0 != field_name.indexOf( 'field_data[' ) ) { 

If we try exact the same in chrome or firefox, this form does work.

Can anyone please take a look at this?

Thanks in advance
Best regards
Maarten van Loon

**Comment by pglewis** [comment]
Haven't heard anything on this in a couple years.
