### ISSUE TITLE
jQuery DataTables for display / edit for loop field input

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1711]
http://www.datatables.net/release-datatables/examples/api/editable.html

**Comment by JoryHogeveen** [comment]
The editor for DataTables isn't free, I don't think we can use it right..

**Comment by sc0ttkclark** [comment]
Not sure if it was always for purchase or initially was free, but we can shelf this then.

**Comment by JoryHogeveen** [comment]
I think I might take the same to create an editor myself. We can use the field display function to output a table.
First finish the link field :) allmost done!
