### ISSUE TITLE
Make docs and other areas like tutorials available offline, maybe through some script that could build out the templates into a PDF

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1775]
Make docs and other areas like tutorials available offline, maybe through some script that could build out the templates into a PDF

**Comment by jimtrue** [comment]
Closing this one as it needs vote to progress. We don't even have a parsed inline docs creator yet, so this gets packed to the back burner until we have that unless someone wants to put in the time to research a solution.
