### ISSUE TITLE
Taxonomies showing up when they shouldn't in post editor.

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1777]
Taxonomy column associated with a Pod show up when "Show Taxonomy column on Post Types" option is NOT selected for that taxonomy.

Reported by a user in [this support thread](http://pods.io/forums/topic/taxonomy-showing-in-column-even-when-option-is-disabled/) and I have confirmed issue using Pods 2.3.11 and WP 3.6.1

**Comment by JoryHogeveen** [comment]
I'm quite sure this is fixed a while ago. Closing topic.
