### ISSUE TITLE
Making Pods compatible with Polylang 1.2

### ISSUE THREAD

**Issue by Chouby** [pods-framework/pods#1801]
Hi Scott!

I will release Polylang 1.2 during the first half of November. It will introduce a lot of changes in the internal structure. I explain why at http://polylang.wordpress.com/2013/10/01/polylang-1-2-beta-ready-for-tests/

I am aware that Pods interacts with Polylang at a rather low level so I did a grep on the Pods code and here are the results of my investigations.

in classes/PodsAPI.php at line 6652
```php
if ( !empty( $current_language ) ) {
	$current_language_t_id = (int) $polylang->get_language( $current_language )->term_id;
	$current_language_tt_id = (int) $polylang->get_language( $current_language )->term_taxonomy_id;
}
```
should be modified in
```php
if ( !empty( $current_language ) ) {
	$current_language_t_id = (int) $polylang->model->get_language( $current_language )->term_id;
	$current_language_tt_id = (int) $polylang->model->get_language( $current_language )->term_taxonomy_id;
	$current_language_tl_t_id = (int) $polylang->model->get_language( $current_language )->tl_term_id; # to be used when querying terms
	$current_language_tl_tt_id = (int) $polylang->model->get_language( $current_language )->tl_term_taxonomy_id; # to be used when querying terms
}
```
get_language has been moved from $polylang to $polylang->model. The initial code will work though as I introduced a magic method __call to transfer method calls to $polylang to $polylang->model but I guess a direct call is always better (a warning will be issued by Polylang if WP_DEBUG is set to true).

I add 2 new var for use below.

in classes/PodsAPI.php at line 6910
```php
elseif ( is_object( $polylang ) && !empty( $current_language ) && function_exists( 'pll_is_translated_taxonomy' ) && pll_is_translated_taxonomy( $taxonomy ) ) {
	$info[ 'join' ][ 'polylang_languages' ] = "
		LEFT JOIN `{$wpdb->termmeta}` AS `polylang_languages`
			ON `polylang_languages`.`term_id` = `t`.`term_id`
				AND `polylang_languages`.`meta_value` = {$current_language_t_id}
	";

	$info[ 'where' ][ 'polylang_languages' ] = "`polylang_languages`.`term_id` IS NOT NULL";
}
```
should move to
```php
elseif ( is_object( $polylang ) && !empty( $current_language ) && function_exists( 'pll_is_translated_taxonomy' ) && pll_is_translated_taxonomy( $taxonomy ) ) {
	$info[ 'join' ][ 'polylang_languages' ] = "
		LEFT JOIN `{$wpdb->term_relationships}` AS `polylang_languages`
			ON `polylang_languages`.`object_id` = `t`.`term_id`
				AND `polylang_languages`.`term_taxonomy_id` = {$current_language_tl_tt_id}
	";

	$info[ 'where' ][ 'polylang_languages' ] = "`polylang_languages`.`term_id` IS NOT NULL";
}
```
Here the initial code will break as the termmeta table will be removed. A term language is now stored in a taxonomy 'term_language' instead of the term meta

In classes/fields/pick.php at line 1579
```php
elseif ( is_object( $polylang ) && in_array( $object_type, array( 'post_type', 'taxonomy' ) ) && method_exists( $polylang, 'get_translation' ) ) { #will break
	$translated = false;

	if ( 'post_type' == $object_type && pll_is_translated_post_type( $object ) )
		$translated = true;
	elseif ( 'taxonomy' == $object_type && pll_is_translated_taxonomy( $object ) )
		$translated = true;

	if ( $translated ) {
		$object_id = $polylang->get_translation( $object, $result[ $search_data->field_id ], $current_language );
```
should move to
```php
elseif ( is_object( $polylang ) && in_array( $object_type, array( 'post_type', 'taxonomy' ) ) && method_exists( $polylang->model, 'get_translation' ) ) { #will break
	$translated = false;

	if ( 'post_type' == $object_type && pll_is_translated_post_type( $object ) )
		$translated = true;
	elseif ( 'taxonomy' == $object_type && pll_is_translated_taxonomy( $object ) )
		$translated = true;

	if ( $translated ) {
		$object_id = $polylang->model->get_translation( $object, $result[ $search_data->field_id ], $current_language );
```
get_translation has moved from $polylang to $polylang->model. The initial call to $polylang->get_translation should work thanks to the backward compatibilty but the test method_exists( $polylang, 'get_translation' ) will fail as get translation is no more a method of $polylang.

All files and lines refer to Pods 2.3.12.

I did not pull a request because I did not make any tests and dont' know how you want to deal with this (support only the latest version ? or both 1.1.x and 1.2 ?)

I am sorry for the inconvenience introduced by the changes in Polylang but hopefully the benefits are woth them (no more extra table, support for WordPress export / import and better extendability for future developments of Polylang). Don't hesitate to ask if you need clarifications.

NB: a continuously updated beta version is available at http://downloads.wordpress.org/plugin/polylang.1.2beta.zip

Frédéric

**Comment by JoryHogeveen** [comment]
Last part is fixed in #3728
