### ISSUE TITLE
Issue with query by date field not return proper post after date is updated

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1815]
In [this support forum thread](http://pods.io/forums/topic/using-wp_query-to-display-cpt-via-date/page/2/#post-178918) user reports an issue with ordering by a date field. I have confirmed the issue he is describing. 

With this code:

```
$todays_date = get_the_date();
$params = array(
        'limit' => 1,
    'where' => 'DATE( event_date.meta_value ) >= "' . $todays_date . '"'
);
$pod = pods('event', $params);
```

The post with the date closest to current date in the date field 'event_date' is return, as expected but if the post with the closest date in its date field is change so it is no longer the closest date, it is still returned.

Oddly enough, the issue is resolved by adding an orderby clause `'orderby' => 'event_date.meta_value',`, which shouldn't be needed.

Issue is present in 2.3.12 but was not in previous versions. User is unsure which version the issue was last not present for.

**Comment by christoferw** [comment]
I have also have problems sorting and filtering events, here is what i need to do / tried to do: 
`
// german date format: 31.12.2016 - >day.month.year
$ctw_today = date('d.m.Y'); 
$my_meta_query = array(
    'relation'		=> 'OR',
    array(
        'key'		=> 'anfangsdatum', //start date of the event
        'compare'	=> '>=',
        'value'		=> $ctw_today,
    ),
    array(
        'key'		=> 'enddatum', //end date of the event
        'compare'	=> '>=',
        'value'		=> $ctw_today,
    )
);

$query_args = array(
    'post_type' => 'event',
    'post_status' => 'publish',
    'posts_per_page' => 50,
    'meta_key' => 'anfangsdatum', // anfangsdatum
    'meta_type' => 'DATE',
    'meta_query'  => $my_meta_query,
    'order' => 'ASC',
    'orderby' => 'meta_value meta_value_num', //sortiere nach einem meta-feld
);
query_posts($query_args);
`
I am not sure how to use your workaround in my case. can you help me with that?

**Comment by JoryHogeveen** [comment]
I honestly do not agree with the original report of what is expected from that query.
If you omit the `orderby` param then this doesn't mean it switched to sort by date as default. This isn't a default in SQL. In facy, I believe it will order by ID as default.

So IMO, the `orderby` field is most definitely mandatory for a case like this.

As for @christoferw 
Please format your date as `Y-m-d` for any queries.

Closing this topic!
