### ISSUE TITLE
Add PlaceHolder for the TItle Field Textbox

### ISSUE THREAD

**Issue by xiuxiu** [pods-framework/pods#1861]
In the current "Add New" Page,

The Title field has not hints or suggestion words. The user would be confused here.

Is it possible to add "placeholder" or extra title for this field?

![screen shot 2013-11-15 at 2 14 13 am](https://f.cloud.github.com/assets/16230/1543534/9c187cda-4d58-11e3-8605-a3f9bfc17f57.png)

**Comment by NikV** [comment]
Fixed!

**Comment by Shelob9** [comment]
@NikV  fixed via what?

**Comment by NikV** [comment]
Fixed and can't be replicated.
