### ISSUE TITLE
Improper Values Being Saved In Weekdays relationship Field

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1862]
User in this [WPORG support thread](http://wordpress.org/support/topic/problem-save-relationship-calendar-on-setting-pod) Reports the following is occurring when saving a date field:
- all day, saved array is
  ( [0] => 0 [1] => 1 [2] => 2 [3] => 3 [4] => 4 [5] => 5 [6] => 6 )
  Correct!
- only Monday, saved array is 1
  Correct!
- only Sunday, saved array is
  ( [0] => 0 [1] => 0 )
  Error! I expect "0" or ( [0] => 0 )
- only Sunday and Monday, saved array is
  ( [0] => 0 [1] => 1 )
  Correct!
- only Sunday and Tuesday, saved array is
  ( [0] => 0 [1] => 0 [2] => 2 )
  Error!
- only Tuesday, saved array is
  ( [1] => 0 [2] => 2 )
  Error!

**Comment by JoryHogeveen** [comment]
I think this is fixed since these PRs:

#5467
#5528
#5538
#5687

Closing here.

**Comment by JoryHogeveen** [comment]
Sorry, wrong field type.

**Comment by JoryHogeveen** [comment]
However. This is fixed in #2397

**Comment by JoryHogeveen** [comment]
Might also be related: #1854
