### ISSUE TITLE
Multi file attachment thumbnail error

### ISSUE THREAD

**Issue by ecoreng** [pods-framework/pods#1870]
When attaching multiple files to a field it brings the wrong thumbnail back to the field.. I am using wordpress 3.4.2 so i dont know if its specifically for this version.

line 63 on file: ui/js/jquery.pods.attach.js says
        var wp_media_thumb = wp_media_meta.parent().find( 'img.thumbnail' ).attr( 'src' );

and changing it to:
        var wp_media_thumb = wp_media_meta.find( 'img.thumbnail' ).attr( 'src' );

fixes the error.

**Comment by JoryHogeveen** [comment]
Deprecated issue since DFV fields.
