### ISSUE TITLE
Long lines in code syntax field cause all fields to escape container in post editor.

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1887]
Placing code with a really long line into a code syntax field causes the field to escape its container in the post editor. All other fields appear to do it as well.

For example, in this screenshot:
![screen shot 2013-11-30 at 12 03 24 pm](https://f.cloud.github.com/assets/1994311/1649110/e7827654-59e1-11e3-8873-7b438c65cb60.png)
Note that the empty WYSIWYG field below the code syntax field is doing the same thing.

I tried emptying the code syntax box and pasting the same code into the WYSIWYG field, and the issue did not occur.

The original reporting user, in this [forum thread](http://pods.io/forums/topic/code-syntax-highlighting-field-word-wrap/) reports the issue in Safari, Chrome and Firefox in OSX. Pods/ WP versions unknown. I reproduced with Pods 2.3.18 and WP 3.8-beta1.

**Comment by NikV** [comment]
Can't replicate anymore.

**Comment by NikV** [comment]
@Shelob9 if you're still finding this an issue, please reopen the issue and list the steps you take to reproduce.
