### ISSUE TITLE
Document and implement a new templating standard for Pods widgets, templates, pod pages, and other output-related files using http://pippinsplugins.com/template-file-loaders-plugins/

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1899]
Document and implement a new templating standard for Pods widgets, templates, pod pages, and other output-related files using http://pippinsplugins.com/template-file-loaders-plugins/

**Comment by pglewis** [comment]
Jim has the roadmap here, this is probably close-able.
