### ISSUE TITLE
Bi-directional fields with User extended pod with multi-select checkbox

### ISSUE THREAD

**Issue by robbiereynolds** [pods-framework/pods#1908]
Situation: Customer review website where customers are asked to write a review along with 5 star rating system for their interaction with a company representative. Each review will be related to a User(representative). 2 Pods - Reviews and User extended.

Pod Reviews:
Basic:
field_name: representative
field_type: relationship
related to: Users
bi-directional field: related_reviews
Additional Field Options:
selection type: single select
format: autocomplete
display field: {@display_name}

Pod User:
Basic:
field_name: related_reviews
field_type: relationship
related to: Reviews
bi-directional field: representative
Additional Field Options:
selection type: multiple select
format: checkboxes
display field: {@name}

Expected outcome:
When adding or editing a review: The representative field should create a checked box under the associated User Pod for related_reviews.

Issue:
In the User Pod, the related_review field values are there, but are not getting the checked value.

**Comment by quasel** [comment]
Duplicate of #1945
