### ISSUE TITLE
Yoast SEO plugin

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#1932]
SEO title & desc don't get saved
https://github.com/Yoast/wordpress-seo/issues/508

**Comment by JoryHogeveen** [comment]
Is this issue still active?

**Comment by szepeviktor** [comment]
Will Pod v3 (repeater field) be ever released?

**Comment by JoryHogeveen** [comment]
@szepeviktor That seems unrelated to this topic.
In any case, first release will be 2.8 (group fields + full refactor of Pods admin).
For 2.9 repeatable fields, see: #1095 
For 3.0 loop fields, see: #1095 

Back on topic, I tried to reproduce this and this doesn't seem to be an active issue anymore (would've noticed that as I use Yoast SEO on several projects as well).
