### ISSUE TITLE
Simple Relationship data does not sanitize.

### ISSUE THREAD

**Issue by SalocinDotTEN** [pods-framework/pods#1943]
Using the latest version 2.3.18 and the data entered in Simple Relationship appears as one line separated by "n".

Using Wordpress 3.8.

Thanks.

**Comment by jimtrue** [comment]
@SalocinDotTEN Can you please share the simple relationship list you created, as well as what content type you are working with and how you are displaying this field? That would be very helpful in determining if this is a bug or an issue with your use that we can help you with.

[--- Linked with ASANA.com using Unito.io
#commenter Jim True
---[aa]

**Comment by jimtrue** [comment]
Hi @Shelob9,

The content type I was working with renders a drop down list.

Relationship [type: pick] 
› Simple (custom defined list) (Custom)

In the Pods editor, there is a text area "Custom Defined Options" where we put the list items in separate lines. Eg..

One
Two
Three

After saving, the list comes out in the editor as...

OnenTwonThree

We correct it and save, only to have it appear like above again.

We have not had any issue with this prior to Wordpress 3.8.
Is there a patch already available for this?

[--- Linked with ASANA.com using Unito.io
#commenter Jim True
---[aa]

**Comment by jimtrue** [comment]
They should be in the form of value|Label, like this:
one|One
two|Two
three|Three

[--- Linked with ASANA.com using Unito.io
#commenter Jim True
---[aa]

**Comment by jimtrue** [comment]
Thanks @Shelob9. It seems to be working just fine now. I shall notify my web dev team. :)

[--- Linked with ASANA.com using Unito.io
#commenter Jim True
---[aa]

**Comment by jimtrue** [comment]
If it's not working unless you use keys here, then there's still a bug to fix I think.

[--- Linked with ASANA.com using Unito.io
#commenter Jim True
---[aa]
