### ISSUE TITLE
Conditional Logic for Relationship Data (limiting subset of data to conditions)

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#1957]
HI..!!

I hope i can explain my idea clearly… I use a UseCase trying to do it:

i can have a pod with 2 relationship (field_A, field_B) fields where field_B visible options depend on the option selected in field_A.
For Example i have 
    field_A=Country
    field_B=Province

so would like to select the Country from field_A and when i click on the drop down (for example) for the field_B, it shows only the Province in the selected Country…

I think that in Relationship Fields manage user interface there could be a textbox named "filter" where i can write a sort of query for example (i think field_A and field_B are pod relationship, in this case)

"where B.related_pod.related_field = A.related_pod.id"

Do you think it's possible/useful..??
I hope in it..!! :)

**Comment by jimtrue** [comment]
Related to #1871

**Comment by globero** [comment]
I also need the same. Ex: 
Adding a new _Father_ (pod), I want to see this father's sons in the field _sons_ (bidirectional relation to _Sons_ pod). I don't want to see other sons in this field. Only sons already assigned to this father.
