### ISSUE TITLE
Add method in Pods_API to check what values changed during save_pod_item (not run by default, but can be run through a pre/post save action/filter)

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1969]
Add method in Pods_API to check what values changed during save_pod_item (not run by default, but can be run through a pre/post save action/filter)

**Comment by thirdender** [comment]
This doesn't work properly for relationship and file fields that support multiple values. The comparison logic in `PodsAPI->get_changed_fields($pieces)` does a `!=` comparison. `$pod->raw($field)` returns an array of arrays with object data, and the `$pieces['fields'][$field]['value']` seems to be the value submitted directly from the form. As a result, relationship fields are always marked as being changed, even when no change has been made.

**Comment by JoryHogeveen** [comment]
Good one! Though I think fields that use multiple meta fields in the database will always be hard to compare since even the order of these fields wille cause a difference.

Please create a new issue for this case if you can (with a reference to this one).
