### ISSUE TITLE
Traversal Pods::field( 'related_field.another_related_field' ) calls should be single/multi value aware, always returning a multi-dimensional array for multi-value fields even if there's only one value

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1976]
Traversal Pods::field( 'related_field.another_related_field' ) calls should be single/multi value aware, always returning a multi-dimensional array for multi-value fields even if there's only one value

**Comment by jimtrue** [comment]
+100

**Comment by sc0ttkclark** [comment]
This one requires a refactor of Pods field(), similar to adding more special dot traversal for things needed for the link field `link_field._target` type of functionality.

**Comment by jimtrue** [comment]
Yeah I was wondering on that one. It would be more consistent to treat any relationship outside of the current object as an associative array because then you wouldn't need to know if the item was single or multi connected and that would mean better encapsulation

**Comment by quasel** [comment]
regarding adding #3719 while I appreciate that what's about backwards compatibility?

**Comment by pglewis** [comment]
> regarding adding #3719 while I appreciate that what's about backwards compatibility?

We should definitely consider if there's a way to implement it in a back-compat way... but if not, this may be one of those cases where it's justifiable to me to break back-compat because it's probably how the behavior should have been all along.
