### ISSUE TITLE
[BUG] in pods_ui search area

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#1981]
using search area in pods_ui() on 2 different pods i obtain the same kind error :

Database Error; SQL: SELECT DISTINCT `t`.\* FROM `wp_posts` AS `t` LEFT JOIN `wp_postmeta` AS `lb1` ON `lb1`.`meta_key` = 'lb1' AND `lb1`.`post_id` = `t`.`ID` WHERE ( ( t.post_author=1 ) AND ( `t`.`post_type` = "test_pod" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) AND `lb1`.`t` LIKE '%3%' ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date` LIMIT 0, 25; Response: Unknown column 'lb1.t' in 'where clause'

Note that the error seams to be in the where clause added for Search 
"AND `lb1`.`t` LIKE '%3%' "
it has to be 
"AND `t`.`lb1` LIKE '%3%' "

I don't think it's only a mine configuration error, i think i is a Bug...
Do you think, too..??

thanks..!!

**Comment by jamesgol** [comment]
This was fixed by PR #4007
