### ISSUE TITLE
A way to conditionally show markup in templates if field has a value.

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1991]
Bad solution that works now:
`<?php if ($obj->field('FIELD_NAME') != '' ) : ?>
<li>Label: {@FIELD_NAME}</li>
<?php endif; ?>`

What I wish we could do is something like this:
`{if: @FIELD_NAME,has_value {
<li>Label: {@FIELD_NAME}</li>
}}`

**Comment by jimtrue** [comment]
#3191 Is a better focused tasklist for this. Closing permanently as duplicate.
