### ISSUE TITLE
Image fields not returned properly when translated by WPML

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2006]
In [this forum thread](http://pods.io/forums/topic/problem-with-displaying-images-from-pods/) a user is not able to get values from a Pods image field in the translated version of their site. 

In [this response](http://pods.io/forums/topic/problem-with-displaying-images-from-pods/#post-180693) they show that the image is not being stored properly in wp_podsrel for the translated field.

**Comment by JoryHogeveen** [comment]
I believe this is fixed in Pods 2.6.6 (#3574)

**Comment by quasel** [comment]
@JoryHogeveen another one - I guess this is still an issue?
