### ISSUE TITLE
Support for sticky posts

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#2026]
after googling a bit and looking everywhere
i cannot find the sticky support for CPT posts

**Comment by SporeProductions** [comment]
11 years later this is still a desirable feature and that recommended plugin hasn't been updated in 10 years.

**Comment by JoryHogeveen** [comment]
Hi @SporeProductions 
Here is a guide made this year: https://www.wpbeginner.com/wp-tutorials/how-to-add-sticky-posts-in-custom-post-type-archives/

**Comment by SporeProductions** [comment]
> Hi [@SporeProductions](https://github.com/SporeProductions) Here is a guide made this year: https://www.wpbeginner.com/wp-tutorials/how-to-add-sticky-posts-in-custom-post-type-archives/

Thank you for that tip. The plugin adds the option to "Make Post Sticky" but unfortunately the Query Loop block still won't show "Sticky Posts" options under the block Settings. Only appears for "Post" Post Type and not for my custom post type.
