### ISSUE TITLE
File upload field doesn't work for custom extensions

### ISSUE THREAD

**Issue by boriskuzmanovic** [pods-framework/pods#2031]
Create a field type "File/Image/Video" and for "Restrict File Types" select "Other (customize allowed extensions)". Enter file extensions "jpg,pdf". File upload stops working.

Workaround to this problem is to select "Any Type (no restriction)" which allows me to upload both jpg and pdf files.

Custom extensions seem to work if they are from the same group. i.e. all images as in 'jpg,gif'.

I'm using WordPress 3.8.1 and Pods 2.3.18.

**Comment by pglewis** [comment]
Note that WordPress will still reject file uploads that are not whitelisted in `wp_get_mime_types()` (or added via a filter).  This currently includes .svg and .vcf at the least.  

You can work around this by adding the proper mime type: https://codex.wordpress.org/Plugin_API/Filter_Reference/upload_mimes

or you can grant certain users the `unfiltered_upload` capability.
