### ISSUE TITLE
Display custom fields on WP admin (post list)

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#2049]
Please implements something like this:
https://gist.github.com/szepeviktor/c3ad865600319a24782b

Thank you!

**Comment by szepeviktor** [comment]
Was it implemented at the end?

**Comment by sc0ttkclark** [comment]
Right, this is now the issue stash we use to prioritize:

https://github.com/pods-framework/pods/issues?q=label%3A%22Needs+Votes%22+is%3Aclosed+sort%3Areactions-%2B1-desc

https://github.com/pods-framework/pods/issues?q=label%3A%22Needs+Votes%22+is%3Aclosed+sort%3Acomments-desc
