### ISSUE TITLE
"is required" message for required fields is not under translation system

### ISSUE THREAD

**Issue by developez** [pods-framework/pods#2054]
file: ui/js/jquery.pods.js
Line: 51

```
$el.closest( '.pods-field-input' ).append( '<div class="pods-validate-error-message">' + label.replace( /( <([^>]+ )> )/ig, '' ) + ' is required.</div>' );
```

I need to modify jquery.pods.js in my theme with my language.

**Comment by JoryHogeveen** [comment]
Fixed in https://github.com/pods-framework/pods/pull/3619

**Comment by MilenFrom** [comment]
If you want this translated without modifying the core files of pods you can do it with jQuery / JavaScript.

On the page where you want the translation include the following code and make sure you have jQuery before this code.

(function($){
    $(document).ready(function(){    
       $('body').on('keyup change keydown load keypress',function(){

            // Let's translate the required string
            let dstrng = $('.pods-validate-error-message').text();

            if(dstrng.includes('required')){
                $('.pods-validate-error-message').text('YOUR TRANSLATION HERE');
            }

        });
        
    });
})(window.jQuery);
