### ISSUE TITLE
[BUG] in Pods Admin (Manage Pods) : Delete all Items function

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#2055]
in Pods Admin (Manage Pods) clicking "Delete all Items" link, nothing happens..
this function is so important..

is it mine problem or is it a BUG.. ?

Thanks..!!

**Comment by jimtrue** [comment]
This is or should be related to #2566

**Comment by quasel** [comment]
works for me - and
Hi, we didn't hear back from you - so I'm closing the issue!
