### ISSUE TITLE
Hundreds of SQL queries

### ISSUE THREAD

**Issue by pavelevap** [pods-framework/pods#2081]
Hi, I have several ACT Pods, some are related to each other. I checked for SQL queries and when I try to edit any field (Pods Admin - Edit Pods) there are 593 queries after clicking on "Save Pod" (huge performance issue):

add_option - 75
delete_option - 293
get_option - 176
WP_Query->get_posts - 30
and some more (usually 1 or 2)

Are they really needed?

Using latest WP 3.8.1 and Pods 2.3.18 (no other plugin).

**Comment by jneto81** [comment]
Hello, any updates on this issue ?

**Comment by sc0ttkclark** [comment]
We're working on some smarter logic for saving pods / fields in Pods 2.8 as part of PodsObject work. At some point between 2.8 and 3.0, we'll be re-evaluating some of the database storage of our objects as WP has grown. They once lived in their own tables of data meaning one query to update, one query to get. Then we moved them to post types, but now it's about time to evaluate that decision as we look to the future of #144 and network-level configurations.

**Comment by sc0ttkclark** [comment]
Pod/field saving has been improved in Pods 2.8. It's not as heavy, however it still uses the normal WP APIs to save data for options/meta so those calls will still be necessary in many areas.

In the future, we will have options to save and store the Pods in their own optimized table structure, but for now it's alleviated by using object caching or Pods Alternative Cache.
