### ISSUE TITLE
Invalid referencing of db table in custom settings page

### ISSUE THREAD

**Issue by rclai** [pods-framework/pods#2088]
I get this error:

```
Database Error; SQL: SELECT DISTINCT `t`.`ID` AS `pod_item_id` FROM `3vetT3s_p0LE_posts` AS `t`
 WHERE ( ( `t`.`ID` = 48 ) AND ( `t`.`post_type` = "attachment" ) ); Response: Table 
'db517790047.3vetT3s_p0LE_posts' doesn't exist
```

The table name is supposed to just be 3vetT3s_p0LE_posts, I don't know why Pods is adding the database name to the prefix?

The settings page was working fine when there was no data in it, but once I put the first piece of data in, this error popped up.

**Comment by zmni** [comment]
This still happened when I try to add taxonomy relationship in Pods version `v2.6.8`. Error show up on pods meta box post new/edit form.

**Error database Wordpress**: [Table 'wordpress.wp_terms' doesn't exist]

`` Database Error; SQL: SELECT DISTINCT `t`.`term_id`, `t`.`name` FROM `wp_terms` AS `t` LEFT JOIN `wp__term_taxonomy` AS `tt` ON `tt`.`term_id` = `t`.`term_id` LEFT JOIN `wp__term_relationships` AS `tr` ON `tr`.`term_taxonomy_id` = `tt`.`term_taxonomy_id` WHERE ( `tt`.`taxonomy` = "cpt_category" ) ORDER BY `t`.`name`, `t`.`term_id`;  Response: Table 'wordpress.wp_terms' doesn't exist ``

The `FROM` table is wrong, the correct one is `wp__terms`, with double underscore `$table_prefix = 'wp__'`.

**Comment by sc0ttkclark** [comment]
@zmni please open a new issue, also please add `pods_debug_sql=1` to the URL you get this error on, it will give us more information to work with

**Comment by antoinepat** [comment]
@sc0ttkclark I have the same exact issue as zmni  and rclai because of the table name stocked in transient cache with a single underscore instead of double. Should I open a new issue ? Thanks
