### ISSUE TITLE
File upload from a PODS field doesn't allow .PDF/.docx MIME types

### ISSUE THREAD

**Issue by stffrd** [pods-framework/pods#2090]
Environment: Windows (WAMP)
Wordpress Version: 3.8.1 
Pods Version: 2.3.18

I'm unsure as to whether or not this is a Wordpress issue or a PODS issue, but I've found that when I add a field to a custom settings page (in this case, a file/image/video field) and I attempt to upload a PDF/Doc through that settings page, I get an unsupported file type error.

HOWEVER, when done from the multi-file uploader anywhere else (or even the basic uploader that WP allows you to use), the PDF/Doc uploads without error. I'm not sure if PODS is doing something else with MIME types, but I thought I would open up a ticket. 

![s1](https://f.cloud.github.com/assets/5068257/2440937/0ef9086c-ae0e-11e3-9cb3-11198eeb5960.PNG)
![s2](https://f.cloud.github.com/assets/5068257/2440938/0efa13e2-ae0e-11e3-9c85-89f23b0fdab9.PNG)
![s3](https://f.cloud.github.com/assets/5068257/2440939/0efbcc6e-ae0e-11e3-9293-79a46ae8f8e9.PNG)

**Comment by amit9400** [comment]
Where is listed 'Additional Field Options' and 'Restrict File Types' and select 'Any Type (no restriction)'

**Comment by amit9400** [comment]
please tell me its very urgent

**Comment by JoryHogeveen** [comment]
Hi @amit9400 
In that case your WordPress core settings don't allow these file types.
This is a tutorial I found doing a quick Google search: https://www.wpbeginner.com/wp-tutorials/how-to-add-additional-file-types-to-be-uploaded-in-wordpress/
If you are on a network/multisite installation you can add file types in your network settings.
