### ISSUE TITLE
Error: unable to process request, please try again

### ISSUE THREAD

**Issue by axeldevo** [pods-framework/pods#2104]
Hello, I have a similar issue as this: https://github.com/pods-framework/pods/issues/2019. 

Every time I save a Pod, I see this error msg. Though everything seems to save correctly. This affects the back-end as well as my front-end form where it seems to stop the redirect to thank you page from working. 

Is this an issue with my server? I'm with Rackspace Cloud Sites.

Below are my debug info and php.ini settings:

WordPress Version: 3.8.1
PHP Version: 5.4.10
MySQL Version: 5.1.61
Server Software: Apache/2.2
Your User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0
Session Save Path: /var/lib/php/session
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
WPDB Prefix: wp_
WP Multisite Mode: Yes
WP Memory Limit: 512M
Pods Network-Wide Activated: Yes
Pods Install Location: /mnt/target04/xxxxxx/www.website.com/web/content/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Plugins:
    Anti-spam: 2.1
    BulletProof Security: .50
    Cleverness To-Do List: 3.3.2
    Contact Form 7: 3.7.2
    Dagon Design Sitemap Generator: 3.17
    Download Manager: 2.5.99
    Duplicate Post: 2.6
    Easy FancyBox: 1.5.6
    Events Manager: 5.5.2
    Eyes Only: User Access Shortcode: 1.8
    Google Analytics for WordPress: 4.3.5
    Google XML Sitemaps: 3.4
    Gravity Forms: 1.8.5
    Gravity Forms CSS Ready Class Selector: 1.1
    Gravity Forms Data Persistence Add-On: 3.0
    Gravity Forms Survey Add-On: 2.1
    Gravity Forms User Registration Add-On: 1.7
    iframe: 2.7
    Multisite Plugin Manager: 3.1.4
    Multisite User Management: 1.1
    Nav Menu Roles: 1.4.1
    Pods - Custom Content Types and Fields: 2.3.18
    Post Types Order: 1.6.8
    Really Simple CAPTCHA: 1.7
    Revision Control: 2.3
    Revolution Slider: 3.0.5
    Safe Redirect Manager: 1.7.2
    SeedProd Coming Soon Pro: 3.15.2
    Social: 2.11
    Spectacu.la Discussion: 2.3.1
    Theme My Login: 6.3.9
    User Role Editor: 4.10
    Widget Logic: 0.57
    WordPress Importer: 0.6.1
    WordPress MU Domain Mapping: 0.5.4.3
    WordPress MU Sitewide Tags Pages: 0.4.2
    WordPress SEO: 1.5.2.1
    WP Admin Bar Removal: 2013.0624.0361
    WP Super Cache: 1.4

post_max_size = 96M
file_uploads = On
upload_max_filesize = 192M
memory_limit = 256M
max_execution_time = 360 ;

Really hope you can help! Thanks a lot

**Comment by pglewis** [comment]
Closing this out as nothing reproducible ever turned up.  Both this and the originally referenced #2019 appear to have been environmental issues, so new fresh issues only for anyone running into this in the future.
