### ISSUE TITLE
[DOCS] pods_api_post_save_pod_item --> post_save_pod_item ...ecc

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#2122]
After some hours of stomachache, tring to usin the "old" pods hooks from here i look inside the code, and it seems that you changed these hooks...

i dont know why.. 
but please........ say about it in the docs... :)

Thanks..!!

**Comment by sandhya09** [comment]
@Shelob9 @sc0ttkclark 
Im using same filter now and it doesn't work.
See my sample code below.
add_filter('pods_api_post_save_pod_item_scott', 'add_scott_data', 10, 3);

function add_scott_data($pieces, $is_new_item ,$id){
     wp_die( '<pre>'.print_r( $pieces).'</pre>' );
         return $pieces;
}

handle not go through function.
Can you help me with this please?
If I save pods with UI ie with wordpress save/update button this filer will be called?
Or it is called when pods save with API endpoint.

**Comment by sc0ttkclark** [comment]
What type of Pod is this for?

**Comment by sandhya09** [comment]
@sc0ttkclark ,
This is for some gallery images.
And I want to add some image related data after pod item is saved(with code)

**Comment by sc0ttkclark** [comment]
Please open a new issue and provide the code from above along with the exact pod type ('Media' pod type?).

**Comment by sandhya09** [comment]
@sc0ttkclark ,
This is normal pod from post post type.
And the code I have used is already mentioned.
I want to update pods with this function.
add_filter('pods_api_post_save_pod_item_scott', 'add_scott_data', 10, 3);

function add_scott_data($pieces, $is_new_item ,$id){
     wp_die( '<pre>'.print_r( $pieces).'</pre>' );
         return $pieces;
}
