### ISSUE TITLE
Error on relationship fields with 2.4

### ISSUE THREAD

**Issue by paoloimpelluso** [pods-framework/pods#2125]
Hi, just updated to 2.4
I've got an error on relationship fields, not reported with previous version.
When i try to update an item, if i set a value in relationship field i have the following error (no error if i leave the rel fileld empty):

SELECT
                DISTINCT
                `t`.`id`
                FROM `wp_pods_vs_model` AS `t`
                WHERE ( `t`.``= &#039;1&#039; OR`t`.`name`= &#039;1&#039; )
                ORDER BY`t`.`name`,`t`.`id`
                LIMIT 0, 1

Database Error; SQL: SELECT
                DISTINCT
                `t`.`id`
                FROM `wp_pods_vs_model` AS `t`
                WHERE ( `t`.``= '1' OR`t`.`name`= '1' )
                ORDER BY`t`.`name`,`t`.`id`
                LIMIT 0, 1; Response: Unknown column 't.' in 'where clause'

**Comment by kaushikam** [comment]
I am using pods 2.6.7. I am using pods-ui like below:

```
function myplguin_admin_sub_page() {
	$offices = pods('office');

	$fields = $offices->fields();

    $filters_array      = array('office_name','street', 'town', 'district', 'pincode');

	$offices->ui = array (
		'item' => 'Office',
		'items' => 'Offices',
		'orderby' => 'office_name ASC',
		'fields' => array (
			'manage' => array (
				'office_name' => 'Office Name',
				'street' => 'Street',
				'town' => 'Town',
				'district' => 'District',
				'pincode' => 'Pin Code',
			),
			'add' => $fields,
			'edit' => $fields
		),
        'filters' => $filters_array
	);

	pods_ui($offices);
}
```
But when I am using the default search the following error appears.

`atabase Error; SQL: SELECT DISTINCT `t`.* FROM `vi_posts` AS `t` LEFT JOIN `vi_postmeta` AS `office_name` ON `office_name`.`meta_key` = 'office_name' AND `office_name`.`post_id` = `t`.`ID` LEFT JOIN `vi_postmeta` AS `street` ON `street`.`meta_key` = 'street' AND `street`.`post_id` = `t`.`ID` LEFT JOIN `vi_postmeta` AS `town` ON `town`.`meta_key` = 'town' AND `town`.`post_id` = `t`.`ID` LEFT JOIN `vi_postmeta` AS `district` ON `district`.`meta_key` = 'district' AND `district`.`post_id` = `t`.`ID` LEFT JOIN `vi_postmeta` AS `email_id` ON `email_id`.`meta_key` = 'email_id' AND `email_id`.`post_id` = `t`.`ID` LEFT JOIN `vi_postmeta` AS `pincode` ON `pincode`.`meta_key` = 'pincode' AND `pincode`.`post_id` = `t`.`ID` WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "office" ) ) AND ( `office_name`.`t` LIKE '%kalamassery%' OR `street`.`t` LIKE '%kalamassery%' OR `town`.`t` LIKE '%kalamassery%' OR `district`.`t` LIKE '%kalamassery%' OR `email_id`.`t` LIKE '%kalamassery%' OR `pincode`.`t` LIKE '%kalamassery%' ) ORDER BY `office_name`.`meta_value` ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date` LIMIT 0, 25; Response: Unknown column 'office_name.t' in 'where clause'`
