### ISSUE TITLE
Add ability to have relationships between post types across sites in multisite network

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2144]
Quoting @sc0ttkclark  "To make it happen, we'll have to probably add two new relationship types to the Advanced Relationships component. One for 'Post Type on another site' and 'Taxonomy on another site', which will appear only if multisite is setup. Upon selecting, you will have to specify the post_type or taxonomy manually with a text field, so as to avoid having to have those content types registered on every site of yours, or even having Pods activated on those other sites. You'd then select the specific subsite you want to relate to via a select2 AJAX lookup (could have a LOT of subsites, could blow up admin area unnecessarily if we do a normal select."

**Comment by thuycoi** [comment]
Hi all. Is there any Tutorial for this topic? I tried everything but some how cannot connect my pods to another site in my multsite network.
