### ISSUE TITLE
Pod template auto-complete

### ISSUE THREAD

**Issue by rmckeel** [pods-framework/pods#2157]
Pod template auto-complete for a WordPress category (taxonomy) gives category.term_taxonomy_id as an option.  Fiddling with a Pods query in the database indicates the field should be category.term_id.

**Comment by GaryJones** [comment]
@rmckeel Was this resolved for recent versions?

**Comment by rmckeel** [comment]
@GaryJones For a custom taxonomy type on the site this was initially observed, I see both `{@term_taxonomy_id}` and `{@term_id}` come up - likely solving the initial concern.  The system seems to work as expected, I am out of context on this issue after 4 years, so it is no longer something that affects this project, and I am not sure how to reproduce or test the output specifically.  This site is on v2.6.10 (it is a bit behind as it needs some code customizations and deeper testing for each release we want to deploy).

Thanks for responding, I'll close this for now.
