### ISSUE TITLE
pods->save: $allow_custom_fields implemented but not working

### ISSUE THREAD

**Issue by thiagof** [pods-framework/pods#2163]
Would like to have the beautiful `$allow_custom_fields` option to work with pods()->save but a small bug seems to break it.

PodsAPI.php:3294 (v2.4) _save_pod_item()_

```
$params->id = $this->save_wp_object( $object_type, $object_data, array(), false, true );
```

If you check the 3th param is empty and is in the place of the `$custom_data` variable, which was already populated in the method.

Sounds like incomplete implementation - or there is a special reason for not allowing it yet?

**Comment by pglewis** [comment]
Duplicate, keeping #5218 open as the canonical ticket
