### ISSUE TITLE
post_format taxonomy not being registered for Pods CPT

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2165]
When support for a post format is registered for a CPT, the post_format taxonomy is not added to it.

I tested with this:

```
    $taxonomy_names = get_object_taxonomies( 'tutorial' );
print_r( $taxonomy_names);
$taxonomy_names = get_object_taxonomies( 'post' );
print_r( $taxonomy_names);
```

It returned post_format as a taxonomy for post, but not for tutorial. Both should support  post formats. In addition I tried manually adding the taxonomy with:

```
    add_action('plugins_loaded','add_pf_to_cpt', 99999);
    function add_pf_to_cpt(){
        register_taxonomy_for_object_type('post_format', 'tutorial');
    }
```

That had no effect.

**Comment by robrecord** [comment]
Please can this be fixed, I am getting 404s when previewing posts with post_types when post_format support is added.

**Comment by robrecord** [comment]
Here's your research: 
https://core.trac.wordpress.org/ticket/32385
https://core.trac.wordpress.org/ticket/20438
https://codex.wordpress.org/Post_Formats#Adding_Post_Type_Support

**Comment by robrecord** [comment]
For anyone who wants to work around this issue, add the following to functions.php in your theme:

**Remember to change _news_ to your post type slug.**
`
<?php
function _register_post_formats_for_post_types(){
	if ( post_type_exists( 'news' ) && post_type_supports( 'news', 'post-formats' ) ) {
		register_taxonomy_for_object_type( 'post_format', 'news' );
	}
}
add_action('init', '_register_post_formats_for_post_types', 11);
`
