### ISSUE TITLE
Editing custom pod "undefined offset: 0"

### ISSUE THREAD

**Issue by rmckeel** [pods-framework/pods#2169]
I'm getting a notice that I can't easily get rid of.  I've changed the theme to a default theme (which has our code customizations) and disabled a multi user role plugin we've home-grown.  Still, on one pod, a user with specific capabilities (edit_custompodcapability) produces the below error.  When I disable notices, the edit form functions fine.  Also, an admin with all privileges does not get this notice.  Also, I've upgraded to latest WP 3.9.1 and the error still appears.

Any ideas?

Thanks ~ Ryan

Notice: Undefined offset: 0 in .../wp-includes/capabilities.php on line 1102
Call Stack
No       Time    Memory  Function        Location
1       0.0000  239872  {main}( )       ../post.php:0
2       0.1502  21577720        include( '.../wp-admin/edit-form-advanced.php' )        ../post.php:211
3       0.1645  21706128        do_action( )    ../edit-form-advanced.php:2234       0.1692  21716248        call_user_func_array:{..gaynor/wp-includes/plugin.php:470} ( )  ../plugin.php:470
5       0.1692  21716280        PodsMeta->meta_post_add( )      ../plugin.php:470
6       0.1917  22369768        PodsForm::permission( ) ../PodsMeta.php:846
7       0.1917  22369944        pods_permission( )      ../PodsForm.php:1076
8       0.1919  22371032        current_user_can( )     ../general.php:1022
9       0.1919  22371872        call_user_func_array:{..gaynor/wp-includes/capabilities.php:1337} ( )   ../capabilities.php:1337
10      0.1919  22372208        WP_User->has_cap( )     ../capabilities.php:1337
11      0.1919  22372696        call_user_func_array:{..gaynor/wp-includes/capabilities.php:956} ( )    ../capabilities.php:956
12      0.1919  22373120        map_meta_cap( ) ../capabilities.php:956
13      0.1920  22375304        call_user_func_array:{..gaynor/wp-includes/capabilities.php:1300} ( )   ../capabilities.php:1300
14      0.1920  22375728        map_meta_cap( ) ../capabilities.php:1300

**Comment by GaryJones** [comment]
@rmckeel Did this issue disappear with subsequent releases?

**Comment by rmckeel** [comment]
@GaryJones Good question.  So much has changed, and I'd have a hard time replicating or testing at this point.  I will assume closed and open again if I see another notice or issue with current versions.  Thanks
