### ISSUE TITLE
Required simple list field doesn't accept value | label options with value 0

### ISSUE THREAD

**Issue by bakaburg1** [pods-framework/pods#2171]
Hello. I noticed that since I updated pods 2.4 and worpdress to 3.9, a field that is required and has an option with value 0, if that option is chosen, when saving the item you receive the message "Field x is empty". If the field is not required everything's ok.

I guess is an "== false" instead of "=== false" problem.

**Comment by pglewis** [comment]
I can't reproduce this with either text or number type fields.  As this no longer appears to be an "across the board" issue we need to know what specific field types are having a problem so we can reproduce.

**Comment by pglewis** [comment]
One second after closing the issue I realized the field type is in the title.  But I just tested simple custom defined list with: 

```0|Zero
1|One
2|Two
3|Three
```

and saw no issues with any of the format options for the field.
