### ISSUE TITLE
Error Notice when using find() to retrieve pods by custom taxonomy fields

### ISSUE THREAD

**Issue by paoloimpelluso** [pods-framework/pods#2180]
Hi guys, let me explain better.
I've got CPT linked to custom taxonomies. Custom taxonomies ha some custom field.

When i use pods->find() to retrieve CPT, filtering by Custom Tax field ( using this expression: 'where' => ' custom_tax.custom_field = "value" ' ), i got this error: 

Notice: Undefined index: pod in .../wp-content/plugins/pods/classes/PodsData.php on line 2743

The method is working well ... so i got the result. The notice message anyway sould be cleaned ... any idea on how to remove it?

thanks, Paolo

**Comment by quasel** [comment]
a lot has happened since 2014!
