### ISSUE TITLE
File Upload has class "hidden" on thumbnail

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#2182]
This is the list that displays thumbnails on an edit-pods-item-page after uploading. The <li> has class hidden; I don't think this is intended.

ul class="pods-files pods-files-list"
  li class="pods-file hidden" id="pods-file-49"

**Comment by dpark83** [comment]
@Shelob9 the file class is changing the field type to attachment for frontend forms https://github.com/pods-framework/pods/blob/b316cc6a63034d6cbe7045e9a125d18461f4e9df/classes/fields/file.php#L292-L295

**Comment by pglewis** [comment]
What I don't see explained anywhere is why we're tacking on a class named hidden, namespaced or not.  

Now (#3334) might be a great time to just yank this out.

**Comment by pglewis** [comment]
I have nothing specific to reproduce at this point.  File upload has been reworked for the admin side and I've seen no instances of it being hidden.  

Regarding front-end forms, there's a reported forum issue above which couldn't be reproduced using a default theme.  

If this turns up again it's time for a new issue with specifics on reproducing this issue.
