### ISSUE TITLE
$field[ 'options' ] unset for some fields when using front-end form for custom taxonomy

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2189]
I got errors of $field[ 'options' ] being an undefined index for several fields when using Pods Form to create custom taxonomy terms in the front-end. The taxonomy is extended, but it is the default fields that do not have the options index set.

**Comment by quasel** [comment]
from @sc0ttkclark at the closed PR:

> This will no longer be needed in the new 3.0 revamp of our field object/arrays. I'm going to keep the original ticket open though, until this portion of the code has resolved.

so that's 2.8 now ;)

**Comment by sc0ttkclark** [comment]
Resolved in Pods 2.8
