### ISSUE TITLE
Create Pods Settings In Pods Admin-> Settings

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2197]
Based on discussion in #2191 we will be creating a Pods global settings in Pods Admin->Settings. The debug info that is there now will get moved into a tab of Pods Admin->Help (see #2195).

STEPS:
- [x] re-enable settings tab.
- [x] add method with array of fields to  create _pods_settings to Admin class.
- [x] add method to Admin class to implement settings.
- [ ] add _pods_settings via API. (This is #2214 for @sc0ttkclark )
- [ ] Output settings UI in settings tab. 
- [ ] Hook Pods_Admin::pods_settings_callback() to something/ figure out what to hook it to, once its ready to be implemented.

Proposed list of settings:
- GENERAL
- [ ] Default search/pagination options (Turns defaults to off, or on, for all find() used on the site, unless explicitly defined as on when using those Pods)
- PERFORMANCE
- [x] Enable Pods Light mode
- [x] Enable Pods Tableless mode
- [ ] Disable Full Meta integration for performance (`get_post_meta( $id )`)
- [x] Disable Pods API Cache
- [x] Disable Deprecated functions
- [x] Disable Session Auto-start
- ACCESS & SECURITY
- [x] Disable 'Pods' content menu
- [x] Disable eval
- [x] Disable file uploaders / media modals
- [x] Require Login For uploader/ modal
- [x] Disable SQL for Shortcodes
- [x] Access to Pods Admin by user role. In network mode allow setting by site, with network-wide default if isn't set per site.
- COMPONENT SETTINGS
  - \- [x] Pod Pages:*\* Disable Pod Page check on every page
  - \- [x] Pod Pages:*\* Allow Pods Version number output on Pod Pages
  - \- [x] Pods Pages: Disable Pods Meta

**Comment by pglewis** [comment]
Seems like a nearly completed list here... could the remaining pieces be extracted into new issues?  (Keep in mind I'm skimming here, on a sweep)

**Comment by sc0ttkclark** [comment]
No, this is all in Pods 3.0 and has to be backported now

**Comment by jimtrue** [comment]
@sc0ttkclark @pglewis Is this actually IN our code or just documented here?

Migrating most of the wp-config.php directives into an actual settings page would be absolute awesome-ness. Especially if we can group them by "area of impact"
