### ISSUE TITLE
Feature Request: Date Format

### ISSUE THREAD

**Issue by asap247** [pods-framework/pods#2208]
Hi,

Simple feature request:  Can you make the following date format for the pods date select field.

Month Year

That's all.

**Comment by szepeviktor** [comment]
Is it possible to default to WP's data format?

**Comment by jimtrue** [comment]
Related #4105

**Comment by jimtrue** [comment]
Why was this particular issue closed? An easier to use date filters format input screen would be a very good thing.

**Comment by jimtrue** [comment]
Even WordPress Core has it:

![screenshot 2017-04-10 06 34 37](https://cloud.githubusercontent.com/assets/3052875/24857887/d5fc0498-1db7-11e7-883d-8413cd528342.png)

**Comment by JoryHogeveen** [comment]
@jimtrue I'm already working on this. One problem I'm running into is that the backend UI (jQuery datepicker) doesn't handles formats differently and might nog support all PHP date() options.

WP only has this for front-end output (so PHP only).

**Comment by jimtrue** [comment]
Weren't we looking for some better datepickers anyway? I know we use HTML5 as an option (which I think turns off the jQuery datepicker)

**Comment by jimtrue** [comment]
I'd also like to confirm that by default the date output that we kick out matches the WP General Settings one.

**Comment by sc0ttkclark** [comment]
Added this ability as part of #4106
