### ISSUE TITLE
Feature request : empty result set template

### ISSUE THREAD

**Issue by squeezeboxhuf** [pods-framework/pods#2211]
I am using a pods 2.4 shortcode to present a list of upcoming events embedded within a page, but I would like to somehow specify something to display when the "where" parameter returns no results - I'm thinking something like a new parameter e.g. empty_template="no_events" which will trigger the template "no_events" which just contains a pre-configured polite message, "check back later" type of thing.

Does that sound reasonable? Just trigger the alternative template in the case of a zero-sized result set...?

Cheers. Thanks for producing a fantastic plug-in.

**Comment by FrankHablawi** [comment]
Not exactly sure how to add a vote to this, so I starred it. Great potential feature for many users.

**Comment by jimtrue** [comment]
Looks like you found it @FrankHablawi The 'reaction' of a thumbs up is a vote ;)

**Comment by jimtrue** [comment]
## TaskList for Shortcode Addition for 'No Results'

- [ ] Return default "No Results Found" (override default handling?); this would match WP Query style.
- [ ] `hide_no_results` parameter, default false
- [ ] `no_results_message` parameter, provide override for no results message
- [ ] `no_results_template` parameter, route to a different template for no results
