### ISSUE TITLE
Problem storing JSON in PODS field?

### ISSUE THREAD

**Issue by lapidus** [pods-framework/pods#2219]
I am trying to store a JSON response from another database in a PODS paragraph field:

`{"request":{ "ind<50" : 1 } }`

This however gets cut off at the "<" character:

`{"request":{ "ind`

What is the issue here and how can I work around it?

**Comment by quasel** [comment]
@pglewis maybe related #5040 ? Is this still an issue?

**Comment by quasel** [comment]
see #3795 - for ison in paragraph field -> usage of \r\n is converted to rn

**Comment by pglewis** [comment]
> @pglewis maybe related #5040 ? Is this still an issue?

Not on this one.  #5040 specifically concerns only backslashes being stripped.  This issue is very likely and HTML escaping issue.

**Comment by JoryHogeveen** [comment]
Might be related: #5665

**Comment by JoryHogeveen** [comment]
Closing this issue. As stated by @sc0ttkclark this is because HTML tags are stripped.
One workaround is to empty the "allowed html tags" option (only set a space).
A better way is to use the code field as mentioned above.
