### ISSUE TITLE
Pods admin pages blank when Pods is symlinked

### ISSUE THREAD

**Issue by naomicbush** [pods-framework/pods#2221]
The Pods admin pages are blank when Pods is symlinked into the WordPress plugin directory because PodsView::locate_template, line 569 

`if ( false === strpos( $_real_view, realpath( WP_PLUGIN_DIR ) ) && false === strpos( $_real_view, realpath( WPMU_PLUGIN_DIR ) ) )`

is searching the plugin directory path, but the actual files are stored elsewhere.

I'm curious — why is WP_PLUGIN_DIR used and not PODS_DIR? Using PODS_DIR, it works fine.

**Comment by quasel** [comment]
as of #2945 fixed!
