### ISSUE TITLE
Extended Post Types, With Dashes In Names Have Dashes Translated To Underscores

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2227]
I have traced the root of #2218 to the name of the post type, in that case 'sfwd-courses' containing dashes. The extended Pod is called 'sfwd_courses' and therefore the Pods fields can't be loaded properly in the editor for 'sfwd-courses'.

As an additional test, I registered a post type without using Pods that called 'test-post-type' and then extended it with Pods and then I extended it with Pods, which translated the name to 'test_post_type'. I added a custom field, but the Pods meta box did put output in the post editor for test-post-type.

I used get_post_types() to check the names of registered post types and sfwd-courses' and 'test-post-type' were int he returned array, not 'sfwd_courses'  and 'test_post_type'

**Comment by quasel** [comment]
couldn't even remember but #3012 :D should all be fixed and 3.0 went another way R.I.P :D
