### ISSUE TITLE
Replace all session and session_id usage

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#2237]
We've had ongoing issues with incorrect session save path configurations, plus now we've encountered an added complication with modern hosting where sessions are handled by a dedicated machine via IP address stored in the session save path.  

It appears our primary remaining usage of sessions is to use the session ID as added security for wp_verify_nonce() (and even then only when not logged in). After a little discussion with @sc0ttkclark I think we've agreed that we can replace that by incorporating the session management here: https://github.com/ericmann/wp-session-manager.

**Comment by Enchancer** [comment]
I think it is not fixed: http://pods.io/forums/topic/issue-with-php-session-open_basedir/#post-192912

**Comment by jimtrue** [comment]
This doesn't indicate it's fixed, it's that it's on our roadmap for Future Pods Release. However, if you're looking for a workaround, you can discuss that here @Enchancer

**Comment by tristanleboss** [comment]
The best would be to get rid of sessions totally. Indeed, even WP_Session drops a cookie.

Cookies, especially when they are dropped on every single page, are a problem for caching system like Varnish.

**Comment by quasel** [comment]
possible workaround see #2542 

This is what that particular config variable does:
PODS_SESSION_AUTO_START – false – Disables Sessions from starting when Pods is loaded. Sessions are used by Pods for securing usage of public forms visitors who are not logged in.

**Comment by sc0ttkclark** [comment]
Maybe instead of wholesale removing sessions, we should think about why we needed them and what solutions exist now to achieve the same goals.

From what I remember, we had sessions to uniquely identify that someone (logged out) was indeed who they were supposed to be and that they only had access to the fields presented in the form itself.

Now, what pros/cons can we see with removing sessions? Let's put together a list to start.

**Comment by maiki** [comment]
I haven't used forms from Pods, so I haven't had an opportunity to use sessions. However, I did [recently run into this](https://interi.org/2016/07/disable-session-cookies-in-pods/), and have disabled sessions to get caching to work properly. I haven't had any other issues with it, so my cons list is very short:

* Sessions don't currently play well with caching
* May be deprecated; this is just from the context from the earlier posts in this issue, it seems we didn't have an alternative when this was implemented

**Comment by robrecord** [comment]
After trying to figure out why my client's site isn't caching for a very long time, I have stumbled across this. This issue is really important and has become a showstopper for me - I am considering ditching Pods. I will try setting PODS_SESSION_AUTO_START but I am not sure what I will be missing.

**Comment by sc0ttkclark** [comment]
We use sessions for public forms, so when you embed a form via the Pods shortcode or when you output one with `$pod->form()`

If you have no need for public forms, disabling the auto start should cover your bases.

**Comment by robrecord** [comment]
Will you consider disabling sessions unless forms are actually in use by the setup?

**Comment by sc0ttkclark** [comment]
Open to ideas on how to accomplish that.

**Comment by robrecord** [comment]
Perhaps auto start could be disabled by default on new installs, with an option + information about it in the administration panel.

**Comment by robrecord** [comment]
PS I am sorry if I appeared to be rude, I appreciate your efforts on this plugin.

**Comment by ahmed-sigmalux** [comment]
Seconding @robrecord 's suggestion of making sessions an opt-in feature.

**Comment by quasel** [comment]
related to #4636 and #2237 ;) it's a never ending story :D 
> There are only 2 hard problems in computer science:
> Cache Invalidation
> Naming Things
> Off-by-one Errors

it never get's old 🎣

**Comment by sc0ttkclark** [comment]
Fixed via #5626
