### ISSUE TITLE
Add option to "website" type field to use "insert link" modal from the post editor

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#2268]
Is there a field type that mimics the Insert link modal on the post editor?
To choose from various post types or input an URL.

**Comment by szepeviktor** [comment]
Related: https://github.com/pods-framework/pods/issues/2655

**Comment by JoryHogeveen** [comment]
Included in 2.7

**Comment by JoryHogeveen** [comment]
@szepeviktor 
I had the need for this field for a client so I patched the 2.7 field code into a separate plugin to use as long as Pods 2.7 isn't official yet.
You can install it and it will add the field to the Pods field type with all functions exactly as merged into the 2.7 release.
It will also patch any `Website` field if you change it to a `Link` field.

https://github.com/JoryHogeveen/pods-link-field
Just to let you know!

**Comment by szepeviktor** [comment]
@JoryHogeveen Thank you for your work.
