### ISSUE TITLE
Pods From Widget Doesn't Support Extended-User Pods

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2289]
I'm not sure if this was intentional or not, but the options in the Pods Form widget do not include an extend-user Pod. The list of Pods is generated like this in ui/admin/widgets/form.php:
            $api = pods_api();
            $all_pods = $api->load_pods( array( 'names' => true ) );

I tested that same code, with `print_r( $all_pods );` added and do not see the extended users Pod. On the other hand, `print_r( $api->load_pod( 'user') );` returns info about my extended users Pod as expected.

Related forum post:
http://pods.io/forums/topic/add-relationship-field-entry-from-front-end/#post-185825

**Comment by quasel** [comment]
works now ;)
