### ISSUE TITLE
PODS_LIGHT check before components menu call in PodsAdmin.php:507

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2301]
PODS_LIGHT check before components menu call in PodsAdmin.php:507

**Comment by rogerlos** [comment]
(Not sure if this is where to leave this note, but if I define `PODS_LIGHT` to true, my complete admin back end crashes with a fatal error (in strict mode, in any case). I assume that is what this bug is noting?)

**Comment by JoryHogeveen** [comment]
Related: https://github.com/pods-framework/pods/issues/3811

**Comment by sc0ttkclark** [comment]
Fixed by #3837
