### ISSUE TITLE
Capabilities: delete_users

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#2311]
It looks like access to pods is solely based on one wordpress capability: delete_users.

What should I do if I want a client to be able to delete users and NOT have access to pods?

**Comment by quasel** [comment]
from @JoryHogeveen #3625

>  Currently the admin capabilities check for the delete_users capability in pods_is_admin() (includes / general.php).
> I've would like to see this changed into manage_options or administrator since Pods is a options page...
> 
> An other idea is to just use the is_super_admin() function since this function also works for non-multisite installations.

is this still an issue or just a doc's issue?

**Comment by quasel** [comment]
and from @sc0ttkclark  #3985 

> There's a filter where you can override all access checks via `pods_is_admin()`, the filter is named `pods_is_admin`.
> 
> For single site installs, you can disable access from delete_users capability by using the filter:

```php
add_filter( 'pods_admin_capabilities', '__return_empty_array' );
```
