### ISSUE TITLE
Impossible to save required number and currency fields with 0 / 0.00

### ISSUE THREAD

**Issue by mfalkvidd** [pods-framework/pods#2313]
The fixes for #2064 (commits 52d3b6b2, 679b876a) made it impossible to save a "Required" number or currency field with the values of 0 or 0.00.

"00" or "0.000" are still possible to save though.

imho, an alternative fix for #2064 would be to set the default values to an empty string instead of 0 and 0.00 respectively.

How to reproduce:
1. Create a new pod.
2. Add a Plain Number field and check the "Required" checkbox
3. Add a Currency field and check "Required" checkbox
4. Save the Pod
5. Add a new pod of the type you just created. Make sure the Plain number value is 0 and the Currency value is 0.00.
6. Click preview.

I guess it is debatable what "Required" means for number and currency fields.
* A Currency field could for example be used for a price. For me it makes sense to allow a price of 0.00 (=free), but not an empty price.
* Number could be the amount in stock. The stock could be empty, which should be denoted by the value 0.

Maybe revert the fixes for #2064 and set the default value to "" instead?

Possible workaround (until this issue is resolved): Don't set fields of number and currency to Required in your pods, at least not if you want to be able to save the value 0/0.00.

Also related to issue #2171

**Comment by pglewis** [comment]
We need a general audit of required fields by type (Bool, numeric, drop-down field with simple values).  Too many false positives coming up in fields due to a general falsiness check.

**Comment by pglewis** [comment]
This one is going down as "could not reproduce" as well.  I was able to enter 0 for a standard required number field with the defaults, and 0 or 0.00 for currency format.
