### ISSUE TITLE
Impossible to save required boolean fields with value of false

### ISSUE THREAD

**Issue by mfalkvidd** [pods-framework/pods#2314]
commit 1e7dd942b (#1142) made it impossible to save a Required boolean field with the value false (the value must always be set to true).

How to reproduce:
1. Create a new pod.
2. Add a Yes / No field and check "Required" checkbox
3. Save the Pod
4. Add a new pod of the type you just created. Make sure the Yes/No value is unchecked.
5. Click preview.

Does "Required" make sense for a checkbox? Maybe the fix is to remove the "Required" option for boolean fields? But users might want to require the checkbox to be checked, for example when accepting a license agreement. For that case, the current implementation is good.

Possible workaround: Don't set fields of types boolean to Required in your pods. Maybe this should be the documented and recommended way.

**Comment by JoryHogeveen** [comment]
This was fixed in #5550

@jimtrue You tagged it as Documentation, still valid or can I close this?
