### ISSUE TITLE
Add ability to extend the Customizer with new sections / fields

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2318]
Add ability to extend Theme Customizer with new fields/groups

**Comment by sc0ttkclark** [comment]
In our work integrating with CMB2, we may have Customizer access built into that just in time -- https://github.com/WebDevStudios/CMB2/issues/465

I've moved this to 3.0 and will be assisting in the process of merging Customizer support into CMB2.

**Comment by sc0ttkclark** [comment]
Some things we can lean on here:

https://github.com/WebDevStudios/CMB2/pull/468

**Comment by harlet** [comment]
Any updates on this topic?

**Comment by steve231293** [comment]
Hello there,
Any updates on this?
