### ISSUE TITLE
Add ability in magic tag parsing to do calculations

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2320]
Add ability in magic tag parsing to do calculations:

`{@field_name*other_field}` or `{@field_name*100}`

Including normal math operators for:
- `*` (multiplication)
- `-` (division)
- `+` (addition)
- `-` (subtraction)
- `%` (modulus)

**Comment by hefejeff** [comment]
Has this feature been implemented yet?

**Comment by sc0ttkclark** [comment]
No, not yet
