### ISSUE TITLE
Simple Relationship (list) won't save a value with double quotes

### ISSUE THREAD

**Issue by maiki** [pods-framework/pods#2360]
This may be related to the spirit of #1943. I've also posted this at https://wordpress.org/support/topic/how-do-i-get-the-lable-instead-of-the-value-from-a-list-with-get_post_meta.

My issue is that if I have double quotes in the value of a list item, it won't save when I update the post; it returns an empty field instead. In the past I got away with these items:

1|5.5" x 8.25"
2|6" x 9"
3|5.5" x 7.5"
4|5.25" x 7"
5|5.375" x 7"
6|5.5" x 7"
7|7" x 9"
8|7.25" x 9.5"
9|8" x 10"
10|9" x 7"

Those are the trim of a book (its size), and the reason this worked is because I would use a magic tag, `{@trim}`, and it gets the label. That works, so I didn't think about it much. Now I am moving my templates into the theme, and `<?php echo get_post_meta( get_the_ID(), 'trim', true); ?>` returns the value, which in this case isn't helpful.

As @Shelob9 pointed out, there are ways to get the label, but I'd rather figure out how to save the value I want, and just use `get_post_meta`.

I've tested the following modifications to the list:

|5.5" x 8.25"
6" x 9"|6" x 9"
5.5 x 7.5|5.5" x 7.5"
5.25" x 7"

Of those four, only the third, `5.5 x 7.5|5.5" x 7.5"`, will save the value. That may work in the meantime, but of course we would prefer to have the double quotes to refer to the inches in the size.

I've tried escaping the double quotes, with back slashes, but that didn't change anything. Suggestions? ^_^

**Comment by quasel** [comment]
any plans to tackle this or shall we just close it - there is a PR since 2016 time to make a decision ;) @sc0ttkclark @jamesgol - or just add a doc with it's a known issue don't fo it :P
