### ISSUE TITLE
Notice: Use of undefined constant JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by davcevski** [pods-framework/pods#2367]
Notice: Use of undefined constant JSON_UNESCAPED_UNICODE - assumed 'JSON_UNESCAPED_UNICODE' in /plugins/pods/classes/PodsAPI.php on line 6913

I got this notice today using PODS while looping over custom taxonomies and getting the extra field values. I tried digging into the class, with no luck since you are using 'JSON_UNESCAPED_UNICODE' only on Servers running php 5.4 and over, and its strange since the web I am working on is running on PHP 5.4.33. No biggie, but wanted to let you know. 

Best

**Comment by pglewis** [comment]
This is 2 1/2 years old, no update, and not a single other issue in a search on "JSON_UNESCAPED_UNICODE".
