### ISSUE TITLE
Pods with required fields and Polylang

### ISSUE THREAD

**Issue by jmcbade** [pods-framework/pods#2369]
I am using WP 4, Polylang Version 1.5.5, Pods Version 2.4.3

I have done a very basic (no other plugins added) and created a simple Pod (not advanced)

I have two fields that are required. I create a post using the pod. Then for the translation, clicking the “+” for Polylang translation. I get warning message, white box on a gray background, I think it’s from Pods, saying:

<required field> is missing

If I edit the pod and say the first field is no longer required, then the next screen shows the same message but saying the second field is missing.

If no fields are set required, then the translation version of the record appears as expected.

**Comment by jtraulle** [comment]
:+1: following this too

**Comment by JoryHogeveen** [comment]
@jmcbade @jtraulle 
I can't reproduce this issue with the latest release (v2.6.6). Can you please verify the latest release is working for you too?

**Comment by JoryHogeveen** [comment]
Closed due to no reply.
