### ISSUE TITLE
JS Validation on extended WP object forms

### ISSUE THREAD

**Issue by ghost** [pods-framework/pods#2424]
## Tasks
- [ ] Look into pulling our existing JS form validation code that we use on ACT forms
- [ ] On WP forms, call JS function/method once page loads that hooks into validation

---

Original message:

When an input is not valid, like blank input for a required field, letters in a number only field, can we have the validation message on the same page rather than going to another page to see the error message and then come back. Because if I click the back button to do the amends, I'm actually creating another page rather than editing the page I've worked on.

Thanks.

**Comment by sc0ttkclark** [comment]
Updated issue title and added tasklist to complete

**Comment by sc0ttkclark** [comment]
In Pods 2.7 we are now showing back links when using wp_die(). This isn't a fix for this issue however it does at least improve things in a minor way.
