### ISSUE TITLE
Give pods full access to administrators by default

### ISSUE THREAD

**Issue by redpik** [pods-framework/pods#2446]
When I create pods on a WP multisite, I need to install "Roles & Capabilities" and tick pods capabilities to administrators.
IMHO administrators should access pods by default.

**Comment by JoryHogeveen** [comment]
I'd say this is a user prefference. For example, I like it that Pods is only visible for super-admins on a network.

**Comment by jimtrue** [comment]
Shouldn't this be something we either set through a wp_config.php directive or inside our Pods Settings menu when Pods recognizes it's on a Multisite? I know at present the method for 'fixing' this issue isn't clear or straightforward.

**Comment by JoryHogeveen** [comment]
> I know at present the method for 'fixing' this issue isn't clear or straightforward.

To me it feels quite straightforward. Just grant the Pods capabilities to the `administrator` role.

**Comment by jimtrue** [comment]
Until WordPress provides that roles/capabilities management as part of their WP Core, it's not that straightforward. And you've got to find all of them. And it's easy to miss some.

The point I'm coming from is: We're a bridge or an onboard for people getting started in 'better web development'. If we can help them configure stuff like this (and like all the WP_CONFIG settings), shouldn't we?

**Comment by JoryHogeveen** [comment]
Fair enough. In that case more options are possible:

- Defining a global constant in wp-config.php
- Add the option to the Pods setting page and enable/disable access for each blog separately
- (also) Add the option to a Pods setting page on the network admin and setting it globally (requires more work I'd guess)
