### ISSUE TITLE
Git Branch cleanup

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2459]
Some branches need renaming / cleanup:

* [x] assets - remove /assets/ folder out of the main 2.x / 3.0-unstable branches (@shelob9) 
* [x] bugfix/* - are these merged in, do we need them anymore? (@clubduece)
* [x] pods-field - is this merged in? (@clubduece)
* [x] test/* and tests/* - are this merged in? do we need anymore? (@clubduece)

**Comment by Ramoonus** [comment]
bump

**Comment by sc0ttkclark** [comment]
I've already cleaned up
