### ISSUE TITLE
Pods will not update

### ISSUE THREAD

**Issue by TomAuger** [pods-framework/pods#2467]
HI Scott, so I've got Pods on a completely virgin, 4.0.1 install, and have successfully created a CPT pod with a custom Cap.

When I go back to edit that pod - anything: label, turn on/off a checkbox, whatever, and hit the Save Pod button, I get the "saved succesfully" green admin notice, but the change is not actually saved. So that kind of sucks.

I'm going to delete the pod altogether, and try creating a new one and see at what point the saving breaks.

Oh, and happy Thanksgiving Pods team!

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
