### ISSUE TITLE
Deleting Pod does not delete any custom caps

### ISSUE THREAD

**Issue by TomAuger** [pods-framework/pods#2468]
Not sure this should be an automatic thing, but it should definitely be an option when deleting a Pod that has a custom capability associated with it.

I created a Pod that used a custom capability, turned on the Roles extension and added all the new caps that were associated with that Pod to the Admin user. Then I deleted that Pod.

The caps are still there and still associated with the Admin user. I would guess that in 90% of use cases, custom caps that are associated with a Pod ought to be deleted when that Pod is deleted, provided there are no other Pods that require that cap as well.

**Comment by sc0ttkclark** [comment]
Actually I'm afraid of doing this for a number of reasons now that I'm revisiting this. Like when deleting a pod and reimporting it, or deleting a pod to recreate it with some tweaks. Removing the capability from the users and roles may be overstepping in some situations. We could consider highlighting old capabilities for Pods that don't exist with a button to remove each more easily though.
