### ISSUE TITLE
Request for documentation for pod_item actions and filters

### ISSUE THREAD

**Issue by amerie999** [pods-framework/pods#2480]
I would find it very helpful if all the actions and filters that act on pod items were documented. I'm talking about the filters and actions analogous to pods_api_pre_save_pod_item and pods_api_pre_save_pod_item_{podname}. I have no complaint with the forum support; the support folks respond within 24 hours at most, are very helpful, and go the extra mile so they can answer my questions. And I'm really not trying to give y'all a hard time, but I am frustrated at not having the information I need. The lack of documentation has probably cost me several weeks, and I have yet more questions (or maybe issues) about the actions and filters I'm trying to use.

**Comment by GaryJones** [comment]
A more encompassing Issue to replace this one has been opened at #5045.
