### ISSUE TITLE
Pods 2.5 There was a server error with your AJAX request @Bi-directional field

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#2511]
Edit Pod -> ACT -> Related Pod -> happens only for WP User/Cat/etc ... 

JS Console:
Fatal error: Uncaught exception 'Exception' with message 'Related Pod not found' in /var/www/vhosts/just4us.eu/mq.just4us.eu/wp-content/plugins/pods/includes/general.php:145
Stack trace:
#0 [internal function]: pods_error(Object(Exception))
#1 {main}
thrown in /var/www/vhosts/just4us.eu/mq.just4us.eu/wp-content/plugins/pods/includes/general.php on line 145 (edited)

**Comment by quasel** [comment]
Seems this isn't solved entirely - it works for me with 2.5 (live and dev) but we had a report @slack support chat where this still happens ... @jamesgol did mention https://github.com/pods-framework/pods/commit/e8f503727f7b2ddc3ef4fc79ae874303ab7a1a2b#diff-f01d16819fcb44038b25d9cbc5778c56R1455 as starting point

**Comment by adamdunford** [comment]
Confirm this is not fixed.  Pods 2.5.1.1 on WP 4.1:
![image](https://cloud.githubusercontent.com/assets/57126/6077149/3cd27000-adec-11e4-87ca-84d90b60e1a5.png)

**Comment by Shelob9** [comment]
Yes I can confirm. Still an issue.

**Comment by sc0ttkclark** [comment]
Check the JS console and let us know what you see, we are writing d (the return data) and json (the parsed json object from the return data) to the console for debug purposes on this specific error.

**Comment by jamesgol** [comment]
console.log( d ) prints: []
console.log( json ) prints: Object {}

If there is nothing eligible to be a bidirectional relationship on the sister pod it returns an empty object, so jQuery.isEmptyObject( json ) will be truthy and it'll print that error.  Is that maybe supposed to be && instead of ||?

**Comment by sc0ttkclark** [comment]
Fixed via #2693
