### ISSUE TITLE
Documentation:  ACT & author Field

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#2540]
don't know where this should be or how to improve it - is this somewhere else? 
http://pods.io/forums/topic/understanding-roles-and-capabilities/

 When you use the Advanced Content Type pod, and use the ‘Author’ field, users with access to the basic capabilities for the Pod can only see / edit their own items. Unless they have admin access, or all of the pod capabilities checked for the pod, they shouldn’t see all items. Also note, the ‘pods’ and ‘pods_content’ capabilities will give full access, so avoid that for their role.

**Comment by JoryHogeveen** [comment]
Fixed in #5504
