### ISSUE TITLE
Upload - after the upload, you can not see what images are loaded in form.

### ISSUE THREAD

**Issue by andre2** [pods-framework/pods#2556]
I created form and add multiupload images field, when i add two images:
I see this:
<img src="http://i.imgur.com/Z2jGVKw.png?1">

and after upload status i don't see images, optional information with upload succes and number of items.

i use front end form.

**Comment by andre2** [comment]
Ok, a try this but this is my configuration:
<img src="http://i.imgur.com/TaWET0P.png?1">

and upload images process
<img src="http://i.imgur.com/USg1dZ9.gif">

**Comment by Shelob9** [comment]
@andre2 I am reclassifying this as a bug then. It sounds like there could be a Javascript error.

Can you please test again while watching the console and see if you have any errors and check the response in the network inspector for the requests to admin-ajax for processing those uploads? If you can let us know what errors you are seeing, that would be a big help.

**Comment by andre2** [comment]
Okay, i found my bug, i use bootstrap, and bug follows from class hidden of bootstrap.
and in dom i see code with class hidden, after remove hidden i see image ;)

**Comment by Shelob9** [comment]
@andre2 Thanks for pointing out that this is related to Bootstrap. I've seen too many of these issues. @sc0ttkclark and I agree that our use of .hidden is a mistake, so we will change it to `.pods-hidden`.

I'm going to close this issue to keep things clean, but will work on #2578 today, which should clear this up for you in Pods 2.5.1.

**Comment by andre2** [comment]
Thanks!

**Comment by Shelob9** [comment]
@andre2 Can you please test my fix for this by checking out the feature/2578 branch or downloading it here:

https://github.com/pods-framework/pods/archive/feature/2578.zip

**Comment by andre2** [comment]
@Shelob9 okey, works but, icon trash, image name are not editable, please add follow lines to ul.pods-files in css

    position: relative;
    z-index: 9999;

**Comment by Shelob9** [comment]
Thanks for the feedback.

I do not think it would make sense for us to mess with position or z-index for this. It's better for you to make the tweak in your own site with that css.
