### ISSUE TITLE
Clear Pods' Cache after upgrade

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2558]
Issues that occurred on Pods.io last night were cured by clearing Pods cache. But cache should have been cleared by update. Could be something else, but sounds like the clearing of cache in PodsInit.php at roughly line 1000 didn't run. But why?

**Comment by quasel** [comment]
same here - update from 2.4.3 - clear cache issue gone ...

**Comment by Shelob9** [comment]
@quasel Can you elaborate on what issue you had? On Pods.io we had some errors where keys of arrays returned by `Pods::field()` for relationship fields were missing. Clearing cache (we are using SiteGround's implementation of memcached) fixed the issue.

**Comment by quasel** [comment]
Bug: pods-json-api ajax calls did return 404 after update - didn't investigate more :/ sorry - just hit clear pods cache 

Debug Information
WordPress Version: 4.1
PHP Version: 5.3.3
MySQL Version: 5.1.73
Server Software: Apache
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.10 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.10
Session Save Path: /var/lib/php/session
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
WPDB Prefix: wpuni_
WP Multisite Mode: No
WP Memory Limit: 40M
Pods Network-Wide Activated: No
Pods Install Location: /data/web/www/vhosts/unisport-austria/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Unisport2012

Currently Active Plugins:

Adminer: 1.3.2
BackWPup: 3.1.4
Custom Meta Widget: 1.4.6
Debug Bar: 0.8.2
FancyBox for WordPress: 3.0.2
imes Athleten Database: 0.8
JSON REST API: 1.1.1
Members: 0.2.4
Pods - Custom Content Types and Fields: 2.5
Pods JSON API: 0.2.3
TablePress: 1.5.1
TablePress Extension: Larger Edit Input Fields: 1.0
Theme My Login: 6.3.10
TinyMCE Advanced: 4.1.7
Widget Logic: 0.57
WordPress phpinfo(): 14.12
WP Slimstat: 3.9.1

**Comment by Shelob9** [comment]
@quasel Thanks. This is good info.

@sc0ttkclark Notice that he is NOT using multi-site. We had suspected Pods being network updated on pods.io might have been to blame.

**Comment by Shelob9** [comment]
So, https://github.com/pods-framework/pods/commit/cbb9ecc73faff9a4ff0b2b09684c675183ff2a81 (which shouldn't get merged) sets the version ahead and adds some pods_errors() where we hope it would be (IE where cache gets flushed) and they get hit on refresh.

So here's my two new theories:
1) when the plugin gets updated, the option 'pods_framework_version' gets reset without flush. Then next time 'init' is run, the version is already right, so flush never happens.

2) The two reported cases result from the value getting messed with in development, testing.

Since @jimtrue has not seen any sign of this in  the wild. I lean towards theory 2, which would mean non-issue.

**Comment by Shelob9** [comment]
#2561 is evidence that this is a "real" issue :(

**Comment by pglewis** [comment]
I've changed the issue title to what I think needs to be done.  

@sc0ttkclark: any compelling reason not to blindly clear cache after upgrade?

**Comment by pglewis** [comment]
Also, from James Golovich: `One thing I had planned to do before but never had the time to do was add a version prefix, so if the version number changes the cache key will be guaranteed to be different`

**Comment by sc0ttkclark** [comment]
I'm open to either of those, maybe the default groups get prefixed by version, in addition to attempting to clear cache?

**Comment by pglewis** [comment]
Is there any advantage to leaving a previous version's transients hanging around?  Instincts say better to do one or the other without anything concrete to hang my hat on.

**Comment by sc0ttkclark** [comment]
No advantage, but we need to find out why caches aren't being deleted on upgrade as transients in the DB will get unwieldy if we don't fix that too.

**Comment by sc0ttkclark** [comment]
The fix in #3401 is ready for testing.

**Comment by Shelob9** [comment]
@sc0ttkclark A little later, but what about a unique version prefix for Pods cache, updated by Grunt?

**Comment by quasel** [comment]
got another report about about issues after 2.6 to 2.61 update with pods that are resolved by clearing cache ( widget template content not dispalying )

**Comment by jimtrue** [comment]
Fixed by #3487
