### ISSUE TITLE
like_escape notice

### ISSUE THREAD

**Issue by rmckeel** [pods-framework/pods#2559]
Running latest WP 4.1 and Pods 2.5.  Get the stack trace below (it's a notice, so minor but needs to be fixed).

This seems to be a logic issue with data.php line 115 "pods_version_check( 'wp', '4.0', '<' ) ) {", since it should be running esc_like instead.  "..." in image represents hidden information to keep the privacy of the project.

![image](https://cloud.githubusercontent.com/assets/4602573/5589874/a564071a-90e5-11e4-820c-cc4d416245a5.png)

**Comment by sc0ttkclark** [comment]
Fixed in #2572
