### ISSUE TITLE
Hidden fields show up for an admin user

### ISSUE THREAD

**Issue by rmckeel** [pods-framework/pods#2560]
I'm doing quality control before I upgrade Pods from 2.4 -> 2.5 (I did not do interim updates).

I created a new pod called 'test' and created a default text field called 'private'.  I then checked 'Hide field from UI'.  As an administrator (the user who set it up), clicking 'Add new' for test shows that field.  This is different than functionality in v2.4, where the field would be hidden.  Can provide screenshots if necessary, but I think it is really simple to duplicate.

**Comment by sc0ttkclark** [comment]
Try this fix: https://github.com/pods-framework/pods/tree/feature/2560

ZIP: https://github.com/pods-framework/pods/archive/feature/2560.zip

**Comment by rmckeel** [comment]
Thanks, Scott.  I'll see if I can get some time to test that out today.


Ryan McKeel
Practical advice for pursuing holiness in the trenches of everyday life -
whybemerelyhuman.com
<http://whybemerelyhuman.com/?utm_source=email&utm_medium=email%20signature&utm_campaign=signature>

**Comment by Shelob9** [comment]
Reassigning to @sc0ttkclark as issue is not resolved by eba54273cf73297a4aa57fc7331cf20aa7fa426f
