### ISSUE TITLE
Drag & Drop multiple image field not saving order

### ISSUE THREAD

**Issue by robertfyffe** [pods-framework/pods#2567]
I have added a multiple image field to my pod. When I try and re-order the images using the drag and drop facility it works just fine, however when I save the post the order is not saved it reverts to the original order. See screenshots below:

![before](https://cloud.githubusercontent.com/assets/6306113/5598645/035d937e-9288-11e4-84cd-c54180ccaf7d.jpg)
![required_order](https://cloud.githubusercontent.com/assets/6306113/5598646/036112e2-9288-11e4-9ecd-7728a61a298e.jpg)

The first screenshot is the original order, the second is what I want but when the post is saved it just reverts to the original.

I have the latest version of Wordpress and Pods installed and very few other plugins so cannot see any problem from my side. Could this issue be tested?

Thanks
Robert

**Comment by sc0ttkclark** [comment]
Could this be cache related @jamesgol?

@robertfyffe Can you go to Pods Admin > Settings > Clear Pods Cache and then return to the edit page? Let me know if you see it in the order you had originally saved it in now.

**Comment by robertfyffe** [comment]
Thanks for the reply, I just tried clearing the cache still the same problem.

**Comment by Shelob9** [comment]
Possibly related #2556

**Comment by robertfyffe** [comment]
I have looked through that issue, don't think it is related, I tried selecting different options and still have the same problem.

**Comment by robertfyffe** [comment]
Now working perfect, thanks guys.

**Comment by MrWebslinger** [comment]
I see you said this was fixed, is there an update or do I need to manually change the code?

**Comment by Shelob9** [comment]
This will be included in Pods 2.5.1, which is almost complete. You can get the latest beta version by checking out the 2.x branch or via http://pods.io/latest
