### ISSUE TITLE
Add help text to Create Taxonomy Wizard to reference additional modules

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2569]
Add help text to Create Taxonomy Wizard to reference additional modules:

This is in reference to this support forum post:
https://wordpress.org/support/topic/cant-see-option-to-extend-taxonomies

Adding help text to activate Table Storage if you're doing a Custom Taxonomy.

From Scott:
We could add text for table storage / advanced content types too, since they're both optional.

Perhaps we could add a little box below the wizard box with information about other optional components related to the creation/extension of content types with Pods. If they are enabled, don't show the text, if not, show the text (maybe even offer a 'dismiss')

**Comment by Shelob9** [comment]
I think I already did this in 3.0-unstable. But it definetly should get put into 2.5.1.

**Comment by jimtrue** [comment]
This is no longer required because Extended Taxonomy no longer uses Table Storage but Term Meta.
