### ISSUE TITLE
Change from using .hidden to .pods-hidden

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2578]
#2556 Is one of many issues and forum threads where we have run in to problems with Pods Form's use of `.hidden`, since Bootstrap's JS and/or CSS acts on `.hidden`. Many other frameworks probably do as well.

Therefore all CSS and JS in Pods should be updated to use `.pods-hidden` in place of `.hidden`

**Comment by Shelob9** [comment]
be7184e is missing something, as I'm seeing some hidden text, visible with it.

**Comment by Shelob9** [comment]
Punting to 2.5.3 and deducting 5 imaginary internet points from @shelob9 for not finishing the PR on this.

**Comment by pglewis** [comment]
2.7 should remove all remaining instance.  Any future issues should be new issues with specifics on where it's happening and under what circumstances.
