### ISSUE TITLE
Related meta_value traversal not completing in find() with array params.

### ISSUE THREAD

**Issue by DavidCramer** [pods-framework/pods#2582]
When doing a find using the following:

``` PHP
    $params = array(
        "where" => array(
            array(
                "field"   => "location.country",
                "value"   => "ZA",
                "compare" => "="
            )
        )
    );
```

The query traverses correctly joins ``wp_postmeta` AS `location_country` ON `location_country`.`meta_key` = 'country'` but it doesn't add the meta_value compare in the WHERE. Instead it keeps the traversal syntax `WHERE ( ( `location`.`country` = 'ZA' )...` resulting in a "Unknown column 'location.country' in 'where clause'"
Here's the full SQL generated:

``` SQL
SELECT DISTINCT
`t`.*
FROM `wp_posts` AS `t`

    LEFT JOIN `wp_podsrel` AS `rel_location` ON
        `rel_location`.`field_id` = 1898
        AND `rel_location`.`item_id` = `t`.`ID`

    LEFT JOIN `wp_posts` AS `location` ON
        `location`.`ID` = `rel_location`.`related_item_id`


    LEFT JOIN `wp_postmeta` AS `location_country` ON
        `location_country`.`meta_key` = 'country'
        AND `location_country`.`post_id` = `location`.`ID`

WHERE ( ( `location`.`country` = 'ZA' ) AND ( `t`.`post_type` = "review" ) AND ( `t`.`post_status` IN ( "publish" ) ) )


ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
```

**Comment by sc0ttkclark** [comment]
Sounds like we need another few assertions added to the unit tests.

Can you clarify -- to be sure.

* `review` is a custom post type pod, it uses meta-based storage
* `location` is a custom post type pod, it uses meta-based storage
* `location` is a relationship field on the `review` pod, related to the `location` pod
* `country` is a custom field on the `location` pod

Can you verify?

**Comment by jamesgol** [comment]
I tried to reproduce this tonight and definitely received the same errors, I had just looked into a similar issue from the forums and couldn't find a bug but just a naming problem.

@Desertsnowman have you tried:
```
        "where" => array(
            array(
                "field"   => "location.country.meta_value",
                "value"   => "ZA",
                "compare" => "="
            )
        )
```

**Comment by sc0ttkclark** [comment]
Sounds like country is a simple relationship field using the states list, which indeed will need selecting .meta_value because location isn't a table-based Pod (or else it would be `location.d.country`)

**Comment by Desertsnowman** [comment]
@jamesgol yes I did try it. still failed but created a new join the went even more wonky

**Comment by Desertsnowman** [comment]
@sc0ttkclark not using the states list, its using a standard pod

**Comment by jamesgol** [comment]
When you say country is a "custom field" is it a releationship to a "Simple (custom defined list)"?  In my test (which worked) I had it setup like you said except country was a "Plain Text" field.  If so I'll give that a shot and see what I come up with.

**Comment by Desertsnowman** [comment]
@jamesgol I cant remember right now. I'll re do it quick and get you a proper test case

**Comment by Desertsnowman** [comment]
@jamesgol update- using meta_value does work, but it should be finding this automatically when using the .
I have kinda found the problem but am looking to confirm.

**Comment by sc0ttkclark** [comment]
Yes, it should find this automatically. The point of the array syntax is that it should not require prefix/affix like t. tt. d. or .meta_value -- so it's a bug.

**Comment by jamesgol** [comment]
Definitely a bug.  Glad to have dug into this, never knew that it shouldn't require the prefixes.  More fun stuff to play with

**Comment by Shelob9** [comment]
punting to 2.5.2 for lack of unit tests.

**Comment by Shelob9** [comment]
@sc0ttkclark What would it take to make the tests reliable enough to merge or reject @jamesgol patch on this?

**Comment by mirluin** [comment]
I applied the patch and it fixed the SQL error I was getting before.
Thanks @Shelob9 for pointing me in the right direction.

**Comment by sc0ttkclark** [comment]
Currently, the code doesn't support auto-prefix/suffix when using related fields. So we'll have to treat this as an enhancement. I have unit tests running locally showing the problem as reproducible, so now it's just a matter of adding the functionality via #3033
