### ISSUE TITLE
Three forms on one page

### ISSUE THREAD

**Issue by andre2** [pods-framework/pods#2584]
Is option add two forms on one page and next display all two forms on created page?
I created two forms but i can't display forms vales, forms must have edit option

is option to submit two forms after click submit button?
my code:

	<?php 

		// Fields
		$array = array(
			'first',
			'second',
			'third',
			'last',
		); 

		// Set type
		$type = 'first';

		// Create object
		if (pods_v_sanitized( 'edit', 'post', false, true ) ) {
			$form = pods($type,pods_v_sanitized( 'edit', 'post', false, true ) );
		} else {
			$form = pods($type);
		}

		// Print
		echo $form->form($array, 'Dodaj', site_url("add/?success=X_ID_X")); 

	?>

and next form

	<?php 

		// Fields
		$array = array(
			'name',
			'surname',
			'mail',
			'phone',
		); 

		// Set type
		$type = 'second';

		// Create object
		if ( pods_v_sanitized( 'edit', 'post', false, true ) ) {
			$form = pods($type, pods_v_sanitized( 'edit', 'post', false, true ) );
		} else {
			$form = pods($type);
		}

		// Print
		echo $form->form($array, 'Dodaj', site_url("add/?success=X_ID_X")); 

	?>

**Comment by Shelob9** [comment]
NOTE: I changed your code to use `pods_v_sanitized()` to get the POST variable, which I would recommend.

There is nothing in Pods that support this. That said, you can, using the jQuery submit function make one form's submission trigger another form's submission (demo here http://jsfiddle.net/shelob9/pe3tvdyk/).

That said, I have no idea what will happen on the AJAX side when you submit both forms at once, but you should try it and see what happens. If not, I can think of some workarounds, but they are not particularly simple, though the Gravity Forms or Caldera Forms processors for Pods might also be an easier option.

**Comment by andre2** [comment]
Ok, thanks, i want use pods becouse i have 2 forms to create custom post type from front.
First is public second is private
