### ISSUE TITLE
Possible Issue with pods_api->delete_field()

### ISSUE THREAD

**Issue by ckpicker** [pods-framework/pods#2593]
I'm always getting 'Field not found' when using this function.  I think there's a bug here: https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L4549

Here's the code I'm using: https://gist.github.com/ckpicker/8eae792e7a5f2058ad6b

Any issues with that?

**Comment by Shelob9** [comment]
@ckpicker Have you confirmed that you have the right ID on L20 (https://gist.github.com/ckpicker/8eae792e7a5f2058ad6b#file-gistfile1-txt-L20)?

**Comment by ckpicker** [comment]
This is what I'm seeing when I output the $params:  http://drops.caseypicker.com/DFsA

This is what I'm seeing in pods: http://drops.caseypicker.com/DFsC

**Comment by Shelob9** [comment]
I tried, and even with the pod_id in there, it doesn't work:

```php
   $field_id = 527;
   $pod_name = 'xc';
   
   $pod_api_object = pods_api();
   
   $params = array(
       'pod'  =>  'xc',
       'name' => 'email',
       'id' => 527,
       'pod_id' => 521
   );
   
   $result = $pod_api_object->delete_field( $params );
   var_dump( $result );
```

Reclassifying as a regression, though @sc0ttkclark might say why we are both wrong.

**Comment by ckpicker** [comment]
Thanks for confirming.  After clearing transients and changing line 4549 to the following, I was able to get it to work:

```
$field = $this->load_field( array( 'name' => $params->name, 'id' => $params->id, 'pod' => $params->pod, 'pod_id' => $params->pod_id ) );
```

**Comment by Shelob9** [comment]
@ckpicker I'm glad to see that you've found a solution. Can you submit a PR for this please?

**Comment by ckpicker** [comment]
Done: https://github.com/pods-framework/pods/pull/2595
