### ISSUE TITLE
Submit error

### ISSUE THREAD

**Issue by andre2** [pods-framework/pods#2605]
Hello, 

In latest version not work submiting form, after submit i has been redirected to succes page "my-page/?success=NaN"

Version 2.5

    <?php 

        $array = array(
            'name',
            'surname',
            'mail',
            'phone',
        ); 

        $type = 'second';

        if ( pods_v_sanitized( 'edit', 'post', false, true ) ) {
            $form = pods($type, pods_v_sanitized( 'edit', 'post', false, true ) );
        } else {
            $form = pods($type);
        }

        echo $form->form($array, 'Submit post', site_url("add/?success=X_ID_X")); 

    ?>

before update all works

**Comment by QsmaPL** [comment]
Alert with message about required fields not works too.

**Comment by Shelob9** [comment]
@andre2 and @QsmaPL can you please check your JavaScript consoles and report what the errors are that you are seeing?

**Comment by andre2** [comment]
@Shelob9 my console is without errors :/

ps.
how i can get data?
I use this shortcode: do_shortcode("[pods id='get_the_ID()' name='get_post_type()']{@name}[/pods]
How i can get this only with php?

**Comment by sc0ttkclark** [comment]
I don't want to sound crazy here, but couldn't you just use `<?php the_title(); ?>`?

**Comment by andre2** [comment]
nope, i have a lots of custom fields ;)

**Comment by sc0ttkclark** [comment]
```php
$pods = pods(); // This will auto-fill with current post type and post ID

echo $pods->display( 'post_title' );
echo $pods->display( 'custom_field_here' );
```

**Comment by andre2** [comment]
Thanks @sc0ttkclark , i add this

    $get = pods(get_post_type(), get_the_ID());

becouse without params not works in while loop, thanks!

**Comment by sc0ttkclark** [comment]
If you are looping through a bunch of the same post type, this would be more optimal:

```php
$pods = pods( get_post_type() );

// in your loop

$pods->fetch( get_the_ID() );
// your code

// end of loop
```
