### ISSUE TITLE
find() and taxonomy custom field error

### ISSUE THREAD

**Issue by paoloimpelluso** [pods-framework/pods#2607]
With the release of pods 2.5 i've faced an error tha was precedently discussed and solved.

When, in find() arguments, i ask for records with a particular value in a tax custom field i get this error: Unknown column 'custom_tax.related_item_id' in 'on clause'

Everything was fine with version 2.4.3

Code: 
find( array( "where" => " custom_tax.d.custom_field = 'value' " ) )

WordPress Version: 4.1
PHP Version: 5.5.9-1ubuntu4.5
MySQL Version: 5.5.40
Server Software: Apache/2.4.7
Session Save Path: /var/lib/php5
Session Save Path Exists: Yes
Session Save Path Writeable: Yes

**Comment by quasel** [comment]
did you try a cache reset? - had a similar issue after update - cache reset to the rescue

**Comment by paoloimpelluso** [comment]
yes, i've tried to do "Clear Pods Cache" .. but with no luck!

**Comment by sc0ttkclark** [comment]
This is one of the cases we have in our unit test, can you clarify a few things?

* Is this a custom taxonomy added by Pods or extended?
* Do you have the Table Storage component enabled for Pods?
* Can you provide the actual code you're using?

**Comment by paoloimpelluso** [comment]
Hi Scott,
here we are:

- this is a custom tax added by pods with (obviously) extra fields enabled
- table storage ON

Code:

        $params = array(
                    'limit'	 => 21,
                    'pagination' => true,
                    'page'	 => $page,
                    'orderby'	 => "post_date DESC",
                    'where' =>  "1 AND boat_cmp.d.length >=10.00"
                    );
        
        $boat = pods("boat",$params);

**Comment by paoloimpelluso** [comment]
if you can give me a private email address, i can also provide the whole sql error

**Comment by jamesgol** [comment]
I wasn't able to replicate this error at all on my setup, I tried to replicate your setup as best as possible.

Do you have any external caching (xcache, memcached, etc.) enabled?

**Comment by paoloimpelluso** [comment]
Hi, do you mean that the query is working for you?
No external caching enabled ... if you have a private address, i can send you the url of the site ...

It seems to me that there is a problem in sql, when asking for extra field in taxonomy ...

**Comment by paoloimpelluso** [comment]
to clarify my setup, there are 2 elements involved:
- boat: custom post type
- boat_cmp: custom tax with extra fields

Everything is fine, except when i run find() for a value in tax extra fileds (see code above).

**Comment by jamesgol** [comment]
Yes the query worked for me.  You can email me at james@gnuinter.net

I set it up exactly how I deduced your setup.  boat as a custom post type, and boat_cmp as a custom taxonomy with extra fields (I only added a length field as a number) and a relationship from boat to boat_cmp.

Are you sure there isn't memcached, APC, or xcache running on there?

**Comment by paoloimpelluso** [comment]
Hi James,
sorry but ... APC is enabled for this website! ... i'm using w3tc plugin with apc object cache enabled.
Anyway i tried to empty APC cache (via plugin setting page) and the error is still there ... 

Regarding the setup, the only difference is that boat_cmp is not a relationship, but it is a Built-in Taxonomies associated to cpt via PODS configuration page

**Comment by paoloimpelluso** [comment]
i've just sent you an email.

thanks, Paolo

**Comment by jamesgol** [comment]
I switched my test to having the taxonomy associated with the CPT and get the same error on 2.5 as well as 2.4.3.  This definitely worked on 2.4.3 before?

**Comment by paoloimpelluso** [comment]
yes it worked!
you can see the website working here (2.4.3 installed): http://www.mediaship.it/cerco/
You can repeat the same test i've just emailed to you.

thanks again,
Paolo

**Comment by jamesgol** [comment]
Ok after some playing around I think I've got your setup simulated locally.  It works on 2.4.3 and is failing on 2.5 with the same error (related to a join).  I'll have some time later to look into it more

**Comment by jamesgol** [comment]
Bug was introduced by fix for bug #2398

**Comment by sc0ttkclark** [comment]
@jamesgol isn't this unit test passing though?

**Comment by jamesgol** [comment]
@sc0ttkclark: I'm not sure if this exact situation is covered by the unit tests.  The difference between this case and the #2398 case from what I can see is that here the table based taxonomy is associated with the pod where in #2398 the table based taxonomy was setup as a relationship.

I've come up with a hack that makes both cases work and passes the unit tests, but I want to keep digging to see if there is a proper fix for it.
