### ISSUE TITLE
URL Variables not passing through

### ISSUE THREAD

**Issue by MrWebslinger** [pods-framework/pods#2609]
After moving my site from GoDaddy to Bluehost, my code stopped working.  I was pulling a variable from the URL and now, all URL Variables are ignored.  This is only an issue on pages with Pod code on it.

For this url
http://example.com/?var1=red&var2=blue

$thisurl = get_current_url(); returns http://example.com/
$_SERVER[“REQUEST_URI”]; returns http://example.com/
echo var_dump($_GET); returns array {}

Every way I have tried to pull the URL Variable has failed.  

(GoDaddy) PHP Version:5.3.24 works.
(Bluehost) PHP Version:5.4.28 does not work

**Comment by Shelob9** [comment]
@MrWebslinger What value do you get for `pods_v_sanitized( 'var1' )` for that URL string?

**Comment by MrWebslinger** [comment]
That comes back blank.

**Comment by Shelob9** [comment]
And it works when not on a Pods Page?

How are you testing this?

**Comment by MrWebslinger** [comment]
Yes, I have tested it on a non-pods page and it works fine.

echo $myvar = $_GET['var1']; returns the correct value on those pages.

**Comment by Shelob9** [comment]
What about `pods_v_sanitized( 'var1' )`

Can you please explain to me your testing methods for this, or explain how the problem is manifesting itself in the Pods Pages? I'm not sure how to help you when it is this abstract.

**Comment by sc0ttkclark** [comment]
This sounds like a deeper issue, we don't override $_GET with an empty array at any point in the Pods code.

What other plugins / theme do you have active on the site?

**Comment by MrWebslinger** [comment]
The way I was testing this is I was pulling the URL on a standard page by using:
$thisurl = getCurrentURL(); and then writing the value to the console.  It always worked but ignorantly, I was using ?test=1 instead of my actual variable ?eid=100 or whatever.  Apparently when I use ?eid=100 on the non-pod pages, it doesn't work either.  Very odd.  This is all working fine on my GoDaddy dev site but not working on the Bluehost site.  The only difference being, the PHP version.  Everything else was copied as-is.

**Comment by Shelob9** [comment]
What is `getCurrentURL()`?

Also, are you running this code in the Pods Pages, page code or pre-code fields, which is deprecated, or in a WordPress page template, or Pods Template, or in a function hooked to a filter such as `the_content` or `pods_content`?

**Comment by MrWebslinger** [comment]
Sorry, that was a function that parsed the URL that I had found online.

I think by you having me go deeper on my testing, I have found the we solution.  Apparently it was the url "eid" variable that was not pulling in but all others work so I renamed the variable and I am good.

Whew, talk about a lot of wasted hours.  Sorry for the false alarm and believe it or not, this just made my day.

**Comment by Shelob9** [comment]
@MrWebslinger No worries.

BTW Take a look at `pods_current_url()`

**Comment by MrWebslinger** [comment]
Will do, thanks again.  I was beating my head against the wall for the last 2 days.
