### ISSUE TITLE
Calling display('field') on built-in taxonomy not returning value(s), worked in 2.4

### ISSUE THREAD

**Issue by maarten00** [pods-framework/pods#2611]
I have a pod with two built-in taxonomies enabled. In pods 2.4 I was able to retrieve the selected value(s) with $pod->display('field') or get_field('field'). In Pods 2.5 this no longer seems to work. If I revert my plugin back to 2.4 it works again.

I have tried debugging the issue myself. From what I have gathered the issue is not with the display() or field() function, but with the pods() call itself. It does not seem to gather the data for built in taxonomies.

**Comment by sc0ttkclark** [comment]
Have you cleared your cache via Pods Admin > Settings > Clear Pods Cache?

Can you also clarify whether you created or extended the taxonomies with Pods, or are you trying to call `pods( 'taxonomy_name' )` for a non-Pod that's just an existing taxonomy?

**Comment by maarten00** [comment]
Heh, I just found [https://github.com/pods-framework/pods/issues/2558](this issue) and tried clearing the cache, that has resolved the problem for me. 

Both taxonomies were created with pods, one of them is extended with custom fields. Neither of them were showing data prior to clearing the cache.

**Comment by sc0ttkclark** [comment]
Yeah we are seeking a solution for Pods 2.5.1 to get around this cache clearing problem. Sorry for the inconvenience, glad it's all working now for you.

**Comment by sc0ttkclark** [comment]
#2558
