### ISSUE TITLE
Boolean field passed as array, not string using {@field_name,function} notation in Pods Template

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2614]
I need to do more research on this, but I am currently trying to do `{@boolean_field,esc_attr}` or `{@boolean_field,strtolower}` in a Pods Template and get an array to string conversion error. The trace shows an array is being passed to the callback function.

**Comment by jamesgol** [comment]
I wasn't able to reproduce this, I tried just using the magic tags in a shortcode from a WP Page as well as from a Pods template.  I'm sure my test must be setup differently than yours.

**Comment by sc0ttkclark** [comment]
I wonder.. if you used a custom field and you gave the wrong field name (typo), it's possible it passed an array.

**Comment by jamesgol** [comment]
Using an invalid field name does return Array on esc_attr and on strtolower I get the backtrace.

Here is my test output/code.  bool1 is valid and false, bool2 is valid and true, bool3 field does not exist

```
bool1: No
bool1, esc_attr: 0 
bool1, strtolower: 0
bool2: Yes
bool2, esc_attr: 1 
bool2, strtolower: 1
bool3: 
bool3, esc_attr: Array 
bool3, strtolower: 
```

```
bool1: {@bool1}<br/>
bool1, esc_attr: {@bool1,esc_attr} <br/>
bool1, strtolower: {@bool1,strtolower}<br/>
bool2: {@bool2}<br/>
bool2, esc_attr: {@bool2,esc_attr} <br/>
bool2, strtolower: {@bool2,strtolower}<br/>
bool3: {@bool3}<br/>
bool3, esc_attr: {@bool3,esc_attr} <br/>
bool3, strtolower: {@bool3,strtolower}<br/>
```

**Comment by jamesgol** [comment]
On an invalid field
$value = $this->field( $field_name );
is returning an empty array.  Which to me suggests a bug in field.  Since it should be returning null if the field doesn't exist (according to the phpdoc).

I'll dig into it a bit more

**Comment by sc0ttkclark** [comment]
When it's a custom field for a field that we don't cover, we don't know what field type it is, and it's a custom field value returned by get_post_meta or whatever meta function we're using. We just return it.

**Comment by jamesgol** [comment]
After walking through the code I see that.  get_post_meta is returning an empty array (or would be '' if $single is true).  Too bad WordPress's get_metadata doesn't return something more useful if nothing is set.

Should the docs for field get updated then?

**Comment by quasel** [comment]
If I understand this correctly the original issue couldn't be reproduced and the Rest is just how WP works!
