### ISSUE TITLE
Use Icon Font For Pods Logo

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2617]
#2615 was an initial pass, but it is not working so far.

**Comment by ghost1227** [comment]
Test all PRs before you merge ;) However.... Works for me (tm). What is it doing for you? Can you post a screenshot or similar of the issue?

**Comment by Shelob9** [comment]
It's showing the default admin gear dashicon `dashicons-admin-generic`

**Comment by ghost1227** [comment]
Strange... lemme check something

**Comment by ghost1227** [comment]
Nope, even using 2.x post merge, it's working fine on my dev site... Can you verify that it's actually loading the pods-font css file on your site?

**Comment by Shelob9** [comment]
The CSS is being loaded fine. I'm testing in Chrome for Mac OS, regular release channel.

James also doesn't see it.

**Comment by ghost1227** [comment]
I've tested on Chrome and FF, but stable release on Yosemite... works fine for me. I can't duplicate your bug anywhere... caching issue?
