### ISSUE TITLE
Load language

### ISSUE THREAD

**Issue by andre2** [pods-framework/pods#2625]
Hello,

How i can add my lanugage,
I added define('WPLANG', 'pl_PL'); to config and add my language with small changes, but this not work for me :/

In form i see english error messages.

I use version 2.4.3

**Comment by pavelevap** [comment]
It seems to me that `pl_PL.mo` file is empty and `pl_PL.po` does not contain anything translated.

When you edit localization file, do not forget to compile `pl_PL.mo` file. How did you edit language files?

**Comment by andre2** [comment]
I have file pl_PL.mo and file pl_PL.po but i translate only needed lines.
But this not work for me :/

**Comment by sc0ttkclark** [comment]
Our translations are managed here:

http://wp-translate.org/projects/pods/pl/pl_PL

**Comment by Shelob9** [comment]
@andre2 As @pavelevap points out, editing the po file is not enough. You must compile the changes.

Since we manage translations on http://wp-translate.org/ we will not accept pull requests for translations here. Instead, send Scott (Scott@pods.io) your wp-translate.org username and he can add you as a translator, and the changes will be included in our next version.

**Comment by andre2** [comment]
@Shelob9 
Okey, i want translate only 3 lines, but when i try load translated and generate files mo and po not work, i don't see changes..

I want translate only line:

%field% is required

**Comment by Shelob9** [comment]
@andre2 We'd love to have your help with translations, even if it is only three lines, every little bit helps, but it has to be done via wp-translate.org

**Comment by andre2** [comment]
@Shelob9 okey ;)

**Comment by Shelob9** [comment]
The easiest way would be to get your changes into wp-translate.org, then use it to generate the .mo file for you and hotfix it in your local install until the next release. 

Another option is to use this plugin, which makes this sort of thing really easy, but then no one else gets your changes:
https://wordpress.org/plugins/codestyling-localization/

**Comment by andre2** [comment]
@Shelob9 okey, i added 121 translations to wp-translate.org, waiting for confirmation.
And what next? when i add exported files as mo and po from wp-translate.org i don't see translated text on my wordpress page, i use version 2.4.3.

On my front end form i see english errors for example : E-mail is required
Can you help me?

**Comment by Shelob9** [comment]
@andre2 Thank you for doing that. When we build a new release of Pods, we pull the translations from there, so what you've done will show up in Pods 2.5.1.

**Comment by andre2** [comment]
Okey, how i can use this translations? because after upload to my server this doesn't work :-1:

**Comment by Shelob9** [comment]
@andre2 2.5.1 should be out tomorrow. Why not just wait and update. Any changes you put into wp-translate.org before tonight will be in that release.

As far as hotfixing translation files in your own download goes, I've never done it. That's a question that is better asked in a general WordPress support forum.
