### ISSUE TITLE
Pods Requirements

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#2634]
Is this posted anywhere?  If not, can we have updated required/suggested configuration posted on github or pods.io?

Thanks!

**Comment by Shelob9** [comment]
@cspicuzza What type of requirements or suggestions exactly are you looking for that isn't in readme.txt?

**Comment by sc0ttkclark** [comment]
@cspicuzza you're going to need PHP

**Comment by sc0ttkclark** [comment]
:)

**Comment by sc0ttkclark** [comment]
* PHP 5.2.4+ (PHP 5.3+ officially tested, PHP 5.4+ recommended)
* MySQL 5.0+
* WP 3.8+

**Comment by sc0ttkclark** [comment]
@Shelob9 i don't think this is in readme.txt, but should be added, also added to README.md. It may be on our site too, but we should update there as well (and include the additional notes on tested/recommended).

**Comment by cspicuzza** [comment]
I only brought this up because recently I upgraded to 2.5 and the php version was too old causing havok.   Quakers...

**Comment by sc0ttkclark** [comment]
Yeah technically we support PHP 5.2.4+ but there was that fatal that snuck in, since unit tests require 5.3+ to run (we didn't see it, because we don't actually run old PHP versions for giggles). That's been patched in Pods 2.5.1 though, which is just now out :)

**Comment by jimtrue** [comment]
@sc0ttkclark We don't actually note this anywhere. Should this be in the GitHub readme.md and in our FAQ for WordPress Plugins as Minimum PHP, MySQL and WordPress requirements (and perhaps Minimum RAM configuration?)
