### ISSUE TITLE
/wp-json and all endpoints 404 after updating Pods.

### ISSUE THREAD

**Issue by mj-interactive** [pods-framework/pods#2642]
Pods JSON API is throwing 404 error on all my existing pods. Please help! Can I restore the old version?

**Comment by Shelob9** [comment]
@mj-interactive I can reproduce this, but resaving my permalinks resolves it. Please try that and see if it resolves it for you.

**Comment by Shelob9** [comment]
I can confirm this, when updating to 2.5.1.1 all REST API routes 404, but flushing rewrites fixes the issue. I'm pretty sure that having Pods JSON API active is irrelevant and issue is Pods + REST API, but not positive.

**Comment by mj-interactive** [comment]
That did work! Thanks again, Josh!

**Comment by Shelob9** [comment]
Closing via PR #2644
