### ISSUE TITLE
Automate release process in 3.0

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2649]
Everything in #2648
Plus: dependencies

**Comment by Shelob9** [comment]
Since we are going to have dependancies of at least cmb2, this process will need to be run more often than just releases, so we will need an alpha/beta task that doesn't push to SVN, but pushes a new zip file to pods.io/latest

**Comment by szepeviktor** [comment]
Pod 3 will depend on cmb2?

**Comment by Shelob9** [comment]
@szepeviktor Yes Pods 3.0 and later will use CMB2.

**Comment by szepeviktor** [comment]
That tells me that CMB2 is better written as Pods - at least in regards of custom fields.

**Comment by sc0ttkclark** [comment]
Pods is incorporating CMB2 because we want to *share* the burden of code, rather than carry the burden of our own code forever. Shared burden allows both of our teams to improve CMB2 for the greater good, and reduces overall bugs and CMB2 has unit tests.

**Comment by sc0ttkclark** [comment]
CMB2 is just forms, it doesn't come with data storage options or everything Pods was built to be. We're merely replacing our WP forms integrations with CMB2.
