### ISSUE TITLE
oEmbeds not showing up using a Pods field

### ISSUE THREAD

**Issue by schikulski** [pods-framework/pods#2650]
Have a custom article field in my post type that sucessfully show oembeds in visual editor, but not in the actuall post. I've tried a few things, and it seems that ```[embed]youtube.com/example[/embed]``` works fine, with ```apply_filters('the_content', $pods_field)``` added. But using just the URL shows only the URL in the post. 

Wordpress 4.1
Pods 2.5.1.1

**Comment by Shelob9** [comment]
Is this custom article field a WYSIWYG field? If so, under the additional options tab for the field, you can enable oEmbed support.

**Comment by schikulski** [comment]
Ah, that was easy. Didn't know about that setting. Thanks @Shelob9!
