### ISSUE TITLE
Bulk edit for pods

### ISSUE THREAD

**Issue by andybridges** [pods-framework/pods#2651]
Hi,

I've recently just imported from a .csv file to my new site using the following plugin - https://wordpress.org/plugins/csv-importer-for-pods/. I was wondering if there is an easier way to do a bulk edit on each of the new posts and assign them to a blog type (custom pod). I'm really hoping I don't have to go through each article and assign individually.

Any help would be greatly appreciated.

Thanks

Andy

**Comment by Shelob9** [comment]
Andy-

This shouldn't have been necessary, as they should have been properly assigned on import.

Now that they exist and you do have this issue, I would use this plugin to fix it:

https://wordpress.org/plugins/post-type-switcher/

**Comment by andybridges** [comment]
That’s great, thank you very much for the help. 

I’m hoping you can help me on another issue I have just encountered…

I’ve just followed the instructions on this article to create a archive filter - http://pods.io/docs/code/pods/filters/ <http://pods.io/docs/code/pods/filters/>

All seems to work pretty well apart from the text search keeps returning the following notice:

Notice: like_escape is deprecated since version 4.0! Use wpdb::esc_like() instead. in /Applications/MAMP/htdocs/sam/wp-includes/functions.phpon line 3378

Any help would be ace!

Thanks


Andy Bridges
Interactive Developer | Like Digital Media
---------------------------------------------------------------------
Studio 57
The Old Truman Brewery
91 Brick Lane, London E1 6QL

Studio: 020 3603 7579 
Email: andy@likedigitalmedia.com <mailto:andy@likedigitalmedia.com>
Twitter: @likedigital
www.likedigitalmedia.com <http://www.likedigitalmedia.com/>

Making the internet look good since 2011
---------------------------------------------------------------------

**Comment by andybridges** [comment]
Also, If you were able to give me some insight as to how I could add a date filter to this search that would be great!


Andy Bridges
Interactive Developer | Like Digital Media
---------------------------------------------------------------------
Studio 57
The Old Truman Brewery
91 Brick Lane, London E1 6QL

Studio: 020 3603 7579 
Email: andy@likedigitalmedia.com <mailto:andy@likedigitalmedia.com>
Twitter: @likedigital
www.likedigitalmedia.com <http://www.likedigitalmedia.com/>

Making the internet look good since 2011
---------------------------------------------------------------------

**Comment by Shelob9** [comment]
What version numbers of Pods and WordPress are you running?

**Comment by andybridges** [comment]
Hi Josh,

I’m currently using version 2.4.3 of pods and wordpress version 4.1

Thanks


Andy Bridges
Interactive Developer | Like Digital Media
---------------------------------------------------------------------
Studio 57
The Old Truman Brewery
91 Brick Lane, London E1 6QL

Studio: 020 3603 7579 
Email: andy@likedigitalmedia.com <mailto:andy@likedigitalmedia.com>
Twitter: @likedigital
www.likedigitalmedia.com <http://www.likedigitalmedia.com/>

Making the internet look good since 2011
---------------------------------------------------------------------

**Comment by Shelob9** [comment]
Can you try again with Pods 2.5.1.1 please? It has a ton of bug fixes.

**Comment by andybridges** [comment]
Brilliant, fixed it instantly. 

Any idea on the search by date functionality? 

Thanks 

Andy Bridges
Interactive Developer | Like Digital Media
---------------------------------------------------------------------
Studio 57
The Old Truman Brewery
91 Brick Lane, London E1 6QL

Studio: 020 3603 7579 
Email: andy@likedigitalmedia.com <mailto:andy@likedigitalmedia.com>
Twitter: @likedigital
www.likedigitalmedia.com <http://www.likedigitalmedia.com/>

Making the internet look good since 2011
---------------------------------------------------------------------

**Comment by Shelob9** [comment]
Pods::filters() is very limited in what it can do, and adding a date filter is going to be very difficult. Instead use FacetWP, which besides many other great features lets you filter by date with range sliders.
