### ISSUE TITLE
Network paths on windows system gets stripped in PodsView::locate_template

### ISSUE THREAD

**Issue by cocoanton** [pods-framework/pods#2658]
Using Pods 2.5.1 on a clients windows server with WP4.1. 
They are using a network path as the real path.
This ends up being an problem when pods try to render the templates because locate_template strips the leading \\.

This is due to the replacement happening in the locate_template [function at row 576](https://github.com/pods-framework/pods/blob/master/classes/PodsView.php#L576)
I actually don't think these are necessary since realpath() already does the stripping and optimizing of the paths and the function should rely on that instead. Removing these two lines fixes the problem for my clients install. 

Is there any other reason these two replacements are done? Or should we just let realpath() do the lifting in that matter.

**Comment by sc0ttkclark** [comment]
Fixed via #2793 and #2795
