### ISSUE TITLE
In Pods "Post" type is displayed only!

### ISSUE THREAD

**Issue by AlexeyGonchar** [pods-framework/pods#2661]
Hi there! 

In Pods "Post" Type is displayed only,

but plugin "The Events Calendar" created three new post types, they are not displayed in "Pods" to add some templates.

Would you tell me please how to make it work correctly?

Thanks!

**Comment by Shelob9** [comment]
You must extend the post types added by this other plugin first.

You can do so by creating a new Pod and selecting "extend existing"

**Comment by AlexeyGonchar** [comment]
Hi, Shelob9!

Is there some manual for it?

**Comment by Shelob9** [comment]
http://pods.io/docs/build/how-to-extend-a-post-type/

**Comment by AlexeyGonchar** [comment]
Shelob9, thank you very much for great help!

**Comment by Shelob9** [comment]
@AlexeyGonchar Your welcome. Please let us know if there is anything else we can do to help in the future, here, in our [forums](http://pods.io/forums/forums) or our [chat](http://pods.io/forums/chat/)
