### ISSUE TITLE
CodeMirror fields won't save

### ISSUE THREAD

**Issue by jamesgol** [pods-framework/pods#2665]
Can't reproduce on CPT for some odd reason, but on ACT codemirror field isn't saved.

Looks like CodeMirror dropped the 'onBlur' at 3.0

PR coming

**Comment by sc0ttkclark** [comment]
Closed by #2666

**Comment by cspicuzza** [comment]
I upgraded a multisite to 2.5.1.2 and noticed the CodeMirror fields still are not saving.  Was this fix included with that release?

**Comment by sc0ttkclark** [comment]
No it's in Pods 2.5.2 http://pods.io/latest/

**Comment by cspicuzza** [comment]
I probably should of picked up on that... woops.  Thanks!
