### ISSUE TITLE
orderby field problem

### ISSUE THREAD

**Issue by AecrimRO** [pods-framework/pods#2679]
Hello. I want to sort the pod items by a field.

The field it is numeric / currency.

I have 18 items. The orderby function it is working but only / row

eg.
5.16   5.50   6
4   8.15   10

I want to sort them in the normal way

4   5.16    5.50    6    8.15   10

I used this:

$params = array(
       'limit' => -1,
       'orderby' => 'CAST(price_1000.meta_value  AS DECIMAL) ASC',
	   );
	   
$mypod = pods('products', $params );

The field is price_1000 and it supposed to be used to filter the items by the lowest price.

It is a catalog with pormotional items and we have multiple prices based on quantity.

What I can do?

Regards, Mircea

**Comment by jimtrue** [comment]
The declaration syntax for a DECIMAL column is DECIMAL(M,D). The ranges of values for the arguments in MySQL 5.1 are as follows:

M is the maximum number of digits (the precision). It has a range of 1 to 65. (Older versions of MySQL permitted a range of 1 to 254.)

D is the number of digits to the right of the decimal point (the scale). It has a range of 0 to 30 and must be no larger than M.

You may need to do add (16,2) behind the DECIMAL to get it to recognize., ie:

'CAST(price_1000.meta_value AS DECIMAL(16,2)) ASC'

**Comment by AecrimRO** [comment]
Thank you very much Jim.

It is working.

Have a good day.
