### ISSUE TITLE
Missing _e()s and __() in ui/admin/settings-reset.php

### ISSUE THREAD

**Issue by NikV** [pods-framework/pods#2690]
A few missing _e()s and stuff

**Comment by NikV** [comment]
Patched Here: https://github.com/pods-framework/pods/pull/2691

**Comment by Shelob9** [comment]
@nikv Can you please be more descriptive of the issue? Please explain which methods or line numbers you are concerned about.

**Comment by NikV** [comment]
Sure, this is for the reset weekend section. Line 109-115. Just adds new things that can be translated.

**Comment by NikV** [comment]
Old patch had a git problem, new one created: https://github.com/pods-framework/pods/pull/2702
