### ISSUE TITLE
Make Sure Existing Pods From 2.X Go Into A Default Group

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2709]
"i think we should save the group when they go to the Pod editor" - @sc0ttkclark

I think existing fields should go in group 0 by default.

**Comment by sc0ttkclark** [comment]
This was done this past weekend:

- [x] When you go to the pod edit screen for the first time, a new first group is created and all of your fields are moved into that group. It uses the "More Fields" label with same filter we had for forms for customization -- so if they customized it, it will be saved to the real group as customized.
- [x] When you go to any form before going to the pod edit screen, if the pod has no groups, it will continue to use the faux group "More Fields" (with label filter as before).
