### ISSUE TITLE
Display pods assigned by the logged user

### ISSUE THREAD

**Issue by AecrimRO** [pods-framework/pods#2732]
Hello,

I am trying to create a kind of directory where my users can add their listings.

How can I display in a page template just the items added by logged in user.

Eg. User A submited 3 listings , when user click on the menu My listings he can see only the listings that he added.

Regards, Mircea

**Comment by Shelob9** [comment]
@AecrimRO 

I'm assuming you have a post type Pod called 'listing'. If your post type is set to support post author, then you can use `Pods::find()` to query by post_author. That means that you can construct a query based on post_author, using the current user's ID. Something like this:

```
	$id = get_current_user_id();
	if ( $id ) {
		$params = array(
			'where' => 't.post_author = "'.$id.'"',
		);
		$pods = pods( 'listing', $params );
	}
```

You might also want to check out a plugin I co-wrote, Caldera Easy Pods that gives you a visual query builder that can use dynamic values such as current user ID in the query. See: https://calderawp.com/doc/using-magic-tags-in-caldera-easy-pods-queries/

**Comment by AecrimRO** [comment]
It is working. Thank you!

**Comment by Shelob9** [comment]
@AecrimRO Awesome. Glad to hear.
