### ISSUE TITLE
Manage 3rd party script dependencies using Bower (right Bower not Grunt?)

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2733]
@sc0ttkclark  Do we need anything besides select2 and codemirror at this point?

@shelob9 You can automate Bower with Grunt right?

**Comment by sc0ttkclark** [comment]
There are others we're using, check ui/js

**Comment by sc0ttkclark** [comment]
https://github.com/rackt/redux/issues/944#issuecomment-154858804
