### ISSUE TITLE
Adding a new field group goes back to pods editor.

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2735]

**Comment by jamesgol** [comment]
I ran into this and started looking into it but it wasn't exactly clear to me what the intended path was supposed to be.  I bet @sc0ttkclark can fix it quick, otherwise it'll probably take me a while to dig through and find whats broke

**Comment by sc0ttkclark** [comment]
Adding an item should always go to edit, editing an item should always stay in edit, deleting an item should always go to manage of the next level up.

**Comment by jamesgol** [comment]
I'm definitely not going to merge the fix to this, I want someone else who knows the code better to do it.

**Comment by Shelob9** [comment]
@jamesgol I'm merging it since it works for me and I need this work for further dev/testing. If you missed something we can get it later.
