### ISSUE TITLE
pods_register_related_object stopped working with 2.5

### ISSUE THREAD

**Issue by mpsteel** [pods-framework/pods#2737]
I posted on the pods.io forum but someone mentioned I try posting here as well. Here's my initial post:
http://pods.io/forums/topic/ok-pods_register_related_object-really-not-working-at-2-5-1-1/#post-189173

I’m dealing with a bug that is extremely weird, among the most frustrating I’ve encountered.

When I say bug, I don’t mean Pods offhand, my system is complicated, but what I do know is if I roll back Pods to 2.4.4-alpha or even 2.4.3 my custom object pick select lists are populated.

Here’s where it gets weird. If I swap out 2.4.3 for 2.5 (or 2.5.1.1) and refresh the page the pick objects continue to work and are populated. Refresh after refresh, no problem… until I clear the Pods cache, then the lists won’t populate.

I’ve traced this down a lot into the code. In /pods/classes/fields/pick.php PodsField_Pick::register_related_object() if I dump put $related_object after the array merge my data for the list is there. It seems to get lost however somewhere with the handling of self::$custom_related_objects.

Is there anything you can tell me offhand what might be causing this? Anything that changed between 2.4.3 and 2.5 that might cause this kind of behavior?

I know this is crazy, I’ve been working on resolving this for days, any help would be greatly appreciated. 

Thanks,

-Marc

**Comment by jamesgol** [comment]
Will get a PR in for this soon

**Comment by quasel** [comment]
the link to the code from @mpsteel @slack - http://pastebin.com/yZbpD6T0

**Comment by jamesgol** [comment]
@quasel Thanks for sticking that link in here.  Always good to have as much documentation in an issue as possible.

**Comment by jamesgol** [comment]
@mpsteel The solution I gave you to call setup_related_objects( true ), isn't an efficient one.  It will cause more DB queries than are needed.  If you could test out the branch and confirm it works for you that would be great.

**Comment by mpsteel** [comment]
I'd be happy to, are you referring just to the change found here?
https://github.com/pods-framework/pods/pull/2739/files

**Comment by mpsteel** [comment]
Well, I placed in the file and it worked! Thanks so much.

**Comment by jamesgol** [comment]
@mpstel Thanks for testing, sorry I couldn't get back to you earlier.  It worked in my tests so I was pretty sure it would work for you, but always good to have additional testers.

**Comment by Shelob9** [comment]
Closing as fixed via PR #2739
