### ISSUE TITLE
ACT not saving plain paragraph text, plain text, wysiwyg, or code (syntax highlighting) fields after upgrade

### ISSUE THREAD

**Issue by c0rnbread** [pods-framework/pods#2751]
Here's my debug information. Please help!

WordPress Version: 4.0.1

PHP Version: 5.5.9-1ubuntu4.5

MySQL Version: 5.5.40

Server Software: nginx/1.4.6

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

Session Save Path: /var/lib/php5

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/nwmarine/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: BASE THEME

Currently Active Plugins:

Admin Columns: 2.3.3
Contact Form 7: 4.1
Database Sync: 0.4
Google Analytics Dashboard for WP: 4.4.6
Pods - Custom Content Types and Fields: 2.5.1.1
Simple Login Log: 1.1.0
uSquare: 1.6.5
WP Mobile Detect: 1.2.0

**Comment by c0rnbread** [comment]
If the field is required, the entry will not save at all.

I've tried clearing the Pods Cache, recreating the field, recreating the Pod, and upgrading all plugins.

**Comment by Shelob9** [comment]
Have you tired disabling all other plugins and switching to the default theme?

**Comment by c0rnbread** [comment]
Yep

**Comment by c0rnbread** [comment]
I downgraded to Pods 2.4.3 and the issue went away.

**Comment by c0rnbread** [comment]
So here's steps to reproduce the issue:

1. Create a new ACT called Videos
2. Create a code (syntax highlighting) field
3. Create a new Video
4. Enter some embed code in the code field
5. Save the new VIdeo

Once you save the new Video, you should see an error message that says "Error: Pod not found"

**Comment by Shelob9** [comment]
Does removing the code syntax field from your Pod help? We have had some issues with that field.

**Comment by c0rnbread** [comment]
I tried using a plain paragraph text field, plain text field, and a wysiwyg
field. All produced the same results.

**Comment by pglewis** [comment]
This report goes back a while.  I haven't seen this behavior while testing various other ACT issues, so is this still happening for you on 2.5.2 and/or 2.x, @c0rnbread?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
