### ISSUE TITLE
Delete Not Working for Edit Items

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#2752]
When editing an item, the delete link in the right sidebar does not seem to be working. Tested with default TwentyFifteen theme. It takes you back to list screen, but the item you just deleted remains.

![delete](https://cloud.githubusercontent.com/assets/2176348/6311234/ded79b18-b92d-11e4-9048-54a2f6c1fc63.jpg)

**Comment by andymakesglasses** [comment]
I just came here to post about the same issue. Deleting from the list screen does work but deleting from the item edit screen doesn't.

**Comment by Shelob9** [comment]
@pglewis I'm assigning to you as I assume this is related to overescaped URLs.

**Comment by jimtrue** [comment]
I can verify the activity as well, only on ACT's. ACT's 'Delete!' like the Cybermen; CPT's 'trash'.

**Comment by pglewis** [comment]
We had a missing nonce
