### ISSUE TITLE
Template traversal with magic_tags for file attachments not working (ACT)

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#2755]
given an ACT with a pdf-file attachment field:
if i use the pod itself  {@attachment}  it gives me the URL - http://mq.just4us.eu/wp-content/uploads/2015/02/attachment.pdf
in a related pod -  {@pod_rel.attachment} or {@pod_rel.attachment._src}  - it doesnt work.

**Comment by Shelob9** [comment]
Does `{@pod_rel.attachment}` give you the ID? If so, you could use `{@pod_rel.attachment,wp_get_attachment_url}`

**Comment by quasel** [comment]
the weird thing it returns nothing on the Site ...

**Comment by quasel** [comment]
had a conversation with @Shelob9 -  
```var_dump(  $pods->field('pod_rel.attachment') )``` and ```var_dump(  $pods->field('attachment') )``` works 
```{@pod_rel.attachment},{@pod_rel.attachment.ID} ```doesnt work -> seems a bug with magic tags and attachments

**Comment by quasel** [comment]
further investigation: 
```$pod->display('pod_rel.attachment')``` gives the ID 
```$pod->display('attachment')``` gives the full attachment url

**Comment by quasel** [comment]
did update my last post - seems to be a very strange issue
```$pods->display('pod_rel.attachment')```  calls ```$this->field()``` wich delivers a different result as ```$pods->field('pod_rel.attachment') ```wich leads to  ```pods_serial_comma()``` being called ... result is  'and ID' ( [pod_item_id]  ist the last key of the array ... )

Magic Tag  ```{@pod_rel.attachment.ID}``` does work but [if pod_rel.attachment.ID] results to false it seems ... very strange!

**Comment by quasel** [comment]
Maybe a better description:
``` $pods->field('pod_rel.attachment', array( 'display' => true ))``` returns: nothing 
``` $pods->field('attachment', array( 'display' => true ))``` returns: the full attachment URL 
```$pods->display('pod_rel.attachment')```  returns: 'and ID' (attchment ID)
last example leads to ```$this->field()``` wich returns an array and pods_serial_comma() gets called 

i am done with it for today its starting to go far beyond my experiecne with pods ;) guess i really need to setup my vm with debugger ;)

**Comment by quasel** [comment]
@sc0ttkclark #2766 fixes all issues but one is left (wich is a special case anyway) 
``` $pods->field('pod_rel.attachment', array( 'display' => true ))``` result:  'and ID' (attchment ID)
