### ISSUE TITLE
Custom Page Types

### ISSUE THREAD

**Issue by mythusmage** [pods-framework/pods#2757]
As far as I can see, Pods only deals with Posts on WP. I'd like to create custom page types, with the page functionality ready to go.

**Comment by sc0ttkclark** [comment]
I assume you mean pages as in being able to select Page templates? If so, Page templates are intentionally limited inside WordPress for the 'page' post type. If you don't need that, Pods already supports hierarchical post types. Create a new post type, choose under the Advanced options in the Edit Pod area and check the 'Hierarchical" option to on. This provides url structures like `/your-post-type/any-page-here/` and `/your-post-type/any-page-here/any-sub-page-here/`.

**Comment by mythusmage** [comment]
Actually, I found out that you can do it, but the instructions are a bit
intimidating. What I need is a Pods for Dummies

On Tue, Feb 24, 2015 at 4:48 PM, Scott Kingsley Clark <
notifications@github.com> wrote:

> I assume you mean pages as in being able to select Page templates? If so,
> Page templates are intentionally limited inside WordPress for the 'page'
> post type. If you don't need that, Pods already supports hierarchical post
> types. Create a new post type, choose under the Advanced options in the
> Edit Pod area and check the 'Hierarchical" option to on. This provides url
> structures like /your-post-type/any-page-here/ and
> /your-post-type/any-page-here/any-sub-page-here/.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pods-framework/pods/issues/2757#issuecomment-75883680>
> .
>



-- 
Opinions are subject to adjustment and alteration. Facts are not.

**Comment by sc0ttkclark** [comment]
Working on that :)
