### ISSUE TITLE
Top 10 Unit Tests Every Pods 2.5.2 Needs

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2759]
1) Fetching associated taxonomy with Pods::field() #2749
Needed to ensure PR #2750 fixes #2747 and doesn't cause regression on the issue that fixed, which in itself was a regression.

2) Tests for magic tags, make sure output, especially traversals (for example #2755 ) works properly.

3) Unit Test For Ordering By Date & Number #2585

4) Test for `Pods::display()` output of related fields. #2654

5) Where arrays  traversals #2689

6) Pods::saved() cache flush #1786

7) Server Side Validation #2505

**Comment by jimtrue** [comment]
But you've only gone to 7, we need 3 more ;)

**Comment by pglewis** [comment]
This is detritus from history.
