### ISSUE TITLE
Required Plain Text field, when inputting "0" as the string, returns a [Field] is empty error

### ISSUE THREAD

**Issue by Copperdust** [pods-framework/pods#2776]
Using Wordpress 4.1, pods version 2.5.1.1

I created a plain text field and made it required, if I input 0 as its value, I see a [field] is empty error.

I could reproduce this error by creating a new custom post type, and creating a single custom required plain text field. When trying to create a new post I can use 1 as the value and it works, but using 0 makes it return an error.

**Comment by Shelob9** [comment]
Related: #2768

**Comment by Shelob9** [comment]
#2355 Is a pending pull request that should resolve this.

**Comment by Shelob9** [comment]
close via #2355
