### ISSUE TITLE
Pods helper failure after 2.5.1.2 update ..

### ISSUE THREAD

**Issue by hashur** [pods-framework/pods#2801]
Hi

After I updated to the latest update yesterday (Monday) 2.5.1.2.
This helper is not working anymore, causing fatal problems for using pods and my site.
This is the code for the helper, not sure why, but when I take the ref to the helper from the pod template, it works, when I add the ref, it does not.

site info:
pdhsource.com
pod name: courses
pod template: courses_detail

Helper Name: estore_helper
estore_product_id: the field name

this is the ref from the template:
{@estore_product_id,estore_helper}

 The helper is used to get product id value from the plugin (estore) ..
Helper code:

<?php 
$shortcode = sprintf('[wp_eStore_fancy1:product_id:%d:end]', $value);
echo get_button_code_for_product($value);
echo eStore_shopping_cart();
?>

PLEASE HELP....
THANK YOU

**Comment by sc0ttkclark** [comment]
What version of Pods were you using before?

**Comment by sc0ttkclark** [comment]
What errors do you see?

**Comment by hashur** [comment]
I don't remember the older ver
I don't see the error
this is what I get (suppose to get a list of fields and a shopping cart that works..
http://www.pdhsource.com/courses/petroleum-pipelines-ground-fueling-facilities/

**Comment by sc0ttkclark** [comment]
What type of field is estore_product_id?

**Comment by hashur** [comment]
plain no.
its used to get the product id from the estore plugin and generate shopping cart .. used to work fine till the update .. I can send you login info..

**Comment by sc0ttkclark** [comment]
Send login info via https://pods.io/help/

**Comment by hashur** [comment]
I tried captcha error  ???

**Comment by hashur** [comment]
won't let me   any other way

**Comment by hashur** [comment]
sent to your email

**Comment by sc0ttkclark** [comment]
I just fixed that form, sorry about that.

**Comment by Shelob9** [comment]
This issue was resolved in Slack by @sc0ttkclark and was not a Pods issue.
