### ISSUE TITLE
How to change order way for the record of PODS

### ISSUE THREAD

**Issue by greatzhao** [pods-framework/pods#2802]
create a Pod called A for example. Its type is Advanced Content Type and storage type is table.
Under A, I created several labels including A-1, A-2, A-3...
How and where to define the order of records as ascending or descending based on one of the labels such as A-1?

**Comment by Shelob9** [comment]
I answered this question here: https://wordpress.org/support/topic/how-to-change-order-way-for-the-record-of-pods?replies=2#post-6713655
