### ISSUE TITLE
HTML5 Time Field Not Saving

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2804]
Reported here:

https://wordpress.org/support/topic/time-field-with-enable-html5-input-field-not-saving?replies=1

Possibly related #2799

**Comment by NikV** [comment]
I have replicated this issue exactly as it is seen in the screencast. I am currently using WordPress Version 4.1.1 and Pods Version 2.5.1.2. I have simply added the time field to a random post type, checked the box for HTML5 (no extra setup) and yes, the field does not save any time.

**Comment by NikV** [comment]
Found this error in the JS console: `The specified value 'T22:30:00' does not conform to the required format.  The format is 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS' where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.`

**Comment by joethomas** [comment]
Thanks, NikV. That is the same error my JS console is giving me.

**Comment by pglewis** [comment]
I'm going to nix regression because this behavior and the console notice go back at least 2 years.  I'm unsure HTML5 time fields have ever worked.

**Comment by pglewis** [comment]
Typo?  An embedded tab that was converted to "\T" maybe?  Should be straightened out.
