### ISSUE TITLE
Pagination & Shortcode issues

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#2807]
josh [9:47 PM] 
@datasplit: [pods name="videos" page="2" limit ="2"] That will give you videos 3 and 4
or [pods name="videos" limit="10" offest="2"] will give you 3 through 12

datasplit [9:48 PM] 
page=2" and limit="4" is giving me videos 1 through 4
it isn't giving videos 5 through 8

datasplit [10:02 PM] 
so this [pods name="videos" limit="10" offest="2"] will give you 3 through 12 doesn't work
it would have to be [pods name="videos" limit="10" offest="2" pagination="true"] to work but then it gives you the pages... not ideal for a sidebar unless it was in a slider or something
just as a test, I did pagination="false" and it gave pagination anyway

pglewis [11:13 PM] 
sounds like we need a GitHub issue to look into those params
and tests in the unit test while we're at it
if it reproduces, which I don't see why it wouldn't

**Comment by Sheriziya** [comment]
After talking with @jimtrue about this in the chat, here's my issue with pagination in the shortcode:
I've got this code:
[pods name="gameprojects" orderby="post_title DESC" where="pods_aft_tutorial_example='1'" limit="5" pagination="true" template="Games_overview"]

I've got 8 gameprojects in that particular pod. I only get to see 5 projects and NO pagination.

I've also tried:
pagination="false"
pagination="1"
Limit removal + pagination="false"
Limit removal + pagination="true"

None of these options work.

I have checked to see if the theme's pagination (theme 2014) does produce pagination. This function works perfectly. It's only the pagination inside the shortcode which doesn't work at all for me.

Luckily I don't have that many projects yet, so it's not a problem yet :D

**Comment by pglewis** [comment]
My quick testing shows that setting pagination to anything other than an empty string will turn on pagination.  The pagination will not be displayed if the limit is greater than or equal to the number of items (as in this case of 5).

I would test without your where clause, which should return all 8 records.  If so, there appear to be three records that don't match your where criteria.

**Comment by pglewis** [comment]
As for the original report: I think `pagination` must be set for limit/page to work properly.  If so, I think that's a bug.  Clearly there are use cases for people supplying their own pagination mechanism.

**Comment by pglewis** [comment]
Note that the `pagination` param's behavior has just changed as per #2932.  The `filter_var` behavior from the [PHP manual for FILTER_VALIDATE_BOOLEAN: ](http://php.net/manual/en/filter.filters.validate.php)

>Returns TRUE for "1", "true", "on" and "yes". Returns FALSE otherwise.

**Comment by Sheriziya** [comment]
@pglewis I've checked all 8 game projects and for all the projects the where clause "pods_aft_tutorial_example" is set to yes, which is "1", correct? So all should show up, with three games on a second page.

I have tested it without the where clause with the following code:
[pods name="gameprojects" orderby="post_title DESC"  limit="5" pagination="true" template="Games_overview"]
Still only five games show up without any pagination.

**Comment by pglewis** [comment]
From the behavior I'm wondering if the pagination is being put into the document but hidden for some reason (CSS, some other element on the page covering it, etc).  I've done a bit of testing, both with the shortcode and `find()` and the `offset` param does not seem to be working correctly... but everything else works as expected for me so far when pagination is set to true.

**Comment by Sheriziya** [comment]
Hmmm.... So, it could be something in the CSS? But where? Cause the theme's CSS (2014 theme) allows the pagination. I've tested that by adding page breaks in the same page and the pagination from the pagebreaks does work. It's purely the pagination from the shortcode that doesn't show up.

Where can I find the pagination in CSS that's specifically related to pods? If I know where to look, perhaps I can find it and solve it :)

**Comment by quasel** [comment]
- pagination=true limit="5" offset=2 works 
- pagination=true limit="5" offset="2" page="2"  displays it correctly but navigation doesnt work (shows on all links the same result)
- pagination=false  always displays page 1 and ignores page/offset (reported @sc0ttkclark @slack and verified) 

wich is altogether a bit weird ... 
i would expect:

offset:  sets always the starting point 
page: calculated starting from offset based on limit
pagination: should only switch the display of navigation links maybe add values show/hide

@Sheriziya deactivate css - or look at the source in you browser if its there ... or youse the a "standard" theme

**Comment by Sheriziya** [comment]
@quasel Okay, this gets weirder..... Like you suggested I've checked the source code (seemed the fastest thing to do) and here's what I find, nicely in the code, after game "#5":
<span class="pods-pagination-advanced ">
    
    <span class="pods-pagination-number pods-pagination-current ">1</span>

            <a href="/fgc-test-games/quick-test-for-tutorial-all-game-projects/?pg=2" class="pods-pagination-number pods-pagination-last ">2</a>
                    <a href="/fgc-test-games/quick-test-for-tutorial-all-game-projects/?pg=2" class="pods-pagination-number pods-pagination-next ">Next &rsaquo;</a>
                                <a href="/fgc-test-games/quick-test-for-tutorial-all-game-projects/?pg=2" class="pods-pagination-number pods-pagination-last ">Last &raquo;</a>
                    
</span>

Here's the full source code of the pods part: http://pastebin.com/0uAzsUvL

So..... if it's in the code, why isn't it showing up? I'm pretty confused right now.....

**Comment by pglewis** [comment]
So, what are we left with here as far as actual issue(s)?  Possibly the pagination link isn't working?

**Comment by Sheriziya** [comment]
Okay, with thanks to @pglewis and @quasel my pagination problem is solved. I had placed the <div> and <ul> outside my template because I didn't get the set up working the way it was supposed to work otherwise. @quasel pointed me to the [before] and [after] options in Frontier (which is what I'm using) and now my problem with the pagination is solved. It's showing perfectly! Thanks to both of them for testing and guiding me with this issue!

**Comment by jimtrue** [comment]
Remember that before and after exist in the core pods template code without installing frontier.

**Comment by Sheriziya** [comment]
Thanks @jimtrue I didn't know that :) Learned again something new today.

I am using Frontier, but it's good for others to know as well :)

**Comment by pglewis** [comment]
> pagination=true limit="5" offset="2" page="2" displays it correctly but navigation doesnt work (shows on all links the same result)

@quasel: can you create a new issue for this (and anything else you turned up)?  Since this issue has taken twists and turns, we'll call the pagination/page/limit patches "done" for this, and start fresh with any separate issues that came out of this.
