### ISSUE TITLE
ACT validation errors gives no feedback

### ISSUE THREAD

**Issue by diachedelic** [pods-framework/pods#2811]
Using Advanced Content Types

When failing to add a required file, or the main "Name" field, I get a JS popup saying "Error: Unable to process request, please try again."

However, failing to fill in a text field gives a handy on-page error in dark red.

**Comment by diachedelic** [comment]
This is in 2.5.1.2

**Comment by diachedelic** [comment]
![image](https://cloud.githubusercontent.com/assets/310464/6891813/fb6fe524-d709-11e4-98d9-6e78672a7175.png)

**Comment by Shelob9** [comment]
Can you please try this with Pods 2.5.2 (available by checking out the 2.x branch here or by downloading pods.io/latest)?? This should be fixed in 2.5.2

**Comment by diachedelic** [comment]
Great, that works fine - I get a JS popup saying ‘Error: Name is empty’ when I leave it empty :)

**Comment by Shelob9** [comment]
@diachedelic Awesome. I am closing this as a duplicate then.
