### ISSUE TITLE
ACT WYSIWYG conflict with Styles with Shortcodes for WordPress plugin

### ISSUE THREAD

**Issue by c0rnbread** [pods-framework/pods#2812]
With the Styles with Shortcodes for WordPress plugin activated, my WYSIWYG fields disappear. The frame appears, but I cannot see or edit the text. Plain paragraph text fields are not affected. I'm using ACTs.

Is this an issue you would  be look into or should I choose another shortcode plugin? Can you recommend one that works well with PODS?

Thanks in advance!

**Comment by Shelob9** [comment]
That's very odd. Are you getting a PHP errors or notices with WP_DEBUG enabled, or are you seeing any console errors?

I'm not familiar with this plugin or what it does, so hard for me to give non-generic advice.

**Comment by c0rnbread** [comment]
There's a javascript console error being caused by the Shortcode plugin. I would say at this point that its not a Pods issue. Thanks for your help.
