### ISSUE TITLE
2.5.1.2 github updater not working under wp 3.9.2

### ISSUE THREAD

**Issue by YammYcoding** [pods-framework/pods#2817]
( I can't update this wp right now )

- Had version 2.5.1.2
- Added the two lines for updated in wpconfig
- Now the button to force update shows in pods > settings. I click it.
- It goes to plugins pages with the force reset param in url.
- But there is no option with Pods plugin, therefore I can't update from there :(

**Comment by sc0ttkclark** [comment]
Fixed via #2819

**Comment by YammYcoding** [comment]
didn't work either ways =(
