### ISSUE TITLE
3.0 Merge

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#2822]
- [x] init.php

---

- [x] classes/PodsAdmin.php
- [ ] classes/PodsAPI.php
- [x] classes/PodsArray.php
- [x] classes/PodsComponent.php
- [x] classes/PodsComponents.php
- [x] classes/PodsData.php
- [x] classes/PodsField.php
- [x] classes/PodsForm.php
- [x] classes/PodsInit.php
- [x] classes/PodsMeta.php
- [x] classes/PodsMigrate.php
- [x] classes/Pods.php
- [x] classes/PodsUI.php
- [x] classes/PodsView.php

---

- [x] classes/Pods/Field/*

---

- [x] components/*

---

- [x] classes/Pods/Widget/*

---

- [x] includes/*

---

- [x] tests/*

---

- [x] ui/admin/components-admin.php
- [x] ui/admin/field-option.php
- [ ] ui/admin/form.php [@sc0ttkclark plz]
- [x] ui/admin/form-settings.php
- [x] ui/admin/help.php
- [x] ui/admin/help-debug.php [formatting only]
- [x] ui/admin/help-github.php [formatting only]
- [x] ui/admin/help-resources.php [formatting only]
- [x] ui/admin/help-send-info.php [formatting only]
- [x] ui/admin/settings.php
- [x] ui/admin/settings-reset.php
- [x] ui/admin/settings-settings.php
- [x] ui/admin/settings-tools.php
- [x] ui/admin/setup-add.php
- [x] ui/admin/setup-edit-field-fluid.php
- [x] ui/admin/setup-edit-field.php
- [x] ui/admin/setup-edit-group.php [formatting only]
- [x] ui/admin/setup-edit.php
- [x] ui/admin/shortcode.php
- [x] ui/admin/view.php

---

- [x] ui/admin/upgrade/*

---

- [x] ui/admin/widgets/*

---

- [x] ui/fields/*

---

- [x] ui/front/*

---

- [x] ui/front/pagination/*

**Comment by sc0ttkclark** [comment]
I'll close #2135

**Comment by cannect** [comment]
Hi guys,

I am sorry to comment here, but I think 3.0 is going to be released in days when I see this merge issue?

Keep up this awesome work!

**Comment by quasel** [comment]
dont expect it to be days sorry :/ - its just to be sure that all improvments to the 2.x branch are moved to 3.0
