### ISSUE TITLE
Fatal error:is_callable()

### ISSUE THREAD

**Issue by ReevesPro** [pods-framework/pods#2832]
My client just started the following message:

Fatal error: is_callable(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;PodsField_Pick&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in html/wp-content/plugins/pods/classes/fields/pick.php on line 1357

Not really sure what's going on as it just started saying this today.

**Comment by quasel** [comment]
well we would have needed more information ;) 
Sorry for the late reply, feel free to comment if you still have questions!
