### ISSUE TITLE
Fatal Error: Call to undefined function wp_get_current_user()

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#2833]
Fatal error: Call to undefined function wp_get_current_user() in /wordpress/wp-includes/capabilities.php on line 1356

Call Stack:
    0.0010     241832   1. {main}() /wordpress/wp-admin/index.php:0
    0.0020     243416   2. require_once('/wordpress/wp-admin/admin.php') /wordpress/wp-admin/index.php:10
    0.0024     244432   3. require_once('/wordpress/wp-load.php') /wordpress/wp-admin/admin.php:31
    0.0027     245648   4. require_once('/wordpress/wp-config.php') /wordpress/wp-load.php:29
    0.0038     248800   5. require_once('/wordpress/wp-settings.php') /wordpress/wp-config.php:80
    0.2576    1695648   6. include_once('/wordpress/wp-content/plugins/pods-release-3.0/init.php') /wordpress/wp-settings.php:215
    0.2583    1697800   7. current_user_can() /wordpress/wp-content/plugins/pods-release-3.0/init.php:93

(I've removes all host-dir info).

- WordPress 4.1.1
- No other plugins (clean installation)
- Only happend in wp-admin, front-end works.

Hope this helps!

**Comment by sc0ttkclark** [comment]
Avoid running Pods 3.0 yet, it's not beta and isn't fully functional. Try http://pods.io/latest/

**Comment by JoryHogeveen** [comment]
Hi Scott, I know, It was on a test website because I'd like to test Pods 3.0 in advance. I thought I'd let you know what I found :).

**Comment by JoryHogeveen** [comment]
Maybe close this since the future 3.0 branche will not be similar to the old
