### ISSUE TITLE
traversal tests should use `$field_type . '_format_type'` instead of `pick_format_type`

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2837]
This is fix needed to properly test #2750

**Comment by Shelob9** [comment]
https://github.com/pods-framework/pods/blob/ad02de671cbabb65f7b167f2976d471292d5a4fb/tests/includes/tests-traversal.php#L543

**Comment by sc0ttkclark** [comment]
And line ~607, there's three usages in that file I believe.
