### ISSUE TITLE
Pods Converts menu positions with decimals to int on save

### ISSUE THREAD

**Issue by Elwood-P** [pods-framework/pods#2839]
I've had pods installed on a site for a while. I have 8 custom post types, 3 custom taxonomies and a custom settings page. I've just noticed that "Posts" menu is missing from the left hand side admin menu. All posts are fine and I can still access pages by going to their URLs e.g "mysitecom/wp-admin/edit.php". I'm not sure when the problem started.

Disabling all plugins results in "Posts" reappearing in the menu. Activating only Pods plugin results in it disappearing again.

Updating Pods and WP to latest versions doesn't help. Clearing Pods cache doesn't help. Reseting Pods data and settings on a staging site does remove the problem.

I'm not sure how to proceed to further troubleshoot and fix the problem.

**Comment by sc0ttkclark** [comment]
Sounds like a menu position conflict, if you set it to a known one, it will sit on-top of it. Try tweaking your menu positions for the post types.

**Comment by Elwood-P** [comment]
Thanks Scot. All the CPT Menu Positions are set to "5". I thought this meant they would display in the order they were registered underneath Posts.

However it seems I'm wrong. Checking the Wordpress Codex I read:
"WARNING: if two menu items use the same position attribute, one of the items may be overwritten so that only one item displays! Risk of conflict can be reduced by using decimal instead of integer values, e.g. 63.3 instead of 63 (Note: Use quotes in code, IE '63.3')."

I've tried using a decimal value in the Pod's Menu Position Field but it is stripped after saving. Could you please advise how I can place my 8 CPTs and 1 Settings page in between Posts(5) and Menu (10)?

**Comment by Shelob9** [comment]
@Elwood-P Use decimals. 5.1, 5.2, 5.3, 5.4 and 5.5 will put them all right under posts.

**Comment by sc0ttkclark** [comment]
I think he said he tried to use the decimal value but it was getting forced to int on saving on the Pods side.

**Comment by Elwood-P** [comment]
Yes, that is correct Pods converts to integer on saving.

**Comment by Shelob9** [comment]
OK, I am renaming and relabeling as bug then.

**Comment by Shelob9** [comment]
Possibly caused by #2674

**Comment by pglewis** [comment]
Despite the excerpt from the codex, WordPress enforces integer menu positions for post types: https://github.com/WordPress/WordPress/blob/b5b5c98e/wp-admin/menu.php#L108

ACTs and post types will already save menu positions in the format 'xx.x' in the database, though they'll be converted to integer when displayed in the ui admin tab.  An ACT will actually get inserted into the global `$menu` array that way too (e.g. '78.3'), but post types are at the mercy of WordPress's intervention above.  

We could easily fix all the other stuff up, including auto-incrementing by .1 on menu position conflicts, but it seems like a moot point until WordPress cleans up its handling such that non-integer values are fully supported.

**Comment by pglewis** [comment]
I'm going to punt this from 2.5.3 for now, but it would be nice to support this eventually.
