### ISSUE TITLE
ACT - Admin Order DESC not working && SQL error if order by an relationship field 

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#2843]
Changing sort column in the standard UI ACT 
e.g. wp-admin/admin.php?page=pods-manage-pod&orderby=field&orderby_dir=DESC
works in 2.5.1.2
broken in 2.5.2 latest 

- if its a standard field  -its always sorted ASC 
- if field is relationship: 
```
WordPress database error: [Unknown column 't.field' in 'order clause']
SELECT DISTINCT `t`.* FROM `jfu_pods_pod` AS `t` ORDER BY `t`.`field` ASC, `t`.`id`, `t`.`id` LIMIT 0, 25

Database Error; SQL: SELECT DISTINCT `t`.* FROM `jfu_pods_pod` AS `t` ORDER BY `t`.`field` ASC, `t`.`id`, `t`.`id` LIMIT 0, 25; Response: Unknown column 't.field' in 'order clause'
```

**Comment by sc0ttkclark** [comment]
Do all relationship fields get prefixed with t. in the error messages?

**Comment by quasel** [comment]
the complete error msg is listed - but you only get the error if you try to sort by a relationship field

**Comment by sc0ttkclark** [comment]
And sorting by the same relationship field works in 2.5.1.2?

Can you verify that the URL to sort by relationship field is the exact same Pods 2.5.1.2 vs 2.5.2?

**Comment by quasel** [comment]
Yes same URL

**Comment by sc0ttkclark** [comment]
In 2.5.1.2, can you add `&pods_debug_sql=1` to the URL of the working relationship field sort?

**Comment by sc0ttkclark** [comment]
With that added, you should see a textarea somewhere on the page above the table list

**Comment by quasel** [comment]
2.5.1.2  - Relationship field
admin.php?page=pods-manage-imes_plc&orderby=hs_rel&orderby_dir=DESC&pods_debug_sql=1
```
                SELECT
                
                DISTINCT
                `t`.*
                FROM `jfu_pods_imes_plc` AS `t`
                
                    LEFT JOIN `jfu_podsrel` AS `rel_hs_rel` ON
                        `rel_hs_rel`.`field_id` = 2084
                        AND `rel_hs_rel`.`item_id` = `t`.`id`

                    LEFT JOIN `jfu_pods_imes_hs` AS `hs_rel` ON
                        `hs_rel`.`id` = `rel_hs_rel`.`related_item_id`
                
                
                
                
                ORDER BY `hs_rel`.`name` DESC, `t`.`id`, `t`.`id`
                LIMIT 0, 25
```
2.5.1.2 - number field
admin.php?page=pods-manage-imes_plc&orderby=age&orderby_dir=DESC&&pods_debug_sql=1
```
                SELECT
                
                DISTINCT
                `t`.*
                FROM `jfu_pods_imes_plc` AS `t`
                
                
                
                
                ORDER BY `t`.`age` DESC, `t`.`id`, `t`.`id`
                LIMIT 0, 25
```
2.5.2 - Relationship field - not working right
admin.php?page=pods-manage-imes_plc&orderby=hs_rel&orderby_dir=DESC&pods_debug_sql=1
ASC in SQL but URL says DESC !!!
```
        SELECT
                
                DISTINCT
                `t`.*
                FROM `jfu_pods_imes_plc` AS `t`
                
                
                
                
                ORDER BY `t`.`hs_rel` ASC, `t`.`id`, `t`.`id`
                LIMIT 0, 25
```

2.5.2 - number field - not working right
admin.php?page=pods-manage-imes_plc&orderby=age&orderby_dir=DESC&pods_debug_sql=1
ASC in SQL but URL says DESC !!!
```
                SELECT
                
                DISTINCT
                `t`.*
                FROM `jfu_pods_imes_plc` AS `t`
                
                
                
                
                ORDER BY `t`.`age` ASC, `t`.`id`, `t`.`id` 
                LIMIT 0, 25

**Comment by sc0ttkclark** [comment]
@quasel can you test against #2847?

**Comment by quasel** [comment]
Nope - still cant sort DESC and Same error on Relations ...

**Comment by quasel** [comment]
as of 2.5.2 still broken! (verfied)

**Comment by pglewis** [comment]
PR fixes submitted
