### ISSUE TITLE
Migrate: Import from Advanced Custom Fields

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#285]
Same as #287, except for Advanced Custom Fields

**Comment by Dave3o3** [comment]
Hi!

I never contributed to something here and just started coding last year. I'm a ACF user and like to switch to Pods. So how can I help here?

**Comment by sc0ttkclark** [comment]
We're in the process of compiling a large document that specs out each custom fields / content types plugin for our purposes. We'll be writing the code that can migrate between (back and forth!) the plugins once we have enough to work with.

https://docs.google.com/spreadsheets/d/1eHAvAY8k_W_X9Gqs_QdDpluoklym51qk6y1Ro0weVDY/edit#gid=0

If you want edit access, just request access from Google docs itself.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Is this fully off the table?

**Comment by sc0ttkclark** [comment]
No, I definitely want to do this. It mainly just requires planning and a UI to power it
