### ISSUE TITLE
Adding ability to translate strings in ui/admin/help-resources.php

### ISSUE THREAD

**Issue by NikV** [pods-framework/pods#2850]
Currently fixing this, PR coming soon!

**Comment by Shelob9** [comment]
@NikV Good, make sure to do in 2.x and 3.x

**Comment by NikV** [comment]
Actually, was already done for 2.x back in February apparently. So I'll just keep patching up the 3.x one and submit a full PR soon.

**Comment by GaryJones** [comment]
The `ui/admin/help-resources.php` file doesn't seem to exist any more, and the PR got closed.

Can this Issue be closed?
