### ISSUE TITLE
Magic Tags - Author Real name

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#2851]
Searched everything and could not find it.

Is it possible with some tricks to show name instead of Author ID with Magic Tags ? Pods templating, not custom PHP templates.

You have to admin it is a bit stupid to list posts with Magic Tags templates and Pods widget, and not be able to show author name.

**Comment by StaggerLeee** [comment]
I have seen topic about how user names are in separate tables in database and how difficult is for Pods to show realname. But problem is, why it is so easy for Pods Tag to show User ID. It needs just converting to name.

**Comment by StaggerLeee** [comment]
This seems to work in template. One forum topic confused me about PHP inside Pods template. But after more careful reading I see it is about Pods Frontier templates.
```
<?php
	$row = $obj->row();
	$author_id=$row['post_author'];
	$author = get_the_author_meta( 'display_name', $author_id );
?>
 
<?php print $author; ?>
```

**Comment by quasel** [comment]
PHP in any Template works but it isnt recommend and deprecated due to security issues

- for CPT to get display name you could do:   {@author, get_the_author} wich i would recommend  (if the Template is used within the loop (e.g. shortcode etc ) 
if you need a different field i would recommend to write your own function and use it in the magic tag (which will pass the id from @author to your function)
- i would expect {@author.display_name} to wokr but didnt test it
- for ACT it would work {@author.display_name} becaus the Author is simply a relationship field

**Comment by StaggerLeee** [comment]
- {@post_author} gives Author ID = Number.
- {@author, get_the_author}  gives nothing.
- {@author.display_name} gives Author ID = Number

It is outside of the loop, latest posts in widgets, with Pods widget.

Can it be maybe because I transfered/converted posts from WP native post type to Pods types ?

**Comment by quasel** [comment]
sorry didn't need it up to now ;) outside the loop either write you own function 
or does  {@post_author.display_name} work then? i would expect it ^^

**Comment by quasel** [comment]
seems #1694 never did reach code ;)

**Comment by StaggerLeee** [comment]
"Write your own function" is music for my ears. But how.

-{@post_author.display_name}  doesnt work.

WP post type is extended right way, no options there.

- One widget shows latest posts from WP posts (Pods extended)
- Another one shows post from Pods type (before converted from WP posts)

**Comment by jimtrue** [comment]
`{@post_author,the_author}` and `{@post_author,get_the_author}` work perfectly. However, none of the other Template tags (like the_author_link or get_the_author_link, appear to. https://codex.wordpress.org/Template_Tags#Author_tags

**Comment by StaggerLeee** [comment]
Non of it worked for me in Pods widgets.

If i add () then again it shows pure Author ID number.

- {@post_author,get_the_author()}

**Comment by quasel** [comment]
Somewher in your Plugin or functions.php add: 
````
yourPrefix_get_author_display_name($userID) {
     return get_the_author_meta( 'display_name', $userID );
}
````
{@post_author, yourPrefix_get_author_display_name}

or write a custom widget ;) 
@jimtrue seems the widget isnt "int the loop" hence it doesnt work for him

**Comment by StaggerLeee** [comment]
Thank you a lot. So simple, why not in Pods core.
```
function yourPrefix_get_the_author_display_name($userID) {
     return get_the_author_meta( 'display_name', $userID );
}
```

**Comment by quasel** [comment]
Because this would be needed for each existing "field" - i agree there should be an easy to use solution :D - glad it worked for you

**Comment by StaggerLeee** [comment]
Man, it is not like this. 
There is already Autrhor User ID in Pods core. What is use of it on frontend. I dont get it.

**Comment by sc0ttkclark** [comment]
We're working on magic tag traversal for post_author.

![Soon](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQzukfwvtQH-zMoOzBzA4_vIXTw1v6ipqZ72rqmzbOHK0rAjFnd)
