### ISSUE TITLE
Pods Templates: Add index magic tag

### ISSUE THREAD

**Issue by makbeta** [pods-framework/pods#2855]
When pods templates are used in a list, there is no way to add any conditional logic in the middle of the list. It would be nice to have index magic tag available to enable conditional html be inserted in the middle of the list.  
Use case:

``` [before]
<div class="client__container">
[/before]
<div class="client client-{@index}">
<h4>{@post_title}</h4> 
  [if post_thumbnail]<img class="client__image" src="{@post_thumbnail_url.medium}" />[/if]
</div>
[if index%3 == 0]<hr />[/if]
[after]
</div>
[/after] 
```

Thank you

**Comment by sc0ttkclark** [comment]
This should map to `Pods::field( 'index' )` and index should be an alias (assuming field of that name doesn't exist) and call `Pods::index()`
