### ISSUE TITLE
Need help with a little bit of code

### ISSUE THREAD

**Issue by davebo11** [pods-framework/pods#2863]
I have inherited a Pods based WP site.  When I first started working on it I stupidly deleted a line of code because the site owner said he no longer wanted text content on the home page.  So I deleted the line of PHP code from the custom template page (home.php) that took the content from the editable page home_page and inserted it into the page.  
Now he wants that text, etc. back on the site and I can't figure how to regenerate that code.  Default WP code does not work. Can anyone help me with this?

Thanks!

**Comment by NikV** [comment]
Could you please create this as a support thread on WordPress.org? Thanks!

https://wordpress.org/support/plugin/pods
