### ISSUE TITLE
Pods caching with 'expires' returns cache for wrong post type

### ISSUE THREAD

**Issue by maarten00** [pods-framework/pods#2869]
We've found a bug in the PodsData select function. Consider the following example. I have a page with multiple pods calls which are retrieved from the cache:
```
$werkplaatsacties = pods('werkplaatsacties', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS));
$werkplaatstips   = pods('werkplaatstips', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS));
$downloads        = pods('downloads', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS));
```
As you can see the params for these three calls are exactly the same. The only difference is the pod name. Fetching this without cache works, fetching this with cache results in only the first query working. After investigation I found that the second and third query contained the results for the first query. Disabling expire or changing some params around fixed this issue, but not permanently. 

After a lot of debugging we found the culprit:
https://github.com/pods-framework/pods/blob/master/classes/PodsData.php#L635

The params for the query are serialized to generate a cache key, but not the pod name. This explains the behavior in my example.
A workaround that fixes this is adding a random extra parameter to each query: 
```
$werkplaatsacties = pods('werkplaatsacties', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS, 'pod' => 'werkplaatsacties'));
$werkplaatstips = pods('werkplaatstips', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS, 'pod' => 'werkplaatstips'));
$downloads = pods('downloads', array('where' => 'merk.slug = "'.$merk.'"', 'limit' => '10', 'expires' => HOUR_IN_SECONDS, 'pod' => 'downloads'));
```
I've added 'pod' => 'podname' to each call, but it doesn't really matter what you add, as long as it's key-value and different to the other queries it works. The definite fix should be adding the pod name to the MD5 hash that is used for caching. I would've done a pull request, but I'm not quite sure where the cache is being set.

**Comment by Shelob9** [comment]
@maarten00 Good catch. A lot of thank you.

The variable `$params` has the table name, which is different for all advanced content Pods, but will be the same for each post type Pod. I added the Pod name to what is used to create the key, which should make them properly unique.

**Comment by Shelob9** [comment]
Close via #2870 & #2871
