### ISSUE TITLE
Special magic tags not working

### ISSUE THREAD

**Issue by int2k** [pods-framework/pods#2874]
was trying to get home url using {@home-url} inside template
but no output at all
have tried manually using do_magic_tags (from pods object) but result is the same

i'm currently using 2.5.1.2

**Comment by Shelob9** [comment]
Special magic tags do not work inside of a Template. As long as you're opening PHP tags, just use `home_url()` https://codex.wordpress.org/Function_Reference/home_url

**Comment by int2k** [comment]
i'm need to insert pods content inside normal post using shortcode
using the tags directly inside the shortcode also doesnt seem to work
is there any alternative ?

**Comment by int2k** [comment]
found temporary solution by forcing shortcode processing
