### ISSUE TITLE
New, or modified plugin to list related children

### ISSUE THREAD

**Issue by johnruciak** [pods-framework/pods#2877]
Currently,in Pods List widget,  a list of related children prints out all related children of all parents. This feature request is to ask for a way that only the related  children of the current parent is shown, either as an option to the existing Pods List Widget, or the development of a new plugin.

**Comment by jimtrue** [comment]
I think the primary issue with this one is, Widgets exist outside of the loop, so I think what John is looking for is a way for the Widget to understand what kind of page it's own and get the Current Pod Object outside the loop, without having to hard code a slug or id in the widget.
