### ISSUE TITLE
Copy over EDD's scrutinizer

### ISSUE THREAD

**Issue by chriscct7** [pods-framework/pods#2917]
Seriously use Scrutinizer. It's amazing. It finds bugs and can automatically fix docblocs for you.
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/.scrutinizer.yml + a scrutinizer hook in the repo config

**Comment by chriscct7** [comment]
@Shelob9 must have copied over EDD's testing suite before we added it

**Comment by chriscct7** [comment]
Just testing @josh++

**Comment by Ramoonus** [comment]
I`m in

**Comment by Ramoonus** [comment]
#3072
