### ISSUE TITLE
`Pods_Unit_Tests\Pods_UnitTestCase::_initialize_data()` throws notice in tests

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2922]
For example, see: https://travis-ci.org/pods-framework/pods/jobs/62443451

Notice is `Notice: Undefined index: field in /home/travis/build/pods-framework/pods/classes/PodsAPI.php on line 3795` stack trace shows that it is `Pods_Unit_Tests\Pods_UnitTestCase::_initialize_data()` that sets it off.

**Comment by sc0ttkclark** [comment]
Fixed
