### ISSUE TITLE
shortcode pagination=false sets the flag as true

### ISSUE THREAD

**Issue by str** [pods-framework/pods#2932]
[pods name="foo"  pagination=false] or [pods name="foo"  pagination="false"]
  
This will show the pagination links.

**Comment by sc0ttkclark** [comment]
Needs PR for `release/3.0`, then we can merge this into 2.5.3 and 3.0

Current 2.5.3 PR is at #2936 and needs a refresh with latest from 2.x

**Comment by pglewis** [comment]
Thanks for the fix on this, I've gone ahead and created merges to get it into the codebase.
