### ISSUE TITLE
shortcode forces a limit when no pagination was requested

### ISSUE THREAD

**Issue by str** [pods-framework/pods#2934]
Only showing 15 elements is confusing when in the shortcode there was no limit set nor pagination set. It should either set no limit or set pagination true

**Comment by Shelob9** [comment]
`Pods::find()` already sets 15 as a limit.

**Comment by str** [comment]
@Shelob9 that's exactly the problem. It is confusing to have a hardcoded limit when there was no pagination or limit set in the shortcode.

**Comment by quasel** [comment]
well you can limit the number returned and have no navigation displayed ... it maybe confusing but afaik its done the same way in wp core. It's basically a saftey net because if you have many pod items it can timeout ...

**Comment by str** [comment]
@quasel, yes, you can you can set a limit in the shortcode, but, there should not be a hardcoded limit if no pagination was set. That's what I'm fixing in my pull request #2935.

**Comment by str** [comment]
@quasel  "afaik its done the same way in wp core" What do you mean? paginate posts by defautl? Yes, but it shows you the pagination by default too. That's not the case for pods.

**Comment by Shelob9** [comment]
@str The limit is hardcoded in `Pods::find()` which is what the shortcode wraps. I think that is a sensible default and for backwards compatibility, it would be bad to change it now.

**Comment by str** [comment]
OK, understood
