### ISSUE TITLE
Reverse sorting using default Pods Admin when clicking on column heading stopped working in 2.5.2

### ISSUE THREAD

**Issue by clampdesign** [pods-framework/pods#2937]
I just upgraded from Version 2.5.1.2  to 2.5.2 and noticed that I am no longer able to reverse the sort order by clicking on any column heading. I am using the "Normal" Admin UI Style.

**Comment by quasel** [comment]
related to #2843

**Comment by Shelob9** [comment]
I'm closing this as a dupe of #2843 The over escaping of URLs in 2.5.2 was too extreme in some cases and we need to round up everything that is broken.
