### ISSUE TITLE
Development version numbering

### ISSUE THREAD

**Issue by afragen** [pods-framework/pods#2939]
GitHub Updater works best with non-alpha version numbers. For reference and example this is how I use version numbering with GitHub Updater itself.

`master` is the release branch and is the branch that is on .org

As `2.x` seems to be the development branch, what I would do is at the next develop version bump I would push the version from `2.5.2 Beta 1` to `2.5.2.1`. I would continue to increment the development branch using this fourth digit and only update elsewhere just before merging into master. This way master will always have a version number lower than develop. If the GHU user has `Pods/init.php` with `GitHub Branch: master` they will **always** and **only** receive updates from .org

The following semantic versioning works best, `<major>.<minor>.<patch>.<development>`

That is also why it's necessary to keep the `GitHub Branch` headers in line with the branches they belong with.

Anytime you wish to _push out_ a `2.x` update simply increase the version number to `2.5.2.x`.

**Comment by Shelob9** [comment]
This is going to require some judgment from @sc0ttkclark I don't like the idea of using 4th point numbering for incorrect reasons.

**Comment by sc0ttkclark** [comment]
Our intention is not to release development versions on an ongoing basis, but make it possible for someone to use the GitHub updater to pull the latest development branch. For that purpose, the development branch will normally have the next version or an alpha/beta designation. Would a format in our WP plugin version header like `2.5.3-b-1` work better than `2.5.3 Beta 1`? Or is there nothing you can do on your side? Are you using PHP's version_compare?

**Comment by afragen** [comment]
As long as version_compare sees the beta number as higher it works. But currently the release is 2.5.3 and the `2.x` branch is at `2.5.3 Beta 1`. This is lower and it should be either the same, if there are no difference between master and develop or develop should be higher, i.e. `2.5.4 beta 1`.

Make sense?

**Comment by Shelob9** [comment]
@afragen I'm confused. The currently release is 2.5.2, so version_compare should see 2.5.3-b-1 as later.

**Comment by afragen** [comment]
Yes it should, but the current version number in `2.x` is `2.5.2 Beta 1` and this is lower than `2.5.2`

**Comment by Shelob9** [comment]
#2944 will fix version in 2.x wrong issue.

**Comment by Shelob9** [comment]
Close as fixed in #2944 & will be fixed in #2931
