### ISSUE TITLE
Local dev environment and symlink'd Pods plugin

### ISSUE THREAD

**Issue by afragen** [pods-framework/pods#2945]
I use DesktopServer to create local dev environments. All my local git repos are in a different folder. When I'm testing I usually create a symlink to wp-plugins from my local git plugin repo.

In Pods when I do this I have empty Pods Add New, Settings and Help pages.

**Comment by pglewis** [comment]
If we're to support a Pods plugin directory that is symlinked to a location outside `.../wp-content/plugins` then we cannot blindly set `PODS_URL` based on `__FILE__`, because that magic constant will already have resolved the symlink.

**Comment by pglewis** [comment]
An additional whitelist for views might be a good feature as well, but I think that's a separate feature request from this. I think there should be a workable solution to figure out if the pod directory is a symlink and not dereference it when setting PODS_DIR if so.

**Comment by pglewis** [comment]
From the convo on the original pull request: 

`if ( false === strpos( $_real_view, realpath( WP_PLUGIN_DIR ) ) && false === strpos( $_real_view, realpath( WPMU_PLUGIN_DIR ) ) && false === strpos( $_real_view, PODS_DIR ) )` 

is probably the "proper" and easiest fix here.

**Comment by pglewis** [comment]
Still the 3.0 PR and then this one should be closed.

**Comment by afragen** [comment]
The PR seems to have been reversed in 5ff23512dcf759bf56f9f4cca9e160f80b10d44e

**Comment by afragen** [comment]
Though merged PR should be changed to reflect new logic as in current `2.x`

**Comment by pglewis** [comment]
Yeah, my mistaken direct push to 2.x instead of a pull request muddied the waters even more.  I've verified the fix looks correct to me now in both 2.x and 3.0.  Away she goes.
