### ISSUE TITLE
JavaScript Unit Testing

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#2948]
dfferent WordPress versions contain different branches of jQuery
We spent much focus on PHP unit testing but not on the JavaScript front end part

**Comment by Shelob9** [comment]
@Ramoonus Yes, we should be doing JavaScript testing for the UI. I can think of one issue a few versions back where a change in PodsUI passed all tests, gave no PHP errors, and caused several of our UIs to have no options displayed. Not sure we have the bandwidth the write these tests yet, but if you want to write some, that would be great:)

**Comment by Ramoonus** [comment]
first a framework has to be chosen
QUnit for instance

**Comment by sc0ttkclark** [comment]
QUnit sounds fine to me, I've seen it pop up in multiple places like in 10up chats and WP core usage.

**Comment by Ramoonus** [comment]
https://github.com/gruntjs/grunt-contrib-qunit

**Comment by Ramoonus** [comment]
benefit is also theoretic and cross-browser checking
just done some tests in IE + Edge

**Comment by Ramoonus** [comment]
question is if we want Travis to test this, or do it manually
i would prefer the second

**Comment by sc0ttkclark** [comment]
What jQuery tests do we need specific to Pods, once CMB2 is implemented? We're going to have to rewrite our whole UI layer outside of CMB2 anyways in the upcoming year or so for a responsive refresh anyways. Maybe we should just keep this in mind for the future.

**Comment by Ramoonus** [comment]
downside is that QUnit normally runs under Node.js when externalizing
https://github.com/Krinkle/travis-ci-node-and-browser-qunit

**Comment by Ramoonus** [comment]
or grunt

**Comment by Ramoonus** [comment]
https://confluence.jetbrains.com/display/WI/JsTestDriver+IntelliJ+plugin

**Comment by Ramoonus** [comment]
https://karma-runner.github.io/

**Comment by pcfreak30** [comment]
I believe we are already using mocha now due to @pglewis .

**Comment by Ramoonus** [comment]
@pcfreak30 https://mochajs.org you mean?

**Comment by pcfreak30** [comment]
@Ramoonus yes

**Comment by pglewis** [comment]
Yeah, I'm gonna close this one out as we now have a path to Javascript unit testing.  It may shift as we move forward, but we have a foothold!

**Comment by Ramoonus** [comment]
if we want to use karma on Travis, we should switch to node.js
as described on https://karma-runner.github.io/1.0/plus/travis.html
