### ISSUE TITLE
Students, Courses, Attendance

### ISSUE THREAD

**Issue by tayssirch** [pods-framework/pods#2963]
Hello i would like to ask if you plugin can help
i have post type called Students ( lot of students )
Post Type Called : Courses ( lot of courses )

i want to have a relation between (Students, and Course)
but also i want to add a custom filed for Each Relation;
for example

Student Name : Tayssir
Register in Course Called : IT
Attend The Couse : (checkbox):True
Result is : A+ (Custom field)

Student Name : Tayssir
Register in Course Called : Web Development
Attend The Couse : (checkbox):False 
Result is : F (Custom field)

Same User, could Register in another Course, and have another attend custom field value, and another exam result value.

how can i have this relationship (many to many)

**Comment by jimtrue** [comment]
Our GitHub repo is only for bug reporting and feature requests, not for general questions. Please ask this question over at pods.io/forums/

**Comment by Ramoonus** [comment]
http://pods.io/forums/
