### ISSUE TITLE
Spacing and Typography in help bubbles is suboptimal

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2964]
All text is too small, but the headline is smaller then the text and there is crazy padding.

![screen shot 2015-05-23 at 7 17 47 pm](https://cloud.githubusercontent.com/assets/1994311/7786047/79883290-0180-11e5-8578-1c7f11e7b66d.png)

**Comment by NikV** [comment]
Dup. https://github.com/pods-framework/pods/issues/2668
