### ISSUE TITLE
Unit Tests and Pods

### ISSUE THREAD

**Issue by cannect** [pods-framework/pods#2979]
I am trying to create unit tests with the help of `WP_UnitTestCase`. 

When I use `pods()` it is not found. So I thought I should include it: `include('../../pods/init.php');`.  However, I got a bunch of error by doing so. 

So my question is: how do you use Pods in `WP_UnitTestCase`? 

Maybe I really need the custom boostrap.php file Pods uses?

**Comment by Shelob9** [comment]
@cannect I'm closing this, as it's not an issue, it's a question. It's a good question, if you look at the tests for pods-rest-api you can see how I handled the need to have Pods active, https://github.com/pods-framework/pods-rest-api/tree/master/tests 

The tests channel in our slack would be the best place to discuss this.
