### ISSUE TITLE
Edit pods is blank

### ISSUE THREAD

**Issue by Zyles** [pods-framework/pods#3007]
Suddently my "edit pods" page when I try to edit a pod is blank. No fields show up at all. So I can't work on my website.

Any way to fix this issue?

Not sure what occured to do this.

I tried to delete a pod and it seems like it got removed. But now I can't edit or add new ones...

I cleaned cache, deleted the pods and activated it using the settings feature and activated it again and I still can't do ANYTHING... I can't even create a new pod after this!

Nothing happens when you click "Create New" etc. It is as if there is a javascript not triggering. There are no error logs in Apache. Nothing.

**Comment by sc0ttkclark** [comment]
Please go to Pods Admin > Settings and let us know what you see there under "Debug Information".

**Comment by Zyles** [comment]
More investigations lead to the fact that I can't use anything that is javascript related AT ALL in the ENTIRE wordpress admin.

This includes using stuff like gravity forms dragging and dropping. Basically something happened that shut off a lot of javascript stuff.

Here is debug info:
```
Debug Information

WordPress Version: 4.3-alpha-32675

PHP Version: 5.5.9-1ubuntu4.9

MySQL Version: 5.5.43

Server Software: Apache/2.4.7 (Ubuntu)

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

Session Save Path: /var/lib/php5

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/httpd/demo70/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Shopkeeper Child Theme

Currently Active Plugins:

Admin Columns: 2.4.3
Easy Pricing Tables Lite by Fatcat Apps: 2.0.1
Email Login: 4.6.4
Gravity Forms: 1.9.4
myCRED: 1.6.3
Pods - Custom Content Types and Fields: 2.5.2
Pods Gravity Forms Add-On: 1.0 Alpha 10
Revolution Slider: 4.6.5
WooCommerce: 2.3.9
WooCommerce Direct Checkout: 1.1.2
WooCommerce Header Category Image: 1.0.0
WooCommerce Sequential Order Numbers: 1.4.0
WPBakery Visual Composer: 4.4.2
```

**Comment by Zyles** [comment]
Think I fixed it.

The admin gave errors in Firefox that jQuery was undefined and 500 error on wp-admin/load-scripts.php

I added this to wp-config.php under define('ABSPATH') ....:
define('CONCATENATE_SCRIPTS', false);

Stuff is loading again. Yay...

**Comment by pglewis** [comment]
I'm glad you tracked it down, I'm going to close this one.
