### ISSUE TITLE
Admin UI Sorting Issues

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#3011]
![untitled-1](https://cloud.githubusercontent.com/assets/2176348/7995775/55f38c92-0ae7-11e5-96c6-f39eee237ee8.jpg)
I'm using Pods 2.5.2 and Wordpress 4.2.2.

For a pod's Admin UI, the Admin Table Columns Headers are not sorting correctly. 

Sort order with ASC and DESC are not working.

Also, when sorting a relationship column, a SQL error happens such as:
Database Error; SQL: SELECT DISTINCT `t`.* FROM `wp_pods_listings` AS `t` ORDER BY `t`.`model` ASC, `t`.`id`, `t`.`id` LIMIT 0, 25; Response: Unknown column 't.model' in 'order clause'

Might be related to https://github.com/pods-framework/pods/issues/1230

**Comment by quasel** [comment]
thx for reporting - #2843
it's already fixed either use latest Version or 
wait for 2.5.3 to be released (planned for this week)
