### ISSUE TITLE
Improve documentation for magic tags 

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#3027]
http://pods.io/docs/build/using-magic-tags/

for CPT  title magic tag it's  {@post_title}

not usre how the doc process works / where to add it

**Comment by jimtrue** [comment]
Actually both {@title} and {@post_title} work equally well for CPT's. But I will add {@post_title} to the Documentation.

**Comment by quasel** [comment]
no {@title} doesnt work in widgets - did test it yesterday
