### ISSUE TITLE
Feature Request: Adding hooks for the markup of the Upload field type

### ISSUE THREAD

**Issue by curdin** [pods-framework/pods#3046]
Hi,

This follows up on a discussion with Jim True about changing the markup of the Upload field type [File uploader admin ui hooks](http://pods.io/forums/topic/file-uploader-admin-ui-hooks/) . While my initial intent was to simply add an edit link to each file uploaded with the file uploader it would seem sensible to actually add hooks so the markup can be filtered before being printed on page. In fact it would be great if all field types had that capability.

**Comment by sc0ttkclark** [comment]
Sounds like this would be accomplished through #3086?
