### ISSUE TITLE
PHPUnit Fatal error:  Call to a member function field() on a non-object

### ISSUE THREAD

**Issue by cannect** [pods-framework/pods#3047]
Hi guys,

I am not sure this is 100% Pods related, maybe I get the same error when unit testing when using other plugins in my plugin. 

Situation:
- I use `pods()` in my plugin
- I init my plugin after 'plugins_loaded'
- I Unit test my plugin in PHPUnit
- PHPUnit gives the error `PHP Fatal error:  Call to a member function field() on a non-object`
- Running the plugin the error does not exists

```php
class Category {

    public $data;

    public function __construct()
    {
        // We use Pods, so init after all plugins are loaded
        add_action ( 'plugins_loaded', array( $this, 'init' ) );
    }

    public function init( $category = 'action')
    {
        $this->data = pods( 'category', array( 'where' => "name = '{$category}'" ) );
        
        // Debug
        var_dump($this->name); // Website outputs 'action', PHPUnit gives an error on this line
    }

    public function __get( $key ) {

        $field = $this->data->field( $key );
        if ( isset( $field ) ) {
            return $field;
        }

        return null;
    }
}
```

In the code above you see the comment line `// Website outputs 'action', PHPUnit gives an error on this line`. When I run my tests in PHPUnit, on that line PHPUnit fails while the website version outputs `action`. So it has nothing to do with the test code itself, if you want I can show it too. 
But I do not want to have my question to complicated.

I hope you guys can shed any light on this one. Because, how do you ever test your plugins that use Pods?

**Comment by pcfreak30** [comment]
Pods can return false in some situations. Thus you need to check your parameters to it and verify them. My advice though for simple WHERE conditionals is using meta_query syntax.

```php
$this->data = pods( 'category', array( 'where' => array('name' => $category)) );
```

**Comment by cannect** [comment]
Hi pcfreek30,

Thanks for your comment, your code works also with the same behavior. 

This code:
```php
 $this->data = pods( 'category', array( 'where' => "name = '{$category}'" ) );
        
  var_dump($this->name); 
```

Again works when I run my plugin, but gives the same error when I fire up PHPUnit with the `phpunit --debug` command.

**Comment by sc0ttkclark** [comment]
Did you create your pod during setUp?

**Comment by cannect** [comment]
Ah Scott, many thanks. What the heck, I need a new cup of coffee.  :-)

Of course in PHPUnit we work with a complete different database, I have to mock the pods object. I did not think about that, and will go and find out how to create dummy data in setUp.

**Comment by cannect** [comment]
I have opened a topic about how to Mock a Pod in PHPUnit tests: http://pods.io/forums/topic/how-to-phpunit-your-plugin-that-uses-pods/#post-191194
