### ISSUE TITLE
Bug? Get relational fields in one query

### ISSUE THREAD

**Issue by cannect** [pods-framework/pods#3061]
Hi,

I mentioned when using Debug bar that there will be a heck of a lot queries when you start getting relational fields with `$pods->get('relational_field')`. Sadly I have lots of them. So I want to optimize.

Pod Article
- name -> text field
- category -> relational field to Pod Category

**What I did 1**
```
$pod = pods( 'article', array(
   'where' => array(...),
   'select' => array('t.name', 'category')
));
```

**What I expected to get 1** 
```
array
  0 => 
      'name' => string 'Article 1'
      'category' => array
          0 => 
            array
              'id' => string '5'
              'name' => string 'Category 1'
          1 => 
            array
              'id' => string '5'
              'name' => string 'Category 2'
```

But I got an error:  `WordPress database error: [Unknown column 'category' in 'field list']`

**What I did 2**
```
$pod = pods( 'article', array(
   'where' => array(...),
   'select' => array('t.name', 'category.name AS category')
));
```

**What I expected to get 2** 
```
array
  0 => 
      'name' => string 'Aritlce  1'
      'category_name' => array
          0 => 
            array
              'name' => string 'Category 1'
          1 => 
            array
              'name' => string 'Category 2'
```

But I get: 
```
array (size=2)
  0 => 
    array
      'name' => string 'Article 1'
      'category' => string 'Category 1'
  1 => 
    array 
      'naam' => string 'Article 1' 
      'category' => string 'Category 2'
```

I hope someone can explain why it is not possible to get the expected result with those queries?

**Comment by sc0ttkclark** [comment]
We don't have auto traversal prefix/suffix handling for 'select' like we do for 'where'. You have to specify the full field path, like category.name etc.

See the table at the bottom for a breakdown of how to target each field based on it's field type and/or pod type / storage.

http://pods.io/docs/code/pods/find/
