### ISSUE TITLE
Feature Request for 'If' Conditional in Templates

### ISSUE THREAD

**Issue by dmlws** [pods-framework/pods#3062]
We are using the Pod’s template to make a layout display some entries. It would be great if there was a way that we could specify for the template to show certain information if that entry has a certain category.

Ex.
Pods = Books
Categories = Horror, Science Fiction

In the template could we…
[if @category=’Horror’]
show an image of a zombie
[/if]
[if @category=”Science Fiction”]
show an image of a rocket
[/if]

Thanks,
Doug

**Comment by jimtrue** [comment]
Closing in favor of #3191
