### ISSUE TITLE
Feature request for pod item management

### ISSUE THREAD

**Issue by martinstark** [pods-framework/pods#307]
On the front page of my site I have 2 "large features" and four "small features", and I'm managing them through a single Pod.

The Pod is called Home Features and there's a Yes/No drop-down (renamed to Large/Small) defining how the feature is dealt with in the front end.

The feature I'm requesting is to make managing the pod items easier for my clients, by allowing them to discern, in the back-end, which items are large, and which ones are small. Or on which page they are appearing.

I know I could work around this problem by separating them into several different Pods, but the WP admin menu would quickly become flooded (8 different pages with 2 different feature sizes, and that's only the options required for the featured content, not other types of content).

Introducing an option for a field & its value to be visible on the Pod page would be the easiest solution, I believe. Mock up:
http://img716.imageshack.us/img716/1743/featre.png

**Comment by jimtrue** [comment]
I see no more activity on this one, so I'm closing. This is handled under Admin Columns/Admin Columns Pro or pods_ui
