### ISSUE TITLE
Custom taxonomy filtered post archive not pulling post type meta data

### ISSUE THREAD

**Issue by JacobLett** [pods-framework/pods#3075]
I am trying to create a library of a single custom pod resources. I am then trying to have an archive where visitors can search and filter through this pod by some custom taxonomies. I am also using the pod template frontier. So that each post display is the same across post-archive and taxonomy-archive.

I was using the search and filter plugin to help filter the results https://wordpress.org/plugins/search-filter/

The default archive view works but when I select a taxonomy filter it does not pull the variable data. Do you have any idea on what I could try to correct this? Thank you.

**Comment by sc0ttkclark** [comment]
I assume this is because the taxonomies on the Pod are fields? Or did you only use the 'Associated Taxonomies' option in the Pod's settings? If they are fields, they won't work with the taxonomy filter, they'd have to be used as a custom field filter.

**Comment by JacobLett** [comment]
Thanks for your reply/help Scott. After some testing I found a solution.

I created a pod that had custom fields of meta data (title, description, image, etc) that I was trying to filter through a custom taxonomy in the sidebar. When filtering with the search filter plugin the archive template would only show the title and permalink.

What ended up working for me was to turn off the pods archive and deactivate the plugin. I then removed the custom taxonomies and added them as custom fields instead. I then followed http://pods.io/docs/code/pods/filters/ to create filters. Things are working as expected now but I am having trouble with the following:

- How do I set a cap on results to show the pagination? I have // Add some pagination 
echo $pod->pagination(); but see no place to add a cap to then show pagination

I have solved the issues below with javascript but was wondering if there was a built in way.
- Can you change the output of the filters? (instead of select change to checkboxes)
- Can you change the order of the filters?

Thank you.

**Comment by quasel** [comment]
Been a long time - complex filters can now be done with e.g FacetWP + Pods integration!
