### ISSUE TITLE
Custom Post Type: Unchecking "Supports comments" in Advanced Options does not set comment_status to 'closed'

### ISSUE THREAD

**Issue by bretthamm** [pods-framework/pods#3076]
Unchecking "Supports comments" in Advanced Options does not set comment_status to 'closed'.

Is there another way to set the comment_status to 'closed' ???

**Comment by sc0ttkclark** [comment]
Unchecking Comments from a custom post type does not disable comments, I know it sounds weird. That's just how WordPress itself works with register_post_type, there's nothing Pods does unique here so I'd consider this out of scope for Pods and instead something for WordPress core (at http://core.trac.wordpress.org/)
