### ISSUE TITLE
pods import keeping id

### ISSUE THREAD

**Issue by LuKSD** [pods-framework/pods#3077]
pods->add() and save() function dont accept "import_id" (like wordpress) and generate new id.
(this functionality is present in wp_insert_post() function with “import_id” parameter setted)

Maybe can be useful insert (import) table-based pod and keep id from previous exported items (cause i lost relationship between items if id are regenerated :( ).

LZ

**Comment by sc0ttkclark** [comment]
No, that's not available in the current API for Pods, and WordPress won't allow it in it's own API as well. If we add this as an enhancement, it would definitely be for Advanced Content Types only.

There's no way around that without causing some havoc in other places (there's no hook to tell plugins that a Post or User ID has changed, and inserting with a custom query outside the WP API would be a bad idea in general, so it's blocked on both sides there)
