### ISSUE TITLE
Auto Display Debug Errors

### ISSUE THREAD

**Issue by dlincoln** [pods-framework/pods#3078]
With "Display a form for creating entries" option selected in short codes on a WP page, which is set to display 3 fields (which it does properly!) I used this code:
[pods name="song" slug="edit-song-pod" form="1" fields="track_title,rel_track_to_bandname,related_tracks_to_catalog_name"]

WP Debugger threw the following error on top of my Preview Page:
( ! ) Notice: Undefined index: section_page in /Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-content/plugins/pods-auto-display/PodsAutoDisplaySettings.php on line 27
Call Stack
#	Time	Memory	Function	Location
1	0.0007	296368	{main}( )	../index.php:0
2	0.0008	299224	require( '/Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-blog-header.php' )	../index.php:17
3	0.3149	32281864	require_once( '/Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-includes/template-loader.php' )	../wp-blog-header.php:16
4	0.3327	33931608	include( '/Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-content/themes/twentyfifteen/page.php' )	../template-loader.php:74
5	0.3778	34067856	get_template_part( )	../page.php:24
6	0.3778	34068728	locate_template( )	../general-template.php:171
7	0.3779	34068896	load_template( )	../template.php:477
8	0.3781	34088600	require( '/Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-content/themes/twentyfifteen/content-page.php' )	../template.php:503
9	0.3797	34089608	the_content( )	../content-page.php:22
10	0.3798	34090368	apply_filters( )	../post-template.php:230
11	0.4325	37234472	call_user_func_array:{/Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-includes/plugin.php:213} ( )	../plugin.php:213
12	0.4325	37234832	PodsAutoDisplay->handleFilter( )	../plugin.php:213
13	0.4325	37234896	PodsAutoDisplaySettings::isPostTypeEnabled( )	../PodsAutoDisplay.php:31
14	0.4326	37235152	PodsAutoDisplaySettings::getOption( )	../PodsAutoDisplaySettings.php:37

The GIST from previous issue reported should apply here too:
https://gist.github.com/dlincoln/81c92e96625bcd4a0cf0#file-more-20templates-json

**Comment by dlincoln** [comment]
For reference here's debug info on that host:

Debug Information

WordPress Version: 4.2.3

PHP Version: 5.5.24

MySQL Version: 5.6.24

Server Software: Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.5.24 mod_perl/2.0.8-dev Perl/v5.16.3

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16

Session Save Path: /Applications/XAMPP/xamppfiles/temp/

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 96M

Pods Network-Wide Activated: No

Pods Install Location: /Users/dlincoln/Documents/Websites/musicli-dev.dev/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Fifteen

Currently Active Plugins:

Admin Menu Editor Pro: 1.98
Caldera Clarity For FacetWP: 1.2.3
Caldera Custom Fields: 2.0.1
Caldera Easy Pods: 1.1.2
Caldera Easy Queries: 1.0.1
Caldera Forms: 1.2.2
Metaplate: 0.4.0
Plugin Groups: 1.0.3
Pods - Custom Content Types and Fields: 2.5.3
Pods Auto-Display: 0.4.1
Pods Frontier Auto Template: 1.1.2
Pods Jobs Queue: 0.1.6
Pods Visualize: 1.0
Routed Actions: 1.1.0
WordPress Importer: 0.6.1

**Comment by pglewis** [comment]
I know this is old, but Pods Auto Display is not our plugin: https://wordpress.org/plugins/pods-auto-display/

**Comment by sc0ttkclark** [comment]
Best way forward for anyone using Pods Auto Display is to use Pods Frontier Auto-Template code that is now included in the core component Pods Templates functionality.
