### ISSUE TITLE
Restrict File Types not working for multiple extensions

### ISSUE THREAD

**Issue by Dooza** [pods-framework/pods#3083]
Not sure when this "broke" but I have a pod with a file upload field, and using "Other" as Restrict File Types. My allowed extensions are "pdf,zip,jpg", but when I try to add a file from the media library, nothing appears in the custom field.

If I remove the file type restriction it does work.

**Comment by Dooza** [comment]
I tried setting the restrictions to just one file type, "pdf", and it works. It must be something to do with having multiple extensions. Maybe its the way its been escaped?

**Comment by Ramoonus** [comment]
maybe it has problems loading an array like that
did you try:
"pdf", "zip", "jpg"

**Comment by Dooza** [comment]
@Ramoonus 
I have tried that, but the Media Library now doesn't show anything when trying to find a file to attach.

When I use the recommended method: pdf,zip,jpg the list of files appear filtered in the Media Library, but when selected, all that happens is the Media Library closes. The chosen file doesn't appear in the list of attached files.

**Comment by Ramoonus** [comment]
that sounds more like WP or javascript phenomena to me

**Comment by Dooza** [comment]
There aren't any JavaScript errors occurring when this happens, but that doesn't mean it isn't. If I use just "pdf" it works, or if I leave it without restrictions it works, so my money is on it being a bug in Pods.

**Comment by pglewis** [comment]
Is this still an issue?  pdf, zip, and jpg are all whitelisted mime types in `wp_get_mime_types()`, so it seems like this should work with just a normal comma separated list.

**Comment by pglewis** [comment]
See also: #2031

**Comment by Dooza** [comment]
I can confirm this problem still exists.

**Comment by Ramoonus** [comment]
@Dooza in which version?

**Comment by pglewis** [comment]
This'll be like the third time I've dug into this area, if there's a bug here I'll get it squashed.

**Comment by Dooza** [comment]
Pods 2.6 on WordPress 4.4 using PHP 5.6.16

**Comment by Dooza** [comment]
If I use just pdf it works, if I use pdf,jpg,zip it shows the files but when selected doesn't appear on the edit page, and if I use "pdf","jpg","zip" no files files show in the media library at all.

I am happy to help with any test code you come up with to fix this.

**Comment by pglewis** [comment]
Yeah, I think that's one combination I somehow haven't tested yet: multiple whitelisted types.  A lot of the other reports (like #2031) turned out to be due to using a non-whitelisted type (commonly svg and vcf)

**Comment by Dooza** [comment]
I am pretty sure this worked when I first setup my site, I think the bug was introduced in an update.

**Comment by pglewis** [comment]
This seems to be working at b316cc6 and broken again in c397212

**Comment by pglewis** [comment]
This is not strictly a problem with multiple extensions, even, as `png,jpg` or `wav,mp3` do work.  Could possibly be whenever there are mixed mime types.

**Comment by pglewis** [comment]
The ideas in #3326 might be the way to fix this "the right way".  Things appear to be handled on a mime-type basis under the hood, so we should probably be setting the file upload's whitelist by mime type(s) and not file extension (which just opens up a vector for formatting error anyway).

**Comment by pglewis** [comment]
We have a patch that can be tested on a separate branch: #3328

**Comment by Dooza** [comment]
Excellent, thank you for your help, I have applied the changes on my test system and it is working as expected now.

**Comment by pglewis** [comment]
Glad to hear it, gonna keep this open until the patch gets merged just procedurally :)

**Comment by OWMC** [comment]
Exact same problem as Dooza described. Except if I use just "pdf" it still doesn't work, whereas if I leave it without restrictions it does work.  But only for a specific site on a specific server. Locally I have no problem adding pdfs. And live sites with similar setups but on other servers also work fine. But this one site on it's live server, no dice. Removing the file restriction is good enough for now. I've tried with the last 2 official releases of Pods (2.5 and 2.6) and also with the latest unofficial (2.6.1-a-1). Same result. If I can provide more details let me know what to provide :) (i love pods!)

**Comment by pglewis** [comment]
@OWMC: if it's a specific site on a specific server I'd suspect a mime-type configuration on that server possibly, or some other piece somewhere mucking with the mime types.  

I tested locally with the latest patch applied and pdf by itself is working, so if you can't dig it up as a configuration problem this needs to be a new issue as it's likely unrelated.
