### ISSUE TITLE
Error while adding new field

### ISSUE THREAD

**Issue by ladislavkotik** [pods-framework/pods#3084]
Hi, I am getting an error (Unable to process request) while trying to add a field to any pod. Does anybody faced similar problem before? What would be the cause of this behaviour?

**Comment by Ramoonus** [comment]
could you please tell us what version of wordpress and pods you are using?

**Comment by pavelevap** [comment]
Related? #2104

**Comment by jamesgol** [comment]
Whenever I've seen issues like these it is because of debugging/errors being enabled and something triggers a notice output on the AJAX request.

**Comment by quasel** [comment]
see #2104 - closing for the same reason ;)
