### ISSUE TITLE
Ability to edit media meta data after it's uploaded via pods file upload field type

### ISSUE THREAD

**Issue by LinzardMac** [pods-framework/pods#3086]
If you create a file upload field you have the option to choose whether you want to use plupload or the WordPress modal window (media manager pop up). When you choose the WordPress media manager pop up you get the ability to add all of the media meta data that is set up for the attachment post type. Once that file is saved to the field and the WordPress media manager modal is closed you can no longer go back to edit the meta for that image. 

Adding new file you can see the attachment details on the right sidebar 
![screen shot 2015-08-04 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/322595/9071886/d4fa7024-3ac5-11e5-8c26-de0ae9f9889f.png)

Once the file is added, there is no way to open the media manager modal again with the specific image selected or a way to edit the meta fields on the pods edit page similar to the "title" field is dealt with
![screen shot 2015-08-04 at 4 26 33 pm](https://cloud.githubusercontent.com/assets/322595/9071896/e3400b3a-3ac5-11e5-9f37-eb7401d273b4.png)
- this problem exists for multiple file uploads as well as single file uploads 
- for coding inspiration see stackexchange post by the developer of ACF http://wordpress.stackexchange.com/questions/112599/pre-populate-wordpress-wp-media-modal-with-image-selection

**Comment by sc0ttkclark** [comment]
Good find, yeah this would be nice to have 'edit' or 'meta' icon of some sort.

Wonder what CMB2 is doing here?

**Comment by pglewis** [comment]
Probably too much to consider for 2.7, but then again might be worth a peek to see how much effort to integrate with #3334
