### ISSUE TITLE
Feature request - Edit Post Title placeholder

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3093]
Can you consider making this in Pods core. Many Users would be thankfull for this, I think anyway.
Something like this but adapted to one new field in Pods Admin settings.

```
function change_default_title( $title ){
 $screen = get_current_screen();
 if  ( 'members' == $screen->post_type ) {
      $title = 'Team Member Name';
 }
 return $title;
}
add_filter( 'enter_title_here', 'change_default_title' );    
```

## Task list

- [ ] Add `title_placeholder` option for CPTs (not extended) labels screen, show default text as `Enter title here` after `label_choose_from_the_most_used` option is shown, restrict it to `post_type` only: https://github.com/pods-framework/pods/blob/2.x/ui/admin/setup-edit.php#L448
- [ ] Add method to PodsMeta that filters `enter_title_here`, checks if the post type is a Pod and if so checks to see if we have a value for `title_placeholder` in the pod options; add after `add_meta_boxes`: https://github.com/pods-framework/pods/blob/2.x/classes/PodsMeta.php#L136

**Comment by sc0ttkclark** [comment]
+1

**Comment by sc0ttkclark** [comment]
Added tasklist
