### ISSUE TITLE
Admin URL's are not created properly

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3102]
Pods admin URL's appear to be constructed not using the same functions/methods of wordpress.

If you use in .htaccess

```
RewriteBase //
```

Then accessing a url in pods admin takes you to `http:///....`. While ideally this would never be setup, It can happen. Since WP handles it, pods should too.

**Comment by sc0ttkclark** [comment]
RewriteBase // is a bad config, regardless of whether parts of WordPress supports it. We use `add_query_arg` ultimately, which interacts with `$_SERVER['REQUEST_URI']` which I bet is what comes back with the // and causes some issues in some places naturally. WP uses it much less than Pods, so it's less obvious of a problem in WP core.

**Comment by Ramoonus** [comment]
http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritebase
