### ISSUE TITLE
pods_group_add ignores existence of field

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3110]
If you delete a field or just use a fake name, it show up as a textbox. Threw me off thinking something in data bugged up.

**Comment by sc0ttkclark** [comment]
That's intended, because it's a meta-based field, it'll just work for any custom fields you throw in there. You can pass full field options arrays in there and tell it how to function. It won't work as well for relationship/file (non-simple) fields though, there are some limitations there.
