### ISSUE TITLE
Some fields doesn't appear in admin edit area

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#3119]
it's so difficoult to say how i arrived here...
so i try with a direct question.. :

file 
classes > PostMeta.php line 974

i find..
<code>foreach ( $metabox[ 'args' ][ 'group' ][ 'fields' ] as $field ) {</code>

but the edit admin area doesnt show some fields

i change  with
<code>foreach ( $metabox[ 'args' ][ 'group' ]['pod'][ 'fields' ] as $field ) {</code>

and the fields appear.....

did i find a code error...?! or am i in a very strange situation ?!?!

Thank's a lot..!!

**Comment by sc0ttkclark** [comment]
Changing that line to use ['pod'] array of fields returns ALL fields.

You are not seeing some fields by default because:

1. You have a field hidden, under Edit Field > Advanced Field Options
2. You have a field restricted by capability/role, under Edit Field > Advanced Field Options

**Comment by gigi-budrio** [comment]
Unfortunately none of the listed options are correct...

I use pods from a lot of time, but never seen that "error".

I try to add any fields.... But new fields never appear..
In the pod manage area it appear, but these don't appear in the pods instance editor for that pod...

If i delete an "old" field it doesn't desappear.. It only become a simple text field for every type of fileds.... The strange thing is that if i fill the simple text fields and update the pod.... The fields values are saved! (The relative fields are delete from pod manage).

I fimd in another resolved issue that the solution can be increase the memory limit, but it dont resolve the problem.


I hoped that the code line mentioned avove can be an "error".... Now i dont know where to find the problem..

Thanks..

**Comment by gigi-budrio** [comment]
For complete information:

on the same WP installation, i have 7other pods that have also 15/20 fields and which haven't this problem..
i have an other pods that have almost the same fields of the "at issue" pod, and i can add/remove fields like always whitout problems...

only this pod (CPT pod) have this anomaly..

Thanks again.


here the pod manage area where "Download Documents" appear (under "Presentation Variants")

![schermata 2015-08-27 alle 09 03 41](https://cloud.githubusercontent.com/assets/3088694/9514627/02884768-4c9c-11e5-8470-d73b339d8877.png)

here the "pod instance" editor area, where "Download Documents" doesn't appear (under "Presentation Variants").
![schermata 2015-08-27 alle 09 13 43](https://cloud.githubusercontent.com/assets/3088694/9514647/2a8eafae-4c9c-11e5-8c4d-0c5fafc87b3b.png)


it's the real example i need, but i tried with a lot of fields type with the same result.....

seems that
<code> $metabox[ 'args' ][ 'group' ][ 'fields' ] </code>
is not updated... or partially, because (like said before) if i delete an "old" field it appear again, but like a simple text field...

Thanks..

**Comment by sc0ttkclark** [comment]
On all three of those big relationship fields, try using the autocomplete option instead. I bet this could be a memory issue.

**Comment by gigi-budrio** [comment]
Nothing... :((

![schermata 2015-08-27 alle 16 49 31](https://cloud.githubusercontent.com/assets/3088694/9523792/eb104c9e-4cdb-11e5-849a-3d8082a46578.png)


i also try to remove other metaboxes i added separately from pods.... 
but nothing changes..

It's so strange.

**Comment by sc0ttkclark** [comment]
Let me make sure I completely understand.

You're currently not seeing your "Download Documents" field? Can you screenshot what the settings are for each of the tabs in that field?

**Comment by gigi-budrio** [comment]
yes.. 
But it's the same if i try to add any field for any field type... 
The Download Documents field was only the concrete example i needed.. but i try with a lot of other fields...

these are the requested screenshots

![schermata 2015-08-27 alle 17 05 55](https://cloud.githubusercontent.com/assets/3088694/9524272/60817582-4cde-11e5-982c-175702d1602d.png)
![schermata 2015-08-27 alle 17 05 47](https://cloud.githubusercontent.com/assets/3088694/9524271/6080ca6a-4cde-11e5-840c-e75d2f66f643.png)
![schermata 2015-08-27 alle 17 05 18](https://cloud.githubusercontent.com/assets/3088694/9524273/608332a0-4cde-11e5-9f7d-f49a5609266a.png)


i want to hightlight again another very strange behaviour..:
when i delete one of the "old" fields (the fields the I correctly see in editor) p.e. "Suggest Variant" ...
this field doesn't disappear from editor .... it only become a simple text field (and continue to store text values if some value is setted)...

**Comment by sc0ttkclark** [comment]
Try using Autocomplete for Download Documents too

**Comment by sc0ttkclark** [comment]
I just want to be sure we have all of the information here --

Your screenshot you sent previously https://cloud.githubusercontent.com/assets/3088694/9523792/eb104c9e-4cdb-11e5-849a-3d8082a46578.png

That shows you had all of your fields except the Download Documents field. Is that not the case?

**Comment by gigi-budrio** [comment]
I use autocomplete for download documents too.. In the trial above..

**Comment by sc0ttkclark** [comment]
The field options you sent a screenshot of for Download Documents said it was checkboxes.

**Comment by gigi-budrio** [comment]
... I change it when i just check that the problem persisted..
Then you say to do rhe screenshots.. And i did it with checkboxe resetted...

**Comment by sc0ttkclark** [comment]
Is there a way I could get access to the site to test and see it for myself?

https://pods.io/help/

**Comment by gigi-budrio** [comment]
i submit the credential and insert a reference to that issue...
i only ask that someone starts to work... he sends me an email to the specified address.

PS:

Ops...
i note that i didn't say where to find the interested pod... i specify it below:

the problematic pod (where new fields are not showed) is
- dispenser 

there's a pod that is almost eguale to the dispenser, that is 
- mixer_and_shaker


Thanks again.

**Comment by gigi-budrio** [comment]
Any news ?

**Comment by quasel** [comment]
so mich has changed ;) 
Sorry for the late reply, feel free to comment if you still have questions!
