### ISSUE TITLE
Custom settings page need css fix

### ISSUE THREAD

**Issue by namaless** [pods-framework/pods#3122]
The current version: http://take.ms/s6giL

Need changes to this:

.pods-manage-field .pods-field-option input[type="text"], .pods-manage-field .pods-field-option select, .pods-manage-field .pods-field-option textarea, .pods-manage-field .pods-field-option .pods-field.pods-boolean, .pods-manage-field .pods-pick-values, .pods-manage-field .pods-field-option .pods-form-ui-field-type-file, .pods-manage-field .pods-slider-field

and remove this 2 settings:

float: left;
margin-left: 22px;

With this modification the options appear ok: http://take.ms/ViHUc

Give this example from wp settings: http://take.ms/B56hQ

**Comment by nicdford** [comment]
I tested this in Chrome/osx 10.10, firefox/osx 10.10, safari/osx 10.10 and wasn't able to recreate. What browser are you using?

**Comment by namaless** [comment]
Chrome: http://take.ms/NmN2X

**Comment by nicdford** [comment]
I tested on chrome/win10 and wasn't able to recreate. Can you make sure there aren't other plugins/code causing the issue? 
![image](https://cloud.githubusercontent.com/assets/7292444/9551388/bae0d7e8-4d65-11e5-9fd0-ee6d3f5dae58.png)

**Comment by namaless** [comment]
I think you not understand, sorry for this, the problem are into custom options page not into metabox.

**Comment by nicdford** [comment]
Ahhh i'm sorry, you're right. I'll make a pull request for this fix.

**Comment by namaless** [comment]
No worries, i put the issue and not a pull request because i don't know where i can fix it, i post the solution without code change, sorry for this.

**Comment by nicdford** [comment]
I made the fix for 2.x in #3124, i'll make another for 3.x release

**Comment by pglewis** [comment]
Fixed in the upcoming 2.7 release
