### ISSUE TITLE
Relationship Post where taxonomy

### ISSUE THREAD

**Issue by blackdragon1** [pods-framework/pods#3127]
Hi there, I've been searching high and low but couldn't find anything that helped.

I've added a field which is a relationship to a custom post type, each post has a taxonomy.
Now let's say I've got 5 posts of type A and when I'm creating a custom post of type B there's a pod field with the relationship to type A, it should appear only 3 posts because it would be filtered by a taxonomy.
I'm only using the UI, I tried using the box "Customized WHERE Clause" but it only queries the post table.
Is there a solution for this, be it via UI or PHP?

Thanks in advance.

**Comment by jimtrue** [comment]
This isn't actually a bug or issue, could you repost on our Support Forum over at http://pods.io/forums/

Thanks!

**Comment by blackdragon1** [comment]
If this isn't possible this issue could be used as new feature request. It's possible in advanced custom fields, so why not in pods?
