### ISSUE TITLE
Constant PODS_VERSION - assumed 'PODS_VERSION' Error when in debug

### ISSUE THREAD

**Issue by chmchm** [pods-framework/pods#3129]
Got this error when I switched into debug after update to WP 4.3 Bille

Constant PODS_VERSION - assumed 'PODS_VERSION' in /blah/wp-content/plugins/pods-frontier-auto-template/pods-frontier-auto-template.php on line 47

**Comment by jimtrue** [comment]
Cross-posted over in the right GitHub Repo for the plugin: https://github.com/pods-framework/pods-frontier-auto-template/issues/30
