### ISSUE TITLE
Detect slow unit tests

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3132]
Might consider
Http://github.com/johnkary/phpunit-speedtrap

**Comment by pglewis** [comment]
Definitely worth a look.  I suspect that finding the slowest tests currently wouldn't be very difficult but this follows my number one rule of optimizing: always benchmark first.

**Comment by sc0ttkclark** [comment]
Let's make it happen :)

**Comment by Ramoonus** [comment]
I don't think this should be integrated with Travis, because it's likely a run once thing?

**Comment by pglewis** [comment]
Thank you #3283.
