### ISSUE TITLE
SUPPORT: filter relationship fields

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3136]
Hi there, I hope someone is able to take the time to help me with this.

Situation:

I have multiple post types and taxonomies created with pods and I would like to filter the available relationships based on taxonomy and other relationships.

I have a type "bands", a type "Events" and a taxonomy "Region".

Both bands and events have this taxonomy and are so linked to a specific region.

And Event can have a relationship to a band that is playing on this event, but this can only be a band which is enabled for the region this event is enabled on.

At this point the bands-relationship will show all available bands. Is it possible to filter this with Pods so the user can only select bands in the region the event is set on?

Thanks! Jory

**Comment by jimtrue** [comment]
Our Support forum is located over at http://pods.io/support/ We only use GitHub for Feature, Enhancement Requests and Bug Tracking. Please repost your question over there. Thanks!

**Comment by JoryHogeveen** [comment]
Ok sorry!

**Comment by jimtrue** [comment]
No worries, just trying to keep our support channels manageable.

**Comment by JoryHogeveen** [comment]
I understand, and could've known that come to think of it.. GitHub is not a support tool.
