### ISSUE TITLE
Grunt Travis matrix generator 

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3154]
See title

As inspired by
https://gist.github.com/Rarst/2f1c5599f7be1256e8a0

**Comment by sc0ttkclark** [comment]
Might have a start here -- https://github.com/arhea/grunt-travis which we could fork to create one for WP based on the one Rarst made via PHP.

**Comment by Ramoonus** [comment]
i think you tackled this issue 2 days ago

**Comment by sc0ttkclark** [comment]
If we use Dockunit.io, we'll want to figure out how best to make a config builder for that instead.

**Comment by Ramoonus** [comment]
let`s put this on hold for the moment

**Comment by pglewis** [comment]
Anything actionable or that needs to be retained from this issue?  Big 'ol GitHub sweep going on.

**Comment by sc0ttkclark** [comment]
Don't think we need this anymore, we fixed the long running Travis tests issue that brought this up
