### ISSUE TITLE
permalink/slug traversal broken for taxonomies in ACTs

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3155]
#2779 
https://github.com/pods-framework/pods/commit/c90acb

**Comment by pglewis** [comment]
Before we patch this, we need to write a failing test since this was not detected by tests.

**Comment by pglewis** [comment]
Candidate fix here: 

```elseif ( in_array( $field, array( '_link', 'detail_url' ) ) || ( in_array( $field, array( 'permalink', 'the_permalink' ) ) && 'pod' != $object_type ) )```

**Comment by pglewis** [comment]
We have a patch together in the feature/3155 branch that's ready to be tested.

**Comment by quasel** [comment]
Did some additional manual Tests e.g 
pods('test')->find()->display('related.author.permalink');
pods('test')->find()->display('related.permalink');
pods('test')->find()->display('author.permalink');
pods('test')->find()->display('related.name');

Seems to work fine -
