### ISSUE TITLE
More Field Design look

### ISSUE THREAD

**Issue by Loncey** [pods-framework/pods#3177]
Hello,
I'm not sure if this is the place, am I able to make a suggestion for a design look of back-end under the "More Fields" in wordpress? Let me know if I'm in the right area to post a suggestion or whether I need to post it elsewhere on pods cms.

Thanks

**Comment by sc0ttkclark** [comment]
In Pods 3.0, we'll be using CMB2 for these fields, so they'll take on the look and feel of CMB2. If you want to help improve the design of CMB2, try https://github.com/WebDevStudios/CMB2/issues
