### ISSUE TITLE
PHP Code Sniffer: implement WordPress-Coding-Standards 

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3181]
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

**Comment by Ramoonus** [comment]
I think this needs a combination of
composer include
php codesniffer
define ruleset(s)

**Comment by pglewis** [comment]
What's the thought here, replacing Scrutinizer with PHP Code Sniffer?

**Comment by Ramoonus** [comment]
@pglewis I`m for, but Scrutinizer uses PHP-CS

**Comment by GaryJones** [comment]
While there are still a good few violations to address, the Pods project does use WPCS, as can be seen in the [config file](https://github.com/pods-framework/pods/blob/2.x/phpcs.xml.dist).

I think this ticket can be closed.
