### ISSUE TITLE
Not allowed to edit my own posts?

### ISSUE THREAD

**Issue by workrbee** [pods-framework/pods#3187]
I just installed Pods on a new site. Not much there yet. Just set up a new set of fields for a pod type, but I'm getting a message below the main WP description field:
> You are not allowed to edit this item.

Can't save it as a draft, can't publish it, and can't edit if I do manage to save something. When I hit Save or Publish, I get this error:
> You are not allowed to edit this post.

I can edit the regular pages and posts without a problem. This seems to be just in Pods.

Suggestions?

**Comment by Ramoonus** [comment]
could you flush the cache
maybe that helps

**Comment by Ramoonus** [comment]
are you an other user rank thank the default?

**Comment by workrbee** [comment]
Thx Ramoonus,
Flushed and disabled cache on server, cache disabled in WP. No change, still not allowed to edit.
I'm the only (admin) user, so rank not an issue.

**Comment by workrbee** [comment]
aha! Pods has it's own cache, which I cleared. 
Also opened a bunch of settings, and now I can add and edit.
Thx again Ramoonus.
