### ISSUE TITLE
Attempting to delete pod from edit page results in fatal error (missing nonce?)

### ISSUE THREAD

**Issue by cpruitt** [pods-framework/pods#3194]
There appears to be an issue with deleting a pod from the pod's edit view. I'm getting three warnings and a fatal error when I use the Delete link in the right sidebar:

```
Warning: Attempt to modify property of non-object in /Users/cpruitt/Sites/pods.cliffpruitt.com/public_html/wp-content/plugins/pods/classes/PodsAdmin.php on line 1804

Warning: Attempt to assign property of non-object in /Users/cpruitt/Sites/pods.cliffpruitt.com/public_html/wp-content/plugins/pods/classes/PodsAdmin.php on line 1806

Warning: Attempt to assign property of non-object in /Users/cpruitt/Sites/pods.cliffpruitt.com/public_html/wp-content/plugins/pods/classes/PodsAdmin.php on line 1807

Fatal error: Call to a member function message() on a non-object in /Users/cpruitt/Sites/pods.cliffpruitt.com/public_html/wp-content/plugins/pods/classes/PodsAdmin.php on line 1809
```

The error prevents the pod from being deleted. I do not receive the error when trying to delete the pod from the delete link within the pod's row in the Manage Pods list view.

The difference I see between the two is that the delete link on the Manage Pods list view has a nonce value in the query string, whereas the delete link in the Edit screen's right sidebar has no nonce. If I use firebug to add the nonce into the right sidebar link, the error is not raised and delete is successfully performed.

(This is on a fresh Wordpress installation with only Pods 2.5.5 core installed.)

**Comment by quasel** [comment]
Can Confirm in my Test Setup
There is more difference ... never investigated this part of pods but seems a bit weird ...

```
<a href="/wp-admin/admin.php?page=pods&action=delete&id=1719" class="submitdelete deletion pods-confirm" data-confirm="Are you sure you want to delete this Pod? All fields and data will be removed."> Delete Pod </a>
```

```
<a href="/wp-admin/admin.php?page=pods&amp;action=delete&id=1719&_wpnonce=a207f6fa3b" title="Delete this item" class="submitdelete" onclick="if(confirm('You are about to permanently delete this item\n Choose \'Cancel\' to stop, \'OK\' to delete.')){return true;}return false;">Delete</a>
```

**Comment by cpruitt** [comment]
This change fixes the issue for me.

https://github.com/cpruitt/pods/blob/feature/3194/ui/admin/setup-edit.php#L823

Does anyone a little more familiar with the rest of Pods want to take a quick look and let me know if this is worth submitting a PR?

**Comment by sc0ttkclark** [comment]
When in doubt, submit a PR. Even if it's a one line fix :) We love one line fixes (keeps it simple!)

Oh hey, are you going to WCUS this year?

**Comment by cpruitt** [comment]
OK, happy to submit. Has the destination branch changed since this the pods contributing info was last updated?

https://github.com/pods-framework/pods/blob/master/CONTRIBUTING.md

At the risk of proving myself to be blind, I don't see 3.0-unstable and don't want to just assume another branch.

Sadly, no Word Camp for me this year. It'd be nice to go and meet some people but it falls right square in the middle of some other stuff I've got going on.

**Comment by sc0ttkclark** [comment]
`release/3.0` (for 3.0) and `2.x` (for 2.5.6) would be what you'd want to do PRs against.

**Comment by quasel** [comment]
@sc0ttkclark never dig into our pods admin and before i do:

Why are the delete links and the Text completelly different for delete from the Manage Pods overview and  the edit screen itself? 

Guess Old code ;) target for refactoring for pods x.x.x  ;)

**Comment by sc0ttkclark** [comment]
Merged for 2.x, still needs a PR on release/3.0

**Comment by sc0ttkclark** [comment]
Great job @cpruitt! MVP of new contributors :)
