### ISSUE TITLE
Caching issue on update meta data

### ISSUE THREAD

**Issue by tuanmh** [pods-framework/pods#3219]
Hi guys, we've noticed this bug since 2.5.3. Basically if you update any Pods field before ``save_post`` hook, the field value won't be updated to DB. For example:

Have a hook on save_post_syllabus with any priority:
```php
add_action('save_post_posttype', array($this, 'testSavePostType'), 10); // e.g. slug change -> effects links in TOC
```

```
public function save_post_posttype(){
    global $post;
    error_log(var_export(get_post_meta($post->ID, 'test_field'), 
    update_post_meta($post->ID, 'test_field', 21);
    error_log(var_export(get_post_meta($post->ID, 'test_field'), true));
}
```

After ``update_post_meta($post->ID, 'test_field', 21);`` ``test_field`` meta value will be updated correctly in DB. However, after save_post_posttype finished, the meta value will be reverted to old value. This is because after this Pods will just use the old value in the POST data to update the database again, please refer to ``save_post`` function.

**Comment by sc0ttkclark** [comment]
We've hooked into the `save_post` action for a while now. The `save_post_{post_type}` action runs before `save_post` does, so that's for sure the issue as you've already described.

The solution would be to either hook into `save_post` at a priority of 11+, or hook into `pods_api_pre_save_pod_item_{post_type}` instead:

http://pods.io/docs/code/filter-reference/pods_api_pre_save_pod_item_podname/

**Comment by tuanmh** [comment]
@sc0ttkclark Yes, you're right - that is what we're doing. Reason we would like to use ``save_post_{post_type}`` is because we have multiple post types and don't really like the idea of having ``if...else`` checking for a specific post type. ``pods_api_pre_save_pod_item_{post_type}`` is also good but it's Pods-specific. 

thanks for clarifying - happy to use ``save_post``.

**Comment by quasel** [comment]
@tuanmh just for educational prposes `pods_api_pre_save_pod_item`does exist too ;) and as soon as 3.0 arrives pods should be aware of all Post types regardless of registering them with pods

http://pods.io/docs/code/filter-reference/pods_api_pre_save_pod_item/
