### ISSUE TITLE
ACT Cannot compare dates with Where parameter

### ISSUE THREAD

**Issue by c0rnbread** [pods-framework/pods#3224]
I'm trying to filter out records from the beginning of the month one year ago today. The following code returns all records. Any ideas?

$day = date('d') - 1;
$beginingOfMonthOneYearAgo = strtotime('-1 year -' . $day . ' days');

$p = array();
$p['limit'] = -1;
$p['orderby'] = 't.date_created';
$p['where'] = 't.date_created > ' . date('Y-m-d', $beginingOfMonthOneYearAgo);

$timesheets = pods('timesheet', $p);

while ($timesheets->fetch()) {

	echo $timesheets->field('date_created');
	echo '<br/>';
	
}

**Comment by sc0ttkclark** [comment]
Date strings should be quoted:

`$p['where'] = 't.date_created > "' . date('Y-m-d', $beginingOfMonthOneYearAgo) . '"';`

**Comment by c0rnbread** [comment]
Thanks Scott, that worked for me. However, when I also check for the id in the where parameter, I get no results, and I expect one:

$p['where'] = 't.id = "' . $_GET['id'] . '" && t.date_created >= "' . date('Y-m-d', $beginingOfMonthOneYearAgo) . '"';

Any ideas?

**Comment by c0rnbread** [comment]
Never mind... I needed to specify client.id instead of t.id.

**Comment by Shelob9** [comment]
Don't forget to verify $_GET[ 'id' ] is an integer.

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
@Josh412 <http://twitter.com/Josh412>
