### ISSUE TITLE
Time Field Shows Date Select

### ISSUE THREAD

**Issue by linchpinstudios** [pods-framework/pods#3225]
We have a custom field setup as a time field. However when a user is trying to select it only shows and filters to a date.

Field Setup:
![screen shot 2015-11-05 at 1 49 58 pm](https://cloud.githubusercontent.com/assets/630868/10982800/434ecfec-83c4-11e5-91c9-5d2bbbe5b8fd.png)

Field Input:
![screen shot 2015-11-05 at 1 49 49 pm](https://cloud.githubusercontent.com/assets/630868/10982806/4a7af6b0-83c4-11e5-8e70-5360e2575ad6.png)

pods version: Version 2.5.5 
Wordpress: Version 4.3.1

**Comment by pglewis** [comment]
Anyone wanna try to reproduce this?  This seems to have gotten lost in the shuffle without a milestone.

**Comment by jamesgol** [comment]
Just tried to reproduced this with Pods 2.5.5 and the latest 2.x branch and could not reproduce.  Maybe a conflict from another plugin?

Maybe a 'Migrate Packages' dump of the Pod would help reproduce here.

**Comment by codente** [comment]
I also cannot reproduce this.

**Comment by JoryHogeveen** [comment]
Me neither

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
