### ISSUE TITLE
Unit Testing: Include different MySQL versions

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3227]
Current one used DB=mysql-5.5
Should include latest stable DB=mysql-5.6
And GA too, but for now DB=mysql-5.7-dmr

**Comment by Ramoonus** [comment]
Followup of #3212

**Comment by pglewis** [comment]
What's the status on this?  You got found in my sweep.

**Comment by pglewis** [comment]
In the past 2-3 years I can't recall a single issue that stemmed from the MySQL version in use.  We stick with `WP_Query` where possible and don't do anything version specific when we do need to go off the reservation.  Not a compelling reason to increase the complexity of testing matix for it at this time.
