### ISSUE TITLE
Losing Value in Relationship Field on Update of Post

### ISSUE THREAD

**Issue by brenew** [pods-framework/pods#3232]
Hello, and thanks for the awesome plugin.

We are having a problem with one of our Pods post types. We have created a type for “Events” and a type for “Event Series”. In the “Events” type, we added a Relationship field that is related to “Event Series”. We can create posts and everything is gravy. However, if we update one of the posts, the last post that was edited/created will lose it’s value for the related field “Event Series”. On the front end it’s a problem because we are filtering by that field, and if it isn’t set then it isn’t shown in the list. Oddly enough, the post that we updated gets replaces the previous item that lost it’s field value.

Link to the frontend page: https://www.fairwarning.com/events/webinars/fairwarning-executive-series-webinars/
Note: the area of concern is the first section under the search bar that contains 6 blocks of webinars.

Have you seen this before and are you able to suggest a fix? In addition, is there anything else I can provide that will help debugging?

**Comment by pglewis** [comment]
Do you have any code involved here?  I'm not personally aware of anything like this being reported, but it's impossible to see every combination people might use.  

Our best bet is always finding a way to reproduce your issue with, of course, the least amount of effort ;).  Boiling down the problem to something we can recreate ourselves is more than half the battle, so if there's anything else you can provide to help in that direction we'll definitely dig into what is wrong.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
