### ISSUE TITLE
PODs Template with if Statement for field as part of a Relationship Field not working

### ISSUE THREAD

**Issue by wmg481** [pods-framework/pods#3237]
So we have 2 content types, one for Learning Center Articles and one for Learning Center Article Types. Both have their own fields and have a relationship field attaching the two.

Learning Center Articles has a template where we want to test if the name field for the Learning Center Article Type is null/empty. If it's not empty it should display a paragraph with the name and icon (both of which are fields that exist on the Learning Center Article Type.

However, when we upgraded to the latest version of the plugin (even before that this was a little sporadic), this if statement no longer works properly and pulls back random values for the label and icon.

We think this is only an issue with bi-directional fields and attempting to apply if statements to fields on the other end of the relationship.

This is either broken functionality or a feature that I would like to request. Not sure which, but was hoping someone could tell me.

Our fix for this was to simply remove the if statement altogether, but then we have empty paragraphs in certain situations (as the name field isn't required, nor does the client want it to be), and this element have a background color.

Attached are the template with the if statement and our debug settings. Someone on our support staff has already tried disabling plugins with no success. Any help would be much appreciated.

[Pods-Debug-Settings.txt](https://github.com/pods-framework/pods/files/38433/Pods-Debug-Settings.txt)

[LearningCenterArticleTemplate.txt](https://github.com/pods-framework/pods/files/38431/LearningCenterArticleTemplate.txt)

**Comment by jimtrue** [comment]
@wmg481 this looks like you've inaccurately defined your if statement in the Pods Template. It's not designed to go after specific values, like taxonomy-type.name, but rather the relationship as a whole, to determine if there are relationships defined within.

You should try `[if taxonomy-type]` instead and see if that works for you. We've got an additional enhancement request to add multiple conditional and equality tests to the if blocks, but for right now, they only detect if relationships exist.

**Comment by jimtrue** [comment]
Not related to If/each EPIC issue #4309 this was more specifically going for conditional related field tests.
