### ISSUE TITLE
pod->duplicate not working

### ISSUE THREAD

**Issue by jlami** [pods-framework/pods#3238]
Hi,

It seems that pod->duplicate is not working because PodAPI::duplicate_pod_item is giving save_pod_item a data array with an ID in it from the original item to be duplicated. This will then update the old item, instead of making a new one. I think `unset($save_params['data']['ID']);` in duplicate_pod_item is enough to make it work correctly.

FYI, to reproduce you might need a pod item without any pod fields, since our system uses pods only to create custom post types, without specifying any extra fields in pods.

**Comment by pglewis** [comment]
Anyone wanna volunteer to verify this sooner that my next loop around?
