### ISSUE TITLE
spatial data

### ISSUE THREAD

**Issue by karneaud** [pods-framework/pods#3240]
Does the plugin handle spatial data?

**Comment by Ramoonus** [comment]
what do you mean?

**Comment by karneaud** [comment]
new to create a custom field type need to store the value as spatial data in a spatial column data type

**Comment by pglewis** [comment]
WordPress primarily works on MySQL and compatible databases so this would be a pretty experimental area, if you're talking about using geospatial database features.  There is an extension for MySQL for it, though, so we shouldn't rule it out.
