### ISSUE TITLE
Edit Pod Template->Pod Reference Recursion

### ISSUE THREAD

**Issue by jkiefner** [pods-framework/pods#3241]
When building a template for a pod with several relationships, the Pod Reference dropdown goes into a nasty recursion loop which will lock the screen and basically render the reference picker useless. I've hacked  function-pod_reference.php to limit recursion to one depth, but this should probably be addressed by your team. Here is how i hacked it:
40:  function pq_tunnel_pod_field( $fields, $prefix = null, $recurse = true ){
70: if( !empty( $field['table_info'] ) && $recurse ){
77: if(!empty($field['table_info']['recurse'])){
78:                      $field['table_info']['recurse'] = false;
79:                       }   
81:		$out = array_merge( $out, pq_tunnel_pod_field( $field['table_info']['object_fields'], $prefix . $name . '.' ,false) );
93:$out = array_merge( $out, pq_tunnel_pod_field( $pod_fields, $prefix . $name . '.',false) );

Thanks.
Jamie Kiefner

**Comment by pglewis** [comment]
This one just sitting here, assigning it to 2.6.1 just so it gets looked at

**Comment by pglewis** [comment]
Gonna mark this as a dupe of #3370
