### ISSUE TITLE
Related child rows are lost when saving master entity

### ISSUE THREAD

**Issue by virgiltrasca** [pods-framework/pods#3252]
Please see attached.

2 related ACT entities customers and transactions. 1 customer can have multiple transactions. 
I linked/related transactions to customers as per the attached. I assign transactions to customers through the wordpress pod's generated admin GUI.

When I go in wordpress admin GUI (automatically generated by pods) to edit a customer and I save (I change something not related with transactions) the list of corresponding transactions is emptied out. Basically transactions for the saved customer vanish out.
![fields-definition](https://cloud.githubusercontent.com/assets/8201251/11610280/fa71f564-9b9d-11e5-99bd-8f903d6e306e.png)
![replicate](https://cloud.githubusercontent.com/assets/8201251/11610329/f35a01de-9b9f-11e5-9b3e-6ecff05d75ff.png)

------------------------------------------------------------------------------------------------

There is a piece of custom plugin code which is trying to disable editing of transactions in the customer entity (show transactions as read only while viewing a customer) - I'm not sure if this code is interfering. Here is the code.

//////////////////////////////////////////////// Disallow transactions changing in CRM->customers->edit customer 

add_filter( 'pods_form_ui_field_pick', 'disallow_relationship_fields', 10, 6);

function disallow_relationship_fields($output, $name, $value, $options, $pod, $id){

	if ($name == "pods_field_transactions") {

			$output = "No Transactions";

			if (is_array($value)) {
				 	$output = "";
				 	foreach ($value as $one_value) {
						$transaction_pod = pods( 'transactions', $one_value);
          	$output .= $transaction_pod->field( 'name' )."<br>";
    			}
			}

	}
	return $output;
}

**Comment by quasel** [comment]
First and easy test - deactivate cusotm Code and take a look if it works 
Did never touch this part of Pods but if it is just about deactivating the ability to edit the field in the Customer pod just go to the Advanced Tab of your field -> restirct access -> make field "Read Only" in UI

**Comment by virgiltrasca** [comment]
Hi,

Thank you for your help.

I deactivated the custom code and now works fine. So this was indeed the reason.
However I will open another case that the ""Read Only" in UI" option it's not available for the relationship fields. This was actually the reason why the custom code was written to compensate for the missing "Read Only" in UI option.
