### ISSUE TITLE
Issues with orderby 'order ASC' in findRecords > find calls

### ISSUE THREAD

**Issue by tomherold** [pods-framework/pods#3254]
I switched to PHP7 yesterday and have since then mysql database errors related to pods. Have you tested the latest version with PHP7?

**Comment by sc0ttkclark** [comment]
Yes, we've been testing on PHP7 and HHVM for a while now. Our tests run lightning fast on them and have had no failures. What errors are you seeing?

**Comment by tomherold** [comment]
Hello Scott,

I posted on error on the forum - here it is again:

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
	LIMIT 0' at line 14 for query SELECT
	
	DISTINCT
	`t`.*
	FROM `wp_posts` AS `t`
	
	LEFT JOIN `wp_postmeta` AS `order` ON
	`order`.`meta_key` = 'order'
	AND `order`.`post_id` = `t`.`ID`
	
	WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "forces" ) )
	
	
	ORDER BY ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
	LIMIT 0, 10 made by do_action_ref_array, ewf_create_report3, Pod->__call, Pods->find, PodsData->select, pods_query, PodsData::query, QM_DB->query



Maybe you can give me a hint what’s wrong...


cheers

Thomas Herold

Social Entrepreneur, Founder & CEO Evolving Wealth Foundation

tom@evolvingwealth.org <mailto:tom@evolvingwealth.org> / http://www.evolvingwealth.org <http://www.evolvingwealth.org/> / @evolvingwealth

**Comment by sc0ttkclark** [comment]
What is in your ewf_create_report3 code?

**Comment by tomherold** [comment]
Scott, can I send this in private?

**Comment by sc0ttkclark** [comment]
Sure, scott@pods.io

**Comment by tomherold** [comment]
Thanks, just sent it to you...

**Comment by sc0ttkclark** [comment]
I think the issue stemmed from your orderby:

`$params = array( 'orderby' => 'order ASC', 'limit' => 10);`

I changed this to:

```php
$params = array(
	'orderby' => 't.menu_order ASC', // was 'order ASC'
	'limit' => 10,
);
```

**Comment by tomherold** [comment]
Hello Scott,

Thank you for checking on this and also cleaning up my code. Looks like I used some old pods statement as well as some incorrect statements. The code runs fine now.

Thanks again Scott!

Thomas

**Comment by tomherold** [comment]
Hello Scott,

I have another incident which I can’t solve. The field of this pod is called ‘order’ and is meta based (custom post type). What’s wrong with this statement? Causes a database error.

	$params = array(
		'orderby' => 'order.meta_value ASC',
		'limit' => 10
	);


cheers

Thomas

**Comment by jimtrue** [comment]
@tomherold You really shouldn't be sending support questions into GitHub. I saw you opened this as a forum post and then also opened it here. If it's an emergency and you're needing very fast support, you should be joining us on Slack Chat at http://pods.io/forums/chat/

**Comment by tomherold** [comment]
Sorry, deleted it already. Emailed from the wrong place...
