### ISSUE TITLE
Replace `register_api_field()` with `register_rest_field()`

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#3266]
See: https://github.com/WP-API/WP-API/pull/1824

**Comment by Shelob9** [comment]
@pglewis Doing a find and replace should solve both issues-- make work with new function and prevents it from working with older versions of the rest api plugin. There is a notice in admin when it doesn't load about what version is required, that needs update to 2.0-beta9

**Comment by sc0ttkclark** [comment]
Fixed
