### ISSUE TITLE
PODS pods_api_post_save_pod_item_{item} not working

### ISSUE THREAD

**Issue by sandhya09** [pods-framework/pods#3268]
Hi,

Im writing a piece of code where I while saving one pod item i have to update hidden field in it.
Is this possible with this filter?
I have use simple pods from post.I have to use this for gallery/portfolio item.
Below is the code

<?php
add_filter('pods_api_post_save_pod_item_galleryitem', 'add_data', 10, 3);
function add_data($pieces, $is_new_item ,$id){
     wp_die( '<pre>'.print_r( $pieces).'</pre>' );
          die('here in function');
//I have to add more data here
            return $pieces;
}
?>
Please help me with this.

**Comment by sandhya09** [comment]
You can close this issue I  have found solution.
Thank you very much!

**Comment by jimtrue** [comment]
What was your solution?
