### ISSUE TITLE
How to use "{@post_mime_type}" magic tag ?

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3272]
How to use it ? Documentation and Google have nothing about it.
What needs to be added and how to show image attachments, or PDF attachments, or whatever ?

**Comment by jimtrue** [comment]
Please don't use the GitHub for Support, @StaggerLeee. Please either open a Forum Topic at http://pods.io/forums/ or join our Slack Chat at http://pods.io/forums/chat/ to ask Support questions. Github is only for Feature Requests and Bug Reports.

**Comment by StaggerLeee** [comment]
It is more complaint about missing documentation for {@post_mime_type}. Nowhere it is mentioned.

**Comment by jimtrue** [comment]
https://codex.wordpress.org/Function_Reference/get_post_mime_type

It contains the values listed in that Codex Article if the file is an attachment. This is a Post Meta field. We don't do anything specifically with it; it's up to your code to figure out how you'd use it. We don't typically mention the already documented Post Meta keys that have nothing to do with Pods. We don't use them for File attachments, etc, we handle those with pods_image or the other WordPress Image functions.

**Comment by StaggerLeee** [comment]
I still dont get it what is purpose of this magic tag. Why it is there.
Can explain with real example.

- Have Pods CPT = Gallery
- 3 Posts with attached images and featured image
- Added 2 Pods widgets (single and multiple Posts)
- Made Pods template with this magic tag and nothing.

Why it is there ?

**Comment by jimtrue** [comment]
See the note above regarding Image Meta Tags. We report the values of ALL post-meta in magic tags. That's what the "purpose" of the magic tag is. See the codex also referenced, that's what is reported in that particular postmeta. There is no "real example"; we provide the window into all the post and post meta values; again, it's up to you to decide if you need it or not. 

For displaying file or image attachments, you often don't need them, use the ._src or ._img magic tags referenced in Using Magic Tags above: http://pods.io/docs/build/using-magic-tags/, which has several examples of how they're used.

**Comment by StaggerLeee** [comment]
Thank you. I was not specific enough. I am looking for a way to list attachments from one Pod but exclude featured image, as it is often already in gallery.

Will open topic at forum about it.

**Comment by jimtrue** [comment]
Thank you, that's the appropriate place for questions or on our Slack Chat. You might not be able to do what you're looking for in Pods Templates with Magic Tags, but that should be fairly easy with PHP by grabbing the ID of the Featured image (post_thumbnail) and when listing attachments just check for that particular ID.
