### ISSUE TITLE
write_handler in PodsRESTHandlers.php is not getting 'id' and 'type'

### ISSUE THREAD

**Issue by zevenbergm** [pods-framework/pods#3278]
Hi,

Thanks for making this nice PODS framework! 

I've a quick question: Is the validation (e.g. required field) working using the new REST feature? If that is not the case: What is the best option to get it working? Adding a custom controller? Or do you have any other ideas?

Regards,
Martin

**Comment by zevenbergm** [comment]
After some debugging I changed the subject of this issue. 

It seems that the write_handler function is grabbing the wrong variables 'id' and 'type'. I modified the code as follows:

OLD:
$pod_name = pods_v( 'type', $object );
$id = pods_v( 'id', $object );

NEW:
$pod_name = pods_v( 'post_type', $object );
$id = pods_v( 'ID', $object );

After this change the fields are updating and validation is applied. Cool! However, I'm not sure if this i what you initially intended...

**Comment by pglewis** [comment]
I haven't dug into this one yet but will soon.  Can you give me a boiled-down Pod configuration to reproduce the issue?  Does it manifest with a post type Pod with a single required field?

**Comment by quasel** [comment]
fixed!
