### ISSUE TITLE
Error on extended CPT Relationship Fields queried by REST API

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#3280]
PHP Fatal error: Call to a member function fields() on a non-object in /home/ubuntu/wordpress/wp-content/plugins/pods/classes/PodsRESTHandlers.php on line 69

Reported here: https://github.com/pods-framework/pods/pull/3184#issuecomment-159921920

**Comment by pglewis** [comment]
`$related_pod = $pod->field( $field_name, array( 'output' => 'pod' ) );` appears to be returning an array instead of a Pod object as expected.

**Comment by pglewis** [comment]
Calling `field()` this way is always going to return an array of `Pods` objects, one for each value in the related field (can me multiples with multi-select).

**Comment by pglewis** [comment]
@arikogan, @jaavid

**Comment by arikogan** [comment]
Thanks for the heads up @pglewis

**Comment by brad-decker** [comment]
Maybe not the testing you're looking for, but this fixed pods rest api for me so that I could check the "show all fields" box and didn't have to go into each field and specify only name/id for relationships

**Comment by pglewis** [comment]
The patch gets rid of the error, but I think relationship fields in general needs a pow-wow discussion on how we should implement them.  With relationship fields being somewhat unique to Pods I'm not sure what would be the most standard way of exposing them via the REST API just yet.

**Comment by brad-decker** [comment]
Cool, well when that discussion comes up something to consider is predefined relationships like states returning both abbreviation and full state name.

**Comment by pglewis** [comment]
I'm opening up #3342 for brainstorming on this topic, feel free to include anything there you think we should consider for implementaion.

**Comment by grandgeorg** [comment]
This is a mager issue for me. I can not use biderectional Field binding with REST API in pods. The worst thing ist that in file PodsRESTHandlers.php on line 78
```
$related_pod = $pod->field( $field_name, array( 'output' => 'pod' ) );
```

$related_pod can be an object, an array of objects or a boolean ```false```! With bidirectional binding it is an array of pod objects or a boolean ```false```. Both lead to a fatal error of course (as in line 79 it is treated as an object). It's even hard to figure out under which condition a boolean and under which an array of objects is returned. I have e.g. a relationsship between pods [books] and [authors] where, if querying authors, ```false``` is returned (although each author has books assigned) and I have another relationsship between pods [bands] and [albums] where if querying bands an array of pods objects (with albums) is returned. Both relationships have the same settings (REST API Settings for whole pod: Enable - Yes, Show All Fields? - Yes).

**Comment by quasel** [comment]
Looking at the code this should be fixed! including some filters explicit fro relations…
