### ISSUE TITLE
Disable xdebug on Travis

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3283]
HHVM on Travis is running without xdebug and is somewhere in the neighborhood of 13,000% faster than any of the other PHP instances there.

**Comment by sc0ttkclark** [comment]
Related https://github.com/sonata-project/SonataPropelAdminBundle/compare/f30da4319b9a9263d0028a90fb8f982e96474f14...da78f3ea4698aea35a73ab5dd36dbde0c9951bce

**Comment by sc0ttkclark** [comment]
Fixed expertly via #3284
