### ISSUE TITLE
Pods template "<p class="

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3295]
Why Pods treats this snippet as invalid ?

P class is outside and empty, all pods content is too outside "p" tag. Template editor marks closing P tag as red/invalid.

&lt;p class="bg-warning"&gt;
&lt;h6&gt;&lt;a href="{@permalink}" title="{@post_title}"&gt;{@post_title}&lt;/a&gt;&lt;/h6&gt;
&lt;i class="icon-map-marker"&gt;&lt;/i&gt; {@location}
&lt;i class="icon-calendar-simple"&gt;&lt;/i&gt; {@date_time}
&lt;/p&gt;

**Comment by pglewis** [comment]
The HTML specification does not allow headings inside a paragraph.  It makes no sense semantically, but more importantly: browsers are normally going terminate paragraph tags the moment they see a heading because they try to make the best sense they can out of bad HTML.  Either use a generic div instead of a paragraph or switch to tags that are allowed in a paragraph.

**Comment by sc0ttkclark** [comment]
This is outside the scope of Pods itself, the issue comes from the WP Editor and/or any potential wpautop functionality running.

**Comment by StaggerLeee** [comment]
Scott, it it code inside Pods template editor, not TinyMce.

**Comment by pglewis** [comment]
The problem is your HTML is invalid, as I outlined above.  Try a Google search for "HTML heading inside a paragraph tag"

**Comment by StaggerLeee** [comment]
@pglevis, thank you. Make sense. Same is with p tags inside this p tag. (when H tag is removed) 
Are not nested paragraphs allowed by standards ?

**Comment by sc0ttkclark** [comment]
Pods Template Editor uses TinyMCE / WP Editor.

**Comment by pglewis** [comment]
Yeah, no nested paragraphs either for the same reason: a paragraph in a paragraph has no semantic meaning.  Best to just change to a div in your template, that's just a generic "box" without the semantic meaning to it.

**Comment by StaggerLeee** [comment]
I will, pglewis, not so big deal. Using Bootstrap theme and try to use CSS code lines already inside, to not to duplicate CSS code unnecessary.

Best to use <div> as block-level elements, but hate this for a reason I dont know why. Now I see even this is not valid. Remains <br> as block elements, but hate them too. :)

**Comment by jimtrue** [comment]
@StaggerLeee Look at your semantic HTML5, there might be a block level element that works for you, ie aside, etc. that fits semantically what you're trying to do. Regardless, this is outside of scope for Pods. so we're closing and locking this one for comment.
