### ISSUE TITLE
Flexible Relationships - New relationship input, based on File Upload input

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#3311]
Prerequisite: #3309, #3334

This new Flexible Relationship input would allow you to 'Add New', 'Select from Existing', Reorder, and Remove related items. Support for showing a thumbnail (if related to a post_type object type and has featured image support, or if user object type we can use avatar).

**Comment by pglewis** [comment]
#3334 is probably the roadmap to this

**Comment by pglewis** [comment]
This is all taking place as part of 2.7.  I'm going to be migrating the tasklist items over and close this issue to avoid confusion.
