### ISSUE TITLE
Simple Relationship Storage

### ISSUE THREAD

**Issue by ConneXNL** [pods-framework/pods#3315]
Simple Relationship Storage enables single-select relationships to be stored in the same ACT table (or any table-based Pod) instead of storing the relationship in wp_podsrel. This enables quicker operations in some cases, and table indexing on this field for lookups as well. Traversal can still possible through normal syntax.
## Tasklist
- [ ] Add 'Enable Simple Storage' option for pick field, only available for single (not multiple) select pick fields
- [ ] On save, store in field like normal non-pick fields would, if simple storage is enabled for field
- [ ] On traversal, join on normal field (new), if simple storage is enabled for field (also look at enabling post_author traversal #1694 at same time since it's the same spot in the code)
- [ ] On value get, don't look in podsrel, look at normal non-pick field

---

Original message:

I was looking for a way to prevent the use of wp_podsrel and store the relation id in the table itself. For example:

Chapters

---

chapter_id
name
book_id

In the following discussion it was mentioned that something like this would come in pods 2.3:
https://wordpress.org/support/topic/how-to-insert-value-of-relationship-field-into-database

However, I couldn't find the feature yet. Was this feature added? Are there any workarounds?

**Comment by quasel** [comment]
currently not yet, question is why you want to do it this way - workaround might be to use a filter to store the info additonaly in a colllumn.

**Comment by ConneXNL** [comment]
I was thinking about using Pods to make admin functionality for an existing application that uses "normal" tables.

**Comment by quasel** [comment]
for now a workaround as already mentioned can be use the filter: http://pods.io/docs/code/filter-reference/pods_api_pre_save_pod_item_podname/  

1) add Relationship field
2) add collumn book_id
3) use the filter to store the information from 1) into 2) 

just wont work if the data is additonal manipulated elsewhere ... if you need to import data you could do the same by iterating over all pods and just saving the relationship programmatically

**Comment by sc0ttkclark** [comment]
We've been searching for the feature request I put together for this but can't find it anywhere. We started on a solution for it in Pods 3.0 but it wasn't complete. I'll come back around on this issue and make it more official this weekend.

**Comment by sc0ttkclark** [comment]
I just updated the original issue with a better title / description and added some tasks to make it clear what we need to do

**Comment by quasel** [comment]
should we add an automated way to change to simple related storage? ( just add a collumn, save value from podsrel, delete row from podsrel ) ?

**Comment by sc0ttkclark** [comment]
Changes like these are difficult, I doubt we can show this option except when adding the field initially it feels like.

**Comment by quasel** [comment]
even in this case? maybe i did miss an important point ^^

**Comment by sc0ttkclark** [comment]
Any db migration that can potentially involve tables with a ​*lot*​ of rows needs a better solution for migration. Same reasoning behind switching a Pod storage type from meta >> table or table >> meta, among other things.

**Comment by sc0ttkclark** [comment]
I implemented this as part of a new Pods Pro add-on https://pods-pro.skc.dev/downloads/advanced-relationship-storage/ that I worked on which relies on Pods 2.8
