### ISSUE TITLE
How to get fields from custom settings page?

### ISSUE THREAD

**Issue by andre2** [pods-framework/pods#3332]
I create pod custom settings page, with name "my_set" and 3 fields, "text_1", "text_2", "text_3".
How i can get this settings in theme header?

**Comment by jimtrue** [comment]
This is a support question, not a bug or feature request. Our GitHub is *only* for Bug and Feature requests. To open a support question, head over to our forums at http://pods.io/forums/ or you can join our Slack Chat at http://pods.io/forums/chat/ and ask a question there.

Thanks - Jim
