### ISSUE TITLE
Pods list items with magic tags in widget pods-list items

### ISSUE THREAD

**Issue by espiat** [pods-framework/pods#3337]
I made:
1 Pod "Beispiel Pods" as Custom Post Type (i created 4)
1 Custom Taxonomy named "Places" (hierarchical and related to associated post types: Beispiel Pods)

then: 
- add new widget "Pods - list items"
- code in Custom template 

```
<li><strong>{@title}</strong> ({@place})</li>
```

naturally before `<ul>` and after `</ul>`

problem: 
if the taxonomy has more then 2 items the syntax will display
item 1, item 2**, and** item 3

it should be: 
item 1, item 2 **and** item 3 (without the comma)

image:
![unbenannt](https://cloud.githubusercontent.com/assets/6573582/12221526/d0836784-b79e-11e5-867c-d127fca3be09.JPG)

**Comment by jimtrue** [comment]
I can verify this one on Custom Taxonomy **and** on Relationship fields. You get ", and"

**Comment by jimtrue** [comment]
This isn't actually a 'bug', this is a Serial Comma and is considered proper format by the Oxford English Dictionary:

https://en.wikipedia.org/wiki/Serial_comma

However, it might not be a bad thing to give people some options in how they want their 'lists' displayed.
