### ISSUE TITLE
Visual Changes to 2.7

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods#3341]
- [x] change out the trash icon to a red X (to replace the trash can, for "remove" implication, not "delete" implication, check the show file link/download option for another icon to be consistent with in the UI)
- [x] margins collapse on file upload field when multiple are used in an row

make against: feature/3334-file-upload-rewrite

**Comment by pglewis** [comment]
Got a new one for you here on the text input if you allow editable title and shrink the window width enough:

![editable-title](https://cloud.githubusercontent.com/assets/1973916/12975594/ef7e6e72-d08a-11e5-91ae-00c050712c60.png)

**Comment by pglewis** [comment]
Checkboxes also a bit wonky at a narrower width:

![multi-checkbox](https://cloud.githubusercontent.com/assets/1973916/13128969/d6182b7c-d5a7-11e5-9b7d-e3e3921e902d.png)

**Comment by nicdford** [comment]
From what I can tell the text input issue seems to be fixed on the `feature/#3364-2.7-Feature-Release` branch so the #3444 PR should close out this issue unless there is anything else you want to add :)
