### ISSUE TITLE
Exposing relationship fields to the REST API

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3342]
Details to be discussed here

**Comment by brad-decker** [comment]
Simple relationship fields, such as predefined relationships (states), should provide a way to either define what is returned via rest api calls in the case of custom relationships added via code, or should return things like state name/abbreviation/etc for predefined states.

**Comment by brad-decker** [comment]
Add another option to go with full that limits the returned results to fields we actually require for whatever function we are running.

**Comment by Shelob9** [comment]
@brad-decker Currently you have the option -- from the UI -- for a relationship field to show nothing, the related item id(s), post title(s) or the full related item object.

To provide greater control over what relationship fields return we have two filters. One for limiting the number of fields returned and one for limiting the traversal depth. See: 

https://github.com/pods-framework/pods/blob/master/classes/PodsRESTHandlers.php#L75-L103
