### ISSUE TITLE
Permalink Structure 404 Error Upon Save of Pod

### ISSUE THREAD

**Issue by robbiereynolds** [pods-framework/pods#3345]
Situation: 1 ACT Pod (brand_location) & 1 CPT (location) with 2 taxonomies (city) (state)

brand_location: single select bi-directional relationship field to CPT location
location: single select bi-directional relationship field to ACT brand_location

URL structure: domain.com/location/state/city/location-name (works!)

Plugin to create custom URL structure: Custom Post Type Permalinks (https://wordpress.org/plugins/custom-post-type-permalinks/)

Upon save of brand_location edit pod screen, the URL structure stops working and 404 errors. Flush rewrite rules and permalinks work again.

**Comment by jimtrue** [comment]
This actually had to do with the Custom Post Type Permalinks plugin and not Pods. Once the plugin was deactivated saves, etc. worked as expected.
