### ISSUE TITLE
associated taxonomies to be fetched via magic tags not being displayed in 2.6

### ISSUE THREAD

**Issue by zoomwebstudio** [pods-framework/pods#3348]
Hello, 

A friend of mine encountered an issue with the display of the taxonomies using the magic tags in the new 2.6 version. 

After readings I discovered that this issue was solved in 2.5.2 version according the release notes : 
** "* Fixed: Issue preventing associated taxonomies to be fetched via Pods::field() and therefore magic tags." **

Could take a lot at it please?

**Comment by jimtrue** [comment]
Can you give us a few more details in order to replicate what you're seeing as not working? You've actually not given us any information above.

**Comment by zoomwebstudio** [comment]
Ok sorry,

There is a post type called "voyage" with 4 related taxonomies : "compagnie, trajet, heurededpart, tarif" all created with pods.

So with magic tags, flights are displayed in a table with this code : 

<table class="flight-table">
<thead>
<tr>
<th>Numéro de voyage</th>
<th>Compagnies / Agences</th>
<th>Trajets</th>
<th>Heure de départ</th>
<th>Tarifs</th>
<th></th>
</tr></thead>
<tbody>
[pods name="voyage" orderby="post_date desc"]
<tr>
<td>{@post_title}</td>
<td>{@compagnie}</td>
<td>{@trajet}</td>
<td>{@heurededpart}</td>
<td>{@tarif}</td>
<td><a class="more-link" href="{@permalink}">Acheter un ticket »</a></td>
</tr>
[/pods]
</tbody>
<tfoot></tfoot>
</table>

On 2.6 no value except those called with {@post_title} and {@permalink} are displayed. But When we roll back to 2.5.2, values are displayed.

**Comment by jimtrue** [comment]
I'd have to disagree with you there; I'm looking at a Pods Template right now on Pods 2.6 that is both handling the inline taxonomy output {@taxonomy_name}, which outputs to 'red, blue and yellow' style and it also works with [each taxonomy_name]{@name}[/each] to traverse the taxonomy.

Look at possible conflicting plugins, disable everything except for Pods and one of the default themes and make sure you clear the cache under Pods Admin, Settings, Clear Cache.

**Comment by zoomwebstudio** [comment]
Ok, I will try...
But as I said with the 2.5.2 version the code above works for me ..

I will follow your guidances and post an update

**Comment by jimtrue** [comment]
We've had several versions between 2.5.2 and 2.6, including 2.5.5 which specifically addressed taxonomy issues in templates.

**Comment by jimtrue** [comment]
@zoomwebstudio any update?

**Comment by jimtrue** [comment]
This sounds like the clearing pods cache issue that specifically prevents taxonomies from displaying in Pods Templates until the cache is cleared. Original poster has not returned with an update so closing. Related to #3401 for eventual fix on updating Pods.
