### ISSUE TITLE
Enhancement Request: Add search box to the relationship field checkboxes/select format

### ISSUE THREAD

**Issue by fbg13** [pods-framework/pods#3350]
Hello!

A little suggestion, add a search box to the relationship field, checkboxes/select format.
When having many items it takes a lot of scrolling.
Something like this https://silviomoreto.github.io/bootstrap-select/examples/#live-search.

**Comment by pglewis** [comment]
This is something that's already on our radar with some of the field redesign work that's starting in 2.7.  

Until that arrives the Autoselect (select2) field type is often an acceptable solution when you have a lot of related items to choose from.
