### ISSUE TITLE
X Theme Cornerstone Plugin?

### ISSUE THREAD

**Issue by punkwaffle** [pods-framework/pods#3352]
Any plans on writing a Cornerstone plug-in for the X Theme (the fastest and most popular WP theme on themeforest.com)?

There's a fanatical user community around X (myself included) and it would be great to do what you have done for Conductor for X as well.

**Comment by jimtrue** [comment]
Very doubtful. We didn't write the interface for Conductor; Conductor did that themselves. X Theme would have to write the interface to Pods, not the other way around, or you can take this on yourself. We don't write interfaces to specific themes; we just don't have the resources for that.

**Comment by sc0ttkclark** [comment]
I went ahead and reached out, just in case there's something we can piggy back off of. Otherwise, we definitely don't have the resources to build something for it from scratch.
