### ISSUE TITLE
error with date function in pods field

### ISSUE THREAD

**Issue by oldskier** [pods-framework/pods#3356]
There is a definite little issue with  using the date function in pods fields.  While there are several possible date formats available, if the format to show only the year is selected, it will not actually enter a date, unless a full date is selected, day-month-year. What it does do, if all three are not used, is it generates a date of all zeros,, which cannot be seen, unless you check the settings in custom fields.  I had set  up a list of project details with a field labeled date completed, using if and each so that if no date was selected, (the project was ongoing, )nothing appeared.  I had someone adding data to all the entries, and they didn't know how to set the date. So, it shows up as year completed, with a blank. If I enter the date correctly, it works  This is going to be very confusing for client. The only way I have figured out so far, to correct a bad entry is to find the field using the WP custom fields, and clear the entry.

Michael Jamison [7:02 PM] 
![date error display](https://cloud.githubusercontent.com/assets/13236543/12436820/787b5af2-bee6-11e5-83d7-ba5c4de5429b.PNG)
![date error](https://cloud.githubusercontent.com/assets/13236543/12436823/787db2ca-bee6-11e5-8834-d9a875ed9b3b.PNG)
![date field form](https://cloud.githubusercontent.com/assets/13236543/12436824/787f440a-bee6-11e5-88cf-0313fd81cef6.PNG)
![date options](https://cloud.githubusercontent.com/assets/13236543/12436821/787d7800-bee6-11e5-9e05-125b44b9af66.PNG)
![pods date template](https://cloud.githubusercontent.com/assets/13236543/12436822/787d9f1a-bee6-11e5-84f9-0d1613c3e677.PNG)

**Comment by sc0ttkclark** [comment]
I ran into the year issue on another project myself this past month but worked around it by changing my field to a number field (no decimals) which worked great.

I was thinking we might just not show datepicker for the year option and use `YEAR` for the SQL column schema. Date formatting would just enforce digits `$date = str_pad( (int) $date, 4, '0' );`

**Comment by oldskier** [comment]
Thank you for your reply.

Here is what I suggest for Pods. This is offered as positive advice, not in
anger.

1. state right up front, that the  conditional statements in pods templates
are limited and specify what those limitations are. The will not work with
any sort of numerical field. (or, make them so they will.)

2. Change the field for images, to show only images, not files and video.
Explain in the documentation what is needed in order for Pods to display
video, or embedded video.

3. There is a section that Josh wrote specifically regarding Pods use in
Genesis. In it, he states that Pods integrates well with Genesis. That
needs to be amended, to say that Pods templates do not always work well
with Genesis archives, that the line of code genesis-cpt-archives-settings
needs to be added in advanced settings, the code snippet needs to be added
to the taxonomy archives to pull in the pods template.

4. state up front, in the documentation, that the pods filters are not the
best. (I struggled with these, brought it up in the support group, and
then, several days later I lurked a conversation that Jim True had with
someone else, in which they both said they prefered Beautiful taxonomy
filter plugin to the pods filters. That would have saved me a half a day of
time.

5. there seems to be an problem, that is not just with Pods, but other apps
that create CPTs, with the priority. I don't fully grasp it, but I know
that it is the root issue with Visual composer not being able to use field
values created in a Pods CPT and it's a problem that runs interferes with
other programs.

As to the complexity of my sites and the coding required:
I do use other means to code besides Pods templates. I have tried to use
them from time to time because they can be made very quickly, So for
something simple, such as the issue that initiated this, it's much faster
than writing or even altering a php template. A jobs opening page with just
three fields, all of them simple text, just a UL, no conditionals, in a div
with a class.  is pretty basic stuff.

What I DO, find annoying is that all of the things I mentioned here, have
been known to the Pods developers but not made public. That is an
incontrovertible fact.

It's one thing to find a bug. I do know all about bugs in programs. My
brother in law, who has been like a much older big brother to me, graduated
with a degree in computer science way back in 1962. He used to sometimes
take me to work with him, and I got to see IBM mainframes that took up
entire floors of buildings running reels of tape. (I think my phone has
more computing power than that whole floor did.) He gave me computer kits
for christmas and birthdays. He was one of the team that wrote the military
precursor language to html.
My brother writes missile guidance programs.
I learned to write fortran programs on punch cards in college.
 You can imagine the conversations at Thanksgiving dinners.
So, sure, bugs are baffling. The good thing is, there is always a logical
 reason for them.
But it is annoying, when you run into one and spend time on it, only to
discover later that it was known about and nobody told you.

I think that for many of the members of the pods support group, they are
using pods in very advanced ways. I think that probably Pods work very well
for what they are doing. I also think, that they tend to not think much
about the Pods templates anymore, and dismiss my issues as newbie problems
. Which, I suspect, is the root of this; perhaps it's time to decide what
Pods are going to be- an advanced plugin for developers, or a simple way
for novice site builders to use CPTs and template them?

**Comment by sc0ttkclark** [comment]
Sounds like you replied to our public github on an unrelated topic, I deleted your post but I'll reply to you privately via e-mail for follow-up :)

**Comment by quasel** [comment]
The Date input has changes since this to allow for custom formats - I still find it a bit weird to select a full date but it does the job now to display only the year in edit and frontend!
