### ISSUE TITLE
WP REST API error when adding new post meta data to a pod

### ISSUE THREAD

**Issue by okrg** [pods-framework/pods#3362]
I am trying to use the new integration between Pods and WP REST API v2. I am using all the latest versions of plugins.

I have a pod type called sprtid_profile that contains information about a person.

My partner is creating a REST client that will externally create and update data on these pods from another website.

Here is how we do it:
1. Authenticate and get an oauth token
2. Create a new post for the pod like this: 
   `POST <http_host>/wp-json/wp/v2/sprtid_profile?access_token=<oauth_token>`
   Response contains new post ID.
3. Use the post ID to create my pod field values: 
   `POST <http_host>/wp-json/wp/v2/posts/<post_ID>/meta?access_token=<oauth_token>&key=first_name&value=Johnny`

Response is an error from the WP REST API 
`Fatal error: Call to undefined method WP_Error::set_status().`

It works totally fine however, and the meta value is added to the post. And everything else looks good. It just seems that an unexpected WP_Error is being thrown and there is no condition for catching that properly.

In debugging:/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-meta-controller.php
I found the WP_Error is being created by line 201:
`return new WP_Error( 'rest_meta_invalid_id', __( 'Invalid meta id.' ), array( 'status' => 404 ) );`

I traced this back to line 394:
`$mid = add_metadata( $this->parent_type, $parent_id, $meta_key, $value );`
I discovered that the $mid returned is the exact same as the parent id. Instead of the meta row id.

Someone mentioned something very similar to this in a closed WP-API issue:
https://github.com/WP-API/WP-API/issues/1294

They mentioned it was suspicious that the post id and mid are the same and traced it back to the add_post_metadata filter in Pods. In the end their solution was to NOT USE PODS. Which is not a real solution for me.

Please let me know what I can do to get around this. It’s not a critical or fatal error since it still “works” but I would like to get it to send the right response so we can have some kind of sane error checking in our REST client.

**Comment by jimtrue** [comment]
Referred over from this forum post: http://pods.io/forums/topic/wp-rest-api-error-when-adding-new-post-meta-data-to-a-pod/ since this is definitely a bug.

**Comment by Shelob9** [comment]
This is not a bug. To update a post meta, use the endpoint for that meta ID or enable updateing the field via the post endpoint for this CPT. I'm assuming that `sprtid_profile` is the name of the meta field. So either find its meta ID and use `wp/v2/meta/<mid>` or set `sprtid_profile` to be writeable via the CPT endpoint.

**Comment by okrg** [comment]
@Shelob9  This issue occurs when creating new post meta.   Not when updating.  When I am trying to write the value for the first time and there is no known mid I am getting this error response. In my example, the pod is named `sprtid_profile` and the field is `first_name`

**Comment by pglewis** [comment]
Until we figure out what's up, as a temporary band-aid you might be able to prefex the `add_metadata` call with `pods_no_conflict_on()` and follow it with `pods_no_conflict_off()`.  I believe you'd give it the custom post type's name as the `$object_type` param.  That would bypass Pods' hooks for that call.  

http://pods.io/docs/code/general-functions/pods-no-conflict-on/
http://pods.io/docs/code/general-functions/pods-no-conflict-off/

**Comment by pglewis** [comment]
Let me know if that patches around the issue for the short term.  This is one of those that's going to require I push everything else aside temporarily and look at closely.  That'll happen, just working out when.

**Comment by okrg** [comment]
Thank you for the band-aid.  I will reply back after I had a chance to try
it out.

**Comment by huangc28** [comment]
is there an further fixation on this issue? i've tried @okrg's method all the way through, but pods custom field is still not changing. I have enabled all rest read/write api support on both the field and field type, but only WP's original field is being updated @@. please help!

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions! But going to close that for now!
