### ISSUE TITLE
Cull legacy WordPress support based on min required version

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3363]
A quick audit shows a couple dozen places we're checking `pods_version_check( 'wp', '3.5'...` or for 3.6.  If we're at 3.8 min version then I believe we've given enough deprecation time.

**Comment by GaryJones** [comment]
The [current version of the `readme.txt](https://github.com/pods-framework/pods/blob/2c8e27f5a822adb899d00c297c8c50f679a9f507/readme.txt#L5) has the minimum WP set as 4.5.

**Comment by sc0ttkclark** [comment]
Nothing left here
