### ISSUE TITLE
saving a post with a required custom taxonomy and/or WYSIWYG field ends up with an empty post 

### ISSUE THREAD

**Issue by webitekt** [pods-framework/pods#3366]
WP4.4.1, pods 2.6

I setup up a Custom Taxonomy "tax_infotype".
This Custom Taxonomy is empty and has no add. fields. It appears under the settings menu.
The customer can manage all needed entries.

Those entries are displayed through a relationship field in another CPT within pods.
The CPT is called "articles". Articles has a couple of fields (some are required) and one field "infotypes" which is a relationship field that is connected to the Custom Taxonomy "tax_infotype". This field is also checked as required. It is set to multi selection with checkboxes.

When I create a new entry for "articles" and leave everything empty and hit the save/publish button, the required fields are marked as required and the hint is shown on the right site of the field (based on the jquery.pods.js). That's fine and works as expected. 
When all fields are filled and only the "infotype" field is empty and I hit save/publish, the browser shows up a new page (based on post.php) and says that the "infotype" field is empty - no header, no footer, no sidebar - nothing only "name_of_the_field" and "is empty". There is no button to add the field or go back. So I have to hit the "back" button of the browser (tested with safari 9.0.2., chrome 47.0.2526.111 (64-bit) and firefox 43.0.4 on OS X 10.11.2) and then all fields are empty. But there is a new record saved without title in the "article" view.

Doing the same with a CPT instead of a Custom taxonomy works in the same setting and the check if the required field are filled is done before saving, when clicking the save/publish button.

The same happens to a WYSIWYG Field (independent from the editor) wich is a required field in a pod.
I tested this also with a new blank pod, only with a WYSIWYG Field. Same issue.

I had a conversation with Jim regarding this issue and he suggested to open an issue here.
Please let me know if you need any add. information.

**Comment by pglewis** [comment]
Slight chance this is related to #2313, we're having issues with "falsey" checks on required fields

**Comment by S8nsick66** [comment]
+1

**Comment by webitekt** [comment]
additional information from a conversation in slack.
User extends the "user" content type with a custom field (plain text) marked as required.
Editing the user screen and leaving the field empty shows a new screen with the information "<field-name> is empty". entered data in other fields are still there if you go back with the back bottom of the browser. 
I could confirm that behavior. 

It should behave like other required fields on CPT Pages, where in most cases the validation marks the empty required field with a message and jumps to the first empty required field.

I didn't test other field types, but can be done up on request.

**Comment by quasel** [comment]
maybe #5031
