### ISSUE TITLE
Pods iterator not working

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3372]
It seems since `$iterator` is false by default in `Pods`, and there is no code setting it to true, all the `Iterator` interface methods return false.

A refactor is needed or `$iterator` just set to true since you have `stop_iterator`.

**Comment by pglewis** [comment]
I'm not sure where this was left off-- if it was something that was being done for the old 3.0 branch,  something that was started and back-burnered, or something that was started and didn't pan out.  

I'm not seeing any feature issues about Iterator implementation plans, this is as good a spot as any to put 'em.

**Comment by sc0ttkclark** [comment]
I think someone just needs to go through and see if we have all iterator methods etc in place like we need, test that iterator is working (maybe even a unit test?) and then test to confirm it doesn't break existing unit tests.

**Comment by sc0ttkclark** [comment]
http://php.net/manual/en/class.iterator.php

- [ ] `current`
- [ ] `key`
- [ ] `next`
- [ ] `rewind`
- [ ] `valid`

It seems that in `rewind()` we want to set the $iterator to true.

But I'm not sure how this affects other methods as there are some methods of the same name already in place.

**Comment by pglewis** [comment]
Will also need docs
