### ISSUE TITLE
Style file upload queue and progress bars for pluploads

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods#3380]
Related to #3334

**Comment by nicdford** [comment]
a la slack for future reference:
Phil Lewis [3:06 PM] 
I didn't stick any IDs on the field containers yet, so digging up the container is a little dumber than it should be, but I'll have a gist for ya in a moment

https://gist.github.com/pglewis/ab675df1bb12a78d4e3c

line 2 you'll have to modify for your field name each one of those is a single line from the console should work if you have the new file upload field on a page after creating collection, model, and view and attaching it all to the DOM, all you have to do is update the model's progress value (percentage)(edited)

`.pods-ui-region` is currently just a generic container for any UI needs any specific uploaders may have

media modal doesn't even need it because it's a modal the collection magically takes care of the list so you can add more models without futzing

`model = new pods_ui.FileUploadQueueModel( { id: 2, filename: 'test me too!' } )`

`collection.add( model )`

`model.set( { progress: 40 } )`(edited)

after the setting up from the gist above add the model to the collection, ​*poof*​ new list item update that model, ​*poof*​ updated UI should make this unit-testable... need no real file upload to test the majority of the behavior

**Comment by pglewis** [comment]
The original gist and code here have been update and should work for testing until I decide to change it again.

**Comment by sc0ttkclark** [comment]
Maybe we can use some CSS classes from WP itself to use the color scheme, right now it's a dark grey but we could use the same blue that the WP modal uses for consistency.

**Comment by nicdford** [comment]
This can be closed, the rest of the changes are on #3341
