### ISSUE TITLE
Target Pods UI Column pick data field - filter not working

### ISSUE THREAD

**Issue by cannect** [pods-framework/pods#3383]
Hi,

What I am trying to accomplish is to show the customer name instead of numbers in the Column data. It is the default Pods UI from the menu.

Here a screenshot of what field I am trying to edit:
![image](https://cloud.githubusercontent.com/assets/939500/12887629/ec1269da-ce75-11e5-94c9-73480c2cc45c.png)

I have found out that the following filter will do: `pods_ui_coupon_field_value`.

So I added a filter and a function: 

```
add_filter('pods_ui_coupon_field_value', array($this, 'show_customer_name_instead_of_numbers'), 1, 4); // four arguments

public function show_customer_name_instead_of_numbers( $row_value, $field, $attributes, $row )
    {
        $return = "";

        var_dump('test'); // debug, but not shown

        if ($field == "customer") {
            foreach ( $row as $key => &$data ) {
                if ( $data['firstname'] && $data['lastname'] ) {
                    $return += $data['firstname'] . ' ' . $data['lastname'] . ' and ';
                }
            }
        }
        return $return || $row_value;
    }

```

But my filter function is not even called. How is that possible?

PS: maybe some spelling errors in my code, I translated some words to English.

**Comment by quasel** [comment]
depending on where you call the filter you might need to change it to:
`add_filter('pods_ui_coupon_field_value', array($this, 'show_customer_name_instead_of_numbers'), 1, 4);`

**Comment by cannect** [comment]
Hi @quasel ,

Sorry for the late reply from my side, but I call it from within a class. One line above this `add_filter` function call I have another one that does work. So this time I am very sure the filter does not work ;-) 

Or is that not what you intended to say?

**Comment by cannect** [comment]
I catched another one: `pods_form_ui_field_' . $type . '_attributes` in `pods/classes/PodsForm.php` on line 382.

I var_dumped the $type so I am pretty sure my filter is correct: `pods_form_ui_field_pods_field_klant_attributes

**Comment by quasel** [comment]
seems #1240 has the answer :D but then this is an old post ->
Sorry for the late reply, feel free to comment if you still have questions!
