### ISSUE TITLE
Possible compatibility issue with Pods and Relevanssi

### ISSUE THREAD

**Issue by lukecav** [pods-framework/pods#3384]
Had a odd issue where the permalink would not work in the search results of posts that has been indexed by Relevanssi.

But when just using say Better Search the permalinks all worked fine in the search results.

**Comment by pglewis** [comment]
Is the issue intermittent?  Is it easy to isolate and reproduce?  Or are you saying you've found a solution to the problem?

**Comment by jimtrue** [comment]
@lukecav Would definitely help to get a bit more details as to your setup. It did seem strange that on all the search results you provided for the link in Slack, the 'permalink' it was giving was just the search query. Did you reach out to Relevanssi?

**Comment by lukecav** [comment]
Not yet, ended up just using Swiftype on the live site and Better Search on the dev site.

**Comment by lukecav** [comment]
The issue was as soon as you deactivated Relevanssi then the permalinks would work fine in the search results.
