### ISSUE TITLE
Custom taxonomy and Polylang plugin

### ISSUE THREAD

**Issue by batterylow** [pods-framework/pods#3400]
Pods correctly work with Polylang plugin only if entity is custom post for custom taxonomy code:

```
$params = array(
   'limit'=>-1,
 );
 $Taxs = pods('tax_name', $params);
```

always return 0 items.This is a bug or am I doing something wrong?

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
