### ISSUE TITLE
[data-icon]:before CSS rule overriding Icon rules for Divi theme

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#3404]
The following lines in the pods/ui/css/pods-font.css are creating issues with Divi Theme's handling of icon fonts.

https://github.com/pods-framework/pods/blob/dde459f59321827049a466a2df4d656688989790/ui/css/pods-font.css#L15-L17

`[data-icon]:before {
  font-family: "pods" !important;
  content: attr(data-icon);
`

This applies our pods-font for the Admin menu. In looking at other plugins, we're referencing this incorrectly (compared with JetPack & OptInMonster):

OptinMonster:
`#toplevel_page_optin-monster-api-settings .dashicon-before,
#toplevel_page_optin-monster-api-settings .dashicons-before:before {
 font-family: ... /* no need for !important on any of these tags
`

JetPack:
`li.toplevel_page_jetpack .wp-menu-image:before {
   font-family & content /* no need for !important or most of the other things */
`

So, ours should be:
`li.toplevel_page_pods .dashicons-before,
#toplevel_page_pods .dashicons-before,
#toplevel_page_pods .dashicons-before:before {
    font-family: "pods";
    font-size: 20px;
    content: "c";
}`

Related to forum post: 
http://pods.io/forums/topic/pods-messing-up-icons-selection-in-divi/

**Comment by pglewis** [comment]
Verified, @jimtrue?  I'll merge it.
