### ISSUE TITLE
missing endpoint to get Pod definition and fields (= legacy Pods JSON API plugin)

### ISSUE THREAD

**Issue by cmjn14** [pods-framework/pods#3408]
Hi,
I was using Pods 2.5 with WP REST API v1 and Pods JSON API Plugin.
I have upgraded to WP4.4, WP REST API v2 and Pods 2.6, and I understand that Pods JSON API is now deprecated.
However now I miss an endpoint to get the Pods definitions with their lists of fields, including for each relationship field its sister_id ( = what I used to have from wp-json/pods-api/mypodname in Pods 2.5).

I've tried to use the REST API Enabler plugin as a workaround, which works but it seems to conflict with Pods.

Can you help me with this ?
Thanks!

**Comment by jimtrue** [comment]
Did you follow the procedures outlined in this document that Josh put together on working with the new REST API features in Pods?

http://pods.io/docs/build/extending-core-wordpress-rest-api-routes-with-pods/

**Comment by cmjn14** [comment]
Yes I did. This doesn't give me the same functionalities as the former Pods JSON API plugin, it seems that there's nothing like the former /wp-json/pods-api/ endpoint, that gave access to the Pods structure itself.
The reason why I need this is because my javascript application explores this structure to know which Pods exist and what are their fields, and builds further ajax requests from that.

**Comment by jimtrue** [comment]
Can you give us an example of what you were getting before that you're not getting now?

**Comment by cmjn14** [comment]
Yes, here is the response I used to have with the url `http://localhost:8080/mysite/wp-json/pods-api/team`, where "team" is a Pod I have defined, and "team_members" is a field defined for this pod:

`{"id":78,"name":"team","label":"Teams","type":"post_type","storage":"meta","fields":{"team_members":{"id":79,"name":"team_members","label":"Team members","type":"pick","weight":0,"pick_object":"post_type","pick_val":"person","sister_id":"80","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"multiselect","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Team","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"team","capability_type_extra":"1","has_archive":"0","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"publish","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"1","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_page_model":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","menu_location_custom":"edit.php?post_type=person"}`

**Comment by jimtrue** [comment]
What are you getting now at /wp-json/v2/team ?

**Comment by cmjn14** [comment]
The same content as I had at `/wp-json/pods/team` (= the list of teams with the data for each team), which is different from what I had at `wp-json/pods-api/team` (= the definition of "team" pod).

It looks like this:
`[{"id":322,"date":"2015-07-03T08:01:03","date_gmt":"2015-07-03T08:01:03","guid":{"rendered":"[removed for confidentiality reasons]"},"modified":"2015-07-03T08:01:03","modified_gmt":"2015-07-03T08:01:03","slug":"a_team_name","type":"team","link":"[removed for confidentiality reasons]","title":{"rendered":"A Team Name"},"content":{"rendered":""},"parent":86,"menu_order":1,"team_members":false, [ etc etc]`

**Comment by sc0ttkclark** [comment]
@Shelob9 can you remember why we didn't include the endpoints? Maybe it was that they weren't ready yet?

**Comment by quasel** [comment]
The former endpoint for pods-api doesn't exist currently.
Some of the information is:
/wp-json/wp/v2
/wp-json

For discovery maybe helpfull too
/wp-json/wp/v2/types

for the rest we either would need custom endpoinst or filters that extend existing revield information 

The whole API project is still in Beta and things keep changing - althoug it seems most part are more or less in a final/stable state. There has been an attempt to create a new https://github.com/pods-framework/pods-rest-api but at current state the team has decided to just "activate" CPT like wp posts ... although if you stick to the v1 with the old plugin everthing just should work like before

**Comment by cmjn14** [comment]
Yes but I had to migrate to WP REST API v2 because I need to use the JWT Authentication for WP REST API plugin, and v2 is a prerequisite ...

Note that the "REST API Enabler" plugin proposes the endpoint I need, so it's possible ... the bad thing is that this plugin overwrites the other Pods endpoints :-(

**Comment by quasel** [comment]
well to just get the data you dont need REST API Enabler  - just go to your pods setting -> REST API tab and activate it there

**Comment by jimtrue** [comment]
We're tracking (or will be tracking) what endpoints from the API are missing and need to be migrated over in this particular issue #3357

**Comment by cmjn14** [comment]
@quasel : it's not to get the data that I need REST API Enabler, it's to get the Pods structure as explained above. To get the data everything is fine with the Pods GUI.

**Comment by quasel** [comment]
the REST Enabler just allows you to output meta - without looking at their code they do just about the same we do by using - register_rest_field - to add fields to the output - neither of this options would expose the schema or configuration as the old api endpoint did :/ sorry but currently there is no way without further coding ( filters, custom endpoints ) to expose this information. 

as already mentioned my approach woul be to improve the output from wp-json/wp/v2/  - but all depends on your logic and you use case - sorry to have no better information for you!

**Comment by cmjn14** [comment]
It's not totally similar as the old api but I can manage it, here is the kind of response I get from the REST Enabler plugin on `http://mysite/wp-json/wp/v2/pod-fields` : 

[{"id":64,"date":"2016-01-19T12:43:23","date_gmt":"2016-01-19T12:43:23","guid":{"rendered":"http:mysite?post_type=_pods_field&#038;p=64"},"modified":"2016-01-20T13:29:06","modified_gmt":"2016-01-20T13:29:06",**"slug":"team_members"**,"type":["pick"],"link":"http:\/\/localhost:8080\/qmsccint\/?post_type=_pods_field&p=64","title":{"rendered":"Team members"},"content":{"rendered":""},"author":1,**"parent":63**,"pick_object":["post_type"],"pick_val":["person"],"pick_format_type":["multi"],"pick_format_single":["dropdown"],"pick_format_multi":["multiselect"],"pick_taggable":["0"],"pick_limit":["0"],"pick_allow_html":["0"],"pick_user_role":["a:0:{}"],**"sister_id":["22"]** etc etc.

and from `http://mysite/wp-json/wp/v2/pods/63` :

{**"id":63**,"date":"2016-01-19T12:43:23","date_gmt":"2016-01-19T12:43:23","guid":{"rendered":"http:mysite?post_type=_pods_pod&#038;p=63"},"modified":"2016-01-20T13:29:06","modified_gmt":"2016-01-20T13:29:06",**"slug":"team"**,"type":["post_type"],"link":"http:mysite?post_type=_pods_pod&p=63","title":{"rendered":"Teams"},"author":1,"label_singular":["Team"],"public":["1"],"capability_type":["post"],"capability_type_custom":["team"],"capability_type_extra":["1"],"hierarchical":["1"],"default_status":["publish"],"menu_position":["0"],"_links":{"self":[{"href":"http:\/\/mysite\/wp-json\/wp\/v2\/pods\/63"}],"collection":[{"href":"http:\/\/mysite\/wp-json\/wp\/v2\/pods"}],"about":[{"href":"http:\/\/mysite\/wp-json\/wp\/v2\/types\/_pods_pod"}],"author":[{"embeddable":true,"href":"http:\/\mysite\/wp-json\/wp\/v2\/users\/1"}],"https:\/\/api.w.org\/attachment":[{"href":"http:\/\/localhost:8080\/qmsccint\/wp-json\/wp\/v2\/media?parent=63"}]}}

(in bold is what is important to me to know the pods structure)
That's OK for me, if Pods could simply provide me these 2 endpoinds it would be great.

Because while the REST API Enabler is activated, it doesn't let me reach Pods endpoints. If I modify the relative priority of each plugin, I can reach Pods endpoints but not the ones from REST API Enabler anylonger ... :-/

**Comment by quasel** [comment]
well cant help you right now - would need to dig into what REST Enabler does - pods configuration is stored as own CPT _pod ...   so maybe this plugin is activating all CPT&Meta - but then you shouldn't need the pods REST endpoints so maybe just deactivate the ones from pods and just use the enabler plugin - the other possible soluitons are already mentioned in here :/ sorry at time beeing we cant provide an out of the box solution 

http://v2.wp-api.org/extending/adding/
http://v2.wp-api.org/extending/modifying/

**Comment by quasel** [comment]
closing as we already have an issue for it https://github.com/pods-framework/pods/issues/3357
