### ISSUE TITLE
Make prefixes and suffixes optional for `find()`

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3409]
If we can manually lookup prefixes to use based on field types then Pods could be doing this on its own.  No need to remove them internally and upset back-compat.  

Goal: traversal always looks like this: `field.related_field.indirect_third_level`

A lot of support issue evaporate if end-users don't have to know anything about prefixes and suffixes.

**Comment by quasel** [comment]
i guess this would be a big improvment and make life easier for starters!!!
