### ISSUE TITLE
Slider in the taxonomy using pod

### ISSUE THREAD

**Issue by rajeshbhammar** [pods-framework/pods#3410]
Hi, 

I am trying to add slider (smart slider 3) short code for each of the custom taxonomy. I am using clipper theme and its child theme flatter. I was able to create field and it is showing on the front end however, while i add shortcode of the slide from the custom taxonomy, it is not showing slider and showing only shortcode on the front end.

I had tick "show shortcode" field from advance field options

https://coupon52.com/stores/1mg-coupons-discount-coupon-codes-promo-offers/

I also tried adding following in the function.php but it is breaking the screen and the screen just go while on click on "update file"

add_filter( 'term_description', 'shortcode_unautop');
add_filter( 'term_description', 'do_shortcode' );

I dont have coding knowlege

help is appreciated.
Regards,
Rajesh

**Comment by jimtrue** [comment]
This is actually a support question; GitHub is only used for Bug Reports or Feature Requests. Please post your support questions over at http://pods.io/forums/ or you can join our Slack Chat at http://pods.io/chat/ and ask your questions in #support.

**Comment by rajeshbhammar** [comment]
thank u :) not much knowledge, newbie :)
