### ISSUE TITLE
Error registering Pods programatically

### ISSUE THREAD

**Issue by webmandesign** [pods-framework/pods#3416]
Hi guys,

**ISSUE DESCRIPTION:**

I am trying to add a Pod and some custom fields via my theme's `functions.php` file, but it throws me an error in WP dashboard: http://easycaptures.com/fs/uploaded/848/1822267647.png

What I am trying to do specifically is to add a metabox to easily set up custom fields for WordPress Pages. I want this to be automatically added via my theme once a user activates the Pods plugin. 

**HOW TO REPLICATE**

To replicate the issue you can put this into Twenty Sixteen theme `functions.php` file:

```
/**
 * Testing Pods plugin
 */
function themeslug_pods_register_custom_fields() {

    if ( function_exists( 'pods_register_type' ) ) {
        pods_register_type( 'post_type', 'themeslug_page' );
    }

} // themeslug_pods_register_custom_fields

add_action( 'init', 'themeslug_pods_register_custom_fields' );
```

As you can see, I've stripped this to pure `pods_register_type( 'post_type', 'themeslug_page' );`. Without the 3rd parameter and without additional `pods_register_field` to debug. Even this bare minimal code doesn't work and throws the error above.

I get the error on all WP admin pages - I can not use WP admin, basically.

Also I would like to note that I've tested this on WordPress multisite only without any additional plugins enabled.

Could you please have a look at the issue and resolve it?

Thanks in advance!

Regards,

Oliver

**Comment by quasel** [comment]
Did a quick Test on a single install same behaviour!

No idea what's you plan is but as @sc0ttkclark already mentioned you wont have the full set of pods functionality. One workaround could be the usage of the [Pods Migration component ](https://github.com/pods-framework/pods/blob/dde459f59321827049a466a2df4d656688989790/components/Migrate-Packages/Migrate-Packages.php) guess @pcfreak30 could help with some sample code 

Or if it's only to add some Meta Boxes just use [CMB2](https://github.com/WebDevStudios/CMB2)

**Comment by webmandesign** [comment]
Hi,

Indeed, just custom meta boxes is the only thing I need.

I am currently supporting Advanced Custom Fields (ACF) in my theme which works fine.

However, I've found a Pods plugin that looks great and wanted to add a support for that plugin in my theme too. It seems to support creating custom meta boxes, plus you can do a lot more with custom post types with it. That, however can not be done with ACF.

So, the ideal scenario would be: 

- If a theme user don't want to extend the site, just use ACF. 
- If there are some extensions needed (additional Custom Post types), (s)he could use Pods plugin instead, which would display the theme predefined metabox plus additional custom posts could be created by the user afterwards.

Hope I've explained my intentions well. I don't know what does it mean that I "wouldn't have the full set of Pods plugin functionality". _I don't need that, really._ I just thought that the plugin is capable of displaying custom meta boxes too, which would be starting point for my theme users.

The theme just needs a support for **a tool that replaces WordPress native custom fields with something more intuitive, more user friendly**. The additional functionality of Pods plugin is only a **bonus that theme user can build on**.

It's pity that Pods plugin can't do this.

Thanks for help anyway.

Regards,

Oliver

**Comment by sc0ttkclark** [comment]
I'd like to figure out what's going on with that function, it should be working especially at that priority (10) for the init action. Pods registers post types during init action 11 normally, so as long as you've registered your Pods before then, it should kick in and set things up with WordPress properly.

**Comment by JoryHogeveen** [comment]
It looks like @jamesgol fixes this issue in 2016
