### ISSUE TITLE
The ability with date fields to set just the month and year would be nice.

### ISSUE THREAD

**Issue by m9n** [pods-framework/pods#3420]
Just sayin' :)

**Comment by m9n** [comment]
Sorry, that was too little info!

At the moment, you can set the year only in the date formatting options for date fields, and only the year is added to the field when you pick it.

So would this be a question of allowing formatting options for "February 2016", "Feb 2016", "02-2016", etc?  While I could perhaps think of a better UI, this would work adequately well.

**Comment by sc0ttkclark** [comment]
Sounds like we'd need a UI that uses dropdown for Month, and a text field to enter the year. Alternative date UI inputs could also follow the same sort of inputs used in the Post editor 'publish date' field.
