### ISSUE TITLE
Change in POD's API for export() function

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#3426]
in a site with in PODS 2.5.3
i used <code>pods->export()</code> function that return either a  "category" field with all category attacched to that pod... this feature was foundamental for the site.

i update the plugin (2.6.1) and the same function doesn't return "category" field anymore... and the site..."stops to work" :(((((((

Is there a way to obtain again that infos (the category associated to the pod) direcly from export function??

Thanks...!!!

**Comment by quasel** [comment]
Hi strange i'm not aware of any changes for export() 

maybe Try clearing the object cache / transients that Pods uses, go to ​*Pods Admin > Settings > Clear Pods Cache*​ helps

**Comment by gigi-budrio** [comment]
Yeeeeahhhhh!!
Many THANKS...!! it was the (very strange for me) problem..!!

Hope it helps to other !

Thanks again!

**Comment by quasel** [comment]
anoter incident related to #2558 let's hope 2.6.2 fixes it for good !
