### ISSUE TITLE
Pods shortcode view echo vs return

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3433]
in the pods shortcode function, line 667, `$return = pods_view( $tags[ 'view' ], null, (int) $tags[ 'expires' ], $tags[ 'cache_mode' ] );`, you are wanting to return and not echo, but you dont past true for the return argument thus breaking that functionality.

**Comment by sc0ttkclark** [comment]
Sounds good

**Comment by jimtrue** [comment]
@pcfreak30 if you feel up to the challenge, take the above and create a PR against this issue following our contribution guidelines. Thanks!
