### ISSUE TITLE
Complete rewrite of Pods documentation and real life examples

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3435]
Simply have to write this. It comes over and over again. 

I am by no means WordPress beginner. Have one localhost WordPress installation and database of 1300 Posts with mostly different WordPress PHP snippets, often several of them in one Post. Probably one of the biggest private collection in the world, but enough about it.

I am giving you a picture that I am not lazy, I spend big share of time Googling help and things. 

But all this in Pods community is complete chaos. For almost all my problems I found solution on different forum, different blogs, never in official documentation. And in 95% of cases it takes me countless hours and hours reading things around to find help. Many times several days. Just to find out it exist and solution is not some complex workaround, but just something simple, and very difficult to find.

Sorry for this, but cannot keep it in myself anymore.
It is as I said madness and chaos. And following this i have feeling (i know) I am not using even 40-50% of Pods potential.

Dont know what has to be changed, dont ask.

**Comment by lkraav** [comment]
Have you thoughts about joinings Friends of Pods https://pods.io/friends-of-pods/ and putting in some monthly support, so they could hire a person to work on docs? (I'm Silver supporter)

**Comment by StaggerLeee** [comment]
I doubt it would change anything. Writing Docs is for sure easier than writing code for Loops field.
It is not ybout time spent writing docs, but to make them a bit different. It takes a hell lot of time to find solutions.

Why I have to spend 2 days to find how to pull Pods items via shortcode by **multiple** terms.
Something like this should be in Docs, people dont list Items allways by fields. Dont get this logic about priority in Docs. This is just one example. Dont want to start discussion just about it.

**Comment by sc0ttkclark** [comment]
Just a heads up, we've rewritten our Pods documentation, revamped our information structure, have a new process down for support, are working on expanding our examples and documentation after each engagement with a developer/user during support. The new docs site should be launched within the coming weeks, we're just polishing up the theme and juggling ongoing support needs at the moment.

Supporting Pods through Friends of Pods is one of the best ways to make everything better, the only other way to have as direct of an impact is to contribute time yourself to work on docs.

Please take time and gather a list of some areas you'd like to see improved most, maybe like a top 5 or top 10 areas that could use ______ and we'll pay extra attention to that too.

Sorry that you're frustrated, it's certainly difficult as only in the past month we've had enough funding to have our people working full time on Pods, but that doesn't cover the fact that we need extra support help. Once we get a bit more funding, we're looking to bring on another person to help with ongoing support and/or docs.

Please send along your list to my e-mail at scott@pods.io so I can follow up with you and get our team organized around your pain points.

**Comment by sc0ttkclark** [comment]
Also I should note, we do have a pretty active Slack group with people across many time zones, full of people who are using Pods every day who could be of use or help in sharing solutions. You might consider joining our chat http://pods.io/chat/ in the future.

**Comment by StaggerLeee** [comment]
If it is true than thank you. 

I can filter my private collection and see what problems took me long time to find solution. And make a list for Docs.

Yes, I know many of them will be laughable now. But it really took me hell of time to find solutions.

**Comment by jimtrue** [comment]
@StaggerLeee I know I've reached out to you before in the forums to join our Slack Chat, even saw a notice about that on one of your issues a few back. Our Chat is our FASTEST route to quick answers and to help you find the murkiness through the docs. We're working very diligently to redo the documentation and mark items as deprecated, etc, but it is a mountain of work (8 years of docs). Please join our Slack Chat when you need assistance and believe me, you will get help!

**Comment by sc0ttkclark** [comment]
Sounds great, thanks @StaggerLeee -- and yes it is definitely true :)

**Comment by StaggerLeee** [comment]
I have send you an email with some list to start with. Thanks.

**Comment by quasel** [comment]
Well regarding: 

> Yes, I know many of them will be laughable now. But it really took me hell of time to find solutions.

dont worry nobody started as expert it takes time - and you might even get a hint if somethin could be done better and the support get's more ideas for areas with room for improvement ^^
