### ISSUE TITLE
Pods session issue

### ISSUE THREAD

**Issue by abhinav-maheshwari** [pods-framework/pods#3439]
I was trying to store some pods variables in session as follows:
`pods_v_set($bulk_ids, 'action_bulk_ids', 'session');`

However, this does not work because pods checks for existence of session_save_path which is usually empty and hence pods returns false and session does not work. 

```
// in function pods_session_start
elseif ( empty( $save_path ) || !@file_exists( $save_path ) || !is_writable( $save_path ) ) {
```

Just removing this check lets the session work correctly.
Please do let me know if I am missing something.

**Comment by quasel** [comment]
see #3439 - closing this 

Sorry for the late reply, feel free to comment if you still have questions!

**Comment by quasel** [comment]
meant #2237
