### ISSUE TITLE
Bulk actions submit all ids via HTTP GET

### ISSUE THREAD

**Issue by abhinav-maheshwari** [pods-framework/pods#3441]
Pods UI bulk actions have a drawback, all the item ids are sent via HTTP GET. This works for many cases, specially when you are not displaying too many items in a single page, and when you want the bulk action to only be limited to items on that page. But what if you want to delete all items in all pages ? Or you need a bulk action that exports all the items to a CSV or PDF ? This plugin - https://github.com/ipragmatech/advanced-pods-bulk-action solves these cases.

**Comment by sc0ttkclark** [comment]
If we switch this to a POST for the bulk action, that should work well. Not sure about best course of action to support exporting of specific selections, but that shouldn't be hard considering the way bulk actions work right now to add extra bulk export options based on selections.

**Comment by abhinav-maheshwari** [comment]
POST will solve one part of the issue. But what happens if we want to take a bulk action on items on several pages, like we wanted to build an export to CSV functionality. In that case, we have to first display all items on a single page and then take a bulk action. In our case, there were more than a 1000 items and displaying on a single page is not user friendly.

**Comment by sc0ttkclark** [comment]
right, those cases just can't be easily handled here as a fix, those require a better interface, possibly utilizing things from the Tools > Export page, or additional plugins.

**Comment by abhinav-maheshwari** [comment]
Agreed. So we can solve one part of the issue by using POST in PodsUI and for the other part, i.e. marking items for bulk actions in several pages, the advanced-pods-bulk-action will have the solution. Will modify it accordingly when the PodsUI changes.

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
