### ISSUE TITLE
Bulk action delete works only once

### ISSUE THREAD

**Issue by abhinav-maheshwari** [pods-framework/pods#3442]
In Pods UI, selected some items and did a bulk delete. If I now try to select items again and do a bulk delete, it does not work. Could this be due to the deleted_bulk = 1 present in the URL ?

**Comment by ihsanberahim** [comment]
I face the same issue. I found that this issue happen only if we set "Parent Menu ID " to the pods. I also looking for the solution for this issue.

**Comment by ihsanberahim** [comment]
This is my custom solution. Please advise if this is bad in the practice.
```
add_action('admin_init', 'fix_redirection_bug', false, 1);

function fix_redirection_bug(){
    $page = @$_GET['page'];
    $post_type = @$_GET['post_type'];
    $pods_name = '<your_pod_name>';
    $parent_menu_id = "<your_pod_parent_menu_id>";
    $params = http_build_query($_REQUEST);

    if($page!="pods-manage-{$pods_name}") return;
    if(strpos($_SERVER['REQUEST_URI'], $parent_menu_id)!==FALSE) return;

    wp_redirect(admin_url("/{$parent_menu_id}&{$params}"), 302);

    exit;
}```

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
