### ISSUE TITLE
Pods relationship fields and poylang

### ISSUE THREAD

**Issue by batterylow** [pods-framework/pods#3448]
If we create for post a relationship with elements of other post type, and go to edit page for this post in «MoreField» block we will see drop-down list or checklist relationship options of this post. 

The problem. 
If activated Polylang plugin and enabled option «display data only one language» (switch in the admin page header), our drop-down list will only consist of elements linked to this language. It seems that this is correct, BUT if we edit a post whose language is different from the selected to display a drop-down list will still be filled with the elements with reference to the selected language, not the language of the edited post, so in save process post will be linked with elements are not his language, and in output results on the website, they will not participate.

The Decision.
Display in the admin page for the relationship lists ONLY elements of the default language, automatic reference to their language copies of the relevant language of the edited post when saving. Or display the list of relationships linked only to the language of the edited post .

**Comment by quasel** [comment]
seems fixed with #3506
