### ISSUE TITLE
Specify which post types show on Taxonomy archive

### ISSUE THREAD

**Issue by lkraav** [pods-framework/pods#3449]
- [ ] Add pick field `archive_post_types` option to Taxonomy Advanced options to choose which post types to show posts for
- [ ] Add pick field `archive_taxonomies` option to Post Type Advanced options to choose which taxonomies to show posts on
- [ ] Hook into `pre_get_posts` action if main query and on a tax archive, check if that tax has `archive_post_type` and override if not empty, lookup post types with the option enabled for `archive_taxonomies`

---

_Original issue_
Problem: `/category/something/` archive, where I have added a custom post type entry and assigned it the `Something` category.

Query Monitor shows `post_type = post` is enforced. If I have the built-in taxonomies attached to new Pods-based custom post types, shouldn't these post types automatically be filtered into the taxonomy query, without me having to do custom `pre_get_posts` mangling myself?

**Comment by jimtrue** [comment]
That might be a WP specific issue. I've noticed the same with the default categories, that they don't pick up other post types by default. Not sure how we'd fix this one, since the WP Query for taxonomies often includes the post type specifically in the taxonomy archive

**Comment by jimtrue** [comment]
Unless I'm missing something

**Comment by lkraav** [comment]
Yeah I'd actually be interested in people being able to reproduce this, so I know I'm not seeing something specific to my setup.

Seems like this could be caught via unit tests right? In that case, feels like a fixable thing via `pre_get_posts`. Pods knows which post types have been attached, so it could add these to the query.

**Comment by lkraav** [comment]
Well, a month later, I forgot I filed this and organically found the ticket again after the underlying issue was raised during internal pre-launch QA.

I'm still thinking Pods has to automatically add `pre_get_posts` actions for checking and adjusting taxonomy archive queries for those all taxonomies that are selected for Pods-managed CPT-s.

**Comment by jimtrue** [comment]
The problem I would see if we automatically added it, how could we determine that was not intended by the theme author? ie, if I wanted my regular taxonomy archive to only show built-in because I'm processing and handling specific custom post types in taxonomy separately within their own theme files.

I did do some verification for you: I have a default taxonomy archive (using one of the Twenty-"something" themes, and this works as inteded: <taxonomy-type>/<taxonomy-term>/ shows all posts regardless of post-type that are associated with that taxonomy and term. I can verify this in Genesis Default and in the Twenty-"somethings".

Unless, I'm missing something in what you're attempting that isn't working on your end.

**Comment by sc0ttkclark** [comment]
I think it'd be cool to offer an Advanced option for Custom Taxonomies to choose which post type(s) appear within that archive and then hook into the `pre_get_posts` action to set that appropriately.

**Comment by sc0ttkclark** [comment]
Related https://core.trac.wordpress.org/ticket/37424#ticket

**Comment by sc0ttkclark** [comment]
Category and Post Tag taxonomies are the only ones affected by this issue, so to clarify Custom Taxonomies work as expected.

Here is a function that will enable the custom post types to show up on Category and Post Tag taxonomy archives:

https://gist.github.com/sc0ttkclark/912ca1ff635fffdc892557e539607da3

**Comment by jimtrue** [comment]
@sc0ttkclark Yep I agree this is the better way to handle that

**Comment by codente** [comment]
I do love the idea of Pods handling this automatically or via opt-in checkbox.  And if it handles automatically, an option to disable if so desired.

**Comment by jimtrue** [comment]
I really think this needs to be added if someone enables Categories & Tags on their custom post types. Requiring people to add a script to make this work just seems very backwards. I know this is WordPress being the bad guy here, but I did find a plugin from 7 years ago that just "works". https://wordpress.org/plugins/custom-post-type-taxonomy-archives/

**Comment by sc0ttkclark** [comment]
I'm looking at doing this as soon as I'm able to in the coming weeks.

**Comment by skinnerjoe** [comment]
The plugin referenced above has now been removed for download from wordpress.org. This is the worst thing I have encountered while using PODS and it should be addressed. I'm dead in the water with what i'm doing because of this.

**Comment by jimtrue** [comment]
@skinnerjoe That plugin being removed unfortunately has nothing to do with us. That's the WordPress.org plugin repository yanking old projects off their repository. I was able to find that plugin's GitHub Repo: https://github.com/WPPlugins/custom-post-type-taxonomy-archives

You can enable your post types in the main archive, category or tag archives using the pre_get_posts filter and this code snippet which you can add in your child theme's functions.php or using the Code Snippets plugin:

https://docs.pods.io/code-snippets/modifying-pre_get_posts-categories-tags-show-custom-post-types/

I hope that helps!

If

**Comment by mrpackgoat** [comment]
I tried adding the snippet into the function.php, but CPT tags still don't display.  I'm a non-techie, so I probably screwed up something.  Here's a screenshot... am I missing something?
![cpt snippet](https://user-images.githubusercontent.com/60116414/72759194-cdf27a00-3b89-11ea-884f-c256507f7a81.jpg)

**Comment by JoryHogeveen** [comment]
@mrpackgoat 
See line 25 to 28. You'll have to pick your condition for this to work, please always read everything, not just copy/paste code ;)

**Comment by mrpackgoat** [comment]
Jory, thanks for your note.  I have read everything but as I mentioned I’m not technical (hence the reason I’m using Pods).  

 

I assume there are some specifics I need to change, but it’s not clear to me how to tweak things.

 

All I’m trying to do is to get my CPT tags to display for the “afdr_posts”.

**Comment by sc0ttkclark** [comment]
Implemented in https://github.com/pods-framework/pods/commit/dbc200ceb81b35f0c44af240c5da8003adea5225

<img width="698" alt="Screen Shot 2021-08-22 at 10 48 38 AM" src="https://user-images.githubusercontent.com/709662/130361497-f4c05742-ff93-4b72-9074-a4ffbaf3c9d6.png">

**Comment by sc0ttkclark** [comment]
Updated https://docs.pods.io/code-snippets/modifying-pre_get_posts-categories-tags-show-custom-post-types/ to include directions on how to do this in 2.8 in case people find that through searching.
