### ISSUE TITLE
Autocomplete field broken for many mobile devices

### ISSUE THREAD

**Issue by m9n** [pods-framework/pods#3450]
When you click into an autocomplete field, the devices on-screen keyboard open, but then quickly flicks closed again, making it impossible to enter anything into the field.  This happens on both front-end and back-end fields.

I uploaded short video to Slack to demonstrate the bug: https://podswp.slack.com/files/mina/F0T1XPPGW/pods-autocomplete-bug.mp4

Browsers / OS versions I've confirmed this on on:
- Dolphin / Android 4.1
- Chrome / Android 4.4
- Chrome / Android 6

I've also tried disabling all plugins except Pods, and using the Twenty Fifteen theme.  In that environment, I can't easily test the front-end (my front-end forms were built in my theme template files, using Pods functions/API).  But the bug is still present in the back-end with nothing else going on.

I've managed to isolate this to auto-complete working on single-select fields.  If you use auto-complete with the multi-select, taggable options, then everything works fine.  But single-select seems unusable on a majority of Android devices.

**Comment by jimtrue** [comment]
When you're saying Single-Select, are you meaning Single Select and then AutoComplete or are you limiting your 'choices' to 1 in the options under AutoComplete? And you definitely have Taggable un-selected, correct? So basically, this would be an HTML5 'searchable' drop-down only. Thanks for providing the video for verification of the bug.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! and I think that's fixe all happened around the select2 implementation!
