### ISSUE TITLE
Pod Item Delete - Automatic 301 Re-Direct Created

### ISSUE THREAD

**Issue by shaunretief** [pods-framework/pods#3452]
Hi Guys, Hello from South Africa. Hope you are all well. Query from my side. A client has asked me if it is possible that when a pod item/record is deleted, that a re-direct gets automatically created, thus ensuring no SEO traction is lost and minimises the amount of work that needs to be done. They are wanting to streamline the process instead of having to manually add a 301 via a plugin. Any thoughts out there?

**Comment by jimtrue** [comment]
In most cases when a record is deleted, you're dealing with specific business rules as to 'where' the record should redirect to. Does it go to the Archive for that post type? Related Items? Some other business logic?

If you can write up very specific logical rules for a 301 redirect rule to be added, it might fall under scope. Right now, what you're describing doesn't sound in scope for Pods Framework.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
