### ISSUE TITLE
Filter to modify field value if empty

### ISSUE THREAD

**Issue by bemeall** [pods-framework/pods#3457]
Got a question, what I'm trying to achieve, is to set a value for a field (called with $pod->display()) dynamically if the field is empty.

Found two filters for this, but both are not doing what I need, if i'm right.

First, pods_pods_field, which has al the data I need available, but this one is not called when the value is empty.

Secondly, i tried pods_pods_field_{field_name}. Strangely you have to call this with the field type (in this example 'file'), am I right?
The problem here is that I don't have the initial value of the field available to check if it is already empty. True?

Maybe there's another filter what can do what I want, but I'm out of options at the moment :-)

**Comment by quasel** [comment]
Maybe a bit late but just check the return value? why filter? 

Sorry for the late reply, feel free to comment if you still have questions!
