### ISSUE TITLE
priority of pods_api_post_save_pod_item_ 

### ISSUE THREAD

**Issue by webitekt** [pods-framework/pods#3459]
I'm using facetWP (2.4.1) and pods (2.6.1) on WP 4.4.2.
Each time a post is saved, I save some content to add. fields using the 
 „pods_api_post_save_pod_item_**podsname** hook.

The data is saved correctly in the db.
Im also using facetWP which also hooks in the save_post hook and runs its own index tasks.
Unfortunately the facetWP indexer is always faster than the pods api task (it runs on priority = 10).
I tried to run the pods api task with different priorities less than 10, even 1.
 But it is always the same result, the pods field is saved on post save, but the facetWP indexer is faster and stores the old field value in the index. it sounds like $pod->save() also triggers the "save_post“ hook. What is the best way to investigate this issue and get the $pod->save() to do the job faster?

The actual workaround is to hit the "save" button twice. :-(

**Comment by pdclark** [comment]
I'm also running into this issue — running Facet WP with a Custom Post Type and meta fields powered by Pods, new posts don't appear to be indexed when submitted via a Pods front-end form.
I also tried triggering indexing programmatically, but the post still doesn't get indexed:
```php
add_action(
	'pods_api_post_save_pod_item_weekly_tracker',
	function( $pieces, $is_new_item, $id  ) {
		FWP()->indexer->index( $id );
		return $pieces;
	},
	PHP_INT_MAX,
	3
);
```

Any thoughts @sc0ttkclark ?

**Comment by sc0ttkclark** [comment]
@pdclark new issue please, you can reference this issue number there too
