### ISSUE TITLE
pre-save filters misbehaving from back-end admin to front-end

### ISSUE THREAD

**Issue by Vrhovc** [pods-framework/pods#3467]
I have set some fields to read only in UI, and when using a pre save filter, the fields changed in filter in backend get updated, on the other hand the fields when using a frontend are not updated.
user_longitude and user_latitude are set to read only in UI.

functions.php
add_filter('pods_api_pre_save_pod_item_user', 'my_pre_save_function', 10, 2);
function my_pre_save_function($pieces, $is_new_item) {

```
//Get User Address
$user_address = $pieces['fields'][ 'user_address' ]['value'];
//Get User Postal Code
$user_postalcode = $pieces['fields'][ 'user_postalcode' ]['value'];

$address_to_gps = $user_address . ", " . $user_postalcode;
$arGPS = gps_AddressToGps($address_to_gps);

$user_latitude = $arGPS["lat"];
$user_longitude = $arGPS["lon"];

$pieces['fields'][ 'user_longitude' ]['value'] = $user_longitude;
$pieces['fields'][ 'user_latitude' ]['value'] = $user_latitude;
if ( $user_address ) {
    return $pieces;
}
else {
    //if not throw an error.
    pods_error( 'There was no user address supplyed!');
}
```

}

frontend form code:
user_id = get_current_user_id();
$user_pod = pods( 'user', $user_id ); 

$fields = array( 'user_address', 'user_postalcode', 'user_city', 'user_country', 'user_longitude', 'user_latitude' );
echo $user_pod->form( $fields ); 

It looks like I have found a bug if this can be reproduced.

Regards,

**Comment by jimtrue** [comment]
Can you please provide us the name of the plugin you're using for your Map/GeoCode selection?

**Comment by Vrhovc** [comment]
there is no plugin, it is just a function in theme-s functions.php that handles that http request.

**Comment by jimtrue** [comment]
We'll need that function if you want us to troubleshoot.

**Comment by Vrhovc** [comment]
`function gps_AddressToGps($sAddress){
  $arGPS = array("lat"=>"", "lon"=>"");
  $sLat = "";
  $sLon = "";
  
  // convert address to gps
  $ch = curl_init("https://maps.googleapis.com/maps/api/geocode/json?address=" . urlencode($sAddress.", Slovenija") . "&sensor=false");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  $response = curl_exec($ch);
  curl_close($ch);

  $oGps = json_decode($response, true);
  
  $sStatus = $oGps['status'];
  
  if($sStatus=="OK")
  {
    $oResults = $oGps['results'];
    if(count($oResults)>0)
    {
      $oGeometry = $oResults[0]['geometry']['location'];
      $sLat = "".$oGeometry['lat'];
      $sLon = "".$oGeometry['lng'];
    }
  }
  // return array(lat, lon)
  $arGPS["lat"] = $sLat;
  $arGPS["lon"] = $sLon;
  return $arGPS;
}`

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
