### ISSUE TITLE
Allow external service to Import/Export extended users via some method

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#3470]
Hi,

We're trying to find a way to allow an external service to import data into Pods, ideally we'd use the API for this, but because the API isn't yet ready and has various issues, this isn't possible.

The current solution we're looking at is to import data into Pods via the WP CSV mechanism.

For now I'm looking for a way to export extended user data so I can inspect the data format and produce a CSV template for our external service.

It seems that there is no method for exporting Pods extended user data into a CSV (I'm using this plugin, I don't know whether it's affiliated with the project or is a third party add on - https://wordpress.org/plugins/csv-importer-for-pods/)

So my questions are:

* Is there any method to import and export extended user data into Pods via WP CSV importer?
* Is there any mechanism that would allow a non-PHP, external application (or manual user upload) to import data into Pods, other than WP JSON REST API?

Thanks in advance! :)

**Comment by jimtrue** [comment]
Did you look at WP All Import/WP All Export? Extended User just adds user_meta which is standard and should be supported. The above plugin supports automating methods for repeated imports from CSV/XML, etc.

**Comment by jimtrue** [comment]
And no, CSV Importer with Pods is not affiliated with the project and hasn't been touched in several years.

**Comment by lougreenwood** [comment]
Yep, I gave that plugin a try, but it garbles real fields on export.

for example, I was hoping I would be able to just import the ID of a related post for a real field, but the export from that plugin indicates it expects much more data than that...

**Comment by jimtrue** [comment]
We've reached out to WP All Import to engage with them for a True Import/Export add-on for Pods using their API. Unfortunately, we have to program it ourselves, so it depends on us being able to find available resources for it. CIO created an import for Pods add-on that handles relationship fields and runs on top of WP All Import. I've heard the developer CIO is very helpful, you could reach out to him.

**Comment by jimtrue** [comment]
I believe I actually gave you that advice on this support forum post:
http://pods.io/forums/topic/pods-custom-content-types-and-fields-wp-all-export/

**Comment by lougreenwood** [comment]
Who/What's CIO?

(Side note: we may be able to use the API after all, it seems that accessing Pods CPTs and custom fields is much more reliable over WP API V1...)

Thanks

**Comment by lougreenwood** [comment]
Nope, that wasn't me, but I'll check the thread, thanks...

**Comment by jimtrue** [comment]
You should clarify when you're saying 'the API' and indicate you mean the REST API. Everybody who has a plugin calls their interface an API. We call ours the Pods API.

Sorry on the confusion on the forum post, it sounded like almost exactly what you were asking.

**Comment by jimtrue** [comment]
I also know you can get the Relationship ID if you enable it at the field field with our Pods REST API as well.

**Comment by lougreenwood** [comment]
Yep, WP JSON REST API V1...

**Comment by jimtrue** [comment]
Okay since this is a support question, I'm closing this. GitHub is only used for bug reports and enhancement requests. If you do have a support question, please open a new Support ticket at http://pods.io/forums/ or join us on our Slack Chat at http://pods.io/chat/ and speak up in #support

**Comment by lougreenwood** [comment]
Getting rel ID isn't an issue, but there's a bug that means I can't save if it's in a user post type and also some internal server errors with the Pods API over WP JSON REST API V2 - basically V2 API and pods is a no-go for us, luckily we tried implementing over WP JSON REST API V1 and it's much more stable 

Thanks for your help 👍

**Comment by jimtrue** [comment]
You're quite welcome. Yes, we're aware there's some weirdness with Pods REST API and WP API v2... if you search through the issues here at GitHub you can flag yourself to follow those. They've been marked for some attention, we just have to get some developers who are more up to date on REST API to assist.

**Comment by jimtrue** [comment]
Take a look at this PR #3419 it patches Extended User for v2. Might do exactly what you need.
