### ISSUE TITLE
Magic tags in where clause on relationship-fields does not seem to output values

### ISSUE THREAD

**Issue by toralph** [pods-framework/pods#3472]
[bettingtips.zip](https://github.com/pods-framework/pods/files/213019/bettingtips.zip)
When trying to use magic tags to output on a customized where clause for a Pods relationship-field it does not seem to process the value of my magic tag. I am trying to create a relationship field on a cpt (oddstips), liga (league) which is to display a filtered list of leagues. The leagues in the list is dependent on which country is selected in the "land" field. Each league has a related country.

**The statement rel_land = {@land} gives:**
Database Error; SQL: SELECT DISTINCT `t`.`ID`, `t`.`post_title`, `t`.`post_type` FROM `wp_posts` AS `t` WHERE ( ( rel_land = ) AND ( `t`.`post_type` = "liga" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`; Response: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND ( `t`.`post_type` = "liga" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) ' at line 7

**rel_land.id = {@land.id} gives:**
Database***\* Error; SQL: SELECT DISTINCT `t`.`ID`, `t`.`post_title`, `t`.`post_type` FROM `wp_posts` AS `t` WHERE ( ( rel_land.ID = “" ) AND ( `t`.`post_type` = "liga" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`; Response: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '" ) AND ( `t`.`post_type` = "liga" ) AND ( `t`.`post_status` IN ( "publish" ) ) ' at line 7

**Field translations:**
Land: Country
Liga: League
Tidsperspektiv: Time perspective (longterm or short term)
Spilltype: Type of game (single, double, multiple)
Tips: tip
Resultat: Result

Migrated package in json and screenshots are attached.

**Comment by quasel** [comment]
Seems to work (now)
