### ISSUE TITLE
Edit relationship data in admin screen

### ISSUE THREAD

**Issue by arkonisus** [pods-framework/pods#3475]
If there is a relationship to a dataset of a different post type (pod) it would be very cool if there is a button to edit the selected entry directly without leaving the screen e.g. in a modal view like editing link details in the normal post editor.

For example there could be a relation between an Author field in a post type Books. If i create a new Book i can select the Author from a list of my Author-Post-Type-Entries. With the field-option "Taggable" i am able to create new Author entries within the Books edit-screen.

It would be very helpful if there could be an optional button next to the relation-field to open the modal view where i can edit the whole Author data. Without that button i have to save my book and swith over to the new created Author where i can edit all the missing data.

**Comment by jimtrue** [comment]
Please take a look at #3309 and #3311 Both of these handle what you're looking for.
