### ISSUE TITLE
Number/Currency format validation error with French formatting

### ISSUE THREAD

**Issue by xsalto-camille** [pods-framework/pods#3482]
Hello,

Thanks for great works on this plugin !

We have an error with number validation in French because we use a space for thousand_sep !! This separator is written like a '&nbsp;' in the number/currency input in Wordpress backend when we edit a pod.

Proposed solution on [currency.php line 496](../blob/master/classes/fields/currency.php#L496) : 
`$check = str_replace( array( $thousands, $dot, $currency_sign, html_entity_decode( $currency_sign ), html_entity_decode( $thousands ) ), array( '', '.', '', '', '' ), $value );`

And at line 499 add `\s` to preg_replace : 
`$check = preg_replace( '/[0-9\.\-\s]/', '', $check );`

Do the same for [number.php line 343](../blob/master/classes/fields/number.php#343) : 
`$check = str_replace( array( $thousands, $dot, html_entity_decode($thousands) ), array( '', '.', '' ), $value );`

And add `\s` to preg_replace at line 346 : 
`$check = preg_replace( '/[0-9\.\-\s]/', '', $check );`

Thank you !

**Comment by Ramoonus** [comment]
+1 from me

**Comment by sc0ttkclark** [comment]
+1

**Comment by JoryHogeveen** [comment]
Fixed in #3950 
Thanks for your report @xsalto-camille !
