### ISSUE TITLE
Can not user custom form.php file located in theme folder

### ISSUE THREAD

**Issue by Vrhovc** [pods-framework/pods#3492]
I have tried to do a bit of customization, so I looked at the code and saw I can use my own custom form.php file, when the exact the same form.php(from /ui/front) is placed in the theme folder the file is not used at is should be, it can be found and processed, but there is something wrong with variables..

https://github.com/pods-framework/pods/blob/master/classes/PodsView.php#L589-L594

I have tested a different locations for this original form.php file and noticed that as long as the file is somewhere in plugins directory it all works fine(I know there is some code to check the location of the form.php file for security reasons).

The code i used for including different form.php file:
`add_filter( 'pods_view_inc', 'mau_pods_alternate_form', 10, 4);
function mau_pods_alternate_form( $view, $data, $expires, $cache_mode ){
    //this line set the form.php file that is located in my theme directory
    //$view = 'pods/form.php';

   //this line is used to set the form.php file somewhere else(plugins)
    //$view = str_replace('/plugins/pods/ui/front/form.php', '/plugins/pods-form-setup/pods/form.php', $view);

```
return $view;
```

}`

the first $view is used when using form.php from theme directory
the second I changed to some other location outside or inside pods plugin directory

**Comment by quasel** [comment]
Sorry for the late reply - Closing - if you still have issues or feedback pleas open a new issue
