### ISSUE TITLE
Multiple choice select

### ISSUE THREAD

**Issue by keenam** [pods-framework/pods#3493]
The issue is that I would like to extend WordPress comment field with a custom field where user can choose one from several different selections presented, and the current "Yes / No" field type does not let me present all the choices that I would like to offer.

Please consider expanding this possibility.

Thank you!

**Comment by jimtrue** [comment]
@keenam You should look at a Relationship, Simple Custom Defined List if the values for your comments questions aren't going to change, or creating a Relationship to another Post Type, if you want to keep the values easy to modify. That's the methodology for that.

http://pods.io/docs/learn/field-types/relationship/

**Comment by keenam** [comment]
Many thanks for pointing me in the direction to explore!

**Comment by jimtrue** [comment]
Not a problem. Happy to do it. If you get lost and need pointers, just hop on our Slack chat at http://pods.io/chat/ and ask a question ;)
