### ISSUE TITLE
British pound symbol contains space

### ISSUE THREAD

**Issue by winnersmedia** [pods-framework/pods#3498]
Hi
With a currency field. I always have a space after my British pound symbol (£) then the amount

I think this line of code is the problem in the pods plugin:

file: pods/classes/fields/currency.php:310 to line 317

// Currency placement policy
// Single sign currencies: 100$, ¬£100
// Multiple sign currencies: 100 Fr, Kr 100
$currency_gap = ”;

if ( strlen( $currency_sign ) > 1 ) {
$currency_gap = ‘ ‘;
}
If its reading the British pounds symbol as ¬£ this counts as 2 characters therefore the logic is adding a gap.

**Comment by jimtrue** [comment]
Reference by this Forum Ticket: http://pods.io/forums/topic/pods-british-pounds-currency-field/
