### ISSUE TITLE
Additional Field Options disappeared completely after update. (Plain number decimals settings disappeared!)

### ISSUE THREAD

**Issue by Jossnaz** [pods-framework/pods#3501]
i resetted the pods plugin, i deleted the cache, but the addition field options is not here any longer

http://imageshack.com/i/plNp8qGSp

http://imageshack.com/i/pnlMalrwp

no decimal places to define. In the database table, they have no decimal values

Debug Information

WordPress Version: 4.5.1

PHP Version: 5.6.19-1+deb.sury.org~trusty+1

MySQL Version: 5.5.44

Server Software: Apache/2.4.7 (Ubuntu)

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: Yes
Memcached: No
Redis: No
Object Cache:

Apc: Yes
Apcu: Yes
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: jcr_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /var/www/html/jewcer/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Jewcer's FundingPress

Currently Active Plugins:

Duplicator: 1.1.6
Easy HTTPS (SSL) Redirection: 1.4
Force Email Login: 0.5.1
LayerSlider WP: 5.6.2
Pods - Custom Content Types and Fields: 2.6.5
User Role Editor: 4.25.2

**Comment by sc0ttkclark** [comment]
I'm looking over this issue right now, thanks for letting us know.

**Comment by sc0ttkclark** [comment]
I've got a solution for this ready, pushing it up now

**Comment by sc0ttkclark** [comment]
I just pushed out Pods 2.6.5.1 with the fix for this, but you can also get it from http://pods.io/latest/
