### ISSUE TITLE
Bug in 2.6.5.1 PodsAPI.php for PLL (Polylang)

### ISSUE THREAD

**Issue by fmommeja** [pods-framework/pods#3503]
The line 7326 in PodsAPI.php  today's upgrade is:

`            	if ( function_exists( 'PLL' ) && isset( PPL()->model ) && method_exists( PLL()->model, 'get_language' ) ) {
`
as I guess it should be:

`            	if ( function_exists( 'PLL' ) && isset( PLL()->model ) && method_exists( PLL()->model, 'get_language' ) ) {
`

Found out as I got the error:

> PHP Fatal error:  Call to undefined function PPL() in /wp-content/plugins/pods/classes/PodsAPI.php on line 7326

**Comment by fmommeja** [comment]
When applying above change (PPL to PLL) I get this:

> PHP Parse error:  syntax error, unexpected '}' in /wp-content/plugins/pods/classes/PodsAPI.php on line 8184

??

**Comment by jimtrue** [comment]
@fmommeja We're getting these corrected under #3504 I'll make sure with @JoryHogeveen that we're not having that issue on this bugfix.

**Comment by JoryHogeveen** [comment]
@fmommeja 
Checked with my fix on multiple installations, not getting your parse error.
Did you changed anything else?

**Comment by fmommeja** [comment]
Oh, thanks.
I'm king of a newbie on GitHub, sorry.

**Comment by jimtrue** [comment]
@fmommeja and @JoryHogeveen As soon as it passes tests, I'll merge it to 2.x and you can re-download from pods.io/latest/ and make sure it's working for you as well.

**Comment by fmommeja** [comment]
Thanks a lot for your reactivity  :)
Should I close the report?

**Comment by jimtrue** [comment]
@fmommeja I'll do it when we confirm it's working as expected ;)

**Comment by jimtrue** [comment]
BTW, thank you for reporting the bug as quickly as you did. We can only keep on top of stuff like this with help from our community of users.

**Comment by fmommeja** [comment]
@jimtrue Thx
Have a good day  :)

**Comment by jimtrue** [comment]
@fmommeja We just merged the fix into http://pods.io/latest/ Would you pull it down to your installation and make sure you're working again? Thanks!

**Comment by fmommeja** [comment]
Works fine now  :)
Thanks a lot!

**Comment by jimtrue** [comment]
Thank you so much for confirming this @fmommeja we should be pushing this out in another maintenance release later today.
