### ISSUE TITLE
Backend editor hangs with PageFrog AMP plugin

### ISSUE THREAD

**Issue by payetteforward** [pods-framework/pods#3512]
The backend post editor hangs when the [Facebook Instant Articles & Google AMP Pages by PageFrog](https://wordpress.org/plugins/pagefrog/) plugin. 

The PageFrog plugin adds a mobile preview metabox to the backend post editor: 

<img width="307" alt="screen shot 2016-05-09 at 1 12 36 pm" src="https://cloud.githubusercontent.com/assets/3673460/15121273/c1a7e4d6-15e7-11e6-8c4c-447f1679dd5f.png">

This was causing this error in my nginx server logs:

`2016/05/09 11:52:55 [error] 7448#7448: *482117 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 173.245.52.183, server: payetteback.com, request: "GET /?page_id=3231&pagefrog_preview=fbia&preview=true HTTP/1.1", upstream: "fastcgi://127.0.0.1:9070", host: "www.payetteback.com", referrer: "http://www.payetteback.com/wp-admin/post.php?post=3231&action=edit"`

After getting a hint from a comment on Yoast's website, I was able to fix the problem by removing the metabox from the Wordpress post editor. I commented out lines 168-170 of `/wp-content/plugins/pagefrog/includes/class-pagefrog.php` that add the metabox to the backend. 

```
/*
$this->loader->add_action( 'add_meta_boxes', $plugin_admin, 'add_meta_boxes' );
$this->loader->add_action( 'wp_ajax_pagefrog_get_preview', $plugin_admin, 'pagefrog_get_preview_callback' );
$this->loader->add_action( 'wp_ajax_pagefrog_set_post_status', $plugin_admin, 'pagefrog_set_post_status' );
*/
```

Hope this helps! This is the first Github bug I've ever submitted to please feel free to offer suggestions as to etiquette, formatting, or anything else. :)

**Comment by Ramoonus** [comment]
are you still using this plugin?
or Automattic`s AMP plugin?

**Comment by payetteforward** [comment]
Yep! Still using both, I think.

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
