### ISSUE TITLE
Meta query syntax quoting functions

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3515]
if using 
```
[
'key' => 'due_date',
'value' => 'CURDATE()',
'compare' => '<='
]
```
`CURDATE()` gets quoted as a string, not treated as a function.

**Comment by jamesgol** [comment]
This is a WordPress thing, not a Pods thing. 

See https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-meta-query.php#L629
