### ISSUE TITLE
Trying to use a meta field in "Display Field in Selection List"

### ISSUE THREAD

**Issue by S8nsick66** [pods-framework/pods#3519]
My configuration:
 
[pods_problem.txt](https://github.com/pods-framework/pods/files/259405/pods_problem.txt)

Have discussed this with Jim True in the chat, was asked to create issue with attached json.

**Comment by S8nsick66** [comment]
It's a kindergarten. There are children and adults. Each adult can be connected to several children, with different relationship to each child ('mother' to two children, 'neighbor' to one child)

The relationship works but when I edit a child (wp-admin/user-edit.php) I want to see the connected adults with there names. Currently I see only the post_title (of Pod 3). Tested a lot of things in "Display Field in Selection List", för example {@adult.post_title}, {@adult}. The last one gives me:

Database Error; SQL: SELECT DISTINCT `t`.`ID`, `adult`.`meta_value` AS adult, `t`.`post_type` FROM `wp_posts` AS `t` LEFT JOIN `wp_podsrel` AS `rel_adult` ON `rel_adult`.`field_id` = 290 AND `rel_adult`.`item_id` = `t`.`ID` LEFT JOIN `wp_posts` AS `adult` ON `adult`.`ID` = `rel_adult`.`related_item_id` WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "adult_child_relation" ) ) ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`; Response: Unknown column 'adult.meta_value' in 'field list'

- Pod 1: Adult CTP
 - Field: post_title (the name of the adult)
- Pod 2: Child (extended user)
  - Field: adults (Relationship to Pod 3, bi-directional field 'child') <- here's where I want the 'Display Field in Selection List' to be the name of the adult
- Pod 3: Adult/Child Relation CTP
  - Field: adult (Relationship with Pod 1)
  - Field: child (Relationship with Pod 2, bi-directional field 'adults')
  - Field: post_title (this is the value I get and don't want)

**Comment by quasel** [comment]
another one for #1240
