### ISSUE TITLE
Fields filter

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#3520]
Hi Pods team

Could you please add 
_$metabox[ 'args' ][ 'group' ][ 'fields' ] = apply_filters( 'pods_meta_' . __FUNCTION__ . '_fields', $metabox[ 'args' ][ 'group' ][ 'fields' ], $id );_ 
to classes/PodsMeta.php abvoe 
_foreach ( $metabox[ 'args' ][ 'group' ][ 'fields' ] as $field )_ 
in the public function meta_post ( $post, $metabox ); ?

Just so I can filter fields to display for each page.

Thanks a lot.

**Comment by jimtrue** [comment]
@coding-panda Go ahead and submit your change as a pull request against 2.x on a new branch called "feature/3520" and we can test and verify your change. We'll give you credit when we merge it in as well.

Thanks!

**Comment by jimtrue** [comment]
Here's a link to our [Contributing guidelines](https://github.com/pods-framework/pods/blob/master/CONTRIBUTING.md) as well.

**Comment by coding-panda** [comment]
@jimtrue I'm new to github. Would you advice how I can do it? Thanks,

**Comment by coding-panda** [comment]
@jimtrue I have done it. Not sure if I have done it right but it is on the Pull Requests list now. https://github.com/pods-framework/pods/pulls

**Comment by sc0ttkclark** [comment]
Merged into 2.6.6
