### ISSUE TITLE
Feature Request: improve Relationship field type UI

### ISSUE THREAD

**Issue by argosmedia** [pods-framework/pods#3521]
This is posted here after suggestion from Jim True, in http://pods.io/forums/topic/relationship-field-type-ui/?utm_campaign=website&utm_source=sendgrid&utm_medium=email#post-194582.

The Relationship field type user interface is in my opinion very basic and rather clunky. It’s not user friendly at all, especially for content contributors. On the other hand, I find the interface for the Relationship field type in the plugin Custom Fields Suite impressively good, so I suggest the Pods devs have a look at CFS and do something similar for Pods.

I have made a screenshot of both interfaces, with some comments. The site is in Dutch, but the comments are in English. The top UI is CFS, and the bottom one is Pods.

![ui](https://cloud.githubusercontent.com/assets/1938045/15244889/c706e868-1903-11e6-89a7-bb78a9be05a7.jpg)

**Comment by sc0ttkclark** [comment]
Funny note, Custom Field Suite is written by @mgibbs189 (originally forked from a much older version of Advanced Custom Fields, but now it's completely different) -- Matt Gibbs is also the original and founding developer of the Pods Framework. So you could say we're pretty familiar with CFS, and a fan of Matt's ongoing work :)

Thanks for the note, we'll see what we can come up with here, but if you are able to find a way to contribute code for something like this, we'd love the help.

**Comment by argosmedia** [comment]
Hi, thanks for your reply. What a coincidence Matt is related to both plugins :-)
I would love to see something along the lines of the CFS Related Fieed Type UI in Pods in the future!

I wish I could contribute, but I cannot code... I know HTML and CSS, and I can tweak PHP and do very (and I do mean VERY!) elementary stuff, but that's all. I can test if you like, or if you have something else to do for me please let me know.

**Comment by Archie22is** [comment]
That's still part of contributing to open source :-)

Welcome aboard!

**Comment by sc0ttkclark** [comment]
@argosmedia want to have a go at what the HTML/CSS might look like for this field for Pods?

**Comment by argosmedia** [comment]
I think the CFS layout is perfectly fine. I'm not sure how I can use that to help Pods though. I'm relatively new to WP in general (coming from another CMS) and totally new to Github and contributing to the techy side of open source this way. I just installed Pods a few days ago and still in the beginning stage of getting my grips on it. Some things I get, a lot of other stuff is still abacadabra to me :-) But if you could help me a bit and tell me in practical terms how I could help out, I may give it a shot.

**Comment by sc0ttkclark** [comment]
Maybe we can find another contributor who's interested in this who can assist, or take point on this. We're open to having it, but our Autocomplete option does let you select from a list as well as reorder. It's not the same exact interface, but it can be useful in the interim for you.

**Comment by JoryHogeveen** [comment]
@pglewis I this would be implemented for the current pick field. Would this get troublesome for the 2.7 branche? (since you are busy with a new field implementation)

**Comment by pglewis** [comment]
This is definitely a job for the new fields, but not sure if it could hit 2.7.  Relationship field views are undergoing a complete rewrite so any effort to work this into place before 2.7 would have to be duplicated to port it over.

**Comment by JoryHogeveen** [comment]
Ok! :+1:
