### ISSUE TITLE
#2607 broke table storage relationships

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3522]
#2607

```
LEFT JOIN `@wp_podsrel` AS `rel_task` ON
                        `rel_task`.`field_id` = 33
                        AND `rel_task`.`item_id` = `t`.`ID`

                    LEFT JOIN `wp_posts` AS `task` ON
                        `task`.`ID` = `rel_task`.`related_item_id`


                    LEFT JOIN `wp_pods_task` AS `task_d` ON
                        `task_d`.`id` = `rel_task`.`ID`
```

in my case with commit `395dc356df91ad963629488dfd9f5cfb24fc6ac1`, `$traverse[ 'id' ]` == `$traverse[ 'pick_val' ]` which both have values of `task`, and its a many (assignment) to one (task).

**Comment by jimtrue** [comment]
References #2607. Needed to be in the comments for the link and reference to the other issue.

**Comment by pcfreak30** [comment]
Already did so :)

**Comment by quasel** [comment]
is this still an issue?

**Comment by quasel** [comment]
yeah shouldn't have happened - but that's life! if you remember it… and guess if it where true we would have seen more issues popup in that area - wouldn't we? You linked to https://github.com/pcfreak30/pods/commit/618aed4b11f8a9a255961cd1f3a7fba8f4be8ed5 in the other three the code is still the same…

Going to close this if you still see the need open a PR ;) Thank You!
