### ISSUE TITLE
"Plain Number" only accepts integers

### ISSUE THREAD

**Issue by atlanticcan** [pods-framework/pods#3524]
I needed a field for latitude and longitude and Plain Number seemed like the best fit. Unfortunately, it rounded my coordinates to integers.

It doesn't look like there's any data type for decimal/long/double/floating point numbers.

**Comment by sc0ttkclark** [comment]
Have your tried the option under Additional Field Options for decimals? Default is integer, but you can accept decimal values easily with a definition of how many places you want to normalize to.

**Comment by atlanticcan** [comment]
Oh, you are absolutely correct. Thank you both for your help, Scott and Jim. I apologize for not seeing that.

I'm very grateful for the work you've put into Pods - it's a huge improvement over regular WordPress.

**Comment by jimtrue** [comment]
Thanks so much @atlanticcan ! Always appreciate the kudos ;)
