### ISSUE TITLE
If you make a Yes/No field required, Yes is the only valid value

### ISSUE THREAD

**Issue by atlanticcan** [pods-framework/pods#3525]
I tried to require my users to provide a boolean value. Yes/No fields are represented by a checkbox. When I made that required, there was no way for users to save the object without answering Yes.

I ended up using a Simple (custom defined list) Relationship with "Yes" and "No" strings instead.

**Comment by jimtrue** [comment]
This is available under "Additional Field Options" you can select radio buttons or select drop down will give yes no options for required. Checkbox will only ever give one check box.

**Comment by atlanticcan** [comment]
I can't recall what I ended up doing. I've switched up my career, so I'm not involved with that anymore. I'll close this.

Thanks for you help learning how to use Pods :)
