### ISSUE TITLE
Allow table storage fields to be defined as not null

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3538]
Right now all fields have `DEFAULT NULL` in the DDL. Even a field with a default value has it. This needs to be changed or have an option to.

**Comment by quasel** [comment]
hi, can you go into more detail? in my test this works just fine, but that depends on the use case ;) I guess  - I'm going to close this issue - feel free to open a new one - a good starting point is https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff
