### ISSUE TITLE
Feature request - Separator field type

### ISSUE THREAD

**Issue by erikfrye** [pods-framework/pods#3545]
When adding many custom fields to a pod, grouping these fields becomes hard. Having a separator as a field type would allow a user to create space between groups of fields and make them a little more user friendly.

**Comment by JoryHogeveen** [comment]
With the upcoming field groups I doubt this will be needed.
@sc0ttkclark any thoughts?

**Comment by jimtrue** [comment]
#799 Group Fields 2.8 will be covering this particular need. Closing.

**Comment by sc0ttkclark** [comment]
Groups are in Pods 2.8 now and there are also new Layout Element field types: Heading and HTML content. That should cover the needs. Not opposed to an hr kind of layout element field type in the future if desired and it looks good.

**Comment by lkraav** [comment]
> Groups are in Pods 2.8 now and there are also new Layout Element field types: Heading and HTML content. That should cover the needs. Not opposed to an hr kind of layout element field type in the future if desired and it looks good.

Groups probably take care of it. We'll see.

**Comment by erikfryed2l2** [comment]
Excellent news. Is there a release date for 2.8?

**Comment by sc0ttkclark** [comment]
No release date yet. We are finishing up conversion of our fields to React and once that is done we will go into beta some time at the end of this month.
