### ISSUE TITLE
Refactor PodsUI to use Pods::save

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3577]
PodsUI current does direct DB calls bypassing all pods infrastructure code entirely which can cause tons of issues. My case was caching was not flushing. Pods settings use pods_ui for forms so this needs way better handling.

**Comment by quasel** [comment]
sounds reasonable? but that's for another day I guess ^^

**Comment by JoryHogeveen** [comment]
@pcfreak30 is this one fixed by #5062 as well?

**Comment by pcfreak30** [comment]
They are separate issues last I remember or I would have put then in 1 issue/pr.

**Comment by JoryHogeveen** [comment]
Ok, I thought the PR would fix them both since you referenced this issue in #4960

**Comment by sc0ttkclark** [comment]
Fixed via 491954afddfec87adc018cf281875103a14b523f
