### ISSUE TITLE
register api field needs an update

### ISSUE THREAD

**Issue by bustapaladin** [pods-framework/pods#3581]
If wp debug is turned on https://gyazo.com/379df6bbb764e6b86c9b8021c39281e4

By searching for said call or function how you guys may call it:

```
if ( $read || $write ) {
            register_api_field( $object_type, $field_name, $args );
        }
```

Don't know if that is causing those rows of notices.

**Comment by sc0ttkclark** [comment]
Have a fix for this, will merge it shortly.
