### ISSUE TITLE
Tiles CSS not uniform

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#3591]
http://sc0tt.me/1S0X3i0j043Q/Screen%20Shot%202016-06-22%20at%209.58.06%20PM.png

**Comment by sc0ttkclark** [comment]
Handle, remove and download should all be at top of each square and squares should be uniform max size

**Comment by sc0ttkclark** [comment]
Also made handle use dashicon

**Comment by JoryHogeveen** [comment]
Check PR above. I thing this is fixed for the 2.7 branche

**Comment by sc0ttkclark** [comment]
Fixed in #3592
