### ISSUE TITLE
Result after upgrade from 2.6.6-a1 to 2.6.6

### ISSUE THREAD

**Issue by fmommeja** [pods-framework/pods#3596]
Hi, this is what I got after #3503 was resolved (with Divi 2.7.7 + WP 4.5.3):

![sb-pods2-6-6-a1](https://cloud.githubusercontent.com/assets/19188155/16338214/88690c1a-3a1b-11e6-891a-6fd332db2a1c.jpg)

And, after upgading to 2.6.6, here is the result:

![sb-pods2-6-6](https://cloud.githubusercontent.com/assets/19188155/16338215/886c4d94-3a1b-11e6-88ae-9e715e5458f7.jpg)

Any advice ?
Is it still relative to Polylang?

**Comment by fmommeja** [comment]
Here was the Pods 2.6.6-a1 hover result:
![sb-pods2-6-6-a1-2](https://cloud.githubusercontent.com/assets/19188155/16338369/7d022608-3a1c-11e6-852a-b04660f63bd7.jpg)

**Comment by fmommeja** [comment]
Here is the source code of the page with Pods 2.6.6-a1:
[https://www.dropbox.com/s/jwvqr7cxsdg5tzv/sb-pods266a1.html?dl=0](url)

Her is the one with Pods 2.6.6:
[https://www.dropbox.com/s/u3dgw874o7ql5bn/sb-pods266.html?dl=0](url)

Do you need something else?
I can't give you a direct link to the site as it is a restricted access one and my client wouldn't allow it, sorry.

**Comment by JoryHogeveen** [comment]
This hardly could be related to polylang. It looks like shortcodes aren't being processed...

**Comment by sc0ttkclark** [comment]
Maybe it's related to some other change between 2.6.5.2 and 2.6.6?

**Comment by JoryHogeveen** [comment]
Probably yes, guess this is a wysiwyg field? If so, any changes there?

**Comment by jimtrue** [comment]
@fmommeja These locations with the [et pb] shortcodes, are they inside a Pods Template or inside a content box within one of your custom fields? Both of your URL's above give 404 errors, so we need more information.

**Comment by fmommeja** [comment]
@jimtrue 
Hi Jim,  :)
I don't know why the URLs don't work when clicking on them, but you can copy/paste them and its OK 👍 
https://www.dropbox.com/s/jwvqr7cxsdg5tzv/sb-pods266a1.html?dl=0
https://www.dropbox.com/s/u3dgw874o7ql5bn/sb-pods266.html?dl=0

**Comment by jimtrue** [comment]
Unfortunately, this is like your inspection source. We need to know what you're doing to generate those areas: ie Pods Templates, Shortcodes in Custom Fields or Content boxes or actual PHP templates. Neither of the above are helping; all we can tell is the Divi shortcodes aren't being processed in those areas.

**Comment by jimtrue** [comment]
Also, do you have this on a development website? We always say it, but check to make sure you did a Clear Cache (Pods Settings, Clear Cache), just to rule that out.

**Comment by fmommeja** [comment]
Here is the Pods shortcode in a Text Divi Module:
[pods name="listedeformats" slug="carre-vintage-chasse-congo" template="Formats template"]

Other shortcodes on the page under the previous one in a Text Divi Module:
VINTAGE >[button link="/collections/vintage/#theme-africa" color="black"]Africa[/button][button link="/collections/vintage/#theme-american-daily-life" color="black"]American Daily Life[/button][button link="/collections/vintage/#theme-celeb" color="black"]Celebrities[/button][button link="/collections/vintage/#theme-cities" color="black"]Cities[/button][button link="/collections/vintage/#theme-engines" color="black"]Engines[/button][button link="/collections/vintage/#theme-mideast" color="black"]Middle East[/button][button link="/collections/vintage/#theme-nature" color="black"]Nature[/button][button link="/collections/vintage/#theme-shipssailing" color="black"]Ships & Sailing[/button]

The weird thing is that these button shortcodes are still correctly displayed at the bottom of the page:

![sb-pods2-6-6-bottom](https://cloud.githubusercontent.com/assets/19188155/16341093/ad25364a-3a2b-11e6-830f-1093f0286cf7.jpg)


---> And I _did_ purge the Varnish cache multiple times.

**Comment by jimtrue** [comment]
Can you share the contents of the  Template: "Formats template"?

Looks like, to me, something is improperly nesting or kicking out something that is preventing something from finishing.

**Comment by fmommeja** [comment]
Here is my Formats template:
`<div class="pttip">
<a href="#" class="linktt">Formats disponibles</a><div class="tooltip">[before]<div class"formats-wrap">
[/before]
    [if formats_associes]
        [if titre_liste]
            <h5>{@titre_liste}&nbsp;:</h5>
        [/if]
        <ul>
            [each formats_associes]
            <li>{@formats_associes.largeur} x {@formats_associes.hauteur} cm[if formats_associes.largeur_ouverture] - ouverture {@formats_associes.largeur_ouverture} x {@formats_associes.hauteur_ouverture} cm[/if]</li>
            [/each]
        </ul>
    [else]
        <p>Aucun format disponible.</p>
    [/if]
[after]</div>[/after]</div></div>`

**Comment by fmommeja** [comment]
Made a test project without Divi Builder, simply pasting the Pods shortcode:
![sb-pods2-6-6--1](https://cloud.githubusercontent.com/assets/19188155/16343380/25294afe-3a37-11e6-8e83-21c58ebcc473.jpg)

Here is the result:
![sb-pods2-6-6--2](https://cloud.githubusercontent.com/assets/19188155/16343381/25316900-3a37-11e6-985a-2a8f4eed585f.jpg)

**Comment by jimtrue** [comment]
Honestly, that looks like none of your shortcodes are being processed (including the Pods one). Have you tried backing up your current 2.6.5.2 and downloading a fresh version of 2.6.6 (not 2.6.6-a1) directly from the repo and installing to see if it resolves the issue?

**Comment by fmommeja** [comment]
OK, I'll try that

**Comment by fmommeja** [comment]
- Deleted "pods" plugin directory via FTP.
- Downloaded "pods.2.6.6.zip" from https://wordpress.org/plugins/pods/
- Unzipped it
- Copy back to plugin directory via FTP
- Purge cache
- Activate plugin in the WP admin
![sb-pods2-6-6--3](https://cloud.githubusercontent.com/assets/19188155/16344220/c7c4b880-3a3b-11e6-9248-03754febcad7.jpg)

- Reopened "Test PODS" project page
- Update page
- Display page

--> Same result  :/
![sb-pods2-6-6--4](https://cloud.githubusercontent.com/assets/19188155/16344298/35ada7b2-3a3c-11e6-8051-99d7dc10606c.jpg)

Sorry

**Comment by jimtrue** [comment]
No need to apologize; we're sorry you're having issues and hoping to help you troubleshoot.

I'm still highly concerned that the pods shortcode isn't being processed in that standard visual text editor (assuming that is the regular Test Page Content Editor).

Can you give us a Pods Admin, Components, Migrate: Packages, Enable and then go to Migrate: Packages and export your configuration (doesn't have to be your data, though we'll need a little bit of something to test it). The export is a big text box (JSON), just cut and paste it into a text file and zip it and upload it here.

That will include your Pods Configurations and Templates

**Comment by fmommeja** [comment]
Here it is:
[sb-pods20160624.json.zip](https://github.com/pods-framework/pods/files/332135/sb-pods20160624.json.zip)

**Comment by fmommeja** [comment]
For you can assume that is the regular Test Page Content Editor…
Most basic test page:
![sb-pods2-6-6--5](https://cloud.githubusercontent.com/assets/19188155/16344744/70075cbc-3a3e-11e6-844a-a33c14881ed5.jpg)

Result:
![sb-pods2-6-6--6](https://cloud.githubusercontent.com/assets/19188155/16344753/789a5c80-3a3e-11e6-877d-c55e5cb51e33.jpg)

**Comment by jimtrue** [comment]
I could tell it was the standard visual context editor based on your screenshot. That's the default page theme for Divi.

**Comment by jimtrue** [comment]
BTW, not the Varnish Cache, I mean the Pods Settings, Clear Cache. It should happen automatically on upgrade, but that's the one that clears Pods specific transients, etc. in the database.

I've got it locally and I'm getting the pods shortcodes processing just fine, but the one missing element I don't have is the Divi theme. It's premium and we don't have a copy of it. We can't troubleshoot everything out there unfortunately.

Can you deactivate everything except for Pods, Polylang and Divi, just to rule out anything else impacting the issue you're having? (again, if you've got a development website that would be better for testing so you don't impact your client, this sounds like you're running on an internal website, though).

**Comment by fmommeja** [comment]
Well, did Clear _Pods_ Cache with no more results…
Try to deactivate plugins next.
I'll keep in touch.

**Comment by fmommeja** [comment]
And yes, fortunately for my client's sake, I'm testing on a clone  :)

**Comment by jimtrue** [comment]
Thanks for continuing to work on this from your end; we're also doing stuff from our end as well. Definitely leads it to be more 'code' based if you're on a cloned box and you're seeing the issue.

**Comment by fmommeja** [comment]
So, I deactivated _all_ plugins except: __Pods__ and __Polylang__
__Divi__ is the theme so I didn't deactivate it.

Emptied the _Pods_ cache once again… same result.

Then I deactivated Polylang…  it worked !!!

Reactivated Polylang… broken again!

So we can say that once again Polylang is to blame…

I'll now try to reactivate all but Polylang.  ;)

**Comment by jimtrue** [comment]
From my testing locally, I also ran into the 'opposite' issue of yours, but guessing they're somewhat related since they're both related to the shortcode. My shortcode processes twice when Polylang is activated, once when I deactivate Polylang.

We'll call it the interaction with Polylang and Pods Shortcode as the issue at the moment for clarity. We've got our guys troubleshooting as well.

**Comment by fmommeja** [comment]
Works fine with all plugins activated except Polylang.

Breaks as soon as Polylang is activated.
HTH

**Comment by jimtrue** [comment]
For confirmation: "breaks" in your case means the shortcode isn't processed at all, right?

**Comment by fmommeja** [comment]
Right :)

**Comment by fmommeja** [comment]
Just for my knowledge, what should be the fine way for me to say it so you can understand without asking?  :)

**Comment by jimtrue** [comment]
"breaks" should just be specifically defined. In your case, the error is that the pods shortcode isn't being processed with this upgrade with Polylang activated, so that's the problem you're having. We've got another person to duplicate the same issue. Mine is apparently *another* bug (mine processes, but does it twice)

**Comment by jimtrue** [comment]
Well, in addition, it _looks_ like it's preventing some of your Divi shortcodes from being processed as well.

**Comment by fmommeja** [comment]
Maybe a cross bug with yours, because the Divi shortcodes appear not to be processed in the upper part of the page, but they _are_ displaying correctly in the bottom part like they usually do when they are correctly processed!

**Comment by jimtrue** [comment]
Yep, Divi does a lot of 'sub shortcode' and nested shortcode calling (especially inside text boxes inside the Divi builder) so yep, I'd say somewhat related.

**Comment by jimtrue** [comment]
@fmommeja Go ahead and grab our patched version at http://pods.io/latest/ and replace that in your cloned copy and see if that fixes your problem with Polylang, Pods and Divi.

**Comment by fmommeja** [comment]
Thank you @jimtrue ! and the rest of the team of course!
Everything's working fine now for me  :D 

Have a good evening and take care
See you

**Comment by jimtrue** [comment]
Perfect, thanks!
