### ISSUE TITLE
New pods fields for Posts post type not appearing in Posts pages

### ISSUE THREAD

**Issue by remcokalf** [pods-framework/pods#3598]
When I make new extra fields in the Posts post-type, they are not appearing in Post pages in Wordpress backend.

- Previously made extra fields in Posts show up okay
- Extra fields in other custom post types and pages are showing up okay.
This seems to happens only with Posts.

Not sure if it has to do with the new Pods version 2.6.6 that I installed this morning. 
I am on WP 4.5.3

I don't see any php errors/notices/warnings.

**Comment by jimtrue** [comment]
Do you mean Extended Posts? Or any Custom Post Type?

**Comment by remcokalf** [comment]
Happens only with Extended Posts. With all my Custom Post Types I can add fields and they appear as normal.

**Comment by jimtrue** [comment]
I had myself and another person just test this one on extended posts and no issues, but that doesn't rule out a potential problem. Standard troubleshooting:

- Deactivate other plugins but Pods and switch to a Twenty-something theme and see if you still have the issues with other fields not showing
- Deactivate or purge any server based cache if you're running one, especially if it impacts the database
- If this was working in the prior version and you just upgraded, can you go back to your original version and see if you have the same issue?

**Comment by remcokalf** [comment]
I'm really sorry to have bothered you with this, it is not a Pods issue. I tracked it down to a Tabify Edit Screen plugin setting.

**Comment by jimtrue** [comment]
No worries, at least you know we're responsive to issues :)

**Comment by remcokalf** [comment]
And that is highly appreciated, and very rare :-)
