### ISSUE TITLE
Getting metadata >> Pods logic vs WP logic

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3614]
## Related issues:
- #1484
- #1578
- #5055
- #5147
- https://wordpress.org/support/topic/array-from-ae-pro-template-pods-relationships-fields/

## Summary
This is a follow up of my conversation with @jimtrue at Slack (29-06-2016).
I'll take post relationships as an example at first:

If I would setup Pods to have relationship from one post_type to another and use `get_post_meta` to get the relationship data, Pods filters this and returns the WP_Post property structure as an associative array.

Example **without** Pods logic:

``` php
$var = get_post_meta( $post_id, 'relationship_meta_key' );
print_r($var);

// returns:
// Note that the array key doesn't reflect the post id
Array
(
    [0] => // the post id
    [1] => // the post id
    etc.
)
```

Example **with** Pods logic:

``` php
$var = get_post_meta( $post_id, 'relationship_meta_key' );
print_r($var);

// returns:
// Note that the array key doesn't reflect the post id
Array
(
    [0] => Array
        (
            [ID] => // the post id
            [post_title] => // the post title
            [post_content] => // the post content
            [post_excerpt] => // the post excerpt
            [post_status] => // the post status
            etc.
        )
    [1] => Array
        (
            [ID] => // the post id
            [post_title] => // the post title
            [post_content] => // the post content
            [post_excerpt] => // the post excerpt
            [post_status] => // the post status
            etc.
        )
    etc.
)
```

Another example is with the recent oEmbed field.
As a theme developer I'd like to have Pods power for giving a client a field to give their imput for an oEmbed field but I'd like to handle this myself in a theme.
Currently the only way to do this is to use Pods functions to get the raw data or to use `get_post_custom` to get literally all post metadata (this function doesn't get filtered by Pods).

Example **without** Pods logic:

``` php
$var = get_post_meta( $post_id, 'oEmbed_meta_key' );
print_r($var);

// returns:
Array
(
    [0] => // RAW VAR FROM DB
)
// This is usable for whatever the developer would like to do
```

Example **with** Pods logic:

``` php
$var = get_post_meta( $post_id, 'oEmbed_meta_key' );
print_r($var);

// returns:
Array
(
    [0] => '<iframe scrolling="no" frameborder="no" src="VAR"></iframe>'
)
// This is restricted to the WP (and Pods) logic for oEmbed. 
// If I would like to use WP's oEmbed function but still would like to have 
// some other attributes or classes, this would be fairly difficult to do.
```

For me as a developer for plugins and themes the Pods logic for `get_post_meta` seems a bit odd.
`get_post_meta` is a WP core function to get post meta directly from the database (or meta cache) so I don't expect to get "filtered-for-display" post data in this case.
If I would like to display output with Pods logic I'd use `pods_field_display( POD_NAME, ID, META_KEY )` or any other Pods method.

I'm not implying to to have a solution (since it's been in Pods for a while) but just would like to get this up for discussion.

The above is a result of Pods filtering the `get_post_meta` function with the `display` function of the Pods field.
IMO `get_post_meta` is a function to get raw metadata from the database for use as you like but not to get metadata that has been filtered with various functions.

This is merely my thought about this matter so any feedback would be very much appreciated!
(of course all the above goes for other object metadata aswell  (tax, user, etc.) )

**Comment by JoryHogeveen** [comment]
@sc0ttkclark When do you thing this could be discussed? My recent comment on the address field is also related.

**Comment by JoryHogeveen** [comment]
Also related to the new WP Gallery output in Pods 2.6.8.
`get_post_meta()` would return the gallery HTML instead of the attachment post ID's.
I would still expect attachment post ID's in this case since I asked for metadata, not formatted HTML.

**Comment by JoryHogeveen** [comment]
Update on this issue.
There are some filters/functions to disable Pods logic in your themes.

**Disable everything:**
`add_filter( 'pods_meta_handler_get', '__return_false' );`

**Disable object_type:**
`pods_no_conflict_on('post') // Disable Pods meta handling for post types`
Possible values: `post` / `taxonomy` / `media` / `user` / `comment` / `settings`

**Comment by raptor235** [comment]
When is this supposed to run?

add_filter( 'pods_meta_handler_get', '__return_false' );


I've just spend 3 hour trying to get to the bottom of this and it seems that pods->run functions which gets run on __construct triggers everything before the filters can be set via functions.php.

**Comment by raptor235** [comment]
@JoryHogeveen would appreciate a quick response... this is a blocker for looming deadline 

thank you

**Comment by raptor235** [comment]
@JoryHogeveen I'm absolutely not trying to be demanding here by any means, just would love to hear from you if you're around.

**Comment by raptor235** [comment]
Also tried the pods_no_conflict_on but it seems to be ignored... I see that polylang query is added to the join statement by pods.

`
pods_no_conflict_on( 'taxonomy' );
$catalogs         = get_term_meta(2520,'catalogs');
var_dump($catalogs);
`

**Comment by JoryHogeveen** [comment]
Hi @raptor235 
I honestly never actually used it. I just posted it here since @sc0ttkclark noted me for these filters.

Maybe `add_filter( 'pods_meta_handler_get', '__return_false', 99 );` ?

Let's continue on Slack on your actual problem to keep this issue on topic :)

**Comment by quasel** [comment]
as the question surfaced in the Beaver Community too - because of the way how we return image relations vs the expected id - any new ideas?

**Comment by tobiasschutter** [comment]
We ran into the exact same issue with admin columns when writing the 'editing' part of each Pods field. The `get_post_meta` becomes unreliable with Pods as it tries to turn it into a display method. We need to reliably get the database value with `get_post_meta`, without Pods interfering with it.

Like @JoryHogeveen suggested, introducing a display function `get_pods_field()` for a Pod field would solve this. You could then remove the hook into `get_post_meta`.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Why is this closed?

**Comment by sc0ttkclark** [comment]
It's not a perfect system, but that's why it works -- because people will ping the closed issues that don't need to be iceboxed :)

**Comment by AnthonyIacono** [comment]
I personally agree that the behavior of get_post_meta() and get_term_meta() should not be changed by Pods. That being said, I'm sure this is a breaking change. Would it be possible for Pods to introduce some functions like `pods_get_post_meta_raw` and `pods_get_term_meta_raw`? That way, we can get around the filter on a case to case basis.

**Comment by JoryHogeveen** [comment]
Closing this issue.
The latest versions of Pods no include settings which can disable this behavior if you user wants this!
