### ISSUE TITLE
Notice: Undefined index: menu_position in 

### ISSUE THREAD

**Issue by bustapaladin** [pods-framework/pods#3617]
With wp debug turned on I get this , it seems no matter what number you put for the position of the custom post type in the admin menu it won't change and the notice will keep showing.

**Comment by JoryHogeveen** [comment]
Hi @bustapaladin 
Can you give us a bit more information? Maybe a line number or other debug info?

**Comment by bustapaladin** [comment]
It appears this is caused by some other plugin. Need to investigate.
