### ISSUE TITLE
Field descriptions

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3622]
Can you make it a bit different than other text.
For instance:

```
.pods-form-ui-comment {
    font-style: italic;
    color: #999;
}
```
And give table th, td some 10px paddings on all side, now all is stucked to "the wall".
Man, you are Mozarts of code but suck for design.

**Comment by sc0ttkclark** [comment]
I can appreciate that you want to improve Pods and really am thankful for your suggestion. We'll take a look at it and see if we can improve with this and other tweaks. We really want to make things more responsive.

> Man, you are Mozarts of code but suck for design.

Your last sentence really usurped your whole helpful effort here, that sort of attitude does little to motivate developers to do the things that you had previously asked so kindly.

**Comment by JoryHogeveen** [comment]
I think making the description italic is a user preference instead of an actual UI improvement.
I'd say we should just add the "description" class. This is a WP class for this ( italic & #666 ).

Also, the fields already have a 10px padding so I don't realy get that "problem"..
The paddings from the side are just the default paddings from the WP meta box UI. Nothing to do with Pods.

**Comment by StaggerLeee** [comment]
Common, dont be easy offended. 
Look how guy from Australia is doing in ACF. He is one and alone, you are bunch of developers, 12 persons, maybe more of you..

**Comment by sc0ttkclark** [comment]
We're not all working full time on Pods, we don't charge for Pods most-wanted features, we are made up of developers who each have a voice and can make this project as great as we wish it.

We're not offended, it's just not helpful.

**Comment by sc0ttkclark** [comment]
Joey that idea sounds good, adding the description class makes sense.

**Comment by JoryHogeveen** [comment]
https://github.com/pods-framework/pods/commit/98663d0b9d2ad4b9e651a14b51eb6c861f66a95f

**Comment by sc0ttkclark** [comment]
Thanks for the contribution Jory, will review shortly.
