### ISSUE TITLE
Feature Request (Admin UI): Show Field column on Taxonomy Terms table

### ISSUE THREAD

**Issue by fireundubh** [pods-framework/pods#3645]
I would like to be able to show a custom taxonomy field on the terms table, preferably at a specific column index.

For example, if I have a field named "Menu Order," I'd like to change this:

Name | Description | Slug | Count
--- | --- | --- | ---
Contract | | contract | 0
Full-time | | full-time | 0
Part-time | | part-time | 0

To this:

Menu Order | Name | Description | Slug | Count
--- | --- | --- | --- | ---
0 | Full-time | | full-time | 0
1 | Part-time | | part-time | 0
2 | Contract | | contract | 0

For custom taxonomies, you already have the "Show Taxonomy column on Post Types" option. 

This new feature would work similarly at the field level, and you'd toggle the option in the Advanced tab section.

**Comment by sc0ttkclark** [comment]
This is what you're looking for, very useful and popular with our users! https://wordpress.org/plugins/codepress-admin-columns/

Thanks for the suggestion, we'll look at doing something like this in the future to keep things simple, but for now it's not a high priority since there's such a great (free) solution out there already which we've got direct integration with.

**Comment by fireundubh** [comment]
Admin Columns works with only post types, custom post types, comments, media library, and users.

Admin Columns does not work with custom taxonomies.

**Comment by sc0ttkclark** [comment]
Looks like Taxonomies is currently a pro feature -- https://www.admincolumns.com/features/

Actually, our Friends of Pods can get access to a 15% off coupon for Admin Columns Pro at the Bronze (or higher) level -- https://pods.io/friends-of-pods/rewards/

**Comment by fireundubh** [comment]
I just saw that. I'm not keen on subscription-only products.

I'll just implement this myself. Thanks.

**Comment by sc0ttkclark** [comment]
No problem, totally understand that :)

**Comment by fireundubh** [comment]
Do you know what filter is used instead of `request` for Pods custom taxonomy pages?

This function isn't executed at all when using the `request` filter.

```php
function cqt_order_columns($vars)
{
	-dd($vars);
	if (!isset($vars['orderby']) || (isset($vars['orderby']) && $vars['orderby'] == 'term_order'))
	{
		$vars = array_merge($vars, array(
			'meta_key' => 'term_order',
			'orderby' => 'meta_value_num'
		));
	}
	return $query;
}
add_filter('request', 'cqt_order_columns', 10, 2);
```

**Comment by pglewis** [comment]
Not sure if this is the problem but you're specifying 2 parameters in your `add_filter` call, but the function only has one.

**Comment by fireundubh** [comment]
Sorry, I should say that `-dd($vars)` is a [Kint](http://raveren.github.io/kint/) function that dumps the output of `$vars` and exits the function. None of the code below that actually runs. I'll clarify in the example.

**Comment by fireundubh** [comment]
I found the right filter via the WP issue tracker: [#35381: Introduce `WP_Term_Query`](https://core.trac.wordpress.org/ticket/35381).

In 4.5.x, there's a new filter that's not `query`, `query_string`, `query_args`, or `request`!

`WP_Term_Query` uses `get_terms_args`.

**Comment by pglewis** [comment]
Good find!  I didn't have any info for ya off the top of my head, glad you figured it out.
