### ISSUE TITLE
shortcode and page title

### ISSUE THREAD

**Issue by dsg257** [pods-framework/pods#3653]
after having a lot of problems displaying a pod with the shortcode incerting it into the page 
what i founf is when i had the page title of test page and pods page office bearers  it displayed properly 
but when i created a page called office bearers and called the pod office bearers the pod data is shown below the header menu but above the sidebars 
probably more a conflict than a bug but thought better to let you know

**Comment by quasel** [comment]
Sound like a naming conflict - naming different things the same is never a good idea in WordPress :D 

Sorry for the late reply, feel free to comment if you still have questions!
