### ISSUE TITLE
WPML Filtering posts and taxonomies in Pods Relationship meta box comp-1858

### ISSUE THREAD

**Issue by srdjan-jcc** [pods-framework/pods#3675]
Content should be filtered according to Language Resolution.
Current Language is determined by edited post language (as seen in top bar switcher).

![pods-rel](https://cloud.githubusercontent.com/assets/3109112/16875735/37954d1c-4aa1-11e6-80e2-fa1592f49fed.png)

If content is not translated - better to exclude those entries
than trying to offer user to use temporary default language.

We should enable WPML filtering by setting WP Query arg `suppress_filters` to `false`.
Check if other WPML API calls are needed.

**Comment by srdjan-jcc** [comment]
@jimtrue Can you please point us to place in code where we can do few tests?
Thank you.

**Comment by jimtrue** [comment]
Actually going to point this one to @JoryHogeveen as he handled the Polylang integration and might be better able to assist.

**Comment by JoryHogeveen** [comment]
@srdjan-jcc 
I can't recall this happening with wpml. I guess you're on the "test" post_type supplied with the import file I've send you?
In my tests here I only get results of relationship objects of that language. Objects that are only available in a different language should be excluded.

Only with taxonomy pages and the top bar switcher set to "all languages" will Pods show options from multiple languages since we don't know what language will be used.

The current language logic can be found here:
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L8246

**Comment by JoryHogeveen** [comment]
Oh, just to make sure we have the same code, I have WPML 3.4.0 installed

**Comment by srdjan-jcc** [comment]
@JoryHogeveen Thank you for update.
I understand now it's by design.

'Tests' custom post types are set as translatable,
so maybe relation fields should be filtered by language.

We usually try to avoid having content in mixed languages
and try to use WPML Multilingual Setup screen to define behaviour.

WPML should take care of Relation fields according to translation preferences.
Only obstacle can be if field value is not post meta.

Please let me know what do you think.
I can do more tests to confirm it's working.

**Comment by JoryHogeveen** [comment]
@srdjan-jcc 

> 'Tests' custom post types are set as translatable,
> so maybe relation fields should be filtered by language.

It should work like that, is this not working on your setup?

I totally agree to avoid having mixed languages but it a post type isn't set for translations it's hard to know what language the user would want to relate to. That is why I'm not filtering in that scenario.
But on my tests this is only possible with non-translatable post_types and on the edit-tags.php screen when the admin bar is set to "all languages".

Please verify if this is the same in your setup.
Thanks!

**Comment by srdjan-jcc** [comment]
@JoryHogeveen 
Yes, it's different at my tests.
List is not filtered for both custom post types/tax:

- rel_non_translateable (OK)
- rel_nontrans_tax (OK)
- rel_page (not filtered)
- rel_testtax (not filtered)

Can you point me to place in code where I can test?

I'm working on different branch, so could be due to local changes.
https://github.com/pods-framework/pods/compare/2.x...OnTheGoSystems:wpml-comp-1850

**Comment by JoryHogeveen** [comment]
It looks like you've already been there in your branche.
Are you checking your branche or the version in the Pods 2.x branche?

Current 2.x WPML references are in PodsAPI.php:

Line 8246 to get and filter the current language
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L8246

And SQL stuff on line 7554 and 7632
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L7554
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L7632

And some more:
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L5423
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L5475
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L5511

**Comment by srdjan-jcc** [comment]
@JoryHogeveen I tested again and works as you suggested.
Fixed in wpml-comp-1850. Closing.
Thanks!
