### ISSUE TITLE
Pods custom capability inputs aren't sanitized

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3679]
CPT's, CT's and fields all have custom capability options but these values aren't validated for use of spaces and other characters.

A capability like this is currently accepted: `test @ $123`

All capability fields should be sanitized on frontend (during typing) and in the backend.
- Only lowercase
- Remove special characters
- Spaces to underscores
- _Dashes to underscores?_
- _Do we want to allow numbers?_

Maybe use the base of `sanitize_title()`?

**Comment by sc0ttkclark** [comment]
Believe it or not, WP does not escape or sanitize any capabilities or roles names. Sure they escape them on output, but you can actually use anything that is acceptable as an array key in PHP for a role or capability name.

**Comment by sc0ttkclark** [comment]
Going to close this for now, if WP doesn't normalize, we don't need to. Would I like a standard? Sure, but not sure that's our duty to restrict.

**Comment by JoryHogeveen** [comment]
Oh ok, fair enough! Just seemed weird to me...

**Comment by sc0ttkclark** [comment]
No, it is weird! :)
