### ISSUE TITLE
Conditional tags don't work for date / time field

### ISSUE THREAD

**Issue by workvista** [pods-framework/pods#3680]
Hi,

I am using the following template : 

`
[if last_date_of_application]
    <p><strong>Last Date of Application</strong>: {@last_date_of_application}</p>
[/if]
`

last_date_of_application is date time custom field. The above template always displays empty string after  "Last Date of Application :"

How should I hide a empty date time field. 

Thanks .

**Comment by jamesgol** [comment]
I know @jimtrue, opened a new issue on this but I just tried this exact code (date field used default settings) and it worked the way you would expect.  If the field was empty it did not show and did show if a date was entered.

**Comment by robrecord** [comment]
This also happens with the time field.

`	[if course_info_time_start]<tr>
		<th>Time</th>
		<td>{@course_info_time_start} - {@course_info_time_end}</td>
	</tr>[/if]`

This displays **Time** 12:00am - 12:00am

**Comment by jimtrue** [comment]
Fixed in 2.7 #4106
