### ISSUE TITLE
Cannot access usermeta as display for a user relationship field.

### ISSUE THREAD

**Issue by aaandersen** [pods-framework/pods#3687]
I was attempting to create a user relationship, which for dev purposes we need to hook the whole user as the user relationship does. However, when the client selects one, we are trying to show them a usermeta field instead of the user itself. 

From our usermeta table:
![screen shot 2016-07-18 at 5 41 12 pm](https://cloud.githubusercontent.com/assets/5503539/16931474/20e94de6-4d0f-11e6-9bd8-0dad9a1c453a.png)

Setting the field: (updated the field AND saved the pod)
![screen shot 2016-07-18 at 5 41 46 pm](https://cloud.githubusercontent.com/assets/5503539/16931483/2b010846-4d0f-11e6-84a7-66153d74411a.png)

Results: (Default shows the display name)
![screen shot 2016-07-18 at 5 45 06 pm](https://cloud.githubusercontent.com/assets/5503539/16931522/6395c368-4d0f-11e6-88d3-72d3f67efd48.png)

In using the magic tags `{@wpc_cf_depositor_code}` , our usermeta field, the display does not change. But using something like `{@user_email}` the display changes to email correctly. 

![screen shot 2016-07-18 at 5 30 28 pm](https://cloud.githubusercontent.com/assets/5503539/16931437/05137f7e-4d0f-11e6-8d12-bb02a055ddd0.png)

I even tested `{@nickname}` in case our custom usermeta field was the issue, but even Wordpress default usermeta seems to be inaccessible. It continued to show the default display name instead.

Thanks to @jimtrue for the help on Slack.

**Comment by jimtrue** [comment]
Thanks for the very detailed bug report, this will be extremely helpful!

**Comment by sc0ttkclark** [comment]
Is this field supposed to be related to the current user logged in?

**Comment by jimtrue** [comment]
Nope, it's just a meta field of user that isn't selectable as the display field in the select list.

**Comment by aaandersen** [comment]
Ha, Jim beat me to it, thanks for the attention guys :) Here is what I was typing in case the elaboration of intention on my above post helps:

No, it's supposed to be relative to the user selected in this field. This is a user relationship field in our pod, ie. this pod item is related to this user, but could be any user (in the selected roles) not necessarily who is logged in at the moment. 

However, the client (Wordpress user) is more familiar with this usermeta in reference to this content, rather than a user's display name. We are trying to display the usermeta wpc_cf_depositor_code value for the user association in the dropdown for the client's reference. 

The display field allowed me to access items in the wp_users (such as @user_email seen above) table but not wp_usermeta.

**Comment by sc0ttkclark** [comment]
I see now, yeah we don't have the ability to select anything other than what's on wp_users.* from this field right now. It's a known limitation right now on that option.

There are a couple of filters that could be used here though.

**Comment by aaandersen** [comment]
Filters I could hook into? I apologize if I missed those somewhere. We are currently appending them to the items via Ajax/JS.

Do you know which filters? I only saw the actions and filters in the documentation which don't seem to handle input display. If not, we can hunt them down, just thought I'd ask if you knew off the top of your head while here. Thanks!

**Comment by sc0ttkclark** [comment]
You could do your own query and return the values through the `pods_field_pick_object_data` filter.

https://github.com/pods-framework/pods/blob/2.x/classes/fields/pick.php#L1347

Return a `$id => $display_field` array and you'll be all set there. Sorry for the inconvenience, still more to be done to allow much more flexibility here.

**Comment by quasel** [comment]
One example as a starting point with the `pods_field_pick_data ` (note the misssing _object_ ) 

http://stackoverflow.com/questions/14259179/how-to-change-output-of-a-certain-pods-field

**Comment by brianshim** [comment]
Just as in the original post, I am not able to display some of the native fields in wp_users such as {@nickname} or {@display_name}.  Other fields such as {@user_email} do work.  I'm not talking about custom fields here, just some of the WP native fields. Anyone find an explanation or workaround for this?
