### ISSUE TITLE
Should 'orderby' option override all default 'ORDER BY's?

### ISSUE THREAD

**Issue by ajaykurien** [pods-framework/pods#3688]
Hi

Consider this pod:

``` php
$pod = pods('plb_links', array(
                            'where' => "`t`.`ID` IN (42, 73)",
                            'limit' => '-1'
                         )
       );
```

`var_dump($pod->sql)` produces:

``` sql
SELECT

DISTINCT
`t`.*
FROM `wp_posts` AS `t`

WHERE ( ( `t`.`ID` IN (42, 73) ) AND ( `t`.`post_type` = "plb_links" ) AND ( `t`.`post_status` IN ( "publish" ) ) )


ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
```

When I add an `orderby` key to the array:

``` php
$pod = pods('plb_links', array(
                            'where' => "`t`.`ID` IN (42, 73)",
                            'limit' => '-1',
                            'orderby' => "FIELD(`t`.`ID`, 42, 73)"
                         )
       );
```

``` sql
SELECT

DISTINCT
`t`.*
FROM `wp_posts` AS `t`

WHERE ( ( `t`.`ID` IN (42, 73) ) AND ( `t`.`post_type` = "plb_links" ) AND ( `t`.`post_status` IN ( "publish" ) ) )


ORDER BY FIELD(`t`.`ID`, 42, 73), `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
```

A couple of questions:
1. Should the `orderby` option fully override the default `ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date` and return just `ORDER BY FIELD(`t`.`ID`, 42, 73)` ?
2. I'm using `FIELD(`t`.`ID`, 42, 73)` to retrieve posts in a specific order — is there a more efficient alternative to `FIELD()`?

This is a superb project, thank you for your efforts!

**Comment by sc0ttkclark** [comment]
I'm open to the idea of an override as opposed to prepending what was there. As long as we document that and warn people that if their order is not unique between two posts then there is no further default ordering that will kick in. Perhaps we could even add an `orderby_prepend` option which would be off by default, but they could enable it to re-enable that functionality should they need it in the future.
