### ISSUE TITLE
jQuery .live is deprecated

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3699]
https://github.com/pods-framework/pods/blob/8262a6f/ui/js/jquery.pods.js#L1628

**Comment by pglewis** [comment]
Replace with `.on`

**Comment by JoryHogeveen** [comment]
Why 2.7?

**Comment by pglewis** [comment]
I will probably need to make at least a few changes in jquery.pods and there is no emergency to push it into 2.x sooner (and then merged back out to the 2.7 branches).

**Comment by JoryHogeveen** [comment]
Okidoki!

**Comment by pglewis** [comment]
This was done in #3771
