### ISSUE TITLE
Plugin conflict with The Events Calendar Pro

### ISSUE THREAD

**Issue by texomacog** [pods-framework/pods#3700]
I’ve used Pods and The Events Calendar (theeventscalendar.com) plugins on my wordpress site for several years now. However, I’ve uncovered a plugin conflict after a recent update.

When creating events, the recurring event pattern options are not available when Pods is activated on the site. Unfortunately, this is an issue since I’ve deeply integrated both plugins’ functionality.

When Pods is activated, there is a console error on the post page:

```
Uncaught Error: Parse error on line 53:
...tribe_checked_if_is 'yes' custom.day.[sa
-----------------------^
Expecting 'CLOSE', 'STRING', 'INTEGER', 'BOOLEAN', 'ID', 'SEP', got 'undefined'
```

This code is referring to the following file:
`handlebars.js?ver=1.0.0.beta.6:194`

When Pods is deactivated, there are no console errors and functionality for the CPT is restored.

The `<script>` used for the recurring event functionality with ECP is:
[ECP Recurring Event.txt](https://github.com/pods-framework/pods/files/390844/ECP.Recurring.Event.txt)

Below is some relevant system info for my install:

```
http://www.texoma.cog.tx.us
SITE URL
http://www.texoma.cog.tx.us
WORDPRESS VERSION
4.3.5
PHP VERSION
5.4.45
PLUGINS
Gravity Forms version 2.0.3 by rocketgenius(http://www.rocketgenius.com)
Document Gallery version 4.2.3 by Dan Rossiter(http://danrossiter.org/)
The Events Calendar PRO version 4.2.2.1 by Modern Tribe, Inc.(http://m.tri.be/20)
Pods - Custom Content Types and Fields version 2.6.6 by Pods Framework Team(http://pods.io/about/)
The Events Calendar version 4.2.2 by Modern Tribe, Inc.(http://m.tri.be/1x)
WooCommerce version 2.5.5 by WooThemes(http://woothemes.com)
WP Super Cache version 1.4.8 by Automattic(https://automattic.com/)

WORDPRESS TIMEZONE
-
SERVER TIMEZONE
UTC
COMMON LIBRARY DIR
[...]/texoma.cog.tx.us/wp-content/plugins/the-events-calendar/common/src/Tribe
COMMON LIBRARY VERSION 4.2.1.1
```

I will notify the ECP staff and provide them with a backlink to this bug report. Please, if I can provide additional information don't hesitate to reach out to me.

**Comment by texomacog** [comment]
I've obviously screwed this up by posting html - thought I had included it in a code wrap so I will try to reconstruct my message.

**Comment by jimtrue** [comment]
If you hit the back tick three times, it should wrap your code properly.

**Comment by texomacog** [comment]
@jimtrue In troubleshooting a little bit more closely, I notice that this conflict only occurs when adding a file upload field to the tribe_events Post Type with a Pod. Other fields do not cause this problem. 

I tested this in a local environment on a fresh install with the most current versions of WP, Pods, and The Events Calendar Pro.

**Comment by texomacog** [comment]
@jimtrue @sc0ttkclark This specific conflict is resulting from your plugin using an outdated version of handlebars.js

I tested this out by commenting out line 292 of `classes/PodsInit.php` where handlebars.js is registered and creating a new Event with ECP. ECP also uses handlebars.js, but they use version 3.0.3 - I presume that your version is getting enqueued instead of ECP's.

Will leaving that line commented out be detrimental to the performance of the plugin? Is this something you guys would push out a fix for or do you have a specific reason for utilizing an older version of the script? I appreciate your time!

**Comment by sc0ttkclark** [comment]
We're actually moving away from Handlebars soon, and commenting that line out shouldn't cause any problems but you still might want to test to confirm that. We'll still look into a proper solution here.

**Comment by pdclark** [comment]
Hey Scott! 😄 

I encountered this issue as well. In my case, conflicts were with both `handlebars` and `select2`.

I was able to resolve the conflict without editing the Pods plugin using the following PHP function (in a plugin or theme):

```php
/**
 * Disable enqueued Pods select2 and handlebars scripts
 * on The Events Calendar admin edit screens.
 *
 * @see https://github.com/pods-framework/pods/issues/3700
 */
add_action( 'admin_footer', function(){

	if ( 'tribe_events' == get_current_screen()->post_type ) {

		wp_dequeue_style( 'pods-select2'  );
		wp_dequeue_script( 'pods-select2' );
		wp_dequeue_script( 'pods-handlebars' );	

	}

});
```

👌 ✌️ 👋

**Comment by edsvcs** [comment]
This issue is 3 years old but I am about to use Pods with The Events Calendar Pro for the first time so I'm wondering if it's still an issue and is this code still needed?

**Comment by JoryHogeveen** [comment]
Indeed, I don't think this is an issue anymore. Closing now!
If it is this an issue we can re-open or create a new ticket.
