### ISSUE TITLE
Grunt - Karma linking

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3703]
https://github.com/karma-runner/grunt-karma

**Comment by Ramoonus** [comment]
realted #2948

**Comment by pglewis** [comment]
JS tests are already running on the 2.7 branch with mocha... karma hasn't been discussed to this point.

**Comment by pglewis** [comment]
Also, I'm personally looking to set a moratorium on further grunt runners (as soon as I can settle on what we should replace it with)

**Comment by Ramoonus** [comment]
if grunt is phased out, im closing this
