### ISSUE TITLE
Feature: Ability to "disable" a Pod/Field/FieldGroup but keep it's settings.

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3705]
I know that Types has something like this. Could be handy in some cases.
- [ ] Disable a whole pod
- [ ] Disable a field from a pod (or in the future release, the field group
- [ ] Future: Disable a field group

**Comment by JoryHogeveen** [comment]
Now that I think of it.

- Pods can be set to hidden (Disable admin UI) or private (disable "public" in Advanced options) so I think this would be overkill
- Fields can also set to be hidden in the "Advanced" tabs.
- I'd think Field Groups can also set to be hidden when they are available in the future release.

I'm closing this issue unless anyone else has an other idea of a "disable" functionality.

**Comment by quasel** [comment]
> I'm closing this issue unless anyone else has an other idea of a "disable" functionality.
@JoryHogeveen did it for you ;) 😈
