### ISSUE TITLE
Value of mulitlingual custom taxonomy not being saved

### ISSUE THREAD

**Issue by lemoinet** [pods-framework/pods#3728]
I've created some custom multilingual taxonomies and attached them through relationships to my custom post types.

I've currentle these issues:
- When I save a newly created item of a custom post type, the values of the multilingual dropdown fields aren't saved.
- When switching from all languages to a single language, the multilingual dropdown fields are empty. The options dissapear
- When editing an item of a custom post type, the multilingual dropdown fields are also empty.

And it only happens with the mulitlingual custom taxonomies, the other custom taxonomies appear as it should.

I'm using Pods 2.6.7 & Polylang 2.0.3

**Comment by JoryHogeveen** [comment]
@lemoinet 
I'll try to reproduce this a.s.a.p and let you know!

**Comment by JoryHogeveen** [comment]
@lemoinet 
Getting the same problem here aswell.

@sc0ttkclark There seems to be an issue with the SQL for term-languages in `get_table_info`. I've asked for some info on this at Polylang.

**Comment by JoryHogeveen** [comment]
Related #1801

**Comment by JoryHogeveen** [comment]
@lemoinet 
If you are able, can you test the PR #3754 and verify if this is working in your installation?

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
I didn't put compat for very old versions of Polylang (lower than 1.2) because these versions aren't used anymore and are older than 3 years. (https://wordpress.org/plugins/polylang/stats/)

**Comment by lemoinet** [comment]
it's working

**Comment by JoryHogeveen** [comment]
Ok great, thanks for testing!
