### ISSUE TITLE
Fix plupload file field listings

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3731]
It seems that the handlebars template has a hidden class which may not get removed for existing items if it uses `!important`. For new uploads the slide down does not override the hidden class as well if it uses `!important`.

Needs a compatibility fix to use `hide()`, remove `hidden`, and then slideDown.

**Comment by pglewis** [comment]
64b18c breaks file upload with a JavaScript error, note in the commit.

**Comment by pglewis** [comment]
Fixed via hulk smash 30dffaa
