### ISSUE TITLE
ACT Field-Type Relationship (Multiple Select) shows ID in output

### ISSUE THREAD

**Issue by arkonisus** [pods-framework/pods#3733]
Please create an ACT pod where you set the "Title Field" to "ID" (Advanced Options) 
![pod_settings](https://cloud.githubusercontent.com/assets/7242966/17836743/67b745d6-679d-11e6-9b94-ced357fab97d.png)

Then create another pod with a relationship-field set to "Multiple Select" and the "Display"-Option to "{@name}"
![field_settings](https://cloud.githubusercontent.com/assets/7242966/17836756/f817ceca-679d-11e6-8829-69ca66ae533f.png)

Now please try to get the values as described in your tutorial:
http://pods.io/tutorials/get-values-from-a-custom-relationship-field/

The output will contain only the ID's of the fields.
This behaviour is also the same in the CSV-Export of the pod. 

If you set the relationship to "Single Select" or if you don't set the Pod-Title to "ID" it works well!

**Comment by quasel** [comment]
Hi is this still an issue? I know it's been a log time but :D
