### ISSUE TITLE
Text label with problem editing

### ISSUE THREAD

**Issue by saulolago** [pods-framework/pods#3735]
At some time I have noticed this problem. When we try to edit the Pods of the label text does not work. See the picture: http://www.awesomescreenshot.com/image/1503105/c5b49fd945226b27d22a4e5c29943628

**Comment by JoryHogeveen** [comment]
@saulolago 
That is strange, just tested this and it works like expected.
Have you tries clearing you cache?

**Comment by saulolago** [comment]
Yes, I cleared the cache but still does not work @JoryHogeveen

**Comment by JoryHogeveen** [comment]
Can you try two things?

- Is the same problem happening on the other custom post types?
- If you disable the admin modifications, does it work then?

**Comment by saulolago** [comment]
- It is going on with any type pods created
- Deactivated and activated again but not resolved

**Important**: I am using Advanced Content Type

**Comment by JoryHogeveen** [comment]
@saulolago 
Ah, that was it. Same problem here. Will dive into this a.s.a.p.

**Comment by JoryHogeveen** [comment]
Fixed in #3737
