### ISSUE TITLE
Add an action to media.php

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#3751]
Hi Pods team

I would like to add an action to the ui/fields/media.php on line 282 so I can add some commands to the media uploader.
Code:
<?php do_action( 'pods_media', 'pods_media_' . esc_js( pods_js_name( $attributes[ 'id' ] ) ), $attributes, $options ); ?>

Thanks

**Comment by jimtrue** [comment]
Go ahead and submit PR against 2.x branch into your own branch "feature/3751" following our contribution guidelines contributing.md

**Comment by sc0ttkclark** [comment]
In Pods 2.7 and above, we're looking at redoing a bunch of this JS, so it won't even be running within PHP or that media.php file, it'll be running in it's own encapsulated JS file with it's own logic separation from the inputs. What exactly are you trying to do? Maybe we can think of an alternative solution that won't change when 2.7 comes out.

**Comment by sc0ttkclark** [comment]
PR: #3752

**Comment by coding-panda** [comment]
For some files, I want to upload them to a different folder or a sub-folder rather than the default upload folder. Adding an action there will allow me to alter the upload path. Thanks.

**Comment by sc0ttkclark** [comment]
You're actually going to want to do this through PHP directly, the action you're trying to add here happens only on output of the file uploader script.

Maybe try the `add_attachment` hook in WordPress?

**Comment by coding-panda** [comment]
That'll have a global effect. I just need it for some special fields.

2016年9月19日 13:35，"Scott Kingsley Clark" <notifications@github.com>写道：

**Comment by sc0ttkclark** [comment]
My solution to this was to run a post save hook, like on save_post to check the file field path and if it's not moved then move it and update the attachment's path.

**Comment by sc0ttkclark** [comment]
If you use the Pods file field option for plupload then you can hook into some of the hooks in classes/fields/file.php at the bottom.
