### ISSUE TITLE
Possible performance issues with PODs

### ISSUE THREAD

**Issue by wacochili** [pods-framework/pods#3757]
We're getting slow logs on a site running PODs version 2.6.7.

I'm attaching a slew of server logs this week for more information.

The types of these PODs are all Custom Post Type
Storage types for all is Table
Number of fields range from 5 on one, to 24 on another (most fall somewhere in between)
Many fields are plain text, some are boolean
Here is sample code from a single template:

```
<div class="col-md-4 col-sm-6">
  <a href="{@guid}"><img src="{@post_thumbnail_url.custom-size}" class="img-responsive"></a>
  <p><a href="{@guid}">{@post_title}</a></p>
</div>
```

[Archive.zip](https://github.com/pods-framework/pods/files/450176/Archive.zip)

**Comment by quasel** [comment]
Hi hard to tell without more information - poissble related to #1911 / #3768 

we would need the full code to maybe give some advice

**Comment by quasel** [comment]
and btw @guid isn't really a good choice better go with @permalink

**Comment by wacochili** [comment]
@quasel we're taking your advice on replacing @guid with @permalink.

I'm also attaching our code for single.php and a sub-category page in which multiple, related PODs are displayed on a page in a grid-like structure.

Hopefully to your point about needing full code, this will help or at least give you insight.
[Archive.zip](https://github.com/pods-framework/pods/files/457016/Archive.zip)

**Comment by quasel** [comment]
At a quick glance i dont see something wich is obviously slow ... but did not dig deeper into it - besides your code could use a bit cleanup/styling ;) but that's a different matter :P

A plugin that can help is https://de.wordpress.org/plugins/query-monitor/ - it's one of must have things for development ^^

**Comment by quasel** [comment]
Closing this - feel free to comment if or how you solved it ;)
