### ISSUE TITLE
Default REST Base for post type "post" to "posts" 

### ISSUE THREAD

**Issue by pablopaul** [pods-framework/pods#3759]
When adding a new pod to extend the default post type post and enabling the REST API the default suggested "REST Base" is `post`. This replaces the default posts endpoint of the json-api which is available as `/wp-json/wp/v2/posts` and now results in a 404 response, since the new endpoint with Pods enabled is `/wp-json/wp/v2/post`. This can be confusing.

That is why I suggest to default the "REST Base" for the post type "post" to "posts".

I guess it should be improved here: https://github.com/pods-framework/pods/blob/fe8da9d61b576ed8fd8ff9f345e743fec42140f3/classes/PodsRESTHandlers.php#L285

**Comment by sc0ttkclark** [comment]
Thanks for the heads up, I've rectified this in the latest development release of Pods 2.6.8 at http://pods.io/latest/

**Comment by sc0ttkclark** [comment]
Fixed this for Taxonomies too now
