### ISSUE TITLE
cant use selection limit with autocomplete

### ISSUE THREAD

**Issue by saltnpixels** [pods-framework/pods#3761]
I wanted to allow up to three relationships in a relationship field, but with autocomplete it doest work.
After saving a selection limit, the selection limit field reverts to 0.

**Comment by jimtrue** [comment]
@saltnpixels I just tested this on my local version of Pods; I was able to set the AutoComplete field with a selection limit of 0 and it remained in the field:

![screenshot 2016-09-02 12 40 47](https://cloud.githubusercontent.com/assets/3052875/18211292/f47070bc-710a-11e6-80e6-c4affd1d2a77.png)

I was also able to have the relationship field recognize the limit of 3 items:
![screenshot 2016-09-02 12 41 17](https://cloud.githubusercontent.com/assets/3052875/18211307/055b0036-710b-11e6-9a8b-be302047fef6.png)


Can you check to see if maybe you have another plugin interfering/interacting with Select2 maybe? Do the standard troubleshooting of turning off other plugins and switching to the base theme and see if you still have an issue.

**Comment by saltnpixels** [comment]
i deleted field and made a new one. now it works…
strange. probably an issue with me…
