### ISSUE TITLE
Pods Poor Poor Performence

### ISSUE THREAD

**Issue by hanabadler** [pods-framework/pods#3764]
Hello Pods Team.This is my first issue here
pods is a great plugin, and i am using it over more than 20 websites.
however, i would like to address the following problem we saw in one of the project which shows pods poor performance and i think it should be resolved ASAP

here is the scenario:
3 pods declarations using custom table storage: 

1.schoolplan - short list of different plans . the structure is id,name and description
2.school -which has fields like name, number of students, and a relation field to schoolplan
3.class - which has some meta data fields-name,location.... and a relation to school.

Now, we have for example 2 schools and 20000 classes -10000 for each school 
we wanted to display a table with class name, grade and its relevant school
first we did the following

$args = ('where' => 'school.id = 1');
$classes = pods('class',$args);
while($classes->fetch()){
   echo $classes->display('name');
   echo $classes->display('school.name');
   
}

this made 10000 query's which made the database break!
the fetch makes a new query !
(assume we have 1000 users which looks at the table - this made 10,000,000 querys in 1 minute- mysql cant handle this)

So, we tryed a second approach-passing the param we wanted in the args
$args = ('select'=>''t.id,school.name,'where' => 'school.id = 1');
....

Again, this only made the change in the query but the fetch is queryiing the db - the 10000 querys remains

our third attempt was taking the generated query pods makes( very long query which is using the pods rel table and doing some left joins)- we used "Query Monitor' plugin to look at the query's
and use wpdb -
this made one query and the loop was going over the result set !!
so, we started converting all pods calls to wpdb using the generated sqls and performance improved drastically !
my suggestion to look at it-Pods is really good tool for creating the model but it appears the its performance is not good at all , when you use big tables .

thanks
Hana.

**Comment by quasel** [comment]
Thank you for your report - related to #1911 

It "should" work this way:

```
 $args = ('select'=>''t.id,school.name as xxx,'where' => 'school.id = 1');
```
and
```
echo $classes->display('xxx');
```

The point is that we can't query every relationship beforehand so it's done on the fly if not selected as alias beforhand.

**Comment by pglewis** [comment]
@quasel hit on the best optimization for this case.  

If Pods were to select all relationship data during a `find()` it could be an incredibly large dataset, depending upon how complex the relationships are as well as tricky puzzles involving with circular relationships.  The vast majority of use cases only need to pull a handful of records at a time so this doesn't normally present a bottleneck.  

In your case, however, you are going to generate an extra query every pass through your `while()` loop to go pick up the school name.  The solution above (detailed in #1911) is to tell Pods what fields to retrieve during the find so that all the data you need is retrieved in the initial query.  Cutting out that many round-trips to the database should perform quite well.

**Comment by pglewis** [comment]
Also, it looks like you were close to this solution, only missing the aliased field name in the `SELECT` and `display()`

**Comment by quasel** [comment]
I'm goint to close this issue - if you need further help don' hesitate to ask again!

**Comment by jimtrue** [comment]
Sorry this was mistakenly closed. We'd like to get your responses to our suggestions @hanabadler

**Comment by hanabadler** [comment]
Hi.yes,i tryed and indeed performence improved.thank you.i would suggest
some doc on main site...
Thanks,hana

בתאריך 4 בספט׳ 2016 09:34,‏ "Bernhard" <notifications@github.com> כתב:

**Comment by pglewis** [comment]
This workaround gets the job done but there should be a less "fiddly" way to do it.  Something like a "prefetch" parameter with an array of related field names so you don't have to setup aliases.  I think formal documentation should probably wait until that better solution is implemented.  

I'll assume you're straightened out for now but feel free to re-open if there are problems.
