### ISSUE TITLE
JS for field types not working in Modal popup because of AJAX loading

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3766]
https://github.com/pods-framework/pods/issues/3765 triggerd some extra testing and showed that field types based on a script (eg. WYSIWYG, Colorpicker, Date/Time, Image, etc.) are not working in WP Modal view (mostly used for attachments).
Most of them are just outputted as plain text inputs.

wp_enqueue_script is ofcourse not working when using AJAX but maybe we can make a workaround?
@pglewis Maybe the new MV fields structure can help with this??

**Comment by JoryHogeveen** [comment]
And while we're at it.
Maybe also add compat for the `show_in_edit` and `show_in_modal` for fields of an attachment post type.

**Comment by pglewis** [comment]
Closing this in favor of #4798.  

This issue is a puzzle involving how WordPress fields in the media library in grid mode.
