### ISSUE TITLE
jquery.pods.js?ver=2.6.7:1628 Uncaught TypeError: $(...).live is not a function

### ISSUE THREAD

**Issue by mikeschinkel** [pods-framework/pods#3771]
Running into this error in a site that I just installed Pods into when `'jquery-migrate'` is dequeued.

Not being a heavy JS developer, I defer to StackExchange which says [`.live()` is deprecated](http://stackoverflow.com/questions/14354040/jquery-1-9-live-is-not-a-function).

Changing it from:

```
$( '.pods-toggled .handlediv, .pods-toggled h3' ).live( 'click', function () {
    $( this ).parent().find( '.inside' ).slideToggle();
    return false;
} );
```

To this fixes the problem _(but may not be optimized since it uses `'body'`):_

```
$( 'body' ).on( 'click', '.pods-toggled .handlediv, .pods-toggled h3', function () {
    $( this ).parent().find( '.inside' ).slideToggle();
    return false;
} );
```

**Comment by pglewis** [comment]
Duplicate: #3699.  

This will be done as part of 2.7.

**Comment by Ramoonus** [comment]
why dequeue migrate?

**Comment by mikeschinkel** [comment]
Someone else on my team did it to get rid of the JQMIGRATE error in the browser console.

**Comment by pglewis** [comment]
That's the same notice that brought it to my attention :D.  

This might need to be bumped up to 2.x after all if it's starting to cause problems in the wild.

**Comment by Ramoonus** [comment]
I agree
especially since jQuery  3.x will be included in WP one day (soon)

**Comment by GaryJones** [comment]
Looks to have been completed in fa428bc20c3e9603d5249e96bf2a8e0baed71a85.
