### ISSUE TITLE
Relationship are showing all and looped by count of selected item(s). 

### ISSUE THREAD

**Issue by Tobimen** [pods-framework/pods#3782]
I have setup two Advanced Content Type with a reference to the other.  (Same when I setup a custom post type + an advanced content type. 
When I select at least one it shows every time also the non selected: 

1 select -> shows all 
2 select -> shows all in a loop 2 times
3 select -> shows all in a loop 3 times
…

available options are: Mo, Di, Mi, Do 
and I have selected one: 
Fronted: 
`Mo
Di
Mi
Do`

select two of them: 
`Mo
Di
Mi
Do
Mo
Di
Mi
Do`

etc. 

Pods Template: 
`<ul>
[each times]
        <li>{@name}: {@weekday}</li>
[/each]
</ul>
`

Pods Export:
`{"meta":{"version":"2.6.7","build":1473756967},"pods":{"148":{"id":148,"name":"mannschaft","label":"Mannschaften","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":149,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_repeatable":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255"},"created":{"id":150,"name":"created","label":"Date Created","description":"","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","datetime_format":"ymd_slash","datetime_time_type":"12","datetime_time_format":"h_mm_ss_A","required":"0","unique":"0","datetime_repeatable":"0","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0"},"modified":{"id":151,"name":"modified","label":"Date Modified","description":"","help":"","class":"","type":"datetime","weight":2,"pick_object":"","pick_val":"","sister_id":"","datetime_format":"ymd_slash","datetime_time_type":"12","datetime_time_format":"h_mm_ss_A","required":"0","unique":"0","datetime_repeatable":"0","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0"},"author":{"id":152,"name":"author","label":"Author","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"user","pick_val":"","sister_id":"","pick_format_type":"single","pick_format_single":"autocomplete","default_value":"{@user.ID}","required":"0","unique":"0","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_post_status":"publish","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_user_role":"","pick_where":"","pick_orderby":"","pick_groupby":""},"permalink":{"id":153,"name":"permalink","label":"Permalink","description":"Leave blank to auto-generate from Name","help":"","class":"","type":"slug","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0"},"trainer":{"id":154,"name":"trainer","label":"Trainer","description":"","help":"","class":"","type":"pick","weight":5,"pick_object":"pod","pick_val":"trainer","sister_id":"","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"co-trainer":{"id":155,"name":"co-trainer","label":"Co-Trainer","description":"","help":"","class":"","type":"pick","weight":6,"pick_object":"pod","pick_val":"trainer","sister_id":"","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"mannschaftsleiter":{"id":156,"name":"mannschaftsleiter","label":"Mannschaftsleiter","description":"","help":"","class":"","type":"text","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"trainingszeiten":{"id":455,"name":"trainingszeiten","label":"Trainingszeit(en)","description":"","help":"","class":"","type":"pick","weight":8,"pick_object":"pod","pick_val":"time","sister_id":"","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"trainingsort":{"id":158,"name":"trainingsort","label":"Trainingsort","description":"","help":"","class":"","type":"text","weight":9,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"liga":{"id":163,"name":"liga","label":"Liga","description":"","help":"","class":"","type":"text","weight":10,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"saison":{"id":164,"name":"saison","label":"Saison","description":"","help":"","class":"","type":"pick","weight":11,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"2015\/2016\n2016\/2017","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"gamelink":{"id":165,"name":"gamelink","label":"Spiele Link","description":"","help":"","class":"","type":"website","weight":12,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","website_format":"force-www","website_clickable":"1","website_new_window":"1","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"website_repeatable":"0"},"table":{"id":166,"name":"table","label":"Tabelle Link","description":"","help":"","class":"","type":"website","weight":13,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","website_format":"force-www","website_clickable":"1","website_new_window":"1","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"website_repeatable":"0"},"mannschaftsbild":{"id":168,"name":"mannschaftsbild","label":"Mannschaftsbild","description":"","help":"","class":"","type":"file","weight":14,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","unique":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"file_allowed_extensions":""},"hintere_reihe_von_links":{"id":169,"name":"hintere_reihe_von_links","label":"hintere Reihe von links","description":"","help":"","class":"","type":"text","weight":15,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"mittlere_reihe_von_links":{"id":170,"name":"mittlere_reihe_von_links","label":"mittlere Reihe von links","description":"","help":"","class":"","type":"text","weight":16,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"vordere_reihe_von_links":{"id":171,"name":"vordere_reihe_von_links","label":"vordere Reihe von links:","description":"","help":"","class":"","type":"text","weight":17,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"es_fehlt":{"id":172,"name":"es_fehlt","label":"es fehlt","description":"","help":"","class":"","type":"text","weight":18,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0"},"menu_order":{"id":173,"name":"menu_order","label":"menu_order","description":"","help":"","class":"","type":"number","weight":19,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"1","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0"},"description":{"id":167,"name":"description","label":"Beschreibung","description":"","help":"","class":"","type":"wysiwyg","weight":20,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""}},"show_in_menu":"1","label_singular":"Mannschaft","pod_index":"name","hierarchical":"0","ui_style":"post_type","menu_position":"0","ui_actions_enabled":["add","edit","duplicate","delete","reorder"],"ui_reorder_field":"menu_order","ui_fields_manage":{"0":"name","2":"modified","5":"trainer","6":"co-trainer"},"ui_filters":{"0":"name","5":"trainer","6":"co-trainer"}}}}`

**Comment by quasel** [comment]
I think this stuff has been fixed at some point! If there is still an issue pleas open a new issue.
Sorry for the late reply, feel free to comment if you still have questions!
