### ISSUE TITLE
using add_to and outputting the new content

### ISSUE THREAD

**Issue by saltnpixels** [pods-framework/pods#3784]
I was trying to get a custom relationship field, check it, and then if needed, add to it and then get it again for output:

I simplified what i was doing…
basically.

```
  $member_found = false;
   $pod = pods('pod_name', $id);
  //get all assigned_members
   $assigned_members = $pod->field('assigned_members.ID');

  foreach($assigned_members as $member){
    if($member == get_the_ID() ){
       $member_found  = true;
       break;
    }
 }

if(! $member_found ){
  $pod->add_to('assigned_members', get_the_ID() );
  $assigned_members = $pod->field('assigned_members.ID');
}
```

if I try to output the $assigned members it will not include the new one until I refresh the page.
Why?

**Comment by jimtrue** [comment]
@saltnpixels we need to see the 'rest' of your code so we can see why it's not displaying.

**Comment by saltnpixels** [comment]
just do a print_r($assigned_members).
ok fine
```
if ( ! empty( $assigned_members ) ) {
        foreach($assigned_members as $member){
       echo $member;
  }
}
```
:)

**Comment by jimtrue** [comment]
Why are you using `$pod->field('assigned_members.ID')` instead of just $pod->field('assigned_members')`? The latter would give you the associative array of the relationship, I'm not sure what you're getting in the former, just an simple array of ID's?

**Comment by saltnpixels** [comment]
I find I usually just need ID's when getting relationships. Then I can output stuff with them... get_the_title($member)…

It seems easier…

**Comment by sc0ttkclark** [comment]
That's right @saltnpixels, no problem there :)

I verified this issue with him via Slack today @jimtrue and it looks like add_to() isn't clearing cache or a stored value some place so that when ->field() runs it's not updated. This may be because add_to() adds a value to the relationship and calls ->field() in order to add it, so it caches it then probably and then doesn't get properly (re)set after saving.
