### ISSUE TITLE
Problems with multiple files in web https

### ISSUE THREAD

**Issue by saulolago** [pods-framework/pods#3787]
Would you help me? I installed a certificate on my site and own an item of multiple images, but the images are coming at http just and necessary that they come as https.

In simple files are coming correctly, the only problem is the multiplo files.

**Comment by JoryHogeveen** [comment]
Hi @saulolago,
How are you getting this data? Are you using shortcodes or PHP functions?
Also, I assume the URL's are set correctly? (under settings >> General)

**Comment by Ramoonus** [comment]
can we exclude serverside HTTPS problems or browser problems?

**Comment by Ramoonus** [comment]
caching maybe?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
