### ISSUE TITLE
wordpress 4.5.3 and pods 2.6.5.2 - boolean field value, default value is array(0) instead of empty string '' or 0 or false

### ISSUE THREAD

**Issue by Jossnaz** [pods-framework/pods#3791]
wordpress 4.5.3 and pods 2.6.5.2 - boolean field value, default value is array(0) instead of empty string '' or 0 or false

that is, when creating a new pods object the default value is an empty array instead of '' or 0

the code I used to check the value:

```
$t = get_post_meta(338372, 'jcr_is_disabled', true);
var_dump($t); //echos array(0)
```

the code I used to create the fields:

```
  $post_information = array(
    'post_title' => 'fooo',
    'post_content' => 'bar',
    'post_type' => 'project',
    'post_author' => $current_user->ID,
    'post_status' => 'publish'
  );
   $new_id = wp_insert_post( $post_information);
```

the project type is a migrated type. That is, it was half a year ago created by a dev using native functions, and i migrated it to pods with your toolset.

The way it shows now in the pods admin is this:

> Project project   Post Type (extended)    Meta    22

the behaviour used to be different, we only have those problems as of a couple days, maybe weeks

**Comment by quasel** [comment]
not sure I can follow ;) bu I think that has changed! 

Sorry for the late reply, feel free to comment if you still have questions!
