### ISSUE TITLE
Issue with \r\n , converted to rn while saving 

### ISSUE THREAD

**Issue by baljindersingh88** [pods-framework/pods#3795]
Hi 
I have a text paragraph field.It contains data in json format.I have an issue with \r\n.
When i use $pod->add() function \r\n are converted to rn.
In the admin side when i edit some pod item, and add \r\n manually, it is also converted to rn.
Can you please help to sort out this issue.

Thanks
Baljinder Singh

**Comment by jimtrue** [comment]
Additional commentary from the WordPress.org original issue (https://wordpress.org/support/topic/new-line-issue/)

I am able to maintain the \n in the textarea with this code(added from front end)

```
if(isset($_POST[‘Submit’])){
$first_name = ($_POST[‘test_name’]);

// Get the book pod object
$pod = pods( ‘test’ );
$preg_replace = trim( preg_replace( ‘/(\r\n)|\n|\r/’, ‘\\n’, $first_name ) );
$json_array = json_encode(array(‘name’=>’gagan’,’age’=>20,’questions’=>$preg_replace));

$as = addslashes($json_array);
// To add a new item, let’s set the data first
$data = array(
‘name’ => ‘test’,
‘author’ => 2, // User ID for relationship field
‘post_content’ => ‘Awesome book, read worthy!’,
‘test_name’ => $as
);

// Add the new item now and get the new ID addslashes($r, “\v\t\n\r\f\”\\/”)
$new_book_id = $pod->add( $data );

}
```

But it is again converted to r n(\r\n to rn) when i update the pod item in admin area.Any ideas?

**Comment by quasel** [comment]
closing in favor of #2219

**Comment by pglewis** [comment]
I believe this is directly related to #5040 and not 2219.
