### ISSUE TITLE
Extra param in filters to select WHEN to  apply them

### ISSUE THREAD

**Issue by jaumearagay** [pods-framework/pods#3805]
I'd like to make a suggestion for the **pods_api_pre_save_pod_item_{podname}** and **pods_api_pre_save_pod_item** filters, to add an extra parameter where you could select WHEN to apply them.

Now they are applied both when coming from a frontend form and when working in the admin section when editing the Pods content. That drove me nuts! As I expected them to work in the frontend but not when editing from the admin area of the site.

I've managed to differentiate where the save action takes place because some parameters are different, so using this if statement I apply the filter when I want to, but I think it would be a great addition to have a $section or $area parameter with "both", "front" and "admin" as options to select when to apply the filter.

This is the if statement I use in the filter function actually, and it works to me:
```
if ( ! ( ( $pieces[ 'params' ]->location == '' ) && ( $pieces[ 'params' ]->from == "save" ) ) ){ 
        /* Beware of the ! initial symbol. ONLY APPLIED WHEN COMING FROM A FRONTEND FORM, AS WHEN YOU COME FROM THE ADMIN PAGE: from = "save" AND location = '' */
```

**Comment by JoryHogeveen** [comment]
Hi @jaumearagay 
Not sure it this should be a hook param. I don't believe WP has something similar aswell. I personally think that the plugin/theme that uses this hook should determine when to use it.

I assume your example code is within the hooked function?
Something else you can do is as simple as this:
```php
if ( is_admin() ) {
    // No hook called
} else {
    add_action( /*etc*/ );
}
```

**Comment by jaumearagay** [comment]
Ok. Then I'd make it clear in the documentation that it triggers always and add your if statement in the examples. 
If I'm working in the admin I consider I'm working on the "raw" data. I considered --erroneously -- that they applied only to data coming from the frontend.

**Comment by sc0ttkclark** [comment]
You might try checking the `location` parameter too. `is_admin()` will probably always return true since `save_pod_item` is called from forms via the `admin-ajax.php` file which is in `/wp-admin/`.

**Comment by JoryHogeveen** [comment]
This would fix that aswell right?
```php
if ( is_admin() && ( ! defined( 'DOING_AJAX' ) || ! DOING_AJAX ) ) {
    // No hook called
} else {
    add_action( /*etc*/ );
}
```
