### ISSUE TITLE
Please could media/file fields set the post_parent

### ISSUE THREAD

**Issue by m9n** [pods-framework/pods#3808]
My specific problem leading to this request is wanting building a search facility with SearchWP, that searches all Pages in a section, and also the contents of their attached PDFs.  SearchWP can only do that by using post_parent to understand the hierarchy.  But I think Pods doesn't update the post_parent (core WP) field when a file is attached with a field.

Steps to reproduce:
- Create a post type pod
- Add a file upload field
- Create a post of this type and add a file to it
- Have a look in the database at the file's entry in the wp_posts table, and you'll see the post_parent set as 0 (where files uploaded through the Media button and embedded have main post's post_id in their post_parent).

**Comment by JoryHogeveen** [comment]
Hi @m9n 
A parent for attachments is only set when this attachment is uploaded in the post-edit page (post.php).
So, when you upload in the media library, alle files have no parent, even if you attach these afterwards, no parent is set.
From what I see here, WP core handles this the same way.

However, you can detach/attach your files from within the media library itself.
![image](https://cloud.githubusercontent.com/assets/826148/19772572/f364cb00-9c66-11e6-86c1-1bf1c3f87df1.png)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
We can add a small update check for the file fields that checks if the attachment already has a parent.
If it doesn't, we could attach the current post-edit ID as the parent.
If it already has a parent, we do nothing.

**Comment by m9n** [comment]
> A parent for attachments is only set when this attachment is uploaded in the post-edit page (post.php).

This is why I think I perceive this as an error in Pods.  WordPress core attaches a file to a post when you upload it on the post edit screen.  So when you upload a file to a Pods file field - on the same post edit screen - I don't think it's unreasonable to assume it would work in the same way.

Of course, the relationship that WordPress builds here is blunt, inflexible, and sometimes annoying.  But that's the way it works, and, I think it would make sense to me if Pods mirrored this behaviour.

**Comment by JoryHogeveen** [comment]
The behaviour you describe already works in the tests I did though.
Only if the attachment already exists Pods doesn't set it's parent since this happens while uploading. The PR fixes this though!

**Comment by m9n** [comment]
Ah, I think my tests weren't detailed enough, and that I've not fully understood WP's behaviour.  Thank you very much for your help with this, Jory.  Super appreciated.

**Comment by JoryHogeveen** [comment]
No problem!
I'll leave this issue opened untill the PR is merged.

**Comment by JoryHogeveen** [comment]
Closing this since it is merged in 2.x
