### ISSUE TITLE
PODS_LIGHT uses components

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#3811]
In PodsAdmin.php:517

``` php
if ( 'pods-components' == $page )
    PodsInit::$components->menu( $parent );
```

null has no menu()

**Comment by szepeviktor** [comment]
+1 Somehow admin_components() gets called and triggers a warning.

**Comment by JoryHogeveen** [comment]
Hi @szepeviktor 
Do you have more debug info? Maybe a backtrace?

**Comment by szepeviktor** [comment]
PODS_LIGHT is a very nice feature!
