### ISSUE TITLE
/wp-admin/images/button-grad.png is not in WP core

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#3812]
But in pods-ui-list-table.css and pods-front.css (total of 5 times) causing 404-s.
https://github.com/pods-framework/pods/blob/2.x/ui/css/pods-ui-list-table.css#L162

Please consider fixing these.

**Comment by JoryHogeveen** [comment]
Related: https://github.com/pods-framework/pods/issues/2566
