### ISSUE TITLE
Markdown_Parser has a deprecated constructor in pods/components/Markdown.php

### ISSUE THREAD

**Issue by kelfy** [pods-framework/pods#3813]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Markdown_Parser has a deprecated constructor.

Suggested to change to __construct() on line 230 at pods/components/Markdown.php

**Comment by JoryHogeveen** [comment]
Related: https://github.com/pods-framework/pods/issues/3828
PR: https://github.com/pods-framework/pods/pull/3830
