### ISSUE TITLE
Making Pods compatible with upcoming release for Admin Columns 4.0

### ISSUE THREAD

**Issue by DGStefan** [pods-framework/pods#3815]
We've changed our storage modal in our upcoming release.
We try to make our upcoming release as backward compatible as possible but we run into some conflicts with Pods that is causing some errors.

Please change the following code

public function cpac_meta_value() in PodsMeta.php
$obj->options->field_type  -> $obj->get_option( 'field_type' );
$obj->options->field  -> $obj->get_option( 'field' );

This will work in older versions of Admin Column but most important it will not break our upcoming release.

**Comment by sc0ttkclark** [comment]
Update the code, thanks for being an awesome partner!
