### ISSUE TITLE
Too Many Backslashes "\'s" Added When Using Quotes in Search Field

### ISSUE THREAD

**Issue by scottjeter** [pods-framework/pods#3823]
I'm having an issue with search filters in pods. In a listing of custom pods (businesses), I've added the filter to search the post_title. The search works great until you add a quote to the search field. 

For example, searching for a business with the title:
Ray's

Turns into:
Ray\\\'s

The search results return the following error. Please help.

Database Error; SQL: SELECT DISTINCT `t`.\* FROM `wp_posts` AS `t` WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "businesses" ) ) AND ( `t`.`post_title` LIKE '%Ray\\\'s%' ) ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date` LIMIT 0, 15; Response: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%' ) ORDER BY `t`.`menu_order' at line 7

**Comment by sc0ttkclark** [comment]
What are you using for your `find()` call here?

**Comment by scottjeter** [comment]
$businesses = pods( 'businesses' );

echo $businesses->filters( array(
    'fields' => array( 'title' ),
    'label' => 'Go'  
) );

$businesses->find($params);

while ( $businesses->fetch() ) {  //stuff }

**Comment by sc0ttkclark** [comment]
What was in the `$params`?

**Comment by scottjeter** [comment]
Oh, sorry.

$params = array( 
'orderby' => 'title', 
'limit' => 15 
);

Before you ask, I'm running:
WordPress 4.6.1
Pods 2.6.7
PHP 5.6.25
MySQL 5.6.32

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
The problem is over-escaping in `pods_sanitize_like` (data.php).

In the case of a find() method the value is already sanitized.
After that `pods_sanitize` adds backslashes for both `\` and `'`;
After that `$wpdb->esc_like` does exactly the same..

Two possible solutions I can think of:

1: Add code after escaping that removes and "wrong" data with a simple `str_replace()` loop.

2: Change the following:
```php
$output = $wpdb->esc_like( pods_sanitize( $input ) );
```
to:
```php
$output = pods_sanitize( $wpdb->esc_like( $input ) );
```
And do the same as in option 1, but within `pods_sanitize`

**Comment by JoryHogeveen** [comment]
Hi @sc0ttkclark,

Ah yes I see. You essentially do the same but `pods_unslash` handles arrays aswell.
I've kept the "unslashing" before the if/else statement though.

@scottjeter 
If you are able, please test!
https://github.com/pods-framework/pods/pull/3836

**Comment by scottjeter** [comment]
Moving the pods_unslash before the if/else statement works. This issue is resolved for me.
