### ISSUE TITLE
Loop not working

### ISSUE THREAD

**Issue by ThiloL** [pods-framework/pods#3825]
Hi,

the following template isn't working, even if I have such posts. Any ideas?

```
[if vereinsmitglied]
<table>
	<tr>
		<th>Mitgliedsnr.</th>
		<th>Name</th>
	</tr>
	[each vereinsmitglied]
	<tr>
		<td>{@membership_number}</td>
		<td>{@last_and_firstname}</td>
	</tr>
	[/each]
</table>
[/if]
```

**Comment by jimtrue** [comment]
@ThiloL Where are you calling the above template and how are you calling it? Is this from a shortcode? Is this from an Auto Template on a single detail record with related fields in `vereinsmitglied`?

**Comment by ThiloL** [comment]
Template is called from a page (no Auto Template etc.):

`[pods name="vereinsmitglied" orderby="membership_number" template="Mitglied"]`

**Comment by jimtrue** [comment]
`vereinsmitglied` is the pod name and also the name of your relationship field?

**Comment by ThiloL** [comment]
I have no relationship field. only a pod "vereinsmitglied" with some 'posts'.

**Comment by ThiloL** [comment]
I have a few custom posts (vereinsmitglied) which I want to show as table in a wordpress page.

**Comment by jimtrue** [comment]
[each][/each] is only used for looping through relationship fields and taxonomy.

Remove the [if] and [each] blocks in your template above and see if your template works for your content. Also check out this tutorial series from OS Training:
https://www.ostraining.com/class/pods/

This documentation also covers the Template Tags and their uses in Pods Templates:
http://pods.io/docs/build/template-tags-in-pods-templates/
