### ISSUE TITLE
Wrong sorting by number

### ISSUE THREAD

**Issue by ThiloL** [pods-framework/pods#3827]
Sorting by number-field in a template doesn't work correctly. Sorting is done by text representation and NOT by the real number. #

**Comment by Ramoonus** [comment]
could you tell me a bit more, what you are doing and how

environment

**Comment by ThiloL** [comment]
I have a pod with a playin number field. The corerct sort oder works only with this statement:
[pods name="vereinsmitglied" orderby="CAST(membership_number.meta_value AS SIGNED)" template="Mitglied"]

orderby="membership_number" ... doesn't do the sort correctly.

**Comment by quasel** [comment]
Delfine incorrect ;) is it just about ASC / DESC or more?
