### ISSUE TITLE
Neue Tabelle

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#3855]
Why your Pods .po file for German formal (Sie) has this line for adding new Posts ?
(Add New string)

**Neue Tabelle**

**Comment by JoryHogeveen** [comment]
Guess this is a wrong translation.

I see it was added by one TobiasBg on translate.wordpress.org. No clue why the german translation moderator accepted this translation...

**Comment by JoryHogeveen** [comment]
I'm closing this here since this is not related to Pods development.
Translations are 100% managed by WP itself and it's i18n moderators. Unless someone volunteers the be the editor for the German translations this is out of our hands.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark As the plugin author you could reject this translation on translate.wordpress.org though.

**Comment by StaggerLeee** [comment]
Not a big deal, it is not end of the world. Right thing to close it. Easy to fix it by own, and Pods types have visual fields to change strings. Just for you to be aware of it. 
Looks like it was translated by someone from Typo3 world.
