### ISSUE TITLE
pods_meta_groups - register an class method throws an warning 

### ISSUE THREAD

**Issue by staude** [pods-framework/pods#3856]
hi,

wenn i use 
`add_action( 'pods_meta_groups',  array( 'myclass', 'myfunction') , 10, 2 );`

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'myclass' not found in /app/public/wp-includes/plugin.php on line 524

Registering an function works fine.

**Comment by JoryHogeveen** [comment]
This is not an error due to Pods. Are you sure your class etc. is defined properly?

**Comment by staude** [comment]
Sorry. I can not reproduce it anymore.
i close the ticket and I report if it should occur again.
