### ISSUE TITLE
pods ui default search error

### ISSUE THREAD

**Issue by kaushikam** [pods-framework/pods#3858]
I am using pods 2.6.7. I am using pods-ui like below:

```php
function myplguin_admin_sub_page() {
    $offices = pods('office');

    $fields = $offices->fields();

    $filters_array      = array('office_name','street', 'town', 'district', 'pincode');

    $offices->ui = array (
        'item' => 'Office',
        'items' => 'Offices',
        'orderby' => 'office_name ASC',
        'fields' => array (
            'manage' => array (
                'office_name' => 'Office Name',
                'street' => 'Street',
                'town' => 'Town',
                'district' => 'District',
                'pincode' => 'Pin Code',
            ),
            'add' => $fields,
            'edit' => $fields
        ),
        'filters' => $filters_array
    );

    pods_ui($offices);
}
```
But when I am using the default search the following error appears.

`Database Error; SQL: SELECT DISTINCTt.* FROMvi_postsAStLEFT JOINvi_postmetaASoffice_nameONoffice_name.meta_key= 'office_name' ANDoffice_name.post_id=t.IDLEFT JOINvi_postmetaASstreetONstreet.meta_key= 'street' ANDstreet.post_id=t.IDLEFT JOINvi_postmetaAStownONtown.meta_key= 'town' ANDtown.post_id=t.IDLEFT JOINvi_postmetaASdistrictONdistrict.meta_key= 'district' ANDdistrict.post_id=t.IDLEFT JOINvi_postmetaASemail_idONemail_id.meta_key= 'email_id' ANDemail_id.post_id=t.IDLEFT JOINvi_postmetaASpincodeONpincode.meta_key= 'pincode' ANDpincode.post_id=t.IDWHERE ( (t.post_statusIN ( "publish" ) ) AND (t.post_type= "office" ) ) AND (office_name.tLIKE '%kalamassery%' ORstreet.tLIKE '%kalamassery%' ORtown.tLIKE '%kalamassery%' ORdistrict.tLIKE '%kalamassery%' ORemail_id.tLIKE '%kalamassery%' ORpincode.tLIKE '%kalamassery%' ) ORDER BYoffice_name.meta_valueASC,t.menu_order,t.post_title,t.post_dateLIMIT 0, 25; Response: Unknown column 'office_name.t' in 'where clause'`

Instead of `office_name.t` shouldn't it be `office_name.meta_value` ?

**Comment by Ramoonus** [comment]
what version of MySQL are you using?

**Comment by Ramoonus** [comment]
in the query you are showing, spaces are missing. making it slightly more difficult to debug

**Comment by kaushikam** [comment]
5.6.34 - MySQL Community Server

**Comment by kaushikam** [comment]
Database Error; SQL: SELECT DISTINCTt.* FROM vi_posts AS t LEFT JOIN vi_postmeta AS office_name ON office_name.meta_key= 'office_name' AND office_name.post_id=t.ID LEFT JOIN vi_postmeta AS street ON street.meta_key= 'street' AND street.post_id=t.ID LEFT JOIN vi_postmeta AS town ON town.meta_key= 'town' AND town.post_id=t.ID LEFT JOIN vi_postmeta AS district ON district.meta_key= 'district' AND district.post_id=t.ID LEFT JOIN vi_postmeta AS email_id ON email_id.meta_key= 'email_id' AND email_id.post_id=t.ID LEFT JOIN vi_postmeta AS pincode ON pincode.meta_key= 'pincode' AND pincode.post_id=t.ID WHERE ( (t.post_status IN ( "publish" ) ) AND (t.post_type= "office" ) ) AND (office_name.t LIKE '%kalamassery%' OR street.t LIKE '%kalamassery%' OR town.t LIKE '%kalamassery%' ORdistrict.t LIKE '%kalamassery%' OR email_id.t LIKE '%kalamassery%' OR pincode.t LIKE '%kalamassery%' ) ORDER BY office_name.meta_value ASC,t.menu_order,t.post_title,t.post_date LIMIT 0, 25; Response: Unknown column 'office_name.t' in 'where clause'

**Comment by JoryHogeveen** [comment]
```sql
SELECT DISTINCT t.* FROM vi_posts AS t 
	LEFT JOIN vi_postmeta AS office_name ON office_name.meta_key= 'office_name' AND office_name.post_id=t.ID 
	LEFT JOIN vi_postmeta AS street ON street.meta_key= 'street' AND street.post_id=t.ID 
	LEFT JOIN vi_postmeta AS town ON town.meta_key= 'town' AND town.post_id=t.ID 
	LEFT JOIN vi_postmeta AS district ON district.meta_key= 'district' AND district.post_id=t.ID 
	LEFT JOIN vi_postmeta AS email_id ON email_id.meta_key= 'email_id' AND email_id.post_id=t.ID 
	LEFT JOIN vi_postmeta AS pincode ON pincode.meta_key= 'pincode' AND pincode.post_id=t.ID 
WHERE ( (t.post_status IN ( "publish" ) ) 
	AND (t.post_type= "office" ) ) 
	AND (office_name.t LIKE '%kalamassery%' OR street.t LIKE '%kalamassery%' OR town.t LIKE '%kalamassery%' ORdistrict.t LIKE '%kalamassery%' OR email_id.t LIKE '%kalamassery%' OR pincode.t LIKE '%kalamassery%' ) 
ORDER BY office_name.meta_value 
ASC,t.menu_order,t.post_title,t.post_date 
LIMIT 0, 25; Response: Unknown column 'office_name.t' in 'where clause'
```

@Ramoonus @sc0ttkclark 
`ASC,t.menu_order,t.post_title,t.post_date`, The comma after `ASC`, that shouldn't be there right?

**Comment by kaushikam** [comment]
I copied it from and then edited to remove space hence. Anyway that code is auto generated. Does anybody using pods-ui after all ?
