### ISSUE TITLE
`track_changed_fields` doesn't work for relationship fields

### ISSUE THREAD

**Issue by thirdender** [pods-framework/pods#3861]
d7525f5 and #1969 added a way to track changes to fields when saving using `PodsAPI::save_pod_item()`. However, as mentioned in the discussion, there's no support for loop fields. The comparison is a simple string comparison done in [`PodsAPI->get_changed_fields($pieces)`](https://github.com/pods-framework/pods/blob/3bda035e3dfacf35ef0fbe488fd60e29cb678f45/classes/PodsAPI.php#L3892):

    $pod->raw( $field ) != $pieces[ 'fields' ][ $field ][ 'value' ]

This also causes issues when relationship fields are saved. `$pod->raw( $field )` returns an array of data. For example, here's the data for a "user" relationship field:

    array(2) {
      [0]=>
      array(10) {
        ["ID"]=>
        string(1) "4"
        ["user_login"]=>
        string(6) "writer"
        …
      }
      [1]=>
      array(10) {
        ["ID"]=>
        string(1) "6"
        ["user_login"]=>
        string(6) "another_writer"
        …
      }
    }

`$pieces[ 'fields' ][ $field ][ 'value' ]` only contains:

    ["value"] => string(3) "4,6"

I tried to catch the change by hooking the actions `pods_api_pre_save_pod_item` and `pods_api_post_save_pod_item`. The value doesn't change between the two actions, suggesting that the value may be retrieved from `$_POST` once. Oddly enough, removing an item from the relationship field does trigger a change between the two actions. It also works when adding an initial value to a field, but _not_ when adding additional values to a nonempty relationship field. This is where I started getting really lost, and my notes may not be helpful…

A similar situation happens with "media" relationship fields.

I'm trying to catch when users are added to a "user" relationship field so I can e-mail them that they've been "assigned" to a post. I'm thinking I may end up hooking `added_post_meta` and watching for the change that way.

Another tangentially related frustration is that I did have this working by hooking `pods_meta_save_pre_post_resume` and `pods_meta_save_post_resume` to compare the saved data, as long as I ran `pods_cache_clear(TRUE, 'pods_items_resume')` *before* I retrieved the data in the second hook. However, after I switched from the WordPress post edit screens to the `pods_ui` edit screens, these hooks stopped being called. That may be another issue, at this point I'm rambling…

Sorry, I tried to dig a bit into the [`PodsAPI->get_changed_fields($pieces)`] method to see if I could get it to work, but I think this may require someone more familiar with the system to provide some direction.

Thanks again for the great framework :-)

**Comment by lougreenwood** [comment]
I'm now finding different behaviour to that reported above. Specifically that any rel field which already has a value set will always report changes, even if no changes are actually made!

@thirdender BTW - What you mention below should have been fixed by @sc0ttkclark's work on #3917 
>  tried to catch the change by hooking the actions pods_api_pre_save_pod_item and pods_api_post_save_pod_item. The value doesn't change between the two actions, suggesting that the value may be retrieved from $_POST once.

**Comment by quasel** [comment]
No idea if that#s still the case but with the work on 2.8 and the PodsObject there are some changes ahead ;)
