### ISSUE TITLE
Add new Post Type labels

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3879]
https://make.wordpress.org/core/2016/11/03/new-post-type-labels-in-4-7/

**Comment by JoryHogeveen** [comment]
See #3929 
This PR can be done for 2.6.8 as well but it will require another PR that was done for 2.7 first: #3689

**Comment by sc0ttkclark** [comment]
We can do this in 2.6.8 and just manually resolve conflicts accepting 2.7 in that block.

**Comment by JoryHogeveen** [comment]
Ok, I'd guess you could merge the commits from #3689 and #3929 into 2.x manually if you want it applied on Pods 2.6.8.

**Comment by sc0ttkclark** [comment]
We can leave this for 2.7, sorry I didn't catch the trail of history from before :)

**Comment by pglewis** [comment]
Since we've moved the milestone to 2.7 and all the necessary pieces are in the 2.7 branch, is this ready to be closed?  (and also #3854?)

**Comment by JoryHogeveen** [comment]
Yep :)
