### ISSUE TITLE
jQuery.fn.size() is deprecated

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3898]
https://github.com/pods-framework/pods/blob/30dff/ui/fields/media.php#L301
https://github.com/pods-framework/pods/blob/30dff/ui/js/jquery.pods.attach.js#L84

**Comment by pglewis** [comment]
`JQMIGRATE: jQuery.fn.size() is deprecated; use the .length property`

**Comment by JoryHogeveen** [comment]
@pglewis Is this a change for 2.7 or 2.6.8?

**Comment by pglewis** [comment]
Probably 2.7 but it's small enough that it could be squeezed in whenever.  I just stumbled over it while doing something else.
