### ISSUE TITLE
WP_Query style where arg for Pods::find() should support 'meta_type'

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#3899]
In WP_Query you can specify 'meta_type' to cast a meta query argument. That's cool, would be hella useful in Pods.

Stand back, I'm about to do science.

**Comment by Shelob9** [comment]
OK, this totally works. Here is my test:

```
$params = array (
		'where' =>
			array (
				0 =>
					array (
						'relation' => 'AND',
						0 =>
							array (
								'field' => 'num_1',
								'value' => '1.5',
								'compare' => '>=',
								'meta_type' => 'DECIMAL'
							),
						1 =>
							array (
								'field' => 'num_2',
								'value' => '10.5',
								'compare' => '<=',
								'meta_type' => 'DECIMAL'
							),
					),
			),
	);

	$pods = pods( 'scott', $params );
```

This query works for scotts with num_1 greater than say 3.3 and less than 10.4, which as a string would not work. That said, in my patch I am assuming these fields would get ".meta_value" appended, which smells bad to me. I got SQL error before I did that. That's bad because without the cast, that isn't needed for meta queries.

Please let me know what would be best in terms of making this most useful -- I remember casting meta values being a major sticking part in Pods support -- vs not breaking stuff.

**Comment by sc0ttkclark** [comment]
I looked over this, it's already possible by using the `type` parameter.
