### ISSUE TITLE
Highlighting draft pods

### ISSUE THREAD

**Issue by iantresman** [pods-framework/pods#3906]
I often forgot to publish drafts, or to Save my Pods. As a reminder and highlight, it would be useful if the following notifications could be optionally  enabled:

1. For Pod fields to show “Unsaved” in red, if they have not been saved
2. For the WP Pods Admim menu to show a numeric flag, indicating the number of unsaved Pods. Similar to the number of waiting updates, when WP has updates waiting
3. Similarly for Unpublished new content types, to show (a) "Unpublished" on the Content type page if it needs to be published still (b) for the WP menu for each new content type, to show a numeric flag  indicating the number of Unpublished content types.

**Comment by quasel** [comment]
add1) my guess - you are talking about the "edit" screen for a CPT?
add2) pleas clarify if they are unsaved how should that work? 
add3) not sure I can follow ^^

Sorry for the late reply, feel free to comment if you still have questions!
