### ISSUE TITLE
REST-API Full relationship field to woocommerce product returns false

### ISSUE THREAD

**Issue by MaxZiebell** [pods-framework/pods#3908]
Using a custom PODS with a relationship-field _(multiselect/singleselect, autocomplete, REST read enabled, depth set at 2)_ pointing to the products custom post type of woocommerce. If set to return FULL and call the the JSON endpoint of my PODS it only returns (in data branch)

`"fieldname": [false],`

Requesting ID or NAME works fine and returns a list of elements

On the woocommerce side I enabled REST Endpoints just to make sure that's not the cause.

**Comment by jimtrue** [comment]
What are the results that return with just ID or NAME?

We're discussing this one on Slack, because I'm getting a full post return on a fresh setup with the same relationship settings.

**Comment by MaxZiebell** [comment]
As expected …

for multiselect:
`"fieldname": [40,41]`

single select:
`"fieldname": 40`

with the names the same thing.

**Comment by jimtrue** [comment]
Okay, that's good, but I'm still concerned you're not getting the full result like I'm getting with my local setup:

```
"related_products": {
"ID": "158",
"post_author": "1",
"post_date": "2016-12-31 11:57:57",
"post_date_gmt": "2016-12-31 11:57:57",
"post_content": "Product Details",
"post_title": "Test Product",
"post_excerpt": "",
"post_status": "publish",
"comment_status": "open",
"ping_status": "closed",
"post_password": "",
"post_name": "test-product",
"to_ping": "",
"pinged": "",
"post_modified": "2016-12-31 11:57:57",
"post_modified_gmt": "2016-12-31 11:57:57",
"post_content_filtered": "",
"post_parent": "0",
"guid": "http://local.wordpress.dev/?post_type=product&#038;p=158",
"menu_order": "0",
"post_type": "product",
"post_mime_type": "",
"comment_count": "0",
"pod_item_id": "158"
},
```

**Comment by jimtrue** [comment]
Still doesn't grab price which would be the most useful, so I still think grabbing just the id's and then pulling a separate JSON for the products might be smartest.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!

**Comment by AniketMalik** [comment]
Is there any possible solution to this ?

**Comment by JoryHogeveen** [comment]
Hi @AniketMalik 
Is the `product_tag` taxonomy extended with Pods?
Cheers, Jory

**Comment by AniketMalik** [comment]
@JoryHogeveen No, i have not extended `product_tag` taxonomy. I have created a separate `Tags` field using pods as a Relational Type of field and to which i have related the `product_tag` taxonomy of woo-commerce. I have attached the images above of the `Tags` field setup.

**Comment by JoryHogeveen** [comment]
Hi @AniketMalik 
Then please extend the `product_tag` taxonomy with Pods.

**Comment by AniketMalik** [comment]
@JoryHogeveen Please tell me how should I extend `product_tag` taxonomy with Pods, i mean should I define a separate field or what ?

Thanks.

**Comment by JoryHogeveen** [comment]
You can extend an existing object by creating a new Pod and select "extend".

**Comment by AniketMalik** [comment]
@JoryHogeveen Thanks.
