### ISSUE TITLE
Relationship from Post to User

### ISSUE THREAD

**Issue by andreash** [pods-framework/pods#3909]
Hi - 

I may have found a bug in relationships ... tracked it down a bit. I set up a relationship (even bi-directional) between pages and users. Multivalued. From a page, the name of the relationship field is "contact". In a PODS template I use [each] to loop over all contacts. Between [each] and [/each] I try to output field contents of the contact, i.e. a the related user pod. Fields like "display_name" give me nothing, and {@id} or {@title} show the id and title of the post, which relates to the contacts.

I tracked it down to "functions-view_template.php" where in line 250 the subpod is loaded: $subpod = pods( $pod->fields[ $atts[ 'field' ] ][ 'pick_val' ] );
This doesn't work because the 'pick_val' entry of a user-pod ($atts['field'] = 'user') is empty. Tried to track down the reason for that, but got lost in PODS code.

Can you confirm my analysis?

If I set the pic_val value to "user" during a debuggin session, the right values are shown. 

My "final" solution was to manually add an entry in table "wp_postmeta" where the post_id would be the id of the relationship field in wp_posts, the meta_value would be "pick_val" and the meta_value would be "user". Then, after clearing the PODS cache, the correct results were shown.

**Comment by andreash** [comment]
Hi - me again. Further investigations on this showed, that my workaround is not really successful. With the "pick_val" set in the wp_postmeta, the data comes out OK. But after I added another field to "Page", the Admin-Editor for Pages showed an SQL-error, trying to read from table "user", where the edit box for the Contacts should have been shown.

I now work with a filter on "pods_view_get_transient" and add the pick_val during the process.

`/*******************************************************************************
 * Patch for PODS which doesn't assign a pick_val for related USER fields
 */
add_filter('pods_view_get_transient','dpm_pods_view_get_transient',10,3);
function dpm_pods_view_get_transient($value,$original_key,$group) {
  if ($original_key == 'pods_wp__pod_tableinfo_page') {
    foreach($value['fields'] as &$field) {
      if ($field['pick_object'] == 'user' and empty($field['pick_val'])) {
        $field['pick_val'] = 'user';
      }
    }
  }
  return $value;
}`

**Comment by quasel** [comment]
closing in favor of #4484
