### ISSUE TITLE
Memory Issue switching to PHP7

### ISSUE THREAD

**Issue by steve-acet** [pods-framework/pods#3912]
Hi there,
I thought I would give PHP7 a go and have issues getting into the Dashboard, these are from my error logs:

[03-Jan-2017 16:47:52 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/aclighti/public_html/test/wp-content/plugins/pods/�' (include_path='.:/usr/local/php70/pear') in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 16:48:14 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 578721528598759536 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 16:48:20 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 26319559590072 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 16:57:04 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 755914244504 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 17:01:57 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 15530610620704 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 17:02:07 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1992864826280 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 17:28:53 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1992864826280 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[04-Jan-2017 08:58:58 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 8391086184879776200 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[04-Jan-2017 09:44:00 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/aclighti/public_html/test/wp-content/plugins/pods/x' (include_path='.:/usr/local/php70/pear') in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[04-Jan-2017 09:44:04 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1477468749912 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[04-Jan-2017 09:45:27 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_SimplePie_File' not found in /home/aclighti/public_html/test/wp-includes/SimplePie/Registry.php:179

Any ideas where I should start looking?

Cheers,

Steve

**Comment by pglewis** [comment]
PHP 7 should work fine, what version of Pods and WordPress?  

Also seems to be some weird characters in a couple of the paths you pasted... may just be buffer issues when running out of memory, or may be something odd.

**Comment by steve-acet** [comment]
Pods 2.6.7 and WordPress 4.7

The weird characters show that way in the log as well.

WordPress memory limit is 768Mb

**Comment by sc0ttkclark** [comment]
How many Pods/fields do you have on your site? What other plugins are you running?

Unit tests for Pods are passing just fine for PHP 7, 7.1, and HHVM.

**Comment by sc0ttkclark** [comment]
You also might try re-downloading Pods and uploading it to your /pods/ plugin folder.

**Comment by steve-acet** [comment]
4 x Custom Taxonomies
2 x Custom Post Types
2 x Post Types (extended)
2 x Advanced Content Types
1 x Media (extended)

10 pods, 42 fields

I will have a go at re-uploading the Pods folder.

**Comment by sc0ttkclark** [comment]
Doesn't look too bad, do you have a lot of data on your site or many large plugins?

**Comment by steve-acet** [comment]
This is from WooCommerce:

`
### WordPress Environment ###

Home URL: http://test.aclighting.com
Site URL: http://test.aclighting.com
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (69) ###

Query Monitor: by John Blackbourn – 2.13.2
License-Manager: by Isaac Oyelowo – 5.1
Annual Archive: by Twinpictures – 1.4.8
Attached Files Widget: by Steve Hoare – 1.0
Better Search: by Ajay D'Souza – 2.1.0
iThemes Security: by iThemes – 6.0.0
Black Studio TinyMCE Widget: by Black Studio – 2.3.1
Brand Info Widget: by Steve Hoare – 1.0
Better WordPress Minify: by Khang Minh – 1.3.3
Category Tag Pages: by Marzio Carro – 1.0
Chase Paymentech Hosted Checkout Canada Payment Gateway For WooCommerce: by Steve Hoare – 0.1
Contact Form 7 - Dynamic Text Extension: by Chris Mavricos
SevenSpark – 2.0.1

Contact Form 7 Honeypot: by Nocean – 1.10
Contact Form 7: by Takayuki Miyoshi – 4.6
Country Popup: by Steve Hoare – 1.0.0
Debug: by SoniNow Team – 1.7
Duplicate Post: by Enrico Battocchi – 3.1.2
Email Log: by Sudar – 1.9.1
Enable Media Replace: by Måns Jonasson – 3.0.5
Facebook Conversion Pixel: by Kellen Mace – 1.3.5
Featured Image Column: by Austin Passy – 0.2.3
Featured Image: by Mervin Praison – 2.0
Fluid Video Embeds: by jamie3d – 1.2.9
Font Awesome 4 Menus: by New Nine Media – 4.7.0
Format Media Titles: by David Gwyer – 0.30
Hierarchical Pages: by William Lindley – 1.6.1
HTML entities button: by tmatsuur – 2.0.0
Image Widget: by Modern Tribe
Inc. – 4.2.2

Jetpack by WordPress.com: by Automattic – 4.4.2
Link Library: by Yannick Lefebvre – 5.9.13.15
Listo: by Takayuki Miyoshi – 1.1
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.2

New Facebook Pixel with Standard Events for WooCommerce: by GhostMonitor – 1.4.0
Pages Order: by SedLex – 1.1.3
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.6.7
WordPress Post Type Archive Links: by Stephen Harris – 1.3.1
Redirection: by John Godley – 2.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Related Pages Widget: by Steve Hoare – 1.0
Related Posts By Taxonomy: by keesiemijer – 2.2.1
Search box on Navigation Menu: by Nazmul Hasan Rupok – 1.1
SearchWP Live Ajax Search: by Jonathan Christopher – 1.1.8
Selected Related Pages Widget: by Steve Hoare – 1.0
SG CachePress: by SiteGround – 2.3.11
Simple Locator: by Kyle Phillips – 1.5.6
Simple Page Hierarchy Widget: by Josh Mallard – 1.0.3
Page Builder by SiteOrigin: by SiteOrigin – 2.4.21
SiteOrigin Widgets Bundle: by SiteOrigin – 1.7.2
TweetScroll Widget: by Pixel Industry – 1.3.7
Ultimate Tag Cloud Widget: by Rickard Andersson – 2.7.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.30

Visual Term Description Editor: by Shea Bunge – 1.5.0
WooCommerce Weight Based Shipping: by dangoodman – 4.2.2
WooCommerce Accepted Payment Methods: by jameskoster – 0.7.0
WooCommerce Extended Coupon Features: by Soft79 – 2.3.7.4
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Shipping Tracking: by Lagudi Domenico – 4.7
WooCommerce Stock Manager: by Vladislav Musílek – 1.1.3
WooCommerce: by WooThemes – 2.6.11
WooCommerce Helper: by WooCommerce – 1.7.2
WP Crontrol: by John Blackbourn & Edward Dale – 1.4
Force Login: by Kevin Vess – 5.0
WP Migrate DB: by Delicious Brains – 0.9.2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.0

WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WP RSS Aggregator: by RebelCode – 4.10
WP RSS Aggregator - Feed to Post: by RebelCode – 3.7.2
WP Template Viewer: by keesiemijer – 0.1.2

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #14556 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: AC Lighting Inc
Version: 1.14
Author URL: http://www.ac-et.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: ac-lighting-inc-v16/woocommerce/archive-product.php
ac-lighting-inc-v16/woocommerce/cart/cart-totals.php
ac-lighting-inc-v16/woocommerce/cart/cart.php
ac-lighting-inc-v16/woocommerce/checkout/thankyou.php
ac-lighting-inc-v16/woocommerce/content-product.php
ac-lighting-inc-v16/woocommerce/emails/customer-new-account.php
ac-lighting-inc-v16/woocommerce/emails/customer-reset-password.php
ac-lighting-inc-v16/woocommerce/emails/email-addresses.php
ac-lighting-inc-v16/woocommerce/emails/email-footer.php
ac-lighting-inc-v16/woocommerce/emails/email-header.php
ac-lighting-inc-v16/woocommerce/emails/email-order-items.php
ac-lighting-inc-v16/woocommerce/emails/email-styles.php
ac-lighting-inc-v16/woocommerce/loop/add-to-cart.php
ac-lighting-inc-v16/woocommerce/order/order-details-item.php
ac-lighting-inc-v16/woocommerce/order/order-details.php
ac-lighting-inc-v16/product-searchform.php
ac-lighting-inc-v16/woocommerce/single-product/meta.php
ac-lighting-inc-v16/woocommerce/single-product/product-image.php
ac-lighting-inc-v16/woocommerce/single-product/related.php
ac-lighting-inc-v16/woocommerce/single-product.php

`

**Comment by sc0ttkclark** [comment]
If you're going to run that many plugins and have that much configuration in the database, you're going to want to up your memory limit.

**Comment by sc0ttkclark** [comment]
I haven't actually needed more than 1024M - 1536M on the biggest most complex projects of mine.

**Comment by sc0ttkclark** [comment]
If you're using SiteGround's memcaching then Pods Alt Cache will also improve performance a bit too, so that'll be an easy success there. Start with 1024M and see if that resolves your problems, adjust higher only if necessary.

**Comment by steve-acet** [comment]
I will see what Siteground say.

Replacing the pods folder and the alternative cache hasn't worked, even when set to use memcache in wp-config.php. The site works, just can't get to the dashboard to do anything, which is kinda annoying :)

**Comment by steve-acet** [comment]
I turned off most and slowly turned them back on, seems ok so far. Not everything was needed as it was my test site, but all essential ones are on without any issues. Even PHP7.1 seems ok. Just trying to figure out which plugin was pushing the site over the edge, it must be a combination, just need to find it.

**Comment by sc0ttkclark** [comment]
SiteGround does have the cloud hosting option where you can choose to get a bit more dedicated memory, but I'm glad you were able to get it working.

**Comment by lukecav** [comment]
Never needed 1024mb of memory limit defined in wp-config.php on a client project ever.

**Comment by sc0ttkclark** [comment]
When we implement Groups in Pods 2.8 we'll be refactoring our configurations to make use of PodsObject which uses a fraction of the memory that we're using now. I don't think Pods itself is using up all that memory though, that's a pretty small config.

**Comment by steve-acet** [comment]
Do you have a rough date for 2.8?

**Comment by sc0ttkclark** [comment]
We're working on getting 2.7 finished up if all goes well this month. From there, it'll be a few months minimum because there's a lot of testing to be done to ensure ArrayAccess overload bugs are all fixed up across Pods.

**Comment by steve-acet** [comment]
Cool. I am happy to test on my test site if that helps?

**Comment by sc0ttkclark** [comment]
Sounds great, we will announce the 2.8 beta when that gets closer

**Comment by lkraav** [comment]
@steve-acet @sc0ttkclark this is all about a completely different issue and nothing to do with actual memory consumption (see how insane the memory counts are in the bug report?). SiteGround has been running a broken PHP7 configuration since the release of PHP7 last year, and it took them a year (up to just last week) to finally figure out that for whatever reason, on their shared specific infrastructure opcache was running out resources and going crazy. I don't want to start counting the time and money it cost me to fight with their support and eventually simply had to give up. Migrated one client away, but the other two were too big and expensive to move at the time.

https://www.facebook.com/groups/advancedwp/permalink/1366059663456244/

`opcache.interned_strings_buffer = 8M` is the current best bet to get PHP7 working on SG.

I will be testing it myself over this weekend.

```
> [03-Jan-2017 16:47:52 UTC] PHP Fatal error: require_once(): Failed opening required '/home/aclighti/public_html/test/wp-content/plugins/pods/��' (include_path='.:/usr/local/php70/pear') in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
[03-Jan-2017 16:48:14 UTC] PHP Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 578721528598759536 bytes) in /home/aclighti/public_html/test/wp-content/plugins/pods/classes/Pods.php on line 3901
```

**Comment by quasel** [comment]
Now that explains some very weird stuff I encountered :/

**Comment by steve-acet** [comment]
So this may explain why last week it started working for. It just happened to be when I was trying to fix it that they fixed it.
