### ISSUE TITLE
WPML relationship duplication/copying not working

### ISSUE THREAD

**Issue by veisis** [pods-framework/pods#3916]
When post is duplicated or meta field copied (meta field is set to "copy" in wpml settings) to other language meta data is set correctly, but relationship in table "wp_podsrel" is not added.
Pods framework needs to hook in wpml_after_copy_custom_field to add relationship in "wp_podsrel" table.

**Comment by quasel** [comment]
that's a tricky thing - as for the related item should it stay the same? will it also be translated? what if that item has further relations? not a WPML user but sounds tricky ^^

**Comment by JoryHogeveen** [comment]
Same issues: #4544 #2006 
Closing here
