### ISSUE TITLE
pods_api_post_save_pod_item returns old field values

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#3917]
I have a feature which, when a post is saved, automatically sets the title of a post. It uses the values of various fields for that record.

E.g let's say the Pod (let's call it OriginalPod) has a couple of fields:

FieldA: Relationship field to some other Pod
FieldB: Number

After save of a record in OriginalPod any called to `$original_pod_just_saved_record->field()` and also `$original_pod_just_saved_record->display()` displays the data saved for the record _before_ the save function. 

Essentially, this means that my feature which automatically updates a records name, after save, needs to be executed/triggered by 2 saves to the record:

* First save - saves the new values into the record
* Second save - updates the title using the values saved (but not available) during first save.

Expected behaviour is that when retrieving the values for `$original_pod_just_saved_record` in the `pods_api_post_save_pod_item` action hook, the values returned in `$original_pod_just_saved_record->field()` & `$original_pod_just_saved_record->display()` should be the same as what was saved for the fields.
i.e - Only a single save should be necessary of my auto-title-update feature.

I have a hunch this may be similar/related to #3801

**Comment by lougreenwood** [comment]
This can be verified with something like...:

```
add_action( 'pods_api_post_save_pod_item', function( $id, $pieces, $is_new_item ) {
$my_pod( 'some_pod', $id );
var_dump( $my_pod->field( 'some_field' ) );
var_dump( $my_pod->display( 'some_other_field' ) );
die();
}, 10, 3 );
```

**Comment by lougreenwood** [comment]
Hey @sc0ttkclark 

I think I've just run into this bug again, but in a slightly different context.

It seems that this bug still exists when calling via REST API. I'm finding that when I create a post using wp-admin, I use some `pods_api_post_save_pod_item` to do some automation on the new record (auto-set title etc). This is working as expected.

When I create a new post using WP JSON REST API, doing `$mypod->fields('some_field')` is returning empty/null values...

Is this possible given the Pods architecture? Perhaps REST API uses a different workflow and doesn't clear the cache?

**Comment by sc0ttkclark** [comment]
The latest issue as described by @lougreenwood is fully documented and explained in #4358
