### ISSUE TITLE
When User is extended by Pods, saving a new user does not trigger 'pods_api_post_save_pod_item'

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#3918]
If User is extended by Pods and an action hook exists to do some stuff to new users, the hook is not triggered when new users are created.

However, hook is triggered upon first save of a user's profile.

**Comment by jimtrue** [comment]
The new user form doesn't include all the profile fields or any of the user_meta unless you've replaced that with another user registration form.

**Comment by lougreenwood** [comment]
hey :)

I mean from within wp-admin.

It seems to me that the expected behaviour for hooks, when creating a user from within wp-admin should be that it behaves as any other Pod does - i.e. on create OR update the hook is triggered. User only triggers the hook on update...

**Comment by jimtrue** [comment]
You'd probably need to add your 'hook' into the default New User hook by WordPress core, in addition to the Pods-save one if you want it to be fired. This is a limitation on the New User Registration form, not Pods, because there are no extended Pods fields available on New User Registration, though we might have to also make sure we're firing on that hook (but if our fields aren't part of the New User registration, there's not much we can do there).

**Comment by jimtrue** [comment]
That looks like it's covered in this article:
https://codex.wordpress.org/Plugin_API/Action_Reference/user_register

**Comment by lougreenwood** [comment]
Thanks, I'll look into it 👍 

But surely, if I can hook into it, Pods could also hook into it and trigger it's own 'pods_api_post_save_pod_item' action by adding a do_action into the WP new user hook you mentioned above

Just mentioning it as this seems like an edge case that could trip up other Pods users and if this is the issue, seems like a trivial core fix to ensure User behaves the same as all other Pods...

**Comment by jimtrue** [comment]
Possibly, but the issue **may** be that we can't insert our Pods fields on the New User Registration form and that maybe why we can't hook into it at that point. We're an open source community supported plugin; if you figure it out and get it working, draft a PR and we'll get it fixed and credit you for the fix!

**Comment by sc0ttkclark** [comment]
We do not currently hook into `user_register` or anywhere else on user creation.
