### ISSUE TITLE
Mapping formidable pro form inputs to pods custom fields issues

### ISSUE THREAD

**Issue by codente** [pods-framework/pods#3930]
So this works really well, actually, except that if you have a Pods required field, you get an error on submission of the form:

e.g.  Date is empty

Even though I have a form field mapping to the Pods custom field.  The post DOES get created but the custom fields are empty for the post you created.  If I remove all required fields, then the post gets created and the custom fields are populated.

I'm not sure but it seems like the post get created before the field mapping happens so maybe it's not an issue with Pods at all.  Not sure.

**Comment by codente** [comment]
I was able to resolve this actually.  False alarm!

**Comment by jimtrue** [comment]
We've discussed this on Slack. It sounds like the issue specifically is the 'save' order with Required fields in Pods and when the post is written and meta written coming over from Formidable Forms Pro. We're probably going to need you to bring your support folks over here for discussion and resolution, since you have a premium license and we don't. Without the pro version of the plugin, we have no way to test what you're experiencing.

**Comment by codente** [comment]
I was going to try to reproduce this with the free version but the ability to create posts is only available in the pro version.

Here's what I have via Formidable support "When Formidable creates posts, the post is created first, and then the custom fields are added afterwards. Perhaps this order is causing issues in Pods?"

I've since linked their support to this issue in hopes they are willing to work on this and chime in as well.

**Comment by jwahlin** [comment]
Hello,

This is Jamie, a developer from Formidable Forms. I would be happy to help resolve this incompatibility. At this point, we are creating the post with wp_insert_post(), then we are adding custom fields with update_post_meta(). It looks like we now have the option of including post meta in the array passed into wp_insert_post(). That could be one solution to this issue, but this would increase our minimum required WP version to 4.4.0. Currently, we are compatible with WP 3.8 and higher. Do you have a way for us to bypass the required custom field checks when the post is created with wp_insert_post( $postarr ) and the custom field values are not included in the meta_input item of $postarr?

**Comment by sc0ttkclark** [comment]
This sounds like a bug we can fix on our side. Looking into it.

**Comment by codente** [comment]
@jwahlin Thanks for chiming in Jamie! :)

@sc0ttkclark thanks Scott.  Let me know if you need me to test anything if you come up with something.  I have a live setup with both that I'd ideally like to use Pods required fields on if it can be done :)

**Comment by sc0ttkclark** [comment]
I've got a solution for this in the PR https://github.com/pods-framework/pods/issues/3937

**Comment by codente** [comment]
Thanks @sc0ttkclark.  I wouldn't mind testing this but not sure how to with a PR.

**Comment by sc0ttkclark** [comment]
You can download the branch from https://github.com/pods-framework/pods/tree/feature/3930-keep-track-of-podsmeta-direct-saves

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/archive/feature/3930-keep-track-of-podsmeta-direct-saves.zip

**Comment by codente** [comment]
@sc0ttkclark  Ok I installed this version but the same issue exists.  Is there anything else I need to do on my end?

**Comment by sc0ttkclark** [comment]
@codente tested and confirmed on your test site. Should be good to go
