### ISSUE TITLE
Extra currencies

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3939]
After #1915 
i would like to add currencies for:

- [ ]  Europe
- [ ]  [North America](https://en.wikipedia.org/wiki/List_of_currencies_in_North_America)
- [ ]  South America
- [ ]  Africa
- [ ]  Asia
- [ ]  Oceania
- [ ]  [cryptocurrencies](https://en.wikipedia.org/wiki/List_of_cryptocurrencies)

this will increase user functionality around the globe for non USD and Euro people

**Comment by sc0ttkclark** [comment]
+1

**Comment by JoryHogeveen** [comment]
This should fixed together with #1915, #3482, #3453 and #3218

**Comment by JoryHogeveen** [comment]
Maybe a but over the top but:
https://en.wikipedia.org/wiki/List_of_circulating_currencies

**Comment by sc0ttkclark** [comment]
I think having more would be great, but having a select2 to choose would make it at least a bit easier :)

**Comment by Ramoonus** [comment]
scope creep

**Comment by Ramoonus** [comment]
updated initial post with a todo list and checkboxes

**Comment by Ramoonus** [comment]
I might have some time tuesday/wednesday

**Comment by Ramoonus** [comment]
today

**Comment by Ramoonus** [comment]
first step #3987
