### ISSUE TITLE
More fields, options to move it to the side?

### ISSUE THREAD

**Issue by zilveer** [pods-framework/pods#3944]
Hello,
when creating custom fields in pods I would like to have an option to have it on the side instead of below the editor.

Maybe this is even possible, I have tried to search for this without results..

Please let me know.

regards

**Comment by sc0ttkclark** [comment]
@zilveer I will make sure this is available as an option when we get Pods 2.8 out the door, great idea!

**Comment by JoryHogeveen** [comment]
ACF has some nice options for metaboxes. Could be nice to check.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen I'm cool with feature parity there, but the conditional logic feature would require us to have the input UI abstracted there because we'd want to reuse that per-field and in other cases like admin visibility etc.

**Comment by zilveer** [comment]
@sc0ttkclark thank you very much :)

**Comment by sc0ttkclark** [comment]
This made it into Pods 2.8 groups work.
