### ISSUE TITLE
Localization for labels in get_wp_object_fields()

### ISSUE THREAD

**Issue by pavelevap** [pods-framework/pods#3956]
Can we have a localized labels in [get_wp_object_fields()](https://github.com/pods-framework/pods/blob/2.x/2.6.8/classes/PodsAPI.php#L898)?

Labels are used automatically for example in `[pods-form]` shortcode (displayed on website). I can use `get_wp_object_fields` hook, but localization is better, I guess.

If I did not miss anything, can I try to prepare PR for 2.7?

**Comment by quasel** [comment]
PR's are always welcome ;) feel free to creat one - I'll close this issue but if you happen to do a PR just open a new issue
