### ISSUE TITLE
Bug Report: Notice: Undefined index

### ISSUE THREAD

**Issue by David-Brown** [pods-framework/pods#3964]
Hi, 

Recently updated to Pods 2.6.8 on a client's site. The site is using a custom post type for patient forms that a user can download. The post type includes a single custom field, for file upload ("File/Image/Video" field type), allowing only doc, docx, and pdf file extensions. This custom post type is being used within a Pods template in a WYSIWYG editor. Following the update to 2.6.8, this throws the following notice: 

`Notice: Undefined index: file_wp_gallery_output in /path/to/wordpress/wp-content/plugins/pods/classes/fields/file.php on line 293`

This occurs running PHP 7.0.12 and MySQL 5.6.33 in a local environment. I haven't tested with other PHP versions.

I also have the following in my error log: 

`Illegal string offset 'pod' in /path/to/wordpress/wp-content/plugins/pods/components/Templates/includes/element-pod_reference.php on line 14`

**Comment by JoryHogeveen** [comment]
Hi @David-Brown 

Your first issue is fixed in this PR: https://github.com/pods-framework/pods/pull/3958
You can also simply fix the issue by re-saving your Pods.

I'm afraid I can't help you with the second one on short notice, I'm not familiar with the Pods Templates code. @sc0ttkclark Maybe you can look into that one?

**Comment by David-Brown** [comment]
Thanks, @JoryHogeveen . I tried re-saving all of the Pods, but no joy. I'm assuming that this PR will be in a future Pods release, correct?

**Comment by JoryHogeveen** [comment]
That is weird, resaving should save these keys.
This PR will be for the next release (2.7 if I'm correct).
You can however apply this fix manually if you want. No harm done :)
https://github.com/pods-framework/pods/pull/3958/files

**Comment by pglewis** [comment]
We should have a separate issue for the warning coming from Templates.
