### ISSUE TITLE
WP Job Manager Job search is not functioning correct when pods is active

### ISSUE THREAD

**Issue by Irpe1337master** [pods-framework/pods#3965]
In WP Job Manager search form job type checkbox checked value is not saved temporarily if pods is active. This happens when user **is not logged in**. Tested using Firefox 51.0 and Internet explorer 11.0.38. This doesn't happen in Chrome. 

In first image PODS is not active and it show how search form works. Search form is located in "Jobs" page.

1. Uncheck few checkboxes. 
2. Visit Job Dashboard page and come back to the previous page ( JOBS )  using browsers back button. 3.Form remembers which checkboxes were checked or unchecked.

![job type saved](https://cloud.githubusercontent.com/assets/25027233/22283354/692fdda6-e2ea-11e6-97d4-5daf3de04a38.png)

I activated PODS and logged out. Refresh Jobs page few times. Repeat previous steps. 

![unchekc few boxes](https://cloud.githubusercontent.com/assets/25027233/22283516/65099e64-e2eb-11e6-9ee8-2ca21446e483.png)

All the checkboxes are now selected.

![outcome checkboxes are checked](https://cloud.githubusercontent.com/assets/25027233/22283519/72ed0dd6-e2eb-11e6-8618-0803f15c49df.png)
 selected.

**Comment by sc0ttkclark** [comment]
Do you know if the jobs plugin is using sessions or cookies to save the form state?

**Comment by pglewis** [comment]
Also, worth a look at Firebug/Dev Tools console to see if there are any errors or clues there.

**Comment by Irpe1337master** [comment]
I tried IE developer tools, chrome dev tools and installed dev tools to firefox. I didn't see any errors.  Firefox dev tools showed some errors but those errors were not in wp job manager files. 

What is the best way to test if form state is saved to sessions or cookies? I tried disabling cookies which had no effect to form state.

**Comment by quasel** [comment]
did you try - define('PODS_SESSION_AUTO_START', false); ? of they were using sessions related to #4636 

Sorry for the late reply, feel free to comment if you still have questions!
