### ISSUE TITLE
Not Working: define( 'PODS_UPLOAD_REQUIRE_LOGIN', false ) 

### ISSUE THREAD

**Issue by Budapresst** [pods-framework/pods#3970]
I have a frontend page with a pods plupload field... the upload does not require login to be used because the page itself is password protected...
I am getting this error: YOU DO NOT HAVE ACCESS TO UPLOAD / BROWSE FILES. CONTACT YOUR WEBSITE ADMIN TO RESOLVE. even though, I have added these lines to my wp-config.php file: 
define( 'PODS_UPLOAD_REQUIRE_LOGIN', false );
define( 'PODS_DISABLE_FILE_UPLOAD', false);

WP v. 4.7.2
Pods v. 2.6.8

please advise... the workarounds don't look pretty... :)

**Comment by baljindersingh88** [comment]
Hi
Can you please share your frontend code.just paste the lines.

Thanks
Baljinder Singh

**Comment by Budapresst** [comment]
Sorry for the slow reply, I was in a meeting and couldn't get the code with my phone only... 

So, I've tested it with the short code on a regular page and it doesn't work either... Just build a one field pod with an upload field and output it to a frontend form in WP 4.7.2 and it won't work... 

In the actual case where I discovered the problem, I was using a custom template with this code:
----------------
$fields = array('event' => array( 'value' => 'Istanbul Launch' ),'pressconf'=> array( 'default' => 1 ),'salutation','firstname','lastname','company','jobtitle','email'=> array( 'default' => $eadd ),'country_code','mobile','guest_photo');
--
echo pods( 'attendee')->form($fields,'Submit Registration', '/press-registration-successful' );
------------
where 'guest_photo' is my plupload field...

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
