### ISSUE TITLE
Passing array to html_entity_decode() for currency fields

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3975]
`Warning: html_entity_decode() expects parameter 1 to be string, array given in .../pods/classes/fields/currency.php on line 475`

`Warning: html_entity_decode() expects parameter 1 to be string, array given in .../pods/classes/fields/currency.php on line 548`

**Comment by pglewis** [comment]
Should be addressed in #3954

**Comment by Observer999** [comment]
Is there fix for this bug? I have it too?

**Comment by JoryHogeveen** [comment]
@Observer999 This is fixed in the 2.x branch, or http://pods.io/latest/ and will be included in our next Production Release.
