### ISSUE TITLE
PHPUnit 6 update (from 4)

### ISSUE THREAD

**Issue by Ramoonus** [pods-framework/pods#3984]
long term
but 4 is now unsupported
and 5 is phasing out next year

https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0

**Comment by sc0ttkclark** [comment]
We might utilize something like Codeception (built on-top of PHPUnit) in the future too

**Comment by Ramoonus** [comment]
you mean http://codeception.com/for/wordpress ?

**Comment by Ramoonus** [comment]
duplicate #3989
