### ISSUE TITLE
Unable to disable Pods Admin access for roles that have edit_users capability

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods#3985]
Hi,

I have a custom user role (_my_role_) defined on plugin initialisation. This role has no 'Pods' capabilities. If I double-check the cap-settings for this role, all 'Pods' capabilities are unchecked as they should be.

```
register_activation_hook(__FILE__, function(){
  add_role( 'my_role', 'My Role', array(
    'delete_others_pages'			=> true,
    'delete_pages'						=> true,
    'delete_private_pages'		=> true,
    'delete_published_pages'	=> true,
    'edit_others_pages'				=> true,
    'edit_pages'							=> true,
    'edit_private_pages'			=> true,
    'edit_published_pages'		=> true,
    'read_private_pages'			=> true,
    'publish_pages'						=> true,
    'delete_others_posts'			=> true,
    'delete_posts'						=> true,
    'delete_private_posts'		=> true,
    'delete_published_posts'	=> true,
    'edit_others_posts'				=> true,
    'edit_posts'							=> true,
    'edit_private_posts'			=> true,
    'edit_published_posts'		=> true,
    'read_private_posts'			=> true,
    'publish_posts'						=> true,
    'add_users'				 => true,
    'create_users'		 => true,
    'edit_users'			 => true,
    'delete_users'		 => true,
    'remove_users'  	 => true,
    'list_users'			 => true,
    'read' 						 => true,
    'level_0' 				 => true,
    'access_userarea'  => true,
    'use_sxd_tools'		 => true,
    'delete_others_tribe_events'	=> true,
    'delete_tribe_events'					=> true,
    'edit_others_tribe_events'		=> true,
    'publish_tribe_events'			  => true,
    'read_private_tribe_events'		=> true,
    'delete_private_tribe_events' => true,
    'delete_published_tribe_events' => true,
    'edit_private_tribe_events'		=> true,
    'edit_published_tribe_events'	=> true,
    'edit_tribe_events'						=> true,
  });
```

However, the Pods Admin menu including all sub menu items appear in the WP-Admin of any user with only the 'my_role' role. Every feature of Pods can be accessed by this role without proper capabilites.

Thanks.

**Comment by sc0ttkclark** [comment]
Any user with the `edit_users` capability means they can change anyone's role. Anyone with that capability is specifically treated as a super admin within WordPress, and is what we fallback to when our capabilities are not present.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark
A super admin is defined with `delete_users` capability within WP, not `edit_users`.
I'd say either that will need to be updated or we should use the `is_super_admin()` function to determine wether a user is a super admin.

**Comment by sc0ttkclark** [comment]
Sorry, you are right @JoryHogeveen I was remembering wrong but my point was the same here. They have the `delete_users` capability enabled for this role.

**Comment by sc0ttkclark** [comment]
Here's where our checks roll through:

https://github.com/pods-framework/pods/blob/2.x/includes/general.php#L281

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Ah sorry, I thought Pods checked `edit_users`.
Maybe off topic (not sure if it is a network installation). But still I'd like to see the implementation of `is_super_admin()` as well (reason I self-assigned).

More on topic:
Is the `pods` capability checked? If so, maybe a denied capability (can be done with Members) will solve this.

**Comment by sc0ttkclark** [comment]
In the code, if it's a super admin, we do check is_super_admin()

**Comment by JoryHogeveen** [comment]
Just noticed.. (long day..)

**Comment by sc0ttkclark** [comment]
There's a filter where you can override all access checks via `pods_is_admin()`, the filter is named `pods_is_admin`.

For single site installs, you can disable access from delete_users capability by using the filter:

```php
add_filter( 'pods_admin_capabilities', '__return_empty_array' );
```

**Comment by sc0ttkclark** [comment]
Need to document that if it's not already, for people to be aware.

**Comment by quasel** [comment]
closing and collecting all related stun in #2311
