### ISSUE TITLE
Hidden fields don't save Default Values

### ISSUE THREAD

**Issue by wagontrader** [pods-framework/pods#3996]
1) Created custom post type
2) Added new text field, set default value and hid from UI

When adding a new post, html source shows hidden field without a value attribute

Post meta record in database does contain the default_value

3) Changed field to no longer hide from UI

When adding a new post, the field does contain the default value.

Dave

**Comment by jimtrue** [comment]
@wagontrader A little confused on the issue here. If it's writing your default value to the database (which means it's also saving it) and it's hiding it from the UI. What's the issue? Typically the 'visibility' options are primarily to 'hide' the field from specific roles. Admin's should always be able to see and edit them.

**Comment by wagontrader** [comment]
Let me see if I can clarity...

If you check the box to hide the field from the UI, pods generates a hidden input tag in the form. The value of that tag should be the value saved in the database tables to preserve the data when the form is submitted. Instead, the value in the hidden input tag is empty... value=""

If you uncheck the option to hide from the UI, pods generates a standard text input field, this field is properly filling with the default value if the value is empty.

If the field is hidden, it writes NULL to the database, if the field is visible, it displays and writes the default value to the database. I am not talking about the visibility options, I am talking about the option to hide the field from the UI.

Hope that clarifies.
Dave

**Comment by wagontrader** [comment]
Just one more clarification... If it is a new record (one does not already exist in the database) the hidden input field should also be filled with the default value assigned, it is not, it is also empty.

**Comment by jimtrue** [comment]
Dave, thanks for the clarification! When I first read that, it sounded like it was actually working as intended (other than not displaying your field the way you intended on the front-end).

This will need verification, but it sounds like:

Hidden Fields don't save Default Values, correct?

**Comment by wagontrader** [comment]
Correct

**Comment by pglewis** [comment]
> If the field is hidden, it writes NULL to the database, if the field is visible, it displays and writes the default value to the database. I am not talking about the visibility options, I am talking about the option to hide the field from the UI.

I'm unable to reproduce this behavior at all; I'm seeing a value for my hidden input on both the 2.x branch and master (the current release).  My basic test was with a new Post type Pod and two text fields.  

It could be an edge case that only manifests under certain circumstances but we'd have to be able to reproduce it.

**Comment by wagontrader** [comment]
Using pods 2.6.8
64 bit Wampserver running PHP 5.6 on localhost
Latest chrome browser

Based on pglewis test, I gave it another try by creating a new Post type pod and two text fields. One was visible and the second hidden. Nothing fancy, just named the fields, gave them a default value and marked the second to hide from ui.

I created a new post, saved it with the default values and the hidden field did not save the value. Edited the new post and looked at the form fields, this is the input for the visible field...

`<input name="pods_meta_test_one" data-name-clean="pods-meta-test-one" data-label="Test One" id="pods-form-ui-pods-meta-test-one" class="pods-form-ui-field-type-text pods-form-ui-field-name-pods-meta-test-one" type="text" value="The Value" tabindex="2" maxlength="255">`

and this is the input for the hidden field...

`<input name="pods_meta_test_two" data-name-clean="pods-meta-test-two" id="pods-form-ui-pods-meta-test-two" class="pods-form-ui-field-type-text pods-form-ui-field-name-pods-meta-test-two" type="hidden" value="">`

**Comment by pglewis** [comment]
I think we're talking about two issues?  

1) All hidden fields have blank values, so saving will clobber any previous metadata that may have been set.  

2) Properly setting default values for fields set to be hidden from the UI.  

I could not reproduce item 1 at all, ignoring default value (no default value set) 

The second one sounds like what you've reproduced above and one that I haven't looked at as closely... I'll take another look.  But I do definitely get values in my hidden inputs in case 1.

**Comment by wagontrader** [comment]
I just tested scenario 1 by manually entering the meta value in the database and editing the post. The hidden field does contain the saved value.

Scenario 2 is the problem, without properly setting the default value, NULL is always saved to the database on record insert.

Dave

**Comment by pglewis** [comment]
Okay, so it sounds like this issue is just limited to the default value scenario.  I'll poke around with it again, should be easy to track down.

**Comment by pglewis** [comment]
PR: #4061

**Comment by paddelboot** [comment]
Having the same issue with a hidden field and a default value of `{@get.my_id}`.

Strangely enough, it works on localhost under all circumstances, but on the remote server, it will only save the default value if I uncheck the "hide from UI" option.
