### ISSUE TITLE
Overly aggressive cach flushing on multisite

### ISSUE THREAD

**Issue by svandragt** [pods-framework/pods#4006]
Calling `wp_cache_flush()` within a multisite generally clears the cache for all sites in a cluster. Currently we are unable to update to PODS 2.6.8 because of the excessive cache flushing. We have several dozen sites in our cluster.

PODS 2.6.8 has an issue / feature which appears to be periodically flushing the entirety of the Redis object cache, thus causing performance and scaling issues for the environment which never recovers in time. (WordPress 4.6.3). What we experienced was after deploying this update that immediately the redis cache got flushed repeatedly and would not recover within a 20 minute timespan, where as we would have expected the cache to restore past the 4 minute point.

We have been forced to roll the plugin back to the previous version of 2.6.7 but as it stands, we cannot updated the plugin.

Is there really a need to clear the complete cluster object cache?
See https://github.com/pods-framework/pods/search?q=wp_cache_flush(&type=Code&utf8=✓ for the instances of wp_cache_flush

**Comment by sc0ttkclark** [comment]
What version are you running now? Are you sure those wp_cache_flush() calls are causing your specific problems?

**Comment by sc0ttkclark** [comment]
PodsMigrate only runs when someone is doing a big import script manually, it's not used anywhere in our plugin's admin area through any other means besides someone calling it directly.

PodsView only runs the cache flushes there when it's asked to delete a transient or site transient for all keys that match a certain pattern, like when deleting all pods related transients.

If you have an alternative you'd like to suggest for our use of wp_cache_flush in multisite environments, we're definitely open to improving it.

**Comment by sc0ttkclark** [comment]
All of the wp_cache_flush() calls in PodsView were added 3 years ago

**Comment by sc0ttkclark** [comment]
We flush all of the Pods cache when you add/edit/delete a pod, on activation, on deactivation, or on an upgrade (2.6.7 > 2.6.8 for instance).

**Comment by svandragt** [comment]
Thanks scott. We're running 2.6.7. When we deploy 2.6.8 (nothing else) we're seeing the issue appear. Perhaps there's an edge condition - If you wouldn't mind keeping this open I will gather more data and stacktraces and get back to you.

**Comment by svandragt** [comment]
Update, it turns out what we were actually seeing was an wp alloptions concurrency bug /  race condition during busier traffic periods. We suspect this is caused by another plugin, cron or long running requests. See https://core.trac.wordpress.org/ticket/31245 for WordPress core work on this.

This caused a back and forth between the version numbers reported for PODS (amongst other things). Whenever the version number changed the upgrade process kicks including flushing the object cache.

We developed a plugin to report the difference between the cached options and the database options and then clear out the object cache record; After doing this PODS updated correctly.

**Comment by pglewis** [comment]
Bonus points for the "fun" that is debugging caching gremlins.  I assume we can close this issue out?
