### ISSUE TITLE
Prototype view updates from JSON for 2.7 add new

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4020]
Related: #3309

Part of #3364

**Comment by pglewis** [comment]
No PR involved, this is just an example of returning the data and refreshing the view.  

https://github.com/pods-framework/pods/commit/0a02fbc

**Comment by sc0ttkclark** [comment]
I've got everything in there for posts, terms, users, and pod forms. The only thing remaining there is to handle the JS saving process that terms have which is unique to any of the others. In the future there will be more JS things in core so it'll have to be less than hacky.

That's all that's left though.

**Comment by sc0ttkclark** [comment]
Edit links can be used for modals too now, just need to flesh out onChildviewEditClick in _src/pick/pick.js and add the event handler on the edit links in that modal.

**Comment by sc0ttkclark** [comment]
Needs PR and merge into 2.7

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/tree/feature/4020-view-update-prototype
