### ISSUE TITLE
Pods  sortby auto-appends columns

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#4021]
```
$analytic_day = pods( 'analytic_day', [
							'select'  => [ 't.post_date', 'd.sessions' ],
							'where'   => [
								'project.ID' => get_the_ID(),
								[
									'key'     => 'post_date',
									'value'   => ( new DateTime() )->modify( '-30 days' )->format( 'Y-m-d H:i:s' ),
									'compare' => '>=',
								],
							],
							'orderby' => 'post_date ASC',
						] );
```
`orderby` should only be `post_date ASC`, and not auto append menu order, post title, post status ETC as it can potentially luck with the results.

**Comment by pglewis** [comment]
If I'm following you correctly, adding more orderby shouldn't affect the results unless there are multiple results with the same date.  Without those secondary orderbys  the results would just be arbitrary for items with the same date.  

I can see an argument both ways: it removes full control of the built SQL this way, but no secondary sorting by default isn't useful, either.

**Comment by pcfreak30** [comment]
@pglewis you are correct.

**Comment by pglewis** [comment]
Is there a use case here, something it's messing up?  Or is this something we can close?

**Comment by pcfreak30** [comment]
@pglewis not following? I just stated the problem and use case. I want to sort by X columns but not let any the columns be magically injected and potentially tamper with the sorting. As of right now the results are fine but I see potential for error, so it should be dealt with proactively.

**Comment by sc0ttkclark** [comment]
This is already possible by passing in the `'strict' => true` parameter in your `find()`

However, when strict mode is enabled for `find()`, **NO DEFAULT** is set/merged for `'join'`, `'where'`, or `'orderby'`.

https://github.com/pods-framework/pods/blob/2.x/classes/PodsData.php#L848
https://github.com/pods-framework/pods/blob/2.x/classes/PodsData.php#L856
https://github.com/pods-framework/pods/blob/2.x/classes/PodsData.php#L914
