### ISSUE TITLE
PHP max_input_vars limitation on Pods Edit pages

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4022]
When you have a Pod with a LOT of fields you can encounter a `max_input_vars` limitation.
WP had the same problem with the menu admin pages and fixed by adding all post fields to one large JSON serialized string that is send as first. Maybe we can do a similar solution?

Related: https://core.trac.wordpress.org/ticket/14134

**Comment by sc0ttkclark** [comment]
This will be easier to approach with full DFV coverage.

**Comment by JoryHogeveen** [comment]
With the i18n component merged this is quickly starts to be a major issue with a few fields when you have some languages enabled. It will add fields exponentionally.

Two options:
- Do not pass fields that should be excluded (dependencies -> set field to `disabled`)
- Pass as JSON string (first parameter)

**Comment by JoryHogeveen** [comment]
After doing some more research I see that a json formatted string is already send though somehow not all values are stored correctly when having a lot of fields and languages. 
Wondering if a single very very large json variable as parameter could be stripped as well somehow/somewhere..

**Comment by sc0ttkclark** [comment]
Resolved with new Pods editor in DFV/React
