### ISSUE TITLE
Change name of project

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#4024]
I know it will sound funny to you. It sounds to me too.

"Pods" is very generic and making huge problems searching for tutorials, snippets, solutions, etc on Google.
I guess I could add "wordpress" to the keywords, but not on any page where "pods" is indexed "wordpress" keyword is mentioned. So it misses many good things.

Same is with "Shortcake" project. Something one doesnt think about when starting a project. Searching on search engines.

All I know I have hell of the time to find solutions to my Pods problems on Google. 
For instance ACF or "advanced custom fileds" is not so generic and I find solution to all problems very quickly.

OK now, do you still laugh ? :)

**Comment by StaggerLeee** [comment]
Will just make isssue closed. it is not real issue as others, so it it not right to influence percentage solved/unsolved. Just to be here for you, as info.

**Comment by sc0ttkclark** [comment]
Being that we are quickly approaching a project age of 9 years old, I don't think a project name change would be in the cards for us. And Advanced Content Types wouldn't accurately represent what Pods does nowadays. If we want to improve the project visibility, we'll need to continue to work on our onboarding process for new users and developers, improve documentation, add the features coming in 2.7-3.0, and keep our demo video up to date each major release.

**Comment by StaggerLeee** [comment]
Hi Scott.
Very understandable.

I have seen somewhere new documentation URL from pods.io (unfinished and hidden).
Can you put it (URL) on Wiki here ?

**Comment by sc0ttkclark** [comment]
Hop into our Slack #core-docs channel to join the beta group who has been using and providing feedback about the docs.
