### ISSUE TITLE
Pods::Duplicate() doesn't work

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4025]
When attempting to duplicate an item using `Pods::duplicate` method(), no item is duplicated and the original Pod item is returned.

http://pods.io/docs/code/pods/duplicate/

To reproduce, do:

```
$new_pod = Pods( $someID );
$dupe_id = $new_pod->duplicate();
if( $dupe_id == someID ){
echo('not duplicated');
}
```

**Comment by lougreenwood** [comment]
Looks like #3238 may be related...?

**Comment by sc0ttkclark** [comment]
@lougreenwood is this an issue only with WP objects? This doesn't happen on ACT's right?

**Comment by sc0ttkclark** [comment]
Looks like a duplicate of #3238 unless this doesn't work for ACTs too.

**Comment by pglewis** [comment]
Yeah, looks like a duplicate.  I left the other one open as I was going to copy over the extra information there and didn't get to it yet.
