### ISSUE TITLE
Polylang & Fetch

### ISSUE THREAD

**Issue by raptor235** [pods-framework/pods#4035]
When doing a simple fetch of custom taxonomies I seem to be getting the full list of taxonomies no matter what language I'm in...

$product_categories = pods( 'product_category', array( 'limit' => -1)

Are we supposed to pass in a lang param somehow or is the query supposed to be intercepted at the db abstraction layer?

**Comment by JoryHogeveen** [comment]
Just did a quick test and my return is filtered by language correctly (both on front and admin).
Could you give me more insights in your config?

Where did you test this code for example?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
