### ISSUE TITLE
Pods extended User cannot save first_name, last_name

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4041]
When extending wp_user with pods, $pod->save() does not save the first_name or last_name values.

```
$pod->save([
    'first_name' => 'new_fn',
    'last_name' => 'new_ln',
]);
```

Doesn't result in a saved user first/last name.

**Comment by sc0ttkclark** [comment]
@lougreenwood what happens to $pod above this?

**Comment by jimtrue** [comment]
Related #1890 and #3430

**Comment by jimtrue** [comment]
In addition @sc0ttkclark for your reference, these fields also are not available in the magic tag syntax/template reference, which probably means we're not 'presenting' them.

**Comment by lougreenwood** [comment]
@sc0ttkclark 

> when do you call that save() and on what page?
save() is called by a hook which is triggered when saving another Pod (let's called it `related_pod`). I have the same issue when saving `related_pod` via wp-admin or front-end.

> what is done with `$pod` above your `->save()` call?
I have a wrapper which I use as an interface to updating a pod, this is the code which my internal code calls to update the field:

```
    /**
     * Update an existing record.
     * @param  int      $id       ID of record to be updated.
     * @param  array  $fields Record fields & values to be saved.
     */
    public static function update( int $id, array $fields ){
        // Initalise the pod for this controller's associated model
        $pod = \pods( static::SLUG );

        // Update the entry
        return $pod->save( $fields, null, $id );
    }
```

**Comment by sc0ttkclark** [comment]
My test code works for this. So it looks like there's another problem going on here. Have you extended the Users pod yet? You need to extend that wp object with Pods first before you can start saving fields to it with pods().

**Comment by lougreenwood** [comment]
@sc0ttkclark Yep, Users has been extended.

I have an idea for how to reproduce, we can discuss it in Slack as some details are private.

**Comment by rosalynpoort** [comment]
I'm having the same issue, when i display a form for user pod (extended wp user) the first name, last name, description fields don't show.
`$mypod = pods( 'user' );
echo $mypod->form();`

**Comment by sc0ttkclark** [comment]
@rosalynpoort please create a new issue for that, this is a separate issue about saving, yours is an issue about the form fields shown by default for users.

**Comment by louisgan** [comment]
Could be the new updates on W3 Total Cache causing the issue or because of certain cache configuration. I cleared cache and disabled W3TC plugin and this issue went away.

**Comment by louisgan** [comment]
Ah could be related to issue #4005 when using redis

**Comment by lougreenwood** [comment]
@sc0ttkclark 

> My test code works for this. So it looks like there's another problem going on here. Have you extended the Users pod yet? You need to extend that wp object with Pods first before you can start saving fields to it with pods().

Do you still have the test code? Curious to see what field name you use for first name & last name...

Just came up against this bug again

**Comment by sc0ttkclark** [comment]
Took me long enough, finally debugged this deep enough to find the issue!
