### ISSUE TITLE
website field - output format set to without protocol - needs protocol for saving

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4050]
if a website field is set to format:   example.com  - you need to manually add the protocol (https://)  each time you edit the entry - else it wont safe as it is output without the protocol ....

**Comment by quasel** [comment]
![grafik](https://cloud.githubusercontent.com/assets/9464217/23832662/9dd48430-0739-11e7-8e18-4d9209e2eda3.png)

![grafik](https://cloud.githubusercontent.com/assets/9464217/23832667/b4a607f6-0739-11e7-8682-a7c554a90ff7.png)

**Comment by pglewis** [comment]
Is this pre-existing in 2.x?  I have a large axe at the ready.

**Comment by pglewis** [comment]
Possible suspect from digging on #4545: https://github.com/pods-framework/pods/commit/013fb6e

**Comment by pglewis** [comment]
#4583 appears to fix this for me

**Comment by quasel** [comment]
no idea still broken on the site after switching to the branch :/

**Comment by pglewis** [comment]
Sorry, I commented on the wrong issue :o

**Comment by quasel** [comment]
Okay it's HTML5 related - needs:
pattern=[] regex - https://www.w3schools.com/tags/att_input_pattern.asp 
Already broken in 2.x

**Comment by pglewis** [comment]
Works for me with the latest commits
