### ISSUE TITLE
Pods - Custom Post Type, Field - File/Image/Video title does not update

### ISSUE THREAD

**Issue by craiglondon** [pods-framework/pods#4062]
I am unable to update the title of an item that is in the media library.

I am using Pods, custom post type.  Using storage meta.

There is two items highlighted in the screenshot below, they do not update.  They are using the multiple attachments.   Then I was working with Jim True on this issue and we tested it on the two images, they are single attachments, same issue, cannot update the title via the Pod.

![image](https://cloud.githubusercontent.com/assets/3833140/24047825/48be772c-0afd-11e7-8798-1cea21682d57.png)

![image](https://cloud.githubusercontent.com/assets/3833140/24047839/575c89f4-0afd-11e7-8645-1363a3e28615.png)

![image](https://cloud.githubusercontent.com/assets/3833140/24047843/5d1c08c4-0afd-11e7-9752-9be74e322926.png)

`Debug Information

WordPress Version: 4.7.3

PHP Version: 5.3.29

MySQL Version: 5.6.28

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: No
WPDB Prefix: wpru_

WP Multisite Mode: No

WP Memory Limit: 128M

Pods Network-Wide Activated: No

Pods Install Location: /home/CLIENTREDACTED/public_html/CLIENTREDACTED/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Child Theme for Divi

Currently Active Plugins:

Elegant Themes Updater: 1.2
Insert PHP: 1.3
Inventory Search:
Loginizer: 1.3.4
Max Mega Menu: 2.3.5
Max Mega Menu - Pro Addon: 1.6.2.1
Menu Duplicator: 1.0
Noindex Pages: 1.0.1
Pods - Custom Content Types and Fields: 2.6.8
Quick Page/Post Redirect Plugin: 5.1.8
Salesforce Sync:
WordPress Importer: 0.6.3
WordPress Twitter Bootstrap CSS: 3.3.7-1
WP Job Manager: 1.25.3`

**Comment by craiglondon** [comment]
I did a bit more testing with Jim.

If I edit the title for Images or the PDFS in the Media Library, the change is reflected in the Pod, but you cannot update the text within the Pod even though the setting "Title editable" is enabled.

![image](https://cloud.githubusercontent.com/assets/3833140/24048457/54a2c3e8-0aff-11e7-93b5-ea7ec0eb6f20.png)


![image](https://cloud.githubusercontent.com/assets/3833140/24048440/4870b54e-0aff-11e7-89d9-c96c83f12e24.png)
![image](https://cloud.githubusercontent.com/assets/3833140/24048447/4c8cfd9a-0aff-11e7-9b74-296925dba154.png)

**Comment by veisis** [comment]
Same issue for me.

Debug Information

WordPress Version: 4.7.3
PHP Version: 5.4.45
MySQL Version: 10.1.18
Server Software: Apache
Your User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Session Save Path: /tmp
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:
    Apc: No
    Memcached: No
    OPcache: No
    Redis: No
Object Cache:
    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 256M
Pods Network-Wide Activated: No
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No

**Comment by jimtrue** [comment]
#4112 This was uncovered as broken in 2.6.8, appeared fixed in 2.6.9 and re-opened as still broken. Closing this issue as Duplicate to #4112 Please follow that issue for eventual solution.
