### ISSUE TITLE
Revisionary plugin not working properly with Pods

### ISSUE THREAD

**Issue by HeidiEllis** [pods-framework/pods#4063]
Word of Caution: This issue involves Revisionary which hasn't been updated in two years. ISo far I haven't been able to find another plugin that will do what I want. 

I have a "Learning Material" Pod with fields for Overview, Link to Material, and Source.  I am trying to set up a moderated editing process using the Ultimate Member and Revisionary plugin.  Currently, Revisors are able to make changes to the fields in th Learning Material Pod. They are able to click the "Submit Revision" and the proper people are notified. However when the revision is approved by an editor or admin, the changes to the fields aren't applied. Changes are correctly incorporated to regular posts and pages.  In the Advanced Options tab of the Learning Material, the Supports/Revisions option is checked. 

To reproduce the issue (starting as admin):
1. Install Ultimate Member and Revisionary plugins
2. Create a "Revisor" user type.  You may have to provide edit privileges to Posts in user permissions.
3. Create a Pods type with fields. 
4. Create a couple of instances of the Pods type.
5. Login as Revisor
6.  Navigate to one of the instances of a Pod type. 
7. Make a change to one of the fields in the instance.
8. Click "Submit Revision" 
9. Login as admin and edit the instance of the Pod type. 
10. Click "Publish"
At this point, the change in the field does not appear. The Pods instance is unchanged.

**Comment by quasel** [comment]
well dealing with an outdated not maintained plugin is always hard :/ did you solve it? 
Sorry for the late reply, feel free to comment if you still have questions!
