### ISSUE TITLE
Pods post type not showing in get_post_types

### ISSUE THREAD

**Issue by faysalmahamud** [pods-framework/pods#4064]
I am building a custom plugin. I tried to get a result using get_post_types() but this not showing pods related post type.

result: Array ( [post] => post [page] => page [attachment] => attachment)
 

I found a solution, given below. 

public $post_types = array();
add_action('admin_init',array($this,'get_post_types'));
public static function get_post_types(){
      $all_post_types = get_post_types( array( 'public' => true ), 'names' );
      unset($post_types['attachment']);
    $this->post_types = $all_post_types;
  }
result: Array ( [post] => post [page] => page [attachment] => attachment [newpostype] => newpostype [test] => test )

But now the problem is when I want to show this the result in the other class or templates it reset
and shows empty array.
ex: $test->post_types; // array()

Can you tell me, how can I show pods with others post type anywhere in the sites?
Thanks

**Comment by intelliweb** [comment]
This is related to [this issue](https://github.com/pods-framework/pods/issues/4115).

@faysalmahamud My notes there might help you find a temporary workaround.

**Comment by quasel** [comment]
same as #4115
