### ISSUE TITLE
Improvement: track changed fields would also track Wordpress field changes

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4072]
I'm currently to write an afterSave() method which performs some action upon a pods::save() is completing.

My specific use case is to track that a post title was changed. However, I have other scenarios where I need to track whether pods-specific custom fields have changed - with this in mind I'm keen to work with a single, generic interface for tracking changes (via Pods), rather than splitting into 2 methods for Pods & WP.

It would be very useful if track changed fields were extended to include WP native post fields, or at a minimum these fields:

* post_title
* post_date
* post_author
* post_excerpt
* featured_image

Is this something that's possible & within scope of the project's aims?

**Comment by sc0ttkclark** [comment]
This is possible, but the code to do it would be somewhat hacky, but still possible.

**Comment by sc0ttkclark** [comment]
Fixed via #4187
