### ISSUE TITLE
Duplicate Custom Field

### ISSUE THREAD

**Issue by TeamSDA** [pods-framework/pods#4073]
**Hello Support Team...** May have run into a bug. Seems that when a pods field is displayed in custom post type edit page that the WordPress custom fields section creates a duplicate. See screenshot in the Pods forum thread, link below.

Kind Regards,
Dave

Post: March 20, 2017 at 2:00 pm
http://pods.io/forums/topic/custom-fields-name-field-being-populated-after-install-cpt-made/

**Comment by quasel** [comment]
That's not a bug - that's just how Wordpress works - all Information regarding it can be found in the mentioned blog post. 

- Pods (in default settings) stores all fields (the WordPress way)  as https://codex.wordpress.org/Custom_Fields
- Pods Provides an improved interface which enforces the configured field settings
- The Native WordPress Interface (which is per default hidden) is not touched by Pods (the WordPress Way ;) ) 
- All fine! and if you don't want the fields to show up just follow @jimtrue suggestion - https://codex.wordpress.org/Function_Reference/add_post_meta ( the part about hidden custom fields)

While this might be an UX issue to think about it's currently just reflecting how WordPress works and the Pods Team sticks to default WordPress stuff as close as possible!

**Comment by TeamSDA** [comment]
**Thanks...** Appreciate you explaining this and providing the WordPress knowledge resources.
