### ISSUE TITLE
Field of type date is rendered with jQuery date picker despite HTML5 field enabled

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods#4079]
I have custom field of type Date which has `Enable HTML5 input field?`option enabled. While the native browser date picker shows up in WP Admin view, on the website front end, the jQuery date picker is rendered instead.

This is my template code to render the field:

```
$userPod = pods('user', get_current_user_id());
$fieldsToShow = array(
  'sxd_birthday',
);
echo $userPod->form( $fieldsToShow, 'Save Changes', '/my-profile?success' );
```

Pod Admin Setting:

![screen-pods-admin-view](https://cloud.githubusercontent.com/assets/8035912/24259226/913e2932-0ff0-11e7-8d50-43b2a45b9da3.png)

Admin Screen:

![screen-admin-view](https://cloud.githubusercontent.com/assets/8035912/24259240/9c4b9774-0ff0-11e7-9120-5433ec275ee9.png)

Website View:

![screen-website-view](https://cloud.githubusercontent.com/assets/8035912/24259252/a4463d30-0ff0-11e7-8037-2c6c7dbcc52a.png)

**Comment by quasel** [comment]
works for me in the default UI… but this will change with the new DFV stuff anyway! 
Sorry for the late reply, feel free to comment if you still have questions!
