### ISSUE TITLE
Support 'wildcard-on' field dependencies

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4080]
Needed for #4039 

PR: #4081

**Comment by JoryHogeveen** [comment]
@pglewis How does this option actually function? Are there any docs/comments?

**Comment by pglewis** [comment]
Missed this question apparently, @JoryHogeveen 

Array of regexes: 

https://github.com/pods-framework/pods/blob/9f48159/classes/fields/pick.php?ts=4#L178
