### ISSUE TITLE
CSS class 'hidden' applied to field type file list items in WP Admin Pods form

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods#4102]
We have a Pods form in WP Admin with a field of type file (multiple files allowed).

If we upload files, a CSS class `hidden` will be added to each list item representing an uploaded file, but the last one. This doesn't do any harm in standard WP environments. However, if custom Admin styles are used and well-known frameworks like Bootstrap are included, it's pretty likely, that CSS settings like

`.hidden{display: none; }`

prevent uploaded files from being shown in the field's list. 

![screenshot-pods-admin-ui](https://cloud.githubusercontent.com/assets/8035912/24749855/eaba4e08-1ac4-11e7-8662-9fb2aecd0971.jpg)

**Comment by JoryHogeveen** [comment]
Hi @Digitale-Substanz 
Thank you for your bug report. We are aware of this and already have it fixed in Pods 2.7.
PR: #3968
Similar issues: #2578, #2556

**Comment by JoryHogeveen** [comment]
Fixed in #3968
