### ISSUE TITLE
Magic code for displaying all feilds from pods name

### ISSUE THREAD

**Issue by Kayapati** [pods-framework/pods#4113]
I have created pods  'Talent' and added 10-15 custom fields.

I have created Pods templates like “talent list” and “Talent detailed” also added all fields individually in detailed page using magic codes, here in detailed page I need to display all fields from pods name 'Talent'  I do not want to add all fields name separately. I want to display the details page what ever fields the Talent pods having, because  my clients need to add extra fields based on their needs,  and they do not know how to add them in detailed page if they add several fields.

Right now this template system work very well for those who create sites for end clients, I am talking about for those who create premium themes.

Scott I hope you got my point and waiting for your views on this.

Any one can help on this please?

**Comment by quasel** [comment]
that's a tricky thing to do and maybe best done in php where you can get all field's via e.g.  `$field = $pod->fields( 'field_name' ); ` and output them… 

Sorry for the late reply, feel free to comment if you still have questions!
