### ISSUE TITLE
Issue /w uploading files.

### ISSUE THREAD

**Issue by raptor235** [pods-framework/pods#4114]
Seems that the UI isn't being drawn for already uploaded file... it shows up after initial upload, gets saved in the db, and on the refresh the UI for that uploaded file isn't there anymore so the user doesn't know if there is a file uploaded already.

Using latest build.

Upload
http://www.flowpress.com/screenshots/Screenshot_2017-04-13_8.32.35.png

DB
http://www.flowpress.com/screenshots/Screenshot_2017-04-13_8.32.48.png

After Saved Refresh
http://www.flowpress.com/screenshots/Screenshot_2017-04-13_8.34.50.png

**Comment by jimtrue** [comment]
I'm not seeing this particular issue locally on latest build version 2.6.8. 

Have you checked for other plugin conflicts first?

**Comment by raptor235** [comment]
Just tracked it down, the conflict is with Polylang Pro... that's a major translation plugin.

**Comment by raptor235** [comment]
It seems like also getting the file in the template is also not working... when I try 

$product_category_pod->field('catalog_pdf')

I get a false result...

If I disable language translations it starts working...

**Comment by raptor235** [comment]
Other fields work fine, it just seems to be the file field type.

**Comment by jimtrue** [comment]
Luckily we have the guy who wrote our PolyLang integration! @JoryHogeveen Have you seen what @raptor235 is describing above?

**Comment by JoryHogeveen** [comment]
I think this is related to media translations.
@raptor235 
Do you have media set as translatable in your Polylang settings?
Polylang Pro should auto-add media translations, could be that it is still returning the incorrect reference or something.
Let me know and I'll do some tests here!

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
