### ISSUE TITLE
Post types registered too late?

### ISSUE THREAD

**Issue by intelliweb** [pods-framework/pods#4115]
Another plugin is using the function `get_post_types` to pull a list of post types but none of the custom post types created via Pods are returned. CPTs from other plugins appear properly but not Pods. I've replicated/simplified the function from that plugin in my own functions.php for testing and confirmed that Pods CPTs are not returned:
```php
add_action( 'init', 'custom_get_post_types' );
function custom_get_post_types() {
	$post_types = get_post_types( array( 'public' => true ), 'objects' );
	foreach( $post_types as $post_type ) {
		echo $post_type->name . '<br>';
	}
}
```
It appears Pods is registering post types after the `init` action and thus too late to be included in the above function. Using a later action, such as `wp_loaded` works properly and Pods CPTs are returned as they should be. Should Pods be registering post types earlier to avoid this issue?

**Comment by sc0ttkclark** [comment]
Have you tried using a higher priority in your init hook?

**Comment by slawekniewiadomski** [comment]
Guys, im creating a widget plugin for siteorigins page builder and i have to list all cpt's created by pods. I've tried adding custom get_post_types with various priorities, and all i can get to show is built-in types and _pods_templates, but not any of my custom added post types. Is there any workaround for this, or i have to hardcode all cpt's into theme?

**Comment by sc0ttkclark** [comment]
@slawekniewiadomski can you provide some example of the code you're using and the hooks?

**Comment by slawekniewiadomski** [comment]
Fast reply, thanks!
theme's **functions.php:**
``` php
function atm_get_post_types() {
  $post_types = get_post_types(array(), 'objects');
  $return_arr = array();
  foreach ($post_types as $post_type) {
    $return_arr[$post_type->name] = $post_type->label;
  }
  return $return_arr;
}
add_action('wp_loaded', 'atm_get_post_types', 20);
```
in class extending SiteOrigin_Widget:
```php
public function get_widget_form() {
  $form_options = array(
    'posts_source' => array(
      'type'        => 'select',
      'label'       => __('Żródło', $this->text_domain),
      'description' => __('Wybierz grupę postów które mają być wyświetlone'),
      'options'     => $this->get_post_types() // <--- There i i populate a select field
  );
}
```
In same class:
```php
  private function get_post_types(){
    $wp_post_types = atm_get_post_types();
    // There i modify this array, but for test purposes i simplified it (still same effect)
    return $wp_post_types;
}
```
And what i get in dropdown:
```php
Array ( 
  [post] => Wpisy 
  [page] => Strony 
  [attachment] => Media 
  [revision] => Starsze wersje 
  [nav_menu_item] => Elementy menu nawigacyjnego 
  [custom_css] => Własny CSS 
  [customize_changeset] => Zestawy zmian 
  [_pods_template] => Pod Templates 
)
```

**Comment by sc0ttkclark** [comment]
You can't depend on the hook wp_loaded to get post types and taxonomies registered by plugins and themes. You'll need to hook in somewhere after init priority 12 to be sure they've already been registered.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! Guess it's solved 🥇
