### ISSUE TITLE
Feature request - Ability to have field for country/region/city selection

### ISSUE THREAD

**Issue by ddon** [pods-framework/pods#4116]
Currently Pods support "Countries" and "US States" fields, but what would be great is to have "Country", "Region (State/Province/etc..)" and "City" fields, and they should of course work together, that Region should display only regions for a currently selected country, and city field should display cities for given region in given country. 

Of course this database of countries/regions/cities is constantly changing and updating, so how to deal with this correctly I don't know. But there are free databases available, which potentially can be installed or may be there are service which we can use without downloading and installing on the machine where wordpress is running.

**Comment by JoryHogeveen** [comment]
I think the address field would be related and might provide a solution through the Google Maps API: #3634

Creating an actual "city" field that will display cities based on the country and province would be nearly improssible in terms of performance.

**Comment by sc0ttkclark** [comment]
Closing in favor of https://github.com/pods-framework/pods/issues/657
