### ISSUE TITLE
Use select2/autocomplete for List View's select from existing

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4126]
Main 2.7 issue: #3364 
PR: #4127

- [x] AJAX select text (make sure it supports i18n)
- [x] Empty list text
- [x] Selection limit  [fixed for autocomplete but not List View yet.  The list view's autocomplete field only allows one selection at a time, so `maximumSelectionLength` can't enforce the limit]
- [x] Placeholder text
- [x] Normalize how we deal with the order of items in both the autocomplete and view lists (see also: #4053)
- [x] AJAX support

**Comment by pglewis** [comment]
Placeholder text and i18n for it?

**Comment by pglewis** [comment]
We should also consider the behavior and text when there are no items to select from (occurs with no items and when all items have been selected).

**Comment by jimtrue** [comment]
"No Soup for You!" ? (wink)

**Comment by pglewis** [comment]
I think my vote from Jim's placeholder text suggestions would be "Search [pods name]"

**Comment by jimtrue** [comment]
I agree, it's the most logical.

**Comment by quasel** [comment]
May extend it to "Search [] to add" or something similar because if a "user" sees the field he might have no idea why to search :D
