### ISSUE TITLE
SQL Error when updating existing field

### ISSUE THREAD

**Issue by raptor235** [pods-framework/pods#4131]
When trying to update an existing file field I get a SQL error alert

Error: Database Error; SQL: UPDATE `wp_termmeta` AS `m`
                LEFT JOIN `wp_terms` AS `t`
                    ON `t`.`term_id` = `m`.`term_id`
                SET
                    `m`.`meta_key` = 'image'
                WHERE
                    `m`.`meta_key` = 'thumbnail'
             AND `t`.`taxonomy` = 'catalog'; Response: Unknown column 't.taxonomy' in 'where clause'

http://www.flowpress.com/screenshots/Screenshot_2017-04-26_11.25.38.png

**Comment by raptor235** [comment]
Latest ver of wp and pods

**Comment by Gremlin67** [comment]
Hello,

I am new here and I have encountered the exact same problem. It seems that clicking twice on the "Save Pod" button eventually works :  I get the error the first time, not the second time.
This happens for every single field, so if I modify three fields, I have to click six times to save the pod...

**Comment by jimtrue** [comment]
@raptor235 and @Gremlin67 it might help if you provide your Debug information, under Pods Admin, Settings

**Comment by Gremlin67** [comment]
Thank you for your answer! Here is my debug info, sorry : 

> Information de débuggage
> 
> WordPress Version: 4.8.1
> 
> PHP Version: 7.1.7
> 
> MySQL Version: 5.5.5
> 
> Server Software: Apache/2.4.26 (Unix) OpenSSL/1.0.2l PHP/7.1.7 mod_perl/2.0.8-dev Perl/v5.16.3
> 
> Your User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
> 
> Session Save Path: /opt/lampp/temp/
> 
> Session Save Path Exists: Yes
> 
> Session Save Path Writeable: Yes
> 
> Session Max Lifetime: 1440
> 
> Opcode Cache:
> 
>     Apc: No
>     Memcached: No
>     OPcache: No
>     Redis: No
> 
> Object Cache:
> 
>     APC: No
>     APCu: No
>     Memcache: No
>     Memcached: No
>     Redis: No
> 
> WPDB Prefix: wp_
> 
> WP Multisite Mode: No
> 
> WP Memory Limit: 40M
> 
> Pods Network-Wide Activated: No
> 
> Pods Install Location: /opt/lampp/htdocs/www/wp-content/plugins/pods/
> 
> Pods Tableless Mode Activated: No
> 
> Pods Light Mode Activated: No
> 
> Currently Active Theme: Twenty Seventeen
> 
> Currently Active Plugins:
> 
>     Pods - Custom Content Types and Fields: 2.6.10
>     WordPress Importer: 0.6.3

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
