### ISSUE TITLE
feature request => please support group field

### ISSUE THREAD

**Issue by rolldone** [pods-framework/pods#4154]
like CPT, maybe pods adding group field too 

thanks..

**Comment by quasel** [comment]
if you request feature it's always helpful to bee a bit more descriptive  - that said there is a function to group your field's in the WordPress Admin - currently there is no UI for it but it can be done with Code: http://pods.io/docs/code/general-functions/pods-group-add/

**Comment by jimtrue** [comment]
@rolldone See #799 Closing this in favor of that issue. This is being worked on the road map as part of 2.8.
