### ISSUE TITLE
Enhancement: Let Pods use any WP object by default

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4174]
Currently if you want Pods Power for an existing WP Object, for example Posts, you'll have to extend it.
Why not support it by default and only require extending if you want to add fields for example?

**Comment by garypaul** [comment]
Good idea. Requiring you to extend a Post type is a barrier to entry for many. Also, this would benefit users who install a plugin like WooCommerce or Sensei and get a list of Post types, but are afraid of extending them for fear of breaking them.

While a dev knows that is unlikely when they understand what Pods does, there is still this thought that runs through your mind... "is making a *Pod* reversible? If I extend the `Product` posttype to add this field that isn't in WooCommerce and later find out that the field DOES exist, there's another solution... will removing the `Product` Pod delete my data? Will it wreck my site?

I think allowing a Pod to use an unmodified Post Type in a relationship field could be very powerful and helpful.

**Comment by sc0ttkclark** [comment]
Pods 2.8 with the PodsObject rework will support any WP object by code itself. You'd still have to register the fields you want but it would be able to work with any WP object (base fields and custom fields) just fine.

**Comment by jimtrue** [comment]
Definitely second'ing this one; never realized that using the default taxonomy category/tags can't be 'traversed' in the templates without extending them first.

Would this also open up the Users connection to Author for automatic traversal as well?

**Comment by sc0ttkclark** [comment]
Anyone want to test and see if this is working properly in Pods 2.8?

**Comment by lkraav** [comment]
> Anyone want to test and see if this is working properly in Pods 2.8?

I don't get the opening issue text.

What's would the test process be here?

**Comment by sc0ttkclark** [comment]
To test this, you could use the following code. Expect two `true` booleans to output from the results. Basically, if a Pod does not exist, it should now fallback to checking if the pod is a valid WP object and auto-setup itself!

```php
add_action( 'init', static function() {
	register_post_type( 'my_test_cpt' );

	$pod = pods( 'my_test_cpt' );

	var_dump( $pod->valid() );

	register_taxonomy( 'my_test_tax', 'post' );

	$pod = pods( 'my_test_tax' );

	var_dump( $pod->valid() );

	die();
} );
```

The functionality is now in `release/2.8`!
