### ISSUE TITLE
Invalid AJAX error with frontend form + settings pod

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4181]
When using a Pods form on the front-end of a custom setting page I get issues with the AJAX calls. It looks like it's called twice, one successful, one not.
So while the Pod is actually saving, it doesn't run any callbacks and triggers an ugly alert.

## AJAX call 1:
**Initial save button trigger**
```
Request URL: http://domain/wp-admin/admin-ajax.php?pods_ajax=1&action=pods_admin
Request Method: POST
Status Code: 302 Moved Temporarily
```
**postdata:**
```
action: pods_admin
method: process_form
do: save
_pods_nonce: 479bda4f15
_pods_pod: website_settings
_pods_id: 134
_pods_uri: b13d5f934b
_pods_form: blogname,blogdescription,site_icon,header_image
_pods_location: /dev/
pods_field_blogname: Test titel 123
pods_field_blogdescription: Desc
```
**No response data**

## AJAX call 2:
**Get's triggered right after the first, not sure why/where**
```
Request URL: http://domain/wp-admin/admin-ajax.php?pods_ajax=1&action=pods_admin&success=1
Request Method: GET
Status Code: 200 OK
```
**postdata:**
```
pods_ajax: 1
action: pods_admin
success: 1
```
**Response data**
```<e>Invalid AJAX request</e>```

**Comment by JoryHogeveen** [comment]
Some extra info.
The first AJAX call isn't even run through `PodsAdmin::admin_ajax()`

**Comment by pglewis** [comment]
Current release?  2.x?  2.7?

**Comment by JoryHogeveen** [comment]
Current release!

**Comment by pglewis** [comment]
Just that pang of wondering if I had introduced it :)

**Comment by JoryHogeveen** [comment]
Nah, this is something else..

**Comment by JoryHogeveen** [comment]
Got it, it's an issue in `PodsAPI::process_form()`. I'll dive into it a.s.a.p.
