### ISSUE TITLE
Determine min PHP version for 2.7

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4194]
Discuss

**Comment by sc0ttkclark** [comment]
We upped to PHP 5.3+ (Pods 2.6.x and below supported PHP 5.2+). I think that's all we can do right now, let's inch it up as we're able to and try to focus on PHP 5.6 for Pods 3.0 if things continue to progress with people upgrading their PHP overall.

**Comment by Ramoonus** [comment]
do we have statistics?
