### ISSUE TITLE
DFV: Clean up all selection limit enforcement

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4197]
PR: #4218 

[Edit: This has become a generic "sweep up selection limits" issue]
- [x] I don't think there's a way to select _no_ items once there has been a selection (er, whoops) [ctrl-click here... it's just whatever standard multiselect behavior is for the platform]
- [x] We need a plan for how to handle consecutive selections that go over the limit (click-select).  This may need some discussion
- [x] Disable "add new" whenever selection limit is reached
- [x] Disable checkboxes to enforce limit, using the same approach as multiselect
- [x] Make sure all views still respect unlimited selection (limit = 0)

**Comment by pglewis** [comment]
I'm patching this in #4127 due to some helper functions there that haven't made their way into 2.7

**Comment by pglewis** [comment]
Checkboxes should be fixed in the feature/4126 branch

For multiselect, I think I'd prefer to disable all unselected items once you reach the selection limit.  It's a small thing, but I really don't like the flash of a new item being selected then immediately unselected when it's handled in the change event.

**Comment by pglewis** [comment]
A couple different ways we could handle Add New at first blush:

- Disable add new button if at selection limit
- Allow add new but don't select it

**Comment by pglewis** [comment]
Handy package to test various relationship views.  All the relationships are set to WordPress Pages, simply because that's where I already had a dozen or so test records.  

https://gist.github.com/pglewis/b15b71db343ecb19df8efae6c275b0a5

**Comment by pglewis** [comment]
> A couple different ways we could handle Add New at first blush:
> 
> Disable add new button if at selection limit
> Allow add new but don't select it

@sc0ttkclark: probably an executive decision on how to handle this one

**Comment by sc0ttkclark** [comment]
An idea -- disable add new button at selection limit but show some sort of text saying "you have reached the limit, remove items to select more"?

**Comment by pglewis** [comment]
That'll go hand in hand with the "Come up with a UI indicator that will explain why the UI isn't letting you select more items" task item.  We'll need that even if they don't allow add new on the field.

**Comment by pglewis** [comment]
> My thinking to this point is to have a message that the field is limited to N items and style that to red/alert whenever you're actually at the limit.

@JoryHogeveen: and brainstorming / placement ideas in that direction?

**Comment by jimtrue** [comment]
![screenshot 2017-05-23 12 24 59](https://cloud.githubusercontent.com/assets/3052875/26364602/deac0fa8-3fb2-11e7-8026-76056ecbb0e4.png)

I actually really like the placement of this and agree the alert message should advise you to remove first to add a new one:
"You can only select # item(s). To add a new one, remove an existing record first."

**Comment by jimtrue** [comment]
Or possible when AT the selection limit, when you disable the add-new button, add a message to the right of the button: You are at the selection limit. To add new records, remove an existing one first.

**Comment by quasel** [comment]
Nicely done - agree with jim - it's alway better to be explicit if possible I would grey out the add new button too once the limit is reached

**Comment by JoryHogeveen** [comment]
Nice one @jimtrue. I'd say that should be fine!

**Comment by sc0ttkclark** [comment]
Messaging either next to add new button or above it in what Jim did an example of but not at top of list, it'd be at bottom of list.

It might also be handy to see `%1$d of %2$d %3$s selected`:

* %1$d: # of items selected
* %2$d: # of items allowed
* %3$s: item vs items

Just an idea though.

**Comment by pglewis** [comment]
> I would grey out the add new button too once the limit is reached

That was definitely the plan all along for that, now way we could leave the button normal without some visual indicator.  

Implemented now and ready to be tested.
