### ISSUE TITLE
Updating Pod Configuration Options doesn't work ( except Basic Tab)

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4202]
PR: #4003 

Current 2.7 branch broke saving of updated Pods Configuration Options in Pods Admin
Only changes to the Basic options Tab are saved.

**Comment by jimtrue** [comment]
Do you have additional details? You mean ALL fields Basic tab?

**Comment by quasel** [comment]
no only changes to the Basic tab are saved - everything else like Additional .. , REST etc are not saved

**Comment by JoryHogeveen** [comment]
I can't reproduce locally, Is the data being send correctly?

**Comment by pglewis** [comment]
Tried clearing Pods cache?  Might be something that direction.

**Comment by pglewis** [comment]
I don't think this is happening across the board.  Can it be boiled-down in a new pod with a single field that can be reproduced?

**Comment by jimtrue** [comment]
New Pod with single field works fine. Clear cache, and edit that field, options beyond 'basic' are not saved.

Editing any existing Additional Options, REST API, etc. changes are not saved.

Clearing cache made no difference.

**Comment by jimtrue** [comment]
Additional investigation: When testing #4175 branch, I'm not experiencing the Field Options saving issue. So that seems isolated to release/2.7 branch

**Comment by JoryHogeveen** [comment]
Weird, now I have the same issue as well.

**Comment by pglewis** [comment]
Definitely introduced in one of the merges in the past couple days.  This was working or I wouldn't have been able to test stuff.

**Comment by pglewis** [comment]
So... who do we get to beat with a rake... :D

**Comment by pglewis** [comment]
Appears to be working at 7352f40

**Comment by pglewis** [comment]
And the winner is: me, in #4028.  Let the rake-beatings begin.

**Comment by pglewis** [comment]
Should be fixed in both 2.x and 2.7 now.

**Comment by quasel** [comment]
works like a charm
