### ISSUE TITLE
CSS changes are hiding scrollbar for multiselect checkboxes and radio buttons

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4219]
https://github.com/pods-framework/pods/commit/28bb1e1

**Comment by JoryHogeveen** [comment]
@pglewis Are you sure you have all changes? It change was made together with a change in the DFV CSS.

**Comment by pglewis** [comment]
I'm testing changes I'm making to the javascript, so I'm definitely not caching anything.

**Comment by pglewis** [comment]
Try the package here: https://github.com/pods-framework/pods/issues/4197#issuecomment-302541914

Get enough records to kick in scroll and look at multi checkbox and regular multi select
