### ISSUE TITLE
Migrate Packages broken in 2.7

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4220]
I only tested a single Pod export thus far (to provide a package for testing various pick views)

**Comment by quasel** [comment]
Can confirm - error msg on import although it seems to have worked using - https://gist.github.com/sc0ttkclark/9ef6a5c092cedf4f69624f19ab7a005f

Works on 2.x - Error on 2.7

**Comment by pglewis** [comment]
Quite possibly DFV related, will know more when I dig in.

**Comment by pglewis** [comment]
This was due to some changes to handle JSON data for add new ACT (which are submitted via AJAX).  

Appears to work for both cases now.
