### ISSUE TITLE
Modal add/edit broken in a "settings pod"

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4240]
PR: #4245

Add New, Add File all "modal" Links seem to have stopped working 
<img width="615" alt="ohne titel" src="https://cloud.githubusercontent.com/assets/9464217/26284589/455a12b0-3e3f-11e7-94aa-2719ae5b9b74.png">

**Comment by quasel** [comment]
and seems the CSS iss of for Multiple images!
![CSS](https://cloud.githubusercontent.com/assets/9464217/26285999/0e6d5f70-3e5b-11e7-9a7e-4ef8200c2747.png)

**Comment by pglewis** [comment]
Probably won't be able to look at it until tonight.  I was gonna ask if you had any console errors, but might just be CSS related?

**Comment by pglewis** [comment]
And if it's CSS: see also #4219.  Might combine CSS fixes into one PR

**Comment by JoryHogeveen** [comment]
The CSS part is indeed fixed in 2.7.

**Comment by pglewis** [comment]
I'm digging into the problem with the modal Iframe.  

I'll try to verify the CSS part after that, though @quasel _was_ testing on 2.7

**Comment by pglewis** [comment]
It's going afoul between when our code triggers `modal.open()` and when WordPress is assembling the underscore template.  Everything looks okay on our side when we hand off control to the WP media modal. The call stack up to the error is exactly the same.  

There's something I've missed while extending `wp.media.view.Frame`.

**Comment by pglewis** [comment]
Add/Edit should be working on the PR branch.  

Let me know what the status of the CSS issue(s) is/are.

**Comment by quasel** [comment]
works for me!

**Comment by pglewis** [comment]
Just holding on @sc0ttkclark to do a quick sanity check on where I've placed the fix and it's merged.

**Comment by sc0ttkclark** [comment]
Fixed via #4245
