### ISSUE TITLE
Encapsulate PodsI18n js object

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4253]
It's now a DFV dependency, so the test side needs access to the object as well.  Needs to be `import`able and encapsulated rather than in the global namespace.  

The global reference has also leaked out into legacy JS, so we need to keep a global reference around until we've refactored all the code that still expects it to be global.

**Comment by pglewis** [comment]
I hadn't taken into account the fact that we link the translation strings to the script via `wp_localize_script`.  I think it's going to be more hassle trying to absorb this one into the build than it would be to just stub out a stand-in for the tests so I'm gonna reluctantly punt on this for now.

**Comment by sc0ttkclark** [comment]
Why not encapsulate it before the script outputs, and have the script localized as the variable `PodsI18n.strings`?

**Comment by sc0ttkclark** [comment]
Sorry, I just realized what I suggested.
