### ISSUE TITLE
Spelling mistake in ui/admin/setup-add.php

### ISSUE THREAD

**Issue by danmaby** [pods-framework/pods#4266]
Lines 186 and 197 of `ui/admin/setup-add.php` have a spelling mistake: `Indentifier` should be`Identifier`

**Comment by sc0ttkclark** [comment]
What do you have against indents? :) Just kidding, thanks for the heads up! We'll get this fixed soon.

**Comment by pglewis** [comment]
PR: #4267

**Comment by sc0ttkclark** [comment]
Fixed in #4267
