### ISSUE TITLE
Evaluate EJS tag usage

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#4273]
* `<%=` Outputs the value into the template (HTML escaped)
* `<%-` Outputs the unescaped value into the template

We should be using `<%=` when outputting into attributes and `<%-` for outputting outside of attributes (except within textarea and option tags I believe).

**Comment by pglewis** [comment]
We're currently using Underscore templates: http://underscorejs.org/#template

It appears Underscore and EJS went opposite directions on the meaning of `<%=` and `<%-`.  

Note that I'm not married to sticking with Underscore templates.  They're the default, so it was the path of least resistance, but swapping out for another template solution is possible.

**Comment by pglewis** [comment]
The appropriate tag was considered while building the templates so we should be good to go here.
