### ISSUE TITLE
Select2 Conflict 3.x - 4.x

### ISSUE THREAD

**Issue by benfavre** [pods-framework/pods#4289]
Hey there !

From what I have gathered, there seems to be a conflict right now between the way the newer versions of Select2 work (4.x+) and the way the current Select2 version that Pods uses (3.x).

All my Woocomerce sites that include Select2 4.x  are conflicting with the Pods Version.

```
Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
   ....
```

So right now i've actually removed Pods version of select2 so Woocomerce is working again, but obviously all my Pods based Dropdown are screwed.

If this is not on a list I missed somewhere, you might want to handle it as it also brakes SearchWP and any other plugin depending on Select2 4.x

Thanks.

**Comment by sc0ttkclark** [comment]
Fixed in 2.7 as we're upgrading to 4.x, more info in #4141

**Comment by benfavre** [comment]
sorry .... good work, thanks.

**Comment by pglewis** [comment]
I'm also exploring possibilities for encapsulating our dependent copy of select2 to avoid potential conflicts in the future (and with another other plugins out there still on 3.x when we move to 4). 

https://github.com/pods-framework/pods/issues/4178
