### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods#4290]
Goal is to refactor the css to be easier to update the frontend (starting with the admin edit pods page).

- [x] Source maps
- [x] Styles for Boolean checkbox for a field in a metabox are broken (could be others as well)
- [x] Check if the full `pods.css` is getting loaded for front end forms, if so remove @pglewis 
- [x] Don't load the old pods-form styles on admin pages
- [x] Test front-end forms
- [x] Test various places that the wizard css is needed
- [x] Fix select2 styles
- [x] jQuery UI smoothness images
- [x] Fix timepicker styles
- [x] Fix up style registers/enqueues
- [x] add `export-ignore` to all scss sources via .gitattributes @pglewis 
- [x] create npm build tasks `npm run build-css` 
- [x] reorganize/restructure css 
- [x] setup pods-admin, pods-front, and pods-wizard files to serve styles more specifically @pglewis 

Potential Sass Compiler Options
- https://www.npmjs.com/package/node-sass
- https://www.npmjs.com/package/scss-compile

**Comment by quasel** [comment]
- keep the compiled resource in the repo

**Comment by pglewis** [comment]
It appears that `pods-front.css` was not previously referenced anywhere.  I'm not sure if it is an old file that was phased out or was an attempt to separate front end styles but wasn't implemented yet.  

Whatever the case: we probably want to audit what we're building for `pods-front.css` now in the refactor.

**Comment by pglewis** [comment]
> keep the compiled resource in the repo

Yeah, this one was a given.
