### ISSUE TITLE
Pods Admin Relationship Customized WHERE should  post_author = {@post_author} work?

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4291]
post_author = {@post_author} => doesn't work = SQL error ( Where is just post_author = )
What works is    post_author = {@user.ID}

Idea is to allow only items from the same author to become related - working with user id breaks the stuff if an editor or admin interferes ( could add/remove capabilities ) 

anyway it would be nice to have a where to be able to be based on fields on both sides - like same author or same field or same taxonomy ...

**Comment by JoryHogeveen** [comment]
Similar topic: https://wordpress.org/support/topic/relationship-options-where-group-by-display-order-by/

**Comment by vesna-droid** [comment]
Hello,

I would also be happy with this functionality. 

I have relationship field connecting extended user pod with extended post pod.

In this field In user pod i need to select a post from posts list by user currently being edited.
In where clause of this relationship field i would need magic tag like this which currently doesn’t work:

t.post_author={@post_author.id} 
or
 t.post_author={@post_author}

**Comment by sc0ttkclark** [comment]
New functionality here added by 8b2ad300ffcc5d14c244ea4c7fa921d3d73f8e9e
