### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by RichardUUU** [pods-framework/pods#4295]
From: http://pods.io/docs/learn/planning-your-custom-content-types/

"Content Types are no longer suffice for your projects"
should be: 
"Content Types no longer suffice for your projects"

**Comment by jimtrue** [comment]
Actually it was "sufficient" then it makes sense. Thanks for the note!

**Comment by RichardUUU** [comment]
Either way makes sense, but sufficient is passive voice which is weaker writing. Cheers.
