### ISSUE TITLE
Shortcodes within conditional (if/else) statements not parsed since pods 2.6.9

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#4303]
Hi folks

I have a website using pods and the avada theme at https://sortering.sonfor.dk/materiale/el-tandboerste/

In the pod template, I use conditional statements to display different icons depending on the pod. Sample snippet:

[if genbrugsbeholder]
  [fusion_content_box title="Genbrugsbeholder" icon="fa-trash" circlecolor="#5ebc61" /]
[else]

That worked perfectly in Pods 2.6.8, but since 2.6.9, the shortcode within the conditional statement is not begin passed, and the shortcode is displayed on the front end.

Shortcodes **outside** the conditional statement is passed just fine, showing, in this case the icon.

If I remove the conditional statements, thus always displaying the icon, it works fine - so the shortcode itself is working fine.

I downgraded to Pods 2.6.8, and the template worked perfectly again.

Any ideas?

**Comment by jimtrue** [comment]
@oldrup I had a similar issue that was reported on our pods.io forums last week. They also down-revved to 2.6.8 and it fixed the issue. 

Can you do me a great favor? Could you upload the entire code in your template and not just the piece you provided above? I have a feeling this has something to do with also including post_content in the template itself. Also, it'd be really helpful to see the error you received in your templates after upgrading (ie what was output in the inspector before and after).

Thanks!

**Comment by jimtrue** [comment]
@jamesgol I think this might have to do with your short-circuiting the Pods Shortcode, but I want to get you more ammunition (more details) to help troubleshoot it. We've had a long standing issue with [if][/if] blocks and [each][/each] blocks with single-select images and single-select relationships and I think this is all related.

**Comment by oldrup** [comment]
Hi Jim! Thanks for digging in to this. I'm very happy about my pods solution, and sad that it breaks with the latest update. I may be "holding it wrong" ;). I'll attach the template as a txt file, screenshot of results before and after pods 2.6.9 update. Should a login to the development-site be useful to you, I'd be happy to create one.
[pods_template.txt](https://github.com/pods-framework/pods/files/1070819/pods_template.txt)
![before-pods-2 6 9](https://user-images.githubusercontent.com/17141205/27073821-76d288de-5025-11e7-8024-0eef30b2fb26.PNG)
![after-pods-2 6 9](https://user-images.githubusercontent.com/17141205/27073898-bd4bdfcc-5025-11e7-9faa-ecff9fdabeaf.PNG)

The dev site is currently at 2.6.9, here is a direct link http://sortering.oldrup.dk/materiale/el-tandboerste/

Please let me know, if there is anything else I can provide to help troubleshooting this.

Best regards
Bjarne

**Comment by jimtrue** [comment]
@oldrup No worries and apologize for taking so long to reply on yours as well. We have a fix for you if you're willing to test it:

1. Copy your existing /pods/ plugin from `/wp-content/plugins/pods/` into a `/wp-content/plugins/backups/` directory (you'll probably have to make this one) (you can do this on your CPanel on your webhost or through FTP/SFTP.
2. Download the following version of Pods: https://github.com/pods-framework/pods/archive/feature/4324-shortcodes-in-html.zip
3. Install through the Plugin, Add New, Upload screen, or unzip the file above into your `/wp-content/plugins/` directory. WordPress will recognize it as 'Pods'

Test! If it works, let us know back here. If it doesn't, let us know how it's still broken.

Thanks!

**Comment by oldrup** [comment]
Thank you so much, for digging into this issue - and of course I'm happy to test...

Unfortunately, the new version does not seem to "render" the shortcodes within the Pods IF/ELSE statements - I still get the Avada Fusion Builder shortcodes for icons, instead of the icons :/

I backed up, removed Pods 2.6.8, and installed the linked zip file. The Plugin page now reports Pods Version 2.6.10-a-1

I navigated the Pods menus, edited a Pod, that stuff still seem to work just fine as always. I also cleared the Pods cache just in case..

The result is still a partially working development site: http://sortering.oldrup.dk/materiale/el-tandboerste/ where the live site running Pods 2.6.8 works just fine: https://sortering.sonfor.dk/materiale/el-tandboerste/

If there's anything I can do to help troubleshooting this issue, please let me know.

Best regards
Bjarne

**Comment by jimtrue** [comment]
Can you check your inspector of the output before and after around your issue and let us know what is actually outputting in the HTML

**Comment by jimtrue** [comment]
It's going to be really tough to troubleshoot this one because you've got a theme shortcode etc inside and if/else which should never have worked. Giving us the actual output is helping us track down what's processing and what isn't.

**Comment by oldrup** [comment]
Hi Jim, your efforts are really appreciated. I've zipped the before/after html source along with the template, hopefully it can shed som light on whats going on. And as mentioned before, I'd be more than happy to provide you with a login to the development site, I'd even make a clone for you to experiment on if that would help... But most importantly, do remember to have a nice weekend ;)

Bjarne
[pods-outputs.zip](https://github.com/pods-framework/pods/files/1132173/pods-outputs.zip)

**Comment by jimtrue** [comment]
@oldrup Can you test this again with Pods 2.7 RC1 https://pods.io/pods-beta/ We should be releasing RC2 this week and hopefully Pods 2.7 this month but it would help to know if this particular mixture of fixes corrected your issue.

I've tested extensively with shortcodes inside if/else clauses now and also calling shortcodes inside fields or using fields as the 'values' for shortcodes and all work successfully. I'm closing this ticket as #4408 should've corrected your issue, but if it does fix it for you @oldrup please let us know in the ticket.

**Comment by oldrup** [comment]
Woop woop! Success! With the 2.7 beta, my templates works great, just as they did in 2.6.8! Tried editing pods, adding fields, adding a pod, viewing pods using all my templates - no problems encountered...

Thumbs up and thanks to the whole team! Your work is greatly appreciated 👍
