### ISSUE TITLE
Image not shown with polylang plugin

### ISSUE THREAD

**Issue by nanu-c** [pods-framework/pods#4304]
I have some fields
![grafik](https://user-images.githubusercontent.com/404058/27025780-fb171814-4f5b-11e7-8fd1-925ceb9622fe.png)

And I have a template

```
<div class="sights">
	<div class="sights-title">{@post_title}</div>
	
	<div class="sights-img" style="background-image: url('{@bild._src}')"></div>
	<div class="description">{@beschreibung}</div>
	<div class="sights-map">
		{@karten_slug}
	</div>
</div>
```
In the main language it produces:
```
<div class="sights">
	<div class="sights-title">21er Haus Wien</div>
	
	<div class="sights-img" style="background-image: url('http://hotelpensionbosch.com/wp/wp-content/uploads/2017/06/21er_haus1-1.jpg')"></div>
	<div class="description"><p>some description</p>
</div>[...]
```
In a second language it produces:
```
<div class="sights">
	<div class="sights-title">21-er Haus Vienna</div>
	
	<div class="sights-img" style="background-image: url('')"></div>
	
	<div class="description"><p>some description</p>
</div>[...]
```

And the two shortcodes used are:
`[pods name="sehenswuerdigkeit" where="sprache.name='English'" template="Sehenswuerdigkeiten_template"]`
and main language:
`[pods name="sehenswuerdigkeit" where="sprache.name='Deutsch'" template="Sehenswuerdigkeiten_template"]`

The permalink structure is like that: 
`?page_id=251&lang=en`

**Comment by JoryHogeveen** [comment]
Can it be that you enabled media translations in Polylang?
If so, then your media items must be translated.

**Comment by nanu-c** [comment]
You are right, I didn't remember that it was activated, yet it's not so easy to see the language selection in the mediathek upload screen.
Thank's for the fast help :+1:
I would not have found the error

**Comment by JoryHogeveen** [comment]
No problem! And yeah, Polylang media translations aren't as "easy" as other content types. Polylang Pro makes it easier though (it allows automatic creation of translated media items)
