### ISSUE TITLE
Researching the [if][/if], [each][/each] Pods Template & Shortcode Issue

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4309]
Post 2.6.9 something has broken some handling of shortcodes, if/else and each where a combination of if/else and shortcodes were included in the same template. This ticket will be used to track repeatable, specific story issues that are broken and need to be fixed.

Ticket List so far: #4303, #4307, #4308 (and for history #2853, #3237, #3249, #3481, #3611, #3972, #4034, #4071 )

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/compare/2.x/2.6.8...2.x/2.6.9

**Comment by sc0ttkclark** [comment]
Probably related to these lines:

https://github.com/pods-framework/pods/compare/2.x/2.6.8...2.x/2.6.9#diff-2c9f345c44362bf8bbf16893a4c8d377L1001

I admit I wasn't involved in those commits, needs further review to see what's happened there.

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/commit/e9562e30987d8b2a57883ddc81df7482362bd546

**Comment by sc0ttkclark** [comment]
Our if/else etc shortcodes aren't actually just if/else. They evaluate to different ones during template processing:

https://github.com/pods-framework/pods/blob/2.x/components/Templates/includes/functions-view_template.php#L329

So the line here isn't going to be picking up 'if', 'else', etc as the tag name, it'll be picking up pod_if_field etc.

**Comment by sc0ttkclark** [comment]
@pglewis can you hop into this at top priority this week?

**Comment by imarcos22** [comment]
I'm using a Single Item Pods Widget

**Comment by jimtrue** [comment]
With the Checkbox for Current Post?

**Comment by jimtrue** [comment]
Actually that should be on #4324  ;)

**Comment by pglewis** [comment]
I'm not sure what we have left here after the patch for 2.6.10.  I know there is another edge case we've been unable to reproduce but otherwise I'm not sure how many of these can be closed out.

**Comment by jimtrue** [comment]
Officially closing this EPIC. All issues noted above closed and verified. Yay! Thanks @jamesgol and @pglewis and @sc0ttkclark
