### ISSUE TITLE
Bidirectional Relationship Not Working With Posts <-> CPT In List View

### ISSUE THREAD

**Issue by reachadam** [pods-framework/pods#4310]
This is a live site, testing 2.7

The site has existing posts. Attached is how I have the field set up and what it shows in the CPT.

<img width="801" alt="screenshot 2017-06-13 22 37 30" src="https://user-images.githubusercontent.com/20959226/27116968-ff33cb76-5088-11e7-96af-cbe28e94f04a.png">
<img width="518" alt="screenshot 2017-06-13 22 37 49" src="https://user-images.githubusercontent.com/20959226/27116970-0175f6e8-5089-11e7-8ede-5519db1ce06c.png">

You see from the first image there is no option to select a post to establish the relationship.

**Comment by sc0ttkclark** [comment]
Can you screenshot the 'Basic' tab too?

**Comment by reachadam** [comment]
My apologies, here it is. The config works properly on a test site with no real data, but this site from the screen shots has real data, 200 blog posts, etc.
<img width="521" alt="screenshot 2017-06-14 07 25 37" src="https://user-images.githubusercontent.com/20959226/27137400-b93752f6-50d2-11e7-8cb7-9981fd9e3e75.png">

**Comment by reachadam** [comment]
Further to add to the conversation, here is what it looks like after changing from list view to autocomplete, it does show posts in the relationship, but there is no option to add new posts. 
<img width="770" alt="screenshot 2017-06-14 07 29 33" src="https://user-images.githubusercontent.com/20959226/27137671-57aaa898-50d3-11e7-93ea-b7625015a57c.png">

**Comment by sc0ttkclark** [comment]
Sounds like an issue for sure, we'll check this out and figure out what's up. Thanks for helping us test!

**Comment by reachadam** [comment]
Here is what Safari says
<img width="1313" alt="screenshot 2017-06-14 07 35 26" src="https://user-images.githubusercontent.com/20959226/27137942-16951482-50d4-11e7-94af-5cbc8eee6e7b.png">

**Comment by sc0ttkclark** [comment]
What plugins do you have activated on your site?

**Comment by reachadam** [comment]
Great news depending on how you look at it. I moved everything to staging, then disabled all my plugins except PODS. Found the culprit, but its a bigger problem I think. The issue goes away when I deactivate Advanced Custom Fields which is odd because I am not using it in the CPT but I am using it in Posts. The reason this is a problem is that I am sure people will be migrating from ACF to pods or they will be using both.

**Comment by pglewis** [comment]
We're definitely looking into the possibility of encapsulating our copy of select2 in order to avoid future version conflicts (which is what I think may be going on here).  See: #4178

**Comment by reachadam** [comment]
I'm good, just converted all of my ACF fields to PODS, then deactivated ACF. All my data is intact and my list view is working.

**Comment by pglewis** [comment]
This problem report emphasizes the need to encapsulate, however.  There will be other plugins that haven't updated the select2 version and there will be installations where people haven't upgraded other plugins.  An ounce of prevention...
