### ISSUE TITLE
Unclear if sub shortcodes work as intended

### ISSUE THREAD

**Issue by m9n** [pods-framework/pods#4312]
Based on [the documentation](http://pods.io/docs/learn/shortcodes/pods/), I understand that getting shortcodes to work in templates which are called by a Pods shortcode requires the following steps:

1. Set `define('PODS_SHORTCODE_ALLOW_SUB_SHORTCODES',true);` in `wp-config.php`
2. Then either add `shortcodes=1` to specific Pods shortcodes, or include this in your theme/plugin: 
    add_filter( 'pods_shortcode', function( $tags )  {
      $tags[ 'shortcodes' ] = true;
      return $tags;
    });

**I can't get this to work with the `shortcodes=1` approach**.  Using that approach, the text of the shortcode from the template is displayed in the Pods shortcode output.  But I can get it to work when I approach it with the function in my theme.

I'm pasting my template and Pods shortcode below for reference.

## Template

    <div class="meta">
    	[pk_dates opt="event,_start_date,_end_date" format="j F Y" id="{@ID}"]
    	[if _event_times]
    	<div class="times">{@_event_times}</div>
    	[/if]
    	[if _location]
    	{@_location, pk_gmap}
    	[/if]
    </div>
    <div class="content">
    	{@post_content}
    </div>

## Pods shortcode

    [pods name="event" limit="10" template="Event, single"]

**Comment by jimtrue** [comment]
Add reference to #4303

**Comment by jamesgol** [comment]
This should be be resolved.  Can you test the release/2.7 branch (or the next RC coming out soon) and report back.

**Comment by jimtrue** [comment]
@m9n Can you validate on this one? I've tested shortcodes within if/each blocks as part of the testing of all the fixes from #4324 and #4335 should have fixed this situation as well, but would love you to confirm.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! Guess it's solved!
