### ISSUE TITLE
Saving multi-file upload fields causes Array to string conversion in classes/PodsAPI.php on line 3754

### ISSUE THREAD

**Issue by mgratch** [pods-framework/pods#4313]
First reported: https://wordpress.org/support/topic/error-when-using-multiple-images/
I was able to reproduce locally on a fresh local VVV install.
nothing but pods installed.
1 post type added (artwork)
1 field added – file (slide show images)
only setting change was to set it to multiple files

I ensured that define('WP_DEBUG', true);
Added 4 images to slide_show_images
debug log displayed the notice

**Comment by sc0ttkclark** [comment]
Fixed via #4314
