### ISSUE TITLE
Inconsistent behaviour between shortcode and widget (using where in query)

### ISSUE THREAD

**Issue by m9n** [pods-framework/pods#4316]
I've been helping @ablewebs in #support with this.  I'm brain-dumping the issue here in haste.  Please ask for clarification if needed.

We've got an 'event' pod, and it has a date field called event_date.  We've set `define('PODS_SHORTCODE_ALLOW_EVALUATE_TAGS',true);` in our `wp-config.php`.

Then we include the following shortcode **in a page**:

`[pods name="event" orderby="event_date" where="event_date.meta_value >= '{@date.Y-m-d}'" template="Upcoming Events"]`

That returns the text "Pod not found".

If we remove `where="event_date.meta_value >= '{@date.Y-m-d}'"`, then the shortcode returns the list of events (although not filtered to show only future dates, of course).

So that's confusing, because that syntax has worked for me on other sites.

But what I have noticed is that the shortcode has worked on other sites where I've put it in a plain text widget (before the latest WP upgrade made them mini TinyMCE editors) - in a sidebar, or used within a page builder layout.

However, back on my local test site where I'm getting "Pod not found", if I build the same query using the Pods widget, then the query works just fine - using the where statement to filter for only future events.

So the where query causes "Pod not found" if use in a shortcode in a Page; but it works fine if used in a Pods Widget.

So... wassup with this? :)

**Comment by quasel** [comment]
Dates are stored as stings therefore in most cases you need to cast it to work! 

`CAST( entry_date.meta_value AS DATE )`

Sorry for the late reply, feel free to comment if you still have questions!
