### ISSUE TITLE
Make Pods Templates available for relationship

### ISSUE THREAD

**Issue by davidatwhiletrue** [pods-framework/pods#4331]
Hi,

I'd like to add a new field in a Pods settings page with type relationship and linked to Pods Templates. But 'Pods templates' is not listed in the relationship targets list.

I think that option might be useful. In my case, I want the user can select the template to use to build a mail message when a new post is created.

Thanks.

David

**Comment by JoryHogeveen** [comment]
Hi @davidatwhiletrue 

There is a filter to enable internal pods objects in the relationships.
Just add the code below in a plugin or your theme functions.php

```php
add_filter( 'pods_pick_ignore_internal', '__return_false' );
```

**Comment by davidatwhiletrue** [comment]
That does what I need. Thanks a lot @JoryHogeveen
