### ISSUE TITLE
WooCommerce - Shop Order

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#4332]
What is the reason you take in relationship field WooCommerce Order **date** ?
I men not much use of it. Better to pick Order ID, or something else.

**Comment by sc0ttkclark** [comment]
Can you explain a little further? Not sure what you're asking or describing here.

**Comment by sc0ttkclark** [comment]
Oh you mean relationship to the shop_order post type? We're showing post_title by default, you should try using the `{@ID}` for display field in the relationship additional field settings.

**Comment by StaggerLeee** [comment]
Thank you, it works. ACF fields are not recognized.

**Comment by sc0ttkclark** [comment]
Only post object fields in the wp_posts table are available currently (or whatever the table for the related object). There are improvements planned for the display field support in the future.

Related: #1240 #3379 #3817
