### ISSUE TITLE
Front-end Profile Editor

### ISSUE THREAD

**Issue by lvito** [pods-framework/pods#4344]
Hi,

I would like to be able to create a front-end profile editor where cover and profile image is uploaded from the front end and not from the back-end of wp. 
Im using Beaver Builder (and Beaver themer) for creating profile for multi-author website where author post archive is under each profile. Users (authors) must me able to upload/update cover and profile images as well as bio about them without entering wp back-end.
Is anything like this possible with Pods without touching php. Im not familiar with php jet.

Thank you!

Vit

**Comment by jimtrue** [comment]
This is actually a support question and should be posted on our forums at https://pods.io/forums/ or on the WordPress.org Support Forum for Pods at https://wordpress.org/support/plugin/pods. The GitHub Repo is only used for bug reports or feature enhancements.

To answer your question: you can use Gravity Forms with the User Registration add-on to provide profile editor access on the front-end.
