### ISSUE TITLE
Labels a ignored for Featured Image

### ISSUE THREAD

**Issue by staude** [pods-framework/pods#4345]
i have a new, fresh WordPress ( 4.8) installation wit the default theme and pods as the only plugin.
then I create a new Posttype. This Posttype uses the featured image.
When i use the label to translate it for my German customer, the labels are fine, without the featured images labels.

<img width="993" alt="beitrag1" src="https://user-images.githubusercontent.com/870951/28170111-95015ef8-67e4-11e7-9f26-ef047851f697.png">

<img width="1919" alt="beitrag2" src="https://user-images.githubusercontent.com/870951/28170117-9a0538f2-67e4-11e7-91ba-94a4b618796e.png">

The Screenshots are from the project site. Here is a video from the new WP installation.

https://screencast.com/t/7pyy9YMCvR0

**Comment by JoryHogeveen** [comment]
This was fixed in #3689 (Merged into 2.7).
