### ISSUE TITLE
Feature: Add `offset` as an option to the pods shortcode to skip a number of records

### ISSUE THREAD

**Issue by mermare** [pods-framework/pods#4348]

**Comment by JoryHogeveen** [comment]
While looking at the code I already see an `offset` parameter so I just tested a simple shortcode and the offset parameter worked fine.
Do you have a particular configuration where it doesn't work?

**Comment by mermare** [comment]
Hi Jory, The offset didn't work in a shortcode with a limit parameter specified but once I removed that it does work. Thanks for the quick response.

**Comment by jimtrue** [comment]
Looks like it was documented in 'find' but not in the shortcodes. Added to shortcode docs.

**Comment by jimtrue** [comment]
Limit and offset and mutually exclusive; from the [Find](https://pods.io/docs/code/pods/find/) documentation:

`offset - Override what's calculated automatically based on 'limit' and 'page'`
