### ISSUE TITLE
if statement not showing single image

### ISSUE THREAD

**Issue by Vanbrent** [pods-framework/pods#4354]
Using the following code does not show the image. (when use the code without an if statement the image is shown.

[if media_afbeelding]<div style="width: 45%; float: right; margin-left: 1em; margin-bottom:.5em;"  >
				<img src="{@media_afbeelding._src}" alt="{@post_title}" title="{@post_title}">
				</div>	[/if]

**Comment by jimtrue** [comment]
Is this a single upload image, not a multiple file/upload image?

**Comment by Vanbrent** [comment]
it is a single uploade image

**Comment by jimtrue** [comment]
That's what I thought, it's related to these issues: #4403 and #3481

**Comment by jimtrue** [comment]
This has been corrected as of #4408 in Pods 2.7 RC1
