### ISSUE TITLE
Add ability to traverse into a related field's meta value: related_field.another_field_name.meta_value

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4355]
Image relationships referenced inside a loop will generate an extra query per loop iteration when used in that context.  This normally isn't a problem because you would limit the number of records being accessed at a time but there are valid use cases where this becomes a bottleneck.

**Comment by sc0ttkclark** [comment]
What about this:

`'select' => 't.ID, related_image._wp_attached_file.meta_value'`

**Comment by sc0ttkclark** [comment]
While that should technically be possible, it's not, so I think we're looking at needing to eventually add the ability to traverse related field (pick/file/author) meta values. Setting this as an enhancement and punting.

**Comment by sc0ttkclark** [comment]
A potential workaround if you needed to do something the long way -- using a custom join:

```php
'select' => 't.*, main_image.ID, main_image_attached_file.meta_value',
'join' => 'LEFT JOIN @wp_postmeta AS main_image_attached_file ON main_image_attached_file.post_id = main_image.ID AND main_image_attached_file.meta_key = "_wp_attached_file"'
```
