### ISSUE TITLE
2.7 - plugins generate php error in Edit Pods

### ISSUE THREAD

**Issue by bwsolutions** [pods-framework/pods#4356]
in the 2.7 beta a couple plugins generate errors in Edit Pod screen.  When I deactivate the problem plugins, the errors go away. 

The plugins are "Post Expirator - version 2.3.1.1" and "FooGallery - version 1.3.6"

Here is a stack trace for one error...

`
( ! )  Notice: Trying to get property of non-object in  F:\web\websites\wptesting\wordpress\wp-content\plugins\post-expirator\post-expirator.php  on line 263
--

1 | 0.0007 | 180744 | {main}(  ) | ...\admin.php:0
2 | 4.0468 | 81526456 | do_action(  ) | ...\admin.php:222
3 | 4.0468 | 81526880 | WP_Hook->do_action(  ) | ...\plugin.php:453
4 | 4.0468 | 81526928 | WP_Hook->apply_filters(  ) | ...\class-wp-hook.php:323
5 | 4.0468 | 81527400 | call_user_func_array:{F:\web\websites\wptesting\wordpress\wp-includes\class-wp-hook.php:298} (  ) | ...\class-wp-hook.php:298
6 | 4.0468 | 81527784 | PodsAdmin->admin_setup(  ) | ...\class-wp-hook.php:298
7 | 4.0502 | 81818480 | pods_ui(  ) | ...\PodsAdmin.php:890
8 | 4.0558 | 82646184 | PodsUI->__construct(  ) | ...\classes.php:49
9 | 4.0670 | 83208280 | PodsUI->go(  ) | ...\PodsUI.php:516
10 | 4.0673 | 83208960 | PodsUI->edit(  ) | ...\PodsUI.php:1353
11 | 4.0673 | 83209128 | PodsUI->callback_action(  ) | ...\PodsUI.php:1478
12 | 4.0674 | 83209792 | call_user_func_array:{F:\web\websites\wptesting\wordpress\wp-content\plugins\pods-release-2.7\classes\PodsUI.php:4575} (  ) | ...\PodsUI.php:4575
13 | 4.0674 | 83210056 | PodsAdmin->admin_setup_edit(  ) | ...\PodsUI.php:4575
14 | 4.0674 | 83210608 | pods_view(  ) | ...\PodsAdmin.php:909
15 | 4.0675 | 83210872 | PodsView::view(  ) | ...\classes.php:215
16 | 4.0688 | 83212520 | PodsView::get_template_part(  ) | ...\PodsView.php:118
17 | 4.0708 | 83389744 | require( 'F:\web\websites\wptesting\wordpress\wp-content\plugins\pods-release-2.7\ui\admin\setup-edit.php' ) | ...\PodsView.php:515
18 | 7.0373 | 85810232 | do_meta_boxes(  ) | ...\setup-edit.php:710
19 | 7.0387 | 85811480 | call_user_func:{F:\web\websites\wptesting\wordpress\wp-admin\includes\template.php:1050} (  ) | ...\template.php:1050
20 | 7.0387 | 85811928 | expirationdate_meta_box(  ) | ...\template.php:1050
`

**Comment by sc0ttkclark** [comment]
Looks related to this:
https://github.com/pods-framework/pods/commit/c3d15292550295b52066c2d7306b1a09dfeb5aef

In 2.7 we're passing $pod but it be the $pod_post object instead.

**Comment by pglewis** [comment]
Fixed in #4357 and ready for testing
