### ISSUE TITLE
2.6.10 - Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by TerribleGit** [pods-framework/pods#4363]
Hey there,

On the Pods help page in wp-admin I get the following error output:

Warning: A non-numeric value encountered in /app/public/wp-includes/SimplePie/Parse/Date.php on line 694

{main}( )	.../admin.php:0
do_action( )	.../admin.php:222
WP_Hook->do_action( )	.../plugin.php:453
WP_Hook->apply_filters( )	.../class-wp-hook.php:323
PodsAdmin->admin_help( )	.../class-wp-hook.php:298
pods_view( )	.../PodsAdmin.php:2312
PodsView::view( )	.../classes.php:206
PodsView::get_template_part( )	.../PodsView.php:118
require( '/app/public/wp-content/plugins/pods/ui/admin/help.php' )	.../PodsView.php:515
SimplePie->get_item_quantity( )	.../help.php:72
SimplePie->get_items( )	.../class-simplepie.php:2812
SimplePie_Item->get_date( )	.../class-simplepie.php:2925
SimplePie_Parse_Date->parse( )	.../Item.php:773
SimplePie_Parse_Date->date_w3cdtf( )	.../Date.php:603

**Comment by pglewis** [comment]
This might be limited to PHP 7.1 or higher and almost certainly a WordPress bug.  We call through to SimplePie with `$feed->get_item_quantity( 10 )`... literally a hard-coded integer.  I'm not seeing any way we could be causing it nor fix it from the Pods side.  

https://github.com/pods-framework/pods/blob/ecbca6f7b78c77b988db75ab5d76fa9e143c823e/ui/admin/help.php#L27

**Comment by pglewis** [comment]
Rather than close this out, I @sc0ttkclark may want to use his influence to get this into trac, if need be.  

In the call stack above we hand over control to SimplePie with a guaranteed numeric value and control never returns to Pods, so it seems clear it's a minor WordPress bug.  May only manifest on PHP 7.1 and above: http://php.net/manual/en/migration71.other-changes.php

**Comment by pglewis** [comment]
All indications are this is coming from WordPress itself and there have been no other/further reports.

**Comment by jimtrue** [comment]
Guessing there's no going to get any traction from the WP side. Can we bypass this library? I didn't check to see what it's doing for us but if it's part of the last forum posts and they're not the WP.org posts, we should be able to remove it completely. 

Which file drives the Help page? I can look at changing it all to our new resources.

**Comment by pglewis** [comment]
> [...] if it's part of the last forum posts and they're not the WP.org posts, we should be able to remove it completely

We are actually pulling a feed from the pods.io forums as well.  For some reason that one doesn't kick off the warnings but obviously a new issue needed to either just yank that portion out or switch it to a feed from wp.org if one exists.  

https://github.com/pods-framework/pods/blob/ecbca6f/ui/admin/help.php#L24

**Comment by pglewis** [comment]
This should be "fixed" (more accurately, "hidden") via #5180
