### ISSUE TITLE
__construct Deprecation Notice in User Roles

### ISSUE THREAD

**Issue by leepeterson** [pods-framework/pods#4366]
WordPress Version: 4.8
Pods Version: 2.7.0-b-2
Operating system: Ubuntu 16.04.1
Server Software: Apache 2.4.27 / OpenSSL 1.0.2g
PHP Version: 7.1.7
MySQL Version: 5.7.19

When deleting a user role, the following appears: 

"Notice: __construct is deprecated since version 3.1.0! Use WP_User_Query instead. in /wp-includes/functions.php on line 3831"

**Comment by pglewis** [comment]
PR: #4389
