### ISSUE TITLE
Incompatibility with custom attachment and WPML

### ISSUE THREAD

**Issue by IJohnGalt** [pods-framework/pods#4374]
When creating a custom content type and uploading media (a picture) you can "clone" everything with WPML (as I understand the image is not cloned, just linked). The problem is that the custom attachment doesn't get "cloned". 

There is no problem with other fields like with featured Image for example. I tested it with Catalan to Spanish and the other way around. Also I'm aware that WPML was able to reproduce the bug with their own installation.

I've opened a ticket in WPML forum already where there are images of the bug:
https://wpml.org/forums/topic/i-cant-translate-attachments-with-pods/#post-1328931

Also in the wordpress forum @jimtrue linked me to: https://github.com/pods-framework/pods/issues/3727 (I'm not sure if it's the same bug).

**Comment by srdjan-jcc** [comment]
@IJohnGalt We can confirm issue and started to debug it.
I will update here soon.

**Comment by srdjan-jcc** [comment]
@IJohnGalt We still do not have fix suggestion for this issue.

When fetching images, WPML $join and $where parameters
are added to Pods SQL query but original attachment IDs are used - so it fails.
There are no images in requested language matching copied IDs.

For quick fix we tested adding filter after code
pods/classes/Pods.php:1195
\Pods::field()
```$ids = $this->api->lookup_related_items(...```

pods/classes/Pods.php:1203
```
if ( ! empty( $ids ) && $type == 'file' ) {
    foreach ( $ids as $k => $att_id ) {
        if ( wp_attachment_is_image( $att_id ) ) {
            $ids[ $k ] = apply_filters( 'wpml_object_id', $att_id, 'attachment', true );
        }
    }
}
```

This will adjust copied values before query.

Edit post screen meta box shows editable form for images
but should inform that WPML will just copy fields and read-only list of images should appear.

**Comment by quasel** [comment]
Hi is this still an issue with WPML? 
Sorry for the late reply!

**Comment by ThomasHyunsooChoi** [comment]
I guess this is still an issue...I know this has been an issue for a while. Any plan to include this fix on the next release?

**Comment by jimtrue** [comment]
@srdjan-jcc Do you still have PR access to our plugin base? As this issue has come back up again, can you please push a PR for this fix?

**Comment by baltaran** [comment]
I have just tried the fixe given above by srdjan-jcc but no luck.
It is not working.
Can anyone please have a look at it?
Thanks

**Comment by JoryHogeveen** [comment]
Duplicate issues: #4544 #2006
Closing here
