### ISSUE TITLE
use of  < > in 'where' argument causes [pods] shortcode to not pass SQL query

### ISSUE THREAD

**Issue by wildmercury** [pods-framework/pods#4376]
Found when trying to implement a where argument restriction on a pods list with a "deadline" date field.
=curdate() works fine, !=curdate() works fine, but >, >=, < or <= all fail with a "Pod not found" response and the Query never seems to have been parsed.
Screenshot:
![job opportunities itc consulting](https://user-images.githubusercontent.com/8449753/28745622-4847a05a-747c-11e7-90b5-05fe428d63a8.png)

List of shortcodes used to generate the above:
<h3>Greater or equal:</h3>
[pods name="vacancies" orderby="deadline ASC" template="Vacancy list template" where="deadline.meta_value>=curdate()"]
<hr/>
<h3>equal</h3>
[pods name="vacancies" orderby="deadline ASC" template="Vacancy list template" where="deadline.meta_value=curdate()"]
<hr/>
<h3>not equal</h3>
[pods name="vacancies" orderby="deadline ASC" template="Vacancy list template" where="deadline.meta_value!=curdate()"]

**Comment by Wilko-C** [comment]
Hi, 
I have the same error.

I used that shortcode:

[pods name="veranstaltung" orderby="datum" limit="10" where="datum.meta_value > CURRENT_DATE()" template="Termine Aktuell"]

Result - on page:

Database Error; SQL: SELECT DISTINCT ... WHERE ( ( `datum`.`meta_value` > CURRENT_DATE() )...
Response: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '; CURRENT_DATE() ) AND ( `t`.`post_type` = "veranstaltung" ) AND ( `t`.`post_st' at line 11

in the page-source i found the REAL error:
... WHERE ( ( `datum`.`meta_value` `&gt;` CURRENT_DATE()  )...

so: htmlspecialchars!

`< (less than) results in &lt;`
`> (greater than) results in &gt;`

Workaround: SQL BETWEEN
[pods name="veranstaltung" orderby="datum" limit="10" where="datum.meta_value BETWEEN CURRENT_DATE() AND ADDDATE(CURRENT_DATE(), 365) " template="Termine Aktuell"]

and u should `<pre>` the MySQL-Error...

Thx
Wilko

**Comment by Wilko-C** [comment]
naaa...
it could be that the htmlspecialchars is just MY problem here.. im still testing :)

But Workaround - works.

**Comment by jimtrue** [comment]
Interesting solution the BETWEEN. There's still something going on where the >= is not recognized so that's still the primary error (along with the <pre><code></code></pre> surrounding the SQL error.

**Comment by sc0ttkclark** [comment]
Fix ready for merge
