### ISSUE TITLE
Field boxes extending to obscure side meta-boxes

### ISSUE THREAD

**Issue by markjohnl** [pods-framework/pods#4379]
When editing a post and pasting a Google embed code into an html field, the box extends out to obscure all meta boxes on the right side of the page. If there are other fields on the page, all field boxes will extend out in the same way. It seems to be where a line exceeds a certain length it fails to wrap around to the next line.

https://screencast-o-matic.com/watch/cbivYHlaPt

I get the same issue with both the latest stable version and 2.7 beta.

**Comment by pglewis** [comment]
#4487 should fix it up

**Comment by pglewis** [comment]
Merged.
