### ISSUE TITLE
2.7 Editing relationship adds entries to other relationships on same page

### ISSUE THREAD

**Issue by bwsolutions** [pods-framework/pods#4380]
in 2.7.0-b-2 if there are multiple relationships to the same post_type, making multiple edits to these relationships, seems to add entries to these relationships.

I have a pod with 3 relationships to the same post_type (Events). Each of these events or dates are setup as a single selection, list view, with allow add new.

you can edit one of the relationships (date_1) update, and when you return to the pod, everything looks fine.

Before updating the pod, edit a second relationship (date_2), save the changes, and when you return to the pod
The relationship that was edited (date_2), looks fine, only lists 1 item.
However the first relationship that was edited (date_1), now looks like there are 2 items selected, the original (date_1) and the relationship just edited (date_2).
It looks like an additional input statement, etc was inserted in the first relationship that was edited.
The one relationship that was not edited has not changed.

Edit the third relationship (date_3) and the date_3 relationship looks fine, only 1 item listed.
However date_1 now has 3 items (Date_1, Date_2, and date3).
Date_2 now has 2 items (date_2 and date_3).

clicking update to update the post saves everything as expected and everything is back to only 1 item displayed for each date field.

![image](https://user-images.githubusercontent.com/6188158/28758428-a364562e-7565-11e7-944f-367fd6c1ef11.png)

**Comment by pglewis** [comment]
PR: #4382

The first commit there handles the situation as reported.  We also need to trap cancel events from the modal as this can still manifest that way.

**Comment by pglewis** [comment]
The PR branch should be ready for testing.  We should no longer generate spurious extra rows when adding, editing, or cancelling an edit.

**Comment by sc0ttkclark** [comment]
Resolved via #4382
