### ISSUE TITLE
pods_group_add sharing a meta group with multiple pods returns a memory error

### ISSUE THREAD

**Issue by wpstudio** [pods-framework/pods#4385]
When attempting to share meta groups creating with pods_group_add() with multiple pods, a memory error (not enough memory) triggers a failure.

`pods_group_add( array('books', 'other_books'), 'Book Meta Title', 'field1,field2');`

You can see the actual issue during this live training event. https://youtu.be/fXJbXiTnqBk?t=43m34s

I even attempted to allocate over 2GB of memory and this array() sucked it all up. :)  Greedy little bastard.

**Comment by sc0ttkclark** [comment]
Well of course it would happen while you're doing it live! Thanks for the heads up, will check into it

**Comment by sc0ttkclark** [comment]
Found it:

https://github.com/pods-framework/pods/blob/2.x/classes/PodsMeta.php#L596

We should be using $p there, not $pod

**Comment by wpstudio** [comment]
Ha... maybe I should have just looked at the code myself :)

**Comment by sc0ttkclark** [comment]
Fix is a one-liner via #4386

**Comment by sc0ttkclark** [comment]
This has actually been around since August 5th, 2013 -- which coincidentally we're coming up on the 4 year anniversary for :)

**Comment by sc0ttkclark** [comment]
The commit we can blame for this:
https://github.com/pods-framework/pods/commit/72803d10bd11aa4f789598ad0b15ebf88a1a76b9

That committer is a dummy
