### ISSUE TITLE
Expose old slugs in REST API

### ISSUE THREAD

**Issue by cr101** [pods-framework/pods#4387]
I'm building a React-powered app using Pods 2.7-beta-1 and the WP REST API 4.8 and I need to expose the old slugs for all post types in the REST API. This is so I can automatically redirect users if they clicked on a old link.
The old slugs are stored in table `wp_postmeta` with `meta_key = '_wp_old_slug'`

To add  '_wp_old_slug' to the WP API response I wrote the WP plugin below:

```
add_action( 'rest_api_init', 'expose_old_slugs_in_api' );

function expose_old_slugs_in_api() {
 // // Get list of all post types
  $post_types = get_post_types( array( 'show_in_rest' => true, 'show_in_nav_menus' => true ) ) ;
    
  $args = array(
    'type'          => 'string',
    'single'        => false,
    'show_in_rest'  => true
  );
  
  foreach ($post_types as $type) { 
    register_meta( $type, '_wp_old_slug', $args );
  }
}
```

It works for all the post types except for the custom post types created through Pods because `custom-fields` never gets set in `setup_content_types()`
Is there a way to fix this issue and expose the old slugs for all post types as shown below?
![screenshot_8](https://user-images.githubusercontent.com/4064582/28907066-4f259cfe-7870-11e7-854d-57a925f5b333.jpg)

**Comment by sc0ttkclark** [comment]
Did you enable Custom Fields support on your Pods themselves?

<img width="519" alt="screen shot 2017-08-03 at 12 24 51 am" src="https://user-images.githubusercontent.com/709662/28907149-398f7bbe-77e2-11e7-859f-8e3834240446.png">

**Comment by sc0ttkclark** [comment]
That's under Pods Admin > Edit Pods > Edit {Pod} > Advanced Options > Supports

**Comment by cr101** [comment]
@sc0ttkclark Thank you. That added `_wp_old_slug` to the WP API response but now **Custom Fields** appear on the Edit/Add New page which I don't need.
![screenshot_9](https://user-images.githubusercontent.com/4064582/28907816-42748624-7874-11e7-951e-591dc08da275.jpg)

I will try using [register_rest_field()](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#using-register_rest_field-vs-register_meta) instead.

**Comment by sc0ttkclark** [comment]
I just ran into that type of issue before too, it's so silly!

register_rest_field() vs register_meta() differences are amazing, another reason why WP needs a real Fields API :)

**Comment by cr101** [comment]
@sc0ttkclark I agree with you that WP needs a Fields API.
In case someone else needs to expose the old slugs for all post types (including custom post types) in the REST API I used the solution below:

```
add_action( 'rest_api_init', 'expose_old_slugs_in_api' );
 
function expose_old_slugs_in_api() { 
  $post_types = get_post_types( array( 'show_in_rest' => true, 'show_in_nav_menus' => true ) ) ;

  $args = array(
    'get_callback' => 'get_old_slugs_for_api', 
    'schema' => null
  );
  
  foreach ($post_types as $type) {    
    register_rest_field( $type, 'old_slugs', $args );
  }  
}
 
function get_old_slugs_for_api( $object ) {
  //get the id of the post object array
  $post_id = $object['id'];

  //return the post meta
  return get_post_meta( $post_id, '_wp_old_slug' );
}
```
![screenshot_11](https://user-images.githubusercontent.com/4064582/28949776-163f3578-7913-11e7-96eb-d9f596b5aadf.jpg)
