### ISSUE TITLE
Relationship field "List view" format not adding posts when selected

### ISSUE THREAD

**Issue by rob** [pods-framework/pods#4388]
I'm using the new "List view" format for the Relationship field in the Pods 2.x branch. I set it to be related to "Posts (post)."

**Issue:** When searching for posts and clicking enter, or clicking a post manually, it doesn't add that post to the list. It doesn't do anything. However, sometimes it _does_ add the post to the list. I would say usually it doesn't, however.

Don't see any JavaScript errors in the console or anything.

Video showing issue, where it both adds and doesn't add posts:

![record](https://user-images.githubusercontent.com/503/28945693-88d6c75c-7875-11e7-896d-2a7c567c5799.gif)

Any thoughts?

**Comment by sc0ttkclark** [comment]
Thanks for posting your issue and describing it very well, we really appreciate the effort you put to provide the video. We'll take a look and see what's up.

**Comment by pglewis** [comment]
I wasn't aware that list view had even been put into the 2.x branch.  Can you test this on the 2.7 branch?  That's the only one where the list view work is actively going on.

**Comment by pglewis** [comment]
Actually, I'm guessing "2.x" was a typo... I don't get anything for list view on the 2.x branch.  

I've tested this under 2.7 and haven't been able to reproduce it yet.  

I'm also seeing entity escapes ("Ireland's") and raw markup (<em>...</em>) in your screen cap.  This does not happen for me in the 2.7 branch.  I'm starting to wonder if you have the older version of select2's javascript cached.  We should be cache-busting via version number and Wordpress's enqueueing, I think, but it wouldn't hurt to make sure it's not keeping an old local copy of select2 for some reason.

**Comment by rob** [comment]
Hmm, that might be it. I upgraded via GitHub Updater from the stable 2.6
version installed. I'll check tomorrow and let you know. Thanks!

Rob

On Aug 3, 2017 22:37, "PG Lewis" <notifications@github.com> wrote:

Actually, I'm guessing "2.x" was a typo... I don't get anything for list
view on the 2.x branch.

I've tested this under 2.7 and haven't been able to reproduce it yet.

I'm also seeing entity escapes ("Ireland's") and raw markup (*...*) in your
screen cap. This does not happen for me in the 2.7 branch. I'm starting to
wonder if you have the older version of select2's javascript cached. We
should be cache-busting via version number and Wordpress's enqueueing, I
think, but it wouldn't hurt to make sure it's not keeping an old local copy
of select2 for some reason.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pods-framework/pods/issues/4388#issuecomment-320140960>,
or mute the thread

**Comment by rob** [comment]
Hmm, still having the issue. Looks like it's using select2 v4.0.3. On the release/2.7 branch.

<img width="1230" alt="screen shot 2017-08-05 at 9 36 02 am" src="https://user-images.githubusercontent.com/503/28995848-cc51a068-79c1-11e7-8514-29f001f702fc.png">

<img width="539" alt="screen shot 2017-08-05 at 9 37 29 am" src="https://user-images.githubusercontent.com/503/28995849-d146f9c4-79c1-11e7-87f4-ed6199ce6a07.png">

**Comment by pglewis** [comment]
Are you in a testing environment where you can disable other plugins?  One other possibility is another plugin is loading the 3.x version of select2 and overriding the version we enqueue.  

Otherwise I'm at a loss... I'm not seeing this behavior in Chromium nor Chrome and we've had no other reports on this (and it's easy enough to reproduce that I think we would have seen it if it's chronic).

**Comment by rob** [comment]
@pglewis I actually did disable all plugins except for GitHub Updater and Pods, and it still happened.

I can create you an account if you'd like to log in and check? Maybe there's something you can see that I'm missing. Might be easier. Let me know.

**Comment by pglewis** [comment]
> I can create you an account if you'd like to log in and check? Maybe there's something you can see that I'm missing. Might be easier. Let me know.

That's probably the best next step since we're baffled trying to reproduce it.  Can you join our Slack and PM me?

**Comment by pglewis** [comment]
This only manifests if there are more than 30 records so that it kicks off the AJAX mode.  I have it reproduced locally, hopefully a patch soon.

**Comment by pglewis** [comment]
PR: #4405 

Not 100% ready at this moment but should address the specific issue with List View
