### ISSUE TITLE
Bug with Pods + free Admin Columns : the custom columns data displays in weird ways

### ISSUE THREAD

**Issue by YammYcoding** [pods-framework/pods#4392]
![image](https://user-images.githubusercontent.com/1200923/28976868-0788570a-7916-11e7-8324-16fce34c26f6.png)

To make a workaround for these, I had to make ugly loops in jquery to hide the extra stuff.

**Comment by quasel** [comment]
we fixed a bunch of issues with them - if they still exists may try their pro Version - they have an extra pods add-on now! 

Sorry for the late reply, feel free to comment if you still have questions!
