### ISSUE TITLE
The new Gutenberg editor and the future of Pods

### ISSUE THREAD

**Issue by cr101** [pods-framework/pods#4396]
As I'm sure you already know, Gutenberg will soon be the default editor in WordPress. The Gutenberg developers are now seeking collaboration from the Pods plugin developers. 
See [Wordpress/gutenberg/#320523428 (comment)](https://github.com/WordPress/gutenberg/issues/952#issuecomment-320523428) which was posted a few hours ago

**Comment by sc0ttkclark** [comment]
Replied, thanks for the heads up!

**Comment by szepeviktor** [comment]
When reading this blog post
https://riad.blog/2017/12/11/with-gutenberg-what-happens-to-my-custom-fields/
I wonder where is a reading on Pods in *Guternberg-times*.
