### ISSUE TITLE
The Gutenberg editor and the future of ButterBean

### ISSUE THREAD

**Issue by justintadlock** [pods-framework/pods#4397]
As requested in [#952](https://github.com/WordPress/gutenberg/issues/952#issuecomment-320523428), I'm creating a ticket for the ButterBean meta box framework.

Repo: https://github.com/justintadlock/butterbean/tree/dev

For testing purposes, the framework is included in this plugin: https://github.com/justintadlock/custom-content-portfolio

ButterBean is a drop-in framework built with Backbone.js and Underscore.js.  It is modeled heavily off of the customizer in core WP.  It's primary purpose is to be used with custom post types that have several meta fields.

It's a young framework, but it's one I've been planning to roll into several plugins this year.  Right now, I and others are hesitant to do this because of the direction of Gutenberg. 

## Hooks used

The following are the primary core WP hooks used (pretty standard for most meta box frameworks, I'd imagine):

```
load-post.php
load-post-new.php 
add_meta_boxes
save_post 
admin_enqueue_scripts
admin_footer 
admin_print_footer_scripts
```

**Comment by lkraav** [comment]
@justintadlock just curious, was this supposed to be posted into Gutenberg repo, not Pods?

**Comment by justintadlock** [comment]
Crap.  Well, that's what I get for having about 20 tabs open. :)

My bad.
