### ISSUE TITLE
2.7 causing problems with other plugin metaboxes

### ISSUE THREAD

**Issue by bwsolutions** [pods-framework/pods#4400]
When you open the edit pod page, there is a php error in another plugin trying to get a property of a non-object related to a metabox.

![image](https://user-images.githubusercontent.com/6188158/29051123-6d733e6e-7bae-11e7-93e1-ff49a9fd0681.png)

**Comment by jimtrue** [comment]
@bwsolutions Did you specify _which_ metaboxes? I see FooGallery in your list but nothing else. Were there others that were conflicting?

**Comment by bwsolutions** [comment]
Sorry for the delayed response.  But yes this seems to be the only plugin I am having a problem with.
It is version 1.3.6 of FooGallery with Pods 2.7.0-b-2.
I upgraded Pods to 2.7.0-rc-1 and FooGallery to 1.3.8 and I still get the same error.
I have not seen this on other pages, or other plugins.

**Comment by sc0ttkclark** [comment]
Can you screenshot the exact error again when running on 2.7 RC1?

**Comment by sc0ttkclark** [comment]
Sorry, I see now. This isn't actually our fault entirely, the hook in question being run through Foogallery is checking a `$post` global variable instead of looking for it in the hook it's running through.

I've added a support ticket for that plugin directly here:
https://wordpress.org/support/topic/add_meta_boxes-compatibility-issues/

**Comment by sc0ttkclark** [comment]
Closing this for now here, will follow up in that support thread going forward.

**Comment by bwsolutions** [comment]
Sorry for the delayed response.  But yes this seems to be the only plugin I am having a problem with.
It is version 1.3.6 of FooGallery with Pods 2.7.0-b-2.
I upgraded Pods to 2.7.0-rc-1 and FooGallery to 1.3.8 and I still get the same error.
I have not seen this on other pages, or other plugins.
