### ISSUE TITLE
Unable to save a relationship field if relating to draft post

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4409]
I have a relationship field which I have enabled 'draft' posts for:

<img width="564" alt="screen shot 2017-08-09 at 18 51 08" src="https://user-images.githubusercontent.com/12051736/29135978-c070de88-7d33-11e7-94be-d6e536b3200b.png">

I have a post of this Pod type, when I edit the post, I can use the relationship field to choose a draft post, but when I save the post, the relationship isn't saved and the relationship field is empty.

**Comment by sc0ttkclark** [comment]
Can you clarify -- what post type is it related to?

**Comment by lougreenwood** [comment]
Standard Pods table-based CPT

**Comment by lougreenwood** [comment]
Update: I just went through and updated many of the draft posts to 'publish' and they appeared in the dropdown selector - no need to re-link after just changing the post's status.

**Comment by sc0ttkclark** [comment]
Oh that helps a ton, thanks!

**Comment by sc0ttkclark** [comment]
Fixed
