### ISSUE TITLE
Pods CSS files in frontend should neither be included in footer nor contain `!important` modifiers

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods#4412]
I could not find no way to override Pods CSS directives in the front end, such as

    .pods-form-front .pods-field-input, .pods-form-front .pods-field-label{
     float: none!important;
     width: 100%!important;}

IMHO, that's an unnecessary restriction, especially as Pods CSS file `wp-content/plugins/pods/ui/js/select2/select2.css` is included in the page footer rather than in the header and should therefore be addressed. 

Thanks.

**Comment by pglewis** [comment]
I'm not seeing those rules in any of our CSS source in a quick check of master, 2.x, and 2.7.  This might be due to dynamic rules changes via Javascript.  

We have also cut-down what's enqueued on the front-end for 2.7 as part of a major CSS refactor, it should only be enqueueing `pods-form` related styles on the front-end in 2.7.

**Comment by pglewis** [comment]
@nicdford / @JoryHogeveen: any ideas on what might be generating those `!important` directives?

**Comment by Digitale-Substanz** [comment]
This is the script inclusion statement in page footer:

`<link rel='stylesheet' id='pods-select2-css'  href='http://localhost:97/wp-content/plugins/pods/ui/js/select2/select2.css?ver=3.3.1' type='text/css' media='all' />`

However, your idea with dynamic JS changes seems to be the reason for the behaviour described. Need to mention, though, that this most likely is not caused by Pods but rather in my personal scripts. So, big sorry for troubling you guys! I guess, this issue can be closed/deleted for now.
