### ISSUE TITLE
Selected date is not added to the input field

### ISSUE THREAD

**Issue by cr101** [pods-framework/pods#4417]
I have a Date field type. When I select a date from the Datepicker the date is not added to the input field.
I'm using Pods 2.7.0-b-2 via Github Updater and Google Chrome Version 60.0.3112.90

![screenshot_17](https://user-images.githubusercontent.com/4064582/29255971-9fedff36-80fa-11e7-9fbe-343af1d9f1cc.jpg)

**Comment by quasel** [comment]
works for me in 2.7.9 but we had some changes to the date fields! 

Sorry for the late reply :/
