### ISSUE TITLE
Add new option to set a post type or taxonomy permalink structure apart from the default

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#442]
This would provide similar functionality to what this plugin offers, but it would be in with the other post type / taxonomy options.

http://wordpress.org/extend/plugins/custom-post-type-permalinks/

**Comment by jimtrue** [comment]
Is there a need to incorporate this into Pods if there is a plugin still being actively managed that we can recommend (and other SEO plugins that do this same functionality)? This question still comes up through our #support Slack Chat on a semi-regular basis (usually coinciding with someone releasing another 'this is the best URL structure for SEO!' article).
