### ISSUE TITLE
Save custom taxonomy terms for CPTs in wp_term_relationships

### ISSUE THREAD

**Issue by cr101** [pods-framework/pods#4421]
Is it possible to save the taxonomy terms associated with CPTs in `wp_postmeta` instead of `wp_term_relationships`?
Currently it's tricky to get the number of terms in a taxonomy since `count` in `wp_term_taxonomy` is not updated.

**Comment by jimtrue** [comment]
It's WP Core strategy to store taxonomy terms associated with CPT's in `wp_term_taxonomy` (which also tracks the `count`) and then to track the post object ID to the term ID per post in `wp_term_relationships`. `count` is properly updated for Pods Custom Taxonomy terms and posts. `wp_postmeta` isn't where anything related to the Taxonomy belongs. 

Do you have a valid reason to go against the normal way for handling taxonomies from WP Core?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! (and some stuff change in core anyway)
