### ISSUE TITLE
Duplicating Pods with Custom Field Suite Fields

### ISSUE THREAD

**Issue by azaleas** [pods-framework/pods#4425]
CPT created with pods framework is not duplicating custom fields, created with Custom Field Suite, while using duplication plugins like Duplicate Post.

Original topic: https://wordpress.org/support/topic/not-working-with-post-duplication-plugins/

@jimtrue suggested to create an issue for this topic. 

@mgibbs189 any thoughts?

**Comment by quasel** [comment]
why use pods and custom field suite? and not only pods instead? but anyway it should just work as it copies just the meta_values maybe ask their support!
