### ISSUE TITLE
Shortcode for images does not render

### ISSUE THREAD

**Issue by frontenddevguy** [pods-framework/pods#4431]
On a localhost (AMPPS) site I have tried using the shortcode:
[pods field="project_image"]

This outputs the image url as text.

I also tried:
[pods name="project"]{@project_image._img}[/pods] 
This causes all of the fields on the page to not render

Initially tried the above with Divi theme, then tested with Visual Builder, and finally with a bare bones site and basic text editor, and same results.

I have also tried different images (with short filename).

Only this field is not working.

**Comment by quasel** [comment]
either use [pods field="project_image._img"] or provide a slug or id for the shortcode! 

https://pods.io/docs/learn/shortcodes/pods/
https://pods.io/docs/build/using-magic-tags/

Sorry for the late reply, feel free to comment if you still have questions!
