### ISSUE TITLE
Pods Gravity Forms AddOn - not populating some fields

### ISSUE THREAD

**Issue by userphil** [pods-framework/pods#4434]
"Enable populating field values for this form using current post" in pods feed settings is checked.

When loading the form most fields populate with existing data, however check boxes, multi-select fields and address sub-fields do not populate with existing data.

Current versions
PODS - 2.6.10
PODS Gravity Forms Addon - 1.3
Gravity Forms - 2.2.5

**Comment by jimtrue** [comment]
@userphil This actually needs to go over in our Pods Gravity Forms GitHub. I have created an issue for you over there with my own findings:
https://github.com/pods-framework/pods-gravity-forms/issues/82
