### ISSUE TITLE
Date Field Causing Issues With >=< BETWEEN AND statements

### ISSUE THREAD

**Issue by InterPreneur** [pods-framework/pods#4436]
WordPress: 4.8.1
PODS: 2.6.10

//works

$params = array(
    'where' => 'tr_date >= "2017-08-01"'
);

//doesn't work!!!

$date = '2017-08-01';

$params = array(
    'where' => 'tr_date >= '.$date.''
);

// tried swapping single / double quotes, as well as using "%'.$date.'%" instead of '.$date.', as well as using 'tr_date BETWEEN '.$date.' AND '.$date2.'' (which works with direct strings, instead of php variables)

**Comment by quasel** [comment]
when dealing with dates it's always best to use `CAST( post_date as DATE )` as it's only stored as a string im the DB!
