### ISSUE TITLE
Beta 2.7: Clipping Issue for button on several fields in new Relationship Field

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4439]
Field Type and Related to:
<img width="575" alt="screenshot 2017-08-30 12 51 41" src="https://user-images.githubusercontent.com/3052875/29884758-71a59cd0-8d82-11e7-832a-10f5ac379e0f.png">

Selection Type and Format (Additional Options for Relationship Field):
<img width="560" alt="screenshot 2017-08-30 12 51 52" src="https://user-images.githubusercontent.com/3052875/29884800-90465c92-8d82-11e7-9b12-e0eebcb0526d.png">

Post Status (under Relationship Field, Additional Options):
<img width="576" alt="screenshot 2017-08-30 12 52 01" src="https://user-images.githubusercontent.com/3052875/29884827-ab23360c-8d82-11e7-9e27-07dd5251da83.png">

**Comment by jamesgol** [comment]
What are these buttons supposed to be?  I just looked for this and couldn't find any way to make buttons show up in those spots

**Comment by sc0ttkclark** [comment]
Add New

**Comment by jamesgol** [comment]
I've looked all over the place and I'm guessing there is some prerequisite for this to happen.  I'm running the release/2.7 branch and don't see any buttons next to these fields

**Comment by sc0ttkclark** [comment]
I believe add new is not on by default for existing fields

**Comment by pglewis** [comment]
This is marked reproduced but I have never seen this show up in the admin.  

Any deets to make it happen @jimtrue ?

**Comment by jimtrue** [comment]
This appears to have been cleared up in a subsequent CSS change. It's no longer happening on current 2.7.
