### ISSUE TITLE
select2 minimumInputLength (Performance Improvement)

### ISSUE THREAD

**Issue by jneto81** [pods-framework/pods#4444]
I need a way to set the minimumInputLength per field ( can be a hook )

`                minimumInputLength : 1
`
Default value is 1, and with a large number of posts, it takes a lot of time.

**Comment by jamesgol** [comment]
Same as #4445, these should be adjustable by a filter

**Comment by pglewis** [comment]
PR #4555 (so much chance for dyslexia among these issue/PR numbers)

**Comment by pglewis** [comment]
Done, and will be improved in #4561
