### ISSUE TITLE
select2  set delay option (Performance Improvement)

### ISSUE THREAD

**Issue by jneto81** [pods-framework/pods#4445]
I need a way to set the delay option, because now its 100 ms by default  and my wordpress almost die using the select2 search because it send several ajax request to get the response. ( i have a large posts table )

**Comment by pglewis** [comment]
This may be a good candidate for an advanced setting to override the default; whatever default we choose is likely to be sub-optimal for someone.

**Comment by jamesgol** [comment]
I think a filter to allow the select2 options to be adjusted is the right way to go.  That will allow advanced users to adjust without cluttering up the UI with too many options that most people don't use

**Comment by pglewis** [comment]
PR: #4555

**Comment by pglewis** [comment]
Done, and will be improved in #4561
