### ISSUE TITLE
JSON Output From PODS Endpoint Not Complete

### ISSUE THREAD

**Issue by qrahaman** [pods-framework/pods#4446]
I have two PODS (calibration and length) connected with a bi-directional relationship field.  When I output the JSON for the “calibration” endpoint, all of the custom fields are shown, including the relationship field connecting to the “length” pod.  That relationship field contains an array with an object that shows key/value pairs such as, the ID, title, taxonomies, etc for the “length” pod.  What I expected that object to also show were the custom fields defined for the “length” pod.  Those custom fields are missing.  The reverse is also true if I view the JSON output for the “length” endpoint.  I have enabled the READ via REST API checkbox  to no avail.  Is what I’m expecting to see not possible?

[Archive 4.zip](https://github.com/pods-framework/pods/files/1278807/Archive.4.zip)
[Archive 2.zip](https://github.com/pods-framework/pods/files/1278895/Archive.2.zip)

**Comment by quasel** [comment]
![image](https://user-images.githubusercontent.com/9464217/44932088-4756b600-ad64-11e8-8b00-53bb35d3140f.png)

just set the options you need - should work!
