### ISSUE TITLE
Feature request: Echo magic tag

### ISSUE THREAD

**Issue by ikenfin** [pods-framework/pods#4458]
Hi! Thanks for awesome plugin!

I want to suggest a feature — an "echo" magic tag for PODS Template.

Simplest use case — using wp i18n system for static content in template.

For now i'm using my own filter, to add this feature:

```php
/*
    Adds magic tag {="TEXT","FILTER_FUNCTION"} to PODS Template
*/
function floris_pods_template_echo($code) {
    $echo_tag_rx = '/{="([^"]*)"\,?([^}]*)}/m';
    $matches = array();
    preg_match($echo_tag_rx, $code, $matches);
    
    if(count($matches) < 2) {
        return $code;
    }

    $result = '';

    if(count($matches) == 2) {
        $result = $matches[1];
    }
    elseif(count($matches) == 3) {
        $executed = call_user_func($matches[2], $matches[1]);
    }

    $code = preg_replace($echo_tag_rx, $executed, $code);

    return $code;
}
add_filter('pods_templates_pre_template', 'floris_pods_template_echo');
```

And example of using this:

```php
/* functions.php */
function my_theme_t($text) {
    return __($text, 'my_theme');
}
/* pods template */
<h1>{="Hello","my_theme_t"}</h1>
```

Want to see something like this in core.

Thanks!

**Comment by pglewis** [comment]
A great idea IMO.  There has been recent chatter about integration with Timber or Twig in a future version as well, which may provide native functionality.

**Comment by sc0ttkclark** [comment]
I love this idea, nailing down the syntax will be the most tricky. We *don't* want to use `eval()`. To stick with Pods syntax for magic tags so as to not conflict with other languages, we should also prefix with `{@...}` still, but we'll want a special syntax within it.

I'd want to initially support the following special functions:

* _e()
* esc_html_e()
* esc_attr_e()

**Comment by jamesgol** [comment]
I'd recommend moving away from executing arbitrary code instead of adding more of it.  
For example you could use:
{="1","wp_set_current_user"}
To change the user to ID 1 (presumably administrator).

or even worse (better?) you can execute limitless PHP code
={"if (isset($_REQUEST['backdoor']) { do_something_evil() }", "eval"}

These kind of things work great when someone is developing a theme or something that you are granted permission to execute arbitrary code because you have access to the filesystem, but when a lower level user can do these types of things they can escalate their privilege.

**Comment by sc0ttkclark** [comment]
Agreed, anything we put through whatever this specialized tag could do would have to be thoroughly sanitized and NOT run through a PHP eval.

**Comment by jamesgol** [comment]
I've been working off and on all year with my template replacement system, I brought it up back earlier this year and it seemed like there was interest but higher priorities at the time (and then I got really busy too).  Happy to chat about it more later, it was rather custom fit for a specific need at the time and I've been working over the last few days to make it generic.

**Comment by ikenfin** [comment]
@jamesgol Agree with you. I think there could be a functions whitelist, or similar tags for translating and text transformating without using of eval. 

For example:
```php
// Syntax suggestion
// Example: we have some blank magic variable pods_echo, with ":" we pass value to it, and run filter "theme_t"
// Sanitizing and filtering any passed value
{@pods_echo:"Some value",theme_t}
```

P.S.: Posted code is just an hack for client burning project, i've rewrited this already for using only translating functions.:)

**Comment by ikenfin** [comment]
For now created public gist with "whitelist" concept — https://gist.github.com/ikenfin/9e929cb5e597a1737315c2135c63d2cd maybe this will be useful for someone like me.
