### ISSUE TITLE
Pods 2.7 RC1 Image Field max size bug?

### ISSUE THREAD

**Issue by pierluigiabramo** [pods-framework/pods#4463]
So like subject.. i think there is a bug.. add image field in cpt with max size es. 500 KB but in custom post edit i can still upload images of any weight..

**Comment by jimtrue** [comment]
Can you confirm if this is just a 2.7 issue or if it's also an issue in 2.6?

**Comment by pglewis** [comment]
This has been broken all along for KB, copy/paste error is converting the same as MB.  

https://github.com/pods-framework/pods/blob/40539a514d6524b9c40133760e4cb40aa8653d44/classes/fields/file.php#L792-L799

**Comment by pglewis** [comment]
Fixed and merged, #4485
