### ISSUE TITLE
Pods form field array key notices

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4466]
Happens in some cases when using `pods_form()` on the front-end with WP core fields when the object doesn't have any Pods fields.

Notice: Undefined index: options in /wp-content/plugins/pods/ui/front/form.php on line 24
Notice: Undefined index: options in /wp-content/plugins/pods/ui/front/form.php on line 35
Notice: Undefined index: options in /wp-content/plugins/pods/ui/front/form.php on line 36
Notice: Undefined index: options in /wp-content/plugins/pods/ui/front/form.php on line 39
Notice: Undefined index: help in /wp-content/plugins/pods/ui/front/form.php on line 125

**Comment by sc0ttkclark** [comment]
Fixed in 2.7
