### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ....../plugins/pods/classes/fields/file.php on line 588

### ISSUE THREAD

**Issue by dragondesigns** [pods-framework/pods#4471]
Hi there,

I've using PODS with Beaver Builder/Themer/ Themer PODS Add-on.

When I try to add an image field from a PODS custom post into the Beaver Themer Template, I get the above error. 

Regular text seems to be added without an issue.

**Comment by quasel** [comment]
are you using - https://github.com/pods-framework/pods-beaver-builder-themer-add-on?
Which way do you try to add the image? (Code example)
Which Version of pods do you use? 
Which Version of Beaver?
Which Beaver Module? 
Is your image field set to single or multiple images? 
how is you image field configured? (options, output as a gallery?) 

for issues it's always helpfull to provide details else it's hard to help and figure out if it's a bug related to pods!

**Comment by dragondesigns** [comment]
Hi,

Thanks for your reply.

I got it resolved by changing the image field set to single image, so all good!

Thanks again :)

**Comment by quasel** [comment]
Maybe I can prevent that for the future - you had a field set to multiple images but could select it for a single image field connection? or what cause the original issue?

**Comment by dragondesigns** [comment]
By default the field was set to multiple images it seemed - perhaps an error message explaining the cause of the problem would be useful to the user.

I also raised a ticket to Beaver Builder, and they were willing to discuss the issue with you to help resolve it.
