### ISSUE TITLE
Number Field with decimals

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#4472]
I ran into an issue:

Pod Field type was set to "Plain Number", and when the value contained a decimal, it caused a MYSQL error. Was working fine until today, only thing that changed was latest Wordpress update (4.8.2).

I changed the field type to "text" and it's now working. 

It was trimming off the decimal leaving the whole number, and right before that in the query, attempting to insert '%01.1f'- with no quotes, causing the error.

**Comment by leejacksonltd** [comment]
We are having exact issue. Suddenly stopped working over night. However we dont have the latest. Ive tested on as old as 4.7.6. Happens for both currency and number when there is decimal of 2.....

**Comment by leejacksonltd** [comment]
One thing we noticed. In a non cpanel based environment it works. Tested on TSO dev. However we did port a copy over to WP Engine and it still bugged out.....

**Comment by quasel** [comment]
@leejacksonltd  thx - copy your results from Facebook: 
$wpdb->prepare() can create unexpected and unsafe queries leading to potential SQL injection (SQLi). WordPress core is not directly vulnerable to this issue, but we’ve added hardening to prevent plugins and themes from accidentally causing a vulnerability. Reported by Slavco
This was updated in 4.8.2 BUT also the 4.7 received the patch too.

**Comment by leejacksonltd** [comment]
Yes thanks we are temporarily rolling back. We just came to same conclusion after reading https://wordpress.org/news/2017/09/wordpress-4-8-2-security-and-maintenance-release/
