### ISSUE TITLE
Allow setting the a global default setting for rel fields REST API result

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4475]
The current default response for all relationship fields over REST API is 2 levels deep and to return the full object:

<img width="576" alt="screen shot 2017-09-21 at 11 20 43" src="https://user-images.githubusercontent.com/12051736/30691310-40eef34a-9ebf-11e7-9f7e-d364355f66c4.png">

For systems where relationships are extensively used or there are many records, this can create un-necessarily large REST responses.

It would be very useful if there were a config setting to globally override what this should be for all new relationship fields. For example, I would set it to 1 level deep and return ID only.

**Comment by jimtrue** [comment]
@lougreenwood I personally agree with you that we should only return the id and encourage people to open different rest api endpoints for the connections (like taxonomy is returned, I believe). But you think like a developer and realize that you're trying to optimize what is being queried and only query the connections you need when you need them.

But folks who aren't as aware (or are new to REST API), tend to want to get at least that next level of connection (the fields from the other side of the relationship). Would you like this maybe as a Pods CONSTANT in the wp_config.php? (Settings which will be migrated to a Pods Admin, Settings page at some point in the future, probably after Group Fields). Or would you rather see this in the REST API setting when you turn on REST API access for the Pod (not at the field level but at the Pod Level)?

**Comment by lougreenwood** [comment]
Personally, for my use case, CONST in wp_config.php would be fine for me. 👍 

Obviously, having this as a nice, pretty UI config in WP Admin when enabling REST would be handy and useful for other users, but probably not essential for now.

**Comment by jimtrue** [comment]
Cool, thanks for that feedback. The CONST might be the easiest to implement and migrate to the Settings page #2197 when that's on the RoadMap.

**Comment by sc0ttkclark** [comment]
I know there is a filter for depth (override for all fields), but i don't think there is one for response type, I'll check.

**Comment by sc0ttkclark** [comment]
Added a new hook https://github.com/pods-framework/pods/pull/4476

**Comment by lougreenwood** [comment]
@sc0ttkclark Cool, but it looks like this is on a per-field basis and not global for all fields?

**Comment by sc0ttkclark** [comment]
* The depth hook is: pods_rest_api_depth_for_relationship_response
* The output type (id) hook is now: pods_rest_api_output_type_for_relationship_response

**Comment by sc0ttkclark** [comment]
These hooks are overrides, so yes it's still per field and not the ability to change it on adding a new field -- it just overrides when the code itself runs.

**Comment by sc0ttkclark** [comment]
I'm also not opposed to changing the default field option here to depth = 1 and output_type = id

**Comment by sc0ttkclark** [comment]
Also if it seems like I don't want to add filters for the default field values, you're correct. I'm hoping to have better handling for defaults in Pods 2.8 with the introduction of Pods_Object class structures which would make that much cleaner.

**Comment by lougreenwood** [comment]
I've just sat down to  manually update all 50 of my Pods (each probably has ~3 rel fields each) to ID only, 1 deep - so this issue has returned to my mind :)

Here's my perspective as a Pods user:

In relation to what @jimtrue said about new users, Initially I thought it was a reasonable stance - but I've now been reflecting on this for a few days now and I now wonder if just changing the default to ID only, 1 deep default (as suggested by @sc0ttkclark) may actually be a better choice, even for the inexperience API developers...

If a user is advanced enough to know/need the API, they'll probably appreciate the improved performance of ID only 1 deep than the potential risk that some other another might be confused when they don't receive a bunch of embedded objects by default.

Arguably, it's also better to teach an inexperienced developer who's likely working with an API for the first time (presumably the user-segment Jim's mindful of) to be efficient and only retrieve objects they need, rather than teach that they should always include everything...?

**Comment by lougreenwood** [comment]
Another thought just hit me too....

Since relationship fields don't respect whether the related pod has REST API turned on, defaulting to FULL/2 is a potential data leak. This is because, that default makes it possible to fetch data about a pod which should be private (REST disabled) if some other related Pod has REST enabled, e.g:

I have 2 Pods:
* 'Private' has REST disabled
* 'Public' has REST Enabled
    * Public has a related field linking to private

As a malicious actor, I could scrape the 'Public' endpoint and collect full data objects for records in the 'Private' Pod - possibly not all data (unless public records link to ALL private), but still more than I should have access to...

**Comment by jimtrue** [comment]
Should it actually return the href json endpoint to the post/posts on the other side of the equation? Wouldn't that be more accurate and appropriate since, if you don't have access to the other post type, then you couldn't return anything or at least the JSON would return a more appropriate answer of 'you don't have access to that data'.

**Comment by lougreenwood** [comment]
@jimtrue Actually, it seems that your links suggestion is built into the WP JSON REST API design:

https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/

AFAIK, Pods supports neither, but adding support (and removing the ID/Full/Depth fields) for `_links` & `_embed` properties would solve this and bring Pods more inline with WP REST.

It seems that an `_embeddable` property would be needed to allow `_embed`, so maybe this could be a toggle in Pods (again, replacing Full/ID/Depth) to allow controlling this. Ideally, this would be disabled by default if the related Pod does not have REST enabled.
