### ISSUE TITLE
PODS 2.7RC1 Roles component goes in loop when save

### ISSUE THREAD

**Issue by pierluigiabramo** [pods-framework/pods#4477]
![schermata 2017-09-22 alle 09 46 33](https://user-images.githubusercontent.com/17725824/30734472-95256310-9f7b-11e7-943c-86968b63fe11.png)

**Comment by sc0ttkclark** [comment]
I noticed this too, is it just 2.7 or is it 2.6.x too?

**Comment by pierluigiabramo** [comment]
Only in 2.7

**Comment by sc0ttkclark** [comment]
Great, thanks for the quick reply. I'll get it fixed :)

**Comment by pierluigiabramo** [comment]
Thank's! Scott.. when you have time take a look #4463

**Comment by pglewis** [comment]
Should be fixed in #4492
