### ISSUE TITLE
Pods 2.6.11 Breaks Duplicate Post 3.2

### ISSUE THREAD

**Issue by techprogrammer** [pods-framework/pods#4482]
Wordpress 4.8.2
Pods 2.6.11
Duplicate Post 3.2
https://wordpress.org/plugins/duplicate-post/

Cloning a custom post type results in either a sql error or the pods fields not being cloned.

It worked ok with Wordpress 4.8.1, Pods 2.5.3, Duplicate post 3.2

Looking at this sql error, I notice that the t.id= is missing the post number after it.

================

[24-Sep-2017 11:21:03 America/Los_Angeles] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND ( `t`.`post_type` = "deals" ) AND ( `t`.`post_status` IN ( "publish" ) ) )' at line 19 for query SELECT
               
                DISTINCT
                t.*, d.*, `vendor_d`.`id`              AS avnd_id, `vendor`.`name`              AS avnd_name
                FROM `wp_posts` AS `t`
               
                    LEFT JOIN `wp_podsrel` AS `rel_vendor` ON
                        `rel_vendor`.`field_id` = 176
                        AND `rel_vendor`.`item_id` = `t`.`ID`
 
                    LEFT JOIN `wp_terms` AS `vendor` ON
                        `vendor`.`term_id` = `rel_vendor`.`related_item_id`
               
               
                     LEFT JOIN `wp_pods_vendors` AS `vendor_d` ON
                        `vendor_d`.`id` = `rel_vendor`.`related_item_id`
                
                LEFT JOIN `wp_pods_deals` AS `d` ON `d`.`id` = `t`.`ID`
                WHERE ( ( t.id =  ) AND ( `t`.`post_type` = "deals" ) AND ( `t`.`post_status` IN ( "publish" ) ) )
               
               
                ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
                LIMIT 0, 15 made by do_action('admin_action_duplicate_post_save_as_new_post'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, duplicate_post_save_as_new_post, duplicate_post_create_duplicate, do_action('dp_duplicate_post'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, bv_copy_post, PodsAPI->save_pod_item, PodsAPI->save_wp_object, call_user_func, PodsAPI->save_post, wp_update_post, wp_insert_post, do_action('save_post'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WPSEO_Link_Watcher->save_post, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, shortcode_vendor_jump, pods, Pods->__construct, Pods->find, PodsData->select, pods_query, PodsData::query

**Comment by jimtrue** [comment]
I just tested with Duplicate Post 3.2, Pods 2.6.11 and received no errors and all custom meta including relationships copied fine. Do you perhaps have custom code or filters written around Duplicate Post to handle any kind of custom code?

**Comment by dannywnuk** [comment]
I'm having a problem with button "add image" can you tell me why is not working? Every time when I'm trying to add image it's empty.

**Comment by jimtrue** [comment]
> I'm having a problem with button "add image" can you tell me why is not working? Every time when I'm trying to add image it's empty.

@dannywnuk I'm not sure, but I think you just reached out to me with this question on Facebook. Typically with GitHub, unless you're having the same issue as the person who opened the ticket, you should create a new one and I definitely needed the more detailed information you provided in your Facebook message. I've also passed along our Support details: https://pods.io/support/ and the fastest way to get help, https://pods.io/chat/

**Comment by dannywnuk** [comment]
Yes I did and I have to say you where right. Another plugin was making a
problem. I'm having a big project that's why that was so important for me.
Thank you again.

**Comment by chitwarnold** [comment]
Just Use Post Duplicator by www.metaphorcreations.com. Here is the Link on Wordpress Plugin Site. https://wordpress.org/plugins/post-duplicator/

This worked for me when Duplicate Post was Acting up

All The Best.

**Comment by techprogrammer** [comment]
Wordpress 4.9.5

Post Duplicator 2.2 when Duplicating a post, does nothing for me.

Duplicate Post 3.2.2 at least duplicates the post and just a couple fields, with the rest of the pods fields being empty.
