### ISSUE TITLE
Can't read private pod post that the logged-in user authored

### ISSUE THREAD

**Issue by siy34** [pods-framework/pods#4488]
I’ve set capabilities for logged in non-admin users to be able to read private posts but when I login as one of these users I can view all private pod posts except the ones I authored.

**Comment by siy34** [comment]
Just did some more testing and found that editors and admins can read all singular pod pages just fine. A custom user group that I have on my website which has 'read_private_posts' enabled in their capabilities may read all singular pod pages except the ones they authored.

**Comment by jimtrue** [comment]
@siy34 Are you using Custom Capabilities or 'post', 'page' capabilities? Please provide more specifics about the capabilities you've set and the roles so we can more properly replicate the issue you're experiencing. You can take screenshots and upload here.

**Comment by jimtrue** [comment]
Need both the settings for your Pods post-types under Advanced Options and whatever you have configured for the capabilities for those posts.

**Comment by siy34** [comment]
The pod is using 'post' capabilities (under advanced options) and the custom user role I created has all post related capabilities enabled including (publish/read/write/edit) (posts/private posts).

I noticed that only when I changed the "read" capability (i.e. the one that allows user to access wordpress backend) to true can my custom user role view the singular pod post they authored.

**Comment by jimtrue** [comment]
'read' is required. If you look at the Role vs. Capability table (https://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table), that's the one capability that is on for every single Role. 

Would you mind providing a screenshot of what you've configured as the capabilities for the access role? Might help in troubleshooting.

**Comment by jimtrue** [comment]
Sweet, glad to hear it. BTW, you might find [Members Plugin](https://wordpress.org/plugins/members/) a little easier to read/manage all this stuff with. I personally prefer it over our 'Roles & Capabilities' component.
