### ISSUE TITLE
PODS "Image / File / Video" field returns “False” in the WP API for some images.

### ISSUE THREAD

**Issue by obedparla** [pods-framework/pods#4496]
I'm using PODS to create custom post types. I have a custom post type and a field `thumbnail_img` within it of the type "File / Image / Video".

When I access the WP RESTful API I can see all of the custom post fields, including the PODS field, but the thumbnail_img field's value is "false". Even though an image has been added.

I tried adding the ?_embed to the API call with no success. After asking for support in the slack channel @jimtrue tried to test and he could see the data for an image in the API.

I've been testing a few things and noticed that any new image I upload works correctly (I get data on the API), but any of the images I had before don't (value is "false"). I can't remember if I had PODS installed when I uploaded those images, could it be that PODS creates the API endpoint when the image is added, so if an image is added when pods isn't installed/disabled, the endpoint will never be created? 

I also uploaded all those images together (selecting all of them and uploading). And I'm using Kraken.io to crunch the image's size. 

Wordpress version: 4.8.2
PODS: 2.2.3

**Comment by obedparla** [comment]
I've been working today with PODS and I'm trying to use the "File / Image/ Video" field again. I can confirm that the case I mentioned above of PODS not creating endpoints for old images doesn't seem to be the case. I'm adding new images (with pods enabled and working) and some images appear on the API and others don't, seems arbitrary to me.I switch from one image to another and it goes from working to giving me "false" without apparent reason, for 2 images of similar file size (6kb or so). 

Sorry for not giving good guidance on how to reproduce this bug... If I nail it down I'll give instructions here.

**Comment by quasel** [comment]
Did you work it out? Anyway a long time has passed gonna close the issue! 
Sorry for the late reply, feel free to comment if you still have questions!
