### ISSUE TITLE
Saving Pods templates is broken

### ISSUE THREAD

**Issue by jamesgol** [pods-framework/pods#4500]
Appears to be caused by https://github.com/pods-framework/pods/commit/9698a88364073e4f9e43348f0d839c2afc0aad4a

( ! ) Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/pods/classes/PodsMeta.php on line 1209
--

1 | 0.0033 | 436200 | {main}( ) | .../post.php:0
2 | 0.4352 | 28830320 | edit_post( ??? ) | .../post.php:193
3 | 0.4481 | 28834392 | wp_update_post( ???, ??? ) | .../post.php:378
4 | 0.4488 | 28844880 | wp_insert_post( ???, ??? ) | .../post.php:3583
5 | 0.4976 | 29928560 | do_action( ???, ???, ???, ??? ) | .../post.php:3510
6 | 0.4976 | 29928936 | WP_Hook->do_action( ??? ) | .../plugin.php:453
7 | 0.4976 | 29928936 | WP_Hook->apply_filters( ???, ??? ) | .../class-wp-hook.php:323
8 | 0.5033 | 29908624 | PodsMeta->save_post( ???, ???, ??? ) | .../class-wp-hook.php:298

Simple fix is to just return if (!$pod) but need to dig a bit more.

**Comment by pglewis** [comment]
I'm not reproducing this on the current 2.7 with a quick new template save.  We'll need to find out what's different.

**Comment by jamesgol** [comment]
Weird.  I'll have to spin up another test environment to see if I can reproduce it there.  Only Pods installed.

**Comment by jamesgol** [comment]
On a fresh new install this didn't happen until I enabled WP_DEBUG.  Now I'm wondering if '_pods_template' should be added to the blacklisted types here https://github.com/pods-framework/pods/blob/release/2.7/classes/PodsMeta.php#L1155-L1159

I'm really curious if someone who is not having this issue could setup a breakpoint around line 1203 in PodsMeta->save_post() https://github.com/pods-framework/pods/blob/release/2.7/classes/PodsMeta.php#L1196-L1205 and tell me what $pod or self::$current_pod is

Presumably it should be false unless there is some other way that '_pods_template' is a valid pod.

**Comment by jamesgol** [comment]
It might be more appropriate actually to have the frontier code add a filter on 'pods_meta_save_post_blacklist_types' to add '_pods_template' to the array.  Since that post_type is technically specific to the "frontier" template component

**Comment by jamesgol** [comment]
When I have a chance, I will create a branch to fix this and then a PR.  Should be able to create a couple tests to reproduce the error and then fix it up
