### ISSUE TITLE
Autocomplete/List view broken with "Other WP Objects"

### ISSUE THREAD

**Issue by jamesgol** [pods-framework/pods#4504]
Testing stuff on #4484 I discovered that Autocomplete and List view did not pull up anything for most (all?) of the "Other WP Objects".

One of the fields was initially a multi select and once the setting was switched to List view it would not actually remove the entry when removing it and saving.

**Comment by jamesgol** [comment]
Same issue with "Predefined lists"

**Comment by pglewis** [comment]
- [ ] User Roles: works properly when adding a new post, logic incorrectly forces it into ajax mode on saved records

**Comment by pglewis** [comment]
Packge for testing: https://gist.github.com/pglewis/530b85c56fa0a3496c1874cb9bfb7734

**Comment by pglewis** [comment]
https://github.com/pods-framework/pods/blob/224ac16/classes/fields/pick.php?ts=4#L809-L825

**Comment by pglewis** [comment]
I have had some cases where `$ajax` is set correctly if you are editing a new post and it works until after the first save.  The package with a single field seems to behave that way for me right now; the other package with more fields ceased working even on a new post, could be some interaction with more fields on the page.

**Comment by pglewis** [comment]
Also, this is a pre-existing issue.  2.x has the same problem if you use autocomplete with either single or multi-select.  You may be able to select and save the very first time on a new post, but it will not work on subsequent page loads due to forcing ajax mode in select2.

**Comment by pglewis** [comment]
Now gets puntable.  I'd love to fix every 2.x bug before 2.7 goes out but I have to draw the line in the sand somewhere.

**Comment by pglewis** [comment]
If it's a fair assumption that the objects that are breaking with select2 could just be forced to never set the ajax flag then this could probably be quick-patched to at least not break in 2.7.  But I believe how we set the ajax flag needs a rethink from the ground up.

**Comment by sc0ttkclark** [comment]
We need a conditional for 'simple' wp rel objects to not support AJAX.

**Comment by pglewis** [comment]
#PR: #4978
