### ISSUE TITLE
JS errors when using pods form with 2.7

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#4514]
Hi Pods team
I've encountered an error when using pods form with 2.7. It causes problems to wysiwyg fields. Could you have a look please?

https://pods.io/docs/code/pods/form/ 
![wysiwyg](https://user-images.githubusercontent.com/17201482/31602834-0d242918-b256-11e7-821d-037428708957.jpg)

Thanks

**Comment by pglewis** [comment]
`media-audiovideo` isn't a Pods JavaScript file, this is likely an issue with another plugin.

**Comment by coding-panda** [comment]
Hi pglewis, 

Thanks for your reply.

I just created a brand new WP site, deleted all plugins and installed Pods 2.7 only. It still gives me the same error.  Pods 2.6.11 doesn't have this problem. Could you have a look again please? Thanks.

Best Regards

**Comment by pglewis** [comment]
We'll get to the bottom of it.  In case it turns out difficult to reproduce: 

What is the underlying Pod type and how are you calling Pods Form?  

Are there any key options I may need include in order to reproduce?  

Does the error always happen on page load, or is it the result of some ajax activity?

**Comment by coding-panda** [comment]
I tried the extension to Page and an Advanced Custom Type, they both produce the same error. Here is the migration code:

{"meta":{"version":"2.7.0-rc-1","build":1508179185},"pods":{"12":{"id":12,"name":"page","label":"Page","description":"","type":"post_type","storage":"table","object":"page","alias":"","fields":{"test":{"id":13,"name":"test","label":"Test","description":"","help":"","class":"","type":"wysiwyg","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_repeatable":0,"wysiwyg_allowed_html_tags":""}},"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","rest_base":"page","read_all":"0","write_all":"0"},"14":{"id":14,"name":"wysiwyg","label":"Wysiwygs","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":15,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_repeatable":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":""},"created":{"id":16,"name":"created","label":"Date Created","description":"","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","datetime_format":"ymd_slash","datetime_time_type":"12","datetime_time_format":"h_mm_ss_A","required":"0","unique":"0","datetime_repeatable":"0","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","datetime_type":"format","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"modified":{"id":17,"name":"modified","label":"Date Modified","description":"","help":"","class":"","type":"datetime","weight":2,"pick_object":"","pick_val":"","sister_id":"","datetime_format":"ymd_slash","datetime_time_type":"12","datetime_time_format":"h_mm_ss_A","required":"0","unique":"0","datetime_repeatable":"0","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","datetime_type":"format","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"content":{"id":18,"name":"content","label":"Content","description":"","help":"","class":"","type":"wysiwyg","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""}},"show_in_menu":"1","label_singular":"Wysiwyg","pod_index":"name","hierarchical":"0","ui_style":"post_type","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":{"0":"name","2":"modified"}}}}

**Comment by pglewis** [comment]
Probably not enqueueing something on the front end that we need to.  `wp.media.view.settings` is set to an empty object in the 2.7 branch.  Just haven't tracked down the culprit yet.

**Comment by coding-panda** [comment]
Cool. I believe that you will fix it soon. Thanks.

**Comment by pglewis** [comment]
@coding-panda: Are you on 4.8.2?  Suddenly I'm not seeing this error and it was 100% reproducible for me digging into it last week.

**Comment by pglewis** [comment]
Ehn... disregard.  After changing branches a few times it's showing back up again.

**Comment by pglewis** [comment]
PR: #4535

**Comment by pglewis** [comment]
Very pesky bug and a good find, this definitely needed fixing before release.  Everything should be good, you'll want to ensure you clear any local cache after updating to make sure scripts all get reloaded.  Let us know if there are any lingering issues.

**Comment by coding-panda** [comment]
Brilliant! That problem is sorted. Thanks for your hard work.
I'm not sure if you are bothered about this one. It gives an error on FireFox but the forms still work. Basically, I have two forms at the same time with the two Pods I pasted above:
			$mypod = pods( 'page' );
			echo $mypod->form(); 
			$my1pod = pods( 'wysiwyg' );
			echo $my1pod->form();  
If I submit the second one, the console will show: TypeError: jQuery(...).datetimepicker is not a function

**Comment by pglewis** [comment]
@coding-panda: Can you extract that info out into a new issue?  It's possibly unrelated to this one and best for the issue history if it has its own issue to keep issue conversation from getting confused.   Also, if you can check the behavior on 2.x to see if it's newly introduced in 2.7 or pre-existing.

**Comment by coding-panda** [comment]
@pglewis I just tested it with 2.6.11, worked perfectly. I will create a new issue. Thanks
