### ISSUE TITLE
Duplicating posts doesn't trigger pods_api_post_save_pod_item

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4528]
It seems that when duplicating a post (Pods::duplicate() - https://pods.io/docs/code/pods/duplicate/) the `pods_api_post_save_pod_item` action hook isn't triggered.

Ideally the hook would be triggered and `$is_new_item` would = true.

**Comment by lougreenwood** [comment]
`pods_api_post_save_pod_item` is now triggered, but it appears that it still doesn't return `$is_new_item = true`.

**Comment by sc0ttkclark** [comment]
Resolved in #4582
