### ISSUE TITLE
Feature Request - Use default value if blank

### ISSUE THREAD

**Issue by nicholmikey** [pods-framework/pods#4531]
I am requesting a new feature 'Use default value if blank' to be added to the Pod's Advanced options tab. 

This is for cases where pods have many posts with the same field values, and it would be handy to set those values in a shared location (Default value). 

For example I have a footer that is almost always the same, and I would like it to always use the default value unless I specifically set something.

**Comment by nicholmikey** [comment]
For now I have added this functionality with a filter: 

`add_filter('pods_api_pre_save_pod_item_french-email', 'my_pre_save_function', 10, 2); 
function my_pre_save_function($pieces, $is_new_item) { 
    $fields = $pieces[ 'fields' ];
    foreach ($fields as $field)
    {
        $fieldName = $field['name'];
        $fieldValue =  $field['value'];
        $defaultValue = $field['options']['default_value'];
        
        if(empty($fieldValue))
        {
            $pieces[ 'fields' ][ $fieldName ][ 'value' ] = $defaultValue;
        }
    }
    return $pieces; 
} `

**Comment by quasel** [comment]
until I missed something we have a default value - and it's prepopulated! But maybe that's a newer addition ;)
