### ISSUE TITLE
featured image woocommerce product category not showing in template

### ISSUE THREAD

**Issue by Vanbrent** [pods-framework/pods#4532]
So I used the featured image to add an image to a woocommerce product category. I have extended the prod_cat with an extra field so in the pods templates it would show the fields that are used in prod-cat.

I have looked for a way to display the image. Normally this line: <img src="{@thumbnail_id._src} "/> would work. Somehow it does not work. but maybe it does not define the term before getting the image in the template. 

Woo writes that normally (not using pods templates) but maybe something like an archive page you should use code like: 

add_action( 'woocommerce_archive_description', 'woocommerce_category_image', 2 );
function woocommerce_category_image() {
    if ( is_product_category() ){
	    global $wp_query;
	    $cat = $wp_query->get_queried_object();
	    $thumbnail_id = get_woocommerce_term_meta( $cat->term_id, 'thumbnail_id', true );
	    $image = wp_get_attachment_url( $thumbnail_id );
	    if ( $image ) {
		    echo '<img src="' . $image . '" alt="' . $cat->name . '" />';
		}
	}
}

Adding my own image field with pods to the prod_cat works like a charm. but getting the featured image failed

**Comment by jimtrue** [comment]
Can you please share the contents of the template you created that didn't work, @vanbrent ?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
