### ISSUE TITLE
Select2 version incompatibility with The7 theme

### ISSUE THREAD

**Issue by hsingh56** [pods-framework/pods#4541]
relationship list field does not show selected items. see attached pods  and JS screenshot
![capture1](https://user-images.githubusercontent.com/1814961/32274784-8b86e0a4-bf2e-11e7-813e-bb190387da74.PNG)
![capture2](https://user-images.githubusercontent.com/1814961/32274785-8bb7e938-bf2e-11e7-8485-1fbf3bbabee1.PNG)

**Comment by pglewis** [comment]
We need steps to reliable reproduce the error: 

- the pod type and its fields (a package export can be helpful there)
- where the field is being displayed (front end form?  back end?) 
- any other information that may be important to causing it to happen

This isn't an error we've encountered before so we need to find the magic combination that makes it show up.

**Comment by hsingh56** [comment]
Hi, Yes it is for 2.7 branch (i wanted to utilise the relationship list functionality)

I have tested this and can confirm that it is an issue of number of items to load from related pod, if we have more than 30 items in the related field, it stops working. (perhaps something reported here https://github.com/pods-framework/pods/issues/4505) 

I have 2 pods 
1) Portfolio and 
2) Itinerary Days.
I am trying to show multiple "itinerary days" posts in Portfolio (between 10 - 15 in each portfolio item) and i will have around 20 portfolio items and itinerary days posts will be more than 200!! (workaround for repeater field)

1) Fields are not showing in the back end when adding/ editing pod. pod type - Relationship Field > Multiple Select > List View

2) see attached, if i reduce post to less than 30 (published), it shows fine otherwise it is blank
![less than 30 items](https://user-images.githubusercontent.com/1814961/32311422-872ba306-bfbe-11e7-9a73-7aab2f52973b.PNG)
![27 published items](https://user-images.githubusercontent.com/1814961/32311423-8785b4fe-bfbe-11e7-888b-211a899a747d.PNG)
![when more than 30 items](https://user-images.githubusercontent.com/1814961/32311424-87f46b2e-bfbe-11e7-8522-0567096a5197.PNG)

3) also attached is pods export (txt), I have one new pod and one extended pod
[PODS EXPORT.txt](https://github.com/pods-framework/pods/files/1436634/PODS.EXPORT.txt)

hope i have explained it well. many thanks

**Comment by pglewis** [comment]
I think there is a select2 version conflict going on here.  2.7 has moved to select2 4.0 and the error you're getting shouldn't happen on that version.  Probably one of two things: either an older version of select2's js is being cached by the browser or some other plugin is using select2 3.x (can be tested by disabling other plugins).

**Comment by hsingh56** [comment]
hi, yes you are correct. I am using The7 theme and it is using select2 3.7 version!! so deactivating plugin does not help. i have theme's latest version.

i am extending one of the theme's custom post type (portfolio).

**Comment by jimtrue** [comment]
Could you Child Theme this to un-enqueue their outdated version of Select2 and only load our updated version until the theme updates with the current version? You would also run into this issue with practically any plugin using the newer version of Select2.

**Comment by pglewis** [comment]
This is frustrating byproduct of select2 updating with changes that aren't 100% backward compatible but keeping the same name for both versions in the global namespace.  

We rely too much on it right now to drop it completely (which I'm mad enough to want to do) but I think we should move to https://github.com/woocommerce/selectWoo

**Comment by pglewis** [comment]
Also, I predicted this problem in May and set out to encapsulate our copy of select2 in #4178.  Unfortunately there are complications with trying to pull it out of the global space due to the CSS and translation dependencies and that issue had to die, unfulfilled.

**Comment by pglewis** [comment]
Fix for testing in #4546

**Comment by pglewis** [comment]
Even if the PR resolves the conflict between your theme and Pods you have a high risk of future conflicts with other things.  We need to move forward with updates but don't want to be the ones that signal the incompatibility so we'll do an end-run around this problem once and for all (hopefully).  Not every theme or plugin is going to do that.

**Comment by hsingh56** [comment]
thank you. I have manually updated the select2 to version 4 in the theme and its works fine (nothing has broken so far).

i could in fact create a new pod instead of extending the pod provided by the theme but then i lose the various functionality offered by theme for custom post type (slider, page title, custom footer etc.) 

thank you for your support!

**Comment by pglewis** [comment]
Just make sure you are properly child-theming for you change, don't change your theme's code directly as you'll either have your changes overwritten at the next update, or worse decide not to update anymore.  You're best best is to contact the theme's author and let them know about the sticky compatibility probs coming as more people adopt select2 v4.  

Regardless, we should now play nice no matter what other versions of select2 are out there for now.
