### ISSUE TITLE
Custom Taxonomy Creation in v2.7

### ISSUE THREAD

**Issue by leepeterson** [pods-framework/pods#4543]
![screen shot 2017-11-01 at 9 03 19 pm](https://user-images.githubusercontent.com/972141/32305357-7a803b58-bf4b-11e7-9ba9-eceb70ea4a73.png)

I expect these options to be more yes/no based. Both seem to be "yes". 

The tooltip content says that WP taxes don't support this natively, then the first option appears to be a native solution which is contradictory to what the tooltip just said. It's confusing from a UX standpoint. 

The solution here is to prefix each option with "Yes, meta-based..." and "Yes, table-based" and "No, no extra fields".

**Comment by JoryHogeveen** [comment]
This seems to be an old label indeed. Thanks for noticing!

**Comment by sc0ttkclark** [comment]
Fixing

**Comment by JoryHogeveen** [comment]
Oh, already made a PR

**Comment by sc0ttkclark** [comment]
Fixed in #4609, not sure yet if it's going into 2.7, pending @pglewis's approval and tests running.

Please verify at your leisure too if it's looking as you'd expect now too.

**Comment by leepeterson** [comment]
Excellent.
