### ISSUE TITLE
PODS-Framework/ Beaver Themer Add-on/ Pods Beaver Themer Add-on

### ISSUE THREAD

**Issue by lmichd2d** [pods-framework/pods#4552]
Hey, Everyone out there using Beaver Themer with PODS, I am wondering if you are facing the problem where the Theme Layout just go blank after creating PODS where they have a relationship with one another. Example, create pod-A and then pod-B. Then Pod-A has a field AAA that has relationship with Pod-B with field BBB, making a bidirectional relationship.  After creating both PODS A & B and their bidirectional relationship, I can still use the Beaver Themer to edit the layout. The editing fields and screens works alright. The moment I entered values into PODS A & B, the Themer breaks down and clicking on the Theme Layout will produce a blank page. No layout, rows, modules or columns available for edit. 

The moment I removed the field AAA and field BBB, the Theme Layout starts to function normally allowing editing on it. If you have a solution to this problem, kindly share it with me, please.

**Comment by jimtrue** [comment]
@lmichd2d You've posted this in our general GitHub issues and this should be posted directly in the Themer Add On Issues list: https://github.com/pods-framework/pods-beaver-builder-themer-add-on/issues/new
