### ISSUE TITLE
Pods, could create, in the WordPress Table, relationships fields. Now does not.

### ISSUE THREAD

**Issue by acosior** [pods-framework/pods#4564]
Pods, could create, in the WordPress Table, relationships fields. Now does not.
It is very important to be able to query the tables with the plugin wpData Tables, and to be able to edit the values field’s much faster by updating queries SQL.

**Comment by sc0ttkclark** [comment]
Can you clarify? We store all relationship data for post types in the post meta using the following keys:

* `_pods_{field_name}` stores the full serialized array of the values as input (in the order input)
* `{field_name}` individual meta records for each related item

**Comment by sc0ttkclark** [comment]
We also have an optimized relationship table `wp_podsrel` that stores the related items using the following schema:

* `pod_id` The pod id of the relationship field
* `field_id` The field id of the relationship field
* `item_id` The item id being related **from**
* `related_item_id` The item id being related **to**

**Comment by jimtrue** [comment]
@acosior You also posted this on our Support Forum at pods.io. Sounds like you're actually using an Advanced Content Type for your tables. Advanced Content Types don't 'talk' to the WordPress tables so much as they are tables external to the WordPress tables. They don't write to `wp_posts` or `wp_postmeta`

**Comment by jimtrue** [comment]
Thus, if you're using a plugin that talks to the WordPress tables (https://wpdatatables.com/), it's not going to work for you in this type of a situation, because it communites with posts and postmeta and Advanced Content Types does not. You would need to use traditional Custom Post Types to organize your content.

**Comment by acosior** [comment]
Well, but it would not be possible for PODS to write the Relationsships fields in the WordPress ACTs tables. This way you could query those tables with all the fields on the ACT. This would need to change the code of PODS that writes the tables WP for the ACTs, so that also add the columns corresponding to the fields relationships.

**Comment by sc0ttkclark** [comment]
What you're looking for is a new feature we're working on called Simple Relationship Storage #3315. I'm going to close this issue in favor of that one. It's slated for 2.8 if all goes well.
