### ISSUE TITLE
Empty date field type output a value

### ISSUE THREAD

**Issue by agileware-ploy** [pods-framework/pods#4584]
I have created custom fields called closing_date that attach to custom post type using Pods. Allow empty values is enabled for date field. It shows as blank field in the post type when edit it. However, the date is displayed as "30 November -0001" when I view the post.

How can I wipe out/not show the date if there is no value set for that date field.

Cheers

**Comment by JoryHogeveen** [comment]
@agileware-ploy 
How are you displaying the field?

**Comment by agileware-ploy** [comment]
@JoryHogeveen 
This is the way I display the field in Pods Template.

[if closing_date]
	<p><strong>Closing date</strong>: {@closing_date}</p>
[/if]

If works fine for text field. However, seems like it does not work for date field, it now outputs 1 January 1970.

Thank you.

**Comment by JoryHogeveen** [comment]
Might be related to: #4227 
Are you on the 2.6.x version of the plugin?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
