### ISSUE TITLE
Required fields in Pods causing issues

### ISSUE THREAD

**Issue by Brian-Milnes** [pods-framework/pods#4586]
Over the last couple of days I have had some problems in performing an WP All Import of data into a Pod created CPT.
I am pretty familiar with using WP All Import, using it fairly frequently on another WP site which has 20,000 records in EDD Downloads CPT.
The failure of the Import was caused, it transpires, by the Required field marker used in Pods. When manually removed, the Import worked as expected.

This same problem is occuring in other component operations, too. Gravity Forms not completing all required Pods fields will leave the CPT in a "incomplete" state (404 error when trying tp view, but editable normally)

**Comment by jimtrue** [comment]
@Brian-Milnes We discussed this in email, but I'm reiterating it here: If the field is 'required' that means it's 'required' all the time, for an input on the back-end and also for an import.

If you want the field to act differently on import than on input: create a form that forces the 'required' field settings and set the field to not require any data on import. You would error on an import if this was going into a database on a field flagged required as well.

**Comment by Brian-Milnes** [comment]
...and there I was thinking I was dutifully writing up as requested (!) ;-)

At elast it's recorded for anyone else who might have expected different behaviour through different previous experience.

And yes, I'd already thought about using the Gravity Forms required field instead, and that may well provide a more suitable solution.  Allowing ignoring the required flag was a response to lax historical data and requiring better data in future.

**Comment by jimtrue** [comment]
My thought would be is: How would you want this to act differently? Imports are automated; input is manual (or user centric). I can't imagine how this would act differently. I know that WP All Import was looking for a filter to override the 'required' behavior. Is that what you would expect as a developer end-user, a filter to override the 'required' behavior?

**Comment by jimtrue** [comment]
I know from my background with databases as well, we often had to change the settings for those fields or create 'dummy' data that meant 'it wasn't entered historically, but it's required now. If you can provide this value in the future, force it.'

**Comment by Brian-Milnes** [comment]
It's not so much a Pods problem or a WP All Import problem, more a lack of consistency between plugins, I guess.
(And a bit frustrating that WP All Import support works on 24 hr reply cycle...)(Unlike your own exemplary efforts)

**Comment by quasel** [comment]
guess you solved this? 
Sorry for the late reply, feel free to comment if you still have questions!
