### ISSUE TITLE
Associated Custom Taxonomy not showing WPML translated strings in template driven Custom Post Type. Front end only.

### ISSUE THREAD

**Issue by wildmercury** [pods-framework/pods#4588]
Custom Post Type (meta) with associated Custom Taxonomy (meta):- Custom taxonomy showing correct WPML translated strings in admin area for the custom post type in a translated post. However, when viewed in front end, the custom taxonomy strings are only showing the original language strings. All other content (fields, labels, separators etc) are showing correct language. 
The testing I've done shows that if the original post is in either language the correct translation is visible in the front end. 

I hope the following screen captures illustrate the issue:
Back End English translation of French post (note taxonomy boxes in right hand column):
![fireshot capture 38 - edit itc reference itc _ - http___www itcc wildmercury net_wp-admin_post php](https://user-images.githubusercontent.com/8449753/33381491-d4774cdc-d526-11e7-810c-a8ac3908656b.png)
Back End Original French post (note taxonomy boxes in right hand column):
![fireshot capture 41 - edit itc reference itc _ - http___www itcc wildmercury net_wp-admin_post php](https://user-images.githubusercontent.com/8449753/33381500-defbffd6-d526-11e7-8659-c1151f54abfb.png)
Front End English translation (Note sub-title and Region fields still in French)
![fireshot capture 39 - strengthening haiti s negotiating capa_ - http___www itcc wildmercury net_it](https://user-images.githubusercontent.com/8449753/33381520-ec7f3efc-d526-11e7-8b3f-0c161ff5e3dd.png)
Front End French original post
![fireshot capture 40 - renforcement des capacites de negociat_ - http___www itcc wildmercury net_fr](https://user-images.githubusercontent.com/8449753/33381529-f4b3a090-d526-11e7-8dca-766564a0145b.png)
Back end view of English post listings with correctly translated strings showing in Taxonomies:
![fireshot capture 42 - itc references itc cons_ - http___www itcc wildmercury net_wp-admin_edit php](https://user-images.githubusercontent.com/8449753/33381755-8e791200-d527-11e7-9164-577540f05825.png)
List of CPTs and CTs:
![fireshot capture 37 - edit pods itc consulti_ - http___www itcc wildmercury net_wp-admin_admin php](https://user-images.githubusercontent.com/8449753/33381788-ab3fadea-d527-11e7-85fe-37e2bb64a43c.png)
English Template:
![fireshot capture 43 - edit pod template itc c_ - http___www itcc wildmercury net_wp-admin_post php](https://user-images.githubusercontent.com/8449753/33381936-0f9b6d56-d528-11e7-9e9e-bf76ce684fc4.png)
French Template:
![fireshot capture 44 - edit pod template itc c_ - http___www itcc wildmercury net_wp-admin_post php](https://user-images.githubusercontent.com/8449753/33381949-186cef72-d528-11e7-93b3-70087eb66513.png)

**Comment by jimtrue** [comment]
@JoryHogeveen Does this one sound like an existing issue you've seen? Or is related to this one #3242

**Comment by JoryHogeveen** [comment]
Well, it is related but not 100% sure if the issue is the same.
@wildmercury What versions are you using for Pods, WPML and WP?

**Comment by wildmercury** [comment]
latest full releases of each:
WP: 4.9.1
Pods: 2.6.11
WPML: 3.8.4

**Comment by wildmercury** [comment]
Anything I can do to help move this forward?

**Comment by wildmercury** [comment]
Problem solved! Errors/duplication in of naming of fields and taxonomies caused this. User error!
