### ISSUE TITLE
Plain number field is returned as a string value when using field()

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods#4593]
I have a CPT pod with a field of type `plain number`. When I fetch the pod and output the entries using `field()` (not `display()`), values of the plain number field are shown as strings rather than integers.

    $args = array( 'limit' => -1 );
    $pod = pods( 'profiles', $args );
    while ( $pod->fetch() ){
        var_dump( $pod->field( 'counter' ), true );
    }

The output of `var_dump` would be `str(1) "3"` instead of `int(3)`.

The field in concern is also set to `Make field "Read Only" in UI` in the advanced field settings as the value should be manipulated programmatically.

**Comment by JoryHogeveen** [comment]
Might be an enhancement for this field, but keep in mind that metadata is *allways* a string in WP.
A quick fix would be to parse it as an int: `(int) $pod->field( 'counter' )`

**Comment by quasel** [comment]
that's how WordPress works ;) and with php being a loosely typed language ;)
