### ISSUE TITLE
Pods and Admin Columns Pro 4.1: "deprecated filter cac/column/meta/value"

### ISSUE THREAD

**Issue by remcokalf** [pods-framework/pods#4594]
With Admin Columns Pro 4.1 and Pods 2.6.11 I get the following warning in Admin Colums settings:

"The filter cac/column/meta/value used on this website is deprecated since 3.0. The callback used is PodsMeta::cpac_meta_value"

There is a link to this documentation behind it:
https://www.admincolumns.com/documentation/filter-reference/cac-column-meta-value

The warning refers to the only place cac/column/meta/value is used:
pods/classes/PodsMeta.php
line 419
add_filter( 'cac/column/meta/value', array( $this, 'cpac_meta_value' ), 10, 3 );

**Comment by JoryHogeveen** [comment]
Fixed in #4570
