### ISSUE TITLE
Multiple image field returns first image src and img in [each] block

### ISSUE THREAD

**Issue by CPapadim** [pods-framework/pods#4596]
```
[each images]
    {@images}  # Returns each image correctly
    {@images._src}  #returns src of first image for all loop iterations
    {@images._img}  #returns img of first image for all loop iterations
[/each]
```

In a multiple image field, the above template returns the first image src and img for each iteration of the loop.

**Comment by jimtrue** [comment]
@CPapadim It looks like you've got a little confusion about the syntax of the `[each][/each]` blocks. They start a loop, so when you're in the loop, you don't repeat the multiple image field, taxonomy or related field _inside_ the each block. See our documentation on [Template Tags](https://pods.io/docs/build/template-tags-in-pods-templates/)

You should be using the each block like this:
```
[each images]
     {@_src} // for the src
     {@_img} // for the img
[/each]
```

Let me know if that works as you expect.

**Comment by CPapadim** [comment]
Yes that's right, I did use that page as a reference but for some reason thought the {@_img} references were entirely different fields that were coincidentally named _img etc. rather than being part or the looping field.   In retrospect it's very clear :)

Thanks for the clarification, that solves the issue!
