### ISSUE TITLE
BETA 2.7 - Extended post and page types pods not available through the REST API.

### ISSUE THREAD

**Issue by obedparla** [pods-framework/pods#4598]
The issue resides in the REST API not showing the PODs extensions (for pages and posts). I have `meta_title`, `meta_description`, and `hero_image_text`. Using the stable version 2.6 they show fine in the api. When updating to the 2.7 they stop working. Cleared PODs cache, didn't help.

An easy way to understand what happens is to compare my staging env which is using 2.7 beta: http://reactcasino.staging.wpengine.com//wp-json/wp/v2/posts. And searching for `meta_`. No results found. As mentioned above these fields are added with PODs.

In production (using 2.6) http://reactcasino.wpengine.com//wp-json/wp/v2/posts. Search for `meta_` again and you'll see the fields.

The custom fields show in the posts and pages (under both versions) only the API seems to be affected.

Running Wordpress 4.8.4 (can update staging if you think 4.9 can fix it).

**Comment by obedparla** [comment]
Both environments are exactly the same, the only difference is the version of PODS.

**Comment by jimtrue** [comment]
I can verify this as an issue, was able to reproduce instantly. Extended posts, added one field, Enabled REST API 'show all fields'. 2.6.11 the field shows in the REST API output (/wp-json/wp/v2/posts) in 2.7rc1, it doesn't.

**Comment by jimtrue** [comment]
I can confirm Custom Posts/taxonomy don't seem to have this issue, just 'post' extended. 'users' extended is also fine. Testing 'page' and the others very quickly.

**Comment by jimtrue** [comment]
Confirmed Extended Page also loses pods custom fields in 2.7rc1

**Comment by sc0ttkclark** [comment]
Looking

**Comment by sc0ttkclark** [comment]
Found

**Comment by sc0ttkclark** [comment]
Fixed
