### ISSUE TITLE
Extra help tooltips in Spanish language

### ISSUE THREAD

**Issue by davidatwhiletrue** [pods-framework/pods#4614]
With Spanish language active Pods editor show some help tooltips that are not in the English version. Since there is no help string those show just 'ayuda' (help in English). Probably those shouldn't just appear.

Example:

<img width="164" alt="screen shot 2017-12-06 at 21 15 40" src="https://user-images.githubusercontent.com/2131247/33684231-dee40a00-dacd-11e7-9389-c298ebc7ef8e.png">

<img width="171" alt="screen shot 2017-12-06 at 21 15 52" src="https://user-images.githubusercontent.com/2131247/33684234-e1480918-dacd-11e7-8972-d2a0dc3011ed.png">

The same happens in different tabs.

**Comment by sc0ttkclark** [comment]
we probably need to check for the i18n string `__( 'help', 'pods' )`, right now it's only checking for "help"
