### ISSUE TITLE
Custom extra advanced option not passed to filters

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#4619]
I added an extra option through the filter pods_admin_setup_edit_field_options. Before updating to 2.7, the value saved was passed to filters like pods_form_ui_field_pick without any problems, but after the update, it is not passed over any more. Would you advice please? Thanks.

![custom extra advanced option](https://user-images.githubusercontent.com/17201482/33713529-7af68056-db43-11e7-8afb-db4aa654afd9.png)

-------------Code -----------------------
add_filter( 'pods_admin_setup_edit_field_options', 'extra_options_fn', 10, 2 );

function extra_options_fn( $options_arr, $pods_obj ) {

		foreach ( $options_arr as $k_str => $opt_arr ) {
                    
			if ( $k_str == 'advanced' ) {
                               $options_arr[$k_str]['Extra'] = array(
					'sp_level' => array(
						'name'    => 'sp_level',
						'label'   => __( 'Level', 'pods' ),
						'help'    => 'Display level',
						'type'    => 'paragraph',
						'default' => '',
					),
				);
			}

		}

		return $options_arr;
	}
Then use it in:
add_filter( 'pods_form_ui_field_pick', array( $this, 'toggle_level_fn' );
sp_level was in the options array but not any more after updating to 2.7

**Comment by coding-panda** [comment]
@pglewis Hi Phil, just wonder when it 2.7.2 will be released so I can let the team know? We are waiting for it to be fixed so we can update Pods for our projects. Thanks.

**Comment by pglewis** [comment]
This is actually top on my list at the moment, most other new issues are in hand.  I just need to setup a test here and do the digging.  Famous last words: I don't think it's going to be too troublesome once I find it.

**Comment by coding-panda** [comment]
That is great. Thank you very much.

**Comment by quasel** [comment]
@coding-panda is this still an issue?

**Comment by coding-panda** [comment]
It doesn't seem to be an issue anymore. Thanks.
