### ISSUE TITLE
String "is required" is Translated in Italian, continues to display in English

### ISSUE THREAD

**Issue by pierluigiabramo** [pods-framework/pods#4620]
..i continue to see in english... Pods 2.7 WP4.9.1... same thing in 2.6.11
![schermata 2017-12-07 alle 17 56 32](https://user-images.githubusercontent.com/17725824/33727685-16fd02b0-db79-11e7-8f18-ef92b1dfd55d.png)

**Comment by jimtrue** [comment]
This might be related to #4614

**Comment by pierluigiabramo** [comment]
Ok @jimtrue thanks!

**Comment by quasel** [comment]
Seem Fixed!
