### ISSUE TITLE
WP Core Style Conflict in _advanced.scss

### ISSUE THREAD

**Issue by napa-web-designer** [pods-framework/pods#4624]
It looks like you are using a generic class (.left which is styled to float left) in your css that is conflicting with the WP Admin area styling and causing a formatting issue. See attached screenshots looking at WP admin area Custom Fields which is affected along with Chrome Dev tools showing the .left rule toggled on and then off, exemplifying the affect, and then the file pathway leading to the file _advanced.scss.

Steps to duplicate, I created a new Upload file custom field for the post type Posts. Then when I went to edit a post and was showing custom fields, I got what is in the screenshots.

<img width="1280" alt="screen shot 2017-12-07 at 10 00 08 am" src="https://user-images.githubusercontent.com/1827904/33732813-7b08b2fa-db3c-11e7-8e08-17aee6b02865.png">
<img width="1280" alt="screen shot 2017-12-07 at 10 00 23 am" src="https://user-images.githubusercontent.com/1827904/33732814-7b255356-db3c-11e7-83ea-2501eec771eb.png">
<img width="563" alt="screen shot 2017-12-07 at 10 01 23 am" src="https://user-images.githubusercontent.com/1827904/33732815-7b44c72c-db3c-11e7-8478-62a051bab198.png">

**Comment by pglewis** [comment]
Related #4612 

Should probably be added to #4615

**Comment by nicdford** [comment]
Fixed with #4632

**Comment by nicdford** [comment]
Verified this was fixed with #4632
