### ISSUE TITLE
Pods Form: List View's dashicons display improperly

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4626]
![pods-form-listview-dashicons](https://user-images.githubusercontent.com/1973916/33738031-20378a0c-db66-11e7-9025-7e7eed6172a4.png)

**Comment by nicdford** [comment]
Fixed with #4635

**Comment by pglewis** [comment]
Closer but I'm getting underlined links: 

![pods-form-listview-dashicons](https://user-images.githubusercontent.com/1973916/33780122-97707b8a-dc1d-11e7-882c-6c1394423c1d.png)

**Comment by JoryHogeveen** [comment]
How can I repro this?

**Comment by pglewis** [comment]
That last screenshot is probably something related to the 2017 theme and I think Nic as a bead on it already.
