### ISSUE TITLE
Min version bump from MySQL 5.0 to MySQL 5.5 

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4627]
https://pods.io/forums/topic/updated-to-pods-2-7-broke-site/

https://github.com/pods-framework/pods/commit/5618995379319f62328a19fcbe3bdb9743c20a1c

**Comment by pglewis** [comment]
PR: #4628

**Comment by sc0ttkclark** [comment]
Closing this, we're going to keep min at 5.5 for now.
