### ISSUE TITLE
Pods adds backend headers which causes issues with Varnish

### ISSUE THREAD

**Issue by BeSite** [pods-framework/pods#4636]
Hi,
We enabled Varnish on some of our websites but the Varnish cannot fully get to the page because of X-Cacheable: NO: Backend headers from what I have seen in the Network tab of the inspector.
I use a private tab in the browser and I am not logged in into wp-admin.

On this page: https://github.com/pods-framework/pods/issues/2298
I have found an solution which worked. I added this row in the wp-config:
define('PODS_SESSION_AUTO_START',false);

The backend headers didn't show up and I got good results. The website was blazing fast into Varnish but unfortunately the site broke. Which means some Pods fields where empty like images disappeared or I got a white screen (front-and backend). After I rolled back and define() and added the images again manually the site works fine again.

Here are some headers which I want to have:
Via:1.1 varnish
X-Application:dynamic
X-Cache:HIT
X-Cacheable:YES

Instead I got:
Via:1.1 varnish
X-Application:dynamic
X-Cache:MISS
X-Cacheable:NO: Backend headers

Can you please give me a solution to savely prevent the headers from showing up so the sites can be cached with Varnish.

Thank you,

Rob

**Comment by sc0ttkclark** [comment]
Fixed via #5626
