### ISSUE TITLE
Look into tooling to auto-update the changelog

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4641]

**Comment by pglewis** [comment]
Coming up with a PR Template that includes a task-item for changelog has been mentioned

**Comment by jimtrue** [comment]
- here's one tool.   https://github.com/lalitkapoor/github-changes
- could be integrated with the grunt release process

- There’s a lot of formatting that we’re pulling into the changelogs. Too. I think the maintenance ones are a little different in structure, but the ‘release’ one we got was a big deal and needed to highlight major feature in this release, etc. Required a different changelog format for that one.

- here's another https://github.com/lo1tuma/pr-log
- part of the approval process would be to make sure the PR subject accurately describes

**Comment by jamesgol** [comment]
The developer of one of the existing tools has a list of similar tools.
https://github.com/skywinder/github-changelog-generator/wiki/Alternatives

Have to decide if you want them to take tags from specially formatted commits or pull requests (and labels).

I'm guessing one of the main requirements is that it should be able to integrate into the grunt workflow
