### ISSUE TITLE
Date/Time field with Asian letters

### ISSUE THREAD

**Issue by m3h1nd3r** [pods-framework/pods#4666]
Dear Pods team,
we experience a strange behaviour with the Pods Date/Time field. Some text parts like month names etc. are being displayed in Asian letters (please compare screenshot: https://pasteboard.co/GXfWkK5.jpg)
![8993bed0-9db7-4b23-815a-92189dba23e1](https://user-images.githubusercontent.com/3052875/33993721-c4248054-e0a5-11e7-8636-1232d14d5793.jpg)

The WP page language is German, but it doesn’t change anything if we switch back to English (US). WordPress is latest version (4.9.1), Pods is 2.7, but this appeared on previous Pods versions as well.

Any hint how this is caused or how it can be fixed?

Thank you and best regards!

(as discussed here: https://wordpress.org/support/topic/date-time-field-with-asian-letters/)

**Comment by jimtrue** [comment]
@JoryHogeveen Any thoughts on this one? This looks like it is in the DatePicker jQuery.

**Comment by JoryHogeveen** [comment]
I actually think this is a WP issue. Pods uses the WP core datepicker (we don't even pass locale info, this is all handled within WP).
The only part we actually change is the timepicker and that works fine (Zeit / Stunde / Minute)

**Comment by JoryHogeveen** [comment]
@m3h1nd3r 
Can you provide a list of other plugins you use?

**Comment by jimtrue** [comment]
@JoryHogeveen Don't know if this helps, but here's a note from the original ticket on how "CriticalTinkerer" replicated the issue:

> After writing the above I checked a site where I use Pods to add a Date field to User profiles. The Date widget comes up in English, as it should. I then went to admin menu >> settings >> general >> Site Language and changes the language to Japanese and save settings. I again went to the User Profile date field expecting to see a Japanese Calendar but it is unchanged and still in English.

**Comment by JoryHogeveen** [comment]
@jimtrue Correct, I can replicate that part. The time selection is in Japanese then but the date selection is not.
I'm 99% sure this is a WP issue since WP doesn't use the datepicker's own translation files but instead uses the WP core translations. It might be possible that the japanese translations isn't completed yet.

But from what I understand, the above is the other way around, which is strange.

In any case. We don't have control of the UI in the datepicker since this is WP core. We only tell WP to instantiate the datepicker and optionally add the timepicker to it.

**Comment by JoryHogeveen** [comment]
To get back on this. The Japanese issue was a local issue, unrelated to Pods. After switching to the stable 2.7.1 release it all worked correctly.
![image](https://user-images.githubusercontent.com/826148/33997345-54afd950-e0e4-11e7-992d-a65506103101.png)

As for the reported issue (mixed languages). I think this might be cause by a third party plugin that is setting defaults for the datepicker jQuery plugin.
This will also explain why the timepicker is correct but the datepicker is not.

**Comment by jimtrue** [comment]
@m3h1nd3r Might help the most if you can deactivate each of those plugins and test to see if deactivating one of them clears the problem. I see you're on Pods 2.7, I'd also suggest upgrading to 2.7.1

**Comment by m3h1nd3r** [comment]
It's the "Simple Fields" plugin (https://wordpress.org/plugins/simple-fields/). After deactivating this, the display of the Date Field in Pods is correct. With Simple Fields active, the Asian letters will be displayed again (also with latest Pods 2.7.1).

As Simple Fields seems to be abandoned and it not even tested with current WordPress, I assume there's nothing you guys can do about this, right?

**Comment by jimtrue** [comment]
@m3h1nd3r Nope, we're a free plugin with free support and incredibly tight on resources supporting our own plugin and it's 50k+ users. Sorry we can't help you with that one, but you can always open a support issue on their plugin page. At least you figured it out ;)

I'm going to close this ticket and thanks for bringing it over from WordPress.org.

**Comment by m3h1nd3r** [comment]
No worries, that's totally fine and actually it's amazing how much you supported us on this one already, especially as it's a free plugin, as you said ;) Thank you very much and have a great Christmas time ahead!

**Comment by jimtrue** [comment]
Thanks and the same to you! You might want to look and see what Simple Fields was providing and see if you can replicate it in Pods. I noticed you had several fields based plugins installed.

**Comment by m3h1nd3r** [comment]
Thanks, yes I had the same thought, will see what we can do there. Would be best if we could get rid of Simple Fields and do it all through Pods, I guess.

**Comment by JoryHogeveen** [comment]
@m3h1nd3r From what I see in the feature list from Simple Fields you could definately switch to Pods 100%.
The only thing you might have to do (depending on the theme) is update the field/value functions within theme templates.
Good luck!
