### ISSUE TITLE
Gutenberg Blocks manager

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods#4668]
- [ ] Ability to create a new block
- [ ] Ability to configure settings for block
- [ ] Ability to choose type of block from a few basic blocks
- [ ] Ability to set custom block label and placeholders etc

Nice to have:

- [ ] Possibly use Gutenberg itself to create nested blocks if they want to build a block 'layout' (nested block) from multiple blocks
- [ ] Ability to control block view with some sort of template

**Comment by sc0ttkclark** [comment]
Renaming/filling in more details here based on scope that's in my head

**Comment by sc0ttkclark** [comment]
Updated

**Comment by sc0ttkclark** [comment]
Going to tackle this via a Pods Pro add-on, eventually may bring it into Pods core itself
