### ISSUE TITLE
PHP Fatal error after Updating plugin to v2.7.1

### ISSUE THREAD

**Issue by enquirer32** [pods-framework/pods#4669]
php error: PHP Fatal error: Unsupported operand types in /public/wp-content/plugins/pods/classes/fields/number.php on line 202

WordPress Version: 4.9.1
PHP Version: 5.6.6
MySQL Version: 5.5.58
Server Software: Apache/2.4.28 (Unix) OpenSSL/1.0.1f

**Comment by jamesgol** [comment]
I see how this could help but I'm curious about the context your are seeing it.  Does this happen when viewing a specific page/template that has a pod in it?  It's easy to stop that error right there, but I don't want to cover up any underlying issues that there could be.

**Comment by enquirer32** [comment]
Not sure... I am logging php errors. Doesn't seem to be page specific just when someone accesses the website.

**Comment by jamesgol** [comment]
Can you share some of your code that is calling Pods functions?  Maybe from a template or from some custom code in your themes functions.php?

I can't come up with a method that this should happen

**Comment by enquirer32** [comment]
You will have to help me here. I have several pods, lots of templates. Shall I export the lot? Thanks. (Still happening).

**Comment by sc0ttkclark** [comment]
Please export a package of your pods and templates. Do you have custom PHP code running anywhere in the theme or plugin that interacts with Pods directly? Send the package to support@pods.io if you don’t want to share publicly.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
