### ISSUE TITLE
Relationship field to custom taxonomy not displaying in pods template

### ISSUE THREAD

**Issue by hgordon-whoi** [pods-framework/pods#4671]
Just updated to 2.7.1. Have Pod 'recipe' which has a related_sample_type multiselect checkbox field for the the custom taxonomy 'sampletype'. 
![image](https://user-images.githubusercontent.com/14059422/34014021-ac993424-e0e7-11e7-987a-3d2fbd3d54f5.png)
![image](https://user-images.githubusercontent.com/14059422/34014040-bbece39e-e0e7-11e7-900a-721f4e1a6bf2.png)
![image](https://user-images.githubusercontent.com/14059422/34014049-c0d80a82-e0e7-11e7-9de8-844e09e49ead.png)
The custom taxonomy has 4 entries at present.
My Pods Template uses the following to display the sample type(s):  

```
<td>
[each related_sample_type]
<p>{@related_sample_type.name}</p>
[/each]
</td>
```

This worked until 2.7.1 when related_sample_type no longer displays. The pod has another relationship field to another pod (element) that does still display in the template.
![image](https://user-images.githubusercontent.com/14059422/34014197-4a231994-e0e8-11e7-8268-e92d01887f2d.png)

**Comment by sc0ttkclark** [comment]
@jimtrue correct me if I'm wrong, but does their each syntax need the prefixes in the magic tag within?

```
<td>
[each related_sample_type]
<p>{@name}</p>
[/each]
</td>
```

**Comment by hgordon-whoi** [comment]
Hi @sc0ttkclark - This is a change from earlier pods version! Earlier versions required fully qualified related field reference. Just tried your suggestion of {@name} and ta-da!
![image](https://user-images.githubusercontent.com/14059422/34014658-01eefccc-e0ea-11e7-823e-7a416f70073e.png)

**Comment by jimtrue** [comment]
Didn't realize they were in an each block, but yes, we're less forgiving of bad syntax in each blocks now

**Comment by hgordon-whoi** [comment]
Thank you for the help. We can mark this closed.
