### ISSUE TITLE
How make “templates” compatible with visual composer??

### ISSUE THREAD

**Issue by ndaweb** [pods-framework/pods#4672]
My idea is that I can use the pods templates and at the same time design them with visual composer.
For this I need the textarea that uses pods templates to be transformed into wp editor.
For this, change the element-view_template.php file.
This..
<?php
/**
* Frontier Template code editor metabox
*/
?><textarea id=”content” name=”content”><?php if ( isset( $content ) ) {
echo esc_textarea( $content );
} ?></textarea>

/// By This!!

<?php
/**
* Frontier Template code editor metabox
*/
wp_editor(
esc_textarea( $content),
‘content’,
array( ‘textarea_name’ => ‘content’ )
)
?>

I still do not get the expected results.
That’s why I ask for your help.

**Comment by quasel** [comment]
maybe sue a shortcake instead :D
