### ISSUE TITLE
How to optimize find requests for specific relationship fields

### ISSUE THREAD

**Issue by CPapadim** [pods-framework/pods#4674]
I'm trying to get field values for a number of pods of a particular type.  I'm doing this:

```
$my_pods = pods('my_pod_type')->find( array('limit' => -1,  'where' => 't.ID IN (' . implode(', ', $id_array) . ')'));

while ( $my_pods->fetch() ) {
                echo $my_pods->field('my_field');
}

```

This works, but when I run it it generates an absolutely massive amount of queries (like 3000+ since that's how many results exist).

I should also mention, `my_field` is a relationship field, however, I only wish to get the value of the field (so for example the ID or whatever is stored on $my_pod's side of things), and not any information about the pod it relates to.

Is there a way to grab the fields with just one query?  It seems like it should be possible.

On a related note, it seems that $my_pods->field('my_field') is when the query runs, so if I try to get more than one fields that will further increase the number of queries.  Is it possible to get all fields at once?

**Comment by sc0ttkclark** [comment]
This sounds like an easy place to make use of the find() `select` option:

```
$params = array(
    'select' => 't.ID, my_field.ID AS my_field_id',
    'where' => 't.ID IN ( ' . implode( ', ', array_map( 'absint', $id_array ) ) . ' )',
    // You really should not do unlimited queries, set to 5000 or something, never do unlimited
    'limit' => 5000,
);

// Shorthand to setup the Pods object and do a find()
$my_pods = pods( 'my_pod_type', $params );

while ( $my_pods->fetch() ) {
    // my_field_id will be the ID of my_field relationship
    echo $my_pods->field( 'my_field_id' );
}
```

You didn't specify whether my_field is a single-select relationship. The code above assumes this as a single-select relationship.

**Comment by CPapadim** [comment]
Interesting.  That works but I'm not sure why.  Does find() automatically handle the necessary joins when select is specified?

Anyway thanks!  

Also I do have a couple of fields I'd like to pull that have multiple values, is there something special to do for that?

**Comment by sc0ttkclark** [comment]
Indeed, find() does all the joins necessary for you automatically. One query, no extra queries needed when you've aliased to a non-Pod field name, so it works swimmingly :)

For multiple values, you would do something in your select like:

`GROUP_CONCAT( DISTINCT multiple_field.ID SEPARATOR ',' ) AS multiple_field_ids`

and for the field() output you would use:

```php
$multiple_field_ids = implode( ',', $my_pods->field( 'multiple_field_ids' ) );

// Do whatever with your $multiple_field_ids array
```

This `select` optimization is by far the best thing EVAR!

Enjoy :)

**Comment by CPapadim** [comment]
Hmm not quite able to get the multiple fields thing to work.  Since in that case I need to groupby each resulting my_pod, and that seems to go back to running one query per grouped result (so one per my_pod again, but no extra queries for additional fields which is good).

**Comment by CPapadim** [comment]
Erm, nevermind it seems to be working now :)  

Once in a while the query results seems odd, e.g. it can't find the groupby field or some other such stuff, but after refreshing it seems to work.  Maybe cache related - not sure, but seems good for now!

**Comment by sc0ttkclark** [comment]
Updated my message with the `groupby` param just now

**Comment by CPapadim** [comment]
Hmm, there's still an issue with this.

When I leave the page for a while, the first refresh after some time has passed will do one query for every resulting pod even when I use the 'select' setting, (but notably, NOT for every field, which is good).  I tested this by changing the query limit so I can see that it's what's driving the number of queries.  When the query limit is low the queries are far fewer, and when it's high it's much higher.  

So it seems that after some time has passed it will do one query per result, but subsequent refreshes just do a single query. 

Subsequent refreshes go back to just being a single query.  Why is that?

**Comment by CPapadim** [comment]
So now that I know about this, I'm trying to optimize some other queries (the original queries are working great, thanks!)  In these other queries, group_concat is not suitable because those multivalue relationship fields hold thousands of entries.

Is there another way to get those with an optimized query like the one below, but without using group_concat (and maybe even avoiding groupby, as I'm unaware of any other useful aggregate functions toward this goal)?

```
$params = array(    'select' => 't.term_id, GROUP_CONCAT(multi_value_field.id) AS field_vals', 
                                'where' => 't.term_id = ' . $obj_id,
                                'limit' => 1
                                'groupby' => 't.term_id'
                        );
```

The above query will run over the group_concat limit.  My goal here is to get all of the values of a multi_value_field with a single query.  The values exist in a single pod (so that's why limit is 1). 

I also tried standard methods to just find the pod by id, and hten use $pod->field('multi_value_field') and this seems to run one query per field value every so often, but sometimes it runs just one query.  So it seems like the result is cached for some amount of time.

**Comment by CPapadim** [comment]
I was able to determine that the above issue was due to caching as I suspected, but separate from pods.  (Database cache).  I've adjusted cache settings accordingly, and now everything is super speedy

**Comment by sanderaido** [comment]
@sc0ttkclark 
> and for the field() output you would use:
> 
> $multiple_field_ids = implode( ',', $my_pods->field( 'multiple_field_ids' ) );
> 
> // Do whatever with your $multiple_field_ids array

I think this should be `explode()` instead of `implode()` to turn it into an array?
But thanks for the GROUP CONCAT hint, got me on the right track!
