### ISSUE TITLE
Pods fields not showing up for custom post type wc_user_membership (Woocommerce Membership)

### ISSUE THREAD

**Issue by dragondesigns** [pods-framework/pods#4675]
I have extended wc_user_membership using Pods and have added custom fields, but they are not displaying in the Membership pages.

I am sure it is the correct custom post type, as I have managed to create custom fields using Advanced Custom Fields without an issue:

https://www.useloom.com/share/1e7f5229d7b64886897cb82867d249d5

**Comment by jamesgol** [comment]
Have you tried this with ACF disabled?  I don't know if anyone has ever tried using Pods + ACF side by side with both trying to extend a post type.  

Also since we don't have a copy of WooCommerce Membership we won't really be able to test it out.

**Comment by jamesgol** [comment]
I just tried extending a WooCommerce product both with ACF and Pods and it did appear to work the way you would expect, so it doesn't seem like a conflict between ACF and Pods.  That leads me to believe it's probably an issue connected to the Membership plugin.

**Comment by jamesgol** [comment]
The plugin has code in it to remove "overzealous 3rd-party meta boxes".  There appears to be a WordPress filter 'wc_memberships_allowed_meta_box_ids' that can be used to append to the whitelist of IDs that would be allowed.  

In theory adding the following would add the Pods fields to the whitelist:
```
add_filter( 'wc_memberships_allowed_meta_box_ids', 'jmg_wc_memberships_allowed_meta_box_ids' );
function jmg_wc_memberships_allowed_meta_box_ids( $ids ) {
   $ids[] = 'pods-meta-more-fields';
   return $ids;
}
```

Untested code, but it should work.  Though I would recommend talking to that plugin developer to see if they have an alternate suggestion.

**Comment by dragondesigns** [comment]
Great - thanks, that worked fine :)
