### ISSUE TITLE
Nice little bug in dropdown selectors (not present in 2.6.11)

### ISSUE THREAD

**Issue by RichwebInc** [pods-framework/pods#4679]
“I know it when I see it.” Perhaps, one of the best ways to describe the bug I’ve found.

In the “link to page I need help with” is a field that we’re using Pods to generate.

Late last week, I performed WordPress updates. Pods was updated to 2.7

In version 2.6.11, the user account responsible for posting jobs on this site has access to that dropdown.

I rolled the Pods version back from 2.7 to 2.6.11. I then updated it to Pods version 2.7.1. I then tested the form to see if the dropdown was missing (it was), so I then reverted back to version 2.6.11.

I downloaded a FRESH version of 2.6.11 directly from WordPress and tested it with the jobs account. (I wanted to make sure that the Pods plugin hadn’t been customized; great news for me (and bad news for the Pod folks): It wasn’t customized)

I am now able to 100% confirm that there is an issue with 2.7 AND 2.7.1, that is not present in 2.6.11.

I’ll be happy to provide additional information, as needed.

I do have a JSON export available for y’all (in a text file).

![umfspodspluginbug](https://user-images.githubusercontent.com/34729204/34237889-0a02ade0-e5cd-11e7-8dd0-f68306edc29d.jpg)

**Comment by jimtrue** [comment]
@RichwebInc If you can provide us the Pods, Migrate: Packages export to this issue, that would be seriously awesome. Can you give us more details as to what kind of relationship field this is?

**Comment by RichwebInc** [comment]
https://www.umfs.org/umfsPodsPluginJSON.txt is the JSON. :)

Parent Pod is Custom Post Type.
Child pod info, is as follows:
Employment Type
employment_type
Relationship › Simple [type: pick] (custom defined list) (Custom)
Options: Full-time, Part-time, PRN, Temporary
Restricted by role (Admin and HR Team)
Single select dropdown.

**Comment by quasel** [comment]
Hi @RichwebInc is this still an issue for you?

**Comment by RichwebInc** [comment]
Greetings, Bernhard!

 

I’ll test and check this on Tuesday when we’re back in non-holiday hours. J

 

-- Doug

**Comment by RichwebInc** [comment]
GREAT job, y'all! The dropdown appears after I did the update. :D 

Thank you for the fix, y'all!

**Comment by quasel** [comment]
Nice one! annnnnnd closed ;)
