### ISSUE TITLE
Uncaught TypeError: jQuery(...).PodsDFVInit is not a function

### ISSUE THREAD

**Issue by xkungfu** [pods-framework/pods#4680]
On the create new post page, the below error showing in the console:

**_Uncaught TypeError: jQuery(...).PodsDFVInit is not a function_**

the error is caused by the last line in the below file:

`\plugins\pods\ui\js\pods-dfv\pods-dfv.min.js
`
`jQuery(function() {
		jQuery(".pods-form-ui-field").PodsDFVInit(U.fieldInstances)
})
`

I don't understand this js file. please have check on it.

thanks!

**Comment by pglewis** [comment]
I cannot think of why the code to _call_ `PodsDFVInit` would be there but not the `PodsDFVInit` function itself.  

I would try disabling all other plugins and set the theme to a default theme to test for some conflict.

**Comment by xkungfu** [comment]
if fact, the error in console show the error is in this file:

> \pods\ui\js\pods-dfv\_src\pods-dfv.js  line 19


the code is:
```
jQuery( function () {
	jQuery( '.pods-form-ui-field' ).PodsDFVInit( PodsDFV.fieldInstances );
} );
```

but whether I delete this line or delete the whole file  "pods-dfv.js", the error is still there!!!

the file "pods-dfv.js" is really deleted, but the error report in this file, why?

![20171222112318](https://user-images.githubusercontent.com/26067653/34284219-5d7a8d82-e70b-11e7-8fcf-e158c7a4d723.png)
![20171222112533](https://user-images.githubusercontent.com/26067653/34284228-677c9078-e70b-11e7-8e1c-8b71d016d457.png)

but after I delete the related code in the file '\pods\ui\js\pods-dfv\pods-dfv.min.js',
the error is disappeared.
`jQuery(function() { jQuery(".pods-form-ui-field").PodsDFVInit(U.fieldInstances) })
`

**Comment by xkungfu** [comment]
thanks

**Comment by xkungfu** [comment]
I found the conflict file:

> \plugins\wp-editormd\editormd_class.php

on line 261:

`wp_enqueue_script( 'jqueryjs', paf( 'jquery_library' ) . '/jquery.min.js', array(), WP_EDITORMD_PLUGIN_VERSION, true );`

I don't know how to resolve this problem. hope there is a solution.

bytheway: WP Editor.MD is the best one MarkDown editor for wordpress.

**Comment by xkungfu** [comment]
MORE DETAIL:
It seems if any plugin wp_enqueue_script a jquery library file, then the error would  occur.

please have a check ,thanks!

**Comment by pglewis** [comment]
We attach a jQuery plugin to WordPress's copy of jQuery.  Over-riding the WordPress copy with a different copy of jQuery thus removes that bootstrap function we have that creates the fields.

**Comment by xkungfu** [comment]
thanks , I SEE now.
I removed the jquery library file registered by WP Editor.MD plugin.
now the problem is temporary fixed.

**Comment by pglewis** [comment]
I'm not going to just close this, there is probably action to take.  

Overriding the default jQuery script is a Bad Idea no matter how you slice it but it should be trivial to do the bootstrap without attaching it to `jQuery.fn` so that things wouldn't break except in cases of actual incompatibility.

**Comment by pglewis** [comment]
PR: #4826
