### ISSUE TITLE
Some infolabels missing on Dutch translation of Pods 2.7.1

### ISSUE THREAD

**Issue by FWaalboer** [pods-framework/pods#4689]
Some infolabels are missing on Dutch translation of Pods 2.7.1.

When in pods admin > edit pods > advanced settings (translated on the fly) the first three settings only have an infolabel with the word 'help'.
![bugreport pods infolabels](https://user-images.githubusercontent.com/34897236/34392756-8ab830a0-eb4e-11e7-889f-ff88760ed623.png)

**Comment by JoryHogeveen** [comment]
Dit is not dutch related, they are missing in general.
Similar: #4614
Fix PR: #4684
