### ISSUE TITLE
Advanced Filters Popup Not Loading

### ISSUE THREAD

**Issue by 3rdplanetstudios** [pods-framework/pods#4693]
Since upgrading to Pods CMS version 2.7.1 the Advanced Filters popups when managing content do not display filter options. This is the case across all sites that I have upgraded.
![advanced-filters](https://user-images.githubusercontent.com/24754822/34464860-2abf3ab6-ee61-11e7-9365-74a95bf11eb9.jpg)

**Comment by jimtrue** [comment]
This is on Advanced Content Types, correct? Have you been able to test if going back to a Pods Version prior (like 2.6.11) brought the functionality back?

**Comment by rpall** [comment]
This is indeed an issue. And quite annoying. Do you still need verification/reproduction info?

**Comment by jimtrue** [comment]
Also #4740 and #4704

**Comment by jimtrue** [comment]
I closed the other two issues referencing this one.

**Comment by maxisosa** [comment]
Temporary solution: Add on lines 3003 and 3013 –> <?php add_thickbox(); ?> <– in file /classes/PodsUI.php
![sin titulo-1](https://user-images.githubusercontent.com/840261/36038489-a1aabb9e-0d9e-11e8-9db9-2e371ef61ec0.png)

**Comment by jimtrue** [comment]
Thanks @maxisosa for transferring that from the forum post ;)

**Comment by abhinav-maheshwari** [comment]
Verified that the issue exists on 2.7.1 but works on 2.6.11

**Comment by pglewis** [comment]
I believe this is just some missing CSS after the style restructuring in 2.7.  

https://github.com/pods-framework/pods/commit/cbbd0bdd98132a3718b7fa4f3f54210905d0f8e8#diff-f9dfd1411999d1bb8a81f4cee87caca5L2878

**Comment by pglewis** [comment]
PR #4797 

We just missed the dependency on the thickbox css when we changed things over.
