### ISSUE TITLE
Cannot MultiSelect on relationship field between two custom content types

### ISSUE THREAD

**Issue by PeterIbsen** [pods-framework/pods#4694]
I have a one-way relationship between two custom content types. It is setup with selection type "Multiple Select" and format "Checkboxes". Selecting the check boxes in the edit interface for the content type used to work fine, but now has reverted to "Single Select" functionality even though it is still setup to be "Multi Select". I am running the newest version of WP (4.9.1) and Pods (2.7.1). It may have happened at the update of Pods in December, but I am not 100% sure.
Thanks!
Peter

**Comment by PeterIbsen** [comment]
I just rolled back to Pods version 2.6.11 and the issue disappeared. So it does seem to be introduced with version 2.7.1.

**Comment by jimtrue** [comment]
Did it work in 2.7?

**Comment by PeterIbsen** [comment]
I am actually not sure which version I upgraded from to 2.7.1. The only place I could find older versions was here: https://wordpress.org/plugins/pods/advanced/  and the "newest of the old" was 2.6.11. 
I can try 2.7 if there is a place where I can get it?

**Comment by PeterIbsen** [comment]
Sorry, I am new to GitHub. I now downloaded a zip called "pods-2.x-2.7" which in WP indicates its version 2.7. The issue is present there as well - so, no, it doesn't work in 2.7 as far as I can tell.

**Comment by jimtrue** [comment]
You beat me to it, that's the proper method for getting older versions from GitHub. Thank you for confirming. We'll need to confirm the issue on our end, but you've done the legwork so that helps tremendously!!

**Comment by PeterIbsen** [comment]
Super! Thx!

**Comment by jjsanderson** [comment]
I'm seeing something similar with Pods 2.7.1. I have three custom post types with two-way Pods relationships set up between the types; all are set to multi-select, autocomplete.

In the post editor, with Pods 2.7.1 the relationship field displays a label but no content:
<img width="543" alt="with pods 2 7 1" src="https://user-images.githubusercontent.com/184010/34821900-0068ea32-f6bd-11e7-8eee-fd26ec5fc587.png">

Reverting to Pods 2.6.11 restores the expected behaviour:
<img width="434" alt="with pods 2 6 11" src="https://user-images.githubusercontent.com/184010/34821901-0080cd0a-f6bd-11e7-8617-41070dd07fb2.png">

**Comment by jjsanderson** [comment]
Initial testing with Pods 2.7.3: this issue appears to be resolved. Excellent!

**Comment by PeterIbsen** [comment]
Just an FYI - I updated to 2.7.6 and this issue is still there. Will roll back to 2.6.11.

**Comment by jimtrue** [comment]
@PeterIbsen You may need to provide us a Migrate Package Export so we can more easily replicate the case you're running into.

From our Bug Report Template, these are the two things we need to more accurately diagnose and figure out what you're running into:

## WordPress Environment
This is REQUIRED for Bug Reports, so we can check for conflicts, version issues, etc.

Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.

## Pods Package Export (helpful!)
Please include the Pods Package Export as it will be helpful in reproducing your issues.
- To access: Pods Admin, Components, Migrate: Packages, Enable.
- Then Pods Admin, Migrate: Packages, Export and Copy and Paste the JSON here OR 
Save to a text file and upload to this bug report

**Comment by PeterIbsen** [comment]
Hi Jim,
Please see below and let me know if you need anything else!
Thx Peter

### **Debug Information**

WordPress Version: 4.9.6

PHP Version: 7.1.13

MySQL Version: 5.6.33

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: No
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/oetool/public_html/wp-content/plugins/pods-2.x-2.6.11/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Sixteen Child

Currently Active Plugins:

    Admin Menu Editor: 1.8.4
    Capability Manager Enhanced: 1.5.8
    Display PHP Version: 1.4
    Fix Another Update In Progress: 1.0
    Groups: 2.3.1
    Members: 2.1.0
    Pods - Custom Content Types and Fields: 2.6.11
    Regenerate Thumbnails: 3.0.2
    TablePress: 1.9
    UpdraftPlus - Backup/Restore: 1.14.11

**### Pods Package Export**
[180626 Pods Package Export.txt](https://github.com/pods-framework/pods/files/2138442/180626.Pods.Package.Export.txt)

**Comment by jimtrue** [comment]
@PeterIbsen Thanks for uploading your structure. Which specific fields are you showing the issue in? 

Also, why you are using in most of your Multiple Select relationships a Selection Limit of -1? If you don't want to have any limits, you should just leave the field empty.

**Comment by jimtrue** [comment]
The primary place where I saw you had Multiple Select Checkboxes for One Way Relationships (no bidirectional) was in Cases. If you can provide any specifics as to what parts of your configuration are working in 2.6.11 and which ones aren't, we can better isolate down your edge case or see if this is something that we lost support for in 2.7+

**Comment by PeterIbsen** [comment]
@jimtrue When I go to the WP Admin interface for Cases I have the fields 'Research', 'Researchers', 'Entrepreneurs', 'Intrapreneurs' and 'Companies' all displaying as selection lists with check boxes. With 2.6.11 I can multi-select just fine; if I upgrade to 2.7+ the list now has single select functionality.
However, I was not aware that I shouldn't put -1 and {@post_title} in there - I removed those, and now it works fine in 2.7.6  :-)  Thank you!! Much appreciated!

**Comment by jimtrue** [comment]
Excellent, I'll mark this as closed. Glad you figured it out!
