### ISSUE TITLE
Pods displaying after the_content, even when auto-template is set elsewhere

### ISSUE THREAD

**Issue by joegrantstn** [pods-framework/pods#4695]
Description of issue:
--
I am using a Pods auto-template to display wholesale information after the woocommerce_short_description (the excerpt) shown here: ![](https://i.imgur.com/qJU0JJh.png)
However, even with the auto-template set to display after the woocommerce_short_description, it still ALSO shows after Description (the_content): ![](https://i.imgur.com/pM1dglB.png)

Template settings: https://i.imgur.com/fhMHq16.png
I have also tried checking the "Execute outside the WP Loop" box, but it doesn't help.

Expected Result
--
I'd like to have the pod display only after the short description, not after the main description.

Functional Example:
--
Product: https://bbtooinc.com/product/green-bead-garden

You will need to be logged in as a Wholesale User. Use this login info:
LOGIN: https://bbtooinc.com/wholesale-log-in-page
USER: adam@gearboxstudios.com
PASS: UYx6ve9#eReOOsNWdn0FX6So

If it helps troubleshoot, I can also make you a temporary Admin user on this site. Let me know at joe@stoysnet.com if you need admin access.

**Comment by JoryHogeveen** [comment]
Hi @joegrantstn 
I can't reproduce on my installation.
It looks like the `woocommerce_short_description` hook is also triggered within the "Description" tab, can you verify this isn't the case?

**Comment by JoryHogeveen** [comment]
I take that back, reproduced it on another installation, wil give it a look and report back here!

**Comment by JoryHogeveen** [comment]
@joegrantstn 
I added a solution in this PR: #4696
If you are able to test, let me know!

**Comment by joegrantstn** [comment]
@JoryHogeveen  Sorry, kind of new to Github... How do I test it if the new version isn't released?

**Comment by JoryHogeveen** [comment]
This is the direct link to the branch:
https://github.com/pods-framework/pods/tree/feature/4695-fix-autotemplate-hook-validation
On there you can download (green button) the dev version and overwrite your local installation.
Please test it on a staging/test server and not on a public site!

**Comment by joegrantstn** [comment]
Success! Tested on my WP Playground and it works as expected. Thanks for the quick response time!

**Comment by JoryHogeveen** [comment]
No problem!
