### ISSUE TITLE
Cannot see User Pod after WordPress reinstall

### ISSUE THREAD

**Issue by fiberlyone** [pods-framework/pods#4698]
Because of issues with other plug-ins, I reinstalled WordPress. I had a User Pod with 15 fields. 

To reinstall WordPress, I followed the steps at 
http://www.wpbeginner.com/wp-tutorials/how-to-uninstall-and-reinstall-wordpress/ 
(except step 0.  I just downloaded an SQL file of my tables, since I'd backed up earlier in the month)

When I got to step 6, the import threw up errors.

After step 7, I repopulated all the tables I kept one by one in the new database using SQL REPLACE.

I couldn't see my events or pages, so I tried step 6 again without errors.

In _posts_, I see all my pods users fields.  In _postsmeta_ meta_key=pod_reference, meta_value=a:1:{s:3:"pod";s:4:"user";}

When I click on Edit Pods, I'm taken to the _create new_ screen.  I select Users and this is what I see:
![screen shot 2018-01-05 at 7 15 59 am](https://user-images.githubusercontent.com/35142885/34616894-665458a0-f1ee-11e7-8687-2f520c4f1259.png)

**Comment by sc0ttkclark** [comment]
Have you tried clearing the Pods cache by going to Pods Admin > Settings > Clear Pods Cache?

**Comment by sc0ttkclark** [comment]
What does this query yield?

`SELECT ID, post_name, post_type WHERE post_type LIKE "_pods_%" ORDER BY post_type`

**Comment by fiberlyone** [comment]
Hi, Scott,

Please tell me how/where to make the query. 

Patty

----------------------------------------
Patty Hudson
fiberlyone@gmail.com

**Comment by fiberlyone** [comment]
Scott,

Saw this after the query email.

I just cleared the cache and that did the trick.   Edit Pods was no longer available and I’ve just added a User Pod.

Thanks.

----------------------------------------
Patty Hudson
fiberlyone@gmail.com

**Comment by jimtrue** [comment]
Are you able to access phpMyAdmin (MySQL access) through your CPanel or Client dashboard on your host account?

**Comment by jimtrue** [comment]
Never mind ;) Glad that worked! Thanks @sc0ttkclark
