### ISSUE TITLE
How does Pods tag a new CPT?

### ISSUE THREAD

**Issue by stllrnet** [pods-framework/pods#4701]
I ask this because I want to validate a CPT to show off on the categories' pages. But right now I don't know what is the tag for the CPT. Is it "test_post_type"?

This is the code I'm adding to the functions.php file:

`function add_my_post_types_to_query( $query ) {
	if ( (is_single() || is_home() || is_category() ) && $query->is_main_query() )
		$query->set( 'post_type', array( 'post', 'criticas_post_type' ) );
	return $query;
}`

And yes, my CPT is called Critica for singular and Criticas for plural.

**Comment by sc0ttkclark** [comment]
Your CPT name is the name of the pod. So if your singular title for the post type is `Critica`, it is more than likely just `critica` for the post type name unless you customized it by clicking "Edit" next to the name in the pod editor.
