### ISSUE TITLE
Pods Data Content Source Makes Scrolling Arrows Disappear

### ISSUE THREAD

**Issue by billren** [pods-framework/pods#4706]
Hi guys,

Issue: I am using the UABB Posts Module by the Astra team in BB/Beaver Themer and while displaying the Post results in a Carousel format, the arrows allowing the user to scroll disappears.

http://screencast-o-matic.com/watch/cFVirMo1mE

This issue is related to the thread:
https://pods.io/forums/topic/pods-data-content-source-overwrites-posts-module/

From what I understand, they've mentioned that Pods is overwriting the HTML structure and removing their carousel arrow’s HTML.

For the full context, please see thread: https://pods.io/forums/topic/pods-data-content-source-overwrites-posts-module/

Please let me know if you have any questions.

Thanks!

**Comment by jimtrue** [comment]
Are you using Beaver Themer?

**Comment by billren** [comment]
Hi Jim, yep, I'm using Beaver Themer.

**Comment by jimtrue** [comment]
I'm sorry, but this ticket actually needs to be entered over in our Pods Beaver Themer Add-on GitHub then, because any integration with Beaver Themer and Pods is managed in that plugin:

https://github.com/pods-framework/pods-beaver-builder-themer-add-on/issues/new

**Comment by billren** [comment]
No worries, switched to the BB Themer github.
