### ISSUE TITLE
Allow Remove CPT slug from post URL [Feature Request]

### ISSUE THREAD

**Issue by stllrnet** [pods-framework/pods#4707]
Hi Pods team! I took a dive into your forum and found a comment from Jim True saying post-slugs are typically required. Even when this stands true, there are some scenarios where clean url with just the name of the post are required. 

I'm starting to use Pods and for the site I'm running I've seen myself obligated to migrate some regular posts to a CPT, this is adding the CPT slug to the url, forcing me to create some redirections.

I think it would be great to have the option to not display the CPT slug in the url. Or if you have a function for this I'd be glad to know.

**Comment by jimtrue** [comment]
You might try checking out this article: https://wordpress.stackexchange.com/questions/203951/remove-slug-from-custom-post-type-post-urls

**Comment by ArtfulPussycat** [comment]
The above snippets on StackExchange work perfect and are easy to use. This is more of a WP core thing... the fact that you used Pods to create the CPT is irrelevant.

**Comment by jimtrue** [comment]
Yep, we provide the register_post parameters for URL Rewrites that WP provides without custom code or .htaccess changes. We really don't want to get into the job of adding this to Pods when it can be done with easy to locate code snippets that are WP approved. Closing this one; you are welcome to take this up with WP Core to provide a redirection API that would cover SEO URL Rewrites or other use cases like this, but this isn't really in the Pods area of responsibility.

**Comment by rafaeljuliani** [comment]
In advanced options of your pod, you can type "/" in the field "Custom Rewrite Slug" and also uncheck "Rewrite with Front".
