### ISSUE TITLE
CPT not respecting _Rewrite with Front_ option

### ISSUE THREAD

**Issue by danmaby** [pods-framework/pods#4709]
With permalink structure set to: `/%year%/%postname%/` on a vanilla 4.9.1 WP install with 2.7.1 PODs, using a default theme.  PODs/browser/etc. cache cleared and saved permalink settings. 

With the _Rewrite with Front_ option ticked I'm seeing the following structure: 

`example.com/cpt-name/post-name/` 

So the _Year_ isn't being included as expected?

**Comment by kathrynjws** [comment]
I'm having the same issue, is there a way to 'with_front' => false for the CPT's so the permalink structure is a clean example.com/cpt-name/post-name/ when the permalink structure for posts is /news/%postname%/

**Comment by quasel** [comment]
Seems resolved!

Sorry for the late reply, feel free to comment if you still have questions!
