### ISSUE TITLE
Media modal doesn't work on frontend using pods form

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4715]
It works when using the tinyMCE field but the `file` field doesn't trigger a media modal.

**Comment by JoryHogeveen** [comment]
Might be related:

```
tinymce.min.js?ver=4607-20171116:28
Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined
    at h (tinymce.min.js?ver=4607-20171116:28)
    at k (tinymce.min.js?ver=4607-20171116:28)
    at <anonymous>
```

**Comment by pglewis** [comment]
Disallowing the Media Library and forcing plupload when not in admin needs a rethink.  

https://github.com/pods-framework/pods/blob/2.x/classes/fields/file.php?ts=4#L478

**Comment by pglewis** [comment]
Pinging @sc0ttkclark: I don't think unconditional rejection is the right approach; at the very least I think we need a filter to override and allow using Media Library.

**Comment by sc0ttkclark** [comment]
Is this any help? https://wordpress.stackexchange.com/a/243402/296

**Comment by pglewis** [comment]
Sorry, it's not a technical issue to display it, we're disallowing it (see code link above)

**Comment by pglewis** [comment]
PR: #5149
