### ISSUE TITLE
PODS and Divi

### ISSUE THREAD

**Issue by wowdigital** [pods-framework/pods#4716]
I have the latest version of WP, PODS and Divi installed.

Small issue, but when I go to Divi > Theme Options, the menu CSS on the page is all incorrect – alignment is off, colours, etc. When I deactivate the PODS plugin, it goes back to normal.

This doesn’t affect any functionality, but the aesthetic and legibility.

Somehow your CSS is mixing in with theirs.

**Comment by jimtrue** [comment]
Can you provide any examples of the before and after? (Screenshots are fine, but it might help to provide any actual CSS that you can see that's having issues. Divi being a premium plugin means it's going to be hard to troubleshoot without sources.

**Comment by wowdigital** [comment]
I've done 2 screenshots.  You can see which one is the wrong layout.

When on the page, I opened up my inspector, and found this line:
<link rel="stylesheet" id="pods-styles-css" href="http://bbdc.wowdigital.com/wp-content/plugins/pods/ui/styles/dist/pods.css?ver=2.7.1" type="text/css" media="all">

is there a way to have that only inserted if you're on a screen that's related to pods? That way it won't affect other plugins/themes/options elsewhere in the admin panel.

https://pasteboard.co/H3IRKJw.jpg
vs
https://pasteboard.co/H3IS394.jpg

**Comment by rthaler-PBIG** [comment]
Is there any update on this issue? I was planning to use PODs along side with Divi in my next project. I feel pods is the best way to build the relationships I need between post types, but I don't want the use of Divi to be affected.

**Comment by jimtrue** [comment]
We're still missing details. It is impossible to troubleshoot this particular one without reference, CSS conflicts or actual code to determine where we're conflicting. Again, since this is a premium theme, we either need you folks to open a support ticket at Divi and have them escalate to our ticket for assistance, or you will have to provide _where_ we're conflicting.

**Comment by rthaler-PBIG** [comment]
Thanks for getting back Jim. I will reach out to the Divi support and see if there is anything on their end.

**Comment by jimtrue** [comment]
You can inspect your CSS in your Developer Console of your browser and if you can identify where the conflict is occurring you can let us know and that will help, but since we don't own Divi, it's very hard to troubleshoot Divi issues.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
