### ISSUE TITLE
Conflict with FreelanceEngine Theme - Marionette jQuery Conflict on pods-dfv.js

### ISSUE THREAD

**Issue by webacers** [pods-framework/pods#4717]
Hi, 
I just installed the plugin from WP and I am not able to create any POD as the post type dropdown is not visible. Please see the attached screenshot. 
Please let me know the resolution asap. 

Thanks.

![pod add new](https://user-images.githubusercontent.com/16399804/35164171-63926968-fd6f-11e7-9b06-0d7f66ac38cd.png)

**Comment by jimtrue** [comment]
@webacers What theme are you using in this installation? Also can you switch to a WordPress Default Twenty-"Something" theme and see if works properly?

**Comment by jimtrue** [comment]
@webacers We just had someone on our Slack Chat this morning provide a screenshot very similar to yours and was on a theme called 'FreelanceEngine' Theme. Take a look at your Developer Console on Chrome specifically to look for JavaScript errors or conflict errors.

**Comment by webacers** [comment]
Hi, 
Yes, we are using freelance engine theme. Please find the attached screenshot of the console error. 
It is related to marrionette. 
Please check and let me know if you have any resolution. 

![screenshot from 2018-01-24 22-29-05](https://user-images.githubusercontent.com/16399804/35345687-4220d720-0156-11e8-8c85-b7a3cfd46b2a.png)

Thanks,

**Comment by jimtrue** [comment]
@pglewis This one is for you. Looks like we have a conflict with Marionette.

**Comment by jimtrue** [comment]
@webacers Can you open a ticket with the FreelanceEngine Theme folks (since it's a premium plugin) and also refer them to this ticket? That will help us because since it's premium, we can't test without a copy of their theme.

**Comment by pglewis** [comment]
Closing for the catch-all #5237.  Note that other plugin and theme authors may still have to take action on their end to resolve the conflicts from their end.
