### ISSUE TITLE
Single-select Post Thumbnail does not display in Pods Template traversal

### ISSUE THREAD

**Issue by garypaul** [pods-framework/pods#4719]
When you have a Pod that's setup as a relationship, using the template tags, featured image is never output.

**Contrived Example**
Pods: `Recipes` and `Cuisines`

`Recipes` has the following fields
 - `post_title` ( obviously )
 - `post_thumbnail`  ( featured image )
 - `directions` ( text )
 - `main_cuisine`  ( bi-directional relationship field )

`Cuisines` has the following fields
 - `post_title` ( obviously )
 - `post_thumbnail`  ( featured image )
 - `cooking_style` ( text )
 - `all_recipes`  ( bi-directional relationship field )
 
Turning on templates and auto-templates for `Recipes` I could have the following for the Single template:

```
<h1>{@post_title}</h1>
Cuisine: {@main_cuisine.post_title}
<img src="{@main_cuisine.post_thumbnail._src, esc_attr}" />
Cooking Style: {@main_cuisine.cooking_style}

<!-- Ways of showing featured image of cuisine that should work, but doesn't -->
{@main_cuisine.post_thumbnail}
{@main_cuisine.post_thumbnail.medium}
{@main_cuisine.post_thumbnail.thumbnail}


<h2>Directions</h2>
{@directions}
```

No matter how I try to get the post_thumbnail of the related item, it will NOT show. Even if I wrap it in an `[each]` and allow multiple items.

**Comment by jimtrue** [comment]
I can confirm this is an issue.

Single-Select, related post, post_thumbnail should work. In a template:

`{@related_record.post_thumbnail}` returns nothing
`<img src="{@related_record.post_thumbnail_url}" />` returns `<img src="unknown" />`

I need to check the related to multiple in an each block. This is a BIG break, if this no longer works.

**Comment by jimtrue** [comment]
Workaround: use `{@id,get_post_thumbnail_id}`

**Comment by jimtrue** [comment]
Can confirm #4848 fixes this issue.
