### ISSUE TITLE
Field (file/image/upload) resets with post update, fixed by toggling "required"

### ISSUE THREAD

**Issue by dizziness1138** [pods-framework/pods#4720]
I have created a custom post type with three file/image/video fields. When I update a post, uploaded media is no longer attached to the field(s), the media is removed from the WP Media Browser, and yet the original media remains in the server storage. I can try uploading again, the file is stored with “-1, -2, etc.” suffix, attached to the post. But when I update the post, again media is not attached, removed from media browser, and file stays on the server. 

By way of troubleshooting, when I go to attach a file in the media browser, its showing all my attempts to attach the file to my custom post type (article) as separate posts.

Originally, the field was indicated as "required" when the posts were created. Recently I disabled the "required" field for other purposes. When re-enabling this field as "required," behavior returns to normal. 

<img width="583" alt="screenshot 2018-01-20 12 01 42" src="https://user-images.githubusercontent.com/24559405/35188557-e3269da6-fdfc-11e7-902c-fd0a895707f0.png">

**Comment by jimtrue** [comment]
@dizziness1138 Can you provide us the Pods Admin, Settings, Debug screen here as well?

**Comment by jimtrue** [comment]
Original forum post: https://pods.io/forums/topic/field-file-upload-resets-with-post-update/
Possible related forum post: https://pods.io/forums/topic/issue-with-images-disappearing/

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! We would need more details of your use case - maybe some 3rd plugin is interfering?
