### ISSUE TITLE
Template conditionals on Relatshonship fields

### ISSUE THREAD

**Issue by mrhyper** [pods-framework/pods#4721]
I have latest Wordpress (4.9.2) and latest PODS (2.7.1).
I'll say that I did try different legacy versions of both 9reverting Wordpress and / or PODS to earlier releaseas - especially pods 2.68 and lowe).

I have a problem in building PODS template, in which I use conditionals ([if][else][/if]) for reltionship fields.
I don't get any output from those conditionals - niether TRUE, neither FALSE.
[If][/if] line present in template is just ommited.

Example:
1. 1st pods cutom type: appartments (designed to present appartments to sell or rent).
2. 2nd pods custom type: Agents (people hired to sell appartments - each agent might have or not f.e. a phone number)
The 1st post type "Appartments" as one of it's fields has Agents dropdown - a relationship to Agents POD.
Not all of functionalities are working here.

If in APPARTMENTS TEMPLATE I use:
**[if agents]**THERE IS AN AGENT ASSIGNED TO THIS ENTRY**[/if]**
it works.
but if I use:
**[if agents.telephone]**
AGENT'S TELEPHONE NUMBER
**[else]**
print a note that there is no telephone number for this agent (or just skip whole paragraph line since it is not needed)
**[/if]**
it doesn't give any results: neither TRUE nor false.
I think that complexexed relathionship conditionals currently don't work.
Could someone help me if I'm wrong? Or add the bug to the fix list?

Wierd thing is that outside this [IF]{{ELSE] statement tag:
{@agents.telephone} works and prints out the correct number. But inside if conditional it just dissapears.

I do use an external theme Artbees Jupiter in this installation, but for testing purposes i DID DISABLE EVERYTHING and I'm left with vanilla Wordpress and Pods - PODS still doesn't work as I expect it to.

**Comment by jimtrue** [comment]
@mrhyper You can't use traversed fields in the IF conditionals. You've got agents.telephone, you'd have to nest those inside an `[each agent][/each]` and use `[if telephone][/if]` inside those. If your agents are multiple select, that's the appropriate way to loop through the Agents anyway.

https://pods.io/docs/build/template-tags-in-pods-templates/

If you absolutely need this kind of a reference: Create a separate Pods Template that is just for the agent details (it works at the Agent Post level, not at the Apartments); it includes the `[if telephone][else][/if]` blocks, etc.

Then inside your apartments' template call the agent blocks with a shortcode:

`[pods name="agents" where="ID={@agents.ID}" template="Agent Details"]`

You just need to make sure you configure your Pods Templates to call shortcodes:
https://pods.io/docs/build/using-shortcodes-pods-templates/

Let us know if the above works for you. If you're still having issues, drop into our Slack Chat at https://pods.io/chat/ on Monday (during our Support hours) and I'll see if I can help you out.

**Comment by benallfree** [comment]
> You can't use traversed fields in the IF conditionals

@jimtrue I noticed this too, it's a tough limitation to work around. Is there any reason or history behind why `[if]` doesn't support traversal or magic tags (which do support traversal)?

A useful alternative would be something like `[each]` but for single object relationships. Maybe `[with]`:

```
[with agent]
   [if telephone_number]
      {@telephone_number}
    [/if]
[/with]
```

**Comment by jimtrue** [comment]
We don't have a `[with][/with]` template tag ;) @benallfree

**Comment by jimtrue** [comment]
Check the History on the Frontier plugin that the Template Tags were inherited from. They are a very very very fragile environment. We've worked what magic we can to make them still work with our existing stuff, but honestly, the Pods Templates need a complete overhaul and probably need to switch to conditionals that _don't_ use a Shortcode styled control mechanism.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
