### ISSUE TITLE
Currency Field Saving... Weirdly

### ISSUE THREAD

**Issue by copperleaf** [pods-framework/pods#4724]
I've identified what may be a bug with Currency fields in v2.7.1.  In short, when a value is entered and saved, it repeats itself *comma separated*.  i.e., you enter "249" an it saves "249,249".  If you simply resave, you then get "249,249,249,249".  The third re-save gets real weird saving "249,249,249,249,249,250,508,800".  

Here's a screen capture video: https://www.dropbox.com/s/2bxszn1pf6xhtig/Pods%20Bug%2020180122.mp4?dl=0

Rolling back to v2.6.11 solves the issue.  I can give you access to the staging enviro if you want to dig into it directly on our site.  In Staging all other plugins are deactivated and the theme is Twenty Sixteen.

**Comment by JoryHogeveen** [comment]
Hi @copperleaf 
Could you make screenshots of your field configuration so I can try to reproduce? Thanks!

**Comment by copperleaf** [comment]
Sure thing!  Attached.
![capture](https://user-images.githubusercontent.com/5854482/35295153-99fa9174-0035-11e8-94e6-90288dc1a895.JPG)
![capture2](https://user-images.githubusercontent.com/5854482/35295154-9a0ac486-0035-11e8-8b73-e55acd335898.JPG)
![capture3](https://user-images.githubusercontent.com/5854482/35295155-9a1eb4fa-0035-11e8-9967-b8c72ffa6a69.JPG)
![capture4](https://user-images.githubusercontent.com/5854482/35295156-9a3687d8-0035-11e8-9e74-eb39e6e8fd93.JPG)

**Comment by JoryHogeveen** [comment]
I'm sorry to say that I'm unable to reproduce. Have you tried disabling plugins and switching to a default theme to see if the issue still occurs?

**Comment by copperleaf** [comment]
Jory,

Yes, all plugins are turned off and the theme is Twenty Sixteen.  Here are
credentials to the staging environment where you can examine it
first-hand.  Feel free to do anything you feel necessary in the Staging
enviro.  It's totally expendable.

https://heilsound.staging.wpengine.com/wp-admin/
podstech
yInlLKVDkyEJhA^n0KiESj64

Thanks!

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com


*I typically check email at 9:00 AM and 3:00 PM.  If you need something
time-sensitive midday, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*
*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

*Check our references: **https://www.youtube.com/watch?v=3-j7kPi4Oxs
<https://www.youtube.com/watch?v=3-j7kPi4Oxs>*

**Comment by JoryHogeveen** [comment]
@copperleaf 
Same thing happens with me when logged in to your installation. I can't find differences in the Pods code from what I am using to reproduce so the only thing I can think of is the must-use plugins.
Maybe @sc0ttkclark or @pglewis can take a look as well?

**Comment by copperleaf** [comment]
Hey Friends!  Just checking in on this.  Any update?


<https://chrome.google.com/webstore/detail/bitmoji/bfgdeiadkckfbkeigkoncpdieiiefpig>

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com


*I typically check email at 9:00 AM and 3:00 PM.  If you need something
time-sensitive midday, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*
*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

*Check our references: **https://www.youtube.com/watch?v=3-j7kPi4Oxs
<https://www.youtube.com/watch?v=3-j7kPi4Oxs>*

**Comment by copperleaf** [comment]
Hey Friends!

It seems this never got resolved.  The client just tripped over it again
and brought it back to my attention.

@sc0ttkclark <https://github.com/sc0ttkclark> or @pglewis
<https://github.com/pglewis> did you get a chance to look at it?

The staging area is still available:
https://heilsound.staging.wpengine.com/wp-admin/
podstech
yInlLKVDkyEJhA^n0KiESj64

Thanks guys, you're the best.

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com


*I typically check email at 9:00 AM and 3:00 PM.  If you need something
time-sensitive midday, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*
*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

*Check our references: **https://www.youtube.com/watch?v=3-j7kPi4Oxs
<https://www.youtube.com/watch?v=3-j7kPi4Oxs>*

**Comment by sc0ttkclark** [comment]
Change that password and send a new one to us at scott@pods.io

**Comment by quasel** [comment]
Did this ever happen? @sc0ttkclark

**Comment by JoryHogeveen** [comment]
@copperleaf 
This is an old issue, I believe we have fixed this. Can you confirm?

**Comment by copperleaf** [comment]
Yes, I believe it did.

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com

*I do not check email  until 2:00 PM daily.  If you need something
time-sensitive before that, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*

In case of Urgency, please call (970) 776-5021 and leave a message.  We'll
return your call as soon as humanly possible.

*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

**Comment by JoryHogeveen** [comment]
Thanks!
