### ISSUE TITLE
Simple (custom defined list) won't display using if each

### ISSUE THREAD

**Issue by KenLGD** [pods-framework/pods#4727]
When trying to display a Simple (custom defined list) as an UL, the correct number of list items appears but they are empty.
<img width="845" alt="screen shot 2018-01-23 at 9 05 03 am" src="https://user-images.githubusercontent.com/35733919/35282534-bb6942ea-0023-11e8-9f2c-1ce124f4df1e.png">
<img width="296" alt="screen shot 2018-01-23 at 9 54 48 am" src="https://user-images.githubusercontent.com/35733919/35282536-bb938726-0023-11e8-8858-53d1dcf9468f.png">
<img width="250" alt="screen shot 2018-01-23 at 9 14 52 am" src="https://user-images.githubusercontent.com/35733919/35282535-bb84655c-0023-11e8-8d60-7985f486277e.png">
<img width="556" alt="screen shot 2018-01-23 at 9 57 41 am" src="https://user-images.githubusercontent.com/35733919/35282623-ebcc7678-0023-11e8-9694-356990b7118b.png">
<img width="738" alt="screen shot 2018-01-23 at 9 57 19 am" src="https://user-images.githubusercontent.com/35733919/35282622-ebb9ca00-0023-11e8-801a-b938bc93f6e0.png">

**Comment by KenLGD** [comment]
Note: my HTML was sloppy. I have since closed the UL which doesn't fix the bug.

**Comment by jimtrue** [comment]
@KenLGD No worries on the HTML. This is more an issue of how these Simple Custom Defined Lists are supposed to be referenced properly. I think this is a problem with `display()` vs. `field()` on Relationships with Simple Custom Defined Lists in Pods Templates.

**Comment by jimtrue** [comment]
@KenLGD Try using `{@_value}` in your Template instead of `{@value}`.

**Comment by KenLGD** [comment]
Success! Thank you Jim.

**Comment by jimtrue** [comment]
Super!!! Glad to hear it @KenLGD
