### ISSUE TITLE
Discussion: Allow accessing WP native fields via Pods object?

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4730]
When developing a complex feature using Pods, a time usually comes where a feature requires accessing both WP-native fields and Pods fields for a given Pod.

Currently, Pods is not able to handle a number of use-cases which involve WP native fields:

* `pods_api_post_save_pod_item`
** Tracking WP-native changed fields
** Triggering  when WP native fields on a Pods object is saved.
*** If a feature being developed using Pods needs to perform some `pods_api_post_save_pod_item` action when ANY field (Pods or WP) is changed, the developer must hook into both `pods_api_post_save_pod_item` AND `save_post`. Complex code is also needed to stop any action by both action triggers
* Modifying the `post_status` or `post_parent` fields via Pods::save()
* Modifying various User fields (`first_name`, `last_name` etc) Pods::save()
* Updating a record where WP & Pods fields are to be updated requires calling both `Pods::save()` & `wp_update_post` etc (Possible performance issue from requiring multiple updates?)

As I understand, Pods 2.8 will introduce a new `PodsObject` feature. It seems that this may be a good time to harmonise the WP/Pods API so that Pods can be used as a single API for interacting with a Pod.

**Comment by quasel** [comment]
the most scenarios should be covered by pods, at least from the post edit screen everything works just fine 
example use case for post_title: 
https://docs.pods.io/code-snippets/create-post-title-from-fields-in-the-post-using-pods_api_pre_save/

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! 
( native fields are to be found under object_fields )
