### ISSUE TITLE
Feature Request - Support "WP Multilang" Multilingual plugin for WordPress

### ISSUE THREAD

**Issue by ommedical** [pods-framework/pods#4731]
Dear Developers,
you are doing a great job and really very quality work too..
The plugin that is great combination of great tools..
thanks alot..

also request you if possible please make compatibility for "WP Multilang" wordpress multilingual plugin as it's also as equal usefull and advance as that of "pods"..
Not it's gui is so easy and usefull but it helps users to translate the contend in commited and real meaning

website link is as below
[WP Multilang](https://github.com/VaLeXaR/wp-multilang)

![2018-01-26_184238](https://user-images.githubusercontent.com/35499925/35441505-bc2c11dc-02c9-11e8-8748-62fb21b2df7f.jpg)
![2018-01-26_184640](https://user-images.githubusercontent.com/35499925/35441508-bcb1a298-02c9-11e8-9eab-492b05d46135.jpg)

**Comment by quasel** [comment]
well we just create a CPT - there is nothing special with it - seems the Plugin doesn't support translating CPT at least a quick google search just lead to WPML ;)
