### ISSUE TITLE
Feature Request - Template - Shortcode - Listing Viewing Editing - All Related List Items

### ISSUE THREAD

**Issue by ommedical** [pods-framework/pods#4732]
# Feature Request
**Feature Request - Template - Shortcode - Listing Viewing Editing Quick Editing - All Related List Items and their related fields**

Better if there is a kind of shortcode that canbe used to create template that can list all the related list items if not null and as per privilage rules of userroles.
so that admin/user can able to present each list items and their relative fields may be aligned horizontally (multiple list items in single box or div or say without pagination) or vertically (ie single list item on a single page or say with pagination)

![2018-01-26_152117](https://user-images.githubusercontent.com/35499925/35440724-a9a63f04-02c6-11e8-80f2-02e741895fc8.jpg)
![2018-01-26_175513](https://user-images.githubusercontent.com/35499925/35440725-aa0d879a-02c6-11e8-925e-22ac0d878dcc.jpg)
![2018-01-26_150951](https://user-images.githubusercontent.com/35499925/35440811-01b67bfa-02c7-11e8-82e5-1a595cc9a653.jpg)
![2018-01-26_183243](https://user-images.githubusercontent.com/35499925/35441168-793949ea-02c8-11e8-9421-32423bbd66c0.jpg)

**Comment by quasel** [comment]
if I understand you correctly you should take a look at Admin Columns Pro - that might suit your needs - at least in parts!

**Comment by quasel** [comment]
And take a look at the new List View option for related items!
