### ISSUE TITLE
UI conflict with WP All Import

### ISSUE THREAD

**Issue by trey8611** [pods-framework/pods#4733]
Hello, I'm Trey and I work for Soflyy (creators of WP All Import/Export). We recently had someone report a UI issue within WP All Import that only happens when Pods is active. I was able to reproduce the problem with Pods 2.7.1 on a test site (latest version of WordPress) - here's a quick video to show the issue: https://d.pr/4krAb4/LtKIDsFz3p.

I found that this is being caused by the /pods/ui/styles/dist/pods.css file. If I disable the file or comment out these lines:

`.left{ float:left; } .right{ float:right }`

Then, the UI works fine. I am not certain how to fix this correctly, so I figured I should reach out to you guys. Let me know if you need any information from our end.

**Comment by quasel** [comment]
Seems to be fixed! at least on my installation - does it still happen for you? Tested with 2.7.9
Sorry for the late reply, feel free to comment if you still have questions!
