### ISSUE TITLE
Visual builders for content templates?

### ISSUE THREAD

**Issue by benallfree** [pods-framework/pods#4738]
I'm interested in integrating visual builders like Beaver Builder with the Pods content template feature. Right now the template editor is tightly coupled with CodeMirror and can't benefit from most visual builders because it doesn't use the standard `editor` field (which builders override).

Is there any history on this? I'd like to contribute some code updates if there is no reason not to.

**Comment by quasel** [comment]
https://github.com/pods-framework/pods-beaver-builder-themer-add-on iris the current integration for Beaver Themer using their field connections

**Comment by quasel** [comment]
hi didn't hear back from you going to close the issue - any help on the integration is gladly accepted!
