### ISSUE TITLE
Numeric field in Advanced Content Type rounded to 6 decimals

### ISSUE THREAD

**Issue by rodpal** [pods-framework/pods#4741]
I have a "Plain number" field with the following settings
Format: 1,234.00
Decimals: 8
Maximum Length: -1

Input value: 0.12345678
The number is rounded to 0.12345700

The field looks correctly setup in database: DECIMAL(64,8)

This only happens with the Advaned Content Type fields. With other types (custom post types/taxonomies) the number is not rounded to 6 decimals

**Comment by 0xLBF** [comment]
I traced this problem to PodsData::insert_on_duplicate where the format specified is left as "%s" for every field. Perhaps it should use "%g" instead when the input is a double ?  https://stackoverflow.com/questions/34540812/what-type-of-format-should-i-use-when-using-wpdb-insert-on-a-double

**Comment by 0xLBF** [comment]
Traced it further to the vsprintf inside $wpdb->prepare and I found this 8 year old comment buried inside the comment section of the PHP documentation at http://php.net/manual/en/function.sprintf.php : "To add to other notes below about floating point problems, I noted that %f and %F will apparently output a maximum precision of 6 as a default so you have to specify 1.15f (eg) if you need more." .

**Comment by pglewis** [comment]
PR: #4742
