### ISSUE TITLE
Add New Relationship Modal

### ISSUE THREAD

**Issue by leepeterson** [pods-framework/pods#4743]
WP: v4.9.2
Pods: v2.7.1
Field Type: Relationship
Severity: Low/Cosmetic

When adding new posts via the Relationship modal, the WYSIWYG toolbar covers overflowed content. Not sure how else to describe it. See: http://s.rma.host/pInE

Seems it functions as expected, but perhaps the Title field should stay in place along with the WYSIWYG toolbar below it.

**Comment by quasel** [comment]
Seem to no longer happen - or I misunderstood it - and the screenshot is no longer available! 

Sorry for the late reply, feel free to comment if you still have questions!

**Comment by leepeterson** [comment]
Yeah, this only occurred for a single release cycle. Good to remain closed.
