### ISSUE TITLE
Some "Profile" records (Council Members) are not displayed

### ISSUE THREAD

**Issue by mb4wdc** [pods-framework/pods#4748]
There are 8 Profile records that are Council Members  Regardless of whether sorting by last name, some records are missing. When sorted by last name the last two records are missing. When NOT sorted by last name, the two that were missing before show up but others do not.

Let me know if there's other information you need. And I'll send that Migration:Export file once I'm told where it was created.

Thank you.

Margie

![editor-shortcodes](https://user-images.githubusercontent.com/35839084/35809312-3ab5ec4c-0a56-11e8-8a63-71479c547f3a.PNG)
![template - council members](https://user-images.githubusercontent.com/35839084/35809314-3d83c4da-0a56-11e8-90c0-567d55f0fa08.PNG)
![profile pod fields](https://user-images.githubusercontent.com/35839084/35809317-413c1d02-0a56-11e8-9ba4-9dbf1d82e49a.PNG)
![missing-robbin smith-page1](https://user-images.githubusercontent.com/35839084/35809323-44b12a7c-0a56-11e8-882b-44ca82a1d27a.PNG)
![missing-robbin smith-page2](https://user-images.githubusercontent.com/35839084/35809327-46647932-0a56-11e8-81c5-9488c18fa82b.PNG)

**Comment by jimtrue** [comment]
Looks like you created this one twice: #4747 I'm closing this issue in favor of the first @mb4wdc I just changed the name of the original one so it was a clearer bug title.

**Comment by mb4wdc** [comment]
[Pods Migration Export.docx](https://github.com/pods-framework/pods/files/1695512/Pods.Migration.Export.docx)

**Comment by jimtrue** [comment]
Trying to clarify how this issue differs from #4747 Are the "same names" always missing if you do an orderby or is it always the last two records?

**Comment by mb4wdc** [comment]
Screenprints of results with and without orderby showing records missing in both instances.

![page builder plugin by cmsmasters](https://user-images.githubusercontent.com/35839084/35810970-5a5dbab6-0a5b-11e8-98ae-c018907d510d.PNG)
![shortcode-no page builder](https://user-images.githubusercontent.com/35839084/35810988-64cad146-0a5b-11e8-823b-843ce0943d23.PNG)
![display-no page builder-no orderby](https://user-images.githubusercontent.com/35839084/35811060-8eecae18-0a5b-11e8-91f2-c404c025f540.PNG)

![shortcode-no page builder-with orderby](https://user-images.githubusercontent.com/35839084/35811101-a42d6218-0a5b-11e8-9b0f-5d0d43c469e0.PNG)
![display-no page builder-with orderby-page1](https://user-images.githubusercontent.com/35839084/35811134-b2a790f2-0a5b-11e8-90d4-12dfe773a7b2.PNG)
![display-no page builder-with orderby-page2](https://user-images.githubusercontent.com/35839084/35811136-b4c6fb2a-0a5b-11e8-909b-7d6f66ee2369.PNG)

**Comment by mb4wdc** [comment]
With #4747 only the last record of the four records is missing.

With #4748 there are records missing regardless of using orderby.

**Comment by jimtrue** [comment]
For clarification:

Are the only templates you're having an issue with display the 'Council Members Template' and the 'Contract and Grievance Template'? The other templates/shortcodes calling those templates are displaying fine?

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
