### ISSUE TITLE
jQuery Conflict with WP Smush Pro in Relationship Fields

### ISSUE THREAD

**Issue by pmsteil** [pods-framework/pods#4749]
After updating to version Pods 2.7.1 the other day our RELATIONSHIP fields stopped showing up in all our custom post types.

Here is a video that shows the before and after.
https://www.dropbox.com/s/q2xb0vqpazfnwfw/pods%20latest%20version%20issue.mp4?dl=0

The fix for this was to use the "WP Rollback" plugin to roll back to version 2.6.11.

WP Version: 4.9.3
PHP Version: 7.0.27-1~dotdeb+8.1
PODS Version: 2.7.1

**Comment by jimtrue** [comment]
@pmsteil Do you have a Development site? You've got more things in the possible fault domain than just WordPress and Pods looking at the list of plugins down the left hand side of your Admin screen. I'm thinking you're running into a possible jQuery conflict.

If you have a Development copy of your site, can you re-upgrade to Pods 2.7.1 and check for Javscript Conflicts in your Developer Console in your browser?

Another method would be to disable other plugins except WordPress and Pods and turn on one plugin at a time until you find the one that is causing the relationship fields to not display.

**Comment by pglewis** [comment]
Check for errors in the dev tools / firebug console

**Comment by pmsteil** [comment]
@jimtrue thanks for the reply.

This is a huge site and I don't have a dev site.

I can do that testing to find any possible plugin/theme conflicts on the site late tonight.  But keep in mind that reverting back to 2.6.11 fixed this.  

I had looked for javascript errors when we were on 2.7.1 and (from memory) I do know there was one or two errors showing up that referred to the load-scripts.php file.  

But running the 2.6.11 version I still get these (took this screenshot just now) - the one marked with an arrow is the one I remember seeing before, maybe twice.
http://screencast-o-matic.com/screenshots/u/fObY/1518022930718-82373.png

Is load-scripts.php related to pods?

**Comment by jimtrue** [comment]
Did you just upgrade to Pods 2.7 and Pods 2.7.1 this week? They've been out since December. They included a *substantial* change to the relationship fields which is why Pods 2.7 was in beta for six months before we went live with it to make sure folks had a chance to test.

If you have a huge site, all the more reason you _need_ to have a development/staging site to deal with problems that will inevitably occur when plugins and WordPress updates.

I don't recognize that URL of your load-scripts.php; that looks like default WordPress or possibly your theme.

**Comment by jimtrue** [comment]
Depending on your hosting company, most of them will let you spin up a staging copy of your production site. You can also provide us your full list of plugins by cutting and pasting the Pods Admin, Settings 'Debug Details' here as well.

**Comment by pmsteil** [comment]
Yes, I think we did just upgrade.  

I will get you more info on this tonight / tomorrow, thanks.

**Comment by jimtrue** [comment]
Thanks @pmsteil I know it's frustrating, but it's usually not hard to find out what is causing the conflicts.

**Comment by pmsteil** [comment]
@jimtrue ok, to the bottom of this.  All works well with no script errors when I disable this plugin:

WP Smush Pro v.2.7.7 by WPMU DEV - https://premium.wpmudev.org/

Do you have access to this plugin to test with?

**Comment by jimtrue** [comment]
We doc not have access to it, nope. I've heard a few people mention issues with WP Smush. You'd have to open a ticket with them as a premium client and refer them to this ticket so we could work this to resolution. Guessing it's a name spacing issue.

**Comment by jimtrue** [comment]
@pmsteil Were you able to open a ticket with the WP Smush Pro folks and direct them over to this ticket? We're going to be hard-pressed to able to fight down the conflict in this issue without some sort of access for testing.

**Comment by quasel** [comment]
works for me in 2.7.9
