### ISSUE TITLE
Receiving notice in the Members plugin Role Editor related to Pods

### ISSUE THREAD

**Issue by corypina** [pods-framework/pods#4750]
I'm using the [Members](https://wordpress.org/plugins/members/) plugin for role management. Whenever I'm in the Role Editor (and only there) I see the following notice at the top of the page:

`Notice: Trying to get property of non-object in /www/wp-content/plugins/pods/components/Templates/class-pods_templates.php on line 177`

I haven't seen this anywhere else, and it doesn't seem to affect any functionality, but it's a persistent notice.

Here's the line in context, with line 177 indicated:

```
/**
	 * setup meta boxes.
	 *
	 *
	 * @return    null
	 */
	function add_metaboxes( $slug, $post = false ) {

		if ( !empty( $post ) ) {
	     [LINE 177]	if ( !in_array( $post->post_type, array( '_pods_template' ) ) ) {
				return;
			}
		}
		else {
			$screen = get_current_screen();
			if ( !in_array( $screen->base, array( '_pods_template' ) ) ) {
				return;
			}
		} ...
```

**Comment by jimtrue** [comment]
@corypina Are you also using our Pods Admin, Components, Roles & Capabilities?

That's an odd one because it's specifically in Pods Templates. I have Members on many of my sites and just checked locally in the Role Editor with Debug & Debug display enabled and I'm not getting the above errors. Can you provide us a Debug listing from Pods Admin, Settings, Debug and upload it here?

**Comment by corypina** [comment]
@jimtrue No components enabled on this site. I do have some custom plugins I've written, some of which refer to Pods, but I tried disabling them — no change.

I'm also using the `Pods Beaver Themer Add-On`, which also didn't fix it when deactivated.

Debug info:
```
Debug Information
WordPress Version: 4.9.4
PHP Version: 5.6.33-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.6.32
Server Software: Flywheel/4.1.0
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

Session Save Path: /tmp
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440

Opcode Cache:
Apc: Yes
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: Yes
APCu: Yes
Memcache: Yes
Memcached: No
Redis: No
WPDB Prefix: wp_327zn6w4nl_

WP Multisite Mode: No
WP Memory Limit: 200M

Pods Network-Wide Activated: No
Pods Install Location: /www/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:
All In One SEO Pack: 2.4.4.1
Beaver Builder Plugin (Pro Version): 2.0.4.4
Beaver Themer: 1.1
CMS Tree Page View: 1.5
Customizer Export/Import: 0.7
Display Posts Shortcode: 2.9.0
Enhanced Media Library: 3.0.beta2-29
Featured Block: 1.0
Fuller.edu Custom Beaver Builder Modules: 1.0
Fuller.edu Custom Functions: 1.4
Fuller.edu Publishing and Editorial Workflow: 1.0
Members: 2.0.2
Pods - Custom Content Types and Fields: 2.7.1
Pods Beaver Themer Add-On: 1.2.1
Redirection: 3.1.1
String Locator: 2.3.0
Swiftype Search: 1.1.49
Template Part Shortcode: 0.1
User Switching: 1.3.0
WP-FormAssembly: 2.0.2
WP Editor: 1.2.6.3
WP Mail SMTP: 1.2.5
```

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions! works for me now! if it's still an issue pleas inform us!
