### ISSUE TITLE
Missing items in checkbox/select pick field against Pages

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#4751]
I recent dealt with a site where a page would not show in the select and checkbox UI's. The following was found/tested.

- Renaming did not help
- Cloning with a post clone plugin did not affect anything
- Changing to a list or autocomplete **fixed** the problem
- It  appears to have only happened with 1 page supposedly
- It did not work as a child of any other page, only a parent
- It has been tracked to `pods_hierarchical_list` that it modifies the list. The SQL returns fine.

I do not have any package export currently.

**Comment by jimtrue** [comment]
@pcfreak30 Can you duplicate the issue? The package export would also help.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
