### ISSUE TITLE
Numeric Value Simple Custom Defined Relationship Multiple-Select  Not Saving

### ISSUE THREAD

**Issue by texomacog** [pods-framework/pods#4753]
## Issue Overview
I've discovered a bug introduced in the 2.7 update to Pods. I have a custom defined-list relationship field (checkbox) for a custom post type - when saving changes to the post, the checkbox is cleared after the page refresh. On the front end the data is displayed correctly, but if I make an edit to the post and don't recheck the box then the value is removed from the post.

I can confirm this issue occurs with both 2.7 and 2.7.1; rolling back to 2.6.11 resolves the bug.
For debug data on my WP configuration and additional details for this bug. please refer to the original post in pods forum: https://pods.io/forums/topic/relationship-field-changes/#post-198180

## Expected Behavior
When saving the values in a simple custom defined relationship, the values should be selected upon refreshing the edit screen (either after Save/Update or when visiting the post again).

## Current Behavior
Upon Saving the Values, they are written to the database properly, but the user interface in the Admin is not showing the correct values chosen. In some cases it will show one selected, in some cases, none selected

## Possible Solution
Not sure what the issue is specifically, but it seems relegated to the UI of the fields and is _specifically_ limited to Numeric 'value' choices.

## Steps to Reproduce (for bugs)

1. Create a Relationship Field, Simple Custom Defined List
2. Use Numbers for the 'Values' or value|Label choices
3. Save a Record with choices selected under 2.6.11 - Works properly
4. Open same record under 2.7+, values are not selected and values do not update in the UI though they are saved properly in the database and display properly.

## Pods Package Export (helpful!)
[simple-json.txt](https://github.com/pods-framework/pods/files/1903515/simple-json.txt)
This import also includes a simple 'display' template so you can quickly see the issue.

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Debug Information
WordPress Version: 4.9.2

PHP Version: 7.0.18

MySQL Version: 5.7.18

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Session Save Path: /opt/bitnami/php/tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: TCOG

Currently Active Plugins:

Advanced Post Manager: 4.4
Force Regenerate Thumbnails: 2.0.6
Gravity Forms: 2.2.5
Gravity Forms Geolocation Add-on: 2.5
Gravity Forms Multilingual: 1.3.16
Gravity Forms SendinBlue Add-On: 1.0.5
Pods – Custom Content Types and Fields: 2.7.1
Post SMTP: 1.8
SendinBlue Subscribe Form And WP SMTP: 2.8.3
Slider Revolution: 5.4.6.3.1
The Events Calendar: 4.6.10
The Events Calendar PRO: 4.4.22
WPBakery Page Builder: 5.4.5
WPML Multilingual CMS: 3.9.2
WPML String Translation: 2.7.2
WPML Translation Management: 2.5.1
```
</details>

**Comment by jimtrue** [comment]
Here's the Debug Information from that post:
Debug Information
WordPress Version: 4.9.2

PHP Version: 7.0.18

MySQL Version: 5.7.18

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Session Save Path: /opt/bitnami/php/tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: TCOG

Currently Active Plugins:

Advanced Post Manager: 4.4
Force Regenerate Thumbnails: 2.0.6
Gravity Forms: 2.2.5
Gravity Forms Geolocation Add-on: 2.5
Gravity Forms Multilingual: 1.3.16
Gravity Forms SendinBlue Add-On: 1.0.5
Pods – Custom Content Types and Fields: 2.7.1
Post SMTP: 1.8
SendinBlue Subscribe Form And WP SMTP: 2.8.3
Slider Revolution: 5.4.6.3.1
The Events Calendar: 4.6.10
The Events Calendar PRO: 4.4.22
WPBakery Page Builder: 5.4.5
WPML Multilingual CMS: 3.9.2
WPML String Translation: 2.7.2
WPML Translation Management: 2.5.1

**Comment by jimtrue** [comment]
@texomacog Can you provide us with a Pods Admin, Components, Migrate: Packages, Export of this field configuration? It will create a JSON configuration that you can cut and paste; copy and paste that into a text file and upload here as it will let us see if we can replicate the issue on another machine.

**Comment by texomacog** [comment]
@jimtrue 
[20180209 Pods bug report.txt](https://github.com/pods-framework/pods/files/1711619/20180209.Pods.bug.report.txt)

**Comment by webswk** [comment]
Hi, Exprienced the same problems with checkboxes not saving.

[pods-export-checkbox-not-saving.txt](https://github.com/pods-framework/pods/files/1743304/pods-export-checkbox-not-saving.txt)

**Comment by jimtrue** [comment]
I was able to confirm this one. The issue seems to be specific to NUMERIC Value Simple Custom Defined Relationships, ie where the value|Label is numeric|Label or even if the value list is simply numeric. The values are saved properly to the database (can confirm upon viewing the record), but the INPUT Options/Selected Options are wiped on load or 'save'.

This works correctly under 2.6.11 and is broken under 2.7+

**Comment by jimtrue** [comment]
I can also confirm a combination of numeric/alphanumeric work fine, ie 00F|Blue, 0F0|Green. It seems to be only an issue when the values are numeric only.

**Comment by jimtrue** [comment]
[simple-json.txt](https://github.com/pods-framework/pods/files/1903491/simple-json.txt)
Migration package for testing. I can also confirm that this is broken under 2.x as well.

**Comment by pglewis** [comment]
PR: #4928

**Comment by jimtrue** [comment]
@texomacog If you have a development site, you can test this one now using https://pods.io/latest/

**Comment by jimtrue** [comment]
Correction @texomacog this hasn't been merged yet, so you can test from this link:
https://github.com/pods-framework/pods/archive/feature-4892-multiselect-predefined-lists.zip

**Comment by texomacog** [comment]
@jimtrue : it appears that this issue has been remedied with this latest link you provided me with.
