### ISSUE TITLE
Fatal error: Call to a member function total() on boolean

### ISSUE THREAD

**Issue by armandoduran** [pods-framework/pods#4755]
Hi Everyone,

This issue may be a bug.  The only reference I found about it is issue [#3047](https://github.com/pods-framework/pods/issues/3047).

### Description

- This is a web application that runs entirely on the back-end of WordPress.  
- The back-end has been styled in order to give the application look.
- The system has various modules, one of them is called Time Entries which is a Pod that is used to track the hours employees spend on specific projects.
- The name of the Pod is time_report.
- The user basically selects a project, labor type and the minutes spent which is a drop-down field.
- I have a function that first checks if the module (Pod) is time_report, based on that, I run a function that queries the time_report Pod for that specific user and the date.
- This returns an array with some info that I use  to display via jQuery on a label where they add the time, how much time is left for the day and for the week.
- The screenshot attached is just to show the screen where the minutes spent are added. It does not contain the error because at this point it seems to happen randomly.
<img width="1301" alt="screen shot 2018-02-13 at 3 18 37 pm" src="https://user-images.githubusercontent.com/2701240/36179517-6f6efa74-10d1-11e8-8376-6bc109c3c18f.png">
 
- Everything has been working fine so far but recently a few users have reported the following:
  > Fatal error: Call to a member function total() on boolean

### Code

**The line and code that triggers the error is this:**
   `f ( 0 < $time_report->total() ) {`

**The entire function**

// Get total of minutes spent based on parameters.
'function get_time_report_minutes_spent( $date, $user_ID = 0 ) {

	if ( $user_ID == 0 ) {
		$user_ID = get_current_user_id();
	}

	// Initialize array and add some desault values.
	$total_minutes_spent = array(
		'isNew'				=> module_is( 'time_report', 'new' ),
		'beforeMinutes' 	        => '<br /><small><label class="minutes-spent">',
	        'MinutesSpentDay'	        => 0,
		'MinutesLeftDay' 	        => 480,
		'afterMinutes'	 	        => ' left today</label></small>',
		'day_html' 			=> '', // For echoing debug results, etc.
		'beforeMinutesWeek'	=> '<br /><small><label class="minutes-spent-week">',
		'MinutesSpentWeek'	=> 0,
		'MinutesLeftWeek'	        => 2400,
		'afterMinutesWeek'	        => ' left this week</label></small>',
		'week_html' 		        => '', // For echoing debug results, etc.	
		'message'			=> '', // For general error and info messages
	);

	// Query time_report Pod for specified user.
	$params = array(
		'where' => 'post_author = ' . $user_ID,
	    'limit' => -1,
	);
	$time_report = pods( 'time_report', $params );

	$this_monday = date('Y-m-d', strtotime('monday this week', strtotime($date)));

	// Loop through results and accumulate/calculate minutes spent per day and week
	if ( 0 < $time_report->total() ) {

		$total_minutes_spent['day_html'] += '<p>' . $time_report->total() . ' records where found:</p>';

	    while ( $time_report->fetch() ) {

			$time_report_minutes_spent = $time_report->display( 'time_report_minutes_spent' );
			$separator_pos = strpos( $time_report_minutes_spent, '-');
			
			// If there is an hour indicator, take only minutes.
			if ( $separator_pos == 0 ) {
				$minutes_spent_value = intval( $time_report_minutes_spent);
			} else {
				$minutes_spent_value = intval( substr( $time_report_minutes_spent, 0, $separator_pos) );
			}
			
			// Accumulate hours for the weeek (starting Monday).
			if ( $this_monday <= $time_report->field( 'time_report_date' ) ) {
				$total_minutes_spent['MinutesSpentWeek'] += $minutes_spent_value;
			}

			// Only accumulate for specified day.
			$report_date = date('Y-m-d', strtotime( $time_report->field( 'time_report_date' ) ));
			if ( $date == $report_date ) {

				$total_minutes_spent['MinutesSpentDay'] += $minutes_spent_value;
				$total_minutes_spent['day_html'] 		+= '<p>Time spent: ' 	. $time_report->display( 'time_report_minutes_spent' ) . 
											  			   ' - Date: ' 	 		. $time_report->field( 'time_report_date' ) . 
											  			   ' - Entry desc.: ' 	. $time_report->field( 'post_title' ) . '</p>';
			}

	    }

		// Populate the rest of the values into the array before returning it.
		$total_minutes_spent['MinutesLeftDay'] = 480 - $total_minutes_spent['MinutesSpentDay']; //8 Hrs per day max
		$total_minutes_spent['afterMinutes'] = ' (' . round( $total_minutes_spent['MinutesLeftDay'] / 60, 1) . ' hrs.) left today</label>';
		$total_minutes_spent['MinutesLeftWeek'] = 2400 - ### $total_minutes_spent['MinutesSpentWeek']; //40 Hrs per week max
		$total_minutes_spent['afterMinutesWeek'] = ' (' . round( $total_minutes_spent['MinutesLeftWeek'] / 60, 1) . ' hrs.) left this week</label>';

	} else {
		$total_minutes_spent['message'] = '<p>No records found</p>';
	}

	$total_minutes_spent['day_html'] += '<p>Total minutes spent: ' . $total_minutes_spent['MinutesSpentDay'] . '</p>';
	$total_minutes_spent['week_html'] += '<p>Total minutes spent for the week: ' . $total_minutes_spent['MinutesSpentWeek'] . '</p>';

	return $total_minutes_spent;

}`

### Debug Info (from Pods settings):

WordPress Version: 4.9.4

PHP Version: 5.6.31-4+wpengine10

MySQL Version: 5.6.38

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: No
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: Yes
    Redis: Yes

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/tslplanner/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

    Admin Columns - Pods add-on: 1.0.2
    Admin Columns Pro: 4.0.5
    Categories Metabox Enhanced: 0.6.1
    Duplicate Post: 3.2
    Legacy - White Label WordPress Admin Theme: 5.2
    My Custom Functions: 4.3
    Pods - Custom Content Types and Fields: 2.6.9
    Redirection: 2.6.2
    TSL Planner: Beta 0.6
    Ultimate Branding: 1.8.6
    User Activation Keys: 4.6
    User Role Editor: 4.35
    View Admin As: 1.7.2
    WP All Export Pro: 1.5.1
    wpDataTables: 1.7.1
    WP Help: 1.5.2
    WPide: 2.4.0
    WPMU DEV Dashboard: 4.3.1

**Comment by quasel** [comment]
Did you solve it? sounds like https://pods.io/docs/code/pods/ returns false 

add a check 
`if ( $pods->exists() ) { 
    // This pod exists! 
} `

Going to close this as it's been open a long time sorry for missing it! 
Feel free to comment if you have still questions.
