### ISSUE TITLE
Possible to discover if item saved using Pods::save() is a new item?

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4757]
Using the return value of `Pods::Save()`, is it possible to infer whether the item just save dis new or not?

I've taken a walk through the result, but nothing stands out to me. My wacky idea is to use post_date timestamp, but this seems less reliable than an actual flag in the response?

**Comment by quasel** [comment]
no it just returns the ID you can use any of the pods_api_pre_save or post_save or other filter around it there you have access to `$is_new_item`as a parameter 

Sorry for the late reply, feel free to comment if you still have questions!
