### ISSUE TITLE
Separate public/non-public post types in relationship field options list

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#4758]
![screen shot 2018-02-17 at 12 55 57 pm](https://user-images.githubusercontent.com/1994311/36344022-19954d38-13e2-11e8-9aa7-7f6a47380037.png)

I find it a little off that CSS rules, oEmbed cache, and other hidden post types show here __and I actually understand why they are used__. I would suggest two groupings "Post Types" and "Private Post Types"

**Comment by jimtrue** [comment]
@Shelob9 How would you designate us pulling 'private' post types? What code in the registration of those post types indicates those as private?

**Comment by Shelob9** [comment]
Yes, Post Types have a public argument.

**Comment by jimtrue** [comment]
@Shelob9 Doh, wasn't thinking of that particular switch. For some reason, I was thinking like the hidden custom fields prefixed with underscore. Thinking forward: is there a place on post type registration that indicates ownership/app or plugin namespace?

**Comment by quasel** [comment]
Good Idea!
