### ISSUE TITLE
SiteGround Memcache issues creating new pods and adding new fields

### ISSUE THREAD

**Issue by exprance** [pods-framework/pods#4759]
I got here from this previous post:

https://pods.io/forums/topic/siteground-memcached-pods-cannot-create-cpt/

It seems I can create the pods and fields when I disable Memcache or even when I flush the cache right before I do anything with Pods. Other than that I get an error and the fields I created disappear from the interface but still exist in the database.

I get the error "Pod not found"

Pods version: 2.7.1
WordPress version: 4.9.4

**Comment by lkraav** [comment]
Siteground Memcached has problems with other things as well. ACF is one notable case. Nobody has been able to do anything sensible about it thus far.

I use Redis everywhere else, so have had little motivation to debug Memcached issues so far. Would be nice if someone would figure it out.

**Comment by quasel** [comment]
I remember @sc0ttkclark suggesting the use of https://wordpress.org/plugins/pods-alternative-cache/ for Siteground users!

**Comment by quasel** [comment]
Going to close the issue caching related stuff is hard to reproduce without the exact setup to test! and more Details!
