### ISSUE TITLE
pods_clean_name performs like pods_js_name

### ISSUE THREAD

**Issue by leepeterson** [pods-framework/pods#4761]
WP 4.9.4
Pods 4.8

Haven’t tested the regex to verify it’s correct, but clean name does in fact do the same thing js name does, but only with spaces. 

It leaves alone existing hyphens, it lowercases uppercase letters, but it replaces spaces with underscores. 

Going to use create slug function instead but wanted to point out this oddity.

**Comment by quasel** [comment]
pods_js_name uses pods_clean_name() with lower option and then  does `$str = str_replace( '-', '_', $str );` don't see an issue with that! 

Sorry for the late reply, feel free to comment if you still have questions!

**Comment by quasel** [comment]
maybe I misunderstood your issue ;) just took a look at the code - seems pretty legit but then - gone through a bunch of issues today :D

**Comment by leepeterson** [comment]
Updated in original description. 

The issue is related to how the docs describe what the function does. 

> Return a lowercase alphanumeric name (with underscores)

Hyphens are left as hyphens, they’re not converted to underscores. 

Maybe that’s all the docs need for it. I can see now how create slug, js name, etc. perform as advertised, and that clean name sorta falls in between. Useful for sure.
