### ISSUE TITLE
[performance] Pods locks simultaneous page load

### ISSUE THREAD

**Issue by chaugi** [pods-framework/pods#4762]
Hi,

I have recently found out that activating Pods plugin forces PHP to work in first in first out mode, regardless of page load time.

For a test purpose I have installed clean latest WP v4.9.4 with default theme activated.
Pods v2.7.1 being installed and activated, none of settings were changed, just activated. No new content/fields added.
I used Insert PHP Code Snippet v1.2.3 plugin for convenience to add some custom PHP to one page, to make it loading for 20 seconds, e.g.
`set_time_limit(0);`
`$starttime = microtime(true);`
`while(microtime(true) - $starttime <= 20) {`
`  sha1(rand());`
`}`
`set_time_limit(30);`
`print "20 second processing finished";`
Then if you open that page, which is loading for 20 seconds and try to simultaneously open other pages of the site which loads much faster, you will notice, that new pages will not be opened unless 20 second pages is loaded.
If you disable Pods, then everything is fine and you can open as many pages as you want while 20 second page is still loading.

While this behaviour does not state Pods plugin is hitting performance it does indirectly slowing down overall site performance in case concurrent page loads occurs.

For example in my case, I serve files via script, not via Apache, because I check permissions in the script. Therefore if someone downloads big file and therefore script is executed, nobody can load any other pages of the site, because PHP is locked and not working simultaneously anymore.

This behaviour does not depend whether Pods is being used on that page, or whether viewed content has any fields added by pods. No. If everything is clean and unconfigured, just Pods plugin activated, then side-effect occurs. So this affects whole site, which is very sad.

I was able to profile using Xdebug my test case and it turned out that when new concurrently loaded page is waiting it is hanging on following line of the code executed by pods plugin:

File: wp-content\plugins\pods\includes\general.php
Function: function pods_session_start() {…}
Code line: 2152
`// Start session`
`@session_start();`
pods_session_start() is executed by \PodsInit->core() method in wp-content\plugins\pods\classes\PodsInit.php line 196.

Any ideas?

**Comment by chaugi** [comment]
Some interesting related articles:
https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/
https://pressjitsu.com/blog/wordpress-sessions-performance/

It looks like for best practice you need to initiating session_start() right before you want to read/write $_SESSION variable, and right after that you need to execute session_write_close() in order to free file lock. Session variable will still be available in read-only mode after executing session_write_close();

Second option is switching sessions usage to database, which will require more refactoring...

I see pods_session_start() being executed in many places, e.g. admin_ajax_* calls, but I don't see any single session_write_close() to free them up.

**Comment by lougreenwood** [comment]
> Second option is switching sessions usage to database, which will require more refactoring...

@chaugi Are you aware of the following plugin? Maybe you could try your test with this plugin enabled to see if it helps?

https://wordpress.org/plugins/wp-native-php-sessions/

**Comment by chaugi** [comment]
@lougreenwood 
Thanks. I was not aware of this plugin. I have tested it in test environment and it seemed to do the trick. New pages are successfully loading while _20 seconds_ one is still loading.

Also adding session_write_close() at the end of \PodsInit->core() method does the trick.

As far as I understood session_start() must be initialised when $_SESSION data is needed, if it is required just for read only then session_write_close() must be initiated right after session_start(). If writing to session is needed to preserved between page loads, then session_write_close() must be executed right after modification of $_SESSION; This will allow to use sessions natively without locking others.

**Comment by jagsileo** [comment]
We use pods in our production site and I see this in New Relic, could this issue be related to what is said above? If yes, would the suggested plugin help? 
<img width="896" alt="screen shot 2018-05-09 at 12 32 37 pm" src="https://user-images.githubusercontent.com/16673020/39827177-311129cc-5385-11e8-86c7-d80d2bafada1.png">

**Comment by chaugi** [comment]
@jagsileo 
Just either try on test environment.
Or you can try my patch/hack to see if it solves your problem:
> Also adding session_write_close() at the end of \PodsInit->core() method does the trick.
Then you can think about more elegant solution.

**Comment by jagsileo** [comment]
Thanks @chaugi I will try both and get back

**Comment by sc0ttkclark** [comment]
We should look into the `session_write_close()` usage

**Comment by lkraav** [comment]
I've been running with `PODS_SESSION_AUTO_START false` for whatever reason, have not noticed anything malfunction?

Maybe time to revisit "why do we even have sessions" https://github.com/pods-framework/pods/issues/2237#issuecomment-234564344 or?

**Comment by lanaphillips** [comment]
Do we have any idea when the fix for this will be implemented? As of 4/19/2021, WP Engine gave me this screenshot showing that PODS takes a significant chunk of time when hitting /wp-admin/admin-ajax.php. Can I help in some way? I've worked on lots of themes, but never a plugin.
![PODS-impact-on-admin-ajax](https://user-images.githubusercontent.com/2228995/115447225-16ee0f80-a1cd-11eb-8a06-52f52d1a9404.jpg)

**Comment by sc0ttkclark** [comment]
Fixed via #5626
