### ISSUE TITLE
"Edit Pods" option disabled and enabled upon clearing pods cache

### ISSUE THREAD

**Issue by Dilip7597** [pods-framework/pods#4763]
I'm using pods for one of my projects, it's been working quite perfectly, but recently (I believe this happened after installing a couple of plugins) when I log in to the system (as admin), the "edit pods" option is disabled by default.

If I use the URL to access the edit pods option by appending "wp-admin/admin.php?page=pods" in URL, then it gives me the error saying "error, you are not allowed to access this page" regardless of me being the admin.

The option comes again if I 1. clear the pods cache 2. deactivate/activate pods plugin.

I'm not sure if it's because of the plugin functionality clashing with other plugin or something wrong with the pods plugin.

**Comment by quasel** [comment]
Sounds like an issue with you setup - closing it 

Sorry for the late reply, feel free to comment if you still have questions!
