### ISSUE TITLE
Restrict pod view by role

### ISSUE THREAD

**Issue by CPapadim** [pods-framework/pods#4767]
Is it possible to restrict users being able to view a pod based on their role?  E.g. if I they try to go to www.mysite.com/mypod/mypod_instance1, they should get a 404 or 403 (for all instances, not per instance) unless they have a specific role.

I haven't been able to find anything like this in settings.

**Comment by jimtrue** [comment]
That is handled with Roles and Capabilities which we support: https://docs.pods.io/advanced-topics/roles-capabilities-in-wordpress/

However, with Display, you can mix content on a page if you make a post type public, as long as the role has read capabilities, they can read any post that isn't flagged private. You have to specifically create custom Capabilities and assign them by roles if you want to restrict content.

**Comment by CPapadim** [comment]
I did look into Roles and Capabilities, and it wasn't clear how to use it.  Now I see, for those running into this issue, by setting the `User Capability` setting under a Pod's `Advanced Options` to `Custom Capability`, you'll then have access control specific to that pod.  

Thanks!

**Comment by CPapadim** [comment]
Hmm is there no way to access control Public types of posts?

I have already made thousands of them and marking them all private is going to be a huge pain.

**Comment by CPapadim** [comment]
Hmm This isn't quite working.  I added the custom permissions and they show up under Roles and Capabilities when I change a role.

So i removed all capabilities from subscribers, but they can still see everything.

**Comment by CPapadim** [comment]
Looks like access control is only working on the backend stuff, so if I try to edit those pods it won't let me, but if I view them, even though I have no read permissions, I still can.

**Comment by jimtrue** [comment]
That is where Roles & Capabilities works, on the back-end. If you want to restrict front-end display (which _you_ are totally in control of), you have to wrap your content output with capability or role based 'wrappers' restricting the content. That's WordPress.

**Comment by CPapadim** [comment]
I still can't get this to work using wordpress.  

If I make my own capabilities, I can use something like:

`current_user_can('my_capability', get_the_ID() )` on a post type's single-post-type.php page to use the capability and gate the content.

However, if I use that same thing with one of the pre-created read_post-type capabilities under Roles & Capabilities in pods, it doesn't work.  That same function above will always return true if the general `read` capability is on, and false if `read` is off, but the specific `read_post-type` doesn't seem to effect it even though that's what I'm passing in to the `current_user_can` function.
