### ISSUE TITLE
Images/files disappearing

### ISSUE THREAD

**Issue by sourcejockey** [pods-framework/pods#4772]
I don't have a lot of info, at least not yet, but it appears the images/files vanish without cause. Please let me know what other information could be pertinent.

**Comment by jimtrue** [comment]
@sourcejockey As noted in our #support Slack Channel, issues like this are often the result of other plugins doing things to the Media Library. Can you verify you're not running any other plugins that might be doing organizational or cleanup work to the Media Library?

**Comment by sourcejockey** [comment]
We have the Media Library Assistant enabled:
https://wordpress.org/plugins/media-library-assistant/

**Comment by sourcejockey** [comment]
The issue is so inconsistent that we can't really tell.

**Comment by jimtrue** [comment]
Then that's really going to be hard for us to troubleshoot either. My suggestion would be setting up a duplicate staging site without that plugin and do a large number of image additions and see if they all make it in. Then duplicate the same setup with that plugin working and that will let you know if that's the conflicting issue.

**Comment by sourcejockey** [comment]
I'll give that a shot & let you know my findings.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
