### ISSUE TITLE
delete() function skips trashcan; deletes everything

### ISSUE THREAD

**Issue by Dilip7597** [pods-framework/pods#4775]
I used [delete()](https://pods.io/docs/code/pods/delete/) function, and did echoed it with dynamic post id, and it deleted all the entries it found.

I'm writing this as comparison with [wp_delete_post](https://developer.wordpress.org/reference/functions/wp_delete_post/), as if I use this function an any item gets deleted, it goes to trashcan, so we have the ability to restore it, however with pods->delete(), it wipes the data clean bypassing the trashcan.

I maybe wrong here, but can you guide me if I'm wrong?

**Comment by sc0ttkclark** [comment]
Currently the `delete()` does not have any trash support. At some point, we should add functionality for trashing posts with the Pods object.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
See: https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L5527

`delete_wp_object` has a third parameter `$force_delete` which bypasses the WP Trash. This is set to true by default, shouldn't that be false to be more in sync with how WP handles deletions by default?
