### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by Cyberdemon87** [pods-framework/pods#4781]
Hello.

I have found a really strange color bug/conflict.

Here’s an example.

With Pods enabled:
https://s7.postimg.org/c35ctuii3/image.png

With Pods disabled:
https://s7.postimg.org/gp1h27bqz/image.png

The screenshots above are from Ultimate Member’s options but I suspect the same issue may be found in similar options from other plugins maybe...
In case you want to see for yourself, you can download the new Ultimate Member on the link below and take a look:

https://ultimatemember.com/wp-content/uploads/2017/11/ultimate-member.zip

It's their new upcoming version which hasn't been posted to the official Wordpress repository yet.

Thank you.

**Comment by Cyberdemon87** [comment]
Same thing happens with other plugins that use similar interface.

Here's some screenshot from the "Post SMTP" plugin:


Here’s its settings with Pods enabled:

https://s9.postimg.org/a2sq7znzj/Screenshot_2018-03-09_19.55.42.png

And this is with Pods disabled:

https://postimg.org/image/5to05tsfv/

**Comment by Cyberdemon87** [comment]
So, do you think this can be fixed in the next version?

**Comment by jimtrue** [comment]
@Cyberdemon87 it's on the 2.7.2 milestone so yes, that would be the next version.

**Comment by pglewis** [comment]
Yeah, it's likely just a CSS tweak or three needed, just a matter of getting through a few other trickier issues ahead of this one in my queue.  

If you have the time to check dev tools / firebug for the CSS rules being applied and find what is different in the two cases it might sped things along but we'll get to it either way.

**Comment by jimtrue** [comment]
Here's some of the research on this one: https://wordpress.org/support/topic/color-bug/#post-10091447

**Comment by jimtrue** [comment]
Specifically in this comment: https://wordpress.org/support/topic/color-conflict-bug-with-pods/#post-10050681
```
/*Tooltip*/
.ui-tooltip.um_tooltip {
    padding: 8px;
    color: #eeeeee;
    background-color: #333;
    position: absolute;
    z-index: 1000000;
    max-width: 300px;
    font-size: 12px;
    border-radius: 5px;
	border: none !important;
	text-shadow: none !important;
}
```
I could not tell how our plugin was overriding what was coming through from the other one. I'm not that good a CSS person, unless we're being too specific with ui-tooltip

**Comment by Cyberdemon87** [comment]
That's nice.

But guys, I think there are css conflicts with other plugins except UM as well. Another example is with Post SMTP plugin that's mentioned on my second post of this thread here.

**Comment by jimtrue** [comment]
I was providing History @Cyberdemon87 We're aware of the SMTP plugin conflict from your notes above. We still have to figure out _how_ the CSS is conflicting and why it's being so specifically odd about it.

**Comment by Cyberdemon87** [comment]
Right, thank you :)

**Comment by pglewis** [comment]
I've verified this on the master branch (2.7.1) using the Post SMTP plugin and following the "Show All Settings" link.  The current 2.x branch no longer shows this issue.
