### ISSUE TITLE
Trouble Displaying Extended 'User' custom fields in front end using Short code and Magic Tags

### ISSUE THREAD

**Issue by smsfdesign** [pods-framework/pods#4799]
## Issue Overview

I am having difficulty displaying extended 'User' custom fields in front end of website (i.e. on a page or post) using short code and/or pods magic tags.

I have tried various methods, short code, magic tags and finally building a pods template which includes magic tags and I'm not able to successfully display on front end when inserting pods short code for the pods template.

## Expected Behavior

I simply want to be able to display User meta data on front end using short code and/or magic tags.  Example:  I have a extended the 'User' by adding a number of custom fields.  

I want to be able to display these custom fields on the front end.  EXAMPLE:  custom field that is a "total revenue field".  I want to be able to include this in a GravityView report by entering short-code or magic tag references the current logged-in users custom field that is "total revenue".

I was unsure how to best use the 'Where' clause to select current logged-in user.

## Current Behavior

Unable to successfully display current logged-in user extended custom field on front end.

I am getting some kind of result, because the short code I have used does display a result.  I'm unable to determine where this result is coming from as it appears to be a text label and not custom field content.  I also can't find where this text label is coming from.

The only code example that seems to be returning a value...although not correct and not what I'm after.  It's important to note that the same return value is showing up for all the magic tags inserted in the pods template and then referenced by short code on page.

**[pods name=“user” slug=“user”]{@pods_smsf_revenue}[/pods]     NOTE THIS IS RETURNING A TYPE OF POD FIELD NAME OR LABEL, BUT NOT VALUE?

In the front end the following value is returned:  {smsf_strategiess_smsf_revenue}

I am unsure where this value is coming from...spelling mistake and all?**

Screenshot of magic tags used in pods template:
![pods template using magic tags](https://user-images.githubusercontent.com/37314724/37315741-4c9a0112-26af-11e8-9356-9dc2701c4733.png)

Screenshot of short code used in front end page:
![short code used on front end page](https://user-images.githubusercontent.com/37314724/37315696-154f769c-26af-11e8-9903-e34a1e542a99.png)

Screenshot of front end results page with template short code used below:
![pods template result on front end page](https://user-images.githubusercontent.com/37314724/37315601-96c052ba-26ae-11e8-91f6-8647a37b8f02.png)

## Possible Solution

In relation to extended fields for User using pods.

Once I created these, I have used the Gravity Forms User Registration add-on to create a form that allows me to have users write data to these custom user fields.  This seems to be working.

I can also update this data using the same form or another form dedicated to updating the user custom field data.

When using gravity forms I can also pre-fill this data in the gravity form using gravity forms merge tag such as...{user: pods_smsf_revenue} and this seems to work OK.

![gravity view prefill using gravity forms merge tag custom field](https://user-images.githubusercontent.com/37314724/37316543-da4b88ec-26b3-11e8-8b59-d708ac3f128c.png)

I am then hoping to report upon this data using GravityView.

I do have WooCommerce installed and I found the following that sounded like it might have some similarities to my problem, not 100% sure on that.   https://github.com/pods-framework/pods/issues/1273

** UPDATE 1 **

As an attempt to work around this issue I realised that I am not only using Gravity Forms but also the GravityWiz GravityPerks plugin which extends Gravity Forms functionality.  One extension allows users to use Gravityforms merge tags (the same merge tags used to pre-populate gravity forms with user data, including from custom fields created by pods) in standard pages and posts.  It's common use purpose is to customise a redirect page on submission of form.  However, I've discovered that if I use the standard wordpress text editor and a user is logged-in that the Gravityforms merge tags (with the gravityperks add-on activated) will display extended user custom fields created with pods on the page or post.  This is essentially what I needed without writing code.

Only problem now is that the same gravity forms merge tag is not working inside a html content block while using Elementor visual page builder.  (I have contacted both GravityWiz and Elementor about this).

Reference Links:

Gravity Forms Merge Tags:  https://docs.gravityforms.com/merge-tags/

GravityWiz GravityPerks plugin to extend merge tags functionality: 
 http://gravitywiz.com/documentation/gravity-forms-post-content-merge-tags/

** UPDATE 2 - have sorted a work around, but would still like to be able to use pods features to access pods custom fields**

I have sorted out my issue of not being able to get the pods custom user meta data out to the front end by using wpDatables plugin to produce a table based on the Wordpress Database wp_usermeta to find the custom user pod fields via mysql query and produce a table of user meta data based logged-in user data only.

This work around has replaced the gravity forms and gravity view solution mentioned in update 1 above.

Refer: https://wpdatatables.com

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
Debug Information
WordPress Version: 4.9.4

PHP Version: 7.0.28

MySQL Version: 5.5.5

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: vvqtd_

WP Multisite Mode: Yes

WP Memory Limit: 512M

Pods Network-Wide Activated: No

Pods Install Location: /home/thestrat/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: GeneratePress Child

Currently Active Plugins:

ActiveMember360: 2.1.2
Ajax Search Lite: 4.7.13
Bulk Actions Pro for Gravity Forms: 1.2.11
Code Snippets: 2.10.1.1
Duplicate Post: 3.2.1
Easy Passthrough for Gravity Forms: 1.2.4
Elementor: 1.9.7
Elementor Pro: 1.15.3
Envato Market: 1.0.0-RC2
Essential Addons for Elementor: 2.4.2
FooEvents for WooCommerce: 1.5.15
FooEvents PDF Tickets: 1.2.7
GFChart: 1.10.0
GFChart Charting vs Time Add-On: 0.2
GFChart GravityView Add-On: 0.2
GP Live Preview: 1.2.9
GP Multi-page Navigation: 1.0.2
GP Premium: 1.5.6
GP Preview Submission: 1.2.8
GP Terms of Service: 1.3.9
GP Unique ID: 1.3.12
Gravity Forms: 2.2.5
Gravity Forms ActiveCampaign Add-On: 1.4
Gravity Forms integration for wpDataTables: 1.0.1
Gravity Forms Partial Entries: 1.0
Gravity Forms Polls Add-On: 3.1
Gravity Forms Quiz Add-On: 3.1
Gravity Forms Send to Third-Party API: 1.5.0
Gravity Forms Stripe Add-On: 2.4
Gravity Forms Survey Add-On: 3.2
Gravity Forms User Registration Add-On: 3.9
Gravity Forms Utility: 2.3.0
Gravity Forms Zapier Add-on: 2.1
Gravity PDF: 4.3.2
Gravity Perks: 2.0.3
GravityView: 1.22.5
GravityView - Advanced Filter Extension: 1.0.20
GravityView - DataTables Extension: 2.1.1
GravityView - Featured Entries Extension: 1.1.3
GravityView - Gravity Forms Import Entries: 1.3.2
KB - Elegant Layouts: 1.3.3
Knowledge Base for Documents and FAQs: 3.3.0
Live Population for Gravity Forms: 1.3.11
Math by GravityView: 1.0.3
Pods - Custom Content Types and Fields: 2.7.1
Pods Gravity Forms Add-On: 1.3
Post Type Switcher: 3.1.0
SSL Insecure Content Fixer: 2.5.0
The Events Calendar: 4.6.11.1
Thrive Architect: 2.0.22
Thrive Leads: 2.0.24
UpdraftPlus - Backup/Restore: 2.13.5.21
Wistia WordPress Plugin: 0.8
WooCommerce: 3.3.3
WooCommerce eWAY Payment Gateway: 3.1.14
WooCommerce Order Status Control: 1.9.0
WooCommerce PDF Invoices: 2.9.12
WooCommerce PDF Invoices Premium: 1.6.3
WooCommerce Product Dependencies: 1.2.1
WooCommerce Stripe Gateway: 4.0.7
WooCommerce Subscriptions: 2.2.18
Wordfence Security: 7.1.0
WordPress Importer: 0.6.4
wpDataTables: 2.1
WP RSS Aggregator: 4.11.2

**Comment by jimtrue** [comment]
@smsfdesign Not sure how we missed this one when it came in, but this is actually a Support question and should be routed through [the Support Forums](https://pods.io/forums/) or through our Slack Chat at https://pods.io/chat/

Since you've been waiting so long for a response on this one, I'll go ahead and reply here, though.

You've got a couple of things incorrect, primarily your shortcode to call your Pods Template. 

If you're wanting to only show the Logged In User's information, that means you have to have Special Magic Tags enabled using the settings in the [Special Magic Tags documentation](https://pods.io/docs/build/special-magic-tags/). Specifically, the change to the wp-config.php:

> Important: In many cases, such as inside a shortcode, or in the Pods widget settings, you must add the following `define('PODS_SHORTCODE_ALLOW_EVALUATE_TAGS',true);` to your wp_config.php for these tags to be used.

Next, your shortcode is configured incorrectly. You're listing both a `slug="8014"` and a where clause. You have to use one or the other, not both. Your where clause is also incorrectly formatted, you have:
```
field="{@pods_smsf_revenue} where = user = {@user.ID}"
```

That's not going to work because you've got a run-on sentence going between the field and where in the same clause. Field should be `field="pods_smsf_revenue"` if you only want to show the value of that field. You don't use magic tags in the field parameter.

Your `where` parameter needs to be configured like `where="ID = {@user.ID}"` There isn't a 'user' field in the User WP Object, so 'user =` wouldn't match with anything.

After you make those changes, we should be able to help you with the rest once you see what the results are of making the changes above. But please route them to the correct area for Support as noted above.
