### ISSUE TITLE
Component: WPMS Network-wide Mode (store one set of Pod fields, helpers, pages, templates, types; but individual sets of item data)

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#48]

**Comment by jaboi** [comment]
Help! I need this across a network for Advanced Content Types. I imported the same fields to the second site on the network, and I can't access the data via pods functions. When I imported the fields, they were placed in the database as wp_2_pods_fieldname -- is there a workaround?

@sc0ttkclark - you said above that something like this might be possible for ACTs. Still true? Any ideas?

**Comment by Shelob9** [comment]
@jaboi There is no current way to do this in place and we are a fair way from where the refactoring that Scott wants to do to make this possible can be done.

A work around would be to use the Pods JSON API to pull Pods configuration and content between site. I'd absolutely love for us to make that plugin, and would love to work on it, but it's not something we have the bandwidth to work on right now without it having its own funding.
