### ISSUE TITLE
HTTPS not fully available on Custom Settings pages.

### ISSUE THREAD

**Issue by OWMC** [pods-framework/pods#4801]
## Issue Overview
Https does not fully work on a custom settings page.

## Expected Behavior
We should get the green bar in the browser url on all fully secured pages served via https.

## Current Behavior
We don't. 
![screen shot 2018-03-13 at 17 42 16](https://user-images.githubusercontent.com/5149760/37359654-18352a28-26e6-11e8-806d-cf077f8abe1b.png)

## Possible Solution
I identified these resources in the source that were referencing http and not https
![screen shot 2018-03-13 at 17 44 47](https://user-images.githubusercontent.com/5149760/37359768-5b9ad786-26e6-11e8-93bb-99f89bbf488b.png)
![screen shot 2018-03-13 at 17 44 38](https://user-images.githubusercontent.com/5149760/37359769-5bbdaec8-26e6-11e8-9be2-8f104e5f0684.png)

## Steps to Reproduce (for bugs)
1. Create a custom setting page.

## Todos
- [ ] Create PR changing all dashicons usage to https

**Comment by jimtrue** [comment]
@JoryHogeveen @pglewis I believe this would be solved across the board by changing our dashicons reference to https:// throughout, correct?

**Comment by pglewis** [comment]
I believe this is coming from WordPress: 

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/template.php#L2166-L2186
