### ISSUE TITLE
Pods Framework and Divi Builder hamburger menu issue...

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#4804]
## Issue Overview
With Pods enabled, the Divi Builder hamburger menu is being cut off..

## Steps to Reproduce (for bugs)
Please see short screencast here:
https://youtu.be/_qVGFyKIVqw

## WordPress Environment
<details>
WordPress Version: 4.9.4

PHP Version: 7.1.15

MySQL Version: 10.1.24

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

Session Save Path: /opt/alt/php71/var/lib/php/session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/sonformi/dev.sonfor.mitspace.dk/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Divi

Currently Active Plugins:

MainWP Child: 3.4.6
Pods - Custom Content Types and Fields: 2.7.1
Really Simple SSL: 2.5.26
Wordfence Security: 7.1.0
</details>

**Comment by jimtrue** [comment]
@oldrup Since the only way we'll be able to troubleshoot this is with a Divi license (which we don't have and don't have access to), can you do some troubleshooting on your end and 'inspect' the CSS involved around the 'hamburger' menu? It would help us see what the conflict may be coming from. Even better if you can cut and paste it in here. Thanks!

**Comment by oldrup** [comment]
I'd be happy to help. Been inspecting (and reproducing) this in both Chrome and IE. But I'm in doubt what to look for, as the inspect tool, in my hand, only shows the CSS for the selected item.

I have a test domain with a WordPress multisite installation and divi. Would it be an idea see if I can reproduce the issue there and provide you with a login?

**Comment by oldrup** [comment]
Hm. Quickly create a different site with Divi and Pods, and no issue there... Don't spend more time on this @jimtrue - closing this issue for now...

**Comment by jimtrue** [comment]
Thanks for checking @oldrup looking at your video, you were dealing with a absolute position and z-index issue.
