### ISSUE TITLE
Self-related pods create duplicates on the back-end (I think)

### ISSUE THREAD

**Issue by gregersen12** [pods-framework/pods#4805]
## Issue Overview
I have a custom post type created by pods, that have a self-related field for linking related items (that our moderators fill out manually). 
However, above a certain threshhold, (seems to be 3 or 4), the current item also becomes added to the related, although something can't be related something to itself.
It's not possible to remove the self-related item from the list.

Displaying itself as related:
![displaying itself as related](https://user-images.githubusercontent.com/9022499/37521344-ae5df214-2920-11e8-975d-bff5b2ccdc57.png)

In the backend:
![skaermbillede 2018-03-16 kl 13 49 41](https://user-images.githubusercontent.com/9022499/37521391-d898f51a-2920-11e8-99f3-d19bd999cf56.png)

Pods configuration:
![skaermbillede 2018-03-16 kl 13 50 41](https://user-images.githubusercontent.com/9022499/37521436-0a1e189a-2921-11e8-84c8-c20f07b42622.png)

![skaermbillede 2018-03-16 kl 13 50 56](https://user-images.githubusercontent.com/9022499/37521441-0d3caa5a-2921-11e8-8d0f-75b83e77989d.png)

![skaermbillede 2018-03-16 kl 13 51 02](https://user-images.githubusercontent.com/9022499/37521444-0f486c76-2921-11e8-9b64-6110ec4c4ec5.png)

![skaermbillede 2018-03-16 kl 13 51 07](https://user-images.githubusercontent.com/9022499/37521449-12039148-2921-11e8-9f5b-4b06f109339c.png)

Here's the small code used to display the related: 
```
<?php

$ord     = pods( $post->post_type, $post->ID );
$related = $ord->field('related');

if ( !empty($related)) {
  foreach($related as $rel ) {
    $id = $rel['ID'];

    $all_html .= '<a href="'.get_the_permalink($id).'"><div class="">'.get_the_title($id).'</div></a>';
  }
}

echo $all_html;

?>
```
However it's just for display and probably doesn't have a big impact on the behaviour.

## Expected Behavior
It should not add itself, as related to itself. 
It should add itself to other posts, that add it as a related. So X adding Y means Y also adds X. Thats fine. But X should never add X.

## Current Behavior
X adds X :) 

## Possible Solution
I am not sure, but I'm guessing there is something up with the logic behind it I'm not quite understanding

## Steps to Reproduce (for bugs)
Here's a link to the issue: 
https://dinero.dk/ordbog/betalingsevne/

1. Create pod with same configuration
2. Add some fillers to DB
3. Add 3-4-5 related to X
4. See if X also shows up on X.

## WordPress Environment
<details>
```
WordPress Version: 4.9.4

PHP Version: 7.0.25-0ubuntu0.16.04.1

MySQL Version: 5.7.21

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: f10_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/dinerodk/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Dinero 2

Currently Active Plugins:

Accordion Shortcodes: 2.3.3
Add Categories to Pages.: 1.0
Akismet Anti-Spam: 4.0.3
Better Notifications for WordPress: 1.6.12
BNFW - Send to Any Email Add-on: 1.0.0
Calculated Fields Form: 5.0.23
Category Order and Taxonomy Terms Order: 1.5.3.2
Coming Soon Page & Maintenance Mode by SeedProd: 5.0.17
Custom Facebook Feed: 2.4.6
Dinero App Zopim Overlay: 1.0
Dinero Pro Articles: 1.0
Disable Emojis: 1.7
Enhanced Media Library: 2.5
Integration Rating:
iThemes Security Pro: 4.8.3
Kraken Image Optimizer: 2.6.2
Media Cleaner: 4.5.7
No Category Base (WPML): 1.3
Pods - Custom Content Types and Fields: 2.7.1
Regenerate Thumbnails: 3.0.2
Schema App Structured Data: 1.9.9
Shortcodes to show or hide content: 2.5
Title and Nofollow For Links: 1.02
User Roles and Capabilities: 1.2.1
Was this Helpful?: 1.2.2
WP Engine Content Performance: 1.5.0+585.911ce2b
WP Mail SMTP: 1.2.5
Yoast SEO Premium: 6.3
```
</details>

**Comment by sc0ttkclark** [comment]
Interesting find, definitely an edge case. We'll take a look at this as soon as we are able to. Excellent bug report!

**Comment by gregersen12** [comment]
Thank you Scott. Let me know if I can be of further assistance.

**Comment by sc0ttkclark** [comment]
I bet we used to not list current item in the lists when it’s a bidirectional relationship field @pglewis, if not then we probably should in this case.

**Comment by gregersen12** [comment]
Is there any update on this issue? I will gladly assist fixing this, if I can be of more assistance

**Comment by gregersen12** [comment]
Has there been any efforts to replicate this issue? 
I'll gladly assist if that helps smoothen things along.
