### ISSUE TITLE
Latency is autocomplete field to respond with suggested terms in PODS form 

### ISSUE THREAD

**Issue by investreads** [pods-framework/pods#4808]
## Issue Overview
Slow autocomplete. I'm pulling from a custom flat taxonomy. My term list is only 200 or so. I don't think the amount of terms is causing the latency.
## Expected Behavior
Quicker at showing possible terms

## Current Behavior
It lags a good 3-5 seconds in pulling suggested terms after the first digit is entered.

## Possible Solution
Not really a solution but rather better responsiveness is Gravity Forms use of TagIt in a Gravity Wiz plugin. It is super fast and reading the given taxonomy

I don't have to necessarily read from a taxonomy for this, if there is a different table format to store my term list. If that makes it faster, great.

## Steps to Reproduce (for bugs)

1. Create taxonomy
2. Create custom post and relationship field to taxonomy
3. Make field autocomplete multiple selections
4. Add PODS form to page using Beaver Builder
5. Use form. Lag is seen.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by investreads** [comment]
Note there are a bunch of reasons why I'm trying to exclusively use PODS in llieu of GF (in case you were wondering).

**Comment by investreads** [comment]
Sorry- one more thing. I think there's a pretty good chance the reason PODS is slower than GF is you don't just return results based on matching characters from the start. 

Example: if I typed "Li" and there weren't any words that started with "Li", you would look elsewhere in the terms, such as f"li"p. But I actually don't need this. Just searching for words that start with the characters is good enough. So if this is a situation where the SQL query is slowing it down, maybe you can let me know if a more simple SQL query is possible? thanks

**Comment by jimtrue** [comment]
Can you please provide the items for the Debug Information and an export of your Pods Configuration and also an example of the form you're having an issue with? Recreating all your steps takes time and you may have noticed we're a small team, so providing the additional exports and code to recreate your issue makes it easier and quicker for us to get to the problem you're experiencing.

**Comment by investreads** [comment]
Sure-happy to. Thanks in advance.

**Super simple Form example**
http://lifeflow.io/form/

**Debug Information**
WordPress Version: 4.9.4
PHP Version: 7.0.25-0ubuntu0.16.04.1
MySQL Version: 5.7.21
Server Software: Apache
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Session Save Path: /var/lib/php/sessions
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:
Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:
APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 40M
Pods Network-Wide Activated: No
Pods Install Location: /nas/content/live/danlifeflow/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: Beautiful Pro Theme
Currently Active Plugins:
Beaver Builder Plugin (Standard Version): 2.0.6.3
BuddyPress: 2.9.3
Bulk Actions Pro for Gravity Forms: 1.2.11
BulkPress: 0.3.5
Code Snippets: 2.10.1.1
Custom HTML/PHP Post Templates: 2.0.0
Custom Post Type UI: 1.5.7
Genesis Design Palette Pro: 1.3.22
Genesis Footer Builder: 1.3.2
Genesis login modal box: 1.2.3
Genesis Simple Hooks: 2.2.1
Genesis Simple Menus: 1.0.0
GP Live Preview: 1.2.10
GP Nested Forms: 1.0-beta-4.20
GP Post Content Merge Tags: 1.1.1
Gravity Forms: 2.2.6.1
Gravity Forms + Custom Post Types: 3.1.13
Gravity Forms Advanced Post Creation Add-On: 1.0-beta-1
Gravity Forms Bulk Add Fields: 1.0.2
Gravity Forms Collapsible Sections: 1.0.9
Gravity Forms Image Choices: 1.1.11
Gravity Forms Sticky List: 1.5.1
Gravity Forms Styles Pro: 2.3.4
Gravity Perks: 2.0.3
Imagify: 1.7
Live Population for Gravity Forms: 1.3.11
Nav Menu Roles: 1.9.1
Photo Gallery: 1.4.0
Plugin Organizer: 9.3.6
Pods - Custom Content Types and Fields: 2.7.1
Pods Gravity Forms Add-On: 1.3
Remove Widget Titles: 1.0
Search & Filter: 1.2.9
Simple Custom CSS and JS PRO: 4.3
Slim Image Cropper for Gravity Forms: 1.4.4
Sticky Menu (or Anything!) on Scroll: 2.1.1
SVG Support: 2.3.11
Toolset CRED: 1.9.5
Toolset Types: 2.3-b5
Toolset Views: 2.5.2
Ultimate Member: 1.3.88
WordPress Media Library Folders: 4.1.5
WordPress Media Library Folders Reset: 4.1.5
WordPress Tooltips Ultimate: 2.9
WP Responsive Menu: 3.0.3

**PODS Configation- Kept it simple. Two fields. Tag taxonomy is TermWPDefaults and called "big_list_of_words as a custom field**

{"meta":{"version":"2.7.1","build":1521816030},"pods":{"464":{"id":464,"name":"termwpdefault","label":"TermWPDefaults","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"TermWPDefault","public":"1","show_ui":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"termwpdefault","query_var":"1","sort":"0","built_in_post_types_bp-email":"0","built_in_post_types_bwg_album":"0","built_in_post_types_bwg_gallery":"0","built_in_post_types_bwg_tag":"0","built_in_post_types_cred-form":"0","built_in_post_types_cred-user-form":"0","built_in_post_types_custom-css-js":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_fl-builder-template":"0","built_in_post_types_gplp":"0","built_in_post_types_mgmlp_media_folder":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_path":"0","built_in_post_types_pet":"0","built_in_post_types_plugin_filter":"0","built_in_post_types_plugin_group":"0","built_in_post_types_post":"0","built_in_post_types_tooltip_selectors":"0","built_in_post_types_um_directory":"0","built_in_post_types_um_form":"0","built_in_post_types_um_role":"0","built_in_post_types_view":"0","built_in_post_types_view-template":"0","built_in_post_types_word_output":"1","built_in_post_types_wp-types-group":"0","built_in_post_types_wp-types-term-group":"0","built_in_post_types_wp-types-user-group":"0","built_in_post_types_wpcmtt_hotspots":"0","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0"},"455":{"id":455,"name":"word_output","label":"Word Outputs","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"path_name":{"id":456,"name":"path_name","label":"Path Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"1","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":"Path Name","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0"},"big_list_of_words":{"id":457,"name":"big_list_of_words","label":"Big List of Words","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"taxonomy","pick_val":"termwpdefault","sister_id":"","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_allow_add_new":"0","pick_taggable":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","default_value_parameter":"Words","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Word Output","public":"1","show_ui":"1","supports_title":"0","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"word_output","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"publish","supports_author":"1","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"1","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"1","supports_page_attributes":"1","supports_post_formats":"1","supports_genesis_seo":"0","supports_genesis_layouts":"0","supports_genesis_simple_sidebars":"0","built_in_taxonomies_bp-email-type":"0","built_in_taxonomies_bp_member_type":"0","built_in_taxonomies_bwg_tag":"0","built_in_taxonomies_category":"0","built_in_taxonomies_filter_group":"0","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_keywords":"0","built_in_taxonomies_life_event_pod":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_path_types":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_tooltip_selector_style":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_single":"Template test 1","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_termwpdefault":"1"}},"templates":{"Template test 1":{"id":224,"name":"Template test 1","code":"{@path_name}\r\n{@big_list_of_words}","type":"template","slug":"template-test-1","options":{"_edit_lock":"1521809722:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","_um_custom_access_settings":"0","_um_accessible":"0","_um_access_redirect2":"","_um_access_roles":"a:1:{i:0;s:1:\"0\";}","_um_access_redirect":"","pod_reference":"a:1:{s:3:\"pod\";s:11:\"word_output\";}"}}}}

**Comment by investreads** [comment]
I'm going to go ahead and close this issue because I think the root cause is that it is a SQL search and some latency comes with the territory. I've got some possibly faster ways using jQuery. Still worth exploring. If WP actually used the term_group SQL column, you probably could speed things up that way. Probably could through custom PODS taxonomies as well, as I think the default QL query PODS uses starts a bit broader. Thanks for your time!
