### ISSUE TITLE
Add filter for frontend form HTML classes

### ISSUE THREAD

**Issue by paddelboot** [pods-framework/pods#4813]
## Issue Overview
Limited possibilities for frontend form styling.

## Expected Behavior
Would like to display certain form elements horizontally, using columns (i.e. first and last name, ZIP and city, etc.). By adding a user defined class to the **li.pods-field** - Elements within the form, the styling would be much more within the end user's control. 

## Current Behavior
Can only display form fields vertically. 

## Possible Solution
pods/ui/front/view.php:

`<li class="pods-field <?php echo apply_filters( 'pods_field_class', $field ); ?> [...] >`

**Comment by davidatwhiletrue** [comment]
To do something similar I'm 'overriding' the `pods/ui/front/form.php` creating a copy of the file in my theme and changing it to restyle the form.
To tell pods that I want to use my `form.php` file I do:
```
function icc_pods_view_alt_view($view)
{
    if($view===(PODS_DIR . "ui/front/form.php"))
        return "/pods/ui/front/form.php";

    return $view;
}


add_filter('pods_view_inc', 'icc_pods_view_alt_view', 10, 1);
```
I locate the copy of the file in `themes/my_theme/pods/ui/front/form.php`.

May be you can do something similar with `view.php `.

**Comment by paddelboot** [comment]
@davidatwhiletrue I am using this method with another plugin where the original devs did not include too many filter options for their values, ie. apply_filters(), before returning them.

The downside to this approach is that you end up with an outdated version of form.php over time. You would have to manually update it everytime the core file is updated. Since I am working on a client project, this is not really an option.

**Comment by jimtrue** [comment]
@davidatwhiletrue Yep, the approved method is to submit a PR using the processes in https://github.com/pods-framework/pods/blob/2.x/CONTRIBUTING.md to get your filters incorporated.

**Comment by paddelboot** [comment]
https://github.com/pods-framework/pods/pull/4816
