### ISSUE TITLE
Retrieving the date in localized format

### ISSUE THREAD

**Issue by dohukk** [pods-framework/pods#4814]
I have **Custom Post Type** with **Date Field Type**. **Date Format Type** in **Additional Field Options** set as **WordPress Default**

![01_setting](https://user-images.githubusercontent.com/37911414/38105905-aea9c8c0-338d-11e8-8f31-2841c146026e.jpg)

And this Custom Post Type return date correct but month not translated.

![02_output_pods_item](https://user-images.githubusercontent.com/37911414/38105937-c67fdf2a-338d-11e8-99a6-64584fd71532.jpg)

As for example in WordPress Post. 

![03_example_post](https://user-images.githubusercontent.com/37911414/38105963-dc51dccc-338d-11e8-93c5-1c2304a4a236.jpg)

Why?

**Comment by jimtrue** [comment]
@JoryHogeveen @pglewis `date_il8n()` issue perhaps? https://developer.wordpress.org/reference/functions/date_i18n/

**Comment by dohukk** [comment]
I don't think so, because WP and other plugins display date is correct in localized format.

**Comment by jimtrue** [comment]
@dohukk This was a comment to our internal team, since we're the one handling that display.

**Comment by quasel** [comment]
same corner as #5038
