### ISSUE TITLE
WP 4.9.5 breaks links with .permalink in shortcode

### ISSUE THREAD

**Issue by danmaby** [pods-framework/pods#4825]
## Issue Overview
Following an upgrade to WP 4.9.5 all links throughout the site that used `.permalink` within the shortcode broke. Example: `[pods field='custom_url.permalink']` 

## Expected Behavior
Shortcode to output URL

## Current Behavior
Shortcode outputs as plain text

## Possible Solution
Not a solution but short term workaround has been to downgrade WP core to 4.9.4 on the site.  Links working as expected after downgrade.  

## Steps to Reproduce (for bugs)
Upgrade to WP 4.9.5.  Insert shortcode with `.permalink` 

## WordPress Environment
4.9.5 was installed when the issue presented.  Below is after the site was restored, hence the 4.9.4
```
WordPress Version: 4.9.4

PHP Version: 7.2.4

MySQL Version: 5.6.36

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: pm5_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/wpldn776/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No
```
</details>

**Comment by danmaby** [comment]
To add; fields are single-select relationships.

**Comment by jimtrue** [comment]
@danmaby Can you provide us with a Pods Components, Migrate: Packages, Enable, Export? It would help to get your structure and some context (ie, Where are you using these shortcodes? ) Especially since it's outputting or not processing the shortcode when you upgraded, it might not be totally our plugin that is the issue here, too. Do you have a staging version of this website that you can test on or can you copy it down local for testing?

**Comment by jimtrue** [comment]
@danmaby I was able to test this locally and I'm not seeing the issue you're seeing, so we do need more information from you, specifically the context of these shortcodes and where you have them placed, if you have them nested in other shortcodes, text widgets, etc.

I know you have WordCamp London next weekend, so it's fine if you can't get back to us until afterwards. Kicking off a Staging site or a copy of that site locally and testing for plugin conflicts, etc. would be a good additional troubleshooting step.

**Comment by danmaby** [comment]
Hey @jimtrue, I'll spin up a copy of the site to replicate the issue and provide the additional context and data. Unfortunately it won't be today. For now though; the shortcodes are placed on pages within the text editor & html modules of the beaver builder plugin. The output was being returned unprocessed i.e. the page displayed `[pods field='custom_url.permalink']`.  As soon as I can share more detail I will.

**Comment by danmaby** [comment]
Hey @jimtrue we've been able to test further and the issue was being caused by another plugin!  The Amazon Polly plugin at [version 1.0.2](https://wordpress.org/plugins/amazon-polly/#developers) was causing the same issue across three further staging sites of ours.  With each if we ran WP 4.9.5, Pods 2.7.1 with Polly 1.0.2 the Pods shortcodes would break, downgrading to WP 4.9.4 masked the issue with Polly. 

Polly is now at 1.0.9 and runs well with Pods & WP on 4.9.5

**Comment by jimtrue** [comment]
Thanks for the update ;) I had a feeling it wasn't Pods because if pods was processing the shortcode it would actually have displayed something. Since it was kicking out the shortcode in full, something wasn't allowing it to process the shortcode at all. Glad you figured it out ;)
