### ISSUE TITLE
Pods Admin Page Provides "No Access" Error when No Pods Exists

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4842]
## Issue Overview
This is a workflow type issue. If you delete all of your Pods, you no longer actually have a 'manage' Pods screen. After deleting your Pods and clicking on Pods Admin (the main menu for Pods), you will receive the error 'You do not have access to this page' because it's attempting to go to:
/wp-admin/admin.php?page=pods
(and there are no 'pods' to edit)

and it should be attempting to go to:
/wp-admin/admin.php?page=pods-add-new

## Expected Behavior
Clicking on Pods Admin when no Pods exist (or after deleting them) should go to `pods-add-new` not `pods` or maybe `pods` should just handle the redirect itself.

## Current Behavior
Clicking on Pods Admin when no Pods exist after deleting Pods routes to /wp-admin/admin.php?page=pods

## Possible Solution
Page=pods should handle the redirection or check for existence of any pods and send to pods-add-new.

## Steps to Reproduce (for bugs)
1. Create a Pod with Add New, and then go to Edit Pods (/wp-admin/admin.php?page=pods)
2. Delete it (and select Ok) (Confirmation of Pod Deleted Successfully and 'No Pods Found'.
3. Click on Pods Admin Menu (/wp-admin/admin.php?page=pods)
4. "Sorry, you are not allowed to access this page"

Yes, I realize I can click on Add New or the button for Add New and it works properly, but this is a UX issue.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by vitmarks** [comment]
Oktober 2020 -> still have the issue. After create new CPT I could see "edit pods" menu again

**Comment by JoryHogeveen** [comment]
@vitmarks  PR #5853 fixes this.
