### ISSUE TITLE
Elementor integration similar to the existing Pods Beaver Themer Add-on

### ISSUE THREAD

**Issue by HQRaja** [pods-framework/pods#4844]
Now that Elementor 2.0 is out with theme building support for creating archive pages and single post/CPT pages, they have announced plans to integrate ACF as well as Toolset to support content types and fields created by them. Unfortunately, Pods hasn't been officially announced for their current roadmap.

There's a lot of community interest in such integration, with the announcement post for Elementor 2.0 alone gathering 8+ comments requesting for it, and several others chiming in about it on multiple community forums and groups.

I created an [official request for the integration on the Elementor GitHub](https://github.com/pojome/elementor/issues/4129) where it's been getting a lot of traction, with many stating this is the only feature keeping them from switching to the combination of Elementor + Pods.

I'd like to hear the take of the Pods community on it, and request potential collaboration with the Elementor team to work on the integration in form of an add-on similar to that available for Beaver Themer. Also, Adam Preiser of WPCrafter (@reachadam) has offered to finance the development of such integration.

**Comment by quasel** [comment]
I‘ll take a look after my return from India - no promise from my side an if i‘ll Make one it might not be officaly supported because the Beaver Builder Integration already put a bit of on the support ...

**Comment by HQRaja** [comment]
Thank you! And I completely understand. It can be community-supported perhaps, in that case.

**Comment by quasel** [comment]
The Elementor them decided to this on their own - the basics work just fine!
