### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by naugustijr** [pods-framework/pods#4852]
## Issue Overview
An error displayed in the google chrome console seems to be the cause of some strange behavior when I filter information on the page.
Whenever I click the Submit button the error appears in the console and the behavior of the page does not match what I expect, which is to display the filtered results on the page. A lot of the time nothing happens.

## Expected Behavior
Fill out the form, click submit (PESQUISAR/SEARCH), and see the results appear on the page.

## Current Behavior
I filled out the form and clicked Submit. Nothing happened.

## Steps to Reproduce (for bugs)
1. Go to page http://parisnaamerica.org/search/
2. Click on PEQUISAR/SEARCH
3. Open console on Google Chrome
4. See the error 

Sometimes this error has no negative effect.
Other times it freezes the page. Nothing happens!

## Pods Package Export 
attached

## Related Issues and/or PRs
https://github.com/CalderaWP/Caldera-Forms/issues/2448

## WordPress Environment
Informação de Debug
WordPress Version: 4.9.5
PHP Version: 5.6.35
MySQL Version: 5.6.36
Server Software: Apache
Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by naugustijr** [comment]
[Pods.txt](https://github.com/pods-framework/pods/files/1929235/Pods.txt)

**Comment by naugustijr** [comment]
Erro on Firefox:
TypeError: b.jqxhr.responseJSON is undefined[Learn More]
ajax-core.min.js:1:2228
error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/ajax-core.min.js:1:2228
request_error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:1692
c
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:2048
error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:9877
i
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:27444
fireWith
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:28213
y
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:4:22744
abort
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:4:20559
request
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:1372
c
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:2048
a.fn.baldrick/</<
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:10191
dispatch
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:12392
add/r.handle
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:9156
trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:11571
a.event.trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery-migrate.min.js:2:8273
trigger/<
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:18983
each
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:2879
each
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:844
trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:18962
init_search<
http://parisnaamerica.org/search/:461:8

**Comment by naugustijr** [comment]
https://github.com/CalderaWP/Caldera-Forms/issues/1157

**Comment by jimtrue** [comment]
From your other bug report, you indicated when you disabled Caldera Easy Pods the problem disappeared. Do you still have the issue with just Pods and Caldera Forms?

**Comment by naugustijr** [comment]
The entire site is using Caldera easy pods.
The error disappears as well as all the functionality.

**Comment by jimtrue** [comment]
The problem is that we don't have anything to do with the coding of Easy Pods. If @shelob9 needs to for assistance on fixing the bug you reported over there, we'll assist, but this isn't an issue with our product.

**Comment by naugustijr** [comment]
Thanks!
