### ISSUE TITLE
Pods Settings WYSIWYG Float Issue

### ISSUE THREAD

**Issue by leepeterson** [pods-framework/pods#4857]
## Issue Overview
`.pods-manage-field .pods-field-option textarea` allows the WP WYSIWYG `textarea` element to float left at line 1924; elements placed after the `textarea` within the same parent then creep up aside it.

## Current Behavior
Created a WYSIWYG in a Pods Settings panel; added Description content for the element; Description content floats to the right of the WYSIWYG's `textarea` element
![image 2018-04-21 at 8 35 52 pm](https://user-images.githubusercontent.com/3052875/39263066-24de7034-488f-11e8-9741-da42defa93fc.png)

## Expected Behavior
WYSIWYG's `textarea` element should not be floated at all, so the expectation is that it clears elements which follow it within the DOM
![image 2018-04-21 at 8 36 59 pm](https://user-images.githubusercontent.com/3052875/39263073-2ae4cd48-488f-11e8-9e0b-2e10612b1585.png)

## Possible Solution
Add a `float: none` declaration to line 1930 in pods.css within the `.pods-manage-field .pods-field-option .pods-form-ui-field-type-wysiwyg textarea` block

## Steps to Reproduce (for bugs)
1. Create a WYSIWYG in a Pods Settings panel
2. Add Description content for the element
3. View resulting Settings page (resize screen for full effect)

## WordPress Environment
<details>
WordPress Version: 4.9.5
PHP Version: 7.2.4
MySQL Version: 5.7.21
Server Software: Apache/2.4.33 (Unix) OpenSSL/1.0.2g
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
</details>

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!

Seem to work for me! Closing it.
