### ISSUE TITLE
Pods Shortcode conflict - WPML Multilingual CMS

### ISSUE THREAD

**Issue by texomacog** [pods-framework/pods#4859]
## Issue Overview
While using Pods shortcode, additional LEFT JOIN sql statement is generated (and therefore a SQL error) on a page refresh or subsequent visit to page where data is displayed. 

## Expected Behavior
Pods shortcode should display a list of results from data stored in a custom post type generated by the Pods plugin every time a page loads.

## Current Behavior
Pods shortcode displays a list of results from data stored in a custom post type generated by the Pods plugin only on the first page load. Subsequent page loads/refreshes result in a SQL error caused by the addition of a third LEFT JOIN statement in the SQL command. This is only remedied when the Pods cache is flushed. After flushing, page reloads fine ONCE and the bug surfaces again.

## Possible Solution
Temporary fix is disabling WPML Multilingual CMS. 

## Steps to Reproduce (for bugs)

1. Create Pods "membership", meta storage type, 10 fields
2. Fields include:
- Member Type (Relationship - Simple (custom defined list) )
- Contact Name (Plain Text)
- Website (Website)
- Phone (Phone)
- Fax (Phone)
- County (Relationship - Simple (custom defined list) )
- Mailing Address (Plain Text)
- City (Plain Text)
- State (Relationship - US States (Predefined List) )
- Zip (Plain Text)
3. Create new Page and use following shortcode to display results:
```<dl>[pods name="membership" where="county.meta_value = 'Cooke County' AND (member_type.meta_value='City' OR member_type.meta_value='County')" orderby="member_type.meta_value DESC"]
<dt>[if website]<a href="{@website}" target="_blank" title="Visit {@title} online" class="themecolor">[/if]<h5>{@title}</h5>[if website]</a>[/if]</dt>
<dd><p>{@contact_name}</p>
<p>{@mailing_address}<br />{@city}, {@state} {@zip}
[if phone]<br /><a href="tel:{@phone}" title="Call {@title} at {@phone}">{@phone}</a><strong> Phone</strong>[/if]
[if fax]<br />{@fax}<strong> Fax</strong>[/if]</p>
[if website]<p><a href="//{@website}" target="_blank" title="Visit {@title} online">Visit website</a></p>[/if]
[/pods]</dl>
```

4. View page. Load fine. Refresh page. SQL error. Empty cache. Load fine. Refresh page. SQL error.
SQL Error
`https://gist.github.com/texomacog/8a326b700b3c98ebfe514139d905c1d1`
## Pods Package Export (helpful!)

`
https://gist.github.com/texomacog/3dd1b9161ed8ac12d0b6d4dda4824d47#file-membership-pod-export-pkg-2018-04-12-txt
`
## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
WordPress Version: 4.9.5

PHP Version: 7.0.18

MySQL Version: 5.7.18

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Session Save Path: /opt/bitnami/php/tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: TCOG

Currently Active Plugins:

Advanced Post Manager: 4.4
All-in-One WP Migration: 6.67
Force Regenerate Thumbnails: 2.0.6
Gravity Forms: 2.2.5
Gravity Forms Geolocation Add-on: 2.5.0.1
Gravity Forms Multilingual: 1.3.16
Gravity Forms SendinBlue Add-On: 1.0.5
Pods - Custom Content Types and Fields: 2.6.11
Post SMTP: 1.8.3
SendinBlue Subscribe Form And WP SMTP: 2.9.1
Slider Revolution: 5.4.7.2
The Events Calendar: 4.6.13
The Events Calendar PRO: 4.4.24.2
WordPress Database Reset: 3.0.2
WPML Multilingual CMS: 3.9.3
WPML String Translation: 2.7.3
WPML Translation Management: 2.5.2
</details>

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Due to the age of this issue, is this still relevant?

**Comment by JoryHogeveen** [comment]
Reviewed the error and I'm sure this is an old bug that is fixed since we refactored our WPML integration.
Closing issue.
