### ISSUE TITLE
Getting into WordPress core

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#4862]
Are there plans/intentions to get Pods (or a part of it) into WordPress core?

Thanks.

**Comment by sc0ttkclark** [comment]
There are no plans, WordPress core would probably not merge ACF into core either. Whatever ends up in core (if at all) would be something totally new but based off of some existing patterns used by popular plugins like ACF. There's also the whole Gutenberg thing so we're not likely to see much focus on custom fields for a great deal of time.

**Comment by szepeviktor** [comment]
Thank you.

Do Pods remains a must-have for professionals.
