### ISSUE TITLE
Single Select Simple List Only Returns 'Value' in PHP Template

### ISSUE THREAD

**Issue by clearlymedia** [pods-framework/pods#4869]
## Issue Overview
I am working on pulling in the value|Label from a simple list in a php template. No matter how I approach outputting it, whether using $pod->display or $pod->field, it only returns the ‘value’.
Currently, I am inside a related loop looking to output the value and Label in a simple list selection from that related item. 

## Expected Behavior
Based on the special note at the bottom of this page, https://pods.io/tutorials/get-values-from-a-custom-relationship-field/ `$pod->display('field_name');` should display the value and `$pod->field('field_name');` should display the label. 

## Current Behavior
No matter what method I use, `$pod->display('field_name');` or `$pod->field('field_name');` it only returns the value in the Key|value pair. So I then did a var_dump and it says I only have 1 item in the array (the value), and doesn't even recognize the key. 

## Steps to Reproduce (for bugs)
1. I have a pod called Reviews that has a Simple List relationship (single select) called 'Overall Rating' with options of 
1|1 Star
2|2 Star
3|3 Star
4|4 Star
5|5 Star
2. I then have a pod called Location that has a bi-directional field 'Related Reviews' that relates to the review. 
3. I am then using a php template to pull in the selection from the 'Overall Rating' field inside the 'Related Reviews' loop.

```
<?php
    $pod = pods( 'location', get_the_id() );
    $relatedreviews = $pod->field( 'related_reviews' );
    if ( ! empty( $relatedreviews ) ) {
?>
	<div class="reviews-sidebar">
		<div class="box-title">
			Reviews
		</div>
		<div class="box-body">
		<?php foreach ( $relatedreviews as $rel ) { ?>
			<div class="item reviews">
			<?php	
				$id = $rel[ 'ID' ];
			?>
				<span class="review-info"><strong><a href="<?php echo get_permalink($id); ?>"><?php echo get_the_title( $id );?></a></strong>
				<br>
				<?php
					$overallrating = $pod->field('related_reviews.overall_rating'); 
					$overallratingvalue = $pod->display('related_reviews.overall_rating');
				?>
				<?php echo $overallrating; ?></span> <span class="star-<?php echo $overallratingvalue; ?>"></span>
				<br>
				<a href="<?php echo get_permalink($id); ?>">Read Review</a>
			</div>
		<?php } ?>
		</div>
	</div>
<?php } ?>
```

[Location - Review Pods.txt](https://github.com/pods-framework/pods/files/1961504/Location.-.Review.Pods.txt)

## Pods Package Export (helpful!)
.txt file attached

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
WordPress Version: 4.9.4

PHP Version: 7.0.28-0ubuntu0.16.04.1

MySQL Version: 5.7.21

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/staging/afsrepair/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme:

Currently Active Plugins:

Akismet Anti-Spam: 4.0.3
FooBox Image Lightbox: 2.5.2
Gravity Forms: 2.2.6.5
Gravity Forms Bootstrap 3 Style: 0.3
Jetpack by WordPress.com: 6.0
Nested Pages: 2.0.4
Pods - Custom Content Types and Fields: 2.7.1
Pods SEO: 2.1
Social Warfare: 2.3.5
WordPress Importer: 0.6.4
WPBakery Page Builder: 5.4.6
Yoast SEO Premium: 7.0.3
[Location - Review Pods.txt](https://github.com/pods-framework/pods/files/1961507/Location.-.Review.Pods.txt)

```
</details>

**Comment by GaryJones** [comment]
I experienced this as well. I had a simple custom field when extending _Pages_ and wanted to display a dropdown that would allow me to select an `<option>` that had values different to the label, but the values seemed to be populated with the labels which then would break in the Pod Template output.

**Comment by pglewis** [comment]
Without having attempted to reproduce this one yet, I see we have numeric keys for the simple list, which might be resolved via #4928

**Comment by quasel** [comment]
Should be fixed pleas test/comfirm!

**Comment by jimtrue** [comment]
@clearlymedia this was patched to be fixed (using numerical 'values' was the issue) in this update #4928. Can you confirm that you are now properly working? If we don't hear back from you, we will consider this issue closed. Thanks!

**Comment by jimtrue** [comment]
Closing this one per last comment.
