### ISSUE TITLE
Website & Phone Custom Fields Value Masks are not working properly

### ISSUE THREAD

**Issue by TheDude12x** [pods-framework/pods#4881]
## Issue Overview
When I use the Phone custom field and select “US (999) 999-9999 x123” as the format, when the field is left blank, it saves “() -” as the value. And when using the Website custom field and chose one of the “force www” as the format, when I enter domain.com, the saved value does not have the “www” added.

## Expected Behavior
When the Phone field is left blank, there should be no value saved. When a value is entered for the Website field without the "www", the "www" should be added to the value. 

## Field Formats to fix

- [ ] Phone should not put anything in the field input on 'blank' values
- [ ] Force WWW on Website/URL fields should add the `www.` to the front of field.

**Comment by jimtrue** [comment]
@pglewis Let me know if these should be two separate bug reports.

**Comment by TheDude12x** [comment]
Will this be addressed soon? I know it's not high priority but I use it quite a bit. Thanks.

**Comment by jimtrue** [comment]
This should be addressed if not before 2.8 at least as part of 2.8.

**Comment by pglewis** [comment]
PRs: #5290, #5291
