### ISSUE TITLE
Simple Predefined List Days of Week is not saving choices properly

### ISSUE THREAD

**Issue by rotirk** [pods-framework/pods#4892]
## Issue Overview

Hello.I'm not so good at english but I will try to tell the problem.I made a website for movies with shedule and halls.When I create Shedule and check few days etc. Tuesday, Friday and I Publish that it works fine all.But If I want to edit or change that shedule it show me default first 2 days checked (Sunday,Monday).If I did check one it will show on edit Sunday.If I check 3 like (Friday,Monday,Saturday) it will show me on Edit after Publish Sunday,Monday,Tuesday.

## Expected Behavior

![multiplex](https://user-images.githubusercontent.com/24462215/39628511-9c55b106-4fa9-11e8-9a92-04ee98ab1658.png)
![multiplex](https://user-images.githubusercontent.com/24462215/39628511-9c55b106-4fa9-11e8-9a92-04ee98ab1658.png)

## Current Behavior

Checking first days instead of selected days.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```d

## Related Issues and/or PRs
<!-- List related issues or PRs against other branches:  -->
sda
## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by jimtrue** [comment]
@rotirk It would help to receive your Migrate Packages Export as requested above:
## Pods Package Export (helpful!)




```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by rotirk** [comment]
[JSON.txt](https://github.com/pods-framework/pods/files/1974531/JSON.txt)

**Comment by jimtrue** [comment]
VERIFIED: Both using @rotirk JSON export and a simple test with only a Simple Relationship, with Custom Defined 'Days of Week'. No matter what you select, it immediately chooses only the first items.

**Comment by jimtrue** [comment]
Possibly related to #4753 since value of the field is actually numeric (the index 0-7 for day of the week) and the Label is what is visible. That problem was also with fully numeric values.

**Comment by pglewis** [comment]
PR: #4928

**Comment by rotirk** [comment]
Tested and working well!
