### ISSUE TITLE
Code Syntax Fields Overflowing primary container on Taxonomy/Category post 2.7.2

### ISSUE THREAD

**Issue by davidki11** [pods-framework/pods#4913]
After update Pods to version 2.7.2 and the last 2.7.2.1, there are problems in admin of category pages.

All fields are stretched at a width larger than the width of the page. The problem persists even if I switch on one of the default WordPress theme.

No other plugin has been updated in recent days. Just Pods.

When I deactivate Pods plugin, everything is fine.

Can you fix it, please?

Thank you, David

**Comment by pglewis** [comment]
Both the main categories page and edit categories resize properly for me, perhaps I don't understand exactly where you're talking about?  

![categories](https://user-images.githubusercontent.com/1973916/39670680-e982db8c-50d7-11e8-83b2-ac397fe4479d.png)
![categories-wider](https://user-images.githubusercontent.com/1973916/39670682-ec0f5934-50d7-11e8-802e-1dcaca0c5f02.png)
![edit-category](https://user-images.githubusercontent.com/1973916/39670683-edd1739c-50d7-11e8-9eaf-6c4a2a66bdc5.png)
![edit-category-wider](https://user-images.githubusercontent.com/1973916/39670686-ef59c214-50d7-11e8-8f2b-1124b4f594d8.png)

**Comment by davidki11** [comment]
But I see it like on the screenshot
![category-page](https://user-images.githubusercontent.com/25124156/39672997-c28e3974-5134-11e8-99ab-5a5ccb41b632.png)

**Comment by jimtrue** [comment]
@davidki11 you'd need to give us a before and after because that looks totally normal to me when you're editing the term directly on a wide screen monitor.

**Comment by davidki11** [comment]
1. Here is a screen from category term page when Pods is deactivated
![category-page - pods deactivated](https://user-images.githubusercontent.com/25124156/39673357-f0de2e6e-513a-11e8-9a1d-d9dcf5007974.png)

2. Here is a screen from category term page when Pods is active
![category-page - pods active](https://user-images.githubusercontent.com/25124156/39673361-ff8e3468-513a-11e8-9299-e1175ad837f6.png)

**Comment by jimtrue** [comment]
@davidki11 I'm on a local installation with nothing but Pods installed and unfortunately, I'm not seeing that issue. 

When you created this issue, it appears you didn't answer or provide any of the details that were in our Issue Template (the ones that ask you to include your debug details, etc.). We ask for those in bug reports so that we can properly troubleshoot your problem, without having to ask for them again later.

Please provide us the following:
## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by davidki11** [comment]
I have these problems only in category term pages. Because category taxonomy is the only one taxonomy for which I created a custom field with Pods. Tags term pages are ok. Also, term pages of taxonomies created by Pods are ok.

I tested it with the default wordpress template. I also tried to deactivate all plugins except Pods plugin v 2.7.2.1

When is Pods v 2.7.2.1 deactivated, all works well. I also tried to downgrade Pods back to version 2.7.1 

With version 2.7.1 there are no such problems. 

Besides the stretched fields in category term page, on this screenshot, you can also see some problem with z-index or what:
![category-page - z_index](https://user-images.githubusercontent.com/25124156/39675478-c45246b6-515b-11e8-920f-5371641f0130.png)

And here is another weird thing. Some overflow-x CSS problem:
![category-page - owerflow](https://user-images.githubusercontent.com/25124156/39675483-d4484fc0-515b-11e8-96ad-ac4ef135fe70.png)

Here is my Debug Information:
WordPress Version: 4.9.5

PHP Version: 7.0.19

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

Session Save Path: /data/web/virtuals/189768/virtual/session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: hekag_

WP Multisite Mode: No

WP Memory Limit: 128M

Pods Network-Wide Activated: No

Pods Install Location: /data/web/virtuals/189768/virtual/www/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: recenzoid-child

Currently Active Plugins:

    Affiliate Egg Pro: 8.9.5
    Ajax Search Pro: 4.13
    Akismet Anti-Spam: 4.0.3
    All In One WP Security: 4.3.3.1
    BackWPup: 3.4.5
    Bellows Accordion Menu: 1.2.1
    Content Egg Pro: 4.5.0
    Duplicate Post: 3.2.2
    Indeed Ultimate Membership Pro: 6.9
    Loco Translate: 2.1.3
    Mailster - Email Newsletter Plugin for WordPress: 2.3.5
    Optimize Database after Deleting Revisions: 4.5.2
    Pods - Custom Content Types and Fields: 2.7.2.1
    Really Simple SSL: 2.5.26
    RH Fallback image: 1.1
    RH Grandchild Custom: 1.0.3
    Server IP & Memory Usage Display: 2.1.0
    Shortcode in Menus: 3.4
    Taxonomy admin filter: 1.1.0
    Thrive Leads: 2.0.30
    TinyMCE Advanced: 4.6.7
    User Role Editor: 4.40.3
    WooSidebars: 1.4.3
    WordPress Meta Data & Taxonomies Filter (MDTF): 2.2.3
    WP-PostRatings: 1.85
    WPBakery Page Builder: 5.4.7
    Yoast SEO: 6.3.1

**Comment by deepak-india** [comment]
![image](https://user-images.githubusercontent.com/38727553/39752178-48659516-52d8-11e8-8045-fc924cb69441.png)
same thing happen with me, all fields are stretched in category edit page if i update the pods to 2.7.3, but if i switch back to pods 2.7.1. it work fine. does any function depreciate or is it a bug .
Debug Information
WordPress Version: 4.9.5

PHP Version: 7.1.14

MySQL Version: 5.6.39

Server Software: Apache

Your User Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/xj7c534hh05h/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Crypto Scribe

Currently Active Plugins:

Admin Columns: 3.1.10
Contact Form 7: 5.0.1
EWWW Image Optimizer: 4.2.1
Google Analytics for WordPress by MonsterInsights: 7.0.5
MailChimp for WordPress: 4.2.1
OptionTree: 2.6.0
Pods - Custom Content Types and Fields: 2.7.3
Restrict Content Pro: 2.9.7
Restrict Content Pro - MailChimp Pro: 1.3.3
Slimstat Analytics: 4.7.8
Supreme Google Webfonts: 2.0.1
Wordfence Security: 7.1.4
Yoast SEO: 7.4.2

**Comment by jimtrue** [comment]
Here's an Export Package for verification. All that's required is adding a Code field to a Taxonomy or Extended Category. It impacts both screens.

```
{"meta":{"version":"2.7.2","build":1525782395},"pods":{"37":{"id":37,"name":"category","label":"Category","description":"","type":"taxonomy","storage":"meta","object":"category","alias":"","fields":{"test_code":{"id":45,"name":"test_code","label":"Test Code","description":"","help":"","class":"","type":"code","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","code_allow_shortcode":"0","code_max_length":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","code_repeatable":"0"}},"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

**Comment by deepak-india** [comment]
Yes i am using Code (Syntax Highlighting) field , should i change the field to textarea or there any solution for it.

**Comment by jimtrue** [comment]
That would be your workaround until we're able to hotfix this one or downgrade your Pods version. It should still save the exact same information, you just wont' have the code syntax highlighting.

I believe this has to do with the fixes we put into the codemirror field to stop other plugins from conflicting with them.

**Comment by pglewis** [comment]
Thanks for helping us find the culprit, we'll get it fixed.

**Comment by pglewis** [comment]
This also affected CodeMirror fields in Users and possibly a few other places.

**Comment by pglewis** [comment]
PR: #4923.  

Browsers can be aggressive about caching CSS, so be sure to clear cache or use a private/incognito window if you test.
