### ISSUE TITLE
Show text if no pods items found with shortcode.

### ISSUE THREAD

**Issue by ghost** [pods-framework/pods#4918]
Hey, im building a tv schedule with pods, and in a wordpress page i use this shortcode [pods name="sndning" orderby="starttid" where="datum.meta_value = '2018-05-06'" template="Stor tablå"] is it possible to in some how display a specifik message like "No schedule" if no pods items is loaded ?

**Comment by quasel** [comment]
Depending on your use case you might find the answer here - https://pods.io/docs/build/template-tags-in-pods-templates/ 

Sorry for the late reply, feel free to comment if you still have questions!
