### ISSUE TITLE
Gutenberg MVP Functionality for 2.8

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4921]
## Issue Overview
Creating a list of the items that will be at a minimum what we need to provide compatibility with Gutenberg.

- [x] Ability to turn on or off 'Gutenberg Editor' on a Post type/Pod basis much like this plugin, the [Gutenberg Manager](https://wordpress.org/plugins/manager-for-gutenberg/)
- [x] Add Gutenberg Support in Editor should use the REST API 'on' configuration as this makes us instantly work (ie REST API supported metabox) in the Gutenberg Editor
- [x] Add New Items currently explode out of the modal (showing the entire WP Admin) when inside the Gutenberg editor. I think #4600 addresses this. (Fixed by: #5501)
- [x] Rewrite Widgets to use Block Support #4668 & #5240

**Comment by sc0ttkclark** [comment]
Resolved in 2.8
