### ISSUE TITLE
PODS breaks Theme Editor

### ISSUE THREAD

**Issue by KP987** [pods-framework/pods#4931]
## Issue Overview
The "PODS" plugin interferes with the WP Theme Editor's ability to save PHP files

## Expected Behavior
To be able to edit the Theme without an error.  If you Disable the plugin, then theme edits can be saved without an error.

## Current Behavior
When the "PODS" plugin is enabled, the following error message displays when you try to save a PHP file in the WP Theme Editor ( /wp-admin/theme-editor.php ):

"Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP."

## Possible Solution
UPDATE: I got some informative feedback, and an Plugin update with the fix, from Bob at Watu Pro…
https://wpengine.com/support/php-editor-errors-wordpress-4-9-higher/
Hope this helps. KP

## Steps to Reproduce (for bugs)
1. Install default WP with "Twenty Seventeen" Theme
2. Install "PODS" plugin
3. go to /wp-admin/theme-editor.php and try to save any PHPOOP file
4. Observe the error message and inability to save the file

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
v 4.9.5
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by sc0ttkclark** [comment]
Oh wow this is weird, I've never seen this issue before. However, they can disable the Pods auto start of sessions via a new constant in wp-config.php with `define( 'PODS_SESSION_AUTO_START', false );`

**Comment by sc0ttkclark** [comment]
What hosting are you currently using? Is it WPEngine? What are the values of Pods Admin > Settings for Session Save Path, Session Save Path Exists, and Session Save Path Writeable? See here for an example:

![](http://sc0tt.me/3t0x2D0b413f/Screen%20Shot%202018-05-22%20at%205.28.41%20PM.png)

**Comment by pglewis** [comment]
PR: #4953

**Comment by pglewis** [comment]
This should hopefully be resolved in the branch for the PR above so please test.
