### ISSUE TITLE
Magic tags / Traversal - Outputting "raw" value instead of "display" value (date, pick,… )

### ISSUE THREAD

**Issue by BenJackGill** [pods-framework/pods#4932]
## Issue Overview
When using magic tags that traverse through a relationship in a pods template it is displaying as 'raw' data instead of 'human readable' format.

For example, using {@custom_field_with_related_post.custom_meta_field} will output raw data instead of a human readable format.

## Expected Behavior
Output human readable format.

## Current Behavior
Outputs raw data.

## Steps to Reproduce (for bugs)
1. Make a custom post type (e.g. "Engines") and give it a yes/no custom field (e.g. "Is powerful?").
2. Make a custom post type (e.g. "Cars") and give it a custom relationship field (single select) linked to Engines.
3. Add some posts to the Engines post type.
4. Create a template (e.g. "Engine Power") and include the magic tag {@engines.is_powerful}
5. Create a Cars post, and select an engine from the custom relationship field. Include [pods template="Engine Power"] into the post editor.
6. Preview the cars post on the front end. The "engine power" custom field will be output as a raw data ("1" or "0") instead of the correct human readable format ("Yes" and "No").

## Pods Package Export (helpful!)
Export attached 
[bug report.txt](https://github.com/pods-framework/pods/files/2000742/bug.report.txt)

## WordPress Environment
<details>
```
Debug Information
WordPress Version: 4.9.5

PHP Version: 7.0.30-1~dotdeb+8.1

MySQL Version: 5.6.39

Server Software: Apache/2.4.10 (Debian)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: Yes
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: Yes
APCu: Yes
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/43307-85855.cloudwaysapps.com/jwzqnqwkyc/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Pro – Child Theme

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.3
WP All Import Pro: 4.5.1
```
</details>

**Comment by bennygill** [comment]
Also want to add, this same issue occurs when traversing a related custom taxonomy. It's not just custom posts.

**Comment by quasel** [comment]
same applies to shortcodes and dates see #5070 for details!
