### ISSUE TITLE
Hour field blank if set to 12.00am

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#4937]
The hour field remains blank on save when I select 12.00am as a time.

This is a re-up of an earlier report of mine here - [Issue 3499](https://github.com/pods-framework/pods/issues/3488)

Also - and perhaps this should be a separate issue - it isn't possible to copy and paste into the hour fields which would be handy for multiple duplicate fields. 

![blank-time-field](https://user-images.githubusercontent.com/1478964/40120630-9722b676-5917-11e8-97bb-a98c3c72f036.png)

**Comment by pglewis** [comment]
12:00am saves as 00:00:00, so the problem is on the loading side.
