### ISSUE TITLE
datetimepicker is not a function

### ISSUE THREAD

**Issue by tomwake** [pods-framework/pods#4939]
## Issue Overview
After upgrading to Pods 2.7.3 I get the following error on an admin page -

``` jQuery(...).datetimepicker is not a function```
The pods code is as follows -

``` jQuery( 'input#pods-form-ui-pods-meta-published-date' ).datetimepicker( pods_form_ui_pods_meta_published_date_args );```

Any ideas on where to start looking? In the datetime.php file it's loading en as the locale, but I can see that this file doesn't exist in the i18n folder for the timepicker.

**Comment by pglewis** [comment]
@tomwake: did you mean to close this?  Did the issue resolve itself?

**Comment by tomwake** [comment]
Apologies, I didn't mean to close this. I've carried out extensive testing and believe that it could relate to a conflict with another plugin. I'm currently working out whether I can deactivate any without losing site functionality - the theme relies heavily on some.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
