### ISSUE TITLE
Extended Post Type on Media disabled Set Featured Image button

### ISSUE THREAD

**Issue by joegrantstn** [pods-framework/pods#4945]
## Issue Overview
I recently noticed that when I created a new Pod to extend the Media files on my site, the Set Featured Image button on posts/pages/etc became disabled (see screenshot: https://i.imgur.com/UhOVGTo.png  ) So far I have tested this with the Plain Text, Website, and Yes/No Picker pod types, all NOT required, but the result is the same.

## Expected Behavior
Adding Pods to create additional meta info on Media within the Media Library should not affect the ability to add/change the Featured Image of a post/page.

## Current Behavior
When a Media (extended) Pods type is added (so far it doesn't seem like it matters which type of field(s) are used), trying to add or change a Post/Page's Featured Image is disabled (see screenshot: https://i.imgur.com/UhOVGTo.png  ). When I turn off Pods or remove the Media Pod, I can then set featured images.

## Steps to Reproduce (for bugs)
[redacted] 

The only plugin on this site is Pods. I created a basic Plain Text pod on the Media items, and added a bunch of items to the Media Library.

Edit or create posts and pages, then try to add or switch Featured Images. Occasionally it will work, but most of the time it is disabled.

## Possible Solution
I know very little about how all this works, but it seems to me like having the Media pod on there is making it query the database and it is either getting stuck, or looping. I think this because on occasion, if it sits for a second, the button reactivates, but if I try another image, it deactivates again like it is re-querying for something.

## WordPress Environment
```
WordPress Version: 4.9.6

PHP Version: 5.6.36

MySQL Version: 5.6.33

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: Yes
WPDB Prefix: 8EcGz82u_

WP Multisite Mode: Yes

WP Memory Limit: 64M

Pods Network-Wide Activated: Yes

Pods Install Location: /home/example09.stoysnet.com/httpdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.3
```
</details>

## Pods Package Export (helpful!)
```
{"meta":{"version":"2.7.3","build":1526685215},"pods":{"9":{"id":9,"name":"media","label":"Media","description":"","type":"media","storage":"meta","object":"media","alias":"","fields":{"text-field":{"id":10,"name":"text-field","label":"text-field","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":1,"rest_enable":"0","read_all":"0","write_all":"0"}}}
```

## Workaround or Alternate Solution Until Bug is Addressed
No idea yet.

**Comment by pglewis** [comment]
PR: #4946

**Comment by pglewis** [comment]
> I am getting the Uncaught ReferenceError: PodsDFV is not defined... javascript error on Pods 2.7.9. It happens when the Featured Image is already set and I try to change it with another one. So the Use Image button can't be clicked.
> 
> I verified that there's no javascript file named pods-dfv that gets loaded when I'm on the admin panel.
> 
> Any ideas?

I'll see if I can reproduce this, though it seems like #4946 should have fixed it.

**Comment by pglewis** [comment]
Also @BorislavZlatanov: have you extended WordPress media?  I'm guessing that's the case, either with a pick field or file upload.  If so, what field type and display option?

**Comment by pglewis** [comment]
Replies on #5111, I'm closing this again in favor of a new issue.
