### ISSUE TITLE
Resyncing bi-directional relationships

### ISSUE THREAD

**Issue by TrevorSather** [pods-framework/pods#4948]
## Issue Overview

Let’s say we create two pods, People and Pets, and then add a relationship field to each one to connect to the other one.  But we only remember to connect one of them.  So on the People pod, a field related_pets is connected to related_people on the Pets pod;  but on the related_people field on the Pets pod, it isn’t connected back again.

Then we let a site admin update the site for a while, and they add lots of relationships from the People end, which are saving, but they’re not updating at the other end.  We then realise the error and go and fix the fields.

But, is there any easy way of getting the historic data to sync - short of going through and resaving each Person?

(@jimtrue suggested I log this here.)

## Possible Solution

@jimtrue wondered - maybe a "Resync Relationships" button in Pods Admin?

## WordPress Environment

(Example above from my imagination.)

## Workaround or Alternate Solution Until Bug is Addressed

We can resave each record individually and manually, from the side that was working originally, and now the other side will update.  But problematic if there are 100s of records.

Thanks!

**Comment by quasel** [comment]
Well if I'm not mistaken simpelst way would be a simple "resave" maybe you need to tweak it to first gather ID / Value and save in a second loop (never tested it might break if you use the same pods_object to load and save ;)  Maybe @sc0ttkclark can answer this quicker then me researching it ^^

Depending on how many items you already have and your Server Settings you might run into a Server Timeout then you would need to do it in batches - using https://pods.io/docs/code/pods/find/ with Parameters ;) 

`
function resave_pod_items() {
    // Create and find in one shot
    $your_cpt = pods( 'your_cpt' )->find();
    if ( 0 < $your_cpt->total() ) {
        while ( $your_cpt->fetch() ) {
            $your_cpt->save( 'your_relationship_field', $your_cpt->field('your_relationship_field'));
        } // end of your_cpt loop
    } // end of found your_cpt
}
`

**Comment by jimtrue** [comment]
That's not actually a Support item @quasel Having the ability to rebuild the wp_podsrel wouldn't be a bad idea. But this is a Feature Request and will be flagged Needs Votes and Enhancement.
