### ISSUE TITLE
Toggle between Advaced Content Types and WP table storage

### ISSUE THREAD

**Issue by jonathanasbell** [pods-framework/pods#4950]
## Issue Overview

Allow a Pod to be re-configured with "Advaced Content Types" even after it was created, and also back to WP types
## Expected Behavior

 

ability to flip between storage approaches at any time
## Current Behavior

 

must choose on creation and there is no way to convert it back
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
Create any pod
## Possible Solution

Make an adapter that can move the pod storage from one type to another and back at any time
## WordPress Environment

<details>
```n/a
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```n/a
</details>

## Pods Package Export (helpful!)
<!-- Please include the Pods Package Export as it will be helpful in reproducing your issues. -->
<!-- To access: Pods Admin, Components, Migrate: Packages, Enable. -->
<!-- Then Pods Admin, Migrate: Packages, Export and Copy and Paste the JSON here OR -->
<!-- Save to a text file and upload to this bug report -->
```n/a
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```
n/a
## Workaround or Alternate Solution Until Bug is Addressed

none
## Related Issues and/or PRs

n/a

**Comment by jimtrue** [comment]
Just a note: this wouldn't and couldn't possibly be a toggle. This would require a conversion because WP custom post types are in completely different structures from ACT which are stand alone tables.

**Comment by quasel** [comment]
Never tested it but @sc0ttkclark did some work in that direction - https://github.com/pods-framework/pods-convert - although that's likely outdated ;)

**Comment by jonathanasbell** [comment]
Thanks Jim and Quasel. Yes I didnt really mean it the way I said it. I did mean convert. That said a convert mechanism would get rid of the need to have a custom configured import and export

**Comment by jimtrue** [comment]
Like our other Feature Requests, closing with Needs Votes.
