### ISSUE TITLE
PodsUI/PodsData cache bug

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#4960]
See #3577

In `PodsUI::get_row` `$this->pod->fetch();` is called. However in `PodsData::fetch`, it checks if the ID is a number and falls back to a slug. But there seems to be a case where both `id` and `slug` are null.

With object cache, that causes the cache key to be only the pods version number? The result is a weird edge case situation which i have yet to debug the actual saving of the key, but the key never gets cleared and causes the UI to never update, and maybe other side effects.

**Comment by quasel** [comment]
@pcfreak30 is this still an issue did you dig deeper?

**Comment by pcfreak30** [comment]
Yes, I had to re-apply my patch to it my client recently on the latest 2.x branch.

**Comment by JoryHogeveen** [comment]
Closed by #5062
