### ISSUE TITLE
Value not saving to table storage

### ISSUE THREAD

**Issue by Zudin-Evgen** [pods-framework/pods#4965]
## Issue Overview

Value not saving to table storage

## Expected Behavior
1. I want to add a few(or more) options to empty selectbox with the help of javascript(or via ajax, it's not matters):
![screenshot_5](https://user-images.githubusercontent.com/24369932/40660394-8ec5f32a-6359-11e8-98ea-98b5cded9d83.png)
2. And save this value it to cpt table storage:
![screenshot_6](https://user-images.githubusercontent.com/24369932/40660440-ae2bb1fa-6359-11e8-9374-827b7c6c07bf.png)
![screenshot_10](https://user-images.githubusercontent.com/24369932/40660880-f441fffe-635a-11e8-91f4-7dba501be0b9.png)

## Current Behavior

Value is not saving

## Steps to Reproduce (for bugs)

1. Add cpt "test" in pods:
![screenshot_1](https://user-images.githubusercontent.com/24369932/40660523-e7deec64-6359-11e8-88ed-86bf00709adc.png)
2. Add relationship field(custom defined list) "testfield".
![screenshot_2](https://user-images.githubusercontent.com/24369932/40660856-e7f44554-635a-11e8-8a1b-74e48e88a93f.png)

3.  Click "Add new" 
![screenshot_3](https://user-images.githubusercontent.com/24369932/40660619-2da46fc6-635a-11e8-931e-091f9832e605.png)

4. Add custom js code to console:
`$('#pods-form-ui-pods-meta-testfield').append('<option value="1">One</option>').append('<option value="2">Two</option>');`
![screenshot_5](https://user-images.githubusercontent.com/24369932/40660640-42ab5a9c-635a-11e8-91ce-b00157dfd901.png)

5. Click "publish" button.
![screenshot_6](https://user-images.githubusercontent.com/24369932/40660925-1482f426-635b-11e8-9333-14b9157047db.png)

6. Check post id
![screenshot_7](https://user-images.githubusercontent.com/24369932/40660944-29b7152a-635b-11e8-8731-a4c8113ca6f8.png)

7. Check new cpt entry in table storage:
![screenshot_8](https://user-images.githubusercontent.com/24369932/40660977-414583fc-635b-11e8-9cef-38fab713a088.png)

end.

## In addition
This method working for other type of fields(number, textplain).

Also, value not saving when i'm filling selectbox with "pods_field_pick_data" filter:
`function pods_teacher_pick_data2323($data, $name, $value, $options, $pod, $id){
    $data[1] = 'One';
    $data[2] = 'Two';
    return $data;
 }

add_filter('pods_field_pick_data', 'pods_teacher_pick_data2323', 1, 6);`

## WordPress Environment

<details>
WordPress Version: 4.9.6

PHP Version: 7.1.1

MySQL Version: 5.7.17

Server Software: Apache/2.4.25 (Win64) PHP/7.1.1

Your User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 86400

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: af_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: C:\www\afu\wp-content\plugins\pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: afu

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.3

</details>

**Comment by quasel** [comment]
Hi,
A relationship fields need an existing CPT entry to point too - if you just add the value to the select dropdown there is no "entry" to point to! Hence this can't work if you don't create the related item first and provide the ID!
