### ISSUE TITLE
Add Media Loses Attachment Settings when Extended with Pods Fields

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4967]
## Issue Overview
When Extending Media Library with additional fields, the Attachment Settings Metabox disappears entirely. This is from this forum post: https://wordpress.org/support/topic/media-fields-issue-display-settings/

## Expected Behavior

 

When adding media to the post, the Pods field should just display above the Attachment Settings, not replace them, entirely. (See example of how this works without the fields being added)

![screenshot 2018-05-30 09 32 47](https://user-images.githubusercontent.com/3052875/40723409-e17abc66-63ec-11e8-8478-30c78592ef1e.png)

## Current Behavior

 

If you extend Media and add a field, this is the display you get when adding media inside a post:
![screenshot 2018-05-30 09 32 11](https://user-images.githubusercontent.com/3052875/40723656-59cf9484-63ed-11e8-94cc-2f43db2cafff.png)

## Steps to Reproduce (for bugs)

1. Extend the Media Library and add any field to it.
2. Go to a post or page and attempt to insert Media via the Add Media button.
3. The Add media screen pops up but the Attachment Display Settings (Alignment, Link To, Size) are not visible.
4. Delete the Pods Feilds and the Attachment Display Settings come back.

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 4.9.6

PHP Version: 7.1.7

MySQL Version: 5.6.37

Server Software: nginx/1.10.1

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.4-a-1
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by pglewis** [comment]
Related: #4945

Should be fixed in #4946
