### ISSUE TITLE
Required select options not being saved

### ISSUE THREAD

**Issue by bemdesign-er** [pods-framework/pods#4968]
## Issue Overview
Required select field, selected option not being registered or saved, triggering validation error on front-end form submission.

## Expected Behavior
User selects option on required select field and their selected option is registered/saved on form submission.

## Current Behavior
Despite selecting an option in a required select field, the form generates a javascript alert message about how the first required select field is empty. Exact message: "Error: [Field Name] is empty" even though that field is not empty.

## Steps to Reproduce (for bugs)
See https://f2fmichigan-staging.cyuytk3-liquidwebsites.com/family-stories/submit-your-story/ - fill in the required fields and try to submit the form.

## Possible Solution
No idea at the moment how to resolve - there's no js console error message and no other debug messages I can see.

## WordPress Environment
<details>
```WordPress Version: 4.9.6

PHP Version: 7.0.30-1+ubuntu14.04.1+deb.sury.org+1

MySQL Version: 5.6.36

Server Software: nginx/1.12.1

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: No
WPDB Prefix: b4kids_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/s948/html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: f2f 2017 Child Theme

Currently Active Plugins:

Admin Columns: 3.1.10
Advanced Custom Fields: 4.4.12
Breadcrumb Trail: 1.1.0
Bulk Term Generator: 1.3.0
CMS Tree Page View: 1.5
Contact Form 7: 5.0.2
Contact Form 7 Honeypot: 1.13
Custom Content Shortcode: 3.7.0
Custom Field Suite: 2.5.12
Duplicator: 1.2.38
Event Organiser: 3.7.0
FacetWP: 3.1.7
Filters: 0.3
Get Slug: 1.0.0
Helpful Information: 1.0.2
iThemes Sync: 2.0.9
Members: 2.1.0
More File Formats: 0.1
Nested Pages: 3.0.2
Optimize Database after Deleting Revisions: 4.6
Outerbridge Nested Shortcodes: 1.3
Plainview Activity Monitor: 20161228
Pods - Custom Content Types and Fields: 2.7.3
Query Monitor: 3.0.1
Regenerate Thumbnails: 3.0.2
Rewrite Rules Inspector: 1.2.1
Search & Filter: 1.2.9
SearchWP: 2.9.13
SearchWP Live Ajax Search: 1.3.1
SearchWP Shortcodes: 1.5.4
Simply Show IDs: 1.3.3
Slideshow: 2.3.1
TablePress: 1.9
User Switching: 1.3.1
Velvet Blues Update URLs: 3.2.8
WordPress Importer: 0.6.4
WP Cerber Security & Antispam: 6.7.5```
</details>

## Pods Package Export (helpful!)
```
{"meta":{"version":"2.7.3","build":1527710528},"pods":{"3462":{"id":3462,"name":"county","label":"Counties","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"County","public":"1","show_ui":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"custom","capability_type_custom":"county","query_var":"1","sort":"0","built_in_post_types_acf":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_event":"1","built_in_post_types_family_voice":"1","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"1","built_in_post_types_post":"1","built_in_post_types_slideshow":"0","built_in_post_types_wpcf7_contact_form":"0","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_resource":"1","built_in_post_types_organization":"1","built_in_post_types_cfs":"0","built_in_post_types_np-redirect":"0","built_in_post_types_fln_contact":"0"},"1684":{"id":1684,"name":"family_voice","label":"Family Stories","description":"","type":"post_type","storage":"table","object":"","alias":"","fields":{"fv_first_name":{"id":1685,"name":"fv_first_name","label":"First Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","pick_post_status":["publish"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_placeholder":""},"fv_last_name":{"id":1686,"name":"fv_last_name","label":"Last Name","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","pick_post_status":["publish"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_placeholder":""},"fv_email":{"id":1687,"name":"fv_email","label":"Email","description":"","help":"","class":"","type":"email","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","email_max_length":"512","email_html5":"1","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"email_repeatable":"0","pick_post_status":["publish"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","email_placeholder":""},"fv_address":{"id":1688,"name":"fv_address","label":"Address","description":"","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"500","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"fv_city":{"id":1689,"name":"fv_city","label":"City","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"fv_zip":{"id":1690,"name":"fv_zip","label":"ZIP","description":"","help":"","class":"","type":"number","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"9999.99","number_decimals":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"5","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_format_soft":"0","number_placeholder":""},"fv_phone":{"id":1693,"name":"fv_phone","label":"Phone","description":"","help":"","class":"","type":"phone","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","phone_format":"999-999-9999 x999","phone_enable_phone_extension":"0","phone_max_length":"25","phone_html5":"1","pick_allow_html":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"phone_repeatable":"0","pick_post_status":["publish"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","phone_placeholder":""},"fv_your_story":{"id":1691,"name":"fv_your_story","label":"Your Story","description":"","help":"","class":"","type":"paragraph","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","paragraph_allow_html":"0","paragraph_oembed":"0","paragraph_wptexturize":"0","paragraph_convert_chars":"0","paragraph_wpautop":"0","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"paragraph_repeatable":"0","paragraph_max_length":"0","pick_post_status":["publish"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","paragraph_placeholder":""},"fv_picture_to_share":{"id":3759,"name":"fv_picture_to_share","label":"Picture to Share","description":"Do you have a picture to share? If yes, we will contact you to arrange image transfer.","help":"","class":"","type":"pick","weight":8,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_custom":"Yes\nNo","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"fv_privacy_options":{"id":1692,"name":"fv_privacy_options","label":"Publishing Options","description":"Please let us know if we can directly publish your story or if you would like us to contact you first.","help":"","class":"","type":"pick","weight":9,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"Contact me before publishing story\nGo ahead and share my story","required":"1","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_limit":"0","pick_user_role":[],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_taggable":"0","pick_allow_html":"0","pick_allow_add_new":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_post_status":[],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"fv_picture":{"id":3762,"name":"fv_picture","label":"Picture (300 px by 300 px square)","description":"Associated picture","help":"","class":"","type":"file","weight":10,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","unique":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"Family Story","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"family_voice","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","menu_name":"Family Stories","built_in_taxonomies_item_category":"1","built_in_taxonomies_county":"1","built_in_taxonomies_event-category":"0","built_in_taxonomies_event-tag":"0","built_in_taxonomies_event-venue":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Family Voices Story First Name Only","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-megaphone"},"3461":{"id":3461,"name":"item_category","label":"Item Categories","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Item Category","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"item_category","query_var":"1","sort":"0","built_in_post_types_acf":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_event":"1","built_in_post_types_family_voice":"1","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"1","built_in_post_types_post":"1","built_in_post_types_slideshow":"0","built_in_post_types_wpcf7_contact_form":"0","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_resource":"1","built_in_post_types_organization":"1","built_in_post_types_cfs":"0","built_in_post_types_np-redirect":"0","built_in_post_types_fln_contact":"0"},"3821":{"id":3821,"name":"organization","label":"Organizations","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Organization","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"organization","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"1","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_county":"1","built_in_taxonomies_event-category":"0","built_in_taxonomies_event-tag":"0","built_in_taxonomies_event-venue":"0","built_in_taxonomies_item_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Family Voices Story First Name Only","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-admin-multisite"},"3808":{"id":3808,"name":"resource","label":"Resources","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Resource","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"resource","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"1","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_county":"1","built_in_taxonomies_event-category":"0","built_in_taxonomies_event-tag":"0","built_in_taxonomies_event-venue":"0","built_in_taxonomies_item_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","menu_icon":"dashicons-portfolio","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Family Voices Story First Name Only","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}},"templates":{"Family Voices Story First Name Only":{"id":15,"name":"Family Voices Story First Name Only","code":"<div class=\"family-story {@post_name}\">\r\n\t[if fv_picture]\r\n\t<img src=\"{@fv_picture._src.large}\" alt=\"\" \/>\r\n\t[else]\r\n\t[\/if]\r\n\t<p>{@fv_your_story}<\/p>\r\n\t<p>{@fv_first_name}<\/p>  \r\n<\/div>","type":"template","slug":"family_voices_story_first_name_only","options":{"_edit_lock":"1523655857:1","_edit_last":"1","type":"template","slug":"family-voices-story-first-name-only","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}","admin_only":"","restrict_capability":"","capability_allowed":""}},"Family Voices Story":{"id":16,"name":"Family Voices Story","code":"<div class=\"family-story {@post_name}\">\r\n\t[if fv_picture]\r\n\t<img src=\"{@fv_picture._src.large}\" alt=\"\" \/>\r\n\t[else]\r\n\t[\/if]\r\n\t{@fv_your_story}\r\n<\/div>","type":"template","slug":"family_voices_story","options":{"_edit_lock":"1523649147:1","_edit_last":"1","type":"template","slug":"family-voices-story-2","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}"}},"View All Family Voices":{"id":17,"name":"View All Family Voices","code":"[before]<ul class=\"family-voices-grid-view\">[\/before]\r\n<li class=\"family-voices family-voices-item {@post_name}\">\r\n    <a class=\"fv-display-container\" href=\"{@permalink}\">\r\n\t\t[if fv_picture]\r\n\t\t\t<img class=\"fv-display-bg\" src=\"{@fv_picture._src.large}\" alt=\"\" \/>\r\n\t\t[else]\r\n\t\t\t<img class=\"fv-display-bg\" src=\"https:\/\/f2fmichigan-staging.cyuytk3-liquidwebsites.com\/wp-content\/uploads\/2018\/05\/family-stories.jpg\" alt=\"\" \/>\r\n\t\t[\/if]\r\n\t\t<span class=\"fv-display-title\">{@post_title}<\/span>\r\n\t<\/a>\r\n<\/li>\r\n[after]<\/ul>[\/after]\t","type":"template","slug":"view_all_family_voices","options":{"_edit_lock":"1526050127:1","_edit_last":"1","type":"template","slug":"view-all-family-voices","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:12:\"family_voice\";}"}},"Family Voices Story Show All":{"id":18,"name":"Family Voices Story Show All","code":"<div class=\"family-story {@post_name}\">\r\n\t[if fv_picture]\r\n\t<img src=\"{@fv_picture._src.large}\" alt=\"\" \/>\r\n\t[else]\r\n\t[\/if]\r\n\t<p>{@fv_your_story}<\/p>\r\n    <p>{@fv_first_name} {@fv_last_name}<br \/>\r\n    {@fv_address}<br \/>\r\n\t{@fv_city}, {@fv_zip}<\/p>  \r\n<\/div>","type":"template","slug":"family_voices_story_show_all","options":{"_edit_last":"1","_edit_lock":"1524494968:1","type":"template","slug":"family-voices-story","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:12:\"family_voice\";}"}},"County Archive View":{"id":3888,"name":"County Archive View","code":"[if county]\r\n<ul>\r\n[each county]\r\n\t<li>\r\n\t\t<a href=\"{@slug}\">{@name}<\/a>\r\n\t<\/li>\r\n[\/each]\r\n<\/ul>\r\n[\/if]","type":"template","slug":"county-archive-view","options":{"_edit_lock":"1524772015:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:6:\"county\";}"}}}}
```

## Workaround or Alternate Solution Until Bug is Addressed
Switch select fields to not be required and visually fake it being required via CSS

## Related Issues and/or PRs
Not known at this time.

**Comment by bemdesign-er** [comment]
Another workaround/solution I just found: Instead of using the select UI controls, using the radio button UI controls allows the form to be validated and submitted correctly.

**Comment by bemdesign-er** [comment]
**Update**:  I had to switch to the radio button UI on the staging site temporarily but it's back to using select dropdowns UI currently so Pods developers can see the issue first-hand.

**Comment by bemdesign-er** [comment]
Oh that is a clue! I think I have some javascript in my child theme that tweaks the labels and the names attributes on the select fields so the error validation messages are more user friendly for those controls (using the label text, and not the programatic name). Hmmm...

**Comment by bemdesign-er** [comment]
The issue was indeed caused by some custom javascript from the child theme. We can close this one out then. 

Future enhancement suggestion: customization of field's validation error messages. It would be nice to be able to customize error messages on a per-field basis.

**Comment by bemdesign-er** [comment]
Closing out as issue was caused by custom javascript on the theme's end and was not an issue with Pods.

**Comment by pglewis** [comment]
> Future enhancement suggestion: customization of field's validation error messages. It would be nice to be able to customize error messages on a per-field basis.

If you would, make up a new issue for that request.  One issue per ticket helps us keep things straight.
