### ISSUE TITLE
Export process failed

### ISSUE THREAD

**Issue by elia-senatore-cippest** [pods-framework/pods#4970]
https://github.com/pods-framework/pods/blob/ae9f431aec0419a940c7a8701efb7dc26d198c6d/classes/PodsMigrate.php#L798

The export process fails cause wrong check of $uploads['error'] that in normal way is false.

The line fix could be: if ( ! $uploads || false !== $uploads['error'] )

**Comment by sc0ttkclark** [comment]
Thanks so much for doing the leg work here, I was able to simply confirm your suspicion and make a PR within two minutes!
