### ISSUE TITLE
PHPCS: Use interpolation for dynamic hook names

### ISSUE THREAD

**Issue by GaryJones** [pods-framework/pods#4992]
## Issue Overview
The [coding standards says](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#interpolation-for-naming-dynamic-hooks):

> Dynamic hooks should be named using interpolation rather than concatenation for readability and discoverability purposes.

Among other reasons, it allows WP-Parser and other documentation extraction tools to more easily read the whole double-quoted first arg string, instead of the tokens in the first arg up to the first comma.

## Expected Behavior
A dynamic hook name like:

```php
apply_filters( 'pods_pods_field_' . $this->fields[ $params->name ]['type'], ... );
```

_could_ be updated to be:

```php
apply_filters( "pods_pods_field_{$this->fields[ $params->name ]['type']}", ... );
```

and _should_ be updated to be:

```php
$field_type = $this->fields[ $params->name ]['type'];
apply_filters( "pods_pods_field_{$field_type}", ... );
```

## Current Behavior
A quick regex search with `~apply_filters\([^,]*\..*,~` and `~do_action\([^,]*\..*,~` suggests there are at least 98 instances of concatenation (plus any `*_ref_array()` and `*_deprecated()` variations).

There are some filter and action hooks which are already named with interpolation, so this isn't a new concept the Pods codebase.

## Possible Solution
Update filter and action hook names where necessary. This doesn't affect the PHP runtime behaviour.

Note that it's [not yet possible](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/751) to use WPCS to detect the instances that would need changing.

**Comment by pglewis** [comment]
PR: #5011
