### ISSUE TITLE
Export all button for ACTs: the link is broken

### ISSUE THREAD

**Issue by elia-senatore-cippest** [pods-framework/pods#5005]
**Description**
When enabled in pods settings, the "Export all" functionality does not work as expected.

**To Reproduce**
Click on button "Export all", nothing happens. From browser console the following error message is displayed: SyntaxError: '' string literal contains an unescaped line break

**Possible Workaround**
in /classes/PodsUI.php at line 3139, remove after document.location=' the semicolon and the line break, and at the end after the closing tag ?> remove the line break.

## WordPress Environment

<details>
```
WordPress Version: 4.9.6

PHP Version: 7.0.3

MySQL Version: 5.7.11

Server Software: Apache/2.4.18 (Win32) OpenSSL/1.0.2f PHP/7.0.3

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

Session Save Path: N;C:/UwAmp/bin/apache/sessions

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: sms_

WP Multisite Mode: No

WP Memory Limit: 1024M

Pods Network-Wide Activated: No

Pods Install Location: C:\UwAmp\www\wp\wp-content\plugins\pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Divi
```
</details>

**Comment by pglewis** [comment]
It should be noted that this is specific to ACTs and requires Admin UI -> Actions Available -> Export to be checked for the Pod itself.   The Export all button will then show up near bulk actions in the post list for the ACT.

**Comment by pglewis** [comment]
PR: #5034
