### ISSUE TITLE
Ability to make fields required on front-end forms but optional on backend

### ISSUE THREAD

**Issue by bemdesign-er** [pods-framework/pods#5010]
**Describe the solution you'd like**
I'm thinking of a front-end form that creates a custom post type item on submission - it would be nice to have fields that are only required on the front-end form and not on the actual backend post editor.

_Example_: An event booking form where you want to capture certain details from the submitter (name, contact info) that may not be as useful if the event booking item is created by an admin from the backend (i.e. they don't need that information as it was created by a known user in the system).

_Possible Solution_: Have an option (checkbox?) after the required checkbox to make the field required only from front end forms.

**Describe alternatives you've considered**
Not sure yet. Maybe have a way to make a required field only available via the roles module? (i.e. only show required field if user has no role/unauthenticated).

**Additional context**

**Comment by jimtrue** [comment]
Remember, we're not a forms engine. The actions that are available on the back-end is what is available on the front-end. If you'd like something 'different' on the front-end, that probably needs to come from a form engine that submits to a custom post type.

**Comment by bemdesign-er** [comment]
I still think it would be a nice feature to have in Pods - a way to configure when/where a field is required depending on the form state or even the user role.

But yeah, I can see how my example would be a better fit for a forms engine.

**Comment by jimtrue** [comment]
You can configure based on user role under the Advanced Options, Visibility. But most of this kind of stuff will be configurable when conditional field groups are added. At that point, you would be able to add a class or something that would make the block or field not show on the front-end (and thus not be required). If the field doesn't show, it can't be required.

You're welcome to add your ideas to #609 but I'll be closing this one.
