### ISSUE TITLE
REST API POST Multiple Files Fields not working with array

### ISSUE THREAD

**Issue by eljuani** [pods-framework/pods#5013]
Can't create Multiple Files field through REST API, it just works for a single value, not an array
Im using the rest api to update, via POST (and using Postman), a multiple file upload field in a custom post type I created. If I include just one file it works, like this:
{
   "pdf":
       {    
           "post_content": "blablalbla",
           "post_title": "Bla1",
           "post_name": "Bla1" ,
           "guid": "http://bla.local/wp-content/uploads/2018/06/bla.pdf",
           "post_type": "attachment",
           "post_mime_type": "application/pdf"    
       }
}
But if i use and array, it doesn't work:
{
   "pdf":  [
       {    
           "post_content": "blablalbla",
           "post_title": "Bla1",
           "post_name": "Bla1" ,
           "guid": "http://bla.local/wp-content/uploads/2018/06/bla.pdf",
           "post_type": "attachment",
           "post_mime_type": "application/pdf"    
       },
       {    
           "post_content": "blablalbla",
           "post_title": "Bla2",
           "post_name": "Bla2" ,
           "guid": "http://bla.local/wp-content/uploads/2018/06/bla2.pdf",
           "post_type": "attachment",
           "post_mime_type": "application/pdf"    
       }
    ]
}

## WordPress Environment
Debug Information
WordPress Version: 4.9.6

PHP Version: 5.6.20

MySQL Version: 5.5.55

Server Software: Apache/2.4.10 (Debian)

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

BSK PDF Manager: 1.8.1
Client Portal: 1.0.4
JSON Basic Authentication: 0.1
Pods - Custom Content Types and Fields: 2.7.5
Profile Builder: 2.8.3
```
</details>

**Comment by eljuani** [comment]
Solved the problema, it was related to Postman, I can post arrays succesfully with Form Data. 
BUT the problem of not being able to update the post_title persists. Should I open another BUG ?

**Comment by GaryJones** [comment]
Glad you got it sorted :-)

> BUT the problem of not being able to update the post_title persists. Should I open another BUG ?

If you can offer a targeted bug report just related to the post_title issue, then yes please :-)
