### ISSUE TITLE
Broken: Add New doesn't 'SELECT' record or refresh list view in 2.7.5

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5014]
**Describe the bug**
Reported from: https://pods.io/forums/topic/2-7-5-not-linking-relationship-field/#post-198847

List View, Add New creates supplementary record, but the record created isn't selected and doesn't refresh List View so record isn't 'added' to Relationship. Refreshing the post will allow selection, but obviously this isn't ideal.

**To Reproduce**
1. Go to any existing Relationship List View in 2.7.5
2. Add New and Save Child Record
3. Modal Closes, but record is not selected and is not listed in List View
4. Refresh screen, record can be selected.

**Expected behavior**
This should work the way it used to ;)

**Screenshots**

**Comment by pglewis** [comment]
Appears to have been introduced in 2.7.4, off to find out exactly where.

**Comment by pglewis** [comment]
Preliminary, but I believe the winner is: 6f15f04

**Comment by pglewis** [comment]
PR: #5017
