### ISSUE TITLE
Pods Template Editor is adding two 'tabs' to the front of the template during Save.

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5022]
**Describe the bug**
When you open or Save the Pods Template the editor is pre-pending 2 tabs to the front of the Template. If you save multiple times, you will prepend two tabs with every save.

**To Reproduce**
1. Go into the Pods Template editor (a new one is fine)
2. You will notice two blank tabs at the beginning of the editor.
3. Hit Save multiple times; two tabs will be prepended to the front of the template with each save.

**Expected behavior**
The editor should be empty when first opened and should not prepend empty tabs to the contents of the editor.

**Comment by jimtrue** [comment]
Verified fixed from my end. What's the final status @pglewis ?

**Comment by pglewis** [comment]
Fixed/Needs Testing has typically been the final status in the past.

**Comment by jimtrue** [comment]
Ah I was looking for `Ready for Merge`

**Comment by jimtrue** [comment]
Duh, those are for PR's, not for the issues.
