### ISSUE TITLE
pod edit issue

### ISSUE THREAD

**Issue by Ulminia** [pods-framework/pods#5043]
## Issue Overview
pod apt cannot enable edit access for users

## Expected Behavior
user creates a post and is redirected to the post to edit like normal wordpress behaviour

## Current Behavior
all conditions in function restricted( $action = 'edit', $row = null ) make it so if a user has edit permissions but not edit others they cannot edit
as denoted by } elseif ( current_user_can( 'pods_' . $action . '_' . $this->pod->pod ) && current_user_can( 'pods_' . $action . '_others_' . $this->pod->pod ) ) {
also all other checks fail id $row is empty...

## Steps to Reproduce (for bugs)
create acpt 
add users 
add users create edit and delete there own pod type not others
edit fails after creating a post for acpt

## Possible Solution
add
} elseif ( current_user_can( 'pods_' . $action . '_' . $this->pod->pod ) ) {
$restricted = false;
}
## WordPress Environment
Debug Information
<details>
WordPress Version: 4.9.6

PHP Version: 7.0.30-1+ubuntu14.04.1+deb.sury.org+1

MySQL Version: 5.6.40

Server Software: nginx/1.12.1

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 128M

Pods Network-Wide Activated: No

Pods Install Location: /home/s4/html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Intuition

Currently Active Plugins:

Advanced Custom Fields Multilingual: 0.7
BackUpWordPress: 3.6.4
BackWPup: 3.6.0
Black Studio TinyMCE Widget: 2.6.2
CPO Content Types: 1.1.0
Database Browser: 1.4
Display PHP Version: 1.4
Events Manager: 5.9.4
Events Manager and WPML Compatibility: 1.2
Exports and Reports: 0.7.4
Export User Data: 1.3.1
Gravity Forms: 2.3.2
Gravity Forms Multilingual: 1.3.17
Gravity Forms User Registration Add-On: 3.9
Loco Translate: 2.1.4
Menu Image: 2.9.1
Page Links To: 2.11.1
PHP code snippets (Insert PHP): 2.0.4
Pods - Custom Content Types and Fields: 2.7.6
Real-Time Find and Replace: 3.9
s2Member Framework: 170722
Shareaholic | share buttons, analytics, related posts: 8.7.2
SiteOrigin Widgets Bundle: 1.11.8
Username Changer: 3.1.3
Wordfence Security: 7.1.7
WPBakery Page Builder: 5.4.7
WP Clips: 2.1.1
WP Downgrade | Specific Core Version: 1.1.4
WP Edit: 4.0.3
WPML All Import: 2.0.5
WPML CMS Nav: 1.4.23
WPML Media: 2.3.3
WPML Multilingual CMS: 4.0.3
WPML Sticky Links: 1.4.4
WPML String Translation: 2.8.3
WPML Translation Management: 2.6.3
WPML XLIFF: 0.9.1
Yoast SEO: 7.6.1
</details>

## Workaround or Alternate Solution Until Bug is Addressed
add this
		$pod_author = $this->get_field( 'author' );
		if ($pod_author['ID'] == get_current_user_id())
		{
			$restricted = false;
		}
to line 5119

**Comment by sc0ttkclark** [comment]
Good find and excellent leg work! This will make solving so much easier. I agree, that probably should be an || and not an && for that capability check.

**Comment by pglewis** [comment]
PR: #5044

**Comment by pglewis** [comment]
This should be fixed in 2.x and will go out with 2.7.7
