### ISSUE TITLE
Add missing documentation for action and filter hooks

### ISSUE THREAD

**Issue by GaryJones** [pods-framework/pods#5045]
## Is your feature request related to a problem? Please describe.

Some hooks are not documented, which means any efforts to extract this documentation into an external resource will be missing information. Developers who look through the source code would also be better informed if the documentation was present. See #2480, for example.

## Describe the solution you'd like

All hooks documented, as per https://pods.io/inline-documentation-filters-actions/, which essentially says to follow the [WP core way of documenting hooks](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters).

Doing this by directory and type seems like a manageable way to break it down. There are no `do_action_ref_array()` or `apply_filters_ref_array()` calls currently being used.

The counts below indicate the **total** number of the respective calls - not how many may or may not be documented - each will need checking and potentially updating individually.

### `do_action()`

- [ ] `/classes/` (71)
- [ ] `/components/` (8)
- [ ] `/deprecated/` (2)
- [ ] `/includes/` (1)
- [ ] `/sql/` (4)
- [ ] `/ui/` (20)

### `apply_filters()`

- [ ] `/classes/` (root files) (200)
- [ ] `/classes/fields/` (78)
- [ ] `/classes/widgets/` (5)
- [ ] `/components/` (50)
- [ ] `/deprecated/` (9)
- [ ] `/includes/` (38)
- [ ] `/sql/` (7)
- [ ] `/ui/` (28)

**Comment by quasel** [comment]
Did you count in the do_hook() Stuff as apply_filters()?

**Comment by GaryJones** [comment]
> Did you count in the do_hook() calls as apply_filters()?

No, I just searched for the exact `apply_filters(` string. 

I believe I saw a different ticket already open for converting `do_hook()` to standard WP hook calls. There appears to be 103 of them throughout the source code, so I was ignoring them for this ticket. They should obviously be documented when they are converted.
