### ISSUE TITLE
Empty comment box on page for approved comment

### ISSUE THREAD

**Issue by David240** [pods-framework/pods#5052]
## Issue Overview

I created a new custom post type to provide a second posts page, independent of the default wp posts page. A couple of posts of the new type were published and could be read without difficulty on the new page.
A logged in user left a comment on the new page. [As a side comment, I don't see that there's any way to have comments on individual posts of the new type.] The comment has been approved by admin.
The problem is that on the page, we [admins] can see the normal metadata introducing the comment, but the comment box itself is blank. We can only see the text of the comment by [as admin] editing the comment. The screenshot shows what we see.
![screenshot_20180630-201409](https://user-images.githubusercontent.com/14995618/42128397-42792354-7ca2-11e8-988d-ed8e6fd26949.png)

Here is what the Dashboard's Comment list says:

From Fraser on Adoption Links

    What a great website! Goes perfectly with the book. I love it.

## Expected Behavior

Expect to see the text of the comment.

 

## Current Behavior

Comment body box is empty on the page.

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

WordPress 4.9.6 running _tk Child theme.
Pods plugin 2.6.7
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
Debug Information

WordPress Version: 4.9.6

PHP Version: 5.6.36

MySQL Version: 5.6.39

Server Software: Apache

Your User Agent: Mozilla/5.0 (Android 7.0; Tablet; rv:61.0) Gecko/61.0 Firefox/61.0

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: No
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wpyh_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/freedomw/juliewetherby.com/wp/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: _tk Child

Currently Active Plugins:

    Activity Log: 2.4.1
    Amazon Link: 3.2.8
    Change Case: 2.0.3
    Cookie Consent: 2.3.10
    Credit Tracker: 1.1.12
    Custom Twitter Feeds: 1.2.9
    Footer Text: 2.0.2
    MailChimp: 1.5.7
    Pods - Custom Content Types and Fields: 2.7.6
    reGenerate Thumbnails - advanced: 1.6.3.1
    Sassy Social Share: 3.2.1
    TinyMCE Annotate: 1.1.2
    TinyMCE Custom Styles: 1.0.9
    tinyWYM Editor: 1.4.1
    TK Google Fonts: 2.0.2
    Under Construction: 3.05
    Widgets On Pages: 1.4.0
</details>

## Pods Package Export (helpful!)

{"meta":{"version":"2.7.6","build":1530386892},"pods":{"652":{"id":652,"name":"adoption_link","label":"Adoption Links","description":"Adoption Link article","type":"post_type","storage":"meta","object":"","alias":"","fields":{"adoption_link_quotation":{"id":654,"name":"adoption_link_quotation","label":"Adoption Link Quotation","description":"A headline quotation from linked material, if there is one.","help":"","class":"blockquote","type":"paragraph","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","paragraph_allow_html":"1","paragraph_oembed":"1","paragraph_wptexturize":"1","paragraph_convert_chars":"1","paragraph_wpautop":"1","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"i","paragraph_max_length":"0","paragraph_placeholder":"Text with no surrounding quote marks","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","paragraph_repeatable":"0"},"quotation_originator":{"id":655,"name":"quotation_originator","label":"Quotation originator","description":"Original source of Adoption Link Quotation, if there is one.","help":"","class":".book_chapter","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":"Quotation originator","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0"},"quotation_source":{"id":656,"name":"quotation_source","label":"Quotation Source","description":"Source material of Article Link quotation, if there is one..","help":"","class":".chapter_name","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"linked_article_title":{"id":657,"name":"linked_article_title","label":"Linked article title","description":"Title of linked article.","help":"","class":".chater_name","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"linked_article_text_or_extract":{"id":658,"name":"linked_article_text_or_extract","label":"Linked article text or extract","description":"","help":"","class":"","type":"paragraph","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","paragraph_allow_html":"1","paragraph_oembed":"0","paragraph_wptexturize":"1","paragraph_convert_chars":"1","paragraph_wpautop":"1","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","paragraph_max_length":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","paragraph_repeatable":"0","paragraph_placeholder":""},"article_link":{"id":659,"name":"article_link","label":"Article Link","description":"URL (web address) of linked article","help":"","class":"","type":"website","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"no-http-force-www","website_allow_port":"0","website_clickable":"1","website_new_window":"1","website_max_length":"255","website_html5":"0","website_placeholder":"e.g., example.com\/this-section\/this-page (If omitted, www will be added at front)","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0"}},"show_in_menu":"1","label_singular":"Adoption Link","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"adoption_link","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"1","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_single":"Writing","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_archive":"Writing","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","label_edit_item":"Edit"}},"templates":{"Writing":{"id":622,"name":"Writing","code":"<p>{@post_title}<\/p>\r\n<p>{@post_content}<\/p>\r\n<p>Category: {@category} Post tag: {@tag}<\/p>\r\n\r\n","type":"template","slug":"writing","options":{"_edit_lock":"1516894005:2","_edit_last":"2","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}"}}}}

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by jimtrue** [comment]
@David240 Have you checked this in a default theme? Comments display on the front-end is typically managed by your theme and comments.php

Comments support for Post Types is enabled under the Edit Pods screen, Advanced Options, Supports (down at the bottom). You also have to check your Screen Options when you're editing a post to make sure the 'Comments' or 'Discussions' options are showing.

**Comment by David240** [comment]
Thanks for your attention and for your useful advice that the displaying of page comments is outside the scope of Pods itself. 

After I got more time to look at it, my  problem turned out to be my own fault and is now resolved, so this issue should be closed in an appropriate way - not sure how that works...
