### ISSUE TITLE
Gutenberg 3.3.1 conflict: TypeError: CodeMirror.modes[mode] is undefined (loadmode.js:20:9)

### ISSUE THREAD

**Issue by lkraav** [pods-framework/pods#5054]
**Describe the bug**

**To Reproduce**
1. Extend post type
2. Add a Pods Code field
3. Open Gutenberg editor for a post in the extended post type above

**Expected behavior**
* No JS errors

**Screenshots**

## Pods Version
2.7.6

## WordPress Environment
4.9.6

## Pods Package Export (helpful!)
N/A

**Additional context**
Seems like an obvious CodeMirror instances conflict.

**Possible Workaround**
N/A

EDIT removed "Gutenberg HTML block not working" part, this was caused by something else.

**Comment by quasel** [comment]
works for me in the most recent Gutenberg Update 3.6.2

feel free to comment again it the issue still affects you!

**Comment by lkraav** [comment]
Yep, it's highly likely this issue has self-healed over time. I've not encountered crashes in the recent months.

**Comment by quasel** [comment]
Thanks for confirming!
