### ISSUE TITLE
FacetWP Filter Support in Pods

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5055]
**Is your feature request related to a problem? Please describe.**
Yes, and No. Built-in support for Pods Relationships doesn't exist in FacetWP, though FacetWP has written in support for post-type relationship support. 

FacetWP Support responded in this way:

> A relationship field in PODS will probably needs some custom code to index correctly.

>Here is a basic example of a using a relationship >[Gist Link](https://gist.github.com/djrmom/dda751819dc238a51a484bea4ba74240)

>I think for pods you may need

>`$related_post_id = $params[‘facet_value’][‘ID’];`

**Describe the solution you'd like**
Let's see if we can get this filter working!

**Comment by kpstraus** [comment]
New response from FacetWP.  Doesn't work (when added to functions.php).  Does anyone know how pods relationship fields save data -- and thus how to fix line 3?

<pre>add_filter( 'facetwp_index_row', function( $params, $class ) {
	if ( 'subject' == $params['facet_name'] ) { // change my_facet to name of your facet
		$related_post_id = $params['facet_value']['ID']; // depnding on how your relationship field saves its data this might need to be changed or looked up from a different value
		$params['facet_display_value'] = get_the_title( $related_post_id ); // lookup custom field 
		$params['facet_value'] = $params['facet_display_value'];
	}
	return $params;
}, 10, 2 );</pre>

**Comment by nicdford** [comment]
I was able to get it working using: https://gist.github.com/djrmom/dda751819dc238a51a484bea4ba74240

**Comment by nicdford** [comment]
I did some basic testing and this seems to be working 100% of the time. Works with bi-directional, single, and multi-select field options. I would think that would be the majority of the use-cases I can think of.

**Comment by jimtrue** [comment]
Now we just need this to be included in FacetWP documentation/code. @sc0ttkclark is this something you can push Matt to add?

**Comment by kpstraus** [comment]
Jenny Ragan (FacetWP) said "I added a gist specifically for it and it will get imported into our code snippet's soon https://gist.facetwp.com/"

Thanks

**Comment by jimtrue** [comment]
Here's the additions directly from the Gist from @kpstraus 

> This works for my Pods relationship field!
```
add_filter( 'facetwp_index_row', function( $params, $class ) {
if ( 'subject' == $params['facet_name'] ) { // change 'subject' to name of your facet
    $related_post_id = $params['facet_value']['ID']; 
    $params['facet_display_value'] = get_the_title( $related_post_id ); // lookup custom field 
    $params['facet_value'] = $params['facet_display_value'];
  }
  return $params;
}, 10, 2 );
```

> If more than one Pods relationship field:
```
if ( 'subject' == $params['facet_name'] || 'otherfacet' == $params['facet_name'] ) { 
```
> Or, make an array:
```
$fields = array( 'subject', 'another_facet', 'some_other_facet' );
if ( in_array( $params['facet_name'] , $fields ) ) {
```
> Replace 'subject', 'otherfacet' and 'some_other_facet' with your own facet names.

**Comment by JoryHogeveen** [comment]
This is directly related to https://github.com/pods-framework/pods/issues/3614 since Pods doesn't return the actual meta value but parses it first and return the object vars as an array.

The change will work but imo Pods is using `get_post_meta()` incorrect from 2.x or before.

**Comment by jimtrue** [comment]
In discussion with #3614, what would break if we didn't do what we're currently doing with get_post_meta with media and relationship fields? (Ie if the filtering wasn't done or if there was a specific config to force the filtering not to happen)?

**Comment by nicdford** [comment]
Seems to me that get_post_meta should return the same values as the core WP expected result when used on a custom post type and anyone who wanted to gain access to the nested array values would just have to use `pods()`... is that the essence of the problem?

**Comment by pglewis** [comment]
> Seems to me that get_post_meta should return the same values as the core WP expected result when used on a custom post type item

I agree, if this is not already the case.  Sounds like I need to roll up the sleeves and dig in to this.  

Only tangentially related, but another inconsistency with `get_meta()` possibly still around since the dawn of time, #1484

**Comment by sc0ttkclark** [comment]
There's now an official add-on that we've collaborated with FacetWP on:
https://github.com/FacetWP/facetwp-pods

It covers relationship fields and all other pod fields :)
