### ISSUE TITLE
Pods + GraphQL: Inconsistent field type error

### ISSUE THREAD

**Issue by lesliecdubs** [pods-framework/pods#5059]
## Issue Overview
When querying Pods data with GraphQL, inconsistent field types are returned when an object field is left empty and the build fails.

## Expected Behavior
Need the ability to either 
1) standardize field types so object fields consistently return empty objects instead of boolean values, or
2) customize the default value of a field so we can force the field type to be consistent

## Current Behavior
We have a custom post type set up in our WP admin Pods called "Heroes." This post type contains two fields, both of the field type `File / Image / Video`: a required image field and an optional video field.

When querying this data with GraphQL (in our case, using GatsbyJS), we get the following error when the optional "video" field is empty: 

```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
wordpress__wp_hero.video:
 - type: boolean
   value: false
 - type: object
   value: { wordpress_id: '274', post_author: '1', post_date: '2018-07-06 15:26:22', post_date_gmt: '2018-07-06 15:26:22', post_content: '', post_title: 'SampleVideo_1280x720_1mb-converted-with-Clipchamp', post_excerpt: '', post_status: 'inherit', comment_status: 'closed', ping_status: 'closed', post_password: '', post_name: 'samplevideo_1280x720_1mb-converted-with-clipchamp-4', to_ping: '', pinged: '', post_modified: '2018-07-06 15:26:24', post_modified_gmt: '2018-07-06 15:26:24', post_content_filtered: '', post_parent: '171', menu_order: '0', post_type: 'attachment', post_mime_type: 'video/mp4', comment_count: '0', pod_item_id: '274', guid___NODE: 'b3056e40-4ed1-5f1a-9578-6a5bf8cb54b3' }

GraphQL Error Field "video" must not have a selection since type "Boolean" has no subfields.
```

Our query looks like this, and it fails on `video` since it's returning the boolean value `false` instead of an empty object:

```
fragment ProjectTypeFragment on wordpress__wp_project_type {
   title
   description
   hero {
      video {
         guid {
            alt_text
            source_url
         }
      }
   }
}
```

## Possible Solution
In the Pods admin for the `video` field, I tried adding an empty object value (`{}`) in the Advanced > Default Value field, but this didn't change the behavior.

Perhaps make it possible to set the default field type here?

## WordPress Environment
```
WordPress Version: 4.9.7

PHP Version: 7.0.30

MySQL Version: 5.5.5

Server Software: nginx

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: No
Redis: No
WPDB Prefix: wp_147769543_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: /wpcom-147769543/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Dara

Currently Active Plugins:

ACF to REST API: 3.1.0
Adminimize: 1.11.4
Advanced Custom Fields: 4.4.12
Advanced TinyMCE Configuration: 1.3
Akismet Anti-Spam: 4.0.8
AMP: 0.7.2
Disable Blog: 0.4.3
Disable Comments: 1.7.1
Google Analytics Dashboard for WP (GADWP): 5.3.5
Jetpack by WordPress.com: 6.3.2
My Custom Functions: 4.22
Pods - Custom Content Types and Fields: 2.7.6
TinyMCE Advanced: 4.7.11
User Role Editor: 4.44
```

## Workaround or Alternate Solution Until Bug is Addressed
None yet

**Comment by quasel** [comment]
What/How do you query pods to create the result set? As it's a pick field there is no "empty" default it's either set or not ;) - but you could filter the return depending on the way how you access the pods data! 

Or maybe there is a filter in you GraphQL plugin to deal with "default" values!

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!

**Comment by lesliecdubs** [comment]
Apologies for the late reply - deadlines have had me laser-focused on writing code!

We are using GraphQL inside GatsbyJS to query the result set. Ultimately we ended up using a Gatsby plugin (https://www.gatsbyjs.org/packages/gatsby-plugin-node-fields/) to transform the returned data from a boolean to an empty object, which got us past the GraphQL conflicting field type error.

This is definitely not an ideal fix as it's specific to Gatsby and requires a lot of extra config work. Is there a way to ensure consistent field types coming out of Pods?

**Comment by sc0ttkclark** [comment]
Just following up (late) on this -- I built an in-depth WPGraphQL integration for Pods and it works exactly as you'd hope with relationships/files -- with connections! It's pretty useful, check it out here: https://pods-pro.skc.dev/downloads/wpgraphql-integration/

**Comment by lesliecdubs** [comment]
Nice! Thanks for the update!
