### ISSUE TITLE
rendering extendeded comments inside template is not working

### ISSUE THREAD

**Issue by jyapujuju** [pods-framework/pods#5063]
[each comments]
				
       <div class="review">
        <div class="persona_container">
          <div class="persona">
            <p class="gender">{@sex}</p>
            <span class="slash">/</span>
            <p class="nationality">{@comment_country}</p>
            <span class="slash">/</span>
            <p><span class="nick_name">{@comment_author}</span>(<span class="age">{@_age}</span>)</p>
          </div>
        </div>
        <div class="contents_area">
          <h4 class="review_title">title Lorem ipsum dolor sit amet, consectetura</h4>
          <div class="evaluation">
            <span class="rate rate3"></span>
          </div>
          <p class="day">{@comment_date}</p>
          <p class="review_text">
			{@comment_content}          
			</p>
        </div>
        <div class="images_box_container">
			[each photos]
			          <div class="box">
					 	{@_img.thumbnail}
					</div>
			[/each]
		   </div>
      </div>			
	
		[/each]

**Comment by jimtrue** [comment]
Please provide the items requested in the Bug Report template so we can better work your issue. At a minimum, we need the Pods Version of your installation and it would be helpful to have the Pods Package Export (from the Bug Template):

## Pods Package Export (helpful!)
Please include the Pods Package Export as it will be helpful in reproducing your issues.
To access: Pods Admin, Components, Migrate: Packages, Enable. -->
Then Pods Admin, Migrate: Packages, Export and Copy and Paste the JSON here ORSave to a text file and upload to this bug report
