### ISSUE TITLE
2.7.7 + PHP 5.4 is_empty bug?

### ISSUE THREAD

**Issue by davegaeddert** [pods-framework/pods#5079]
**Describe the bug**

We're seeing the exception `Can't use function return value in write context` on a number of sites from this line: https://github.com/pods-framework/pods/blob/2.x/2.7.7/classes/fields/time.php#L168

Seems to be an issue with PHP < 5.5. I think this is the problem: https://stackoverflow.com/a/2173318/1110798

edit: the note in the PHP docs about this is here - http://php.net/manual/en/function.empty.php

I see 5.3 in the tests so I assume you still plan to support < 5.5?

**To Reproduce**

Just open the site after updating the plugin. Sometimes it only shows up in WP admin.

## Pods Version
Please provide the version of Pods you are running: 

2.7.7

**Comment by pglewis** [comment]
I'll look into this pronto.  We do still support 5.3 and up, though this is one of those things that tests didn't specifically catch and of course I'm on 7.x locally.  

Should be easy to patch, expect a PR link here soon.

**Comment by davegaeddert** [comment]
Great, thanks for all your work on Pods!

**Comment by pglewis** [comment]
PR: #5080, if you have time to download and verify the fix.  

Good find and good legwork, makes fixing things so much easier!

**Comment by davegaeddert** [comment]
Yep, that should fix it. I was hoping to submit a PR but I started poking around for where to put a new test case and gave up 😄.

Thanks again!

**Comment by pglewis** [comment]
> I was hoping to submit a PR but I started poking around for where to put a new test case and gave up .

No worries, you'll be getting the credit in the changelog anyway :)

**Comment by pglewis** [comment]
Hotfix released as 2.7.8.
