### ISSUE TITLE
Category and Post_Tag do not interpolate in each tags in Pods Templates

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5087]
**Describe the bug**
This was brought to us through a question on Slack and should work by default:
`{@category}` in a Pods Template is output properly
```
[each category]
{@name}
[/each]
```
Generates a 'Pods Not Found' error for each 'term' selected in Category.

Ditto with `post_tag`: exact same issue as Category
Custom Taxonomy works just fine (in other words, as expected). This seems to be limited to the built-in Category and Post_Tag

**Expected behavior**
Output should be translated as it is for a Custom Taxonomy

**Screenshots**
![screenshot 2018-08-01 11 05 07](https://user-images.githubusercontent.com/3052875/43530120-ca80025e-957a-11e8-8e76-34e5f2456cd0.png)

## Pods Version
Please provide the version of Pods you are running: Pods 2.7.8; have not tested this to see if it worked on prior versions and if this is a recursion error or not.

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.8","build":1533136028},"pods":{"90":{"id":90,"name":"test_tax","label":"Test Taxes","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Test Tax","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"test_tax","query_var":"0","sort":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_latex_test":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_simple_test":"0","built_in_post_types_time_test":"0","built_in_post_types_user_request":"0","built_in_post_types_weekly":"0","built_in_post_types_yesnotest":"1","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_page_test":"0","built_in_post_types_calculator_group":"0","built_in_post_types_text_test":"0","built_in_post_types_required_rel":"0","built_in_post_types_nocontent":"0","built_in_post_types_invoice_items":"0","built_in_post_types_invoices":"0","built_in_post_types_video":"1"},"62":{"id":62,"name":"video","label":"Videos","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"video":{"id":63,"name":"video","label":"Video","description":"","help":"","class":"","type":"oembed","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","oembed_width":"0","oembed_height":"0","oembed_show_preview":"1","oembed_restrict_providers":"0","oembed_enabled_providers_amazoncn":"0","oembed_enabled_providers_amazoncouk":"0","oembed_enabled_providers_amazoncom":"0","oembed_enabled_providers_amazoncomau":"0","oembed_enabled_providers_amazonin":"0","oembed_enabled_providers_animotocom":"0","oembed_enabled_providers_cloudupcom":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_dailymotioncom":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_flickrcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_imgurcom":"0","oembed_enabled_providers_instagramcom":"0","oembed_enabled_providers_issuucom":"0","oembed_enabled_providers_kickstartercom":"0","oembed_enabled_providers_meetupcom":"0","oembed_enabled_providers_mixcloudcom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","oembed_enabled_providers_redditcom":"0","oembed_enabled_providers_reverbnationcom":"0","oembed_enabled_providers_screencastcom":"0","oembed_enabled_providers_scribdcom":"0","oembed_enabled_providers_slidesharenet":"0","oembed_enabled_providers_smugmugcom":"0","oembed_enabled_providers_someecardscom":"0","oembed_enabled_providers_soundcloudcom":"0","oembed_enabled_providers_speakerdeckcom":"0","oembed_enabled_providers_spotifycom":"0","oembed_enabled_providers_tedcom":"0","oembed_enabled_providers_tumblrcom":"0","oembed_enabled_providers_twittercom":"0","oembed_enabled_providers_vimeocom":"0","oembed_enabled_providers_wordpresscom":"0","oembed_enabled_providers_wordpresstv":"0","oembed_enabled_providers_youtubecom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_repeatable":"0"}},"show_in_menu":"1","label_singular":"Video","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"video","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_single":"Video Detail","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_test_tax":"1"}},"templates":{"Video Detail":{"id":65,"name":"Video Detail","code":"{@video}\r\n\r\n<div>Categories: {@category}<\/div>\r\n\r\n<div>Category Each'd:\r\n[each category]\r\n    <a href=\"{@permalink}\" title=\"See all {@name} Videos\" class=\"category\">{@name}&nbsp;<\/a>\r\n[\/each]\r\n<\/div>\r\n\r\n<div>Tags: {@post_tag}<\/div>\r\n\r\n<div>Post Tag Each'd:\r\n[each post_tag]\r\n    <a href=\"{@permalink}\" title=\"See all {@name} Videos\" class=\"category\">{@name}&nbsp;<\/a>\r\n[\/each]\r\n<\/div>\r\n\r\n\r\n<div>Test Tax: {@test_tax}<\/div>\r\n\r\n[each test_tax]\r\n    <a href=\"{@permalink}\" title=\"See all {@name} Videos\" class=\"category\">{@name}&nbsp;<\/a>\r\n[\/each]","type":"template","slug":"video-detail","options":{"_edit_lock":"1533132397:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:5:\"video\";}"}}}}
```

**Possible Workaround**
If you have discovered a workaround, please include it below.

Not sure, but might be related to the differences in how Category and Tags are handled with WP functions. Though `get_the_term_list` should work for category and post_tag, but not sure how those taxonomies are handled inside our `each` templating code.

**Comment by jimtrue** [comment]
Possible Workaround, call the `get_the_term_list` function within the template against the Post ID:

```
function display_category_list ($id) {
      return get_the_term_list($id, 'category');
}
```

in the format `{@ID,display_category_list}`

**Comment by jimtrue** [comment]
That is the error, the fact that it doesn't do what our other Taxonomies do. I didn't check back for recursion, either. The fact that category and post_tag don't output in an each or aren't treated the same as other custom Taxonomies means we aren't doing what is required. They obviously are received as an array or they wouldn't output the standard list style.

**Comment by jimtrue** [comment]
Extending the Category and Tags (duh!) corrected this issue and allows traversal into both. This is the solution for now until we are able to automatically traverse without having to Extend first with Pods.

**Comment by JLNNN** [comment]
@jimtrue

```
[each post_tag]
  {@name}
[/each]
```

This is still not working (Pods v2.7.12). Any ideas? I don't want to use a custom relation because otherwise the custom field and the wordpress default have different states.

**Comment by jimtrue** [comment]
@JLNNN did you extend Tags in Pods Admin, Extend Existing, Taxonomy? This is required for this to work

**Comment by JLNNN** [comment]
@jimtrue yeah, I did. I only get "Pod not found" messages :(

**Comment by jimtrue** [comment]
@JLNNN what is the context you're calling that each block? How are you calling it in your website and where?

**Comment by JLNNN** [comment]
I'm using a custom pods template without access restriction. The each block is inside that template. And rendering is happening in a Gutenberg editor block with

`[pods name="project" template="Projekt Details" slug="my-project"][/pods]`

All other fields are displayed correctly.

**Comment by jimtrue** [comment]
@JLNNN Please export your configuration with Pods Admin, Migrate: Packages and upload here as a text file. You might have to Enable under Pods Admin, Components, Migrate: Packages first.

Alternately, send me temp admin access to your website at support@pods.io

**Comment by JLNNN** [comment]
Here's the configuration: https://gist.github.com/JLNNN/2845cfe722382bb2556b30a244e90784

Thanks in advance!

**Comment by jimtrue** [comment]
Hate to tell you this, but I got it working immediately. You didn't provide `customer` in your export or `post_tag` in your configuration, so I added at least the post_tag portion.

https://gist.github.com/jimtrue/36f2745d464ff5282a8543722685b90c

Viewing the project with Auto Template enabled:
![Screenshot 2019-04-05 09 14 41](https://user-images.githubusercontent.com/3052875/55631062-2ab0af80-5785-11e9-8a40-722fab7a3fb0.png)

Viewing the project added to a Page in a Gutenberg shortcode block as you did above:
![Screenshot 2019-04-05 09 24 49](https://user-images.githubusercontent.com/3052875/55631106-3f8d4300-5785-11e9-8560-0c547734c607.png)

**Comment by JLNNN** [comment]
Oh wow - I didn't know it's required to extend a wordpress default field (in this case -> tags) with zero added custom properties to get that list. Is that stated anywhere in the documentation?

A last question: When using {@permalink} to get the "list" of all posts/entries/data that have been assigned to that post_tag, my project is not listed there. Any suggestions? (Link is: http://localhost.local/tag/hardware/).

**Comment by jimtrue** [comment]
See comment above: https://github.com/pods-framework/pods/issues/5087#issuecomment-419894576

That's the workaround until we automatically traverse into Category and post_tag which we don't do now and probably won't until post 2.8. That's why this one is closed.

To the latter, if you want your custom post types to show up on post tag or categories archives, you have to modify the pre_get_posts filter to activate that; same with widgets. This is a failing in WP Core because all of queries are written to only work against 'post'. Custom Taxonomies don't require this change.

https://docs.pods.io/code-snippets/modifying-pre_get_posts-categories-tags-show-custom-post-types/

**Comment by JLNNN** [comment]
You've been a very great help, everything is working now as expected. What's your paypal address so I can send you a little THANKS? :)

**Comment by jimtrue** [comment]
https://friends.pods.io for our Donation model

**Comment by jimtrue** [comment]
We accept One Time donations: https://friends.pods.io/donations/one-time-donation/
