### ISSUE TITLE
Outputting the values ​​of the select field in the template

### ISSUE THREAD

**Issue by dvijnru** [pods-framework/pods#5098]
Hi, I installed Pods Admin. Added a new pods and added fields to it. Field Type: relationship, Related To: Simple (custom defined list). How do I display options for the filter in the template?
My template:
<!select>
Here need to display the parameters from the field
<!/select>
Thank you

**Comment by dvijnru** [comment]
At me it turned out to output here so:

`$queried_object = get_queried_object();`
`$term_id = $queried_object->term_id;`
`$pod = pods('cats', $term_id);`
`$fields = $pod->api->pod_data['fields'];`
`echo $fields['poroda']['options']['pick_custom'];`

But because of this page a long load

**Comment by quasel** [comment]
looks like this is an taxonomy term archive page right? and you extend the Taxonomy? 

`$pods = pods();` normally get's all it needs, on archive pages maybe it needs  `pods('cats', get_queried_object_id()`
and then just do `echo $pods->display('poroda')` 

A Good Starter Video: https://pods.io/2015/02/28/podscast-001-finding-your-way-with-podsfind/
for the basics - https://pods.io/docs/code/pods/find/ 

But your code shouldn't affect the page load in any noticeable way - is there other code?
Sorry for the late reply, feel free to comment if you still have questions!
