### ISSUE TITLE
Gravity Forms Populating Pods Selection - Feeds Not Working

### ISSUE THREAD

**Issue by basharourabi** [pods-framework/pods#5100]
**Describe the bug**
Gravity Pods inter-phase intermittent; upon new form creation then stops feeding.

**To Reproduce**
1. Created Pods with relations to taxonomies and posts
2. Populated Pods Posts and selection taxonomies
3 .Under Basic tab, created bidirectional relationships by selecting related to the appropriate pod, also selecting bidirectional field.
4. Under additional field options, selected  "multiple select", format"list view"
5. in Gravity Forms, created a form,
6. in Gravity Forms,  selected "Multi Select" field
7.in Gravity Forms multi select field, under general tab selected "in Gravity Forms,  selected " Populate Related Items (requires a feed configured)" option.
8.in Gravity Forms multi select field, under advanced tab selected "Allow field to be populated dynamically" option.
9.in Gravity Forms multi select field, under appearance tab selected "Enable enhanced user interface" option.
10. after saving form, in settings, Selected pods, created Pods Feed, mapped the fields.
11. when previewing the form; no feeds selection passing through.

**Expected behavior**
I expected all feeds to be presented in the forms for selection

## Pods Version
PODS gravity forms 1.4 Beta

## WordPress Environment

Debug Information
WordPress Version: 4.9.8

PHP Version: 5.6.30

MySQL Version: 5.5.51

Server Software: Microsoft-IIS/7.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3517.0 Safari/537.36

Session Save Path: D:\Temp\php\session\

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: -

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Ourabi Theme

Currently Active Plugins:

Accordion and Accordion Slider: 1.0.1
Add Shortcodes Actions And Filters: 2.0.9
Anywhere Elementor: 1.0
Classic Editor: 0.4
CM On Demand Search And Replace: 1.1.11
Custom Sidebars: 3.1.6
Duplicate Page: 2.7
Easy Passthrough for Gravity Forms: 1.3.1
Easy Sidebar Menu Widget: 1.0
Ele Conditions: 1.0.1
Elementor: 2.1.6
Elementor Addons & Templates - Sizzify Lite: 1.2.5
Elementor WHMCS Elements: 1.0.2
Entry Automation for Gravity Forms: 1.3.4
Essential Addons for Elementor: 2.7.5
Fullwidth Page Templates: 1.0.3
Geolocation Detector for Gravity Forms: 1.0
GEO my WP: 3.1
Gravity Flow: 2.2.3
Gravity Forms: 2.3.3.2
Gravity Forms Chained Selects Add-On: 1.0.9
Gravity Forms Partial Entries Add-On: 1.2
Gravity Forms Polls Add-On: 3.1.4
Gravity Forms Quiz Add-On: 3.1.7
Gravity Forms Range Slider: 1.1
Gravity Forms Signature Add-On: 3.5.2
Gravity Forms styler for Elementor: 1.0.0
Gravity Forms Styles Pro: 2.4.6
Gravity Forms Survey Add-On: 3.2.2
Gravity Forms User Registration Add-On: 3.9.2
Gravity Forms Webhooks Add-On: 1.1.5
GravityView: 2.0.14.1
Gutenberg: 3.4.0
JS & CSS Script Optimizer: 0.3.3
Livemesh Addons for Elementor: 2.3.3
Live Population for Gravity Forms: 1.4.1
Max Mega Menu: 2.5
NavMenu Addon For Elementor: 1.1.2
Osclass job board: 1.3.2
Pods - Custom Content Types and Fields: 2.7.9
Pods Gravity Forms Add-On: 1.4 Beta
Popup Maker: 1.7.29
Post Tags and Categories for Pages: 1.4.1
Quick Page/Post Redirect Plugin: 5.1.8
Really Simple CAPTCHA: 2.0.1
Sassy Social Share: 3.2.4
Simple Custom CSS and JS: 3.18
Slider Revolution | VestaThemes.com: 5.4.7.3
Title Remover: 1.2
Toolbar Extras: 1.3.3
Void Elementor Post Grid Addon for Elementor Page builder: 1.0.9
Wp-D3: 2.4.1
WP Add Mime Types: 2.2.1
WP Coder: 1.1
wpDataTables: 2.0.3 Lite
WP FullPage: 4.0.5.2
WP Meta and Date Remover: 1.7.2
WP no-iFrames (Content Protection): 1.3
Yoast SEO: 7.9.1

**Additional context**
I deleted all forms and recreated them after updating to pods gravity forms 1.4 beta; one form worked briefly; upon creating new forms the feeds stopped working again.

**Comment by jimtrue** [comment]
We have a dedicated GitHub for the Pods Gravity Forms Add-On. I notice in your debug that you're using the beta 1.4.1, so it would definitely help more to have that information inside that particular GitHub Repository (along with the other items we request for bug reports in that Repository):

https://github.com/pods-framework/pods-gravity-forms/issues/new
