### ISSUE TITLE
REST API for ACT Pods?

### ISSUE THREAD

**Issue by paulwoolsey** [pods-framework/pods#5124]
## Issue Overview

I'm trying to load a page that lists the data from a pod (484 people, with associated data). Page time was interminably slow (22s minimum, up to page timeout). I've gone through [this](https://github.com/pods-framework/pods/issues/1911 ) and brought the page time down to a consistent 13s. Still unacceptable, obviously. I need a way to make these calls via Ajax (client doesn't want pagination, for some internal political reason involving who gets to be on the first page and who doesn't....sigh.) I can't find any functional, up-to-date tutorials on how to extend the WP REST API for use with Pods ACTs specifically. 

## Expected Behavior

 

It seems like we should have a tutorial, or some boilerplate code to get people started. 

## Current Behavior

 

Terribly long page load times.

## Steps to Reproduce (for bugs)

http://jwdevelopment.wpengine.com/people/

## Possible Solution

Moving the pods find() function to a more asynchronous method?

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 4.9.8

PHP Version: 5.6.36-1+wpengine16

MySQL Version: 5.6.34

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/jwdevelopment/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: The7

Currently Active Plugins:

Contact Form 7: 5.0.3
HTML PDF Generator: 1.0.0
Insert Headers and Footers: 1.4.3
JW Custom Post Types V3: 3.1.1
Pods - Custom Content Types and Fields: 2.7.9
Pods Visualize: 1.0
Smart Slider 3: 3.3.6
Smart Slider 3 Pro: 3.3.3
Tabify Edit Screen: 0.9.7
Timeline and History Slider: 1.2.5
TinyMCE Advanced: 4.8.0
Typekit Fonts for WordPress: 1.9.0
Visual Composer Website Builder: 2.10
WP Admin UI Customize: 1.5.11
WP Google Maps: 7.10.28
WP Google Maps - Pro Add-on: 7.10.21
```

</details>

## Pods Package Export (helpful!)

```

[export.json.txt](https://github.com/pods-framework/pods/files/2303696/export.json.txt)

```

## Related Issues and/or PRs

https://github.com/pods-framework/pods/issues/1911

**Comment by pglewis** [comment]
> I've gone through this and brought the page time down to a consistent 13s. Still unacceptable, obviously.

Can you share what youv'e done here?  Assuming that's not overwhelming, how much code is there that involves the relationship fields inside a fetch loop?  

I'm still not convinced you need to resort ajax-ing as a solution here.

**Comment by paulwoolsey** [comment]
Sure. I'll share what I can.

Here's our whole call: 

`
$fields = array(
	'primary_practice_group.name AS ppg_name',
	//'practices.name AS prac_name',
	'primary_city.name AS city',
	't.*'
);
$fields = implode( ', ', $fields );
$params = array(
	'select' => $fields,
	'limit' => -1,
	'orderby' => 't.last_name ASC',
	'where' => 't.private = "No"'
);
$pods = pods( 'people', $params );
$total = $pods->total_found();	
//loop through records
if ( $pods->total() > 0 ) {
while ( $pods->fetch() ) {
//Put field values into variables
$private = $pods->display('private');
$title = $pods->display('full_name');
$last_name = $pods->display('last_name');
$first_name = $pods->display('first_name');
$middle_name = $pods->display('middle_name');
$name_suffix = $pods->display('name_suffix');
$permalink = site_url( 'people/' . $pods->field('permalink' ) );
$image_large = $pods->field('image_large');
$image_small = $pods->field('image_small');
$attorney_type = $pods->display('attorney_type');
$primary_practice_group = $pods->display('ppg_name'); //rel
$practices = $pods->display('practices'); //rel
$primary_city = $pods->display('city'); //rel
$primary_phone = $pods->display('primary_phone');
$primary_fax = $pods->display('primary_fax');
$primary_mobile = $pods->display('primary_mobile');
$email = $pods->display('email');
$linkedin = $pods->display('linkedin');
$twitter = $pods->display('twitter');
$vcard = $pods->display('vcard');
$id = $pods->field('id');
$additional_languages = $pods->display('additional_languages');`

The practices field was giving us issues (inserting the same person multiple times for each practice, rather than listing the practices in an array, as before). Because we are on a time crunch, I just commented it out and kept going to see what we could get in terms of results from the rest.

Most all of this data is a direct call from a single pod, people. We did what we could up front to limit our relationships as much as possible.

**Comment by pglewis** [comment]
Also, another diagnostic you can do is add `?pods_debug_sql=1` to the end of the URL (you'll need to be logged in as admin, or at least a user with those privs).  

I'm looking at what you provided but the above might shed some light too.

**Comment by pglewis** [comment]
If any of the fields left inside the while loop are coming from outside "people" and haven't been placed into the select then each of those `field` or `display` calls is going to generate an extra query per loop iteration.  If that's the case then it'll probably be pretty clear from the above debug flag as it'll fill the browser with queries.

**Comment by pglewis** [comment]
We have integer keys for the joins and even complex queries with quite a few rows should be able to perform reasonably well.  I'm not sure where "reasonably well" begins but I know it's well below 13s.

**Comment by paulwoolsey** [comment]
This is our primary select statement, it seems.


 SELECT
    DISTINCT
                `primary_practice_group`.`name` AS ppg_name, `primary_city`.`name` AS city, t.*
                FROM `wp_pods_people` AS `t`
                
                    LEFT JOIN `wp_podsrel` AS `rel_primary_practice_group` ON
                        `rel_primary_practice_group`.`field_id` = 177
                        AND `rel_primary_practice_group`.`item_id` = `t`.`id`

                    LEFT JOIN `wp_pods_practice_areas` AS `primary_practice_group` ON
                        `primary_practice_group`.`id` = `rel_primary_practice_group`.`related_item_id`
                
                
                    LEFT JOIN `wp_podsrel` AS `rel_primary_city` ON
                        `rel_primary_city`.`field_id` = 55
                        AND `rel_primary_city`.`item_id` = `t`.`id`

                    LEFT JOIN `wp_pods_office` AS `primary_city` ON
                        `primary_city`.`id` = `rel_primary_city`.`related_item_id`
                
                WHERE ( t.private = "No" )

**Comment by pglewis** [comment]
> This is our primary select statement, it seems.

I don't think that alone would be that bad if `people` is under a thousand rows as I think I recall.  Can you run that query from an external DB tool to see execution time and rows returned?

**Comment by pglewis** [comment]
> The practices field was giving us issues (inserting the same person multiple times for each practice, rather than listing the practices in an array, as before)

This part is a pest as well, with the one-to-many relationship.  An inner loop to pull the practices, checking for a change in the person should still perform just fine despite being a hassle to have to deal with yourself.  Still likely a much better solution than trying to ajax for the data if so.

**Comment by quasel** [comment]
That's weird e.g https://www.bowling-esvoenb.eu/wp-euro/results/ that's close to 800 Games from 90 Players crunched with statistics - using multiple CPT (meta and table Storage) - runs fast on a crappy host - page load is even faster thx to caching (page cache+transients -> "expires" option in pods find)

I would check if your select really is setup for all fields you need! $pods->row()

**Comment by pglewis** [comment]
Keep us abreast of your progress and any pitfals, @paulwoolsey.  Asynchronous stuff via Javascript is great when you need dynamic data and behavior but that's not the case here.  Even if ajaxing and adding round-trips to the server works out you're adding more moving parts to the solution which equals more things to maintain and more vectors for breakage.  You have more data than a typical install but it's not at otherworldly levels, we've dealt with bigger by judicious optimization.

**Comment by paulwoolsey** [comment]
For now, we're going to a paginated version of the search.  I still want to get this version running, because at this point it's a challenge. But for now, because deadlines, we're going with the traditional model. Page loads in 3s, filters work, life is good.

**Comment by quasel** [comment]
@paulwoolsey still weird makes no sense with that number of record's but maybe I'm missing something!

**Comment by pglewis** [comment]
Excellent news overall, and I think paging might turn out to be good solution from a UI/UX perspective as well.  

I'm going to close this out as this ticket if very specific to your situation, but also open a future feature from supporting REST API on ACTs.  We do still need that.  Open a new ticket if you have further probs.
