### ISSUE TITLE
Autocomplete conflict with Smush + Yoast SEO v8

### ISSUE THREAD

**Issue by martinosmartinos** [pods-framework/pods#5128]
After recent updates autocomplete fields stopped working and, instead, show simple select list. Console shows following errors while editing/ creating new post:

![screen shot 2018-08-22 at 10 41 48](https://user-images.githubusercontent.com/6096385/44452946-2968b300-a5f8-11e8-9bc5-3a1a348580d1.png)

and autocomplete field looks as follows:
![screen shot 2018-08-22 at 10 42 01](https://user-images.githubusercontent.com/6096385/44452974-3e454680-a5f8-11e8-8b9c-6d32437b0dea.png)

## Pods Version
2.7.9 

## WordPress Environment
<details>
WordPress Version: 4.9.8

PHP Version: 7.0.30-0ubuntu0.16.04.1

MySQL Version: 5.7.22

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_20_

WP Multisite Mode: Yes

WP Memory Limit: 512M

Pods Network-Wide Activated: Yes

Pods Install Location: /nas/content/staging/lemurs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Mongabay Environmental News

Currently Active Plugins:

Amazon Web Services: 1.0.5
AMP: 0.7.2
Bloom: 1.1.8
ElasticPress: 2.5.2
Feedzy RSS Feeds Lite: 3.0.9
Google Analytics Top Content Widget: 1.7.3
Google News Sitemap: 1.0.11
Google XML Sitemaps: 4.0.9
GTmetrix for WordPress: 0.4.2
HungryFEED: 1.6.3
iframe: 4.3
JotForm Embed Forms: 1.2.2
MonsterInsights - AMP Addon: 1.1.7
MonsterInsights - Dimensions Addon: 1.1.5
MonsterInsights - Facebook Instant Articles Addon: 1.0.6
MonsterInsights Pro: 7.1.0
Multisite User Sync: 1.1
Nelio External Featured Image: 1.2.0
Paid Memberships Pro: 1.9.5.3
Pods - Custom Content Types and Fields: 2.7.9
Post Thumbnail Editor: 2.4.8
REST API ALL CORS: 0.0.1
RSS Via Shortcode for Page & Post: 1.2.b
Simple Drop Cap: 1.2.8
Simple Facebook Instant Articles: 0.5.3
Smush: 2.8.0.1
Soliloquy: 2.5.5
TablePress: 1.9
Third Column: 2.0
Toplytics: 3.2
User Role Editor: 4.44
WP External Links: 2.2.0
WP Missed Schedule (The Original): 2014.1231.2017.5
WP Offload S3: 1.7.2
WP Scroll Depth: 1.4.1
Yoast SEO: 8.0
Yoast SEO: News: 5.4
</details>

**Comment by pglewis** [comment]
Have you also reported this conflict with Yoast?

**Comment by martinosmartinos** [comment]
@pglewis no I did not.

**Comment by pglewis** [comment]
This is some conflict between the two plugins so I would report it with them as well.

**Comment by pglewis** [comment]
I installed the latest Yoast SEO plugin locally and tested both a single select and multi-select autocomplete without issue and no console errors, so there must be some other setting or factor to reproduce the problem.  

![autocomplete](https://user-images.githubusercontent.com/1973916/44465124-a5f49500-a5ea-11e8-985b-c262b8ecc366.png)

**Comment by martinosmartinos** [comment]
@pglewis might be autocomplete is relationship autocomplete to custom taxonomy.

**Comment by pglewis** [comment]
I'll try that when I get a chance.  We're going to reach out to Yoast and see if they have any insight on what recent changes may be causing a conflict with the SelectWoo control.

**Comment by martinosmartinos** [comment]
@pglewis I appreciate!

**Comment by jimtrue** [comment]
@martinosmartinos Try disabling Smush. That fixed mine instantly.

**Comment by martinosmartinos** [comment]
@jimtrue let me try...

**Comment by martinosmartinos** [comment]
@jimtrue indeed Smush is the one causing a problem. Yoast is now enabled in combination with PODs and it seems to work if Smush deactivated.

**Comment by jimtrue** [comment]
Open the bug report with Smush, it's not Yoast or Pods.

**Comment by pglewis** [comment]
Title updated, I'll do some legwork on what's causing it if I can reproduce.

**Comment by martinosmartinos** [comment]
@jimtrue thanks for pointing out! Let's go to Smush and smush them:)

**Comment by pglewis** [comment]
It's more complicated that _that_, even.  It appears to be the combination of all three plugins.  Pods works for me with both Yoast SEO V8 and Smush individually but all three with cause the conflict.

**Comment by martinosmartinos** [comment]
@pglewis another day in paradise....

**Comment by pglewis** [comment]
@martinosmartinos: Are you still using this combination of Pods/Yoast/Smush?  I just tested after updating both Yoast and Smush to the latest versions and autocomplete seems to be working again.

**Comment by martinosmartinos** [comment]
Yup and everything seems to work for me as well.
