### ISSUE TITLE
"Single Select" Relationship Return differently depending on Format

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#5138]
## Issue Overview
"Single Select" Relationship Return differently depending on Format in the filter `pods_api_pre_save_pod_item`

## Expected Behavior
Consitent Behavior 

## Current Behavior
List View - array()
Autocomplete - single value
Radio Buttons  - single value
Drop Down - single value

## Possible Solution
no idea :/ - just tell users to check for an array ;)

**Comment by sc0ttkclark** [comment]
This is related to the DFV list view when using a single select field, it should submit as a single param not an array `[]`

**Comment by pglewis** [comment]
PR: #5139

**Comment by quasel** [comment]
works for me!
