### ISSUE TITLE
Custom settings page fields not saving - seems to be conflict with W3 Total Cache

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#5151]
This occurs in a multisite install in case that has any bearing (have not tested this on a single site)
 
The bug manifests itself as simply not being able to save any changes made on a custom settings page I've created

e.g. checking or unchecking boxes reverts to the previous state after saving or I cannot delete or add new entries in text boxes.

Disabling W 3 Total Cache fixes the issue

**Debug Information:**

WordPress Version: 4.9.8

PHP Version: 7.0.31-1+ubuntu18.04.1+deb.sury.org+1

MySQL Version: 5.5.5

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: Yes
    Memcached: Yes
    Redis: Yes

WPDB Prefix: wp_8_

WP Multisite Mode: Yes

WP Memory Limit: 64M

Pods Network-Wide Activated: Yes

Pods Install Location: /var/www/websussed.co.uk/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme:

Currently Active Plugins:

    Pods - Custom Content Types and Fields: 2.7.9
    Sucuri Security - Auditing, Malware Scanner and Hardening: 1.8.18
    W3 Total Cache: 0.9.7

**Comment by quasel** [comment]
Hi, did you try saving, then manually force the cache invalidation? the important distinction is do the Values get saved to the DB and you just see the outdated values or aren't they saved! 

Furthermore i see you have 3 different object caches active - which are in use? 
and W3 Total can be tricky to configure properly! 

Did you try resetting the pods cache? (Pods/Settings)

**Comment by Pezzab** [comment]
I think it's definitely the case that entries are remaining within the database (hence check marks reappearing after unchecking then saving and so on).

The behaviour doesn't seem to be totally consistent - I  briefly had W3TC working fine after reactivating for instance.

It definitely seems to be some sort of caching issue - though I've been using W3TC for quite some time with Pods with no problems.

I'll investigate further.
