### ISSUE TITLE
import_package is not importing a package

### ISSUE THREAD

**Issue by andrewmackie** [pods-framework/pods#5157]
Hi,

It appears that import_package function of the pods_api is not importing a package. 

I tested many variations of code, but the following is the final and simplest version that I tested:

    add_action( 'plugins_loaded', 'my_pods_init' );

    function my_pods_init() {
        if ( !function_exists( 'pods_api') ) {
            return;
        }
        pods_api()->import_package( file_get_contents(dirname( __FILE__ ) . '/includes/pods.json'), true);
        pods_api()->cache_flush_pods();
        pods_api()->load_pods();
    }

This code runs silently but does not import a package on either 1) a clean WP/Pods install or 2) a WP/Pods instance which already has some Pods.

In my testing I confirmed that:
- my code was being run by WP, 
- the pods.json filepath was valid (by echoing its contents), and
- the package JSON was valid (by manually importing it into another WP/Pods instance using Migrate Packages). 

I am running the latest WP/Pods versions. Here is the Pods debug information for my clean WP/Pods instance:

WordPress Version: 4.9.8
PHP Version: 5.6.38
MySQL Version: 5.6.40
Server Software: LiteSpeed
Your User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Session Save Path: /tmp
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:
    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No
Object Cache:
    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 40M
Pods Network-Wide Activated: No
Pods Install Location: /home/foo/public_html/test/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: Twenty Seventeen
Currently Active Plugins:
    [My plugin containing the above code]
    Limit Login Attempts Reloaded: 2.7.1
    Pods - Custom Content Types and Fields: 2.7.9

Thanks for Pods and for your help here.
Andrew

**Comment by sc0ttkclark** [comment]
Can you verify the site you are running this code on has the Migrate Packages component enabled? If the component is not enabled, that code function won't do anything. You should check and see what import_package() is returning.

**Comment by andrewmackie** [comment]
Thanks for your quick reply. Yes I can confirm that Migrate Packages was enabled and it didn't import the package. 

That's a good reminder, though, to put pods_require_component in the plug-in code, thank you. My code is now as follows (and it adds Migrate Packages to Pods components but doesn't import the package, even after deactivating and reactivating my plugin):

    add_action( 'plugins_loaded', 'my_pods_init' );

    function my_pods_init() {
        if ( function_exists( 'pods') ) {
           pods_require_component( 'migrate-packages' );
       }
       if ( !function_exists( 'pods_api') ) {
           return;
       }
       pods_api()->import_package( file_get_contents(dirname( __FILE__ ) . '/includes/pods.json'), true);
       pods_api()->cache_flush_pods();
       pods_api()->load_pods();
    }

**Comment by andrewmackie** [comment]
As far as I can tell, it's not returning anything. I tried:

    echo(pods_api()->import_package( file_get_contents(dirname( __FILE__ ) . '/includes/pods.json'), true));

And saw nothing at the top of the admin screen.  (Sorry, I'm a Python guy, not a PHP person - is there a better way of displaying what the function returns?)

**Comment by ChristopheSeguinot** [comment]
Hi, 
I'm having exactly the same issue so I use this old discussion instead of opening a new issue. 
I'm trying to import a pod package in a theme using a very similar code 
`
$pods_api = pods_api();
$temp = $pods_api->import_package( file_get_contents(dirname( __FILE__ ) . '/includes/pods.json', false);
`
The Pods framework is installed, the migrate package is enabled, the filepath has been verified, it's a fresh pods export package. 
import_package silently fail and return bool(false) . 
How can I help debugging this?

**Comment by ChristopheSeguinot** [comment]
Hi again, 
My mistake. I used the filename, instead of the file content (JSON encoded)
It works fine and I think this issue can be closed.

**Comment by jimtrue** [comment]
Thanks for the update

**Comment by Kpudlo** [comment]
@ChristopheSeguinot would you be able to share your final line for import_package? Going through this issue myself and still not fairing well!

**Comment by ChristopheSeguinot** [comment]
My final function is closed to the one proposed by andrewmackie. 
1- export all your pods from your dev website ans save the json file somewhere in your theme under development . 
As indicated in my function, $temp can be used to investigated if all your pods have been imported
 
`
function load_default_pods() {
    // Import pods without replacing existing items when found
    
    global $wp_filesystem;
    // Initialize the WP filesystem
    if (empty($wp_filesystem)) {
        require_once (ABSPATH . '/wp-admin/includes/file.php');
        WP_Filesystem();
    }
    
    pods_require_component( 'migrate-packages' );
    $pods_api = pods_api();
    
    $default_package = $wp_filesystem->get_contents(get_template_directory().'/assets/pods/default_pods.json') ;
    $temp = $pods_api->import_package($default_package , false);
    // $temp contains the list of imported pods. It can be used to test if every pods have been imported
    $pods_api->cache_flush_pods();
    
    // Test if theme_settings pods exists (one of my pod) if true, pods have probably been imported correctly
    if (! pods('theme_settings', null, true)) {
        return false; 
    }
    return true; 
}
`
This function is called inside mytheme_install() after testing if pods api is loaded. The theme install itself being fired to an 'admin_init' hooked function mytheme_detect_need_update(). 
`
function mytheme_detect_need_update() {
    // Do not echo anything in this function, this breaks wordpress!
    
    // no version saved in first development version; and at fresh theme install.
    $previous_version = get_option( 'MYTHEME_VERSION', -1 ); 
    
    // Case install : import all pods and content then return
    if (-1 == $previous_version) {
        // This is probably a fresh install of the theme : import pods structure (config) and pods default values ??
        mytheme_install();
    }
    
    if ( version_compare( MYTHEME_VERSION, $previous_version, '==' ) ) {
        // Identical version: no upgrade needed !
        return;
    } elseif ( version_compare( MYTHEME_VERSION, $previous_version, '>=' ) ) {
        // New version, upgrade needed.
        mytheme_upgrade( $previous_version, THEME_VERSION );
        
    } else {
        // Older version !! not possible excepted in case of manual downgrade !
        return;
    }
}

add_action( 'admin_init', 'mytheme_detect_need_update' );
`

**Comment by Kpudlo** [comment]
So weird, I still can't get it to work within a plugin...
```
function orbitspin_axis_menu() {

    if (function_exists('pods')) {
        pods_require_component('migrate-packages');
    }

    if (!function_exists('pods_api')) {
        return;
    }

    global $wp_filesystem;

    if (empty($wp_filesystem)) {
        require_once (ABSPATH . '/wp-admin/includes/file.php');
        WP_Filesystem();
    }

    $data = $wp_filesystem->get_contents(plugin_dir_path( dirname( __FILE__ ) ) . 'admin/json/test.json');

    pods_api()->import_package($data,false);
    pods_api()->cache_flush_pods();
}
```
I can print the data just fine, so I know I'm getting it, it's just not creating a settings page. I have also manually imported the JSON to ensure that was accurate. 

I'll keep plucking away at it...or just write everything manually.

**Comment by sc0ttkclark** [comment]
@Kpudlo Where/when does `orbitspin_axis_menu` get called?

**Comment by Kpudlo** [comment]
I've done both `plugins_loaded` and `admin_init`

**Comment by sc0ttkclark** [comment]
How far does your function get? Does it get all the way to `import_package()` itself?

**Comment by Kpudlo** [comment]
Yes, it does. I even added a `pods_register_type('settings','test_page');` line after the `import_package()` and that triggered fine.

**Comment by sc0ttkclark** [comment]
Can you verify that `$data` is getting the contents correctly and it has valid JSON within it?

**Comment by Kpudlo** [comment]
I was able to get contents from $data with print_r, I'll be able to get the actual output in a few hours.

**Comment by ChristopheSeguinot** [comment]
If $data is correct, your code should works. The only difference in my code is the use of $pods_api = pods_api(); I verified that directly callign the pods_api class with pods_api()-> also works (that's normal!). 
You can also test a raw import of the exactly the same json file (in case of file access rights issue) using the pods plugin "Migrate: Packages" import feature (but it seems you already done this).

**Comment by Kpudlo** [comment]
Alright, it's working now! I restarted XAMPP and did a reset of Pods again and now it's importing correctly. :confounded: Thanks for your assistance @sc0ttkclark and @ChristopheSeguinot!

Final code:

```
function orbitspin_axis_menu() {


    if (function_exists('pods')) {
        pods_require_component('migrate-packages');
    }

    if (!function_exists('pods_api')) {
        return;
    }

    global $wp_filesystem;

    if (empty($wp_filesystem)) {
        require_once (ABSPATH . '/wp-admin/includes/file.php');
        WP_Filesystem();
    }

    $data = $wp_filesystem->get_contents(plugin_dir_path( dirname( __FILE__ ) ) . 'admin/json/test.json');

    pods_api()->import_package($data,false);
    pods_api()->cache_flush_pods();
    pods_api()->load_pods();
}

add_action('admin_init','orbitspin_axis_menu');
```

**Comment by sc0ttkclark** [comment]
@Kpudlo That's great -- however you are running this on every single admin page load. This is not optimal and it forces the save of your pod configuration over and over which will slow down the admin area. You should try only running it as needed by putting it behind a query check which you can implement like this at the top of your function:

```php
if ( empty( $_GET['reinstall_my_pods'] ) || ! current_user_can( 'edit_plugins' ) ) {
    return;
}
```

This will prevent the installation from happening unless you set `&reinstall_my_pods=1` in the URL of an admin page while logged in as an administrator account that has access to edit plugins. That is my suggestion and is easy to implement.

**Comment by Kpudlo** [comment]
Thanks for the suggestion! I'll be adding that right now!
