### ISSUE TITLE
In Hebrew - Translate or remove “and” at multiple values

### ISSUE THREAD

**Issue by amiayu** [pods-framework/pods#5160]
## Issue Overview

I have field with multi select.
When a few values are selected, a “and” label appears between the last value and the one before. This is well, but my site is in Hebrew language, so the “and” should be either translated or ommited.

## Expected Behavior

 

Bug: In a response in support forum Jim True wrote:
"The system should be attempting to translate this; if it’s not that’s definitely needs a bug report on it"
## Current Behavior

 

a “and” label appears between the last value and the one before, and it is not translated to hebrew.
## Steps to Reproduce (for bugs)

1. [https://www.ayu.co.il/herbs/testbug/](url)
2. Link to screenshot [https://www.ayu.co.il/wp-content/uploads/2018/09/testBug.png](url)
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
Debug Information
WordPress Version: 4.9.8

PHP Version: 7.2.10

MySQL Version: 5.6.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

Session Save Path: /opt/alt/php72/var/lib/php/session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wpdj_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/ayuilinf/ayu.co.il/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Accessible Poetry - WordPress Accessibility Plugin: 3.0.4
AddToAny Share Buttons: 1.7.30
Click to Chat for WhatsApp: 1.6
Contact Form 7: 5.0.4
Contact Form 7: Accessible Defaults: 1.1.4
Easy Table of Contents: 1.7
Elementor: 2.2.4
Elementor Pro: 2.1.9
HREFLANG Tags Lite: 1.7.2
MaxButtons: 7.5.1
Navigation Tree Elementor: 1.0.1
Pods - Custom Content Types and Fields: 2.7.9
Premium Addons for Elementor: 2.6.7
Really Simple SSL: 3.0.5
Redirection: 3.5
Shortcode in Menus: 3.4
Smush: 2.8.1
Tooltipy - (PRO): 4.3.11
UpdraftPlus - Backup/Restore: 1.15.2
WP Google Search: 1.0.7
Yoast SEO: 8.3
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```
{"meta":{"version":"2.7.9","build":1537925045},"pods":{"3532":{"id":3532,"name":"herbs","label":"חומרי מרפא","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"rasa":{"id":3533,"name":"rasa","label":"טעמים ראשיים","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"M|מתוק\nA|חמוץ\nL|מלוח\nK|חריף\nT|מר\nKs|מכווץ","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"photo":{"id":3555,"name":"photo","label":"תמונה","description":"","help":"","class":"","type":"file","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"1","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"guna":{"id":3557,"name":"guna","label":"מאפיינים","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"multiselect","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_custom":"laghu|קל לעיכול (laghu)\nguru|קשה לעיכול (guru)\nruksha|יבש (ruksha)\nsnigdha|שומני (snigdha)\ntikshna|חד (tikshna)","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"vipak":{"id":3573,"name":"vipak","label":"טעם אחרי העיכול (vipak)","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"M|מתוק\nA|חמוץ\nK|חריף","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"virya":{"id":3574,"name":"virya","label":"עוצמה (Virya)","description":"","help":"","class":"","type":"pick","weight":4,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"U|חם (Ushna)\nS| קר (Shita)","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"botanical_name":{"id":3575,"name":"botanical_name","label":"שם בוטני","description":"","help":"","class":"","type":"text","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"rasa2":{"id":3576,"name":"rasa2","label":"טעמים משניים","description":"","help":"","class":"","type":"pick","weight":6,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"M|מתוק\nA|חמוץ\nL|מלוח\nK|חריף\nT|מר\nKs|מכווץ","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"dosha":{"id":3592,"name":"dosha","label":"השפעה על דושה:","description":"","help":"","class":"","type":"pick","weight":7,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"V|מפחית ואטה\nP|מפחית פיטה\nK|מפחית קאפה","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"חומר מרפא","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"_","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_keywords_family":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}},"templates":{"test":{"id":3601,"name":"test","code":"<ul>\r\n\t<li>\r\nddd{@dosha}\r\n\t<\/li>\r\n<\/ul>\r\n\r\n<ul> \r\n     <li><strong>Name:<\/strong> {@dosha}<\/li> \r\n\r\n<\/ul>","type":"template","slug":"test","options":{"_edit_last":"1","_edit_lock":"1537923961:1","bluet_exclude_post_from_matching":null,"bluet_exclude_keywords_from_matching":"","bluet_matching_keywords_field":"a:0:{}","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}"}}}}
## Workaround or Alternate Solution Until Bug is Addressed

Jim True suggested:
"workaround if you’re working with a relationship field, just output as an unordered list and you can style it with CSS"
I did not manage to do that yet. Tried.

**Comment by jimtrue** [comment]
This actually isn't handled in our Pods Code, this is handled through Translations provided to https://translate.wordpress.org/projects/wp-plugins/pods/stable/he/

The string you're referring to is linked below. All translatable strings in our code are handled through the links above.

https://translate.wordpress.org/projects/wp-plugins/pods/stable/he/default?filters%5Boriginal_id%5D=773447

I'm closing this in favor of the process above. We have a FAQ about that:
https://docs.pods.io/faqs/ive-noticed-pods-strings-arent-translated-language-fix-help/
