### ISSUE TITLE
картинки стали битыми  

### ISSUE THREAD

**Issue by meni77** [pods-framework/pods#5167]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by jimtrue** [comment]
@meni77 did you open this in error? You haven't described an issue.
