### ISSUE TITLE
Conditional tags in Pods Template are not saved

### ISSUE THREAD

**Issue by frankmeeuwsen** [pods-framework/pods#5169]
## Issue Overview
Using Pod Templates, the conditional tags are not saved in the editor

## Expected Behavior
When I use the contional tags in the Pods Template editor, I expect them to stay in the editor after I save the template.

## Current Behavior
I have the [before] and [/before] tag at the top of a template and [after] and [/after] to wrap around a closing div. When I save the template, the output on the frontend is OK. But the editor in the Pod Template editor doesn't show the conditional tags any more. When I save this again, the condition Before and After are missing again at the front. 

This might be due to conflicting plugins that use the CodeMirror. I checked with other plugins. We use both [WPML](http://wpml.org/) and [WP All Import](www.wpallimport.com/), who use CodeMirror as well. Deactivating these plugins does not change the behaviour of the Pod Template editor.

 

## Steps to Reproduce (for bugs)

1. Install WPML and WP All import plugins
2. Make a Pod Template and use the [before] and [after] template
3. Save the template

## WordPress Environment

<details>
WordPress Version: 4.9.8

PHP Version: 7.2.9

MySQL Version: 5.7.23

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Corporate Pro

Currently Active Plugins:

    Admin Columns Pro: 4.3.8
    Admin Menu Editor: 1.8.5
    Admin Post Navigation: 2.1
    Business Profile: 1.1.4
    Debug Bar: 0.9
    Display Posts Shortcode: 2.9.0
    Fast Velocity Minify: 2.3.5
    GDPR Cookie Consent: 1.6.7
    Genesis Portfolio Pro: 1.2.0
    Genesis Simple Share: 1.1.1
    Genesis Testimonial Slider: 1.2.5
    Genesis Visual Hook Guide: 1.0.0
    Genesis Widget Column Classes: 1.2.4.1
    Gutenberg: 3.9.0
    HappyForms: 1.6.6
    Icon Widget: 1.1.0
    JSON Basic Authentication: 0.1
    Kint Debugger: 1.2
    Pods - Custom Content Types and Fields: 2.7.9
    Query Monitor: 3.1.1
    SEO Slider: 1.0.3
    Shortcode Cleaner: 1.1.5
    Show Git Branch: 1.0
    Simple Social Icons: 2.0.1
    SyntaxHighlighter Evolved: 3.2.1
    WP Featherlight: 1.3.0
    WP Migrate DB: 1.0.4
    WPML Multilingual CMS: 4.0.6
    WPML String Translation: 2.8.6
    WPML Translation Management: 2.6.6
    Yoast SEO: 8.3

</details>

## Pods Package Export (helpful!)

[pods_pressrelease.txt](https://github.com/pods-framework/pods/files/2449783/pods_pressrelease.txt)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Is this still relevant? I can't reproduce.

**Comment by JoryHogeveen** [comment]
Closing topic, too old and not reproduceable, probably not a bug anymore.
