### ISSUE TITLE
SimplePie DATE.PHP Parsing error on Pods Admin, Help Screen

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5171]
**Describe the bug**
On Pods Help page I see 20 times this PHP Warning:

“Warning: A non-numeric value encountered in /data/web/virtuals/189768/virtual/www/wp-includes/SimplePie/Parse/Date.php on line 694”

This spams about 20 times on the Pods Admin, Help Screen. Not sure what might be calling it, but it doesn't look good.

**To Reproduce**
1. Go to Pods Admin, Help on a clean Pods Installation
2. You'll see the spammed errors.

**Expected behavior**
This should not be happening.

**Screenshots**
![screenshot 2018-10-15 09 43 48](https://user-images.githubusercontent.com/3052875/46954531-dd1d7a80-d05e-11e8-8e34-e09b9ae46300.png)

## Pods Version
Please provide the version of Pods you are running: Pods 2.7.9, WP 4.9.8

Linked from https://wordpress.org/support/topic/php-warning-on-pods-help-page/

**Comment by pglewis** [comment]
I've researched this and it appears to be a WordPress bug: #4363
