### ISSUE TITLE
Missing field types in admin field edit dropdown in Firefox

### ISSUE THREAD

**Issue by modelm** [pods-framework/pods#5173]
## Issue Overview
As discussed in https://podswp.slack.com/archives/C02SVLHQF/p1539810466000100.
Firefox 62.0.3 does not display all field types when editing a pod to add a new field in the admin dashboard. Safari 12.0 does show them all.

## Expected Behavior
Firefox should show the same field types as Safari (all of them).

Safari:
![image](https://user-images.githubusercontent.com/330857/47118123-5e7a3600-d234-11e8-8297-98aeb7470853.png)

## Current Behavior
Firefox:
![image](https://user-images.githubusercontent.com/330857/47117956-da27b300-d233-11e8-8fa4-a54556a03ddb.png)

## Steps to Reproduce (for bugs)
Install WordPress
Install Pods
Add a new pod
Add a field
Note that in Firefox, not all field types show up in the dropdown.

## Possible Solution
None yet determined.

## WordPress Environment

<details>

```
Debug Information

WordPress Version: 4.9.8

PHP Version: 7.2.9

MySQL Version: 5.5.5

Server Software: Apache/2.4.25 (Debian)

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /var/www/html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.9
```
</details>

**Comment by modelm** [comment]
This has fixed itself in FF 63.

**Comment by pglewis** [comment]
It has been a really long time since I've seen a weird browser bug, glad they got that glitch ironed out.
