### ISSUE TITLE
Same classes for pods pagination numbers links and labels links while using shortcode

### ISSUE THREAD

**Issue by MyleneLapierre** [pods-framework/pods#5179]
## Issue Overview
The pagination HTML code rendered by the shortcode use displays the same CLASSES for : 
- The next/previous, first/last page NUMBERS and
- The "Next >", "< Previous", "First" and "Last" LABELS
It's difficult then to style those items separatly or to make the page numbers displayed without the next/previous/first/last labels....

## Expected Behavior
It would be great if the HTML rendering of the function called by the shortcode would give as least one different class to those items so we can style them individually.
Ex : 
Actual HTML rendering for the first page links :
"a href="/accueil/medias/?pg=1" class="pods-pagination-number pods-pagination-first ">« First</a		
[...]
a href="/accueil/medias/?pg=1" class="pods-pagination-number pods-pagination-first  ">1</a"

Versus the Ideal HTML rendering for the first page links :

"a href="/accueil/medias/?pg=1" class="pods-pagination-number pods-pagination-first PODS-PAGINATION-FIRST-LABEL ">« First</a 		
[...]
a href="/accueil/medias/?pg=1" class="pods-pagination-number pods-pagination-first PODS-PAGINATION-FIRST-NUMBER  ">1</a"

**Comment by jimtrue** [comment]
@nicdford Can you look at this one?

**Comment by JoryHogeveen** [comment]
@jimtrue @MyleneLapierre 
Please check patch #5979 and let me know!
