### ISSUE TITLE
"Full" missing from "Gallery image size" options

### ISSUE THREAD

**Issue by swinggraphics** [pods-framework/pods#5185]
**Describe the bug**
"Full" is missing from the list of "Gallery image size" options.

**To Reproduce**
1. Create a field of type "File / Image / Video".
2. Click on "Additional Field Options" and check "Output as a WP Gallery".
3. Click menu next to "Gallery image size".

**Expected behavior**
Menu should include "Full". 
As described in [Gallery Shortcode](https://codex.wordpress.org/Gallery_Shortcode), "size" can be any valid image size name. The menu currently lists all default and custom image sizes except for Full.

## Pods Version
2.7.9

## WordPress Environment
<details>
```
WordPress Version: 4.9.8

PHP Version: 7.2.8

MySQL Version: 5.7.23

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: No
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /Users/greg/Sites/Seans/wordpress/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Sean's Landscaping

Currently Active Plugins:

    Gutenberg: 4.1.1
    Pods - Custom Content Types and Fields: 2.7.9
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by jimtrue** [comment]
@swinggraphics The Gallery Size items are defined by the Media Image Sizes in your Theme. What theme are you using and can you verify under Settings, Media the image sizes defined?

**Comment by swinggraphics** [comment]
"Full" is a default size, not requiring definition in any theme. For testing purposes, I'm using Twentyseventeen. 

I have found a workaround for now:

`add_filter( 'pods_form_ui_field_pick_data_image_sizes', function( $data ){
	$data[ 'full' ] = 'Full';
	return $data;
} );`

**Comment by jimtrue** [comment]
@swinggraphics I'd agree with that (it is default), but wasn't sure if a theme could de-register any of those particular image sizes. You confirmed with Twenty-Seventeen.

I also just validated with my own recently loaded installation:
![screenshot 2018-10-31 07 48 19](https://user-images.githubusercontent.com/3052875/47786222-785e5300-dce1-11e8-8e6a-a793224687bd.png)

@JoryHogeveen You created this implementation: Can you look into this one?
