### ISSUE TITLE
PHP Notice: Undefined index: HTTP_HOST in general.php on line 577

### ISSUE THREAD

**Issue by besweeet** [pods-framework/pods#5186]
## Issue Overview

I checked my PHP log and noticed over 50,000 identical lines. Example:
`[02-Nov-2018 13:50:05 UTC] PHP Notice:  Undefined index: HTTP_HOST in \wp-content\plugins\pods\includes\general.php on line 577`

Pods seems to work fine so I don't know if I should be concerned about this error or not. In any case, it's quickly filling up the PHP log every four-to-five seconds.

## WordPress Environment

<details>
```
WordPress Version: 4.9.8

PHP Version: 7.2.7

MySQL Version: 8.0.13

Server Software: Microsoft-IIS/10.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

Session Save Path: \temp

Session Save Path Exists: Yes

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: \wp-content\plugins\pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Superior Vision

Currently Active Plugins:

All In One SEO Pack: 2.9.1
Automatic Copyright Year: 1.0
Better Search Replace: 1.3.2
Browser Theme Color: 1.2
Custom Login Page Customizer: 2.0.1
Elementor: 2.2.7
Elementor Pro: 2.1.11
Google Analytics Dashboard for WP (GADWP): 5.3.5
One Click Accessibility: 2.0.3
Per page head: 1.4.2
Pods - Custom Content Types and Fields: 2.7.9
PopBox For Elementor: 1.0.7
Really Simple SSL: 3.1.1
Redirection: 3.5
Safe SVG: 1.7.1
Search & Replace: 3.1.2
WP Super Cache: 1.6.4
```
</details>

**Comment by adriangordon1231** [comment]
Did you ever figure out why this is happening and/or how to stop it?

**Comment by besweeet** [comment]
> Did you ever figure out why this is happening and/or how to stop it?

I can't recall exactly what happened. I think it may have resolved itself.

**Comment by JoryHogeveen** [comment]
`HTTP_HOST` is actually a server variable that should always be there, if it isn't then please provide more info about your server configuration.

More info here: https://www.php.net/manual/en/reserved.variables.server.php
