### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by ebrady8** [pods-framework/pods#5195]
**Describe the bug**

I am creating a website for someone in my department and I have added PODS to their site. I have them login and they are unable to see the PODS item in the WP menu. How can I get them access to the PODS Admin item in the WP menu?

**Comment by jamesgol** [comment]
By default the capability required to see the Pods admin interface is 'delete_users' so your user would need admin access or some higher level permissions.

**Comment by JoryHogeveen** [comment]
@jamesgol @ebrady8 
The capability `pods` should be sufficient as well but doesn't provide all options like settings and selecting components.
