### ISSUE TITLE
WYSIWYG/TinyMCE does not save using the Gutenberg editor

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#5197]
Everything displays properly but no changes are saved on publish/update.

**Comment by lkraav** [comment]
Yep, I've noticed this in the wild.

**Comment by modelm** [comment]
I'm using this workaround to make WYSIWYG fields save correctly when using Gutenberg:

`wp.data.subscribe( tinyMCE.triggerSave );`

**Comment by pglewis** [comment]
Also for reference: https://github.com/WordPress/gutenberg/issues/7176

**Comment by pglewis** [comment]
> I'm using this workaround to make WYSIWYG fields save correctly when using Gutenberg:
> 
> `wp.data.subscribe( tinyMCE.triggerSave );`

You may want to test that this doesn't muck things up if any of your TinyMCE instances have the "text" tab selected.

**Comment by modelm** [comment]
Thanks for the heads up - I tried it and didn't notice any problems, text & markup seem to save just fine whether text or visual mode is active.

**Comment by pglewis** [comment]
Good news, I'll be testing a bunch of scenarios myself.  We're determined to iron out all the basic compat issues with Gb in 2.7.10.

**Comment by pglewis** [comment]
There is a fix on the Gutenberg side that hopefully results in this issue evaporating without any action needed.  Fingers crossed.
