### ISSUE TITLE
<p> tags are not appearing in WP Rest API 

### ISSUE THREAD

**Issue by enosh94** [pods-framework/pods#5198]
when i use WYSIWYG Editor in a custom field, It won't return <p> tags in WP Rest API.  (wpautop option is enabled to the field in POD).

Json Messsage in Rest API  for the field -         `"summary": "tsdfwes"`

And 

I want it to be like  `"summary": "<p>tsdfwes</p>"`

Default content (not a custom field) in wordpress returns P tags properly.  I just typed `ttt `in the WYSIWYG Editor and it returns following response to REST API
```
        "content": {
            "rendered": "<p>tttt</p>\n", }
```

**Comment by fueguino84** [comment]
Were you able to fix it? I am experiencing the same problem.

**Comment by sc0ttkclark** [comment]
There's a new option in Pods 2.9.4 that allows you to specify which field mode you want to use. By default, Pods always sends the raw values through the REST API to work with. That isn't flexible for cases like you have and so now there are three field modes available:

* Raw values
* Rendered values
* Both raw and rendered values `{value: raw_value, rendered: rendered_value}`

<img width="1050" alt="Screen Shot 2022-09-20 at 10 43 38 PM" src="https://user-images.githubusercontent.com/709662/191409664-c9374781-fcc3-424f-93c3-57dd82c65341.png">

**Comment by sc0ttkclark** [comment]
Introduced in: a4d69e36ddb27004299e174eb8115dee2bdf139d
