### ISSUE TITLE
Show bi-directional status in fields admin

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5200]
Currently the relationships show the related object in the field list but it doesn't show whether it's bi-directional. You need to edit the field to see that.
I think it would be handy to show this as well.

Example:
![image](https://user-images.githubusercontent.com/826148/48633668-0fa2f600-e9c4-11e8-8b0d-cd329e2953c6.png)

**Comment by JoryHogeveen** [comment]
Checked the code. The actual name of the bi-directional field is only fetched after a field is "opened" for editing. So on page load I can't get the field name etc. from the bi-directional field.
This is probably due to performance so I think it's better to leave that as is.

**Comment by pglewis** [comment]
Closed via #5201
