### ISSUE TITLE
Gutenberg Compatibility: Autocomplete or List View Post Search breaks up/down scroll after returning focus

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5213]
**Describe the bug**
Autocomplete and List View use the 'Search for related posts' search screen. After selecting a post, after focus is returned to the page, the up/down scroll on the Gutenberg page no longer works. Refreshing the page fixes it, but that's not a good solution. Tested on both WP5.0 and Gutenberg plugin.

**To Reproduce**
1. Use a List View &/or Autocomplete relationship field
2. Make sure your Post type uses the Gutenberg Editor
3. Also make sure your page has enough content in it to require a scroll
4. Search for a post and select it, when focus returns to the Gutenberg editor, the scroll will no longer work.

**Expected behavior**
Scroll should work normally when focus returns.

## Pods Version
2.7.10 alpha

**Comment by pglewis** [comment]
This only happens with List View for me, I could not reproduce with the vanilla autocomplete.
