### ISSUE TITLE
Slider input range 0.5

### ISSUE THREAD

**Issue by JLNNN** [pods-framework/pods#5215]
**Describe the bug**
When entering 0.5 as slider step and choosing 1.5 in backend form, it just saves the number as 15. Even when I'm activating "use decimals" with length 1 it saves the value as 15.0. What am I doing wrong?

I'm using this to save ratings from 0.5 to 5 but it's not working as expected :/

Have a nice day,
  Julian

**Expected behavior**
Save range value with dots.

## Pods Version
2.7.9

## WordPress Environment
<details>
```
WordPress Version: 4.9.8

PHP Version: 5.6.38

MySQL Version: 5.1.73

Server Software: Apache/2.2.15 (CentOS)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

Session Save Path: /var/lib/php-sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /path/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Zerif Lite

Currently Active Plugins:

Antispam Bee: 2.9.0
Cachify: 2.2.4
Check and Enable GZIP compression: 1.1.11
Cookie Consent: 2.3.11
Email Address Encoder: 1.0.9
Google XML Sitemaps: 4.0.9
menu shortcode: 1.0
Minify HTML: 1.99
Open Graph for Facebook, Google+ and Twitter Card Tags: 2.2.4.2
Pods - Custom Content Types and Fields: 2.7.9
Simple Lightbox: 2.7.0
Statify: 1.6.3
WP Google Fonts: v3.1.4
WP Sitemap Page: 1.6.1
```
</details>

**Comment by JLNNN** [comment]
By the way it's working correctly when altering the content of table `wp_postmeta` field `meta_value` directly. I guess the problem is when saving the data to the database.
By the way 2: The same is happening when using currency.

**Comment by JLNNN** [comment]
Any updates on this? Or can you provide a workaround?

**Comment by pglewis** [comment]
This does not reproduce with the "1,234.56" format but does with the "1.234,56" format

**Comment by JoryHogeveen** [comment]
@JLNNN please test #5439 as well for your issue!
