### ISSUE TITLE
Incorrect use of `the_title` filter in pick field

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5236]
When using the AMP plugin the pick field results an error.
The `the_title` filter requires two parameters according to the WP documentation. The second should be the post ID. This doesn't happen with the pick field apparently.

The new AMP plugin required that second parameter, which is totally fine since that is how the filter is provided in WP Core.

https://codex.wordpress.org/Plugin_API/Filter_Reference/the_title

Stacktrace:
```
mod_fcgid: stderr: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function AMP_Validated_URL_Post_Type::filter_the_title_in_post_list_table(), 1 passed in /wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /wp-content/plugins/amp/includes/validation/class-amp-validated-url-post-type.php:1897, referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
Stack trace:, referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
#0 /wp-includes/class-wp-hook.php(286): AMP_Validated_URL_Post_Type::filter_the_title_in_post_list_table('TITLE'), referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
#1 /wp-includes/plugin.php(203): WP_Hook->apply_filters('TITLE', Array), referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
#2 /wp-content/plugins/pods/classes/fields/pick.php(2346): apply_filters('the_title', 'TITLE'), referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
#3 /wp-content/plugins/pods/classes/fields/pick.php(1672): PodsField_Pick->get_object_data(Array), referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
#4 /wp-content/plugins/amp/includes/validation/class-amp-validated-url-post-type.php on line 1897, referer: https://www.domain.nl/wp-admin/post-new.php?post_type=article
```

**Comment by robpie-de** [comment]
got the same error by adding this:

`add_filter( 'the_title', 'woo_title_order_received', 11, 2 );
function woo_title_order_received( $title, $id ) {
        if ( function_exists( 'is_order_received_page' ) &&
             is_order_received_page() && get_the_ID() === $id ) {
                $title = "Thank you for your order! :)";
        }
        return $title;
}`

to the functions.php an go to the edit pod item page on backend

**Comment by JoryHogeveen** [comment]
Just added a local `the_title` filter again with two parameters and I cannot reproduce this issue anymore.
Either something has changed in Pods or this wasn't a Pods issue at all (I think it was the latter).

@robpie-de You already opened another issue where I replied the same.

Closing this one!
