### ISSUE TITLE
Date field corrupted when using custom format

### ISSUE THREAD

**Issue by tomas-eklund** [pods-framework/pods#5238]
## Issue Overview
When using the Date type Pods field with custom date format, the "Date format for input" parameter seems to be parsed or used wrong. 

According to the tooltip for the input field (it links to the [jQuery UI datepicker documentation](https://api.jqueryui.com/datepicker/)) the format string "yy-mm-dd" should mean "year (four digit)"-"month of year (two digit)"-"day of month (two digit)", which is also known as ISO_8601 date format.

However, somehow Pods seems to interpret the "mm" in the format string as "current minute" when displaying the date in the admin UI and the month is always replaced with 12 (december) when saving to database.

![image](https://user-images.githubusercontent.com/1409791/49788654-2e2db000-fd2a-11e8-931c-b9de8cfc92b0.png)

## Expected Behavior
The Pods UI should honor the format entered and not mangle the date. 

## Current Behavior
The entered date is corrupted. No matter if I use the datepicker or enter the date using the keyboard, the date is always saved wrong to the database. 
Let's say I enter the date 2019-01-24, this is saved as 2019-12-24. The month is always replaced with 12. 

Also when the date is read from the database, it is displayed wrong. 
If the date in the database is 2019-01-24, this is displayed in the admin UI as 2019-(current minute)-24. 

![image](https://user-images.githubusercontent.com/1409791/49788093-b7dc7e00-fd28-11e8-8709-bba08c4340d1.png)

## Steps to Reproduce (for bugs)

I've created a simple pod for events (calendar).
![image](https://user-images.githubusercontent.com/1409791/49786032-aee8ae00-fd22-11e8-9426-625d5e2d32b2.png)

The pod has a field for the event date. The type of this field is Date.
![image](https://user-images.githubusercontent.com/1409791/49786080-d5a6e480-fd22-11e8-9d1e-6ba3a85b3b66.png)

Under "Additional Field Options" I choose "Custom format".
The "Date format for input" I set to "yy-mm-dd" according to the jQuery UI Datepicker specifications.
![image](https://user-images.githubusercontent.com/1409791/49786167-2a4a5f80-fd23-11e8-85bf-aaefa8894485.png)

When I try to add an event with the date 2019-01-24 (January, 24) and click Publish...
![image](https://user-images.githubusercontent.com/1409791/49785740-ca06ee00-fd21-11e8-9e4b-25b092727dd1.png)

...the date is displayed wrong afterwards. The month (01) is replaced with the current minute of the clock. In this case the time was 07:50 so the month of the date was replaced with 50, resulting in a bogus date of 2019-50-24. If I wait a minute and refresh the page the date is displayed as 2019-51-24.
![image](https://user-images.githubusercontent.com/1409791/49785777-edca3400-fd21-11e8-8a7c-cc6e9a4e3904.png)

In the database the date is saved as 2019-12-24. My guess is that the date is sanitized and any month greater than 12 is simply truncated to 12.
![image](https://user-images.githubusercontent.com/1409791/49786440-22d78600-fd24-11e8-89ab-319489ca759b.png)

This has been verified on a fresh install of WordPress 4.9.8 with no other plugins than the latest version of Pods installed. Twenty Seventeen theme. A login to a demo site has been sent to Jim True. 

## WordPress Environment

<details>
WordPress Version: 4.9.8

PHP Version: 7.2.13

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

Session Save Path: /var/lib/php/session

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 5.937M

Current Memory Usage (real): 8.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/vhosts/blyberg.se/httpdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.11
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.11","build":1544518532},"pods":{"5":{"id":5,"name":"my-event","label":"Events","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"event-date":{"id":6,"name":"event-date","label":"Date","description":"","help":"","class":"","type":"date","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"custom","date_format_custom":"j M","date_format_custom_js":"yy-mm-dd","date_format":"mdy","date_allow_empty":"0","date_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0"},"event-time":{"id":7,"name":"event-time","label":"Time","description":"","help":"","class":"","type":"time","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","time_type":"24","time_format":"h_mma","time_format_24":"hh_mm","time_allow_empty":"1","time_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","time_repeatable":"0","time_format_custom":"","time_format_custom_js":""},"event-title":{"id":8,"name":"event-title","label":"Title","description":"","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Event","public":"1","show_ui":"1","supports_title":"0","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"my-event","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

**Comment by tomas-eklund** [comment]
In `pods/classes/fields/datetime.php` there is a method `convert_format()` which most certainly has a bug. 

It tries to map PHP date format strings to the jQueryUI counterpart. For example it can convert `Y-m-d` (PHP) to `yy-mm-dd` (jQueryUI) which is the ISO date format. But the method messes up completely when trying to do the opposite. When converting `yy-mm-dd` (jQueryUI) to PHP notation it returns `Y-i-d`!

It uses a dictionary mapping the PHP date and time format characters (single letter) to the jQueryUI (one or two letters) format strings. However, in jQueryUI the format string "mm" can stand for "month of year (two digit)" **OR** "minute with leading zero". So when the dictionary is flipped "mm" is always mapped to the PHP date format character "i" which is "minutes with leading zeros".

This explains why Pods displays the wrong date when using custom date formats. Not sure why the wrong date (month) is saved to the database though.

**Comment by tomas-eklund** [comment]
I've verified that commenting out line 797 in datetime.php makes Pods display the right month. The right month is also saved to the database. 

However, one needs to "Enable HTML5 Input field" for any Time type fields since it messes up the jQueryUI formatting of minutes.
```
	public function convert_format( $source_format, $args = array() ) {
		...
		// Keep keys and values sorted by string length.
		$symbols = array(
			...
			// Minute
			//'i' => 'mm', <-- line 797
```
Of course, a proper solution is much more complex than this. The ambiguity of the jQueryUI time and date format strings is the real problem and I suggest that PHP format strings are used throughout the application, mapping only internally to jQueryUI format whenever needed.

**Comment by sc0ttkclark** [comment]
Well you seem to have found a very interesting bug! I never realized mm was used in both the date and time formats for datepicker / timepicker, seems like a conflict they could have avoided when they made it :/

Converting the format strings and switching entirely to PHP format would be nice but problematic for people with packages and registration via code. It's hard to know exactly which letter should be migrated to which. This is a sticky situation, but I think there's an easy solution (for the month vs minute issue) beyond commenting it out. I think we can use the context we have in the field classes to determine whether or not the format is using the date OR time. Then convert those separately using separate `$symbols` arrays, one for date and one for time formats.

As for the HTML5 issue, I need to reread a bit more to see if I totally understand what's happening there.

**Comment by tomas-eklund** [comment]
@sc0ttkclark 
I just meant that IF you comment out the `'i' => 'mm'` line in the datetime.php file, then you must not use the jQueryUI time picker. Because that will result in this happening:

![image](https://user-images.githubusercontent.com/1409791/49814089-322cf280-fd69-11e8-82ac-bef5074ce507.png)

As far as I understand, you can only disable the jQueryUI time picker by enabling the HTML5 time picker instead.

I've actually done this on a site as a temporary workaround.

**Comment by tomas-eklund** [comment]
Just curious. Any updates on this?

**Comment by JoryHogeveen** [comment]
@tomas-eklund 
This might be fixed in the latest release. Can you verify?

**Comment by JoryHogeveen** [comment]
Hello @tomas-eklund 

Tested your package and found that your display format (`yy-mm-dd`) is not a correct PHP date format.
Assuming you wanted 19-09-13 (year-month-day, all in 2 digits) your format should be: `y-m-d`.
If you look at the help text (see questionmark in the field option label) you'll see that the input should be in PHP date format, not jQuery format.

As for your issue with the timepicker, I can't seem to replicate this with your package.

**Comment by JoryHogeveen** [comment]
> I suggest that PHP format strings are used throughout the application, mapping only internally to jQueryUI format whenever needed.

@sc0ttkclark What do you think? This would probably fix our issues but will break backwards compatibility when users have defined their own formats in jQueryUI.

**Comment by tomas-eklund** [comment]
> As for your issue with the timepicker, I can't seem to replicate this with your package.

I don't really have a problem with the timepicker. The [remark](https://github.com/pods-framework/pods/issues/5238#issuecomment-446266042) was with regards to my hacky workaround, commenting out [the specified line in datetime.php](https://github.com/pods-framework/pods/blob/02dbf2fb5756ac3dae00b35c3211ae4ecf0a874b/classes/fields/datetime.php#L826). The problem is of course expected and the workaround for _that_ is to not use the jQuery timepicker, but the HTML5 one. I'm afraid that me even mentioning the stupid workaround and its consequences has polluted this thread with irrelevant noise. For this I'm sorry.

**Comment by JoryHogeveen** [comment]
@tomas-eklund 
No problem, I was indeed reading this issue wrong. But I think I have found a fix for this and will add a PR in a few minutes for you to test and @sc0ttkclark to review.

**Comment by JoryHogeveen** [comment]
@tomas-eklund 
Can you please verify the PR is working for you too? I'd like to add this fix to the next maintenance release.
My tests are working.

**Comment by tomas-eklund** [comment]
Sorry for taking so long. I've been busy and had a working (albeit hacky) workaround in place on the client's site, so there was no rush to update. If the fix had come sooner, I would have updated Pods, tested the fix and responded more quickly. The fact that it took almost a year to fix a fairly well-researched bug, actually made me move away from Pods.

I've now updated Pods on the client's site, configured the Pod to use jQuery UI date and time pickers, and verified that the problem appears to be fixed. Thank you.
