### ISSUE TITLE
Block Editor Conversion for Pods Widgets

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5240]
**Is your feature request related to a problem? Please describe.**
Not related to a problem; this is part of Gutenberg/WP 5.0 Block Editor compatibility. Basically, converting our existing Pods Widgets into a Block or multiple blocks.

**Describe the solution you'd like**
Ideally, this should take advantage of the REST API to include field lookup from the Pods Object, so 2.8 might be a blocker. 

**Additional context**
This is a Starter Issue to include all the different things currently in the Pods Widgets and document what we're keeping/converting. Pods Single & List Widgets should be able to be 'combined' into one Block with a conditional check.

**Comment by damen02** [comment]
That would be a great feature! Any advance? Thanks :)

**Comment by sc0ttkclark** [comment]
Resolved in 2.8
