### ISSUE TITLE
Html parsing bug in CPT pods > Manage fields > right column for Relationship fields

### ISSUE THREAD

**Issue by remcokalf** [pods-framework/pods#5246]
In Pods Admin > Edit Pods > CPT Pod, in the Manage Fields tab, there is a display /  html parsing bug for relationship fields. 
In the right 'Field type' column, html is visible:
For example:

Relationship (Bi-directional Field) 
› Destinations (destinations) <small>(Post Type)</small>

## Pods Version
2.7.11

## WordPress Environment
Wp 4.9.8

**Comment by jimtrue** [comment]
@remcokalf Can you provide a screenshot?

**Comment by remcokalf** [comment]
![schermafbeelding 2018-12-14 om 12 50 03](https://user-images.githubusercontent.com/4609920/50002400-4d357780-ffa0-11e8-8324-04f154634100.png)

**Comment by jimtrue** [comment]
@remcokalf LOL, don't you hate when that happens? I see _exactly_ what you're talking about. I'll get this into the bugs list.

**Comment by pglewis** [comment]
PR: #5256
