### ISSUE TITLE
Please Add Indonesian Currency

### ISSUE THREAD

**Issue by jprumekso** [pods-framework/pods#5247]
Hi, thanks for developing such a wonderful plugin. This plugin really help me a lot to create custom Wordpress site easily. Can you add Indonesian currency too? Indonesian Rupiah (IDR) -> Rp 1.000,00
Point for thousands, and comma for decimals, no space between the "Rp" and the number.

Thank you so much.

**Comment by sc0ttkclark** [comment]
Add a PR for this
