### ISSUE TITLE
'bypass_helpers' => false in save_pod_item doesn't work 

### ISSUE THREAD

**Issue by th-santos** [pods-framework/pods#5254]
## Issue Overview

When using `save_pod_item` and explicitly setting `'bypass_helpers' => false`, post-save helper will be bypassed (pre-save helper not tested).

## Expected Behavior

 

Explicitly setting `'bypass_helpers' => false` (default value) should not bypassed post-save helper*, as documented in [https://pods.io/docs/code/pods-api/save-pod-item/](https://pods.io/docs/code/pods-api/save-pod-item/).

| Option         	| Type   	| Default 	| Details                                                      	|
|----------------	|--------	|---------	|--------------------------------------------------------------	|
| bypass_helpers 	| (bool) 	| false   	| Set to true to bypass running pre-save and post-save helpers 	|

\* pre-saved helper not tested.

## Current Behavior

 

`'bypass_helpers' => false` is bypassing `pods_api_post_save_pod_item_{podname}`. 

When `'bypass_helpers' => false` is removed, `pods_api_post_save_pod_item_{podname}` is not bypassed.

## Steps to Reproduce (for bugs)

Snippet to reproduce the bug:
```
$params = array(
  'pod' => 'post',
  'id' => $post_id,
  'data' => array(
    "field_name" => $value
  ) ,
  'bypass_helpers' => false
);
// sanitize and save
$params = pods_sanitize($params);
pods_api()->save_pod_item($params);
```

## Possible Solution

Something here ([https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php](https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php)). I don't know :(

**Comment by jamesgol** [comment]
I was definitely able to reproduce this.  The PR #5480 solves the problem.  The pods_str_replace() function was called on $params and it was replacing false with ''
