### ISSUE TITLE
Targetting speciffic pods on creation and switching title field for content of a field

### ISSUE THREAD

**Issue by Ragevortex** [pods-framework/pods#5258]
## Issue Overview

Im using this as a base for my example
/*script for auto publishing pods, goes in the functions.php */

add_filter('pods_api_post_create_pod_item', 'sod_auto_publish_pod');

function sod_auto_publish_pod($pieces) {
    //grab the id of the newly created pod
    $id = $pieces['params']->id;
    $new_post = array();
    $new_post['ID'] = $id; //id del pod
    
    //set the post status to publish
    $new_post['post_status'] = 'publish'; //setear como publicado puede cambiarse a draft tambien
    $new_post['post_title'] = $id;//special modification to change the post title to the ID
    // Update the post
    wp_update_post( $new_post );
    
    return $pieces;
}

/*

## Expected Behavior

 

I'd like  to be able to instead of targetting all published pods and swapping the id for their title. I'd like to be able to target a speciffic pod and swap their title to whatever is in a speciffic field.
For example:
I have a pod called Abreviatura with a field abbr which contains 4 characters. I'd like to use the same exact four characters as the title of the pod being published. I have other pods which I'd like to have the same ressult so that I can use the provided shortcodes to display correctly the information. I'm working this in wordpress.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by jamesgol** [comment]
I'm not sure exactly what you are looking for.  If you want specific code to only handle a specific Pod you could use one of the other hooks that has the Pod name appended.  You are using 'pods_api_post_create_pod_item' but you could use 'pods_api_post_create_pod_item_Abreviatura'

**Comment by jimtrue** [comment]
That is the solution. Target the specific pod with the built in targeting, `_pod_item_{podname}`. Closing this ticket
