### ISSUE TITLE
Create Pods from Existing Table 

### ISSUE THREAD

**Issue by hanabadler** [pods-framework/pods#5265]
**Is your feature request related to a problem? Please describe.**
I have an existing database with several tables that contains data without any references or foreign keys.i would like to create a pods for these tables . several tables contains more than 80 fields. i would like to create the pods automaticly and not manully

**Describe the solution you'd like**
i would like a screen in pods managemnt which ask the table name in the database, and create the pods from it.

**Describe alternatives you've considered**
other alternative is to create the json object only, and after it import that json

**Additional context**

**Comment by quasel** [comment]
I think that's out of scope for pods - an workaround might be to take a look at our import/export for the config and maybe create one yourself… but it might be to late for this suggestion ^^
