### ISSUE TITLE
Extended Post Types or Taxonomy Should say 'Extended' in the Pods Admin List

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5273]
**Describe the bug**

When you're in the Pods Admin, Edit Pods (or Manage Pods) list, Extended Custom Post Types or Taxonomies do not have any kind of indicator that they are 'extended'. That would be helpful in the display.

**Comment by quasel** [comment]
is this still an issue? I see the Type Columns - Taxonomy (extended), Post Type (extended) and a filterbar on top? - you can reopen it if I did misunderstand it ^^
