### ISSUE TITLE
Can’t create advanced post entry with emoji (general encoding problem)

### ISSUE THREAD

**Issue by Axinet** [pods-framework/pods#5276]
## Issue Overview
Placing any emoji (like 😉) in any text field of Advanced Custom Post Type (stored in separate tables) results in error message "Error: <pod name> not found." after saving new object (or existing object is not updated with no error message).

## Expected Behavior
Emoji characters should be supported in text fields like any other characters.

## Current Behavior
Can't use emoji in text fields.

## Steps to Reproduce (for bugs)
1. Create new Pod and set type to "Advanced Content Type (separate from WP, blank slate, in its own table)"
2. Accept existing fields and save pod e.g. "Emoji problem". 
3. Create new entry of type "Emoji problem" and use title like "With emoji 😉" and save
4. The error should be displayed and there should be no new object of type "Emoji problem"

## Possible Solution
After investigating the problem it looks like the error is returned by a database `Incorrect string value: 'With emoji \xF0\x9F\x98\x89' for column 'name'`. 
It is due to the character set used on text fields as well as whole tables created for advanced custom post types like the wp_pods_emoji_problem. Despite the database encoding is set to `utf8mb4_polish_ci ` and in wp-config.php there is a line `define('DB_CHARSET', 'utf8mb4');` the tables created by pods plugin (and all text fields) have character set configured as `utf8_general_ci`. This result with incomplete support for multibyte characters in MySql/MariaDB databases.
Native WordPress tables in that configuration use `utf8mb4_unicode_520_ci` encoding.
Tables and text fields for Advanced Custom Post Types should use same encoding as native WordPress tables.

## WordPress Environment

<details>
```
WordPress Version: 5.0.3
PHP Version: 7.1.24
MySQL Version: 5.7.14
Server Software: Apache/2.4.23 (Win32) PHP/7.1.24
WPDB Prefix: wp_
WP Multisite Mode: No
Pods Network-Wide Activated: No
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Plugins:
    Pods - Custom Content Types and Fields: 2.7.12
```
</details>

## Workaround or Alternate Solution Until Bug is Addressed
After creating pod manually change encoding in the database. Watch out for problems with a default value for `created` field.

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/blob/2.x/classes/PodsAPI.php#L2076

Currently Pods uses charset utf8, it should get this from the config like it does for other tables during install like: https://github.com/pods-framework/pods/blob/2.x/sql/upgrade/PodsUpgrade.php#L66

**Comment by charles-ctrl** [comment]
I'm struggling with this issue at the moment. If a custom field contains an emoji, it shows up in WP as empty. Has it been fixed? Or is there a workaround?
