### ISSUE TITLE
Versioned tag names are not compatible with Composer

### ISSUE THREAD

**Issue by simensen** [pods-framework/pods#5278]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/pods-framework/pods
2. Click on `Branch: 2.x`
3. Click on `tags`
4. See valid Composer tags: `2.7.9` and `2.7.10`
5. See invalid Composer tags: `2.x/2.7.11` and `2.x/2.7.12`

**Expected behavior**

I would expect (and so would Composer) the tag for version 2.7.12 to be `2.7.12` and not `2.x/2.7.12`.

**Screenshots**

You can see that 2.7.9 and 2.7.10 are the only versions listed as installable [on Packagist](https://packagist.org/packages/pods-framework/pods):

![image](https://user-images.githubusercontent.com/191200/51554309-9cda4f00-1e3a-11e9-8c84-e6beba660ed6.png)

You can see from the tag list [on GitHub](https://github.com/pods-framework/pods) that this looks to be an intentional naming scheme and that `2.7.9` and `2.7.10` were merely... accidents?

![image](https://user-images.githubusercontent.com/191200/51554375-c4c9b280-1e3a-11e9-9a15-1e261737543e.png)

## Pods Version

I'm using `"pods-framework/pods": "^2.7"` but it won't install or upgraded past 2.7.10 due to the fact that Composer does not think `2.x/2.7.11` and `2.x/2.7.11` are versions.

## WordPress Environment

<details>

```
Debug Information
WordPress Version: 4.9.9

PHP Version: 7.1.23

MySQL Version: 5.5.5

Server Software: nginx

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Session Save Path: /tmp/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 200000

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 10.914M

Current Memory Usage (real): 2.000M

Pods Network-Wide Activated: No

Pods Install Location: /app/web/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Blog Blackfire

Currently Active Plugins:

Crayon Syntax Highlighter: 2.8.4
Edit Flow: 0.8.2
Enable oEmbed Discovery: 1.0.0
Intercom: 2.6.1
Jetpack by WordPress.com: 6.9
Pods - Custom Content Types and Fields: 2.7.10
Regenerate Thumbnails: 3.1.0
The Events Calendar: 4.7.4
UpdraftPlus - Backup/Restore: 2.16.4.0
W3 Total Cache: 0.9.7
```

</details>

**Possible Workaround**
I could possibly install via wpackagist but it seems like installing it via Packagist directly would be preferred. I don't want to change this in my project just yet if the pods team is OK rolling 2.7.13 soon using tag `2.7.13` or `v2.7.13` soon. :)

Also, note, I don't think this would or should require the old tags to be removed. Just that going forward new tags be in this format if you want to be compatible with Composer/Packagist.

**Comment by pglewis** [comment]
@sc0ttkclark was the last one to dig-in to the Composer stuff: https://github.com/pods-framework/pods/issues/5030#issuecomment-419732578

I was under the impression that things were ironed out for the recent releases and moving forward, maybe that post helps?  (Keeping in mind I'm personally ignorant on the Composer side of things)

**Comment by simensen** [comment]
Indeed, in the referenced comment by @sc0ttkclark, it mentions this: 

> ... I can confirm that the versions that pull in are only the tags without 2.x/ and 1.x/ prefixes. As a result, only versions going forward from 2.7.9+ will be available in Packagist, but I doubt that's going to be a problem.

It looks like `2.7.9` and `2.7.10` came in just fine, as stated in that comment. However, from `2.7.11` on, the tags started having the `2.x/...` prefix again.

I'm guessing someone either didn't know about the new tagging scheme or forgot the last few times around.

**Comment by pglewis** [comment]
> I'm guessing someone either didn't know about the new tagging scheme or forgot the last few times around.

It's possible we need to make some changes/additions to the instructions for the release process.  Those last two releases would be firmly on my shoulders as are most of the maintenance releases.  

I need to find the time to educate myself on what's needed for it to go right and what may have gone wrong, the primary hurdle is I don't use Composer myself and just plain ol' don't understand anything about these details yet.  Apologies for any inadvertent hiccups.

**Comment by simensen** [comment]
@pglewis It's all good. I hope I didn't sound too cranky or harsh. That was definitely not my intent. :)

If there are docs written somewhere on the release process that I can help update, let me know. For this particular problem, I would update the docs to say something along these lines:

Release tag names need to be in the format of `2.7.13` or `v2.7.13` in order for Composer to detect them as installable versions. Tags created like `2.x/2.7.13` will be ignored by Composer and should not be used.

**Comment by pglewis** [comment]
PR: #5292
