### ISSUE TITLE
Bug: Shortcode with error makes page uneditable in the Block Editor

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5279]
**Describe the bug**

If you use a shortcode in the Block Editor (Gutenberg) with an error in the shortcode, the error causes the block editor to automatically preview so the error takes focus and makes the page uneditable.

**To Reproduce**
1. Go to a page and use the Block Editor (instead of the Classic Editor)
2. Create a shortcode with an error (I used an orderby non-existent field)
3. The AutoSave will fail, you can try to preview, but editing in the block editor will no longer work.
4. You can edit it with the Classic Editor

**Expected behavior**
It should provide the SQL Error and fail gracefully

## Pods Version
Please provide the version of Pods you are running: 
Pods 2.7.12

**Possible Workaround**
Discussed with @sc0ttkclark: should add a shortcode_handler that wraps around the shortcode output, checks for error and provides a more useful message.

**Comment by quasel** [comment]
any update? seems important with the rise of Gutenberg?
