### ISSUE TITLE
$is_new_item parameter never TRUE in pods_api_post_save_pod_item_{podname} hook

### ISSUE THREAD

**Issue by Budapresst** [pods-framework/pods#5282]
**Describe the bug**
Hook fires, but $is_new_item parameter is either NULL or False (didn't check explicitly which value), but it is never True... even for truly new items added via wp-admin.

**To Reproduce**
1. create pod
2. add hook code and echo/save $is_new_item value somewhere referenceable
3. add new pod item in wp-admin
4. check $is_new_item value 

**Expected behavior**
$is_new_item parameter should equal True for newly added Pod items

**Screenshots**

## Pods Version
2.7.12

## WordPress Environment

<details>
```
WordPress Version: 5.0.3

PHP Version: 7.2.14

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea-php72

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: do_

WP Multisite Mode: No

WP Memory Limit: 256M

Current Memory Usage: 45.737M

Current Memory Usage (real): 26.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/doverhu/public_html/bosch/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: DoverBosch

Currently Active Plugins:

Brute Force Login Protection: 1.5.3
Disable Emojis: 1.2.0
Disable Post Via Email: 1.0.0
Disable Search: 1.1.0
Disable XML-RPC: 1.1.1
Duplicate Post: 3.2.2
EWWW Image Optimizer: 4.6.1
Header Cleanup: 1.2.0
Password Protected: 2.2.3
Pods - Custom Content Types and Fields: 2.7.12
Polylang: 2.5.1
Profile Builder: 2.9.5
Remove Dashboard Access: 1.1.3
Search by ID: 1.3
WordPress Importer: 0.6.4
WP-Sweep: 1.1.0
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
Can analyze post_date to determine "newness"...

**Comment by quasel** [comment]
Did you try pods_api_pre_save_pod_item_{podname} ? maybe after saving … well @sc0ttkclark do you know that out of your head?

**Comment by jamesgol** [comment]
I just tried to duplicate this on 2.7.12 as well as the most recent git version and could not duplicate the issue.  Are you properly setting up the filter?  If you don't specify the expected number of parameters then it will default to passing one and I suspect the others will be null.

**Comment by Budapresst** [comment]
@jamesgol  I just tested it as well on 2.7.15 and was unable to reproduce it.  I honestly can't remember much about this issue 8 months later, but I think I found a simple workaround at the time.  As it's working now, I'm going to close it out.  Maybe I made a late-night careless error with the number of parameters, but I sure hope not.  Thanks for testing it!
