### ISSUE TITLE
Pods function has no results

### ISSUE THREAD

**Issue by jnaklaas** [pods-framework/pods#5283]
**Describe the bug**
I have a pod with name "team_member". When using the pods function, it doesn't contain any posts. This is my code and output:

```php
$team_members = pods('team_member');
echo 'total: '. ($team_members->total()); //displays 'total: ' - no output from the function
if ( $team_members->total() > 0 ):
  while ( $team_members->fetch() ):
    echo 'hello'; //is never displayed
  endwhile;
endif;
```

When using `WP_Query` I do get the expected output:

```php
$args = (array('post_type' => 'team_member'));
$team_members = new WP_Query($args);
while ($team_members->have_posts()):
  $team_members->the_post();
  the_title(); //the title of each pod post is displayed
endwhile;
```

Why does the latter work, and the first doesn't?

**Comment by jimtrue** [comment]
You've opened the object, but you didn't give it any parameters, so it's basically just an object with no pointer at that point (like opening the WP_Query without any $args) . At a minimum, you want to set `$params = (array('limit' => '-1'));` and call the first line as `$team_members = pods('team_member',$params);`

https://pods.io/docs/code/pods/
https://pods.io/docs/code/pods/find/ << also very useful for passing all the query type parameters.

**Comment by jimtrue** [comment]
Did that work @jnaklaas ?

**Comment by jnaklaas** [comment]
It did, cheers!
