### ISSUE TITLE
Date output in magic tags for date fields uses DateTime class by default instead of date_il8n

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5296]
**Describe the bug**

When outputting a magic tag in a Pods Template/field, etc. the Date Field is not translated to the local language (it does recognize the field display PHP format).

**To Reproduce**
1. Create a Date Field
2. Switch to another language (ie French/fr-BE)
3. Output that field with either `display` or in a magic tag
4. See that the date output doesn't translate to the local language

**Expected behavior**
The date output should be translated locally.

**Possible Workaround**
From notes from Scott, change the route of the field from DateTime >> Unix timestamp >> `date_il8n()`
https://codex.wordpress.org/Function_Reference/date_i18n

**Comment by pglewis** [comment]
PR: #5297
