### ISSUE TITLE
Display Field in Selection List is not working for woocommerce sku field: _sku

### ISSUE THREAD

**Issue by webninja2** [pods-framework/pods#5299]
## Issue Overview
I have a pods custom post type (Artists).

There is a Custom Field (artist_products) set to a Relationship (to woocommerce products), which is set to Multiple Select and Auto Complete. I have extended Woocommerce Products with Pods.

So far so good, all works fine when I manually update the CPT, selecting products by Title, (and use Themer to display on frontend).

My issue is that I would like to enter in the artist_products values by the woocommerce product SKU instead of by Title.

Under Additional Field Options, I have "Display Field in Selection List" set to {@_sku} but it doesn't work.

## Expected Behavior

In the backend it should be able to autocomplete by the sku number, but it doesn't work.

## Current Behavior

Multi Selection remains by product title only, and does not allow a sku

<img width="565" alt="screenshot 2019-02-18 11 44 43" src="https://user-images.githubusercontent.com/33987120/52973359-b8217700-3372-11e9-9ad1-d381783e7478.png">

<img width="1183" alt="screenshot 2019-02-18 10 46 32" src="https://user-images.githubusercontent.com/33987120/52972331-6c210300-336f-11e9-923e-215442e13453.png">

## Steps to Reproduce (for bugs)
1. Extend WooCommerce via pods

2. Add a Pods CPT for Artists and and add a relationship field: artist_products
i.e.
Relationship 
› Products (product) (Post Type)

3. Create a record for an Artist. And then under More Fields > Artist Products, try to add products. You can do it by Product Title but not by SKU.

## Possible Solution
unknown

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 5.0.3

PHP Version: 7.2.7

MySQL Version: 5.7.21

Server Software: Microsoft-IIS/8.5

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Session Save Path: D:\temp\Session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 2880

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: okdr22018_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 28.504M

Current Memory Usage (real): 16.000M

Pods Network-Wide Activated: No

Pods Install Location: D:\virtualwww\1000museums.scarabmedia.com\wwwroot\wp-content\plugins\pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:

Add From Server: 3.3.3
All-in-One WP Migration: 6.84
All-in-One WP Migration FTP Extension: 2.45
All In One WP Security: 4.3.8.3
Antispam Bee: 2.9.1
Beaver Builder Plugin (Pro Version): 2.2.1.1
Beaver Themer: 1.2.2.1
Broken Link Checker: 1.11.5
Caldera Forms: 1.7.6
CIO Custom Fields Importer: 1.0.3
Classic Editor: 1.4
FacetWP: 3.2.6
FacetWP - Beaver Builder: 1.2.1
FacetWP - Relevanssi integration: 0.5.1
Google Tag Manager for Wordpress: 1.9.2
Max Mega Menu: 2.5.3.2
Max Mega Menu - Pro Addon: 1.7.1
Microthemer: 5.5.3.6
Pods - Custom Content Types and Fields: 2.7.12
Pods Beaver Themer Add-On: 1.3.2
PowerPack for Beaver Builder: 2.6.9
Redirection: 3.7.3
Relevanssi: 4.1.3
Replace Image: 1.1.6
Smart Slider 3 Pro: 3.3.12
TablePress: 1.9.1
Tawk.to Live Chat: 0.3.5
The Events Calendar: 4.8.1
Ultimate Addons for Beaver Builder: 1.15.0
UpdraftPlus - Backup/Restore: 1.16.6
Windows Compatibility Fix: 1.0.2
WooCommerce: 3.5.4
WooCommerce Menu Cart: 2.7.3
WooCommerce Stripe Gateway: 4.1.14
WooPack for Beaver Builder: 1.3.4.3
WordPress Importer: 0.6.4
WP-Sweep: 1.1.0
WP All Import - WooCommerce Add-On Pro: 3.0.6
WP All Import Pro: 4.5.5
WP Mail SMTP: 1.4.1
YITH Advanced Refund System for WooCommerce Premium: 1.1.2
YITH WooCommerce Color and Label Variations Premium: 1.8.7
YITH WooCommerce Gift Cards Premium: 2.2.1
YITH WooCommerce Recover Abandoned Cart Premium: 1.3.3
YITH WooCommerce Wishlist Premium: 2.2.7
```
</details>

## Pods Package Export (helpful!)

```
[pods_export.txt](https://github.com/pods-framework/pods/files/2877165/pods_export.txt)
```

**Comment by jimtrue** [comment]
I can verify this. The field should actually be `{@_sku}` but for some reason it's not recognizing the postmeta field for products, `_sku`, even with Pods Extended.

I tested against another setup to see if it was the hidden field that was preventing it from showing up in our *Display Field in Selection List* but those work just fine, so it appears to just be the WooCommerce `_sku`

**Comment by jimtrue** [comment]
[migratepackage_issue5299.json.txt](https://github.com/pods-framework/pods/files/2877211/migratepackage_issue5299.json.txt)

Created Migrate Package for Testing. You'll need to install WooCommerce, and obviously add a couple of Products with SKU numbers (sku's are entered under inventory).

**Comment by pglewis** [comment]
This issue isn't limited to Woo's post types, currently we'll only use the provided display field if it is a field added by Pods itself: https://github.com/pods-framework/pods/blob/0f76296/classes/fields/pick.php?ts=4#L2096

**Comment by jimtrue** [comment]
Oh that's not good at all

**Comment by sc0ttkclark** [comment]
If we add logic to allow the field to pass through if the field name passes `registered_meta_key_exists()` then it would solve that problem probably.
