### ISSUE TITLE
Bug: Archive Remains when Enable Archive is unchecked

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5304]
## Issue Overview
After checking 'Enable Archive Page' (and providing an Archive Page Slug Override) in Edit Pods, Advanced Options, archive is enabled. Unchecking (to disable the archive), the archive remains 'enabled' in WordPress, even though Pods Admin shows the archive is not 'Enabled'.

## Expected Behavior
Disabling Archive should NOT leave it 'enabled' (has_archive should still represent as 'false' and there should not be a rewrite rule that points to the archives.

## Current Behavior
Enabling Archives, enables archive. Unchecking 'Enable Archive Page' leaves the archive enabled.

Archive is Unchecked
![screenshot 2019-02-26 08 23 59](https://user-images.githubusercontent.com/3052875/53415746-fdabf880-399f-11e9-9aba-f9684fab7f94.png)

View Tests (View Archive is still available
![screenshot 2019-02-26 08 24 19](https://user-images.githubusercontent.com/3052875/53415770-0e5c6e80-39a0-11e9-99f4-8f3c40742631.png)

Archive Front-end Post Type Archives: Tests is still visible
![screenshot 2019-02-26 08 24 34](https://user-images.githubusercontent.com/3052875/53415811-28964c80-39a0-11e9-9bf0-30c45ddcb2c1.png)

## Steps to Reproduce (for bugs)

1. Create a Custom Post Type
2. Enable Archive under Advanced Options, 'Enable Archive Page'. Save and verify it works.
3. Edit pod, and Uncheck 'Enable Archive Page'. Save and Pods Settings, Clear Cache (just in case)
4. Visit Custom Post Type and see that View Archives is still available.

Current Pods Version 2.7.12

**Comment by jimtrue** [comment]
This was reported on Slack today and validated locally by me.

**Comment by pglewis** [comment]
@jimtrue: I'm curious if clearing the Pods cache straightens it out.

**Comment by jimtrue** [comment]
@pglewis Please see notes above in the issue. Clearing the pods cache doesn't fix this.

**Comment by pglewis** [comment]
Ah, I did read through, just missed that bit.

**Comment by gberg927** [comment]
Hi, I am seeing the same error listed above.

I enabled the archive page for a pod. Later on I decided I didn't want the archive page. I unchecked the "Enable Archive Page" under Advanced Options. Unfortunately the archive page still operates.

Thanks

**Comment by Driekes** [comment]
I resolved it by enabling archive page, then remove the text in the 'slug' field that appears and disabling the archive page again.
Then go to settings--> permalinks and click save (as far as I know this triggers permalink rewrites). That solved it for me.

**Comment by JoryHogeveen** [comment]
Hi @Driekes 
This indeed sounds like a permalink cache issue.

@sc0ttkclark 
- Line that triggers cache flush: https://github.com/pods-framework/pods/blob/main/classes/PodsAPI.php#L2401
- Line that triggers cache refresh transient: https://github.com/pods-framework/pods/blob/main/classes/PodsAPI.php#L9229
- Actual rewrite refresh (after `wp_loaded`): https://github.com/pods-framework/pods/blob/main/classes/PodsInit.php#L1469

What I noticed is that using the function `flush_rewrite_rules()` defaults to a hard flush while we only do a soft flush. A particular reason for this?

**Comment by Driekes** [comment]
Might it not be the case that the slug is used even if the archive checkmark is set to off? Not sure if this is just a cache issue, but you'll know better 👍🏻

**Comment by corypina** [comment]
Came here to file this same issue.
I too had to make sure to remove the text from the custom Slug Override field before unchecking the box.
That was enough to fix the issue, without having to flush permalinks.

**Comment by JoryHogeveen** [comment]
Patch can be tested!
See pull request: #6069
