### ISSUE TITLE
Translations for relationships (in WPML) are impossible to get

### ISSUE THREAD

**Issue by soulwasted** [pods-framework/pods#5307]
**Describe the bug**
It's "impossible" do display translated relationships. In my case czech (CS) as original language. And english (EN) as second.
_Better is: I am desperatly looking for a way how to make it working._

**To Reproduce**
1. Create CPT (1) which is translatable. Eg "person".
2. Create another CPT (2) which is translatable and add custom field as relationship to (1). Eg "project" is done by "person".
3. Create new record for (2), assign (1). Translate it.
4. Display (2) in second language and try to display its relationship (1).

**Expected behavior**
I would love to see translated relationships. Or to find out _simple_ way how to achieve this.

**Screenshots**
Simple DB structure:
![image](https://user-images.githubusercontent.com/12861876/53608052-8b1a6300-3bc1-11e9-9ca7-b079ab4679ee.png)
Simplified view of connections for CS record and EN record:
![image](https://user-images.githubusercontent.com/12861876/53608067-953c6180-3bc1-11e9-9623-a0afb31fc362.png)

## Pods Version
2.7.12

## WordPress Environment

<details>
WordPress Version: 5.1

PHP Version: 7.2.8

MySQL Version: 5.7.23

Server Software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.8 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 51.533M

Current Memory Usage (real): 8.250M

Pods Network-Wide Activated: No

Pods Install Location: /Users/swd/DEV/www/wp-test/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Nineteen

Currently Active Plugins:

Duplicator: 1.3.8
Pods - Custom Content Types and Fields: 2.7.12
Query Monitor: 3.3.1
WPML Multilingual CMS: 4.2.4
WPML String Translation: 2.10.2
WPML Translation Management: 2.8.2
</details>

## Pods Package Export (helpful!)
{"meta":{"version":"2.7.12","build":1551400657},"pods":{"85":{"id":85,"name":"person","label":"People","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"p_name":{"id":86,"name":"p_name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"p_focus_t":{"id":87,"name":"p_focus_t","label":"Focus","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"p_email":{"id":88,"name":"p_email","label":"Email","description":"","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"p_position":{"id":89,"name":"p_position","label":"Position","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"position","sister_id":"","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Person","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"person","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_translation_priority":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"},"90":{"id":90,"name":"position","label":"Positions","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Position","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"position","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_translation_priority":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"},"91":{"id":91,"name":"project","label":"Projects","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"prj_identification":{"id":92,"name":"prj_identification","label":"Identification","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""},"prj_description_t":{"id":93,"name":"prj_description_t","label":"Description","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""},"prj_solver":{"id":94,"name":"prj_solver","label":"Solver","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"person","sister_id":"","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Project","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"project","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_translation_priority":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}
</details>

**Additional context**
According to attached images, there is showcase of displaying project in CS and in EN language.
- https://strapa.cz/wp-test/projekty/
- https://strapa.cz/wp-test/en/projects/

I can provide Duplicator package of this.

**Possible Workaround**
I am trying to solve this in WPML forum here: https://wpml.org/forums/topic/wpml-doesn-show-translated-relationship-custom-fields/
- unfortunately using "suppress_filters" doesn't work
- maybe this "bug report" is duplication to another issues

**Comment by JoryHogeveen** [comment]
Hello @soulwasted 

Automatic translation of metadata isn't supported and can be difficult to do since translation and relationships are different content within WP. In short, a relationship value in lang EN is a different post than in lang CZ so if you sync relationship data the wrong ID gets added to the translation.

I think your only solution is to go with custom code that hooks into the synchronization of relationship data.
Once you safe a post and it syncs to it's translations you could convert the relationship ID's to the translated ones before saving. Keep in mind that if these doesn't exist this won't work.
That is also the reason this isn't within Pods core (yet) since there isn't a nice streamlines way of doing this and automatically add translations if they don't exist. Such functionality will create a lot more issues to tackle and Pods isn't a plugin for translations.
This is (IMO) something translation plugins should support, not Pods or similar plugins.

**Comment by soulwasted** [comment]
Hi.
This is exactly what I get as answer from WPML guys. That this doesn't work "automatically" but using hooks etc. can solve this. WPML plugin cannot do this and I don't think it will by possible in any near future.
I think this is a big "problem" for many projects.

Thanks for answer anyway.
