### ISSUE TITLE
Special Magic Tag {@user.any} uses deprecated argument to call WP_User->ID

### ISSUE THREAD

**Issue by faffioza** [pods-framework/pods#5309]
## Issue Overview
With WP_DEBUG switched on, the following notice is presented when the page runs:

**Notice**: WP_User->id was called with an argument that is **deprecated** since version 2.1.0! Use WP_User->ID instead. in **/home/circulusco/dev-lrn.circulus.co.za/wp-includes/functions.php** on line **4546**

## Expected Behavior
No debug message.

## Current Behavior
With WP_DEBUG switched on, the following notice is presented when the page runs:

**Notice**: WP_User->id was called with an argument that is **deprecated** since version 2.1.0! Use WP_User->ID instead. in **/home/circulusco/dev-lrn.circulus.co.za/wp-includes/functions.php** on line **4546**

Busy testing on dev site.  WP_DEBUG is not switched on on the production site.

## Steps to Reproduce (for bugs)

1. Added the following to wp-config.php:  **define('PODS_SHORTCODE_ALLOW_EVALUATE_TAGS',true);**
2. Using Pods Shortcode to display template:  [pods name="external_cpd" orderby="external_cpd_date_completed_earned DESC" template="Display External CPD" where="post_author = **{@user.id}**"]
3. Page correctly only displays the records where the author is the same as the logged in user.
4. Debug message (or notice) is displayed above the content from the pods template as explained above.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
Debug Information
WordPress Version: 5.1

PHP Version: 7.1.14

MySQL Version: 5.6.41

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 8640

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: devlrn_

WP Multisite Mode: No

WP Memory Limit: 768M

Current Memory Usage: 101.217M

Current Memory Usage (real): 104.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/circulusco/dev-lrn.circulus.co.za/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: LifterLMS LaunchPad Child

Currently Active Plugins:

Abandoned Cart Lite for WooCommerce: 5.2.1
Admin Menu Editor: 1.8.7
All-in-One WP Migration: 6.85
All-in-One WP Migration File Extension: 1.3
All-in-One WP Migration Unlimited Extension: 2.25
Better Search Replace: 1.3.3
Black Studio TinyMCE Widget: 2.6.7
CartFlows: 1.1.8
Checkout Field Editor for WooCommerce: 2.9.8
Classic Editor: 1.4
Coming Soon Page & Maintenance Mode by SeedProd: 5.0.24
Elementor: 2.4.7
Google Analytics Dashboard for WP (GADWP): 5.3.7
Google Tag Manager for Wordpress: 1.9.2
LifterLMS: 3.29.3
LifterLMS Advanced Quizzes: 1.0.9
LifterLMS Bulk Registration: 1.0.0
LifterLMS Customizations: 1.0.0
LifterLMS Helper: 3.0.2
LifterLMS Labs: 1.5.2
LifterLMS MailChimp Add-on: 3.1.0
LifterLMS WooCommerce: 2.0.7
Loco Translate: 2.2.0
Nav Menu Roles: 1.9.3
Pods - Custom Content Types and Fields: 2.7.12
Post SMTP: 1.9.8
Simple CSS: 1.1
SiteOrigin Widgets Bundle: 1.15.2
SSL Insecure Content Fixer: 2.7.2
TinyMCE Advanced: 5.1.0
UpdraftPlus - Backup/Restore: 1.16.6
Upload Max File Size: 1.2
User Role Editor: 4.50
User Switching: 1.4.2
WooCommerce: 3.5.5
WooCommerce Blocks: 1.4.0
WooCommerce PayFast Gateway: 1.4.11
Wordfence Security: 7.2.3
wpDataTables: 2.4
WP User Avatars: 1.4.0
Yoast SEO: 9.7

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by quasel** [comment]
never used that shortcode - seems like an edge case did you try using ID for the magic tag - it might make a difference   `{@user.ID}`

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
