### ISSUE TITLE
Accentuated characters not supported in labels

### ISSUE THREAD

**Issue by lcswillems** [pods-framework/pods#5311]
**Describe the bug**
Accentuated characters seem not to be supported in labels. I labelled this pod "Exposés" but below, it is always written "Expos".

![image](https://user-images.githubusercontent.com/5437552/54025024-94936480-4199-11e9-9350-6301a76b1eba.png)

## Pods Version

2.7.12

## WordPress Environment

<details>

WordPress Version: 5.1

PHP Version: 7.2.15-0ubuntu0.18.10.1

MySQL Version: 5.7.25

Server Software: Apache/2.4.34 (Ubuntu)

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 19,956M

Current Memory Usage (real): 6,000M

Pods Network-Wide Activated: No

Pods Install Location: /mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/sapt/Www/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: OceanWP

Currently Active Plugins:

Analytify - Google Analytics Dashboard: 2.2.10
Duplicator: 1.3.8
Elementor: 2.5.3
Elementor Pro: 2.4.7
Gutenberg: 5.2.0
Pods - Custom Content Types and Fields: 2.7.12
WP Fastest Cache: 0.8.9.1
Yoast SEO: 9.7

</details>

**Comment by quasel** [comment]
Yep can confirm it - seems we are striping it out only in pods admin views, a minor issue as it works everywhere else…

**Comment by jamesgol** [comment]
I tried to reproduce this on Pods 2.7.12 and the current dev version but was unable to.  Maybe I'm looking at the wrong place.

**Comment by jamesgol** [comment]
Ok I see the issue now.  It's all happening in JavaScript to try to stop XSS.  The filtering was added back in 2012 with this commit https://github.com/pods-framework/pods/commit/ac2959e3a91af6485b5d7443adb90262efc3f2ed

It gets pretty complicated trying to whitelist all valid character sets, I'm sure I can come up with something to cover the basic latin based letters but I'm not sure what the ultimate solution is to allow all other languages.

**Comment by JoryHogeveen** [comment]
This will need some refactoring as the sluggables currently do not distinguish any form of sanitation besides lower/uppercase.
In fact, in this case the whole term "sluggable" isn't correct and caused confusion for me at start.
