### ISSUE TITLE
How i can generate the archive pods-debug.xcconfig?

### ISSUE THREAD

**Issue by veronesecoms** [pods-framework/pods#5317]
Im trying to build an app in IOS but im receiving this warnings/errors with pods:

![Captura de Tela 2019-03-22 às 08 11 25](https://user-images.githubusercontent.com/32598503/54819415-8e61b580-4c7a-11e9-9e65-612cd29eea1e.png)

In 32 line i have:

`#include "../pods-debug.xcconfig"`

But dont have this archive in my project. How i can generate this archive?

I run inside my project the commands:

```
pod init
pod setup
pod install

```
but this archive never is created. Someone can help me please

**Comment by quasel** [comment]
Guess you got the wrong GitHub Repo - this is a WordPress CPT Plugin - pods.io
