### ISSUE TITLE
2.8 random todo list and branstorming

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#5346]
- Fields in general
	- Need a way to keep track of both the raw value as entered and any formatting

- Number field
	- min max options
	- audit other field config and make sure everything is implemented
	- slider

- Paragraph field
	- Is really 3 fields in one
		- textarea, basics already done
		- WYSIWYG
		- code

- Validation
	- deny post/update for both Gb and classic
	- ? Should it always run onChange

- i18n
	- Look into tools, try generating a translation file from the source to verify it all works

- Error/excpetion handling
	- rules engine

- Tests

- Comments, jsdoc for All The Things, draw boxes to show the containment model

- Misc
	- pods-dfv's brute force list of fields/renders is growing.  The field-manifest is specifically meant to be the only brute force list... see if the information can be consolidated in the manifest so that stuff doesn't have to stay in sync

	- dev/production builds, served based on SCRIPT_DEBUG settings

**Comment by sc0ttkclark** [comment]
Resolved in the current iteration of Pods 2.8
