### ISSUE TITLE
No custom post-types created with Pods are retrieved by get_post_types()

### ISSUE THREAD

**Issue by enventa** [pods-framework/pods#5351]
**Describe the bug**
When using get_post_types() function from WordPress core, it doesn't retrieve custom post-types created by Pods.

**Expected behavior**
Get a list of all existing custom post-types, including the ones created by Pods.

## Pods Version
2.7.12

## WordPress Environment

<details>
```
Debug Information

WordPress Version: 5.1.1

PHP Version: 7.1.26

MySQL Version: 5.5.5

Server Software: nginx/1.11.1

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

Session Save Path: /var/lib/php/session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: Yes
    Memcached: Yes
    Redis: No

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 96M

Current Memory Usage: 68.684M

Current Memory Usage (real): 28.000M

Pods Network-Wide Activated: No

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Astra

Currently Active Plugins:

    Better Font Awesome: 1.7.1
    Contact Form 7: 5.1.1
    Elementor: 2.5.11
    Elementor Pro: 2.5.0
    Molongui Authorship: 3.2.5
    Molongui Bump Offer For WooCommerce: 1.1.1
    Pods - Custom Content Types and Fields: 2.7.12
    WC Variations Radio Buttons: 2.0.2
    WooCommerce: 3.5.6
    wpDiscuz: 5.3.2
    Yoast SEO Premium: 9.7
```
</details>

**Comment by sc0ttkclark** [comment]
When are you calling get_post_types? We add ours during the `init` action which is the current standard for WordPress custom post type registration.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue!
If you can provide some more information we can reopen it!

**Comment by enventa** [comment]
Sorry for not having been able to answer before. The thing was that you hook into the `init` action at a priority of 11, while I was hooking into it at a 10. So my code was run before yours. Changing the priority to 12 solved the issue. Now I'm getting all defined post types.

Thanks!
