### ISSUE TITLE
Admin UI issues: PODS conflicts with Polylang

### ISSUE THREAD

**Issue by phrench** [pods-framework/pods#5365]
**Describe the bug**
When Polylang is enabled, WYSIWYG fields of CPT can't be edited resp. it's not possible to place the mouse cursor into the field.

Also collapsing metaboxes from plugins such as SEOPress doesn't work anymore. But this is only when editing a CPT. When editing a normal blog post, collapsing the very same metabox works.

Thus looks like some conflict of Polylang with the PODS plugin.

**To Reproduce**
1. Install the PODS plugin
2. Create a custom post type
3. Add a custom field of the type WYSIWYG (Visual Editor) to the custom post type
4. Add a new entry (of the custom post type)
5. TinyMCE field cannot be access with the mouse cursor. (= actual behavior)
6. Disable Polylang plugin
7. TinyMCE field can now be accessed with the mouse cursor. (= expected behavior)

**Expected behavior**
See step 7 above.

## Pods Version
2.7.12

## WordPress Environment

<details>
```
WordPress Version: 5.1.1

PHP Version: 7.1.28

MySQL Version: 5.7.23

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: Yes
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wppt_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 21,955M

Current Memory Usage (real): 26,000M

Pods Network-Wide Activated: No

Pods Install Location: /home/redacted/public_html/redacted.com/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Astra

Currently Active Plugins:

    Avatar Manager: 1.6.1
    Code Snippets: 2.13.3
    Conditional Menus: 1.1.3
    MainWP Child: 3.5.6
    plugin load filter: 3.1.0
    Pods - Custom Content Types and Fields: 2.7.12
    Polylang: 2.5.3
    Q2W3 Fixed Widget: 5.1.6
    Reactive Mortgage Calculator: 1.1
    Really Simple SSL: 3.1.5
    Recent Posts Widget With Thumbnails: 6.5.0
    Regenerate Thumbnails: 3.1.0
    SEOPress: 3.4
    Ultimate Addons for Gutenberg: 1.13.1
    UpdraftPlus - Backup/Restore: 1.16.14
```
</details>

**Comment by phrench** [comment]
Also could reproduce the issue with PODS version 2.7.13-a-1.

**Comment by JoryHogeveen** [comment]
Update on this issue;
This only happens if translations for the CPT aren't enabled. It seems PLL or Pods<>PLL compat is running a script that shouldn't be loaded for these type of CPT.

**Comment by JoryHogeveen** [comment]
Found the issue but this is actually a bug in Polylang.
See: https://github.com/polylang/polylang/pull/369
