### ISSUE TITLE
3x BUG...

### ISSUE THREAD

**Issue by erikdemarco** [pods-framework/pods#5370]
I'm using table storage and run this script (100% copy paste from the pods site)

```
$pod = pods( 'book' );

// To add a new item, let's set the data first
$data = array(
    'name' => 'New book name',
    'author' => 2, // User ID for relationship field
    'description' => 'Awesome book, read worthy!'
);

// Add the new item now and get the new ID
$new_book_id = $pod->add( $data ); 
```

It create the item row succesfully, not 1! but always 3 times. Why?
All my table have 3 duplicate row everytime I add an item.

**Comment by erikdemarco** [comment]
@JoryHogeveen Hi  I tried adding echo "12345" below that code. The echo code only show one time. so it must be the a bug inside save_pod_item() (that save_pod_item function is really really really long so the probability of a bug quite high)

**Comment by erikdemarco** [comment]
@JoryHogeveen I tried adding echo "12345"; below this code. And the echo code only show one time. So the probability of a bug inside save_pod_item is quite high. (that save_pod_item function is really really long)

**Comment by erikdemarco** [comment]
test

**Comment by erikdemarco** [comment]
@JoryHogeveen I tried adding echo "12345"; below this code. And the echo code only show one time. So the probability of a bug inside save_pod_item is quite high. (that save_pod_item function is really really long)

**Comment by JoryHogeveen** [comment]
@erikdemarco 

> I tried adding echo "12345"; below this code. And the echo code only show one time. So the probability of a bug inside save_pod_item is quite high. (that save_pod_item function is really really long)

It could also be triggered because of an AJAX request (WP heartbeat for example) if the code is not within an a function (action).
