### ISSUE TITLE
"Feature request": Info regarding WP 5.2 and PHP 7.3 support on wordpress.org.

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#5376]
Hi! Thanks for a fantastic tool - I really enjoy it. However, reasonably complex as it its, I'm hesitating to update to the latest WordPress 5.2 and the in the new Site Health recommended PHP 7.3, as I can't find any information whether I can expect Pods Framework to be fully compatible with those releases.

I fact, according to wordpress.org, Pods Framework has only been tested compatible up to WordPress 5.0.4
https://wordpress.org/plugins/pods/

That said, I've been using Pods with WP 5.1.1 and PHP 7.2 in production for months, not encountering any issue. (Keeping in mind that my setup is simple with only a handful of pods and few relations)

Are there any "official" recommendations regarding updating to WordPress 5.2 and PHP 7.3?

Best regards
Bjarne Oldrup

**Comment by oldrup** [comment]
To let you know, I've updated to WordPress 5.2 on a single site, and performed basic test, like adding, editing and viewing a custom posts. That did not reveal any critical issues.

**Comment by pglewis** [comment]
We're mostly just behind on documentation.  The 2.8 branch actually requires a minimum of WordPress 5.2 right now; 2.7 will remain current as well if any issues are reported.  

We should probably add PHP 7.3 to the Travis test matrix, I'll create an issue for that if there isn't one already.

**Comment by quasel** [comment]
on my sites it runs flawless with php 7.3 bit it's currently not part of the travis-ci config… and we should update the readme to list it correctly on wp.org

**Comment by sc0ttkclark** [comment]
Updated readme in our upcoming release to tested up to WP 5.2
