### ISSUE TITLE
Gutenberg Block Template

### ISSUE THREAD

**Issue by permrosen** [pods-framework/pods#5383]
I’m trying to make a gutenberg block template (the same predefined blocks on every new post I create) for a CPT called Galleri made in Pods. Described here: https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#api

function myplugin_register_template() {
$post_type_object = get_post_type_object( ‘galleri’ );
$post_type_object->template = array(
array( ‘core/paragraph’ ),
array( ‘core/gallery’ ),
);
}
add_action( ‘init’, ‘myplugin_register_template’ );

It works fine on regular posts if I replace “galleri” in the code with “post”, but not on the Pod created post type. REST API is activated in Pods so Gutenberg is there as it should but not my block template.

**Comment by leepeterson** [comment]
@permrosen I thought the same as you (since WP docs provide that guidance). However, you can hook into `pods_register_post_type` or `pods_register_post_type_{$post_type}` for this purpose.

Example:

```
add_action( 'init', function() {
	add_filter( 'pods_register_post_type_{$post_type}', function( $options ) {
		$template = [
			['core/heading',
				['level' => '2','content' => 'Predefined H2']
			],
			['core/paragraph',
				['content' => 'Predefined paragraph copy']
			],
			['core/image',
				['align' => 'full']
			],
		];
		$options['template'] = $template;
		$options['template_lock'] = 'all';
		return $options;
	});
});
```

**Comment by JoryHogeveen** [comment]
@leepeterson 
Thank you! One edit: you don't need to wrap it within the `init` hook!

@permrosen the code below should work fine.
```php
$post_type = 'galleri';
add_filter( "pods_register_post_type_{$post_type}", function( $options ) {
	$template = array(); // Configure your template array here.
	$options['template'] = $template;
	$options['template_lock'] = 'all';
	return $options;
} );
```

**Comment by leepeterson** [comment]
@JoryHogeveen 	Thanks for that catch! I'm a creature of habit... what can I say :)

**Comment by permrosen** [comment]
Works fine. Thanks a lot! /Per

Bästa hälsningar / Best regards

Mats Forslund
Per Rosén

Visby Web
Soro, Söderväg 5 C, 621 58 Visby

Tel +46 70 625 90 85 (mob)

*crew@visbyweb.se <crew@visbyweb.se>*
visbyweb.se
