### ISSUE TITLE
Typo in tool tip - Custom taxonomy, Advanced Options, "Allow Front Prepend"

### ISSUE THREAD

**Issue by A-Buzon** [pods-framework/pods#5394]
## Issue Overview
Within a Custom taxonomy pod, Advanced Options, "Allow Front Prepend" tooltip says "Checked => /news/, Unchecked => blog/news/" however I've encountered the opposite.
## Expected Behavior
When "Allow Front Prepend" is checked, according to tool tip, the blog/ section of the permalink should remove.

## Current Behavior
The opposite happens.  "Allow Front Prepend" checked keeps /blog/ in the URL, unchecked removes it.
I believe this is just a typo in the Tool Tip.
 Adding to this hypothesis - in Advanced Options for a new Post Type, the tool tip for "Rewrite with Front" (which I think is the same thing?) gives the opposite/correct instructions.

## Steps to Reproduce (for bugs)
1. Create custom Taxonomy in Pods
2. Go to Advanced Options tab
3. go to "Allow Front Prepend"

## Possible Solution
Reverse the instruction of the tooltip.  Also, if  "Allow Front Prepend" and "Rewrite with Front"  are indeed the same setting, change setting's name and tool tips to match - whether in Post or Taxonomy's Advanced Options.

## WordPress Environment
All current versions as of 6/23/2019 (WordPress, Pods)

**Comment by patrikhuber** [comment]
Hi,

I noticed exactly the same today, and was going to report it here as well as a bug.

This would be an easy fix, the text in the tooltip could just be changed around.

![image](https://user-images.githubusercontent.com/4967343/79055980-85f36880-7c49-11ea-89c4-bb31fad737e8.png)
