### ISSUE TITLE
Message Alert display slug not label..

### ISSUE THREAD

**Issue by pierluigiabramo** [pods-framework/pods#5406]
When an user leave blank a field from relationship alert message report the slug name of the field not the (more correct) label

![IMG_0013](https://user-images.githubusercontent.com/17725824/60531668-c659a980-9cfb-11e9-9695-aa029d7f6c9c.jpg)

Informazioni di debug

WordPress Version: 5.2.2

PHP Version: 7.3.5

MySQL Version: 5.6.43

Server Software: Apache

Your User Agent: Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

Session Save Path: /opt/alt/php73/var/lib/php/session

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: sanvitoaltorreonline_

WP Multisite Mode: No

WP Memory Limit: 512M

Current Memory Usage: 55,647M

Current Memory Usage (real): 56,500M

Pods Network-Wide Activated: No

Pods Install Location: /home/xy393ox2/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: San Vito al Torre OnLine

Currently Active Plugins:

Classic Editor: 1.5
Elementor: 2.5.16
Essential Addons for Elementor: 3.1.1
Ocean Extra: 1.5.8
Pods - Custom Content Types and Fields: 2.7.13
Rank Math SEO: 1.0.27.4
Widget Context: 1.1.1

**Comment by jimtrue** [comment]
@pierluigibramo Slack archives are not permanent. Please upload the image you provided in your Slack message and at a minimum a description of where you're seeing the error (all fields that are required or just specific ones)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
See description. Currently the error messages contain the field name (slug) not the label.
What are your thoughts about the error reporting and what it should "report"?

**Comment by JoryHogeveen** [comment]
@sc0ttkclark punting this for 2.8. It might already be fixed in 2.8?

**Comment by sc0ttkclark** [comment]
Needs testing to confirm, but our error messaging has been redone a bit but not enough to get to where we really want it for form submit.

**Comment by sc0ttkclark** [comment]
This is handled through the new error message displays -- but we're still working on better Block Editor field validation and error handling on save.

<img width="527" alt="Screen Shot 2021-05-29 at 8 11 49 PM" src="https://user-images.githubusercontent.com/709662/120088835-388ac280-c0ba-11eb-9760-facdb3a7f07d.png">
