### ISSUE TITLE
compact(): Undefined variable: custom_fields in plugins/pods/classes/PodsAPI.php on line 3574

### ISSUE THREAD

**Issue by tristanleboss** [pods-framework/pods#5411]
Latest version of Pods and WP.

I see errors in my PHP log file:

> 
> [07-Jul-2019 22:47:52 UTC] PHP Notice:  compact(): Undefined variable: custom_fields in /public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 3574
> 
> [07-Jul-2019 22:47:52 UTC] PHP Notice:  compact(): Undefined variable: custom_fields in /public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 3580
> 
> [07-Jul-2019 22:47:52 UTC] PHP Notice:  compact(): Undefined variable: custom_fields in /public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 3587
> 
> [07-Jul-2019 22:47:52 UTC] PHP Notice:  compact(): Undefined variable: custom_fields in /public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 3593
> 
> [07-Jul-2019 22:47:52 UTC] PHP Notice:  compact(): Undefined variable: custom_fields in /public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 4154

The problem is due to the fact the $custom_fields is instantiated at line 3427 in an if structure. If, for some reason, we don't enter this if, the variable is indeed undefined:

```
		if ( ! empty( $params->data ) && is_array( $params->data ) ) {
			$custom_fields = array();
```

Moving the line 3427 before the if structure (line 3425) fix the problem.

**Comment by pglewis** [comment]
PR: #5412, good catch
