### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by twohumans** [pods-framework/pods#5415]
**Describe the bug**
Since version 2.7.13, when the Site Language of a WordPress install is something other than English, changes that are made to fields from a CPT created with Pods cannot be saved. The native WordPress fields (such as Title, Editor, Author, Featured Image,...) are not affected and are saving.

**To Reproduce**
1. When the WordPress install has not it Site Language set to English Go to a CPT and create or modify an entry.
2. Click on Publish or Update
3. The native Wordpress fields are saved but the fields manage by Pods are unchanged. 

**Expected behavior**
I expected to be able to save CPT content specific to Pods even if the Site Language is set to something else then English, like I could do up to version 2.7.12

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 2.7.13

## WordPress Environment

<details>

`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: false
default_comment_status: closed
multisite: true
user_count: 1
site_count: 1
network_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Two Humans Child Theme
version: 1.0
author: Two Humans
author_website: https://twohumans.net.com
parent_theme: Beaver Builder Theme
theme_features: fl-theme-builder-headers, fl-theme-builder-footers, fl-theme-builder-parts, automatic-feed-links, title-tag, post-thumbnails, woocommerce, align-wide, wp-block-styles, menus, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /home/suttonjazz/dev.suttonjazz.com/wp-content/themes/bb-theme

### wp-themes (1) ###

Beaver Builder Theme: version: 1.7.3, author: The Beaver Builder Team

### wp-plugins-active (14) ###

Beaver Builder Plugin (Agency Version): version: 2.2.3.3, author: The Beaver Builder Team
Beaver Themer: version: 1.2.3.4, author: The Beaver Builder Team
Category Order and Taxonomy Terms Order: version: 1.5.7, author: Nsp-Code
Dashboard Welcome for Beaver Builder: version: 1.0.6, author: Beaver Addons, Achal Jain
Health Check & Troubleshooting: version: 1.3.2, author: The WordPress.org community
iThemes Security: version: 7.4.0, author: iThemes
Pods - Custom Content Types and Fields: version: 2.7.13, author: Pods Framework Team
Pods Beaver Themer Add-On: version: 1.3.2, author: Quasel, Pods Framework Team
Pods SEO: version: 2.1, author: Pods Framework Team
Post Types Order: version: 1.9.4.1, author: Nsp Code
PowerPack for Beaver Builder: version: 2.7.1, author: IdeaBox Creations
Ultimate Addons for Beaver Builder: version: 1.18.2, author: Brainstorm Force
UpdraftPlus - Backup/Restore: version: 2.16.15.24, author: UpdraftPlus.Com, DavidAnderson
Yoast SEO: version: 11.6, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.66.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.1.30 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.64-MariaDB-cll-lve
client_version: 5.5.62

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/suttonjazz/dev.suttonjazz.com/wp-content
WP_PLUGIN_DIR: /home/suttonjazz/dev.suttonjazz.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0
pods-session-save-path: /opt/alt/php71/var/lib/php/session
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 65.605M
pods-memory-current-usage-real: 38.000M
pods-network-wide: Yes
pods-install-location: /home/suttonjazz/dev.suttonjazz.com/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
{"meta":{"version":"2.7.13","build":1562697556},"pods":{"274":{"id":274,"name":"site","label":"Sites","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"adresse_du_site":{"id":276,"name":"adresse_du_site","label":"Adresse du site","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"telephone_du_site":{"id":277,"name":"telephone_du_site","label":"Téléphone du site","description":"","help":"","class":"","type":"phone","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","phone_format":"999-999-9999 x999","phone_enable_phone_extension":"1","phone_max_length":"25","phone_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","phone_repeatable":"0","phone_placeholder":""},"site_web_du_site":{"id":278,"name":"site_web_du_site","label":"Site Web","description":"","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"logo_du_site":{"id":279,"name":"logo_du_site","label":"Logo du site","description":"","help":"","class":"","type":"file","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Ajouter un fichier","file_modal_title":"Attacher un fichier","file_modal_add_button":"Ajouter un fichier","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"activites_associees":{"id":281,"name":"activites_associees","label":"Activités associées","description":"","help":"","class":"","type":"pick","weight":4,"pick_object":"post_type","pick_val":"spectacle","sister_id":"280","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"0","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Site","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"site","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-location"},"126":{"id":126,"name":"spectacle","label":"Spectacles","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"nom_du_spectacle":{"id":127,"name":"nom_du_spectacle","label":"Nom du spectacle","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"site_du_spectacle":{"id":280,"name":"site_du_spectacle","label":"Site du spectacle","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"post_type","pick_val":"site","sister_id":"281","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"date_du_spectacle":{"id":139,"name":"date_du_spectacle","label":"Date du spectacle","description":"","help":"","class":"","type":"date","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"wp","date_format":"mdy","date_allow_empty":"1","date_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":""},"heure_du_spectacle":{"id":129,"name":"heure_du_spectacle","label":"Heure du spectacle","description":"","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","seo_analysis_exclude":"0","seo_sitemap_include":"0","text_repeatable":0,"text_placeholder":""},"noms_et_instruments_des_musiciens":{"id":161,"name":"noms_et_instruments_des_musiciens","label":"Noms et instruments des musiciens","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"video":{"id":162,"name":"video","label":"Vidéo","description":"","help":"","class":"","type":"website","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"site_web":{"id":163,"name":"site_web","label":"Site Web","description":"","help":"","class":"","type":"website","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"prix":{"id":164,"name":"prix","label":"Prix","description":"","help":"","class":"","type":"currency","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","currency_format_type":"number","currency_format_sign":"usd","currency_format_placement":"before","currency_format":"i18n","currency_decimals":"2","currency_decimal_handling":"none","currency_step":"1","currency_min":"0","currency_max":"1000","currency_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","currency_repeatable":"0","currency_placeholder":""},"point_de_vente":{"id":172,"name":"point_de_vente","label":"Point de vente","description":"","help":"","class":"","type":"text","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"images":{"id":178,"name":"images","label":"Images","description":"","help":"","class":"","type":"file","weight":9,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Ajouter un fichier","file_modal_title":"Attacher un fichier","file_modal_add_button":"Ajouter un fichier","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"Spectacle","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"spectacle","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_icon":"dashicons-tickets-alt","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","enable_i18n":{"fr_FR":"1"}}}}

**Additional context**
Add any other context about the problem here.

**Possible Workaround**
Change the Site Language to English to create or edit CPT content and revert to the original Site Language when completed.

**Comment by sc0ttkclark** [comment]
Can you provide an example or screenshot of this problem?

**Comment by twohumans** [comment]
Sure, here are 3
#1 is the before
#2 is the changes have been made but not save
#3 is after saving
I can do 3 more after changing the site language to English. For these the site language is Canadian French. The site show the same beaviour with France French.
![Screenshot_2019-07-09 Modifier Spectacle ‹ Festival de Jazz de Sutton — WordPress-1](https://user-images.githubusercontent.com/19491281/60918003-31593200-a260-11e9-92c6-78516aa44ca9.png)
![Screenshot_2019-07-09 Modifier Spectacle ‹ Festival de Jazz de Sutton — WordPress-2](https://user-images.githubusercontent.com/19491281/60918004-31f1c880-a260-11e9-990b-1dfadc09060f.png)
![Screenshot_2019-07-09 Modifier Spectacle ‹ Festival de Jazz de Sutton — WordPress-3](https://user-images.githubusercontent.com/19491281/60918005-31f1c880-a260-11e9-8e72-0197a3a08ee0.png)

**Comment by twohumans** [comment]
I just want to add we are now rolling back out clients to version 2.7.12 because of this problem.
It would need to be address soon.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen can you take a look at this when you're next able to?

**Comment by JoryHogeveen** [comment]
Hello @twohumans 
I've tried to reproduce your issue by changing the locale (Dutch) on my own installation and updating some fields but I have no issues here.

Can you try the following:
- Have you updated Pods to the latest version? (2.7.14)
- Deactivate all plugins except Pods, switch to a default WordPress theme and check if the issue is still there. (Handy plugin: https://nl.wordpress.org/plugins/health-check/)

**Comment by twohumans** [comment]
Hi, I've turned off all plugins but Pods and switched to Twenty Nineteen and still have the problem.
I'm running PHP 7.1. I've added the Site Health info.

`
### wp-core ###

version: 5.2.2
site_language: fr_CA
user_language: fr_CA
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: false
default_comment_status: closed
multisite: true
user_count: 5
site_count: 2
network_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Twenty Nineteen (twentynineteen)
version: 1.4
author: L'équipe WordPress
author_website: https://fr-ca.wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, widgets
theme_path: /home/suttonjazz/public_html/wp-content/themes/twentynineteen

### wp-themes-inactive (2) ###

Two Humans Child Theme: version: 1.0, author: Two Humans
Beaver Builder Theme: version: 1.7.3, author: The Beaver Builder Team

### wp-plugins-active (2) ###

Health Check & Troubleshooting: version: 1.4.0, author: The WordPress.org community
Pods - Custom Content Types and Fields: version: 2.7.14, author: Pods Framework Team

### wp-plugins-inactive (17) ###

Beaver Builder Plugin (Agency Version): version: 2.2.4.4, author: The Beaver Builder Team
Beaver Themer: version: 1.2.4.1, author: The Beaver Builder Team
Category Order and Taxonomy Terms Order: version: 1.5.7, author: Nsp-Code
Classic Editor: version: 1.5, author: WordPress Contributors
Dashboard Welcome for Beaver Builder: version: 1.0.6, author: Beaver Addons, Achal Jain
Google Analytics for WordPress by MonsterInsights: version: 7.7.1, author: MonsterInsights
iThemes Security: version: 7.4.1, author: iThemes
ManageWP - Worker: version: 4.9.0, author: GoDaddy
MultilingualPress: version: 2.11.3, author: Inpsyde GmbH
Multisite Global Media: version: 0.0.8, author: Dominik Schilling, Frank Bültge
Pods Beaver Themer Add-On: version: 1.3.2, author: Quasel, Pods Framework Team
Pods SEO: version: 2.1, author: Pods Framework Team
Post Types Order: version: 1.9.4.1, author: Nsp Code
PowerPack for Beaver Builder: version: 2.7.3, author: IdeaBox Creations
Ultimate Addons for Beaver Builder: version: 1.20.0, author: Brainstorm Force
UpdraftPlus - Backup/Restore: version: 2.16.16.24, author: UpdraftPlus.Com, DavidAnderson
Yoast SEO: version: 11.9, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-11-14 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 31 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.66.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.1.31 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
server-headers: 
	date: Thu, 22 Aug 2019 21:29:09 GMT
	server: Apache
	expires: Thu, 19 Nov 1981 08:52:00 GMT
	cache-control: Array
	pragma: no-cache
	link: <https://suttonjazz.com/wp-json/>; rel="https://api.w.org/", <https://suttonjazz.com/>; rel=shortlink
	set-cookie: PHPSESSID=302735c8fadad6d89fcaa38f91ad6dc1; path=/
	vary: Accept-Encoding,User-Agent
	content-encoding: gzip
	content-length: 3867
	content-type: text/html; charset=UTF-8
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.65
client_version: 5.5.62

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/suttonjazz/public_html/wp-content
WP_PLUGIN_DIR: /home/suttonjazz/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0
pods-session-save-path: /opt/alt/php71/var/lib/php/session
pods-session-save-path-exists: Oui
pods-session-save-path-writable: Oui
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Non
pods-opcode-cache-memcached: Non
pods-opcode-cache-opcache: Non
pods-opcode-cache-redis: Non
pods-object-cache-apc: Non
pods-object-cache-apcu: Non
pods-object-cache-memcache: Non
pods-object-cache-memcached: Non
pods-object-cache-redis: Non
pods-memory-current-usage: 37,560M
pods-memory-current-usage-real: 24,000M
pods-network-wide: Oui
pods-install-location: /home/suttonjazz/public_html/wp-content/plugins/pods/
pods-developer: Non
pods-tableless-mode: Non
pods-light-mode: Non
pods-strict: Non
pods-allow-deprecated: Oui
pods-api-cache: Oui

`

**Comment by twohumans** [comment]
I should also add that I can give you access to a live site if you want to run tests.

**Comment by JoryHogeveen** [comment]
I've tested again with your info and Pod and found that this is an issue with the Date field.
Other fields are saving perfectly fine but the date field isn't working correctly due to the french translation.
Probably related: #5444 

@sc0ttkclark We really need a workaround for this. The input info the datetimepicker adds to the input field isn't working with PHP date conversion.
No idea why this didn't came up earlier as a bug..

**Comment by JoryHogeveen** [comment]
@twohumans Could you test #5451.
I believe this fixes all translation/formatting issues related to date/time fields.

**Comment by twohumans** [comment]
Yes #5451 does solves the problem. Thank you!
