### ISSUE TITLE
pods_api_pre_save_pod_item_user not Validating

### ISSUE THREAD

**Issue by bkonia** [pods-framework/pods#5419]
I'm using the pods_api_pre_save_pod_item_user filter to perform custom validation on a front end user profile form generated with the pods form method documented at https://pods.io/docs/code/pods/form/

In the event of a validation failure, I'm doing the following:

return pods_error("Some error message");

This USED to work fine. When an error occurred, it would cancel the update and display the error message on the form. However, it seems one of the recent Pods updates must have broken this functionality, because it no longer displays the error message and the form always processes the data, regardless of whether it validated or not.

I've traced the code extensively and have verified that the filter is definitely running and it's definitely executing the pods_error() statement.

**Comment by JoryHogeveen** [comment]
Should be fixed in #5453 
If you can, please test the PR!
