### ISSUE TITLE
Date/Time field does not display local time with display method.

### ISSUE THREAD

**Issue by MasatoFukaya** [pods-framework/pods#5423]
**Describe the bug**
I have an advanced content types pods which has a Date/Time field.

I display the field on my page using display method like below.

$pod->display('field_name')

It displayed "2019/07/18 18:19" before I updated my pods plugin to 2.7.14.

It displays "2019/07/19 03:19" with 2.7.14. 

My wordpress time zone is Tokyo.

I guess this issue is related to https://github.com/pods-framework/pods/issues/5402 which was fixed in 2.7.13.

**To Reproduce**
1. Set wordpress time zone to Tokyo.
2. Create an advanced content types pods.
3. Create a Date/Time field in the pods.
4. Insert current date and time in the field.
5. Display the field using display method like below.
   $pod->display('field_name')

**Expected behavior**
For example, if you insert "2019/07/18 18:19" to the field, it should display "2019/07/18 18:19" not "2019/07/19 03:19"

**Screenshots**
![Pods_date_time](https://user-images.githubusercontent.com/40485661/61500789-b33b1f00-aa07-11e9-82a9-30643dc4acfd.png)

## Pods Version
2.7.14

## WordPress Environment
<details>

`
### wp-core ###

version: 5.2.2
site_language: ja
user_language: ja
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 14
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Applications/MAMP/htdocs/photobin
wordpress_size: 275.85 MB (289247132 bytes)
uploads_path: /Applications/MAMP/htdocs/photobin/wp-content/uploads
uploads_size: 189.02 MB (198199362 bytes)
themes_path: /Applications/MAMP/htdocs/photobin/wp-content/themes
themes_size: 8.53 MB (8941654 bytes)
plugins_path: /Applications/MAMP/htdocs/photobin/wp-content/plugins
plugins_size: 25.25 MB (26474311 bytes)
database_size: 6.38 MB (6690372 bytes)
total_size: 505.02 MB (529552831 bytes)

### wp-active-theme ###

name: Onepress Child
version: 1.2.0
author: 匿名
author_website: (undefined)
parent_theme: OnePress
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, woocommerce, custom-logo, recommend-plugins, customize-selective-refresh-widgets, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-styles, align-wide, editor-style, widgets
theme_path: /Applications/MAMP/htdocs/photobin/wp-content/themes/onepress

### wp-themes (2) ###

OnePress: version: 2.2.4, author: FameThemes
THE THOR: version: 1.1.0, author: Kota Naito　@FIT(フィット)

### wp-plugins-active (15) ###

All-in-One WP Migration: version: 6.97, author: ServMask (latest version: 7.0)
Breadcrumb NavXT: version: 6.3.0, author: John Havlik
Category Order and Taxonomy Terms Order: version: 1.5.7, author: Nsp-Code
Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.3, author: Takayuki Miyoshi
Nav Menu Roles: version: 1.9.3, author: Kathy Darling
Pods - Custom Content Types and Fields: version: 2.7.14, author: Pods Framework Team
Search & Filter: version: 1.2.11, author: Designs & Code
Show Current Template: version: 0.3.0, author: JOTAKI Taisuke
User Role Editor: version: 4.51.1, author: Vladimir Garagulya (latest version: 4.51.2)
WP-Members: version: 3.2.9.2, author: Chad Butler (latest version: 3.2.9.3)
WP Match: version: 2.8.0, author: Masato Fukaya
WP Match Promotion: version: 1.0.0, author: Masato Fukaya
WP Match Slug: version: 1.0.1, author: Masato Fukaya
WP Multibyte Patch: version: 2.8.2, author: Seisuke Kuraishi

### wp-plugins-inactive (3) ###

Search & Filter Pro: version: 2.4.6, author: Code Amp

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: 使用できません
imagemagick_version: 使用できません
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 17.7.0 x86_64
httpd_software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.14 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
php_version: 7.2.14 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 32M
php_post_max_size: 8M
curl_version: 7.60.0 OpenSSL/1.0.2o
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.25
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Applications/MAMP/htdocs/photobin/wp-content
WP_PLUGIN_DIR: /Applications/MAMP/htdocs/photobin/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.14 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
pods-session-save-path: /Applications/MAMP/tmp/php
pods-session-save-path-exists: はい
pods-session-save-path-writable: はい
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: いいえ
pods-opcode-cache-memcached: いいえ
pods-opcode-cache-opcache: いいえ
pods-opcode-cache-redis: いいえ
pods-object-cache-apc: いいえ
pods-object-cache-apcu: いいえ
pods-object-cache-memcache: いいえ
pods-object-cache-memcached: いいえ
pods-object-cache-redis: いいえ
pods-memory-current-usage: 54.128M
pods-memory-current-usage-real: 12.250M
pods-network-wide: いいえ
pods-install-location: /Applications/MAMP/htdocs/photobin/wp-content/plugins/pods/
pods-developer: いいえ
pods-tableless-mode: いいえ
pods-light-mode: いいえ
pods-strict: はい
pods-allow-deprecated: いいえ
pods-api-cache: はい

`
</details>

## Pods Package Export (helpful!)
```
{"meta":{"version":"2.7.14","build":1563495544},"pods":{"196":{"id":196,"name":"talk","label":"トーク","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"message":{"id":197,"name":"message","label":"メッセージ","description":"","help":"","class":"","type":"paragraph","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","paragraph_allow_html":"1","paragraph_oembed":"0","paragraph_wptexturize":"1","paragraph_convert_chars":"1","paragraph_wpautop":"1","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","paragraph_max_length":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"paragraph_repeatable":"0","paragraph_placeholder":""},"send_dt":{"id":198,"name":"send_dt","label":"送信日時","description":"","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","datetime_format":"ymd_slash","datetime_time_type":"24","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"datetime_repeatable":"0","datetime_type":"format","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"parent_talk_id":{"id":199,"name":"parent_talk_id","label":"親メッセージID","description":"","help":"","class":"","type":"number","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"9999.99","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""},"sender_id":{"id":200,"name":"sender_id","label":"送信者ID","description":"","help":"","class":"","type":"number","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"9999.99","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""},"sender":{"id":201,"name":"sender","label":"送信者","description":"","help":"","class":"","type":"pick","weight":4,"pick_object":"user","pick_val":"","sister_id":"","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_allow_add_new":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"receiver_id":{"id":202,"name":"receiver_id","label":"受信者ID","description":"","help":"","class":"","type":"number","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"9999.99","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""},"receiver":{"id":203,"name":"receiver","label":"受信者","description":"","help":"","class":"","type":"pick","weight":6,"pick_object":"user","pick_val":"","sister_id":"","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_taggable":"0","pick_limit":"0","pick_allow_html":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_allow_add_new":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"type":{"id":204,"name":"type","label":"タイプ","description":"","help":"","class":"","type":"text","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"receiver_read_dt":{"id":205,"name":"receiver_read_dt","label":"受信者既読日時","description":"","help":"","class":"","type":"datetime","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","datetime_format":"ymd_slash","datetime_time_type":"24","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"datetime_repeatable":"0","datetime_type":"format","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"thread_last_update_dt":{"id":206,"name":"thread_last_update_dt","label":"スレッド最終更新日時","description":"","help":"","class":"","type":"datetime","weight":9,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","datetime_format":"ymd_slash","datetime_time_type":"24","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"datetime_repeatable":"0","datetime_type":"format","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"attachment":{"id":458,"name":"attachment","label":"attachment","description":"","help":"","class":"","type":"file","weight":10,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","unique":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"ファイルを添付","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"talk","pod_index":"id","hierarchical":"0","ui_style":"post_type","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":["message","send_dt","parent_talk_id","sender_id","sender","receiver_id","receiver"],"ui_filters":["message","send_dt","parent_talk_id","sender_id","sender","receiver_id","receiver"]}}}
```

**Additional context**

**Possible Workaround**
I've rolled back to Pods v2.7.12 for now because v2.7.13 has another date/time issue.

**Comment by jimtrue** [comment]
This sounds like it's related to #5402

**Comment by MasatoFukaya** [comment]
Does anyone take care of this issue?

**Comment by sc0ttkclark** [comment]
I'm trying to reproduce this issue right now, as soon as I'm successful I'll have a better handle on timeframe.

**Comment by sc0ttkclark** [comment]
What timezone setting do you have set under Settings > General?

**Comment by MasatoFukaya** [comment]
Hi,

Timezone is Tokyo.

Here is the reproduce step.

To Reproduce
Steps to reproduce the behavior:

Set wordpress time zone to Tokyo.
Create an advanced content types pods.
Create a Date/Time field in the pods.
Insert current date and time in the field.
Display the field using display method like below.
$pod->display('field_name')

**Comment by sc0ttkclark** [comment]
I tried setting WP timezone to Tokyo, tried changing PHP config timezone to Asia/Tokyo, tried setting my Linux server timezone to Asia/Tokyo, but nothing ended up allowing me to reproduce this problem. I'm eager to resolve it but I'm stuck here. Do you happen to have a dev site or a site I could get access to? You can send me a DM in our Pods Slack, my user is sc0ttkclark

**Comment by sc0ttkclark** [comment]
I also tried importing your package, which imported and I'm able to save data. But the dates all come back as I enter them in my tests.

**Comment by MasatoFukaya** [comment]
Thank you for looking into this issue.
I'll send you a DM in the Slack.

**Comment by JoryHogeveen** [comment]
@MasatoFukaya Could you test #5418 and see if this patch fixes your issue?

**Comment by MasatoFukaya** [comment]
@JoryHogeveen I tested #5418. I confirmed that this patch fixed the issue.
