### ISSUE TITLE
Pods Shortcode button on Elementor editor brings up empty list

### ISSUE THREAD

**Issue by HmCody** [pods-framework/pods#5426]
**Describe the bug**
When I click on the Pods Shortcode button at the top of the Elementor Edit Text Editor widget, the pop-up that appears is empty. Shortcodes that are already inserted still work, I just can't insert new ones from the list.

**To Reproduce**
See above

**Expected behavior**
I expect the pop-up to be filled with a list of shortcodes to insert.

**Screenshots**
![image](https://user-images.githubusercontent.com/33326939/61892899-d61f7480-aeda-11e9-8aeb-b27f8ad2b44f.png)

## Pods Version
2.7.14

## WordPress Environment

<details>

`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: undefined
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: XXXX
wordpress_size: 37.40 MB (39221382 bytes)
uploads_path: XXXX/wp-content/uploads
uploads_size: 36.55 MB (38325401 bytes)
themes_path: XXXX/wp-content/themes
themes_size: 5.22 MB (5471440 bytes)
plugins_path: XXXX/wp-content/plugins
plugins_size: 27.88 MB (29236511 bytes)
database_size: 4.14 MB (4341804 bytes)
total_size: 111.20 MB (116596538 bytes)

### wp-active-theme ###

name: Hello Child
version: undefined
author: Anonymous
author_website: (undefined)
parent_theme: Hello Elementor
theme_features: menus, post-thumbnails, automatic-feed-links, title-tag, html5, custom-logo, editor-style, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: XXXX/wp-content/themes/hello-elementor

### wp-themes (4) ###

Astra Child: author: Anonymous, version: (undefined)
Astra: version: 1.8.7, author: Brainstorm Force
Hello Elementor: version: 2.2.0, author: Elementor Team
Twenty Nineteen: version: 1.4, author: the WordPress team

### wp-mu-plugins (1) ###

Elementor Safe Mode: version: 1.0.0, author: Elementor.com

### wp-plugins-active (10) ###

Admin Columns Pro: version: 4.6.3, author: AdminColumns.com
Admin Columns Pro - Pods: version: 1.4.3, author: Admin Columns
Current Year and Copyright Shortcodes: version: 1.0.2, author: David Gewirtz
Duplicate Post: version: 3.2.3, author: Enrico Battocchi
Ele Custom Skin: version: 1.1.4, author: Liviu Duda
Elementor: version: 2.6.6, author: Elementor.com
Elementor Pro: version: 2.6.1, author: Elementor.com
Loginizer: version: 1.4.2, author: Raj Kothari
Pods - Custom Content Types and Fields: version: 2.7.14, author: Pods Framework Team
WPS Hide Login: version: 1.5.3, author: WPServeur, NicolasKulka, tabrisrp

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.1.30 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 50M
php_post_max_size: 8M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.1.40-MariaDB-cll-lve
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: XXX/wp-content
WP_PLUGIN_DIR: XXXX/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: LiteSpeed
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
pods-session-save-path: /opt/alt/php71/var/lib/php/session
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: Yes
pods-memory-current-usage: 37.246M
pods-memory-current-usage-real: 38.000M
pods-network-wide: No
pods-install-location: XXXX/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by youliaaa** [comment]
Any updates on this issue? I need a workaround to deal with the wysiwyg pod field/elementor issue and was under the impression this is the workaround? Really frustrating that Elementor still hasn't fixed the wysiwyg pod field issue and now the workaround isn't working either? Please FIX this urgently!!!

**Comment by JoryHogeveen** [comment]
Hello @youliaaa 
Please contact the Elementor team for a fix since we haven't had any part in the integration addon for Pods and Elementor. If they have questions or anything we'd like to help where possible!

**Comment by youliaaa** [comment]
@JoryHogeveen  - thank you, will do. Apologies for posting this here. I thought this was the Elementor support area but it's clearly not! :)
