### ISSUE TITLE
Updating WP profile (with extra POD database field/s) does NOT save to database.

### ISSUE THREAD

**Issue by richardfoley** [pods-framework/pods#5433]
**Describe the bug**

firstly, thanks for this incredibly useful looking plugin. It was the only of several I tried to enable me to almost seamlessly connect to the database and use a database table/column as fields in the user profile. Much kudos!

However, I have a slight issue 🙂

When the user updates their profile, with the values from the correctly displayed popup, and the “profile updated” message is displayed, the data is not saved to the database.

I did notice the following in the logs: PHP Notice: wpdb::prepare was called <strong>incorrectly</strong>. The query only expected one placeholder, but an array of multiple placeholders was sent. However, I only see this error when 2 fields are “(not)updated” and not when a single field is “(not)updated”.

**To Reproduce**
1. Go to own wordpress user profile.
2. Modify the relevant fields.
3. Click "update profile".
4. See "profile updated" message.

**Expected behavior**
The data should be saved to the database.

**Screenshots**

## Pods Version
2.7.14 

## WordPress Environment

<details>
`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/clients/client8/web5/web
wordpress_size: 88.44 MB (92732244 bytes)
uploads_path: /var/www/clients/client8/web5/web/wp-content/uploads
uploads_size: 2.43 MB (2546064 bytes)
themes_path: /var/www/clients/client8/web5/web/wp-content/themes
themes_size: 10.36 MB (10863052 bytes)
plugins_path: /var/www/clients/client8/web5/web/wp-content/plugins
plugins_size: 138.91 MB (145653210 bytes)
database_size: 10.44 MB (10944512 bytes)
total_size: 250.57 MB (262739082 bytes)

### wp-active-theme ###

name: Expat
version: 1.01
author: Richard Foley
author_website: https://www.expat.cat/
parent_theme: GeneratePress
theme_features: automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, editor-color-palette, responsive-embeds, custom-logo, menus, editor-style, widgets
theme_path: /var/www/clients/client8/web5/web/wp-content/themes/generatepress

### wp-themes (6) ###

GeneratePress: version: 2.3.2, author: Tom Usborne
Square: version: 1.5.1, author: HashThemes
SquarePress: version: 1.0.0, author: Hash Themes
Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (18) ###

Awesome Support: version: 5.8.0, author: Awesome Support Team
Broken Link Checker: version: 1.11.8, author: ManageWP
Clean Login: version: 1.9.10, author: codection
Contact Form 7: version: 5.1.3, author: Takayuki Miyoshi (latest version: 5.1.4)
Contact Form 7 - Dynamic Text Extension: version: 2.0.3, author: Chris Mavricos, SevenSpark
Flamingo: version: 2.0, author: Takayuki Miyoshi
If Menu - Visibility control for menu items: version: 0.15, author: Layered
Maintenance Mode: version: 2.4.3, author: Lukas Juhas
Pods - Custom Content Types and Fields: version: 2.7.14, author: Pods Framework Team
Popups - WordPress Popup: version: 1.9.3.7, author: timersys
RFI: version: 0.02, author: Richard Foley
s2Member Framework: version: 190617, author: WP Sharks
TablePress: version: 1.9.2, author: Tobias Bäthge
User Role Editor: version: 4.51.2, author: Vladimir Garagulya
WP GDPR Compliance: version: 1.5.2, author: Van Ons
WPSSO Core (Premium) [Main Plugin]: version: 5.3.2, author: JS Morisset (latest version: 5.5.0)
WPSSO Ridiculously Responsive Social Sharing Buttons: version: 2.2.1, author: JS Morisset
WPSSO Update Manager: version: 2.1.0, author: JS Morisset

### wp-plugins-inactive (6) ###

Advanced Custom Fields: version: 5.8.2, author: Elliot Condon
Akismet Anti-Spam: version: 4.1.2, author: Automattic
Contact Form 7 Conditional Fields: version: 1.6.4, author: Jules Colle
Username Changer: version: 3.1.3, author: Daniel J Griffiths
WP-ISPConfig: version: 3.0, author: Esteban Truelsegaard <esteban@netmdp.com>
WP-ISPConfig3: version: 1.4.2, author: ole1986 <ole.k@web.de>, MachineITSvcs <contact@machineitservices.com>

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.0-9-686-pae i686
httpd_software: nginx/1.10.3
php_version: 7.0.33-9+0~20190712.17+debian9~1.gbp3af52c
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.52.1 OpenSSL/1.0.2s
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.1.38-MariaDB-0+deb9u1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: https://www.expat.cat
WP_SITEURL: https://www.expat.cat
WP_CONTENT_DIR: /var/www/clients/client8/web5/web/wp-content
WP_PLUGIN_DIR: /var/www/clients/client8/web5/web/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.10.3
pods-user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
pods-session-save-path: /var/www/clients/client8/web5/tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Yes
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: Yes
pods-object-cache-apcu: Yes
pods-object-cache-memcache: Yes
pods-object-cache-memcached: No
pods-object-cache-redis: Yes
pods-memory-current-usage: 7.542M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: /var/www/clients/client8/web5/web/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes

`
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.14","build":1565103005},"pods":{"661":{"id":661,"name":"user","label":"User","description":"","type":"user","storage":"meta","object":"user","alias":"","fields":{"country":{"id":662,"name":"country","label":"Country","description":"Country","help":"","class":"","type":"pick","weight":0,"pick_object":"table","pick_val":"countries","sister_id":"","required":"1","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_table":"countries","pick_table_id":"country_code_char2","pick_table_index":"country_name","pick_display":"country_name","pick_orderby":"country_name","pick_select_text":"","pick_where":"","pick_groupby":""},"state":{"id":664,"name":"state","label":"State","description":"State","help":"","class":"","type":"pick","weight":1,"pick_object":"table","pick_val":"states_subdivisions","sister_id":"","pick_table":"states_subdivisions","required":"1","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_table_id":"state_subdivision_code","pick_table_index":"state_subdivision_name","pick_display":"state_subdivision_name","pick_user_role":[],"pick_orderby":"state_subdivision_name","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_where":"LENGTH( country_name ) >= 1","pick_select_text":"","pick_groupby":""}},"show_in_menu":1,"rest_enable":"0","read_all":"0","write_all":"0"}}}
```

**Additional context**
Also reported on WordPress.org:
https://wordpress.org/support/?post_type=topic&p=11805137

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment]
Hello @richardfoley,

Could you please share the full notice? It should also contain document name and line number so it's easier for us to debug.
Thanks!

**Comment by richardfoley** [comment]
hi Jory, gladly: 
`[07-Aug-2019 13:14:41 UTC] PHP Notice:  wpdb::prepare was called <strong>incorrectly</strong>. The query only expected one placeholder, but an array of multiple placeholders was sent. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.9.0.) in /var/www/clients/client8/web5/web/wp-includes/functions.php on line 4773
`

**Comment by JoryHogeveen** [comment]
Hi @richardfoley 
Thanks! Do you also happend you have a call stack?

**Comment by richardfoley** [comment]
that's all the information that was dumped to the logs. :\

**Comment by jamesgol** [comment]
I'm pretty certain the problem here is your 'Table ID Column' are not numeric.  Pods expects there to be a unique numeric index for any table.  At one point I tried removing this restriction but there were far too many places that have the same assumption and I couldn't be sure it wasn't breaking more.

The simple fix I went for was just adding a unique ID to each row.

**Comment by richardfoley** [comment]
hi James, that sounds plausible enough. Since this bug was reported, I've moved to a different solution to my particular issue, so it's not possible to investigate further at this end. Closing for this reason.
