### ISSUE TITLE
Feature: Change year range for date fields.

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5442]
As the title says. Currently it only allows the default while this is an option for the jQuery datepicker.

Related: https://wordpress.org/support/topic/date-picker-years-range/

**Comment by Science4me** [comment]
This update makes it impossible to pick the Text field and also the datepicker does not work on the  backend , only on the frontend

**Comment by JoryHogeveen** [comment]
Hi @Science4me 
Please make sure you've cleared your cache etc.
I've tested this update locally without any problems.

**Comment by Science4me** [comment]
I cleared my cache several times

**Comment by JoryHogeveen** [comment]
Can you share your import package? (Componend > Migrate Packages)

**Comment by Science4me** [comment]
I didnt migrate it, i just updated the plugin from the wordpress dashboard

**Comment by JoryHogeveen** [comment]
Just tested again (locally) without problems.

> I didnt migrate it, i just updated the plugin from the wordpress dashboard

I mean share your package here so I can test your exact configuration locally.

**Comment by Science4me** [comment]
{"meta":{"version":"2.7.14","build":1567697842},"pods":{"37":{"id":37,"name":"talent","label":"Models","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"age":{"id":50,"name":"age","label":"Age","description":"","help":"","class":"","type":"date","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"format","date_format":"mdy","date_allow_empty":"1","date_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","date_year_range_custom":"-10:+10","date_format_custom":"","date_format_custom_js":""},"height":{"id":55,"name":"height","label":"Height","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"91cm\/3ft\n94cm\/3ft
1inch\n97cm\/3ft 2inch\n99cm\/3ft 3inch\n102cm\/3ft 4inch\n104cm\/3ft
5inch\n107cm\/3ft 6inch\n109cm\/3ft 7inch\n112cm\/3ft 8inch\n114cm\/3ft
9inch\n117cm\/3ft 10inch\n119cm\/3ft 11inch\n122cm\/4ft\n124cm\/4ft
1inch\n127cm\/4ft 2inch\n130cm\/4ft 3inch\n132cm\/4ft 4inch\n135cm\/4ft
5inch\n137cm\/4ft 6inch\n140cm\/4ft 7inch\n142cm\/4ft 8inch\n145cm\/4ft
9inch\n147cm\/4ft 10inch\n150cm\/4ft 11inch\n152cm\/5ft\n155cm\/5ft
1inch\n157cm\/5ft 2inch\n160cm\/5ft 3inch\n163cm\/5ft 4inch\n165cm\/5ft
5inch\n168cm\/5ft 6inch\n170cm\/5ft 7inch\n173cm\/5ft 8inch\n175cm\/5ft
9inch\n178cm\/5ft 10inch\n180cm\/5ft 11inch\n183cm\/6ft\n185cm\/6ft
1inch\n188cm\/6ft 2inch\n191cm\/6ft 3inch\n193cm\/6ft 4inch\n196cm\/6ft
5inch\n198cm\/6ft 6inch\n201cm\/6ft 7inch\n203cm\/6ft 8inch\n206cm\/6ft
9inch\n208cm\/6ft 10inch\n211cm\/6ft
11inch","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","um_actors","um_models"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"country":{"id":53,"name":"country","label":"Country","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"country","pick_val":"","sister_id":"","pick_custom":"India\nAustralia\nSouth
Africa\nEurope\nUSA\nLondon\nSingapore\n","required":"1","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"city":{"id":4973,"name":"city","label":"City","description":"","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong
em a ul ol li b
i","text_max_length":"255","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"language":{"id":78,"name":"language","label":"Language(s)
Spoken","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong
em a ul ol li b
i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","um_musicians"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","text_placeholder":""},"gallery":{"id":91,"name":"gallery","label":"Additional
Gallery
Photos","description":"","help":"","class":"","type":"file","weight":5,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add
File","file_modal_title":"Attach a file","file_modal_add_button":"Add
File","file_wp_gallery_output":"1","file_wp_gallery_link":"file","file_wp_gallery_columns":"3","file_wp_gallery_random_sort":"1","file_wp_gallery_size":"large","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","member"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","file_allowed_extensions":""},"gallery_premium":{"id":5302,"name":"gallery_premium","label":"Premium
Gallery (must be 18 or over and a Member to view these
photos)","description":"","help":"","class":"","type":"wysiwyg","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","member"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"video":{"id":95,"name":"video","label":"Video","description":"","help":"","class":"","type":"wysiwyg","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"1","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","pmpro_role_2","pmpro_role_3"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"audio":{"id":94,"name":"audio","label":"Audio","description":"","help":"","class":"","type":"wysiwyg","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","pick_post_status":["publish"],"admin_only":"0","restrict_role":"1","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","um_musicians"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"my_services":{"id":73,"name":"my_services","label":"Modeling
Services","description":"","help":"","class":"","type":"pick","weight":9,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"Editorial\nFashion\nFit
Modeling\nFitness\nGlamour\nHair\/Makeup\nLifestyle\nLingerie\nSwimwear\nNude","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","um_musicians"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"additional_skills":{"id":75,"name":"additional_skills","label":"Additional
Skills","description":"","help":"","class":"","type":"pick","weight":10,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"Acting\nSinging\nMusician\nDancing\nScript
writing\nDirecting\nShort Film Shooting\nMimicry\nComedy \nVoice
Dubbing\nPhotography\nWriting\nDialog
Delivery\n","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"biography":{"id":96,"name":"biography","label":"About
Me","description":"","help":"","class":"","type":"wysiwyg","weight":11,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","wysiwyg_allowed_html_tags":""},"facebook_profile_link":{"id":4970,"name":"facebook_profile_link","label":"Facebook
Profile
Link","description":"","help":"","class":"","type":"text","weight":12,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"1","text_allow_html":"0","text_allowed_html_tags":"strong
em a ul ol li b
i","text_max_length":"255","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"1","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"twitter_profile_link":{"id":4971,"name":"twitter_profile_link","label":"Twitter
Profile
Link","description":"","help":"","class":"","type":"text","weight":13,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"1","text_allow_html":"0","text_allowed_html_tags":"strong
em a ul ol li b
i","text_max_length":"255","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"instagram_profile_link":{"id":4972,"name":"instagram_profile_link","label":"Instagram
Profile
Link","description":"","help":"","class":"","type":"text","weight":14,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"1","text_allow_html":"0","text_allowed_html_tags":"strong
em a ul ol li b
i","text_max_length":"255","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_songlink":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Model","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"custom","capability_type_custom":"Model
Member","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"pending","supports_author":"1","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_talent_category":"1","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_elementor_library_category":"0","rewrite_custom_slug":"model","has_archive_slug":"model","built_in_taxonomies_fv-category":"0"},"97":{"id":97,"name":"talent_category","label":"Models
Categories","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Model
Category","public":"1","show_ui":"1","hierarchical":"1","built_in_post_types_talent":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"custom","capability_type_custom":"talent_category","query_var":"0","sort":"0","built_in_post_types_ae_global_templates":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor-hf":"0","built_in_post_types_elementor_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_um_form":"0","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"0","show_tagcloud_in_edit":"0","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_amn_mi-lite":"0","built_in_post_types_amn_wpforms-lite":"0","built_in_post_types_notification":"0","built_in_post_types_omapi":"0","built_in_post_types_um_directory":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0"}}}

**Comment by JoryHogeveen** [comment]
I'm unable to import your package (probably because your response is from an email instead if GitHub itself).
Anyhow, I do see your date field config and it looks fine to me.

Do you see any JavaScript errors in your browser console?

**Comment by Science4me** [comment]
Yes i saw some javascript errors in the browser console.
Do you want me to send that?

**Comment by JoryHogeveen** [comment]
Yes please!

**Comment by Science4me** [comment]
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version
1.4.1
admin-ajax.php:1 Failed to load resource: the server responded with a
status of 400 ()
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
admin-ajax.php:1 Failed to load resource: the server responded with a
status of 400 ()
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
admin-ajax.php:1 Failed to load resource: the server responded with a
status of 400 ()
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
extension.js:24 onMessage extension
ial.js:425 Clean the cache of the scraper (new onComplete event)
admin-ajax.php:1 Failed to load resource: the server responded with a
status of 400 ()
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
error @ (index):853
i @ jquery.js?ver=1.12.4-wp:2
fireWith @ jquery.js?ver=1.12.4-wp:2
x @ jquery.js?ver=1.12.4-wp:4
c @ jquery.js?ver=1.12.4-wp:4
admin-ajax.php:1 Failed to load resource: the server responded with a
status of 400 ()
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
error @ (index):853
i @ jquery.js?ver=1.12.4-wp:2
fireWith @ jquery.js?ver=1.12.4-wp:2
x @ jquery.js?ver=1.12.4-wp:4
c @ jquery.js?ver=1.12.4-wp:4
jquery.js?ver=1.12.4-wp:4 POST
https://blackscepter.com/wp-admin/admin-ajax.php 400
send @ jquery.js?ver=1.12.4-wp:4
ajax @ jquery.js?ver=1.12.4-wp:4
method.getItemTotal @ (index):843
shortlist_icons @ (index):909
Owl.trigger @ owl.carousel.js?ver=5.2.3:1643
Owl.refresh @ owl.carousel.js?ver=5.2.3:587
Owl.onResize @ owl.carousel.js?ver=5.2.3:646
(anonymous) @ owl.carousel.js?ver=5.2.3:606
d @ jquery.js?ver=1.12.4-wp:2
(index):853 Uncaught ReferenceError: log is not defined
    at Object.error ((index):853)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
error @ (index):853
i @ jquery.js?ver=1.12.4-wp:2
fireWith @ jquery.js?ver=1.12.4-wp:2
x @ jquery.js?ver=1.12.4-wp:4
c @ jquery.js?ver=1.12.4-wp:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4-wp:4
ajax @ jquery.js?ver=1.12.4-wp:4
method.getItemTotal @ (index):843
shortlist_icons @ (index):909
Owl.trigger @ owl.carousel.js?ver=5.2.3:1643
Owl.refresh @ owl.carousel.js?ver=5.2.3:587
Owl.onResize @ owl.carousel.js?ver=5.2.3:646
(anonymous) @ owl.carousel.js?ver=5.2.3:606
d @ jquery.js?ver=1.12.4-wp:2

**Comment by JoryHogeveen** [comment]
Doesn't look like anything related to the datepicker.
I'd have to see your installation to find the problem here. Could you share an account with me so I can take a look? Preferably on a testing environment.
Please do not share it on GitHub but send it by email: info@keraweb.nl

**Comment by Science4me** [comment]
Thanks i have sent you a mail

**Comment by JoryHogeveen** [comment]
#5472 fixes the issue mentioned by @Science4me

**Comment by Science4me** [comment]
Hello,

Is there a way to change the featured image text and arrangement of fields
in post types created with Pods?

**Comment by JoryHogeveen** [comment]
Hi @Science4me 
Please open a new topic as your question is not related to this one.
