### ISSUE TITLE
JS validation for file upload field

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods#5450]
**Describe the bug**
It looks like if you have a file upload field that is required and isn't given a value, it isn't erroring out as it should and instead is acting like its saving, but doesn't save any of the new/updated values in the entire for,.

**To Reproduce**
1. add file up load field, required
2. add other field, required
3. enter values for second field, but not file upload, hit save

**Expected behavior**
File upload field should error out making the user know that it is a required field.

**Comment by JoryHogeveen** [comment]
Hi @nicdford 
Could you test with #5453?
