### ISSUE TITLE
Date/Time input broken on Chrome

### ISSUE THREAD

**Issue by nobleclem** [pods-framework/pods#5460]
**Describe the bug**
A [commit](https://github.com/pods-framework/pods/commit/d3a3f8d11c067d1085d38a17b9c218e70155eac6#diff-2dbde0964414e5e17ad95175aabfe905R138) to "Fix issues with date/time fields and translations (#5451)" has cause a bug in some browsers.  The input for datetime fields was changed from `type="datetime"` to `type="datetime-local"`.  On Chrome this disables the datepicker for the built in browser picker.  However the date format of the value attribute doesn't match what it is expecting.  `value="2019-09-06 13:45:00"` should be `value="2019-09-06T13:45:00"` as shown on [MDN datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) . A simple switch to the new format might break the fallback date picker.

**To Reproduce**
1. Create pod with Date/Time input
2. Create a new post of that pod
3. Set the datetime and save
4. Edit post just created and datetime doesn't show

**Expected behavior**
The date/time picker should work in all browsers if HTML5 is checked or not for that pod field

## Pods Version
2.7.15

**Possible Workaround**
Uncheck HTML5 Input for field until formatting can be fixed.

**Comment by JoryHogeveen** [comment]
Hello @nobleclem 

Because `datetime` is considered deprecated we switched to `datetime-local`. However, the formatting part seems to be an issue. Weirdly enough, Chrome on my PC worked fine.

Could you test the changes in #5462 and let me know if this fixes your issue?

**Comment by nobleclem** [comment]
That simple changed works for me.  Tested in the following:
OSX 10.14.6
- Chrome: 76.0.3809.132 (uses native HTML5)
- Firefox: 69.0 (uses fallback UI)
- Safari: 12.1.2 (uses fallback UI)
