### ISSUE TITLE
Latest update - Edit Pods option not visible - Workaround

### ISSUE THREAD

**Issue by esa1975** [pods-framework/pods#5461]
Noticed after updating to the latest version (2.7.15) that the option to Edit Pods was not visible. I tried clearing cache and the other basic things one would normally do to no avail. It occurred to me to try deactivating / activating and that did the trick. I can't be sure that it's Pods at fault and don't see this as a major issue and am just posting this here so others can find this workaround if they encounter this. If the devs want I can provide more info.

**Comment by JoryHogeveen** [comment]
Hello @esa1975,
Do you mean the menu item in the wp admin menu?

**Comment by esa1975** [comment]
> Hello @esa1975,
> Do you mean the menu item in the wp admin menu?

Yes, that's correct. It appeared to be a fresh install so for a moment I thought somehow the data had been corrupted but fortunately it seems to have just been a UI or cache issue I assume. If others aren't seeing it happen I wouldn't worry about it. Thanks.

**Comment by JoryHogeveen** [comment]
Check, I assume it was also a cache issue (maybe transients / installation error). Closing this, thanks!
