### ISSUE TITLE
Error reporting in block editor not working correctly

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5464]
https://wordpress.org/support/topic/relationship-required-not-working-for-one-to-many

## Describe the bug

The problem is that when a user submits with required fields not being entered Pods will create a WP Error. But if the user returns all previously (correct) entered data is lost.

Two items:
- [ ] Pods fields (DFV and normal) doesn't seem to do JS validation but just allows hitting save (update/publish)
- [ ] When Pods creates the WP Error screen it would be nice to be able to return with the data entered

## Reference

I defined a bidirectional relationship with attributes as followed:

– Options: Required
– Selection type: “Multiple Select”
– Format: “Autocomplete”
– Add allow new: “Yes”

If I fill out other custom fields but don’t define a relationship for the custom relationship field the pod’s custom fields will not be saved because the empty relationship.

Why doesn’t the “required” option work? I would expect that I cannot safe the pod until at least one relationship is defined and the relationship field should be displayed in red or did I do something wrong?

Any help would be greatly appreciate
Albrecht

---

I installed version 2.7.15 and tested this issue. The problem isn’t solved:

If you fill out the cutom fields with data and don’t select an item for a relationship, an error message on a “new” page appears (why not just marking the relationship field in red?) with the “<relationship name> is empty” message. After klicking “back” on that error page, the pod’s page will be displayed but all other fields are empty. All entered data gets lost.

Best regards
Albrecht

## Pods Version
2.7.15

**Comment by JoryHogeveen** [comment]
Might be duplicate but I couldn't find a similar issue.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Punting this to 2.8 since we're close to releasing. Maybe this is already fixed in 2.8?

**Comment by sc0ttkclark** [comment]
I have a solution to blocking the page on errors -- but I'm working with Zack to resolve the validation/error messages not showing in the block editor.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark This has been reported on several cases, hence it's marked as a blocker for 2.9.
IMO a MR release would be great as well.

**Comment by vgstef** [comment]
A fix needs also to work with Classic editor (in my ma case).

**Comment by sc0ttkclark** [comment]
Closing in favor of #2424
