### ISSUE TITLE
Date Fields Empty on Post Edit

### ISSUE THREAD

**Issue by martinconnelly** [pods-framework/pods#5482]
## Issue Overview
We're running into a new issue: we use pods to made an event post type - standard stuff - events have a start date and and end date.  After a recent update (not sure which) when someone goes to edit an event to change the description, for instance, the contents of those date fields is stripped.  Not sure what the best way to go about looking into this is - or if this is the right place to talk about it - but everyone swears up and down that the dates used to stay set when we went back into an event so this seems new.

## Expected Behavior
I would expect dates set to stay set and not need to be set each time. 

## Current Behavior
Any date set in the date field needs to be set again any time an event description is edited. 

## WordPress Environment
WP 5.2.3
<details>
Debug Information
WordPress Version: 5.2.3

PHP Version: 7.0.33-6+ubuntu14.04.1+deb.sury.org+3

MySQL Version: 5.6.40

Server Software: nginx/1.12.1

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 17.744M

Current Memory Usage (real): 8.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/s2/html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No
</details>

**Comment by JoryHogeveen** [comment]
> the contents of those date fields is stripped

What do you mean exactly?

**Comment by martinconnelly** [comment]
Hey Jory - so the "post" has a title and a body like any post - and then because it's an event it also has a start date and end end date. So when someone adds an event, they set the title, the description, and the start and end time.  But when someone decides they need to update the text of event, they click the edit button in the admin - the titles still there, the description is still there, but the dates that had previously set for the event are gone.  This is new behavior - we're seeing it post update from 2.7.13

**Comment by jamesgol** [comment]
I setup a simple test and couldn't duplicate this.  Maybe related to theme or other plugin?

**Comment by sander-p** [comment]
I experience the opposite behaviour. I can't delete the contents of a date field (with "Allow empty value" checked in the field options). Whatever I try, the field always reverts back yo the previously entered value. Sounds familiar to anyone?

**Comment by JoryHogeveen** [comment]
@sander-p Your issue is a different one, already reported here: #5488

**Comment by JoryHogeveen** [comment]
@martinconnelly Is this issue still occurring in the latest release?

**Comment by JoryHogeveen** [comment]
@martinconnelly 
Closing this issue since we didn't receive a reply. Feel free to reopen if needed.
