### ISSUE TITLE
Uncought TypeError: $ is not a function(plugins\pods\ui\fields\datetime.php)

### ISSUE THREAD

**Issue by reinierdc** [pods-framework/pods#5489]
**Describe the bug**
This bug is causing the featured image popup box not working anymore. It is supposed to be a popup but now it doesn't and instead will direct to a new page. To fix this on my end, I need to update the line 187 from  "var $el = $( el )"  to  "$el = jQuery( el )".

**Expected behavior**
Featured image should able to pop up and not redirected to new page

## Screenshot
![Pods](https://user-images.githubusercontent.com/15815700/66108364-04b17e00-e5f5-11e9-9d6f-2489c43e2a8a.png)

## Pods Version
Version 2.7.15

## WordPress Environment
WordPress Version: 4.9.11

**Comment by JoryHogeveen** [comment]
Fixed in #5472
