### ISSUE TITLE
Notice for Undefined index

### ISSUE THREAD

**Issue by IraklisV13** [pods-framework/pods#5490]
**Describe the bug**
When opening a pod in the wordpress management system it shows the notice below:

“Notice: Undefined index: object in /app/wp-content/plugins/pods/classes/PodsAPI.php on line 6115”

It happens both on Custom Post Types and Custom Taxonomies that i have created.

**To Reproduce**
1. Update the plugin from 2.7.12 to 2.7.15
1. Open the main page of plugin, /wp-admin/admin.php?page=pods
2. Click on any pod
3. On top of this page and below the admin bar it shows the notice of the attached image

**Expected behavior**
Not showing any errors or notices.

**Screenshots**
![image](https://user-images.githubusercontent.com/56111544/66115047-baba9f00-e5d8-11e9-8115-470eb8201267.png)

## Pods Version
2.7.15

## WordPress Environment

`
### wp-core ###

version: 5.2.3
site_language: el
user_language: en_US
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 9415
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /app
wordpress_size: 47.67 MB (49987589 bytes)
uploads_path: /app/wp-content/uploads
uploads_size: 332.06 KB (340032 bytes)
themes_path: /app/wp-content/themes
themes_size: 13.52 MB (14175112 bytes)
plugins_path: /app/wp-content/plugins
plugins_size: 162.49 MB (170384103 bytes)
database_size: 130.38 MB (136708096 bytes)
total_size: 354.38 MB (371594932 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: nlg
version: 0.1.7
author: Vee Winch
author_website: (undefined)
parent_theme: none
theme_features: post-thumbnails, woocommerce, title-tag, automatic-feed-links, html5, menus, post-formats, custom-background, widgets
theme_path: /app/wp-content/themes/nlg

### wp-themes (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-mu-plugins (1) ###

doing-ajax-function.php: author: (undefined), version: (undefined)

### wp-plugins-active (36) ###

Adminimize: version: 1.11.5, author: Frank Bültge
Advanced Custom Fields PRO: version: 5.8.4, author: Elliot Condon
All In One SEO Pack: version: 3.2.7, author: Michael Torbert (latest version: 3.2.9)
CDN Enabler: version: 1.0.9, author: KeyCDN
Disable Gutenberg: version: 1.9, author: Jeff Starr
Disable WP REST API: version: 1.6, author: Jeff Starr
FlowPaper: version: 1.9.2, author: Devaldi Ltd
GP Nested Forms: version: 1.0-beta-8, author: Gravity Wiz (latest version: 1.0-beta-8.2)
Gravity Forms: version: 2.4.12, author: rocketgenius
Gravity Forms + Custom Post Types: version: 3.1.15, author: spivurno
Gravity Forms Multilingual: version: 1.5.0, author: OnTheGoSystems
Gravity Perks: version: 2.1.9, author: Gravity Wiz
greeklish-permalinks: version: 3.1, author: Panagiotis Kontogiannis
Incontrl: version: 1.0.0, author: Indice
Microsoft Azure Storage for WordPress: version: 4.1.1, author: 10up, Microsoft Open Technologies
Papercut Nlg settings: version: 1.0.0, author: Indice
Pods - Custom Content Types and Fields: version: 2.7.15, author: Pods Framework Team
Smartsupp Live Chat: version: 3.3, author: Smartsupp
The Events Calendar: version: 4.9.8, author: Modern Tribe, Inc. (latest version: 4.9.9)
The Events Calendar PRO: version: 4.7.7, author: Modern Tribe, Inc. (latest version: 4.7.8.1)
TinyMCE Advanced: version: 5.2.1, author: Andrew Ozz
User Role Editor: version: 4.51.3, author: Vladimir Garagulya
WooCommerce: version: 3.7.0, author: Automattic
WooCommerce PayPal Checkout Gateway: version: 1.6.17, author: WooCommerce
WooCommerce Smart Collection: version: 1.0.13, author: Down Town
WordPress Importer: version: 0.6.4, author: wordpressdotorg
WP-Optimize - Clean, Compress, Cache: version: 3.0.11, author: David Anderson, Ruhani Rabin, Team Updraft (latest version: 3.0.12)
WP Cassify: version: 2.1.9, author: Alain-Aymerick FRANCOIS (latest version: 2.2)
WP Fastest Cache: version: 0.8.9.7, author: Emre Vona (latest version: 0.8.9.8)
WP Favorite Posts: version: 1.6.6, author: Huseyin Berberoglu
WP Mail SMTP: version: 1.6.2, author: WPForms
WPML Multilingual CMS: version: 4.2.0, author: OnTheGoSystems
WPML String Translation: version: 2.10.0, author: OnTheGoSystems
WPML Translation Management: version: 2.8.0, author: OnTheGoSystems
WPS Hide Login: version: 1.5.4.2, author: WPServeur, NicolasKulka, tabrisrp
WP Support Plus: version: 9999, author: Pradeep Makone

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic
Application Insights: version: 2.3, author: ApplicationInsights
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Post Type Switcher: version: 3.2.0, author: John James Jacoby
Query Monitor: version: 3.3.7, author: John Blackbourn
XT Woo Floating Cart: version: 1.3.8, author: XplodedThemes

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.184-linuxkit x86_64
httpd_software: nginx/1.10.3
php_version: 7.3.4 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 300
memory_limit: 512M
max_input_time: 300
upload_max_size: 50M
php_post_max_size: 50M
curl_version: 7.52.1 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.27
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: http://localhost:6080
WP_SITEURL: http://localhost:6080
WP_CONTENT_DIR: /app/wp-content
WP_PLUGIN_DIR: /app/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.10.3
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: Yes
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: Yes
pods-memory-current-usage: 33.241M
pods-memory-current-usage-real: 26.000M
pods-network-wide: No
pods-install-location: /app/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes

`

</details>

## Pods Package Export (helpful!)

[JSON.txt](https://github.com/pods-framework/pods/files/3685686/JSON.txt)

```

**Comment by JoryHogeveen** [comment]
Hello @IraklisV13 
Could you test #5493 and let us know if that fixes your issue?

**Comment by IraklisV13** [comment]
Hello Jory!!

Yes!! It worked!! Thank you for your quick response!! Is there anything
else you want me to do, like comment somewhere for the issue or anything
else?
Also, I keep this change for now and it will be added in the next update
too right?

Thank you for your help!!
Have a nice day!!

Στις Δευ, 7 Οκτ 2019 στις 3:17 μ.μ., ο/η Jory Hogeveen <
notifications@github.com> έγραψε:
