### ISSUE TITLE
Fix DFV modal issue

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5500]
WordPress 5.3 seems to break the DFV modal popup.
- [x] The adminbar and admin menu shouldn't be visible. (Fixed in #5501)
- [ ] Also there is an error:

```
Uncaught TypeError: Cannot read property 'isCurrentPostPublished' of null
    at i (pods-dfv.min.js:1)
    at HTMLDocument.<anonymous> (pods-dfv.min.js:1)
```

- [ ] Backbone is updated to 1.4.0 (not sure if Pods is affected by this)
https://github.com/pods-framework/pods/blob/2.x/ui/js/pods-dfv/_src/file-upload/file-upload.js#L60
More info about the backbone update here: https://make.wordpress.org/core/2019/10/10/wordpress-5-3-backbone-upgrade-guide/

**Comment by JoryHogeveen** [comment]
@sc0ttkclark If I recall correctly, backbone in Pods is unaffected by backbone used in WordPress (I believe @pglewis mentioned that once). Could you verify this?

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Also punting to 2.8 since we're close to release. Maybe already fixed?

**Comment by sc0ttkclark** [comment]
Zack is going to work on making sure the modals are working as expected here
