### ISSUE TITLE
Add "Add New" to Edit Pod's record page

### ISSUE THREAD

**Issue by simpltw** [pods-framework/pods#552]
Basically it would be great to add a button "Add New", so instead going back to list of all items and then clicking on "Add New" I can directly just click on "Add New" button from the edit page (like when creating new Posts or Pages in WP), so, it would look something like this:

http://i47.tinypic.com/2zdncc1.jpg

I think this feature will be a little time-saver.

**Comment by jamesgol** [comment]
Unless I'm missing something (Image doesn't exist anymore) this must have already been completed or a change in WordPress trickled down to make this available
