### ISSUE TITLE
Number/Currency field forces 0 as empty value

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5539]
**Describe the bug**
Reported on Slack.
Numeric fields do not allow an actual empty value (`''`) so deleting a value results in `0` instead of `null`.

## Pods Version
2.7.16.2

**Comment by vosykapavel** [comment]
I have the same issue:
- in default wordpress backend admin metabox
- in the database, after I use `$pod->add( $data )` with code
- in frontend after I show the pods form (when user delete value, the zero is back immediately)
```
$fields = [
        // default null not helping
        'field' => ['default' => null],
        // default '' null not helping
        'field' => ['default' => ''],
];

$my_pod->form($fields);
```

Even when the number is not required. 🤔 

![image](https://user-images.githubusercontent.com/3764279/141795035-0d0ec5d3-6666-4f99-b004-52f78b457d9a.png)

**Comment by JoryHogeveen** [comment]
Hi @vosykapavel Please check on the latest Pods version: 2.8.4 which has been release yesterday.
