### ISSUE TITLE
"Manage Components", "Description" column shows incomplete text

### ISSUE THREAD

**Issue by samkatakouzinos** [pods-framework/pods#5543]
**Describe the bug**

"Manage Components", "Description" column shows incomplete text. 
It's as if the Description is considered as a single line value rather than a multiline value stored in the components header.

**To Reproduce**
1. Go to Admin 'Pods Admin, Components'
2. Read the incomplete Description column values

**Expected behavior**
Expect multiline value of Description stored in component header to be shown correctly.

**Screenshots**
![chrome_2019-11-24_21-45-08](https://user-images.githubusercontent.com/1305871/69493519-bc7f4f80-0f03-11ea-82be-b33c33e2169f.png)

## Pods Version
Please provide the version of Pods you are running: Version 2.7.16.2

## WordPress Environment

<details> <summary> Tools > Site Health > Info. </summary>

`
### wp-core ###

version: 5.3
site_language: en_US
user_language: en_US
timezone: +11:00
permalink: /%postname%/
https_status: true
user_registration: false
default_comment_status: open
multisite: true
user_count: 1
site_count: 2
network_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /var/www/tatdylf.xyz/htdocs/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (8) ###

Admin Columns: version: 3.4.8, author: AdminColumns.com
Easy Updates Manager: version: 8.2.0, author: Easy Updates Manager Team
EWWW Image Optimizer: version: 5.1.3, author: Exactly WWW
Media Library Folders for WordPress: version: 5.1.1, author: Max Foundry
Members: version: 2.2.0, author: MemberPress
Nginx Helper: version: 2.1.0, author: rtCamp
Pods - Custom Content Types and Fields: version: 2.7.16.2, author: Pods Framework Team
User Switching: version: 1.5.3, author: John Blackbourn & contributors

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Cache Enabler: version: 1.3.4, author: KeyCDN
FooGallery: version: 1.8.18, author: FooPlugins
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Media Library Folders for WordPress Reset: version: 5.1.1, author: Max Foundry
WebP Express: version: 0.17.2, author: Bjørn Rosell

### wp-media ###

image_editor: EWWWIO_Imagick_Editor
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
gd_version: 2.2.5
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.0 x86_64
httpd_software: nginx/1.16.1
php_version: 7.3.11-1+0~20191026.48+debian10~1.gbpf71ca0 64bit
php_sapi: fpm-fcgi
max_input_variables: 20000
time_limit: 300
memory_limit: 256M
max_input_time: 300
upload_max_size: 100M
php_post_max_size: 100M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 10.3.20-MariaDB-1:10.3.20+maria~buster-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/tatdylf.xyz/htdocs/wp-content
WP_PLUGIN_DIR: /var/www/tatdylf.xyz/htdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.16.1
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: Yes
pods-memory-current-usage: 6.014M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: /var/www/tatdylf.xyz/htdocs/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.16.2","build":1574591805},"pods":{"25":{"id":25,"name":"faq","label":"FAQs","description":"Frequently Asked Questions","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"FAQ","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"faq","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-editor-help"},"16":{"id":16,"name":"people","label":"People","description":"Details about a Person.","type":"post_type","storage":"meta","object":"","alias":"","fields":{"name_title":{"id":17,"name":"name_title","label":"Title Name","description":"Titles that are used before surnames or full names as a sign of respect.","help":"","class":"person title name","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":"E.g. Mr, Miss, Ms, Mrs, other","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0"},"name_first":{"id":18,"name":"name_first","label":"First Name","description":"Persons first name","help":"","class":"person first name","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":"E.g. John","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0"},"name_last":{"id":19,"name":"name_last","label":"Last Name","description":"Persons last name","help":"","class":"person last name","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":"E.g. Smith","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0"},"birth_date":{"id":20,"name":"birth_date","label":"Birth Date","description":"Persons birthdate","help":"","class":"person birth date","type":"date","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"wp","date_format":"mdy","date_allow_empty":"1","date_html5":"1","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":"","date_year_range_custom":""}},"show_in_menu":"1","label_singular":"Person","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"person","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"1","supports_post_formats":"1","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"1","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-groups"}}}
```

**Additional context**
No other context about the problem.

**Possible Workaround**
No workaround uncovered by me.

**Comment by JoryHogeveen** [comment]
Hi @samkatakouzinos 
Thank you for your report, this has been fixed in #5546
