### ISSUE TITLE
My relationship field no longer displays

### ISSUE THREAD

**Issue by bryanhiggs** [pods-framework/pods#5551]
**Describe the bug**

A while ago, I used the Pods framework to create two pods for our website: UUCM Services and UUCM Speakers.
The UUCM Services Pod has the fields:
Speakers (Relationship with UUCM Speakers)
Service Date (Date)
Service Time (Time)
From Date (Date)

The UUCM Speakers Pod has no added fields beyond the default. We only really use the title field.

I just noticed that the Speakers field is no longer displaying — anywhere on our site. I don’t know exactly when this changed, because I only just noticed it. The only recent change I have made it so enable the REST API for these Pods, to allow the use of the Block Editor in WordPress (Gutenberg). I tried turning off the REST API and it made no difference — still no Speakers displayed.

I’ve looked around and can find no explanation for this.

**To Reproduce**

I have worked on the Pods Support forum, with Jory Hogeveen to try to reproduce this in his environment, but he was unable to reproduce it. He suggested that I clear the Pods cache, which I did, with no change in behavior.

I then did some further investigation on another website that contains an earlier version of our . production website. It was very behind in updates, so I went through and brought it up to date with WordPress. I then updated each of the plugins that were out of date, checking to see whether the problem occurred after each update. Nothing changed. After I’d brought the site up to date, the speaker was displayed.

Then I tried turning on the REST API for UUCM Speakers, and then checked, and the speakers display went away. I then turned the REST API back off, but still the speakers display was not present.

So, it seems that turning on the REST API was the culprit. Next question: How do I get it back to working again? Turning off the REST API doesn’t seem to do it.

At Jory's suggestion, I disabled all the plugins except for Pods. Still no Speakers displayed.

Jory then suggested I submit a bug report here, so here it is.

The 'other' website where I have duplicated the issue, and which is up to date in WordPress and all plugins, and uses the default Twenty Twenty theme, is https://play.uucm.org/ Navigate via the menu Ministries >> Upcoming UUCM Services to view a page that shows the problem. I have updated a UUCM Service with a fake date/time to make it show up, because the page is populated using a Pods shortcode:

[pods name="uucm_service" template="UUCM Service Template" orderby="service_date" where="CAST(service_date.meta_value as  DATE) BETWEEN CURDATE() and '2099/01/01'"]

If you need an account on that website in order to do further investigation, I can give you access.

**Expected behavior**

I expect the Speakers field to display

**Screenshots**

See the https://play.uucm.org/ website

## Pods Version
Please provide the version of Pods you are running: 

Pods Version 2.7.16.2

## WordPress Environment

<details>

`
### wp-core ###

version: 5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 8
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/uucm_admin/play.uucm.org
wordpress_size: 37.73 MB (39560457 bytes)
uploads_path: /home/uucm_admin/play.uucm.org/wp-content/uploads
uploads_size: 236.64 MB (248133880 bytes)
themes_path: /home/uucm_admin/play.uucm.org/wp-content/themes
themes_size: 12.98 MB (13608616 bytes)
plugins_path: /home/uucm_admin/play.uucm.org/wp-content/plugins
plugins_size: 138.55 MB (145280968 bytes)
database_size: 14.95 MB (15679488 bytes)
total_size: 440.85 MB (462263409 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /home/uucm_admin/play.uucm.org/wp-content/themes/twentytwenty

### wp-themes-inactive (1) ###

OceanWP: version: 1.7.3, author: Nick

### wp-plugins-active (1) ###

Pods - Custom Content Types and Fields: version: 2.7.16.2, author: Pods Framework Team

### wp-plugins-inactive (38) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Broken Link Checker: version: 1.11.9, author: ManageWP
Classic Editor: version: 1.5, author: WordPress Contributors
Code Snippets: version: 2.13.3, author: Shea Bunge
Contact Form 7: version: 5.1.6, author: Takayuki Miyoshi
Contact Form 7 Style: version: 3.1.8, author: Johnny, dorumarginean, mlehelsz, MirceaR
Custom Menu Wizard: version: 3.3.1, author: Roger Barrett
Custom Sidebars: version: 3.2.3, author: WPMU DEV
Duplicate Page: version: 4.0, author: mndpsingh287
Easy Google Fonts: version: 1.4.4, author: Titanium Themes
Elementor: version: 2.7.6, author: Elementor.com
Elementor Addons & Templates - Sizzify Lite: version: 1.3.2, author: ThemeIsle
Essential Addons for Elementor: version: 3.6.1, author: WPDeveloper
Gmail SMTP: version: 1.1.9, author: naa986
Granular Controls Elementor: version: 1.0.5, author: Zulfikar Nore
Jetpack by WordPress.com: version: 8.0, author: Automattic
JetSticky For Elementor: version: 1.0.1, author: Crocoblock
List category posts: version: 0.81, author: Fernando Briano
myStickymenu: version: 2.2.6, author: Premio
NavMenu Addon For Elementor: version: 1.1.6, author: ThemeIsle
Nav Menu Roles: version: 1.9.5, author: Kathy Darling
Ocean Custom Sidebar: version: 1.0.5, author: OceanWP
Ocean Extra: version: 1.5.19, author: OceanWP
Ocean Social Sharing: version: 1.0.15, author: OceanWP
Orbit Fox Companion: version: 2.8.14, author: Themeisle
PopBox For Elementor: version: 1.0.7, author: Zulfikar Nore
Popup Maker: version: 1.8.14, author: Popup Maker
Profile Builder - Email Confirmation Field: version: 1.0.4, author: Cozmoslabs, Adrian Spiac
Profile Builder Pro: version: 3.0.6, author: Cozmoslabs
ShareThis Share Buttons: version: 1.2.10, author: ShareThis
Simple History: version: 2.33, author: Pär Thernström
Stackable - Gutenberg Blocks: version: 2.0.3, author: Gambit Technologies, Inc
TinyMCE Advanced: version: 5.3.0, author: Andrew Ozz
Velvet Blues Update URLs: version: 3.2.9, author: VelvetBlues.com
WordPress Importer: version: 0.6.4, author: wordpressdotorg
WP Database Reset: version: 3.1, author: WebFactory Ltd
WP Super Cache: version: 1.7.0, author: Automattic
Yoast SEO: version: 12.6.2, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1655
imagemagick_version: ImageMagick 6.7.7-10 2017-07-31 Q16 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 252 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 6000
	imagick::RESOURCETYPE_MAP: 252 GB
	imagick::RESOURCETYPE_MEMORY: 126 GB
	imagick::RESOURCETYPE_THREAD: not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.10

### wp-server ###

server_architecture: Linux 3.14.52-vs2.3.6.15-1 x86_64
httpd_software: Apache
php_version: 7.0.32 64bit >> Actually, it's PHP 7.3, per my server information
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 64M
php_post_max_size: 65M
curl_version: 7.35.0 OpenSSL/1.0.1f
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.25-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/uucm_admin/play.uucm.org/wp-content
WP_PLUGIN_DIR: /home/uucm_admin/play.uucm.org/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 5.429M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: /home/uucm_admin/play.uucm.org/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.16.2","build":1575907350},"pods":{"6426":{"id":6426,"name":"uucm_service","label":"UUCM Services","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"speakers":{"id":6433,"name":"speakers","label":"Speakers","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"speaker","sister_id":"","required":"1","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","future"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"service_date":{"id":6471,"name":"service_date","label":"Service Date","description":"The date when the service is presented","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","datetime_type":"format","datetime_format":"fjy","datetime_time_type":"12","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","datetime_repeatable":"0","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":"","datetime_year_range_custom":""},"from_date":{"id":7423,"name":"from_date","label":"From Date","description":"This field is used when we have a \"service\" representing a period of time, for example, for summer services","help":"","class":"","type":"datetime","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","datetime_type":"format","datetime_format":"fjy","datetime_time_type":"12","datetime_time_format_custom":"8:14pm","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","oembed_enabled_providers_cartocom":"0","oembed_enabled_providers_codepenio":"0","oembed_enabled_providers_flatio":"0","oembed_enabled_providers_gettyimagescom":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_houzzcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","datetime_repeatable":0,"datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom_js":"","datetime_year_range_custom":""}},"show_in_menu":"1","label_singular":"UUCM Service","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"uucm_service","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","supports_jetpack_publicize":"0","supports_jetpack_markdown":"0","built_in_taxonomies_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"UUCM Service Template","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_ocean_sidebars":"0","built_in_taxonomies_style_category":"0","built_in_taxonomies_user_status":"0"},"6434":{"id":6434,"name":"speaker","label":"UUCM Speakers","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Speaker","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"speaker","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","supports_jetpack_publicize":"0","supports_jetpack_markdown":"0","built_in_taxonomies_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_ocean_sidebars":"0","built_in_taxonomies_style_category":"0","built_in_taxonomies_user_status":"0","pfat_single":"UUCM Service Template","menu_position":"0"}},"templates":{"UUCM Service Template":{"id":6447,"name":"UUCM Service Template","code":"<h3>{@post_title}<\/h3>\r\n\r\n<h5><strong><time>{@service_date}<\/time><\/strong><\/h5>\r\n<h4>{@speakers.post_title}<\/h4>\r\n\r\n<p>{@post_content}<\/p>\r\n\r\n<hr \/>\r\n","type":"template","slug":"uucm-service-template","options":{"_edit_lock":"1575906902:2","_edit_last":"2","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:12:\"uucm_service\";}"}},"Speakers Template":{"id":6457,"name":"Speakers Template","code":"<h3>{@post_title}<\/h3>\r\n\r\n<p>{@post_content}<\/p>","type":"template","slug":"speakers-template","options":{"_edit_lock":"1547087589:2","_edit_last":"2","pod_reference":"a:1:{s:3:\"pod\";s:7:\"speaker\";}","admin_only":"","restrict_capability":"","capability_allowed":""}},"Our Next Service Template":{"id":6506,"name":"Our Next Service Template","code":"<div class=\"upcomingservice_widget\">\r\n\t<small>Our Next Service(s)<\/small>\r\n\t<p class=\"uucm-service-time\">\r\n\t\t[if from_date]\r\n\t\t<time>{@from_date}<\/time><br\/>&nbsp;through<br\/><time>{@service_date}<\/time>\r\n\t\t[else]\r\n\t\t<time>{@service_date}<\/time>\r\n\t\t[\/if]\r\n\t<\/p>\r\n\t<p class-\"uucm-service-title\"><a style=\"color: #ab1b42; text-decoration: none; font-size: 130%; font-weight: bold;\" href=\"{@guid}\">{@post_title}<\/a><\/p>\r\n\t<p class=\"uucm-service-speakers\">{@speakers.post_title}<\/p>\r\n\r\n\t<p>[if post_excerpt]{@post_excerpt}[else]{@post_content,my_excerpt_filter}[\/if]<\/p>\r\n<\/div>","type":"template","slug":"our-next-service-template","options":{"_edit_lock":"1559082114:2","_edit_last":"2","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:12:\"uucm_service\";}"}},"UUCM Services Extracts":{"id":6626,"name":"UUCM Services Extracts","code":"<h3>{@post_title}<\/h3>\r\n\r\n<h5><strong><time>{@service_date}<\/time><\/strong><\/h5>\r\n<h4>{@speakers.post_title}<\/h4>\r\n\r\n<p>{@post_excerpt}<\/p>\r\n\r\n<hr \/>","type":"template","slug":"uucm-services-extracts","options":{"_edit_lock":"1548381005:2","_edit_last":"2","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}"}}}}
```

**Additional context**

None known.

**Possible Workaround**
If you have discovered a workaround, please include it below.

None.

Your anticipated help is much appreciated! I would dearly love to have my speakers displaying again!

**Comment by bryanhiggs** [comment]
Any progress? Do you need access to the https://play.uucm.org/ website to further your investigations?

**Comment by JoryHogeveen** [comment]
Hi @bryanhiggs 
One thing I just noticed is your date formatting. This is not compatible with MySQL date storage.
The correct format is `yyyy-mm-dd` (dashes instead of slashes).
Could you try that?

**Comment by bryanhiggs** [comment]
I have no idea why that might make a difference to the Speakers field, as that is not a date field.
Anyway, I believe the only place I used that format is in the shortcode for the page Upcoming Services. I changed it to use the format you suggest on the https://play.uucm.org/ site, and it made no difference. Still no Speakers.

**Comment by bryanhiggs** [comment]
Any progress?

**Comment by JoryHogeveen** [comment]
Hi @bryanhiggs 
I tried several times to reproduce this issue without success.
Could to create a dev installation where this problem occurs so I can take a a look at your exact installation?
Please send login information to info@keraweb.nl
Thank you!

**Comment by bryanhiggs** [comment]
If you recall, I offered to provide you with an account on my non-live site where I reproduced the problem.
The site is https://play.uucm.org/ , I have created an account with your email address, and the site should by now have sent you an email regarding that account. Please let me know whether or not you received that information and whether or not you are able to log in.

You can see the problem on the page https://play.uucm.org/ministries/upcoming-uucm-services/

Thanks, and good luck.

**Comment by JoryHogeveen** [comment]
Hi @bryanhiggs
Sorry, just found the automated WP email in my spam box and the link is expired. Please create the user without email confirmation and send me the password through email.
Thanks!

**Comment by bryanhiggs** [comment]
I changed the password, and sent you an email with the password.

Let me know whether you succeed or not...

Bryan

**Comment by JoryHogeveen** [comment]
Hello @bryanhiggs 
Looked at your template and found `{@speakers.post_title}` which should be `{@speakers}`.
The speakers are currently showing again.

**Comment by bryanhiggs** [comment]
Hello @JoryHogeveen 
1) Where in the documentation is this documented? 
2) I'm assuming that just referring to @speakers displays something from the relationship, but it's not clear what, exactly (see question 1) above). What exactly is the bare relationship field reference supposed to display?
3) Can you explain why the behavior suddenly changed only after I enabled the REST_API? It was working before that.
4) While you have provided a solution (thanks!), I fear it's merely a partly understood workaround until we fully understand the reasons for this [change of] behavior. If we don't understand the behavior properly, things may break again in mysterious ways.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark @jimtrue can you respond to the above?
I *think* it's because the field is a multi relationship and thus doesn't allow selecting a specific relationship field (that would require `[each]` right).
Not sure why/how this has changed lately.

**Comment by bryanhiggs** [comment]
???

**Comment by JoryHogeveen** [comment]
Hi Bryan,

1) (Confirmed by @jimtrue ) For **multiple relationships**, please take a look at this page for documentation:
https://docs.pods.io/displaying-pods/template-tags/each-loop-tag/
For single relationships your original implementation should be fine.

2) That would be the default output for a multiple relationship field. (Comma separated and the last is separated by "and"). There is no UI for changing this.

3) No idea, that is why I asked @sc0ttkclark . While I do not know why, your previous implementation shouldn't have worked at all for multiple relationships.

4) See 1!
