### ISSUE TITLE
required YES/NO field triggers "This field is required." error when saving + pods values are lost

### ISSUE THREAD

**Issue by mDrozdova** [pods-framework/pods#5552]
## Issue Overview
required YES/NO field triggers "This field is required." error when saving with the "NO" value selected. Post itself is saved, but pods' values are not saved.

## Expected Behavior
It should save the post, also all fields. YES/NO field should save its value even when set to NO.
Also if error occures, PODS should inform which field is problematic, not only "This field is required.".

## Current Behavior
see Issue Overview

## WordPress Environment

<details>
```
WordPress Version: 5.3

PHP Version: 7.2.16

MySQL Version: 5.5.51

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

Session Save Path: /tmp/

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: a6j3h_

WP Multisite Mode: No

WP Memory Limit: 128M

Current Memory Usage: 19,099M

Current Memory Usage (real): 6,000M

Pods Network-Wide Activated: No

Pods Install Location: /web/htdocs2/******** (sorry, but WTF :) /home/www/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: ****** (custom)

Currently Active Plugins:

Block Bad Queries (BBQ): 20191109
Compress JPEG & PNG images: 3.2.0
Crop Thumbnails: 1.2.5
Disable Search: 1.7.1
Easy FancyBox: 1.8.18
ImageMagick Sharpen Resized Images: 1.1.7
InfiniteWP - Client: 1.9.4.4
Pods - Custom Content Types and Fields: 2.7.16.2
Polylang: 2.6.7
Seamless Sticky Custom Post Types: 1.4
Simple Page Ordering: 2.3.2
Wordfence Security: 7.4.2
WPS Hide Login: 1.5.4.2
Yoast SEO: 12.7
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by BrigittaBuerger** [comment]
I have the same problem with required yes/no field in an ACT. Error "This field is required." when I try to save an existing ACT object having value "no" without changing. Saves fine with value 0 (not "null") when I remove "required". I found this error a week ago. It did work before but I cannot say until when.

**Comment by ostryweb-cz** [comment]
same as
https://github.com/pods-framework/pods/issues/5549

**Comment by mDrozdova** [comment]
https://github.com/pods-framework/pods/issues/5549
