### ISSUE TITLE
Shortcode not working after upgrade

### ISSUE THREAD

**Issue by xaquica** [pods-framework/pods#5554]
## Issue Overview
After upgrading to 2.7.16.2 a shortcode that was working well change the behaviour. If I downgrade to 2.7.15 it works fine.

The shortcode is [pods id="{@id}" template="Meditaciones asociadas"]

After the upgrade it shows "Please provide a Pod name"
Before it showed some links to other pods formatted by the template. They are stored in the same post in a relationship.

## Expected Behavior
It shows some links to other pods formatted by the template. They are stored in the same post in a relationship.
![Captura2](https://user-images.githubusercontent.com/58976952/70988529-5466f800-20c2-11ea-8a63-c9e035fd89ba.JPG)

## Current Behavior
It shows "Please provide a Pod name"
![Captura](https://user-images.githubusercontent.com/58976952/70988530-54ff8e80-20c2-11ea-81ff-fd988876a531.JPG)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
WordPress Version: 5.3.1

PHP Version: 7.1.33

MySQL Version: 5.6.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 30,846M

Current Memory Usage (real): 32,000M

Pods Network-Wide Activated: No

Pods Install Location: /home/comermin/staging/1/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: GeneratePress

Currently Active Plugins:

Admin Block Country: 7.1.1
AdSensei B30: 1.9.9.6
Block Bad Queries (BBQ): 20191109
Broken Link Checker: 1.11.9
Code Snippets: 2.13.3
Convert Pro: 1.4.0
Convert Pro - Addon: 1.3.0
Cookie Notice: 1.2.48
Duplicate Post: 3.2.4
Easy Digital Downloads: 2.9.20
Easy Digital Downloads - Auto Register: 1.3.13
Easy Digital Downloads - Content Restriction: 2.3
Easy Digital Downloads - Disable Purchase Receipt: 1.0
Easy Digital Downloads - Downloads As Services: 1.0.6
Easy Digital Downloads - Recurring Payments: 2.9.4
Easy Digital Downloads - Stripe Payment Gateway: 2.7.4
Easy Digital Downloads - Zapier: 1.3.9
Elementor: 2.8.2
Elementor Pro: 2.7.3
Google Analytics Dashboard for WP (GADWP): 5.3.10
GP Premium: 1.9.1
Gutenberg: 7.1.0
kk Star Ratings: 4.1.2
Loco Translate: 2.3.1
Loginizer: 1.4.3
mb.miniAudioPlayer: 1.9.3
Pods - Custom Content Types and Fields: 2.7.16.2
Redirection: 4.5.1
Table of Contents Plus: 1601
UpdraftPlus - Backup/Restore: 2.16.21.24
WAme chat: 3.1.4
Yoast SEO: 12.7.1
</details>

## Pods Package Export (helpful!)

<details>
`{"meta":{"version":"2.7.16.2","build":1576579615},"pods":{"3903":{"id":3903,"name":"clases","label":"Clases","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"url_video":{"id":3904,"name":"url_video","label":"URL Video","description":"","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"1","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"meditaciones_asociadas":{"id":3905,"name":"meditaciones_asociadas","label":"Meditaciones asociadas","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"post_type","pick_val":"meditaciones","sister_id":"3910","_elementor_controls_usage":[],"required":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","future","draft"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_enabled_providers_collegehumorcom":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"url_audio_de_la_clase":{"id":3906,"name":"url_audio_de_la_clase","label":"URL audio de la clase","description":"Versión solo audio de la clase","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"recursos":{"id":4093,"name":"recursos","label":"Otros recursos","description":"Material complementario","help":"","class":"","type":"wysiwyg","weight":3,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"1","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""}},"show_in_menu":"1","_elementor_controls_usage":[],"label_singular":"Clase","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"video","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"0","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"1","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"0","supports_page_attributes":"1","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_cp_campaign":"0","built_in_taxonomies_cp_connections":"0","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_position":"6","menu_icon":"dashicons-media-video","pfat_single":"Meditaciones asociadas","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_download_category":"0","built_in_taxonomies_download_tag":"0","built_in_taxonomies_edd_log_type":"0","rewrite_custom_slug":"eldojo\/clases"},"3907":{"id":3907,"name":"meditaciones","label":"Meditaciones","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"url":{"id":3908,"name":"url","label":"URL audio","description":"DIrección URL donde está el archivo de audio","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"duracion":{"id":3909,"name":"duracion","label":"Duración","description":"Duración de la meditación","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"clases_relacionadas":{"id":3910,"name":"clases_relacionadas","label":"Clases relacionadas","description":"Clases asociadas a esta meditación","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"clases","sister_id":"3905","_elementor_controls_usage":[],"required":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","future","draft"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_enabled_providers_collegehumorcom":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","_elementor_controls_usage":[],"label_singular":"Meditacion","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"meditacion","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"0","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"1","supports_thumbnail":"0","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_cp_campaign":"0","built_in_taxonomies_cp_connections":"0","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_position":"5","menu_icon":"dashicons-media-audio","pfat_single":"Meditaciones asociadas","rewrite_custom_slug":"eldojo\/meditaciones","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_download_category":"0","built_in_taxonomies_download_tag":"0","built_in_taxonomies_edd_log_type":"0"},"4338":{"id":4338,"name":"tutoria","label":"Tutorias","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"url_video":{"id":4339,"name":"url_video","label":"URL Video","description":"Enlace al video de la tutoria","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"1","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""}},"show_in_menu":"1","_elementor_controls_usage":[],"label_singular":"Tutoria","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"tutoria","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_custom_slug":"eldojo\/tutorias","rewrite_with_front":"0","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"1","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"0","supports_page_attributes":"1","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_cp_campaign":"0","built_in_taxonomies_cp_connections":"0","built_in_taxonomies_download_category":"0","built_in_taxonomies_download_tag":"0","built_in_taxonomies_edd_log_type":"0","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"7","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Meditaciones asociadas","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-groups"}},"templates":{"Meditaciones asociadas":{"id":3911,"name":"Meditaciones asociadas","code":"[before]<div class\"meditaciones_estilo\">[\/before]\r\n    [if meditaciones_asociadas]\r\n        <h3>Meditaciones Relacionadas:<\/h3>\r\n        <ul>\r\n            [each meditaciones_asociadas]\r\n            <li>\r\n\t\t\t\t<a href=\"{@permalink}\">{@post_title}<\/a> - Duración: {@duracion} min.\t\t\t\t\r\n\t\t\t<\/li>\r\n            [\/each]\r\n        <\/ul>\r\n    [else]\r\n        <p>No hay ninguna meditación relacionada<\/p>\r\n    [\/if]\r\n[after]<\/div>[\/after]","type":"template","slug":"meditaciones_asociadas","options":{"_elementor_controls_usage":"s:6:\"a:0:{}\";","_edit_lock":"1574143391:4","_edit_last":"4","type":"template","slug":"meditaciones_asociadas","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}","admin_only":"","restrict_capability":"","capability_allowed":""}},"Clases asociadas":{"id":3912,"name":"Clases asociadas","code":"[before]<div class\"meditaciones_estilo\">[\/before]\r\n    [if clases_relacionadas]\r\n        <h3>Clases Relacionadas:<\/h3>\r\n        <ul>\r\n            [each clases_relacionadas]\r\n            <li>\r\n\t\t\t\t<a href=\"{@permalink}\">{@post_title}<\/a>\t\t\t\t\r\n\t\t\t<\/li>\r\n            [\/each]\r\n        <\/ul>\r\n    [else]\r\n        <p>No hay ninguna clase relacionada<\/p>\r\n    [\/if]\r\n[after]<\/div>[\/after]","type":"template","slug":"clases_asociadas","options":{"_elementor_controls_usage":"s:6:\"a:0:{}\";","_edit_lock":"1569502721:1","_edit_last":"1","pod_reference":"s:31:\"s:23:\"a:1:{s:3:\"pod\";s:0:\"\";}\";\";","type":"template","slug":"clases_asociadas"}}}}`
</details>
## Workaround or Alternate Solution Until Bug is Addressed

Downgrade to 2.7.15

**Comment by JoryHogeveen** [comment]
Hello @xaquica 
This indeed was a change in Pods.
If you are trying to use the shortcode for the current object you can omit the `id` paramater.
`[pods template="Meditaciones asociadas"]`
Cheers, Jory

**Comment by xaquica** [comment]
Thanks It is solved
