### ISSUE TITLE
BUG: Image Gallery With Pods for Elementor

### ISSUE THREAD

**Issue by AlexDeat** [pods-framework/pods#5564]
## Solution I Stumbled Upon

Before - [pods name="post" field="galeria_de_imagens"]

Insert Asterisk in both "" id and name and will work with all elementor posts, pods, etc...
After - [pods id="*"name="*" field="galeria_de_imagens"]

i was trying to erase and i typed the id and the name together... it worked... LOL

## Issue Overview
Elementor Post with Pods Image Gallery wont work, it only imports one of the galleries, all other pots have the same gallery. Changing the new post image galleries images doesnt change nothing.

## Expected Behavior
To each post, one individual gallery.
After i create the Gallery Pod, in the gallery space i can chose images without going each post inserting the images with elementor.

## Current Behavior
All posts have the same gallery that the 1st post.

## Pages And Shortcode

Im extending the Post Pod:

The POD config
[image 1](https://amm.arq.br/wp-content/uploads/2020/01/Post-Pod-1.jpg)
[image 2](https://amm.arq.br/wp-content/uploads/2020/01/Post-Pod-2.jpg)
[image 3](https://amm.arq.br/wp-content/uploads/2020/01/Post-Pod-3.png)

Each page has different photos on the gallery
but it shows only the first page.

the shortcode im using:
[pods name="post" field="galeria_de_imagens"]

Pages:
https://amm.arq.br/arquitetura/
https://amm.arq.br/arquitetura-2/
https://amm.arq.br/arquitetura-3/

**Comment by AlexDeat** [comment]
👍

**Comment by JoryHogeveen** [comment]
`[pods name="post" field="galeria_de_imagens"]`
If it's for the current post you should omit the `name` attribute:
`[pods field="galeria_de_imagens"]`

**Comment by AlexDeat** [comment]
I tried that, but for custom pod posts was not working.

Only for post extension worked.

Thank you!
