### ISSUE TITLE
Pods, Elementor, Ninja Forms conflict

### ISSUE THREAD

**Issue by riverBanjo** [pods-framework/pods#5574]
## Issue Overview

When you have Pods, Ninja Forms, and Elementor active the Ninja Forms form builder page white screens. I can see in the Network tab pods things being included on the page.

## Expected Behavior

 

What should happen is that nothing but Ninja Forms' js gets loaded in the builder and it should load. Like this:

![2020-01-16_10-03-49](https://user-images.githubusercontent.com/43787368/72536378-22bf8900-3848-11ea-9116-f62202a45246.png)

## Current Behavior

 

Currently, the Pods' framework seems to be loading onto the builder when I have the latest versions of Pods, Ninja Forms, and Elementor active.

![2020-01-16_09-56-59](https://user-images.githubusercontent.com/43787368/72535487-9bbde100-3846-11ea-9d01-88d5ff502953.png)

## Steps to Reproduce (for bugs)

1. Install the latest version of Ninja Forms, Pods, and Elementor.
2. Try to edit a form.

## WordPress Environment

<details>
```
WordPress Version: 5.3.2

PHP Version: 7.2.9

MySQL Version: 5.7.23

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 7.202M

Current Memory Usage (real): 6.000M

Pods Network-Wide Activated: No

Pods Install Location: /app/public/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: OceanWP

Currently Active Plugins:

Elementor: 2.8.3
Ninja Forms: 3.4.22
Pods - Custom Content Types and Fields: 2.7.16.2
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
See: https://github.com/pods-framework/pods/issues/5354
