### ISSUE TITLE
Feature request – Themer Add-on: options for BB conditional logic

### ISSUE THREAD

**Issue by lhberg** [pods-framework/pods#5584]
## Issue Overview

I miss the possibility to add a Pods Settings Page field to BB conditional logic, especially a yes/no field to e.g. have a module on a page displayed or not by just setting a checkbox or not.

I've done a search for a similar or identical feature request to no avail; if I've missed such (I would be surprised if I was the first one to suggest this), please let me know so that I can delete the feature request.

## Expected Behavior

 

For me it's essential to hide pages to my clients. Since the only way to add conditional logic to a module on a page is to extend the page post with a Pods custom field, I prefer giving my clients access to a Pods Settings Page.

btw. I know I could do this with an ACF Options Page but I really prefer Pods over ACF!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Hello @lhberg 

This is the wrong place for Themer issues and requests.
Please use the correct repo: https://github.com/pods-framework/pods-beaver-builder-themer-add-on/issues

Cheers, Jory

**Comment by lhberg** [comment]
Hello Jory,

thanks for pointing me to the correct repo, I just reposted there.

Cheers,

Lukas
