### ISSUE TITLE
Incorrect date data output

### ISSUE THREAD

**Issue by enetr** [pods-framework/pods#5593]
## Issue Overview
Website's default time is UTC+3 (Europe/Moscow).
I found such a bug dependency.
Till 12 AM and before 3 AM - all of Date fields in all my pods display the dates -1 day.
When 3 AM comes - Pods display the right dates.
Despite the fact that Date field values is always have the right dates.

## Expected Behavior

 

![Screenshot 2020-02-10 03 01 01](https://user-images.githubusercontent.com/60858284/74114157-75773100-4bb9-11ea-9cad-1c9380183ad9.jpg)
![Screenshot 2020-02-10 03 02 09](https://user-images.githubusercontent.com/60858284/74114159-76a85e00-4bb9-11ea-8f00-09a01e4ede3d.jpg)
![Screenshot 2020-02-09 00 12 28](https://user-images.githubusercontent.com/60858284/74112965-1a8e0b80-4bb2-11ea-8028-8cd90ad7c236.png)
![Screenshot 2020-02-09 00 13 38](https://user-images.githubusercontent.com/60858284/74112966-1a8e0b80-4bb2-11ea-9e8d-1591e1300501.png)
![Screenshot 2020-02-09 00 14 56](https://user-images.githubusercontent.com/60858284/74112967-1b26a200-4bb2-11ea-929a-e44d28865e55.png)

## WordPress Environment
<details>
WordPress Version: 5.3.2

PHP Version: 5.6.40

MySQL Version: 5.7.21

Server Software: Apache/2.4.10 (Unix)

Your User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

Session Save Path: /tmp/php_sess

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 28800

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 31,826M

Current Memory Usage (real): 33,000M

Pods Network-Wide Activated: No

Pods Install Location: /home/s/.../.../public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: UnderStrap Child

Currently Active Plugins:

Akismet Anti-Spam: 4.1.3
Classic Editor: 1.5
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: 5.1.0
Custom Post Type Permalinks: 3.3.4
Cyr-To-Lat: 4.3.2
Google XML Sitemaps: 4.1.0
Health Check & Troubleshooting: 1.4.2
Jetpack by WordPress.com: 8.1.1
Pods - Custom Content Types and Fields: 2.7.16.2
WP Super Cache: 1.7.1
Yoast SEO: 13.0
</details>

## Pods Package Export (helpful!)

[export.txt](https://github.com/pods-framework/pods/files/4178318/export.txt)

**Comment by JoryHogeveen** [comment]
This might be a server issue if the timezone isn't setup correctly.
Do you have the same issue on other installations as well?
Pods simply uses the WordPress core functions for formatting and timezone handling so I don't think this is a Pods issue.

**Comment by enetr** [comment]
Thanks @JoryHogeveen, 
I check the server time and UTC time with PHP date and gmdate (screenshots attached below). At what level should I check yet?
On the early versions of PODS (and on this server) I didn't observe this problem.
Is it possible to downgrade the PODS version? Unfortunately I don't have backups of this site with a different version of PODS(

**Comment by enetr** [comment]
@JoryHogeveen 
I just checked this issue on scratch website on this server.
Everything works right.
So the dates conflict is somewhere in our code..(
For the umpteenth time we need to check everything.
Thanks for help and sorry for disturb.
Plugin is great!

**Comment by JoryHogeveen** [comment]
@enetr No problem!
