### ISSUE TITLE
Error when saving pod reated to gravity forms in debug mode

### ISSUE THREAD

**Issue by digitaliway** [pods-framework/pods#5594]
**Describe the bug**
when wordpress is in DEBUG mode only.  

when I save a new pod or create a new on I get the below error when my site is in debug mode. 

Notice: An outdated add-on or custom code is attempting to access the wp1_rg_form table which is not valid
in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data.
Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2
in /home/directory-name/public_html/wp-content/plugins/gravityforms/gravityforms.php on line 5512

**To Reproduce**

modify wp_config making wordpress DEBUG mode.

go to PODS ADMIN > EDIT PODS > EDIT ANY POD THERE - click save and the error below will appear at the top of the page.

Notice: An outdated add-on or custom code is attempting to access the wp1_rg_form table which is not valid
in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data.
Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2
in /home/directory-name/public_html/wp-content/plugins/gravityforms/gravityforms.php on line 5512

I have deactivated all plugins keeping only PODS and GRAVITY FORMS enabled and error remains.

**Expected behavior**
no errors when I save should be expected.

**Screenshots**
https://share.getcloudapp.com/Z4u5dNLp

## Pods Version
Version 2.7.16.2

## WordPress Environment

<details>

`
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1563
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/fox8abc23/public_html
wordpress_size: 40.11 MB (42059458 bytes)
uploads_path: /home/fox8abc23/public_html/wp-content/uploads
uploads_size: 304.06 MB (318834757 bytes)
themes_path: /home/fox8abc23/public_html/wp-content/themes
themes_size: 11.43 MB (11985773 bytes)
plugins_path: /home/fox8abc23/public_html/wp-content/plugins
plugins_size: 185.40 MB (194409484 bytes)
database_size: 48.82 MB (51190438 bytes)
total_size: 589.83 MB (618479910 bytes)

### wp-active-theme ###

name: Total Child (total-child)
version: 1.0
author: digital.iway
author_website: http://www.digitaliway.com
parent_theme: Total (Total)
theme_features: woocommerce, wc-product-gallery-slider, wc-product-gallery-zoom, post-thumbnails, menus, post-formats, automatic-feed-links, html5, title-tag, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /home/fox8abc23/public_html/wp-content/themes/total-child

### wp-parent-theme ###

name: Total (Total)
version: 4.9.8
author: WPExplorer
author_website: https://themeforest.net/user/wpexplorer
theme_path: /home/fox8abc23/public_html/wp-content/themes/Total

### wp-plugins-active (25) ###

ADning: version: 1.4.7, author: Tunafish
Classic Editor: version: 1.5, author: WordPress Contributors
Ele Custom Skin: version: 1.3.10, author: Dudaster.com
Elementor: version: 2.8.5, author: Elementor.com
Elementor Pro: version: 2.8.3, author: Elementor.com
Envato Market: version: 2.0.3, author: Envato
Event Tickets: version: 4.11.3, author: Modern Tribe, Inc. (latest version: 4.11.3.1)
Event Tickets Plus: version: 4.11.2, author: Modern Tribe, Inc.
GP Limit Submissions: version: 1.0-beta-1.20, author: Gravity Wiz
Gravity Forms: version: 2.4.17, author: rocketgenius
Gravity Perks: version: 2.1.9, author: Gravity Wiz
iThemes Security: version: 7.6.1, author: iThemes
Pods - Custom Content Types and Fields: version: 2.7.16.2, author: Pods Framework Team
Postman SMTP: version: 1.7.2, author: Jason Hendriks
PowerPack Elements: version: 1.4.12.3, author: Team IdeaBox - PowerPack Elements
The Events Calendar: version: 5.0.0.2, author: Modern Tribe, Inc.
The Events Calendar: Remove QR Codes: version: 0.1.1, author: Modern Tribe
The Events Calendar PRO: version: 5.0.0.2, author: Modern Tribe, Inc.
TinyMCE Advanced: version: 5.3.0, author: Andrew Ozz
Total Theme Core: version: 1.0.9, author: WPExplorer
User Role Editor: version: 4.53, author: Vladimir Garagulya
WooCommerce: version: 3.9.1, author: Automattic
WooCommerce Authorize.Net Gateway: version: 5.1.9, author: Pledged Plugins
WooCommerce MultiStep Checkout: version: 3.6.6, author: Kole Roy
WP Media folder: version: 5.0.0, author: Joomunited

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.27.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.14 64bit
php_sapi: fpm-fcgi
max_input_variables: 3000
time_limit: 65
memory_limit: 512M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 512M
curl_version: 7.67.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.29
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/fox8abc23/public_html/wp-content
WP_PLUGIN_DIR: /home/fox8abc23/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
pods-session-save-path: /var/cpanel/php/sessions/ea-php73
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 92.175M
pods-memory-current-usage-real: 94.000M
pods-network-wide: No
pods-install-location: /home/fox8abc23/public_html/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.16.2","build":1581462312},"pods":{"18399":{"id":18399,"name":"newspost","label":"News Posts","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"video_news_file":{"id":18401,"name":"video_news_file","label":"Video News File","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"1","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"video","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"video_news_file_captions":{"id":18403,"name":"video_news_file_captions","label":"Video News File Captions","description":"","help":"","class":"","type":"file","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"1","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"other","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":".vtt"}},"show_in_menu":"1","_elementor_controls_usage":[],"label_singular":"News Post","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"newspost","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_action-group":"0","built_in_taxonomies_category":"1","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_portfolio_category":"0","built_in_taxonomies_portfolio_tag":"0","built_in_taxonomies_post_series":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_product_cat":"0","built_in_taxonomies_product_shipping_class":"0","built_in_taxonomies_product_tag":"0","built_in_taxonomies_product_type":"0","built_in_taxonomies_product_visibility":"0","built_in_taxonomies_tribe_events_cat":"0","built_in_taxonomies_wpmf-category":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-welcome-view-site","pfat_single":"Video JW Player Template Pods"},"17836":{"id":17836,"name":"post","label":"Post","description":"","type":"post_type","storage":"meta","object":"post","alias":"","fields":{"video_file_post":{"id":17837,"name":"video_file_post","label":"Video File Post","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"video","file_field_template":"rows","file_add_button":"Add Video","file_modal_title":"Attach a video file","file_modal_add_button":"Add Video","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":1,"_elementor_controls_usage":[],"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"},"18462":{"id":18462,"name":"video_preroll","label":"Video PreRolls","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"video_preroll_file":{"id":18463,"name":"video_preroll_file","label":"Video PreRoll File","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"1","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"video","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","_elementor_controls_usage":[],"label_singular":"Video PreRoll","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"news_preroll","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_action-group":"0","built_in_taxonomies_category":"1","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_portfolio_category":"0","built_in_taxonomies_portfolio_tag":"0","built_in_taxonomies_post_series":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_product_cat":"0","built_in_taxonomies_product_shipping_class":"0","built_in_taxonomies_product_tag":"0","built_in_taxonomies_product_type":"0","built_in_taxonomies_product_visibility":"0","built_in_taxonomies_tribe_events_cat":"0","built_in_taxonomies_wpmf-category":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Video JW Player Template Pods","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-format-video"}},"templates":{"Video JW Player Template Pods":{"id":18428,"name":"Video JW Player Template Pods","code":"<script src=\"https:\/\/site.fox8tv.com\/jwplayer\/jwplayer.js\"><\/script>\r\n<script>jwplayer.key=\"4n8NloDKIn7kme+PbwrbiNnQHTt06j6+5lxiGAk1ZuM=\";<\/script>\r\n\r\n <div id=\"myVideoElement1\"><\/div>\r\n \r\n <script type=\"text\/JavaScript\">\r\n \r\n\tvar playerInstance = jwplayer(\"myVideoElement1\");\r\n\tplayerInstance.setup({\r\n    \r\n\r\n    \"captions\": {\r\n        \"color\": \"FFFFFF\",\r\n        \"backgroundColor\": \"000000\",\r\n        \"backgroundOpacity\": 90\r\n    },\r\n\r\n    \/\/height: \"100%\",\r\n\twidth: \"100%\",\r\n\taspectratio: \"16:9\",\r\n    autostart: true,\r\n    \r\n    ga: { label: \"title\"},\r\n    \r\n   \r\n    playlist: [{\r\n\r\n        file: '{@ID,output_preroll}',\r\n        image: '',\r\n        title: \"\",   \r\n        mediaid: ''\r\n        },\r\n\r\n        {\r\n\r\n            file: \"{@video_news_file._src}\",\r\n            image: \"\",\r\n            title: \"\",\r\n            mediaid: '',\r\n            \r\n            tracks: [{ \r\n                file: \"{@video_news_file_captions._src}\", \r\n                label: \"ENGLISH\",\r\n                kind: \"captions\",\r\n                \"default\": true \r\n            }]\r\n           \r\n\r\n        }]\r\n\r\n\r\n});\r\n\r\n\r\n<\/script>\r\n\r\n\r\n\r\n","type":"template","slug":"video","options":{"_edit_lock":"1581461058:1","_edit_last":"1","_elementor_controls_usage":"a:0:{}","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:8:\"newspost\";}"}}}}
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment]
Hello @digitaliway 

Pods itself doesn't do anything with GravityForms tables in any way.
I don't see the Pods GravityForms addon in your plugins list.
Are you sure this issue is caused by the Pods plugin?

Despite your claim that disabling other plugins doesn't remove the error I do think that this might be cache or something.
Did you test with the troubleshooting plugin?  https://wordpress.org/plugins/health-check/

Cheers, Jory

**Comment by digitaliway** [comment]
this is a very strange issue that I cannot pin down.  I did test with the troubleshooting plugin and made a video with the error that remains: https://share.getcloudapp.com/bLumY4NJ   I am using the latest version of firefox and all history/temp is fully cleared.

**Comment by JoryHogeveen** [comment]
Hello @digitaliway 

I see your theme is still active in this mode. See notice on the top: "Install a default theme".

Cheers, Jory

**Comment by digitaliway** [comment]
sorry I missed that, but same result / error using 2019 theme 
made another video:  https://share.getcloudapp.com/NQuZOLky

**Comment by JoryHogeveen** [comment]
Hmm weird.. do you have access to your server logs? I'd like to have a stack trace to see what is triggering this notice.

**Comment by digitaliway** [comment]
yes, I have access to all server logs.  I deleted the php log and enabled a back trace then saved the pd to generate the error.  I am attached the backtrace log showing the error.
[fox8tv_com.php.error.log](https://github.com/pods-framework/pods/files/4199516/fox8tv_com.php.error.log)

**Comment by JoryHogeveen** [comment]
Hello @digitaliway 

Found the cause of this issue.
Pods stores all available tables in a transient (cache) in case you want to make a relationship to a table.
The error is caused because you still have the old RG tables from a previous GF version. Pods also stores these tables since it stores _all_ tables. It looks like even though the tables are not used the fact that the name of one of these tables exist in a query it will trigger a notice.

Since this table relationship feature is generic (not plugin depending) we can not change this.
I'd advice to remove these tables as they shouldn't be used anymore. Might be best to consult Gravity Forms before doing this.

Cheers, Jory

**Comment by digitaliway** [comment]
I removed the RG tabled and that worked perfectly – thank you for digging into this.

 

Mike
