### ISSUE TITLE
Date picker often misinterprets saved date field on load, very annoying.

### ISSUE THREAD

**Issue by hedgehog90** [pods-framework/pods#5596]
**Describe the bug**
The datepicker for datetime fields does some weird stuff.

**To Reproduce**
I set the date and time and save my post to:
'14 January 2020 00:00'

On reloading, the text box becomes:
'14th January 2020 00:00'

The 'th' after the date is the issue.
If I click on the textbox to bring up the datepicker, it now loads up the calendar for the current month and year (February 2020), instead of January 2020
If I then click outside of the widget, something even stranger happens - then it becomes:
'9 September 2025 00:00'

And it's all because it adds a 'th', 'st' or 'nd' after the date.
Please fix this.

## Pods Version
2.7.16.2

## WordPress Environment
`
### wp-core ###

version: 5.3.2
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 1
default_comment_status: open
multisite: false
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Projects\Sites\cabtv\public_html
wordpress_size: 40.09 MB (42039005 bytes)
uploads_path: C:\Projects\Sites\cabtv\public_html/wp-content/uploads
uploads_size: 6.14 MB (6437113 bytes)
themes_path: C:\Projects\Sites\cabtv\public_html/wp-content/themes
themes_size: 2.75 MB (2885924 bytes)
plugins_path: C:\Projects\Sites\cabtv\public_html/wp-content/plugins
plugins_size: 44.62 MB (46788858 bytes)
database_size: 3.86 MB (4046848 bytes)
total_size: 97.46 MB (102197748 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: CaB TV Wordpress Theme (cabtv)
version: 1.0
author: Tom Wilson
author_website: https://gpstudios.com
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-background, custom-logo, wp-block-styles, responsive-embeds, customize-selective-refresh-widgets, editor-style, footer-widgets, infinite-scroll, widgets
theme_path: C:\Projects\Sites\cabtv\public_html/wp-content/themes/cabtv

### wp-plugins-active (12) ###

Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.6, author: Takayuki Miyoshi
Flamingo: version: 2.1.1, author: Takayuki Miyoshi
Font Awesome: version: 4.0.0-rc13, author: Font Awesome
Newsletter: version: 6.4.6, author: Stefano Lissa & The Newsletter Team
OneSignal Push Notifications: version: 2.1.1, author: OneSignal
Pods - Custom Content Types and Fields: version: 2.7.16.2, author: Pods Framework Team
Sticky Menu (or Anything!) on Scroll: version: 2.2, author: WebFactory Ltd
Ultimate Member: version: 2.1.3, author: Ultimate Member
WP Crontrol: version: 1.7.1, author: John Blackbourn & crontributors
WP Mail SMTP: version: 1.8.1, author: WPForms
WP Super Cache: version: 1.7.1, author: Automattic

### wp-plugins-inactive (4) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Custom Simple Rss: version: 2.0.9, author: Danny(Danikoo) Haggag
Hide Page And Post Title: version: 1.5, author: Arjun Thakur
WP RSS Aggregator: version: 4.17.3, author: RebelCode

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.2
php_version: 7.4.2 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 60
upload_max_size: 40M
php_post_max_size: 40M
curl_version: 7.67.0 OpenSSL/1.1.1c
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.4.11-MariaDB
client_version: mysqlnd 7.4.2

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Projects\Sites\cabtv\public_html/wp-content
WP_PLUGIN_DIR: C:\Projects\Sites\cabtv\public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.2
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
pods-session-save-path: \Projects\Sites\xampp\tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 50.497M
pods-memory-current-usage-real: 8.000M
pods-network-wide: No
pods-install-location: C:\Projects\Sites\cabtv\public_html\wp-content\plugins\pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.16.2","build":1581639727},"pods":{"253":{"id":253,"name":"go_live","label":"Go Live!","description":"","type":"settings","storage":"none","object":"","alias":"","fields":{"stream_title":{"id":354,"name":"stream_title","label":"Stream Title","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"unique":"0","text_repeatable":"0","text_max_length":"255","text_placeholder":""},"stream_url":{"id":255,"name":"stream_url","label":"Stream URL","description":"","help":"","class":"","type":"website","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","website_format":"none","website_allow_port":"1","website_clickable":"0","website_new_window":"0","website_max_length":"-1","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"unique":"0","website_repeatable":"0","website_placeholder":""},"show":{"id":254,"name":"show","label":"Show","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"show","sister_id":"","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","private","request-pending","request-confirmed","request-completed"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"1","read_only":"0","roles_allowed":["administrator"],"unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"active":{"id":256,"name":"active","label":"Active","description":"","help":"","class":"","type":"boolean","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"boolean_format_type":"dropdown","boolean_yes_label":"Yes","boolean_no_label":"No","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"unique":"0"}},"show_in_menu":1,"menu_name":"Go Live!","menu_location":"top","ui_style":"settings","menu_position":"0","menu_icon":"dashicons-video-alt3"},"246":{"id":246,"name":"post","label":"Post","description":"","type":"post_type","storage":"meta","object":"post","alias":"","fields":{"is_event":{"id":247,"name":"is_event","label":"Is Event","description":"Is this post advertising an upcoming event?","help":"","class":"","type":"boolean","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"boolean_format_type":"dropdown","boolean_yes_label":"Yes","boolean_no_label":"No","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"},"event_date":{"id":248,"name":"event_date","label":"Event Date","description":"Event Date","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","datetime_type":"wp","datetime_format":"dmy","datetime_time_type":"24","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","datetime_repeatable":"0","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":"","datetime_year_range_custom":""},"event_cancelled":{"id":249,"name":"event_cancelled","label":"Event Cancelled","description":"Has the event been cancelled?","help":"","class":"","type":"boolean","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"},"related_shows":{"id":355,"name":"related_shows","label":"Related Shows","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"show","sister_id":"","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_allow_add_new":"0","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"},"235":{"id":235,"name":"show","label":"Shows","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"biography":{"id":243,"name":"biography","label":"Biography","description":"Biography","help":"","class":"","type":"wysiwyg","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"description":{"id":242,"name":"description","label":"Description","description":"Description","help":"","class":"","type":"paragraph","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","paragraph_allow_html":"0","paragraph_oembed":"0","paragraph_wptexturize":"0","paragraph_convert_chars":"0","paragraph_wpautop":"0","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","paragraph_max_length":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","paragraph_repeatable":"0","paragraph_placeholder":""},"url":{"id":236,"name":"url","label":"URL","description":"Stream URL","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"1","website_format":"none","website_allow_port":"1","website_clickable":"0","website_new_window":"0","website_max_length":"-1","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"banner_image":{"id":238,"name":"banner_image","label":"Banner Image","description":"Banner Image","help":"","class":"","type":"file","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"active":{"id":240,"name":"active","label":"Active","description":"Is the show still running?","help":"","class":"","type":"boolean","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"boolean_format_type":"dropdown","boolean_yes_label":"Yes","boolean_no_label":"No","default_value":"1","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"}},"show_in_menu":"1","label_singular":"Show","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","label_all_items":"All Shows","label_search_items":"Search Shows","publicly_queryable":"1","exclude_from_search":"1","capability_type":"custom","capability_type_custom":"show","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"1","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"1","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","menu_icon":"dashicons-format-video","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_flamingo_contact_tag":"0","built_in_taxonomies_flamingo_inbound_channel":"0"},"245":{"id":245,"name":"user","label":"User","description":"","type":"user","storage":"meta","object":"user","alias":"","fields":[],"show_in_menu":1}}}
```

**Possible Workaround**
Remove the date suffix in loading values from the database into the datepicker textbox.

**Comment by JoryHogeveen** [comment]
From your field settings it looks like you are using the WordPress default date format.
Could it be that it is set to add the `th` for dates?
If so, could you test another date format?

**Comment by JoryHogeveen** [comment]
the `S` value from php date (`th` etc) isn't supported by the jQuery datepicker:
https://stackoverflow.com/questions/8199204/adding-st-nd-rd-th-to-jquery-datepicker

**Comment by hedgehog90** [comment]
Yes, if I change the date format to use a date format without the S value it works correctly.
Pods should probably handle this correctly, regardless of what my wordpress date/time settings are set to, and reformat the date for the text input.

**Comment by JoryHogeveen** [comment]
Hello @hedgehog90 
WP default is e recent option. It's not easy / fail-proof to auto-change such things so my advice is not to use the WP default date format is you explicitly need to use the S.

> Pods should probably handle this correctly 
This is actually a bug in jQuery datepicker, not Pods. Pods handles dates fine.

In any case, I will look into this but it will take a while.
Marking todo for v2.8 for now.

**Comment by JoryHogeveen** [comment]
In addition to the above. Switching to HTML5 input will also fix your issue.

**Comment by sc0ttkclark** [comment]
Pods does the best it can here given the date format setting. If the stored value is not in a format it can easily recognize with `strtotime()`-like code -- then that's probably the best we can get things. Pods 2.8 has improved things quite a bit here though :)
