### ISSUE TITLE
Issue with currency formatting

### ISSUE THREAD

**Issue by athos45** [pods-framework/pods#5597]
## Issue Overview

Hello everyone,  I created a pods with Field Type Currency, then in Additional Field Options I set the format as 1'234.00 . Now when I enter 1200 and save it displays 1'200.00 as expected, but won't let me save my entry once more unless I replace 1'200.00 by 1200...

## Expected Behavior

I should be able to save my pod entry without having to retype the currency amount for each of my currency fields.
 

## Current Behavior

 

![bug-report](https://user-images.githubusercontent.com/61057392/74544361-49f09f80-4f47-11ea-9869-31a4498966f3.png)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
Information de débuggage
WordPress Version: 5.3.2

PHP Version: 7.2.27

MySQL Version: 5.7.28

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 640M

Current Memory Usage: 123,669M

Current Memory Usage (real): 24,500M

Pods Network-Wide Activated: No

Pods Install Location: /wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:

Admin Menu Editor: 1.9.3
Beaver Builder Plugin (Agency Version): 2.3.1.3
Beaver Themer: 1.2.5
Classic Editor: 1.5
CSS Hero: 4.07
Disable Comments: 1.10.2
FacetWP: 3.4.7
FacetWP - Beaver Builder: 1.2.5
FacetWP - Pods integration: 1.2.2
Gravity Forms: 2.4.17
JSON Basic Authentication: 0.1
MainWP Child: 4.0.6.2
Multiple Columns for Gravity Forms: 3.0.3
Peter's Login Redirect: 2.9.4
Pods - Custom Content Types and Fields: 2.7.16.2
Pods Beaver Themer Add-On: 1.3.2
Pods Gravity Forms Add-On: 1.4.1
PowerPack for Beaver Builder: 2.7.11
Restrict Content: 2.2.4
Smart Slider 3 Pro: 3.3.26
Ultimate Addons for Beaver Builder: 1.25.1
Ultimate Dashboard PRO: 2.8.2
UpdraftPlus - Backup/Restore: 2.16.21.24
WP All Export Pro: 1.5.10
XYZ WP Insert Code Snippet: 1.2.1
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Workaround or Alternate Solution Until Bug is Addressed

The workaround is to go back to default formatting and to reformat the field in PHP.

**Comment by JoryHogeveen** [comment]
Fixed in #5560
