### ISSUE TITLE
Default sessions to off

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#5600]
We should default the sessions to off for Pods. See #5626

**Comment by JoryHogeveen** [comment]
Open for discussion (see PR #5626 )

Not sure whether a setting is required for this.
The `on` feature seems a bit redundant since `auto` would cover all situations where we need sessions.
Any thoughts are welcome.

**Comment by sc0ttkclark** [comment]
Fixed via #5626
