### ISSUE TITLE
 {@post_thumbnail.ID} Traversal not working

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#5609]
{@post_thumbnail.ID} Traversal not working or any other traversal besides the image sizes/url stuff

**Comment by quasel** [comment]
Related to #3779 - I knew back in my head that wasn't the first encounter…

**Comment by JoryHogeveen** [comment]
@quasel 
That is actually a different issue and has to do with relations, not the current post thumbnail.
Also, it seems that at least the thumbnail part of that issue is also resolved with my PR.
My guess is that that issue in general is just fixed then. Could you verify?
