### ISSUE TITLE
PodsI18n array offset problem

### ISSUE THREAD

**Issue by oadekoya12** [pods-framework/pods#5615]
## Issue Overview
"Notice: Trying to access array offset on value of type bool in \plugins\pods\classes\PodsI18n.php on line 469" issue

## Related Issues and/or PRs
tag/2.7.16.2

**Comment by JoryHogeveen** [comment]
Fixed in #5558

**Comment by oadekoya12** [comment]
I have edited the file and here is the path file
[pods.diff](https://github.com/oadekoya12/pods_PodsI18n_fileupdate-/blob/master/pods.diff)

**Comment by oadekoya12** [comment]
Le

> I have edited the file and here is the path file
> [pods.diff](https://github.com/oadekoya12/pods_PodsI18n_fileupdate-/blob/master/pods.diff)

Please let me know it pass your test.

**Comment by oadekoya12** [comment]
> Fixed in #5558
I did not see the solution in the fix and ended up creating another patch file.

**Comment by JoryHogeveen** [comment]
Sorry your patch is not compatible with the WordPress coding standards.

Besides that, this issue is already fixed in #5558 

> I did not see the solution in the fix and ended up creating another patch file.

Please check the file changes and you'll see the fix. While it's not the exact same notation, the code does exactly the same as your patch.

**Comment by oadekoya12** [comment]
> Sorry your patch is not compatible with the WordPress coding standards.
> 
> Besides that, this issue is already fixed in #5558
> 
> > I did not see the solution in the fix and ended up creating another patch file.
> 
> Please check the file changes and you'll see the fix. While it's not the exact same notation, the code does exactly the same as your patch.

Do you want me to use version 2.x instead of tag/2.7.16.2
I got this problem when am using WP-CLI to check the status of WordPress 

And I also got another notice: 

> Notice: Undefined index: HTTP_HOST in wp-content\plugins\pods\includes\general.php on line 629

**Comment by oadekoya12** [comment]
And Love to learn from my mistakes,
What is the proper patch way that is compatible with WordPress code standards?

**Comment by JoryHogeveen** [comment]
> Do you want me to use version 2.x instead of tag/2.7.16.2

Yep, 2.x has the latest bugfixes.

> Notice: Undefined index: HTTP_HOST in wp-content\plugins\pods\includes\general.php on line 629

That is because you are running the code without $_SERVER[] parameters.

> What is the proper patch way that is compatible with WordPress code standards?

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/
