### ISSUE TITLE
Wordpress Database Error

### ISSUE THREAD

**Issue by ljgarnes** [pods-framework/pods#5630]
I enter a shortcode that was not accurate.  I saved it and now I'm getting this error --- and it won't let me remove the shortcode or save in Elementor... I'm getting a server error.
 I cleared cache and tried another browser too.

WordPress database error: [Unknown column 't.name' in 'order clause']
SELECT DISTINCT `t`.* FROM `wp_jrhc_posts` AS `t` LEFT JOIN `wp_jrhc_term_relationships` AS `rel_category` ON `rel_category`.`object_id` = `t`.`ID` LEFT JOIN `wp_jrhc_term_taxonomy` AS `rel_tt_category` ON `rel_tt_category`.`taxonomy` = 'category' AND `rel_tt_category`.`term_taxonomy_id` = `rel_category`.`term_taxonomy_id` LEFT JOIN `wp_jrhc_terms` AS `category` ON `category`.`term_id` = `rel_tt_category`.`term_id` WHERE ( ( `category`.`name`='Professional Services' ) AND ( `t`.`post_type` = "business_directory" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) ORDER BY t.name ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`

Database Error; SQL: SELECT DISTINCT `t`.* FROM `wp_jrhc_posts` AS `t` LEFT JOIN `wp_jrhc_term_relationships` AS `rel_category` ON `rel_category`.`object_id` = `t`.`ID` LEFT JOIN `wp_jrhc_term_taxonomy` AS `rel_tt_category` ON `rel_tt_category`.`taxonomy` = ‘category’ AND `rel_tt_category`.`term_taxonomy_id` = `rel_category`.`term_taxonomy_id` LEFT JOIN `wp_jrhc_terms` AS `category` ON `category`.`term_id` = `rel_tt_category`.`term_id` WHERE ( ( `category`.`name`=’Professional Services’ ) AND ( `t`.`post_type` = “business_directory” ) AND ( `t`.`post_status` IN ( “publish” ) ) ) ORDER BY t.name ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`; Response: Unknown column ‘t.name’ in ‘order clause’

## Pods Version
Version 2.7.16.2
Add Ons Version 1.4.2

## WordPress Environment
`
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/'
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home3/haywood2/public_html
wordpress_size: 9.32 GB (10003544653 bytes)
uploads_path: /home3/haywood2/public_html/wp-content/uploads
uploads_size: 2.53 GB (2717539524 bytes)
themes_path: /home3/haywood2/public_html/wp-content/themes
themes_size: 20.08 MB (21050274 bytes)
plugins_path: /home3/haywood2/public_html/wp-content/plugins
plugins_size: 160.74 MB (168545139 bytes)
database_size: 18.23 MB (19117208 bytes)
total_size: 12.04 GB (12929796798 bytes)

### wp-dropins (1) ###

install.php: true

### wp-active-theme ###

name: GeneratePress (generatepress)
version: 2.4.1 (latest version: 2.4.2)
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: none
theme_features: automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, custom-logo, menus, editor-style, widgets
theme_path: /home3/haywood2/public_html/wp-content/themes/generatepress

### wp-themes-inactive (2) ###

Customizr Child: version: 1.1455054090, author: Ed Kelley
Customizr Pro: version: 1.2.27, author: Press Customizr

### wp-mu-plugins (1) ###

SSO: version: 0.3, author: Garth Mortensen, Mike Hansen

### wp-plugins-active (15) ###

Akismet Anti-Spam: version: 4.1.4, author: Automattic
All-in-One WP Migration: version: 7.18, author: ServMask
All-in-One WP Migration Dropbox Extension: version: 3.55, author: ServMask
Constant Contact Forms for WordPress: version: 1.8.1, author: Constant Contact
Elementor: version: 2.9.6, author: Elementor.com
Elementor Pro: version: 2.9.1, author: Elementor.com
Essential Addons for Elementor: version: 3.8.5, author: WPDeveloper
Gravity Forms: version: 2.4.17, author: rocketgenius
Navigation Tree Elementor: version: 1.0.1, author: WP Distillery
Pods - Custom Content Types and Fields: version: 2.7.16.2, author: Pods Framework Team
Pods Gravity Forms Add-On: version: 1.4.2, author: Pods Framework Team
Quick Page/Post Redirect Plugin: version: 5.1.9, author: anadnet
Really Simple SSL: version: 3.3, author: Rogier Lankhorst, Mark Wolters
TablePress: version: 1.10, author: Tobias Bäthge
Yoast SEO: version: 13.3, author: Team Yoast

### wp-plugins-inactive (6) ###

Ninja Forms: version: 3.4.24.1, author: Saturday Drive
Photo Gallery: version: 1.5.49, author: Photo Gallery Team
Smart Slider 2: version: 2.3.13, author: Nextend
Under Construction: version: 3.65, author: WebFactory Ltd
UpdraftPlus - Backup/Restore: version: 1.16.22, author: UpdraftPlus.Com, DavidAnderson
Wordfence Security: version: 7.4.6, author: Wordfence

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1650
imagemagick_version: ImageMagick 6.7.2-7 2017-03-22 Q16 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 13 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 48 MB
	imagick::RESOURCETYPE_MEMORY: 48 MB
	imagick::RESOURCETYPE_THREAD: not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.71

### wp-server ###

server_architecture: Linux 3.10.0-693.11.6.1.ELK.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.15 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 64M
php_post_max_size: 64M
curl_version: 7.68.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.41-84.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://www.haywoodchamber.com
WP_SITEURL: https://www.haywoodchamber.com
WP_CONTENT_DIR: /home3/haywood2/public_html/wp-content
WP_PLUGIN_DIR: /home3/haywood2/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 59.092M
pods-memory-current-usage-real: 61.000M
pods-network-wide: No
pods-install-location: /home3/haywood2/public_html/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.

</details>

**Comment by jimtrue** [comment]
@ljgarnes You have a theme/plugin conflict: You need to use this process to turn off plugins until you can edit that page and remove the shortcode: https://docs.pods.io/faqs/plugin-theme-conflicts/

Next time, I would suggest going into a regular page editor (no Elementor) to create & test your shortcodes and so you can edit them. Don't use the Block Editor for testing shortcodes. Use the Classic Editor.  If Elementor breaks on the page because of typing in an invalid shortcode, there's not much we can do to correct that.

**Comment by ljgarnes** [comment]
Actually, I created a new page… added back the Elementor Tabs --- then the shortcodes and the new page works… so something must have corrupted the template on that particular page.

**Comment by Imboga** [comment]
Same issue here, clean install using Avada Theme with no Elementor nor Fusion Builder.
Maybe a Database version issue? I'm using MYSQL 8 under Digital Ocean Managed Databases.

As soon I create a custom post and attach it to a custom taxonomy, next updates throw **Unknown column** error, no matter if I'm using meta or tables configuration.

Unfortunately, I'm moving to another CPT plugin since I didn't find a solution so far. So sad since this plugin looks awesome.

**Comment by JoryHogeveen** [comment]
@Imboga 

I think this is an installation specific error in your case. There is also a difference in using meta and table based storage for Pods.
In any case, I think it's unrelated the this topic so if you need help, please open a new topic.

Cheers, Jory
