### ISSUE TITLE
List View for new List View relationships added in 2.x are not working properly

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5632]
**Describe the bug**
When you add a new relationship with a List View format under 2.x (or anything based on 2.x), you'll see that the List View is not including the post-title. 

If you flip back to Master, the List View is displaying properly. This seems to be something being saved in the structure (meta definition for the field?), because it corrects itself when switching back to master. 

I can verify because I created one structure under 2.x and when you flip back and forth, Master views it properly, but 2.x doesn't. If I load a structure that was created under Master, it's fine, but under 2.x it's broken. I'm going to upload both a structure from 2.x and one from master and you can see the issue.

**To Reproduce**
1. Switch to 2.x Branch and create a new Pod and add a new List View Relationship field to that Pod.
2. Try adding records in the List View interface, you'll see they look like my screen examples below.
3. Switch to Master, they'll look normal again (see screen examples)
4. Switch back to 2.x, they'll be broken

**Expected behavior**
They should look like regular List View items. There are no javascript errors btw.

**Screenshots**
**Created List View Items on 2.x (these were created ON 2.x branch)**
![2 x-created-list-view-with-bad-interface](https://user-images.githubusercontent.com/3052875/77676277-7ba44f80-6f64-11ea-970c-62bba5ed2d8d.png)

**Created List View Items on MASTER (these were created on 2.x branch)**
![2 x-created-list-view-on-master-branch](https://user-images.githubusercontent.com/3052875/77676291-8232c700-6f64-11ea-93c7-c59219d2165d.png)

**List View created outside 2.x branch on 2.x - no issues**
![List-view-created-outside-2 x-branch-on-2 x](https://user-images.githubusercontent.com/3052875/77676314-89f26b80-6f64-11ea-9618-e61ebd6d96b4.png)

## Pods Version
Please provide the version of Pods you are running: 2.7.12

## WordPress Environment

<details>
`
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /app/public
wordpress_size: 37.85 MB (39686439 bytes)
uploads_path: /app/public/wp-content/uploads
uploads_size: 2.09 MB (2191656 bytes)
themes_path: /app/public/wp-content/themes
themes_size: 4.63 MB (4859674 bytes)
plugins_path: /app/public/wp-content/plugins
plugins_size: 64.15 MB (67270836 bytes)
database_size: 3.02 MB (3162112 bytes)
total_size: 111.74 MB (117170717 bytes)

### wp-active-theme ###

name: Twenty Seventeen (twentyseventeen)
version: 2.2
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, editor-styles, wp-block-styles, responsive-embeds, starter-content, custom-header, widgets
theme_path: /app/public/wp-content/themes/twentyseventeen

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team
Twenty Twenty: version: 1.1, author: the WordPress team

### wp-plugins-active (4) ###

Classic Editor: version: 1.5, author: WordPress Contributors
Gutenberg: version: 7.8.0, author: Gutenberg Team
Health Check & Troubleshooting: version: 1.4.2, author: The WordPress.org community
Pods - Custom Content Types and Fields: version: 2.7.17-a-1, author: Pods Framework Team

### wp-plugins-inactive (1) ###

Pods Gravity Forms Add-On: version: 1.4.2, author: Pods Framework Team

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.20

### wp-server ###

server_architecture: Linux 4.9.93-boot2docker x86_64
httpd_software: nginx/1.14.0
php_version: 7.2.9 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_size: 300M
php_post_max_size: 1000M
curl_version: 7.52.1 OpenSSL/1.0.2l
suhosin: false
imagick_availability: true
server-headers: 
	server: nginx/1.13.12
	date: Thu, 26 Mar 2020 17:22:06 GMT
	content-type: text/html; charset=UTF-8
	vary: Array
	x-powered-by: PHP/7.2.9
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	link: <http://testpods.local/wp-json/>; rel="https://api.w.org/"
	x-fw-hash: local
	content-encoding: gzip

### wp-database ###

extension: mysqli
server_version: 5.7.23
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /app/public/wp-content
WP_PLUGIN_DIR: /app/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.14.0
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 9.483M
pods-memory-current-usage-real: 2.000M
pods-network-wide: No
pods-install-location: /app/public/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.17-a-1","build":1585171982},"pods":{"334":{"id":334,"name":"people","label":"People","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"consort":{"id":335,"name":"consort","label":"Consort","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"people","sister_id":"335","required":"0","pick_format_type":"single","pick_format_single":"list","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_display":"{@post_title}","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_where":"","pick_orderby":"","pick_groupby":""},"offspring":{"id":336,"name":"offspring","label":"Offspring","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"post_type","pick_val":"people","sister_id":"337","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"sire":{"id":337,"name":"sire","label":"Sire","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"people","sister_id":"336","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"sibling":{"id":342,"name":"sibling","label":"Sibling","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"people","sister_id":"342","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"list","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"People","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"people","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_test_type":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_single":"People Detail","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"1","read_all":"0","write_all":"0"}},"templates":{"People Detail":{"id":355,"name":"People Detail","code":"[if offspring]\r\n<h3>Children<\/h3>\r\n<ul class=\"offspring\">\r\n\t[each offspring]\r\n\t<li><a href=\"{@permalink,esc_url}\">{@post_title}<\/a><\/li>\r\n\t     [if offspring]\r\n\t\t <h4>Grand Children<\/h4>\r\n\t     <ul class=\"grand-offspring\">\r\n\t     [each offspring]\r\n\t\t <li> - {@post_title}<\/li>\r\n\t     [\/each]\r\n\t     <\/ul>\r\n\t     [\/if]\r\n\t[\/each]\r\n<\/ul>\r\n[\/if]","type":"template","slug":"people-detail","options":{"_edit_lock":"1585171512:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:6:\"people\";}"}}}}
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment]
@jimtrue 
Weird, I can replicate your package but my other Pods still work fine...

**Comment by JoryHogeveen** [comment]
It's a CSS issue. If I add a WYSIWYG field it gets "more" normal.
My first guess is that this is related to the Friends of Pods PR: #5571
