### ISSUE TITLE
double comma on simple custom list with new custom separator (with no "and")

### ISSUE THREAD

**Issue by robpie-de** [pods-framework/pods#5637]
i just updated to use the new display format für simple custom list (checkbox) but one thing... it returns a comma more. with "and" it returns for e.g.: "Montag,Dienstag,Mittwoch,Donnerstag,Freitag, and Samstag" but now with custom separator (with no "and") it returns: "Montag,Dienstag,Mittwoch,Donnerstag,Freitag,,Samstag" - there are two commas before Samstag. 

it looks like the "and" is replaced by "," ... so because of this there are two ",," ... 

![Screenshot_2020-03-27 Positano - Zwerge neu](https://user-images.githubusercontent.com/62729764/77709838-99a59a80-6fcc-11ea-9e77-123f3f7dc9e4.png)
![Screenshot_2020-03-27 Edit Pod Template ‹ Zwerge neu — WordPress](https://user-images.githubusercontent.com/62729764/77709844-9f02e500-6fcc-11ea-9f6f-baa4f92d44ac.png)
![Screenshot_2020-03-27 Edit Produktion ‹ Zwerge neu — WordPress](https://user-images.githubusercontent.com/62729764/77709850-a1fdd580-6fcc-11ea-8f2f-da17ed1dc463.png)
![Screenshot_2020-03-27 Edit Pods ‹ Zwerge neu — WordPress](https://user-images.githubusercontent.com/62729764/77709856-a629f300-6fcc-11ea-8e64-edd8f193c441.png)
![Screenshot_2020-03-27 Edit Pods ‹ Zwerge neu — WordPress(1)](https://user-images.githubusercontent.com/62729764/77709857-a88c4d00-6fcc-11ea-8bcd-68f8cfd9c97b.png)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
Did some digging and found that the commit below added this bug:
https://github.com/pods-framework/pods/pull/5613/commits/5c665707381084e52be1444cbc10d12b90440964

Why always add the extra serial comma for the default display? I went back to 2.7.16 and didn't found that format to be done at all.

Current: (notice the extra comma after "Item 2")
`Item 1, Item 2, and Item 3`

Previous versions:
`Item 1, Item 2 and Item 3`

**Comment by JoryHogeveen** [comment]
In retrospect I was looking at the wrong Pods state (not the tag).
Previously there was indeed the extra comma after the last item.
While I do not understand why this is, as far as I know this is incorrect grammar (at least in the Netherlands).

I'll create a new PR to make this optionally.

**Comment by JoryHogeveen** [comment]
@robpie-de 
Could you please test the changes in #5638 ?

**Comment by robpie-de** [comment]
hey @JoryHogeveen i have tested it, works.... but only the 'non_serial' option will remove the doubled comma.... option 'custom' returns the same like before 'Montag,Dienstag,Mittwoch,Donnerstag,,Freitag'

**Comment by JoryHogeveen** [comment]
Hmm it works in my setup. Are you sure you've applied all code changes?

**Comment by robpie-de** [comment]
@JoryHogeveen i'm sorry - i forgot about the last lines... it works well now - thx a lot :)

**Comment by robpie-de** [comment]
![Screenshot_2020-03-27 Positano - Zwerge neu(1)](https://user-images.githubusercontent.com/62729764/77766869-82a09000-7040-11ea-8538-4635969387b3.png)
![Screenshot_2020-03-27 Edit Pods ‹ Zwerge neu — WordPress(2)](https://user-images.githubusercontent.com/62729764/77766870-83392680-7040-11ea-947c-7c671bc73b3e.png)

**Comment by JoryHogeveen** [comment]
@robpie-de Thanks for the confirmation. Hotfix release is out now!
