### ISSUE TITLE
[if][else][/if] Problem since update to Version 2.7.17 

### ISSUE THREAD

**Issue by vtad** [pods-framework/pods#5643]
**Describe the bug**

I a have field called **free** from Type Yes/No and input Type Radio Buttons 

In the Template I have
`some text [if free][else]&#x1F510;[/if]`

This works correctly until Version 2.7.16.2, displaying a Lock ( see https://www.vtad.de/webithekd/ )

with Version 2.7.17  no lock ist displayed, even using a simple text like "no"
The only change was the update to Version 2.7.17

**Screenshots**
See site with the update at
https://wissentest.vtad.de/webithekd/

## Pods Version
Version 2.7.17 

## WordPress Environment

<details>

Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
`
### wp-core ###

version: 5.3.2
site_language: de_DE
user_language: en_US
timezone: Europe/Berlin
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 273
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/www/wpvtadtest
wordpress_size: 216.25 MB (226756114 bytes)
uploads_path: /home/www/wpvtadtest/wp-content/uploads
uploads_size: 19.41 GB (20842018782 bytes)
themes_path: /home/www/wpvtadtest/wp-content/themes
themes_size: 2.54 MB (2660048 bytes)
plugins_path: /home/www/wpvtadtest/wp-content/plugins
plugins_size: 61.65 MB (64643156 bytes)
database_size: 22.31 MB (23396352 bytes)
total_size: 19.71 GB (21159474452 bytes)

### wp-active-theme ###

name: wpvtad17 (wpvtad17)
version: 1.0
author: JPK
author_website: http://vtad.de
parent_theme: Twenty Seventeen (twentyseventeen)
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, editor-styles, wp-block-styles, responsive-embeds, starter-content, custom-header, align-wide, widgets
theme_path: /home/www/wpvtadtest/wp-content/themes/wpvtad17

### wp-parent-theme ###

name: Twenty Seventeen (twentyseventeen)
version: 2.2
author: the WordPress team
author_website: https://wordpress.org/
theme_path: /home/www/wpvtadtest/wp-content/themes/twentyseventeen

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.1, author: the WordPress team

### wp-plugins-active (24) ###

Advanced CF7 DB: version: 1.7.2, author: Vsourz Digital
All In One WP Security: version: 4.4.3, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy
Auto Prune Posts: version: 1.6.6, author: Ramon Fincken
Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.7, author: Takayuki Miyoshi
Events Manager: version: 5.9.7.3, author: Marcus Sykes
File Manager Advanced: version: 3.3, author: modalweb
File Manager Advanced Shortcode: version: 2.0, author: modalweb
HD Quiz: version: 1.7.0, author: Harmonic Design
MathJax-LaTeX: version: 1.3.11, author: Phillip Lord, Simon Cockell, Paul Schreiber
Members: version: 2.2.0, author: Justin Tadlock
Pods - Custom Content Types and Fields: version: 2.7.17, author: Pods Framework Team
Post Views Counter: version: 1.3.1, author: Digital Factory
Shortcodes Ultimate: version: 5.8.0, author: Vladimir Anokhin
Statify: version: 1.6.3, author: pluginkollektiv
TinyMCE Advanced: version: 5.3.0, author: Andrew Ozz
To Top: version: 2.1, author: Catch Plugins
User Menus: version: 1.2.3, author: Code Atlantic
User Switching: version: 1.5.4, author: John Blackbourn & contributors
VTAD Adim Menu: version: 1.0, author: Kienitz
VTAD Login: version: 1.2.0, author: Jörg Kienitz
WPeMatico: version: 2.5.2, author: etruel <esteban@netmdp.com>
WP Help: version: 1.7.0, author: Mark Jaquith
WP Rollback: version: 1.7.0, author: Impress.org

### wp-plugins-inactive (5) ###

Better Search Replace: version: 1.3.3, author: Delicious Brains
Simple History: version: 2.33.2, author: Pär Thernström
Temporary Login Without Password: version: 1.6.0, author: StoreApps
Tuxedo Big File Uploads: version: 1.2, author: Trevor Anderson
VTAD Login: version: 1.2.0, author: Jörg Kienitz

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1800
imagemagick_version: ImageMagick 7.0.8-50 Q16 x86_64 2019-07-01 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 12 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 12 GB
	imagick::RESOURCETYPE_MEMORY: 6 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.0-6-amd64 x86_64
httpd_software: Apache
php_version: 7.2.24 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 180
memory_limit: 1024M
max_input_time: -1
upload_max_size: 100M
php_post_max_size: 100M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.28
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: https://wissentest.vtad.de
WP_SITEURL: https://wissentest.vtad.de
WP_CONTENT_DIR: /home/www/wpvtadtest/wp-content
WP_PLUGIN_DIR: /home/www/wpvtadtest/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 51.927M
pods-memory-current-usage-real: 6.250M
pods-network-wide: No
pods-install-location: /home/www/wpvtadtest/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

**Comment by vtad** [comment]
Problem still persists with Version 2.7.17.1

**Comment by JoryHogeveen** [comment]
Hello @vtad 
Could you please test #5656 and let me know if it fixes your issue?

**Comment by vtad** [comment]
It works correctly now!
See https://wissentest.vtad.de/webithekd/

(since I don't know how to patch, I simply replaced the original file .../fields/boolean.php with the version of the pull request #5656

**Comment by JoryHogeveen** [comment]
Thanks for letting me know!
