### ISSUE TITLE
Template created in earlier version of Pods doesn't display in 2.7.17.1

### ISSUE THREAD

**Issue by FBEPcode** [pods-framework/pods#5648]
## Issue Overview
We use a template to display linked posts.

For instance: https://pastebin.com/L8TZmgxA

With the 2.7.17.1 update (and perhaps with 2.7.17--not sure) the links no longer display. I rolled back to 2.7.16.2 and it works again.

## Expected Behavior
The template should return linked posts like this: https://thedockforlearning.org/contributions/daily-lesson-checklist-for-home-study/ and like this: https://thedockforlearning.org/series/covid-19-coronavirus-response-plans/

## Current Behavior
When I updated to 2.7.17.1 the template did not display under the post content.

## Steps to Reproduce (for bugs)
As noted, updating to the latest version results in this behavior.

I re-saved the template and the post. In the past, that has allowed the template to re-register (not technical language). It did not help in this case.

Rolling back to Pods 2.7.16.2 fixed the issue. 

## WordPress Environment
<details>
Debug Information

WordPress Version: 5.3.2

PHP Version: 7.0.33-1~dotdeb+8.1

MySQL Version: 5.6.47

Server Software: Apache/2.4.10 (Debian)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: Yes
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: Yes
    APCu: Yes
    Memcache: No
    Memcached: Yes
    Redis: No

WPDB Prefix: wp8w_

WP Multisite Mode: No

WP Memory Limit: 756M

Current Memory Usage: 44.449M

Current Memory Usage (real): 34.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/125234.cloudwaysapps.com/pbsbcxvxwh/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Child

Currently Active Plugins:

    Advanced noCaptcha & invisible Captcha: 5.6
    Asset CleanUp: Page Speed Booster: 1.3.6.0
    bbPress: 2.5.14
    bbPress Genesis Extend: 1.2.0
    bbp style pack: 4.4.0
    Blubrry PowerPress: 8.2.7
    BP Messaging Control: 1.6.6
    Breeze: 1.1.4
    BuddyPress: 5.1.2
    Caldera Forms: 1.8.11
    Caldera Forms Anti Spam: 0.3
    Classic Editor: 1.5
    Cloudflare: 3.4.1
    Collapse-O-Matic: 1.7.11
    Content Aware Sidebars: 3.11.1
    Custom Hooks: 1.0
    Democracy Poll: 5.5.6.3
    Duplicate and Merge Posts: 1.0.5
    Embed Any Document: 2.4.1
    Enhanced Text Widget: 1.4.7
    EventON: 2.8.7
    FacetWP: 3.5.1
    FacetWP - Conditional Logic: 1.3.0
    Favorites: 2.3.1
    Forum Beginner Posts: 1.1.0
    GA Google Analytics: 20200325
    Google XML Sitemaps: 4.1.0
    Imagify: 1.9.9
    Livemesh SiteOrigin Widgets: 2.5.9
    MalCare WordPress Security, Firewall & Malware Scanner: 3.8
    Max Mega Menu: 2.7.4
    MP3-jPlayer: 2.7.3
    myStickymenu: 2.3.8
    Nextend Social Login: 3.0.22
    Nextend Social Login Pro Addon: 3.0.22
    Page Builder by SiteOrigin: 2.10.14
    PhastPress: 1.42
    PHP Code Widget: 2.3
    Pods - Custom Content Types and Fields: 2.7.16.2
    Recent Posts Widget Extended: 0.9.9.7
    Related Posts by Bibblio: 1.3.7
    Related Posts for WordPress Premium: 1.9.0
    Responsive Menu: 3.1.27
    Sassy Social Share: 3.3.8
    SearchWP: 3.1.11
    SearchWP bbPress Integration: 1.3.0
    SearchWP Boolean Query: 1.4.0
    SearchWP WP Job Manager Integration: 1.6.0
    SiteOrigin Premium: 1.12.1
    SiteOrigin Widgets Bundle: 1.16.0
    UpdraftPlus - Backup/Restore: 1.16.22
    Woody ad snippets (PHP snippets | Insert PHP): 2.3.1
    WP-PostRatings: 1.87
    WP Job Manager: 1.34.1
    WP Job Manager Field Editor: 1.9.0
    WP Mail SMTP: 1.9.0
    WP Rollback: 1.7.0
</details>

## Pods Package Export (helpful!)
https://gist.github.com/sc0ttkclark/e1f1be80b2f4f092e6fd4376546bf295

## Workaround or Alternate Solution Until Bug is Addressed
Roll back to previous version

**Comment by sc0ttkclark** [comment]
Do you have an example or screenshot of how it was looking after you upgraded?

**Comment by FBEPcode** [comment]
Sorry, I didn't take one and I'd just as soon not update again for the moment. But as I recall, this section was missing from the Contribution and Audio-Video CPTs:
[cid:dfd969e6-e87e-421e-a360-a314a41ab3bf]

And this from the Series CPT:
[cid:388ff4f7-eae5-4ec7-84c2-dbd6dd49eca3]

I'm sorry I'm not more help.
Lucas
________________________________

**Comment by JoryHogeveen** [comment]
Hello @FBEPcode 

I can't see the images you are referring to.
Could to point out the part of this template that isn't working anymore?

**Comment by FBEPcode** [comment]
I'm very sorry to waste your time. After testing on a staging site, I realized the issue is solved by clearing the Pods cache.
