### ISSUE TITLE
If statement not working in shortcodes/templates

### ISSUE THREAD

**Issue by john-lamb-folkproject** [pods-framework/pods#5649]
I created the following on a page for an existing pod with the YES/NO field named display:

[pods name="performer"]
[if display]{@display}[else]XXX[/if]
[/pods]

With seven published posts in performers, of which the second, fourth and seventh had display set to No and the others had it set to Yes.

Result in 2.7.16.2 was as expected: Yes XXX Yes XXX Yes Yes XXX
Result in 2.7.17 and 2.7.17.1 was Yes No Yes No Yes Yes No

Conclusion: the If test is always evaluating as TRUE for 2.7.17 and 2.7.17.1

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Duplicate issue of #5643

PR : #5656
