### ISSUE TITLE
WP responsive images: add image id to Pod reference list available for magic tags 

### ISSUE THREAD

**Issue by raoulunger** [pods-framework/pods#5652]
Since 2015, Wordpress has added responsive images built into its core. It means that Wordpress, for a certain image, will pick the image size (from all available sizes) that is sufficiently large for the viewport the image is requested from. This prevents unnecessarily large images to be served to mobile devices. It is an important feature in Wordpress. In Pods, this functionality cannot be used yet - hence this feature request.

The functionality is triggered by the specific image id (number) added to the img-tag. Like so:

`<img src="[url here]" alt="" class="alignnone size-full wp-image-2641" />`

The part where it says 'wp-image-[unique image-id]' will trigger the functionality. Wherever an image is included via Wordpress' native editors, this now is the standard markup. 

However, when we use images in Pods, we write the markup ourselves in a template. Presently, the Pods reference list there provides numerous fields related to an image to be used in Magic Tags, but the image-id is not among them. If it would be, we could include it easily in the markup, and thus serve responsive images to our viewers. For example like so:

`<img src="{@image-1}" alt="" class="alignnone size-full wp-image-{@image-1._image-id}" />`

So the feature request would be: please include the image-id in the pod reference list for magic tags.

Thanks!

**Comment by JoryHogeveen** [comment]
HEllo @raoulunger 

Using `{@image-1.ID}` should work since the latest release.
Let me know!

Cheers, Jory

**Comment by raoulunger** [comment]
Hi Jory,

Thank you for your answer! Indeed I was able to include the image-id as intended, so that's great! 

But, unfortunately, for some reason reponsive images still do not work when produced from a pod. The responsive behaviour by WP is triggered by adding a class 'wp-image-[unique image id]. I am able to 'create' that class in the output by writing 'wp-image-{@image1-.ID} in a template. When I inspect the output, that class is there as expected. Still, Wordpress does not add the required SRCSET to the img-tag that is formed in this way.

I made a test set up with one image in a pod. On a page, the first image is frist included by writing the <img> tag myself, with the required trigger added.
The second line contains a pod shortcode 'pulling up' the exact same image with a template that makes sure the trigger is there as well. As you can see in the screenshot of the code the wp-image-class is indeed there. But WP has not added the SRCSET.

So apparently, that functionality is somehow blocked when PODS is the vehicle...

This is the code of the template 'test-responsive-image':
`<img src="{@image-1}" alt="" width="" height="" class="alignnone size-full wp-image-{@image-1.ID}" />`

This the code on the test page;
`<img src="https://roodlof.nl/wp-content/uploads/MU_Rotterdam_160216_073-1024x713-1.jpg" alt="" width="" height="" class="alignnone size-full wp-image-2641"" />`
`[pods name="test" template="test-responsive-image"]`

Both images turn up, but the output in code is different. In the first image WP added the SCRSET, in the second (produced by Pods) it did not:

![Screenshot 2020-03-29 at 20 42 51](https://user-images.githubusercontent.com/53795112/77857463-e1f7cf00-71fd-11ea-90ae-1f6cce8e49e2.png)

Do you perhaps have any thoughts why this might happen?

Thanks!

**Comment by jimtrue** [comment]
My suggestion: we need a handler for this, like the `_img` and `_src` magic tag handlers. Maybe `_resp`?

**Comment by jimtrue** [comment]
Or we need to look at the code we're outputting for _img to output the correct style that the folks are looking for above.

**Comment by JoryHogeveen** [comment]
It seems weird to me that the `display` method from oEmbed outputs the full HTML but the `display` method for images (files) does only return the URL..

@sc0ttkclark Is there a particular reason for this?

Outputting the full HTML would solve this. I also thought this was the case..

**Comment by JoryHogeveen** [comment]
In any case. To get the full `srcset` for responsive images it will need to go through `wp_get_attachment_image()`, or in our case `pods_image()` which uses that same function.

**Comment by JoryHogeveen** [comment]
@raoulunger 
You could try the following: `{@image-1.ID,wp_get_attachment_image}`. This will get the ID and then pass it through `wp_get_attachment_image`.
This will render the full HTML.

**Comment by JoryHogeveen** [comment]
Closing this topic.
`{@image-1._img}` is the correct solution. It will render the full HTML for your image.

**Comment by raoulunger** [comment]
Hi,

Thanks! I tested it again, and the '_img suffix does indeed render the responsive behaviour, so that's great. I used the same test setup as above, a single page with one 'normal' img tag, and one from within a pod shortcode. Both images turn up fine, and both have the SRCSET tag added to the html output. 

However, something weird is still happening: all characters that come after the Magic Tag that inserts the image id, are output at the frond end as text, as is clear in the attached screenshot. You can see the " /> at the right of the image. Any idea why that might be happening?

Page code:
`<img src="https://roodlof.nl/wp-content/uploads/MU_Rotterdam_160216_073-1024x713-1.jpg" alt="" width="" height="" class="alignnone size-full wp-image-2641" />`
+
`[pods name="test" template="test-responsive-image"]`

Template code:
`<img src="{@image-1}" alt="" width="" height="" class="alignnone size-full wp-image-{@image-1._img}" />`

Screenshot of html output:
![Screenshot 2020-03-31 at 18 52 04](https://user-images.githubusercontent.com/53795112/78053323-b94c1280-7380-11ea-97b3-58482d030aed.png)

Screenshot of right hand side of second photo:
![Screenshot 2020-03-31 at 18 47 49](https://user-images.githubusercontent.com/53795112/78053378-cec13c80-7380-11ea-91b4-846bb60be66b.png)

Thanks!

**Comment by JoryHogeveen** [comment]
Your template code is incorrect.

See: `wp-image-{@image-1._img}"`
Since adding `._img` renders the full image HTML it should not be used within attributes.
Just remove that whole line (the full image HTML) and replace it with `{@image-1._img}`

**Comment by raoulunger** [comment]
Ah! Sorry - I assumed that ._img came in place of the .ID solution earlier.
It works fine now - thanks again!
