### ISSUE TITLE
get_post_meta( ID, KEY ) doesn't return array() of values

### ISSUE THREAD

**Issue by nobleclem** [pods-framework/pods#5660]
**Describe the bug**
wordpress get_post_meta should return either an array of values or a single value if $single = true.  However pods breaks this behavior in classes/PodsMeta.php#L3107.  There is a check for `$single = true` on 3107 that was previously on 3108.  With it at this position when `$single = false` (default) the result of get_post_meta() ends up be as if you made `$single = true` in the call.  This breaks expected output of the function breaking some implementations of it.

**Expected behavior**
The check for `$single = true` should be moved from the IF on L3107 to the IF on L3108

## Pods Version
2.7.17.1

**Possible Workaround**
Change L3107 from
`if ( $single && ( ! is_array( $meta_cache[ $meta_k ] ) || ! isset( $meta_cache[ $meta_k ][0] ) ) ) {`
TO
`if ( ( ! is_array( $meta_cache[ $meta_k ] ) || ! isset( $meta_cache[ $meta_k ][0] ) ) ) {`

Change L3108 from
`if ( empty( $meta_cache[ $meta_k ] ) && ! is_array( $meta_cache[ $meta_k ] ) ) {`
TO
`if ( $single && empty( $meta_cache[ $meta_k ] ) && ! is_array( $meta_cache[ $meta_k ] ) ) {`

**Comment by JoryHogeveen** [comment]
Hi @nobleclem 
Could you please provide a test case so I can confirm this locally?

**Comment by nobleclem** [comment]
So did some testing and I have not tested all field types but this seems to happen on file fields.

Here is my test pod: (A post type with a single file/image field, everything else default)
```
{"meta":{"version":"2.7.17.1","build":1585683831},"pods":{"182":{"id":182,"name":"test","label":"Test","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"image":{"id":183,"name":"image","label":"Image","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"link":{"id":185,"name":"link","label":"Link","description":"","help":"","class":"","type":"website","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"-1","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","website_repeatable":0,"website_placeholder":""}},"show_in_menu":"1","label_singular":"Test","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"test","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

Then I created a file in my theme: `single-test.php` with the contents of
```
<pre>
<?php

echo "get_post_meta( $post->ID, 'image' ) \n";
var_dump( get_post_meta( $post->ID, 'image' ) );
echo "\n";

echo "get_post_meta( $post->ID, 'image', true ) \n";
var_dump( get_post_meta( $post->ID, 'image', true ) );
echo "\n";

?>
</pre>
```

In this case I would expect the first line to produce an array of WP_Post arrays, however it produces the same result as the last line which gets a single meta value.

**Comment by nobleclem** [comment]
I did test your code in PR #5661 and that seems to provide the correct results for this (file field) case.

**Comment by JoryHogeveen** [comment]
Hi @nobleclem 

Thanks for your confirmation. I'll add more tests to that PR before merging it to make sure this will always work as intended.
For now, please use that fix!

Cheers, Jory
