### ISSUE TITLE
Other Tables

### ISSUE THREAD

**Issue by chunnr** [pods-framework/pods#5679]
I learnt about Pods just last week at a virtual Meetup group - NH WordPress and I was interested in the plugin, especially after following a couple of videos by Jim True.  It solved my problem as new fields could be added to users table.

My suggestion is this should work on other tables.

The way I see this working based on the need to pair the source table with a 'meta' table, which is similar to 'usermeta' table, and one can provide name of one, if it exists or asks for one to b created.

Either way, the four fields would be:
- meta_id = sequence number in this table e.g. umeta_id. Defaults to 'meta_id'.
- meta_ source_id = unique key in source table e,g, ID, customer_id
- meta_key = pod field name e.g. phone_number
- meta_value = value supplied for the pod field, during maintenance of the source table.

I also see a new table e.g. 'pods_option' which holds various pods options and configuration.  Allowing table DROPS on deactivation, if configured or requested.

So let's say, I want to create a 'pod' called "WC Customer" - corresponding to WooCommerce's customer. At the time, I would say 'Create Meta table' and will be prompted for:
  Source Table = wc_customer_lookup. 
  Source Key = customer_id
  Source Form = xxxxx

I do not know how you would link to a source form e.g. add/edit of source table or create one if necessary.

Assume PODS would create a new table called: pods_wc_customer_meta, and save this name in pods_option table.

In pods_wc_customer_meta, you would have the four fields:
- meta_id = sequence number
- meta_ source_id = unique key in source table e,g, customer_id
- meta_key = pod field name e.g. phone_number
- meta_value = value supplied for the pod field, during maintenance of the source table.

 Advantage of this is the ability to extend power of Pods to work with more tables and other products.  There will need to be a 'sync' option to remove deleted source, and to list new source not defined in the meta table.

**Comment by chunnr** [comment]
I dont know how all this will work, but I just made a suggestion to allow Pods to work with other tables.  My emai is "chun.mail.05@gmail.com', should you need to contact me.  Thanks.

**Comment by jimtrue** [comment]
@chunnr The 'meta table' you are referring to is wp_postmeta, that's how WordPress Post Meta works:
https://deliciousbrains.com/tour-wordpress-database/

We won't be doing this because WordPress is already doing that.

**Comment by chunnr** [comment]
I guess I will have to read more, but sincere 'thank you' Jim.

Regards,
Chun
