### ISSUE TITLE
PodsAPI::save_wp_object is called once for each field on update.

### ISSUE THREAD

**Issue by sourcejockey** [pods-framework/pods#5680]
## Issue Overview
When a post is being updated, PodsAPI::save_wp_object is called once for each field. When there are other save hooks, this exponentially slows an update down.

## Expected Behavior
I would expect PodsAPI::save_wp_object to be called once per post save/update.

## Current Behavior
PodsAPI::save_wp_object is called once per post save/update.

## Steps to Reproduce (for bugs)
1. Save a post with many fields.
2. Watch the server timeout.

## Possible Solution
Reduce PodsAPI::save_wp_object to one call per save.

## WordPress Environment

<details>

```
WordPress Version: 5.4

PHP Version: 7.3.16-1+ubuntu18.04.1+deb.sury.org+1

MySQL Version: 5.7.25

Server Software: Apache/2.4.29 (Ubuntu)

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 512M

Current Memory Usage: 19.926M

Current Memory Usage (real): 20.000M

Pods Network-Wide Activated: No

Pods Install Location: /var/www/html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: REDACTED

Currently Active Plugins:

Admin Columns Pro: 5.1.3
Admin Menu Editor: 1.9.5
Advanced Image Sitemap: 1.2
Akismet Anti-Spam: 4.1.4
Better Notifications for WP: 1.8
BNFW - Conditional Notifications Add-on: 1.0.12
Classic Editor: 1.5
Email Log: 2.3.2
Exports and Reports: 999.6 (modified)
Google Language Translator: 6.0.6
Gravity Forms: 2.4.17
REDACTED
Head, Footer and Post Injections: 3.1.6
REDACTED: 1.0
iContact for Gravity Forms: 1.3.2
Imsanity: 2.6.0
Infinite WP List Tables: 2.0.0
Invisible reCaptcha: 1.2.3
Multi-column Tag Map (!MODIFIED!): 912.0.4
Pods - Custom Content Types and Fields: 2.7.20
Query Monitor: 3.5.2
Redirection: 4.7.1
Regenerate Thumbnails: 3.1.3
Relevanssi Premium: 2.8.2
Responsive Lightbox & Gallery: 2.2.2
SEO Ultimate: 7.6.5.9
Tabify Edit Screen: 0.9.7
REDACTED
W3 Total Cache: 0.13.2
WP Mail SMTP: 1.9.0
WP SEO Structured Data Schema Pro: 1.2.11
XML Sitemap & Google News: 5.2.7

```
</details>

## Workaround or Alternate Solution Until Bug is Addressed
We've disabled some of the more hefty save hooks from OTHER modules that slow things down--but they're just hooking in.

**Comment by sc0ttkclark** [comment]
You'll be happy to know our process for saving pods/fields has changed in Pods 2.8 along with our new admin UI. It's less "all or nothing" and more "save what you want". I'm going to close this for now because of that, but don't think that your opinion here has been forgotten, I love that you found this and we're on the same page!
