### ISSUE TITLE
Empty apply_filters

### ISSUE THREAD

**Issue by cfaria** [pods-framework/pods#5686]
**Describe the bug**
On file **pods/ui/admin/setup-edit-field.php**, **line 22** there is an apply_filters call with an empty hook name.

`$ignored_pick_objects = apply_filters( '', array( 'table' ) );`

If, for any reason, an add_filter is used with empty hook anywhere in themes or other plugins, the function declared will be called and is prone to show fatal errors if the function doesn't have the correct objects. 

If the fatal error is reached, the admin part of pods won't show fields editing a pod...

**To Reproduce**
1. Install and activate pods. Create a pod, create a field inside that pod
2. Install and activate woocommerce
3. Install and activate yith-woocommerce-gift-cards
4. Add this filter in functions.php:
```
add_filter('ywgc_gift_card_code_form_cart_hook', function(){
  return '';
});
```
5. Navigate to edit the pod fields created in step 1

**Expected behavior**
The fields should be seen but they are not visible as there has been a Fatal Error.

## Pods Version
2.7.20

## WordPress Environment
<details>

`
### wp-core ###

version: 5.4
site_language: es_ES
user_language: es_ES
timezone: Europe/Madrid
permalink: /%postname%/
https_status: false
user_registration: 1
default_comment_status: open
multisite: false
user_count: 75002
dotorg_communication: true

### wp-active-theme ###

name: Supermundano v1 (supermundano)
version: 1.16.0
author: Supermundano
author_website: https://supermundano.com/
parent_theme: none
theme_features: post-thumbnails, soil-clean-up, soil-disable-trackbacks, soil-jquery-cdn, soil-js-to-footer, soil-nav-walker, soil-nice-search, soil-relative-urls, title-tag, menus, html5, woocommerce, widgets

### wp-mu-plugins (4) ###

Bedrock Autoloader: version: 1.0.0, author: Roots
Disable plugins on development: version: 1.0.0, author: Supermundano
Disallow Indexing: version: 1.0.0, author: Roots
Register Theme Directory: version: 1.0.0, author: Roots

### wp-plugins-active (3) ###

Pods - Custom Content Types and Fields: version: 2.7.20, author: Pods Framework Team
WooCommerce: version: 4.0.1, author: Automattic
YITH WooCommerce Gift Cards: version: 2.0.3, author: YITH

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: No disponible
imagemagick_version: No disponible
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 17.7.0 x86_64
httpd_software: nginx/1.17.9
php_version: 7.3.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 256M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.69.1 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 10.4.11-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.17.9
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:75.0) Gecko/20100101 Firefox/75.0
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Sí
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 29,501M
pods-memory-current-usage-real: 12,000M
pods-network-wide: No
pods-install-location: /web/app/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Sí
pods-allow-deprecated: No
pods-api-cache: Sí
pods-shortcode-allow-evaluate-tags: No

`

</details>

**Possible Workaround**
Add a hook name to that apply_filters on file **pods/ui/admin/setup-edit-field.php**, **line 22** 👍

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
See commit here: https://github.com/pods-framework/pods/commit/f75c3b8d8f07d844c1983e9e325c7fd7e051e29f

**Comment by sc0ttkclark** [comment]
@JoryHogeveen let's get a real filter name added there with the corresponding hook phpdoc.

**Comment by sc0ttkclark** [comment]
Good find @cfaria!
