### ISSUE TITLE
Incompatibility between PODS 2.7.2 and Elementor Pro 2.9.3 on WP 5.4

### ISSUE THREAD

**Issue by mstempssh** [pods-framework/pods#5695]
## Issue Overview
Incompatibility between PODS and Elementor
I'm using Elementor Pro 2.9.3 and PODS 2.7.2 on WP 5.4
When using the Elementor IMAGE widget, I connect a widget and find that the **Insert Media button is never enabled.**
When I Deactivate PODS, the Insert Media button turns blue.  
I can replicate this situation simply by activating and deactivating PODS.
Is anybody aware of any incompatibility like this between Elementor and PODS?

## Expected Behavior
I'm using the Elementor IMAGE widget to insert an image into a blog post, 
When trying to insert an image into the widget, you should be able to choose an image  and then click on **Insert Media**

## Current Behavior
With PODS enabled, the **Insert Media button is never enabled.**  When I disable PODS, I have no problem.

## Steps to Reproduce (for bugs)
1. Enable PODS
2. Try to connect an image
3. Insert Media button is never enabled
![Insert Image not Enabled](https://user-images.githubusercontent.com/64255576/80206351-278b9a00-85fa-11ea-9275-f4ae2eb46daf.png)

## Possible Solution
Disable PODS
Insert Image into Elementor Image Widget
Re-enable PODS

## WordPress Environment
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
I'm using Elementor Pro 2.9.3 and PODS 2.7.2 on WP 5.4
[PODS Settings Debug.txt](https://github.com/pods-framework/pods/files/4528501/PODS.Settings.Debug.txt)

## Pods Package Export (helpful!)
[PODS Jason.txt](https://github.com/pods-framework/pods/files/4528473/PODS.Jason.txt)```
```

## Workaround or Alternate Solution Until Bug is Addressed
The workaround is 
1. Disable PODS, 
2. Insert Image in Elementor Post widget, 
3. Re-enable PODS

## Related Issues and/or PRs
<!-- List related issues or PRs against other branches:  -->

**Comment by JoryHogeveen** [comment]
Closing due to duplicate issue. There are numerous issues created because of Elementor Pro use. This is an issue on their part thus I'm closing here. Please contact their support.
