### ISSUE TITLE
broken edit-link in custom admin menu

### ISSUE THREAD

**Issue by arkonisus** [pods-framework/pods#5702]
**Describe the bug**
If you try to add a pod to a custom admin menu the edit-link is broken. 

Reason: 
In PR #5497 the hook priority was set to 9. If you change it to any higher number than 9 it will work again.

**To Reproduce**
1. create a custom admin menu via "add_menu_page()"
2. Insert the menu id in field "Admin UI / Parent Menu ID" of your pod
3. The link of the new created menu-entry is broken  `/wp-admin/pods-manage-projekt`

**Expected behavior**
The link should look like `/wp-admin/admin.php?page=pods-manage-projekt`

# Pods Version
&gt; 2.7.15

**Comment by JoryHogeveen** [comment]
@arkonisus 
That priority was changed because it was causing another bug.
In what hook and priority are you creating the menu page?

**Comment by arkonisus** [comment]
@JoryHogeveen 
Oh, thank you very much for the hint!
I used the "admin_menu" hook without any priority like the example from the codex.  
Setting any priority will work well with the latest pods release. So i think we could close this issue...
