### ISSUE TITLE
move to trash

### ISSUE THREAD

**Issue by JoshLavinsky** [pods-framework/pods#5707]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoshLavinsky** [comment]
Hi Jory - I saw this was closed but didn't see any update to my original
support request on WordPress support page. Do you have any idea when I
should see a response?

Thanks

Josh

**Comment by JoryHogeveen** [comment]
Hello Josh,
I closed this since your ticket didn't include any information at all.
Please create a new ticket and fill in all information as described.
