### ISSUE TITLE
Fatal Error on Backend edit pods item page by adding get_title function to functions.php

### ISSUE THREAD

**Issue by robpie-de** [pods-framework/pods#5708]
got error "Fatal error: Uncaught ArgumentCountError: Too few arguments to function woo_title_order_received()" on backend by edit pods item page:

`add_filter( 'the_title', 'woo_title_order_received', 11, 2 );
function woo_title_order_received( $title, $id ) {
        if ( function_exists( 'is_order_received_page' ) &&
             is_order_received_page() && get_the_ID() === $id ) {
                $title = "Thank you for your order! :)";
        }
        return $title;
}`

to the functions.php an go to the edit pod item page on backend

ERROR MESSAGE:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function woo_title_order_received(), 1 passed in /wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /wp-content/themes/storefront-child/functions.php:866 Stack trace: #0 /wp-includes/class-wp-hook.php(287): woo_title_order_received('Titel') #1 /wp-includes/plugin.php(206): WP_Hook->apply_filters('Titel', Array) #2 /wp-content/plugins/pods/classes/fields/pick.php(2384): apply_filters('the_title', 'Titel') #3 /wp-content/plugins/pods/classes/fields/pick.php(1716): PodsField_Pick->get_object_data(Array) #4 /wp-content/plugins/pods/classes/PodsForm.php(239): PodsField_Pick->data('pods_meta_stadt', Array, Array, Object(Pods), '984', true) #5 /wp-content/plugins/pods/classes/PodsMeta.php(1199): in /wp-content/themes/storefront-child/functions.php on line 866`

and line 866 is this one:

`function woo_title_order_received( $title, $id ) {  ... `

Lastest Wordpress & Pods Version

**Comment by JoryHogeveen** [comment]
Hello @robpie-de 
We do not use the `the_title` filter in our code. We do however call `get_the_title` with the correct amount of parameters (1: post ID).
This bug is because of a different plugin. Please disable one by one and you'll find the "faulty" plugin.
Cheers, Jory
