### ISSUE TITLE
Hiding Field Data From Frontend At Specific Date

### ISSUE THREAD

**Issue by swabhav** [pods-framework/pods#5717]
I have a created job post that having an expiry date field and I want to hide all jobs when job expires and expired jobs go to an accordion.

For example-

**when active job posts. Show like this -**
- Samsung Recruiting For Engineer Posts 
- Google Recruiting For Manager Posts

**when expired job posts. Show like this -**
- Google Recruiting For Manager Posts
[See expired jobs (In Accordion)
](#)  - Samsung Recruiting For Engineer Posts

All Job Posts Having a field **expiry date** and I want to hide all those jobs which are expired.
when users click on accordion expired jobs are showing under accordion.

**Comment by JoryHogeveen** [comment]
I think this page and especially the videos will help you: https://docs.pods.io/faqs/what-can-you-build-with-pods/

Note that accordion's UI isn't part of Pods. You'll have to make that yoursend. For example with Bootstrap or something similar/custom.

Good luck with your project!
