### ISSUE TITLE
Add bidirectional field to Media object extended by Pods

### ISSUE THREAD

**Issue by PlutonB** [pods-framework/pods#573]
Referring to the thread http://podsframework.org/forums/topic/relationship-field-to-media-pod/#post-171757

When the media object is extended by Pods, it should be possible to set the file field as being bidirectional. When media files are attached to a pods bidirectional file field, the system automatically updates a corresponding field in the Media Pod. In effect, this makes it possible to attach media to many pods directly from the media file itself.

**Comment by pagesailor** [comment]
+1
