### ISSUE TITLE
Support Pod-related magic tags in where/having tags from shortcode in content

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5734]
Currently magic tags related to the pod (eg: `{@ID}`) can only be used on Pods Templates.
Would be nice if this was possible in shortcodes on any location, post content for example.

Example: `[pods name="page" where="post_parent = {@ID}"]`. ID should refer to the current post.

Ref: https://wordpress.org/support/topic/how-ti-get-id-page-post/

This is because pods_evaluate_tag() doesn't evaluate Pod object related tags, only special magic tags.

Todo:

- [x] Support Pod related tags in `pods_evaluate_tag()`
- [x] Support helpers in `pods_evaluate_tag()`

**Comment by jimtrue** [comment]
They are available in the shortcode, between [pods]...[/pods] Or do you mean some other way?

**Comment by JoryHogeveen** [comment]
I mean in the `where` tags etc.

**Comment by jimtrue** [comment]
Yes, that's much clearer @JoryHogeveen Can you update the issue/title for that? We are restricted way too much about where those kinds of items can be processed.

**Comment by JoryHogeveen** [comment]
Good one, done!
