### ISSUE TITLE
Click to copy element to another relationship field

### ISSUE THREAD

**Issue by Ryvix** [pods-framework/pods#5737]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out the best way to be able to copy elements from one relationship field to another. Basically one field is storing results from a search on posts in the database and one field will be the approved posts which will display on a custom page template.

**Describe the solution you'd like**
I'm currently using the Multiple Select, Autocomplete options for 2 relationship fields and want to be able to click elements in the results field and have them appear in the approved field. This is only for the admin screens in my case when editing the post.

**Describe alternatives you've considered**
I've tried the other Selection Type and Format options but the Autocomplete seemed to work the best. I'm not sure if it would be better to just make a new field type or even how to go about doing that yet.

**Additional context**
I've figured out I can get the data from the field like this:

`let index = $('.pods-form-ui-row-name-results li.select2-selection__choice').index(this);
let data = PodsDFV.fieldInstances['pods-form-ui-pods-meta-results'].fieldItemData[index];
PodsDFV.fieldInstances['pods-form-ui-pods-meta-approved'].fieldItemData.unshift(data);`

I have to add some way to make it not keep adding multiple copies once it already exists too if that's even necessary, and find some way to make it render on the approved field.

I tried doing this but that doesn't seem to work so I'm guessing I'm missing something else.

`PodsDFV.fieldInstances['pods-form-ui-pods-meta-approved'].render();
jQuery(this).trigger('render');`

There has to be a better way to do all this but I can't seem to figure it out. Any help is greatly appreciated!

Thank you!

**Comment by JoryHogeveen** [comment]
Hello @Ryvix 

As you probably noticed this isn't supported by Pods.
Without having a better understanding of your setup I'm not sure how to best help you as this is a more general JavaScript question (getting and setting a field in Select2), not necessarily Pods related.

We have a full template for bug reports, please fill in the info. I've modified your issue.

Cheers, Jory

**Comment by Ryvix** [comment]
Hello,

Thank you very much for the response!

Yes I was thinking it could maybe be added as a new feature if it was good enough or if it isn't useful then maybe someone would be willing to help who knew the inner workings of Pods better than I do.

Unfortunately I can't share a link since it's when editing the post in the admin but it's pretty simple to describe. If you can imagine two separate Pods relationship fields, both using the _Multiple Select_ and _Autocomplete_ options under the _Additional Field Options_ tab in my case. I just want to be able to click the entries in the first field and copy them over to the second field.

**Field 1**
The first field is called Results. It contains a list of search results automatically filled in via a WP cron that searches posts and stores the results in that field. It isn't actually supposed to be manually edited since it will just get replaced the next time the cron runs. So it doesn't matter if this is a Multi-select, autocomplete type but it seemed like it would be easier to copy them to the other field this way.

**Field 2**
The second field is called Approved and any posts that are clicked in the Results field should be copied to the Approved field so that when the post is updated it will store them there properly.

It doesn't seem to be as simple as it sounds and I think that's because Pods must be doing something somewhere with data or something else that I can't quite figure out yet. I was thinking there probably is some way with the right Javascript calls but I just don't know what it is because I still don't know Pods well enough.

Thanks again!

**Comment by Ryvix** [comment]
I finally figured something out!

I found some code in the pick.js modalSuccess function that helped.

I discovered that Pods will output a script tag with some data in it and remove that tag after it processes the data and will add the data to the fields. It also will update the fields when a modal is closed and the  'dfv:modal:update' event is triggered and add any new items added to the list, I suspect from something like the Add New button if it's enabled.

`jQuery(document).ready(function ($) {
	// detects a click on an item in the results field
	$(document).on('click', '.pods-form-ui-row-name-results li.select2-selection__choice', function (event) {
		event.preventDefault();
		event.stopPropagation();

		// closes any dropdowns so they don't get in the way
		$('.select2-dropdown').hide();

		// gets the index of the item clicked in the results field
		let index = $('.pods-form-ui-row-name-results li.select2-selection__choice').index(this);

		// get PodsDFV field instances
		let results = PodsDFV.fieldInstances['pods-form-ui-pods-meta-results'];
		let approved = PodsDFV.fieldInstances['pods-form-ui-pods-meta-approved-listings'];

		// get data from the clicked results item
		let data = results.fieldItemData[index];

		// from Pick.modalSuccess
		const itemModel = approved.collection.get( data.id );
		if ( itemModel) {
			// field exists so update it
			itemModel.set( data );
			approved.getChildView( 'list' ).render();
		} else {
			// field doesn't exist so add it
			approved.collection.add( data );
		}

		return false;
	});
});`

**Comment by JoryHogeveen** [comment]
Hello @Ryvix 

Good to hear you figured it out. Thanks for letting me know!

Cheers, Jory
