### ISSUE TITLE
Error errno=21 when Pods is installed as a must-use plugin

### ISSUE THREAD

**Issue by gpsugy** [pods-framework/pods#5746]
**Describe the bug**
When using the Pods plugin as a Must-Use plugin, an error is shown on the Plugins page.

**To Reproduce**
1. Add/install the Pods plugin on WordPress
2. Drag/drop the generated `pods` folder into the `mu-plugins` directory
3. Go to the Plugins page on the admin-side of the WordPress site
4. See error: `Notice: fread(): read of 8192 bytes failed with errno=21 Is a directory in /Users/myuser/site/src/site.com/web/wp/wp-includes/functions.php on line 5977`

**Expected behavior**
No error

## Pods Version
2.7.20.1

## WordPress Environment
<details>
5.4.2

`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/myuser/site/src/site.com/web/wp
wordpress_size: loading...
uploads_path: /Users/myuser/site/src/site.com/web/app/uploads
uploads_size: loading...
themes_path: /Users/myuser/site/src/site.com/web/app/themes
themes_size: loading...
plugins_path: /Users/myuser/site/src/site.com/web/app/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Test Theme
version: 1.0.0
author:
author_website:
parent_theme: none
theme_features: sage, soil-clean-up, soil-nav-walker, soil-nice-search, soil-relative-urls, title-tag, menus, post-thumbnails, align-wide, responsive-embeds, html5, customize-selective-refresh-widgets, editor-color-palette, widgets
theme_path: /Users/myuser/site/site/src/site.com/web/app/themes/nfwp

### wp-themes-inactive (10) ###

Twenty Eleven: version: 3.4, author: the WordPress team
Twenty Fifteen: version: 2.6, author: the WordPress team
Twenty Fourteen: version: 2.8, author: the WordPress team
Twenty Nineteen: version: 1.5, author: the WordPress team (latest version: 1.6)
Twenty Seventeen: version: 2.3, author: the WordPress team
Twenty Sixteen: version: 2.1, author: the WordPress team
Twenty Ten: version: 3.0, author: the WordPress team
Twenty Thirteen: version: 3.0, author: the WordPress team
Twenty Twelve: version: 3.1, author: the WordPress team
Twenty Twenty: version: 1.2, author: the WordPress team (latest version: 1.4)

### wp-mu-plugins (3) ###

Bedrock Autoloader: version: 1.0.1, author: Roots
Disallow Indexing: version: 1.0.0, author: Roots
Register Theme Directory: version: 1.0.0, author: Roots

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 19.5.0 x86_64
httpd_software: nginx/1.19.0
php_version: 7.4.6 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.70.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 8.0.19
client_version: mysqlnd 7.4.6

### wp-constants ###

WP_HOME: http://localhost:8080
WP_SITEURL: http://localhost:8080/wp
WP_CONTENT_DIR: /Users/myuser/site/src/site.com/web/app
WP_PLUGIN_DIR: /Users/myuser/site/src/site.com/web/app/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.19.0
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 5.125M
pods-memory-current-usage-real: 2.000M
pods-network-wide: No
pods-install-location: /Users/myuser/site/src/site.com/web/app/mu-plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export
This occurs with just a fresh install of the Pods plugin

**Possible Workaround**
Although not desired, this error is avoided when left as a regular plugin (not a Must-Use plugin)

**Comment by JoryHogeveen** [comment]
Pods doesn't officially support being placed in the mu-plugins folder.
I also wouldn't recommend it as WordPress doesn't check this folder for updates.

**Comment by gpsugy** [comment]
Thank you for the clarification!
