### ISSUE TITLE
Multi-Site Media Compatibility 

### ISSUE THREAD

**Issue by marcd123** [pods-framework/pods#5748]
## Issue Overview
We are using Pods custom post types on a WordPress Multi-Site Network. We are also using a plugin called [Network Media Library](https://github.com/humanmade/network-media-library) that forces all media uploaded from any site to be stored under the main site (blog ID 1). All sites can still access this media, it's just stored in the main site folder and recorded in the main site wp_posts table.

If I am editing a custom Pod post on a site other than the main site (Blog 2 for example), and I use a media field to add a photo to the post, I get a "Invalid Post ID" error after trying to save the custom post. All the information saves besides the media, and the error does not occur if no media is selected - thus the media is the issue.

My assumption is that the Pod plugin is trying to look up the Post ID of the image in the Blog 2 posts table, but the Post ID does not exists there - it exists in the main site Posts table. 

I understand why the plugin does this and it makes sense in 99% of cases. I'm looking for advice on how I may alter the plugin to force media fields to point to blog ID 1.

## Expected Behavior
Image record is stored in wp_posts (Blog 1 table)
Create new Pod post in Blog 2
Add photo to Pod post in Blog 2 (photo is stored in Blog 1)
Photo is requested from wp_posts (Blog 1 table)
Post is successfully saved, no "Invalid Post ID" error occurs

## Current Behavior
Image record is stored in wp_posts (Blog 1 table)
Create new Pod post in Blog 2
Add photo to Pod post in Blog 2 (photo is stored in Blog 1)
Photo is requested from **wp_2_posts (Blog 2 table)**
Photo post ID does not exist in wp_2_posts
"Invalid Post ID" error occurs

## Steps to Reproduce (for bugs)
1. Create new Multi-Site network
2. Install Network Media Plugin
3. Install Pod plugin
4. Configure Network Media Plugin to force all media storage to Blog ID 1
5. Create a new blog on the network (Blog ID 2)
6. Create a custom Pod post type with Media Input (on blog 2)
7. Attempt to create and save new custom Pod post on Blog 2, using media/photo that is stored on Blog 1
8. Upon clicking save, should be redirected to error page that says "Invalid Post ID"

## Possible Solution
It's such a specific use case that it probably doesn't need to be accommodated in the plugin.
I would greatly appreciate advice on how I can personally modify the plugin code to force media to always be requested from the Main blog (Blog ID 1). Something like switch_to_blog(1). Just need to know where to implement that in plugin code.

**Comment by JoryHogeveen** [comment]
@marcd123 
Can you please test the changes made in #5754 and let me know of this fixes your issue.

**Comment by marcd123** [comment]
Hey Jory. Thanks for the quick response.

I cloned master and switched to the feature branch you linked and then reinstalled the plugin.

I am still getting the "Invalid Post ID" error. The error is thrown in wp-includes/post.php in the wp_update_post function.

![image](https://user-images.githubusercontent.com/9528376/85326725-5f487e00-b493-11ea-8404-c2c4de07c878.png)

The highlighted portion of the code above is trying to request the Post ID of the image in the current blog's posts table. In my case I'm on blog 2 so it's requesting from wp_2_posts.

The image actually exists in wp_posts (the main blog post table).

Would #5754 be expected to solve that issue?

**Comment by JoryHogeveen** [comment]
Hello @marcd123 

The fix was actually because of the above.
I do not know of any other way to add the information in our update call that the network media plugin could filter.

The idea of my PR is to add the post_type parameter in this update call so the network media plugin would recognize that and apply it's filters. If that doesn't happen then apparently that is not the case. I think it's best to add a support request at them for this issue. I might be missing something here but I'd assume they have filters in place for creating/updating attachments.
