### ISSUE TITLE
Dog ate my homework

### ISSUE THREAD

**Issue by chafields** [pods-framework/pods#5749]
## Issue Overview

If I build up a url from a combination of text and pods tags inside a pods template's anchor tag, it works fine and I can string along arguments with no problem to pass a JSON string full of parameters to the web site, up until I include a pods tag as part of the url.  If I do that, the template editor will erase my work.

## Expected Behavior

When I enter text in the template editor and click on Update, I would expect the editor to somehow mark bad code and give a hint as to what's wrong with it.  Minor automatic corrections would be fine.

Here is existing, similar code that works fine inside an anchor tag:
 `href="https://www.myforms.com/QuickPMDocs/ProjectInformation?entry={%22CompanyName%22:%22{@id,get_company}%22,%22QPMDUserID%22:%22{@id,get_QPMID}%22,%22Postauthor%22:%22{@id}%22}"`
 

## Current Behavior
`
I start by entering this code:'
'<p>
<a target="_blank"
   href="{@create_document}?entry={%22Postauthor%22:}"
   rel="noopener noreferrer">
	<button>Create a New {@post_title}</button>	
</a> </p>`

```

It is accepted.  The tag @create_document contains the url without parameters. 
To complete the JSON string begun with %22Postauthor%22:, I add a tag so that the full JSON entry={%22Postauthor%22:%22{@user.id}%22}
After clicking on "Update", the string in the editor is:
`<p>
<a target="_blank" href="%22{@user.id}%22}" rel="noopener noreferrer">
	<button>Create a New {@post_title}</button>	
	</a> </p>`
I have seen other strings result in no href phrase at all!

<!-- If suggesting a change/improvement, explain the difference from current behavior -->
<!-- Provide screen shots or screencasts, if you can. Anything you can provide to --> 
<!-- help illustrate what you are experiencing is helpful -->

## Steps to Reproduce (for bugs)
<!-- Provide a link to a live example, or an unambiguous set of steps to -->
<!-- reproduce this bug. Include code to reproduce, if relevant -->
1.  Create a pod with a name such as qpm_form
2.  Create a text field within the pod, call it create_document and enter a url.
3.  Create a pods template and enter the code above
4.  Watch the code disappear when you click on Update

## Possible Solution
<!-- Not obligatory, but suggest a fix/reason for the bug, -->
<!-- or ideas how to implement the addition or change -->
  I realize that the code above still needs work.  @user.id needs to be in the context of a user pod, or be referenced from the pod.  I will continue to work on that.  My concern is that the code has valid syntax but the editor deletes it.  With no feedback on the problem with the code, it is difficult to make progress.
## WordPress Environment
<!-- This is REQUIRED for Bug Reports, so we can check for conflicts, version issues, etc. -->
<details>
![image](https://user-images.githubusercontent.com/58439210/84938236-eddf8880-b0aa-11ea-8a92-916e72ddd413.png)

```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
WordPress Version: 5.4.2

PHP Version: 7.3.5

MySQL Version: 8.0.16

Server Software: nginx/1.16.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 11.353M

Current Memory Usage (real): 4.000M

Pods Network-Wide Activated: No

Pods Install Location: C:\Users\cfields\Local Sites\quickpmdocs\app\public\wp-content\plugins\pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Memberlite

Currently Active Plugins:

Akismet Anti-Spam: 4.1.6
Code Snippets: 2.14.0
Dashboard Widgets Suite: 2.5
Duplicate Post: 3.2.4
Paid Memberships Pro: 2.3.3
Paid Memberships Pro - Auto-Renewal Checkbox: .2.8
Paid Memberships Pro - Register Helper Add On: 1.6.1
Pods - Custom Content Types and Fields: 2.7.21-a-1
Simple Example Plugin: 1.0
Ultimate Addons for Gutenberg: 1.15.2
WP AutoTerms: 2.4.1
WPForms Lite: 1.6.0.2
WP Webhooks Pro: 3.0.3
</details>

## Pods Package Export (helpful!)
<!-- Please include the Pods Package Export as it will be helpful in reproducing your issues. -->
<!-- To access: Pods Admin, Components, Migrate: Packages, Enable. -->
<!-- Then Pods Admin, Migrate: Packages, Export and Copy and Paste the JSON here OR -->
<!-- Save to a text file and upload to this bug report -->
```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
`{"meta":{"version":"2.7.21-a-1","build":1592420498},"pods":{"565":{"id":565,"name":"document","label":"Documents","description":"Project Documents","type":"post_type","storage":"meta","object":"","alias":"","fields":{"document_form":{"id":566,"name":"document_form","label":"Document Form","description":"Link to the document entry in Cognito Forms","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","website_format":"normal","website_allow_port":"1","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","website_placeholder":"Automatic","pick_post_status":["publish"],"admin_only":"0","restrict_role":"1","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator","editor","author","contributor"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0"},"form_template":{"id":567,"name":"form_template","label":"Form Template","description":"Which QuickPM Form was used to create this document","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"project":{"id":568,"name":"project","label":"Project","description":"Which project is being documented","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"project","sister_id":"569","required":"1","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Document","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"document","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"1","supports_thumbnail":"0","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"1","supports_revisions":"1","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","built_in_taxonomies_wpforms_log_type":"0","menu_position":"7","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-edit","name_admin_bar":"Project Documents","pfat_single":"NewDocument"},"570":{"id":570,"name":"qpm_form","label":"Forms","description":"Create Document","type":"post_type","storage":"meta","object":"","alias":"","fields":{"create_document":{"id":572,"name":"create_document","label":"Create Document","description":"Link to the Cognito Form, not an existing Entry, so that a new Entry is Created","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"1","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_placeholder":"https:\/\/www.cognitoforms.com\/QuickPMDocs\/","text_repeatable":"0"},"cog_name":{"id":1079,"name":"cog_name","label":"Cognito Name","description":"Name of the Form in Cognito, suffix to url","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"1","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""}},"show_in_menu":"1","label_singular":"QPM Form","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"qpm_form","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_wpforms_log_type":"0","menu_position":"8","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-plus","name_admin_bar":"Create Doc","pfat_single":"MyProjects","label_view_items":"My Forms"},"553":{"id":553,"name":"project","label":"Projects","description":"Each Project is a collection of project documents","type":"post_type","storage":"meta","object":"","alias":"","fields":{"project_information_form":{"id":555,"name":"project_information_form","label":"Edit Project Information","description":"This is the master form of the project, with information shared to all project documents","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","website_format":"force-www","website_allow_port":"1","website_clickable":"0","website_new_window":"1","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"project_id":{"id":556,"name":"project_id","label":"Project ID","description":"Unique ID used by your organization to identify a project","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"project_sponsor":{"id":558,"name":"project_sponsor","label":"Project Sponsor","description":"The person or organization that is paying for the project.  In short, the customer","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"project_manager":{"id":557,"name":"project_manager","label":"Project Manager","description":"Full name of the Project Manager","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"start_date":{"id":559,"name":"start_date","label":"Start Date","description":"The official starting date of the project, usually the approval date","help":"","class":"","type":"date","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"format","date_format":"mdy","date_allow_empty":"1","date_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":"","date_year_range_custom":""},"subproject":{"id":564,"name":"subproject","label":"SubProject","description":"A smaller part of the current project that is being managed as another project","help":"","class":"","type":"pick","weight":5,"pick_object":"post_type","pick_val":"project","sister_id":"","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"documents":{"id":569,"name":"documents","label":"Documents","description":"Set of documents that describe this project","help":"","class":"","type":"pick","weight":6,"pick_object":"post_type","pick_val":"document","sister_id":"568","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"project_creator":{"id":791,"name":"project_creator","label":"Project Creator","description":"WP User who initiated this project","help":"","class":"","type":"pick","weight":7,"pick_object":"user","pick_val":"","sister_id":"792","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Project","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"0","exclude_from_search":"0","capability_type":"post","capability_type_custom":"project","capability_type_extra":"1","has_archive":"1","hierarchical":"1","rewrite":"0","rewrite_with_front":"0","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"publish","supports_author":"1","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"1","supports_page_attributes":"1","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"1","built_in_taxonomies_wpforms_log_type":"0","menu_position":"6","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-portfolio","label_parent":"Portfolio","label_parent_item_colon":"Portfolio","pfat_single":"MyProjects","menu_name":"Projects"},"643":{"id":643,"name":"user","label":"User","description":"","type":"user","storage":"meta","object":"user","alias":"","fields":{"projects_created":{"id":792,"name":"projects_created","label":"Projects Created","description":"Which projects I initiated","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"project","sister_id":"791","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"company":{"id":909,"name":"company","label":"Company","description":"Users in the same company can share projects and documents.","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"qpmid":{"id":917,"name":"qpmid","label":"Quick PM Docs ID","description":"GUID used to assure that each company is unique.  Maps to User ID in Cognito Forms","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""}},"show_in_menu":1,"rest_enable":"0","read_all":"0","write_all":"0"}},"templates":{"NewEntry":{"id":1074,"name":"NewEntry","code":"<p>\r\n<a target=\"_blank\" href=\"%22{@user.id}%22}\" rel=\"noopener noreferrer\">\r\n\t<button>Create a New {@post_title}<\/button>\t\r\n\t<\/a> <\/p>","type":"template","slug":"newentry","options":{"_edit_lock":"1592418739:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:8:\"qpm_form\";}"}},"MyProjects":{"id":595,"name":"MyProjects","code":"[if post_thumbnail]\r\n<img align=\"right\" {@post_thumbnail}\r\n <br>\r\n[\/if]\r\n<p><strong>Project: \r\n\t<a style=\"padding: 0 0 0 3em;\" href={@project_information_form}> {@post_title}<\/a><\/strong> <br>\r\n\tFor {@project_sponsor}, managed by {@project_manager}, cat: {@category}<br>\r\n Created by {@project_creator.display_name} of {@project_creator.company} <br>\r\n QPMID= {@project_creator.qpmid.meta_value}<\/p>\r\n\r\n\r\n","type":"template","slug":"595","options":{"_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","_edit_lock":"1592258166:1","pod_reference":"a:1:{s:3:\"pod\";s:7:\"project\";}"}},"NewProject":{"id":876,"name":"NewProject","code":"<a target=\"_blank\" href=\"https:\/\/www.cognitoforms.com\/QuickPMDocs\/ProjectInformation?entry={%22CompanyName%22:%22{@id,get_company}%22,%22QPMDUserID%22:%22{@id,get_QPMID}%22,%22Postauthor%22:%22{@id}%22}\" rel=\"noopener noreferrer\">  \r\n\t<button>Create a New Project<\/button>\t\r\n<\/a>\r\n","type":"template","slug":"newproject","options":{"_edit_lock":"1592420152:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}"}},"ThisUser":{"id":724,"name":"ThisUser","code":"<p>User {@id} {@display_name} of {@company} ID={@qpmid}<\/p>","type":"template","slug":"724","options":{"_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","_edit_lock":"1588624270:1","pod_reference":"a:1:{s:3:\"pod\";s:4:\"user\";}"}}}}``

## Workaround or Alternate Solution Until Bug is Addressed

One thing I've already noticed is that if I replace the majority of the url, which does not change with each post, with literal text "https:www..." in the template the problem becomes less severe.  What is then read from the post is just the name of the form at the website, not the whole url.

**Comment by chafields** [comment]
Ok, in the course of trying to fix my own issue of needing a user pod shortcode, I prefixed the href result described above with a shortcode+magic tag: 
`<p>
<a target="_blank" href="[pods name="user" where="id = {@user.id}"] %22{@user.id}%22}" rel="noopener noreferrer">
	<button>Create a New {@post_title}</button>	
	</a> </p>`
Result? The entire href clause disappeared!
The use of shortcode in the template is described (but no example) in
`https://docs.pods.io/displaying-pods/pods-templates/using-shortcodes-in-pods-templates/`

**Comment by chafields** [comment]
Here's an update on the workaround, which is satisfactory for a solution to my work but doesn't address the disappearing text.
The following code is accepted by the editor and calls a php function cog_user which will handle adding the JSON arguments to the url.  They all come from the current wp user.  cog_name is the only part that changes from one post to the next within the page, and is the name of the form :
`href="https://www.cognitoforms.com/QuickPMDocs/{@cog_name, cog_user}"`

**Comment by JoryHogeveen** [comment]
Hi @chafields 
Just curious, why are you "building" your URL like this at all? WordPress has permalinks and you can use those.
I'm inclined to close this as out of scope for Pods support as this is definitely not a use case of how any URL should be created in templates.
Cheers, Jory

**Comment by chafields** [comment]
Hi Joey,

My understanding of permalinks is that they are statiic, while these links
are dynamic.

Have I gotten that wrong?

Thanks,

Chuck

**Comment by JoryHogeveen** [comment]
`{@permalink}` will always point to the object it's for. So no, it's not static, it's depending on the object your are using.
