### ISSUE TITLE
WP Rest API media 

### ISSUE THREAD

**Issue by pborri** [pods-framework/pods#5752]
**Describe the bug**
Custome field in media post will show alway the value false in api /wp-json/wp/v2/media/

**To Reproduce**
1. Go to pods and create a pod with a custom field inside called Latitude of type string
2. Go to media library and put a value in field and save
3. If you open the media the value are present
4. if you call the api /wp-json/wp/v2/media/ the field is present but the value is always false

**Screenshots**

![image](https://user-images.githubusercontent.com/1612536/85174915-ac9bd400-b276-11ea-9d05-af71796a33a5.png)

![image](https://user-images.githubusercontent.com/1612536/85174889-9a219a80-b276-11ea-91c6-6090e80915f3.png)

## Pods Version
Version 2.7.20.1

## WordPress Environment
WordPress 5.4.2 running Bridge theme.
<details>

Site Health Status
The site health check shows critical information about your WordPress configuration and items that require your attention.

1 critical issue

Background updates are not working as expected
Security
5 recommended improvements

You should remove inactive plugins
Security

You should remove inactive themes
Security

Your site is running an older version of PHP (7.2.24-0ubuntu0.18.04.6), which should be updated
Performance

One or more recommended modules are missing
Performance

Your site does not use HTTPS
Security
Passed tests
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment]
Hi @pborri 

I could reproduce your issue and will look into this!

Cheers, Jory

**Comment by JoryHogeveen** [comment]
Hi @pborri 

I've created a patch for this issue. If you are able, please let me know if the patch also works for you!
See PR: #5763 
Direct download link: https://github.com/pods-framework/pods/archive/feature/5752-media-rest-fields.zip

Cheers, Jory

**Comment by pborri** [comment]
Thanks i will try



ing. Paolo Borri
CTO e-GATE s.r.l.
Uff.: +39 0112306001<tel:+39%200112306001>
Cell.: +39 3282923887<tel:+39%203282923887>
eMail/skype for business: paolo.borri@e-gate.it<mailto:paolo.borri@e-gate.it>

Send by mobile device



-------- Messaggio originale --------
Da: Jory Hogeveen <notifications@github.com>
Data: 02/07/20 16:17 (GMT+01:00)
A: pods-framework/pods <pods@noreply.github.com>
Cc: "Paolo PB. Borri" <paolo.borri@e-gate.it>, Mention <mention@noreply.github.com>
Oggetto: Re: [pods-framework/pods] WP Rest API media  (#5752)


Hi @pborri<https://github.com/pborri>

I've created a patch for this issue. If you are able, please let me know if the patch also works for you!
See PR: #5763<https://github.com/pods-framework/pods/pull/5763>
Direct download link: https://github.com/pods-framework/pods/archive/feature/5752-media-rest-fields.zip

Cheers, Jory
