### ISSUE TITLE
Relationship Listing showing &nsbp; instead of an "tab"/"indent"

### ISSUE THREAD

**Issue by papa-pup** [pods-framework/pods#5753]
## Issue Overview
Relationship Listing showing &nsbp; instead of an "tab"/"indent"

![image](https://user-images.githubusercontent.com/59635968/85210497-d803e900-b372-11ea-9946-a0957130f73b.png)

## Expected Behavior
It should be an "tab"/"indent" instead of &nsbp;

## Current Behavior
Screen Shot as shown on Issue Overview.

## Steps to Reproduce (for bugs)
1. Create a NEW Pod - i.e. TEST; with a field with a field type - relationship; and related to "pages"
2. Create a Dummy Page - i.e. Dummy Page 1
3. Create another Dummy Page - i.e. Dummy Page 2 and having a parent page of Dummy Page 1

## Possible Solution
To be investigated and fix

## WordPress Environment

<details>
Debug Information
WordPress Version: 5.4.2
PHP Version: 7.4.3
MySQL Version: 5.6.41
Server Software: LiteSpeed
Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Session Save Path: /opt/alt/php74/var/lib/php/session
Session Save Path Exists: No
Session Save Path Writeable: No
Session Max Lifetime: 1440
Opcode Cache:
Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:
APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 40M
Current Memory Usage: 62.645M
Current Memory Usage (real): 36.500M
Pods Network-Wide Activated: No
Pods Install Location: /home/techacti/WP.ridgewell.my/v2/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: TechActions Customized Theme
Currently Active Plugins:
Address Autocomplete Using Google Place API: 1.0.0
BAW Login/Logout menu: 1.3.3
Code Snippets: 2.14.0
Contact Form 7: 5.1.9
Contact Form 7 Conditional Fields: 1.8.7
Contact Widgets: 1.7.0
Duplicate Page: 4.2
Flamingo: 2.1.1
Force First and Last Name as Display Name: 1.0
Frontier Buttons: 2.5.4
Insert Pages: 3.5.4
Login Screen Manager: 3.5.2
Members: 3.0.8
MimeTypes Link Icons: 3.2.8
Nav Menu Roles: 1.10.1
Peter's Login Redirect: 2.9.7
Pods - Custom Content Types and Fields: 2.7.20.1
Popup Maker: 1.10.2
Post SMTP: 2.0.12
Shortcodes by Angie Makes: 3.46
SiteOrigin CSS: 1.2.8
Wordfence Security: 7.4.8
WP Dashboard Notes: 1.0.9
WP Notification Bars: 1.0.5
WP Reset: 1.80
WP Rollback: 1.7.0
WPS Hide Login: 1.5.6
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.20.1","build":1592683802},"pods":{"1167":{"id":1167,"name":"test","label":"tests","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"test":{"id":1168,"name":"test","label":"test","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"page","sister_id":"","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"test","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"test","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_flamingo_contact_tag":"0","built_in_taxonomies_flamingo_inbound_channel":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_listing_status":"0","built_in_taxonomies_listing_type":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_project_phase":"0","built_in_taxonomies_property_amenity":"0","built_in_taxonomies_property_type":"0","built_in_taxonomies_wcs_collage_cat":"0","built_in_taxonomies_wcs_collage_tag":"0","built_in_taxonomies_wcs_slide_cat":"0","built_in_taxonomies_wcs_slide_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"My Property Listing Template","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

## Workaround or Alternate Solution Until Bug is Addressed

Rollback from latest version (2.70.2.1) to 2.70.2

## Related Issues and/or PRs

Not of any known so far.

**Comment by JoryHogeveen** [comment]
Fixed here: https://github.com/pods-framework/pods/pull/5741
Download: pods.io/latest
