### ISSUE TITLE
Pods-WooCommerce conflict

### ISSUE THREAD

**Issue by jasonw99** [pods-framework/pods#5770]
## Issue Overview
With WooCommerce plugin enabled, cannot create new Pod content types or extend existing content types.

## Expected Behavior
Create new Pods

## Current Behavior
Error: Unable to process request, please try again. 

## Steps to Reproduce (for bugs)
1. Create Pod (or extend existing content type)
2. Receive error.

## Possible Solution
Deactivating WooCommerce plugin eliminates the error.

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 5.4.2

PHP Version: 7.3.18

MySQL Version: 5.7.25

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: ohj_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 18.962M

Current Memory Usage (real): 20.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/customer/www/worldvia.com/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Storefront

Currently Active Plugins:

Ele Custom Skin: 2.2.2
Elementor: 2.9.13
Elementor Pro: 2.10.3
Essential Addons for Elementor: 4.0.4
Gravity Forms: 2.4.18.2
Gravity Forms HubSpot Add-On: 1.3
Max Mega Menu: 2.8
Pods - Custom Content Types and Fields: 2.7.21
SG Optimizer: 5.5.7
WooCommerce: 4.3.0
Wordfence Security: 7.4.9
WP Mail SMTP: 2.1.1
Yoast SEO: 14.5
```
</details>

## Pods Package Export (helpful!)

```
There is no export available, because no pods can be created.
```

## Workaround or Alternate Solution Until Bug is Addressed

Deactivating WooCommerce plugin

**Comment by jasonw99** [comment]
I have tried a fresh WP install with all of the same plugins and discovered that it is not WooCommerce itself that is causing the problem, but the Storefront theme. This is a very common theme, so it still makes sense to figure out what is causing this.

**Comment by jasonw99** [comment]
Very strange. The storefront theme, after install, but before configuration, produces an error when creating a pod. However, AFTER you go through the basic theme configuration, Pods works. 

**BEFORE:**
![image](https://user-images.githubusercontent.com/65768285/87089249-24b94200-c204-11ea-98c3-8f00d6691b0f.png)
- If I create a pod here before configuring the theme, Pod creation FAILS: 
![image](https://user-images.githubusercontent.com/65768285/87089350-4e726900-c204-11ea-9a1a-815f999bb770.png)

AFTER:
Once I have finished the setup, or maybe even just dismissed the notice, pods creation works. Well beyond my skills to determine why, but just sharing what I'm seeing.
![image](https://user-images.githubusercontent.com/65768285/87089614-ad37e280-c204-11ea-8ea1-b6cf7b0ce576.png)

**Comment by jasonw99** [comment]
You may close this issue once you've read it. Thanks.

**Comment by JoryHogeveen** [comment]
Hello @jasonw99 
I tried to reproduce this issue but couldn't.
After installing both Pods and Storefront on a new installation I could add Pods without problems even though I didn't configure Storefront yet.
