### ISSUE TITLE
Notice: Undefined index: error on code after updgrading to 2.7.21

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#5778]
**Describe the bug**
Just updated to latest Pods 2.7.21 and am getting this error. Weirdly the code works on pages but not on custom posts.

The code pulls the image url from an image added via post meta so I can set it as a background image on a page header (code below)

**To Reproduce**
Update to latest Pods

**Expected behavior**

Image header should display with no error

**Error message - details redacted**

Notice: Undefined index: ID in /var/www/html/site.org/wp-content/themes/site-theme/inc/header-image-course.php on line 20

## Pods Version
Please provide the version of Pods you are running:
2.7.21

### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/site.org
wordpress_size: 43.43 MB (45543667 bytes)
uploads_path: /var/www/html/sitey.org/wp-content/uploads
uploads_size: 3.67 MB (3847885 bytes)
themes_path: /var/www/html/site.org/wp-content/themes
themes_size: 12.45 MB (13055756 bytes)
plugins_path: /var/www/html/site.org/wp-content/plugins
plugins_size: 42.41 MB (44473629 bytes)
database_size: 4.25 MB (4456448 bytes)
total_size: 106.22 MB (111377385 bytes)

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: redacted
version: 1.0.0
author: redacted
author_website:
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, custom-header, widgets
theme_path: /var/www/html/site.org/wp-content/themes/site-theme

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.2, author: the WordPress team (latest version: 1.4)

### wp-mu-plugins (1) ###

WP Migrate DB Pro Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (10) ###

Admin Columns: version: 4.1.6, author: AdminColumns.com
CAOS: version: 3.6.0, author: Daan van den Bergh
Contact Form 7: version: 5.2, author: Takayuki Miyoshi
Pods - Custom Content Types and Fields: version: 2.7.20.1, author: Pods Framework Team (latest version: 2.7.21)
W3 Total Cache: version: 0.14.2, author: BoldGrid
Widget Logic: version: 5.10.4, author: WPChef
WP Help: version: 1.7.0, author: Mark Jaquith
WP Migrate DB Pro: version: 1.9.10, author: Delicious Brains
WP Rollback: version: 1.7.0, author: Impress.org
Yoast SEO: version: 14.5, author: Team Yoast

### wp-plugins-inactive (1) ###

WP-Optimize - Clean, Compress, Cache: version: 3.1.2, author: David Anderson, Ruhani Rabin, Team Updraft

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: 2.2.5
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.3.0-1028-aws x86_64
httpd_software: Apache/2.4.29 (Ubuntu)
php_version: 7.2.24-0ubuntu0.18.04.6 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 500M
php_post_max_size: 500M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 8.0.20
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/site.org/wp-content
WP_PLUGIN_DIR: /var/www/html/site.org/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache/2.4.29 (Ubuntu)
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Yes
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: Yes
pods-object-cache-apcu: Yes
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 10.231M
pods-memory-current-usage-real: 6.000M
pods-network-wide: No
pods-install-location: /var/www/html/site.org/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

## Pods Package Export (helpful!)

`{"meta":{"version":"2.7.20.1","build":1594824948},"pods":{"415":{"id":415,"name":"course","label":"Courses","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"course_title_background_image":{"id":416,"name":"course_title_background_image","label":"Title background image","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"course_description":{"id":417,"name":"course_description","label":"Course description","description":"Short description that appears at the top of the page","help":"","class":"","type":"paragraph","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","paragraph_allow_html":"1","paragraph_oembed":"0","paragraph_wptexturize":"1","paragraph_convert_chars":"1","paragraph_wpautop":"1","paragraph_allow_shortcode":"0","paragraph_allowed_html_tags":"strong em a ul ol li b i","paragraph_max_length":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","paragraph_repeatable":"0","unique":"0","paragraph_placeholder":""},"overview_section_heading":{"id":418,"name":"overview_section_heading","label":"Course Overview heading","description":"Only Admin can change this heading","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"default_value":"Course Overview","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"course_overview":{"id":419,"name":"course_overview","label":"Course Overview","description":"","help":"","class":"","type":"wysiwyg","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"course_image":{"id":420,"name":"course_image","label":"Course image","description":"","help":"","class":"","type":"file","weight":4,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"covered_section_heading":{"id":421,"name":"covered_section_heading","label":"What's Covered heading","description":"Only Admin can change this heading","help":"","class":"","type":"text","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"default_value":"What's Covered?","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"whats_covered":{"id":422,"name":"whats_covered","label":"What's Covered?","description":"","help":"","class":"","type":"wysiwyg","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"course_structure_heading":{"id":423,"name":"course_structure_heading","label":"Course structure heading","description":"Only Admin can change this heading","help":"","class":"","type":"text","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"default_value":"Course structure","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"course_structure":{"id":424,"name":"course_structure","label":"Course structure","description":"","help":"","class":"","type":"wysiwyg","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"things_to_consider_heading":{"id":425,"name":"things_to_consider_heading","label":"Things to consider heading","description":"Only Admin can change this heading","help":"","class":"","type":"text","weight":9,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"default_value":"Things to consider before applying ","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"things_to_consider":{"id":426,"name":"things_to_consider","label":"Things to consider before applying","description":"Include required criteria and so on","help":"","class":"","type":"wysiwyg","weight":10,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_allowed_html_tags":""},"course_date_heading":{"id":427,"name":"course_date_heading","label":"Course date heading","description":"Only Admin can change this heading","help":"","class":"","type":"text","weight":11,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"default_value":"Course Dates","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"course_dates":{"id":428,"name":"course_dates","label":"Course dates","description":"","help":"","class":"","type":"pick","weight":12,"pick_object":"post_type","pick_val":"course_date","sister_id":"392","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Course","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"course","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_suite":"1","built_in_taxonomies_qa_level":"1","has_archive_slug":"courses"},"431":{"id":431,"name":"page","label":"Page","description":"","type":"post_type","storage":"meta","object":"page","alias":"","fields":{"page_title_background_image":{"id":432,"name":"page_title_background_image","label":"Title background image","description":"Add a header background image - must be 1440 x 200 pixels. Defaults to no background image, does not apply to the home page","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_suite":"0"}}}`

**Additional context**

Code that is generating the error (error only happens on my custom post type - course - not on Pages where I use the exact same code):

	`$inline_style = '';

	if ( get_post_meta( $post->ID, 'course_title_background_image', false ) ) {

		$title_image = get_post_meta( $post->ID, 'course_title_background_image', false ) ;

		$title_image = wp_get_attachment_url( $title_image[ 'ID' ] );

		$inline_style = 'style="background-image: url(%1s);"';

		$inline_style = sprintf( $inline_style,
			esc_attr( $title_image )
		);

		$entry_header_class = '';

		// the default header is applied from within style.css using the following class

	} else {
		$inline_style = '';
		$entry_header_class = ' default-entry-header';
	}`

**Possible Workaround**

Not thought of one though obviously there might be a better way to code this that avoids the issue.

**Comment by JoryHogeveen** [comment]
Hello @Pezzab 

As you see in the error it's because you try to get a parameter that doesn't exist: `$title_image[ 'ID' ]`.

Please verify `get_post_meta( $post->ID, 'course_title_background_image', false )` is returning anything.

**Comment by Pezzab** [comment]
Here it is working on the one of the custom post pages in question (i.e. the header image is appearing) - I rolled the site back to the previous version of Pods.

The code returns the image URL, when it is working as it is here (this is a production site I can't demo it with the latest Pods where the code breaks).

[Example page](https://qualsafeacademy.org/course/qa-level-3-certificate-in-assessing-vocational-achievement-rqf)

**Comment by JoryHogeveen** [comment]
Hi @Pezzab 

I think I see the error.
You pass `false` which makes the return type an array of objects instead of a single item. as the third parameter to `get_post_meta` but you handle the return type as if it was a single item.
If you change the third parameter to `true` it would work.

The fact that this was working before is actually a bug in Pods that was fixed, see here for more info:
PR: #5661 and prev PR #5578

**Comment by Pezzab** [comment]
Brilliant @JoryHogeveen,

Great spot and thanks for the fix

**Comment by JoryHogeveen** [comment]
No problem!
