### ISSUE TITLE
Viewing custom post type reloads editor view

### ISSUE THREAD

**Issue by GitHubGreg** [pods-framework/pods#5781]
**Describe the bug**
When on the edit page of a custom post, clicking the "View" button (top right) should load the view of it (like it did in version 2.7.20 and prior) but in version 2.7.20.1 it reloads the same edit page.

**To Reproduce**
1. Go to https://www.example.com/wp-admin/admin.php?page=pods-manage-reservation&action=edit&id=1457
2. Click on View Reservation
3. Instead of seeing the View, it reloads the Edit page

**Expected behavior**
It should show the View page for that post

**Screenshots**
![image](https://user-images.githubusercontent.com/7059106/87715431-56d62100-c77b-11ea-8dc6-6310a8f6da43.png)

## Pods Version
2.7.20.1

## WordPress Environment

<details>

`
### wp-core ###

version: 5.3.4
site_language: en_US
user_language: en_US
timezone: UTC
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1083
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/redacted/web/redacted.com/public_html
wordpress_size: loading...
uploads_path: /home/redacted/web/redacted.com/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/redacted/web/redacted.com/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/redacted/web/redacted.com/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
db.php: true

### wp-active-theme ###

name: Divi Child Theme (Divi_Child)
version: Updated for Divi 3+
author: Divi Ready Themes
author_website: https://divireadythemes.com/
parent_theme: Divi (Divi)
theme_features: custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /home/redacted/web/redacted.com/public_html/wp-content/themes/Divi_Child

### wp-parent-theme ###

name: Divi (Divi)
version: 4.4.1 (latest version: 4.5.1)
author: Elegant Themes
author_website: http://www.elegantthemes.com
theme_path: /home/redacted/web/redacted.com/public_html/wp-content/themes/Divi

### wp-themes-inactive (2) ###

Twenty Nineteen: version: 1.4, author: the WordPress team (latest version: 1.6)
Twenty Twenty: version: 1.1, author: the WordPress team (latest version: 1.4)

### wp-mu-plugins (1) ###

Customize the dashboard to hide certain items: version: 1.0, author: Awaken Solutions

### wp-plugins-active (25) ###

Admin Menu Editor Pro: version: 2.4.2, author: Janis Elsts (latest version: 2.11)
Classic Editor: version: 1.5, author: WordPress Contributors
Duplicate Page: version: 4.2, author: mndpsingh287
Easy Theme and Plugin Upgrades: version: 2.0.1, author: Chris Jean
Elegant Themes Updater: version: 1.2, author: Elegant Themes
Enable Media Replace: version: 3.4.1, author: ShortPixel
Force Regenerate Thumbnails: version: 2.0.6, author: Pedro Elsner
Gmail SMTP: version: 1.1.9, author: naa986
Gravity Forms: version: 2.4.19, author: Gravity Forms
Gravity Forms Authorize.Net Add-On: version: 2.8, author: Gravity Forms
Gravity Forms Mailchimp Add-On: version: 4.7, author: Gravity Forms
Head, Footer and Post Injections: version: 3.2.1, author: Stefano Lissa
Hide Related Video Youtube: version: 1.0, author: Trần Hoàng Quốc.
MainWP Child: version: 4.0.7.1, author: MainWP
MainWP Child Reports: version: 2.0.4, author: MainWP
Members: version: 3.0.10, author: MemberPress
Pods - Custom Content Types and Fields: version: 2.7.20, author: Pods Framework Team (latest version: 2.7.21)
Pods Gravity Forms Add-On: version: 1.4.3, author: Pods Framework Team
Query Monitor: version: 3.6.0, author: John Blackbourn
Quick Page/Post Redirect Plugin: version: 5.1.9, author: anadnet
URL Params: version: 2.2, author: Jeremy B. Shapiro
Wordfence Security: version: 7.4.9, author: Wordfence
WP Accessibility: version: 1.7.1, author: Joe Dolson
WP Rocket: version: 3.2.4, author: WP Media
Yoast SEO: version: 14.5, author: Team Yoast

### wp-plugins-inactive (13) ###

All-in-One Video Gallery: version: 2.4.1, author: Team Plugins360
Backup: version: 1.3.9, author: BackupGuard (latest version: 1.4.0)
Elfsight InstaShow: version: 2.0.3, author: Elfsight
Expand Divi: version: 1.6.0, author: Faycal Boutam
Fast Velocity Minify: version: 2.8.9, author: Raul Peixoto
Follow Buttons by AddThis: version: 4.2.6, author: The AddThis Team
Responsive Lightbox & Gallery: version: 2.2.3.1, author: dFactory
Speed Booster Pack: version: 3.8.6, author: Optimocha
TLS 1.2 Compatibility Test: version: 1.0.1, author: Stranger Studios
Ultimate Responsive Image Slider - 3.4.7: version: 3.4.7, author: FARAZFRANK
WooThemes Helper: version: 1.5.2, author: WooThemes
WPML Multilingual CMS: version: 4.2.6, author: OnTheGoSystems
WPtouch Pro: version: 4.3.20, author: WPtouch

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: 2.3.0
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1127.13.1.el7.x86_64 x86_64
httpd_software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.4.8
php_version: 7.3.20 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 2048M
max_input_time: 60
upload_max_size: 200M
php_post_max_size: 200M
curl_version: 7.29.0 NSS/3.44
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.65-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/redacted/web/redacted.com/public_html/wp-content
WP_PLUGIN_DIR: /home/redacted/web/redacted.com/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.4.8
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: Yes
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 89.633M
pods-memory-current-usage-real: 91.000M
pods-network-wide: No
pods-install-location: /home/redacted/web/redacted.com/public_html/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
</details>

## Pods Package Export (helpful!)
Confidential (sorry)

**Additional context**

**Possible Workaround**
Reverted to previous version, 2.7.20, and it works again.

**Comment by JoryHogeveen** [comment]
What are your Pod settings?

**Comment by JoryHogeveen** [comment]
I just notices that you are referring to this as it's a post type, though I believe it's not.. it's an ACT, correct?

**Comment by GitHubGreg** [comment]
Correct, it is an Advanced Content Type. Sorry for the confusion. What Pod settings do you need specifically? The Detail Page URL looks like this:
![image](https://user-images.githubusercontent.com/7059106/87739305-8ef65780-c7ad-11ea-91fa-ef853b68a131.png)

And I am using a custom template to render what appears on that page.

**Comment by JoryHogeveen** [comment]
Hello @GitHubGreg 

I've reproduced your issue and created a patch: #5783 
Could you verify this patch works for you as well?

Cheers, Jory

**Comment by GitHubGreg** [comment]
Works great, thanks @JoryHogeveen !
