### ISSUE TITLE
PODS Blocking Learndash LMS Functionality

### ISSUE THREAD

**Issue by 50inthe314** [pods-framework/pods#5789]
## Issue Overview
When PODS is installed and running, a featureset of Learndash is blocked. Learndash is an Learning Management System for sending out educational series.  Courses are by default organized by:

- Courses
-- Classes
--- Lessons

Where a course can have many classes, lessons, etc. They have a feature for backwards up the tree, where a class can be used by multiple courses, and this is the function that PODS is blocking

## Expected Behavior
On the LearnDash course set-up page, you go to the course builder page, and all of the existing classes and lessons are available in the sidebar to add to the course

## Current Behavior
The classes are not showing unless the PODS plugin is deactivated. 

## Steps to Reproduce (for bugs)
1. Create a new course, and enter course builder
2. Classes and lessons do not show up 
3. Deactivate Pods
4. Classes show up

## WordPress Environment

<details>
WordPress Version: 5.4.2

PHP Version: 7.4.6

MySQL Version: 5.7.29

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 31.705M

Current Memory Usage (real): 24.000M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/devccampus/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: OceanWP Child - Clearent Campus

Currently Active Plugins:

Activity Log: 2.5.2
Admin Menu Editor: 1.9.5
Child Theme Configurator: 2.5.5
Conditional Menus: 1.1.8
Content Control: 1.1.4
Custom Post Type UI: 1.7.4
Download Manager: 5.1.17
Dynamic Visibility for Elementor: 3.0.1
Elementor: 2.9.14
Elementor Pro: 2.10.3
Force Regenerate Thumbnails: 2.0.6
Import and export users and customers: 1.15.7.2
LearnDash LMS: 3.2.2
LearnDash LMS - Notifications: 1.4.0
LearnDash LMS - Zapier Integration: 2.1.0
LearnDash ProPanel: 2.1.3.1
MailPoet 3 (New): 3.47.10
Manage Notification E-mails: 1.5.1
Media Library Organizer: 1.1.5
miniOrange SSO using SAML 2.0: 12.0.1
Ocean Extra: 1.6.4
Ocean Stick Anything: 1.0.4
Page Links To: 3.3.4
Pods - Custom Content Types and Fields: 2.7.21
Rank Math SEO: 1.0.45
Related Posts By Taxonomy: 2.7.3
Relevanssi: 4.7.2.1
Remove Dashboard Access: 1.1.3
Search & Filter - Elementor Extension: 1.0.4
Search & Filter Pro: 2.5.1
Search Exclude: 1.2.5
Sidebar Manager: 1.1.3
Site Kit by Google: 1.12.0
Tin Canny Reporting for LearnDash: 3.4.3
Ultimate Member: 2.1.6
Ultimate Member - Terms & Conditions: 2.1.2
Ultimate Member - User Bookmarks: 2.0.4
Uncanny Toolkit for LearnDash: 3.3.1
User Role Editor: 4.55.1
Wicked Folders: 2.17.2
WPDM - Box.com Explorer: 1.2.1
WPDM - Button Templates: 1.3.0
WPDM - Gutenberg Blocks: 1.3.9
WPDM - Import Filebase Data: 1.0
WPDM - Page Template: 1.1
WPForms Lite: 1.6.1
We need YOU in 2020 and beyond
Things are changing for Pods and we want you to be a part of it! Our goal is to be fully funded by users like you. Help us reach our goal of 200 recurring donors in 2020.

Learn More

</details>

## Pods Package Export (helpful!)

{"meta":{"version":"2.7.21","build":1595872989},"pods":{"62":{"id":62,"name":"audience","label":"Audiences","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Audience","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"audience","query_var":"0","sort":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor_font":"0","built_in_post_types_elementor_icons":"0","built_in_post_types_elementor_library":"0","built_in_post_types_oceanwp_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"1","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"1","read_all":"1","write_all":"1","built_in_post_types_resource":"1","built_in_post_types_bsf-sidebar":"0","built_in_post_types_groups":"0","built_in_post_types_ld-notification":"0","built_in_post_types_search-filter-widget":"0","built_in_post_types_sfwd-assignment":"0","built_in_post_types_sfwd-certificates":"0","built_in_post_types_sfwd-courses":"1","built_in_post_types_sfwd-essays":"0","built_in_post_types_sfwd-lessons":"0","built_in_post_types_sfwd-question":"0","built_in_post_types_sfwd-quiz":"0","built_in_post_types_sfwd-topic":"0","built_in_post_types_sfwd-transactions":"0","built_in_post_types_um_form":"0","built_in_post_types_wpdmpro":"1","built_in_post_types_mailpoet_page":"0","built_in_post_types_sfwd-zapier":"0"},"249":{"id":249,"name":"format","label":"Formats","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Format","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"format","query_var":"0","sort":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor_font":"0","built_in_post_types_elementor_icons":"0","built_in_post_types_elementor_library":"0","built_in_post_types_groups":"0","built_in_post_types_ld-notification":"0","built_in_post_types_oceanwp_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_resource":"1","built_in_post_types_search-filter-widget":"0","built_in_post_types_sfwd-assignment":"0","built_in_post_types_sfwd-certificates":"0","built_in_post_types_sfwd-courses":"0","built_in_post_types_sfwd-essays":"0","built_in_post_types_sfwd-lessons":"0","built_in_post_types_sfwd-question":"0","built_in_post_types_sfwd-quiz":"0","built_in_post_types_sfwd-topic":"0","built_in_post_types_sfwd-transactions":"0","built_in_post_types_um_form":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"1","read_all":"0","write_all":"0","built_in_post_types_bsf-sidebar":"0","built_in_post_types_um_directory":"0","built_in_post_types_wpdmpro":"1"},"104":{"id":104,"name":"gate","label":"Gates","description":"Gated or Ungated Content","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Gate","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"gate","query_var":"0","sort":"0","built_in_post_types_course":"1","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor_font":"0","built_in_post_types_elementor_icons":"0","built_in_post_types_elementor_library":"0","built_in_post_types_oceanwp_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_resource":"1","built_in_post_types_download":"1"},"1640":{"id":1640,"name":"post","label":"Post","description":"","type":"post_type","storage":"meta","object":"post","alias":"","fields":[],"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_product":"1","built_in_taxonomies_topic":"0","built_in_taxonomies_audience":"1"},"322":{"id":322,"name":"product","label":"Products","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Product","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"product","query_var":"0","sort":"0","built_in_post_types_bsf-sidebar":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor_font":"0","built_in_post_types_elementor_icons":"0","built_in_post_types_elementor_library":"0","built_in_post_types_groups":"0","built_in_post_types_ld-notification":"0","built_in_post_types_oceanwp_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"1","built_in_post_types_resource":"1","built_in_post_types_search-filter-widget":"0","built_in_post_types_sfwd-assignment":"0","built_in_post_types_sfwd-certificates":"0","built_in_post_types_sfwd-courses":"1","built_in_post_types_sfwd-essays":"0","built_in_post_types_sfwd-lessons":"0","built_in_post_types_sfwd-question":"0","built_in_post_types_sfwd-quiz":"0","built_in_post_types_sfwd-topic":"0","built_in_post_types_sfwd-transactions":"0","built_in_post_types_um_form":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"1","read_all":"1","write_all":"1","built_in_post_types_wpdmpro":"1","built_in_post_types_mailpoet_page":"0","built_in_post_types_sfwd-zapier":"0"},"18":{"id":18,"name":"resource","label":"Resources","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Resource","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"1","capability_type":"post","capability_type_custom":"course","capability_type_extra":"1","has_archive":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"1","supports_comments":"1","supports_revisions":"1","supports_page_attributes":"1","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_elementor_library_category":"0","built_in_taxonomies_elementor_library_type":"0","built_in_taxonomies_link_category":"1","built_in_taxonomies_post_tag":"1","built_in_taxonomies_wpforms_log_type":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"1","read_all":"0","write_all":"0","menu_icon":"dashicons-edit","rewrite_custom_slug":"resource","built_in_taxonomies_audience":"1","built_in_taxonomies_elementor_font_type":"0","built_in_taxonomies_gate":"1","built_in_taxonomies_ld_course_category":"0","built_in_taxonomies_ld_course_tag":"0","built_in_taxonomies_ld_lesson_category":"0","built_in_taxonomies_ld_lesson_tag":"0","built_in_taxonomies_ld_topic_category":"0","built_in_taxonomies_ld_topic_tag":"0","built_in_taxonomies_format":"1","built_in_taxonomies_product":"1","built_in_taxonomies_dlm_download_category":"0","built_in_taxonomies_dlm_download_tag":"0","built_in_taxonomies_mlo-category":"0","built_in_taxonomies_topic":"0"},"544":{"id":544,"name":"topic","label":"Topics","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Topic","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"topic","query_var":"0","sort":"0","built_in_post_types_bsf-sidebar":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_elementor_font":"0","built_in_post_types_elementor_icons":"0","built_in_post_types_elementor_library":"0","built_in_post_types_groups":"0","built_in_post_types_ld-notification":"0","built_in_post_types_oceanwp_library":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_resource":"0","built_in_post_types_search-filter-widget":"0","built_in_post_types_sfwd-assignment":"0","built_in_post_types_sfwd-certificates":"0","built_in_post_types_sfwd-courses":"1","built_in_post_types_sfwd-essays":"0","built_in_post_types_sfwd-lessons":"0","built_in_post_types_sfwd-question":"0","built_in_post_types_sfwd-quiz":"0","built_in_post_types_sfwd-topic":"0","built_in_post_types_sfwd-transactions":"0","built_in_post_types_um_form":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpdmpro":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"1","read_all":"1","write_all":"1","built_in_post_types_mailpoet_page":"0","built_in_post_types_sfwd-zapier":"0"},"1517":{"id":1517,"name":"wpdmcategory","label":"Wpdmcategory","description":"","type":"taxonomy","storage":"meta","object":"wpdmcategory","alias":"","fields":[],"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"1","read_all":"0","write_all":"0"},"1518":{"id":1518,"name":"wpdmpro","label":"Wpdmpro","description":"","type":"post_type","storage":"meta","object":"wpdmpro","alias":"","fields":[],"show_in_menu":1,"built_in_taxonomies_product":"1","built_in_taxonomies_topic":"0","built_in_taxonomies_audience":"1"}}}

## Workaround or Alternate Solution Until Bug is Addressed
Manually duplicate courses.

**Comment by 50inthe314** [comment]
I do have a dev account I can give access too for more troubleshooting

**Comment by sc0ttkclark** [comment]
Sent you a message on our Slack to further discuss troubleshooting access.

**Comment by sc0ttkclark** [comment]
After reviewing your staging site (thanks for that!) and the LearnDash code itself, I've determined there are a couple of things happening here:

* Your site has a Custom Taxonomy you created with Pods called "format"
* LearnDash is (seemingly unnecessarily) sending the "format" along to the `WP_Query` instances for `learndash_builder_selector_pager()` methods (in various locations)
* WP_Query then sees you have a taxonomy "format" (format => json) and sees the argument LearnDash sent called "format" and treats the query like the intention was to limit posts by ones with the term "json" for the "format" taxonomy

So this can be easily worked around by not using the same taxonomy name that conflicts there. I would recommend you contact LearnDash support and send them this comment link so they can stop accidentally passing that argument to WP_Query in a future version. If they need it, they should namespace their custom query var arguments as necessary to prevent conflicts from people like you building cool stuff.
