### ISSUE TITLE
Export Issues / Improvements

### ISSUE THREAD

**Issue by digi-bits** [pods-framework/pods#5790]
## Issue Overview

My client wants to do periodic exports of Pods entries to CSV but the export only outputs the first 25 posts regardless of any filters etc.

## Expected Behavior

 

I would expect it to export whatever posts are showing (via filters, different pages etc) or more helpful, would be having options to change what gets exports including being able to select posts using the filters (same as advanced filters), date ranges, number of posts etc.

## WordPress Environment

<details>
```
WordPress Version: 5.4.2

PHP Version: 7.3.18-1+ubuntu18.04.1+deb.sury.org+1

MySQL Version: 5.7.29

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: k4_

WP Multisite Mode: No

WP Memory Limit: 512M

Current Memory Usage: 43.960M

Current Memory Usage (real): 2.000M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/aiaminnesota/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: AIAMN

Currently Active Plugins:

Admin Menu Editor: 1.9.5
Advanced Custom Fields: 5.8.12
Advanced Custom Fields: Flexible Content Field: 2.1.0
Advanced Custom Fields: Nav Menu Field: 2.0.0
Advanced Custom Fields: Repeater Field: 2.1.0
Breadcrumb NavXT: 6.5.0
Classic Editor: 1.5
Device Detect: 1.4.1
Exports and Reports: 0.8.5
Gravity Forms: 2.4.19
Gravity PDF: 5.3.1
iThemes Security: 7.4.1
Mailgun: 1.7.1
NextGEN Gallery: 3.3.6
Pods - Custom Content Types and Fields: 2.7.21
Post Duplicator: 2.20
Preserved HTML Editor Markup Plus: 1.5.4
Raw HTML: 1.6.3
Relevanssi: 4.7.2.1
SEO Ultimate: 7.6.5.9
Toolset Types: 1.9
WordPress Importer: 0.7```
</details>

**Comment by JoryHogeveen** [comment]
Hello @digi-bits 
I don't know of any export features in Pods other than the migrate packages component.
Are you sure you are exporting posts with Pods?
Cheers, Jory

**Comment by digi-bits** [comment]
@JoryHogeveen thanks for the quick response.

I believe they are through Pods. I only see the button on Pods related post types and I turned off any plugins that might have an export feature to see if any of those could be the issue. 
 
The url for the button points to /wp-admin/admin.php?page=pods-manage-misc_registration&action_bulk=export

Here's a screen shot of the button and the page it takes me to. I can provide more info or sample data privately due to personal info in the reports.

![pods-issue](https://user-images.githubusercontent.com/9203455/88689571-3d5c9f80-d0c0-11ea-9d03-b459cdb72a84.jpg)

**Comment by sc0ttkclark** [comment]
Try the bulk checkbox on the left and then from Bulk Actions try choosing Export.

**Comment by sc0ttkclark** [comment]
We'll have a look at this further to improve the exporting screens, it's something we can do for any pod but right now it's limited to Advanced Content Types. I have that as a future Friends of Pods add-on in my planning schedule at the moment.

**Comment by digi-bits** [comment]
That works better, it gets me to the same checkbox screen it at least exports what's showing on the page (if filtered etc) but still has the issue of only exporting up to 25 items and I can't find/change the number of posts showing like under the screen options on WP pages/posts.

I can do custom exports via the database right now so I can get the client what they need, they just can't do it themselves.

**Comment by sc0ttkclark** [comment]
You should try my other plugin https://wordpress.org/plugins/exports-and-reports/ which could easily do this and more.

You give it a SQL query and it will create the interfaces, offer up various export options (including PDF) and handles exactly what you're asking for here. The Friends of Pods add-on I mentioned would help bring these kinds of features into Pods itself.

**Comment by digi-bits** [comment]
Thanks. It looks like one of the previous developers actually had it installed and had a few reports setup. That should save me from generating the reports manually.

Based on the fact the client never knew these reports existed or didn't use them, my guess is they would prefer having a simpler, less or non-technical way to select and export the specific data they're looking for in different situations.  I think your add-on would fill that need when it's completed.

I should be good for now but will keep the issue open as a bug/improvement item or it can be closed out.

**Comment by sc0ttkclark** [comment]
Closing for backlog

**Comment by ssimo3lsuhsc** [comment]
If you use "Bulk Actions >> Export" on a page other than page 1, you will get a CSV with no records.
