### ISSUE TITLE
Database error on relationships

### ISSUE THREAD

**Issue by tarabyte12** [pods-framework/pods#5795]
Attempting to add a new post into a pod I receive the following error:

Database Error; SQL: SELECT item_id, related_item_id, related_field_id FROM `xwb_podsrel` WHERE `field_id` = 8342 AND `item_id` IN ( 8367 ) ORDER BY `weight`; Response: Table 'db6xw4xr58a7u4.xwb_podsrel' doesn't exist

**Comment by JoryHogeveen** [comment]
It seems your installation wasn't complete. Could you try to reinstall Pods?

**Comment by tarabyte12** [comment]
Hey Jory- No luck with deleting pods and reinstalling. 

Still receiving a similar message when attempting to add a new post into a pod:

Database Error; SQL: SELECT item_id, related_item_id, related_field_id FROM `xwb_podsrel` WHERE `field_id` = 8342 AND `item_id` IN ( 8550 ) ORDER BY `weight`; Response: Table 'db6xw4xr58a7u4.xwb_podsrel' doesn't exist

**Comment by sc0ttkclark** [comment]
Pods 2.8.9 will introduce a new option to recreate tables when they are missing via 2112b41ca6463f7f0d37b1c66202bc52b851af9d

![Screen Shot 2022-01-21 at 4 23 37 PM](https://user-images.githubusercontent.com/709662/150608186-5b8f54de-26f0-4830-86b4-e669d4ad4d50.png)
