### ISSUE TITLE
File Field: Edit link no longer works after Publish

### ISSUE THREAD

**Issue by codente** [pods-framework/pods#5796]
## Issue Overview
If you use a File field and turn on the edit link, that link now takes you to the Posts list instead of editing that item.

## Expected Behavior
Is that it takes you to a page to edit the file/media.

This: https://share.getcloudapp.com/kpubQ2xZ

## Current Behavior
Now the link takes you to the WP Admin posts list.

Example: https://share.getcloudapp.com/bLuRr97O

## Steps to Reproduce (for bugs)
1. Add new pod, add file field with Edit Link turned on in Additional Settings.
2. Add a new post to the CPT you just created and add a file
3. Before you save the post, the link might work so try the edit link to edit the file.
4. Save/Publish the post and then (even without leaving the same page) try to edit the image again and now you are taken to the WP Admin Posts list

## Possible Solution
It looks like this changed in version 2.7.20.1 from my testing.

## WordPress Environment
```
WordPress Version: 5.4.2

PHP Version: 7.4.6

MySQL Version: 5.5.5

Server Software: nginx/1.19.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: Yes
Memcached: Yes
Redis: Yes
WPDB Prefix: test_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 5.408M

Current Memory Usage (real): 2.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/test/webapps/test/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: GeneratePress

Currently Active Plugins:

Beaver Builder Plugin (Pro Version): 2.3.2.7
Pods - Custom Content Types and Fields: 2.7.20.1
WP Downgrade | Specific Core Version: 1.2.1
WP Rollback: 1.7.1
```

## Pods Package Export (helpful!)

Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
[pods-5796.txt](https://github.com/pods-framework/pods/files/5030975/pods-5796.txt)

## Workaround or Alternate Solution Until Bug is Addressed
Downgrade to 2.7.20

## Related Issues and/or PRs
Couldn't find any. Sorry if I missed it!

**Comment by lhberg** [comment]
I noticed that the links look like e.g. this: /wp-admin/post.php?post=43569**&#038;**action=edit – i.e. the ampersand character is replaced by its encoded version. When I copy the link to a new browser tab and replace &#038; by & the link works.

**Comment by lhberg** [comment]
I noticed that the links look like e.g. shown in the attached screenshot: i.e. the ampersand character is replaced by its encoded version. 
![2020-08-17_16-05-59](https://user-images.githubusercontent.com/52177795/90405106-a0c86480-e0a3-11ea-9507-e639a41c7109.jpg)
