### ISSUE TITLE
Issue with default search query

### ISSUE THREAD

**Issue by wowdigitalinc** [pods-framework/pods#5797]
## Issue Overview
I’ve just been working on a client site and upgraded them to the latest version of PODS as well as a number of other updates, including WP core.

On one of the pages, I have a shortcode like this:

[pods name=”members” limit=”20″ pagination=”true” pagination.type=”advanced” orderby=”last_name.meta_value, first_name.meta_value” where=”last_name.meta_value like ‘{@get.alpha}%'”]

The search seems to not return results because of the where statement in the query.  I think it's looking for ?alpha=   but it's not in the URL so nothing is being returned.

## Expected Behavior
This works in 2.7.15.
Previously, when you went to the page, it would show all the member results, and if you went to the page with ?alpha=C (for example) it would show only those members with the last name starting with C.

So what should happen is when you go to 
https://domain.com/membership/
You would see the full list of all members
and when you go to
https://domain.com/membership/?alpha=C
you would see the list of all members with the last name starting with C. 

## Current Behavior
This is for any version of pods 2.7.16.1 or higher.
The pages with the alpha= are working fine. However, when you first go to the page (the all page) is showing as blank – none of the entries appear.

## Steps to Reproduce (for bugs)

1. I can send you the link privately, it is a Live URL so for testing I would need to do it at the same time to show you and then downgrade the PODS plugin.
2. I've deactivated all the plugins and that doesn't seem to make a difference.

## Possible Solution
Unsure

## WordPress Environment

<details>
Debug Information
WordPress Version: 5.4.2

PHP Version: 7.4.8

MySQL Version: 10.3.23

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea-php72

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_domain_

WP Multisite Mode: No

WP Memory Limit: 256M

Current Memory Usage: 84.825M

Current Memory Usage (real): 27.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/domain/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Divi Child Theme

Currently Active Plugins:

All-in-One WP Migration: 7.25
BackWPup: 3.7.1
BE Subpages Widget: 1.7
Bloom: 1.3.10
Caldera Forms: 1.9.2
CMS Tree Page View: 1.6.1
CPT Layout Injector: 4.9.1
Display Posts: 3.0.2
Divi - Disable Premade Layouts: 1.2.2
Divi Booster: 3.2.8
Duplicate Page: 4.2
Easy Updates Manager: 9.0.3
Enable Media Replace: 3.4.1
Google Analytics for WordPress by MonsterInsights: 7.12.0
Imsanity: 2.6.0
InfiniteWP - Client: 1.9.4.6
Jetpack by WordPress.com: 8.8
LiteSpeed Cache: 3.2.4
Open in New Window Plugin: 2.7
Pods - Custom Content Types and Fields: 2.7.15
Pods Caldera Forms Processor: 1.0.0
Redirection: 4.8
Relevanssi: 4.7.2.1
Remove Yoast SEO Comments: 3.1
Search Layout Injector: 2.9.1
Surbma | Divi Remove Project CPT: 2.0
TinyMCE Advanced: 5.4.0
User Switching: 1.5.5
Wordfence Security: 7.4.10
WP-PageNavi: 2.93.3
WP Rollback: 1.7.1
Yoast SEO: 14.7
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Hello @wowdigitalinc 

No idea why this worked before. Could you share the SQL it outputs when adding `pods_debug_sql=1` to the url?

Cheers, Jory

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
Doing research I found this commit: https://github.com/pods-framework/pods/commit/798293ac86fc877093c3be5a107993ad33b8876f
Why is the default fallback two double quotes? `""` ?

**Comment by sc0ttkclark** [comment]
Looks like a mistake, I don't think we need the double quote default there.

**Comment by JoryHogeveen** [comment]
See related commit (edit).
Looks like the double quotes fixed one issue but created a new one.

**Comment by JoryHogeveen** [comment]
@wowdigitalinc 
Could you test PR #5813 and let me know if this fixes your issue as well?
