### ISSUE TITLE
console log error

### ISSUE THREAD

**Issue by kbxian** [pods-framework/pods#5812]
<img width="1276" alt="Screen Shot 2020-08-18 at 10 58 37 pm" src="https://user-images.githubusercontent.com/19197370/90534967-f89ec280-e1ac-11ea-9d32-b69379528832.png">

I’m seeing the below errors in my /wp-admin console.log:
[Error] Failed to load resource: the server responded with a status of 404 () (pods.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (pods-dfv.min.js.map, line 0)
Is there a way to get rid of these errors?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Hello @kbxian 
Do you have debug enabled?
Cheers, Jory

**Comment by JoryHogeveen** [comment]
Probably related: https://stackoverflow.com/questions/34593439/safari-console-show-error-when-sourcemap-is-unavailable

**Comment by JoryHogeveen** [comment]
@nicdford Maybe better to config scss to omit the source maps on distribution files?

**Comment by nicdford** [comment]
Hmmm I'll have to look into this. I'm not sure off the top of my head why we'd be pulling in a source map from a src folder, that seems odd.

**Comment by JoryHogeveen** [comment]
Browsers do this automatically due to this line: `/*# sourceMappingURL=../src/sourcemaps/pods.css.map */`

https://github.com/pods-framework/pods/blob/main/ui/styles/dist/pods.css#L3

**Comment by sc0ttkclark** [comment]
No longer an issue
