### ISSUE TITLE
https://pods.io/register-account/ Captcha Bug

### ISSUE THREAD

**Issue by irro** [pods-framework/pods#5815]
**Describe the bug**
Cannot register a new account on pods.io with chrome or IE.

I wanted to help with documentation as I learn Pods as that is the best way for me to retain knowledge but I cannot create an account because there is no captcha image to enter in the security check. 

**To Reproduce**
1. Go to https://pods.io/register-account/
2. Click on Submit
3. Receive Error

**Expected behavior**
An email to allow me to create an account

**Additional context**
I deleted the rest because it's a simple problem.

**Comment by sc0ttkclark** [comment]
Just seeing this now @irro, did you get it sorted out?

**Comment by irro** [comment]
I was told the Captcha was down by default as a way to prevent anyone from
signing up.  I hope you're well!

**Comment by sc0ttkclark** [comment]
I'm not sure what happened there, the captcha looks like it's working but it relies on the Google Captcha script and how that works. It might have had an outage issue around that time you tried.

I'm doing well, thanks! Can you ping me friends@ pods.io when you can? I'd like to get your GitHub sponsorship value listed under the Friends list for you but didn't have your contact information / website / etc to reference.
