### ISSUE TITLE
JS Console log error

### ISSUE THREAD

**Issue by kbxian** [pods-framework/pods#5822]
<img width="1280" alt="Screen Shot 2020-08-30 at 12 39 29 am" src="https://user-images.githubusercontent.com/19197370/91641762-51961280-ea59-11ea-927b-413a7e618b4e.png">

## Issue Overview
This plugin is suspected to have a clash with some of the plugins on my website. Some of my JS functions on the website are not working. Once deactivated, the functions are working again.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by sc0ttkclark** [comment]
Fixed in Pods 2.7.23 and 2.8.

Changelog: Removed sourcemaps from our CSS/JS build process which were not distributed and caused annoying 404 notices from browsers.
