### ISSUE TITLE
Small z-index issue in pods-form-ui-row-name-file-type-tax

### ISSUE THREAD

**Issue by MDGDesign** [pods-framework/pods#5830]
Hi guys,

**Describe the bug**
The select element box seems to have a z-index problem. This only occurs when two select boxes are one above the other following normal DOM.
When clicking the first select box I can see the placeholder text from the other one below.

To correct rapidly the issue I added some css:
```
.pods-pick-values * {
  z-index: 1;
}
```

**To Reproduce**
1. Place two select box one after the other,
2. Click on the first one to open it,
3. You will se the placeholder text from the second select box

**Screenshots**
![Capture](https://user-images.githubusercontent.com/22817419/93108733-28909700-f681-11ea-8e89-ce4a89a23863.PNG)

## Pods Version
 2.7.22

## WordPress Environment

<details>

`
### wp-core ###

version: 5.5.1
site_language: fr_FR
user_language: fr_FR
timezone: America/Toronto
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: closed
environment_type: production
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/...
wordpress_size: 100,80 Mo (105696052 bytes)
uploads_path: /home/.../wp-content/uploads
uploads_size: 184,97 Mo (193955387 bytes)
themes_path: /home/.../wp-content/themes
themes_size: 44,08 Mo (46225379 bytes)
plugins_path: /home/.../wp-content/plugins
plugins_size: 111,06 Mo (116453043 bytes)
database_size: 27,95 Mo (29310976 bytes)
total_size: 468,87 Mo (491640837 bytes)

### wp-active-theme ###

name: Divi child (...)
version: 1.0.0
author: ...
author_website: https://....
parent_theme: Divi (Divi)
theme_features: core-block-patterns, post-thumbnails, custom-background, automatic-feed-links, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /home/.../wp-content/themes/...
auto_update: Désactivé

### wp-parent-theme ###

name: Divi (Divi)
version: 4.6.1
author: Elegant Themes
author_website: http://www.elegantthemes.com
theme_path: /home/.../wp-content/themes/Divi
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.5, author: the WordPress team,Mises à jour auto désactivées

### wp-plugins-active (17) ###

Classic Editor: version: 1.6, author: WordPress Contributors, Mises à jour auto désactivées
Contact Form 7: version: 5.2.2, author: Takayuki Miyoshi, Mises à jour auto désactivées
Contact Form Entries: version: 1.1.4, author: CRM Perks, Mises à jour auto désactivées
Pods - Custom Content Types and Fields: version: 2.7.22, author: Pods Framework Team, Mises à jour auto désactivées
Safe SVG: version: 1.9.9, author: Daryll Doyle, Mises à jour auto désactivées
WooCommerce: version: 4.5.1, author: Automattic, Mises à jour auto désactivées
WooCommerce Multilingual: version: 4.10.2, author: OnTheGoSystems, Mises à jour auto désactivées
WordPress Importer: version: 0.7, author: wordpressdotorg, Mises à jour auto désactivées
WP-PageNavi: version: 2.93.3, author: Lester 'GaMerZ' Chan, Mises à jour auto désactivées
WP All Export: version: 1.2.7, author: Soflyy, Mises à jour auto désactivées
WP All Import: version: 3.5.4, author: Soflyy, Mises à jour auto désactivées
WP All Import - WooCommerce Add-On: version: 1.4.6, author: Soflyy, Mises à jour auto désactivées
WPML All Import: version: 2.1.1, author: OnTheGoSystems, Mises à jour auto désactivées
WPML Multilingual CMS: version: 4.3.19, author: OnTheGoSystems, Mises à jour auto désactivées
WPML String Translation: version: 3.0.14, author: OnTheGoSystems, Mises à jour auto désactivées
WPML Translation Management: version: 2.9.11, author: OnTheGoSystems, Mises à jour auto désactivées
Yoast Duplicate Post: version: 3.2.5, author: Enrico Battocchi & Team Yoast, Mises à jour auto désactivées

### wp-plugins-inactive (2) ###

WP Mail SMTP: version: 2.3.1, author: WPForms, Mises à jour auto désactivées
Yoast SEO: version: 14.9, author: Team Yoast, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1802
imagemagick_version: ImageMagick 7.0.10-10 Q16 x86_64 2020-07-09 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 8 Go
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 8 Go
	imagick::RESOURCETYPE_MEMORY: 4 Go
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.10 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 0
memory_limit: 256M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.2.33-MariaDB-cll-lve
client_version: 10.2.33-MariaDB

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/.../wp-content
WP_PLUGIN_DIR: /home/.../wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
pods-session-save-path: /opt/alt/php74/var/lib/php/session
pods-session-save-path-exists: Oui
pods-session-save-path-writable: Oui
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Non
pods-opcode-cache-memcached: Non
pods-opcode-cache-opcache: Non
pods-opcode-cache-redis: Non
pods-object-cache-apc: Non
pods-object-cache-apcu: Non
pods-object-cache-memcache: Non
pods-object-cache-memcached: Non
pods-object-cache-redis: Non
pods-memory-current-usage: 106,985M
pods-memory-current-usage-real: 57,000M
pods-network-wide: Non
pods-install-location: /home/..../wp-content/plugins/pods/
pods-developer: Non
pods-tableless-mode: Non
pods-light-mode: Non
pods-strict: Non
pods-allow-deprecated: Oui
pods-api-cache: Oui
pods-shortcode-allow-evaluate-tags: Non

`
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```
{"meta":{"version":"2.7.22","build":1600099696},"pods":{"1142":{"id":1142,"name":"product_file","label":"Fichiers de produits","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"file":{"id":1143,"name":"file","label":"Fichier","description":"Le fichiers à lier au produit","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"browse","file_edit_title":"1","file_show_edit_link":"1","file_linked":"1","file_limit":"0","file_restrict_filesize":"10MB","file_type":"any","file_allowed_extensions":"pdf, step, dwg, xls, xlsx, zip","file_field_template":"rows","file_add_button":"Ajouter un nouveau fichier","file_modal_title":"Attacher un nouveau fichier","file_modal_add_button":"Ajouter le nouveau fichier","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","oembed_enabled_providers_hulucom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"},"file_type_tax":{"id":1144,"name":"file_type_tax","label":"Type de fichier","description":"Le type de fichier que celui-ci représente","help":"","class":"","type":"pick","weight":1,"pick_object":"taxonomy","pick_val":"file_types_tax","sister_id":"","pick_custom":"Instructions\nCatalogue\nBrochure\nCertificats \/ Rapport de test","required":"0","oembed_enabled_providers_hulucom":"0","pick_format_type":"single","pick_format_single":"autocomplete","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"0","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"related_products":{"id":1145,"name":"related_products","label":"Produits reliés","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"product","sister_id":"1146","required":"0","oembed_enabled_providers_hulucom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","future","draft","pending","wc-checkout-draft"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"languages":{"id":1179,"name":"languages","label":"Langues","description":"La langue dans laquelle le fichier est disponible","help":"","class":"","type":"pick","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"EN\nFR","required":"0","oembed_enabled_providers_hulucom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Fichier de produit","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"product_file","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_product_cat":"0","built_in_taxonomies_product_shipping_class":"0","built_in_taxonomies_product_tag":"0","built_in_taxonomies_product_type":"0","built_in_taxonomies_product_visibility":"0","built_in_taxonomies_project_category":"0","built_in_taxonomies_project_tag":"0","built_in_taxonomies_translation_priority":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","enable_i18n":{"fr_FR":"0"},"menu_location_custom":"edit.php?post_type=product","menu_name":"Fichiers de produits","menu_name_fr_FR":"Fichiers de produits","menu_icon":"dashicons-media-document","name_admin_bar":"Fichiers de produits","name_admin_bar_fr_FR":"Fichiers de produits","built_in_taxonomies_file_types_tax":"0"},"1141":{"id":1141,"name":"product","label":"Product","description":"","type":"post_type","storage":"meta","object":"product","alias":"","fields":{"related_files":{"id":1146,"name":"related_files","label":"Fichiers reliés","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"product_file","sister_id":"1145","required":"0","oembed_enabled_providers_hulucom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":"1","pick_taggable":"1","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish","future","draft","wc-checkout-draft"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":1,"pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","enable_i18n":{"fr_FR":"0"},"built_in_taxonomies_file_types_tax":"0"},"1176":{"id":1176,"name":"file_types_tax","label":"Types de fichier","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Type de fichier","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"file_types_tax","query_var":"0","sort":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_et_body_layout":"0","built_in_post_types_et_footer_layout":"0","built_in_post_types_et_header_layout":"0","built_in_post_types_et_template":"0","built_in_post_types_et_theme_builder":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_product":"0","built_in_post_types_product_variation":"0","built_in_post_types_project":"0","built_in_post_types_shop_coupon":"0","built_in_post_types_shop_order":"0","built_in_post_types_shop_order_refund":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpcf7_contact_form":"0","built_in_post_types_attachment":"0","menu_location":"submenu","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","enable_i18n":{"fr_FR":"0"},"menu_location_custom":"\/edit.php?post_type=product","built_in_post_types_product_file":"0"}}}

**Possible Workaround**
CSS correction : 
.pods-pick-values * {
  z-index: 1;
}

**Comment by JoryHogeveen** [comment]
@sc0ttkclark since this is 2.7 related and an issue from 2020, can we close this?

**Comment by sc0ttkclark** [comment]
Yeah I believe this was fixed in the replacement of the select library for DFV.
