### ISSUE TITLE
Relationship Field not displaying values in Post Editor

### ISSUE THREAD

**Issue by lswaterfield** [pods-framework/pods#5831]
## Issue Overview

Multi-select bi-directional relationship field is saving data to DB but not showing that data on the post editor.

I have a multi-select bi-directional relationship field on a CPT. This field is called "employees" and links to users.
There is a corresponding single-select bi-directional relationship field on Users. This field is called "company".
When I pick the users for a post's "employees" field and save the post, the metadata is stored in the DB as expected, however when I go back to re-edit that post, the "employees" field is blank (like it hasn't saved).
Oddly, the user profile field "company" DOES display the correct info (the post name).

## Expected Behavior

I would expect the values set for the "employees" field to remain even when re-editing the post.

## Current Behavior

The 'employees' field values are saved to DB but do not display when re-editing the post, so the field looks blank.
The 'company' field value is saved and DOES display correctly on the user profile editor.

![updating-field](https://user-images.githubusercontent.com/71390469/93347496-0dfb2100-f82d-11ea-90a3-64c1d536f779.png)

## Steps to Reproduce (for bugs)

1. Create CPT 'company'
2. Create multi-select bi-directional relationship field for 'company' CPT, called 'employees'. Related to Users.
3. Create single-select bi-directional relationship field for users, called 'company'. Related to 'company' CPT.
4. Create a 'company' post, and choose 4 users for the 'employees' field. Save
5. Check again - The field is now blank for me. Unexpected behaviour.
6. Check user profiles for the 4 users you chose for that field - Their 'company' field should be the post you were just editing. It is for me, this works as expected.

![field-settings](https://user-images.githubusercontent.com/71390469/93347459-02a7f580-f82d-11ea-93ac-6a74d00d3c56.png)

## WordPress Environment

<details>
```
WordPress Version: 5.5.1

PHP Version: 7.4.9

MySQL Version: 5.7.29

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: tmrlg_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 28.973M

Current Memory Usage (real): 20.000M

Pods Network-Wide Activated: No

Pods Install Location: /nas/content/live/b4ver2/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: B4 2020

Currently Active Plugins:

All In One WP Security: 4.4.4
Calendar Anything: 2.17
Cookie Notice: 1.3.2
If Menu - Visibility control for menu items: 0.16.1
Ninja Forms: 3.4.27
Ninja Forms - File Uploads: 3.3.8
Ninja Forms - Post Creation: 3.0.10
Ninja Forms - User Management: 3.0.12
Page Builder by SiteOrigin: 2.11.3
Pods - Custom Content Types and Fields: 2.7.22
Search & Filter: 1.2.12
Smart Slider 3: 3.4.1.9
Sticky Posts - Switch: 2.1.0
WP All Export - User Export Add-On Pro: 1.0.3
WP All Export Pro: 1.6.2
WP All Import - User Import Add-On Pro: 1.1.3
WP All Import Pro: 4.6.3
```
</details>

## Pods Package Export

[Pods-Package-Export.txt](https://github.com/pods-framework/pods/files/5232596/Pods-Package-Export.txt)

**Comment by ridinghoodmedia** [comment]
I'm having the exact same issue:

I'm having an issue where fFof a custom post (organization) that is supposed to show all users with a certain field (the user in question should show up here). I don't even know how to go about debugging this since it's purely a Pods backend issue. 

I should also mention that the user in question is showing up in the WP backend and the corresponding bidirectional organization field is showing correctly as selected. Only in the organization post itself is there a problem. And seemingly only for this user - that organization has 3 other users properly configured.

**Comment by sc0ttkclark** [comment]
I used the package you provided using Pods 2.7.22 but was unable to reproduce this problem. There's likely something else going on here.

When I added some users from the interface using the 'Add New' button, I did not choose admin/editor role, I chose subscriber. After saving and reloading, I noticed that it saved the data but did not show up. It wasn't showing up for me because they no longer matched the requirements for that field on which users would show. Is that what may have happened for you, or are you talking about the users actually showing in the list and you select+save them, but they don't show on reload?

Appreciate your patience here as I pinpoint exactly how to reproduce the problem here as I must be missing a step.

**Comment by lswaterfield** [comment]
Hi @sc0ttkclark 

The users I'm selecting are authors, and I have authors & admins chosen in the relationship field settings. My site doesn't use subscribers currently, and that's definitely not selected in the field settings either.

Thanks

**Comment by sc0ttkclark** [comment]
@lswaterfield Can you check to see if those users in the `wp_users` table have anything set for their `user_status` column that is NOT "0" (zero)?

**Comment by lswaterfield** [comment]
@sc0ttkclark [They're all zero](https://i.gyazo.com/40968eb4f07a20757b333952a142ab15.png)

**Comment by JoryHogeveen** [comment]
I thought I reproduced this but I couldn't. Imported the package on a clean installation.

@lswaterfield Have you verified this isn't a plugin conflict?
https://docs.pods.io/faqs/plugin-theme-conflicts/

**Comment by ridinghoodmedia** [comment]
@JoryHogeveen @lswaterfield I believe this is the same bug as this one: https://github.com/pods-framework/pods/issues/5677

@sc0ttkclark can you share the test environment I setup with @JoryHogeveen - the bug exists there too.

@lswaterfield can you try changing the field type to "checkbox" on the company side and see if the employees show up as checked there? That's the case for me - it's the dynamic fields that are affected by this bug it seems.

**Comment by lswaterfield** [comment]
@ridinghoodmedia yep changing to checkboxes shows the users correctly, checked as i'd expect them to be

**Comment by ridinghoodmedia** [comment]
@lswaterfield - ok then it's the same bug. I think between these two reports and the test environment, it's enough for you to debug right?

I'd like to help but I'd be really inefficient at trying to debug this because I don't know the pods codebase.

**Comment by lswaterfield** [comment]
@JoryHogeveen I've disabled all other plugins and child theme and the issue is still there I'm afraid. Current status seems to be:

- Works fine when using checkboxes, but not autocomplete
- The first 30 users in the database (alphabetically by display name) work with autocomplete, but none after that

**Comment by JoryHogeveen** [comment]
@lswaterfield 
Have you tried the patch from #5802 
Sounds like that will fix your issue as well.

**Comment by lswaterfield** [comment]
@JoryHogeveen dropped that in lines 1055-1068 but it hasn't made any difference i'm afraid

**Comment by JoryHogeveen** [comment]
Sorry, wrong PR, my bad.
Should be: #5850

**Comment by lswaterfield** [comment]
@JoryHogeveen it worked! well done, and thank you!

**Comment by JoryHogeveen** [comment]
Great, thanks for testing!
