### ISSUE TITLE
Comment types should have auto-templates hooked into comment_text

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#5832]
This is coming from https://wordpress.org/support/topic/custom-comment-fields-are-not-showing-in-front-end/#post-13421929

Basically, for posts we have auto-templating support, but we have nothing to make it easy for comments. This would be a fantastic addition.

**Comment by JoryHogeveen** [comment]
Moving this to PR #5533 since changes like this greatly benefit from the refactor that PR has made.
