### ISSUE TITLE
Date type field issue

### ISSUE THREAD

**Issue by suryavanshi08** [pods-framework/pods#5833]
I’m facing an issue with pods field type "Date". What happens is that when I type the date into the field, as soon as my cursor leaves the field, the date changes immediately to 2026 before I can even save.
Here are my settings in my new pod:
Pod = my_publications_pod
Field name = copyright_year
Field-Type = Date
Options = not required
Additional Field Options
Date Format Type = Predefined format
Date Format = 2020
Year range = blank (I also tried adding a range, but still same problem)
Allow empty value = Yes
Advanced
No settings or values added
REST API
no settings added

**Comment by JoryHogeveen** [comment]
Hello @suryavanshi08 

That is probably because the format you type isn't the same as you've chosen for the field.
In that case jQuery datepickter tries to "guess" the date based on what you types and this doesn't always turn out correct.

Let me know!

Cheers, Jory
