### ISSUE TITLE
In Pull Down Category & turns into &amp;

### ISSUE THREAD

**Issue by techprogrammer** [pods-framework/pods#5835]
This worked fine in 2.7.20, then broke from 2.7.20.1 onwards through 2.7.22

**To Reproduce**
Creating a new entry in my editor, I click on Category popup menu and see this.
Screen shot attached

**Expected behavior**
& not &amp; in menu

**Screenshots**
![pods 2 7 22 bug](https://user-images.githubusercontent.com/5952458/93687177-8867b300-fa70-11ea-80a3-f80717b21a15.PNG)

## Pods Version
2.7.22

## WordPress Environment
5.5.1

Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.

</details>

## Pods Package Export (helpful!)
{"meta":{"version":"2.7.22","build":1600542470},"pods":{"418":{"id":418,"name":"categories","label":"Categories","description":"","type":"taxonomy","storage":"table","object":"","alias":"","fields":{"category_id":{"id":419,"name":"category_id","label":"Category ID *","description":"","help":"","class":"","type":"number","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"1","number_format":"9999.99","number_decimals":"0","number_max_length":"12","wysiwyg_max_length":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","number_repeatable":0,"number_format_type":"number","number_format_soft":0,"number_step":1,"number_min":0,"number_max":100,"number_placeholder":""},"related_category":{"id":420,"name":"related_category","label":"Related Category","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"pod","pick_val":"categories","sister_id":"","required":"0","unique":"0","wysiwyg_max_length":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_limit":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":"","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":1,"pick_taggable":0,"pick_show_icon":1,"pick_show_edit_link":1,"pick_show_view_link":1,"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_user_role":"","pick_post_status":"publish"},"alternate_url":{"id":3812,"name":"alternate_url","label":"Alternate URL","description":"","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","website_format":"normal","website_max_length":"255","website_html5":"0","wysiwyg_max_length":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","website_repeatable":0,"website_allow_port":0,"website_clickable":0,"website_new_window":0,"website_placeholder":""},"hide_shipping":{"id":7559,"name":"hide_shipping","label":"Hide","description":"yes","help":"","class":"","type":"boolean","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","wysiwyg_max_length":"0","boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","default_value":"No","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value_parameter":"","capability_allowed":""},"active":{"id":21087,"name":"active","label":"Active *","description":"","help":"","class":"","type":"boolean","weight":4,"pick_object":"","pick_val":"","sister_id":"","pick_custom":"","required":"0","unique":"0","wysiwyg_max_length":"0","boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","input_helper":"","default_value":"Yes","default_value_parameter":"","admin_only":"0","restrict_capability":"0","capability_allowed":""}},"show_in_menu":1,"label_singular":"category","public":"1","show_ui":"1","show_in_nav_menus":"1","show_tagcloud":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","query_var":"0","built_in_post_types_post":"0","built_in_post_types_page":"0","built_in_post_types_deals":"1","sort":"0","show_admin_column":"0","built_in_post_types_safecss":"0","built_in_post_types_feedback":"0","built_in_post_types_attachment":"0","label_add_new":"","label_add_new_item":"","label_new_item":"","label_edit":"","label_edit_item":"","label_update_item":"","label_view":"","label_view_item":"","label_all_items":"","label_search_items":"","label_not_found":"","label_popular_items":"","label_separate_items_with_commas":"","label_add_or_remove_items":"","label_choose_from_the_most_used":"","menu_name":"","menu_icon":"","label_parent_item_colon":"","label_parent":"","rewrite_custom_slug":"","update_count_callback":""}}}

**Additional context**
https://wordpress.org/support/topic/2-7-20-1-popup-menu-issue/
I had voice this issue in the past when 2.7.20.1 came out.  It had a bug where spaces in this category popup were turned into &nbsp;
Jory claimed it was fixed but alas no.

2.7.21 fixed this space issue, but never did fix this &amp; issue.

**Possible Workaround**
Downgrade to 2.7.20

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
I believe I found the issue for this.
See: https://github.com/pods-framework/pods/blob/main/ui/js/pods-dfv/_src/pick/views/select-view.js#L25

This initial renderer sets the option name as `text` instead of `html` and for this reason thing like `&amp;` do not work.
I think it's best to remove the `esc_html` and `wp_kses_post` from the sanitizer in PHP:
https://github.com/pods-framework/pods/blob/main/classes/fields/pick.php#L1398

Or create a custom function specially for this.
Thoughts?
