### ISSUE TITLE
Pods CPT is creating pages when it should not

### ISSUE THREAD

**Issue by nicocollu** [pods-framework/pods#5836]
**## Issue Overview**
I am using Pods to create a CPT called 'Team Members' which is not 'Public' and not publicly queryable.
Still, it seems to be creating a few pages for some of the team members which it shouldn't.

**## WordPress Environment**
Version 5.5.1

**Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.**
WordPress Version: 5.5.1
PHP Version: 7.3.22
MySQL Version: 5.7.23
Server Software: Apache
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Session Save Path: /var/cpanel/php/sessions/ea-php73
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: Dad_

WP Multisite Mode: No
WP Memory Limit: 40M
Current Memory Usage: 82.588M
Current Memory Usage (real): 85.000M
Pods Network-Wide Activated: No
Pods Install Location: /home1/lifeplv6/public_html/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: Pro – Child Theme
Currently Active Plugins:

Advanced Custom Fields PRO: 5.8.12
Better Notifications for WP: 1.8.4
Code Snippets: 2.14.0
Colorlib Login Customizer: 1.2.96
Elegant Custom Fonts: 1.0
Fluent Forms: 3.6.51
Fluent Forms Pro Add On Pack: 3.6.50
HappyFiles Pro: 1.2
LearnDash LMS: 3.2.2
LearnDash LMS - Course Grid: 1.6.0
LiveChat: 4.3.3
Oxygen: 3.5
Peter's Login Redirect: 2.9.7
Pods - Custom Content Types and Fields: 2.7.22
Post SMTP: 2.0.15
Simple Custom Post Order: 2.5.0
UpdraftPlus - Backup/Restore: 2.16.27.1
WP Simple Mail Sender: 1.0.2

**## Pods Package Export (helpful!)**
[json export.txt](https://github.com/pods-framework/pods/files/5252797/json.export.txt)

**Comment by nicocollu** [comment]
Is there anyone here that can lend a hand? :)

**Comment by nicocollu** [comment]
Here is one of the pages that has a page created for it: https://lifeplus.co.nz/team-member/tahira-nisha/tahira-nisha-2/

It should not exist at all.
Screenshot of POD settings:
<img width="924" alt="Screen Shot 2020-09-24 at 13 16 12" src="https://user-images.githubusercontent.com/62866110/94089871-4bccfa80-fe68-11ea-9ae7-bfd51cde090a.png">

**Comment by nicocollu** [comment]
It seems like the pages have been deleted pages but are still showing when the URL is typed in.
Is there anywhere to purge all previously deleted pages?

**Comment by JoryHogeveen** [comment]
Hello @nicocollu 

When I click the link I get redirected to the homepage so my guess is that this link only works if you are logged in.
Please clear all your cache (browser cache, Pods cache and if you use one, your cache plugin).

Cheers, Jory

**Comment by nicocollu** [comment]
> Hello @nicocollu
> 
> When I click the link I get redirected to the homepage so my guess is that this link only works if you are logged in.
> Please clear all your cache (browser cache, Pods cache and if you use one, your cache plugin).
> 
> Cheers, Jory

Hey Jory,

I installed the RankMath plugin and set redirection to 'Deleted Pages' so it seems as if the pages in question are deleted pages. They still exist though.

I tried clearing all the caches you mentioned but wasn't able to rid of the pages. Because I don't know how to navigate SQL databases, I was not clever enough to find the pages and delete them manually, unfortunately.

Until now, the redirection is doing its work.

**Comment by JoryHogeveen** [comment]
Hi @nicocollu 

Even though deleted pages shouldn't be visible at all, you can permanently remove then from the database through WP admin. Just click on "trash":
![image](https://user-images.githubusercontent.com/826148/94264810-b0a35600-ff37-11ea-98c8-9c8e85e276b3.png)

I do get the feeling that this also might be a plugin conflict.
See this page for more info on how to find the issue: https://docs.pods.io/faqs/plugin-theme-conflicts/

Cheers, Jory

**Comment by nicocollu** [comment]
Hey @JoryHogeveen 

There are no posts in 'Trash' so even though those pages exist, I was not able to find them in the Trash.
That plugin is actually a really helpful link, thanks for that.

Will probably leave the entire this at this point unless the client complains since deleted pages are being redirected and will hopefully, eventually get deleted automatically.

**Comment by JoryHogeveen** [comment]
Hi @nicocollu 

No problem, if/when you do have the time to debug the conflict let me know! Though I think this is a plugin conflict, I'd like to make sure this isn't a bug in Pods.
Closing topic for now!

Cheers, Jory
