### ISSUE TITLE
Unable to upload file via "add media" button on a form generated by pods form shortcode for a user with WP role "author"

### ISSUE THREAD

**Issue by papa-pup** [pods-framework/pods#5837]
## Issue Overview
Unable to upload file via "add media" button on a form generated by pods form shortcode for a user with WP role "author"
[Captures.zip](https://github.com/pods-framework/pods/files/5265751/Captures.zip)

Captures shows both current and expected behavior. Expected behavior simulated as WP role "Editor".

## Expected Behavior
Able to upload file via "add media" button on a form generated by pods form shortcode for a user with WP role "Editor"

## Current Behavior
Produces error "Sorry, you are not allowed to attach files to this post." for WP role "author" and not for WP role "Editor" and above.

## Steps to Reproduce (for bugs)
Scenario 1 
1. Create a POD item "Test"
2. Create a Page using shortcode [pods name="test" form=1 fields="post_content"] 
3. Create a User with WP Role "Author"
4. Log on to the User with that role in step 3 and go to the page created in step 2 
5. Click "Add Media" to upload a file and the error occurs.
Note: If the role of the user is WP Role "Editor" this problem does not happen

Scenario 2 
1. Create a POD item "Test" with following fields
1a. Field TEST_A as "WYSIWYG (Visual Editor)"
2. Create a Page using shortcode [pods name="test" form=1 fields="TEST_A"] 
3. Create a User with WP Role "Author"
4. Log on to the User with that role in step 3 and go to the page created in step 2 
5. Click "Add Media" to upload a file and the error occurs.
Note: If the role of the user is WP Role "Editor" this problem does not happen

Scenario 3 (not a bug - showing that it works)
1. Create a POD item "Test" with following fields
1a. Field TEST_B as "File / Image / Video" with File Uploader selected as "Upload and/or Select (Media Library)"
2. Create a Page using shortcode [pods name="test" form=1 fields="TEST_B"] 
3. Create a User with WP Role "Author"
4. Log on to the User with that role in step 3 and go to the page created in step 2 
5. Click "Add Media" to upload a file and no error occurs.

Scenario 4 
1. Create a POD item "Test" with following fields
1a. Field TEST_B as "File / Image / Video" with File Uploader selected as "Upload and/or Select (Media Library)"
2. Create a Page using shortcode [pods name="test" form=1 fields="post_content, TEST_B"] 
3. Create a User with WP Role "Author"
4. Log on to the User with that role in step 3 and go to the page created in step 2 
5. Click "Add Media" to upload a file and  the error occurs.
Note: If the role of the user is WP Role "Editor" this problem does not happen

Scenario 5 
1. Create a POD item "Test" with following fields
1a. Field TEST_A as "WYSIWYG (Visual Editor)"
1b. Field TEST_B as "File / Image / Video" with File Uploader selected as "Upload and/or Select (Media Library)"
2. Create a Page using shortcode [pods name="test" form=1 fields="TEST_A, TEST_B"] 
3. Create a User with WP Role "Author"
4. Log on to the User with that role in step 3 and go to the page created in step 2 
5. Click "Add Media" to upload a file and  the error occurs.
Note: If the role of the user is WP Role "Editor" this problem does not happen

## Possible Solution
Unknown

## WordPress Environment
<details>
WordPress Version: 5.5.1
PHP Version: 7.4.3
MySQL Version: 5.6.41
Server Software: LiteSpeed
Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Session Save Path: /opt/alt/php74/var/lib/php/session
Session Save Path Exists: No
Session Save Path Writeable: No
Session Max Lifetime: 1440
Opcode Cache:
Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:
APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 40M
Current Memory Usage: 45.332M
Current Memory Usage (real): 46.500M
Pods Network-Wide Activated: No
Pods Install Location: /home/techacti/WPrecp.techactions.net/v1/wp-content/plugins/pods/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: Twenty Twenty
Currently Active Plugins:
Pods - Custom Content Types and Fields: 2.7.22
Wordfence Security: 7.4.11
</details>

## Pods Package Export (helpful!)
```
{"meta":{"version":"2.7.22","build":1600840528},"pods":{"6":{"id":6,"name":"project","label":"Projects","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"project_id":{"id":7,"name":"project_id","label":"Project ID","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","default_value":"PROJECT-RECP-{@user.id}-{@date.YmdHis}","oembed_enabled_providers_hulucom":"0","text_placeholder":""},"project_location":{"id":8,"name":"project_location","label":"Project Location","description":"","help":"","class":"GoogleAutoComplete","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","oembed_enabled_providers_hulucom":"0","text_placeholder":""},"project_phase":{"id":9,"name":"project_phase","label":"Project Phase","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","oembed_enabled_providers_collegehumorcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"0","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":",","pick_custom":"New\/On-Going\nFuture\/Up-Coming\nCompleted\nTemporary Halted \/ Abandon","default_value":"New\/On-Going","oembed_enabled_providers_hulucom":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"project_image":{"id":10,"name":"project_image","label":"Project Image","description":"Add Up to 10 Images (.jpg, .jpeg, .png, .gif)","help":"","class":"","type":"file","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"10","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"none","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"project_brochure":{"id":11,"name":"project_brochure","label":"Project Brochure","description":"Add up to 5 PDF files only.","help":"","class":"","type":"file","weight":4,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"5","file_restrict_filesize":"10MB","file_type":"other","file_allowed_extensions":"pdf","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0"},"test":{"id":35,"name":"test","label":"Test","description":"","help":"","class":"","type":"wysiwyg","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_repeatable":0,"wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""}},"show_in_menu":"1","label_singular":"Project","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"project","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"publish","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"1","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_icon":"dashicons-admin-multisite","show_in_nav_menus":"1","show_in_admin_bar":"0","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"Project Post Template","menu_position":"0","rewrite_custom_slug":"projects","menu_name":"Projects","built_in_taxonomies_project_phase_taxonomy":"1"}}}
```

## Workaround or Alternate Solution Until Bug is Addressed
Unknown

## Related Issues and/or PRs
Unknown

**Comment by papa-pup** [comment]
@sc0ttkclark ,
Can you help on this?

**Comment by JoryHogeveen** [comment]
Hello @papa-pup 
Did you add the required capabilities to your roles?
Cheers, Jory

**Comment by papa-pup** [comment]
Hi @JoryHogeveen,
Those roles are out of the box WordPress roles. No changes made to those roles.

**Comment by papa-pup** [comment]
Hi @JoryHogeveen ,
I did another round of test.

This time, I enable other additional capabilities on top of what existed on standard WP author role. I found that we need to add at two capabilities
a. Edit Other's Pages
b. Edit Published Pages

I am using Members plugin by MemberPress (formerly developed by Justin Tadlock), to test and enable these capabilities.

Just weird why would we need to enable the WP Author role to edit other's pages and published pages when it's about post?

**Comment by JoryHogeveen** [comment]
Hello @papa-pup 

An author normally doesn't have the capability to publish or modify existing posts.
Also, these capabilities can be handled separately for each post type (page, post, test, etc.)
This is simply how WordPress core handles capabilities and not something done by Pods.

> Just weird why would we need to enable the WP Author role to edit other's pages and published pages when it's about post?

This depends on your post type settings. What did you select as the capability? `Page` maybe?

Closing topic!

**Comment by papa-pup** [comment]
Hi @JoryHogeveen ,

Based on the Wordpress documentation at https://wordpress.org/support/article/roles-and-capabilities/#author  author roles can publish and modiy existing post; Or did I misinterpret it wrong. Can you check the link and confirm again....

**Comment by JoryHogeveen** [comment]
Hi @papa-pup 

This only works for posts that the author made, not posts by others. You need the `edit_others_posts` for that. See `Editor` role.

Cheers, Jory
