### ISSUE TITLE
Unable to create new pod, Javascript error

### ISSUE THREAD

**Issue by nocto7** [pods-framework/pods#5848]
## Issue Overview
I'm helping someone out who is trying to install Pods on his wordpress site. It's installing but when you click "create new" nothing happens (or with "extend existing"). I have javascript errors in the browser console. Support have asked me to add this as a bug report.

## Expected Behavior

Go to "add new" in the pods plugin. Hit "create new". I'm expecting to see the next page appear with the content type, singular label, plural label boxes and so on. 

 

## Current Behavior

Go to "add new" in the pods plugin. Hit "create new" or "extend existing". Nothing appears to happen. I get errors in the browser console.

```
Uncaught TypeError: $(...).Pods is not a function
    <anonymous> http://www.[DOMAIN]/wp-admin/admin.php?page=pods-add-new:585
    jQuery 8
        i
        fireWith
        ready
        J
        promise
        <anonymous>
        <anonymous>
        <anonymous>

Source map error: Error: request failed with status 404
Resource URL: http://www.[DOMAIN]/wp-content/plugins/pods/ui/js/pods-dfv/pods-dfv.min.js?ver=2.7.22
Source Map URL: pods-dfv.min.js.map
```
These errors are in addition to seeing the same 11 files loading from pods/ui/js that I see on a different site with a working pods installation when I try to do the same thing. The error points to admin.php line 585 which is  
```$( document ).Pods( 'validate' );```

 

## Steps to Reproduce (for bugs)

This issue seems specific to this website as I can't reproduce it on other sites.

## WordPress Environment

<details>

Debug Information

WordPress Version: 5.5.1

PHP Version: 7.3.3

MySQL Version: 5.6.21

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0

Session Save Path: 10.170.0.172:11211; 10.170.0.173:11211; 10.170.0.174:11211

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 14400

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: Yes
    Redis: No

WPDB Prefix: rnpa_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 33.500M

Current Memory Usage (real): 36.000M

Pods Network-Wide Activated: No

Pods Install Location: /var/sites/r/rnpa.org.uk/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Gridiculous Pro

Currently Active Plugins:

    Admin Bar Disabler: 1.4.1
    Akismet Anti-Spam: 4.1.6
    All-in-One WP Migration: 7.28
    BB Plugins Filterable Gallery - Lite: 1.0.3
    Beaver Builder Plugin (Pro Version): 2.4.0.5
    BuddyPress: 6.3.0
    Classic Editor: 1.6
    Download Manager: 3.1.10
    Elementor: 3.0.11
    Elementor Pro: 3.0.5
    Enhanced Media Library: 2.7.2
    Flickr Justified Gallery: 3.5
    GP Premium: 1.12.1
    Media Library Folders for WordPress: 6.0.3
    Open External Links in a New Window: 1.4
    Pods - Custom Content Types and Fields: 2.7.22
    Simple Links: 4.7.3
    Ultimate Addons for Beaver Builder: 1.27.0
    WP-invites: 2.52
    WP Maintenance Mode: 2.2.4

</details>

## Pods Package Export (helpful!)

When I enable the migrate packages componets there is no "export" option, presumably because no pods have yet been added.

**Comment by nocto7** [comment]
I investigated further and disabling the "BB Plugins Filterable Gallery - Lite" plugin seems to have removed the issue so I'm guessing the problem was actually with them and not with pods. Thanks.

**Comment by JoryHogeveen** [comment]
Hi @nocto7 

Thanks for letting us know!
