### ISSUE TITLE
Previously in version 2.6.11 Display Field In Selection List accepted {@name} in 2.7* it does not.

### ISSUE THREAD

**Issue by winnersmedia** [pods-framework/pods#5859]
## Issue Overview
Previously in version 2.6.11 Display Field In Selection List accepted {@name} for relationships in the additional field options.  In versions 2.7* it does not and only accepts {@post_title}. Although this may be correct with {@post_title} it maybe should still accept {@name} for backwards compatibility.

## Expected Behavior
When upgrading pods to the latest version I would expect the relationship to continue to display using {@name} but they now display as blank.

## Current Behavior
When upgrading pods to the latest version this was causing all my relationships to display as blank on the edit screens.

## Steps to Reproduce (for bugs)
1. Create a bi-directional relationship field
2. Click the Additional Field Options tab
3. Enter {@name} in the "Display Field In Selection List" field
4. Save
5. Go to the edit screen for the pod. 

## WordPress Environment
 5.5.1–en_GB

**Comment by winnersmedia** [comment]
possibly relates to #5839

**Comment by JoryHogeveen** [comment]
Hello @winnersmedia 
I indeed think this never worked at all and just reverted to `{@post_title}`.
In this case you could just omit the whole value since `{@post_title}` is the default anyway.

**Comment by JoryHogeveen** [comment]
Did some more digging and turns out it searches for the meta value if the param isn't an object parameter.
