### ISSUE TITLE
GraphQL support?

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [pods-framework/pods#5868]
Does Pods have graphql support?

**Comment by therealgilles** [comment]
Investigating possible future graphql support (through wp-graphql) would be great. GraphQL is likely to be at the core of headless wordpress implementations, as it optimizes communication between the client and the wordpress backend and thus is more efficient than using the REST API.

**Comment by andrerds** [comment]
Hello friend, there are days that I'm looking for a possible solution for the Pods to work with wpgraphql but without success. Also for the reason of not knowing very well how the whole structure of wordpress and plugins works. More trying that an hour will work. If someone managed to make it work at first with extended custom fields that is my biggest interest. Thanks guys, let's confident we can make it.

**Comment by bencodesall** [comment]
What does need votes actually mean (issue status tag), and how do I add a vote? This feature request is pretty urgent, I would say!

**Comment by sc0ttkclark** [comment]
I built an in-depth WPGraphQL integration for Pods and it works exactly as you'd hope with relationships -- with connections! It's pretty useful, check it out here: https://pods-pro.skc.dev/downloads/wpgraphql-integration/

**Comment by bencodesall** [comment]
Yeah, but still requires unreleased version of pods (2.7.30 is current) for production usage ... waiting on release 2.8 thanks.

**Comment by andrerds** [comment]
Hi, how are you @beekbarkbork ,
 I'm looking forward to this version. Congratulations to the devs :D
