### ISSUE TITLE
Conflict between Pods and Ninja Forms

### ISSUE THREAD

**Issue by spalders** [pods-framework/pods#5886]
**Describe the bug**
Pods conflict with Ninja Forms plugin. Form editor will not load with Pods activated. Just loads a white screen - see below.

**Expected behavior**
Ninja forms editor should load.

**Screenshots**
![Pods Ninja white screen](https://user-images.githubusercontent.com/57146775/98378017-671d4f00-203d-11eb-8040-f380151a6afc.png)

## Pods Version
Please provide the version of Pods you are running: 2.7.24

## WordPress Environment

<details>

`
### wp-core ###

version: 5.5.3
site_language: en_US
user_language: en_US
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 756
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress/core/5.5.3
wordpress_size: 45.55 MB (47765273 bytes)
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: 1.38 GB (1484734447 bytes)
themes_path: /srv/htdocs/wp-content/themes
themes_size: 38.03 MB (39875886 bytes)
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: 407.54 MB (427341678 bytes)
database_size: 78.03 MB (81821696 bytes)
wpcomsh-disk-space-used: 1.9 GB
wpcomsh-disk-space-quota: 200.0 GB

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: BuddyBoss Theme (buddyboss-theme)
version: 1.5.8
author: BuddyBoss
author_website: https://www.buddyboss.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, editor-style, buddypress-use-nouveau, automatic-feed-links, title-tag, html5, customize-selective-refresh-widgets, custom-logo, menus, post-formats, woocommerce, job-manager-templates, widgets
theme_path: /srv/htdocs/wp-content/themes/buddyboss-theme

### wp-themes-inactive (4) ###

BuddyBoss Child: version: 1.0.0, author: BuddyBoss.com
Lodestar: version: 1.0.14-wpcom, author: Automattic
Organic Purpose: version: 2.2.1, author: Organic Themes
Storefront: version: 2.8.0, author: Automattic

### wp-mu-plugins (3) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.7.2
LearnDash LMS Multisite: version: 1.0.0, author: LearnDash
WP.com Site Helper: author: (undefined), version: (undefined)

### wp-plugins-active (53) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic
AMP: version: 2.0.5, author: AMP Project Contributors
AutomatorWP: version: 1.3.0, author: AutomatorWP
AWSM Team Pro: version: 1.8.1, author: AWSM Innovations
BP Profile Shortcodes Extra: version: 2.5.2, author: Venutius
BuddyBoss Platform: version: 1.5.4, author: BuddyBoss
BuddyBoss Platform Pro: version: 1.0.2, author: BuddyBoss (latest version: 1.0.7)
Category Posts Widget: version: 4.9.5, author: TipTopPress
CM Editor Tooltip: version: 1.0.2, author: CreativeMindsSolutions
CM Tooltip Glossary Community Terms: version: 1.2.18, author: CreativeMindsSolutions (latest version: 1.2.19)
CM Tooltip Glossary Ecommerce: version: 3.9.12, author: CreativeMindsSolutions
CM Tooltip Glossary PeepSo Integration: version: 1.1.3, author: CreativeMindsSolutions
CM Tooltip Glossary Remote Import: version: 1.0.12, author: CreativeMindsSolutions
CM Tooltip Glossary Stats: version: 1.1.7, author: CreativeMindsSolutions
CM Tooltip Glossary Widgets: version: 1.3.8, author: CreativeMindsSolutions
CoBlocks: version: 2.5.1, author: GoDaddy
Content Aware Sidebars: version: 3.13.1, author: Joachim Jensen - DEV Institute
Dropdown Content: version: 1.0.2, author: Metaloha
Elementor: version: 3.0.13, author: Elementor.com
Elementor Pro: version: 3.0.6, author: Elementor.com
Essential Addons for Elementor: version: 4.3.5, author: WPDeveloper
FileBird Lite: version: 4.1, author: Ninja Team
Gutenberg: version: 9.2.2, author: Gutenberg Team
Head & Footer Code: version: 1.2.1, author: Aleksandar Urosevic
Head and Footer Scripts Inserter: version: 4.48, author: Space X-Chimp
Health Check & Troubleshooting: version: 1.4.5, author: The WordPress.org community
If Menu - Visibility control for menu items: version: 0.16.1, author: Layered
Instant Images: version: 4.3.5, author: Darren Cooney
Jetpack by WordPress.com: version: 9.0.2, author: Automattic
JetSmartFilters: version: 2.0.4, author: Crocoblock
LearnDash Content Cloner: version: 1.2.9.1, author: WisdmLabs
LearnDash LMS: version: 3.2.3.6, author: LearnDash
LearnDash LMS - Course Grid: version: 1.6.0, author: LearnDash
LearnDash LMS - MemberPress Integration: version: 2.1.1, author: LearnDash
LearnDash Ratings, Reviews, and Feedback: version: 2.0.1, author: WisdmLabs
LuckyWP Table of Contents: version: 2.1.4, author: LuckyWP
MemberPress + BuddyPress Integration: version: 1.1.8, author: Caseproof, LLC
MemberPress Elementor Content Protection: version: 1.0.1, author: Caseproof, LLC
MemberPress Plus: version: 1.9.4, author: Caseproof, LLC
MetaSlider: version: 3.18.9, author: MetaSlider
More Visibility Rules: version: 0.4, author: Layered
Ninja Forms: version: 3.4.30, author: Saturday Drive
Page Optimize: version: 0.5.1, author: Automattic
Pods - Custom Content Types and Fields: version: 2.7.24, author: Pods Framework Team
Restrict Media Library Access: version: 1.0, author: mrfoxtalbot
Simple Tags: version: 2.62, author: WebFactory Ltd
Super RSS Reader: version: 4.0, author: Aakash Chakravarthy
Tin Canny Reporting for LearnDash: version: 3.4.3, author: Uncanny Owl (latest version: 3.4.4)
Ultimate Addons for Gutenberg: version: 1.18.0, author: Brainstorm Force
User Role Editor Pro: version: 4.57.1, author: Vladimir Garagulia
User Shortcodes Plus: version: 2.0.2, author: Kyle B. Johnson
Visual Customizer for LearnDash: version: 2.3, author: SnapOrbital (latest version: 2.3.6.1)
WordPress User Notes: version: 1.2.2, author: SnapOrbital (latest version: 1.6.5)

### wp-plugins-inactive (50) ###

Advanced iFrame: version: 2020.8.1, author: Michael Dempfle
Advanced iFrame custom folder: version: 1.0, author: Michael Dempfle
All In One WP Security: version: 4.4.4, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy
Blog Filter: version: 1.3.0, author: A WP Life
BuddyBoss Products Updater: version: 1.2.8, author: BuddyBoss
BuddyPress for LearnDash: version: 1.3.0, author: BuddyBoss
BuddyPress Group Email Subscription: version: 4.0.0, author: Deryk Wenaus, boonebgorges, r-a-y
BuddyPress Groups Extras: version: 3.6.9.1, author: slaFFik
CBX Bookmark & Favorite: version: 1.6.4, author: Codeboxr Team
CBX Bookmark & Favorite Pro Addon: version: 1.2.6, author: Codeboxr
Classic Editor: version: 1.6, author: WordPress Contributors
CM Tooltip Glossary Custom Taxonomies: version: 1.0.6, author: CreativeMindsSolutions
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: version: 6.0.8.5, author: SeedProd
Export Media Library: version: 3.0.1, author: Mass Edge Inc.
GamiPress: version: 1.9.4, author: GamiPress
GamiPress - Activity by Category: version: 1.0.8, author: GamiPress
GamiPress - Button: version: 1.0.4, author: GamiPress
GamiPress - Conditional Emails Recipients: version: 1.0.0, author: GamiPress
GamiPress - Emails By Type: version: 1.0.2, author: GamiPress
GamiPress - Invite Anyone integration: version: 1.0.0, author: GamiPress
GamiPress - Leaderboards Include/Exclude Users: version: 1.0.3, author: GamiPress
GamiPress - LearnDash Group Leaderboard: version: 1.0.7, author: GamiPress
GamiPress - LearnDash integration: version: 1.2.5, author: GamiPress
GamiPress - Link: version: 1.1.4, author: GamiPress
GamiPress - MemberPress integration: version: 1.0.0, author: GamiPress
GamiPress - Multimedia Content: version: 1.0.3, author: GamiPress
GamiPress - Notifications By Type: version: 1.0.7, author: GamiPress
GamiPress - The Events Calendar integration: version: 1.0.4, author: GamiPress
GamiPress - Vimeo integration: version: 1.0.5, author: GamiPress
Google Analytics for WordPress by MonsterInsights: version: 7.13.0, author: MonsterInsights
Invite Anyone: version: 1.4.1, author: Boone Gorges
Layout Grid: version: 1.3, author: Automattic
LearnDash Group Registration: version: 4.1.0, author: WisdmLabs
LearnDash LMS - Elementor: version: 1.0.2, author: LearnDash
MemberPress Importer: version: 1.6.5, author: Caseproof, LLC
MemberPress User Roles: version: 1.0.5, author: Caseproof, LLC
Plugins Deactivator: version: 1.0.0, author: Ren Ventura
Popup Builder: version: 3.69.5, author: Sygnoos
Posts Table with Search & Sort: version: 1.3.3, author: Barn2 Plugins
PublishPress Capabilities: version: 1.10.1, author: PublishPress
Quiz Reporting Extension for LearnDash: version: 2.1.1, author: WisdmLabs
Social Login: version: 5.6, author: OneAll Social Login <support@oneall.com>
Uncanny Toolkit for LearnDash: version: 3.4, author: Uncanny Owl
User Role Editor: version: 4.56.1, author: Vladimir Garagulya
User Verification: version: 1.0.51, author: PickPlugins
WooCommerce: version: 4.6.2, author: Automattic
WooCommerce Stripe Gateway: version: 4.5.3, author: WooCommerce
WordPress.com Editing Toolkit: version: 2.8.3, author: Automattic
WP Mail SMTP: version: 2.5.1, author: WPForms
Zendesk Chat Widget: version: 1.4.18, author: Zendesk

### wp-media ###

image_editor: Photon_Subsizes_WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.9.0-11-amd64 x86_64
httpd_software: nginx
php_version: 7.3.23 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 256M
max_input_time: 1200
upload_max_size: 2047M
php_post_max_size: 2047M
curl_version: 7.72.0 OpenSSL/1.1.0l
suhosin: false
imagick_availability: false
server-headers: 
	server: nginx
	date: Fri, 06 Nov 2020 14:41:27 GMT
	content-type: text/html; charset=UTF-8
	strict-transport-security: max-age=31536000
	vary: Accept-Encoding
	host-header: WordPress.com
	content-security-policy: script-src * 'self' 'unsafe-inline' 'unsafe-eval'
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	link: Array
	content-encoding: gzip
	x-ac: 5.bur _atomic_bur

### wp-database ###

extension: mysqli
server_version: 10.3.21-MariaDB-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://oneheglobal.org
WP_SITEURL: https://oneheglobal.org
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 144206963
ssl_cert: No
time_diff: undefined
version_option: 9.0.2:1602256006
old_version: 9.0.1:1602011186
public: Public
master_user: #4 nikkispalding
current_user: #4 nikkispalding
tokens_set: Blog User
blog_token: puvm%W!epvQYX7*m%VhEelyz1@ZNZDV0
user_token: isYsLw16v6qrP1X@7*cXz1kVD%kzo*&S
version: 9.0.2
jp_plugin_dir: /wordpress/plugins/jetpack/9.0.2/
plan: business
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Fri, 12 Jun 2020 13:22:06 +0000","finished":"Fri, 12 Jun 2020 13:25:16 +0000","progress":{"constants":{"finished":true},"functions":{"finished":true},"options":{"finished":true},"updates":{"finished":true},"themes":{"finished":true},"users":{"total":"18","sent":18,"finished":true,"last_sent":"2"},"terms":{"total":"215","sent":215,"finished":true,"last_sent":"1"},"posts":{"total":"1273","sent":1273,"finished":true,"last_sent":"2"},"comments":{"total":"1","sent":1,"finished":true,"last_sent":"15"},"term_relationships":{"total":"240","sent":242,"finished":true,"last_sent":{"object_id":"1","term_taxonomy_id":"2"}}},"config":{"constants":1,"functions":1,"options":1,"updates":1,"themes":1,"users":1,"terms":1,"posts":1,"comments":1,"term_relationships":1}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/oneheglobal.org","siteurl":"https:\/\/oneheglobal.org","WP_HOME":"https:\/\/oneheglobal.org","WP_SITEURL":"https:\/\/oneheglobal.org"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### luckywp-table-of-contents ###

domVersion: 20031129
libxmlVersion: 2.9.4
intlVersion: 7.3.23
icuVersion: 57.1
settings: {"lwptoc_general":{"min":"2","depth":"6","hierarchical":true,"numeration":"decimalnested","numerationSuffix":"none","title":"Contents","toggle":true,"labelShow":"show","labelHide":"hide","hideItems":false,"smoothScroll":true,"smoothScrollOffset":"130"},"lwptoc_appearance":{"width":"auto","float":"none","titleFontSize":"default","titleFontWeight":"bold","itemsFontSize":"90%","colorScheme":"inherit","backgroundColor":null,"borderColor":null,"titleColor":null,"linkColor":null,"hoverLinkColor":null,"visitedLinkColor":null},"lwptoc_autoInsert":{"enable":false,"position":"beforefirstheading","postTypes":["post"]},"lwptoc_processingHeadings":{"postTypes":["page"]},"lwptoc_misc":{"skipHeadingLevel":null,"skipHeadingText":null,"hashFormat":"asheading","hashConvertToLowercase":false,"hashReplaceUnderlinesToDashes":false,"wrapNoindex":false,"useNofollow":false,"showMetaboxPostTypes":null,"listMarkupTags":"div","containerClass":null}}

### pods ###

pods-server-software: nginx
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: Yes
pods-object-cache-memcache: Yes
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 130.411M
pods-memory-current-usage-real: 136.000M
pods-network-wide: No
pods-install-location: /srv/htdocs/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

### amp_wp ###

amp_mode_enabled: reader
amp_reader_theme: legacy
amp_templates_enabled: post, post, page, attachment, forum, topic, reply, elementor_library, memberpressproduct, memberpressgroup, sfwd-courses, sfwd-lessons, sfwd-topic, sfwd-quiz, sfwd-certificates, sfwd-transactions, glossary, sfwd-essays, coursenote
amp_serve_all_templates: This option does not apply to Reader mode.
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: undefined
amp_css_transient_caching_time_series: 
amp_libxml_version: 2.9.4

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Duplicate issue: https://github.com/pods-framework/pods/issues/5354
