### ISSUE TITLE
Pods Plugin no longer allowing changes

### ISSUE THREAD

**Issue by westhavenmgmt** [pods-framework/pods#5891]
**Describe the bug**
I am using Pods plugin with Ultimate Member free plugin. I have a talent management company and we need our model portfolios to display on the website. The Pods plugin was allowing me to upload and change/remove/add photos to the website through the Ultimate Member plugin profile feature up until about early November 2020. Now, I can add and delete photos, but when I press save and refresh the page, no changes were saved. I cannot save any photos, delete any previously uploaded photos, or make any changes. It is like the plugin is frozen to a point in time.

When I go to the Dashboard > Pods Admin > Edit Pods > User, I tried to change the name of one of the labels from Image Gallery to Portfolio. I clicked the blue Update Field button at the bottom right and the name changes, but if I try to leave the page, a popup says “Reload Site? Changes you made may not be saved.” No matter how many times I press the Update Field button, it does not save any changes.

A piece of information I’ve discovered is that with the Ultimate Member plugin, once I passed 50 pages, the UM plugin made an unexpected change as a result. When I make more than 50 pages, the UM plugin UM > Settings > General will fallback from a dropdown list to a text field. I was thinking that maybe this has something to do with the performance of the Pods plugin, but I have no idea on how to find out for sure.

I have tried contacting UM plugin for some assistance, but they do not know what is going on. Seeing as how the UM profile photo and stats are updating, but the Pods plugin feature (add image gallery) is not working, I am very certain that there is a problem with the Pods plugin.

**To Reproduce**
I don't know.  It was working a few weeks ago, not it is not.

**Screenshots**
https://snipboard.io/Cjag9K.jpg

## Pods Version
Version 2.7.24

## WordPress Environment
Version 5.5.3

Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.

`
### wp-core ###

version: 5.5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 150
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/westhave/public_html/wp
wordpress_size: 51.85 MB (54369587 bytes)
uploads_path: /home/westhave/public_html/wp/wp-content/uploads
uploads_size: 1.26 GB (1354433381 bytes)
themes_path: /home/westhave/public_html/wp/wp-content/themes
themes_size: 4.60 MB (4826334 bytes)
plugins_path: /home/westhave/public_html/wp/wp-content/plugins
plugins_size: 135.12 MB (141685411 bytes)
database_size: 36.45 MB (38223872 bytes)
total_size: 1.48 GB (1593538585 bytes)

### wp-active-theme ###

name: julia (julia)
version: 2.0.9
author: Kayapati
author_website: https://themeforest.net/user/kayapati/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, wp-block-styles, align-wide, custom-background, customize-selective-refresh-widgets, editor-style, woocommerce, custom-header, infinite-scroll, jetpack-responsive-videos, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, header-footer-elementor, widgets
theme_path: /home/westhave/public_html/wp/wp-content/themes/julia
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.5, author: the WordPress team,Auto-updates disabled

### wp-plugins-active (22) ###

Advanced WordPress Backgrounds: version: 1.7.0, author: nK, Auto-updates enabled
Akismet Anti-Spam: version: 4.1.7, author: Automattic, Auto-updates enabled
All-in-One WP Migration: version: 7.30, author: ServMask (latest version: 7.31), Auto-updates disabled
All-in-One WP Migration File Extension: version: 1.6, author: ServMask, Inc., Auto-updates disabled
Blog Designer For Elementor: version: 1.0.0, author: theimran, Auto-updates enabled
Contact Form 7: version: 5.3, author: Takayuki Miyoshi, Auto-updates enabled
Duplicate Page: version: 4.3, author: mndpsingh287, Auto-updates enabled
Elementor: version: 3.0.14, author: Elementor.com, Auto-updates enabled
Elementor - Header, Footer & Blocks: version: 1.5.3, author: Brainstorm Force, Nikhil Chavan, Auto-updates enabled
Elementor - Kaya Widgets: version: 1.0.4, author: Venisha IT Team, Auto-updates disabled
Final Tiles Grid Gallery - Image Gallery: version: 3.4.22, author: MachoThemes, Auto-updates enabled
Image Hover Effects - Elementor Addon: version: 1.3.3, author: Blocksera, Auto-updates disabled
Interactive Geo Maps: version: 1.4.5, author: Carlos Moreira, Auto-updates enabled
Jetpack by WordPress.com: version: 9.2, author: Automattic, Auto-updates enabled
Kirki Customizer Framework: version: 3.1.5, author: David Vongries, Auto-updates disabled
Photoswipe Masonry: version: 1.2.11, author: Web Design Gold Coast, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.7.24, author: Pods Framework Team, Auto-updates disabled
Popup Builder: version: 3.69.6, author: Sygnoos, Auto-updates enabled
Smart Slider 3: version: 3.4.1.14, author: Nextend, Auto-updates enabled
Smash Balloon Instagram Feed: version: 2.6.1, author: Smash Balloon, Auto-updates enabled
Ultimate Member: version: 2.1.12, author: Ultimate Member, Auto-updates enabled
UM - Shortlist Members: version: 1.0.4, author: Kayapati, Auto-updates disabled

### wp-plugins-inactive (10) ###

AccessPress Social Counter: version: 1.9.0, author: AccessPress Themes, Auto-updates disabled
Facebook for WooCommerce: version: 2.0.5, author: Facebook (latest version: 2.2.0), Auto-updates disabled
Google Ads & Marketing by Kliken: version: 1.0.5, author: Kliken (latest version: 1.0.6), Auto-updates disabled
Mailchimp for WooCommerce: version: 2.4.7, author: Mailchimp, Auto-updates disabled
Printful Integration for WooCommerce: version: 2.1.17, author: Printful, Auto-updates enabled
Printify Shipping Method: version: 2.3, author: Printify, Auto-updates enabled
Resize Image After Upload: version: 1.8.6, author: ShortPixel, Auto-updates enabled
WooCommerce: version: 4.7.1, author: Automattic, Auto-updates enabled
WooCommerce Payments: version: 1.7.1, author: Automattic, Auto-updates enabled
WooCommerce Shipping & Tax: version: 1.25.2, author: Automattic (latest version: 1.25.3), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 512M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.36.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.24 64bit
php_sapi: litespeed
max_input_variables: 3000
time_limit: 180
memory_limit: 512M
max_input_time: 180
upload_max_filesize: 512M
php_post_max_size: 256M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/westhave/public_html/wp/wp-content
WP_PLUGIN_DIR: /home/westhave/public_html/wp/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: 184442958
ssl_cert: No
time_diff: 2
version_option: 9.2:1606853626
old_version: 9.1:1606147760
public: Public
master_user: #1 admin
current_user: #1 admin
tokens_set: Blog User
blog_token: @)wLdegO!@jSbAKv)0)lP^2zvEKLkxKR
user_token: o6Q!FKwNS#4nTlhdVv(eA%0(s(1K17Rb
version: 9.2
jp_plugin_dir: /home/westhave/public_html/wp/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Mon, 23 Nov 2020 16:08:58 +0000","finished":"Mon, 23 Nov 2020 16:09:17 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/westhaveninternational.com\/wp","siteurl":"https:\/\/westhaveninternational.com\/wp","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### pods ###

pods-server-software: LiteSpeed
pods-user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 76.876M
pods-memory-current-usage-real: 79.000M
pods-network-wide: No
pods-install-location: /home/westhave/public_html/wp/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

## Pods Package Export (helpful!)
{"meta":{"version":"2.7.24","build":1607130201},"pods":{"10":{"id":10,"name":"user","label":"User","description":"","type":"user","storage":"meta","object":"user","alias":"","fields":{"image_gallery":{"id":11,"name":"image_gallery","label":"Image Gallery","description":"","help":"","class":"um-icon-ios-photos","type":"wysiwyg","weight":0,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"1","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_repeatable":"0","unique":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"videos":{"id":12,"name":"videos","label":"Videos","description":"","help":"","class":"um-icon-videocamera","type":"wysiwyg","weight":1,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"1","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_repeatable":"0","unique":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"audio":{"id":13,"name":"audio","label":"Audio","description":"","help":"","class":"um-icon-ios-musical-note","type":"wysiwyg","weight":2,"pick_object":"","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"1","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_collegehumorcom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","wysiwyg_repeatable":"0","unique":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"contact_us":{"id":5075,"name":"contact_us","label":"Contact Us","description":"Select contact form to get bookings","help":"","class":"um-faicon-phone","type":"pick","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","_elementor_controls_usage":[],"required":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_custom":"[contact-form-7 id=5071 title=Contact form 1]","pick_select_text":"Choose Contact Shortcode form to get bookings","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":1,"_elementor_controls_usage":[],"rest_enable":"0","read_all":"0","write_all":"0"}}}

**Comment by sc0ttkclark** [comment]
After initial review:

1. Ultimate Members does not have direct Pods integration
2. Julia theme (not sure if this was part of the Julia theme or modified) has some custom Pods integration where it runs the code below to get Pods to think it needs to render the Pods profile fields.
3. Pods never hooks into the saving process on this page, the PodsMeta::save_user never gets triggered, which it would normally be triggered when editing a profile page in the admin area since Pods hooks into the `profile_update` action.

Custom Pods integration for UM profile.php template:

```
if( isset($_REQUEST['um_action']) && ( $_REQUEST['um_action'] == 'edit' ) ){
	// Pods user Profile Edit Form
	do_action('edit_user_profile', um_user('ID'));				
}
```

As a result of the review, it appears that Pods was not properly integrated into the profile editor page. It's missing the save mechanism. You noted that the saving of the field values used to work, but I really can't find any reason that it would have worked in the past based on how the Pods profile saving works.
