### ISSUE TITLE
Modals empty after WP Update

### ISSUE THREAD

**Issue by fjenett** [pods-framework/pods#5896]
**Describe the bug**
We recently updated to the latest WP 5.6 and now the modals that appear for related content fields are blank.

**To Reproduce**
1. Install latest WP 5.6
2. Install latest Pods 2.7.24
3. Create a new content type
4. Add a field that has "Relationship" to any existing content type (page, …)
5. Set field to allow to create new (Add New button)
6. Go to new content type and create entry
7. Click "Add New" at the relation field
8. Modal opens and is blank (no form fields there, jus the `<h1>` of the model)

**Expected behavior**
Modal should show the edit form for the related content type

## Pods Version
2.7.24

## WordPress Environment
5.6 DE

**Comment by JoryHogeveen** [comment]
Hi @fjenett 

Found this issue and PR #5893 should fix this!
