### ISSUE TITLE
New Pod form is broken in 5.6

### ISSUE THREAD

**Issue by fjenett** [pods-framework/pods#5897]
This is probably related to #5893 … but reporting anyway.

**Describe the bug**
On the "New Pod" interface / form the input fields are missing. See screenshot. When submitting the form it hence reports missing data and it becomes impossible to create new pods.

**To Reproduce**
- WP 5.6, PF 2.7.24
- Navigate to Pods → Add New → Create New
- (Fields are missing, advanced is broken)
- Click Next Step
- Form reports error that the name of the pod is missing

**Screenshots**
<img width="828" alt="Screenshot 2020-12-11 at 06 38 01" src="https://user-images.githubusercontent.com/59608/101867819-5ac86c80-3b7c-11eb-9a83-0311439dfc06.png">

## Pods Version
2.7.24

## WordPress Environment
5.6 DE

**Possible Workaround**
If you use the type menu to switch to type Custom Taxonomy (or else) the form fields will appear. Switching back to Custom Post Type will fix the form fields and adding new pods is possible.

**Comment by jas8522** [comment]
Patch merged above def fixes this. Thanks!
