### ISSUE TITLE
Support `metadata_by_mid` filters

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5903]
Currently metadata functions that use the metadata ID do not work with Pods.

- `update_metadata_by_mid`
- `get_metadata_by_mid`
- `delete_metadata_by_mid`

Report: https://wordpress.org/support/topic/edit-woocommerce-product-with-relationship-field-with-api-rest/#post-13838071

**Comment by sc0ttkclark** [comment]
I've put together a fix for this as part of the Pods 2.8 code, it's not ready for use yet because it's based on an alpha build of Pods 2.8 -- but tracking it here so it's easy to get to.

https://github.com/pods-framework/pods/pull/5904

**Comment by sc0ttkclark** [comment]
Noting here -- I have only addressed the update integration. The only other part I need to add support for is the delete hooks. I think we don't need the get by mid integration here, but the update/delete are the modification hooks we need most.

**Comment by sc0ttkclark** [comment]
Update/delete implemented via https://github.com/pods-framework/pods/commit/976c2db31874548cefdfa789232aa418b63c831c
