### ISSUE TITLE
Field settings are stored sanitized

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5909]
We modified the sanitation procedure for field values so users can input backlashed without these being removed etc.
This change has created a new bug for field options which now get sanitized but these slashed aren't removed anymore.

Related: https://github.com/pods-framework/pods/pull/5665

We really should take a good look at how we handle post data as at the moment it seems like it gets sanitized/unsensitized on various locations which makes it hard to find errors and create a good fix.

**Comment by YoPrez** [comment]
Can we expect a quick fix ? I updated Pods plugin lately, and had to update one of my pods containing custom 'WHERE' option in relation fields, and now the pod is broken. Updating the pods adds backslashes in option fields with simple quote (same with double quote), that can't be removed. I can't add/update/create any pod of that type, I get an SQL error on the page. My website can't work anymore... :/

**Comment by JoryHogeveen** [comment]
Hi @YoPrez 
You can find an alpha patch here: #5910 
This patch will need all testing possible. If you want, please also test saving regular Post fields and setting page fields made with Pods.
Thanks in advance!

**Comment by cjc1867** [comment]
Hi Jory
I have downgraded to version 2.7.24 and now I can use the clause Where, brilliant, but I cannot now add a New CPT as it doesn't show the Singular Label or Plural label. The Advanced part won't open either so I can't name the CPT.

Any suggestions?

Colin

**Comment by JoryHogeveen** [comment]
Hello @cjc1867 
This is a jQuery issue since WP 5.6. You could re-add jQuery migrate, that might fix it:
https://wordpress.org/plugins/enable-jquery-migrate-helper/

**Comment by cjc1867** [comment]
Hi Jory
I installed the plugin and changed the JQuery to version 1.12.4 and Pods version 2.7.24 is now functioning again.

I have reactivated Version 2.7.26 and thats functioning again and the _Where_ clause is not bringing up any errors.

Well done for this easy solution, hopefully it will get fixed.

Cheers

Colin

**Comment by JoryHogeveen** [comment]
@cjc1867 Did you see my patch as well? #5910

**Comment by mariwnm** [comment]
I have a problem with this one too. Please get that patch out soon!

**Comment by JoryHogeveen** [comment]
@mariwnm Did you test the patch?

**Comment by mariwnm** [comment]
How do I get the patch?

**Comment by JoryHogeveen** [comment]
https://github.com/pods-framework/pods/archive/feature/5909-meta-sanitizing.zip

**Comment by Kukkimonsuta** [comment]
I have tried the patch and it looks good in our use cases 👍

**Comment by quasel** [comment]
did just come up again in slack #support eta on the fix?

**Comment by JoryHogeveen** [comment]
@quasel 
The patch is ready, just needs thorough testing and confirmation it doesn't break anything else!

**Comment by swabhav** [comment]
I have tried the patch, but now getting a new issue default value coming in the post field correctly but when I publish the post it automatically gone.
