### ISSUE TITLE
Field Type Date / Time – No js UI – wrong time

### ISSUE THREAD

**Issue by Juergen74** [pods-framework/pods#5917]
**Describe the bug**

"Date/Time" Field Type seem's buggy.
- Entering a value doesn' show the js UI.
- Typing in a value like 16.01.2021 19:30 is changing after saving to 16.01.2021 19:03

Similar Problems with the Field Type "Time"
- No js UI is showing
- After typing in a value and saving it, the Field is empty.

I've no problems with the "Date" Field Type
- js UI is showing and value remains the same after saving

**To Reproduce**
1. Go to Pods Admin->Edit Pods
2. Add New Pod ("test")
3. Add Field (Date/Time)
4. Add Field (Time)
5. Go to new Menu entry ("test")->Add new
6. enter values in those fields and save

## Pods Version
Please provide the version of Pods you are running: 2.7.26

## WordPress Environment

<details>

### wp-core ###

version: 5.6
site_language: de_DE
user_language: de_DE
timezone: Europe/Berlin
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test
wordpress_size: 46,10 MB (48340195 bytes)
uploads_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/uploads
uploads_size: 639,64 MB (670716205 bytes)
themes_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/themes
themes_size: 79,64 MB (83506139 bytes)
plugins_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/plugins
plugins_size: 30,99 MB (32491540 bytes)
database_size: 34,93 MB (36622336 bytes)
total_size: 831,30 MB (871676415 bytes)

### wp-active-theme ###

name: Enfold Child (theme-child)
version: 3.8.1474964109
author: Kriesi
author_website: http://www.kriesi.at
parent_theme: Enfold (enfold)
theme_features: core-block-patterns, avia_exclude_bbPress, deactivate_tribe_events_calendar, avia_exclude_GFForms, avia_exclude_menu_exchange, avia_exclude_relevanssi, avia_exclude_WooCommerce, avia_exclude_wpSEO, avia_exclude_wpml, avia_exclude_instagram_feed, avia_mega_menu, avia_improved_backend_style, avia_option_pages_toggles, avia_sidebar_manager, automatic-feed-links, nav_menus, menus, widgets, post-formats, avia-disable-default-shortcodes, avia_post_meta_compat, force-post-thumbnails-in-widget, post-thumbnails, title-tag, editor-styles, editor-style, customize-selective-refresh-widgets, responsive-embeds, editor-color-palette, editor-font-sizes, avia_no_session_support
theme_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/themes/theme-child
auto_update: Deaktiviert

### wp-parent-theme ###

name: Enfold (enfold)
version: 4.7.6.4
author: Kriesi
author_website: https://kriesi.at
theme_path: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/themes/enfold
auto_update: Deaktiviert

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.1, author: WordPress-Team, Automatische Aktualisierungen deaktiviert

### wp-plugins-active (13) ###

Aidenried Kalender: version: 1.0, author: IQONOMY, Automatische Aktualisierungen deaktiviert
API KEY for Google Maps: version: 1.2.0, author: GeoDirectory, Automatische Aktualisierungen deaktiviert
Better Search Replace: version: 1.3.4, author: Delicious Brains, Automatische Aktualisierungen deaktiviert
Contact Form 7: version: 5.3.2, author: Takayuki Miyoshi, Automatische Aktualisierungen deaktiviert
Disable Comments: version: 2.0.2, author: WPDeveloper, Automatische Aktualisierungen deaktiviert
GDPR Cookie Consent: version: 1.9.5, author: WebToffee, Automatische Aktualisierungen deaktiviert
iThemes Security Pro: version: 6.6.0, author: iThemes, Automatische Aktualisierungen deaktiviert
Newsletter: version: 7.0.2, author: Stefano Lissa & The Newsletter Team, Automatische Aktualisierungen deaktiviert
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team, Automatische Aktualisierungen deaktiviert
Simple 301 Redirects: version: 1.07, author: Scott Nellé, Automatische Aktualisierungen deaktiviert
UberMenu 3 - The Ultimate WordPress Mega Menu: version: 3.2.5, author: Chris Mavricos, SevenSpark, Automatische Aktualisierungen deaktiviert
WP Real Media Library: version: 2.4, author: Matthias Günter, Automatische Aktualisierungen deaktiviert
Yoast Duplicate Post: version: 4.0.1, author: Enrico Battocchi & Team Yoast, Automatische Aktualisierungen deaktiviert

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1686
imagemagick_version: ImageMagick 6.9.6-2 Q16 x86_64 2020-08-31 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 48M
upload_max_filesize: 48M
max_effective_size: 48 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 32 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 1920
	imagick::RESOURCETYPE_MAP: 32 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 20.2.0 x86_64
httpd_software: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.9 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
php_version: 7.4.9 64bit
php_sapi: apache2handler
max_input_variables: 1600
time_limit: 180
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 48M
php_post_max_size: 48M
curl_version: 7.68.0 OpenSSL/1.0.2u
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.30
client_version: mysqlnd 7.4.9

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content
WP_PLUGIN_DIR: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.9 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0
pods-session-save-path: /Applications/MAMP/tmp/php
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 77,913M
pods-memory-current-usage-real: 10,500M
pods-network-wide: No
pods-install-location: /Users/jonny/Sites/www.apr-ammersee.de/wordpress_test/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment]
Hi @Juergen74 

This is most likely related to the WP core's jQuery update.
We use jQuery Timepicker for this and this might not be fully compatible with the latest jQuery.
Unfortunately this timepicker addon isn't in development anymore.

I'd advice to use the HTML5 field type!

Cheers, Jory

**Comment by Juergen74** [comment]
Hey Jory, thanks for the quick replay.
I've tested the HTML5 field type but I'm having the same Problems.
Entering a Date/Time into a field and saving it chages the time.

**Comment by Juergen74** [comment]
Ok, found some things:
After switching another plugin off – most of the problems are gone... :D
js Datepicker and Timepickers are working fine.

But the Date/Time Picker is showing the Time Format (standard in German Wordpress-Setting: G:i) instead of the Time! See Images:

Wordpress Settings:
![Bildschirmfoto 2021-01-13 um 09 43 23](https://user-images.githubusercontent.com/11347951/104429226-ac05ba80-5585-11eb-9a62-fc941a92bc4d.png)

My Custom Fields:
![Bildschirmfoto 2021-01-13 um 09 45 33](https://user-images.githubusercontent.com/11347951/104429498-f71fcd80-5585-11eb-9b20-8ea907d88cb0.png)

In Edit Pods -> Field options  I switched "Time Format Type"  from "WordPress default: 10:03" to "24 hour"
**Now it's working.** 👯 

Edit Pods-> Field options:
![Bildschirmfoto 2021-01-13 um 09 41 46](https://user-images.githubusercontent.com/11347951/104430318-cee49e80-5586-11eb-9ac2-68309eb9983f.png)

(Needed to add the line "define('SCRIPT_DEBUG', true )" to the "wp-config.php" to use not minified javascripts...)
I found that the time-format "G:i" is not handled in the javascript:
<img width="1383" alt="Bildschirmfoto 2021-01-13 um 09 50 35" src="https://user-images.githubusercontent.com/11347951/104430631-3995da00-5587-11eb-96ca-d5127f7ac3c8.png">

So there seems to be a Problem within "datetime.php" around this line, I think.
<img width="1114" alt="Bildschirmfoto 2021-01-13 um 09 49 21" src="https://user-images.githubusercontent.com/11347951/104431308-0acc3380-5588-11eb-8987-8ec9c79e41fd.png">

Maybe I could help!
Cheers, Jürgen

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Maybe close this as we do not use the jQuery timepicker anymore
