### ISSUE TITLE
Dynamic Tag {@get.any} is not working

### ISSUE THREAD

**Issue by elviejoloco** [pods-framework/pods#5922]
## Issue Overview
Dynamic Tag {@get.any} is not working with the latests update.

## Current Behavior
no data from url variable

## WordPress Environment
WordPress Version: 5.6
PHP Version: 7.3.26
MySQL Version: 5.7.26

**Comment by JoryHogeveen** [comment]
Hi @elviejoloco 

I just tried using the `any` get variable locally and it's working fine.
Please provide a full bug report and not just "it isn't working" so I can help you better or can try to reproduce your situation. We ask these questions for a reason ;)

Cheers, Jory

**Comment by elviejoloco** [comment]
Hi Jory!! Thanks for your quick response. Sorry about my light report, it's my first report :)

Because I needed to show the site to my client today, I've restore a backup of database and files, so now I have the previous version of Pods (2.7.25) and the dynamic tag {@get.any} is working ok now. I'll try to install a new site to reproduce the situation.

Thanks again, for your patience and you quick response.

Have a good day!

**Comment by elviejoloco** [comment]
Hi Jory!! sorry about my report, was my fault: I deleted this code by mistake... define('PODS_SHORTCODE_ALLOW_EVALUATE_TAGS',true);

Cheers

**Comment by JoryHogeveen** [comment]
Hi @elviejoloco 
Ah no problem, thanks for letting me know!
