### ISSUE TITLE
infinity loop on change status to trash

### ISSUE THREAD

**Issue by vitmarks** [pods-framework/pods#5924]
**Describe the bug**
endless loop while triying to trash an item. OR to "pods->save" post_status to trash

**To Reproduce**
Created new CPT "deliverypoint" and Storage type Table.
CTP contains nothing special as fields.
I created 800 deliverypoints and on edit.php?post_type=deliverypoint
I tried to trash some of them. I always got this error: error allowed memory size of bytes exhausted
I figured out, that the PodsAPI.php->save_pod_item($params) was the problem.
the call -> $params->id = $this->save_wp_object($object_type, $object_data, $meta_fields, false, true, $fields_to_send);
tried to send the same $object_data with the same values over and over again.

**Expected behavior**
no endless loop

## Pods Version 
2.7.26

## WordPress Environment
5.6
php8.0-fpm

**Possible Workaround**

for now I fixed it by checking last run. Not a good fix but for now it works

if (!key_exists('last_pod_save_wp_object', $GLOBALS) || $GLOBALS['last_pod_save_wp_object'] !== $object_data) {
                $GLOBALS['last_pod_save_wp_object'] = $object_data;
                $params->id = $this->save_wp_object($object_type, $object_data, $meta_fields, false, true, $fields_to_send);
            }

hope it helps

**Comment by vitmarks** [comment]
Forget my workaround, after 2 days I removed it and no problems anymore. you can close it i think

**Comment by JoryHogeveen** [comment]
This was most likely a plugin conflict.
https://docs.pods.io/faqs/plugin-theme-conflicts/
