### ISSUE TITLE
Custom Field cant be made unique

### ISSUE THREAD

**Issue by kbachl** [pods-framework/pods#5925]
if you follow pods doc here:
https://pods.io/docs/learn/what-are-custom-fields/

you see Option to make the Number field required as well as unique on screenshot. However, when you add a new Field to a pod, you are only able to make it required, not unique.

Either this has to be that you need additional prerequesites for this to happen, then this has to be added to the documentation page or it is a bug.

**Comment by JoryHogeveen** [comment]
Hello @kbachl 

Honestly, I wasn't aware of this feature and believe this is an old legacy feature.
@sc0ttkclark can you elaborate?

**Comment by sc0ttkclark** [comment]
I believe this only ever worked for Advanced Content Types, but I can check into it today.

**Comment by sc0ttkclark** [comment]
This feature requires table storage set for the Pod or an Advanced Content Type.
