### ISSUE TITLE
Extending WP Coupon Plugins, new fields not displaying

### ISSUE THREAD

**Issue by mungbeen** [pods-framework/pods#5927]
**Describe the bug**

Attempting to extend two WP coupon plugins but adding the ability to embed content via url/iframe etc. Only the default coupons show up, but not the extended Pod fields (website, oEmbed)

**To Reproduce**

**Expected behavior**

In the extended coupon form, I would be able to enter coupon details, and copy/paste a provided embed URL into the corresponding Pod website/oEmbed field, and when published the coupon would display along with the embedded media

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 

2.7.26

## WordPress Environment

<details>

`
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 12
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Bitnami\wordpress\apps\wordpress\htdocs
wordpress_size: 145.40 MB (152461121 bytes)
uploads_path: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content/uploads
uploads_size: 461.35 KB (472423 bytes)
themes_path: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content/themes
themes_size: 12.80 MB (13423857 bytes)
plugins_path: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content/plugins
plugins_size: 78.67 MB (82487704 bytes)
database_size: 11.25 MB (11796480 bytes)
total_size: 248.57 MB (260641585 bytes)

### wp-active-theme ###

name: BuddyX (buddyx)
version: 3.6.0
author: wbcomdesigns,vapvarun
author_website: https://github.com/vapvarun/buddyx
parent_theme: none
theme_features: core-block-patterns, custom-logo, automatic-feed-links, title-tag, html5, customize-selective-refresh-widgets, responsive-embeds, custom-header, custom-background, editor-styles, wp-block-styles, align-wide, editor-color-palette, editor-font-sizes, amp, service_worker, menus, post-thumbnails, editor-style, lifterlms-sidebars, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, buddypress-use-nouveau, widgets
theme_path: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content/themes/buddyx
auto_update: Disabled

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.6, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (10) ###

Affiliate Coupons: version: 1.6.0, author: Affiliate Coupons, Auto-updates disabled
BadgeOS: version: 3.6.9, author: LearningTimes, Auto-updates disabled
BadgeOS Community Add-On: version: 1.2.10, author: Credly, Auto-updates disabled
BuddyBoss Platform: version: 1.5.6, author: BuddyBoss, Auto-updates disabled
BuddyBoss Products Updater: version: 1.2.8, author: BuddyBoss, Auto-updates disabled
Kirki Customizer Framework: version: 3.1.6, author: David Vongries, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team, Auto-updates disabled
Visual Link Preview: version: 2.1.0, author: Bootstrapped Ventures, Auto-updates disabled
WP Coupons and Deals: version: 3.0.4, author: WP Coupons and Deals, Auto-updates disabled
WPForms Lite: version: 1.6.4.1, author: WPForms, Auto-updates disabled

### wp-plugins-inactive (5) ###

Akismet Anti-Spam: version: 4.1.8, author: Automattic, Auto-updates disabled
All-in-One WP Migration: version: 7.33, author: ServMask, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Kaya QR Code Generator: version: 1.4.2, author: Kaya Studio, Auto-updates disabled
Nextend Social Login: version: 3.0.26, author: Nextendweb, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 40M
upload_max_filesize: 40M
max_effective_size: 40 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache
php_version: 7.4.10 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 300
upload_max_filesize: 40M
php_post_max_size: 40M
curl_version: 7.70.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.21
client_version: mysqlnd 7.4.10

### wp-constants ###

WP_HOME: http://localhost/wordpress
WP_SITEURL: http://localhost/wordpress
WP_CONTENT_DIR: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content
WP_PLUGIN_DIR: C:\Bitnami\wordpress\apps\wordpress\htdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wpforms ###

version: 1.6.4.1
lite: Oct 12, 2020 @ 1:42am
upload_dir: Writable
db_tables: wp_wpforms_tasks_meta
total_forms: 1
total_submissions: undefined

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
pods-session-save-path: C:/Bitnami/WORDPR~1/php/tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 13.658M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: C:\Bitnami\wordpress\apps\wordpress\htdocs\wp-content\plugins\pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.

</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.26","build":1611715462},"pods":{"822":{"id":822,"name":"affcoups_coupon","label":"Affcoups Coupon","description":"","type":"post_type","storage":"meta","object":"affcoups_coupon","alias":"","fields":{"embed_content_2":{"id":823,"name":"embed_content_2","label":"Embed via url","description":"Embed social media content","help":"","class":"","type":"website","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","oembed_enabled_providers_localhost":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"test_embed_iframe":{"id":845,"name":"test_embed_iframe","label":"test embed iframe","description":"","help":"","class":"","type":"oembed","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","oembed_width":"0","oembed_height":"0","oembed_show_preview":"1","oembed_restrict_providers":"0","oembed_enabled_providers_amazoncn":"0","oembed_enabled_providers_amazoncouk":"0","oembed_enabled_providers_amazoncom":"0","oembed_enabled_providers_amazoncomau":"0","oembed_enabled_providers_amazonin":"0","oembed_enabled_providers_animotocom":"0","oembed_enabled_providers_cloudupcom":"0","oembed_enabled_providers_crowdsignalcom":"0","oembed_enabled_providers_dailymotioncom":"0","oembed_enabled_providers_flickrcom":"0","oembed_enabled_providers_imgurcom":"0","oembed_enabled_providers_issuucom":"0","oembed_enabled_providers_kickstartercom":"0","oembed_enabled_providers_meetupcom":"0","oembed_enabled_providers_mixcloudcom":"0","oembed_enabled_providers_redditcom":"0","oembed_enabled_providers_reverbnationcom":"0","oembed_enabled_providers_screencastcom":"0","oembed_enabled_providers_scribdcom":"0","oembed_enabled_providers_slidesharenet":"0","oembed_enabled_providers_smugmugcom":"0","oembed_enabled_providers_someecardscom":"0","oembed_enabled_providers_soundcloudcom":"0","oembed_enabled_providers_speakerdeckcom":"0","oembed_enabled_providers_spotifycom":"0","oembed_enabled_providers_tedcom":"0","oembed_enabled_providers_tiktokcom":"0","oembed_enabled_providers_tumblrcom":"0","oembed_enabled_providers_twittercom":"0","oembed_enabled_providers_vimeocom":"0","oembed_enabled_providers_wordpresscom":"0","oembed_enabled_providers_wordpresstv":"0","oembed_enabled_providers_youtubecom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_repeatable":"0"},"test_media":{"id":846,"name":"test_media","label":"test media","description":"","help":"","class":"","type":"file","weight":2,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":1,"pfat_enable":"1","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_excerpt","pfat_run_outside_loop":"0","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"affcoupon embed template","pfat_archive":"affcoupon embed template"},"815":{"id":815,"name":"wpcd_coupons","label":"Wpcd Coupons","description":"","type":"post_type","storage":"meta","object":"wpcd_coupons","alias":"","fields":{"test_embed_code_field":{"id":836,"name":"test_embed_code_field","label":"embed via iframe","description":"","help":"","class":"","type":"oembed","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","oembed_width":"0","oembed_height":"0","oembed_show_preview":"1","oembed_restrict_providers":"0","oembed_enabled_providers_amazoncn":"0","oembed_enabled_providers_amazoncouk":"0","oembed_enabled_providers_amazoncom":"0","oembed_enabled_providers_amazoncomau":"0","oembed_enabled_providers_amazonin":"0","oembed_enabled_providers_animotocom":"0","oembed_enabled_providers_cloudupcom":"0","oembed_enabled_providers_crowdsignalcom":"0","oembed_enabled_providers_dailymotioncom":"0","oembed_enabled_providers_flickrcom":"0","oembed_enabled_providers_imgurcom":"0","oembed_enabled_providers_issuucom":"0","oembed_enabled_providers_kickstartercom":"0","oembed_enabled_providers_meetupcom":"0","oembed_enabled_providers_mixcloudcom":"0","oembed_enabled_providers_redditcom":"0","oembed_enabled_providers_reverbnationcom":"0","oembed_enabled_providers_screencastcom":"0","oembed_enabled_providers_scribdcom":"0","oembed_enabled_providers_slidesharenet":"0","oembed_enabled_providers_smugmugcom":"0","oembed_enabled_providers_someecardscom":"0","oembed_enabled_providers_soundcloudcom":"0","oembed_enabled_providers_speakerdeckcom":"0","oembed_enabled_providers_spotifycom":"0","oembed_enabled_providers_tedcom":"0","oembed_enabled_providers_tiktokcom":"0","oembed_enabled_providers_tumblrcom":"0","oembed_enabled_providers_twittercom":"0","oembed_enabled_providers_vimeocom":"0","oembed_enabled_providers_wordpresscom":"0","oembed_enabled_providers_wordpresstv":"0","oembed_enabled_providers_youtubecom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","oembed_repeatable":"0"},"test_embed_url":{"id":843,"name":"test_embed_url","label":"test embed url","description":"","help":"","class":"","type":"website","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""}},"show_in_menu":1,"pfat_enable":"1","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_excerpt","pfat_run_outside_loop":"0","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"wpcd embed template","pfat_archive":"wpcd embed template"}},"templates":{"wpcd embed template":{"id":837,"name":"wpcd embed template","code":"<div> test embed url: {@test_embed_url}<\/div>\r\n<div> test embed iframe: {@test_embed_code_field}<\/div>","type":"template","slug":"wpcd-embed-template","options":{"_badgeos_not_earned_thumbnail":"777","_edit_lock":"1611715284:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","show_restrict_message":"1","restrict_message":"","pod_reference":"a:1:{s:3:\"pod\";s:12:\"wpcd_coupons\";}","_point_plural_name":"wpcd embed template","_badgeos_plural_name":"wpcd embed template"}},"affcoupon embed template":{"id":847,"name":"affcoupon embed template","code":"<div> test url: {@embed_content_2}<\/div>\r\n<div> test iframe: {@test_embed_iframe}<\/div>\r\n","type":"template","slug":"affcoupon-embed-template","options":{"_badgeos_not_earned_thumbnail":"777","_edit_lock":"1611715243:1","_edit_last":"1","admin_only":"","restrict_capability":"","capability_allowed":"","show_restrict_message":"1","restrict_message":"","pod_reference":"a:1:{s:3:\"pod\";s:15:\"affcoups_coupon\";}","_point_plural_name":"affcoupon embed template","_badgeos_plural_name":"affcoupon embed template"}}}}
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment]
Hi @mungbeen 

I recall your topic on wp.org and when reading this I might have found the issue.

Aren't these coupons related to a product or other page? Or do these coupons have their own detail page?
If they have their own page, could you provide us with an example?
If they are embedded in another page (as a list of coupons for example) then I'm quite sure the auto-templating functionality of Pods won't work.

Let me know!

**Comment by JoryHogeveen** [comment]
Hi @mungbeen 

Both plugins seem to use custom templates for their coupons. I'm confident that you should be able to overwrite these templates and add the Pods template in here.
However, I don't see any hooks within the template you could use so you really should contact the coupon plugin authors on how to best proceed with this.

Good luck! Closing topic here :)

**Comment by mungbeen** [comment]
Thanks for working with me on this, Jory. I will investigate with the coupon plugin maintainers, I hope they are as responsive as you are!

Can Pods be made to work with post types that don't have pages, like in this case? And if so, are there plans to add that support?

Also, when extending the coupon posts wasn't working, I tried creating a new post type with the assumption of possibly adding the coupon fields (available fields from the coupon plugins) to the new post type. Obviously, this capability is not a part of Pods, but I wonder if this is at all possible and a potential solution to the above post-no-page problem too.  It would almost be a reverse-extend, and more of a create-import, where you create a new Pod but can import/use fields from other post types.

Thoughts?

**Comment by JoryHogeveen** [comment]
> Can Pods be made to work with post types that don't have pages, like in this case? And if so, are there plans to add that support?

Only if it works with the loop (like archive pages).
Otherwise it won't automatically work with auto-templates. You'll need to add your own code to load and show the templates.

> Also, when extending the coupon posts wasn't working, I tried creating a new post type with the assumption of possibly adding the coupon fields (available fields from the coupon plugins) to the new post type. Obviously, this capability is not a part of Pods, but I wonder if this is at all possible and a potential solution to the above post-no-page problem too. It would almost be a reverse-extend, and more of a create-import, where you create a new Pod but can import/use fields from other post types.

No, when extending a post type we do not overwrite any settings for this post type. If detail or archive pages are disabled than they will still be disabled after extending.
Also keep in mind that plugin authors can force-disable detail pages etc. by code.

Cheers, Jory
