### ISSUE TITLE
Design overhaul

### ISSUE THREAD

**Issue by kilianso** [pods-framework/pods#5930]
Hello all! 
I think Pods and its features, as well as the active development behind it, are really outstanding. 

Unfortunately, the current design of the plugin and website does not reflect the quality of Pods. While the plugin has constantly evolved on the code and feature side, improvements to the design fell short.

I know, we as developers may prefer not to deal with design. But from a user experience perspective, it is very important that such a product has an appealing, usable, and sophisticated design. 

Are there any plans in this direction? Is there anyone currently responsible for design decisions? Are you currently looking for support in this field at all?

Keep up to good work!

**Comment by sc0ttkclark** [comment]
I've been leading the charge for Pods 2.8 as we revamp our new Groups functionality.

The only page getting a redesign as part of this is the Edit Pod screen.

I'd love more design direction or ideas from other people on any area of Pods. I'm always very eager to get Pods looking as great as it can. I'm not at my computer but I'll send you a screencast here when I get on today and you can see how the 2.8 screen works.

**Comment by kilianso** [comment]
Hey @sc0ttkclark 

Sounds great, would like to look at it! 

I think in terms of inputs, buttons and so on, Pods could stick with the latest default Wordpress styles. So it always visually matches the rest of the Wordpress interface.

But I think spacial patterns and the introduction screen, the screenshots, the website should get a redesign.

**Comment by sc0ttkclark** [comment]
Check out the demo here: https://training.ithemes.com/webinar/the-power-of-pods-2-8-and-pods-pro/

Pods 2.8 Beta will be released today as soon as I get the release post and testing instructions put together.

**Comment by sc0ttkclark** [comment]
Pods 2.8 will be released on October 11th and the new Pods site revamp went out this month 🎉
