### ISSUE TITLE
[Pods 2.8] Make i18n component compatible with new admin UI

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5939]
Currently the i18n component isn't compatible with the newer react UI in Pods 2.8.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen can you walk me through what issues you need to address here and maybe I can figure out how we can work around this by introducing the config options needed.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark I haven't really looked at the backend-side of the new react UI so I'm not sure what to say. However, the current situation is that for translations all fields for other languages aren't shown anymore.
Previously I did this through filters and then adding the i18n fields, see here:
- Filter: https://github.com/pods-framework/pods/blob/main/components/I18n/I18n.php#L165
- Function: https://github.com/pods-framework/pods/blob/main/components/I18n/I18n.php#L867

I doubt this will work for react based UI.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Hit me up when you are able to, I can walk you through the proper filters to use for adding new pod/group/field tabs and fields to the new editor.

**Comment by sc0ttkclark** [comment]
I think we can close this now via #6095
