### ISSUE TITLE
[Pods 2.8 Bug] Help tooltips missing

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5941]
## Pods 2.8 version

2.8.0-b-1

## Description

All help tooltips are missing in the admin interface (both fields and Pod options)

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Can you confirm they are all showing up as expected now in `release/2.8`?

**Comment by JoryHogeveen** [comment]
Yep!
