### ISSUE TITLE
[Pods 2.8 Bug] testing on site using WPML gives error

### ISSUE THREAD

**Issue by carlosrovira** [pods-framework/pods#5945]
## Pods 2.8 version

version of Pods 2.8 running is: "2.8.0-b-1"

## Description

Seems Pods 2.8 is not ready to use in production with WPML. I updated the plugin in our preproduction site and we are getting this:

string(1196) "Database Error; SQL: SELECT
                
                DISTINCT
                `t`.*
                FROM `wp_posts` AS `t`
                
                    LEFT JOIN `wp_postmeta` AS `director` ON
                        `director`.`meta_key` = 'director'
                        AND `director`.`post_id` = `t`.`ID`
                
                
						LEFT JOIN `wp_icl_translations` AS `wpml_translations`
							ON `wpml_translations`.`element_id` = `t`.`ID`
								AND `wpml_translations`.`element_type` = 'post_empleado'
								AND `wpml_translations`.`language_code` = 'en'
					
                
						LEFT JOIN `wp_icl_languages` AS `wpml_languages`
							ON `wpml_languages`.`code` = `wpml_translations`.`language_code` AND `wpml_languages`.`active` = 1
					
                WHERE ( ( `director`.`meta_value` = 1 ) AND ( `t`.`post_type` = "empleado" ) AND ( `wpml_languages`.`code` IS NOT NULL ) AND ( `t`.`post_status` IN ( "publish" ) ) )
                
                
                ORDER BY `order`.`meta_value` ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
                LIMIT 0, 15; Response: Unknown column 'order.meta_value' in 'order clause'"

Just copied one of the errors. In that page you'll see one more.

## Testing instructions

To see the problem in action check our preproduction site here: https://webpre.codeoscopic.com/en/group/

and you'll see the string above printed on the page.

Also in the "Management Team" section is empty. There we should get the management team employees info and then below a list of employees info.

This problem can be seen in the rest of pages using pods like "investors" and "clients", and "work with us" (link in the footer). In this one I see a reduced error:

string(20) "Objeto no encontrado" 

That means "Object not found", so this could be related to pods not using now "Object"

 
## Expected behavior

just to work as before. You can see the right output here in the production site with released pods version: https://codeoscopic.com/en/group/

In the current status I'll not be able to upgrade from pods 2.7 to 2.8. Hope a solution could be found in this beta time frame.

## Possible workaround

No one found

## Other super helpful information

WPML is using the all plugins at its latest official released version.

Thanks

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
Might be best to remove WPML code from our API and use filters for this?
That way we can make separate WPML / Polylang / Others classes for integration.

**Comment by carlosrovira** [comment]
I think that will not solve the current problem and will make hundreds of WPML webs out there unable to upgrade to 2.8. A major change like that will make sense in a 3.0 release with sufficient plan to provide the alternative and a migration plan, but just removing WPML support from 2.8 seems to me like a bad movement for this project.

**Comment by JoryHogeveen** [comment]
Hi @carlosrovira 
I'm not talking about removing WPML support. I'm talking about refactoring this part so it's easier to manage.

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen , ok thanks. In that case, if it's a refactor to be better handled, then that will be cool. But maybe that will mean it could be possible for 2.8 timeframe?, or we'll need to wait to update? 
Thanks

**Comment by sc0ttkclark** [comment]
@JoryHogeveen that pathway sounds good to me

**Comment by carlosrovira** [comment]
Hi @sc0ttkclark and @JoryHogeveen, please, if you can share whatever plan or time frame that will be good to know what to expect. If I need to freeze in 2.7 for sometime or I can expect to try 2.8 for WPML support. Thanks for your support!

**Comment by JoryHogeveen** [comment]
Hi @carlosrovira 
Took a closer look at the error and was wondering:
- Where/How is this query called in your code? Is this a Pods shortcode or something?
- Any idea where the property `order` is coming from. It looks like a custom field is included or something.
Cheers, Jory

**Comment by carlosrovira** [comment]
Hi,

yes, in that page I have 2 shortcodes:
`[pods name="empleado" orderby="order" where="director.meta_value = 1" template="EquipoDirectivo"]`

and

`[pods name="empleado" where="director.meta_value = 0" orderby="nombre.meta_value" template="Equipo" limit="40"]`

Then `order` is a field of not formated number in the pod `empleado`.

HTH

Carlos

**Comment by JoryHogeveen** [comment]
Hi @carlosrovira 

If `order` is a field in the Pod `empleado` then you should use it as metadata: `order.meta_value`.
Keep in mind that you might need to order as numeric: https://stackoverflow.com/questions/489874/sql-order-chars-numerically

Cheers. Jory

**Comment by carlosrovira** [comment]
Hi Jory,

I'm understand correctly that change 1 of the pods above to this:

`[pods name="empleado" orderby="order.meta_value" where="director.meta_value = 1" template="EquipoDirectivo"]`

I tried, but seems not to fix the issue, or is just a fix to be done but separated from the WPML problem?

Thanks for your help

**Comment by JoryHogeveen** [comment]
@carlosrovira 

Sorry for my late reply.
But no, I mean that the `order` as a value for `orderby` isn't correct unless `order` is an actual field in your Pod.
However, it looks like `nombre` is your order field or am I incorrect in assuming this?

**Comment by JoryHogeveen** [comment]
@carlosrovira Could you test the following PR: #6155

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen, I have currently a problem in the pre server where I can test it. I have it in my backlog for several days. Will try to fix this weekend and try it, and back here with my findings. Thanks

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen, after working several hours in the last weekend, I could solve my test server issues. Sorry to be late, but I need to migrate some webs to other server, upgrade SO, PHP, and even install packages that was not considered some years ago until get things working. I finally have the site up in the same state as production.

So from there, I updated Pods to latest RC1 downloading the zip and switching from the latest stable.

I found some things are solved since last time but we have still critical issues. Note that I have WP_DEBUG enabled and also I tried to remove pods cache to ensure issues was not coming from any stale state.

We have basically 3 pages that use Pods (Groups, Investors and Clients), and we have just 2 languages in WPML: Spanish (ES) and English (EN). 

Here's my findings:

1.- In "Group" page, ES version is working fully as expected, but EN version don't show the pods parts: you can check https://webpre.codeoscopic.com/es/grupo/ vs https://webpre.codeoscopic.com/en/group/

2.- The same thing happens in "Investor" page.

3.- "Clients" page is not working at all and is reporting lots of issues that you can see printed in screen: https://webpre.codeoscopic.com/es/clientes/

Maybe I need to update some code, but I thing that should not be necessary since if the page is working in 2.7, it should be ok in 2.8 for a smooth transition. So I didn't try the change you proposed on Mar, 9, since at that time I have the server unoperative due to all the issue I said before. Also I didn't understand really what need to be changed.

I'm open to help trying things, and also we can talk if you need to operate in my pre instalation.

HTH

Carlos

**Comment by carlosrovira** [comment]
hi, 

In En admin page I get this log:

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 422

**Comment by JoryHogeveen** [comment]
Hi @carlosrovira 

Before we continue, did you test on the latest RC or with the integration patch?
By looking at your errors it seems that you've tested on the RC version, not the integration patch.
Please make sure you test on the patch:
Patch PR: https://github.com/pods-framework/pods/pull/6155
Patch download ZIP: https://github.com/pods-framework/pods/archive/refs/heads/feature/2.8/i18n-integration.zip

As for your findings.
Please always also share how your results are fetched. Eg, your shortcode or template code. Otherwise it's very difficult or even impossible for me to find the issue.

Let me know!

Cheers, Jory

**Comment by JoryHogeveen** [comment]
What kind of error do you get?

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen seems a false positive and related to run out of space. Tomorrow will see more about it. Sorry. Will come back when I know more

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen, I just do a severe clean up on the server to get free space and was able to upload the pods with the patch you told me.

Sorry but the patch doesn't seem to make any different with the three issues I already commented  before. Also in the wp I continue seeing this:

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

**Comment by carlosrovira** [comment]
About how I fetch results:

1.- In grupo (ES) / group (EN) page:

[pods name="empleado" orderby="order.meta_value" where="director.meta_value = 1" template="EquipoDirectivo"]
[pods name="empleado" where="director.meta_value = 0" orderby="nombre.meta_value" template="Equipo" limit="40"]

2.- In Inversores (ES) / Investors (EN) page:

[pods name="testimonio" slug="jon-doe" template="Testimonio-Inversor"]
[pods name="testimonio" slug="some-man" template="Testimonio-Inversor"]
[pods name="testimonio" slug="jon-doe2" template="TestimonioCliente-Foto"]
[pods name="testimonio" slug="jon-doe2" template="TestimonioCliente-Frase"]

3.- In Clientes (ES) / Clients (EN) page:

[pods name="testimonio" limit="3" template="TestimonioCliente-Foto" where="tipo.meta_value = 'INSURER'"  orderby="nombre.meta_value"]
[pods name="testimonio" limit="3" template="TestimonioCliente-Frase" where="tipo.meta_value = 'INSURER'"  orderby="nombre.meta_value"]

 [pods name="testimonio" limit="3" template="TestimonioCliente-Foto" where="tipo.meta_value = 'BROKER'"  orderby="nombre.meta_value"]
 [pods name="testimonio" limit="3" template="TestimonioCliente-Frase" where="tipo.meta_value = 'BROKER'"  orderby="nombre.meta_value"]

(I changed a bit labels to avoid give sensible data of real names and companies)

I think that's all the pods I use in the three pages

HTH

**Comment by carlosrovira** [comment]
Here's Pods Templates:

### EquipoDirectivo

<li>
   <a href="{@profile}" target="_blank" class="main_content" rel="noopener noreferrer">
      <span class="user" style="background-image: url('{@foto._src}');"></span>
      <span class="name">{@nombre}</span>
      <span class="role">{@puesto}</span>
   </a>
</li>

### Equipo

<li>
   <div class="main_content">
      <div class="tooltip_user">
          <span class="name">{@nombre}</span>
          <span class="role">{@puesto}</span>
      </div>
      <span class="user" style="background-image: url('{@foto._src}'"></span>
   </div>
</li>

### Testimonio-Inversor

<div class="left_content" style="background-image: url('{@facefoto._src}');"></div>
<div class="right_content">
  <div class="main_comment">
    <p class="quote"><img class="figure" src="/wp-content/uploads/XXX/YY/quotes.svg"/>{@post_content}</p>
    <div class="profile">
      <span class="name">{@post_title}</span>
      <span class="role">{@puesto}</span>
    </div>
  </div>
</div>

### TestimonioCliente-Foto

<li><span class="user" style="background-image: url('{@facefoto._src}');"></span></li>

### TestimonioCliente-Frase

<section>
   <p>{@post_content}</p>
   <div class="info">
      <span class="name">{@post_title}</span>
      <span class="role">{@puesto}</span>
	  [if puesto-subtitulo]<span class="text">{@puesto-subtitulo}</span>[/if]
   </div>
</section>

**Comment by carlosrovira** [comment]
Don't know if this could help, but maybe providing a RC3 with the WPML patch could fix the issue? If you give me a link I can try and report
thanks

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen 

you must consider that the starting point is a website already working in production with current release (2.7.x), so unless there are functional changes in Pods that require implementation changes, all should be working in the current state.

Now, for your questions, how can I check the queries generated by shortcodes?. My pods knowledge doesn't reach that point. If you can point me on how to check that, I can return with my findings.

As I told before, I think at this point could very hard to debug the problem without taking a look at it. I'm available to do a meeting and check the site or even give you credientals so you can "get your hands dirty" in the pre site to see what could be the bug.

About 'INSURER' is just a pods field to categorize, so it's not translated. All translation uses that "keys" so when can query in any language.

Regarding templates. Since all templates doesn't need localization because is just html markup, we only use the same for both languages, and WPML is configured to output the same for all translation. That's the way it works in production. Only one template needs localization and in that case we have  the two versions (EN and ES) and that pod is configured to use the proper language in each case

Thanks for your help

Carlos

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen 

Checking the same url in pro and pre sites throws a significant difference:

## PRESITE

```
 SELECT
                
                DISTINCT
                `t`.*
                FROM `wp_posts` AS `t`
                
                    LEFT JOIN `wp_postmeta` AS `tipo` ON
                        `tipo`.`meta_key` = 'tipo'
                        AND `tipo`.`post_id` = `t`.`ID`
                
                
                    LEFT JOIN `wp_postmeta` AS `nombre` ON
                        `nombre`.`meta_key` = 'nombre'
                        AND `nombre`.`post_id` = `t`.`ID`
                
                
						LEFT JOIN `wp_icl_translations` AS `wpml_translations`
							ON `wpml_translations`.`element_id` = `t`.`ID`
								AND `wpml_translations`.`element_type` = 'post_testimonio'
								AND `wpml_translations`.`language_code` = 'en'
					
                
				LEFT JOIN `wp_icl_languages` AS `wpml_languages`
					ON `wpml_languages`.`code` = `wpml_translations`.`language_code` AND `wpml_languages`.`active` = 1
			
                WHERE ( ( `tipo`.`meta_value` = 'ASEGURADORA' ) AND ( `t`.`post_type` = 'testimonio' ) AND ( `wpml_languages`.`code` IS NOT NULL ) AND ( `t`.`post_status` IN ( 'publish' ) ) )
                
                
                ORDER BY `nombre`.`meta_value`, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
                LIMIT 0, 3
```

## PROSITE

```
                SELECT
                
                DISTINCT
                `t`.*
                FROM `wp_posts` AS `t`
                
                    LEFT JOIN `wp_postmeta` AS `tipo` ON
                        `tipo`.`meta_key` = 'tipo'
                        AND `tipo`.`post_id` = `t`.`ID`
                
                
                    LEFT JOIN `wp_postmeta` AS `tipo_meta_value` ON
                        `tipo_meta_value`.`meta_key` = 'meta_value'
                        AND `tipo_meta_value`.`post_id` = `tipo`.`post_id`
                
                
                    LEFT JOIN `wp_postmeta` AS `nombre` ON
                        `nombre`.`meta_key` = 'nombre'
                        AND `nombre`.`post_id` = `t`.`ID`
                
                
						LEFT JOIN `wp_icl_translations` AS `wpml_translations`
							ON `wpml_translations`.`element_id` = `t`.`ID`
								AND `wpml_translations`.`element_type` = 'post_testimonio'
								AND `wpml_translations`.`language_code` = 'en'
					
                
						LEFT JOIN `wp_icl_languages` AS `wpml_languages`
							ON `wpml_languages`.`code` = `wpml_translations`.`language_code` AND `wpml_languages`.`active` = 1
					
                WHERE ( ( `tipo`.`meta_value` = 'ASEGURADORA' ) AND ( `t`.`post_type` = "testimonio" ) AND ( `wpml_languages`.`code` IS NOT NULL ) AND ( `t`.`post_status` IN ( "publish" ) ) )
                
                
                ORDER BY `nombre`.`meta_value`, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
                LIMIT 0, 3
```

> Note: ASEGURADORA is what I put before as INSURER to avoid confuse you, but is just a constant

So in resume, this seems the missing part in the query

```
LEFT JOIN `wp_postmeta` AS `tipo_meta_value` ON
                        `tipo_meta_value`.`meta_key` = 'meta_value'
                        AND `tipo_meta_value`.`post_id` = `tipo`.`post_id`
```

I'll contact you to the email address so we can have a better close comunication and give you credentials

Thanks

**Comment by carlosrovira** [comment]
(reopening since I can't post without do so)

Hi @JoryHogeveen,

I notice that now, templates show in EN and not in ES. I tried various approaches, but what I found is that If I create add template for a language it doesn't show in the other one and viceversa. I couldn't find a solution for this and decided to post here... do you have any idea of what could be the problem?

**Comment by carlosrovira** [comment]
Hi, I think I finally get it to work with a combination of making the templates not to be a duplicate and clearing pods cache. But was tricky.

While presite is now working, when I cleared the pods cache I got again the following error stack trace:


Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Notice: Trying to access array offset on value of type bool in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

Warning: Invalid argument supplied for foreach() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/pods/components/I18n/I18n.php on line 413

this is using rc3 and 2.8.0 final release update just few minutes ago.

HTH

Carlos

**Comment by carlosrovira** [comment]
I got pro site update to 2.8 final release. Just notice that is a bit tricky since you need to clear pods cache and also other caches you can have in your site and refresh it and try again until things settle. Closing again.

**Comment by carlosrovira** [comment]
also the error stack trace doesn't show in pro site :?

**Comment by JoryHogeveen** [comment]
@carlosrovira 

> also the error stack trace doesn't show in pro site :?

This is probably because debug is disabled on the production website.

About the errors, could you share the full stack trace and not just the error (warning) itself?

**Comment by carlosrovira** [comment]
Hi @JoryHogeveen, ok, please let me know where I can find the full stack trace so I can share here. Thanks

**Comment by carlosrovira** [comment]
@JoryHogeveen remember you hace access to the pre site where you can see that error. Also ensure you put in EN view (since only happens in EN, not in ES).

**Comment by JoryHogeveen** [comment]
Just got another error that is server related it seems:

```
Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/includes/class-wp-installer.php:898
Stack trace:
#0 /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/includes/class-wp-installer.php(99): WP_Installer->load_repositories_list()
#1 /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/includes/class-wp-installer.php(80): WP_Installer->__construct()
#2 /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/includes/functions-core.php(6): WP_Installer::instance()
#3 /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/installer.php(15): WP_Installer()
#4 /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/loader.php(184): include_once('...')
#5 /home/codeoscopic/var/www/codeoscopic.com/wp-includes/class-wp-hook.php(303): wpml_installer_instance_delegator()
#6 /home/codeoscopic/var/www/codeoscopic.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /home/codeoscopic/var/www/codeoscopic.com/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /home/codeoscopic/var/www/codeoscopic.com/wp-settings.php(556): do_action()
#9 /home/codeoscopic/var/www/codeoscopic.com/wp-config.php(120): require_once('...')
#10 /home/codeoscopic/var/www/codeoscopic.com/wp-load.php(50): require_once('...')
#11 /home/codeoscopic/var/www/codeoscopic.com/wp-admin/admin.php(34): require_once('...')
#12 /home/codeoscopic/var/www/codeoscopic.com/wp-admin/index.php(10): require_once('...')
#13 {main} thrown in /home/codeoscopic/var/www/codeoscopic.com/wp-content/plugins/sitepress-multilingual-cms/vendor/otgs/installer/includes/class-wp-installer.php on line 898
```

**Comment by wildmercury** [comment]
I have a very similar issue (same variance across languages, same SELECT DISTINT LEFTJOIN type of query) on a prod site after latest update of Pods. All I can add is that I get a 500 error on the front end and this in the error log:

> Request for [REDACTED]/public_html exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: [REDACTED]/wp-admin/post.php?post=4555&action=edit&lang=fr 

Hosted on SiteGround with PHP 7.4.25.

**Comment by carlosrovira** [comment]
Hi @wildmercury, is your site using WPML? This problem was about using WPML but was fixed.  IMHO, an error 500 indicates something different that seems not related to this problem. Did you try to enable debug to see more traces on screen. Usually that use to help to determine what's happening behind.

Also, when migrating to 2.8 I found that some of my pods config was missing configuration checks that now need to be check in order to work.

HTH

C.

**Comment by wildmercury** [comment]
Thanks for that. Yes, WPML and errors only on one language and with a PHP v8.0 test we get the following error:
Fatal error: Uncaught ValueError: Missing format specifier at end of string in /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/classes/PodsInit.php:2034 Stack trace: #0 /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/classes/PodsInit.php(2034): sprintf('Nouveau %', 'Pod Template') #1 /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/components/Templates/Templates.php(99): PodsInit::object_label_fix(Array, 'post_type') #2 /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/classes/PodsComponent.php(17): Pods_Templates->init() #3 /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/classes/PodsComponents.php(303): PodsComponent->__construct() #4 /home/customer/www/[REDACTED]/public_html/wp-includes/class-wp-hook.php(303): PodsComponents->load('') #5 /home/customer/www/[REDACTED]/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(Array, Array) #6 /home/customer/www/[REDACTED]/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #7 /home/customer/www/[REDACTED]/public_html/wp-settings.php(510): do_action('setup_theme') #8 /home/customer/www/[REDACTED]/public_html/wp-config.php(99): require_once('/home/customer/...') #9 /home/customer/www/[REDACTED]/public_html/wp-load.php(50): require_once('/home/customer/...') #10 /home/customer/www/[REDACTED]/public_html/wp-blog-header.php(13): require_once('/home/customer/...') #11 /home/customer/www/[REDACTED]/public_html/index.php(17): require('/home/customer/...') #12 {main} thrown in /home/customer/www/[REDACTED]/public_html/wp-content/plugins/pods/classes/PodsInit.php on line 2034

Which looks like a string is not being handled properly / has a character missing / or adding a space at the end?

I'm not sure what you mean by "configuration checks that now need to be check in order to work". How would one check a pods config? Nothing has changed in several years (since 2017 I think).

**Comment by wildmercury** [comment]
Follow up on this: I did a manual update of String Translations for Pods FR fields namely:
'New %s' is translated to 'Nouveau %' corrected to 'Nouveau %s'
'View %s' is translated to 'Voir %' corrected to 'Voir %s'
That removed the Uncaught ValueError. Who should I direct the request for a more permanent correction there? Pods of WPML?

Still stuck with the original SELECT error...

**Comment by carlosrovira** [comment]
> I'm not sure what you mean by "configuration checks that now need to be check in order to work". How would one check a pods config? Nothing has changed in several years (since 2017 I think).

I mean that I need to select a couple of checks that was unchecked in 2.7, but was needed in 2.8 in "selected mode" (with the tick) after this major refactor. So 2.7 seems to be less strict in the need

If after try to revise checks and pod config and sabe the problem is not solved, I think you should log a new issue that tries to describe the problem as something new since to me it appears something different to what is described in the original purpose of this issue.

**Comment by JoryHogeveen** [comment]
@wildmercury 
>Follow up on this: I did a manual update of String Translations for Pods FR fields namely:
'New %s' is translated to 'Nouveau %' corrected to 'Nouveau %s'
'View %s' is translated to 'Voir %' corrected to 'Voir %s'
That removed the Uncaught ValueError. Who should I direct the request for a more permanent correction there? Pods of WPML?

I cannot find this translation within the Pods FR translation files: https://translate.wordpress.org/locale/fr/default/wp-plugins/pods/
Where was this added?

> If after try to revise checks and pod config and sabe the problem is not solved, I think you should log a new issue that tries to describe the problem as something new since to me it appears something different to what is described in the original purpose of this issue.

Indeed, your issues sounds unrelated to this one, please create a new bug report and provide all info asked so we can reproduce and fix it!
