### ISSUE TITLE
[Pods 2.8 Bug] Field Relationship - Simple (Custom defined list) not rendering.

### ISSUE THREAD

**Issue by CosmikCarrot** [pods-framework/pods#5948]
## Pods 2.8 version

2.8.0-b-1

## Description

Field Relationship - Simple (Custom defined list) not rendering.

## Testing instructions

1. Go to More fields and add a relationship field.
2. Select - Simple (Custom defined list)
3. Enter list, save.
4. View in cpt block editor > https://www.screencast.com/t/aR9mUCTHvO5W

## Expected behavior

Expect to see list of labels to select with checkboxes.

## Screenshots / screencast

See - https://www.screencast.com/t/aR9mUCTHvO5W

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by JoryHogeveen** [comment]
Duplicate: #5940

**Comment by CosmikCarrot** [comment]
Thanks @JoryHogeveen
