### ISSUE TITLE
[DIVI AND PODS] PHP ERROR IN DIVI LAYOUT SHOWING PODS CUSTOM POST TYPE

### ISSUE THREAD

**Issue by gnegreiros** [pods-framework/pods#5949]
Hi, 
I'm using Pods plugin to create CPTs and taxonomies but:
1- I'm not able to enable my CPTs in Theme Options/Builder.
2- When I visit a CPT page by a Divi layout I have error messages before the content :

> Warning: preg_match() expects parameter 2 to be string, array given in /wp-includes/class-wp-block-parser.php on line 417
> 
> Warning: strlen() expects parameter 1 to be string, array given in /wp-includes/class-wp-block-parser.php on line 489

Can you help me, please?

**Comment by JoryHogeveen** [comment]
Hello @gnegreiros 

Are you sure this is a Pods issue?
Please check for plugin conflicts first: https://docs.pods.io/faqs/plugin-theme-conflicts/

Cheers, Jory

**Comment by gnegreiros** [comment]
Hi,

No, I'm not sure.

**Comment by JoryHogeveen** [comment]
Hi @gnegreiros 

Then please make sure it's a Pods issue first ;)

Cheers, Jory

**Comment by gnegreiros** [comment]
Thank you.



*canadel.com <http://canadel.com>*    *GUILHERME NEGREIROS*
UI / UX Designer

*T : *819-228-8471 #2270
700, av Canadel, C.P. 5, Louiseville (Québec) Canada J5V 2L6

<http://files.canadel.com/?file=inspired-latest>
