### ISSUE TITLE
Getting “\” while updating existing pod field

### ISSUE THREAD

**Issue by swabhav** [pods-framework/pods#5950]
I’m getting problems while updating the existing pods field, getting (slash \ ) automatically if I put ( semicolon " ) in default values.
check the screenshot – https://prnt.sc/zywy98

**Comment by JoryHogeveen** [comment]
Duplicate of #5909 
Patch can be found here: #5910

**Comment by swabhav** [comment]
I have done that, but now getting a new issue default value coming to the post field but when I publish the post it automatically gone.

**Comment by swabhav** [comment]
I have done that, but now getting a new issue default value coming in the post field correctly but when I publish the post it automatically gone.

**Comment by swabhav** [comment]
> Duplicate of #5909
> Patch can be found here: #5910

I have done that, but now getting a new issue default value coming in the post field correctly but when I publish the post it automatically gone.

**Comment by quasel** [comment]
@swabhav pleas add your report to the original issue #5909 !
