### ISSUE TITLE
Custom settings pages are only accessible by multisite Super Admin

### ISSUE THREAD

**Issue by danmaby** [pods-framework/pods#5953]
I appear to have hit an issue with Multisite and access to custom settings pages.  

When creating a custom settings page on multisite, at a site-specific level, I've been unable to grant access to a custom settings page to any user level other than `Super Admin`.  If I set a user to `Admin` or any level other than Super Admin, for a site called `/site-two` in a subdirectory multisite and visit the following URL in the site, they will receive a 403 error: 

`example.com/site-two/wp-admin/options-general.php?page=pods-settings-example-custom-settings`
 
I'm assuming this isn't intentional behaviour? 

WordPress 5.6.2
Pods 2.7.26

**Comment by JoryHogeveen** [comment]
Hi @danmaby 

Each setting page from Pods get's its own capability: `pods_edit_PODNAME`.
You can use one of the following plugins to grant capabilities to various roles in your installation:

- Pods Component: Roles & Capabilities. You can enable this components by going to Pods > Components.
- [Members](https://wordpress.org/plugins/members/)
- [View Admin As](https://wordpress.org/plugins/view-admin-as/) - This is essentially a switching plugin that comes with a role editor. This plugin will also allow you to test your roles etc. without logging out/in.

Cheers, Jory
