### ISSUE TITLE
[Pods 2.8.0 Bug] Problem rendering Admin UI for Custom Post Type

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [pods-framework/pods#5963]
I created an ~~custom post type~~ advanced content type called "resources" and on the admin screen for the post type it displays this warning for each item: `Warning: array_merge(): Argument #1 is not an array in \****\wp-content\plugins\pods-release-2.8\classes\PodsUI.php on line 2939`. See the image below for the call stack.

Any idea what the problem might be? 

Here is the debug info from the Pods Admin settings page:
```
Debug Information
WordPress Version: 5.6.2

PHP Version: 7.2.19

MySQL Version: 5.7.24

Server Software: nginx/1.16.0

Your User Agent: *******

Session Save Path: *****

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 36000

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: *********

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 59.015M

Current Memory Usage (real): 6.000M

Pods Network-Wide Activated: No

Pods Install Location: *****Sitepath\wp-content\plugins\pods-release-2.8/

Pods Tableless Mode Activated: No

Pods Relationship Table Enabled: Yes

Pods Light Mode Activated: No

Currently Active Theme: ****CUSTOM****

Currently Active Plugins:

Custom Post Type Permalinks: 3.4.4
Oxygen: 3.7
Pods - Custom Content Types and Fields: 2.8.0-b-2
```

**Comment by sc0ttkclark** [comment]
There's a fix for this in `release/2.8` that's ready for your confirmation. Let us know if it resolves the issue you reported, I found a few more cases that I had to go and fix outside of this one you noted.

**Comment by Nathaniel-Fernandes** [comment]
It works perfectly! Thanks

**Comment by Nathaniel-Fernandes** [comment]
Actually should have checked further. For some reason, when I go to edit an item, no fields show up at all! It just shows a blank screen. https://ibb.co/pfjcF2S

**Comment by sc0ttkclark** [comment]
Now that we solved the error, the blank fields -- is that the same issue as #5974?
