### ISSUE TITLE
[Pods 2.8 Bug] After upgrading from 2.7 to 2.8.0-b-2 I have some big issues that are showstoppers:

### ISSUE THREAD

**Issue by Niek-SocialCase** [pods-framework/pods#5974]
## Description
I have a pod called "Regeling"(Picture 1)
Editing a "regeling"  item  (example: verhuiskostenstenregeling) in 2.7 gives no problems (picture 2)
Editing the same "regeling" item after upgrading to 2.8 gives some critical errors (picture 3)
The editingpage doesn't show any fields (this is after the second time I upgraded . For showing the problem I downgraded and upgraded again. The thirst time after upgrading fields where showing but with several errors).

## Testing instructions
Edit an existing pod after upgrade

## Expected behavior
Page that sows al the fields. 
## Screenshots / screencast
![bugp1](https://user-images.githubusercontent.com/80762760/111312871-01cb1180-8660-11eb-9633-211bc7747bb9.jpg)
![bugp2](https://user-images.githubusercontent.com/80762760/111312878-055e9880-8660-11eb-9393-bd76225082b8.jpg)
![bugp3](https://user-images.githubusercontent.com/80762760/111312892-08598900-8660-11eb-9969-577ebff15da6.jpg)

## Pods version
2.8.0-b-2

## Other super helpful information
After 1st update the field with label "Soort" which is of type "simple relationship" didn't show it'plain number s related content. Also the required field with label "Minimumleeftijd"which is of type plain number didn't show it's contents. 

<details>
<summary>WordPress Environment</summary>
  
WordPress Version: 5.7
PHP Version: 7.4.10
MySQL Version: 5.6.49
Server Software: Apache

</details>

**Comment by Niek-SocialCase** [comment]
Clearing the pods cache didn't fix the problem.

**Comment by sc0ttkclark** [comment]
I'm curious if going to the Pods Admin > Edit Pods and editing that pod in Pods 2.8 gets everything to start showing up correctly for you in the "regeling" item edit screen.

**Comment by Niek-SocialCase** [comment]
> I'm curious if going to the Pods Admin > Edit Pods and editing that pod in Pods 2.8 gets everything to start showing up correctly for you in the "regeling" item edit screen.

I'm sorry but problems still exist after upgrade from 2.2.27 to 2.8.0-b-2
![pods v2 7 27 no problem](https://user-images.githubusercontent.com/80762760/115956510-7d409e00-a4fd-11eb-999e-9edf96c304ea.jpg)
![pods v2 8 0-b-2 with problems](https://user-images.githubusercontent.com/80762760/115956513-83367f00-a4fd-11eb-9a9a-15198b1636aa.jpg)

**Comment by Niek-SocialCase** [comment]
The first picture shows pod "Regeling" with version 2.2.27, the second picture is after upgrade to version 2.8.0-b-2.
 Field "Soort" of type "simple relationship" still doesn't render and the content from field "MinimumLeeftijd" of type "Plain number" is showed in field "JongMeerderjarigMaxLeeftijd" !

**Comment by sc0ttkclark** [comment]
Go to the Pods Admin area in 2.8 and then edit the pod configuration itself. I just want to verify that it potentially solves your issue through that so I can better track the problem here.

**Comment by Niek-SocialCase** [comment]
I can't solve the problem with editing and saving te pod in 2.8. See attached logfile:
[socialcase.nl-1619399658690.log](https://github.com/pods-framework/pods/files/6373628/socialcase.nl-1619399658690.log)

**Comment by sc0ttkclark** [comment]
Resolved in the list select branch code that will get merged this week
