### ISSUE TITLE
[Pods 2.8 Bug] Renaming group removes fields

### ISSUE THREAD

**Issue by caffeinatedweb** [pods-framework/pods#5980]
## Pods 2.8 version

2.8.0-b-2

## Description

When changing the name of a group, the fields are removed. They don't get deleted but there's nowhere to delete or move them.

## Testing instructions

1. Create a group with fields
2. Rename group

## Expected behavior

Fields either stay in the renamed group or get moved to a generic space?

**Comment by sc0ttkclark** [comment]
I believe what's happening here is when the group is renamed, the fields won't show but still are there. Upon refreshing the page you'll see the fields in the group.

@zrothauser any ideas on what might be going on here with the store on rename of the parent group?

**Comment by sc0ttkclark** [comment]
Fixed via #6017
