### ISSUE TITLE
[Pods 2.8 Bug] A bunch of deprecation errors

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#5992]
Hey. When enabling Pods 2.8.0-b2 on my WordPress 5.7 site running PHP 8.0.3, I'm greeted with the following wall of errors in the dashboard... On the bright side, the issues seems to be related to just a handful lines of code. I'd love give my favorite custom fields and post types plugin a more indepth spin once its plays nice with PHP 8.

`Deprecated: Method ReflectionParameter::getClass() is deprecated in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 789

Deprecated: Method ReflectionParameter::getClass() is deprecated in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 798

Deprecated: Method ReflectionParameter::getClass() is deprecated in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 800

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Warning: The magic method Tribe__Extension_Loader::__wakeup() must have public visibility in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Extension_Loader.php on line 157

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /home/oldrupdk/oldrup.net/wp-content/plugins/bookly-responsive-appointment-booking-tool/lib/Session.php on line 37

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 518

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 59

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php:789) in /home/oldrupdk/oldrup.net/wp-includes/functions.php on line 6362

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php:789) in /home/oldrupdk/oldrup.net/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/vendor/lucatume/di52/src/tad/DI52/Container.php:789) in /home/oldrupdk/oldrup.net/wp-admin/admin-header.php on line 9

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oldrupdk/oldrup.net/wp-content/plugins/pods-release-2.8/common/src/Tribe/Assets.php on line 588`

**Comment by sc0ttkclark** [comment]
Updated the 'common' library to the latest PHP 8 friendly version. Can you retry with the latest from `release/2.8`?

**Comment by oldrup** [comment]
Great! I don't get this error anymore. Thank you :)
