### ISSUE TITLE
Taxonomy templates stopped working

### ISSUE THREAD

**Issue by nightwatchcyber** [pods-framework/pods#5993]
## Description
Taxonomy templates stopped working

## Testing instructions
1. Create a custom pod.
2. Create a custom taxonomy and associate with the pod.
3. Add one pod item and one taxonomy term.
4. Create template for the taxonomy and configure via "auto templates" pad. Add "foobar" to the template.
5. View taxonomy archive page - observe no results from the template.

## Expected behavior
Should say "foobar"

## Pods version
2.7.26

## Other super helpful information
<details>
<summary>WordPress Environment</summary>
 `
### wp-core ###

version: 5.7
site_language: en_US
user_language: en_US
permalink: undefined
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /nas/content/live/hbstaging123
wordpress_size: 44.44 MB (46596850 bytes)
uploads_path: /nas/content/live/hbstaging123/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /nas/content/live/hbstaging123/wp-content/themes
themes_size: 6.51 MB (6825414 bytes)
plugins_path: /nas/content/live/hbstaging123/wp-content/plugins
plugins_size: 9.63 MB (10096969 bytes)
database_size: 2.23 MB (2342912 bytes)
total_size: 62.81 MB (65862145 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Nineteen (twentynineteen)
version: 2.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, custom-line-height, widgets
theme_path: /nas/content/live/hbstaging123/wp-content/themes/twentynineteen

### wp-themes-inactive (2) ###

Twenty Twenty: version: 1.7, author: the WordPress team
Twenty Twenty-One: version: 1.2, author: the WordPress team

### wp-mu-plugins (4) ###

Force Strong Passwords - WPE Edition: version: 1.6.4, author: Jason Cosper
WP Engine Seamless Login Plugin: version: 1.5.5, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 4.1.0, author: WP Engine

### wp-plugins-active (3) ###

Debug This: version: 0.6.3, author: WPChill
Health Check & Troubleshooting: version: 1.4.5, author: The WordPress.org community
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-1024-gcp x86_64
httpd_software: Apache
php_version: 7.4.16 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_size: 50M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
server-headers: 
	server: nginx
	date: Thu, 15 Apr 2021 01:00:01 GMT
	content-type: text/html; charset=UTF-8
	content-length: 6686
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	vary: Accept-Encoding
	content-encoding: gzip
	x-powered-by: WP Engine
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.32-35-log
client_version: mysqlnd 7.4.16

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/hbstaging123/wp-content
WP_PLUGIN_DIR: /nas/content/live/hbstaging123/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: Yes
pods-memory-current-usage: 5.296M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: /nas/content/live/hbstaging123/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

` 

</details>

<details>
<summary>Pods Package Export</summary>
{"meta":{"version":"2.7.26","build":1618448467},"pods":{"11":{"id":11,"name":"book_category","label":"book_categories","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"book_category","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"book_category","query_var":"0","sort":"0","built_in_post_types_book":"1","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_user_request":"0","built_in_post_types_wp_block":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"1","pfat_single":"book_template","pfat_append_single":"append","pfat_filter_single":"get_the_archive_description","rest_enable":"0","read_all":"0","write_all":"0"},"5":{"id":5,"name":"book","label":"books","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"book_title":{"id":6,"name":"book_title","label":"Book Title","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"book_author":{"id":7,"name":"book_author","label":"book_author","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"book","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"book","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_excerpt","pfat_run_outside_loop":"0","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"book_template","pfat_archive":"taxonomy_template","built_in_taxonomies_book_category":"1"}},"templates":{"book_template":{"id":10,"name":"book_template","code":"<b>book template<\/b>","type":"template","slug":"book_template","options":{"_edit_last":"1","_edit_lock":"1618446794:1","pod_reference":"a:1:{s:3:\"pod\";s:0:\"\";}","admin_only":"","restrict_capability":"","capability_allowed":"","show_restrict_message":"1","restrict_message":""}},"taxonomy_template":{"id":12,"name":"taxonomy_template","code":"<b>taxonomy_template<\/b>","type":"template","slug":"taxonomy_template","options":{"_edit_last":"1","_edit_lock":"1618448019:1","admin_only":"","restrict_capability":"","capability_allowed":"","show_restrict_message":"1","restrict_message":"","pod_reference":"a:1:{s:3:\"pod\";s:4:\"book\";}"}}}}
</details>

**Comment by jimtrue** [comment]
These have never worked, so there's not a situation where they were working and stopped working. This is on the roadmap (@keraweb has put in some work on this), but they are not implemented in live.

**Comment by nightwatchcyber** [comment]
Thank you
