### ISSUE TITLE
CustomTable columns rearrange or full rebuild

### ISSUE THREAD

**Issue by justdudeone** [pods-framework/pods#6001]
Hello,

When you create a new Pod with many fields it’s often impossible to arrange all of them ideally from the beginning, mostly you will re-arrange fields many times before you will get the ideal fields order and structure. (All big-data projects optimized and updating many times, mostly of them extending already at work on the fly.)

But on Pod saving (even without data at this Pod) – all CustomFields ID's stay the same from when they was added. For example even when lastly added field will be placed at position #10 of fields list, it still will have the last ID:150. Also when admin rearrange CustomFields at dashboard, CustomFields columns order at DB CustomTable does not updating. 

For ideal conformity will be nice to have automatic functions, or at least buttons:
- “Rearrange DB CustomTable columns by current Pod CustomFields order”;
- "Rebuild whole DB CustomTable from current Pod CustomFields order with ID's reset and data clearing".

It will be much more comfort to work with such DB directly when all Pod CustomFields and CustomTable columns have the same order, to not search and scroll table all the time from the left-start to the right-end.

PS It's just the high-quality DB architect standards.

**Comment by sc0ttkclark** [comment]
Code of conduct warning presented at: https://github.com/pods-framework/pods/issues/6000#issuecomment-825359965 as well as a response to the details of this issue.
