### ISSUE TITLE
Checkbox default value 0 with required - obvious bug

### ISSUE THREAD

**Issue by justdudeone** [pods-framework/pods#6002]
Hello,

If use Pods “Yes/No” field with frontend represent as “Checkbox” (which often are the most comfortable), set this field as Required, preset default value to 0 – if checkbox are not checked – it must send from form to DB value=0. Unfortunately your Pods Checkbox does not work like this. It works as classic web-developing (low-quality and standards violation) WYSIWYG logic - if developer/user don't see checked Checkbox - it does not send Value=1 at all. Simple, but wrong.

I already see about 3 similar topics about your Pods, but Pods developers argue about this problem and still not resolve it... but you must understand that there is simply no room for controversy in this problem... 

It’s the classic “web developers simplified logic” – most of you thinking by web interfaces. Best of you about code optimization. But very few of you thinking about data storing correctly – from the most important project basis – starting from DataBase. In terms of working with data and a specially big-data (Pods created exactly for such purpose) – data is the most important, data have the first priority, only than all other things and interfaces. First of all right developing needs to make all data storing correctly. Than based on DB sustained standards add code and interfaces. At such right for corporate/banks/big-data/etc SW logic – Boolean DB field can be: “empty/0/1”. But if admin needs to make DB field “not empty” anyway, he can do it at DB with many possibilities as: set DEFAULT, set Not null, etc – all works correctly! But at WP-Pods interface your Checkbox destroy and ignore all those DB rules&possibilities – even with “Required” option and “Default value = 0” – your Checkbox does not save 0 to DB. Thus your “Pods web-interface Checkbox field” at such conditions violate of the “more important DB Boolean field rules”. 

Thus there is no doubts and no any room for discussions. If you still not sure, you can try Microsoft Visual Studio C++ with Microsoft SQL Server or Oracle with Checkbox component – it’s a standard. So to comply with international SW-DB standards your MUST resolve this problem at Pods ANYWAY – or by adding possibility to Checkbox to store 0 to DB if it not checked but “Default value = 0”, or to control Default fields-columns values directly by set DB COLUMN DEFAULT values.

**Comment by JoryHogeveen** [comment]
Hi @justdudeone 

I already explained this on wp.org.

Required checkboxes doesn't make any sense. This would only be needed if the checkbox is required to be checked.
The whole required option isn't about making the field required for DB storage. There will ALWAYS be a value stored for checkboxes once the form passes.

> most of you thinking by web interfaces
Correct, because you are working with a web interface... the "required" option is all about the interface / UI, not the storage.

> or to control Default fields-columns values directly by set DB COLUMN DEFAULT values.
The default schema is always 0, see: https://github.com/pods-framework/pods/blob/main/classes/fields/boolean.php#L70

So, to shortly answer again:

- Storage schema for boolean type fields (yes/no) always defaults to 0.
- UI always defaults to the default you set in the field options.
- Required is only affecting UI, not storage (since this always has a default)
- Setting a checkbox to required only affects UI. For this reason, a required checkbox cannot contain 0/false.

I understand that you are working from a DB/storage point of view, **but we are not**. We mostly respect the "WordPress way" of storing data and optionally allow custom table storage.

@sc0ttkclark Anything you'd like to add?

Cheers, Jory

**Comment by justdudeone** [comment]
In terms of DB - the WordPress is an obvious outdated dull garbage. Use WP garbage as basis standard for newer powerful Pods - was actual maybe 15 years ago, but not at 2020 for sure.

About Checkbox - OK, I see your logic. "Checkbox only checked" as "required field" can be useful for "acceptance of an agreements". You can keep current Checkbox behavior for such using.

But, because it's not only me who not happy with it and because it really violate DB standards of Boolean storing logic - you can just add to Checkbox (?) popup tooltip info like: "Checkbox will always send to DB value 0 or 1, to make DB field "not empty" you does NOT need to set Checkbox field as "Required". "Required" option is more actual for "acceptance of an agreements"."

**Comment by JoryHogeveen** [comment]
> Because it's not only me who not happy with it

Could you please refer to other issues that share your opinion on this topic?

> Because current Checkbox UI violate the DB standards and possibilities

> Still your "The default schema is always 0" - is again violating of DB storing/design/control standards - because you store data even which admin not asking for at all!

At the moment we just set a default value (0). None of the field settings are about storage unless explicitly mentioned.
Could you please share a link to these standards you mention?

> The WordPress is an obvious outdated dull garbage. 

If you disapprove of WordPress so much, why are you using it? I'm not saying the WordPress ecosystem is perfect (far from it) but it seems like WordPress in general doesn't match your project's requirements at all, am I correct?

**Comment by justdudeone** [comment]
There is only 2 huge WP advantages - huge ecosystem and fast deploy. All other seems outdated and low-quality.

**Comment by justdudeone** [comment]
BTW even by "logic starts from interface" this problem also must be resolved somehow, because:
This field type named as "Yes/No". When admin set "Required" this field MUST act as "Yes/No - Required". But Checkbox just does not act as "Required - No". So Checkbox is NOT A TRUE "Yes/No field", in terms of your basis-interface - Checkbox is more like an "Yes/Empty field"!
You anyway must or add some warning about those special Checkbox behavior, or better:
a) For Pods "Yes/No" filed with Checkbox style remove "Required" option at all, or replace classic Checkbox with 3 stage Checkbox as "Empty / V / X" or replace Checkbox with Toggle etc - thus field will be TRUE YES/NO;
b) Separate "Checkbox" to standalone field type for functions as "acceptance of an agreements", maybe by default with "Required" option ON, and send 0 to DB if unchecked.

**Comment by sc0ttkclark** [comment]
Code of conduct warning presented at: https://github.com/pods-framework/pods/issues/6000#issuecomment-825359965 as well as a response to the details of this issue.
