### ISSUE TITLE
Too many Pods funtionality does not have proper frontend implementation

### ISSUE THREAD

**Issue by justdudeone** [pods-framework/pods#6003]
Hello,

It's again a some kind of "project architect flaw" or "poor development planning" when you add more functions to your Pods at backend, but those functions does not have proper implementation at frontend, so they are "half-useless".

For example:

- CustomField "Relationship-Simple" - a very nice feature for a fast and easy Values|Labels adding - but it lacks any possibility to use it at frontend FILTERS. Even widely recommended filters for Pods - FacetWP canNOT work with this popular CustomField type. Thus this Values|Labels list cannot be used for Pods data filtering.
- Rating and reviews becomes very popular for already 10 years, even Google now retrieve and show at search results the pages classic "5-stars rating" which significantly improve SEO when users search at Google for "...something... review, test, etc". Pods have CustomField "Number" with frontend representation as "Slider or Number" but again lacks of the such popular option as "Rating" (which must simply recalculate CurrentValue by preset MaxValue to 5 stars (for example current 30 from max 50 will give 3 stars from classic 5 stars) and display them as ★✬☆).
- It's obvious that many users want to compare Pods CPT/ACT CustomFields data side-by-side. For example compare real estate offers or cars specs, etc. (Similar to how WooCommerce Products comparison plugins works.) I'm just amazed at the lack of such obvious function at Pods for so many years of developing.

Etc. Your team really need to re-wise overall project developing procedure:
1) Devise new functionality and write simple functionality specs.
2) Design DB first of all to correspond all DB design-quality and big-data standards.
3) Design dashboard interface to setup the new function.
4) Design frontend to bring all actual possibilities of new function to users.
5) Design code which will link DB-dashboard-frontend.
Implement.

Now I see too much shortcomings at (2) DB design and (4) lack of many obvious very useful functions at frontend.

Highly recommend to work on project planning and architect better.

**Comment by sc0ttkclark** [comment]
Code of conduct warning presented at: https://github.com/pods-framework/pods/issues/6000#issuecomment-825359965 as well as a response to the details of this issue.
