### ISSUE TITLE
[Pods 2.8 Bug] Form: Simple (custom defined list) gives error

### ISSUE THREAD

**Issue by arielsfr** [pods-framework/pods#6005]
## Pods 2.8 version

2.8.0-b-2

## Description

Field type: Relationship, Simple (custom defined list) gives error message on form:
"There was an error rendering the field."

## Testing instructions

1. Create CPT, eg 'My CPT', 'my_cpt'
2. Add Field, eg 'My Test Field', 'my_test_field'. Select Field Type: 'Relationship', Related type: 'Simple (custom defined list)'
2. In Custom defined options, add eg: 'Yes', 'No', 'Maybe'
3. In Relationship Options, select Selection type: Single Select; Format: Drop Down
4. Display the form using PHP (eg, as part of a shortcode inserted in a Page):

	$mypod = pods( 'my_cpt' ); 
	$fields = array( ‘ my_test_field’ );
	echo $mypod->form( $fields );

5. View page: label says 'My Test Field', where the field should be, it says 'There was an error rendering the field.'

The same error occurs with every combination of Relationship Options, eg Single or Multiple select, Radio buttons, Checkboxes, etc.

## Expected behavior

A drop-down selector with options 'Yes', 'No', 'Maybe'

## Possible workaround

Drop-downs do work with Taxonomies, so for some use cases, a taxonomy with all select options can be used instead, at least as a temporary workaround.

## Other super helpful information

This was not an issue in v. 2.7.27.

<details>
<summary>WordPress Environment</summary>
  
`
### wp-core ###

version: 5.7.1
site_language: en_CA
user_language: en_CA
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/creativeensemble/public_html
wordpress_size: 59.86 MB (62766289 bytes)
uploads_path: /home/creativeensemble/public_html/wp-content/uploads
uploads_size: 1.32 MB (1383792 bytes)
themes_path: /home/creativeensemble/public_html/wp-content/themes
themes_size: 6.26 MB (6567469 bytes)
plugins_path: /home/creativeensemble/public_html/wp-content/plugins
plugins_size: 59.76 MB (62660433 bytes)
database_size: 6.18 MB (6481149 bytes)
total_size: 133.38 MB (139859132 bytes)

### wp-dropins (1) ###

maintenance.php: true

### wp-active-theme ###

name: Simple Bootstrap (simple-bootstrap)
version: 2.0.6
author: Nicolas Vanhoren
author_website: https://github.com/nicolas-van
parent_theme: none
theme_features: core-block-patterns, html5, post-thumbnails, automatic-feed-links, custom-background, custom-header, title-tag, menus, wp-block-styles, align-wide, responsive-embeds, widgets
theme_path: /home/creativeensemble/public_html/wp-content/themes/simple-bootstrap
auto_update: Disabled

### wp-themes-inactive (2) ###

e.nigma 2015: version: 1.2.5.1, author: Alexander Lüken, Auto-updates disabled
Twenty Ten: version: 3.3, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (6) ###

Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates enabled
Creative Ensemble custom functions: version: 0.1, author: Ariel Frailich, Auto-updates disabled
GitHub Updater: version: 9.9.10, author: Andy Fragen, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.0-b-2, author: Pods Framework Team, Auto-updates disabled
Wordfence Security: version: 7.5.2, author: Wordfence, Auto-updates enabled
WP Maintenance Mode: version: 2.3.0, author: Designmodo, Auto-updates enabled

### wp-plugins-inactive (4) ###

Akismet Anti-Spam: version: 4.1.9, author: Automattic, Auto-updates enabled
Creative Ensemble Development Utilities: version: 0.1, author: Ariel Frailich, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.7.27, author: Pods Framework Team, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-02-24 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 16M
upload_max_filesize: 10M
max_effective_size: 10 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 40
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-957.10.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.2.34 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 10M
php_post_max_size: 16M
curl_version: 7.76.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.28-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/creativeensemble/public_html/wp-content
WP_PLUGIN_DIR: /home/creativeensemble/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
pods-session-save-path: /var/cpanel/php/sessions/ea-php72
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 65.492M
pods-memory-current-usage-real: 68.000M
pods-network-wide: No
pods-install-location: /home/creativeensemble/public_html/wp-content/plugins/pods-release-2.8/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

{"meta":{"version":"2.8.0-b-2","build":1619022632},"pods":{"age_range":{"object_type":"pod","storage_type":"post_type","name":"age_range","id":196,"label":"Age Ranges","description":"","type":"taxonomy","storage":"meta","label_singular":"Age Range","public":"1","show_ui":"1","hierarchical":"1","_locale":"user","podType":{"name":"ct","label":"Custom Taxonomy"},"storageType":{"name":"meta","label":"Meta"},"built_in_post_types_resume":"1"},"gender":{"object_type":"pod","storage_type":"post_type","name":"gender","id":192,"label":"Genders","description":"","type":"taxonomy","storage":"meta","label_singular":"Gender","public":"1","show_ui":"1","hierarchical":"0","_locale":"user","podType":{"name":"ct","label":"Custom Taxonomy"},"storageType":{"name":"meta","label":"Meta"},"show_in_nav_menus":"0","show_tagcloud":"0","built_in_post_types_resume":"1"},"genre":{"object_type":"pod","storage_type":"post_type","name":"genre","id":81,"label":"Genres","description":"","label_singular":"Genre","public":"1","show_ui":"1","hierarchical":"1","type":"taxonomy","storage":"meta","built_in_post_types_resume":"1"},"resume":{"object_type":"pod","storage_type":"post_type","name":"resume","id":45,"label":"Résumés","description":"","label_singular":"Résumé","public":"1","show_ui":"1","supports_title":"0","supports_editor":"0","type":"post_type","storage":"meta","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"resume","capability_type_extra":"1","has_archive":"1","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"pending","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_menu":"1","menu_position":"0","menu_icon":"dashicons-id-alt","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"replace","pfat_filter_archive":"the_excerpt","pfat_run_outside_loop":"0","rest_enable":"0","read_all":"0","write_all":"0","built_in_taxonomies_genre":"1","pfat_single":"Resume","pfat_archive":"Resume","_locale":"user","podType":{"name":"cpt","label":"Custom Post Type"},"storageType":{"name":"meta","label":"Meta"},"built_in_taxonomies_gender":"1","built_in_taxonomies_age_range":"1"}},"templates":{"Resume":{"object_type":"template","storage_type":"post_type","name":"resume","id":94,"parent":"","group":"","label":"Resume","description":"<h2>Creative Ensemble Fields<\/h2>\r\n<p>LABEL {@first_name}<\/p>\r\n<p>LABEL {@middle_initial}<\/p>\r\n<p>LABEL {@last_name}<\/p>\r\n<p>LABEL {@address_line_1}<\/p>\r\n<p>LABEL {@address_line_2}<\/p>\r\n<p>LABEL {@citytown}<\/p>\r\n<p>LABEL {@provincestate}<\/p>\r\n<p>LABEL {@country}<\/p>\r\n<p>LABEL {@postalzip_code}<\/p>\r\n<p>LABEL {@phone}<\/p>\r\n<p>LABEL {@email}<\/p>\r\n<p>LABEL {@password}<\/p>\r\n<p>LABEL {@email_reminder_question}<\/p>\r\n\r\n<h2>Employer fields<\/h2>\r\n<p>LABEL {@company_name}<\/p>\r\n<p>LABEL {@citytown_public}<\/p>\r\n<p>LABEL {@provincestate_public}<\/p>\r\n<p>LABEL {@country_public}<\/p>\r\n<p>LABEL {@postalzip_code_public}<\/p>\r\n\r\n<h2>Searchable fields<\/h2>\r\n<p>LABEL {@gender}<\/p>\r\n<p>LABEL {@on-camerastage_age_range}<\/p>\r\n<p>LABEL {@genre}<\/p>\r\n<p>LABEL {@occupation}<\/p>\r\n<p>LABEL {@specialization}<\/p>\r\n<p>LABEL {@citytown_public_search}<\/p>\r\n<p>LABEL {@provincestate_public_search}<\/p>\r\n<p>LABEL {@country_public_search}<\/p>\r\n<p>LABEL {@summary}<\/p>\r\n<p>LABEL {@experience}<\/p>\r\n<p>LABEL {@skills}<\/p>\r\n<p>LABEL {@references}<\/p>\r\n<p>LABEL {@additional_comments}<\/p>\r\n<p>LABEL {@where_did_you_hear_about_us}<\/p>","weight":0,"_edit_lock":"1618836501:1","_edit_last":"1","show_restrict_message":"1","pod_reference":{"pod":"resume"}}}}

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by sc0ttkclark** [comment]
Fixed via 1f85c7b54a52a07e62130227302174774d8e3883
