### ISSUE TITLE
Enhancement: Allow specifying what fields should be returned in REST API relationship response type

### ISSUE THREAD

**Issue by datreesezcup** [pods-framework/pods#6019]
# Problem
Sometimes when querying the REST API for a custom post, there will be data in that Pod's relationship field that is needed for the current situation. However, at this time, the only way to obtain this information within the same REST call is to set the relationship response type to "Full", which means a lot more data than needed will be returned by the REST API, which is inefficient, and increases response time and bandwidth.
# Solution(s)
I foresee two possible solutions to this problem, as one I believe would be much easier to implement, but the other is more intuitive. These options could both be implemented in the Pods admin UI as a 4th option to the "Response Type" dropdown, perhaps labelled "Custom". The two options for this field could be:
#### Solution 1: Simple Text Box
Upon selecting the "Custom" response type, a plain text field could appear, and within this text field the user could enter a comma-separated list of the _names_ (not labels) of the fields they wish to be present.
**Drawbacks:** This requires that the user knows the field names present in the relationship object. While this isn't an issue for relationships to other types the user has created, it could be an issue if the relationship is to a type that the user did not create.
#### Solution 2: Checkbox List (or other multi-select field)
Upon selecting the "Custom" response type, a checkbox area would appear with all of the possible fields that could be included in the REST Response, and the user would be able to select which fields they wish to be included.
**Drabacks:** This would be more difficult to implement, and would require more database calls to collect this required info to present to the user.

I currently faced this exact issue, and while it was only for a negligible amount of data, I could see large, complex Pods benefiting greatly from this feature, if they only need a tiny amount of extra data. My current workaround was to _slightly_ modify the plugin to add a 4th option to the dropdown, and hardcode a check for this option in the Pods REST handler.

I look forward to seeing what others think about this feature!

**Comment by pdclark** [comment]
Sounds like you may be looking for GraphQL. For example, see https://www.wpgraphql.com and https://wordpress.stackexchange.com/questions/287196/using-graphql-plugin-with-pods-framework

**Comment by sc0ttkclark** [comment]
Agree on this -- the WPGraphQL solution is very ideal for this kind of need.

Further, I built an in-depth WPGraphQL integration for Pods and it works exactly as you'd hope with relationships/files -- with connections! It's pretty useful, check it out here: https://pods-pro.skc.dev/downloads/wpgraphql-integration/
