### ISSUE TITLE
[Pods 2.8.0 Bug] Trying to access array offset on value of type null in ... pick.php on line 1515

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#6020]
## Pods 2.8 version

**2.8.0 beta 2** as downloaded today May 3rd 2021 on WordPress **5.7.1** and **PHP 8.0.3**

## Description

Errors displayed when publishing a custom post, originally created with pods 2.7x and PHP 7.x

Below are the errors thrown:

It's not a production site. I can offer a temporary login if you want to poke it with a stick.

`
Warning: Trying to access array offset on value of type null in /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/fields/pick.php on line 1515

Warning: Trying to access array offset on value of type null in /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/fields/pick.php on line 1515

Warning: Trying to access array offset on value of type null in /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/PodsAPI.php on line 5393

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/fields/pick.php:1515) in /home/oldrupdk/sortering.oldrup.dk/wp-admin/post.php on line 231

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/fields/pick.php:1515) in /home/oldrupdk/sortering.oldrup.dk/wp-includes/pluggable.php on line 1329

Warning: Cannot modify header information - headers already sent by (output started at /home/oldrupdk/sortering.oldrup.dk/wp-content/plugins/pods-release-2.8/classes/fields/pick.php:1515) in /home/oldrupdk/sortering.oldrup.dk/wp-includes/pluggable.php on line 1332`

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/65a2800ce81e085c540d0b6776156fb7d229e808
