### ISSUE TITLE
Filter giving errors

### ISSUE THREAD

**Issue by bafplus** [pods-framework/pods#6035]
## Description

Using the filter option (shortcode). Worked without problems but since a few days trows an error after someone tries to search the pod using the search field.

## Testing instructions

used shortcode: [pods name="(podsname)" orderby="(ordervalue)" limit="*" filters=""]

Type searchvalue and click searchbutton

Error:
Database Error; SQL: SELECT DISTINCT `t`.* FROM `wp_posts` AS `t` LEFT JOIN `wp_postmeta` AS `naam` ON `naam`.`meta_key` = 'naam' AND `naam`.`post_id` = `t`.`ID` WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "terminals" ) ) AND ( `post_title`.`t` LIKE '%apm%' ) ORDER BY `naam`.`meta_value` ASC, `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`; Response: Unknown column 'post_title.t' in 'where clause'

## Expected behavior

filter podslist to defines values

## Pods version

2.7.28

**Comment by swkpie** [comment]
Found something similar when searching via REST.

I guess; d.post_title should be t.post_title

`SELECT DISTINCT	`t`.*, `d`.*

FROM `wptable_posts` AS `t`

LEFT JOIN `wptable_pods_location` AS `d` ON `d`.`id` = `t`.`ID`

WHERE ( ( `t`.`post_status` IN ( "publish" ) ) AND ( `t`.`post_type` = "location" ) ) AND ( `d`.`post_title` LIKE '%something%' )

ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`;

Response: Unknown column 'd.post_title' in 'where clause'</e>`

**Comment by sc0ttkclark** [comment]
Fixed via 6647828d549e8f5db18e3ef4a41b0ccf20813991 (related: #6050)
