### ISSUE TITLE
Featured Images using Easy Add Thumbnail broke in 2.7.28

### ISSUE THREAD

**Issue by sugarfunk** [pods-framework/pods#6038]
## Issue Overview
 **To Reproduce**
 
 1. Upgrade to 2.7.28
 2. Install https://wordpress.org/plugins/easy-add-thumbnail/ (I use the code only in a snippet rather than plugin. Its a single file plugin)
 3. Use PODs built in form for post submission
 4. No errors supplied, but easy add thumbnail fails to set "featured image"
 
 ## Expected Behavior
First of any image found should be assigned as the featured image. 
 
 ## Current Behavior
 1. No error, but no image is associated to the featured image
 
 ## Pods Version
 Please provide the version of Pods you are running:
2.7.28 fails
all previous versions since at least 1.14 this method works fine
 
 ## WordPress Environment
 ## Pods Package Export (helpful!)
 ```
Dont see this as helpful
 ```
 
 **Additional context**
 Rolling back to 2.7.27 resolves the issue.
 
 **Possible Workaround**
Rolling back is all I have found

**Code from Easy Add Thumbnail**
I am providing the code as it is a very small code that prevents me from having to figure out which image field my users will select. Has worked perfectly for 3+ years.

`
if ( function_exists( 'add_theme_support' ) ) {

	add_theme_support( 'post-thumbnails' ); // This should be in your theme. But we add this here because this way we can have featured images before switching to a theme that supports them.

	/**
	 * Main function.
	 *
	 * @param object $post Post Object.
	 */
	function easy_add_thumbnail( $post ) {

		$already_has_thumb = has_post_thumbnail();
		$post_type         = get_post_type( $post->ID );
		$exclude_types     = array( '' );
		$exclude_types     = apply_filters( 'eat_exclude_types', $exclude_types );

		// Do nothing if the post has already a featured image set.
		if ( $already_has_thumb ) {
			return;
		}

		// Do the job if the post is not from an excluded type.
		if ( ! in_array( $post_type, $exclude_types, true ) ) {

			// Get first attached image.
			$attached_image = get_children( "order=ASC&post_parent=$post->ID&post_type=attachment&post_mime_type=image&numberposts=1" );

			if ( $attached_image ) {

				$attachment_values = array_values( $attached_image );
				// Add attachment ID.
				add_post_meta( $post->ID, '_thumbnail_id', $attachment_values[0]->ID, true );

			}
		}

	}

	// Set featured image before post is displayed on the site front-end (for old posts published before enabling this plugin).
	add_action( 'the_post', 'easy_add_thumbnail' );

	// Hooks added to set the thumbnail when publishing too.
	add_action( 'new_to_publish', 'easy_add_thumbnail' );
	add_action( 'draft_to_publish', 'easy_add_thumbnail' );
	add_action( 'pending_to_publish', 'easy_add_thumbnail' );
	add_action( 'future_to_publish', 'easy_add_thumbnail' );
}
`

**Comment by sc0ttkclark** [comment]
Fixed in 2.8
