### ISSUE TITLE
[Pods 2.8 Bug] DateTime Timezone support

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6043]
## Description

Add support for timezone input.
Similar: #6041

**Comment by sc0ttkclark** [comment]
Needs confirmation this is resolved in 2.8

**Comment by sc0ttkclark** [comment]
@zrothauser can you bring over this change to our DFV time handling so it supports timezones? https://github.com/pods-framework/pods/pull/6042/files

**Comment by sc0ttkclark** [comment]
Just confirmed in the DFV date helper code that it's represented.
