### ISSUE TITLE
No more of 15 records

### ISSUE THREAD

**Issue by lamujeresponja** [pods-framework/pods#6044]
Hi. Pods not run with more than 15 records. Is it right? Or is it an error?
Thanks

**Comment by pdclark** [comment]
Exact formatting will depend on the method you're using to call Pods, but the parameter you're looking for may be `limit`. See the limit parameter in https://pods.io/docs/code/pods/find/ or the shortcode https://pods.io/docs/learn/shortcodes/pods/ for example.

**Comment by lamujeresponja** [comment]
> Exact formatting will depend on the method you're using to call Pods, but the parameter you're looking for may be `limit`. See the limit parameter in https://pods.io/docs/code/pods/find/ or the shortcode https://pods.io/docs/learn/shortcodes/pods/ for example.

Thanks. All right!
