### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by Enato-Ehimen** [pods-framework/pods#6057]
Hi. The issues is I have tried using the plunging to create 
CPT but the featured image even after turning it on doesn't show. 
I've tried it on 4 other wp installations and still the same thing .

Lease help fix the issue asap. 
Thanks

**Comment by unknownnf** [comment]
Hi @Enato-Ehimen have you tried using the default wordpress theme as well?

**Comment by pdclark** [comment]
Post thumbnails may need to be enabled in your theme with `add_theme_support( 'post-thumbnails' );`

See https://www.dummies.com/web-design-development/wordpress/templates-themes-plugins/how-to-add-support-for-post-thumbnails/

**Comment by Enato-Ehimen** [comment]
Thanks. It is working just fine now.
