### ISSUE TITLE
Item_Single.php error

### ISSUE THREAD

**Issue by CosmikCarrot** [pods-framework/pods#6059]
## Description

I’m getting this warning for two single item pod blocks that I’ve added to a test page? - https://www.screencast.com/t/GqqPxThN3Y

## Testing instructions

1. Add a Single Item Block
2. These settings - https://www.screencast.com/t/YhtfnqkigXD
3. View updated page.

## Expected behavior

Not see the error anymore on the front end.

## Screenshots / screencast

Screenshots above.

## Pods version

2.8 beta 3.

## Other super helpful information

Removing the single item block removes the error.

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by sc0ttkclark** [comment]
Resolved at some point after this, closing since it's not happening anymore.
