### ISSUE TITLE
How to display a list of checkbox items as a list of bullet points in a template?

### ISSUE THREAD

**Issue by CosmikCarrot** [pods-framework/pods#6060]
## Description

How can I display these checkboxes in the pod to appear as a list of bullet points in the template, please? - https://www.screencast.com/t/mJ4tIm2OJl5S

## Testing instructions

1. Current template only has; `<h3>{@services}</h3>`
2. How can this be bullet pointed for each of the checkboxes?

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by pdclark** [comment]
Sounds like this is a request for support in writing a template, not a bug.

Assuming your field is a `Relationship` type with "Related to" set to `Simple (custom defined list)`, the values can be output as a bulleted list in a template like this:

```
<ul>
<?php 
foreach( get_post_meta( get_the_ID(), 'services' ) as $value ) {
    echo '<li>' . $value . '</li>';
}
?>
</ul>
```
