### ISSUE TITLE
Conditional Template Tags

### ISSUE THREAD

**Issue by silversufer** [pods-framework/pods#6071]
Hello all,
I am relatively new to the Pods sphere and have a question for you. I hope you can help me because I have not found anything on the net.
I have created a POD with seven fields. One of these fields is a simple dropdown list.  Is it possible to define, if one of the labels is selected from the list, that then defined fields are not active to edit? I have attached values to the labels (e.g. stud|student).
I would be very grateful for any suggestions and hints.

**Comment by sc0ttkclark** [comment]
We do not currently have support for conditional logic for field visibility or disable/readonly handling for that kind of case. It's built into our code to support it however it's just not exposed with the admin interface to set it all per field. That work is planned for a future release.

**Comment by sc0ttkclark** [comment]
#609
