### ISSUE TITLE
Filling up the debug.log when cron called from command line

### ISSUE THREAD

**Issue by edsvcs** [pods-framework/pods#6072]
## Description

On our production sites, we use crontab to call "php wp-cron.php" instead of making a network call. Each call results the following two lines being added to debug.log:

[03-Aug-2021 06:37:02 UTC] PHP Notice:  Undefined index: HTTP_HOST in [path the wordpress home]/var/www/wordpress/wp-content/plugins/pods/includes/general.php on line 632
[03-Aug-2021 06:37:02 UTC] PHP Notice:  Trying to access array offset on value of type bool in /var/www/wordpress/wp-content/plugins/pods/components/Pages.php on line 718

## Testing instructions

Step 1. Edit wp-config.php and add the following entries to disable cron jobs and enable debug log: 
define('DISABLE_WP_CRON', true);
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

Step 2. Create cron job - on Ubuntu type "crontab -e" then add an appropriate entry similar to the following:
*/1 * * * * cd /var/www/wordpress; /usr/bin/php /var/www/wordpress/wp-cron.php > /dev/null 2>&1

Step 3. Let some time pass so your cron job can run then look at the debug.log.

## Expected behavior

Code at these two points should gracefully handle the condition without causing PHP notices.

## Screenshots / screencast

Not needed - see the copied entries above.

## Possible workaround

You can work around this with the following entry in wp-config.php except that it silences all debug entries and we need to know about warnings and errors.

if ( defined( 'DOING_CRON' ) ) {
	define( 'WP_DEBUG', false );
	define( 'WP_DEBUG_LOG', false );
	define( 'WP_DEBUG_DISPLAY', false );
} else {
	define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_LOG', true );
	define( 'WP_DEBUG_DISPLAY', false );
}

## Pods version

2.7.28

## Other super helpful information

None

<details>
<summary>WordPress Environment</summary>
  
```
N/A
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
N/A
```

</details>

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/46676cbe25114abe98cb79b4d1a509629c30b575
