### ISSUE TITLE
Suggestion: Automatically remove accents instead of the whole letter

### ISSUE THREAD

**Issue by alexfoffano** [pods-framework/pods#6079]
When creating a new field, accented letters on the labels are completely removed when the name is automatically generated. It would be better if only the accent was removed and the letter kept. It's not a big deal, as you can edit the name, but it would help people who speak languages that use a lot of accents.

Example: https://ibb.co/cwsVdmj

**Comment by JoryHogeveen** [comment]
This is because the name of the field is for internal use (database). Accents shouldn't be used there.
