### ISSUE TITLE
using save() causes issues with number field formatting for the NL locale (Netherlands)

### ISSUE THREAD

**Issue by winnersmedia** [pods-framework/pods#6083]
Example: When using save() where data includes a number field entered as "10.00" it get saved as "10,000".

This started to happen when setting up a wordpress website with the Polylang plugin default language as Netherlands.

Workaround at the moment is to set the number field formatting as "1,234" under the "Additional Field Options" tab in the Pods admin rather than "Localised Default"

**Comment by JoryHogeveen** [comment]
@MartvanderKruis 
Could you please test the patch in #6269 ?
