### ISSUE TITLE
Expand Conditional Logic from Pods core into fields

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#609]
There's no reason we can't expand the existing conditional logic into the pod fields themselves. We could use something similar to the way Gravity Forms does their Conditional Logic management, but I'm thinking we should keep it simple where possible. We don't need to have it do everything GF does there, just enough to fit the main use-cases such as conditions based on relationship set, or fields being empty or not.

Conditional logic is already built into the entire form system and UI, so it's just a matter of setting up the options in the admin area for the fields, and having some sort of parser in the field handler to automatically set the right classes.

## Conditional Logic for Fields

- [ ] New conditional logic handling to support logic checks per rule instead of whole groups by type
- [ ] Choose conditions for when a field will show or hide
- [ ] Choose to check for ALL conditions or ANY condition
- [ ] Comparison operators
  - [ ] Is (=)
  - [ ] Is not (!=)
  - [ ] Greater than (>)
  - [ ] Greater than or equal to (>= or ≥)
  - [ ] Lesser than (<)
  - [ ] Lesser than or equal to (<= or ≤)
  - [ ] Contains
  - [ ] Starts with
  - [ ] Ends with
  - [ ] Pattern (RegEx pattern, but limited character support) - optional feature
- [ ] Choices
  - [ ] Specific field value
  - [ ] Variables (from query string, current post object, etc)

### Gravity Forms

<img width="648" alt="Screen Shot 2022-01-05 at 9 46 20 PM" src="https://user-images.githubusercontent.com/709662/148326261-4338ba4d-46b7-42bc-b648-f6cf6a7979d2.png">

### Ninja Forms

<img width="902" alt="Screen Shot 2022-01-05 at 9 52 52 PM" src="https://user-images.githubusercontent.com/709662/148326286-8dd1688e-9f36-49c5-9638-6113924799b4.png">

### ACF

<img width="1400" alt="Screen Shot 2022-01-05 at 9 48 47 PM" src="https://user-images.githubusercontent.com/709662/148326323-b41a2a32-d4b3-4414-9068-f5895d572421.png">

<img width="1415" alt="Screen Shot 2022-01-05 at 9 47 51 PM" src="https://user-images.githubusercontent.com/709662/148326331-4a0af796-1a47-495d-8352-b9b61cb45a5d.png">

### WS Forms Pro

<img width="334" alt="Screen Shot 2022-01-05 at 10 07 24 PM" src="https://user-images.githubusercontent.com/709662/148326709-1c26de17-11ce-4980-947c-a6b914c15656.png">

<img width="233" alt="Screen Shot 2022-01-05 at 10 06 42 PM" src="https://user-images.githubusercontent.com/709662/148326716-6717977b-3b11-41b3-9b35-e21b95969134.png">

<img width="226" alt="Screen Shot 2022-01-05 at 10 07 05 PM" src="https://user-images.githubusercontent.com/709662/148326721-4c7ad712-63c3-4648-9d94-e93e55389ca4.png">

## Development complexity

This feature requires heavy user interface work to be done, but much of the logic is already supported in the underlying Field API within Pods right now.

## Out of scope, for the future

* We can merge in our existing logic based on logged in user, capability, or role
* We can add Conditional Logic to Groups

**Comment by kochhase** [comment]
Hi Scott

**Comment by sc0ttkclark** [comment]
Sorry, this is not a focus of Pods 3.0 and we have no current plans to add it to Pods 2.x as of yet.

**Comment by pcfreak30** [comment]
+1

**Comment by JoryHogeveen** [comment]
Very big +1 on this and would like to help! Is there any work already done?

**Comment by JoryHogeveen** [comment]
Could be that the repeater field option could be a requirement for this functionality since the user will need to add conditionals and I guess this will be a repeating combination of 3 fields `target field` | `compare type` | `value`

**Comment by pglewis** [comment]
I'm tasked with reworking the Pods field editor the moment 2.7 is done.  There is a good chance this piece will be reworked as part of that, I'd love to see that capability.

**Comment by JoryHogeveen** [comment]
Good to hear that! So 2.8?? It would be awesome if UI features like this could have a bit of focus :)
There are tons of use-cases where this will be very convenient. I have multiple sites where I use ACF of this. Would be great to have this all packed in one plugin.

**Comment by pglewis** [comment]
Yes, @sc0ttkclark has some specific field editor improvements in mind for 2.8 which means an overdue face-lift for that entire UI.  2.8 should at least lay the foundation for this if it doesn't actually bring it to fruition.

**Comment by sc0ttkclark** [comment]
Something we're looking into using: https://github.com/CacheControl/json-rules-engine

**Comment by Elxafil** [comment]
I know this is an old issue but was this added? If so how do I use it.

**Comment by jimtrue** [comment]
Per this code, this is code only, not UI: https://github.com/pods-framework/pods/pull/5137

**Comment by sc0ttkclark** [comment]
Conditional logic has been revamped for the new DFV code. Everything is working as expected there so all this ticket needs is to be addressed through a future interface.

**Comment by sc0ttkclark** [comment]
Based on the scope of this work, we'll need to revisit the conditional logic configuration structure to support AND/OR groups and handle logic checks per rule instead of as a whole ruleset of one type.
