### ISSUE TITLE
[Pods 2.8 Bug] Missing relationship objects

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6091]
## Pods 2.8 version

2.8.0-b-5

## Description

Not sure if this is even an issue but in Pods 2.7 you could relate to Setting Pods as well. In Pods 2.8 this isn't possible anymore.

Also other post objects like `custom_css`, `cusomize_changeset`, `wp_template` etc. aren't available anymore.

**Comment by sc0ttkclark** [comment]
All of these things were removed in 2.8.

* Relating to a Settings pod was a mistake, that should have been removed when we added the ability to relate to other pods. The problem there is that Settings are one instance, so it doesn't work at all.
* Custom CSS / Customize Changeset / WP Template etc were also removed from the list as we updated to remove some of the internal things from WP which we did not intend to support at this time
