### ISSUE TITLE
Fields - Order By - help&examples

### ISSUE THREAD

**Issue by justdudeone** [pods-framework/pods#6106]
Hello,
I've create Pods Custom Taxonomies and fill them with tons of Terms. Unfortunately WP does not have any functions for Terms custom ordering. (For example WooCommerce many time ago implement simple and effective "drag&drop" reordering of Products Attributes Terms). Thus I've found similar function for WP Taxonomies by plugin "YIKES Simple Taxonomy Ordering". Then I create Pods CPT with field "Relationship - Taxonomy" to use those Taxonomies. Question - how I can order Pods field Terms with custom order made by "YIKES Simple Taxonomy Ordering" plugin? 
At Pods field I see function "ORDER BY" but don't know what I must write there? I've try to search for any instruction many times but without success.
BTW will be nice to add to Pods field "ORDER BY" the tooltip similar to tooltip for Dates with php/jQuery date formats explanation.

**Comment by JoryHogeveen** [comment]
Hello @justdudeone 

Please see this topic: https://wordpress.org/support/topic/custom-field-relashionship-taxonomies-how-order-and-hide-from-post/

**Comment by justdudeone** [comment]
This possibility - the manual ordering of Taxonomies Terms for select fields is ENOUGH IMPORTANT! Maybe you will just add the same simple custom re-ordering by mouse functionality as "WooCommerce Product Attributes" or "YIKES Simple Taxonomy Ordering" or even "Pods Custom Groups&Fields" have to Pods Custom Taxonomies Terms?
And for select fields you can add a simple option like - Order by: A-Z, Z-A, Date (default DB order), Custom (manual order by mouse).
Then all select fields variants order will be much more native!

**Comment by JoryHogeveen** [comment]
Hello @justdudeone 

You can already add a numeric order field to your terms and order your query based on this field.
The only part that Pods does not add is the UI to drag and drop terms to order them within WordPress.
Since there is already a plugin for this (YIKES Simple Taxonomy Ordering) we will not re-invent the wheel. You can install this plugin to use it's functionality.

Cheers, Jory
