### ISSUE TITLE
[Pods 2.8 Bug] When max length is zero, it won't let you type

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6121]
## Pods 2.8 version

2.8 RC1

## Description

When adding a Plain Paragraph Text field, the Maximum Length is set to 0 by default, which makes it impossible to add any text to the field. Should be set to a minimum length, e.g. 255 characters.

## Testing instructions

1. Add a Plain Paragraph Text field to a Pod.
2. Try to add text to the field. Nothing happens.

## Expected behavior

1. Add a Plain Paragraph Text field to a Pod.
2. Try to add text to the field. Text can be added up to the minimum length of the field.
3. If the minimum length is reached, display a message indicating that the field has reached its limit.

## Possible workaround

Remember to check the Maximum Length of the field when adding a Plain Paragraph Text field until this is fixed.

## Other super helpful information

<details>
Running WP5.8 + Beaver Builder Standard 2.4.2.5 + Beaver Themer 1.3.3.1.
PHP7.4 + NGINX
</details>

**Comment by sc0ttkclark** [comment]
Fixed via e8e50c44cc687eb64ff0d16ab3026e62cf7f7833
