### ISSUE TITLE
Can't create a related post when editing the post it will relate to

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6122]
## Description

In Pods 2.7, I rely heavily on two-way relationships. An example is to have a Service CPT and a Testimonial CPT with a relationship between them.

When editing a Service post, I can either choose from a list of existing testimonials, or click New to add a new testimonial.

In Pod 2.8, this works up until the point when I click Publish on the new Testimonial. The testimonial is created and published, but all I see is a blank box where the New Testimonial window was. I then have to close it. After that, I need to reload the edit page for my Service post before the testimonial is visible on the Service post so I can link to it.

My expectation is what I would see in Pods 2.7.
- Click Publish on the Testimonial
- The Testimonial creation window disappears.
- The list of testimonials is refreshed automatically
- The testimonial I just added is already selected as being related.

Video here:

https://www.loom.com/share/422ac29e2d7e4ed8833f638b50f247e6

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6140
