### ISSUE TITLE
Conflict with Ninja Forms

### ISSUE THREAD

**Issue by morgank-atl** [pods-framework/pods#6129]
Don't know if this is something that you'll look into but I have a pro account with Ninja Forms and use them on all my sites. Unfortunately I just diagnosed an issue I was having with creating a new form as a conflict with Pods. I will report this issue to Nina Forms dev team as well. I love Pods and want to use it, and Ninja Forms.

If there's anything you might need for troubleshooting let me know.  Basically I did a "create new" form, selected the blank form, and then got a blank page.

**Comment by sc0ttkclark** [comment]
Which version of Ninja Forms and which version of Pods does this occur on? Do you see any other errors in your browser console?

**Comment by morgank-atl** [comment]
### Environment ###
Ninja Forms Version:     3.5.8
Ninja Forms DB Version:  1.4
Ninja Forms Gatekeeper:  33
Ninja Forms "Dev Mode":  Disabled
WP Version:              5.8.1 - Supported
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             7.4.23
MySQL Version:           5.5.5
SQL Version Variable:    10.3.31-MariaDB
PHP Locale:              negative_sign: </br>
WP Memory Limit:         40M
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      10 MB
PHP Post Max Size:       16M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       173.231.213.235
Host Name:               vps72194.inmotionhosting.com
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###

Activated Plugins:       Advanced Custom Fields: Extended by ACF Extended version 0.8.8.5
                         Advanced Custom Fields PRO by Delicious Brains version 5.10.2
                         Child Theme Generator by Serafino Corriero version 2.2.7
                         Ele Custom Skin Pro by Dudaster.com version 3.1.0
                         Ele Custom Skin by Dudaster.com version 3.1.3
                         Elementor Pro by Elementor.com version 3.4.1
                         Elementor by Elementor.com version 3.4.3
                         ICS Calendar Pro by Room 34 Creative Services
                         LLC version 3.2.0
                         ICS Calendar by Room 34 Creative Services
                         LLC version 8.1.2
                         Ninja Forms by Saturday Drive version 3.5.8
                         Pods - Custom Content Types and Fields by Pods Framework Team version 2.7.30
                         Premium Addons for Elementor by Leap13 version 4.5.4
                         Premium Addons PRO by Leap13 version 2.5.1
                         Say What? by Ademti Software version 2.0.2
                         WooCommerce Stripe Gateway by WooCommerce version 5.4.1
                         WOOF - WooCommerce Products Filter by realmag777 version 1.2.5.6
                         WooCommerce by Automattic version 5.6.0
                         Yoast SEO by Team Yoast version 17.1
                         WP Date and Time Shortcode by Denra.com aka SoftShop Ltd version 2.5.3

**Comment by morgank-atl** [comment]
Console log:

jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
DevTools failed to load source map: Could not load content for https://[SITEURL]/wp-content/plugins/ninja-forms/assets/js/lib/backbone.marionette.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM472:1 XHR finished loading: POST "https://[SITEURL]/wp-admin/admin-ajax.php".
(anonymous) @ VM472:1
send @ jquery.min.js?ver=3.6.0:2
ajax @ jquery.min.js?ver=3.6.0:2
s.ajax.s.ajax @ jquery-migrate.min.js?ver=3.3.2:2
S.<computed> @ jquery.min.js?ver=3.6.0:2
NinjaBatchProcessor.postToProcessor @ batch-processor.js?ver=3.5.8:74
NinjaBatchProcessor.modalData.onOpenCallback @ batch-processor.js?ver=3.5.8:60
onOpen @ ninjaModal.js?ver=3.5.8:176
(anonymous) @ jBox.min.js?ver=5.8.1:2
jBox.open @ jBox.min.js?ver=5.8.1:2
NinjaModal.toggleModal @ ninjaModal.js?ver=3.5.8:315
NinjaModal @ ninjaModal.js?ver=3.5.8:55
NinjaBatchProcessor @ batch-processor.js?ver=3.5.8:116
maybeOpenModal @ dashboard.min.js?ver=3.5.8:1
dispatch @ jquery.min.js?ver=3.6.0:2
v.handle @ jquery.min.js?ver=3.6.0:2
Navigated to https://[SITEURL]/wp-admin/admin.php?page=ninja-forms&form_id=new
jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
builder.js?ver=3.5.8:444 Uncaught TypeError: Cannot read properties of undefined (reading 'extend')
    at builder.js?ver=3.5.8:444
    at main (builder.js?ver=3.5.8:315)
    at callDep (builder.js?ver=3.5.8:181)
    at main (builder.js?ver=3.5.8:306)
    at callDep (builder.js?ver=3.5.8:181)
    at main (builder.js?ver=3.5.8:306)
    at callDep (builder.js?ver=3.5.8:181)
    at main (builder.js?ver=3.5.8:306)
    at callDep (builder.js?ver=3.5.8:181)
    at main (builder.js?ver=3.5.8:306)
(anonymous) @ builder.js?ver=3.5.8:444
main @ builder.js?ver=3.5.8:315
callDep @ builder.js?ver=3.5.8:181
main @ builder.js?ver=3.5.8:306
callDep @ builder.js?ver=3.5.8:181
main @ builder.js?ver=3.5.8:306
callDep @ builder.js?ver=3.5.8:181
main @ builder.js?ver=3.5.8:306
callDep @ builder.js?ver=3.5.8:181
main @ builder.js?ver=3.5.8:306
callDep @ builder.js?ver=3.5.8:181
main @ builder.js?ver=3.5.8:306
(anonymous) @ builder.js?ver=3.5.8:389
setTimeout (async)
req @ builder.js?ver=3.5.8:388
(anonymous) @ builder.js?ver=3.5.8:17353
e @ jquery.min.js?ver=3.6.0:2
t @ jquery.min.js?ver=3.6.0:2
setTimeout (async)
(anonymous) @ jquery.min.js?ver=3.6.0:2
c @ jquery.min.js?ver=3.6.0:2
fireWith @ jquery.min.js?ver=3.6.0:2
fire @ jquery.min.js?ver=3.6.0:2
c @ jquery.min.js?ver=3.6.0:2
fireWith @ jquery.min.js?ver=3.6.0:2
ready @ jquery.min.js?ver=3.6.0:2
B @ jquery.min.js?ver=3.6.0:2
VM6:1 Fetch finished loading: GET "https://syndication.twitter.com/settings?session_id=b5a2456ec524a919bbc214d1c5b826bc109efeec".
(anonymous) @ VM6:1
request @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:18
e.exports @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:18
(anonymous) @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:18
r @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:5
(anonymous) @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:18
r @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:5
(anonymous) @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:5
(anonymous) @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:5
(anonymous) @ widget_iframe.f88235f49a156f8b4cab34c7bc1a0acc.html?origin=https%3A%2F%2F[SITEURL]:18
VM668:1 XHR finished loading: POST "https://[SITEURL]/wp-admin/admin-ajax.php".
(anonymous) @ VM668:1
send @ jquery.min.js?ver=3.6.0:2
ajax @ jquery.min.js?ver=3.6.0:2
s.ajax.s.ajax @ jquery-migrate.min.js?ver=3.3.2:2
l @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
setTimeout (async)
d @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
e @ jquery.min.js?ver=3.6.0:2
t @ jquery.min.js?ver=3.6.0:2
setTimeout (async)
(anonymous) @ jquery.min.js?ver=3.6.0:2
c @ jquery.min.js?ver=3.6.0:2
fireWith @ jquery.min.js?ver=3.6.0:2
fire @ jquery.min.js?ver=3.6.0:2
c @ jquery.min.js?ver=3.6.0:2
fireWith @ jquery.min.js?ver=3.6.0:2
ready @ jquery.min.js?ver=3.6.0:2
B @ jquery.min.js?ver=3.6.0:2
VM668:1 XHR finished loading: POST "https://[SITEURL]/wp-admin/admin-ajax.php".
(anonymous) @ VM668:1
send @ jquery.min.js?ver=3.6.0:2
ajax @ jquery.min.js?ver=3.6.0:2
s.ajax.s.ajax @ jquery-migrate.min.js?ver=3.3.2:2
l @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
setTimeout (async)
d @ heartbeat.min.js?ver=5.8.1:2
v @ heartbeat.min.js?ver=5.8.1:2
h @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
dispatch @ jquery.min.js?ver=3.6.0:2
v.handle @ jquery.min.js?ver=3.6.0:2
VM668:1 XHR finished loading: POST "https://[SITEURL]/wp-admin/admin-ajax.php".
(anonymous) @ VM668:1
send @ jquery.min.js?ver=3.6.0:2
ajax @ jquery.min.js?ver=3.6.0:2
s.ajax.s.ajax @ jquery-migrate.min.js?ver=3.3.2:2
l @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
setTimeout (async)
d @ heartbeat.min.js?ver=5.8.1:2
v @ heartbeat.min.js?ver=5.8.1:2
h @ heartbeat.min.js?ver=5.8.1:2
(anonymous) @ heartbeat.min.js?ver=5.8.1:2
dispatch @ jquery.min.js?ver=3.6.0:2
v.handle @ jquery.min.js?ver=3.6.0:2

**Comment by sc0ttkclark** [comment]
This was addressed in Pods 2.8, if you have a staging site you can test to confirm that. The official Pods 2.8 release will be as soon as we resolve the remaining open bugs.

Follow the testing instructions at: pods.io/2021/02/11/pods-2-8-beta-1-released-and-the-field-guide-to-pods-2-8

Here's where the code is located: https://github.com/pods-framework/pods/tree/release/2.8

**Comment by morgank-atl** [comment]
Thank for this. I don't have a test environment since my sites are pretty basic in terms of plugins and I don't do custom code other than CSS. I did find a temporary fix but look forward to the 2.8 release.
