### ISSUE TITLE
iPad Chrome Browser App - Cannot Change Time in DateTime picker

### ISSUE THREAD

**Issue by techprogrammer** [pods-framework/pods#6130]
Using iPad  - Chrome Browser App

When trying to change a Date/Time - You Cannot Change Time in the picker because it is disabled.

![132892499-5611a6ea-5001-45ba-be6a-6c6b1eb9a1a3](https://user-images.githubusercontent.com/5952458/133003401-a7b1576a-2156-4f12-862f-0ef386161b8c.jpg)

iPad Pro 12.9 Gen4
iOS 14.7.1
Chrome App 93.0.4577.39

Wordpress 5.81
Pods 2.7.30

1. Go to a Wordpress and setup a pods Date/Time field
  Date Format Type: Predefined format
  Date Format 09/10/2021
  Time format type 12 hour
  Time format 11:04am
  year range empty
  allow empty value uncheck
  Enable HTML5 input field UNCHECKED
Advanced
  Additional CSS Classes empty
  Input Helper --select --
  Default value {@date.Y-m-d H:i| today + 1 day 23 hours 59 minutes}
 Set default value empty
 Restrict access all unchecked

2. Go to the page with this field and try editing the time. Its greyed out and can't be edited.

If you use a PC or Mac with Chrome it is editable.

If you change Date/Time field to HTML5 input field, it works on iPad Pro.

**Comment by sc0ttkclark** [comment]
I'll check this out but if you have a staging site you can try running Pods 2.8 on, it'd be great to know if it's resolved already on that for you. I'll look more this weekend.

**Comment by techprogrammer** [comment]
Will test 2.8.

I don’t see 2.8 in the releases. How do I download it?
https://github.com/pods-framework/pods/releases

**Comment by sc0ttkclark** [comment]
Follow the testing instructions at: https://pods.io/2021/02/11/pods-2-8-beta-1-released-and-the-field-guide-to-pods-2-8/

Here's where the code is located: https://github.com/pods-framework/pods/tree/release/2.8

**Comment by pdclark** [comment]
Can't test this on iPad Chrome because I don't have an iPad, but in iOS Chrome for iPhone, the Date/Time picker doesn't display at all; the keyboard displays instead.

**Comment by sc0ttkclark** [comment]
Confirmed as resolve when testing on my iOS 15 iPad Pro via Chrome
