### ISSUE TITLE
[Pods 2.8 Bug] Pods Form ID Field

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#6132]
## Pods 2.8 version

Version 2.8.0-rc-1

## Description

Pods form is working now but displays an ID field. It causes problems when users change the ID number and save, especially in relational databases.

## Testing instructions

1. Create a pod, normal or advanced, or use my exported Pods package below.
2. On the page template, add this code: $pod = pods( 'member' ); echo $pod->form( ); The Member pod is from my exported package.
Here are the tutorials on the Pods site: https://pods.io/docs/code/pods/form/

## Expected behavior

The ID field should be hidden and IDs should not be changeable, like 2.7.30 

## Screenshots / screencast

Working version on Pods 2.7
http://176.32.230.22/codingpanda.co.uk/wp-content/uploads/Pods-2-7.png
No working on Pods 2.8
http://176.32.230.22/codingpanda.co.uk/wp-content/uploads/Pods-2-8.png

## Possible workaround

Like 2.7.30

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
`
### wp-core ###

version: 5.8.1
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: F:\xampp\htdocs\pprf-from-user
wordpress_size: loading...
uploads_path: F:\xampp\htdocs\pprf-from-user/wp-content/uploads
uploads_size: loading...
themes_path: F:\xampp\htdocs\pprf-from-user/wp-content/themes
themes_size: loading...
plugins_path: F:\xampp\htdocs\pprf-from-user/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.6 (latest version: 1.8)
author: the WordPress team
author_website: https://en-gb.wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: F:\xampp\htdocs\pprf-from-user/wp-content/themes/twentytwenty
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.8, author: WordPress Team (latest version: 2.1), Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team (latest version: 2.8), Auto-updates disabled
Twenty Twenty-One: version: 1.0, author: the WordPress team (latest version: 1.4), Auto-updates disabled

### wp-plugins-active (4) ###

Elementor: version: 3.4.3, author: Elementor.com, Auto-updates disabled
Elementor Pro: version: 3.4.1, author: Elementor.com, Auto-updates disabled
Panda Pods Repeater Field: version: 1.4.10, author: Dongjie Xu, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.0-rc-1, author: Pods Framework Team, Auto-updates disabled

### wp-plugins-inactive (1) ###

Pods - Custom Content Types and Fields: version: 2.7.30, author: Pods Framework Team, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 500M
max_effective_size: 500 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/8.0.6
php_version: 8.0.6 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 1800
memory_limit: 512M
max_input_time: 600
upload_max_filesize: 500M
php_post_max_size: 512M
curl_version: 7.75.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.4.19-MariaDB
client_version: mysqlnd 8.0.6

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: F:\xampp\htdocs\pprf-from-user/wp-content
WP_PLUGIN_DIR: F:\xampp\htdocs\pprf-from-user/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/8.0.6
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
pods-session-save-path: F:\xampp\tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 54.891M
pods-memory-current-usage-real: 8.000M
pods-network-wide: No
pods-install-location: F:\xampp\htdocs\pprf-from-user\wp-content\plugins\pods-release-2.8/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: Yes
pods-sessions: Disable sessions
pods-can-use-sessions: Yes
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>
{
    "meta": {
        "version": "2.8.0-rc-1",
        "build": 1631364904
    },
    "pods": [
        {
            "name": "member",
            "id": 6,
            "label": "Members",
            "description": "",
            "label_singular": "Member",
            "public": "1",
            "show_ui": "1",
            "type": "pod",
            "storage": "table",
            "pod_index": "name",
            "groups": [
                {
                    "name": "details",
                    "id": 134,
                    "label": "Details",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "name",
                            "id": 7,
                            "label": "Name",
                            "description": "",
                            "weight": 0,
                            "required": "1",
                            "type": "text"
                        },
                        {
                            "name": "created",
                            "id": 8,
                            "label": "Date Created",
                            "description": "",
                            "weight": 1,
                            "datetime_format": "ymd_slash",
                            "datetime_time_type": "12",
                            "datetime_time_format": "h_mm_ss_A",
                            "type": "datetime"
                        },
                        {
                            "name": "modified",
                            "id": 9,
                            "label": "Date Modified",
                            "description": "",
                            "weight": 2,
                            "datetime_format": "ymd_slash",
                            "datetime_time_type": "12",
                            "datetime_time_format": "h_mm_ss_A",
                            "type": "datetime"
                        },
                        {
                            "name": "author",
                            "id": 10,
                            "label": "Author",
                            "description": "",
                            "weight": 3,
                            "pick_format_type": "single",
                            "pick_format_single": "autocomplete",
                            "default_value": "{@user.ID}",
                            "type": "pick",
                            "pick_object": "user"
                        },
                        {
                            "name": "permalink",
                            "id": 11,
                            "label": "Permalink",
                            "description": "Leave blank to auto-generate from Name",
                            "weight": 4,
                            "type": "slug"
                        }
                    ]
                }
            ]
        }
    ]
}
```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by sc0ttkclark** [comment]
Fixed via e545c491a6efcc832203ec6d533819cb22649550
