### ISSUE TITLE
[Pods 2.8 Bug] Network requests never end if they fail on Block Editor server-side render

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#6135]
When a network request is made from the Block Editor for the server-side render, and if it fails, it keeps retrying. It never stops retrying.

I had my test site open over the past couple of days and then I went to go to the Edit Page screen where it has blocks and the server-side render requests just keep going on loop. The network responses from the server-side render appear to continue forever (after failure, it just runs again):

`{"code":"rest_cookie_invalid_nonce","message":"Cookie check failed","data":{"status":403}}`

This request along with the `admin-ajax.php?action=rest-nonce` appear one after the other.

I'm not sure what caused my REST nonces to be busted since I have done a complete page reload and my normal WP auth is still valid -- but we should at least stop the forever-requests. Max retries should be maybe 3, if those fail then throw a notice onto the screen about a failed load of the block previews?

**Comment by zrothauser** [comment]
This only applies if the error is due to an invalid nonce.

The retry comes from the WP core `api-fetch` wrapper around `fetch`:
https://github.com/WordPress/gutenberg/blob/trunk/packages/api-fetch/src/index.js#L172-L185
