### ISSUE TITLE
Text gets lost when pasting text into a WYSIWYG text area field.

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6141]
## Pods 2.8 version

2.8 RC1

## Description

1. Copy and paste text from Word into a WYSIWYG field with existing content in Visual mode.
2. Switch to Text mode. New and old text is visible.
3. Switch back to Visual mode. New text has disappeared.

## Expected behavior

New text not disappearing would be nice :)

## Screenshots / screencast

https://www.loom.com/share/2db15bc19cb743cd9283bccf04718114

## Possible workaround

Don't switch to Text mode after pasting.

## Other super helpful information

Tried in other WYSIWYG fields on the same page with same result..

**Comment by sc0ttkclark** [comment]
@zrothauser Confirmed, you'll want to put content into the field, then save it, and then reload the page.

Then try pasting some text in or changing the field value at all from visual. Go to text, then switch back to visual. It ends up just replacing the visual content with what it loaded on the page initially with. May be a state related thing here.
