### ISSUE TITLE
File/Image/Video field, Multiple Files, max files set to 0

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6145]
## Description

I changed a File/Image/Video field from single to multiple and found I couldn't upload any more. The Max Number of Files field was set to 0. Changed it to 6 and was able to upload more.

**Another related issue** - when adding a 7th image (when limit set to 6) the first image is removed to make room for the new image. I assume it should not be possible to add any more images after the limit has been reached. Perhaps the Add File button text should change to something else once the limit has been reached?

**Another related issue** I can't reorder images once I've added them. The handles for moving them are showing but they don't work.

## Possible workaround

Make sure to check the max files amount when adding this field type to support multiple images.

## Pods version

2.8 RC1

## Other super helpful information

Running Happy Files Pro, which allows you to organise the media libraries into categories/folders. Disabled it to see if I could add multiple images but that didn't help.

<summary>WordPress Environment</summary>

Latest WordPress, Astra, Beaver Builder, UABB, Powerpack.

**Comment by sc0ttkclark** [comment]
@millionleaves I believe I've fixed the issue with the max files problem, it's no longer having a problem for me on my local site when I've been testing it. We'll have to work on adding additional logic to prevent uploading new files when it hits the limit (so it disables the field or shows a message). We'll work on that in a future release at some point.

@zrothauser The issue with reordering file fields is still a problem for you to sort through.
