### ISSUE TITLE
[Pods 2.8 Bug] Post ID isn't passed using Plupload AJAX uploader

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6146]
Might also be a 2.7 issue. Going to test a.s.a.p.:
Initial report: https://wordpress.org/support/topic/magic-tags-in-custom-upload-directory/

## Pods 2.8 version

2.8.0-rc.1

## Description

When using Plupload we also send the current post. This is used for uploading context.
This isn't send anymore in Pods 2.8
https://github.com/pods-framework/pods/blob/main/classes/fields/file.php#L535-L540

## Testing instructions

4. See error message '....'

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by sc0ttkclark** [comment]
Great find!

Fixed via 39166daf2454297f55f8c8606fad0faf3975b31d
