### ISSUE TITLE
[Pods 2.8 Bug] i18n component - Group names aren't translated

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6148]
## Pods 2.8 version

RC-1

## Description

After migrating the i18n component to 2.8 I've forgot to add support for Group names/labels.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark I can't find any filters that I can use for group labels.
We could add a filter within get_groups in PodsMeta (`pods_groups_label` for example) but not sure what you would prefer for filter names and maybe other locations.
Important note on this is that this should ONLY affect display, not any actual settings of the `Groups` object.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen I just introduced via 3d20b254a3f57aa22954d3968ab21dc24092cb6a new filters to override the label/description of any Whatsit object.

That means pods, groups, and fields all have the same exact override handling.

I suggest switching to hooking into these filters for overriding the label/description for any object:

* `apply_filters( 'pods_whatsit_get_label', $label, $this )`
* `apply_filters( 'pods_whatsit_get_description', $description, $this )`

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6149
