### ISSUE TITLE
[Pods 2.8 Bug] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by po8digital** [pods-framework/pods#6152]
## Pods 2.8 version

2.8.0-rc.1

## Description

`count(): Parameter must be an array or an object that implements Countable`

## Screenshots / screencast

![count-must-be-an-array-or-an-object-that-implements-countable](https://user-images.githubusercontent.com/37078587/135050982-07723c78-09d7-48d6-9378-853a1c38972a.png)

**Comment by sc0ttkclark** [comment]
Thanks for this, on it!
