### ISSUE TITLE
App using REST API doesn't work after upgrade to 2.8

### ISSUE THREAD

**Issue by carlosrovira** [pods-framework/pods#6175]
## Description

I have a third party app using REST API. It's not working with 2.8. If I revert to 2.7 works again
I check end points and see fields are now removed. I guess there should be some way to get it back again, but after looking over website can't figure how to do it

this is the current url that works with 2.7.31:
https://mysite.com/wp-json/wp/v2/product/

How should it looks now in 2.8?

thanks

**Comment by sc0ttkclark** [comment]
I'll have a look at this, we optimized the calls for REST API stuff in 2.8 so I'll see if something went wrong in the last batch of work there.

**Comment by carlosrovira** [comment]
Hi @sc0ttkclark, I'd swear this was working on the latest RC2 or RC3. Where I can find RCs zip to try it?

**Comment by jamesgol** [comment]
Are you at least seeing all of the non-Pod specific fields in the REST result?  I've tested with the default settings and overriding the endpoint and it works as expected for me.

**Comment by sc0ttkclark** [comment]
It looks like this is resolved now, I'll do some more testing before we release 2.8.1 to be sure unless someone else can confirm.
