### ISSUE TITLE
Use SVG for menu icon

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#6177]
We should try to use an SVG for the menu icon if we can figure it out. All my efforts seemed to show a big square in the middle of the logo so something is wrong with the SVG I was using or it may not be possible. Whatever we choose needs to avoid loading our stylesheet on every page for a custom font.

**Comment by JoryHogeveen** [comment]
There is something wrong with the SVG format, the logo path is inaccessible for editors and other software due to the way it's exported. Can only be fixed in the SVG code.
