### ISSUE TITLE
Swiss Currency Symbols

### ISSUE THREAD

**Issue by apothekenschrank** [pods-framework/pods#6184]
## Description

The Swiss currency code is CHF and it is currently also the official "symbol" for price tags. Before, "sFr" was used to differentiate it against the French Franks, which do not exist anymore. "Fr." is certainly not correct. Please change this or provide more options to display it. 
I further noticed that the currency code symbol ahead of the entry field (backend) is always $. It used to match the set currency.

Thank you for looking at this.

## Pods version

5.8.1

**Comment by JoryHogeveen** [comment]
@apothekenschrank 
You can always use the filter `pods_form_ui_field_currency_currencies` to modify existing currencies in Pods.

**Comment by sc0ttkclark** [comment]
Fixed via bca09a521bb960b050b640998198b553456c91c5
