### ISSUE TITLE
Pods 2.8 - Relationship field -> Simple (custom defined list) "parent output" empty

### ISSUE THREAD

**Issue by robpie-de** [pods-framework/pods#6189]
the relationship field output of an "parent" object of an pod did'nt work anymore. 

before i got the field value of e.g.: **$pod->display('mypod.field1');** this is now empty and in date field type it returns "0000-00-00" intead of "" (nothing), by trying to acces the field directly with: **$other_pod->display('field1');** field value returns correctly...

looks like the acces to the Relationship field of an related pods did not work. hope someone understand.

**Comment by jamesgol** [comment]
Can you export your Pods package that has your two pods in it?
