### ISSUE TITLE
Custom post types stopped showing after update

### ISSUE THREAD

**Issue by sensitive--boy** [pods-framework/pods#6192]
I have created several custom post types with pods. After updating to 2.8. the posts I call through fetch() do not show up on the website anymore. seems like there is no result in my function:

      $params = array('limit' => 300);
      $quotes = pods('zitat', $params);
      while ( $quotes->fetch() ) {
         echo ....
     }

Other posts, called through shortcut are still working. 
I rolled back the update with my backup but still the posts don't show up.

**Comment by sc0ttkclark** [comment]
I can't reproduce this at the moment, if you are on our [Slack](https://support.pods.io/chat/), feel free to hop on and ping me to discuss further.
