### ISSUE TITLE
Invalid number_max prop type

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6199]
Warning: Failed prop type: Invalid prop `allPodFields[172].number_max` of type `number` supplied to `DynamicTabContent`, expected `string`.

**Comment by sc0ttkclark** [comment]
Fixed via bd9231a5433f390d3ae6ec6bdb9fbee028a21e98

Just noting -- in the future stuff that gets sent to DFV will be properly prepared and typed at some point. So booleans will be false/true, etc.

Same from the Whatsit object args, when you call an arg that you know is a bool, you don't have to cast, you just check true/false.

Those improvements will come later with additional time.
