### ISSUE TITLE
Pods 2.8.0 WP-Admin interfaces don't work on Safari 15.0 (Mac BigSur 11.6)

### ISSUE THREAD

**Issue by VanWebDev** [pods-framework/pods#6204]
## Description

The Pods interfaces in WP-Admin don't work on Safari 15.0 on Mac Big Sur 11.6

- When trying to add or extend a post type, it only shows the animated grey loading bars instead of the fields. 
- When trying to add a post with custom fields, it only shows the animated grey loading bars where the custom fields should be. 
- The default wordpress editor doesn't appear to be affected, but the custom fields are.
- I have disabled all other plugins and the theme in use is a basic child of the twenty-twentyone default theme

## Testing instructions

1. Go to Pods Admin in WP-Admin panel
2. Try to add new Post Type or Extend Existing Post Type - fields display as animated grey bars
AND
3. Go to Pods Admin -> Edit Pods -> Edit any existing Post Type or Taxonomy - only shows blank screen
AND
4. Go to any existing Pods CPT and try to add or edit a post - fields display as animated grey bars

## Expected behavior

I expect to see the proper interface to add and edit my pods and content.

## Screenshots / screencast

![Create-PostType](https://user-images.githubusercontent.com/30353963/138143242-c0b17fcb-2c58-4fae-8834-6e5a8023cb7f.jpg)

![Edit-ExistingPodCPT](https://user-images.githubusercontent.com/30353963/138143240-c310382b-bc22-4748-b0f2-0e0039b20599.jpg)

![CreateNewPost-PodsCPT](https://user-images.githubusercontent.com/30353963/138143236-28668bdc-0c98-40e7-a59d-99669c340094.jpg)

![CreateNewPost-PodsCPT-2](https://user-images.githubusercontent.com/30353963/138144298-53c97971-cf87-4087-9d8a-272bfc615a77.jpg)

![CreateNewPost-PodsCPT-DefaultEditorOnly](https://user-images.githubusercontent.com/30353963/138144308-a1f890d8-72e7-4ab1-9b5b-1f139710f186.jpg)

## Possible workaround

Only workaround is to change to Chrome or Firefox browsers (or possibly other browsers which I haven't tested)

## Pods version

2.8.0

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
`
### wp-core ###

version: 5.8.1
site_language: en_CA
user_language: en_CA
timezone: America/Vancouver
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: undefined
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/feathery/public_html/devsites/GDC/content
wordpress_size: 48.31 MB (50653111 bytes)
uploads_path: /home/feathery/public_html/devsites/GDC/content/wp-content/uploads
uploads_size: 873.62 KB (894589 bytes)
themes_path: /home/feathery/public_html/devsites/GDC/content/wp-content/themes
themes_size: 3.62 MB (3799977 bytes)
plugins_path: /home/feathery/public_html/devsites/GDC/content/wp-content/plugins
plugins_size: 56.38 MB (59123941 bytes)
database_size: 1.77 MB (1857457 bytes)
total_size: 110.94 MB (116329075 bytes)

### wp-active-theme ###

name: Twenty Twentyone Child (twentytwentyone-child)
version: 1.0
author: Vancouver Web Dev
author_website: https://jenweb.dev/
parent_theme: Twenty Twenty-One (twentytwentyone)
theme_features: core-block-patterns, widgets, widgets-block-editor, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units
theme_path: /home/feathery/public_html/devsites/GDC/content/wp-content/themes/twentytwentyone-child
auto_update: Disabled

### wp-parent-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.4
author: the WordPress team
author_website: https://en-ca.wordpress.org/
theme_path: /home/feathery/public_html/devsites/GDC/content/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-plugins-active (1) ###

Pods - Custom Content Types and Fields: version: 2.8.0, author: Pods Framework Team, Auto-updates disabled

### wp-plugins-inactive (10) ###

Admin Menu Editor: version: 1.9.10, author: Janis Elsts, Auto-updates disabled
Category Order and Taxonomy Terms Order: version: 1.5.7.7, author: Nsp-Code, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Classic Widgets: version: 0.2, author: WordPress Contributors, Auto-updates disabled
Favicon by RealFaviconGenerator: version: 1.3.22, author: Philippe Bernard, Auto-updates disabled
Post Types Order: version: 1.9.5.7, author: Nsp Code, Auto-updates disabled
Safe SVG: version: 1.9.9, author: Daryll Doyle, Auto-updates disabled
Wordfence Security: version: 7.5.6, author: Wordfence, Auto-updates disabled
WPForms Lite: version: 1.7.0, author: WPForms, Auto-updates disabled
Yoast SEO: version: 17.4, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1802
imagemagick_version: ImageMagick 7.0.10-10 Q16 x86_64 2020-07-09 https://imagemagick.org
imagick_version: 3.4.4
file_uploads: File uploads is turned off
post_max_size: 64M
upload_max_filesize: 64M
max_effective_size: 64 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.24 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 64M
php_post_max_size: 64M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 5.7.36
client_version: 5.7.35

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/feathery/public_html/devsites/GDC/content/wp-content
WP_PLUGIN_DIR: /home/feathery/public_html/devsites/GDC/content/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 42.450M
pods-memory-current-usage-real: 44.500M
pods-network-wide: No
pods-install-location: /home/feathery/public_html/devsites/GDC/content/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: Yes

`
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

{
    "meta": {
        "version": "2.8.0",
        "build": 1634752260
    },
    "pods": [
        {
            "name": "challenge_category",
            "id": 119,
            "label": "Challenge Categories",
            "description": "",
            "label_singular": "Challenge Category",
            "public": "1",
            "show_ui": "1",
            "supports_title": "1",
            "supports_editor": "0",
            "type": "post_type",
            "storage": "meta",
            "publicly_queryable": "1",
            "exclude_from_search": "0",
            "capability_type": "post",
            "capability_type_custom": "challenge_category",
            "capability_type_extra": "1",
            "has_archive": "0",
            "hierarchical": "0",
            "rewrite": "1",
            "rewrite_with_front": "1",
            "rewrite_feeds": "0",
            "rewrite_pages": "1",
            "query_var": "1",
            "can_export": "1",
            "default_status": "draft",
            "supports_author": "0",
            "supports_thumbnail": "0",
            "supports_excerpt": "0",
            "supports_trackbacks": "0",
            "supports_custom_fields": "0",
            "supports_comments": "0",
            "supports_revisions": "0",
            "supports_page_attributes": "0",
            "supports_post_formats": "0",
            "built_in_taxonomies_category": "0",
            "built_in_taxonomies_link_category": "0",
            "built_in_taxonomies_post_tag": "0",
            "built_in_taxonomies_wp_theme": "0",
            "show_in_menu": "1",
            "menu_position": "0",
            "show_in_nav_menus": "1",
            "show_in_admin_bar": "1",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "built_in_taxonomies_division": "1",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 172,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "intro",
                            "id": 121,
                            "label": "Intro",
                            "description": "",
                            "weight": 0,
                            "type": "wysiwyg",
                            "required": "0",
                            "wysiwyg_editor": "tinymce",
                            "wysiwyg_media_buttons": "1",
                            "wysiwyg_editor_height": "50",
                            "wysiwyg_oembed": "0",
                            "wysiwyg_wptexturize": "1",
                            "wysiwyg_convert_chars": "1",
                            "wysiwyg_wpautop": "1",
                            "wysiwyg_allow_shortcode": "0",
                            "wysiwyg_allowed_html_tags": "strong em a ul ol li b i br p div embed iframe img video audio h2 h3 h4 h5",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        },
                        {
                            "name": "sub_categories",
                            "id": 122,
                            "label": "Sub Categories",
                            "description": "",
                            "weight": 1,
                            "type": "paragraph",
                            "required": "0",
                            "paragraph_allow_html": "1",
                            "paragraph_oembed": "0",
                            "paragraph_wptexturize": "1",
                            "paragraph_convert_chars": "1",
                            "paragraph_wpautop": "1",
                            "paragraph_allow_shortcode": "0",
                            "paragraph_allowed_html_tags": "strong em a ul ol li b i br",
                            "paragraph_max_length": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        },
                        {
                            "name": "types_preparation",
                            "id": 123,
                            "label": "Types & Preparation",
                            "description": "",
                            "weight": 2,
                            "type": "wysiwyg",
                            "required": "0",
                            "wysiwyg_editor": "tinymce",
                            "wysiwyg_media_buttons": "1",
                            "wysiwyg_oembed": "0",
                            "wysiwyg_wptexturize": "1",
                            "wysiwyg_convert_chars": "1",
                            "wysiwyg_wpautop": "1",
                            "wysiwyg_allow_shortcode": "0",
                            "wysiwyg_allowed_html_tags": "strong em a ul ol li b i br p div embed iframe img video audio h2 h3 h4 h5",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        },
        {
            "name": "competitor_info",
            "id": 32,
            "label": "Competitor Info",
            "description": "",
            "label_singular": "Competitor Info",
            "public": "1",
            "show_ui": "1",
            "supports_title": "1",
            "supports_editor": "1",
            "type": "post_type",
            "storage": "meta",
            "publicly_queryable": "1",
            "exclude_from_search": "0",
            "capability_type": "post",
            "capability_type_custom": "competition",
            "capability_type_extra": "1",
            "has_archive": "0",
            "hierarchical": "0",
            "rewrite": "1",
            "rewrite_with_front": "1",
            "rewrite_feeds": "0",
            "rewrite_pages": "1",
            "query_var": "1",
            "can_export": "1",
            "default_status": "draft",
            "supports_author": "0",
            "supports_thumbnail": "0",
            "supports_excerpt": "0",
            "supports_trackbacks": "0",
            "supports_custom_fields": "0",
            "supports_comments": "0",
            "supports_revisions": "0",
            "supports_page_attributes": "0",
            "supports_post_formats": "0",
            "built_in_taxonomies_category": "0",
            "built_in_taxonomies_link_category": "0",
            "built_in_taxonomies_post_tag": "0",
            "built_in_taxonomies_wp_theme": "0",
            "show_in_menu": "1",
            "menu_position": "0",
            "show_in_nav_menus": "1",
            "show_in_admin_bar": "1",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "built_in_taxonomies_division": "0",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 173,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": []
                }
            ]
        },
        {
            "name": "division",
            "id": 120,
            "label": "Divisions",
            "description": "",
            "label_singular": "Division",
            "public": "1",
            "show_ui": "1",
            "hierarchical": "1",
            "type": "taxonomy",
            "storage": "meta",
            "rewrite": "1",
            "rewrite_with_front": "1",
            "rewrite_hierarchical": "1",
            "capability_type": "default",
            "capability_type_custom": "division",
            "query_var": "0",
            "sort": "0",
            "built_in_post_types_challenge_category": "1",
            "built_in_post_types_competitor_info": "0",
            "built_in_post_types_custom_css": "0",
            "built_in_post_types_customize_changeset": "0",
            "built_in_post_types_honorary_advisor": "0",
            "built_in_post_types_oembed_cache": "0",
            "built_in_post_types_page": "0",
            "built_in_post_types_post": "0",
            "built_in_post_types_user_request": "0",
            "built_in_post_types_wp_block": "0",
            "built_in_post_types_wp_template": "0",
            "built_in_post_types_wpforms": "0",
            "built_in_post_types_attachment": "0",
            "show_in_menu": "1",
            "menu_location": "default",
            "menu_position": "0",
            "show_in_nav_menus": "1",
            "show_tagcloud": "1",
            "show_tagcloud_in_edit": "1",
            "show_in_quick_edit": "1",
            "show_admin_column": "0",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "get_the_archive_description",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 175,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": []
                }
            ]
        },
        {
            "name": "honorary_advisor",
            "id": 116,
            "label": "Honorary Advisors",
            "description": "",
            "label_singular": "Honorary Advisor",
            "public": "1",
            "show_ui": "1",
            "supports_title": "1",
            "supports_editor": "0",
            "type": "post_type",
            "storage": "meta",
            "publicly_queryable": "1",
            "exclude_from_search": "1",
            "capability_type": "post",
            "capability_type_custom": "honorary_advisor",
            "capability_type_extra": "1",
            "has_archive": "0",
            "hierarchical": "0",
            "rewrite": "1",
            "rewrite_with_front": "1",
            "rewrite_feeds": "0",
            "rewrite_pages": "1",
            "query_var": "1",
            "can_export": "1",
            "default_status": "draft",
            "supports_author": "0",
            "supports_thumbnail": "0",
            "supports_excerpt": "0",
            "supports_trackbacks": "0",
            "supports_custom_fields": "0",
            "supports_comments": "0",
            "supports_revisions": "0",
            "supports_page_attributes": "0",
            "supports_post_formats": "0",
            "built_in_taxonomies_category": "0",
            "built_in_taxonomies_link_category": "0",
            "built_in_taxonomies_post_tag": "0",
            "built_in_taxonomies_wp_theme": "0",
            "show_in_menu": "1",
            "menu_position": "0",
            "show_in_nav_menus": "1",
            "show_in_admin_bar": "1",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "built_in_taxonomies_division": "0",
            "groups": [
                {
                    "name": "more_fields",
                    "label": "More Fields",
                    "fields": [
                        {
                            "name": "photo",
                            "id": 117,
                            "label": "Photo",
                            "description": "",
                            "weight": 0,
                            "type": "file",
                            "pick_object": "custom-simple",
                            "required": "0",
                            "text_allow_shortcode": "0",
                            "text_allow_html": "0",
                            "phone_enable_phone_extension": "1",
                            "paragraph_allow_html": "1",
                            "paragraph_oembed": "0",
                            "paragraph_wptexturize": "1",
                            "paragraph_convert_chars": "1",
                            "paragraph_wpautop": "1",
                            "paragraph_allow_shortcode": "0",
                            "wysiwyg_media_buttons": "1",
                            "wysiwyg_oembed": "0",
                            "wysiwyg_wptexturize": "1",
                            "wysiwyg_convert_chars": "1",
                            "wysiwyg_wpautop": "1",
                            "wysiwyg_allow_shortcode": "0",
                            "code_allow_shortcode": "0",
                            "file_format_type": "single",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "0",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_restrict_filesize": "10MB",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "file_wp_gallery_output": "0",
                            "file_wp_gallery_link": "post",
                            "file_wp_gallery_columns": "1",
                            "file_wp_gallery_random_sort": "0",
                            "file_wp_gallery_size": "thumbnail",
                            "oembed_enabled_providers_amazoncn": "0",
                            "oembed_enabled_providers_amazoncouk": "0",
                            "oembed_enabled_providers_amazoncom": "0",
                            "oembed_enabled_providers_amazoncomau": "0",
                            "oembed_enabled_providers_amazonin": "0",
                            "oembed_enabled_providers_animotocom": "0",
                            "oembed_enabled_providers_cloudupcom": "0",
                            "oembed_enabled_providers_crowdsignalcom": "0",
                            "oembed_enabled_providers_dailymotioncom": "0",
                            "oembed_enabled_providers_flickrcom": "0",
                            "oembed_enabled_providers_imgurcom": "0",
                            "oembed_enabled_providers_issuucom": "0",
                            "oembed_enabled_providers_kickstartercom": "0",
                            "oembed_enabled_providers_meetupcom": "0",
                            "oembed_enabled_providers_mixcloudcom": "0",
                            "oembed_enabled_providers_redditcom": "0",
                            "oembed_enabled_providers_reverbnationcom": "0",
                            "oembed_enabled_providers_screencastcom": "0",
                            "oembed_enabled_providers_scribdcom": "0",
                            "oembed_enabled_providers_slidesharenet": "0",
                            "oembed_enabled_providers_smugmugcom": "0",
                            "oembed_enabled_providers_someecardscom": "0",
                            "oembed_enabled_providers_soundcloudcom": "0",
                            "oembed_enabled_providers_speakerdeckcom": "0",
                            "oembed_enabled_providers_spotifycom": "0",
                            "oembed_enabled_providers_tedcom": "0",
                            "oembed_enabled_providers_tiktokcom": "0",
                            "oembed_enabled_providers_tumblrcom": "0",
                            "oembed_enabled_providers_twittercom": "0",
                            "oembed_enabled_providers_vimeocom": "0",
                            "oembed_enabled_providers_wordpresscom": "0",
                            "oembed_enabled_providers_wordpresstv": "0",
                            "oembed_enabled_providers_youtubecom": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        },
                        {
                            "name": "description_text",
                            "id": 118,
                            "label": "Description Text",
                            "description": "",
                            "weight": 1,
                            "type": "paragraph",
                            "required": "0",
                            "text_allow_shortcode": "0",
                            "text_allow_html": "0",
                            "phone_enable_phone_extension": "1",
                            "paragraph_allow_html": "1",
                            "paragraph_oembed": "0",
                            "paragraph_wptexturize": "1",
                            "paragraph_convert_chars": "1",
                            "paragraph_wpautop": "1",
                            "paragraph_allow_shortcode": "0",
                            "paragraph_allowed_html_tags": "strong em a ul ol li b i",
                            "paragraph_max_length": "0",
                            "wysiwyg_media_buttons": "1",
                            "wysiwyg_oembed": "0",
                            "wysiwyg_wptexturize": "1",
                            "wysiwyg_convert_chars": "1",
                            "wysiwyg_wpautop": "1",
                            "wysiwyg_allow_shortcode": "0",
                            "code_allow_shortcode": "0",
                            "oembed_enabled_providers_amazoncn": "0",
                            "oembed_enabled_providers_amazoncouk": "0",
                            "oembed_enabled_providers_amazoncom": "0",
                            "oembed_enabled_providers_amazoncomau": "0",
                            "oembed_enabled_providers_amazonin": "0",
                            "oembed_enabled_providers_animotocom": "0",
                            "oembed_enabled_providers_cloudupcom": "0",
                            "oembed_enabled_providers_crowdsignalcom": "0",
                            "oembed_enabled_providers_dailymotioncom": "0",
                            "oembed_enabled_providers_flickrcom": "0",
                            "oembed_enabled_providers_imgurcom": "0",
                            "oembed_enabled_providers_issuucom": "0",
                            "oembed_enabled_providers_kickstartercom": "0",
                            "oembed_enabled_providers_meetupcom": "0",
                            "oembed_enabled_providers_mixcloudcom": "0",
                            "oembed_enabled_providers_redditcom": "0",
                            "oembed_enabled_providers_reverbnationcom": "0",
                            "oembed_enabled_providers_screencastcom": "0",
                            "oembed_enabled_providers_scribdcom": "0",
                            "oembed_enabled_providers_slidesharenet": "0",
                            "oembed_enabled_providers_smugmugcom": "0",
                            "oembed_enabled_providers_someecardscom": "0",
                            "oembed_enabled_providers_soundcloudcom": "0",
                            "oembed_enabled_providers_speakerdeckcom": "0",
                            "oembed_enabled_providers_spotifycom": "0",
                            "oembed_enabled_providers_tedcom": "0",
                            "oembed_enabled_providers_tiktokcom": "0",
                            "oembed_enabled_providers_tumblrcom": "0",
                            "oembed_enabled_providers_twittercom": "0",
                            "oembed_enabled_providers_vimeocom": "0",
                            "oembed_enabled_providers_wordpresscom": "0",
                            "oembed_enabled_providers_wordpresstv": "0",
                            "oembed_enabled_providers_youtubecom": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        },
        {
            "name": "page",
            "id": 166,
            "label": "Page",
            "description": "",
            "type": "post_type",
            "storage": "meta",
            "object": "page",
            "_migrated_28": "1",
            "built_in_taxonomies_division": "0",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 167,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "banner_image",
                            "id": 168,
                            "label": "Banner Image",
                            "description": "",
                            "weight": 0,
                            "type": "file",
                            "sister_id": "-- Select One --",
                            "required": "0",
                            "file_format_type": "single",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "0",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "roles_allowed": "administrator",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        }
    ]
}

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by VanWebDev** [comment]
Yes, those two screens display correctly, but if I try to Edit a pod on your first screenshot, or Create New or Extend Existing on the second one, that's where the issue happens. 

I cleared browser cache, pods cache, and used a private window. The issue still happens.

**Comment by VanWebDev** [comment]
Ahh, yes...Does this help? 

<img width="1125" alt="Screen Shot 2021-10-20 at 11 28 40 AM" src="https://user-images.githubusercontent.com/30353963/138150582-690b79c1-6cea-4c9b-aa8d-b7d75dfee627.png">

**Comment by pdclark** [comment]
Oh boy. Sounds like there may have been a partial install? Some of the JavaScript files aren't loading? What if you remove and re-install the plugin?
