### ISSUE TITLE
Pods auto-templates not working with WPML

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6218]
## Description

Pods auto-templates are loaded by name (title) and not ID.
This is an issue with translation plugins because these plugins translate posts by ID (and our integration code does the same).

Two options, probable best to do both!
- Change the auto-templates loading and allow loading by ID (prefferable)
- Hook into the auto-templates after the template is loaded by ID.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6219
