### ISSUE TITLE
FormidableForms "Create Post" Action not saving some fields on submit

### ISSUE THREAD

**Issue by sierracircle** [pods-framework/pods#6227]
## Description

On a website for a small private school  I use Pods to manage post-types and fields.   I use FormidableForms for creating sign-ups and registrations for various events and services.

FormidableForms has "Actions" that can be set up to happen after a form is submitted. One of the actions is to create a Post, and create custom fields in that post populated with data from the form.

Pods has (up until the upgrade to 2.8.1) been able to manage those custom fields and display the data when viewing the created posts.

After the upgrade from Pods 2.7  to 2.8, the post was still being created, but not all of the custom fields were being populated.  In fact, it looks as if once a certain field is not being populated, nothing else happens...the rest of the fields do not even show up.
This leads me to believe that some sort of conflict is happening with Pods and FormidableForms on creation of the post as if they are arguing about what should populate the field and then they both go away angry and nothing else happens

## Testing instructions

1. Go to https://sierrawaldorf.com/asc-signup/
2. Fill in the form and click on submit
3. Post is created with data from the form, but fields that should be populated with options checked in the checkboxes are not being populated.

## Expected behavior
I expect all of the fields for each post to be populated with data from the form, but it seems to fail at fields that are supposed to get populated with checkbox options

## Pods version

The problems happened after upgrading Pods to 2.8.1
Downgrading to 2.7.31 solves the problem and things work as expected.

## Other super helpful information

if you are interested in testing this further, I can provide a duplicate form for testing and give you access.

<details>
Wordpress and FormidableForms area updated to the latest version. Server (Contabo VPS) is running Ubuntu 20.04 with all updates.
 

</details>

**Comment by sc0ttkclark** [comment]
I'd like to see where things are going wrong here so that I can help resolve it for others who may not yet know it's happening for them. Perhaps it's related to something that could affect other areas of Pods as well.

Can you share a form and a Pods package?

**Comment by sierracircle** [comment]
I just updated all of the fields that were being saved from a checkbox from plain text to  Code (Syntax Highlighting), then updated Pods to 2.8.3  and everything seems functional.
I used the following admin css to alter the code-boxes to look like plain text boxes:
`//some custom css for the admin area
add_action('admin_head', 'my_custom_fonts');
function my_custom_fonts() {
  echo '<style>

.CodeMirror-linenumber,.CodeMirror-gutter-wrapper, .CodeMirror-gutters {  display: none; margin-left: -10000px; }
.CodeMirror-sizer { margin-left: 2px!important;}
.CodeMirror.cm-s-default.CodeMirror-wrap { max-height: 100px;}


      </style>';
}`
