### ISSUE TITLE
Got PHP Fatal error when run WP-CLI update plugin

### ISSUE THREAD

**Issue by datgausaigon** [pods-framework/pods#6242]
Hi, I use
```
PHP 8.0.12
WordPress 5.8.1
Pods 2.8.1

```
When I run update plugin by WP-CLI I got a message:

```
PHP Fatal error:  Uncaught TypeError: ftp_nlist(): Argument #1 ($ftp) must be of type resource, null given in ..... /wp-admin/includes/class-wp-filesystem-ftpext.php:420

/plugins/pods/includes/general.php(3508): WP_Filesystem_FTPext->exists('....
```

Dees your plugin check with PHP 8.0.12 and WordPress 5.8.1?
Plugin still work but the log will hold this error. Thanks

Please check. Thanks

**Comment by Snail110** [comment]
At the end, this could be solved by adding the following code in wp-config.php file:
if ( ! defined( 'FS_METHOD' ) ) define( 'FS_METHOD', 'direct' );
