### ISSUE TITLE
Checkbox dependencies not showing after creating new CPT

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6255]
## Description

https://wordpress.org/support/topic/admin-ui-icons/

When creating a new pod (post type) the menu fields aren't shown by default even though the `Show Admin Menu in Dashboard` option is checked by default.

Once unchecked and rechecked the fields will show.

Pods version 2.8.3

**Comment by jomarieminney** [comment]
In case this helps, a screen capture vid of it happening: https://www.screencast.com/t/uE8zRhsHlpV3

**Comment by sc0ttkclark** [comment]
Fixed via #6291
