### ISSUE TITLE
Date format 21.10.2021 not working

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6259]
## Description

https://wordpress.org/support/topic/date-field-in-2-8/

The date field format 21.10.2021 (d-m-Y) isn't working. It's not showing the date anymore.
Might be an issue with US and EU formats (day first or month first). My guess is that the script thinks the month goes first, but there are no month numbers higher than 12..

Pods version 2.8.3

**Comment by JoryHogeveen** [comment]
Also see my comment here: https://github.com/pods-framework/pods/issues/6213#issuecomment-956322884

**Comment by sc0ttkclark** [comment]
Fixed via 3ae78798d2e8ac3e2d57b9d7d695e94a0af6008f
