### ISSUE TITLE
Possible bug with date format in Pods version 2.8

### ISSUE THREAD

**Issue by RobertSistere** [pods-framework/pods#6261]
Good morning!

This is my first contribution on GitHub, so I hope to do it properly.

I've been a Pods user for several years and for me it's an essential tool.

After the last update I noticed that when saving a Custom post an error appears in a _date_ field: incorrect format. The value entered in the date field is shown as follows (image-1).

The field is configured as _date type_ (image-2) with the default Wordpress format (image-3). The Wordpress default format is custom format (image-4). This is the configuration it has had from the beginning and until version 2.7.30 it has worked correctly.

But when updating Pods to version 2.8.3 the date field is shown as in image 1 and when saving the following error message appears: "Data has not been entered in a recognised format: "2 DDzz October DDzz 2021" " (image-error).

I tried reinstalling Pods version 2.7.30 and it worked correctly again.

If I change the Wordpress date format to "d/m/y" the date field is displayed in this format and saved correctly, but this affects other parts of the website where dates are also displayed and I don't care to change it.

Is it possible that the error is related to the change of the input interface and the changes introduced in version 2.8?

If this is a bug, I would like you to be aware of it and fix it in future updates.

Thank you very much for your attention.

Best regards!

![image-1](https://user-images.githubusercontent.com/93381246/139458300-373aa2b2-c275-421f-ac55-92c575cd5706.png)
![image-2](https://user-images.githubusercontent.com/93381246/139458301-960ee96c-fc05-4ad4-921d-7ab5b77ba205.png)
![image-3](https://user-images.githubusercontent.com/93381246/139458303-bca33191-d42c-4bb0-966e-ef70ba21a645.png)
![image-4](https://user-images.githubusercontent.com/93381246/139458306-3e7963e0-86d8-40d7-9482-feefdb8832e2.png)
![image-error](https://user-images.githubusercontent.com/93381246/139458307-8cf0792f-06ff-4b2d-abb5-d94eee8504fe.png)

**Comment by JoryHogeveen** [comment]
@zrothauser This format is most likely incompatible with the date picker.

**Comment by sc0ttkclark** [comment]
Fixed via 296ebf6dd369b66995282ca5e8d89154a69ab473 and subsequent regex tweak in cf4e37196ca2ce8364be5e29ba19c763e4a556de
