### ISSUE TITLE
Field added to Comments with Pods doesn't display to logged out users

### ISSUE THREAD

**Issue by Ruanna** [pods-framework/pods#6262]
Hi, I posted this in Slack support thread, but thought you might need it here, too. 

I extended WordPress Comments on a client site with Pods, adding one dropdown field, which worked great for the past year. The field displayed immediately without altering the comments.php file, both to users who were logged in, and to users who were not.

On 2021-10-28 I was advised by my client that the custom field (tell us where you live) was missing from the comment form. 
By that, she meant that a logged out user cannot see the field.  We need for logged out users to see the field, too.  A recent update seems to be the cause.

For the short term I unchecked the "required" box on that custom field.  

Thanks,
Ruanna

![pods-field-details](https://user-images.githubusercontent.com/3707489/139486692-dc7d31ba-3ab9-4af1-92ea-b0ca7ad88771.jpg)
![pods-field-relationship-options](https://user-images.githubusercontent.com/3707489/139486695-770933c3-24f8-489a-93ff-53a786fbbdff.jpg)
![pods-field-advanced](https://user-images.githubusercontent.com/3707489/139486700-ca5b173e-7c72-4906-9f56-032d797fe06a.jpg)
![this-pods-field-only-shows-to-logged-in-users](https://user-images.githubusercontent.com/3707489/139486703-1321d29d-e077-4f99-850e-199f7d20cb61.jpg)

theme: Astra 3.7.4
Pods version: 2.8.3

**Comment by sc0ttkclark** [comment]
Can you provide a package of your configuration (Pods Admin > Migrate Packages) using the Migrate Packages component (Pods Admin > Components)? That might help us to see if we can reproduce the issue.

Also helpful would be access to your Site Health information (Tools > Site Health > Info Tab > Copy site info to clipboard) would also help us determine if there are any potential conflicts from other plugins or your theme.

**Comment by sc0ttkclark** [comment]
Fixed via 577b1f2789740d0342e22cb1dfa2c635cb27b445

**Comment by sc0ttkclark** [comment]
Note: The only place in WordPress that Pods can hook on for both logged in / logged out is just above the submit button. Moved to standardize on that now.

**Comment by Ruanna** [comment]
Thank you - apologies for not providing the requested information in time, but sounds like you got it without me. Please advise if I'm wrong, otherwise - I really appreciate the work on it.
