### ISSUE TITLE
DateTime: ISO time (`c`) format not working

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6272]
## Description

The `c` format (ISO format) isn't working because React still adds a separate time part.
Example: `2021-11-11T15:05:27+01:00 3:05pm`. The last part (`3:05pm`) should not be added here.

Pods 2.8.3

**Comment by JoryHogeveen** [comment]
Also see my comment here: https://github.com/pods-framework/pods/issues/6213#issuecomment-956322884

**Comment by sc0ttkclark** [comment]
Fixed via 9ac961d4cce3ed0a0076afa11bdafc8ec5e0f79c
