### ISSUE TITLE
Placeholder option not working

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6275]
Pods 2.8.3 (2.8.4-dev actually)

The placeholder options aren't working anymore. There is a default `placeholder` option but React only looks for field specific options like `text_placeholder`.
This should just be `placeholder` for all field types, just like `label` and `help` as it was in 2.7.

**Comment by sc0ttkclark** [comment]
The placeholder option is per field and it's prefixed already in the field options.

However, the 2.7.x code remains unchanged in this area: https://github.com/pods-framework/pods/blob/main/classes/PodsForm.php#L581 which shows that it uses the placeholder property first, then uses the field type specific property. I can fix this in the React code to have the same fallback.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Okidoki, see PR!

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6289
