### ISSUE TITLE
Clear cache on update

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6279]
Noticed various bug reports of updates that went wrong because the cache needed to be cleared.
Probably best if we register an update script for Pods that always clears Pods cache on update (whether it's from the UI or manual with FTP).

**Comment by sc0ttkclark** [comment]
PodsView and all transients/caches are salted with the Pods version right now, but there's a possibility that dot characters could be making it in and could causing a problem -- 2.8.4 introduces this to help with that: 930e3444206761b0e32fd6a68dcf87465965f8be

**Comment by sc0ttkclark** [comment]
Closing this for now since salt changes and effectively the old cached data is no longer used/referenced
