### ISSUE TITLE
Unable to add related media to an advanced pod

### ISSUE THREAD

**Issue by eeboo** [pods-framework/pods#6280]
## Description

In creating a new entry of an advanced pod, it is not possible to add an image.

## Testing instructions

1. Go to wordpress dashboard
2. Click on add (advanced POD)
3. Fill info and add a media, submit
4. The media is not saved

## Expected behavior

The media should be saved and retrieved when editing the pod.

## Pods version

2.8.3

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/b9fdc5484ddcb71080141f7458ede0b1154fca1f
