### ISSUE TITLE
New document upload not saving on page save

### ISSUE THREAD

**Issue by nf0l** [pods-framework/pods#6281]
Hello, When i go to add a pdf file to a club (pod is called club) the pdf which i upload isnt added to the Pod. I click save and the document just doesnt get added into the club. I have rolled back to a very early version 2.6.11.2 and the file upload works. So something between then and the latest verison of Pods is causing the file to not save.

Upload a new document to a pod and the pod document is not being added when pod saved.

1- go to pod
2- upload a new pdf
3- click save on pod
4- document not displaying

## Possible workaround

rolled back to a previous version of Pods

## Pods version

Version 2.8.3

**Comment by jenpomphrey** [comment]
Also having this issue with image uploading.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/b9fdc5484ddcb71080141f7458ede0b1154fca1f
