### ISSUE TITLE
Problem saving Image Gallery  (custom field) images,  when adding or editing my Pod (Ornaments).

### ISSUE THREAD

**Issue by rmasulli** [pods-framework/pods#6282]
- `##` Description
Noticed that when adding or editing my pod (Ornament), I am able to load images from the Media Library, to the custom field (Image Gallery), but upon saving the record, the images are not saved. 

## Testing instructions

This problem began on Pods created or edited after October 25th.
4. See error message '....'

## Possible workaround
Was able to once again save images to the Image Gallery Custom Field, once I rolled back the plug in to Version 2.8.1

This may be related to the same issue raised in #6280 

## Pods version
Pods Version 2.8.3

## Other super helpful information
The Featured Image worked fine. The problem appears to be limited to the Image Gallery images. 

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by rmasulli** [comment]
Pods Version 2.8.3  Noticed that when adding or editing my pod (Ornament), I am able to load images from the Media Library, to the custom field (Image Gallery), but upon saving the record, the images are not saved. This problem began after October 25th. I had to rollback the plugin to 2.8.1 to be able to restore my ability to save Image Gallery images to the Ornament record.  The Featured Image continues to work properly. The problem appears to be limited to the Image Gallery custom field.  
![Ornament Edit Screen](https://user-images.githubusercontent.com/79271672/140081268-c8b3ad6c-40bb-4fcb-a008-8712289b18dc.JPG)
This is what my edit screen looks like now. (Back to version 2.8.1)

**Comment by rmasulli** [comment]
Not sure if it matters, but the Pod is a Meta Storage, Custom Post Type
![Pod Management](https://user-images.githubusercontent.com/79271672/140102784-371f0334-a399-4036-a02a-324bb92f0790.JPG)

**Comment by rmasulli** [comment]
I neglected to turn off auto update, so the plug in automatically updated back to 2.8.3. I noticed that an administrator added some new ornaments (pods) after the update and was able to add images and successfully save them.  I just tested and it seems to  be working properly, so I am going to close this issue.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/b9fdc5484ddcb71080141f7458ede0b1154fca1f
