### ISSUE TITLE
REST field settings do not work

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6287]
## Description

If the `all` option from a Pod isn't selected you should be able to enable write or read info by field.
This doesn't work anymore since: https://github.com/pods-framework/pods/commit/f7c3b6e42a9c66ae62c2a25d635e921f1dae8488

Maybe related: https://wordpress.org/support/topic/problem-with-custom-relationship-field-rest-api-2/

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6288
