### ISSUE TITLE
[storage table] fields disapear in edit page after importing an existing pod

### ISSUE THREAD

**Issue by eeboo** [pods-framework/pods#6302]
### Description

after importing an existing pod from a json file when editing existing table type pod, all fields disappear in edit page except the feshly created.
The data are still in database, maybe an issue related to properties group.

### Version

2.8.3

### Testing Instructions

1. export a pod and import a table based pod
2. edit the imported pod
3. the fields have disapear

### Screenshots / Screencast

<img width="936" alt="Capture d’écran 2021-11-15 à 13 15 44" src="https://user-images.githubusercontent.com/2884555/141780583-6b31969f-a89c-4bb3-adf4-28351e73668c.png">

### Possible Workaround

it is possible to recreate the missing field and an error message is displayed telling that the column already exist in database and the field should be displayed

**Comment by sc0ttkclark** [comment]
Can you provide a package of your configuration (Pods Admin > Migrate Packages) using the Migrate Packages component (Pods Admin > Components)? That might help us to see if we can reproduce the issue.

Also helpful would be access to your Site Health information (Tools > Site Health > Info Tab > Copy site info to clipboard) would also help us determine if there are any potential conflicts from other plugins or your theme.

**Comment by myrmithron** [comment]
Hello Scott,

We never add issue between pods and some other plugins, it arrives after the last update of pods version. 

The issue could come from the fact we export our pods package with a different Pods version than the one where we import it.

You can see site info here : [site_info.txt](https://github.com/pods-framework/pods/files/7574698/site_info.txt)

Here is the package we migrate : [right_migrate_package.txt](https://github.com/pods-framework/pods/files/7574699/right_migrate_package.txt)

Here, the package generated when we export from current prod : [bad_migrate_current_package.txt](https://github.com/pods-framework/pods/files/7574701/bad_migrate_current_package.txt)

Nevertheless, old data are still there, and we can see we have the right number of fields.
![image](https://user-images.githubusercontent.com/2914573/142730914-7f0d137f-9efe-4428-8a46-15e3ccf871aa.png)

Impossible to see data (outside the new group) in pods edition
![image](https://user-images.githubusercontent.com/2914573/142730933-6aece91e-d13d-48f6-b40d-97b41eb1dcef.png)

Impossible to update date outside the new group in an entry of pod
![image](https://user-images.githubusercontent.com/2914573/142730951-de6d097a-ff4e-443f-8869-edbfc0a3f57b.png)

But in properties to customize the admin interface, we can see for example that columns are still existing :
![image](https://user-images.githubusercontent.com/2914573/142730988-4698404d-8cdb-4a03-9255-7b7e71d2383a.png)

Thanks for your help, we are starting to be blocked to contribute our new data.

Regards

**Comment by myrmithron** [comment]
Hi Scott,

Do you need some other information ?

Regards

**Comment by myrmithron** [comment]
Hello Scott,

We still can't update our other properties. Do you have any solution ?
We should recreate the config (data are still in database).

Regards

**Comment by sc0ttkclark** [comment]
I haven't been able to reproduce this exact issue yet, it'll take some more effort to figure out what might be going on in this specific case.

**Comment by JoryHogeveen** [comment]
I also cannot reproduce this issue, when I try to import the package I see all fields showing in the Pods admin.
One thing that might be related to this is incorrect rights for ALTER TABLE?

**Comment by JoryHogeveen** [comment]
Wait, I just checked the screenshot.

The `Noms traduits` field is related to a content type I do not have: `Traduction`.
This might be the reason we cannot reproduce the issue?

**Comment by pdclark** [comment]
@myrmithron Are those files complete exports of all pods? Like Jory, I also got errors on the import — looks like it only import a pods with name "Pays", but missing a relationship to another pod or table.

**Comment by myrmithron** [comment]
Hello everybody,
Happy new years to the team :)

There is the package with the relation : [migrate_package_with_related.txt](https://github.com/pods-framework/pods/files/7797797/migrate_package_with_related.txt)
It's from the last version. So, we still miss our configuration. 

Data are still in database. It seems issue come from the group...

Thanks for your investigation and any advices we could get to result this situation

**Comment by myrmithron** [comment]
Hello to the team,

So, we are still blocked. We were investigating testing locally to recreate the field "name". When we add it, we have an error about the fact the field is yet existing. 

So, we see our fields in database, we can use them in the list context (filter, column name...) but we don't see them when we are in detail of an object and we can't see them in the field list ("fields" in "Edit Pod").

We don't know how to deal with that.

**Comment by pdclark** [comment]
Not sure — the file imported alright, then I tried adding a field titled `name` to the `Pays` Pod, and it let me do that without error.

Any ideas on dealing with a stuck field with an advanced storage table @sc0ttkclark ?

**Comment by sc0ttkclark** [comment]
Try adding `&pods_debug_find_orphan_fields=1` to the URL when you are editing a Pod. This will force an orphan field check process which normally happens on the first upgrade of that pod from pre 2.8.

Pods 2.8.9 will force orphan checks after package import going forward.

**Comment by sc0ttkclark** [comment]
Pods 2.8.9 now cross-references the total field count from the Edit Pods page with the total fields found in groups on the pod -- then triggers the migration as needed.
