### ISSUE TITLE
Conflict with Rank Math Taxonomy and Elementor

### ISSUE THREAD

**Issue by coadr93** [pods-framework/pods#6306]
Hello awesome team from PODS.

So I've updated from 2.7.31 to 2.8.4.1 and I have an issue with Rank Math and Elementor.

I'll try to explain to the best of my ability. I did some testing and I've figured some things out.

Rank Math Pro creates a post type called Rank Math Locations with the Taxonomy Rank Math Location Categories.

With Pods 2.7.31 I'm able to extend the taxonomy Rank Math Location Categories and add custom fields to it.

I'm then also able to add an Elementor Archive template and select as a condition the taxonomy Rank Math Location Categories so that the template shows only on the Rank Math Location Categories archive pages.

However, after updating to 2.8.4.1, there seems to be a conflict.

I think it is between Pods and Rank Math Pro.

When updateing to 2.8.4.1 and extending the Rank Math Locations post type or Rank Math Location Categories taxonomy, the taxonomy seems to no longer be linked to the post type, therefore it does not show inside the WordPress Dashboard under RM Locations Locations > RM Location Categories.

Also, the taxonomy disappears from Elementor Pro's Archive template conditions section so I can no longer add a template to that particular taxonomy's archive pages.

When first extending the Post Type or the Taxonomy, there is an option to link it under Connections.

However, after saving the first time, if I close that tab and then try to Edit the extended taxonomy, most tabs disappear, except for the Fields and Rest API tags. So the Labels, Admin UI, Connections and Advanced tabs are gone.

This was the same on 2.7.31, meaning the extra tabs were not visible, but extending the taxonomy worked just fine and no issues with Rank Math or Elementor.

Another note would be that adding the taxonomy in the Post Type doesn't link the Taxonomy back to the Post Type. So fi I edit Post Type > Connections and add the Taxonomy, normally when I edit Taxonomy > Connections it should be inter-linked, but it's not.

All other plugins (Rank Math, Rank Math Pro, Elementor and Elementor Pro) are on latest versions and work fine with Pods 2.7.31 but not with Pods 2.8.41.

Unfortunately, the site is live and too big to duplicate, so I've recreated this on a test site.

I can provide access for further testing.

**Comment by sc0ttkclark** [comment]
This wasn't React but an issue with some of the extending logic we had. Pods 2.8.5 should resolve this, can you confirm?

**Comment by coadr93** [comment]
Wohoo! Seems to be working fine right now on my testing site.

Notes:

With 2.8.5, when extending the RM Locations post type or taxonomy the first time, the extra tabs Labels, Admin UI, Connections and Advanced don't show up anymore, which makes sense since the post types and taxonomies were not created by Pods in the first place.

Thanks a lot!

I will update on the live site as well and confirm once again if everything works fine there as well.
