### ISSUE TITLE
Pods 2.8.5 removed "category" from Product post type

### ISSUE THREAD

**Issue by apooley** [pods-framework/pods#6316]
### Description

Upon updating Pods to 2.8.5, products no longer had a category. All product category links were broken and went to hxxps://sitename.tld/product-cat/product-slug instead of hxxps://sitename.tld/actual/product/categories/slug 

### Version

2.8.5

### Testing Instructions

1. With WooCommerce / products set up install Pods 2.8.5
2. Go to WP Admin -> Products - Category is no longer present
3. Click on any previously-working product category link, will no longer function
4. Click on any previously-working product link (with category in url) - will 404.

**Comment by sc0ttkclark** [comment]
Related to the custom vs extended issue we're tracking.

**Comment by vitmarks** [comment]
I upgraded from 2.7 to 2.8.5 and had the same result. but after clear pods cache it fixed it

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Fixed in 2.8.6?

**Comment by sc0ttkclark** [comment]
This should be fixed in 2.8.6 due to the revised handling of registered vs extended post types/taxonomies
