### ISSUE TITLE
When adding custom groups of fields with pods_group_add(), don't show those fields in other groups (if already in a real group)

### ISSUE THREAD

**Issue by andrepetrini** [pods-framework/pods#6317]
### Description

Hi,
I already have a lot of PODs, and I used to group them with code:
`function my_metaboxes ( $type, $name ) { 
    pods_group_add( 'campaign', 'Campanha', 'images,video1' ); 
    pods_group_add( 'campaign', 'Mais Vídeos', 'video2,video3,video4,video5,video6' ); 
    pods_group_add( 'campaign', 'Créditos', 'agency,brand,sector,creatives' ); 
    pods_group_add( 'campaign', 'Produção', 'production_company,film_director,photographer,illustrator' ); 
    pods_group_add( 'campaign', 'Prêmios', 'award_tracking' ); 
    pods_group_add( 'campaign', 'Outros', 'overview,collections,public_awareness,user_playlist' );
    pods_group_add( 'campaign', 'Antigo (não usar)', 'campaign_video,download_link' ); 

} 
add_action( 'pods_meta_groups', 'my_metaboxes', 10, 2 );`

But when I updated to the 2.8 version, this code broke the admin view because it introduced the new groups. I deleted the code and the admin is back to normal. 
Problem is that I can't manage the groups from my existing pods, since I can't move an existing field to new groups. So, in order to have the groups as I had before, I would need to create all the fields once again. We should have a way to create a new group and move an existing field there. 
If there are issues with dragging from a group to another, maybe it could be with a dropdown inside the Edit Field?
Thank you.
Best

### Version

2.8.5

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
Another user reported the same issue: https://wordpress.org/support/topic/pods_group_add-is-broken-now/

**Comment by sc0ttkclark** [comment]
We'll address moving fields to a different group as part of #6183

I'll look into the issue with using `pods_group_add()` and having those fields not show through other groups. For now, one workaround solution that seems to work for another person is to edit those fields in Pods to hide them from the UI. Then keep your `pods_group_add()` code. It should automatically handle show/hide so that your custom group will show the field but the normal group will hide it.

Other `pods_group_add()` issues known have been addressed in Pods 2.8.6

**Comment by khill07** [comment]
I don't know if this introduced a new bug, but right now in 2.8.7, any field added through pods_group_add() is being rendered as a text field despite the field type being set to something total different.

**Comment by andrepetrini** [comment]
Hey @khill07 , I had the same problem. Removing the pods_group_add() fixed the issue for now, but obviously removed the groups too. Waiting for the new update here to have groups organized again.

**Comment by khill07** [comment]
Why in the world does this just keep getting pushed.  I haven't been able to upgrade for 5 months now.

**Comment by BrookeDot** [comment]
Can this be closed as done in https://github.com/pods-framework/pods/pull/6456 ?

**Comment by sc0ttkclark** [comment]
I'm wondering what the use cases are for adding fields to groups using pods_group_add that couldn't be covered by Pods configs now -- https://docs.pods.io/code/registering-configurations/

I don't know if the group handling is resolved here by manually grouping with this function for a DB-based config, but the file-based configs do work well.

**Comment by sc0ttkclark** [comment]
I have a fix that can address this, it helps to avoid duplicate fields in general when using custom non DB-based configs.
