### ISSUE TITLE
When adding a Relationship field, Related Type should be a mandatory field

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6327]
### Description

I just created a relationship field. I forgot to add what the field related to (another CPT, in this case). I was still able to save the field and the pod.

Then, when I tried to add content for this Pod, I got this error:

Database Error; SQL: SELECT DISTINCT `t`.`id`, `t`.`name` FROM `-_Select_One_-` AS `t` ORDER BY `t`.`name`, `t`.`id` LIMIT 0, 30; Response: Table 'wp_ldp.-_Select_One_-' doesn't exist

I'm jumping to solution here, but it seems that making the "Related Type" field mandatory would be preferable to catching the error on the content creation screen.

### Version

2.8.5

**Comment by sc0ttkclark** [comment]
Fixed via 664777193e5a7e4015c4f231d697a2f7d00f011d
