### ISSUE TITLE
Fatal error: Uncaught Error: Maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6334]
### Description

Looking into this now, since the latest commits in 2.8.6 I get a function loop on registering Pods.

### Version

2.8.6

<html>
<body>

9 | 14.4119 | 52444264 | PodsInit->setup_content_types( ) | ...\class-wp-hook.php:303
-- | -- | -- | -- | --
10 | 14.4795 | 52590464 | apply_filters( ) | ...\PodsInit.php:1799
11 | 14.4795 | 52590872 | WP_Hook->apply_filters( ) | ...\plugin.php:189
12 | 14.4795 | 52592376 | Pods_Component_I18n->translate_register_wp_object( ) | ...\class-wp-hook.php:305
13 | 14.4795 | 52592376 | PodsAPI->load_pod( ) | ...\I18n.php:474
14 | 14.4795 | 52592752 | PodsAPI->_load_object( ) | ...\PodsAPI.php:7832
15 | 14.4795 | 52593128 | PodsAPI->_load_objects( ) | ...\PodsAPI.php:10702
16 | 14.4795 | 52593128 | Pods\Whatsit\Storage\Post_Type->find( ) | ...\PodsAPI.php:10804
17 | 14.4795 | 52595024 | PodsI18n->get_current_language( ) | ...\Post_Type.php:310
18 | 14.4796 | 52595024 | apply_filters( ) | ...\PodsI18n.php:245
19 | 14.4796 | 52595432 | WP_Hook->apply_filters( ) | ...\plugin.php:189
20 | 14.4796 | 52596184 | Pods\Integrations\Polylang->pods_get_current_language( ) | ...\class-wp-hook.php:305
21 | 14.4796 | 52597256 | get_user_meta( ) | ...\Polylang.php:139
22 | 14.4796 | 52597256 | get_metadata( ) | ...\user.php:1143
23 | 14.4796 | 52597256 | get_metadata_raw( ) | ...\meta.php:572
24 | 14.4796 | 52597304 | apply_filters( ) | ...\meta.php:633
25 | 14.4796 | 52597712 | WP_Hook->apply_filters( ) | ...\plugin.php:189
26 | 14.4796 | 52598464 | PodsMeta->get_user_meta( ) | ...\class-wp-hook.php:305
27 | 14.4796 | 52598872 | PodsMeta->get_meta( ) | ...\PodsMeta.php:2736
28 | 14.4797 | 52598872 | Pods\Whatsit\Pod->get_field( ) | ...\PodsMeta.php:3484
29 | 14.4797 | 52599248 | Pods\Whatsit\Pod->fetch_field( ) | ...\Whatsit.php:956
30 | 14.4797 | 52599624 | Pods\Whatsit\Pod->get_fields( ) | ...\Whatsit.php:893
31 | 14.4800 | 52600416 | PodsAPI->load_fields( ) | ...\Whatsit.php:1041
32 | 14.4800 | 52601112 | PodsAPI->_load_objects( ) | ...\PodsAPI.php:8216
33 | 14.4800 | 52601112 | Pods\Whatsit\Storage\Post_Type->find( ) | ...\PodsAPI.php:10804

</body>
</html>

**Comment by JoryHogeveen** [comment]
@sc0ttkclark See PR. This fixes the issue but I've added the stacktrace to this topic to be sure. Maybe you see something here that I dont!

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6335
