### ISSUE TITLE
pods_message has been deprecated since Pods version 2.3

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6340]
### Description

<html>
<body>

Deprecated: pods_message has been <strong>deprecated</strong> since Pods version 2.3 with no alternative available. in D:\WEB\SITES\- Local\pods\app\public\wp-content\plugins\pods-dev\includes\general.php on line 613
--

1 | 0.0004 | 370848 | {main}( ) | ...\admin.php:0
2 | 0.6768 | 10699040 | do_action( ) | ...\admin.php:259
3 | 0.6768 | 10699416 | WP_Hook->do_action( ) | ...\plugin.php:470
4 | 0.6768 | 10699416 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:327
5 | 0.6768 | 10700544 | PodsAdmin->admin_setup( ) | ...\class-wp-hook.php:303
6 | 0.6851 | 10757944 | pods_ui_message( ) | ...\PodsAdmin.php:860
7 | 0.6851 | 10757944 | pods_deprecated( ) | ...\deprecated.php:433
8 | 0.6851 | 10758264 | trigger_error ( ) | ...\general.php:613

</body>
</html>

### Version

2.8.6

### Testing Instructions

Just activate on a fresh installation and go to the add Pod wizard.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/e63ce61bc8b09588ac88dfbd044d0284574144c1
