### ISSUE TITLE
Permalink issue

### ISSUE THREAD

**Issue by dweuste** [pods-framework/pods#6342]
### Description

Same issue as this - https://github.com/pods-framework/pods/issues/6308 now showing in 2.8.6

### Version

2.8.6

### Testing Instructions

Issue resolved with 2.8.5 rollback.

**Comment by sc0ttkclark** [comment]
Please retest on Pods 2.8.7 that just went out

**Comment by dweuste** [comment]
> Please retest on Pods 2.8.7 that just went out

@sc0ttkclark - tested on first site I saw the issue on yesterday, issue still happened with 2.8.7. Reverting back to 2.8.5 fixed the issue.

**Comment by JoryHogeveen** [comment]
Hi @dweuste 
Please test with the latest 2.8.8: https://github.com/pods-framework/pods/archive/refs/heads/release/2.8.8.zip
We just included some fixes for extended object permalinks

**Comment by dweuste** [comment]
Hi @JoryHogeveen I did do a test with a 2.8.8 that @sc0ttkclark sent yesterday and it fixed the issue I was seeing.
