### ISSUE TITLE
Extended Pod label incorrect

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6350]
### Description

Not a pressing bug but the Pod label of an extended object should be the same as the label of that object.

Example from LearnDash:

CPT name = sfwd-courses
CPT label = Courses
Pods name = sfwd-courses (correct!)
Pods label = Sfwd-courses (??)  >> Should be Courses

Code location:
https://github.com/pods-framework/pods/blob/main/classes/PodsAPI.php#L1722

### Version

2.8

**Comment by sc0ttkclark** [comment]
Fixed via 10d472b239a70e6cdb1eca6fe510a9e69957bee1
