### ISSUE TITLE
non-alphanumeric characters are replaced when editing advanced options

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#6354]
### Description

Any non-alphanumeric character for example `/` or `%` gets replaced by `_` in the fields located on the Advanced Options tab.

### Version

2.8.7

### Testing Instructions

1. Go to one of the edit pod screens in the admin
2. Select the Advanced Options tab
3. type `car/%type%` in Custom Rewrite Slug

### Screenshots / Screencast

All of the `_` characters you see in this screencast are any time I entered in a non-alphanumeric character

https://user-images.githubusercontent.com/4442172/144766972-71f3969a-f9cf-4100-9e34-2efc665b58ec.mov

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/f1b3f083d7343d6a2b0d103c38e531030ad1dd0c
