### ISSUE TITLE
Edit Pod Page does not save the selected page template

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#6355]
### Description

I attempted to select a page template for my Pods Page and it doesn't appear save.

### Version

2.8.5 and 2.8.7 (2 different environments)

### Testing Instructions

1. Go to Edit or Add new Pods Page
2. Fill in the required fields
3. Selected a page template
4. Hit Publish/Update

### Screenshots / Screencast

https://user-images.githubusercontent.com/4442172/144770019-128b53e8-7466-4873-b98e-8e44063c14fc.mov

**Comment by sc0ttkclark** [comment]
Value saves but it's not loading up on the form. The associated pod works which is the same kind of field so there's something else going on here.

**Comment by sc0ttkclark** [comment]
Fixed via 5d90f3de172c18cf3d018602534358c6eefe0aad
