### ISSUE TITLE
Decimals on number field mixed up

### ISSUE THREAD

**Issue by ionlantern** [pods-framework/pods#6356]
Hi, I'm having trouble with number/currency field.
The field is setup with 2 decimals with number format 1.234,00 
After saving/updating the post the value (ex 55,33) changes to 5.533. Saving again it turns to 553.300.
Checked on three different sites and on a fresh WP install.

Thanks for your help in advance!

![01 manual input](https://user-images.githubusercontent.com/6387748/145003429-39364323-ed84-49d3-8f18-9d1b28f89785.png)
![02 after saving post](https://user-images.githubusercontent.com/6387748/145003431-56e82438-fb12-4bf0-a167-2c60bd88dfc5.png)
![03 after saving post again with no change](https://user-images.githubusercontent.com/6387748/145003432-433f28ba-f301-44eb-b47d-20452bc63f01.png)
![currency-field-setup](https://user-images.githubusercontent.com/6387748/145003435-bb195a34-a726-40f9-a08a-446263471c2e.png)
l.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Reproduce using the comma for decimals format.

The current REACT component seems only compatible with the dots for decimals format.

Same as #6333

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6269
