### ISSUE TITLE
Displaying list of checkboxes

### ISSUE THREAD

**Issue by CosmikCarrot** [pods-framework/pods#6367]
### Description

I've no idea whether I've set the Pod up correctly, but I've managed to get 4 fields created, and 3 are appearing fine. This is the 4th field - https://www.screencast.com/t/zEF2L3IN78

What Pods block do I need to use to display a list of items please?

This is the current error appearing on the page - https://www.screencast.com/t/Sb13H3YQuKA

In Slack, https://podswp.slack.com/archives/C02SVLHQF/p1639070661369900
 it was mentioned that this is to do with the attributes?

I'm just trying to create a checkbox, to add certain labels for each post in a set location on the page template.

### Version

2.8.8.1

### Screenshots / Screencast

https://www.screencast.com/t/Sb13H3YQuKA

**Comment by sc0ttkclark** [comment]
Fixed via Pods 2.8.9 in https://github.com/pods-framework/pods/commit/8bdb6267361eeff1c496dcd7851861626787eff5
