### ISSUE TITLE
Product Category Page 404 when "when use Pods with Rank Math and enable Remove Category Base for Product"

### ISSUE THREAD

**Issue by datverse** [pods-framework/pods#6369]
### Description

Hi,
When when use Pods with Rank Math and enable Remove Category Base for Product. I go to product category page and got 404 error.
Thanks

### Version

2.8.8.1

**Comment by JoryHogeveen** [comment]
Hi @datverse 

Sorry we did not reply sooner. Can you provide more info on the issue.
Since you did not provide any information, we cannot really try to reproduce.

This does sounds like a plugin conflict, please see: https://docs.pods.io/faqs/plugin-theme-conflicts/

**Comment by datverse** [comment]
Hi this issue fixed in new version 2.9.3

**Comment by datverse** [comment]
Hi,
I have found the origin of the error.
The error is in Rank Math, when deactivating/reactivating Rank Math does not push the rewrite rule. 
We need run wp-cli | wp rewrite flush or PHP like that.
You can close this issue.
Thanks ❤️
