### ISSUE TITLE
Relationship field depth

### ISSUE THREAD

**Issue by marija06** [pods-framework/pods#6373]
### Description

Relationship field returns only term_id and ID, all the other fields are missing.

I tried changing field depth but nothing happens.

Seems that this affects only WP default types like User extended

### Version

2.8.8.1

**Comment by marija06** [comment]
This issue appears with all 2.8 versions.

I rolled back plugin to version 2.7.31 and it works again

**Comment by sc0ttkclark** [comment]
Fixed via 558f4da1ecf680b8200f4b8b9e3627b29bc9313f
