### ISSUE TITLE
Role conditionals for field groups do not work

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6377]
### Description

Field groups also have role access conditionals. However, these do not work.
If you have fields within these groups then the group is still shown.

### Version

2.8.8.1

### Testing Instructions

1. Create a CPT Pod
2. Add a second group and restrict to admin role only
3. Add a field to this group, any field is fine
4. Switch to an Editor role
5. The group is still visible with the field you've added.

**Comment by sc0ttkclark** [comment]
Fixed via b222928604db2dccde2e5e9fb53348130545780d
