### ISSUE TITLE
Incompatibility with Yoast Duplicate Post and Essential Grid

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6379]
### Description

This has been reported several times on various locations.

- https://wordpress.org/support/topic/last-update-cause-timeout-on-wp-admin-post-new-php-and-wp-admin-post-php/
- https://wordpress.org/support/topic/pods-no-longer-compatible-with-divi/

Probably related:
- https://wordpress.org/support/topic/pods-crashing-my-site/
- https://github.com/pods-framework/pods/issues/6363

### Version

2.8.8.1

### Testing Instructions

I haven't found a way to reproduce this yet.

**Comment by sc0ttkclark** [comment]
Fixes for this have been included in Pods 2.8.9

Other incompatibility with SEOPress has been addressed with their developer as well.
