### ISSUE TITLE
Field groups should suspend requirement rules when they're closed

### ISSUE THREAD

**Issue by alex-icstech** [pods-framework/pods#6380]
### Problem to Solve

The new field-groups in Pods 2.8 are great. I use them in cases where I have a complex pod. For instance, I have a photo gallery, and I want a pod that can function either as a "caption" for a photo or as a "translucent-layer" for a photo. 

It's handy to have a pod "Photo Addon" and have field group "Caption" and a field-group "Translucent Layer". That way the api endpoint only has to request a single extra pod for a given Photo. So the cardinality looks like:

Gallery -> hasMany -> Photos -> hasOne -> PhotoAddon

Problem is that the field-groups don't play well with required fields. Each field-group might have required fields. But obviously if I'm filling one field-group out in this example, I won't touch the other field-group. They're purely orthogonal. But when I go to save a new Photo Addon record, it complains that it's missing required fields from the other field-group. 

This is bad because it totally obviates the purpose of having different field-groups in one pod in the first place. The purpose is to give a pod a way to store orthogonal data. But if there's no way to make the validation more granular, then the only thing to do is make all the fields in every field-group optional.

### Proposed Solution

There should be an option in the Advanced Options of a field-group which affects how required fields behave. It could say: "Require if Field Group is active". Checking this box will change the behavior of the Required fields within a field group so that they will allow null values during create/update validation provided that the field group is unopened on the Pods create/update screen.

### Workaround

There is no good workaround. Pods provides an "pods_api_pre_save_pod_item_{xyz}" filter, and you can use this to perform custom validation to some degree, but it can't override the behavior of required fields.

What I'm doing now is just making every field in every field-group in my pod optional. This is, of course, not ideal.

**Comment by JoryHogeveen** [comment]
Hi @alex-icstech 

Field groups are nothing more than field containers so you can position then separately within the WP admin.
As for required fields. ALL required fields are validated each time you try to save. Field groups are unrelated to the validation process.

I think what you are looking for is conditional logic.
So: when one field has a value (or a specific value), another field is shown. And only then will the requirement of such a field be validated.
This feature is planned for 3.0.
