### ISSUE TITLE
Block attributes are not always strings

### ISSUE THREAD

**Issue by websevendev** [pods-framework/pods#6386]
The block render functions in this plugin assume that all block attributes are strings:

[`$attributes = array_map( 'trim', $attributes );`](https://github.com/pods-framework/pods/blob/2b6e56a7e175bcb61e0b21664fc1064edf0ab5c2/src/Pods/Blocks/Types/Item_List.php#L372)

causing a warning:

`Warning: trim() expects parameter 1 to be string`

Block attributes can be extended by [third party plugins](https://wordpress.org/support/topic/problem-with-another-plugin-4/) so that should ideally be accounted for.

**Comment by JoryHogeveen** [comment]
Hi @websevendev 
Thanks for your report, could you test and confirm patch #6388 ?

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6388

**Comment by sc0ttkclark** [comment]
Related: #6367
