### ISSUE TITLE
update_post_meta called recursively because of an hook

### ISSUE THREAD

**Issue by mircobabini** [pods-framework/pods#6391]
### Description

I'm having an issue when trying to change a value just before it's saved into a meta field.

The issue is that I'm applying an encrypt function to the value just before it's saved, but I'm facing a double-encryption.
This is happening because of how the update_post_meta is hooked into Pods.

1) I'm hooked into `sanitize_{$meta_type}_meta_$encrypted_field_name`
2) When using the GUI and saving the post, it works great
3) When using the raw code and colling update_post_meta, the hook is fired twice

This is the log:
https://gist.github.com/mircobabini/9e9bf39aceeb7bfb09968f2c5f7da66e

First time, the password is: It)weSh}334Dov)123456789 and it's encrypted this way:
https://gist.github.com/mircobabini/9e9bf39aceeb7bfb09968f2c5f7da66e#file-pods-bug-log-L1-L13

Just after that, Pods is hooked to update_post_meta => PodsMeta->update_post_meta => (fast-forward) => PodsAPI->save_post_meta => which calls update_post_meta once again.

I think this is wrong or, at least, this is causing issues in some cases. This is the complete log:
https://gist.github.com/mircobabini/9e9bf39aceeb7bfb09968f2c5f7da66e#file-pods-bug-log-L15-L38

If you want to hook to "update_post_meta" to save an entire post, you should not re-use the "update_post_meta" API; to avoid loops, it would be better to use a raw post meta update implementation.

### Version

2.8.8.1

### Testing Instructions

1. Install a fresh wordpress with pods
2. With composer require defuse/php-encryption
3. From a script, hook into `sanitize_post_meta_password` with a function which calls the encryption
4. Try to save a password using update_post_meta( ..., 'password', 'unsecure-value' );

You will see the same log I've posted, the sanitize method above is called twice.

**Comment by sc0ttkclark** [comment]
@mircobabini do you have the code you're using for this specifically?

I'm interested to know why `update_post_meta()` is called in the sanitize hook instead of returning the sanitized/changed value in that filter.

I'll look into loop detection here.

**Comment by sc0ttkclark** [comment]
Recurssive loop prevented via 23fc236b

**Comment by mircobabini** [comment]
> Recursive loop prevented via [23fc236](https://github.com/pods-framework/pods/commit/23fc236bf6c8172bcba83594eda29d43de460c6e)

This was the code btw: https://gist.github.com/mircobabini/7e1ec87f5039999d413ca1f72c0b558c.
I'm doing it at a lower level now, usign `get|add|update_{$meta_type}_metadata filters`.
