### ISSUE TITLE
Apostrophe in pod name displayed as HTML entity

### ISSUE THREAD

**Issue by MarcSiepman** [pods-framework/pods#6394]
### Description

In Dutch, plurals often end with 's. If I create a Pod using an apostrophe, in the menu it says Lemma&#039;s in one instance. The main screen also says "No Lemma&#039;s found".

### Version

2.8.8.1

### Testing Instructions

Just create a new pod with an apostrophe.

### Screenshots / Screencast

![Schermafdruk van 2022-01-04 11-52-44](https://user-images.githubusercontent.com/23240684/148048667-f56bb4ea-5ffe-4a70-8b37-714ae9d8f2eb.png)

**Comment by JoryHogeveen** [comment]
Check the reason for this and found that we use `esc_html()` for the post singular and plural labels.
@sc0ttkclark Any reason we don't allow HTML here?

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6399
