### ISSUE TITLE
Error with comment Submit

### ISSUE THREAD

**Issue by dp1492** [pods-framework/pods#6413]
![image](https://user-images.githubusercontent.com/74495323/150878683-ddde14ca-cdeb-48e3-a8bb-049761420670.png)
I try to extend my comments data, but when press submit button, then take this error message.

**Comment by sc0ttkclark** [comment]
Fixed in Pods 2.8.9 which is going out tomorrow.

**Comment by dp1492** [comment]
@sc0ttkclark Thank you! I tried. it's working fine.
