### ISSUE TITLE
Kadence Blocks - Advanced Image - Dynamic Field

### ISSUE THREAD

**Issue by CosmikCarrot** [pods-framework/pods#6421]
Hi,

Example - image field 'gallery_image_one' does not appear in the dynamic field of the Advanced Image block in Kadence Pro.

See the field not appearing - https://www.screencast.com/t/oXlgUqcxgGra

Thanks.

**Comment by sc0ttkclark** [comment]
Did you try to use custom manual input to use the field? I'll hit you up on Slack to discuss further about the integration side of things.

**Comment by CosmikCarrot** [comment]
Replied in Slack to you @sc0ttkclark 
Thanks 👍🏽

**Comment by sc0ttkclark** [comment]
Have you tried the manual input there where you type the field name?

**Comment by CosmikCarrot** [comment]
Thanks @sc0ttkclark this is no longer an issue, and was working in Kadence.
