### ISSUE TITLE
2.8.9 compatibility with Ultimate Member

### ISSUE THREAD

**Issue by Doc55** [pods-framework/pods#6431]
### Description

Update 2.8.9 broke my site. It appears it is not compatible with Ultimate Member. When I new user signs up using the Ultimate Member Registration form, no data is saved in the database. Rolled back to 2.8.8.1 and everything is working fine. 

### Version

2.8.9

### Testing Instructions

1- Install Ultimate Member 
2- Create a Registration form with a few custom fields 
3- Add User extension in PODS
4- Add custom fields created in Ultimate Member to the PODS user extension 
5- In the frontend, register as a new user. 
6- Non of the custom field data is saved to the database. 

### Possible Workaround

I had to roll back to 2.8.8.1

**Comment by sc0ttkclark** [comment]
Most likely the same issue as to #6429

**Comment by sc0ttkclark** [comment]
Fixed via ec5a20e1c61cd3c1422fcf27d51682c8193bb0e5
