### ISSUE TITLE
WYSIWYG editor not preserving some line breaks (after image HTML)

### ISSUE THREAD

**Issue by MrAndySweet** [pods-framework/pods#6441]
Since upgrading to 2.8.10 (I think, certainly recently) I've noticed a problem with the WYSIWYG editor processing line breaks.

I saw on the Wordpress support forum for Pods that the user rinoxstudio was having a similar problem that was resolved in 2.8.10, however my issue seems to be specifically with line breaks after images (or after the associated HTML for the images). All other line breaks seem to be preserved.

If I go into the editor window and put the line breaks back, when I save the Pods content they are stripped out again and the text appears straight after the image code rather than two lines below.

![linebreaks](https://user-images.githubusercontent.com/4242729/153311598-922da10c-6875-4445-b98f-5e62e55e8183.jpg)

Viewing the webpage the text is shown straight after the image rather than with a clear line between, and the text has also been formatted slightly differently to the rest of the "normal" text.

![linebreaks2](https://user-images.githubusercontent.com/4242729/153312111-82cb4dcf-7d75-40da-b8a0-4c99562ef6c5.jpg)

This is a recent problem, I think since upgrading to 2.8.10 although I couldn't be 100% certain. It's certainly started occurring within the timeframe of the last couple of updates.

I've tried ticking the "Enable wpautop" button in the WYSIWYG options but that doesn't make any difference, the line breaks are still removed upon saving.

The issue doesn't happen with the editor on Wordpress posts and pages so it seems to be specific to the Pods editor.

**Comment by JoryHogeveen** [comment]
Hi @MrAndySweet 

My first guess is that you output the field content yourself using PHP.
Please wrap your field output with `wpautop();`
https://developer.wordpress.org/reference/functions/wpautop/

Cheers, Jory

**Comment by MrAndySweet** [comment]
Thanks, Jory. Yes, I do output it with PHP.

You mentioning wpautop led me to look at the functions.php for my theme and I had a line in there disabling the wpautop function. I don't remember why exactly but think it was a solution to some previous problem some time ago.

I've removed that line and wrapped my Pods field display code with wpautop and it now seems to be displaying as expected at the front end.

Original code:

```
if ( 0<strlen(trim($pods->field('image'))) AND 0<strlen(trim($pods->display('notes'))) ) {
echo '<div class="img-fullwidth-container"><img src="';
echo $pods->field('image');
echo '" style="width:100%;" /><div class="img-fullwidth-textbox"><h1 class="img-fullwidth-title text-shadow-light">';
echo $cleaned_name;
echo '</h1></div></div>';
include (ABSPATH . '/assets/widgets/sharer.php');
echo '<div class="container white"><div class="row grid"><div class="c8">';
echo '<a href="';
echo $pods->field('image');
echo '" rel="lightbox[';
echo $cleaned_name;
echo ']"><img src="';
echo $pods->field('image');
echo '" class="blogimage"></a><br />';
echo $pods->display('notes');
```

New code:

```
$notes = $pods->display('notes');
if ( 0<strlen(trim($pods->field('image'))) AND 0<strlen(trim($pods->display('notes'))) ) {
echo '<div class="img-fullwidth-container"><img src="';
echo $pods->field('image');
echo '" style="width:100%;" /><div class="img-fullwidth-textbox"><h1 class="img-fullwidth-title text-shadow-light">';
echo $cleaned_name;
echo '</h1></div></div>';
include (ABSPATH . '/assets/widgets/sharer.php');
echo '<div class="container white"><div class="row grid"><div class="c8">';
echo '<a href="';
echo $pods->field('image');
echo '" rel="lightbox[';
echo $cleaned_name;
echo ']"><img src="';
echo $pods->field('image');
echo '" class="blogimage"></a><br />';
echo wpautop($notes);
```

Something that confused me slightly when trying to find the solution is that the WYSIWYG editor window in the back end of Pods removes the line breaks after my image code. I had a look in the database itself and the line breaks are preserved as a I wrote them so it just seems to be the way that the WYSIWYG editor is displaying the consent in the back end. I don't know if this is a quirk of Pods or Wordpress.

With my code for an image on its own (no caption) the code ends in </center> and the WYSIWYG editor removes both line breaks. With my code for a captioned image, which ends in </div> it removes one line break.

![linebreaks](https://user-images.githubusercontent.com/4242729/153851061-d8265e1c-a5f1-4b74-8a83-31f465db5154.jpg)

For whatever reason my previous setup was displaying my content as expected but changed relatively recently (without me changing any code, and probably coinciding with one of the last two Pods updates).

**Comment by MrAndySweet** [comment]
I just did a bit more testing having updated the code with wpautop.

If I edit one of my Pods records (which is displaying correctly and has the line breaks preserved in the database when looking at phpMyAdmin) and save it, the line break sale stripped out after the image code as described above. Checking the database shows that the line breaks have also been removed from there for that newly-saved record.

This is obviously quite a problem as if I edit any of my records in the Pods back end I then have to go through phpMyAdmin to reinstate the line breaks which have been stripped out.

**Comment by MrAndySweet** [comment]
I'm not sure what the protocol is on reporting on an old issue but I'm still having this problem.

**Comment by JoryHogeveen** [comment]
This honestly sounds like a WordPress core issue with `wpautop` when using `<div>` and other elements.

**Comment by MrAndySweet** [comment]
Thanks for the reply, I'll look into it.
