### ISSUE TITLE
Edit page not loading – 404 error

### ISSUE THREAD

**Issue by cwgsu** [pods-framework/pods#6445]
I have two sites running same plugins /versions. One works, one doesn’t. The one that doesn’t work gives error:

GET https://godversusreligion.com/wp-content/plugins/pods/ui/js/dfv/pods-dfv.min.js?ver=1f0370ee2aec5d9d2b18b31f7d8e959b net::ERR_ABORTED 404

before eventually ending up with blank edit page.

I tried running with all other plugins disabled(including cache and minify) and get the same error message. Seems to be different from the recently posted edit page error.
Also, when trying to add records, the PODS fields are static text, with no ability to input.
Both sites are up to date on PODS v 2.8.10
! created a staging site and back leveled pods to 2.8.9 and it appears to work. Edit screen is there and data can be entered.
Haven’t done in production yet. Waiting for something from you to say this is OK and won’t mess up anything by going back.

**Comment by cwgsu** [comment]
Just got email from Dreamhost about this file having been "identified as attacker-added malware".  They disabled it.  Also was just disabled in the staging site I set up.  Is this a known issue - where can I send the file to have someone verify it?

thanks,
chris

**Comment by JoryHogeveen** [comment]
Hi @cwgsu 

This isn't a known issue and it's also failty. This is a Pods core file that is required for Pods fields to work correctly.

**Comment by cwgsu** [comment]
Hi – Yes, my hosting provider reached out to PODS as well and have whitelisted it.  They got a false positive and disabled it.

Thanks!
chris

**Comment by JoryHogeveen** [comment]
Hi @cwgsu Thanks for letting us know! Closing topic!

**Comment by cwgsu** [comment]
Hi- it’s 9:15 PM Pacific time – it just happened again.  PODS isn’t working.  Haven’t seen an email yet, but it’s exactly like it was a few days ago.  I was using it and then all of a sudden it’s got a 404 error on the same file.

chris

**Comment by JoryHogeveen** [comment]
Hi @cwgsu 
Please contact your site hosting again. There is nothing I can do for you unfortunately :(
Cheers, Jory
