### ISSUE TITLE
WPML: Clear language cache after switching language

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6448]
### Description

If a language is switched Pods still uses the existing language cache.
We need to refresh this each time the language is switched.

Slack thread: https://podswp.slack.com/archives/C02SVLHQF/p1644853915131059

### Version

2.8.0 - 2.8.10

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6449
