### ISSUE TITLE
Relationship Field – Single Select – Autocomplete OR List View (with reordering) – Deleting Entry – There was an error rendering the field

### ISSUE THREAD

**Issue by SuperCougar** [pods-framework/pods#6454]
### Description

https://wordpress.org/support/topic/relationship-deleting-entry-there-was-an-error-rendering-the-field/

### Version

2.8.10

### Testing Instructions

- **Field Type:** Relationship Field
- **Selection Type:** Single Select
- **Input Type:** Autocomplete OR List View (with reordering)

Clicking “x” to delete an entry from a field in a post type generates the following error message:
**There was an error rendering the field.**

### Screenshots / Screencast

https://clic-now.info/go-1644981337-RWS2E26WigDb272

### Possible Workaround

Multiple Select – Autocomplete – **Selection Limit: 1**

With "**Selection Limit: 1**" there is no error message when the field is cleared but if a value is entered you need to delete it to be able to add a new one.

**Comment by sc0ttkclark** [comment]
@zrothauser can you take a look at this one for Pods 2.8.19?

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6531
