### ISSUE TITLE
"Pod Not Found", "Field not found" error since upgrading to 2.8.10 (possibly some previous versions)

### ISSUE THREAD

**Issue by winnersmedia** [pods-framework/pods#6461]
I'm unable to update my pods since upgrading the plugin, i get a "pod not found" error.  I can't update fields either, i get "field not found"

**Comment by JoryHogeveen** [comment]
Hi @winnersmedia 

Please provide a full bug report, we cannot help you if we do not have all the information we ask for.

**Comment by winnersmedia** [comment]
thanks, where do i find the debugging information on the latest version of pods?
