### ISSUE TITLE
Thumbnails in relationship list fields do not scale down.

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6473]
### Description

Current situation:
![image](https://user-images.githubusercontent.com/826148/157220194-abd0e11f-588c-45b1-858d-b6eac2caecff.png)

Should be: 
![image](https://user-images.githubusercontent.com/826148/157220287-d9533b17-3079-4361-aac0-de1c9b15e1d7.png)

### Version

2.8.11

**Comment by sc0ttkclark** [comment]
Fixed via #6474
