### ISSUE TITLE
Value of Relationship field with Simple Custom Defined List can't be saved

### ISSUE THREAD

**Issue by coadr93** [pods-framework/pods#6476]
### Description

Hello awesome team @ Pods!

I've noticed a bug in the latest version of Pods.

The Relationship field with Simple Custom Defined List value can't be saved. Not sure if there's also an issue with other types of relationship fields, but the simple custom defined list it doesn't work.

Saving it won't have any effect, no matter the value. It will not change anymore. My old fields that I had previously stayed stuck on the old value, so it seems it can store it, but not change it.

Everything on latest versions of Pods WP and PHP

I've recreated it on the test site and sent the login details to Scott.

### Version

2.8.10

### Testing Instructions

1. Go to Pods Admin
2. Add new Custom Settings Page
3. Save and edit the newly created Pods
4. Add a a new Relationship Field with Related Type Simple (custom definied list) and add 2-3 Custom Defined Options one on each line
5. Save field, Save pod
6. In WP dashboard go to the pod settings page
7. Try to select the option in the newly created field and save it and it will not save the value, it will reset to default.

### Screenshots / Screencast

https://youtu.be/G8lUcUQiQZ4

### Possible Workaround

Use a yes/no field if only 2 options

**Comment by michaelstringer** [comment]
We are having the same issue. I reverted back to 2.8.3 and we can save the field values now.

**Comment by sc0ttkclark** [comment]
Fixed via b0538a2e409e833671add40167249e690620ff0a
