### ISSUE TITLE
Version 2.8.11 throws fatal error

### ISSUE THREAD

**Issue by DracoVenturus** [pods-framework/pods#6489]
Hello,
upon upgrading to v.2.8.11 the site crashes and I get the following error.
Reverting to 2.8.10 brings my site back to normal.

[08-Apr-2022 08:22:23 UTC] PHP Fatal error:  Uncaught TypeError: array_unshift(): Argument #1 ($array) must be of type array, string given in /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integration.php:59
Stack trace:
#0 /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integration.php(59): array_unshift('wpml_language_h...', 0)
#1 /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integrations/Service_Provider.php(83): Pods\Integration->hook()
#2 /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integrations/Service_Provider.php(58): Pods\Integrations\Service_Provider->plugins_loaded()
#3 /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integrations/Service_Provider.php(41): Pods\Integrations\Service_Provider->hooks()
#4 /home/xxxxxxx/public_html/wp-content/plugins/pods/tribe-common/vendor/lucatume/di52/src/tad/DI52/Container.php(484): Pods\Integrations\Service_Provider->register()
#5 /home/xxxxxxx/public_html/wp-content/plugins/pods/tribe-common/src/Tribe/Container.php(288): tad_DI52_Container->register('Pods\\Integratio...')
#6 /home/xxxxxxx/public_html/wp-content/plugins/pods/classes/PodsInit.php(2506): tribe_register_provider('Pods\\Integratio...')
#7 /home/xxxxxxx/public_html/wp-includes/class-wp-hook.php(307): PodsInit->run('')
#8 /home/xxxxxxx/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#9 /home/xxxxxxx/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#10 /home/xxxxxxx/public_html/wp-content/plugins/pods/tribe-common/src/Tribe/Main.php(107): do_action('tribe_common_lo...')
#11 /home/xxxxxxx/public_html/wp-content/plugins/pods/classes/PodsInit.php(264): Tribe__Main->plugins_loaded()
#12 /home/xxxxxxx/public_html/wp-includes/class-wp-hook.php(307): PodsInit->maybe_set_common_lib_info('')
#13 /homexxxxxxx/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#14 /home/xxxxxxx/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#15 /home/xxxxxxx/public_html/wp-settings.php(450): do_action('plugins_loaded')
#16 /home/xxxxxxx/public_html/wp-config.php(92): require_once('/home/xxxxxxx/...')
#17 /home/xxxxxxx/public_html/wp-load.php(50): require_once('/home/xxxxxxx/...')
#18 /home/xxxxxxx/public_html/wp-blog-header.php(13): require_once('/home/xxxxxxx/...')
#19 /home/xxxxxxx/public_html/index.php(17): require('/home/xxxxxxx/...')
#20 {main}
  thrown in /home/xxxxxxx/public_html/wp-content/plugins/pods/src/Pods/Integration.php on line 59

**Comment by MartinPL** [comment]
Exacly this hook ->wpml_language_has_switched <-

**Comment by DracoVenturus** [comment]
Solved after updating to 2.8.13
