### ISSUE TITLE
Unable to Attach Media In to post Using Rest API

### ISSUE THREAD

**Issue by tarangpatel61** [pods-framework/pods#6517]
### Description

Hi . 
I have created one Pod with following fields,
1) Store Name
2) invoice Date
3) Invoice File( Multiple )
So the issue is i am not able to save invoice file through api. 
can anyone have any idea about this?.

API url : site name /wp-json/wp/v2/invoice
Data passed in API:  

store_name:Test22
invoice_date:10-05-2022
invoice_file:{{File}}

### Version

2.8.17

**Comment by sc0ttkclark** [comment]
Have you enabled the REST API field to be write-enabled?

<img width="1084" alt="Screen Shot 2022-06-09 at 11 56 59 PM" src="https://user-images.githubusercontent.com/709662/172993264-5dc728ef-44ba-463b-8e8c-cec2151e58df.png">

**Comment by sc0ttkclark** [comment]
Closing this since we don't have any other information about the problem. If they are trying to send the file itself then that won't work here as that needs to happen through another Media API.
