### ISSUE TITLE
WYSIWYG field type using TinyMCE not displaying icons on buttons

### ISSUE THREAD

**Issue by papa-pup** [pods-framework/pods#6525]
### Description

Fields that are of WYSIWYG type using TinyMCE are not displaying icon on buttons

### Version

2.8.17

### Testing Instructions

1. Create a new POD with a WYSIWYG field
2. Use PODS shortcode to display as form

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/59635968/172426692-20598e2d-c90e-44ab-94cd-d7ec5e235341.png)

### Possible Workaround

Workaround provided by @pdclark 

<?php
/**
 * Plugin Name: Enqueue Dashicons
 * Description: Add Dashicons to the frontend theme even when admin bar is not displayed.
 */
add_action(
  'wp_enqueue_scripts',
  function(){
    wp_enqueue_style( 'dashicons' );
  }
);

**Comment by papa-pup** [comment]
Problem disappeared after WP update to 6.0.1 and Astra Theme updated to 3.9.1

**Comment by papa-pup** [comment]
Further checks, this issue still appearing on WP default theme - twenty twenty; hence reopen for consideration for fix

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/a75cf27fe97c9f3d67b1b978da57e59a8c2c6443 which will go out in Pods 2.8.24 or Pods 2.9 (whichever is first)

**Comment by sc0ttkclark** [comment]
Sorry, I fixed [this issue](https://github.com/pods-framework/pods/issues/6525) and not the one you described. Reopened to further look into this

**Comment by sc0ttkclark** [comment]
Fixed via 82768988fa2114d29f028049e9af6929668ef01c
