### ISSUE TITLE
User Relationships : Limit by roles > Field error

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6532]
### Description

When creating a relationship field for users the "limit by roles" field generates an error and isn't usable.

### Version

2.8.18

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/826148/174082596-0cfd8b52-1a81-4cff-8563-ae58b9514762.png)

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6536
