### ISSUE TITLE
Default Value Not Working

### ISSUE THREAD

**Issue by swabhavmishra** [pods-framework/pods#6538]
### Description

After updating from version 2.8.17 to 2.8.20 now I'm getting problem. In the Pod Edit Fileds I have placed shortcode in default value but in frontend exact shortcode is showing allow shortcode option is ticked but not working.

### Version

2.8.20

### Screenshots / Screencast
![image](https://user-images.githubusercontent.com/107936870/174822129-eed66d11-1717-4670-9bef-66b289107c64.png)

![image](https://user-images.githubusercontent.com/107936870/174821753-7daee591-9c4b-4ed6-8818-19d859cb979e.png)

**Comment by sc0ttkclark** [comment]
Make sure the default value via parameter is not filled with that same shortcode. That's meant to specify which `?query_var_to_use=new+default+value` in the URL and you may be encountering some other issue as a result of that.

The default value works for me when I go to add a new post, so I'm wondering if there's something else going on for you here too.
