### ISSUE TITLE
Contents in pods-dfv-container-pick overflows one smaller windows.

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#6542]
### Description

When editing a custom post using the relationship field, the awesome pick list overflows if the window is small, say, when the screen is split 50/50 between two windows (yes, some are still copy-pasting content ;)

### Version

2.8.20

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/17141205/175289900-43cfc3c3-b37e-4d4f-9784-468595f07d43.png)

### Possible Workaround

The lists and its labels are shown in a table with appears to have fixed widths (eg the label column is 200px). Layout can probably be improved without having to change the markup, using CSS only, percentages, max-widths, and overflow properties. May experiment and report back.

**Comment by sc0ttkclark** [comment]
Fixed and tested via:

4d7df5db6577d91449f7bb80331993fc1e0537c4
83f5a6f16dc3ee54fc4d773c19c6dc04cb1d1024
6a9881c5ed913b7cf71fd25658797dc4025fcd24
e91eaa3e0d576f2533529ac13e94087dfb85a4e5
