### ISSUE TITLE
Pods 2.8.21 broke compatibility with Admin Columns Pro

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#6548]
### Description

After updating to Pods 2.8.21, which appears to include some changes to versioning, Admin Columns Pro will no longer activate.

Will roll back for now,.

### Version

2.8.21

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/17141205/176116938-34bc71d1-37dc-4784-8fd6-73f95b303d14.png)

![image](https://user-images.githubusercontent.com/17141205/176117018-de0fa7df-1366-4c17-a780-dd7d453e39f2.png)

**Comment by oldrup** [comment]
I added a support ticket on Admin Columns Pro as well. I'm unable to identify "who's to blame" 😉- but I hope you guys will figure it out. The Pods Framework / Admin Columns Pro is really a powerful combo.

https://www.admincolumns.com/forums/topic/latest-pods-framework-confuses-admin-columns-pro/

**Comment by sc0ttkclark** [comment]
Yeah this doesn't seem Pods specific, it sounds like something is going on there with their dependency logic. I looked at their 1.7 add on code and can see it checks this:

```

	$min_required_pods_version = '2.7';

	if ( ! function_exists( 'pods' ) || ! defined( 'PODS_VERSION' ) || ! version_compare( PODS_VERSION, $min_required_pods_version, '>=' ) ) {
		$dependencies->add_missing_plugin( __( 'Pods', 'pods' ), $dependencies->get_search_url( 'Pods' ), $min_required_pods_version );
	}
```

**Comment by JoryHogeveen** [comment]
Those conditionals should pass though, these are loaded on `after_setup_theme`.

**Comment by DGStefan** [comment]
I'm not able to reproduce the issue with Admin Columns Pods Integration 1.7 and Pods version 2.8.21.
And I checked the conditionals, I don't see why this should not work.
@oldrup are you able to reproduce the issue on a test environment with the same version?

**Comment by oldrup** [comment]
Thank you for helping debugging. I'll test on a different site, right away.

**Comment by oldrup** [comment]
I was not able to reproduce this on a different site either, nor on the original site where I experienced the error 🙄

![image](https://user-images.githubusercontent.com/17141205/176387833-967c2965-c41b-464f-995b-471316911348.png)

I haven't really got a good theory on what happened, but I'll definitely try reproducing any errors on a different site next time, before I bother you guys.

Thank you for your help. 🙏
