### ISSUE TITLE
Create new items from Autocomplete for Relationship field type

### ISSUE THREAD

**Issue by faneye** [pods-framework/pods#655]
Hello,

As a user coming from Drupal I wonder if these type of fields will be implemented in the future in Pods.
In Drupal there is something like this ( I think you guys already know what I'm talking about :) )

1) Field Type : List (text or integer or float) -> Widget : Select list or Check boxes / Radio buttons
2) Field Type : Term reference -> Widget : Autocomplete term widget (tagging)

Autocomplete option for tags (WITH OPTION TO ADD MORE TAGS, SEPARATED BY A COMMA!! ) instead of selecting existing tags as it is now in Pods) and Select lists would be very cool futures.

**Comment by sc0ttkclark** [comment]
We added tagging in Pods 2.4 or Pods 2.5 I think, closing.
