### ISSUE TITLE
Unable to unselect template on Pods

### ISSUE THREAD

**Issue by papa-pup** [pods-framework/pods#6558]
### Description

After enabling auto template and selected a template, we are unable to unselect the template

### Version

2.8.20 - 2.8.23

### Testing Instructions

1. Create any PODS
2. Enable Auto Template
3. Select any template and associate to it
4. Save
5. Now on the same PODs created, unSELECT (disassociate) the template and Save.
6. Select again the same PODs and you will see the template is still selected.

### Screenshots / Screencast

[2022-06-24T03-10-00D0-50.webm](https://user-images.githubusercontent.com/59635968/177191326-f2b77537-f702-460e-a74e-bb4f7278ea18.webm)
Error shown - PODS 2.8.20

### Possible Workaround

downgrade to 2.8.19

**Comment by sc0ttkclark** [comment]
Fixed via 60d32f4f3645c7d6f06e34d9718affd886513035
