### ISSUE TITLE
Admin table columns error on Pod with taxonomy relationship

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#6566]
### Description

Meta fields are not showing in the admin table columns. If you go to the Pods Admin UI tab there are suppressed errors (see screenshots)

I have other pods that are showing meta data ok. The only difference I see is that there are two pod fields that are taxonomy relationships. 

### Version

2.8.23

### Testing Instructions

1. Go to edit Master Exercises in the admin (no providing a link because it's in the admin, you have access), from here you will see there are no meta fields present
2. Go to `wb_master_exercise` Admin UI tab, from here you will see 2 suppressed errors

### Screenshots / Screencast

![screen_shot_2022-07-11_at_7 40 09_pm](https://user-images.githubusercontent.com/4442172/179423074-79b8ac09-3558-4aae-ac4f-e1562fc2051c.png)
![screen_shot_2022-07-11_at_7 41 35_pm](https://user-images.githubusercontent.com/4442172/179423076-ae652f22-e40f-4f9b-8e07-7d99502e7c0b.png)

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/c595bc864328e6b7bfe281cc9dd64b2dbff4da97
