### ISSUE TITLE
Load data dynamically in to relationship field

### ISSUE THREAD

**Issue by naveen17797** [pods-framework/pods#6568]
### Problem to Solve

Currently the relationship field loads the data statically when generating the page, this might not scale well when the number of items to show on the field is high.

### Proposed Solution

The data for the relationship field can be loaded via rest api, when this is enabled the relationship field will

- [ ]  Load x items initially upon page generation
- [ ] The other items are loaded when the user searches for a object ( post, term )

**Comment by JoryHogeveen** [comment]
Hi @naveen17797 
As far as I know this is already happening if you are using the `autocomplete` option. The threshold is at 30 items I believe.
Can you show us an example of what you mean?

**Comment by naveen17797** [comment]
Hi @JoryHogeveen , sorry i wasn't aware of that.  i created some pages and i assumed it was generating the select options statically. i will recheck and close this issue.

**Comment by naveen17797** [comment]
i can confirm this was functionality i needed, thanks for the support :smile: .
