### ISSUE TITLE
"Add Media" Button missing on post_content field for pods form (public form) after upgrading from 2.7x to 2.8.x

### ISSUE THREAD

**Issue by papa-pup** [pods-framework/pods#6569]
### Description

After upgrading from 2.7.x to 2.8.x; pods form containing the post_content field has missing "Add Media".

However, all other added new WYSIWYG fields remain having the "Add Media" button.

### Version

2.8.x

### Testing Instructions

1. Create a mew Custom Post Type
2. Create a new Page with PODS form showing the post_content; and you will see that it is missing in 2.8.x but not on 2.7.x

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/59635968/180475864-bb169e3e-8ac2-4785-abc2-1adccb4d5178.png)
Highlighted is the "Add Media" button affected which goes missing on 2.8.x
Screen capture is using Pods 2.7.x

### Possible Workaround

1. Create another WYSIWYG field for data entry
3. Upon saving the post, copy the content into the post_content field.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/a75cf27fe97c9f3d67b1b978da57e59a8c2c6443

**Comment by papa-pup** [comment]
@sc0ttkclark ,
The "Add Media" button is there now. However, it is not responding - clicking the "Add Media" does not open up the media library.

**Comment by sc0ttkclark** [comment]
Fixed and tested via c91245641cc2d3c66097f690377106e97cc2a04a
