### ISSUE TITLE
Issues with version 2.9.0-rc1

### ISSUE THREAD

**Issue by naveen17797** [pods-framework/pods#6576]
### Description

I have found two issues related to version 2.9.0-rc1

when i  register a pod name via code which is not a post_type, its not showing the fields on the `post_type`

For example to show the fields on the `page` post_type, i would need to name the pod as `page`

You can replicate the issue with the below code snippet

```
add_action('init', function () {
	$pod            = pod( 'page', 'post_type', 'page' );
	group( 'Example Group', $pod, group_fields( array( text('my field') ) ) );
});



function text( $name ) {
	return array(
		'name'                   => $name,
		'label'                  => ucwords( $name ),
		'description'            => '',
		'weight'                 => 0,
		'type'                   => 'text',
		'sister_id'              => '-- Select One --',
		'rest_route'             => '/pods/v1/fields',
		'required'               => '0',
		'text_allowed_html_tags' => 'strong em a ul ol li b i',
		'text_max_length'        => '255',
		'roles_allowed'          => 'administrator',
		'rest_pick_response'     => 'array',
		'rest_pick_depth'        => '1',
	);
}


function group_fields( ...$fields ) {
	$fields = array_merge( ...$fields );
	$result = array();
	array_map( function ( $item ) use ( &$result ) {
		$field_name            = $item['name'];
		$result[ $field_name ] = $item;
	}, $fields );


	return $result;
}

function group( $name, $pod, $group_fields ) {
	$group = array(
		'name'        => $name,
		'label'       => ucwords( $name ),
		'description' => '',
		'weight'      => 0,
	);
	pods_register_group( $group, $pod['name'], $group_fields );
}

function pod( $name, $object_equals, $object_type_equals ) {
	$pod = array(
		'name'         => $name,
		'label'        => ucwords( $name ),
		'description'  => '',
		'type'         => $object_equals,
		'storage'      => 'meta',
		'object'       => $object_type_equals,
	);

	pods_register_type( $pod['type'], $pod['name'], $pod );

	return $pod;
}
```

In this snippet, if you change the first argument of the pod function from `page` to `page1` its no longer showing the fields on the `page` post_type

```
add_action('init', function () {
	$pod            = pod( 'page', 'post_type', 'page' );
	group( 'Example Group', $pod, group_fields( array( text('my field') ) ) );
});
```

The second issue i found is related to pod deletion. When i create a pod using ui, i was not able to delete it from the pods list.
![image (2)](https://user-images.githubusercontent.com/18109258/181269802-d177828b-d397-4964-9493-2c2f6415ce7b.png)
![image (1)](https://user-images.githubusercontent.com/18109258/181269814-e7ab2e8f-a72f-4af1-b1d3-494d996f430f.png)

However i was able to delete the pod from inside the pod edit screen

![image](https://user-images.githubusercontent.com/18109258/181269818-1fca066e-6689-4c24-bf6b-272ac7452a3d.png)

### Version

2.9.0-rc1

**Comment by sc0ttkclark** [comment]
Fixed via 510264d1c5b49415857fef9b6c14e27a9c98c039

You can get RC 2 from https://github.com/pods-framework/pods/releases/tag/2.9.0-rc-2

**Comment by naveen17797** [comment]
@sc0ttkclark now i get this error message when i use the same snippet. No errors on the error log.

![image](https://user-images.githubusercontent.com/18109258/182070898-8ebc87f8-9dbe-42a1-9ed4-c0e22ba76a8d.png)

**Comment by sc0ttkclark** [comment]
Noting here about the original issue problem about renaming to `page1` in the code:

> In this snippet, if you change the first argument of the pod function from page to page1 its no longer showing the fields on the page post_type

Changing to 'page1' leaves the third argument there as 'page' which means it doesn’t match up to what you’re trying to create/extend. If you are creating, you need to not pass object because object is meant for extending something that exists already in WP (through another plugin’s code or core). Essentially, you end up creating a new pod but it’s mapped to one that doesn’t exist so it will not get registered — and even once you remove the object, it will register as an empty post type without any other options available to it.
