### ISSUE TITLE
Improve repeatable fields UI (reduce size)

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6853]
Currently the repeatable fields UI is quite large.
This can be reduced and more aligned with the WP core UI with a few tweaks:

## Current (2.9.1):
![image](https://user-images.githubusercontent.com/826148/184242214-cde58b9d-29c7-46d3-b622-fdf30710837c.png)

## Suggested:
![image](https://user-images.githubusercontent.com/826148/184242370-4c7390fd-0735-4f04-962c-2dcd8ffb1ed7.png)
Large fields:
![image](https://user-images.githubusercontent.com/826148/184335437-11c0b35c-94e5-41f7-b962-0c78f5d8dda6.png)
Hover & Draggins:
![Edit-Person-“Person-Y”-‹-5-Hurkadurk-—-WordPress](https://user-images.githubusercontent.com/826148/184340346-771d9e96-0d9e-44cd-8935-ca94345e70b2.gif)

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6854
