### ISSUE TITLE
Repeatable: Code field

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6856]
### Description

The code field cannot render when repeatable: `There was an error rendering the field.`

### Version

2.9.1

**Comment by sc0ttkclark** [comment]
Code field does not have repeatable option, however if you have a field that is repeatable and you switch to a non-repeatable field type -- then it attempts to save that repeatable option. Will look into that.

**Comment by sc0ttkclark** [comment]
Non-repeatable fields are forced as non-repeatable in these cases now: c9c43da281c3a361cc20ff4ef13a53d51235651d

Will need to eventually follow-up with work in the DFV field editor to not send any values for those fields that should not conditionally be shown (like repeatable, unique, etc).
