### ISSUE TITLE
Repeatable: Color field UI

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6858]
### Description

Similar to the date/time field (#6857)

The color picker that shows when clicking a color field is messing the the UI.
Probably better to open this in a popover/dropdown instead of within the container.

https://wordpress.github.io/gutenberg/?path=/story/components-dropdown--default

v2.9.1:
![image](https://user-images.githubusercontent.com/826148/184254548-8ae955d0-7679-41f8-b460-41ec0fb2fdb7.png)

Suggestion:
![image](https://user-images.githubusercontent.com/826148/184261150-924408b1-ac85-49b8-8942-6a2e35818b9f.png)

### Version

2.9.1

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6859
