### ISSUE TITLE
Taggable not working anymore

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6862]
### Description

User reported: https://wordpress.org/support/topic/taggable-options-does-not-works-in-a-bi-directional-field/

Tested locally and can confirm that the taggable option does not work anymore.

After a fix we should definitely create a unit test for this!

Might be related to these commits:
- https://github.com/pods-framework/pods/commit/c311df17dea0a3a4ce623c15b763f048dab13e69
- https://github.com/pods-framework/pods/commit/c84245d5fb076726bf000be48870b290662de07a

### Version

2.9.1

### Testing Instructions

1. Create taggable relationship field
2. Try to create a new relationship
3. Computer says no :(

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
After testing I found that the condition below passes as `true` when passing a string value (as taggable does).
https://github.com/pods-framework/pods/blob/main/classes/PodsAPI.php#L5734

This is the cause that the whole taggable code is never reached.

**Comment by JoryHogeveen** [comment]
Nevermind, found it.

https://github.com/pods-framework/pods/commit/c84245d5fb076726bf000be48870b290662de07a
`/[^0-9]/'`  was changed into `'/[^\D]/'` and this changes the behavior for non-numeric strings:

`preg_match( '/[^\D]/', 'Test' )` => `0`
`preg_match( '/[^0-9]/', 'Test' )` => `1`

So the first regex will result in a `true` statement (note the `!` in that line of code).

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6863
