### ISSUE TITLE
WPGraphQL "Internal server error"

### ISSUE THREAD

**Issue by anirudh7** [pods-framework/pods#6868]
### Description

After updating to 2.9.2 this [error ](https://github.com/pods-framework/pods/issues/6865) took a new turn.

`{
  "errors": [
    {
      "debugMessage": "Access to undeclared static property: Pods\\Pod_Manager::$pods",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "itsnzSpeakers",
        "edges",
        0,
        "node",
        "speakerName"
      ]
    }
  ],
  "data": {
    "itsnzSpeakers": {
      "edges": [
        {
          "node": {
            "speakerName": null
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": []
  }
}`

### Version

2.9.2

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/5333996/184952030-5232448c-2a7f-49ec-8d64-b74b53a5bd7c.png)

### Pods Package

```json
{
    "@meta": {
        "version": "2.9.2",
        "build": 1660674468
    },
    "settings": {
        "types_only": "0",
        "watch_changed_fields": "0",
        "metadata_integration": "1",
        "metadata_override_get": "0",
        "session_auto_start": "0",
        "wisdom_opt_out": "1"
    },
    "pods": [
        {
            "name": "itsnz_speaker",
            "id": 23,
            "label": "ITSNZ Speakers",
            "description": "",
            "type": "post_type",
            "storage": "meta",
            "label_singular": "ITSNZ Speaker",
            "public": "1",
            "show_ui": "1",
            "rest_enable": "1",
            "supports_title": "1",
            "supports_editor": "1",
            "_migrated_28": "1",
            "required": "0",
            "repeatable": "0",
            "wpgraphql_enabled": "1",
            "wpgraphql_all_fields_enabled": "1",
            "wpgraphql_pick_format": "connection",
            "wpgraphql_file_format": "connection",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 24,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "speaker_name",
                            "id": 25,
                            "label": "Speaker Name",
                            "description": "",
                            "weight": 0,
                            "type": "text",
                            "sister_id": "-- Select One --",
                            "required": "0",
                            "repeatable": "0",
                            "text_allowed_html_tags": "strong em a ul ol li b i",
                            "text_max_length": "255",
                            "roles_allowed": "administrator",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "wpgraphql_enabled": "1",
                            "wpgraphql_pick_format": "connection",
                            "wpgraphql_file_format": "connection",
                            "text_trim": "1"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by sc0ttkclark** [comment]
Is the WPGraphQL Integration Pods Pro Add-On enabled? Try deactivating that and confirm whether you see that error.

**Comment by anirudh7** [comment]
> Is the WPGraphQL Integration Pods Pro Add-On enabled? Try deactivating that and confirm whether you see that error.

It was deactivated but still the same.

![image](https://user-images.githubusercontent.com/5333996/184955520-2be4e13e-6fd2-4a04-8732-e284e877fdb6.png)

**Comment by deployn** [comment]
I do have the same issue, but I also had it yesterday with version 2.9.1

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/6ff0a5b2177d49a3f5c5ef364e355a2dc1c2c882

To be released later today
