### ISSUE TITLE
Code field broken in 2.9.2

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6870]
### Description

https://wordpress.org/support/topic/new-version-2-9-2-bug/

2.9.2 completely broke the code field, both single and repeatable.

Related: #6856

### Version

2.9.2

### Testing Instructions

1. Add code field
2. Try to edit it
3. "There was an error rendering the field."

**Comment by JoryHogeveen** [comment]
@sc0ttkclark After research I found that this is a compilation issue.
After recompiling locally it works again.

I did get a babel issue in that I needed to add `@babel/plugin-syntax-jsx` to the babelrc file's "plugins" list.

**Comment by sc0ttkclark** [comment]
Fixed via 5278278f78739b03fa00b2bc74c9d115fb29a09b (did a fresh npm install after removing node_modules, then did a fresh prod build)
