### ISSUE TITLE
Pod name is different than the pod name filled automatically when using accents after created

### ISSUE THREAD

**Issue by alexfoffano** [pods-framework/pods#6874]
### Description

When creating a new pod and filling the singular and plural labels using a term with accents (for example "vídeo"), the pod name is automatically filled as "video" (which is okay, no problem here), but after going to the next step the pod name is now "vdeo" without the accent and the letter.

### Version

2.9.3

### Testing Instructions

1. Go to Pods Admin > Add new > Create new
2. Fill the singular and plural labels using a term with accent ("vídeo", for example)
3. Click Advanced
4. Observe that the Pod name is filled automatically as the term without the accent (in this example, "video")
5. Click Next step
6. The pod is created without the letter with accent (in this example, "vdeo")

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/a971a6aced4458aaab463a5f7875f26c6f4357b5
