### ISSUE TITLE
 WordPress database error Unknown column 'wp_postmeta.meta_key'......

### ISSUE THREAD

**Issue by soman** [pods-framework/pods#6879]
### Description

When tried from React UI
![image](https://user-images.githubusercontent.com/2465685/187229885-c0dc0493-5b06-4db6-80db-d8ffdf94e7e9.png)

When I browse WP admin
![image](https://user-images.githubusercontent.com/2465685/187240422-16821f37-0ce9-4e42-afb8-5193f0b4e2f0.png)

### Version

2.9.3

### Testing Instructions

React, WP-Graphql plugin and Pods

When I browsed WP Admin's any link then I'm seeing this error in error_logs
Also when I tried to do anything from react UI with wp-graphql then also shows this error in error_logs

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/2465685/187229964-5f5c60a5-7621-4e5e-8215-75c8aff3baa8.png)

![image](https://user-images.githubusercontent.com/2465685/187240450-6c1b6895-3bf2-46dc-a9f0-1e95b2738814.png)

**Comment by sc0ttkclark** [comment]
Can you provide the full error message and logging that explains which files were in the backtrace?

I can't reproduce this at the moment.

**Comment by sc0ttkclark** [comment]
I don't think there's anything we can do about this particular error -- it appears that something was interfering with the WP_Query or WP_Meta_Query handling here and not properly joining the appropriate wp_postmeta table. Probably another plugin doing something there, but I'm not sure it would do that if there were meta fields provided to `meta_query`.
