### ISSUE TITLE
Media button at Custom Settings Page does not work

### ISSUE THREAD

**Issue by HemboPagi** [pods-framework/pods#6883]
### Description

I have created Custom Settings Page with WYSIWYG filed and enabled Media button. When clicking on it nothing happens.

### Version

2.9.3

### Testing Instructions

1. Create new Pods
2. Select Custom Settings Page as content type
3. Create WYSIWYG filed
4. Enable Media button
5. Add new entry under created Pods
6. Click Add Media button

### Screenshots / Screencast

<img width="858" alt="Screenshot 2022-09-02 at 09 34 22" src="https://user-images.githubusercontent.com/95413906/188073715-d4b37e24-61bc-4dfc-b93a-4ae8a3c0323e.png">

**Comment by sc0ttkclark** [comment]
Fixed in 2.9.4
