### ISSUE TITLE
Bug with $display_filter in pods/classes/fields/pick.php

### ISSUE THREAD

**Issue by therealgilles** [pods-framework/pods#6907]
### Description

The value of `$display_filter` is computed using `$search_data->field_index` but a `$field_index` variable is computed below and used in `$filter_args`:

```PHP
              $filter_args = array(
                $display_filter,
                $result[ $field_index ],
              );
```

I think `$display_filter` ought to be computed as follows in the `$results` foreach loop:

```PHP
            // COMPUTE $display_filter HERE with the new $field_index
            $display_filter = pods_v( 'display_filter', pods_v( $field_index, $search_data->object_fields ) );

            if ( 0 < strlen( $display_filter ) ) {
              $display_filter_args = pods_v( 'display_filter_args', pods_v( $field_index, $search_data->pod_data['object_fields'] ) );

              $filter_args = array(
                $display_filter,
                $result[ $field_index ],
              );
```

### Version

2.9.3

### Testing Instructions

1) Set `Display Field in Selection List` to `{@permalink}` for a custom field added to a (custom?) post type.
2) Add a `the_title` filter (to functions.php for instance).

`{@permalink}` will set `$field_index` to `post_name` and the original `$display_filter` will be empty as there are no filters for slugs. But the original `$display_filter` will be computed with the default field index for post type, which is the post title, so `$display_filter` below will not be empty:

```PHP
$display_filter = pods_v( 'display_filter', pods_v( $search_data->field_index, $search_data->object_fields ) );
```

This will result in if `$display_filter` if condition been true and `$filter_args` being evaluated as:

```
Array
(
    [0] => the_title
    [1] => ...post name (slug) here...
)
```

which is twice wrong, i.e. it's using the post slug instead of the post title, and it's missing the post ID as 2nd argument, which is necessary to run `the_title` filter.

**Comment by JoryHogeveen** [comment]
Hi @therealgilles 

Looks good to me, thank you for your research?
If you want you can make a pull request with this fix since credits for this are obviously yours!

Cheers, Jory

**Comment by therealgilles** [comment]
PR here: https://github.com/pods-framework/pods/pull/6909

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6909
