### ISSUE TITLE
pods group cause issue during import on multisite

### ISSUE THREAD

**Issue by kokosg** [pods-framework/pods#6910]
### Description

Import says that is Completed but 2 out of for groups are empty

### Version

2.9.3

**Comment by sc0ttkclark** [comment]
After looking into the package you sent me, you have many fields on this pod which have max limits of 255. Those fields get stored in the database as VARCHAR(255) and contribute towards the maximum row size for the database table itself.

At a certain point, those fields add up to the limitation of 65535 which will prevent you from properly adding new columns to that table.

More details about how the VARCHAR calculates and how you can reach it depending on the CHARACTER SET in your table: https://stackoverflow.com/a/34731323/423330

That’s a database constraint unfortunately.

The best solution is to determine which fields you need 255 characters for and which need less — you can also set them to all use max characters 300 so they use LONGTEXT instead which gets around the row size limitations.

You can easily do this in your package (export the your package, edit it, then import your package again).

Replace this: `"text_max_length": "255",`
with this: `"text_max_length": "300",`

After you import the package then the table should be in much better shape.
