### ISSUE TITLE
Not all checkboxes are set correctly when creating a new Pod

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6914]
### Description

When you create a new Pod and go the the advanced options you'll see nearly all checkboxes unchecked.

However, after saving and reloading the page you'll see that in fact many of these have default values saved.

The UI should mark these checkboxes according to the default value right at the start of a new Pod.

### Version

2.9.3

**Comment by sc0ttkclark** [comment]
This looks fixed based on the code changes made to 2.9.4 that address this specific handling (unchecking boxes would some times revert to checked if those options were defaulting to on).
