### ISSUE TITLE
Since Pods 2.9.4: Restricted Access within Templates defaults to Yes

### ISSUE THREAD

**Issue by danmaby** [pods-framework/pods#6916]
### Description

When creating a new template or editing an existing one in 2.9.4, the Restricted Access settings all default to `Yes`. When unchecking these settings and updating, they default to `Yes`. 

### Version

2.9.4

### Testing Instructions

1. Publish a new Template with no Restricted Access 
2. Review Template
3. See restrictions applied
4. Remove restrictions
5. Update
6. See restrictions applied again  

### Screenshots / Screencast

![pods-2 9 4](https://user-images.githubusercontent.com/13104185/191715264-a4ad79cd-3dbe-4046-80b7-cdd82987c44e.gif)

### Possible Workaround

Temporarily [downgrading to 2.9.3](https://wordpress.org/plugins/pods/advanced/) restores expected behaviour.

**Comment by oldrup** [comment]
Mmm, as this obviously only really affects people without access rights, it goes unseen by me, the admin, until some non-admin user complains: 
![image](https://user-images.githubusercontent.com/17141205/191766961-ab4947dd-0128-4530-8480-fa7d6d610d7e.png)

I've spend some time creating a screencast, somewhat redundant to the fine testing instructions by @danmaby but here it is:
https://www.loom.com/share/09931098c9e048f5b33f097a4079d06c

**Workaround**: disabling the restrictions actually seems to work, even though they still look enabled in the backend.

Is this related to "Fixed: Pod/Group/Field configurations being saved now get their checkbox boolean options properly enforced as 0/1 and sent so they are not reverted to the default value on next load. #6485 (@sc0ttkclark)" ?

Bjarne

**Comment by sc0ttkclark** [comment]
@oldrup it was unrelated to that it appears

Fixed this in the end by just making this into a legitimate pod object (since it was an internal pod but fields were not defined the same way).

960d4e4d98e7a74bb1b9fdc9229ec0bf5b75ffb6
