### ISSUE TITLE
With 2.9.5 problem with related

### ISSUE THREAD

**Issue by sergiobellini** [pods-framework/pods#6919]
### Description

Hi,

after 2.9.5 upgrade, my relationship field with "List View (with reordering)" expanding the dropdown shows about twenty posts, but if I try to do the search it always says that it does not find results.

It's a problem of the last update?

### Version

2.9.5

**Comment by sc0ttkclark** [comment]
Fixed via ee19721aa2c3c25b4d9579ce78a2b7bbcff3b1e7
