### ISSUE TITLE
Add recurring date-time field type

### ISSUE THREAD

**Issue by manastalukdar** [pods-framework/pods#692]
This is a feature request: Add a recurring date-time field type with an advanced option to only choose date or time.

**Comment by Archie22is** [comment]
'Sup @manastalukdar & @sc0ttkclark, 

What's the progress on this one? Sorry, I can't seem to pick it up anywhere in the documentation.

**Comment by sc0ttkclark** [comment]
I think we can solve this a part of Pods 2.9 when we add simple repeatable fields #1095

**Comment by sc0ttkclark** [comment]
Closing this as we'll have repeatable date fields in #1095
