### ISSUE TITLE
Pods Templates content pushed way over to the right

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#6921]
### Description

After the latest update, the template editor seems to go haywire. Please see the attached screenshot. Tested in Firefox and Chrome. All caching disabled.

### Version

~2.9.6~ 2.9.5

### Testing Instructions

1. Open any template

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/17141205/191905492-051030b8-d655-4d8b-9cd6-6244ceae1949.png)

### Possible Workaround

None found yet.

**Comment by oldrup** [comment]
Thank you so much for addressing this quickly. I really prefer to avoid a temporary downgrade if that might affect the database. Editing templates is on hold for now, but existing templates do work fine on the front end, so that is something. 

Please let me know if I can assist in further troubleshooting or testing during the weekend. 

All the best.
Bjarne

**Comment by sc0ttkclark** [comment]
Fixed via #6924
