### ISSUE TITLE
Parse issue with number and currency formats (HTML5)

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6922]
### Description

The current implementation from React conflicts with the PHP side.

Currently React creates two internal values from the number fields:
- Parsed: Parsed according to the user set number format.
- Float: The float version of this value.

The PHP side also parsed the number based on the user set number format.

What happens now is that React sets the actual field value to the Float version and sends that to the server.
However, PHP then tries to parse the value using the user defined format and this creates issues.

From my perspective we have 3 options:

1. Change PHP (not recommended)
Make sure PHP always parsed the value as if it was a float. This will most likely create issues with backwards compatibility and other custom implementations.

2. Change React
Make sure React stores the formatted value and let PHP re-format the same value for storage.

3. Add a second hidden field.
Just like with dates we could create a second field (fieldname__formatted for example).
If this field exists in the POST request we use it for PHP otherwise we use the regular input.

### Version

2.8.0 - 2.9.6

### Testing Instructions

1. Create field with format `9.999,99` (comma as decimals)
2. Try to safe field with decimals.

## UPDATE

I noticed this using a HTML5 field.
Apparently a HTML5 field also only parses as `9999.99` format just as a slider.

I still need to proper validate non-HTML5 parsing but it seems the HTML5 could be fixed quite easily.

Few thinks to note about HTML5 fields:
- accepts both a dot and a comma as a decimal separator
- does not accept any thousands separators
- requires the `step` parameter to properly set the number of allowed decimals.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6928
