### ISSUE TITLE
Magic tags in pods template not displaying proper number formatting when pulling from a related post type

### ISSUE THREAD

**Issue by reedtsutton** [pods-framework/pods#6929]
### Description

I have two custom post types in wordpress - 'credit cards' and 'rebate offers'

I am using  a pods template for rebate offer single pages. Some of the data on the page is pulled in using magic tags, from rebate offer custom fields, and other data from credit card custom fields, using relationship field (each rebate offer is related to a credit card). 

In this example - I have a field in credit cards called 'current bonus' , and the value is 60,000. When I use current_bonus elsewhere on the site it displays the default number formatting with the comma. However when I pull it into this template using the magic tag from the relationship field: {@offer_credit_card.current_bonus}, it loses this formatting.

I also noticed when I use the relationship for currencies, it loses the '$', but if I use a currency field directly eg. {currency} from rebate_offer instead of {@offer_credit_card.currency}  from credit_card, it keeps the '$' formatting as set in pods field configuration.

See attached images. 

### Version

2.9.8

### Screenshots / Screencast

<img width="372" alt="pods-capture1" src="https://user-images.githubusercontent.com/24797871/193101630-2d43aefc-053d-4188-a814-bac56a8c2fe9.PNG">
<img width="468" alt="pods-capture2" src="https://user-images.githubusercontent.com/24797871/193101640-ce5e6686-755f-4543-ae1f-bc5213f743b5.PNG">
<img width="708" alt="pods-capture3" src="https://user-images.githubusercontent.com/24797871/193101643-fc935d37-4881-4525-8da2-fa33989f0d3a.PNG">
<img width="462" alt="pods-capture4" src="https://user-images.githubusercontent.com/24797871/193101645-a6ebb0a5-0d3a-4351-8ae8-a8277d73bfdb.PNG">

**Comment by JoryHogeveen** [comment]
Tested locally and confirmed. Formatting is not done when traversing through relationships.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Just tested through various version and found that this wasn't even working in Pods 2.8

**Comment by JoryHogeveen** [comment]
Did some research and the bottleneck is as follows:

https://github.com/pods-framework/pods/blob/2.9.8/classes/Pods.php#L1563-L1576

Once the traversal cannot traverse deeper and the last iteration is an object it will not fetch a Pod object for this but simply fetch the metadata.

At this point the `$last_options` is filled so the `$related_obj` is never checked for formatting
https://github.com/pods-framework/pods/blob/2.9.8/classes/Pods.php#L1607-L1612

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6930
