### ISSUE TITLE
Can edit my current pods

### ISSUE THREAD

**Issue by carlosrovira** [pods-framework/pods#6931]
### Description

I discover today that my current pods are not recognized. I get "**You do not have any Pods set up yet. You can set up your very first Pod below.**" notification above. I have pods plugin to update automatically and my site is without changes since 2.8 release where I need to do some changes since it was a huge release with lots of changes, but now we are in 2.9.8 and don't know when this problem was introduced.

Some ideas on how to solve it?

thanks

### Version

2.9.8

### Testing Instructions

1. just go to pods section
2. No current pod shows to edit and the message "You do not have any Pods set up yet. You can set up your very first Pod below." with the screen to create new pod or extend

### Possible Workaround

Can't find any

**Comment by sc0ttkclark** [comment]
Is anything showing up after you go to Pods Admin > Settings > Clear Pods Cache?

Also helpful would be access to your Site Health information (Tools > Site Health > Info Tab > Copy site info to clipboard) would also help us determine if there are any potential conflicts from other plugins or your theme.

**Comment by carlosrovira** [comment]
Hi Scott, after clearing cache nothing changes
I'm seeing one of the pods, since I tried yesterday to go to "extend", but didn't do anything more. now that pod show in edit but without content

here 's the info site (some paths was changed to *** to avoid share sensible info):

`
### wp-core ###

version: 6.0.2
site_language: es_ES
user_language: es_ES
timezone: Europe/Madrid
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 7
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /***/codeoscopic.com
wordpress_size: 140.01 MB (146811280 bytes)
uploads_path: /***/codeoscopic.com/wp-content/uploads
uploads_size: 862.08 MB (903957584 bytes)
themes_path: /***/codeoscopic.com/wp-content/themes
themes_size: 42.28 MB (44337822 bytes)
plugins_path: /***/codeoscopic.com/wp-content/plugins
plugins_size: 167.30 MB (175422516 bytes)
database_size: 71.13 MB (74579968 bytes)
total_size: 1.25 GB (1345109170 bytes)

### wp-active-theme ###

name: Codeoscopic 2021 Theme (***)
version: 1.0.9
author: Alexis Hill Prados & Carlos Rovira
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, post-formats, widgets
theme_path: /***/codeoscopic.com/wp-content/themes/***
auto_update: Desactivado

### wp-plugins-active (28) ###

Akismet Anti-Spam: version: 5.0.1, author: Automattic, Actualizaciones automáticas activadas
Classic Editor: version: 1.6.2, author: WordPress Contributors, Actualizaciones automáticas activadas
Classic Widgets: version: 0.3, author: WordPress Contributors, Actualizaciones automáticas activadas
Codeoscopic Site: version: 1.0.2, author: Carlos Rovira, Actualizaciones automáticas desactivadas
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: version: 6.15.4, author: SeedProd, Actualizaciones automáticas activadas
Contact Form 7: version: 5.6.3, author: Takayuki Miyoshi, Actualizaciones automáticas activadas
Contact Form 7 Multilingual: version: 1.1.0, author: OnTheGoSystems, Actualizaciones automáticas activadas
CookieYes | GDPR Cookie Consent: version: 3.0.1, author: CookieYes, Actualizaciones automáticas desactivadas
Duplicate Page: version: 4.4.9, author: mndpsingh287, Actualizaciones automáticas activadas
Dynamic Featured Image: version: 3.7.0, author: Ankit Pokhrel, Actualizaciones automáticas activadas
Email Encoder - Protect Email Addresses: version: 2.1.3, author: Ironikus, Actualizaciones automáticas activadas
Flamingo: version: 2.3, author: Takayuki Miyoshi, Actualizaciones automáticas activadas
MailChimp for WordPress Multilingual: version: 0.0.3, author: OnTheGoSystems, Actualizaciones automáticas activadas
Pods - Custom Content Types and Fields: version: 2.9.8, author: Pods Framework Team, Actualizaciones automáticas activadas
Rank Math SEO: version: 1.0.98.2, author: Rank Math, Actualizaciones automáticas activadas
Snippet Shortcodes: version: 4.0.1, author: Ali Colville, Actualizaciones automáticas activadas
SVG Support: version: 2.5.1, author: Benbodhi, Actualizaciones automáticas activadas
UpdraftPlus - Backup/Restore: version: 1.22.23, author: UpdraftPlus.Com, DavidAnderson, Actualizaciones automáticas activadas
Wordfence Security: version: 7.6.2, author: Wordfence, Actualizaciones automáticas activadas
WP-Optimize - Clean, Compress, Cache: version: 3.2.7, author: David Anderson, Ruhani Rabin, Team Updraft, Actualizaciones automáticas activadas
WP Fastest Cache: version: 1.0.5, author: Emre Vona, Actualizaciones automáticas activadas
WP Fastest Cache Premium: version: 1.6.5, author: Emre Vona, Actualizaciones automáticas activadas
WPML Media: version: 2.7.1, author: OnTheGoSystems, Actualizaciones automáticas activadas
WPML Multilingual CMS: version: 4.5.11, author: OnTheGoSystems, Actualizaciones automáticas activadas
WPML SEO: version: 2.1.0, author: OnTheGoSystems, Actualizaciones automáticas activadas
WPML Sticky Links: version: 1.5.4, author: OnTheGoSystems, Actualizaciones automáticas activadas
WPML String Translation: version: 3.2.2, author: OnTheGoSystems, Actualizaciones automáticas activadas
Zoho-Subscriptions: version: 3.0, author: Zoho Subscriptions, Actualizaciones automáticas activadas

### wp-plugins-inactive (2) ###

Google XML Sitemaps: version: 4.1.5, author: Auctollo, Actualizaciones automáticas activadas
Smush: version: 3.11.1, author: WPMU DEV, Actualizaciones automáticas activadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.4.4
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.11.0-49-generic x86_64
httpd_software: Apache/2.4.46 (Ubuntu)
php_version: 7.4.16 64bit
php_sapi: apache2handler
max_input_variables: 3000
time_limit: 300​
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 128M
curl_version: 7.74.0 OpenSSL/1.1.1j
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 8.0.27-0ubuntu0.21.04.1
client_version: mysqlnd 7.4.16
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /***/codeoscopic.com/wp-content
WP_PLUGIN_DIR: /***/codeoscopic.com/wp-content/plugins
WP_MEMORY_LIMIT: 128M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Sin definir
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache/2.4.46 (Ubuntu)
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Sí
pods-session-save-path-writable: Sí
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Sí
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 51,824M
pods-memory-current-usage-real: 54,000M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Sí
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Sí
pods-api-cache: Sí
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Desactivar sesiones
pods-can-use-sessions: Sí
pods-relationship-table-status: 131

`

**Comment by sc0ttkclark** [comment]
I've continued to face difficulty in reproducing this. Going to see if our team can think of any further ideas on what may be causing this to happen on your site.

If you'd like to join our Live Community Pods Slack at https://support.pods.io/chat/ -- I'm sure we can help you debug this more quickly and get to the bottom of the issue. Once you join, just look for me and send me a Direct Message and I can work with you to figure this out.

Is that something you're open to?

**Comment by carlosrovira** [comment]
Hi @sc0ttkclark, ok. I'll want to help on this. I'll put a reminder since I'm on vacation these days and see as I come back in few days where I can have some free time to handle this. I hope to come back to you in a week or so to do have that chat.

**Comment by carlosrovira** [comment]
Hi @sc0ttkclark, I just saw a new update of Pods, and enter to check it and seems all is solved with this new release. I'll try in the next few days to have some time to check it more deeply but for now I can see again the pods listed and can be edited. So I'll close the ticket for now. If I see something wrong I'll report it here. Thanks!
