### ISSUE TITLE
PHP 8.1 deprecated warnings

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#6943]
### Description

When switching to PHP 8.1 and WordPress 6.1RC5 on my test bench, Query Monitor logs PHP Errors related to Pods Framework. Those are all deprecation warnings.

### Version

2.9.8

### Testing Instructions

Update to WordPress 6.1
Update to PHP 8.1
Install Query Monitor plugin
Install Pods Framework
Look for PHP errors (warnings) logged in Query Monitor

### Screenshots / Screencast

<img width="1280" alt="Pods Framework and PHP 8 1 deprecation warnings" src="https://user-images.githubusercontent.com/17141205/198820066-26608d8b-d2e8-4089-91c9-f5b6e5ef9c79.PNG">

### Possible Workaround

Downgrade to PHP 8.0.x

**Comment by sc0ttkclark** [comment]
This will be resolved automatically as part of Pods 3.0 because it includes a new minimum version requirement of PHP 7.2+ which lets us use more recent PHP method signatures.

Same issue as reported here: #6579

**Comment by ztackett11** [comment]
When is the expected release date for pods 3.0?
