### ISSUE TITLE
Version 2.9.9 may be leading to request time-outs?

### ISSUE THREAD

**Issue by therealgilles** [pods-framework/pods#6947]
### Description

I'm seeing regular request time-outs with version 2.9.9:
```
Maximum execution time of 360 seconds exceeded
```

I just reverted to version 2.9.8 and they seemed to have stopped, so I suspect the 2.9.9 version, but I don't have much information to offer. Request time-outs are very hard to debug.

### Version

2.9.9

**Comment by therealgilles** [comment]
Problem still happening with 2.9.8, so probably not related to the Pods plugin after all, closing.

**Comment by lkraav** [comment]
It may be. There's known massive performance issues with Pods "Enable overriding WP Metadata values" setting. Try toggling this and measure your page build results? Your rendering will be affected by this toggle, if its off, code needs to do its own work to pull data.

**Comment by therealgilles** [comment]
I can confirm my problem was related to an infinite loop created by the Event Calendar plugin due to a caching bug, which has since been fixed. The cached return value was incorrect and was pointing to an event whose content contains the same shortcode that was under evaluation, leading to the infinite loop and the request time-out.
