### ISSUE TITLE
Bug DVF with pod relationship and Input type list view 

### ISSUE THREAD

**Issue by spiderneo** [pods-framework/pods#6963]
### Description

Hi, i'm not sure how to explain this issue. Sorry if i dont use the right terms :S

I have a Pods (let's name it **Parent**) with a custom field related to another pods (name it **child**).  I use the relationship field, which work perfectly. 

The field is configured to be able to add a new child pods and it's using the list view (with reordering) input type. 
So the admin page look like this : 
![image](https://user-images.githubusercontent.com/3339248/205860428-ceb60fa0-c47e-4102-b577-f4244ddf2f61.png)

If I add a new field Child, it opens the iframe to add a new child. I add all the informations, publish the pods, and then i got an error in the JS console : Uncaught TypeError: Invalid attempt to spread non-iterable instance. The main problem with this error is that the newly created child pods is not assigned to the parent Pods. The child is available in the select but is not pre-selected. 

![Capture d’écran 2022-12-06 à 09 36 33](https://user-images.githubusercontent.com/3339248/205861306-86942117-9b78-49e0-a05e-339ab8db8afc.png)

This is happening, ONLY when i edit a parent post with 0 reference to a child post. If there is at least 1 it's ok, the newly created Child pods will be preselected in the select input. 

I know where the error come from, but i'm not able to correct it :S 

In dfv.min.js
the console.log **Pods init with initial values:** show values. The field **pods_meta_child** is set to **false** when the bug appended. But if we add a new child Pods, when the iframe close, the function who is supposed to select the new child pods is excepting an Array and trace the error. 

I made a small video to explain the issue. The naming is not the same, but is to better understand it.

### Version

2.9.9

### Screenshots / Screencast

https://user-images.githubusercontent.com/3339248/205870751-e2517e22-61e6-4dd4-8b86-24de5b0644e7.mp4

**Comment by sc0ttkclark** [comment]
Fixed in #6945
