### ISSUE TITLE
pods-iframe-modal is undersized because Pods' default styles get overwritten by WordPress

### ISSUE THREAD

**Issue by oooh-boi** [pods-framework/pods#6983]
### Description

With the latest WP 6.1, the modal window by Pods is undersized due to default WP styles. 
![modal_undersized](https://user-images.githubusercontent.com/51370907/212545248-0c86604f-9828-42c8-af16-ede45907961c.png)
![styles-overwritten](https://user-images.githubusercontent.com/51370907/212545250-4d52a5a7-2a96-4991-b63f-27105afcb0a8.png)

### Version

2.9.10.2

### Testing Instructions

1. create 2 different custom post types
2. create a Relationship field on one of them, be sure Add New is enabled
3. try to trigger Add New in WP Admin post editor

### Possible Workaround

usage of "!important" rule of Pods' default styles

### Site Health Information

```text
All up to date, PHP 8.1
```

**Comment by sc0ttkclark** [comment]
Fixes in Pods 2.9.12
