### ISSUE TITLE
Custom taxonomy displaying error in PHP 8.0+

### ISSUE THREAD

**Issue by onnorokom69** [pods-framework/pods#6993]
### Description

Custom taxonomy displaying error in PHP 8.0+

### Version

2.9.11

### Testing Instructions

1. Go to the New post
2. Try to add value in custom field input area.

### Screenshots / Screencast

https://prnt.sc/bwro1pHSkzOw

### Site Health Information

`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: UTC
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 5
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /public_html
wordpress_size: 13.41 GB (14395270392 bytes)
uploads_path: /public_html/wp-content/uploads
uploads_size: 13.77 GB (14786490104 bytes)
themes_path:/public_html/wp-content/themes
themes_size: 25.29 MB (26520391 bytes)
plugins_path: /public_html/wp-content/plugins
plugins_size: 78.75 MB (82577188 bytes)
database_size: 1.90 GB (2035070205 bytes)
total_size: 29.17 GB (31325928280 bytes)

### wp-active-theme ###

name: evolve 
version: 4.3.2
author: Theme4Press
author_website: https://theme4press.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, post-thumbnails, title-tag, editor-style, custom-header, custom-background, post-formats, menus, customize-selective-refresh-widgets, widgets
theme_path: /public_html/wp-content/themes/famousb
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (15) ###

Ad Invalid Click Protector: version: 1.2.7, author: Saumya Majumder, Acnam Infotech, Auto-updates disabled
CIO Custom Fields Importer: version: 1.0.3, author: <a href="https://vipp.com.au/cio-custom-fields-importer/">VisualData</a>, Auto-updates disabled
Disable Comments: version: 2.4.3, author: WPDeveloper, Auto-updates disabled
Disable Gutenberg: version: 2.8.1, author: Jeff Starr, Auto-updates disabled
LiteSpeed Cache: version: 5.3.3, author: LiteSpeed Technologies, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.9.10.2, author: Pods Framework Team (latest version: 2.9.11.1), Auto-updates disabled
Post Views Counter: version: 1.3.12, author: Digital Factory, Auto-updates disabled
Rank Math SEO: version: 1.0.109, author: Rank Math, Auto-updates disabled
Rank Math SEO PRO: version: 3.0.28, author: Rank Math (latest version: 3.0.31), Auto-updates disabled
Salt Shaker: version: 1.3.2, author: Nagdy, Auto-updates disabled
String Locator: version: 2.6.1, author: InstaWP, Auto-updates disabled
Thumbnails: version: 1.1.5, author: Stefano Lissa, Auto-updates disabled
WPForms: version: 1.6.7, author: WPForms, Auto-updates disabled
WPForms Post Submissions: version: 1.0.4, author: WPForms, Auto-updates disabled
WP Report Post: version: 2.1.2, author: Alex Raven, Auto-updates disabled

### wp-plugins-inactive (6) ###

Advanced Database Cleaner PRO: version: 3.2.0, author: Younes JFR., Auto-updates disabled
Header Footer Code Manager: version: 1.1.32, author: 99robots, Auto-updates disabled
Quick Featured Images: version: 13.7.0, author: Kybernetik Services, Auto-updates disabled
WP All Import Pro: version: 4.7.1, author: Soflyy, Auto-updates disabled
WPCode Lite: version: 2.0.8.1, author: WPCode, Auto-updates disabled
WP Import Export Lite: version: 3.9.24, author: VJInfotech, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 1000M
max_effective_size: 1,000 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1160.81.1.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.4.33 64bit
php_sapi: litespeed
max_input_variables: 6000
time_limit: 1800
memory_limit: 20000M
max_input_time: 1500
upload_max_filesize: 1000M
php_post_max_size: 1000M
curl_version: 7.88.1 OpenSSL/1.1.1t
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.38-MariaDB
client_version: mysqlnd 7.4.33
max_allowed_packet: 268435456
max_connections: 150

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /public_html/wp-content
WP_PLUGIN_DIR: public_html/wp-content/plugins
WP_MEMORY_LIMIT: 20000M
WP_MAX_MEMORY_LIMIT: 18000M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wpforms ###

version: 1.6.7
pro: Jun 3, 2021 @ 8:12am
upload_dir: Writable
db_tables: wpai_wpforms_entries, wpai_wpforms_entry_fields, wpai_wpforms_entry_meta, wpai_wpforms_tasks_meta
total_forms: 1
total_entries: 1086
license_status: Invalid (valid)
license_location: constant

### pods ###

pods-server-software: LiteSpeed
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
pods-session-save-path: /var/cpanel/php/sessions/ea-php74
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 89.969M
pods-memory-current-usage-real: 18.637M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Auto-detect sessions (enable on first anonymous submission)
pods-can-use-sessions: Yes
pods-relationship-table-status: 1

`

**Comment by sc0ttkclark** [comment]
I'm not 100% sure what the PHP 8+ error is here, the fields just don't show. Do you have any other details like what PHP error logs show or if there are console logs in your browser from JS issues on the page?

**Comment by JoryHogeveen** [comment]
Closing topic due to inactivity. @onnorokom69  Feel free to reopen and reply to our comments.
