### ISSUE TITLE
Site crash when Pods and LearnDash are activated at the same time

### ISSUE THREAD

**Issue by mroverssi** [pods-framework/pods#6999]
After the last update of the plugin (Versión 2.9.11.1) one of my sites are crashing when Pods is active at the same time with LearnDash Plugin. I make some test and this only happen with this two plugins. 

Next you can see the details of the erros with Wordpress debug

Fatal error: Uncaught lucatume\DI52\NotFoundException: pods.rest-v1.repository => Error while making Tribe__REST__Messages_Interface $messages: nothing is bound to the 'Tribe__REST__Messages_Interface' id and it's not an existing or instantiable class. in /www/portalpymenauta_900/public/wp-content/plugins/sfwd-lms/vendor/lucatume/di52/src/Container.php:219 Stack trace: #0 /www/portalpymenauta_900/public/wp-content/plugins/sfwd-lms/vendor/lucatume/di52/src/Container.php(200): lucatume\DI52\Container->castThrown(Object(lucatume\DI52\NotFoundException), 'pods.rest-v1.re...') #1 /www/portalpymenauta_900/public/wp-content/plugins/sfwd-lms/vendor/lucatume/di52/src/Container.php(263): lucatume\DI52\Container->get('pods.rest-v1.re...') #2 /www/portalpymenauta_900/public/wp-content/plugins/pods/tribe-common/src/Tribe/Container.php(176): lucatume\DI52\Container->make('pods.rest-v1.re...') #3 /www/portalpymenauta_900/public/wp-content/plugins/pods/includes/general.php(4315): tribe('pods.rest-v1.re...') #4 /www/portalpymenauta_900/public/wp-content/plugins/pods/src/Pods/REST/V1/Service_Provider.php(47): pods_container('pods.rest-v1.re...') #5 /www/portalpymenauta_900/public/wp-content/plugins/sfwd-lms/vendor/lucatume/di52/src/Container.php(455): Pods\REST\V1\Service_Provider->register() #6 /www/portalpymenauta_900/public/wp-content/plugins/pods/tribe-common/src/Tribe/Container.php(288): lucatume\DI52\Container->register('Pods\\REST\\V1\\Se...') #7 /www/portalpymenauta_900/public/wp-content/plugins/pods/classes/PodsInit.php(2641): tribe_register_provider('Pods\\REST\\V1\\Se...') #8 /www/portalpymenauta_900/public/wp-includes/class-wp-hook.php(308): PodsInit->run('') #9 /www/portalpymenauta_900/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #10 /www/portalpymenauta_900/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #11 /www/portalpymenauta_900/public/wp-content/plugins/pods/tribe-common/src/Tribe/Main.php(107): do_action('tribe_common_lo...') #12 /www/portalpymenauta_900/public/wp-content/plugins/pods/classes/PodsInit.php(280): Tribe__Main->plugins_loaded() #13 /www/portalpymenauta_900/public/wp-includes/class-wp-hook.php(308): PodsInit->maybe_set_common_lib_info('') #14 /www/portalpymenauta_900/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #15 /www/portalpymenauta_900/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #16 /www/portalpymenauta_900/public/wp-settings.php(480): do_action('plugins_loaded') #17 /www/portalpymenauta_900/public/wp-config.php(88): require_once('/www/portalpyme...') #18 /www/portalpymenauta_900/public/wp-load.php(50): require_once('/www/portalpyme...') #19 /www/portalpymenauta_900/public/wp-admin/admin.php(34): require_once('/www/portalpyme...') #20 /www/portalpymenauta_900/public/wp-admin/plugins.php(10): require_once('/www/portalpyme...') #21 {main} thrown in /www/portalpymenauta_900/public/wp-content/plugins/sfwd-lms/vendor/lucatume/di52/src/Container.php on line 219

Notice: La función is_embed ha sido llamada de forma incorrecta. Las etiquetas de las consultas condicionales no funcionan antes de ejecutar la consulta. Haciéndolo antes, siempre devuelven falso. Por favor, ve [depuración en WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) para más información. (Este mensaje fue añadido en la versión 3.1.0). in /www/portalpymenauta_900/public/wp-includes/functions.php on line 5835

Notice: La función is_search ha sido llamada de forma incorrecta. Las etiquetas de las consultas condicionales no funcionan antes de ejecutar la consulta. Haciéndolo antes, siempre devuelven falso. Por favor, ve [depuración en WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) para más información. (Este mensaje fue añadido en la versión 3.1.0). in /www/portalpymenauta_900/public/wp-includes/functions.php on line

**Comment by sc0ttkclark** [comment]
I believe LearnDash fixed this quickly after their release to avoid issues with plugins like Pods, The Events Calendar, and Event Tickets.
