### ISSUE TITLE
Dot notation for Post Thumbnail title and Caption

### ISSUE THREAD

**Issue by pd-cm** [pods-framework/pods#7005]
### Problem to Solve

As found in this thread: https://wordpress.org/support/topic/image-title-and-description/

And this Slack post: https://podswp.slack.com/archives/C02SVLHQF/p1675292247157559

`{@post_thumbnail.post_content}`  and `{@post_thumbnail.post_excerpt}` both don't work

### Proposed Solution

Adding the dot notation for thumbnails would be nice.

### Possible Workaround

`{@ID,get_the_post_thumbnail_caption}` works. Hopefully `{@relationship_field.ID,get_the_post_thumbnail_caption}` also works.

**Comment by picthall** [comment]
Confirming that `{@relationship_field.ID,get_the_post_thumbnail_caption}` works for pulling the Caption.

**Comment by sc0ttkclark** [comment]
Fixed via fb56c5c5b241a63de085968950769d752b3d90f7

Also, check out what I added in 92241ac918e97c9f0eecad0d1321155e90b819cc

Lots more options for dot notation!

As of Pods 2.9.12, these will all be supported:

* Post thumbnail ID: `{@post_thumbnail.ID}` - Example: `1234`
* Post thumbnail title (new shorthand): `{@post_thumbnail.title}` - Example: `This is the image title`
* Post thumbnail description (new shorthand): `{@post_thumbnail.description}` - Example: `This is the description text`
* Post thumbnail caption (new shorthand): `{@post_thumbnail.caption}` - Example: `This is the caption text`
* Post thumbnail alt_text (new shorthand): `{@post_thumbnail.alt_text}` - Example: `This is the alt text`
* Post thumbnail extension (new): `{@post_thumbnail.extension}` - Example: `jpg`
* Post thumbnail mime_type (new): `{@post_thumbnail.mime_type}` - Example: `image/jpeg`
* Post thumbnail width (new): `{@post_thumbnail.width}` - Example: `100`
* Post thumbnail height (new): `{@post_thumbnail.height}` - Example: `200`
* Post thumbnail dimensions (new): `{@post_thumbnail.dimensions}` - Example: `100x200`
* Post thumbnail filesize (in bytes) (new): `{@post_thumbnail.filesize}` - Example: `12345`
* Post thumbnail image_meta.aperture (reference any image meta data) (new): `{@post_thumbnail.image_meta.aperture}` - Example: `0`
* Post thumbnail filename (new): `{@post_thumbnail.filename}` - Example: `my-image.jpg`
* Post thumbnail post_type: `{@post_thumbnail.post_type}` - Example: `attachment`
* Post thumbnail any other object fields: `{@post_thumbnail.whatever_object_field_here}`
* Post thumbnail any other custom fields: `{@post_thumbnail.whatever_meta_key_here}`
