### ISSUE TITLE
Updating 2.7.31 -> Latest Version - Edit Pod has missing fields

### ISSUE THREAD

**Issue by techprogrammer** [pods-framework/pods#7007]
### Description

Been using Pods 2.7.31. Tried to upgrade to 2.9.11.1 and notice issues concerning specific fields.  Isolating it further, we see if you try to Edit Pods on specific Pod - Custom Taxonomy - Table - it shows only 1 field, not 5 fields that exist

Back testing: This issue happens starting with Pods 2.8.

### Version

2.7.31

### Testing Instructions

Website with Pods 2.7.31 working fine.
Upgrade to Pods 2.8
Edit Pods on Category table
Notice only 1 field shows up even though it has 5

### Screenshots / Screencast

![messed up](https://user-images.githubusercontent.com/5952458/217164107-5acb7aef-fbd5-4d86-b2e7-adc8d883f676.PNG)
![messed up-2](https://user-images.githubusercontent.com/5952458/217164112-ba98cf6d-d60e-44fe-936b-4b1e295f3ba2.PNG)
![category fields](https://user-images.githubusercontent.com/5952458/217164659-d639567b-75b7-4f43-aea2-d24d0392fd3f.PNG)

### Possible Workaround

stay with 2.7.31

### Pods Package

```json
{"meta":{"version":"2.7.31","build":1675751043},"pods":{"418":{"id":418,"name":"categories","label":"Categories","description":"","type":"taxonomy","storage":"table","object":"","alias":"","fields":{"category_id":{"id":419,"name":"category_id","label":"Category ID *","description":"","help":"","class":"","type":"number","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"1","number_format":"9999.99","number_decimals":"0","number_max_length":"12","wysiwyg_max_length":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","number_repeatable":0,"number_format_type":"number","number_format_soft":0,"number_step":1,"number_min":0,"number_max":100,"number_placeholder":""},"related_category":{"id":420,"name":"related_category","label":"Related Category","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"pod","pick_val":"categories","sister_id":"","required":"0","unique":"0","wysiwyg_max_length":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_limit":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":"","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_allow_add_new":1,"pick_taggable":0,"pick_show_icon":1,"pick_show_edit_link":1,"pick_show_view_link":1,"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_user_role":"","pick_post_status":"publish"},"alternate_url":{"id":3812,"name":"alternate_url","label":"Alternate URL","description":"PG Partner URL to display if category contains no active deals","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","website_format":"normal","website_max_length":"255","website_html5":"0","wysiwyg_max_length":"0","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value":"","default_value_parameter":"","capability_allowed":"","website_repeatable":0,"website_allow_port":0,"website_clickable":0,"website_new_window":0,"website_placeholder":""},"hide_shipping":{"id":7559,"name":"hide_shipping","label":"Hide Shipping","description":"Hide \"Free Shipping\" in deal titles?","help":"","class":"","type":"boolean","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","wysiwyg_max_length":"0","boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","default_value":"No","admin_only":"0","restrict_capability":"0","css_class_name":"","input_helper":"","default_value_parameter":"","capability_allowed":""},"active":{"id":21087,"name":"active","label":"Active *","description":"","help":"","class":"","type":"boolean","weight":4,"pick_object":"","pick_val":"","sister_id":"","pick_custom":"","required":"0","unique":"0","wysiwyg_max_length":"0","boolean_format_type":"checkbox","boolean_yes_label":"Yes","boolean_no_label":"No","input_helper":"","default_value":"Yes","default_value_parameter":"","admin_only":"0","restrict_capability":"0","capability_allowed":""}},"show_in_menu":1,"label_singular":"category","public":"1","show_ui":"1","show_in_nav_menus":"1","show_tagcloud":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","query_var":"0","built_in_post_types_post":"0","built_in_post_types_page":"0","built_in_post_types_deals":"1","sort":"0","show_admin_column":"0","built_in_post_types_safecss":"0","built_in_post_types_feedback":"0","built_in_post_types_attachment":"0","label_add_new":"","label_add_new_item":"","label_new_item":"","label_edit":"","label_edit_item":"","label_update_item":"","label_view":"","label_view_item":"","label_all_items":"","label_search_items":"","label_not_found":"","label_popular_items":"","label_separate_items_with_commas":"","label_add_or_remove_items":"","label_choose_from_the_most_used":"","menu_name":"","menu_icon":"","label_parent_item_colon":"","label_parent":"","rewrite_custom_slug":"","update_count_callback":""}}}
```

**Comment by sc0ttkclark** [comment]
Seems to be resolved when you run the Repair tool as per https://wordpress.org/support/topic/updating-2-7-31-latest-version-edit-pod-has-missing-fields/#post-16463605

We'll need to go over and see if there are any issues in the first 2.8 upgrade process when editing that pod. Also, if we can detect there may be fields not showing on the screen, perhaps we can show a notice on that screen with a link to run the repair for that specific pod.

**Comment by techprogrammer** [comment]
Output when selecting repair

![Capture](https://user-images.githubusercontent.com/5952458/218330384-d99fc18e-bc0b-40dd-99cb-a563dc27bfa5.PNG)

**Comment by sc0ttkclark** [comment]
Thanks, this helps us further identify where it may be going wrong in the upgrade process for this specific case.

**Comment by techprogrammer** [comment]
I reference the category pods in another pod and notice there is nothing in the Related To field. Works ok with 2.7.31 though.  Latest pods wants something in Related To field.
I tried changing Related To from blank to Categories (categories) and noticed it caused issues reading this value from either pods version.

![oldpods](https://user-images.githubusercontent.com/5952458/218902396-21c4af5c-c316-41f6-8596-fae3ba6b95b8.PNG)

**Comment by sc0ttkclark** [comment]
I'll load up your package and see if I can find out anything there

**Comment by techprogrammer** [comment]
Might be useful:
Working 2.7.31 json data for Deal Pod:
					"pick_object": "pod",
					"pick_val": "categories",


Messed up staging server json data after trying to set Related to:

					"pick_object": "taxonomy",
					"pick_val": "categories",

If I import the working pods data onto my messed up staging server, should it fix the issue I caused changing Related To: ?

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/74ba85d6a98540d61fc9aa011b5e4775d4612d9a and https://github.com/pods-framework/pods/commit/04bf8acc7f86bfc85d53b4e2c933e7fb3f24e8ea plus the work done in Pods 2.9.12 which addresses a more comprehensive upgrade process matching what the repair tool does.
