### ISSUE TITLE
WordPress 6.2 beta 2;  Deprecated: Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in .../wp-content/plugins/pods/classes/PodsMeta.php on line 575 

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7014]
### Description

If enabling Pods on test site running WordPress **6.2 beta 2**, some columns in the post edit screen returns an error. Screenshot:

![image](https://user-images.githubusercontent.com/17141205/219617685-356a8e83-dd55-4563-9cdf-c7be62865689.png)

The test site has WP_DEBUG enabled.

Now, I don't at all expect Pods to be working with a beta of WP 6.2, so this is just meant as a head up.

### Version

Version 2.9.11.1

**Comment by sc0ttkclark** [comment]
Fixed via 31a45ebe3cbdc70d1af878ed09a35a601c6d72bb
