### ISSUE TITLE
Wrong class names in class_exists() check at top of file

### ISSUE THREAD

**Issue by mwf1** [pods-framework/pods#7072]
### Description

The class_exists() check at the top of these files is checking for the legacy class name, prior to the auto template plugin being incorporated into the main Pods plugin.

This may not be causing any problems (I did not experience any that I could trace back to this) but looks wrong. Potentially, these calls may not be needed anymore in the first place.

- wp-content\plugins\pods\components\Templates\includes\auto-template\Pods_Templates_Auto_Template_Front_End.php
- wp-content\plugins\pods\components\Templates\includes\auto-template\Pods_Templates_Auto_Template_Settings.php

<?php
if ( class_exists( '**Pods_PFAT_Frontend**' ) ) {
	return;
}

/**
 * Class Pods_Templates_Auto_Template_Front_End
 *
 * Replaces Pods_PFAT_Frontend
 */
class **Pods_Templates_Auto_Template_Front_End** {

<?php
if ( class_exists( 'Pods_PFAT' ) ) {
	return;
}

/**
 * Class **Pods_Templates_Auto_Template_Settings**
 *
 * This class replaced Pods_PFAT class
 *
 * @since 2.5.5
 */
class **Pods_Templates_Auto_Template_Settings** {

### Version

2.9.13

### Testing Instructions

This may not be causing any problems (I did not experience any that I could trace back to this) but looks wrong.

To check, open the files and inspect the first 20 lines of code.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/9c84ae7af1df8b3cae43fc44140a9aa9e6e7ecf8
