### ISSUE TITLE
Undefined property: stdClass::$item_id in fields\file.php

### ISSUE THREAD

**Issue by mpiasta-ca** [pods-framework/pods#7074]
### Description

Using latest Pods plugin version, on latest WordPress version.

A bug is being thrown when uploading an image using the "File / Image / Video" field while using "Plupload" option.

The ajax request which is fired when uploading an image does not have any parameter called `$item_id`.

**PHP Error Log:**

```
[30-Apr-2023 20:36:14 UTC] PHP Warning: Undefined property: stdClass::$item_id in \wp-content\plugins\pods\classes\fields\file.php on line 1189

[30-Apr-2023 20:36:14 UTC] PHP Warning: Undefined property: stdClass::$item_id in \wp-content\plugins\pods\classes\fields\file.php on line 1244
```

There is a `$post_id` parameter, maybe this is what was supposed to be used instead.

This bug could be causing "Magic Tags" to not work for setting upload Custom Folder Path:

https://wordpress.org/support/topic/magic-tags-not-working-in-custom-upload-directory/

### Version

Latest

### Testing Instructions

1. Create a Pod custom post type
2. Add field: **File / Image / Video**
3. Open field settings
4. Click tab: **File / Image / Video Options**
6. Select: **File Uploader > Upload only (Plupload)**
7. Also, in case it is related to this settings, set max. images allowed to "Single" (instead of Multiple images).
8. Save
9. Via admin menu, open your Pod > Add New.
10. Upload an image with your Plupload field (while monitoring the Chrome Dev Tools > Network requests).
11. Check the AJAX request parameters triggered while the image was being uploaded: the Ajax request does not have any parameter called "item_id" (but there is a parameter called "post_id").
12. Check PHP Error Log.

### Possible Workaround

In my installation, I have temporarily added this code on line 1053 of `pods\classes\fields\file.php`:

```
		if (!isset($params->item_id) && isset($params->post_id)) {
			$params->item_id = (int) $params->post_id;
		}
```

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/09ccb6ee01d8b2f9c5d8128c1ebdfc15f8f08773

**Comment by navthink13** [comment]
> 

In my case this fixed the issue in back-office, but not in front
is the ajax function different for front end form ?

**Comment by navthink13** [comment]
In fact in my case the front-end pods form ( shop_order)  is called in the template from a custom page ( id=13)
In this case $params->id was well corresponding to order number
but $param->post_id was 13
With this quick fix in line 1060

```php
if (isset($params->id) ) {
$params->post_id = (int) $params->id; 
}
``` 
it fixed the issue and works for me
but i am not 100% of the other potential consequences :)
