### ISSUE TITLE
PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in classes/Pods.php

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#7075]
### Description

https://wordpress.org/support/topic/tons-of-php-deprecated-strlen-messages-in-error-log-under-php-8-x/

### Version

2.9.13

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/7076
