### ISSUE TITLE
Link field type

### ISSUE THREAD

**Issue by nicholaswyoung** [pods-framework/pods#708]
Drupal has an awesome field type for Links. [This module](http://drupal.org/project/link) allows me to create a `purchase_links` post type, and fill it with any number of links, avoiding the need to create a seperate field for each link (i.e. `cd_baby_link`, `amazon_link`, etc.)

Basically, each link field includes a HREF and the link text. It's pretty basic, but very powerful. I would love to see Pods adopt something similar.

**Comment by sc0ttkclark** [comment]
This is now in Pods 2.7!

**Comment by JoryHogeveen** [comment]
Also for you @nicholaswyoung 
See my last comment at https://github.com/pods-framework/pods/issues/2268

Or just the direct link: https://github.com/JoryHogeveen/pods-link-field
