### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter 

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7080]
### Description

When activation Pods 3.0.0-b1 on my PHP 8.1 installation, this deprecation warning is shown:

`
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /removed/wp-content/plugins/pods/sql/upgrade/PodsUpgrade.php on line 188`

### Version

3.0.0-b1

**Comment by oldrup** [comment]
Another deprecation warning on strlen:
![image](https://github.com/pods-framework/pods/assets/17141205/9c5ba5ea-035a-4e9e-bd7e-40d4a3fd359c)

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/6ecd43449b7446eb2670fb939e5cf7acba255390
