### ISSUE TITLE
Field Type * There was an error rendering the field.

### ISSUE THREAD

**Issue by anirudh7** [pods-framework/pods#7083]
![image](https://github.com/pods-framework/pods/assets/5333996/9cd9cafd-83f0-4c38-8ff6-9702398ba142)

I found few of them with the day issue, hope is solved soon

[https://wordpress.org/support/topic/there-was-an-error-rendering-the-field-since-update-to-2-9-14/](https://wordpress.org/support/topic/there-was-an-error-rendering-the-field-since-update-to-2-9-14/)

**Comment by rory-ferguson** [comment]
Thanks you
