### ISSUE TITLE
Pods auto-repair changed the storage type from table to meta

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#7087]
### Description

When I clicked a pod, it ran the auto-repair and changed its storage type from table to meta, but it should be table type.

### Version

2.9.15

### Screenshots / Screencast

Before the auto-repair
![Web capture_2-6-2023_155116_uclanip org uk](https://github.com/pods-framework/pods/assets/17201482/13311cd4-8733-4c8b-9b77-7161e309d5d1)
The auto-repair
![Web capture_2-6-2023_155645_uclanip org uk](https://github.com/pods-framework/pods/assets/17201482/edcc4426-f0bf-479c-a32f-8ed041dc8fce)
After the auto-repair
![Web capture_2-6-2023_154726_uclanip org uk](https://github.com/pods-framework/pods/assets/17201482/3544a8ff-2352-4093-aeb7-6f95cce9ea55)

**Comment by sc0ttkclark** [comment]
This was fixed in Pods 2.9.16 and it will attempt to automatically fix itself.

Did you backup your DB before updating to 2.9.15?
