### ISSUE TITLE
A new "old" error reappeared (issue 6971)

### ISSUE THREAD

**Issue by knubew** [pods-framework/pods#7089]
### Description

The pod versions 2.9.14 and 2.9.15 cause errors in my application that do not appear in version 2.9.13.

Basically, an old error has reappeared, which I had already described in great detail at [https://github.com/pods-framework/pods/issues/6971](https://github.com/pods-framework/pods/issues/6971).

**Please read the following paragraph in the error description:**
**_Then I log out (as admin) and log in as author with the login data of an organizer and call up an event ("Event") for editing. However, NO groups are displayed.
07_AUTHOR-View__Event_with_groups_ERROR__AFTER_Pods_update_**

Unfortunately, this time I can't fix the error by deleting the pods cache and the following error message appears several times in the Wordpress debug.log:

[05-Jun-2023 14:51:02 UTC] PHP Warning: foreach() argument must be of type array|object, bool given in /var/www/vhosts/my.domain.com/httpdocs/portal/wp- admin/includes/plugin.php on line 1929

### Version

2.9.14 / 2.9.15

**Comment by sc0ttkclark** [comment]
Please check on Pods 2.9.19, there was a cache-related issue that was resolved and could have caused a similar problem to this.

**Comment by knubew** [comment]
> Please check on Pods 2.9.19, there was a cache-related issue that was resolved and could have caused a similar problem to this.

Okay, I'll give 2.9.19 a try. Thank you.
If the error should also occur in version 2.9.19, I will report again.
