### ISSUE TITLE
3+ WYSIWYG Field Bugs - [1] Shortcode, [2] Adding & Not Adding "<p>" tags, [3] Trim not working...

### ISSUE THREAD

**Issue by dbareis** [pods-framework/pods#7091]
Using a WYSIGYG Field with these selected on PODS v2.9.15:

- Trim extra whitespace
- Enable oEmbed
- Allow Shortcodes

**[1]** First of all shortcodes don't get replaced.  I obviously expect them to.

**[2]** Secondly PODS decides to sometimes add "&lt;p&gt;" &amp; "&lt;/p&gt;" tags and sometimes not to do so.  2 examples follow:

```
MyDump(type: string:Len=257): $GeneralComments
'<p>A hardy scrambler which can be pruned which encourages increased flowering. Grow under established trees. Excellent habitat plant.  Similar to the Blackberry, but not as aggressive.  Birds like the fruit.  Frost tolerant.</p><p>&nbsp;</p><p>&nbsp;</p>'
```
and:

```
MyDump(type: string:Len=271): $GeneralComments
'A hardy scrambler which can be pruned which encourages increased flowering. Grow under established trees. Excellent habitat plant.  Similar to the Blackberry, but not as aggressive.  Birds like the fruit.  Frost tolerant.

second para

3rd para           

&nbsp;

&nbsp;'     

```
**It is very hard to process (to display correctly) with these inconsistencies.**

**[3]** Note that the trim whitespace option also isn't working in either or the above examples

I've also tried with "autop" on but that has its own inconsistencies.

**Comment by sc0ttkclark** [comment]
1. Shortcodes seem to be working fine right now, I haven't been able to reproduce the problem there.
2. I'm not sure what the `MyDump` part of your examples is from, but TinyMCE does adjust the HTML when you switch between Text and Visual tabs. The JS-based TinyMCE editors that we now use does not support remembering the tab you were last on per-editor when refreshing the page. So if you entered HTML into the Text tab, it will automatically be adjusted by TinyMCE.
3. Trim whitespace does appear to be working fine however I added some logic in Pods 3.0 to trim empty `<p>` tags as well as `<p>&nbsp;</p>` and `&nbsp;` from the start/end of HTML strings that have trimming enabled for the associated field.
