### ISSUE TITLE
PHP Notice:  Undefined variable: validate in /home/wcipporg/public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 5166,5168, 5169

### ISSUE THREAD

**Issue by dbareis** [pods-framework/pods#7100]
### Description

As per the PHP logged message "**Undefined variable: validate** in /home/wcipporg/public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 5166".

### Version

2.9.16

### Testing Instructions

Don't know, appears in PHP log

**Comment by sc0ttkclark** [comment]
Fixed via 48e55a16b73388e6814668ab4593237dc1fb2a47
