### ISSUE TITLE
Spelling error in french translation

### ISSUE THREAD

**Issue by skotperez** [pods-framework/pods#7103]
### Description

The string "Form submitted successfully" translated as "Formulaire enregistré avec succes" must be "Formulaire enregistré avec succès".

This string is in the file pods-fr_FR.po.

### Version

2.9.16

**Comment by JoryHogeveen** [comment]
Hi @skotperez 

Our translations are provided by the WordPress community, you can contribute here: https://translate.wordpress.org/projects/wp-plugins/pods/

Cheers, Jory
