### ISSUE TITLE
Conditional Logic has no effect in 3.0 Beta 1

### ISSUE THREAD

**Issue by mrmatteastwood** [pods-framework/pods#7104]
### Description

When creating a Relationship field as a dropdown with a list of custom values, conditional logic tied to that field has no effect. I'm trying this with fields in different groups, so that might have a bearing on the issue.

I'm expecting the field to disappear or appear on the CPT depending on what I choose in another field. However, it 
just sits there doing nothing.

### Version

3.0 Beta 1

### Testing Instructions

1. Make a new post type
2. Add a few field groups to it
3. In the first field group, make a Relationship field called "Options", Related Type: simple (custom list). Add a few custom options, e.g. "Option A".
4. In another field group, make a Text field.
5. Enable conditional logic on that field
6. Set it to show if the "Options" field equals one of the options, e.g. "Option A"

### Screenshots / Screencast

https://youtu.be/TXFQHYA8_7I

### Site Health Information

```text
Affected build: https://hnr2023.2sinn.it/
```

**Comment by sc0ttkclark** [comment]
Fixed via ada54e2f7cf94da79ea681373bd336528a283a4b and 955a4a216d051c13cb3979a078381a5e8bd6246c
