### ISSUE TITLE
Relationship field popup edit screen partially obscured in WP 6.3

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#7131]
### Description

Working on an install using WP 6.3 I've noticed that the popup editor for relationship fields is partially obsucured. The same version of Pods on version 6.2.2 of WP does not show the same behaviour.

In my WP 6.3 set up there is an additional `<div>` wrapped around the popup iframe that isn't showing on my WP 6.2.2 set up.

Editing the HTML in webdev tools in the WP 6.3 set up to remove the additional `<div>` fixes the display problem.

Relationship field settings are identical in both installs.

### Version

2.9.19

### Screenshots / Screencast

Screencap of issue in WP 6.3 with iframe nested inside extra`<div>`, highlighted in dev tools:

![repeat-edit-popup-issue-wp6 3](https://github.com/pods-framework/pods/assets/1478964/eb861d27-ad5a-41e6-835e-435c22121033)

Screencap of setup in WP 6.2.2 with no additional `div` wrapped around the iframe:

![repeat-edit-popup-WP6 2 2](https://github.com/pods-framework/pods/assets/1478964/4781503d-13fa-4262-b92e-20e656745cb0)

Removing extra `<div>` in webdev tools for WP 6.3 setup:

![image](https://github.com/pods-framework/pods/assets/1478964/d48952f9-ea12-4caf-bfea-2eecfaa9c12e)

iframe with div removed:

![image](https://github.com/pods-framework/pods/assets/1478964/9010afef-426e-4403-a6f5-a4e691af94a3)

**Comment by CloundNine** [comment]
I am seeing the same.  used WP Downgrade to roll back to 6.2.2 and my site is back working.  Following for updates on solution.

**Comment by JoryHogeveen** [comment]
As Scott mentioned, it's fixed in 3.0: https://wordpress.org/support/topic/relationship-field-add-new-window-squished/#post-17025647
