### ISSUE TITLE
Error in redirecting after pods deletion

### ISSUE THREAD

**Issue by paoloimpelluso** [pods-framework/pods#7137]
### Description

Hi folks,
if WP if installed in subdirectory (for example a staging environment like https://demo.example.com/site.com/) there's a problem when deleting a POD. After deletion the browser is redirected to root server, like: https://demo.example.com/wp-admin/admin.php?page=pods&deleted=1 and subdirectory **site.com** is missing.

### Version

2.9.19

### Testing Instructions

install WP on a subdirectory like https://demo.example.com/site.com
create a pod
go to edit pod
click on "delete pod" button

**Comment by JoryHogeveen** [comment]
https://github.com/pods-framework/pods/blob/2.9.19/ui/js/dfv/src/admin/edit-pod/postbox.js#L39-L40

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/7162
