### ISSUE TITLE
Auto templates are not auto translated anymore

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#7141]
Not sure when this broke but with the recent releases and the current state of 3.0 the auto templates are not auto translated anymore.
Might first thought would be that this is since the introduction of `pods_get_instance`:  https://github.com/pods-framework/pods/commit/71e916088e7535b17025e6cdc996b4a3dff81609

Forum topic: https://wordpress.org/support/topic/pod-single-post-templates-not-translating-with-wpml/

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/7142
