### ISSUE TITLE
PodsMigrate()->save() sometimes returns URL from GUID, sometimes returns path named $url.

### ISSUE THREAD

**Issue by pd-cm** [pods-framework/pods#7144]
### Description

See https://wordpress.org/support/topic/export-url-gets-incorrect-path/

> See [PodsUI.php:2239](https://github.com/pods-framework/pods/blob/a20d6392eea3cc1fa181953e215cc1c262b15100/classes/PodsUI.php#L2238).

> The error in the file URL is because [PodsMigrate()->save() on lines 883 to 885](https://github.com/pods-framework/pods/blob/a20d6392eea3cc1fa181953e215cc1c262b15100/classes/PodsMigrate.php#L883-L885) sometimes returns a URL from GUID and sometimes returns an URL which is actually an absolute file path.

> Ideally the first would use [wp_get_attachment_url()](https://developer.wordpress.org/reference/functions/wp_get_attachment_url/), not a GUID, and the second would use [wp_get_upload_dir()](https://developer.wordpress.org/reference/functions/wp_get_upload_dir/) to replace `basedir` with `baseurl`.

### Version

2.9.19

### Testing Instructions

Like Jory, I've also never seen this `.txt` exporter used.
I found the errant message by searching for the string and tracing back to the PodsMigrate class returned by `$migrate = pods_migrate( $type, $delimiter, $data );`

### Screenshots / Screencast

Use `wp_get_attachment_url()` and `wp_get_upload_dir()`

e.g., 

https://github.com/pods-framework/pods/blob/a20d6392eea3cc1fa181953e215cc1c262b15100/classes/PodsMigrate.php#L883-L885

...should likely be:

```php
	$url = wp_get_attachment_url( $attachment_id );
} else {
	$upload_dir = wp_get_upload_dir();
	$url = str_replace( $upload_dir['basedir'], $upload_dir['baseurl'], $new_file );
```

**Comment by markryder** [comment]
Hi Jory & PD
Sorry to confuse you, I had installed a plug in 'Advance Pods Export CSV' and had not realised that the export I was referring to was coming from that rather than standard pods. I could see it was using migrate, but was not clever enough to work out the fix.
Having tried your fix, it works perfectly now, so than k you very much for taking the time to help!!

**Comment by JoryHogeveen** [comment]
Hi @markryder 
Thanks for your follow-up on that and glad to hear it's solved.
Closing issue here.
Cheers, Jory
