### ISSUE TITLE
PHP 8+ deprecated issues

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#7145]
- [ ] Implicit float to int conversion: https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string#array-keys
- [ ] Dynamic properties
- [x] Automatic conversion of false to array is deprecated in \pods\components\Templates\includes\auto-template\Pods_Templates_Auto_Template_Settings.php on line 413

Locations (to be completed):
- https://github.com/pods-framework/pods/blob/main/components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php#L58-L81

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Can you confirm the issues here are resolved or need to still be worked on? I had trouble following the file/line numbers referenced here

**Comment by JoryHogeveen** [comment]
@sc0ttkclark The issues I've found so far are fixed in this PR. I can always create a new one if needed!

**Comment by sc0ttkclark** [comment]
Ok great, thanks!
