### ISSUE TITLE
A few Pods 3.0.1 and PHP 8.1 Deprecated warnings (functions-view_template.php on line 174, Pods.php on line 741)

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7171]
### Description

On a test site, when updating to PHP 8.1, and with WP_DEBUN on, I get these deprecation warnings:
`Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/removed/wp-content/plugins/pods/components/Templates/includes/functions-view_template.php on line 174`

and 

`Deprecated : strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/removed/wp-content/plugins/pods/classes/Pods.php on line 741`

![image](https://github.com/pods-framework/pods/assets/17141205/a38fc897-a8cf-4167-91ca-312b488ed27f)

Is that something you can reproduce?

I'm using Pods Templates with MagicTags™. Please tell me, if I should put some effort into pinpointing exactly what query triggers the warning.

![image](https://github.com/pods-framework/pods/assets/17141205/60c40b8c-af14-440c-bf9c-cf2c415fa0aa)

### Version

3.0.1

### Possible Workaround

Downgrading to PHP 8.0 gets rid of the warnings.

**Comment by sc0ttkclark** [comment]
Will tackle this along with the strlen() issues in pick.php (line 2959) - https://wordpress.org/support/topic/tons-of-php-deprecated-strlen-messages-in-error-log-under-php-8-x/#post-17063480

**Comment by sc0ttkclark** [comment]
Fixed via c30862a0c006e2c708cb2ad1a997d73e06dcfef7
