### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in wysiwyg.php on line 241

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7182]
### Description

Testing Pods 3.0.3 with PHP 8.1 and WP 6.3; adding a post with a custom wysiwyg field, I get this deprecation warning.

` Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/removed/wp-content/plugins/pods/classes/fields/wysiwyg.php on line 241
`

The WYSIWYG field is using the **TinyMCE editor** and **Trim extra whitespace before/after contents** option; that might be relevant for the warning (screenshot below)

### Version

3.0.3

### Screenshots / Screencast

Screenshot of deprecation warning:

![image](https://github.com/pods-framework/pods/assets/17141205/b079f25f-55d8-4383-9867-0733815e96e0)

Screenshot of field settings:
![image](https://github.com/pods-framework/pods/assets/17141205/f352b207-49f0-4d3d-aa93-f42d3d101969)

![image](https://github.com/pods-framework/pods/assets/17141205/8c9b046b-1d4e-46b7-b60c-bbd0c1565d7a)

### Possible Workaround

It's a deprecation warning, so turning WP_DEBUG off turns off the warning. 

### Site Health Information

```text
Please reach out to me if that applies.
```

### Pods Package

```json
Please notify me if that applies.
```

**Comment by oldrup** [comment]
Additional info; warning only appears _when adding a new _, not when editing an existing one.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/679a2ddbe7aa7572c0374123439e1753972971f6
