### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in PodsUpgrade.php on line 188

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7190]
### Description

Activating Pods 3.0.4 on a fresh install with PHP 8.1 and WP_DEBUG enabled, results in the following deprecation warning in the admin dashboard:

`Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/removed/wp-content/plugins/pods/sql/upgrade/PodsUpgrade.php on line 188`

### Version

3.0.4

### Testing Instructions

1. install a new WordPress website (may be multisite)
2. ensure running PHP 8.1
3. enable WP_DEBUG
4. install Pods 3.0.4
5. enable Pods

### Possible Workaround

only occurs after fresh install, so problem "goes away" by itself.

### Site Health Information

```text
on request
```

### Pods Package

```json
on request
```

**Comment by sc0ttkclark** [comment]
Fixed via b193fd00ca7f38a925048174971a138b91ce1332
