### ISSUE TITLE
Function tribe was called incorrectly. tribe() is no longer included in Pods Framework directly. Please use pods_container() instead.

### ISSUE THREAD

**Issue by silasantosh** [pods-framework/pods#7194]
### Description

After updating to PODS to the latest version 3.0.5, my website got crashed.
Please help
![image](https://github.com/pods-framework/pods/assets/4695174/707de045-da04-4b0a-92a0-fa887780df00)

### Version

3.0.5

### Screenshots / Screencast

![image](https://github.com/pods-framework/pods/assets/4695174/50b8f575-7b9a-4393-a4ce-4ae8955f08c1)

**Comment by sc0ttkclark** [comment]
@silasantosh Can you confirm this was fixed in Pods 3.0.6?
