### ISSUE TITLE
Pods Item List block; unfinished SQL statements (still typing) crashes block, no immediate fix.

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7207]
### Description

I'm transitioning from Pods shortcodes to the Gutenberg blocks, enjoying how I can actually see the content within the editor.

However, the rendered block in the editor “crashes” when the parameters for the block aren't completely valid. That is a problem, as the block editor attempts to render the Pods block output while still typing the parameters.

Screenshot 1 - the Pods Item List returns some items, fine.

![image](https://github.com/pods-framework/pods/assets/17141205/d9732fbd-6386-4c0f-88cf-079a541fbe31)

Screenshot 2 - after starting to type `t.post_title ASC` in the `Order By`

![image](https://github.com/pods-framework/pods/assets/17141205/04eb9703-bb9d-45d8-ad50-160d29fe8261)

I think that affects all the SQL parameters but I specifically experienced it on the _limit, where and order_ by.

The only resort is to exit the editor and cancel saving.

Is that something you can reproduce?

### Version

3.0.7

### Possible Workaround

Can be worked around by coping and pasting in a finished _where_ or _order by_ clause from another text editor.

**Comment by oldrup** [comment]
One way to mitigate the issue, is to create a pattern of a working Pods block. Then you can insert the pattern, and editing say, short strings in the where clause can be done faster than the editor refreshes.

![image](https://github.com/pods-framework/pods/assets/17141205/a7d7ea20-e5e5-4463-8160-664aced64b8b)

**Comment by sc0ttkclark** [comment]
Good point here, we'll add a better try/catch for the SQL error and avoid this problem.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/commit/9aba67bad2c9218fd2e1fdce5a508b8d95a8d54e

**Comment by sc0ttkclark** [comment]
I wasn't able to get the error to happen itself, but the code I added will catch any other remaining errors that might be happening.

I've made additional adjustments and the errors appear much better now too:

**When not using WP_DEBUG:**

<img width="736" alt="Screenshot 2023-10-20 at 11 49 23 AM" src="https://github.com/pods-framework/pods/assets/709662/92b8de1f-fe3a-45a6-964f-15603393adb9">

**When using WP_DEBUG:**

<img width="740" alt="Screenshot 2023-10-20 at 11 51 12 AM" src="https://github.com/pods-framework/pods/assets/709662/ddb131ee-7694-4a2c-a573-87843cfba5f6">
