### ISSUE TITLE
php 8.3 deprecation error

### ISSUE THREAD

**Issue by netlas** [pods-framework/pods#7225]
### Description

PHP 8.3 has been released now and I get this deprecation error:
Deprecated: Calling get_class() without arguments is deprecated in pods/classes/PodsForm.php on line 285 and 287.

So far that is the only deprecation error I have stumbled upon. And from the comments in the source code this is old depricated code in the pods plugin itself, also says it's suppose to be deleted for pods v3, which it obviouslty hasnt. Maybe time to trim of some old depricated code?

### Version

3.0.8

### Testing Instructions

Errors comes when editing a post in wordpress administration which has pods fields attached to it.

### Possible Workaround

Replace `get_class()` on row 285 and 287 in PodsForm.php with `static::class`

**Comment by sc0ttkclark** [comment]
Thanks for the heads up, if you see any other issues -- just let me know and I can get those sorted in the next release. Appreciate your help here!
