### ISSUE TITLE
Add copy icon to field slugs to make it easier to copy/paste

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#7237]
### Problem to Solve

When I'm looking at a list of custom fields, it would be useful to have a copy icon next to the field slug that appears on hover. At the moment the only way to copy the field slug is to click the field and copy it from the field edit screen.

### Proposed Solution

Add a copy icon next to the field slug that appears on hover

### Examples Elsewhere

This is what ACF looks like when you hover on a field:
![Screenshot 2023-12-19 at 10 06 12](https://github.com/pods-framework/pods/assets/413327/632fa509-35c6-4cb6-b96e-dcf9f152d0ef)

**Comment by heybran** [comment]
If no one's on this task yet, I can take a look after new year and see if I can tackle this.

**Comment by heybran** [comment]
@sc0ttkclark @JoryHogeveen 

Once you see this, what do you think? Maybe to keep consistent with the UI, I should replace svg with text `Copy`?
And while doing this update, I noticed that the button texts are really small, and I have relatively good eye sight, not sure if will bring trouble to other people though? Should we bump up the font size on the UI?

https://github.com/pods-framework/pods/assets/75633537/3764c71d-593d-4fb2-98ae-f1e8af89ffff
