### ISSUE TITLE
 Make Pods storing revisions of Post Meta in WordPress 6.4+

### ISSUE THREAD

**Issue by datverse** [pods-framework/pods#7265]
### Problem to Solve

Hi, 
Can you make Pods storing revisions of Post Meta in WordPress 6.4+
This is helpful for us.
Thanks ❤️

### Proposed Solution

Ref Link from WordPress: 
https://make.wordpress.org/core/2023/10/24/framework-for-storing-revisions-of-post-meta-in-6-4/

**Comment by sc0ttkclark** [comment]
Yeah sure, Pods 3.1.5 adds this support for meta-based post types :)

It'll be released tomorrow and you can enable Meta revisions for a whole pod or per field.

* All fields in pod: Edit the pod and go to the Advanced tab > Track all field value changes in revisions (revisions must be enabled for that post type)
* Per field: Edit the field and go to the Advanced tab > Track field value changes in revisions (revisions must be enabled for that post type)

**Comment by datverse** [comment]
@sc0ttkclark Thanks and Love you all ❤️❤️❤️
