### ISSUE TITLE
Fatal error: array_combine() with WP 6.5 beta 3

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#7266]
### Description

Hey

When upgrading to Pods 3.1.x _on my non-critical test site_, I get this error:

![image](https://github.com/pods-framework/pods/assets/17141205/ed94546a-02f6-41b6-9ce8-882c2c4d4191)

I'm kind of sure that Pods 3.1.x, worked fine with WordPress 6.5 beta 2. I just updated to 6.5 beta 3.

So this might very much just be a WP beta issue, but I only experience the crash when activating Pods. Take from it what you can ;)

### Version

3.1.3

### Possible Workaround

I temporarily disabled Pods

### Site Health Information

```text
WP 6.5 beta 3
PHP 8.3.x

More info on request.
```

### Pods Package

```json
On request
```

**Comment by sc0ttkclark** [comment]
I saw this during my testing, sorry for the late response but this is resolved in Pods 3.1.5 and will be released tomorrow for WP 6.5 release day.
