### ISSUE TITLE
Block API: Label for color

### ISSUE THREAD

**Issue by pdclark** [pods-framework/pods#7305]
### Problem to Solve

When using the Pods Block API, `color` and `file` field types do not render `label` argument.

### Proposed Solution

Render labels.

### Possible Workaround

Add an additional field that is just a label? I did not note any such thing in `RenderedField.js`

### Examples Elsewhere

Yes, usually fields have names. The other field types show labels.

### Screenshots / Screencast

https://wordpress.org/support/topic/block-api-some-fields-do-not-show-labels/

**Comment by sc0ttkclark** [comment]
We'll want to follow up later for the file field and others that don't utilize a label.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/7306
