### ISSUE TITLE
Cant create field type of html

### ISSUE THREAD

**Issue by wireinet** [pods-framework/pods#7311]
### Description

Create field type = html and cant find it in backend simple no field

### Version

3.1

### Testing Instructions

1) create field type html
2) save
3) go to item - no field

### Screenshots / Screencast

pods fields:
![изображение](https://github.com/pods-framework/pods/assets/23517333/78cb059a-5b8d-4614-9885-5e5b6d42b68e)

Edit post:
![изображение](https://github.com/pods-framework/pods/assets/23517333/1921e4be-b385-4821-90fd-4ab6be4641b8)

**Comment by heybran** [comment]
Yes, somehow html field was not rendered.
<img width="1149" alt="image" src="https://github.com/pods-framework/pods/assets/75633537/8234e913-6745-4225-b4cc-9cb6465e9796">

**Comment by Pezzab** [comment]
Hi just to confirm I have come across the same issue. I've tried adding an HTML field in multiple contexts but it doesn't show up in the edit screen.

**Comment by sc0ttkclark** [comment]
@wireinet @Pezzab @heybran Can anyone provide a Pods package to better debug this? I cannot yet reproduce the problem on my testing site on Pods 3.2.4.

But I did run a script rebuild so it may have fixed itself at that point.

You can also test using that version too, but providing the package should also be done in the meantime.

PR: https://github.com/pods-framework/pods/pull/7324
ZIP: https://github.com/pods-framework/pods/archive/refs/heads/release/3.2.4.zip

**Comment by heybran** [comment]
@sc0ttkclark, sorry missed the notification on this one, I will see if I can give it another test next week.

**Comment by heybran** [comment]
@sc0ttkclark  Just downloaded the latest version of Pods (3.2.7) and it seems to me the HTML field is still not showing up.

[pods-package-2024-09-07.json](https://github.com/user-attachments/files/16914775/pods-package-2024-09-07.json)

```
{
    "@meta": {
        "version": "3.2.7",
        "build": 1725690574
    },
    "settings": {
        "types_only": "0",
        "watch_changed_fields": "0",
        "metadata_integration": "0",
        "metadata_override_get": "0",
        "register_meta_integration": "0",
        "media_modal_fields": "0",
        "session_auto_start": "0",
        "dynamic_features_allow": "1",
        "dynamic_features_enabled": [
            "display",
            "form"
        ],
        "show_access_restricted_messages": "0",
        "show_access_admin_notices": "1",
        "dynamic_features_allow_sql_clauses": "0",
        "display_callbacks": "customized",
        "display_callbacks_allowed": "esc_attr,esc_html",
        "wisdom_opt_out": "1",
        "active_components": [
            "migrate-packages",
            "templates"
        ]
    },
    "pods": [
        {
            "name": "page",
            "id": 234,
            "label": "\u9875\u9762",
            "description": "",
            "type": "post_type",
            "storage": "meta",
            "object": "page",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "e69bb4e5a49ae5ad97e6aeb5",
                    "id": 235,
                    "label": "\u66f4\u591a\u5b57\u6bb5",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "test_html_field",
                            "id": 236,
                            "label": "Test HTML Field",
                            "description": "",
                            "weight": 0,
                            "type": "html",
                            "html_no_label": "1",
                            "repeatable": "0",
                            "repeatable_format": "default",
                            "default_evaluate_tags": "0",
                            "default_empty_fields": "0",
                            "roles_allowed": "administrator",
                            "revisions_revision_field": "0",
                            "enable_conditional_logic": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "required": "0",
                            "html_trim": "1",
                            "html_trim_lines": "0",
                            "html_trim_p_brs": "0",
                            "html_trim_extra_lines": "0",
                            "html_oembed": "0",
                            "html_wptexturize": "1",
                            "html_convert_chars": "1",
                            "html_wpautop": "1",
                            "html_allow_shortcode": "0",
                            "logged_in_only": "0",
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by sc0ttkclark** [comment]
@heybran you have to put in HTML content for that field to work. It's not a code editor field, it just lets you output HTML on in the fields area.

**Comment by heybran** [comment]
Thanks for reminding that, in that case, it's working for me.

<img width="968" alt="image" src="https://github.com/user-attachments/assets/3b3b89ae-af39-45cb-a930-cf65b53c0ced">

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/ffea09fe-e1b4-4164-8484-483d226b0467">
