### ISSUE TITLE
All the pods with the posts has disappered on my website after a malware clean!

### ISSUE THREAD

**Issue by alekswellknown** [pods-framework/pods#7335]
### Description

All the pods with the posts has disappered on my website after a malware clean! know i am not able to restore them. There are no pods and no posts. what should i do?

### Version

2.8

### Screenshots / Screencast

![Screenshot 2024-08-16 003226](https://github.com/user-attachments/assets/657d36cd-710e-4a83-b2aa-ec19212bd997)

**Comment by sclark3-godaddy** [comment]
* How did you perform your malware clean on your site?
* Do you see all of your Pods configurations including settings and fields there, just no content?

**Comment by sc0ttkclark** [comment]
* How did you perform your malware clean on your site?
* Do you see all of your Pods configurations including settings and fields there, just no content?

**Comment by sc0ttkclark** [comment]
Have not heard back here, going to close for now.
