### ISSUE TITLE
Opening CPT post in background on iPad causes one-column layout

### ISSUE THREAD

**Issue by nisbet-hubbard** [pods-framework/pods#7338]
### Description

Opening a CPT post in background for editing on iPad causes one-column layout instead of the usual masonry layout of the editor. Occurs in both Safari and Chrome.

### Version

3.2.6

### Testing Instructions

1. Hold ‘Edit’ on a CPT post.
2. Tap ‘Open in Background’.
3. Wait until page finishes loading in background. If you tap on the new tab immediately after step 2, you’ll see the correct masonry layout.
4. Tap on the new tab in background.
5. You’ll see the ‘Publish’ box stretching across the whole screen, instead of its default position in the top right corner.

### Screenshots / Screencast

![IMG_2031](https://github.com/user-attachments/assets/efcd127f-3047-45b6-938e-f79f1774c055)

### Possible Workaround

1. You see the ‘Publish’ box stretching across the whole screen, instead of its default position in the top right corner.
2. Refresh the page.
3. Editor is back to the normal masonry layout, with the ‘Publish’ box in the top right corner.

### Site Health Information

```text
This doesn’t look like an incompatibility problem. I can provide this information on request, though.
```

**Comment by sc0ttkclark** [comment]
I'm not sure this is a Pods issue. It seems like a AO core problem.

But the worst part of this is that you're seeing this problem with Classic Editor and it's doubtful any solution will be pushed forward for that by the WP core team since it's no longer a priority.

Sorry, wish we could fix this one on our side for you.
