### ISSUE TITLE
Upload file from Dropbox

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#761]
https://blog.dropbox.com/2012/11/meet-the-dropbox-chooser-a-new-way-to-add-stuff-from-dropbox/

**Comment by pglewis** [comment]
https://www.dropbox.com/developers/chooser

**Comment by Ramoonus** [comment]
plugin or pods extension?

**Comment by jimtrue** [comment]
I'd say external to Pods or we're going to have to do one for Google Drive, Box, One and every single other cloud system that's hot at the moment. 

If we could leverage with iThemes, they have something built into their Backup Buddy for integrating with DropBox, Google Drive and Amazon S3. All of those systems require separate authentication for permanent connection to those cloud systems. 

I think it matters if you're saving the file permanently to those Cloud locations outside of the Media Library.
