### ISSUE TITLE
fetch() won't return first result

### ISSUE THREAD

**Issue by ecreatrix** [pods-framework/pods#763]
I have a pod and for some reason running while ($pods->fetch()) won't return the first result (and will return nothing if there is only one result based on total_found()). 

I'm not sure what the problem is or what exact information you need.

The pod is based a custom post type (built using register_post_type) that has been extended with pods. 
Object type: post type (extended)
Storage type: table

**Comment by munzirstudio** [comment]
Hi, I'm using Pods 2.6.1, I'm having the same problem, $pods->fetch() wont return first row, $pods->total() return 6 item but only 5 items displayed.
`  <?php 
    // We have a "books" Pod with "category" and "the_author"  
    // as single-select relationship fields, related to  
    // "categories" and "authors" Pods 
    $selected = pods_url_variable(-1);
    $params = array( 
        'where'   =>  'bahagian.slug LIKE "'.$selected.'"', 
        'orderby' => 'menu_order ASC',
        'limit'   => 100  // Return all rows,
    ); 
    // Create and find in one shot 
    $pods = pods( 'direktori', $params ); 
    
    ?>
    <table>
      <tbody>
    <?php

    if ( 0 < $pods->total() ) { 
        while ( $pods->fetch() ) {
          
        // Set 'id' so it thinks it's a single item
        // and won't fetch() loop in template()
        $pods->id = $pods->ID;
        $i = 1;
    ?>

          <tr>
            <td><?php echo $pods->total() ?></td>
            <td><?php echo $pods->display( 'name' ); ?></td>
            <td><?php echo $pods->display( 'direktori_jawatan' ); ?></td>
            <td><?php echo $pods->display( 'direktori_samb' ); ?></td>
            <td><?php echo $pods->display( 'direktori_emel' ); ?></td>
          </tr>
          <?php 
        } // end of loop 
    } // end of found
    ?>`
