### ISSUE TITLE
Field Groups / Metabox Manager

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#799]
Context: Metaboxes are the boxes you can drag around on the Post Editor screen. They are seen in other areas of WordPress, and for objects that don't yet have that treatment, Pods will give them text headings (Users, Taxonomies).

Matt came up with this as an idea on what we can do for managing meta boxes and forms (sort of a merge of the two, but maybe the workflow can be improved.

![Wireframe](http://i.imgur.com/GPfc0.png)

Putting this here for internal review by @pods-framework/contributors

**Comment by sc0ttkclark** [comment]
Also requires PodsObject()

**Comment by DOBss** [comment]
+1

**Comment by sc0ttkclark** [comment]
Closing this as complete now that we just hit feature complete. The only caveat is that we can't support more field types and that will get covered by the DFV React work.
