### ISSUE TITLE
Pods 2.0.5.1 - Upgrade from 2.0.4.1 - Fatal error: Class 'PodsForm' not found in /pods/classes/PodsAPI.php on line 3539

### ISSUE THREAD

**Issue by iamrobreynolds** [pods-framework/pods#825]
Wordpress 3.4.2 Multisite
Pods 2.0.4.1 -> Pods 2.0.5.1

After upgrading Pods, both frontend and backend of WP would display Fatal Error and nothing else on several sites that were using Pods.

Fatal error: Class 'PodsForm' not found in /home/dpn/public_html/wp-content/plugins/pods/classes/PodsAPI.php on line 3539

**Comment by JoryHogeveen** [comment]
I have got the same crash again with the 2.5.1.2 update.

Changed this:
```php
if ( false !== pods_compatibility_check() ) {
	$pods_form = pods_form();

	if ( ! is_network_admin() ) {
		$pods_init = pods_init();
	}

}
```

into this:

```php
if ( false !== pods_compatibility_check() ) {
	$pods_form = pods_form();

	$pods_init = pods_init();
		        /*if ( ! is_network_admin() ) {
		        }*/
}
```

And it was resolved again. Does anyone know why this happens?

**Comment by Shelob9** [comment]
@JoryHogeveen I created a new issue for this #2803
