### ISSUE TITLE
Options when deleting a meta based Pod

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#835]
When you click delete pod, a popup should come up that asks you what you want to do:
- Delete the Pod, 
- Delete the Pod and all data, 
- or just Reset the Content for the Pod

**Comment by jimtrue** [comment]
Is this an actionable option? You can 'Reset Pods settings and data' or 'Deactivate Pods and Delete Pods data', neither of which remove your posts or postmeta. There is a Delete Pod but I don't believe it will delete the posts or the post meta (just the pod configuration).

So yes, we still need a Delete the Pod and All Data (Delete Post Meta, Delete Posts, Delete Pods configuration)
and a Reset the Content for the Pod (Delete Post Meta, Delete Posts, don't delete Pods configuration). It's assumed these would also flush any connections in wp_podsrel?
