### ISSUE TITLE
orderby on plain number field orders incorrectly

### ISSUE THREAD

**Issue by beat-juggler** [pods-framework/pods#910]
I have a plain number field (decimals 0, max. length 4) set up to order my pods (products) but if I use 'orderby' => 'product_weight DESC' the order returned is incorrect. The sequence returned is shown below:

980, 970, 90, 890, 880, ... 810, 800, 80, 790, ... 120, 110, 1000, 100, -130, -120, -110

How can I order the pods in a user chosen sequence? or order correctly by number?

**Comment by tomherold** [comment]
Just found out about this after 3 hours of testing as I switched from advanced custom type pod to custom post type.

**Comment by tomherold** [comment]
As far as I understand this is a WordPress problem, otherwise I think that needs to be improved within Pods.
