### ISSUE TITLE
Add user meta fields to add user/registration form. Set user meta upon user creation.

### ISSUE THREAD

**Issue by gunn4r** [pods-framework/pods#936]
Looking for a straight forward way I could add custom user meta fields to the add user and/or registration form,  so that I can set the meta data upon user creation instead of having to edit the user after.

**Comment by sc0ttkclark** [comment]
I think we can revisit this and make it available in some way in Pods 3.1

**Comment by sc0ttkclark** [comment]
Open to other contributors stepping in to have it done sooner, but for now there are other high priority features in my mind that are in 2.7, 2.8, 2.9, and 3.0

**Comment by JoryHogeveen** [comment]
I guess this is for the backend forms right? (wp-admin/***).
I'd say front end forms already support this when configures correctly.
